### ISSUE TITLE
MA doesn't start with the newest HA beta

### ISSUE THREAD

**Issue by gieljnssns** [music-assistant/hass-music-assistant#1009]
### What version of Music Assistant has the issue?

latest

### The problem

MA doesn't start with the newest HA beta

### How to reproduce

Update to HA 2022.12.b0

### Relevant log output
```
Logger: homeassistant.util.package
Source: util/package.py:98
First occurred: 04:07:08 (3 occurrences)
Last logged: 04:07:22

Unable to install package music-assistant==1.8.7: ERROR: Cannot install music-assistant==1.8.7 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip available: 22.3 -> 22.3.1 [notice] To update, run: pip install --upgrade pip
```
```
Logger: homeassistant.setup
Source: setup.py:202
First occurred: 04:07:37 (1 occurrences)
Last logged: 04:07:37

Setup failed for custom integration mass: Requirements for mass not found: ['music-assistant==1.8.7'].
```

### What version of Home Assistant Core are your running

2022.12.b0

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by fredamn76** [comment]
Issue still present in 2022.12.b1

**Comment by OzGav** [comment]
Marcel is aware and will have a fix before the 2022.12.0 comes out.

**Comment by gieljnssns** [comment]
when updating to MA-core v1.8.8 MA is back.

**Comment by marcelveldt** [comment]
> ~when updating to MA-core v1.8.8 MA is back.~
> MA is starting again, but there are some other errors

yes, it needs more work. I'm sure I can fix it before 2022.12 drops, just a little patience please.
This reminds me btw to setup an automated test that tests MA against HA dev (nightly) to detect breaking changes early....

**Comment by WebfinityDesign** [comment]
Is doesn't start in the final 2022.12. Is there a workaround until the fix is there?

**Comment by johntdyer** [comment]
Correct, failing w/ the GA release

**Comment by gieljnssns** [comment]
You can change "music-assistant==1.8.7" to "music-assistant==1.8.8" in the manifest.json file. 
MA will start but it isn't fully functional.

**Comment by OzGav** [comment]
Yes the MA patch is not yet available. There will be a short MA outage as a result…

**Comment by nickh66** [comment]
2022.12 version just installed but still mass will not load.
Seeing error "ModuleNotFoundError: No module named 'music_assistant'" in the logs.
Also, can't delete the integration either.

**Comment by OzGav** [comment]
Thanks, please be patient while this gets investigated

**Comment by stobiaskoch** [comment]
Hi, same here with 2022.12
After reinstalling the integration, mass is working fine again, thanks for the good work!

**Comment by gieljnssns** [comment]
@marcelveldt 
Thanks for your hard work.
