### ISSUE TITLE
HA 2022.12 dependency conflict

### ISSUE THREAD

**Issue by drthanwho** [music-assistant/hass-music-assistant#1011]
### What version of Music Assistant has the issue?

2022.11.0

### The problem

There is a pip dependency conflict with the upcoming HA Core 2022.12.0 version. 

### How to reproduce

Update to Core 2022.12.0 

### Relevant log output
```
2022-12-01 15:23:38.114 ERROR (SyncWorker_5) [homeassistant.util.package] Unable to install package music-assistant==1.8.7: ERROR: Cannot install music-assistant==1.8.7 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

[notice] A new release of pip available: 22.3 -> 22.3.1
[notice] To update, run: pip install --upgrade pip
```

### What version of Home Assistant Core are your running

2022.12.0b0

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
Please use existing thread https://github.com/music-assistant/hass-music-assistant/issues/1009
