### ISSUE TITLE
error in Random Mode for Youtube Music 

### ISSUE THREAD

**Issue by hermann1514** [music-assistant/hass-music-assistant#1012]
### What version of Music Assistant has the issue?

2022.11

### The problem

If I have selected the random mode for a player, one song is played at random from all the songs in the library. Not just from the current album or a playlist, but from all albums in the library. I noticed this behavior with YoutTubeMusic.

### How to reproduce

Enable Random Mode for a Play and play an ALbum or a playlist. Now all Music from the Library was played random.

### What version of Home Assistant Core are your running

2022.11.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
@MarvinSchenkel is this an issue with the provider or do you think something in MA?

**Comment by hermann1514** [comment]
I think it's problem with the Provider YouTubeMusic.
I create an account for spotify and here the random Mode works fine.

**Comment by Symbiot78** [comment]
When mass is running on .12 I can test this. 
In yt music app the problem is not something I can reproduce. 

Can it be that random option in mass starts/means/interprets as ‘radio’ in yt music?

**Comment by OzGav** [comment]
Please advise if this is still an issue with MA V2.0.0b7 (or later depending on when you test)

**Comment by OzGav** [comment]
No followup. Closing.
