### ISSUE TITLE
Music Assistant and sonos don't work

### ISSUE THREAD

**Issue by barto95100** [music-assistant/hass-music-assistant#1015]
### What version of Music Assistant has the issue?

 v2022.11.0

### The problem

When I select a playlist spotify and select device sonos nothing to do 

### How to reproduce

select device sonos on bottom right > select playlist -> chose on with double click 

### Relevant log output

Logger: music_assistant.players.stream
Source: runner.py:119
First occurred: 11:20:51 (7 occurrences)
Last logged: 11:25:39

Abort: client(s) did not connect within 10 seconds.

### Additional information

IfI test directly with spotify clientto sens music on sonos is work perfectlyl 

### What version of Home Assistant Core are your running

2022.11.5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

ODROID

**Comment by OzGav** [comment]
Have you reviewed the troubleshooting FAQ? Particularly the first point of ensuring everything is on the same local network?

**Comment by barto95100** [comment]
My home assustant blue :  192.168.1.20
and sonos : 192.168.1.215

**Comment by OzGav** [comment]
Try sending a tts to the normal Sonos player and then try sending the same message to the MA version of the player

**Comment by barto95100** [comment]
Hi,

I test the TTS with service to media_player.mass_xxxxxxx: don't work
<img width="560" alt="2022-12-09_11-10-05" src="https://user-images.githubusercontent.com/17863254/206678193-984ae2b6-a03f-4f43-bea6-c7b603cd9e61.png">
<img width="1252" alt="2022-12-09_11-10-40" src="https://user-images.githubusercontent.com/17863254/206678248-2c85605d-84fd-4634-894c-b52c5d8b4ef3.png">

If I test to send directly to sonos media_player.sonos_xxxxxx: work
<img width="579" alt="2022-12-09_11-12-33" src="https://user-images.githubusercontent.com/17863254/206678585-045d0845-4711-44c2-9a66-34acc2c022a9.png">

**Comment by OzGav** [comment]
That suggests that there is an incompatibility with that speaker. It doesn’t support the necessary capabilities to work with MA

**Comment by barto95100** [comment]
Ok but is Sonos play 1 and in list it's say work with SONOS

**Comment by OzGav** [comment]
Yes true but I am not sure if all Sonos players are compatible. You can post the ATTRIBUTES for the player and we can see if something is missing. Not that you can do anything about that but at least you will know why.

**Comment by OzGav** [comment]
Just go to the developer tools>>STATES and then type in the entity name for the player. All the attributes will be shown and you can copy and paste them here. Please format them with the <> button

**Comment by barto95100** [comment]
This is the media_payer.sonos_bureau:

```
group_members:
  - media_player.sonos_bureau
volume_level: 0.48
is_volume_muted: false
media_content_id: >-
  x-sonos-vli:RINCON_7828CAB0153201400:2,spotify:36eb54c6b5a2b8a3c5547b2aee68f369
media_content_type: music
source: Spotify Connect
shuffle: false
repeat: 'off'
queue_position: 1
queue_size: 1
icon: phu:sonos-one
friendly_name: Bureau
supported_features: 981567

```

**Comment by OzGav** [comment]
I’m no expert but it seems like your player doesn’t support SERVICE_REPEAT_SET, and SERVICE_SHUFFLE_SET which MA does use on the queue. However, again can you confirm you have read and tried the troubleshooting steps I listed above, specifically, —- Second situation: The player is listed, but doesn't work. In that case (after you checked if playback works in the standard media browser), there is an expert setting that can probably fix the playback:
First go to settings-integrations-music Assistant. There open the MA devices. Then open the player device that doesn't work and you can find an entity ‘Contenttype to stream to the player’ . Enable that if it’s not enabled yet and check if the media type is mp3 or FLAC. Change that option and try if that solved the playback issue

**Comment by OzGav** [comment]
I will close this soon as no further response received.

**Comment by Greylinux** [comment]
sorry to restart this issue , but I believe I have the same issue , I have 3 sonos 1's all bought at varying times , but none work , Ive enabled ‘Contenttype to stream to the player’ when I configured music assistant , does this mean I cannot use music assistant ?

**Comment by splitsec2** [comment]
I am running on Hassos in a VM and I am having this issue.  How do I check that port 8096 is open?
