### ISSUE TITLE
Unable to install the integration

### ISSUE THREAD

**Issue by polmdm** [music-assistant/hass-music-assistant#1022]
### What version of Music Assistant has the issue?

2022.12.2

### The problem

I have correctly installed the integration from HACS Panel. I have installed the latest version to date 2022.11.0 of Music Assistant. I reboot the system and add the integration to the configuration page. At that point the integration starts loading for more than 5 minutes until I get this error message:

"Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble"

I have also tried an older version of Music Assistant but nothing chages.

### How to reproduce

1. Install the integration from HACS panel
2. reboot hassio
3. add the integration

### What version of Home Assistant Core are your running

2022.12.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by jscherry** [comment]
Same issue as above. I'm using the newest version compatible with HA  2022.12? It installed but just shows Music Assistant with a question mark after and never goes into configuring the players etc?

**Comment by OzGav** [comment]
Thanks. Marcel will have to look again at what the issue is. Please supply any errors in the logs you can see

**Comment by UPEngineer** [comment]
MA showed a HACS update a while ago for Home Assistant 2022-12. Update MA and now get this in the logs:

Setup failed for custom integration mass: Requirements for mass not found: ['music-assistant==1.8.7.1'

MA still will not load.

**Comment by justinbyoung** [comment]
This is the error I receive with 2022.12.0 on HA 2022.12.0

Unable to install package music-assistant==1.8.7.1: ERROR: Could not find a version that satisfies the requirement databases>=0.6.3 (from music-assistant) (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.1.10, 0.1.11, 0.1.12, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5, 0.2.6, 0.3.0, 0.3.1, 0.3.2, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.5.5, 0.6.0, 0.6.1, 0.6.2) ERROR: No matching distribution found for databases>=0.6.3 [notice] A new release of pip available: 22.3 -> 22.3.1 [notice] To update, run: pip install --upgrade pip

**Comment by OzGav** [comment]
Ok so that looks like you might be running a non standard install. Is that correct?

**Comment by justinbyoung** [comment]
Me, I am running HA OS on a VM, but pretty standard. Installed Music Assistant through HACS.

**Comment by kic68** [comment]
After upgrading to Home Assistant 2022.12 I am getting exactly the same error - HA OS on a VM, Music Assistant installed through HACS:

```
Logger: homeassistant.setup
Source: setup.py:202 
First occurred: 8:28:23 AM (1 occurrences) 
Last logged: 8:28:23 AM

Setup failed for custom integration mass: Requirements for mass not found: ['music-assistant==1.8.7'].
```

**Comment by marcelveldt** [comment]
For Home Assistant 2022.12 we have just released 2022.12.1 version of Music Assistant. That will fix this issue.

**Comment by kic68** [comment]
Cool, thanks a lot. I cannot wait to install it, currently I am getting only a spinning wheel when clicking on the upgrade button (I can see the new version), already reloaded HA as well. Just too fresh at the moment :)

**Comment by marcelveldt** [comment]
Just retry it at a later time. The package asset was added later so I think you were just too fast trying to upgrade.

**Comment by woldhek** [comment]
On 2023.1 HA (Pi via HAOS)
I get this alert when i try to integrate music assistant.
```Fout
Config-flow kon niet geladen worden: Unknown error
```

Is it possibly related to this bug from last year?

**Comment by ferrettinico** [comment]
I'm also having issues installing this, it just stays on "Please wait, starting configuration wizard for Music Assistant"

**Comment by OzGav** [comment]
Any errors in the logs?

**Comment by ferrettinico** [comment]
On "Settings" => "System" => "Logs" it says
"There are no new issues!"

not sure where else to look, I'm new to HA
