### ISSUE TITLE
<Integration music-assistant/hass-music-assistant> No assets found for release 'tags/v2022.12.1'

### ISSUE THREAD

**Issue by hermanops** [music-assistant/hass-music-assistant#1023]
### What version of Music Assistant has the issue?

2022.12.1

### The problem

Can't install 2022.12.1

<Integration music-assistant/hass-music-assistant> No assets found for release 'tags/v2022.12.1'

### How to reproduce

try to install

### Relevant log output

<Integration music-assistant/hass-music-assistant> No assets found for release 'tags/v2022.12.1'

### What version of Home Assistant Core are your running

2022.12.0

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

ODROID

**Comment by Liionboy** [comment]
![image](https://user-images.githubusercontent.com/87735636/206652897-d971b268-2fea-4f13-961e-36b6c81d1f66.png)

**Comment by marcelveldt** [comment]
You was too soon with installing, the asset was still uploading. Please try again
