### ISSUE TITLE
Glitched sound while playing through Denon Heos Music

### ISSUE THREAD

**Issue by javireyesnespral** [music-assistant/hass-music-assistant#1027]
### What version of Music Assistant has the issue?

2022.12.1

### The problem

Sound glitches when I select this player.

### How to reproduce

You only have to start playing a song.

### What version of Home Assistant Core are your running

2022.12.1

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
Please read the FAQs in the discussion area

**Comment by javireyesnespral** [comment]
> Please read the FAQs in the discussion area

Thanks, @OzGav . It's working like a charm now.
Regards.
