### ISSUE TITLE
Albums from NAS not shown and full log of error messages

### ISSUE THREAD

**Issue by radek-kafka** [music-assistant/hass-music-assistant#1040]
### What version of Music Assistant has the issue?

2022.12.1

### The problem

I do not see any albums in list .. the log is filled with these error messages:
Dec 15 22:24:40 homeassistant e636ad006825[642]: 2022-12-15 22:24:40.016 ERROR (MainThread) [music_assistant.music.file] Error processing /media/vuplususb/mp3/Grateful Dead/71Skulls&Roses-2tr/3Big Railroad Blues.mp3 - no such column: provider_ids
Dec 15 22:24:40 homeassistant e636ad006825[642]: Traceback (most recent call last):
Dec 15 22:24:40 homeassistant e636ad006825[642]:   File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/filesystem/filesystem.py", line 256, in sync_library
Dec 15 22:24:40 homeassistant e636ad006825[642]:     await self.mass.music.tracks.add_db_item(
Dec 15 22:24:40 homeassistant e636ad006825[642]:   File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/media/tracks.py", line 221, in add_db_item
Dec 15 22:24:40 homeassistant e636ad006825[642]:     track_artists = await self._get_track_artists(item)
Dec 15 22:24:40 homeassistant e636ad006825[642]:   File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/media/tracks.py", line 301, in _get_track_artists
Dec 15 22:24:40 homeassistant e636ad006825[642]:     {await self._get_artist_mapping(x, overwrite) for x in track_artists}
Dec 15 22:24:40 homeassistant e636ad006825[642]:   File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/media/tracks.py", line 301, in <setcomp>
Dec 15 22:24:40 homeassistant e636ad006825[642]:     {await self._get_artist_mapping(x, overwrite) for x in track_artists}
Dec 15 22:24:40 homeassistant e636ad006825[642]:   File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/media/tracks.py", line 390, in _get_artist_mapping
Dec 15 22:24:40 homeassistant e636ad006825[642]:     if db_artist := await self.mass.music.artists.get_db_item_by_prov_id(
Dec 15 22:24:40 homeassistant e636ad006825[642]:   File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/media/base.py", line 349, in get_db_item_by_prov_id
Dec 15 22:24:40 homeassistant e636ad006825[642]:     for item in await self.get_db_items_by_prov_id(
Dec 15 22:24:40 homeassistant e636ad006825[642]:   File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/media/base.py", line 385, in get_db_items_by_prov_id
Dec 15 22:24:40 homeassistant e636ad006825[642]:     return await self.get_db_items_by_query(query, limit=limit, offset=offset)
Dec 15 22:24:40 homeassistant e636ad006825[642]:   File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/media/base.py", line 325, in get_db_items_by_query
Dec 15 22:24:40 homeassistant e636ad006825[642]:     for db_row in await self.mass.database.get_rows_from_query(
Dec 15 22:24:40 homeassistant e636ad006825[642]:   File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/database.py", line 90, in get_rows_from_query
Dec 15 22:24:40 homeassistant e636ad006825[642]:     return await self._db.fetch_all(query, params)
Dec 15 22:24:40 homeassistant e636ad006825[642]:   File "/usr/local/lib/python3.10/site-packages/databases/core.py", line 142, in fetch_all
Dec 15 22:24:40 homeassistant e636ad006825[642]:     return await connection.fetch_all(query, values)
Dec 15 22:24:40 homeassistant e636ad006825[642]:   File "/usr/local/lib/python3.10/site-packages/databases/core.py", line 250, in fetch_all
Dec 15 22:24:40 homeassistant e636ad006825[642]:     return await self._connection.fetch_all(built_query)
Dec 15 22:24:40 homeassistant e636ad006825[642]:   File "/usr/local/lib/python3.10/site-packages/databases/backends/sqlite.py", line 98, in fetch_all
Dec 15 22:24:40 homeassistant e636ad006825[642]:     async with self._connection.execute(query_str, args) as cursor:
Dec 15 22:24:40 homeassistant e636ad006825[642]:   File "/usr/local/lib/python3.10/site-packages/aiosqlite/context.py", line 41, in __aenter__
Dec 15 22:24:40 homeassistant e636ad006825[642]:     self._obj = await self._coro
Dec 15 22:24:40 homeassistant e636ad006825[642]:   File "/usr/local/lib/python3.10/site-packages/aiosqlite/core.py", line 184, in execute
Dec 15 22:24:40 homeassistant e636ad006825[642]:     cursor = await self._execute(self._conn.execute, sql, parameters)
Dec 15 22:24:40 homeassistant e636ad006825[642]:   File "/usr/local/lib/python3.10/site-packages/aiosqlite/core.py", line 129, in _execute
Dec 15 22:24:40 homeassistant e636ad006825[642]:     return await future
Dec 15 22:24:40 homeassistant e636ad006825[642]:   File "/usr/local/lib/python3.10/site-packages/aiosqlite/core.py", line 102, in run
Dec 15 22:24:40 homeassistant e636ad006825[642]:     result = function()
Dec 15 22:24:40 homeassistant e636ad006825[642]: sqlite3.OperationalError: no such column: provider_ids

### How to reproduce

Run HA MA and try to get content of data library 

### Relevant log output

Dec 15 22:24:40 homeassistant e636ad006825[642]: 2022-12-15 22:24:40.016 ERROR (MainThread) [music_assistant.music.file] Error processing /media/vuplususb/mp3/Grateful Dead/71Skulls&Roses-2tr/3Big Railroad Blues.mp3 - no such column: provider_ids
Dec 15 22:24:40 homeassistant e636ad006825[642]: Traceback (most recent call last):
Dec 15 22:24:40 homeassistant e636ad006825[642]:   File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/filesystem/filesystem.py", line 256, in sync_library
Dec 15 22:24:40 homeassistant e636ad006825[642]:     await self.mass.music.tracks.add_db_item(
Dec 15 22:24:40 homeassistant e636ad006825[642]:   File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/media/tracks.py", line 221, in add_db_item
Dec 15 22:24:40 homeassistant e636ad006825[642]:     track_artists = await self._get_track_artists(item)
Dec 15 22:24:40 homeassistant e636ad006825[642]:   File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/media/tracks.py", line 301, in _get_track_artists
Dec 15 22:24:40 homeassistant e636ad006825[642]:     {await self._get_artist_mapping(x, overwrite) for x in track_artists}
Dec 15 22:24:40 homeassistant e636ad006825[642]:   File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/media/tracks.py", line 301, in <setcomp>
Dec 15 22:24:40 homeassistant e636ad006825[642]:     {await self._get_artist_mapping(x, overwrite) for x in track_artists}
Dec 15 22:24:40 homeassistant e636ad006825[642]:   File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/media/tracks.py", line 390, in _get_artist_mapping
Dec 15 22:24:40 homeassistant e636ad006825[642]:     if db_artist := await self.mass.music.artists.get_db_item_by_prov_id(
Dec 15 22:24:40 homeassistant e636ad006825[642]:   File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/media/base.py", line 349, in get_db_item_by_prov_id
Dec 15 22:24:40 homeassistant e636ad006825[642]:     for item in await self.get_db_items_by_prov_id(
Dec 15 22:24:40 homeassistant e636ad006825[642]:   File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/media/base.py", line 385, in get_db_items_by_prov_id
Dec 15 22:24:40 homeassistant e636ad006825[642]:     return await self.get_db_items_by_query(query, limit=limit, offset=offset)
Dec 15 22:24:40 homeassistant e636ad006825[642]:   File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/media/base.py", line 325, in get_db_items_by_query
Dec 15 22:24:40 homeassistant e636ad006825[642]:     for db_row in await self.mass.database.get_rows_from_query(
Dec 15 22:24:40 homeassistant e636ad006825[642]:   File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/database.py", line 90, in get_rows_from_query
Dec 15 22:24:40 homeassistant e636ad006825[642]:     return await self._db.fetch_all(query, params)
Dec 15 22:24:40 homeassistant e636ad006825[642]:   File "/usr/local/lib/python3.10/site-packages/databases/core.py", line 142, in fetch_all
Dec 15 22:24:40 homeassistant e636ad006825[642]:     return await connection.fetch_all(query, values)
Dec 15 22:24:40 homeassistant e636ad006825[642]:   File "/usr/local/lib/python3.10/site-packages/databases/core.py", line 250, in fetch_all
Dec 15 22:24:40 homeassistant e636ad006825[642]:     return await self._connection.fetch_all(built_query)
Dec 15 22:24:40 homeassistant e636ad006825[642]:   File "/usr/local/lib/python3.10/site-packages/databases/backends/sqlite.py", line 98, in fetch_all
Dec 15 22:24:40 homeassistant e636ad006825[642]:     async with self._connection.execute(query_str, args) as cursor:
Dec 15 22:24:40 homeassistant e636ad006825[642]:   File "/usr/local/lib/python3.10/site-packages/aiosqlite/context.py", line 41, in __aenter__
Dec 15 22:24:40 homeassistant e636ad006825[642]:     self._obj = await self._coro
Dec 15 22:24:40 homeassistant e636ad006825[642]:   File "/usr/local/lib/python3.10/site-packages/aiosqlite/core.py", line 184, in execute
Dec 15 22:24:40 homeassistant e636ad006825[642]:     cursor = await self._execute(self._conn.execute, sql, parameters)
Dec 15 22:24:40 homeassistant e636ad006825[642]:   File "/usr/local/lib/python3.10/site-packages/aiosqlite/core.py", line 129, in _execute
Dec 15 22:24:40 homeassistant e636ad006825[642]:     return await future
Dec 15 22:24:40 homeassistant e636ad006825[642]:   File "/usr/local/lib/python3.10/site-packages/aiosqlite/core.py", line 102, in run
Dec 15 22:24:40 homeassistant e636ad006825[642]:     result = function()
Dec 15 22:24:40 homeassistant e636ad006825[642]: sqlite3.OperationalError: no such column: provider_ids

### What version of Home Assistant Core are your running

2022.12.6

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Raspberry Pi

**Comment by radek-kafka** [comment]
Solved by myself... Just deleted .db and restarted the plugin. It is now reading album and showing in menus whatever it foud..

**Comment by erkr** [comment]
👍👍

**Comment by marcelveldt** [comment]
> Solved by myself... Just deleted music_assistant.db and restarted the plugin. It is now reading album and showing in menus whatever it found..

Well you broke it yourself (by manually editing the manifest file) so good thing you fixed it yourself :-)
Great to hear its fixed now.

**Comment by radek-kafka** [comment]
> > Solved by myself... Just deleted music_assistant.db and restarted the plugin. It is now reading album and showing in menus whatever it found..
> 
> Well you broke it yourself (by manually editing the manifest file) so good thing you fixed it yourself :-) Great to hear its fixed now.

Exactly as you said .. Many thanks :) ..
