### ISSUE TITLE
Music Assistant don't play

### ISSUE THREAD

**Issue by roby1o** [music-assistant/hass-music-assistant#1044]
### What version of Music Assistant has the issue?

2022.12.1

### The problem

I was not able to get Music Assistant to work with Google Home mini.

Before installation I was able from the Media tab to get both Radio and TTS to work on 2 devices/entities integrated with Google Cast:

media_player.mini_bedroom
media_player.mini_living

After installing Music Assistant using HACS first and then adding the integration, it cloned the previous 2 media_players entities and created:

media_player.mass_mini_bedroom
media_player.mass_mini_living

I checked option for Tune In and Youtube Music but I can't play anything. When I select a few tracks and click play the player tries for a few seconds but then freezes in an endless loop. 

As I click the various volume or play buttons, I hear clicking sounds coming out of the google home mini, but the track doesn't start. If i try TTS on the new media_player created by MA it does not work. 

If I re-enable visibility of the original 2 players they still work from the Media screen, but I don't see them in the MA screen.

Any ideas?

### How to reproduce

Nothing special, simply installed and tryed to use for the first time.

### Relevant log output

Logger: homeassistant.components.cast.media_player
Source: components/cast/media_player.py:398
Integration: Google Cast ([documentation](https://www.home-assistant.io/integrations/cast), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+cast%22))
First occurred: 00:44:00 (5 occurrences)
Last logged: 01:01:25

Failed to cast media http://172.17.0.2:8095/control/media_player.mini_soggiorno/next.mp3. Please make sure the URL is: Reachable from the cast device and either a publicly resolvable hostname or an IP address
Failed to cast media http://172.17.0.2:8095/announce/media_player.mini_soggiorno.flac. Please make sure the URL is: Reachable from the cast device and either a publicly resolvable hostname or an IP address

### Additional information

Docker container on Synology NAS

### What version of Home Assistant Core are your running

2022.12.1

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Alternative

**Comment by OzGav** [comment]
Have you been through the troubleshooting steps here? https://github.com/music-assistant/hass-music-assistant/discussions/709 At first glance it looks like it is a docker network config issue.
