### ISSUE TITLE
m3u8 playlists not showing up.

### ISSUE THREAD

**Issue by phirestalker** [music-assistant/hass-music-assistant#1047]
### What version of Music Assistant has the issue?

2022.12.1

### The problem

Some of my music has Unicode characters in it. I originally had m3u playlists, but those character are not honored in some software unless in an m3u8 extension playlist file. All of my playlists except one now have this extension.

In the playlists section I am only seeing the one playlist with a regular m3u extension. It is not done scanning yet, but I would expect to see at least one of the other playlists.

### How to reproduce

1. add local music source that has some m3u and m3u8 playlists
2. navigate to music assistant in HA interface
3. go to playlists tab

### What version of Home Assistant Core are your running

2022.12.8

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
You can use the MA addon which is in beta if you wish. Either way if you could just paste in one of the playlists so I can see the format of it.

**Comment by phirestalker** [comment]
```
../Elvis Presley/Blue Christmas/05 Blue Christmas.flac
../Elvis Presley/The Christmas Collection/02 Here Comes Santa Claus.flac
../Burl Ives/Rudolph the Red-Nosed Reindeer/03 We Are Santa's Elves.flac
../Burl Ives/Rudolph the Red-Nosed Reindeer/07 The Most Wonderful Day of the Year.flac
../Burl Ives/Rudolph the Red-Nosed Reindeer/10 Christmas Medley_ The Night Before Christmas Song _ A Merry Merry Christmas _ When Santa Claus Gets Your Letter _ Rockin' Around the Christmas Tree.flac
../Burl Ives/Rudolph the Red-Nosed Reindeer/19 I Heard the Bells on Christmas Day.flac
../Burl Ives/Rudolph the Red-Nosed Reindeer/02 Jingle Jingle Jingle.flac
../Burl Ives/Rudolph the Red-Nosed Reindeer/06 Silver and Gold.flac
../Burl Ives/Rudolph the Red-Nosed Reindeer/08 A Holly Jolly Christmas.flac
../Burl Ives/Rudolph the Red-Nosed Reindeer/04 There's Always Tomorrow.flac
../Burl Ives/Rudolph the Red-Nosed Reindeer/05 We're a Couple of Misfits.flac
../Libera/The Christmas Album/03 Carol of the Bells.flac
../Trans‐Siberian Orchestra/The Christmas Attic/08 Christmas Canon.flac
../Perry Como/Christmas With Perry Como/06 Santa Claus Is Comin' to Town.flac
../Mariah Carey/Merry Christmas/02 All I Want for Christmas Is You.flac
../Mariah Carey/Merry Christmas/04 Christmas (Baby Please Come Home).flac
../Mariah Carey/Merry Christmas/05 Miss You Most (At Christmas Time).flac
../Nat King Cole/Christmas Favorites/01 The Christmas Song.flac
../Nat King Cole/Cole, Christmas, & Kids/01 All I Want for Christmas (Is My Two Front Teeth).flac
../Nat King Cole/Cole, Christmas, & Kids/02 Frosty the Snowman.flac
../Nat King Cole/Cole, Christmas, & Kids/04 The Little Boy That Santa Claus Forgot.flac
../Nat King Cole/Cole, Christmas, & Kids/05 Mrs. Santa Claus.flac
../Nat King Cole/Cole, Christmas, & Kids/07 Take Me Back to Toyland.flac
../Nat King Cole/Cole, Christmas, & Kids/09 The Happiest Christmas Tree.flac
../Elvis Presley/Blue Christmas/04 Silver Bells.flac
../Perry Como/Complete RCA Christmas Collection/02 I'll Be Home For Christmas.flac
../Perry Como/Complete RCA Christmas Collection/12 There Is No Christmas Like A Home Christmas.flac
../Perry Como/Complete RCA Christmas Collection/14 It's Beginning To Look A Lot Like Christmas.flac
../Perry Como/Complete RCA Christmas Collection/26 (There's No Place Like) Home For The Holidays.flac
```

**Comment by OzGav** [comment]
OK that format doesn't appear valid. The format for V2 is as follows. Please report again if you move to V2 and using this format you still have issues:

```
filesystem_smb://track/America/History_ America's Greatest Hits/04 Ventura Highway.m4a
filesystem_smb://track/Phil Collins/But Seriously/12. Find a Way to My Heart - Phil Collins.flac
```

**Comment by phirestalker** [comment]
Are you saying it can't do relative paths?

**Comment by OzGav** [comment]
Relative to what though. MA would need a starting point and since you can have multiple SMB providers I am not sure how easy that would be to manage, But you could just do a global replace of `../` with `filesystem_smb://track/` and it would probably work

**Comment by marcelveldt** [comment]
It should be able to do relative paths wiythin the m3u(8) playlist but not above its parent. Is that supported in other software ?

**so this will work (file in same folder as playlist):**
05 Blue Christmas.flac

**and this (file is in subfolder relative to playlist file):**
Elvis Presley/Blue Christmas/05 Blue Christmas.flac

**and this (file has absolute path):**
/Users/marcel/media/music/b05 Blue Christmas.flac

**and this (full uri):**
spotify://track/12345
or
filesystem_smb://track/blah

**but this is not supported:**
../Mariah Carey/Merry Christmas/02 All I Want for Christmas Is You.flac

espcially not if the file resides outside the folder that is handled by MA.
I could add support for it though but maximum to the level of the folder added to MA (we can not go above)

**Comment by phirestalker** [comment]
Yes, this does work in other software. I generate them with beets, and my Nextcloud music instance in docker uses them with a different folder structure.
The folder hierarchy is
Music
-Artist
--Album
-playlists

So, artist folders and playlists are on the same level with Music as their parent.

**Comment by marcelveldt** [comment]
ah ok that should be possible, I'll see if I can fix that. As long as the playlists folder resides in the music folder it should be fine to use relative paths.

**Comment by OzGav** [comment]
@phirestalker this should be fixed. Please let us know if not.
