### ISSUE TITLE
Playback stuck at transition into the next song

### ISSUE THREAD

**Issue by AndreasBVB** [music-assistant/hass-music-assistant#1049]
### What version of Music Assistant has the issue?

2022.8.4

### The problem

Keeps bouncing back between the end of last and the beginning of the first. Speaker completely silent. Happens with both local MP3 and Spotify.

### How to reproduce

Happens randomly but in about every 2-3hrs.

### Additional information

I am using Squeezelite-ESP32 speakers through the official Squeezebox integration. Previously when using ESPHome I2S speakers similar situations will happen as: MASS plays into the next song silently, but after 30-60 secs it notices and fixes itself by stopping and reversing to the beginning of the new song.

It appears MASS notices the same thing quicker on Squeezelite speakers but the correction strategy somehow fails. I reconstructed my speakers from ESPHome I2S to Squeezelite-ESP32 because of the inferior sound quality and sluggish performance.

Hitting pause and restart doesn't break the loop. Have to hit reverse, then the playlist jumps *forward* by multiple songs. This manual interruption usually works for only one song. After playing on song it falls into another loop at the next transition.

### What version of Home Assistant Core are your running

2022.9.3

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

**Comment by AndreasBVB** [comment]
Example:
https://user-images.githubusercontent.com/89738769/209561729-fbd665e5-4677-4bb0-9e74-9a51dccaf71a.mp4

**Comment by AndreasBVB** [comment]
Additionally, I am using Squeezelite-ESP32 speakers through the official Squeezebox integration. Previously when using ESPHome I2S speakers similar situations will happen as: MASS plays into the next song silently, but after 30-60 secs it notices and fixes itself by stopping and reversing to the beginning of the new song.

It appears MASS notices the same thing quicker on Squeezelite speakers but the correction strategy somehow fails. I reconstructed my speakers from ESPHome I2S to Squeezelite-ESP32 because of the inferior sound quality and sluggish performance.

**Comment by AndreasBVB** [comment]
Now that I added additional speakers, MASS not stuck anymore, but plays silently on and on after transition failures. All speakers are silent so I doubt it's the MASS stream's problem.

**Comment by AndreasBVB** [comment]
The issue has lately become horrendous so I completely deleted the MASS instance and started from scratch. I loaded local files and the Spotify account. As a start I didn't play or even browse from Spotify, but straight into the MP3 playback. It appears everything works with no problem. [The other problem of playing Spotify in place of local MP](https://github.com/music-assistant/hass-music-assistant/issues/1048)3 is also gone. I will report back after more hours of playing.

Maybe the issue is related to the smart decision made on playing alternative sources for better quality?

**Comment by OzGav** [comment]
You should be able to see when MA links tracks from different providers. You can then expect that the highest quality of those linked tracks will be chosen. If MA is linking tracks which are not the same then that needs to be reported. (And equally if it isn’t linking tracks which are the same)

**Comment by AndreasBVB** [comment]
> You should be able to see when MA links tracks from different providers. You can then expect that the highest quality of those linked tracks will be chosen. If MA is linking tracks which are not the same then that needs to be reported. (And equally if it isn’t linking tracks which are the same)

I'm suspecting this linking is doing more harm than merit and provided some evidence. Hopefully will soon have a way to turn it off. The player is a nice concept but as of now is largely unusable.

**Comment by OzGav** [comment]
I believe the linking is fundamental to the way MA works. I can’t quite see how your issue would relate to this feature however.

**Comment by AndreasBVB** [comment]
Can MASS work with MP3 only without Spotify? If so why not keeping them separate instead of doing this linking thing? Because it's doing something at the linking maybe? 

After reload it's has been playing local MP3 for hours without interruption. Previously if fails twice at least every hour. Just trying to provide some hopefully useful materials for developers to to consider.

**Comment by OzGav** [comment]
Yes MA can work with one or more music providers. The point is that MA brings together all your sources so you don’t have to worry about where a track comes from you just see all of the music which is available to you. So as to not have multiple identical tracks from the various providers tracks are linked. However, in order to provide the best audio experience the highest quality source available is selected for playback.

The linking is difficult at times as providers don’t always provide adequate or correct metadata. This is why I suggested raising issues with tracks which are incorrectly linked or not linked when they should be. The Devs will look into this as it is fundamental to the way MA works.

**Comment by AndreasBVB** [comment]
Thank you for looking into this. From a user perspective, being able to manage source from HASS is already a big plus, so that I don't need to switch between LMS and HASS for manage speakers and control playback. On top of that, I'll be happy enough if MASS just respects the playlist/queue, e.g. play from local if the list says local.

**Comment by OzGav** [comment]
You can read here more about how the matching works https://github.com/music-assistant/hass-music-assistant/discussions/543 

You might have the issue that the metadata on your local music isn’t properly filled. This could mean matches occur when they shouldn’t. We recommend tagging all your music with MusicBrainz Picard.

**Comment by OzGav** [comment]
With MA2 in beta I’m not sure what to do with your report. I’m not sure if your initial report is still a problem as you changed to talk about your views on how the linking functionality should work. If I don’t hear back soon that the original issue is still occurring (stuck playback) then I will close this one. Thanks.
