### ISSUE TITLE
Local files not found

### ISSUE THREAD

**Issue by schoeyuk10** [music-assistant/hass-music-assistant#105]
Hi, i have my music, properly tagged in /config/media yet its not found in MA
any ideas what i'm doing wrong ?
Thanks in advance

**Comment by marcelveldt** [comment]
Can you please send me your homeassistant.log ?

**Comment by schoeyuk10** [comment]
There are no errors relating to this in the logs

**Comment by antonyslater** [comment]
Don't think you need the "config", mine is set to "/media/Diskstation" as I have a mounted folder with my music in, seems to be doing something (There are 3 background jobs running) but then I do have a lot of music for it to search/catalogue.

**Comment by schoeyuk10** [comment]
> Don't think you need the "config", mine is set to "/media/Diskstation" as I have a mounted folder with my music in, seems to be doing something (There are 3 background jobs running) but then I do have a lot of music for it to search/catalogue.

Thanks for that.....i tried the way you said, but still no joy
Weird thing is, there is nothing in the logs anywhere

Appreciate your help though

**Comment by schoeyuk10** [comment]
Yeah, he is working hard, and it is appreciated.

I only have 2 files, just to test things out, but they are not showing. I'm pretty sure it's something that i have done that's wrong.....i just don't know what lol

**Comment by marcelveldt** [comment]
> Yeah, he is working hard, and it is appreciated.
> 
> I only have 2 files, just to test things out, but they are not showing. I'm pretty sure it's something that i have done that's wrong.....i just don't know what lol

Later today I will have another good look at the code for the files provider and make improvements.
I think I have now only tested the "happy flow" with music files already containing proper tags and such .
Will let you guys know later today when I have a new version to test.

**Comment by antonyslater** [comment]
> @antonyslater just for my reference how large is your collection ? I have limited the background processing to make sure that it doesn't take too much of system performance. Maybe I have limited it too much.

Erm.... well...... 
![image](https://user-images.githubusercontent.com/38159952/167594237-e3a2ec97-4eb2-4096-9c41-96f4fd36fc9b.png)

Mixture of MP3 and FLAC files (Mainly FLAC).

**Comment by K3str3l** [comment]
@antonyslater I also have a mounted folder from a Synology NAS - have set it up in the integration as /media/music/
The integration seems to sync - I see the icon circling for a couple of hrs., but no media is ever shown :-(
Can you share how you have mounted your folder?
