### ISSUE TITLE
I cant find documentation to change my tune_in login

### ISSUE THREAD

**Issue by nightmare1111** [music-assistant/hass-music-assistant#1051]
### What version of Music Assistant has the issue?

 v2022.12.1

### The problem

I cant find documentation to change my tune_in login

### How to reproduce

when setting up my radio i used my tunein email account

### Relevant log output

This error originated from a custom integration.

Logger: music_assistant.music.tunein
Source: custom_components/mass/__init__.py:190
Integration: Music Assistant (documentation, issues)
First occurred: 5:22:52 PM (2 occurrences)
Last logged: 6:01:25 PM

Emailadress detected instead of username, it is advised to use the tunein username instead of email.

### Additional information

i would like to see maybe a logout link maybe beside the run sync

### What version of Home Assistant Core are your running

2022.12.8

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by erkr** [comment]
In the configuration from MA, the tune in user ID must be used, not the email. This user ID can be found when you log into your tune in account with your browser

**Comment by erkr** [comment]
Got it working? Can we close the issue?

**Comment by nightmare1111** [comment]
so i have deleted the integration and then reinstalled i was able to start with my correct login credentials, i would like to be able to change this without deleting the integration

**Comment by OzGav** [comment]
You can just go to the integration and click on configure to change this. It should reload when you save but ifyou think it hasn’t then click on the overflow menu and select reload.

**Comment by erkr** [comment]
I presume issue is solved
