### ISSUE TITLE
YouTube Music problem with the number of songs in a playlist

### ISSUE THREAD

**Issue by Reprakkucik** [music-assistant/hass-music-assistant#1052]
### What version of Music Assistant has the issue?

2022.12.1

### The problem

I have 622 songs in my YouTube Music playlist, Music Assistant loads 100 songs.

I tried reinstalling and it didn't help.

I don't know what to do anymore.

Thank you for the advice.

Sorry for the translation.

Pictures:
http://imgway.cz/s/90n1
http://imgway.cz/s/4Oe0

### How to reproduce

Reinstallation

Reload login

Waiting 2 days

### What version of Home Assistant Core are your running

2022.12.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Possibly related to this https://github.com/music-assistant/hass-music-assistant/issues/821 Try scrolling down slowly and see if the remaining tracks are grabbed?

**Comment by Reprakkucik** [comment]
It did not help
I'm asking for more advice.

Thank you
