### ISSUE TITLE
TTS not resuming play & Spotify not reflecting actual play

### ISSUE THREAD

**Issue by uriirichard** [music-assistant/hass-music-assistant#1063]
### What version of Music Assistant has the issue?

2022.12.1

### The problem

Hi. First of all im using a Spotify student account wich only allows playing in 1 device.
All my speakers are from Google (2 Home mini + 1 Nest Hub) and Im having 2 strange behaviours:
1- When sending music from Spotify app or web to my Home Mini, or if I ask the speaker to play Spotify, then if I send a TTS message the player stops, says the TTS mesage but does not resume play (also the speaker push the volume up a little before the announcement). But if I send music from HA to the speaker after the TTS it does resume play, working as expected.
Long story short: it only resume play if the music is sent from HA.

2- If I send music from Spotify (app, web or asked by voice) to a speaker I can see in Spotify integration what is playing, BUT if I send music from HA to MA the integration doesn't show what is playing. Also wierd is the fact that I can only play in 1 device (Spotify student account) but sending from HA to MA allows me to play diferent songs in at least 3 diferent devices at once + another diferent song in my phone or web app.

### How to reproduce

TTS:
service: tts.google_say
data:
  message: Hola
  language: es
  entity_id: media_player.mass_bano

Music:
service: media_player.play_media
data:
  media_content_id: https://open.spotify.com/playlist/xxxxxxxxx
  enqueue: replace
  media_content_type: music
target:
  entity_id: media_player.mass_bano

Also tried with "device_id" with the same results.

### Relevant log output

Spotify to speaker:
![01 Cast To Speaker](https://user-images.githubusercontent.com/99214735/211823123-4417b48b-4c12-43f3-a99d-366d118cf40e.jpg)

HA to speaker:
![04 From service call](https://user-images.githubusercontent.com/99214735/211823879-fcc3e418-5a94-4196-b5ca-c462df87f8d1.jpg)

After sending TTS message:
![02 Send TTS](https://user-images.githubusercontent.com/99214735/211825526-87c5ac7f-858a-42f5-bce0-8516ce9c7038.jpg)

### Additional information

I allready uninstalled and reinstalled the integration and reconfigure it several times, even putting a wrong Spotify account wich gives me an error (obviously), and tried both the email account and the user name, allways with the same results.
Thank you in advance, you are doing a great job!

### What version of Home Assistant Core are your running

2023.1.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
There is a rewrite of MA due in the next few weeks. Please revisit this after that is released.

**Comment by OzGav** [comment]
MA V2 beta is available. If you could check if this is still an issue that would be great.

**Comment by OzGav** [comment]
I’m actually going to close this as the TTS is expected behaviour. MA needs to have control of the stream to be able to interrupt it for TTS and then resume the music. 

As for the Spotify integration again this is expected as MA is controlling the stream so that will not be apparent to other software.
