### ISSUE TITLE
YouTube Music listings (e.g. play contents) limited to 100 items

### ISSUE THREAD

**Issue by Reprakkucik** [music-assistant/hass-music-assistant#1072]
### What version of Music Assistant has the issue?

2022.12.1

### The problem

I have 622 songs in my YouTube Music playlist, Music Assistant loads 100 songs.

I tried reinstalling and it didn't help.

I don't know what to do anymore.

Thank you for the advice.

Pictures:
http://imgway.cz/s/90n1
http://imgway.cz/s/4Oe0

### How to reproduce

Reinstallation

Reload login

Waiting 2 days

### What version of Home Assistant Core are your running

2023.1.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by ngalatis** [comment]
I'm facing the same issue.

**Comment by OzGav** [comment]
Possibly related to this https://github.com/music-assistant/hass-music-assistant/issues/821
Please wait until the next MA release in a few weeks and we will see what issues remain

**Comment by marcelveldt** [comment]
Confirmed bug, added it to the backlog to fix it.

**Comment by MarvinSchenkel** [comment]
Should be fixed in https://github.com/music-assistant/server/pull/549

**Comment by OzGav** [comment]
@Reprakkucik please confirm this is fixed and you can close this
