### ISSUE TITLE
The smb fails to be mounted

### ISSUE THREAD

**Issue by jwister** [music-assistant/hass-music-assistant#1075]
### What version of Music Assistant has the issue?

2022.12.1

### The problem

![image](https://user-images.githubusercontent.com/26784039/213129705-eaa4edcb-24c9-440e-9ada-241c0911f83a.png)
Reference example

why coed 255 ？

### How to reproduce

There has been

### What version of Home Assistant Core are your running

2023.1.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
See my comment in your other post.
