### ISSUE TITLE
Error playing some radios

### ISSUE THREAD

**Issue by spady7** [music-assistant/hass-music-assistant#1076]
### What version of Music Assistant has the issue?

2023.1.5

### The problem

Hi, if i try to play, using TUNEIN as service, some radio, i get followin error:
```
Logger: music_assistant.players.stream
Source: runner.py:120
First occurred: 12:31:43 (1 occurrences)
Last logged: 12:31:43

Unexpected number of chunks received for track tunein://radio/s280215: 12/172800 - process_time: 0.35 - player_buffered: 11.59201814058957 
```
Says that Music Player is not supported.
Any idea?

### How to reproduce

.

### Additional information

Logger: music_assistant.players.stream
Source: runner.py:120
First occurred: 12:31:43 (1 occurrences)
Last logged: 12:31:43

Unexpected number of chunks received for track tunein://radio/s280215: 12/172800 - process_time: 0.35 - player_buffered: 11.59201814058957

### What version of Home Assistant Core are your running

2023.1.5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
Let’s hold onto this until the next version of MA comes out in a few weeks and see if it is still an issue then…

**Comment by OzGav** [comment]
Closing. Can reopen if this is still an issue in V2
