### ISSUE TITLE
Chromecast with Google TV devices being excluded from configurable media players

### ISSUE THREAD

**Issue by SteveDinn** [music-assistant/hass-music-assistant#1077]
### What version of Music Assistant has the issue?

2022.12.1

### The problem

When configuring Music Assistant, none of my **Chromecast with Google TV** devices are allowed to be entered. They are cast-enabled devices and as such are [listed in the FAQ](https://github.com/music-assistant/hass-music-assistant#supported-media-players) as being supported, so I believe they should be allowed here.

**Side note:** Chromecast audio groups which contain CCwGTV devices are available and work properly. Chromecast Audio devices and the older, non-Google-TV video Chromecasts work properly as well.

The CCwGTV devices are the ones attached to the best speakers in my house, so they are naturally the ones I would prefer to use for listening to music, despite primarily being used for video.

### How to reproduce

* Have the `Google Cast` integration enabled, and have a **Chromecast with Google TV** device that produces a `media_player` entity for that device.
* See that the media_player entity is not available to configure for Music Assistant.

### Additional information

![image](https://user-images.githubusercontent.com/3911507/213207454-f497cd42-fb5b-4092-b983-ecd9e7808e76.png)

### What version of Home Assistant Core are your running

2023.1.0

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
There are certain capabilities that media players must have to appear in the list of devices. If the players aren’t appearing then they don’t have a required capability. You can check further by following the advice here https://github.com/music-assistant/hass-music-assistant/discussions/622

in the V2 of MA due in the next few weeks Marcel has reduced the number of mandatory capabilities so you might find the players will work then.

**Comment by SteveDinn** [comment]
Taking a glance at the `supported_features` flags on the devices in question, it seems that the CCwGTV devices are lacking the `VOLUME_MUTE`  and `VOLUME_SET` features that are supported by other Chromecast devices. I figure this is because their remotes can typically directly control the volume of whatever device they are attached to via infrared. As a HomeAssistant user, I have other ways to control the volume on those devices :)

I don't think lacking these features should preclude Music Assistant from being able to target these devices.

**Comment by marcelveldt** [comment]
Please read the previous answer you got. A large update of MA is in the making which reduced the number of mandatory features. So please be patient and it will all work out.

**Comment by SteveDinn** [comment]
Agreed. I was just trying to those particular features are ones that could be made "not mandatory".

We're on the same page.  I'm patient :).

**Comment by OzGav** [comment]
https://github.com/music-assistant/home-assistant-addon

Please move to V2 to resolve this. Note that it is still in beta so other issues may arise. However I am closing this as no further investigation will be done as V1 is no longer supported.
