### ISSUE TITLE
Issue with automation

### ISSUE THREAD

**Issue by MRedZac** [music-assistant/hass-music-assistant#1078]
### What version of Music Assistant has the issue?

2022.12.1

### The problem

After last updates, I have several issues, where I don’t understand, why things were working properly before, but now not anylonger at all… This home assistant is really driving me crazy by always rendering things to corrupt or non-working after more or less each update. I am really fed up of this and considering, not updating anymore at all → never change a running system… Here for example, I have this code in an automation:

> alias: Musik beim Kacken YouTube Music
> description: ""
> trigger:
>   - platform: state
>     entity_id:
>       - binary_sensor.tradfri_motion_dusche_occupancy
>     to: "on"
> condition:
>   - condition: time
>     after: "06:00:00"
>     before: "22:00:00"
> action:
>   - service: media_player.volume_set
>     data:
>       volume_level: 0.3
>     target:
>       entity_id: media_player.nestbadezimmer
>   - service: mass.queue_command
>     data:
>       command: play
>       uri: >-
>         https://music.youtube.com/playlist?list=RDCLAK5uy_kbwWhB8U2QURJiXJC3dpkZMStgx845RUo
>       enqueue_mode: play
>       repeat_mode: all
>     target:
>       entity_id: media_player.nestbadezimmer
>   - service: mass.queue_command
>     data:
>       command: play_media
>       uri: >-
>         https://music.youtube.com/playlist?list=RDCLAK5uy_kbwWhB8U2QURJiXJC3dpkZMStgx845RUo
>       enqueue_mode: play
>     target:
>       entity_id: media_player.nestbadezimmer
>     enabled: false
> mode: single
It was working for months now without any issue, but now, the log states following:

> Musik beim Kacken YouTube Music: Error executing script. Unexpected error for call_service at pos 2: URL is relative, but does not start with a /
> 
> 16:09:44 – (FEHLER) Automatisierung - Die Nachricht ist zum ersten Mal am 16:09:44 aufgetreten und erscheint 2 mal
And I really have no idea, what this is talking about… Neither is the youtube URL there relative, nor did I change anything…

Can anybody help to find the problem ? Or do I really have to roll back to a previous version ?

Thanks for your ideas in advance !

### How to reproduce

written above

### Relevant log output

written above

### Additional information

none

### What version of Home Assistant Core are your running

2022.12.9

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by erkr** [comment]
Hi, automation errors can be very unclear indeed. Sometimes the hints are not making sense at all. Can see what something wrong either. 
But let's check the obvious first. The YouTube cookies tend to expire. But then I would expect more YT related errors when you start MA. 
If that is the case, renewal of the cookie it's the first thing to try.
Best Eric

**Comment by MRedZac** [comment]
Well, there is no problem with YouTube in MA... I can play everything there and also no warnings in the log which are YouTube concerned...

**Comment by erkr** [comment]
Not cookie related then. I'm not sure what changed. Looks like a change in the automation indeed.

Best approach is to experiment with 'service: mass.queue_command' under the development tools. 
There one can quickly try some variations. Like adding quotes around the URI.

**Comment by MRedZac** [comment]
Found this in the logs:

```
Logger: music_assistant
Source: /usr/local/lib/python3.10/site-packages/music_assistant/mass.py:232
First occurred: 21. Januar 2023 um 19:36:06 (17 occurrences)
Last logged: 13:35:38

Job [Library sync for provider Youtube Music] failed with error 'gridRenderer'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/music_provider.py", line 402, in sync_library
    async for prov_item in self._get_library_gen(media_type)():
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/ytmusic/ytmusic.py", line 141, in get_library_albums
    albums_obj = await get_library_albums(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/ytmusic/helpers.py", line 117, in get_library_albums
    return await loop.run_in_executor(None, _get_library_albums)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/ytmusic/helpers.py", line 114, in _get_library_albums
    return ytm.get_library_albums(limit=9999)
  File "/usr/local/lib/python3.10/site-packages/ytmusicapi/mixins/library.py", line 131, in get_library_albums
    return parse_library_albums(
  File "/usr/local/lib/python3.10/site-packages/ytmusicapi/parsers/library.py", line 27, in parse_library_albums
    results = get_library_contents(response, GRID)
  File "/usr/local/lib/python3.10/site-packages/ytmusicapi/parsers/library.py", line 113, in get_library_contents
    return nav(results, ITEM_SECTION + renderer)
  File "/usr/local/lib/python3.10/site-packages/ytmusicapi/navigation.py", line 76, in nav
    raise err
  File "/usr/local/lib/python3.10/site-packages/ytmusicapi/navigation.py", line 70, in nav
    root = root[k]
KeyError: 'gridRenderer'
```

**Comment by erkr** [comment]
That is not necessarily related to the automation issue above. See https://github.com/music-assistant/hass-music-assistant/issues/1050. Please try adding quotes to your URL

**Comment by OzGav** [comment]
We will close this issue soon as no further info was provided.

also v2 of MA has been released in beta.

https://github.com/music-assistant/home-assistant-addon
