### ISSUE TITLE
Error with HA 2023.2.0b0

### ISSUE THREAD

**Issue by BeardedTinker** [music-assistant/hass-music-assistant#1080]
### What version of Music Assistant has the issue?

2022.12.1

### The problem

After upgrading to new Home Assistant 2023.2 Beta, MASS is not starting up anymore.

### How to reproduce

Join HA Beta and install latest beta release.

### Relevant log output

2023-01-25 22:13:12.990 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration mass: Requirements for mass not found: ['music-assistant==1.8.7.2'].

### Additional information

Re-downloading MASS doesn't resolve the issue

### What version of Home Assistant Core are your running

2023.2.0b0

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Alternative

**Comment by erkr** [comment]
There is a patch released
