### ISSUE TITLE
Stuttering music from spotify on group google nest devices

### ISSUE THREAD

**Issue by FedericoBS** [music-assistant/hass-music-assistant#1082]
### What version of Music Assistant has the issue?

2022.12.1

### The problem

when I play the music on a group of 2 or more google nest devices the music is stuttering. it is not a band issue, the wifi signal is very high , the internet band unused and the server not loaded at all

### How to reproduce

play a track on a group of 2 or more google nest devices. aftwer a wile the music is stuttering (it is not a syncronization problem)

### Relevant log output

no log output related

### Additional information

none

### What version of Home Assistant Core are your running

2023.1.7

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Windows

**Comment by OzGav** [comment]
Total guess as I don’t recall this issue with Google devices but trying turning off the ICY metadata under SETTINGS>>ADVANCED

**Comment by FedericoBS** [comment]
I disabled the ICY metadata, reduced the speed to 44,1Khz and changed the codec from flac to mp3. Now the stuttering seems gone. thanks for the prompt assistance and congrats for the applications!
