### ISSUE TITLE
Music Assistant broke with HA 2023.2 update

### ISSUE THREAD

**Issue by roby1o** [music-assistant/hass-music-assistant#1083]
### What version of Music Assistant has the issue?

2022.12.1

### The problem

After updating HA to 2023.2 Music Assistant stopped work. 

I usually delete container running HA and remake with new image version, but this time apparently installation of Music Assistant with HACS failed, so mass integration can't load and now i'm stocked because I can't even delete both of them.

If i try to delete mass integration it doens't work and if I try di unsinstall Music Assistant on HACS it says that it can't because integration is using it.

### How to reproduce

I did nothing more then updating HA to 2023.2.0, I did the same thing i did in last 10-15 update process, usually all worked fine.

### Relevant log output

This notify on restart
`Unable to install package music-assistant==1.8.7.2: ERROR: Cannot install music-assistant==1.8.7.2 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip available: 22.3 -> 23.0 [notice] To update, run: pip install --upgrade pip`

This of course when loading the integration
`Setup failed for custom integration mass: Requirements for mass not found: ['music-assistant==1.8.7.2'].`

### Additional information

I think some breaking change with the new version. If I have to guess, maybe python 3.9, I read HA dropped support, but I'm not an expert (just reading breacking changes on HA release note)

### What version of Home Assistant Core are your running

2023.2.0

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Alternative

**Comment by uriirichard** [comment]
![Captura de pantalla 2023-02-01 223229](https://user-images.githubusercontent.com/99214735/216168284-c279f462-e1cf-425b-8916-8f571073494d.jpg)
Hi! Some sort of the same here. Just updated HA to 2023.2.0 and after restart I'm receiving this message.

**Comment by gieljnssns** [comment]
Use the beta version of MA
https://github.com/music-assistant/hass-music-assistant/releases/tag/v2023.2.1

**Comment by roby1o** [comment]
> Use the beta version of MA https://github.com/music-assistant/hass-music-assistant/releases/tag/v2023.2.1

ok, it looks like all working fine with new beta version.

**Comment by MaoriPanda** [comment]
How do you change the repo to the beta?

**Comment by roby1o** [comment]
I simply downloaded mass.zip, unzipped and copied files on custom_component/mass folder.

**Comment by gieljnssns** [comment]
In Hacs tab on music assistant 
Then the dots in the upper corner. 
![21F69082-804D-43DE-8C8F-7166BA51CD81](https://user-images.githubusercontent.com/17234951/216173186-4421e606-f0b9-46ac-af5f-798f638bb54e.jpeg)
And then use beta. 
![36BE7961-6832-4A4A-9E2E-7ACD827832CD](https://user-images.githubusercontent.com/17234951/216173412-4883a9c3-0117-486b-af8f-15105ffe6768.jpeg)

**Comment by marcelveldt** [comment]
I removed the beta mark of the MASS 2023.2.1 release so now it should be available for everyone.

**Comment by juhanjuku** [comment]
> I simply downloaded mass.zip, unzipped and copied files on custom_components/mass folder.
> 
> Then restarted HA of course.

When I download mass.zip to my Win10, Windows Defender blocks it with virus warning?

![image](https://user-images.githubusercontent.com/12792066/228929507-ba899470-305b-40c9-9a03-f10fabeb707e.png)

**Comment by marcelveldt** [comment]
https://github.com/music-assistant/hass-music-assistant/issues/1143

**Comment by userMak** [comment]
> #1143

Hi I am a bit confused. I updated HA in 2023.3.6 and added Music Assistant 2023.2.1 in HACS. After the restart I am trying to add it in my devices and I am getting the following error 

`Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble`

What I am doing wrong here, or at least how can I overcome it?

**Comment by OzGav** [comment]
What is the title of that post?

**Comment by userMak** [comment]
> What is the title of that post?

I thought that the beta version solves the problem.

**Comment by OzGav** [comment]
Please read the third post in that discussion
