### ISSUE TITLE
MASS doesn’t load after home assistant restart

### ISSUE THREAD

**Issue by sauln1** [music-assistant/hass-music-assistant#1084]
### What version of Music Assistant has the issue?

2022.2.1

### The problem

After restart of home assistant for any reason, error logs report MASS cannot be loaded due to missing requirements.

### How to reproduce

Restart HA (with backup) with MASS loaded with Spotify account.

### Relevant log output

Logger: homeassistant.setup
Source: setup.py:205 
First occurred: 6:06:31 PM (1 occurrences) 
Last logged: 6:06:31 PM

Setup failed for custom integration mass: Requirements for mass not found: ['music-assistant==1.8.7.2'].

### What version of Home Assistant Core are your running

2023.1.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by sauln1** [comment]
Accidently closed, apologies. Reopening

**Comment by OzGav** [comment]
Not sure. You could try restarting HA again or reinstall MA. If you are going to upgrade HA today to 2023.2.x you need to upgrade MA to the latest beta.

**Comment by OzGav** [comment]
Have you fixed this?

**Comment by JohnHof1275** [comment]
Same issue

```
Logger: homeassistant.setup
Source: setup.py:205
First occurred: 9:16:29 PM (1 occurrences)
Last logged: 9:16:29 PM

Setup failed for custom integration mass: Requirements for mass not found: ['music-assistant==1.8.7.2'].
```

Home Assistant 2023.2.5
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230202.0 - latest
HACS 1.31.0

**Comment by OzGav** [comment]
A new version of MA is imminent. Please wait until that drops as the current HA architecture changes have made the current MA version unsupportable.

**Comment by JohnHof1275** [comment]
> A new version of MA is imminent. Please wait until that drops as the current HA architecture changes have made the current MA version unsupportable.

timeframe?

**Comment by OzGav** [comment]
Days

**Comment by OzGav** [comment]
https://github.com/music-assistant/home-assistant-addon

Please move to V2 to resolve this. Note that it is still in beta so other issues may arise. However I am closing this as no further investigation will be done as V1 is no longer supported.
