### ISSUE TITLE
Delay when playing streaming radio on ESP32

### ISSUE THREAD

**Issue by preceus** [music-assistant/hass-music-assistant#1085]
### What version of Music Assistant has the issue?

2022.12.1

### The problem

Delay when playing streaming radio (also Tune Id) on ESP32. As if buffering is very long.I tried everything I could - when using MASS, the delay is 25 seconds. There is no delay when playing mp3 files. But even if you insert the url in the form of m3u, there is a delay of 25 seconds. When switching to the wav format in the queue menu settings, radio playback is instantaneous, but hissing every second.

### How to reproduce

Use ESP32 with DAC pcm5102A, install in HA like media player.

### Additional information

MAAS is installed on the HA supervised 2023.1.7 system under Debian 11 on a mini pc GK3V. The problem also appeared when installing HASSOS in a virtual machine.

### What version of Home Assistant Core are your running

2023.1.7

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by erkr** [comment]
Hi
Thanks for reporting your issue. This sounds like a buffering issue indeed. 
Marcel is close to releasing MA 2.0, where the whole streaming engine is revised.
Please report back once MA 2.0 is released, if this issue still persists.

Best Eric

**Comment by clutch70** [comment]
I am experiencing the same behavior using an ESP32-WROOM, for whatever reason that 25 seconds number seems to be significant. Or its a coincidence. What do I know.

I'll look out for MA2.0 announcement as well!

**Comment by OzGav** [comment]
https://github.com/music-assistant/home-assistant-addon

Please move to V2 to resolve this. Note that it is still in beta so other issues may arise.

**Comment by OzGav** [comment]
We will close this soon and ask you to report again when using MA V2
