### ISSUE TITLE
Family Account not working as being premium account - Spotify

### ISSUE THREAD

**Issue by Kris-Morrison** [music-assistant/hass-music-assistant#1087]
### What version of Music Assistant has the issue?

2022.12.1

### The problem

When logging in with the master account of the family subscription, it's saying that it's not a premium account.

### How to reproduce

login with the account of a family subscription on Spotify 

### What version of Home Assistant Core are your running

2023.01.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by erkr** [comment]
I guess that is something to check with Spotify?!

**Comment by Kris-Morrison** [comment]
issue is resolved... Thanks :)

**Comment by erkr** [comment]
Glad to hear that!
