### ISSUE TITLE
Can't add integration

### ISSUE THREAD

**Issue by marc3k18** [music-assistant/hass-music-assistant#1095]
### What version of Music Assistant has the issue?

2023.2.1

### The problem

Can't setup new integration

![image](https://user-images.githubusercontent.com/97817024/217437762-da0f9a8b-557d-428c-b9b6-e48b06df73f5.png)

### How to reproduce

Add Integration, select Music Assistant

### What version of Home Assistant Core are your running

2023.2.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Pleae confirm you have installed it successfully via HACS

**Comment by marc3k18** [comment]
I confirm that I install it via HACS.

I just uninstall, reboot, reinstall, reboot et same thing. Try with version 2022.12 and I got the same 'error'.

**Comment by OzGav** [comment]
Ok you can’t use 2022.x as that definitely won’t work with the current version. So you have successfully installed 2023.2.1 version of MA and you can see that in HACS? Have you ever had MA on your system before?

**Comment by marc3k18** [comment]
No first time



Le mer. 8 févr. 2023, 1 h 06 a.m., OzGav ***@***.***> a
écrit :

**Comment by OzGav** [comment]
How are you running HA? Please be specific.

**Comment by erkr** [comment]
Hi.
Did you follow the installation steps:
- install MA via HACS
- restart HA
- then add the integration via the the standard setup. If MA is not visible, refresh the browser cache

**Comment by marc3k18** [comment]
Yes this is the steps that I follow.

I try on Chrome, Firefox, Android app.

I use a dell i5 with ha os and ha supervisor.

Le mer. 8 févr. 2023, 10 h 25 a.m., Eric ***@***.***> a
écrit :

**Comment by OzGav** [comment]
How are you running HA? Please be specific about your hardware, operating system configuration and network setup.

**Comment by marc3k18** [comment]
Old dell laptop 5420. Running official HA OS and supervisor and core.
No vlan, no filtering.

Google Wifi for router

Using Casa for remote acces

Nothing really special about this setup

Le mer. 8 févr. 2023, 7 h 35 p.m., OzGav ***@***.***> a
écrit :

**Comment by OzGav** [comment]
I'm starting to guess now. Have a look and see if the DB has been created and if so delete it and try again. It will be in your `config `directory and is called `music_assistant.db`

**Comment by marc3k18** [comment]
Nothing with file editor or with ssh

File is not there..



Le mer. 8 févr. 2023, 9 h 27 p.m., OzGav ***@***.***> a
écrit :

**Comment by OzGav** [comment]
@marcelveldt Any ideas?

**Comment by gieljnssns** [comment]
There are no errors in the log?

**Comment by marc3k18** [comment]
Nothing..

**Comment by erkr** [comment]
@marc3k18 
For me it is unclear where in the process you get stuck.
When you go to Settings-integrations and select 'add integration'. Is the music assistant selectable? If selectable, an configuration menu should open. If not clear the browser cache.

**Comment by marc3k18** [comment]
This is the problem. Configuration windows open but empty.

And it's not a cache problem. I try with so many différent device and
browser.



Le jeu. 9 févr. 2023, 9 h 08 a.m., OzGav ***@***.***> a
écrit :

**Comment by erkr** [comment]
Yes, you tried several browsers. But did you try clear the cache, or alternately open HA in a private window? I have seen this behaviour before and clearing the cache and restarting HA resolved it.

Another option is that HACS didn't fully deploy the files for MA. If you open the integration in HACS and press the 3 dots, there is the option to re-download the integration. Restart HA before trying again.

**Comment by marc3k18** [comment]
Hello,

Yes I did clear the cache

Im doing some HA dev for the last 3 days so I restarted a lot of time since.

I try to redownload.

**Comment by erkr** [comment]
🤞hope that is the solution

**Comment by marc3k18** [comment]
No sorry


Try all that.

Even install the integration manually and still have the same problem.

Le sam. 11 févr. 2023, 12 h 37 p.m., Eric ***@***.***> a
écrit :

**Comment by OzGav** [comment]
Obviously we have a lot of users with this working fine so there is something wrong with your setup. Can you post a screen capture of your network config where it shows the external and internal url. Mainly interested in the internal url so you can partially obscure the external.

**Comment by OzGav** [comment]
And also what media player entities do you have?

**Comment by OzGav** [comment]
The other thing @erkr is that the dialog that he shows open has the title “Media Assistant” when the first dialog is normally “Media Players”?

**Comment by marc3k18** [comment]
I'm using yTubeMusic for now. That's all with local mp3.

![Screenshot_20230212-000500](https://user-images.githubusercontent.com/97817024/218294104-a96efeb9-5688-4135-85b2-6bac1cde679c.png)
![Screenshot_20230212-000509](https://user-images.githubusercontent.com/97817024/218294108-0e39eb9a-1592-4ef8-8c64-eb6d5c271730.png)
![Screenshot_20230212-000637](https://user-images.githubusercontent.com/97817024/218294113-a029d5f8-c34f-426a-bae4-7ce32975dca9.png)
![Screenshot_20230212-000648](https://user-images.githubusercontent.com/97817024/218294117-a4b6e6c6-e059-415c-8f34-a5621032ff87.png)

**Comment by erkr** [comment]
> The other thing @erkr is that the dialog that he shows open has the title “Media Assistant” when the first dialog is normally “Media Players”?

That's why I suggested to re-download MA and flush the browser cache.
It looks like the configuration code for the integration is not loaded. @marcelveldt  any other suggestions?!

**Comment by erkr** [comment]
@marc3k18 
I don't see anything wrong. Only difference with my setup is that you have configured your HA network static. Maybe that causes hostname related issues (beyond my expertise). I reserved a static HA ip address in the DHCP list on my router instead and configured dynamic network settings (default) on HA itself.
Best Eric

**Comment by OzGav** [comment]
In the home assistant URL try turning off automatic and add `http://10.18.0.250:8123`

**Comment by OzGav** [comment]
What media player entities do you have?

**Comment by marc3k18** [comment]
First thanks for your help.

So I try to set manually the url for local homeassistant and did a reservation on dhcp and remove the static ip.
Uninstall MA, reboot, install and reboot. Clear cache It still not working.

I remove all "media" intégration that I have.. radio browser and ytubemusic... Reinstall. Still not working.

I only have android tv and cast device.

![Screenshot_20230212-104609](https://user-images.githubusercontent.com/97817024/218321469-11f261bd-da37-484b-af66-5ba5b6332b8e.png)

**Comment by OzGav** [comment]
@erkr could here be something corrupt in the `.storage` folder causing the reinstall to fail?

**Comment by OzGav** [comment]
Looking through similar issues here is one persons solution
=============

Steps I took to get it to work:

Remove Music Assistant through HACS.
Reboot host.
Add Music Assistant through HACS.
Reboot host.
Add integration.
The difference here seems to be a full reboot of the host versus just restarting Home Assistant.

**Comment by erkr** [comment]
I don't have more ideas

**Comment by erkr** [comment]
> @erkr could there be something corrupt in the `.storage` folder causing the reinstall to fail?

Very well possible, but beyond my knowledge. @marcelveldt  other suggestions?

**Comment by marc3k18** [comment]
Case can be close. With the last update, I was able to install it.

Thanks for your help
