### ISSUE TITLE
Streaming the new BBC sounds streams fail.

### ISSUE THREAD

**Issue by Symbiot78** [music-assistant/hass-music-assistant#1097]
### What version of Music Assistant has the issue?

2023.2.1

### The problem

The new bbc sounds stream use a different codec from the old (mp3)

### How to reproduce

try streaming one of the new urls

### Relevant log output

2023-02-11 09:23:54.736 WARNING (MainThread) [music_assistant.music.file] Could not parse uri/file http://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/uk/sbr_high/ak/bbc_radio_two.m3u8 to track: Unable to retrieve info for http://as-hls-uk-live.akamaized.net/pool_904/live/uk/bbc_radio_two/bbc_radio_two.isml/bbc_radio_two-audio%3d320000.norewind.m3u8: Server returned 403 Forbidden (access denied)
2023-02-11 09:23:55.294 WARNING (MainThread) [music_assistant.music.file] Could not parse uri/file http://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/uk/sbr_high/ak/bbc_radio_two.m3u8 to track: Unable to retrieve info for http://as-hls-uk-live.akamaized.net/pool_904/live/uk/bbc_radio_two/bbc_radio_two.isml/bbc_radio_two-audio%3d320000.norewind.m3u8: Server returned 403 Forbidden (access denied)
2023-02-11 09:24:00.774 WARNING (MainThread) [music_assistant.music.file] Could not parse uri/file http://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/uk/sbr_med/ak/bbc_radio_two.m3u8 to track: Unable to retrieve info for http://as-hls-uk-live.akamaized.net/pool_904/live/uk/bbc_radio_two/bbc_radio_two.isml/bbc_radio_two-audio%3d128000.norewind.m3u8: Server returned 403 Forbidden (access denied)
2023-02-11 09:24:00.784 INFO (MainThread) [music_assistant] Finished job [Add file://playlist/radiostationsplaylistm3u to database] in 7.05 seconds.
2023-02-11 09:24:00.791 WARNING (MainThread) [music_assistant.music.file] Could not parse uri/file http://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/uk/sbr_med/ak/bbc_radio_two.m3u8 to track: Unable to retrieve info for http://as-hls-uk-live.akamaized.net/pool_904/live/uk/bbc_radio_two/bbc_radio_two.isml/bbc_radio_two-audio%3d128000.norewind.m3u8: Server returned 403 Forbidden (access denied)
2023-02-11 09:24:16.358 INFO (MainThread) [music_assistant.players.stream] Start Streaming queue track: url://radio/http://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/nonuk/sbr_vlow/ak/bbc_radio_two.m3u8 (bbc_radio_two-audio%3d48000) for queue Køkken - crossfade: False
2023-02-11 09:24:22.891 INFO (MainThread) [uamqp.async_ops.client_async] Keeping 'ReceiveClientAsync' connection alive. b'SBReceiver-0bd395c3-3d82-4816-9519-fd5138cc4149'
2023-02-11 09:24:22.910 WARNING (MainThread) [music_assistant.players.stream] Stream error on url://radio/http://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/nonuk/sbr_vlow/ak/bbc_radio_two.m3u8
2023-02-11 09:24:22.911 INFO (MainThread) [music_assistant.players.stream] Start Streaming queue track: url://radio/http://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/nonuk/low/ak/bbc_radio_two.m3u8 (bbc_radio_two-audio%3d48000) for queue Køkken - crossfade: False
2023-02-11 09:24:27.036 INFO (MainThread) [music_assistant.players.stream] Start Streaming queue track: url://radio/http://stream.live.vc.bbcmedia.co.uk/bbc_radio_two (BBC Radio) for queue Køkken - crossfade: False
2023-02-11 09:24:29.429 WARNING (MainThread) [music_assistant.helpers.audio] Could not determine integrated loudness of url://radio/http://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/nonuk/sbr_vlow/ak/bbc_radio_two.m3u8 - ffmpeg version 5.0.1 Copyright (c) 2000-2022 the FFmpeg developers
built with gcc 11.2.1 (Alpine 11.2.1_git20220219) 20220219
configuration: --prefix=/usr --enable-avfilter --enable-gnutls --enable-gpl --enable-libass --enable-libmp3lame --enable-libpulse --enable-libvorbis --enable-libvpx --enable-libxvid --enable-libx264 --enable-libx265 --enable-libtheora --enable-libv4l2 --enable-libdav1d --enable-lto --enable-postproc --enable-pic --enable-pthreads --enable-shared --enable-libxcb --enable-librist --enable-libsrt --enable-libssh --enable-libvidstab --disable-stripping --disable-static --disable-librtmp --enable-libaom --enable-libopus --enable-libsoxr --enable-libwebp --enable-vaapi --enable-vdpau --enable-vulkan --enable-libdrm --disable-debug
libavutil 57. 17.100 / 57. 17.100
libavcodec 59. 18.100 / 59. 18.100
libavformat 59. 16.100 / 59. 16.100
libavdevice 59. 4.100 / 59. 4.100
libavfilter 8. 24.100 / 8. 24.100
libswscale 6. 4.100 / 6. 4.100
libswresample 4. 3.100 / 4. 3.100
libpostproc 56. 3.100 / 56. 3.100
[hls @ 0x7f3ae0a7f000] Skip ('#EXT-X-VERSION:3')
[hls @ 0x7f3ae0a7f000] Skip ('## Created with Unified Streaming Platform(version=1.8.4)')
[hls @ 0x7f3ae0a7f000] Skip ('#EXT-X-INDEPENDENT-SEGMENTS')
[hls @ 0x7f3ae0a7f000] Skip ('#USP-X-TIMESTAMP-MAP:MPEGTS=1506857888,LOCAL=2023-02-11T08:24:19.200000Z')
[hls @ 0x7f3ae0a7f000] Skip ('#EXT-X-PROGRAM-DATE-TIME:2023-02-11T08:24:19.200000Z')
[hls @ 0x7f3ae0a7f000] Failed to open segment 261891231 of playlist 0
[hls @ 0x7f3ae0a7f000] Failed to open segment 261891232 of playlist 0
[hls @ 0x7f3ae0a7f000] Failed to open segment 261891233 of playlist 0
[pipe @ 0x7f3ae0a70700] Protocol 'pipe' not on whitelist 'crypto,data'!
[hls @ 0x7f3ae0a7f000] Failed to reload playlist 0
[hls @ 0x7f3ae0a7f000] Error when loading first segment 'pipe:bbc_radio_two-audio=48000-261891229.ts'
pipe:: Invalid argument
2023-02-11 09:24:29.430 INFO (MainThread) [music_assistant] Finished job [Analyze audio for url://radio/http://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/nonuk/sbr_vlow/ak/bbc_radio_two.m3u8] in 6.52 seconds.
2023-02-11 09:24:29.542 WARNING (MainThread) [music_assistant.players.stream] Stream error on url://radio/http://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/nonuk/low/ak/bbc_radio_two.m3u8
2023-02-11 09:24:29.543 INFO (MainThread) [music_assistant.players.stream] Start Streaming queue track: url://radio/http://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/nonuk/low/ak/bbc_radio_two.m3u8 (bbc_radio_two-audio%3d48000) for queue Køkken - crossfade: False
2023-02-11 09:24:31.890 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.rest
2023-02-11 09:24:31.890 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.rest
2023-02-11 09:24:36.064 WARNING (MainThread) [music_assistant.helpers.audio] Could not determine integrated loudness of url://radio/http://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/nonuk/low/ak/bbc_radio_two.m3u8 - ffmpeg version 5.0.1 Copyright (c) 2000-2022 the FFmpeg developers

### Additional information

I have tried a bunch of different BBC sounds urls.. and none seem to work. 
the mp3 versions (which are being phased out in 2023) work.

but the new stream simply do not work.

this is an example of an m3u8 file downloaded from a link:

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=50880,CODECS="mp4a.40.5"
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_two/bbc_radio_two.isml/bbc_radio_two-audio%3d48000.norewind.m3u8

if I insert the link in the m3u8 (the next m3u8) 
I get a new file containing:

#EXTM3U
#EXT-X-VERSION:3
## Created with Unified Streaming Platform(version=1.8.4)
#EXT-X-MEDIA-SEQUENCE:261891269
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-TARGETDURATION:6
#USP-X-TIMESTAMP-MAP:MPEGTS=1529897888,LOCAL=2023-02-11T08:28:35.200000Z
#EXT-X-PROGRAM-DATE-TIME:2023-02-11T08:28:35.200000Z
#EXTINF:6.4, no desc
bbc_radio_two-audio=48000-261891269.ts
#EXTINF:6.4, no desc
bbc_radio_two-audio=48000-261891270.ts
#EXTINF:6.4, no desc
bbc_radio_two-audio=48000-261891271.ts
#EXTINF:6.4, no desc
bbc_radio_two-audio=48000-261891272.ts
#EXTINF:6.4, no desc
bbc_radio_two-audio=48000-261891273.ts

### What version of Home Assistant Core are your running

2023.2.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Linux

**Comment by marcelveldt** [comment]
The error is 403 forbidden so they are somehow blocking unknown consumers I guess, may be just by using the UserAgent.
I will take a look at this right after the beta of V2 landed. Are the old url's already phased out or not yet ?

**Comment by Symbiot78** [comment]
I don't know where the difference(s) are but if I take the same URL and start it via vlc player or similar, it works fine.
So something is different in the way they parse the url(s).

The old URL's are not phased out yet.. I believe it's scheduled to happen in June.

listening to the mp3 url you get announcements about changes to the streaming service - but apart from that it works..

**Comment by marcelveldt** [comment]
Finally had time to look at this. Fixed in MA 2.0 beta 16

**Comment by cross-hello** [comment]
@amirsol81 
Find out pattern of URL, then could get Python code:
```python
def get_link(radio_name):                       
       print('http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_{}/bbc_radio_{}.isml/bbc_radio_{}-audio%3d320000.norewind.m3u8'.format(radio_name,radio_name,radio_name))
```

So BBC radio one could get link: http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_one/bbc_radio_one.isml/bbc_radio_one-audio%3d320000.norewind.m3u8

BBC radio three: http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_three/bbc_radio_three.isml/bbc_radio_three-audio%3d320000.norewind.m3u8

Or you could get BBC radio stream from [here](https://gist.github.com/bpsib/67089b959e4fa898af69fea59ad74bc3). Then `curl -L  url` pursue back final destination.

**Comment by cross-hello** [comment]
#EXTM3U
#EXTINF:-1,BBC - Radio 1
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_one/bbc_radio_one.isml/bbc_radio_one-audio%3d320000.norewind.m3u8
#EXTINF:-1,BBC - Radio 1Xtra
http://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/uk/sbr_med/ak/bbc_1xtra.m3u8
#EXTINF:-1,BBC - Radio 1Dance
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_one_dance/bbc_radio_one_dance.isml/bbc_radio_one_dance-audio%3d320000.norewind.m3u8
#EXTINF:-1,BBC - Radio 1Relax
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_one_relax/bbc_radio_one_relax.isml/bbc_radio_one_relax-audio%3d320000.norewind.m3u8
#EXTINF:-1,BBC - Radio 2
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_two/bbc_radio_two.isml/bbc_radio_two-audio%3d320000.norewind.m3u8
#EXTINF:-1,BBC - Radio 3
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_three/bbc_radio_three.isml/bbc_radio_three-audio%3d320000.norewind.m3u8
#EXTINF:-1,BBC - Radio 4
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_fourfm/bbc_radio_fourfm.isml/bbc_radio_fourfm-audio%3d320000.norewind.m3u8
#EXTINF:-1,BBC - Radio 4 LW
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_fourlw/bbc_radio_fourlw.isml/bbc_radio_fourlw-audio%3d320000.norewind.m3u8
#EXTINF:-1,BBC - Radio 4 Extra
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_four_extra/bbc_radio_four_extra.isml/bbc_radio_four_extra-audio%3d320000.norewind.m3u8
#EXTINF:-1,BBC - Radio 5 live
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_five_live/bbc_radio_five_live.isml/bbc_radio_five_live-audio%3d320000.norewind.m3u8
#EXTINF:-1,BBC - Radio 6 Music
http://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/uk/sbr_med/ak/bbc_6music.m3u8
#EXTINF:-1,BBC - Radio 5 Live sports extra (UK Only)
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_five_live_sports_extra/bbc_radio_five_live_sports_extra.isml/bbc_radio_five_live_sports_extra-audio%3d320000.norewind.m3u8
#EXTINF:-1,BBC - Radio Asian Network
http://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/uk/sbr_med/ak/bbc_asian_network.m3u8
#EXTINF:-1,BBC - BBC World Service
http://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/nonuk/sbr_low/ak/bbc_world_service.m3u8
#EXTINF:-1,BBC - BBC CWR
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_coventry_warwickshire/bbc_radio_coventry_warwickshire.isml/bbc_radio_coventry_warwickshire-audio%3d320000.norewind.m3u8
#EXTINF:-1,BBC - BBC Essex
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_essex/bbc_radio_essex.isml/bbc_radio_essex-audio%3d320000.norewind.m3u8
#EXTINF:-1,BBC - BBC Hereford Worcester
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_hereford_worcester/bbc_radio_hereford_worcester.isml/bbc_radio_hereford_worcester-audio%3d320000.norewind.m3u8
#EXTINF:-1,BBC - Radio Berkshire
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_berkshire/bbc_radio_berkshire.isml/bbc_radio_berkshire-audio%3d320000.norewind.m3u8
#EXTINF:-1,BBC - Radio Bristol
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_bristol/bbc_radio_bristol.isml/bbc_radio_bristol-audio%3d320000.norewind.m3u8
#EXTINF:-1,BBC - Radio Cambridge
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_cambridge/bbc_radio_cambridge.isml/bbc_radio_cambridge-audio%3d320000.norewind.m3u8
#EXTINF:-1,BBC - Radio Cornwall
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_cornwall/bbc_radio_cornwall.isml/bbc_radio_cornwall-audio%3d320000.norewind.m3u8
#EXTINF:-1,BBC - Radio Cumbria
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_cumbria/bbc_radio_cumbria.isml/bbc_radio_cumbria-audio%3d320000.norewind.m3u8
#EXTINF:-1,BBC - Radio Cymru
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_cymru/bbc_radio_cymru.isml/bbc_radio_cymru-audio%3d320000.norewind.m3u8
#EXTINF:-1,BBC - Radio Cymru 2
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_cymru_2/bbc_radio_cymru_2.isml/bbc_radio_cymru_2-audio%3d320000.norewind.m3u8
#EXTINF:-1,BBC - Radio Derby
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_derby/bbc_radio_derby.isml/bbc_radio_derby-audio%3d320000.norewind.m3u8
#EXTINF:-1,BBC - Radio Devon
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_devon/bbc_radio_devon.isml/bbc_radio_devon-audio%3d320000.norewind.m3u8
#EXTINF:-1,BBC - Radio Foyle
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_foyle/bbc_radio_foyle.isml/bbc_radio_foyle-audio%3d320000.norewind.m3u8
#EXTINF:-1,BBC - Radio Gloucestershire
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_gloucestershire/bbc_radio_gloucestershire.isml/bbc_radio_gloucestershire-audio%3d320000.norewind.m3u8
#EXTINF:-1,BBC - Radio Guernsey
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_guernsey/bbc_radio_guernsey.isml/bbc_radio_guernsey-audio%3d320000.norewind.m3u8
#EXTINF:-1,BBC - Radio Humberside
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_humberside/bbc_radio_humberside.isml/bbc_radio_humberside-audio%3d320000.norewind.m3u8
#EXTINF:-1,BBC - Radio Jersey
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_jersey/bbc_radio_jersey.isml/bbc_radio_jersey-audio%3d320000.norewind.m3u8
#EXTINF:-1,BBC - Radio Kent
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_kent/bbc_radio_kent.isml/bbc_radio_kent-audio%3d320000.norewind.m3u8
#EXTINF:-1,BBC - Radio Lancashire
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_lancashire/bbc_radio_lancashire.isml/bbc_radio_lancashire-audio%3d320000.norewind.m3u8
#EXTINF:-1,BBC - Radio Leeds
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_leeds/bbc_radio_leeds.isml/bbc_radio_leeds-audio%3d320000.norewind.m3u8
#EXTINF:-1,BBC - Radio Leicester
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_leicester/bbc_radio_leicester.isml/bbc_radio_leicester-audio%3d320000.norewind.m3u8
#EXTINF:-1,BBC - Radio Lincolnshire
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_lincolnshire/bbc_radio_lincolnshire.isml/bbc_radio_lincolnshire-audio%3d320000.norewind.m3u8
#EXTINF:-1,BBC - Radio London
http://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/uk/sbr_med/ak/bbc_london.m3u8
#EXTINF:-1,BBC - Radio Manchester
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_manchester/bbc_radio_manchester.isml/bbc_radio_manchester-audio%3d320000.norewind.m3u8
#EXTINF:-1,BBC - Radio Merseyside
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_merseyside/bbc_radio_merseyside.isml/bbc_radio_merseyside-audio%3d320000.norewind.m3u8
#EXTINF:-1,BBC - Radio nan Gaidheal
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_nan_gaidheal/bbc_radio_nan_gaidheal.isml/bbc_radio_nan_gaidheal-audio%3d320000.norewind.m3u8
#EXTINF:-1,BBC - Radio Newcastle
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_newcastle/bbc_radio_newcastle.isml/bbc_radio_newcastle-audio%3d320000.norewind.m3u8
#EXTINF:-1,BBC - Radio Norfolk
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_norfolk/bbc_radio_norfolk.isml/bbc_radio_norfolk-audio%3d320000.norewind.m3u8
#EXTINF:-1,BBC - Radio Northampton
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_northampton/bbc_radio_northampton.isml/bbc_radio_northampton-audio%3d320000.norewind.m3u8
#EXTINF:-1,BBC - Radio Nottingham
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_nottingham/bbc_radio_nottingham.isml/bbc_radio_nottingham-audio%3d320000.norewind.m3u8
#EXTINF:-1,BBC - Radio Orkney
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_orkney/bbc_radio_orkney.isml/bbc_radio_orkney-audio%3d320000.norewind.m3u8
#EXTINF:-1,BBC - Radio Oxford
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_oxford/bbc_radio_oxford.isml/bbc_radio_oxford-audio%3d320000.norewind.m3u8
#EXTINF:-1,BBC - Radio Scotland FM
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_scotland_fm/bbc_radio_scotland_fm.isml/bbc_radio_scotland_fm-audio%3d320000.norewind.m3u8
#EXTINF:-1,BBC - Radio Scotland MW
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_scotland_mw/bbc_radio_scotland_mw.isml/bbc_radio_scotland_mw-audio%3d320000.norewind.m3u8
#EXTINF:-1,BBC - Radio Sheffield
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_sheffield/bbc_radio_sheffield.isml/bbc_radio_sheffield-audio%3d320000.norewind.m3u8
#EXTINF:-1,BBC - Radio Shropshire
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_shropshire/bbc_radio_shropshire.isml/bbc_radio_shropshire-audio%3d320000.norewind.m3u8
#EXTINF:-1,BBC - Radio Solent
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_solent/bbc_radio_solent.isml/bbc_radio_solent-audio%3d320000.norewind.m3u8
#EXTINF:-1,BBC - Radio Solent West Dorset
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_solent_west_dorset/bbc_radio_solent_west_dorset.isml/bbc_radio_solent_west_dorset-audio%3d320000.norewind.m3u8
#EXTINF:-1,BBC - Radio Somerset Sound
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_somerset_sound/bbc_radio_somerset_sound.isml/bbc_radio_somerset_sound-audio%3d320000.norewind.m3u8
#EXTINF:-1,BBC - Radio Stoke
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_stoke/bbc_radio_stoke.isml/bbc_radio_stoke-audio%3d320000.norewind.m3u8
#EXTINF:-1,BBC - Radio Suffolk
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_suffolk/bbc_radio_suffolk.isml/bbc_radio_suffolk-audio%3d320000.norewind.m3u8
#EXTINF:-1,BBC - Radio Surrey
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_surrey/bbc_radio_surrey.isml/bbc_radio_surrey-audio%3d320000.norewind.m3u8
#EXTINF:-1,BBC - Radio Sussex
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_sussex/bbc_radio_sussex.isml/bbc_radio_sussex-audio%3d320000.norewind.m3u8
#EXTINF:-1,BBC - Radio Tees
http://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/uk/sbr_med/ak/bbc_tees.m3u8
#EXTINF:-1,BBC - Radio Ulster
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_ulster/bbc_radio_ulster.isml/bbc_radio_ulster-audio%3d320000.norewind.m3u8
#EXTINF:-1,BBC - Radio Wales
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_wales_fm/bbc_radio_wales_fm.isml/bbc_radio_wales_fm-audio%3d320000.norewind.m3u8
#EXTINF:-1,BBC - Radio Wiltshire
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_wiltshire/bbc_radio_wiltshire.isml/bbc_radio_wiltshire-audio%3d320000.norewind.m3u8
#EXTINF:-1,BBC - Radio WM
http://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/uk/sbr_med/ak/bbc_wm.m3u8
#EXTINF:-1,BBC - Radio York
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_york/bbc_radio_york.isml/bbc_radio_york-audio%3d320000.norewind.m3u8
#EXTINF:-1,BBC - Three Counties Radio
http://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/uk/sbr_med/ak/bbc_three_counties_radio.m3u8

OK, there are all.
תודה לאל

**Comment by ChristopherW** [comment]
The above are ~48 kbps SBR VBR AAC. ~320 kbps variants of all stations are available if you replace "48000" with "320000" in the URLs.
