### ISSUE TITLE
MA doesn’t work with HA 2023.3.x was: Dependency conflict on HA 2023.3 beta

### ISSUE THREAD

**Issue by Mariusthvdb** [music-assistant/hass-music-assistant#1104]
### What version of Music Assistant has the issue?

2023.2.1

### The problem

probably getting used to this, just mentioning for reference.

### How to reproduce

update to HA 2023.3

### Relevant log output
```
2023-02-23 00:14:51.945 ERROR (SyncWorker_10) [homeassistant.util.package] Unable to install package music-assistant==1.8.7.4: ERROR: Cannot install music-assistant because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
[notice] A new release of pip is available: 23.0 -> 23.0.1
[notice] To update, run: pip install --upgrade pip
```

### What version of Home Assistant Core are your running

2023.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Thanks. Marcel will have a look. This might even get overtaken by v2 but not sure.

**Comment by varungujjar** [comment]
Just tried to install I get the same error, kind of found that its the sqlalchemy version, HASS Recorder uses SQLAlchemy 2.0.4 but MASS demands for sqlalchemy-1.4.46. I tried to fix but get the following error

Traceback (most recent call last):
  File "/home/pi/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/home/pi/config/custom_components/mass/__init__.py", line 197, in async_setup_entry
    raise exc
  File "/home/pi/config/custom_components/mass/__init__.py", line 190, in async_setup_entry
    await mass.setup()
  File "/home/pi/env/lib/python3.10/site-packages/music_assistant/mass.py", line 79, in setup
    await self.database.setup()
  File "/home/pi/env/lib/python3.10/site-packages/music_assistant/controllers/database.py", line 43, in setup
    await self._migrate()
  File "/home/pi/env/lib/python3.10/site-packages/music_assistant/controllers/database.py", line 188, in _migrate
    if prev_version := await self.get_setting("version"):
  File "/home/pi/env/lib/python3.10/site-packages/music_assistant/controllers/database.py", line 53, in get_setting
    return db_row["value"]
  File "lib/sqlalchemy/cyextension/resultproxy.pyx", line 67, in sqlalchemy.cyextension.resultproxy.BaseRow.__getitem__
TypeError: tuple indices must be integers or slices, not str

**Comment by marcelveldt** [comment]
I will not fix it anymore this time. V2 launch is very soon and then we can say goodbye to these kind of dependency conflicts forever. So for now, stick with previous HA or live a while without MA ;-)

I am really working on the last bits of MA v2.0 so keep an eye on discord for the beta instructions.

**Comment by sevagjb** [comment]
> I will not fix it anymore this time. V2 launch is very soon and then we can say goodbye to these kind of dependency conflicts forever. So for now, stick with previous HA or live a while without MA ;-)
> 
> I am really working on the last bits of MA v2.0 so keep an eye on discord for the beta instructions.

How long i need to stay on HA old version???

**Comment by OzGav** [comment]
Impossible to say with certainty but days to weeks not months.

**Comment by Aasikki** [comment]
> I will not fix it anymore this time. V2 launch is very soon and then we can say goodbye to these kind of dependency conflicts forever. So for now, stick with previous HA or live a while without MA ;-)
> 
> I am really working on the last bits of MA v2.0 so keep an eye on discord for the beta instructions.

Hopefully V2 will be awesome! I always update on day one, so going without it for now, but it was always giving me issues with yotube music anyways, so here's hoping V2 will be smoother!

**Comment by userMak** [comment]
> Impossible to say with certainty but days to weeks not months.

make it days please :)

**Comment by Aasikki** [comment]
> > Impossible to say with certainty but days to weeks not months.
> 
> make it days please :)

Hey now, not cool to hurry up someone doing awesome stuff for free :)

**Comment by OzGav** [comment]
https://github.com/music-assistant/home-assistant-addon

V2 is available . Note that it is still in beta so other issues may arise.

**Comment by userMak** [comment]
> https://github.com/music-assistant/home-assistant-addon
> 
> V2 is available . Note that it is still in beta so other issues may arise.

do we have to uninstall the previous version?

**Comment by OzGav** [comment]
You need to temporary disable the MA integration in HA, they can be installed at the same time but not run at the same time.

Make sure to not run HA slimproto integration and/or LMS at the same time as MA 2.0

**Comment by DidibabaQiu** [comment]
> https://github.com/music-assistant/home-assistant-addon
> 
> V2 可用。請注意，它仍處於測試階段，因此可能會出現其他問題。

Thank you for your selfless dedication

**Comment by znack14** [comment]
This add-on is incompatible with your device's processor or the operating system you have installed on your device
What shall I do?  Is raspberry pi 3 support planned?

**Comment by OzGav** [comment]
Are you running the 32 bit version of the OS?

**Comment by znack14** [comment]
> Вы используете 32-битную версию ОС?

yes i have a small raspberry pi 3

**Comment by OzGav** [comment]
There is a 64bit version of HA for the Raspberry Pi 3. I am assuming that is why you can’t install the add on

**Comment by znack14** [comment]
> Для Raspberry Pi 3 существует 64-битная версия HA. Я предполагаю, что именно поэтому вы не можете установить надстройку

yes I have armv7L.  But there will be no other.  It is bad that it is not installed.

**Comment by OzGav** [comment]
Not sure. This says the raspberry pi 3 has an arm v8 https://pi.processing.org/technical/

There is a 64bit version of the HAOS for the raspberry pi 3

**Comment by OzGav** [comment]
ARMv7 was Raspberry pi 2

**Comment by znack14** [comment]
> Для Raspberry Pi 3 существует 64-битная версия HA. Я предполагаю, что именно поэтому вы не можете установить надстройку

Raspberry Pi CM3+ 32GB eMMC,
  - QuadCortexA53@1.2GHz 1GB RAM,
  - PoE 802.3af 13W or 6-24V power supply,
  - Ethernet 10/100Mbit, 2x USB2.0,
  - startup-shutdown button (GPIO3), activation delay 0.1s,
  - DS3231 RTC clock with rechargeable battery (GPIO0,1),
  - RS485 auto-flow, max 500kbps, up to 128 devices (GPIO32,33),

**Comment by znack14** [comment]
these are my raspberry pi settings.  Only 32-bit systems can use it.

**Comment by OzGav** [comment]
Ah the compute module! Ok then I will ask the dev but I don’t think MA will work 32bit. I will confirm for you.

**Comment by znack14** [comment]
> Ах, вычислительный модуль! Хорошо, тогда я спрошу у разработчиков, но я не думаю, что MA будет работать с 32-битной версией. Я подтвержу для вас.

thank you

**Comment by userMak** [comment]
sorry for the off topic, but can someone help me to define the path of my local music to add it in music assistant please?
I have the following in confi.yaml
  media_dirs:
    media: /media
and this is the path 
\\192.168.1.15\media
![image](https://user-images.githubusercontent.com/55662933/224532742-d7c8e3f5-2fa0-4f63-88ff-ffb8c6e24d77.png)

I have HasOS in a nuc. What is the path I should use in MA to Enable filesystem provider?

**Comment by OzGav** [comment]
@znack14 Sorry MA V2 will not run on your hardware. 1GB RAM is not enough as HA alone needs that. To run HA and MA together the advice is:
Minimal rpi4 (or comparable), no rpi 3
64 bits cpu and OS
absolute minimum of 2gb memory, 4 gb or higher recommended

**Comment by FedericoBS** [comment]
i can not find the advanced option on the queue in the beta version. i need to disable the icy metadata to avoid stuttering. Can you help?

**Comment by OzGav** [comment]
ICY metadata has been left out of the current beta as there should be no need for such advanced settings to begin with. Marcel said he can add them back if there really is a demand/need. Is the issue exactly the same or does the music just stutter sometimes ? Stuttering has nothing to do with ICY. A lot of awful noise does.

**Comment by jurgenhaas** [comment]
How can I install this AddOn if I'm running HA in Docker, i.e. without supervisor?

**Comment by OzGav** [comment]
Have a look at post 2 in the beta channel https://discord.com/channels/753947050995089438/1083643113484070953

**Comment by jurgenhaas** [comment]
Mmph, I need Discord??? My goodness, this is one of the worst platforms wrt privacy. Nayways, I logged into an account but the link responds with "No text channels". Is it too much to ask for providing required information here in the repo?

**Comment by OzGav** [comment]
Just trying to save the duplication..

**HOW TO INSTALL/RUN THE BETA OF 2.0 ?**

**Preferred method: Home Assistant Add**
By far the most convenient way to run the Music Assistant Server is to install the Music Assistant Add-on:

> Add the Music Assistant repository to your Home Assistant instance.
> Install the Music Assistant add-on.
> Add repository on my Home Assistant

Click the link below to add the Music Assistant repository to HA:
https://my.home-assistant.io/redirect/supervisor_add_addon_repository/?repository_url=https%3A%2F%2Fgithub.com%2Fmusic-assistant%2Fhome-assistant-addon

**Alternative method: Docker image**
An alternative way to run the Music Assistant server is by running the docker image:

`docker run --network host ghcr.io/music-assistant/server`


You must run the docker container with host network mode and the data volume is /data. If you want access to your local music files from within MA, make sure to also mount that, e.g. /media. Note that accessing remote (SMB) shares can be done from within MA itself using the SMB File provider.

**Comment by jurgenhaas** [comment]
Thanks a lot @OzGav much appreciated. The problem with that link is that it only works when HA is run with supervisor, otherwise that link doesn't work, right?

So I have to go with the separate docker image, which is fine too.

**Comment by schoenwaldnils** [comment]
Is the V2 the default when adding it via this link?
I still get the same error as before.
`Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble`

**Comment by gaussey** [comment]
> Just trying to save the duplication..
> 
> **HOW TO INSTALL/RUN THE BETA OF 2.0 ?**
> 
> **Preferred method: Home Assistant Add** By far the most convenient way to run the Music Assistant Server is to install the Music Assistant Add-on:
> 
> > Add the Music Assistant repository to your Home Assistant instance.
> > Install the Music Assistant add-on.
> > Add repository on my Home Assistant
> 
> Click the link below to add the Music Assistant repository to HA: https://my.home-assistant.io/redirect/supervisor_add_addon_repository/?repository_url=https%3A%2F%2Fgithub.com%2Fmusic-assistant%2Fhome-assistant-addon
> 
> **Alternative method: Docker image** An alternative way to run the Music Assistant server is by running the docker image:
> 
> `docker run --network host ghcr.io/music-assistant/server`
> 
> You must run the docker container with host network mode and the data volume is /data. If you want access to your local music files from within MA, make sure to also mount that, e.g. /media. Note that accessing remote (SMB) shares can be done from within MA itself using the SMB File provider.

So Mass is now an separate addon rather than a HACS addon?

**Comment by OzGav** [comment]
> So I have to go with the separate docker image, which is fine too.
Yes docker for you

**Comment by OzGav** [comment]
> `Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble`
You need to disable or remove the existing integration then install the new add on.

**Comment by OzGav** [comment]
> edit: it’s now seeing my Yamaha receiver, how do you add a network share as a provider? Previously I had to mount my network share inside hass. Also, does anyone have an automation example that would play a playlist using MASS V2 on an a receiver?

V2 has samba shares as a provider now so mounting not required 
Current,y there is no HA integration so automations don’t work. Expect the integration in about a week.

**Comment by Tech33** [comment]
> @znack14 Sorry MA V2 will not run on your hardware. 1GB RAM is not enough as HA alone needs that. To run HA and MA together the advice is: Minimal rpi4 (or comparable), no rpi 3 64 bits cpu and OS absolute minimum of 2gb memory, 4 gb or higher recommended

I am also on same boat with rpi 3 :( would be soo great if you can fix V1 for backwards Compatibility

**Comment by OzGav** [comment]
I’m sorry but it is impossible to fix V1 as this is due to HA changes not MA

**Comment by andrewigali** [comment]
Installed the v2 beta on Rspberry4 Argon One HAOS 2023.3.3, Supervisor 2023.03.1, but can't running. Clicked the Start button, but nothing happened. No error on log and i can't sett.
The old HACS version can't loading, not work. :(
I restored to an earlier system version, but not helped.
Now the Music Assistant doesn't work at all. :(

**Comment by OzGav** [comment]
You can’t have both running at once. Make sure V1 integration is disabled or removed prior to trying to start the add on

**Comment by andrewigali** [comment]
> You can’t have both running at once. Make sure V1 integration is disabled or removed prior to trying to start the add on


Unfortunately, it doesn't work even if I disable Music Assistant in the Settings Devices & Services menu.
 Can someone make a video on how to switch from the no longer working Music Assistant to the new version?

**Comment by OzGav** [comment]
There was an issue with one of the beta. Which beta do you have installed? Make sure you have the latest.

**Comment by andrewigali** [comment]
> There was an issue with one of the beta. Which beta do you have installed? Make sure you have the latest.

2.0.0b4

In Music Assistant log:
![IMG_20230314_074701](https://user-images.githubusercontent.com/73789218/224918298-d109f34e-bba3-4149-9866-0f909f6c7075.jpg)


But doesn't work. :(

**Comment by andrewigali** [comment]
> There was an issue with one of the beta. Which beta do you have installed? Make sure you have the latest.

2.0.0b4

In Music Assistant log:
![IMG_20230314_075003](https://user-images.githubusercontent.com/73789218/224918931-1cb4e3a1-df29-49fe-928f-bd87b972a89a.jpg)

But doesn't work. :(

**Comment by OzGav** [comment]
I think you should open a separate issue for us to step through this. The screen capture above shows MA working. It has started and has found your players. So you saying it doesn’t work is not clearly explaining what isn’t working.

**Comment by andrewigali** [comment]
This is the problem:
![Screenshot_2023-03-14-10-54-25-884_io homeassistant companion android](https://user-images.githubusercontent.com/73789218/224967926-0e860ba0-4a1e-4a13-92c7-963b1a9df5bf.jpg)

![Screenshot_2023-03-14-10-54-37-971_io homeassistant companion android](https://user-images.githubusercontent.com/73789218/224968015-27d54655-eb06-4645-b585-f4b3ecca8acb.jpg)

![IMG_20230314_110613](https://user-images.githubusercontent.com/73789218/224968128-913ee7e5-0f84-4f78-b193-f14bd0548f0f.jpg)

**Comment by OzGav** [comment]
As I said above please open a separate issue. I will remove the above posts soon to reduce this thread length. Just add all that you posted above.

**Comment by marcelveldt** [comment]
closing this in favor of https://github.com/music-assistant/hass-music-assistant/issues/1143
