### ISSUE TITLE
Cannot install Music Assistant system integration

### ISSUE THREAD

**Issue by downeymj** [music-assistant/hass-music-assistant#1111]
### What version of Music Assistant has the issue?

2023.2.1

### The problem

Unable to successfully install Music Assistant. The instruction process fails at the step of installing the system integration.

### How to reproduce

- Download Music Assistant via HACS integrations
- Restart HA per instruction
- Under HA's Settings > Devices & Services > Integrations > Add Integration, choose "Music Assistant".

Expected behavior: 

- Configuration wizard appears to set up integration.

Actual behavior:

- Dialog box appears "Please wait, starting configuration wizard for Music Assistant" with spinner, but hangs.
- Eventually, the following Error appears:  `Config flow could not be loaded: <html> <head><title>504 Gateway Time-out</title></head> <body> <center><h1>504 Gateway Time-out</h1></center> <hr><center>nginx</center> </body> </html> `

### Relevant log output

```
Logger: homeassistant.util.package
Source: util/package.py:107
First occurred: 03:37:44 (3 occurrences)
Last logged: 03:38:10
Unable to install package music-assistant==1.8.7.4: ERROR: Cannot install music-assistant because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip is available: 23.0 -> 23.0.1 [notice] To update, run: pip install --upgrade pip 
```

### Additional information

N/A

### What version of Home Assistant Core are your running

Home Assistant 2023.3.0; Supervisor 2023.01.1; Operating System 9.5; Frontend 20230301.0 - latest

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
This is an issue with HA core. MA is incompatible with > HA 2023.2.x 
Downgrade or wait for MA 2.0
https://github.com/music-assistant/hass-music-assistant/issues/1104

**Comment by OzGav** [comment]
Not yet released. Will be another week or so.

**Comment by OzGav** [comment]
Yeah sorry its not publicly available at this time.

**Comment by OzGav** [comment]
Secret is a totally inappropriate word to describe it. Marcel is working on it by himself as well as his actual job. He doesn’t have 36 hours in a day and so has not had time to properly setup the new new repo

**Comment by marcelveldt** [comment]
This project consists of several repos which all together form Music Assistant. The "core" of MA is being rewritten to 2.0 version which shall be released in a beta soon. Nothing secret about it, just multiple repos and branches. Also wondering why it is so important. There's nothing you can do now to get 2.0 working anyway

**Comment by cociweb** [comment]
> This project consists of several repos which all together form Music Assistant. The "core" of MA is being rewritten to 2.0 version which shall be released in a beta soon. Nothing secret about it, just multiple repos and branches. Also wondering why it is so important. There's nothing you can do now to get 2.0 working anyway

Because, I think, the guys would like to (help and) keep it working with the latest Ha Core (on the release day as well) :)
The last 3 Ha Core update made the integration unusable for the first days/weeks.
Eg. I would like to keep the 2023.03 as it is now, but MA<2.0 broke now... I don't see neither where is the dependcy implemented to make a trial fork for myself of the <2.0 version... May, the overwhelming majority of the community are more appreciate the stable and working versions than the new (but instable) features. - which later (after beta release) become stable...
Please don't misunderstood it: what are you doing is incredibly awsome!!!

**Comment by marcelveldt** [comment]
1) Music Assistant (v1.x) uses the databases package for all database access, which is in turn based on SqlAlchemy Core.
2) Home Assistant updated to sqlalchemy 2.0 which is not compatible with the databases package: https://github.com/encode/databases/issues/530

3) Music Assistant 2.0 is in the making for about half a year now and it is partly rewritten. Most important change is that its "core" will be addon/docker based so it will be detached from HA, so we no longer have to suffer from this kind of dependency conflicts. The hSA integration part will just be a "dumb" connector.

4) The v2.0 is not yet in a shape where somebody can test it, please allow me to publish a first beta version.

My wish was to provide another fix/patch release for Music Assistant 1.x for HA 2023.3+ support but as you can read in the linked issue above, that is going to be hard unless someone patches databases for the SQLAlchemy...

**Comment by cociweb** [comment]
Thank you Marcel,
I think it is a very clear and understandable communication: the excuse is reasonable.
Let's hope someone of us has the proper knowledge to provide SQLA2.0 patch. If not, until that, let me wish time for You, and patience for us - without bother of you - to bring us an awesome release again! (Hint: pin the issue as an announcement to minimize the number of the reopens)

Furthermore, let us know, if you can delegate sub-tasks and need further help!

**Comment by financelurker** [comment]
when will the HA integration - for the dumb connectors - be available for V2? I've installed the V2 beta but without any HA integration it seems a little out of place...
