### ISSUE TITLE
MASS fails to load after upgrading HA to 2023.3 (production version)

### ISSUE THREAD

**Issue by FrankJaco** [music-assistant/hass-music-assistant#1115]
### What version of Music Assistant has the issue?

2023.2.1

### The problem

After upgrade the MASS integration fails to load.

Logger: homeassistant.setup
Source: setup.py:205
First occurred: 7:51:21 AM (1 occurrences)
Last logged: 7:51:21 AM

Setup failed for custom integration mass: Requirements for mass not found: ['music-assistant==1.8.7.4'].

### How to reproduce

Upgrade to HA 2023.3 and from that point on MASS is not functional.

### Relevant log output

Logger: homeassistant.setup
Source: setup.py:205
First occurred: 7:51:21 AM (1 occurrences)
Last logged: 7:51:21 AM

Setup failed for custom integration mass: Requirements for mass not found: ['music-assistant==1.8.7.4'].

### Additional information

Perhaps this may be helpful.    My Wyze integration failed in the EXACT SAME WAY as MASS.   The Wyze integration developer was able to provide a fix (workaround) by a modification to its "Manifest.JSON" file.  Perhaps a similar edit would work for MASS?

Here is the change to the WYZE manifest.JSON file...

  "requirements": [
    "git+https://github.com/brg468/wyzeapy.git@update-deps#wyzeapy==0.5.19"
  ],

### What version of Home Assistant Core are your running

2023.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by Oinq** [comment]
How to completely uninstall MA from HA?

**Comment by erkr** [comment]
See https://github.com/music-assistant/hass-music-assistant/issues/1143#issuecomment-1467928564
Hope this help you
Eric

**Comment by Oinq** [comment]
It worked! Thank you!
