### ISSUE TITLE
Setup failed for custom integration mass: Requirements for mass not found

### ISSUE THREAD

**Issue by antoinevandenhurk** [music-assistant/hass-music-assistant#1124]
### What version of Music Assistant has the issue?

2023.2.1

### The problem

After HA release 2023.03.... update my MASS doesn't load anymore and reports the logging below (Relevant log output)

### How to reproduce

After each HA starts

### Relevant log output

Logger: homeassistant.setup
Source: setup.py:205
First occurred: 07:33:01 (1 occurrences)
Last logged: 07:33:01

Setup failed for custom integration mass: Requirements for mass not found: ['music-assistant==1.8.7.4'].

### Additional information

I also can no longer regularly remove MASS from my integration section

### What version of Home Assistant Core are your running

20230309.0 - latest

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Windows

**Comment by OzGav** [comment]
Please look at the pinned post https://github.com/music-assistant/hass-music-assistant/issues/1104
