### ISSUE TITLE
Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

### ISSUE THREAD

**Issue by dobriys** [music-assistant/hass-music-assistant#1125]
### What version of Music Assistant has the issue?

2023.2.1

### The problem

When trying to add integration i have this error -   `Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble`

### How to reproduce

Settings - Add Integration 

### What version of Home Assistant Core are your running

2023.3.3

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
Please see the pinned post https://github.com/music-assistant/hass-music-assistant/issues/1104

**Comment by xteaun** [comment]
Why was this closed? The pinned posted does not offer a solution or am I missing something? :)

**Comment by OzGav** [comment]
The pinned post makes clear that MA V1 is not supported in HA 2023.3.x It also directs you to the beta V2
