### ISSUE TITLE
[2b1] wrong status Chromecast players

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#1129]
### What version of Music Assistant has the issue?

2b1

### The problem

When Chromecast players are streaming external content, eg  from a mobile Spotify app, the state in MA is either idle or off instead off playing. 
Note: The status in HA via the chromecast integration is correct 

### How to reproduce

See above 

### What version of Home Assistant Core are your running

2023.3.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by marcelveldt** [comment]
This is the intended behavior. I have no intention of tracking external playback on players as that makes things way to complicated. MA only tracks its own playback to players and ignores other playback. That is the scope of MA.

**Comment by marcelveldt** [comment]
If you want to track state of all "controllers" to a player you can use HA

**Comment by erkr** [comment]
Hmm that is pity, I planned to de-install the existing player integrations, once MA gets integrated with HA. For automations I need to know the player status

**Comment by erkr** [comment]
Plz reconsider, or check more opinions. It is existing MA1 functionality
