### ISSUE TITLE
[2b1] Not possible to select advanced settings

### ISSUE THREAD

**Issue by DjDenmark** [music-assistant/hass-music-assistant#1131]
### What version of Music Assistant has the issue?

2.0.0b1

### The problem

I have a clean install of Music Assistant add-on (not installed via HACS), and I cannot find the advanced settings menu from the web-UI. I want to access the advanced settings to enable a new mass media player. 

### How to reproduce

Clean install of Music Assistant addon via the repo. Going to settings menu

### What version of Home Assistant Core are your running

2023.3.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by marcelveldt** [comment]
Players are auto detected. No need to add one. See all the beta instructions we provided on discord.

**Comment by DjDenmark** [comment]
Wow you are quick! :) 
My media players are auto detected, so that is not the issue. I want to create a MA media player to utilize TTS while media is playing.

**Comment by gieljnssns** [comment]
I think this isn't possible right now. You have to wait until the integration with HA is possible. 
https://discord.com/channels/753947050995089438/1083284385974980728/1084043330364657755

**Comment by DjDenmark** [comment]
Ok, I will wait then. Thanks for the link and responses! Should I close this thread as not planned (stale) then? I'm new to github and want to make sure I don't ruin your systems.

**Comment by OzGav** [comment]
Yeah I’ll close this as it is expected behaviour currently but what you have requested is planned
