### ISSUE TITLE
Unable to use the "Browse" function of MA

### ISSUE THREAD

**Issue by Electronlibre2012** [music-assistant/hass-music-assistant#1133]
### What version of Music Assistant has the issue?

2.0.0b1

### The problem

Even if i see all my music in Artists, Albums and Tracks, if i go to "Browse" i just see a "Local FileSystem" folder and anything else.

If i click on "Local FileSystem" nothing append and all my music is already sync.

### How to reproduce

dont know sorry.

I cant delete the HACS version first because it ask to delete the integration first and i cant delete it even with a restart of HA.

So first i stop the AddOn, then i delete all the entities in the integration, then go to HACS and ignore the warning and delete the HACS part. Then restart HA, and delete the integration, now it works. Then restart and start the AddOn MA.

### What version of Home Assistant Core are your running

2023.3.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Known issue https://github.com/orgs/music-assistant/projects/2/views/1

**Comment by OzGav** [comment]
Also see here https://github.com/music-assistant/hass-music-assistant/issues/1106

**Comment by Electronlibre2012** [comment]
Thanks @OzGav 

but for the "Browse" problem?

**Comment by Electronlibre2012** [comment]
i delete addOn, restart HA, install again, same problem, no "Browse" function working

any idea please?

**Comment by gieljnssns** [comment]
https://github.com/orgs/music-assistant/projects/2/views/1?pane=issue&itemId=22570112

**Comment by Electronlibre2012** [comment]
thanks!
