### ISSUE TITLE
Install aborted pip outdated

### ISSUE THREAD

**Issue by RudyReindeer** [music-assistant/hass-music-assistant#1137]
### What version of Music Assistant has the issue?

2023.2.1

### The problem

The install aborts with the error message:
Der Konfigurationsfluss konnte nicht geladen werden: 500 Internal Server Error Server got itself in trouble

### How to reproduce

Downlaod and install the newest version.

### Relevant log output

Logger: homeassistant.util.package
Source: util/package.py:107
First occurred: 18:35:17 (3 occurrences)
Last logged: 18:35:42

Unable to install package music-assistant==1.8.7.4: ERROR: Cannot install music-assistant because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip is available: 23.0 -> 23.0.1 [notice] To update, run: pip install --upgrade pip

### Additional information

I am happy to test / support, as far as possible.
Auf Deutsch or in English ;-)

### What version of Home Assistant Core are your running

2023.3.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by heinzma** [comment]
https://github.com/music-assistant/hass-music-assistant/issues/1104
MA 2023.2.1is not compatible with HA 2023.3.x. 
You have to downgrade HA or try the MA 2 beta. Take a look at the discord channel for that.

**Comment by RudyReindeer** [comment]
Thanks for the fas feedback, I overlooked this.

**Comment by RudyReindeer** [comment]
See above.
