### ISSUE TITLE
Just 19 artists detected

### ISSUE THREAD

**Issue by AvdWerfhorst** [music-assistant/hass-music-assistant#114]
I only have local files. Folders with flac files. (Structure: /Artist/Album). These flac files, are tagged with the name of the artist, name of the track, album, number of the track, year of publishing, etc.

Of all the folders I have, only 19 artists are detected. No albums, no songs in the default view. If I zoom on the artist, I see some tracks in the album view, but only with the album name, instead of the track title.

![FolderViewMedia](https://user-images.githubusercontent.com/35181252/167631548-4d0b3e1e-6a42-4971-8821-4275fa77905d.PNG)
![DetectedFirstScreen](https://user-images.githubusercontent.com/35181252/167631609-da827ac9-fc9c-4a67-8a10-e901de43b257.PNG)
![Detected Artists](https://user-images.githubusercontent.com/35181252/167631633-83bb27e7-654b-4149-93da-0fdb9c9d1ec9.PNG)
![Toptracks](https://user-images.githubusercontent.com/35181252/167631656-4eed1282-8efd-4788-b389-4dbd384e7b3e.PNG)
![Albums](https://user-images.githubusercontent.com/35181252/167631663-91a4b181-f59b-4ae1-9a65-d0cceda51e78.PNG)

**Comment by marcelveldt** [comment]
Yes, I'm currently working on that and hope to provide a new version later today
see also #105
