### ISSUE TITLE
MA2: SMB Scanning also scans Video files (mp4, avi etc)

### ISSUE THREAD

**Issue by icornish72** [music-assistant/hass-music-assistant#1140]
### What version of Music Assistant has the issue?

2.0.0b2

### The problem

MA2: SMB Scanning also scans Video files (mp4, avi etc). Prior version never did this.
This means its scanning my entire multimedia folder, which just happens to include several thousand snippet movie files.

### How to reproduce

Set up SMB to point to SMB folder with movie file in

### What version of Home Assistant Core are your running

2022.3.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by marcelveldt** [comment]
I think that is because of mp4 because that is used as both audio and video extension.
Make sure that you add a subfolder to MA only containing the music files.

So instead of e.g. /media use /media/music

or if you're using smb:

smb://ipaddress/media/music

**Comment by OzGav** [comment]
Please follow Marcels advice and restructure your music folders. We recommend following the guidance here https://kodi.wiki/view/Music_tagging
