### ISSUE TITLE
MUSIC ASSISTANT WILL NOT WORK WITH HOME ASSISTANT 2023.3

### ISSUE THREAD

**Issue by marcelveldt** [music-assistant/hass-music-assistant#1143]
## IMPORTANT NOTICE

Music Assistant is NOT compatible with Home Assistant release 2023.3 (and upwards) due to an unfortunate compatibility issue. At this time it is not possible to fix this issue I'm afraid.

Because a complete overhaul of Music Assistant was already in the making, version 2.0, we have decided to already release an early version of the 2.0 beta so people can get going from there. Follow us on discord to get the latest news about the beta and give and discuss feedback about it or follow progress and/on the backlog:  https://github.com/orgs/music-assistant/projects/2

**What to do next ?**

Please postpone your upgrade to Home Assistant 2023.3
OR
Live a few weeks without Music Assistant

Thanks for your understanding!

**Comment by marcelveldt** [comment]
Following up: It was my intention to still provide fix updates for the current (v1) version of Music Assistant as it is on HACS but unfortunately the upstream dependency issue is bad enough to make it near impossible, hence my decision to move all development focus to the 2.0 version. It is not a bad intention but just bad luck. Sad to hear that some people seem to think otherwise.

**Comment by marcelveldt** [comment]
The new version of Music Assistant will run as a standalone application. The reason for this is exactly why it broke now, you can not have two captains on one ship. Both Home Assistant and Music Assistant are very large and complicated projects and it was a very bad idea of me in the first place to run the "core" of Music Assistant within Home Assistant itself.

The 2.0 approach is that the Music Assistant core runs on its own and the Home Assistant integration is just a connector, making it resilient to the kind of dependency issues that killed the v1 version.

For some this may sound as bad news but it is actually very good news because now we can have a much more fine grained control over the players and playback. You already see the first results of this in the early 2.0 betas: Full metadata is displayed.

There is still a lot of work to do on the 2.0 code but his feels like a very strong foundation to continue and make it into something awesome.

### Running the Music Assistant Server

**Preferred method: Home Assistant Add-on**
By far the most convenient way to run the Music Assistant Server is to install the Music Assistant Add-on:

Add the Music Assistant repository to your Home Assistant instance.
Install the Music Assistant add-on.
[Add repository on my Home Assistant](https://github.com/music-assistant/home-assistant-addon)

**Alternative method: Docker image**
An alternative way to run the Music Assistant server is by running the docker image:

```
docker run --network host ghcr.io/music-assistant/server:2.0.0b4
```

Replace the 2.0.0b4 tag with the correct version. You must run the docker container with host network mode and the data volume is /data. If you want access to your local music files from within MA, make sure to also mount that, e.g. /media. Note that accessing remote (SMB) shares can be done from within MA itself using the SMB File provider.

**Comment by marcelveldt** [comment]
**I have MA v1 installed and now I can no longer remove it ?!**

If you already upgraded to HA 2023.3.x you have two options:

1) Manually remove MA from the "core.config_entries" file within the .storage subfolder of HA config.
2) Restore your backup of HA 2023.2, uninstall MA and upgrade to HA 2023.3 again.

**Comment by marcelveldt** [comment]
**BETA software is not yet polished**

Please understand that we rushed the release of the early beta due to the major dependency conflict with HA 2023.3.x so not all features are ready. Most important, at this time we only have the server component ready, the actual "core" of Music Assistant and we're fixing the last bugs to get that in a stable state. After that we will focus on having the Music Assistant integration working again so you can control your music from within HA. Ultimate goal is to just submit the integration part as an official component for HA but we might reinstate the HACS version to gather some beta feedback first and/or to get people started sooner.

Follow progress of the new v2.0 version here: 
https://github.com/orgs/music-assistant/projects/2/views/1

**Comment by andrewigali** [comment]
I tried but doesn't work. :(

Raspberry Pi 4 rpi4-64 Argon One
Home Assistant 2023.1.7
Supervisor 2023.03.1
Operating System 9.5
Frontend 20230110.0 - latest

1. Deleted old (HACS) Music Assistant on Settings/ Devices & Services/ Integrations.
2. Deleted source on HACS.
3. Restarted Home Assistant.
3. Added this link: https://github.com/music-assistant/home-assistant-addon
4. Refreshed site.
5. Searched and installed Music Assistant Beta (2.0.0b5).
6. Clicked the Start button, but not changed on Runing and green color point, it is still red color.
7. Checked the Music Assistant Log:
2023-03-14 21:50:16 INFO  music_assistant  -- Starting Music Assistant Server (a473959f8ad94c0e82xxxxxxxxxxaad8) on port: 8095 - autodetected IP-address: 192.xxx.x.xxx
2023-03-14 21:50:17 INFO  music_assistant.streams  -- Started stream controller (using ffmpeg version 4.3.5 with libsoxr support)
2023-03-14 21:50:49 INFO  music_assistant  -- Loaded metadata provider MusicBrainz Metadata provider
2023-03-14 21:50:49 INFO  music_assistant  -- Loaded plugin provider Frontend
2023-03-14 21:50:49 INFO  music_assistant  -- Loaded metadata provider TheAudioDB Metadata provider
2023-03-14 21:50:49 INFO  music_assistant  -- Loaded player provider Chromecast
2023-03-14 21:50:49 INFO  music_assistant  -- Loaded music provider URL
2023-03-14 21:50:49 INFO  music_assistant  -- Loaded player provider UPnP/DLNA Player provider
2023-03-14 21:50:49 INFO  music_assistant  -- Loaded player provider SONOS
2023-03-14 21:50:49 INFO  music_assistant.metadata  -- Start scan for missing artist metadata
2023-03-14 21:50:49 INFO  music_assistant.metadata  -- Finished scan for missing artist metadata
2023-03-14 21:50:49 INFO  music_assistant.providers.slimproto  -- Starting SLIMProto server on port 3483
2023-03-14 21:50:49 INFO  music_assistant  -- Loaded player provider Slimproto
2023-03-14 21:50:49 INFO  music_assistant  -- Loaded plugin provider JSON-RPC API
2023-03-14 21:50:49 INFO  music_assistant  -- Loaded metadata provider fanart.tv Metadata provider
2023-03-14 21:50:49 INFO  music_assistant  -- Loaded player provider Airplay
2023-03-14 21:50:50 INFO  music_assistant.players  -- Player registered: exxxxxxa-f6f3-a42e-c27a-1xxxxxxxxxx8/Kitchen speaker
2023-03-14 21:50:50 INFO  music_assistant.players  -- Player registered: 3xxxxxxd-3184-47eb-a1a6-3xxxxxxxxxx8/All speakers
2023-03-14 21:50:59 INFO  music_assistant.players  -- Player registered: 5xxxxxxc-dbba-6069-2b1b-2xxxxxxxxxxa/Bathroom speaker
2023-03-14 21:51:36 INFO  music_assistant.players  -- Player registered: 4xxxxxx6-8ace-0913-4623-cxxxxxxxxxxd/Bedroom speaker


The speakers are Google Nest Audio.
But doesn't work. :(

**Comment by OzGav** [comment]
@andrewigali why do you keep hijacking these threads when I have told you to open a new issue?

**Comment by andrewigali** [comment]
> @andrewigali why do you keep hijacking these threads when I have told you to open a new issue?

Because i just a little bit speak in English and i don't use the github/ issue but now tried.
Please delete this comment.

**Comment by szemod** [comment]
Hello Marcel, 
I try to switchover to version 2.0.0b and I faced with 2 issues:
1. After the addon instaled Music Assistant is inaccessable via the link within the addon, if Home Assistant access set it up with https via duckdns, like: https://mydns.duckdns.org:5643/d5369777_music_assistant_beta/dashboard (dns and port is just example)
Using the IP is accessable otherwise, but only http: http://192.168.1.84:8096/#/
2. The other issue is, that some players automaticaly recognised on my network, but the one I using, the default mpd.music_player unfortunately not among them. In 1.x during the initial configuration I can select what players I want to use, but in 2.0 there is no such function to add a player.
Otherwise, I really like the Music assistant, at the moment I haven't even updated HA because of this and stil using 1.x version of Music assistant. Congratulations on your work!

**Comment by OzGav** [comment]
@szemod please confirm that before you tried use use v2 that you disabled the v1 integration in HA SETTINGS?

**Comment by OzGav** [comment]
Someone asked a similar question in discord. This is the response 

> Heya, is adding mpd as a player in the feature list of V2. I use snapcast and that works fine with mpd.


> Well, it will be if we allow HA players again as players for MA.... So i'd like to have some of the most popular platforms native in MA and all other can be integrated by using the HA connector.

So you will have to wait a little while for this to be implemented. Sorry for the inconvenience.

**Comment by szemod** [comment]
> Someone asked a similar question in discord. This is the response
> 
> > Heya, is adding mpd as a player in the feature list of V2. I use snapcast and that works fine with mpd.
> 
> > Well, it will be if we allow HA players again as players for MA.... So i'd like to have some of the most popular platforms native in MA and all other can be integrated by using the HA connector.
> 
> So you will have to wait a little while for this to be implemented. Sorry for the inconvenience.

Many thanks for your reply! Then I'll need wait until is implemented. I have one more question: The global search field is missing on the HOME page of v2. Is that also planned in the future?

**Comment by OzGav** [comment]
That is currently being worked on https://github.com/orgs/music-assistant/projects/2/views/1

**Comment by andrewigali** [comment]
I share my experience.

HACS version MA must be disabled in the Integrations menu.
If you succeeded in installing the MA v2 extension, but it does not start, you must shut down the machine within the HA system and then turn it on again. It is likely that something was stuck/crashed. You should then be able to start and the webUI interface should be available.
Tested:
Raspberry4 rpi-64 Argon One M.2
HAOS 2023.1.7

Currently, there are no entities with the MA v2 extension, automation/call service options are not yet available. For those who care, continue to use the HACS version.
Last working version: HAOS 2023.2.5 and HACS MA 2023.2.1
HAOS 2023.1.7 and HACS MA 2022.12.1 will not work!
So you definitely need to update to HAOS 2023.2.x.
If you are already running HAOS 2023.3.x or later, you must first restore the previously created backup.
If no HAOS 2023.2.x, only from the previous one (e.g. [2023.1.x, then it must be reloaded.
Then install Terminal & SSH in the Settings/Addons menu. Start it and type the following:
 if core update --version 2023.2.5 then enter.
(2 dashes)
To keep the system stable, use the above command only when upgrading from a previous version to a larger version! The downgrade is only from a backup!
Tested:
Raspberry4 rpi-64 Argon One M.2
From HAOS 2023.1.7 to HAOS [2023.2.5
MA 2023.2.1 (HACS version)



We hope it will exit the beta state as soon as possible, the new MA v2 extension will also include entities, automatisms/call services, dark theme mode. :)

Also, I recommend that there should be a site on the github site about what/what the given MA v2 version update contains, so that the average user can easily see the changes and the development.

**Comment by OzGav** [comment]
> Also, I recommend that there should be a site on the github site about what/what the given MA v2 version update contains, so that the average user can easily see the changes and the development.

Have a look at the link immediately above your post. That shows what is being worked on and what is coming up.

**Comment by andrewigali** [comment]
> > Also, I recommend that there should be a site on the github site about what/what the given MA v2 version update contains, so that the average user can easily see the changes and the development.
> 
> Have a look at the link immediately above your post. That shows what is being worked on and what is coming up. Also you can join the Discord channel which has lots of discussions about what is happening with the project.

Ok, that site is good, but I think it would be better if we could get information about the given version, what has changed and what has been added.
[Example](https://github.com/home-assistant/core/releases)

**Comment by OzGav** [comment]
Yes Marcel does that for full releases for during this beta development phase we are running with the backlog.

**Comment by thermosiphonas** [comment]
Does Browse work in v2.0 or is it something that will be added later on? Clicking on anything does nothing

Thank you

**Comment by OzGav** [comment]
B8 fixed this

**Comment by thermosiphonas** [comment]
Oh! thanks! I hadn't noticed that it had updates!

**Comment by marcelveldt** [comment]
> Oh! thanks! I hadn't noticed that it had updates!

We release a new beta almost every day with bugfixes and the final (missing) features being added.
You can use the backlog to follow along what is being worked on.

When 2.0 is being released there will be a full writeup of the new features and such.
At this point you will have to follow the backlog or join discord to stay updated.

And of course as @andrewigali pointed out, if you just want a stable setup and not toy with beta versions, just stick with the V1 version for now which works rock solid on HA 2023.2.x.

**Comment by marcelveldt** [comment]
@thermosiphonas in Music Assistant v2.0 you no longer use that workaround with mounting a share but instead you pick the "SMB mediaprovider" for direct access to your remote share

**Comment by marcelveldt** [comment]
> I have a very large library (over 950GB and 120,000 files) and SMB mediaprovider gets stuck all the time. I cannot enter a folder and see the mp3s inside it

We're working win improving the smb provider. I have a new testversion ready tomorrow which should improve things. Are the files hosted on a Windows server or on a (linux) NAS ? If its a powerful NAS you could also consider to run the Music Assistant server directly on the NAS so it has local access to the files (super fast)

**Comment by thermosiphonas** [comment]
I have the files hosted on a Windows server in which Home Assistant is running on VirtualBox

**Comment by OzGav** [comment]
There is a known issue with windows shares that is currently being worked on

**Comment by Surgical17** [comment]
> You can also just keep the (now not working) Music Assistant integration installed if you want and upgrade it later to the updated integration for 2.0. It just looks a bit messy to have a malfunctioning integration but it can't do any harm.

I see V2 beta is available as a add-on. So what will be the easiest way to migrate over? Is there any documentation for this?

**Comment by OzGav** [comment]
The instructions are above. Your database will be recreated with the new version so there is nothing to be migrated. Note V2 is still in beta (but working pretty well for most)

**Comment by 80081** [comment]
Thumbs up from me, coming from LMS/Spotty, where there is an issue with LMS and or the Spotify integration, it never worked properly for me and made it almost unusable.  I didn't even know about this project until about a week ago, loaded MA via docker and it's working great so far.  For the first time I can actually listen to stuff on Spotify in every room, without having to constantly intervene to keep it playing.  There are some oddities, some of the controls and UI etc aren't as polished as they could/will be, but for a beta it pretty much does everything I could ask of it, so thank you guys, it already looks like it's going to be a really good solution.

**Comment by 80081** [comment]
Is there somewhere we should post issues to?  I realise this is beta and you dont want spamming with tonnes of things that are already on the roadmap, but there are a few almost trivial little issues I've come across that may or may not be known.

As a for instance when syncing 1 or more players that have different volume levels before syncing, the group volume slider gets confused, if I change each individual player so they match, the group slider works as expected.

**Comment by andrewigali** [comment]
I would like to perform operations in automation.
Which version is expected to have automation settings?
In the link below, which target list contains which one?
[https://github.com/orgs/music-assistant/projects/2](https://github.com/orgs/music-assistant/projects/2) 
Sorry, I'm not good at English. :(

**Comment by OzGav** [comment]
If you have HA >= 2023.3.x installed then you can only use MA V2 BETA. Automations will be available in that in a few weeks.

**Comment by andrewigali** [comment]
> If you have HA >= 2023.3.x installed then you can only use MA V2 BETA. Automations will be available in that in a few weeks.

Yes, I'm still using HA 2023.2.1 and HACS Music Assistant.  It's just the lack of automation that keeps me from upgrading the HA system and switching to the Music Assistant plugin.
That's why I asked which target list I should look at, check, so that I know that I can update and change.
I'm really glad that Music Assistant exists and I hope that a stable version will be released soon. :)

**Comment by OzGav** [comment]
Ok please open a discussion and ask for some help explaining what you want to do and what you have tried so far.

**Comment by vjmaz** [comment]
Dear Marcel will version 2.0 work with new HA 2023.3 onwards , as i had many scripts to say notification then play the music again ? .... I hope it gets sorted all the best Marcel it was awesome while it lasted :)

**Comment by OzGav** [comment]
Version 2 already works with the latest versions of HA. The HA integration to allow automations is a couple of weeks away.

**Comment by pejotigrek** [comment]
> **Alternative method: Docker image** An alternative way to run the Music Assistant server is by running the docker image:
> 
> ```
> docker run --network host ghcr.io/music-assistant/server
> ```
> 
> You must run the docker container with host network mode and the data volume is /data. If you want access to your local music files from within MA, make sure to also mount that, e.g. /media. Note that accessing remote (SMB) shares can be done from within MA itself using the SMB File provider.

I am using HA Container installation, so obviously I've tried the docker version [both by the docker run line you've provided, and by docker-compose that I made].
how can I access the Music Assistant dashboard? I mean - can I access it without HA?
I've tried IP:8095 or IP:8096 [ports that I've found here or in the logs ;)] but with no luck. I've tried to forward those ports to the container but also didn't worked.
it's possible that I'm missing something, but am I? ;)

**Comment by marcelveldt** [comment]
> I am using HA Container installation, so obviously I've tried the docker version [both by the docker run line you've provided, and by docker-compose that I made]. how can I access the Music Assistant dashboard? I mean - can I access it without HA? I've tried IP:8095 or IP:8096 [ports that I've found here or in the logs ;)] but with no luck. I've tried to forward those ports to the container but also didn't worked. it's possible that I'm missing something, but am I? ;)

If you used host network mode (as required in the docs) you can access the local webserver of the MA server on http://ipofyourdockerhost:8095

**Comment by pejotigrek** [comment]
I've tried that [that's what I meant by IP:8095] - but nothing is showing up.

**Comment by marcelveldt** [comment]
> I've tried that [that's what I meant by IP:8095] - but nothing is showing up.

it really should work (look in the log if it started on port 8095 because it auto picks another port if that port is already taken). Also make sure to use HTTP and not HTTPS and maybe try another browser. 100s of people use it this way.

**Comment by pejotigrek** [comment]
log was legit. so I've restarted my docker, and to be sure - deleted browser's cache one more time and it clicked. seems it was some cache problem. thanks!

**Comment by AleksandrBraun** [comment]
I have been and remain a fan of Music Assistant for a long time.
I was disappointed to learn that the new version of Home Assistant broke the correct operation of Music Assistant.
But I believe that such an advanced product will not be left without a continuation.
I regularly monitor your tremendous work on solving this problem.
And I was pleased to find that the BETA version is already available for testing.
I like the new integration design, it's more modern and clear. New services have been added. I connected my favorite radio stations and even YouTube Music without any problems.
The only thing missing from the previous integration version is support for ESPHome i2s Media Player. Maybe I did not fully understand, but I could not see these players in the list of available in Music Assistant.
Please tell me, did I disable something or are there other reasons for their absence?
Thank you very much for your work.

**Comment by OzGav** [comment]
No you haven’t missed anything. The ESP devices are not yet supported. Go to the player provider poll and express your interest in that over there

**Comment by AleksandrBraun** [comment]
Did I understand correctly that support for ESPHome Player has ended due to changes in ESPHome?
On the side of Music Assistant, everything remains the same?

**Comment by OzGav** [comment]
No MA V2 needs to have support added for those devices. Having said that when the HA.integration is written in a few weeks then all HA media player entities will be exposed

**Comment by AleksandrBraun** [comment]
Thanks. Wait for update.
Good job!

**Comment by rvandet** [comment]
May be it is a bug, i do not know. Some Players remain in the list when selecting a target audio device. But these playes have been deleted from the player list. Don know why they show up. Suggestion: it would also be nice if offline devices and devices that are "off", do not show up.

![image](https://user-images.githubusercontent.com/11903294/236675830-5480e489-4ea0-4a64-a42f-f0837353477e.png)

**Comment by OzGav** [comment]
Please look for similar or identical existing issues https://github.com/music-assistant/hass-music-assistant/issues/1180 and don't keep adding to this topic with new or unrelated info, start a new discussion or issue.

**Comment by J0sss** [comment]
Hi all! I have been following the progress here with some interest, and I am trying to install the MA v2 add on using the instructions I found. I have managed to get the MA in my add on store, but I can't install it as it reports my processor or OS is not supported. I am using an RPi 2 model B, so it should have a ARM Cortex-A7 processor. My OS is the latest, 10.1 currently. Am I out of luck that my device is too old, or will it be supported at some time in the future or could something else be wrong?

**Comment by erkr** [comment]
1 GB ram won't be enough either. It works on my test setup using a pi 3b with 1 GB and that just works, as long I don't add other add-on's or many extra integrations

**Comment by J0sss** [comment]
Ok, good to know, thank you for your replies! Time to invest a little bit again..

**Comment by marcelveldt** [comment]
FYI: Music Assistant 2023.6.0 beta 0 is now available on HACS which is the rewritten Home Assistant integration that talks to Music Assistant Server 2.0.

**Comment by rvandet** [comment]
I get a "List index out of range", when
i choose an Album (or radio station) and klick the three buttons (Menu)
then choose "Start radio".
Happens since the latest HA update.

**Comment by OzGav** [comment]
@rvandet You are posting in a closed issue from years ago? Firstly having the start radio option against a radio station is a bug. that will be removed. Next the error message is poor. If you look in your logs you will probably find that "the provider library does not support dynamic tracks". So you need to ensure you have a streaming provider that supports dynamic tracks
