### ISSUE TITLE
Unable to install package music-assistant==1.8.7.4

### ISSUE THREAD

**Issue by r3naissance** [music-assistant/hass-music-assistant#1145]
### What version of Music Assistant has the issue?

2023.2.1

### The problem

Logger: homeassistant.util.package
Source: util/package.py:107
First occurred: 11:04:28 (3 occurrences)
Last logged: 11:04:41

Unable to install package music-assistant==1.8.7.4: ERROR: Cannot install music-assistant because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip is available: 23.0 -> 23.0.1 [notice] To update, run: pip install --upgrade pip

### How to reproduce

Follow the installation steps on the latest version of HA (my specific versions are below). During the adding of the integration a 500 error is thrown on the above logs show there is a dependency conflict.

```
Home Assistant 2023.3.4
Supervisor 2023.03.1
Operating System 9.5
Frontend 20230309.0 - latest
```

### What version of Home Assistant Core are your running

2023.3.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by heinzma** [comment]
please have a look at the pinned issue: https://github.com/music-assistant/hass-music-assistant/issues/1143
