### ISSUE TITLE
Doesn' t work HACS Music Assistant on restored HAOS

### ISSUE THREAD

**Issue by andrewigali** [music-assistant/hass-music-assistant#1146]
### What version of Music Assistant has the issue?

2022.12.1

### The problem

Doesn' t work HACS Music Assistant v2022.12.1 on restored HAOS 2023.1.7.

Raspberry Pi 4 rpi4-64 Argon One
Home Assistant OS 2023.1.7
Supervisor 2023.03.1
Operating System 9.5
Frontend 20230110.0 - latest

It used to work fine, but there may have been some error in the acces.

Can it be resolved that until the HA Addon version is stabilized, the HACS version (v2022.12.1) can still be used (e.g. with HAOS 2023.1.7)?

### How to reproduce

I restored my previous backup (HAOS 2023.1.7), which still includes the HACS Music Assistant integration (v2022.12.1)
I get the following error message:

### Relevant log output

Logger: homeassistant.setup
Source: setup.py:202
First occurred: 7:54:07 PM (1 occurrences)
Last logged: 7:54:07 PM

Setup failed for custom integration mass: Requirements for mass not found: ['git+https://github.com/music-assistant/databases@fix-breaking-sqlalchemy-cursor-changes#databases==0.6.3'].

Full log:
2023-03-15 19:52:44.743 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration mass which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

2023-03-15 19:54:07.531 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration mass: Requirements for mass not found: ['git+https://github.com/music-assistant/databases@fix-breaking-sqlalchemy-cursor-changes#databases==0.6.3'].

![Screenshot_2023-03-15-20-01-22-371_io homeassistant companion android](https://user-images.githubusercontent.com/73789218/225431566-ca6abe2f-84c2-4c2f-a78a-f24e890ca096.jpg)

![Screenshot_2023-03-15-20-05-21-533_io homeassistant companion android](https://user-images.githubusercontent.com/73789218/225431687-58625f99-d0de-4c8c-bc6c-98158e073b4f.jpg)

### What version of Home Assistant Core are your running

2023.1.7

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
It looks like no. It would appear that the restore is not reverting the version of sqlalchemy that is causing the problem. Just to confirm this is a problem with HA and cannot be resolved by the MA project. Sorry.

**Comment by marcelveldt** [comment]
This is strange, restoring the backup should work. We actually had a patch release in january/february.
Are you sure you restored the right backup ? Maybe there is an update waiting in HACS you can install for MA ?

You should be able to run Home Assistant 2023.2.x with Music Assistant 2023.2.1

**Comment by andrewigali** [comment]
> This is strange, restoring the backup should work. We actually had a patch release in january/february. Are you sure you restored the right backup ? Maybe there is an update waiting in HACS you can install for MA ?
> 
> You should be able to run Home Assistant 2023.2.x with Music Assistant 2023.2.1
When reset, HAOS 1.7.2023 and HACS MA 12.1.2022 were loaded.
Unfortunately, MA no longer works, because as soon as HA is available during reset, it gives the above error.
If I delete the MA integration and in HACS, and then want to install it again, it gives the above error.
It used to work until I updated from 1/7/2023 to 3/3/2023.  I restore from backup to no avail.
Currently, HA 2023.1.7 and HACS version 2022.12.1 are up, but they no longer work.
But the addon v2beta doesn't work even with an update.
[https://github.com/music-assistant/hass-music-assistant/issues/1144](https://github.com/music-assistant/hass-music-assistant/issues/1144)

**Comment by OzGav** [comment]
OP advised this was resolved by rebooting host.
