### ISSUE TITLE
Sonos players disappear from the player section

### ISSUE THREAD

**Issue by MarvinSchenkel** [music-assistant/hass-music-assistant#1150]
### What version of Music Assistant has the issue?

MA2 Beta 7

### The problem

Sonos native players do not show up in the bottom-right player section of the UI. It seems to only affect Sonos players that are part of a larger group, e.g. two Sonos Ones in a stereo pair or an Arc + surrounds + sub. The individual uPNP and DLNA players for those speakers DO show up.

### How to reproduce

NA

### Relevant log output

N/A

### What version of Home Assistant Core are your running

NA

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Alternative

**Comment by MarvinSchenkel** [comment]
They appear as "+3" and "+1" in my player list:
<img width="556" alt="image" src="https://user-images.githubusercontent.com/17671719/226709999-dbb285e4-b2ad-4a72-935f-10c5b0709bae.png">

**Comment by marcelveldt** [comment]
fixed in beta16
