### ISSUE TITLE
[MA2] Unable to add Windows SMB shares

### ISSUE THREAD

**Issue by gaussey** [music-assistant/hass-music-assistant#1155]
### What version of Music Assistant has the issue?

2.0.0b10

### The problem

Unable to add a Windows SMB share.

### How to reproduce

adding network IP address, share name, folder name along with username and password
In the form :
![BCD19CBC-2AA4-4F60-92D7-311954091779](https://user-images.githubusercontent.com/1004313/226309186-c9d3b719-557b-4a83-a456-917274d90d22.png)

I’ve tried using the host name, adding // before the ip address, adding hostname before the username (host/username)

### Relevant log output

  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/filesystem_smb/__init__.py", line 166, in _get_smb_connection
    async with AsyncSMB(
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/filesystem_smb/helpers.py", line 116, in __aenter__
    await self.connect()
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/filesystem_smb/helpers.py", line 111, in connect
    raise LoginFailed(f"SMB Connect failed to {self._remote_name}") from exc
music_assistant.common.models.errors.LoginFailed: SMB Connect failed to 192.168.0.xx

[ip address edited]

### Additional information

I’m accessing these shares from multiple different computers and another HomeAssistant add-on (Samba backup) using the same credentials with no issues.

### What version of Home Assistant Core are your running

2023.3.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by infotechjrf** [comment]
@gaussey ; Just saying, but is your Shared Folder really "E" ? To me it looks like your trying to use a Mapped Drive letter as you would in Windows. If so, there's no need to... Simply enter your path directly using the actual shared folder.

**Comment by marcelveldt** [comment]
If you want to add a Windows SMB share you need to enter the dns name instead of IP, at least that is what somebody else reported.

**Comment by gaussey** [comment]
> If you want to add a Windows SMB share you need to enter the dns name instead of IP, at least that is what somebody else reported.

Tried, for about an hour, multiple combinations, every upper case and lowercase version, with slashes and no slashes.

**Comment by marcelveldt** [comment]
We have another report of a user saying that connecting to Windows is not possible. So far I have only tested with linux samba (as I have no Windows here). I'll have to figure out what's wrong. We're using the pretty common pysmb library, which is a bit aged but used by many projects. 

Did you try the full fqdn ? So something like yourhostname.local or something alike ?

I'll see of I can somehow setup a windows box in a VM or something.

**Comment by gaussey** [comment]
> We have another report of a user saying that connecting to Windows is not possible. So far I have only tested with linux samba (as I have no Windows here). I'll have to figure out what's wrong. We're using the pretty common pysmb library, which is a bit aged but used by many projects.
> 
> Did you try the full fqdn ? So something like yourhostname.local or something alike ?
> 
> I'll see of I can somehow setup a windows box in a VM or something.

hostname.local makes no difference.

**Comment by gaussey** [comment]
> Also ensure that you are at least using SMB v2 on your server.

SMBv2 is default on Windows 10 now, I’ve temporarily turned on SMBv1 in case that was the issue.


For what it’s worth this was my mount comment in HomeAssistant that worked fine for mounting the share 👍 
mount_emusic: mkdir -p /media/emusic;mount -t cifs -o vers=3.0,noserverino,username=username,password=pass,domain=WORKGROUP //192.168.0.xx/E/music /media/emusic

**Comment by infotechjrf** [comment]
Might be worth to try disabling SMBv2/v3 encryption feature to test ; https://learn.microsoft.com/en-us/troubleshoot/windows-server/networking/reduced-performance-after-smb-encryption-signing

Don't forget to reboot your SMB Server and HA Host before re-attempting connection to SMB Provider.

**Comment by RJ-Make** [comment]
I'm the other Windows SMB user that has been effected by the changes introduced in b7>. :-)  I was going crazy at first just getting connected to my share. I finally sorted that out (had to use DNS over IP). and un-tic the TCP option but then found out the sync would die (connection failures) after a few seconds presumably from hitting some Windows SMB connection limit. 

Looks like we are in the same boat, You grab the left oare and I'll grab the right...

**Comment by marcelveldt** [comment]
Good news as I think I fixed this by switching to another smb library.
Beta 16 will be available soon (within a few hours) so please give that a proper test, thanks!
