### ISSUE TITLE
Playbook on non-Apple AirPlay devices

### ISSUE THREAD

**Issue by jdelker** [music-assistant/hass-music-assistant#1158]
I would like to stream to my AirPlay-capable receiver (Yamaha RX-V475 with AirPlay v1) but can't find a way to achieve this.

From a post by @postlund in https://github.com/music-assistant/hass-music-assistant/discussions/438#discussioncomment-3031159_
I understand that there is currently a filter in place, which just hides non-Apple devices:

> The filter only applies to discovery though, so it should be possible to add a device manually via IP (assuming the device support AirPlay v1). The streaming support is a bit unstable as it's very early in the development process. Especially when streaming from a remote source, e.g. via https (which is used by TTS) it will likely fail in a lot of cases. There's a very little buffer and pyatv does not handle buffer underruns very good.

I found no reference how such devices could be added manually in HASS.
Any advice how to do that?

**Comment by marcelveldt** [comment]
This will only work with Music Assistant v2.0 which is in beta currently.

**Comment by OzGav** [comment]
Hi @jdelker I will close this soon as Marcel has explained he situation unless you need more info.
