### ISSUE TITLE
Directory exclude on the local filesystem/ SMB share connection for v2 Music Assistant

### ISSUE THREAD

**Issue by mackowskim** [music-assistant/hass-music-assistant#1159]
### What version of Music Assistant has the issue?

2023.3.6

### The problem

Hi,
Could you please add directory exclusion for local files in the library?
I'm using QNAP NAS Samba share for my local files, but this share also includes **@Recently-Snaphot** and **@Recycle** directories.
 
 This is problematic, because Music assistant library finds music file and playlist duplicates in the  **@Recently-Snaphot** folder.

![image](https://user-images.githubusercontent.com/45004433/227231708-0f12eb70-a43c-4dd9-824a-557bb2cc4623.png)
![image](https://user-images.githubusercontent.com/45004433/227231979-83fcd5d7-1d49-497f-b36a-2be60c7723ab.png)

It would be great if we could exclude chosen directories from scanning.

### How to reproduce

Install Music Assistant v2 beta addon
Add QNAP NAS share with snapshots enabled as a Samba share library.

### What version of Home Assistant Core are your running

2023.3.6

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Alternative

**Comment by marcelveldt** [comment]
are these folders in the root level or also within sublevels ?

**Comment by mackowskim** [comment]
**@Recycle** happens to be also in the **@Recently-Snaphot** directory, but as a rule it only exists just in a root SMB share

**Comment by marcelveldt** [comment]
This will be fixed in beta 16
