### ISSUE TITLE
Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

### ISSUE THREAD

**Issue by milandzuris** [music-assistant/hass-music-assistant#1166]
### What version of Music Assistant has the issue?

2023.2.1

### The problem

Logger: homeassistant.util.package
Source: util/package.py:107
First occurred: 16:48:16 (3 occurrences)
Last logged: 16:48:28

Unable to install package music-assistant==1.8.7.4: ERROR: Cannot install music-assistant because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip is available: 23.0 -> 23.0.1 [notice] To update, run: pip install --upgrade pip

### How to reproduce

Restart

### Additional information

Proxmox

### What version of Home Assistant Core are your running

2023.3.6

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Alternative

**Comment by OzGav** [comment]
Look at the pinned post at the top of the issues.
