### ISSUE TITLE
Time Music BAR

### ISSUE THREAD

**Issue by milandzuris** [music-assistant/hass-music-assistant#1174]
### What version of Music Assistant has the issue?

newest

### The problem

Time Music bar Stucked when im sliding music time
![image](https://user-images.githubusercontent.com/42905545/228949377-19ed7a7f-3086-43f5-8670-928cecd1b12e.png)

### How to reproduce

*

### What version of Home Assistant Core are your running

023.4.0b1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Alternative

**Comment by OzGav** [comment]
What type of player are you using?

**Comment by milandzuris** [comment]
> What type of player are you using?

chromecast

**Comment by OzGav** [comment]
Not sure then seems ok to me. Are you saying it isn’t moving at all?

**Comment by OzGav** [comment]
Sometimes I see it move back from where I slide it to but it is moving…?

**Comment by milandzuris** [comment]
> Not sure then seems ok to me. Are you saying it isn’t moving at all?

yes

**Comment by OzGav** [comment]
Try refreshing the browser cache. Try other browsers. Try incognito mode. We don’t have other reports of this. Sorry.

**Comment by OzGav** [comment]
If you have anything further to add please do so otherwise this will be closed. See if you can find someone else who can confirm the issue.
