### ISSUE TITLE
2.0.0b24 - Custom URLs can't be edited or deleted

### ISSUE THREAD

**Issue by wryandginger** [music-assistant/hass-music-assistant#1176]
### What version of Music Assistant has the issue?

2.0.0b24

### The problem

This is a minor issue, but I thought it would be worth reporting.

I can add a custom URL radio station to Music Assistant 2.0 without an issue, but there's no ability in the UI to rename the stream or edit the URL. I can't delete the URL either. I've tried deleting from the radio section. I've tried removing from the library (unhearting) first. I've tried deleting from the "more info" window on the stream itself, but nothing changes and the stations still appear in the radio section. I've tried refreshing and syncing the URL provider, but again nothing changes.

### How to reproduce

1. Go to Radio -> click three dot menu at the top right
2. Click "add item from URL" -> put in http://stream.revma.ihrhls.com/zc7304 (or similar) as the URL
3. Go to Radio -> click the three dot menu next to the station -> click "Remove Item From Database"
OR
3. Go to Radio -> click the three dot menu next to the station -> click "More Info" 
4. Click the three dot menu from the top right --> Click "Remove Item from Database"

nothing changes

### Relevant log output

2023-04-02 09:25:26 WARNING music_assistant.websocket_api  -- [139641311453392] Invalid command: music/delete_db_item

### What version of Home Assistant Core are your running

Home Assistant 2023.3.6

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Thanks for the report. @marcelveldt

**Comment by marcelveldt** [comment]
editing custom url's is not developed yet, the UI is not yet ready for that.
deleting items from the db should be possible so that seems to be broken.

**Comment by wryandginger** [comment]
thanks it works just fine now!
