### ISSUE TITLE
B27: mass is not aware when slimproto player is  powered off

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#1180]
### What version of Music Assistant has the issue?

2B27

### The problem

I physically power off a muse device, and even an hour later the player is still available according MA:

![](https://cdn.discordapp.com/attachments/1083643113484070953/1093601708770332744/image0.jpg)

The other 3 chromecast players above are powered off as well
When I try to start music to the muse, nothing happens of course, but MA still doesn’t recognise it’s gone

### How to reproduce

Physically power off an muse device (squeezelite)

### What version of Home Assistant Core are your running

2023.4.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Confirmed same behaviour with picoreplayer. Reloading the provider causes the player to be shown as unavailable (hourglass icon)

**Comment by erkr** [comment]
Same issue for b30

**Comment by OzGav** [comment]
Seems to be fxed in b36. @erkr ??

**Comment by erkr** [comment]
Will check!

**Comment by erkr** [comment]
Fixed in b35 🥳
