### ISSUE TITLE
SONOS players unavailable when S1 and S2 speakers are connected to the network

### ISSUE THREAD

**Issue by ranoydegraaf** [music-assistant/hass-music-assistant#1184]
### What version of Music Assistant has the issue?

2.0.0b27

### The problem

When SONOS speakers from the S1 and S2 app are connected at the samen time, the S2 speakers are unavaible through Music Asisstant

### How to reproduce

Connect S1 and S2 speaker to your network

### What version of Home Assistant Core are your running

2023.4.0

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Sorry the MA version you have indicated above is not valid. Please recheck and amend

**Comment by ranoydegraaf** [comment]
> Sorry the MA version you have indicated above is not valid. Please recheck and amend

Sorry, edited the original post.

**Comment by OzGav** [comment]
You wrote

> When SONOS speakers from the S1 and S2 app are connected

I don’t use SONOS but looking online it appears that S1 and S2 are different apps and only certain speakers work with those apps. If that is correct then I think you need to specify the speaker models that aren’t working instead of referring to the apps (as they won’t have anything to do with MA)

**Comment by OzGav** [comment]
So is there a confirmed issue here?

**Comment by marcelveldt** [comment]
Is there anything related in the logs ? What happens when you start playback ?
Does the app show anything ?

**Comment by ranoydegraaf** [comment]
Been away for a while but i'm back for testing the beta with the Sonos v1 and v2 devices. It looks like the v2 devices are working good in my setup, but as soon as a v1 device connects to the network and got discovered in MA all the Sonos devices are greyed out in the speaker list.

Restarting the MA add-on works for a while. But the device with the V1 firmware is gone in the speaker list. It is still shown in settings but with the loading icon next to it. Log doesn't show anything about the speaker.

**Comment by marcelveldt** [comment]
The log is complaining about a transition. Could it be that V1 speakers do not support crossfade and you have crossfade enabled ?

**Comment by OzGav** [comment]
Try turning it off and see if those errors go away?

**Comment by OzGav** [comment]
Any updates on this with b35?

**Comment by OzGav** [comment]
Ok closing then. Please raise another issue if problems present in the future.
