### ISSUE TITLE
Is Browse supposed to work in the current version?

### ISSUE THREAD

**Issue by gaussey** [music-assistant/hass-music-assistant#1195]
### What version of Music Assistant has the issue?

2.0.0b27

### The problem

I’m going to need it to create playlists since MAv2’s handling of playlists seems very non-standard. When I tap it it just seems to endlessly seek. Albums/artists/tracks are working ok. This is in relation to SMB shares.

### How to reproduce

Attempt to browse an SMB share.
![20230414_172003](https://user-images.githubusercontent.com/1004313/232101834-c5b2be72-4ed5-403a-9194-932ab64f4776.gif)

### What version of Home Assistant Core are your running

2023.3.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by marcelveldt** [comment]
Question 1: What do you mean with "MAv2’s handling of playlists seems very non-standard", can you elaborate ?
Question 2: Are the files in subfolders per artist or do you have one folder with many items in it ?

Browser should work but its implementation is still a bit basic. It can't handle large listings very well for example.

**Comment by OzGav** [comment]
I think there will be an error in the log.

**Comment by gaussey** [comment]
> Question 1: What do you mean with "MAv2’s handling of playlists seems very non-standard", can you elaborate ? 
When creating a a playlist in, for example VLC, the formatting is as follows :

#EXTM3U
#EXTINF:276,Blondie - Heart Of Glass
Best%20Of/Heart%20Of%20Glass.mp3


This format isn’t recognised.


When creating a playlist in MA the format is :

filesystem_smb2://track/Blondie/Best Of/Heart Of Glass.mp3


and thirdly to create a playlist of a folder outside of MA then  it’s simply the filename of each track on each line with the playlist m3u  in the folder containing the tracks.

This sometimes works and sometimes doesn’t. 

What I intended to do while browse wasn’t working was create playlists in VLC and save them to each folder but that’s not possible as per above, so the only way I’ve found of making playlists is to pipe a directory of filenames to a file which sometimes works and sometimes doesn’t.


Question 2: Are the files in subfolders per artist or do you have one folder with many items in it ?

Each separate album is in a subfolder.
> 
> Browse should work but its implementation is still a bit basic. It can't handle large listings very well for example.

**Comment by OzGav** [comment]
There is a thread where you can contribute your ideas for playlist support https://github.com/orgs/music-assistant/discussions/1088

Again look in the logs when you are browsing without result. Normally it hangs like that when there is a tag error or some other issue with your tracks in that folder

**Comment by gaussey** [comment]
> There is a thread where you can contribute your ideas for playlist support https://github.com/orgs/music-assistant/discussions/1088
> 
> Again look in the logs when you are browsing without result. Normally it hangs like that when there is a tag error or some other issue with your tracks in that folder

Thanks, there was a single mp3 in the root of the folder that was stopping browsing.

What does 

WARNING music_assistant.providers.filesystem_smb2  -- Could not parse uri/file filesystem_smb://track/
Filename.flac to track: track://Filename.flac not found on provider {provider_instance_id_or_domain}

mean? I’m getting it on a lot of flac files in a particular folder.
