### ISSUE TITLE
SMB Provider details duplicated in artist view

### ISSUE THREAD

**Issue by OzGav** [music-assistant/hass-music-assistant#1210]
### What version of Music Assistant has the issue?

2B20

### The problem

![image](https://user-images.githubusercontent.com/19848947/233884536-6470bf78-8ba1-4a66-8b2e-6ed39bf077d2.png)

Seems to only occur when the artist name has a non-letter in the title. e.g. R.E.M. or B-52's (although U2 wasn't a problem)

### How to reproduce

Navigate to an artist and click on the SMB provider icon in the top right. 

### Additional information

If someone can confirm this I will add it to the backlog.

### What version of Home Assistant Core are your running

2023.4.5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Still a problem in B32

**Comment by OzGav** [comment]
I’m still seeing this?
![IMG_0827](https://github.com/music-assistant/hass-music-assistant/assets/19848947/b9199702-5246-4f2a-8ba4-6f7c36835bd9)

**Comment by marcelveldt** [comment]
Do you have multiple B52's folders on disk perhaps ?

**Comment by OzGav** [comment]
No just the multiple album folders.

**Comment by marcelveldt** [comment]
I really can't reproduce this and code-wise it should not happen. Do you have multiple smb providers added ?

**Comment by OzGav** [comment]
On a fresh install of b60 with only the filesystem provider added I am still seeing this. In case it gives you another clue note in the this one how the second one has all the artist name capitllised. I will keep looking through but as I mentioned in the original post it only seems to happen when a non-letter is in the artist name (but not always)

![image](https://github.com/music-assistant/hass-music-assistant/assets/19848947/54736769-3478-49f3-b894-3f074ad23d48)

**Comment by OzGav** [comment]
OK I see now. If you look closely the B-52s have two names recorded one with an apostrophe and one without even though they have the same MB Artist ID. This is how it is getting tagged by Picard. 

![image](https://github.com/music-assistant/hass-music-assistant/assets/19848947/42fc3608-4a43-4071-b19e-2c4dcd2d25ef)

This one (which was reported by someone on Discord as well I thnk)  appears to be tripled because most tracks are by "Blues Brothers" even though the Album Artist is "The Blues Brothers" and there is one track by "Ray Charles with the Blues Brothers"

So do you think that is working per your design?

**Comment by Bodge-IT** [comment]
I can confirm this issue with SMB and Youtube music, happy to provide instances but in most ones I've checked, there is a difference between the Artist name tagged by me and that tagged by YT, either capitals, punctuation or added fluff words.  Pretty hard to fix this I would have thought.

**Comment by OzGav** [comment]
The case of the letters could be ignored to improve some. Whether ignoring symbols would result in false matches I am not sure….

**Comment by OzGav** [comment]
@marcelveldt  I think the issue with R.E.M. is that there are two mappings as the folder name doesn't have the last fullstop and can't have one by the looks of it at least as far as Windows is concerned?
![image](https://github.com/music-assistant/hass-music-assistant/assets/19848947/e3967cd6-d3a3-4e9e-9be5-3b26bef386a6)

**Comment by OzGav** [comment]
@marcelveldt I see you moved this to done in the backlog but I see no change. I have completely uninstalled MA and setup from scratch...? I am still seeing this for 2Cellos (for example)

![image](https://github.com/music-assistant/hass-music-assistant/assets/19848947/d4cc3b32-3bd2-4557-aae4-b2b3ca09ea0f)

![image](https://github.com/music-assistant/hass-music-assistant/assets/19848947/3bb0edd3-3d73-4b02-9db7-c17ad01fa601)

This is in the log though which may have some impact?
```
2023-08-02 11:32:24.969 INFO (MainThread) [music_assistant.metadata] Unable to get musicbrainz ID for artist 2CΞLLOS
 - using lookup-album(s): 2CΞLLOS/2CΞLLOS
 - using lookup-track(s): Misirlou (Theme From Pulp Fiction)/Misirlou (Theme From Pulp Fiction)
```

I watching to see if this self corrects after the full scan is done

**Comment by marcelveldt** [comment]
Yes, it is doing exactly what it should. It matched all those cases to the same artist

**Comment by OzGav** [comment]
Ok then I misunderstood what should happen here. All good.

**Comment by marcelveldt** [comment]
Seeing those different pronounces added to the same artist is actually a good thing and an indication that the mapping is working correctly. It's up to you to cleanup your tags to choose one of the aliases but it's not wrong.

Wrong would be if each of the alias transforms into a different artist.

**Comment by marcelveldt** [comment]
Good:

1 Artist record for R.E.M. and rem and REM and R.E.M


Bad:

An artist record for B-52's and another artist record B52s


Hope that makes more sense

**Comment by OzGav** [comment]
Yep totally does. I’ll add something in the docs somewhere to save the question coming up again the future.

**Comment by marcelveldt** [comment]
Yes, you will notice the same for streaming providers, they will also have multiple id's for the same item. As long as we can stitch that all together it is a feature and not a bug ;-)
