### ISSUE TITLE
Norwegian translation

### ISSUE THREAD

**Issue by hanscats** [music-assistant/hass-music-assistant#1221]
### What version of Music Assistant has the issue?

2

### The problem

I would like to translate MA to Norwegian (Norwegian bokmål)

### How to reproduce

-  

### What version of Home Assistant Core are your running

2023.4.6

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Linux

**Comment by jozefKruszynski** [comment]
@hanscats Just a quick follow up, as I see you didn't join the Lokalise project yet.
Here is the [signup link](https://app.lokalise.com/public/321419046440c0f2bba414.05634832/) just for convenience 😄

**Comment by jozefKruszynski** [comment]
I just saw that I originally added the incorrect Norwegian. My apologies

**Comment by hanscats** [comment]
Thank you. Life came in the way. I've joined the project and will start to
work on it this weekend.

fre. 28. apr. 2023 kl. 08:15 skrev Jozef Kruszynski <
***@***.***>:

**Comment by jozefKruszynski** [comment]
It's great to have you on board 👍
Thank you for your time
