### ISSUE TITLE
Squeezebox `invalid decoder`

### ISSUE THREAD

**Issue by meichthys** [music-assistant/hass-music-assistant#1222]
### What version of Music Assistant has the issue?

2.0

### The problem

I've confirmed that i do not have Logitech Media Server installed on my  network.
I've confirmed that i do not have slimproto or similar integration enabled in HomeAssistant

I receive an `invalid decoder` error on  my  Squeezebox Boom when trying to connect to  MA 2.0
I do see the squeezebox show up as a player in MA2.0

### How to reproduce

Setup Squeezebox Boom to connect to MA2.0
Try to  play music through Squeezebox via MA2.0

### What version of Home Assistant Core are your running

2023.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
Please include the relevant MA log as well

**Comment by OzGav** [comment]
@marcelveldt thoughts?

**Comment by marcelveldt** [comment]
This should be fixed in beta36

**Comment by OzGav** [comment]
Closing assumed fixed pending further info
