### ISSUE TITLE
music assistant 500 internal server error server got itself in trouble

### ISSUE THREAD

**Issue by HeisemerBub** [music-assistant/hass-music-assistant#1223]
### What version of Music Assistant has the issue?

v2023.2.1

### The problem

Hi together,,this is my home assistant configuration
` Home Assistant 2023.4.6 Supervisor 2023.04.1 Operating System 10.1 Frontend 20230411.1 - latest `

i had installed hacs like the documentation, but when i install the music assistant the error comes:

`music assistant 500 internal server error server got itself in trouble`

What can i do and what is my mistake?

abour an answer best thanks.

best regards 

heisemer

### How to reproduce

omly install like the documentation

### Relevant log output

how can i poste the log...?

### What version of Home Assistant Core are your running

2023.04.1

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

**Comment by gieljnssns** [comment]
https://github.com/music-assistant/hass-music-assistant/issues/1143

**Comment by gieljnssns** [comment]
You can try the V2 beta. 
https://github.com/music-assistant/server

**Comment by HeisemerBub** [comment]
Thanks...with the Plugin install MA is Running

Von meinem iPad gesendet
