### ISSUE TITLE
B29: no cleanup triggered when removing a provider 

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#1224]
### What version of Music Assistant has the issue?

B29

### The problem

Once you remove a provider it should start cleaning out all items from that provider in the background.
Several users reported that this doesn't happen.

### How to reproduce

-

### Relevant log output

-

### What version of Home Assistant Core are your running

2023.4.x

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by marcelveldt** [comment]
fixed in b59
