### ISSUE TITLE
B29: cache.db continues to grow and double entries

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#1225]
### What version of Music Assistant has the issue?

V2B29

### The problem

As discussed on discord (https://discord.com/channels/753947050995089438/1098999396869361709) the cache.db file in the data folder of MA continues to grow. Probably related to double entries like playlists. 

### How to reproduce

-

### What version of Home Assistant Core are your running

2023.4.5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
I think we can close this one?
