### ISSUE TITLE
Provide color logo for add-on page. 

### ISSUE THREAD

**Issue by johntdyer** [music-assistant/hass-music-assistant#1236]
### What version of Music Assistant has the issue?

2022.04.03

### The problem

Currently in the add-on page the canonical approach to show state is to have a color icon and a black and white one.  Color for running , B&W for not …. I’m any case currently MASS is not doing this and it’s hard to see state when looking at all the Add-one

 

### How to reproduce

Goto add on page 

### What version of Home Assistant Core are your running

2023.5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Linux

**Comment by johntdyer** [comment]
![2EA2DAA8-E234-41B6-934F-C29010F78B8E](https://user-images.githubusercontent.com/58234/235702168-288554c9-4fc5-4d6d-aaab-5eb9bea79755.png)

**Comment by erkr** [comment]
Thanks for the proposed enhancement

**Comment by Mr-HaleYa** [comment]
Is this the logo a temporary one?
The logo of the [group](https://github.com/music-assistant) should also be changed to match.

I made some colored ones that you can use, if you want something else just let me know.
___
![logo-ff0000](https://github.com/music-assistant/hass-music-assistant/assets/42821995/00d3bb7a-5f95-415a-bc66-6070ef5323a6)
![logo-f9e17e](https://github.com/music-assistant/hass-music-assistant/assets/42821995/bd5ce36b-aaf0-417a-b74d-2e232f3dcb2e)
![logo-bb84e8](https://github.com/music-assistant/hass-music-assistant/assets/42821995/58e7b70c-f122-43ef-a1bf-6ab5b5439e8d)
![logo-010536](https://github.com/music-assistant/hass-music-assistant/assets/42821995/98de99e1-5c4c-47a1-9dac-010254dc25e8)
![logo-42a046](https://github.com/music-assistant/hass-music-assistant/assets/42821995/02c368f6-de12-4c7b-abb5-57847ac33fbc)
![logo-01a9f4](https://github.com/music-assistant/hass-music-assistant/assets/42821995/42c56553-9364-4802-ac50-395a41e856ac)
![logo-f37725](https://github.com/music-assistant/hass-music-assistant/assets/42821995/7b29ed7c-364b-4c92-b493-da94dccc90e3)
![logo-0023ff](https://github.com/music-assistant/hass-music-assistant/assets/42821995/9e426e34-3278-448d-bda1-56d5af88592e)

**Comment by marcelveldt** [comment]
There is no logo on the org level, that is just a github default icon.
We are going to change the logo at some point and when that happens we'll look into this.
