### ISSUE TITLE
Mediaplayers no longer visiable in Home Assistant

### ISSUE THREAD

**Issue by Kouwe-sudo** [music-assistant/hass-music-assistant#1237]
### What version of Music Assistant has the issue?

2.0.0b29

### The problem

Is it a know fact that some of the media_players listed in Music Assistant are no longer visible and available in Home Assistant. I can't give a better clue because it's not a particular type of media_player. One Sonos is still available in HA the other is not. One Google Home player is available, the other is not. They can still be used in HA automations. The will turn on. But they won't turn off. Expect by pulling the plug or turn them of in Music Assistant. 

### How to reproduce

Perhaps:  Use a few mediaplayers a HA automation. Install MA and wait it comes alive, see what mediaplayers are coupled with MA.  See if they are still coupled with HA and can be manipulated from the entity-list .  

### What version of Home Assistant Core are your running

2023.4.6

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
You need to supply the relevant error logs in order for us to help

**Comment by erkr** [comment]
@Kouwe-sudo 
was your issue addressed with my answer?

**Comment by Kouwe-sudo** [comment]
Excuse for the late response but there are more important thing in life that needed my attention. 
To answer your question. No unfortunately not.
The thing is I had existing scripts to turn on and off the radio when I wake up in the morning. The script to turn on the radio with those music-players still works. But one of the two doesn't turn off anymore and I can't renter it in the script once I've deleted it.
It is not a big deal. I just pull the plug now every morning for a second. But I wanted to bring this to your attention while Music Assistant is still in Beta.

**Comment by OzGav** [comment]
I'm just re-reading your report. Currently there is no link between MA and HA. So for some devices both HA and MA will discover and create a player that is accessible withiin the relevant (HA or MA) interface. However, if you start playing something on a HA media player it can't be controlled by MA and vica versa. This might be what you are seeing. 

Why you can't turn off the media player with HA I cannot say but that would be a problem with HA not MA

**Comment by OzGav** [comment]
@Kouwe-sudo unles you have more to add I will close this as the lack of HA integration is known and will be fixed in a few weeks.

**Comment by Kouwe-sudo** [comment]
You can close it. It's fine with me.
