### ISSUE TITLE
Default startup volume not reflected in player 

### ISSUE THREAD

**Issue by gost4711** [music-assistant/hass-music-assistant#1238]
### What version of Music Assistant has the issue?

2.0.0b29

### The problem

The saved volume is not applied when the player is started. I set this under advanced settings.

### How to reproduce

I set the value and start the player

### What version of Home Assistant Core are your running

2023.2.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by gost4711** [comment]
Add:
No setting can be changed.

**Comment by OzGav** [comment]
Not sure what volume you are referring to as there is nothing in advanced settings. This is what options are available
![image](https://github.com/music-assistant/hass-music-assistant/assets/19848947/b6f07ef5-0dc4-431f-b3f6-d098df86b9af)

**Comment by gost4711** [comment]
II mean the  "default starup volume"


<img width="617" alt="Screenshot 2023-05-12 201809" src="https://github.com/music-assistant/hass-music-assistant/assets/33178509/78890b66-6cfa-44cc-8780-ee6211b28abb">

**Comment by OzGav** [comment]
Yes I can see what you mean. The settings value changes and can be saved but when looking the player list the volume there does not change as the player is toggled on and off.

**Comment by OzGav** [comment]
This should be fixed in beta 33
