### ISSUE TITLE
Errors with music assistant, and I can't remove music assistant as well

### ISSUE THREAD

**Issue by Bart-van-Gorp** [music-assistant/hass-music-assistant#1246]
### What version of Music Assistant has the issue?

v2023.2.1

### The problem

I haven't been using Music Assistant for a while since I've deleted our spotify account. I've disabled the integration when I deleted the account. Today I was browsing my logs and I saw that Music assistant is giving errors. Then I've tried to delete music assistant, but it won't let me. It says that I need to delete the configuration first and sends me to my integration page. On that page I see that Music assistant isn't loading and I can't delete it over there as well. What can I do to solve this issue? 

I've been running the following Home assistant version:

Home Assistant 2023.5.2
Supervisor 2023.04.1
Operating System 10.1
Frontend-versie: 20230503.3 - latest

![image](https://github.com/music-assistant/hass-music-assistant/assets/6367588/ffcec850-03d4-4952-999b-51043253392c)

### How to reproduce

I've tried a lot, but I'm afraid to remove folders or lines from the configuration without consulting this first.

### Relevant log output

Failed to parse message (b'8184016a') on cluster 32799, because Data is too short to contain 1 bytes
14:03:27 – (FOUT) runner.py
Setup failed for custom integration mass: Requirements for mass not found: ['music-assistant==1.8.7.4'].
14:03:26 – (FOUT) setup.py
Unable to install package music-assistant==1.8.7.4: ERROR: Cannot install music-assistant because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip is available: 23.1 -> 23.1.2 [notice] To update, run: pip install --upgrade pip
14:03:26 – (FOUT) util/package.py - bericht kwam voor het eerst om 14:03:16 en verschijnt 3 keer

### What version of Home Assistant Core are your running

2023.5.2

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by jozefKruszynski** [comment]
Hi @Bart-van-Gorp 
This discussion thread and post should help you solve your issue:
https://github.com/music-assistant/hass-music-assistant/issues/1143#issuecomment-1467928564

We hope it helps.
