### ISSUE TITLE
B30: add to queue not working as expected

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#1255]
### What version of Music Assistant has the issue?

B30

### The problem

When I have a queue playing (the last track),  and no repeat or shuffle enabled, I added another Spotify playlist to the queue. That screwed up the queue!
-According the ui I only have the new playlist. The previous tracks are not visible anymore. 
-the played items list is empty, should not!
-the player claims the first track is playing: but no it is still playing the previous track!
-when the track is finished, a track of the vanished list starts, not the new queue

Only way to fix, is clearing the queue before starting a new playlist.

### How to reproduce

As described, most likely relevant. I added the new playlist while playing the last track. I verified that, adding tracks while more tracks remain in the existing queue (and not playing) works fine.
So I guess related to: https://github.com/music-assistant/hass-music-assistant/issues/1153

### Relevant log output

No errors

### What version of Home Assistant Core are your running

2023.5.x

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
I will also add that if a queue has items in the played items list and you select another song and PLAY NOW then that track starts playing but the entire original queue gets added after. I would expect the new song starts playing but only the tracks that were in the NEXT ITEMS list (including the track that was playing if any?) would be after.

**Comment by OzGav** [comment]
@erkr Can you have a look at this again as it appears changes have been made to the queue options. The behaviour I reported above is still an issue though

**Comment by erkr** [comment]
I will check it, a few days back the issue was still there

**Comment by marcelveldt** [comment]
is this issue resolved ? can it be closed ?

**Comment by erkr** [comment]
What I original reported is, but this variation mentioned by @OzGav apparently not:

> I will also add that if a queue has items in the played items list and you select another song and PLAY NOW then that track starts playing but the entire original queue gets added after. I would expect the new song starts playing but only the tracks that were in the NEXT ITEMS list (including the track that was playing if any?) would be after.

**Comment by OzGav** [comment]
Yes just tested again with B60 and still seeing all the played items re-added to the queue when selecting a new track to play.

**Comment by marcelveldt** [comment]
should be fixed in b68
