### ISSUE TITLE
Reloading Airplay player results in flickering display

### ISSUE THREAD

**Issue by OzGav** [music-assistant/hass-music-assistant#1274]
### What version of Music Assistant has the issue?

2023.6.b32

### The problem

When doing some testing I disabled the DLNA player and enabled the Kodi Airplay player. This stayed unavailable so I reloaded the AirPlay provider which then resulted in flickering on various parts of the UI. @marcelveldt see this video https://drive.google.com/file/d/18AXWpaepi18sWxwG9J9tg-COQBotbU_Q/view?usp=drive_link 

A restart of the addon is required to fix it

### How to reproduce

As above

### What version of Home Assistant Core are your running

2023.5.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by marcelveldt** [comment]
Should be fixed in beta36, if not please let me know.

**Comment by OzGav** [comment]
Just happened to do a reload of the slimproto provider and got the flickering thing again. Video is on the Google Drive

**Comment by OzGav** [comment]
Appears fixed as at beta88
