### ISSUE TITLE
Can't find my PC as Airplay Device

### ISSUE THREAD

**Issue by sathio** [music-assistant/hass-music-assistant#1277]
### What version of Music Assistant has the issue?

2.0.0b32

### The problem

I'd like to stream to my pc, I've enabled my pc as airplay device and "everyone" can stream to it without password, when I go to the setting I should see my pc with the other Players in the network but it's not there. 
Is it possible that the pc shows itself on the network as PC and for this reason it is not possible to use it? 

as you can see from here, the device is available on the network, but then from Settings -> airplay -> Players I only see Rooms and Sala

![IMG_9426](https://github.com/music-assistant/hass-music-assistant/assets/1990816/932b2be0-df21-415d-b814-92790bb13812)

### How to reproduce

mac os, system settings, general, Airdrop & Handoff, Airplay Receiver on ON and Allow AirPlay for Everyone

### What version of Home Assistant Core are your running

2023.5.4

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
Can MA see any other players?

**Comment by sathio** [comment]
> Can MA see any other players?

yes, it shows the other two correctly

**Comment by sathio** [comment]
> Is your PC on the same subnet? Are there any firewall issues on the PC? Please try and rule out any network issues.

from terminal on HA server:
````
        [core-ssh ~]$ curl -v  192.168.69.69:5000
        *   Trying 192.168.69.69:5000...
        * Connected to 192.168.69.69 (192.168.69.69) port 5000 (#0)
        > GET / HTTP/1.1
        > Host: 192.168.69.69:5000
        > User-Agent: curl/8.0.1
        > Accept: */*
        > 
        < HTTP/1.1 404 Not Found
        < Content-Length: 0
        < Server: AirTunes/680.23.1
        < 
        * Connection #0 to host 192.168.69.69 left intact
        [core-ssh ~]$ 
````

the AirTunes server answers, so I think it should be all good networking wise. 

Do you know where to look on MA code? I might be able to debug this, hopefully :)

**Comment by marcelveldt** [comment]
I've found the issue. Fixed in next release.

**Comment by marcelveldt** [comment]
This should be fixed in beta36!
