### ISSUE TITLE
Server is not available for Raspberry Pi (compatibility issue)

### ISSUE THREAD

**Issue by paulo-graca** [music-assistant/hass-music-assistant#1282]
### What version of Music Assistant has the issue?

2.0.0b32

### The problem

When trying to install the add on (via supervisor) the available add isn't compatible with the Device's Processor or OS.

![image](https://github.com/music-assistant/hass-music-assistant/assets/877488/5a6a0416-6179-4672-940c-f64603057d0b)

![image](https://github.com/music-assistant/hass-music-assistant/assets/877488/97360c7e-9465-4c9e-be13-f0e2a5106da6)

### How to reproduce

Using Raspberry Pi 4, 2GB RAM and 32 Bit version
with
Home Assistant 2023.5.4
Supervisor 2023.04.1
Operating System 10.2
Interface: 20230503.3 - latest

After removing old MASS and all old references from HACS
When trying to add the MASS Beta addon, available here:
https://github.com/music-assistant/server

the addon is unavailable to my System:
![image](https://github.com/music-assistant/hass-music-assistant/assets/877488/5a6a0416-6179-4672-940c-f64603057d0b)

and the message states that isn't compatible.

### What version of Home Assistant Core are your running

2023.5.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Sorry 32bit OS is not supported
