### ISSUE TITLE
Default filters broken

### ISSUE THREAD

**Issue by fliespl** [music-assistant/hass-music-assistant#1285]
### What version of Music Assistant has the issue?

v2

### The problem

Currently artist filters (at least on my end) only display "Various artist". Need to switch it to see all artists.

### How to reproduce

OOTB I guess.

### What version of Home Assistant Core are your running

2023.5.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
Do you mean the album artist filter? If so probably you have a tagging problem.  Check the logs for errors.

**Comment by fliespl** [comment]
By default all I see is: https://ss.codeone.pl/ss-2023-06-05-08-11-27-1685945487-Df04Ni9F.png
After clicking: https://ss.codeone.pl/ss-2023-06-05-08-11-44-1685945504-636FhyXv.png
I see artists properly: https://ss.codeone.pl/ss-2023-06-05-08-11-58-1685945518-4ZoMO5qG.png

**Comment by OzGav** [comment]
It sounds like you don’t have the album artist tagged on your music. In the filesystem provider advanced settings there is an option “Action when track is missing album artist” and I suspect yours is set to use “Various Artists”. If so you need to retag all your music if you want MA to work properly

**Comment by fliespl** [comment]
Thanks, got it now. Didn't realize "album artist" is another tag needed to be used. :)
