### ISSUE TITLE
unexpected error installing MA(beta) on HA

### ISSUE THREAD

**Issue by Africa67** [music-assistant/hass-music-assistant#1289]
### What version of Music Assistant has the issue?

2023.6.0b0

### The problem

MA Server installed with Docker and working properly (http//192.168.1.1:8095) When installing MA Client for HA when asked for the url (http//192.168.1.1:8095) it gives the error message.

### How to reproduce

music assistant installation from Settings->Devices and services->Add Integration->MA(beta)

### Relevant log output

Logger: custom_components.mass
Source: custom_components/mass/config_flow.py:51
Integration: Music Assistant (BETA) ([documentation](https://github.com/music-assistant/hass-music-assistant), [issues](https://github.com/music-assistant/hass-music-assistant/issues))
First occurred: 5 giugno 2023 alle ore 22:33:35 (9 occurrences)
Last logged: 13:38:58

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/mass/config_flow.py", line 199, in async_step_manual
    self.server_info = await get_server_info(self.hass, user_input[CONF_URL])
  File "/config/custom_components/mass/config_flow.py", line 51, in get_server_info
    async with MusicAssistantClient(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/client/client.py", line 286, in __aenter__
    await self.connect()
  File "/usr/local/lib/python3.10/site-packages/music_assistant/client/client.py", line 116, in connect
    info = ServerInfoMessage.from_dict(result)
  File "<string>", line 9, in from_dict
mashumaro.exceptions.MissingField: Field "server_id" of type str is missing in ServerInfoMessage instance

### What version of Home Assistant Core are your running

2023.5.4

### What type of installation are you running?

Home Assistant Core

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by marcelveldt** [comment]
You're running an older server version as it seems. Update the server to the latest version

**Comment by Africa67** [comment]
How do I update the MA server or where can I find the latest version? Thank you

**Comment by OzGav** [comment]
You should be able to just delete the existing container and then pull down the latest version.

**Comment by marcelveldt** [comment]
> You should be able to just delete the existing container and then pull down the latest version.

That is not entirely true while we're running the beta as the "latest" tag won't work so you need the manual version tag like "2.0.0b36"

**Comment by Africa67** [comment]
I have done the latest MA server update and everything is working fine. Thank you
