### ISSUE TITLE
Cannot Delete Players (with Chromecast device)

### ISSUE THREAD

**Issue by yurtalan92** [music-assistant/hass-music-assistant#1290]
### What version of Music Assistant has the issue?

2023.6.bx

### The problem

I cannot delete temporary player (with Chromecast). i Deleted in settings but its still showing in Play screen. i need delete first 3 device. How can i delete it ? I attach picture.

Best regards.
![musicassistantdeleteproblemgithub](https://github.com/music-assistant/hass-music-assistant/assets/118316410/4667d85f-f3c9-41d5-9582-d75c11b06f28)

### How to reproduce

I haven't got Error but İ can't it

### What version of Home Assistant Core are your running

2023.06.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Have you restarted the addon? If those players are still on your network though they will get rediscovered. You can disable them in settings if you don’t want to see them

**Comment by yurtalan92** [comment]
> Have you restarted the addon? If those players are still on your network though they will get rediscovered. You can disable them in settings if you don’t want to see them

Yes, i got it. Thanks for interesting.
