### ISSUE TITLE
Can't use Music Assistant when away from home in iframe

### ISSUE THREAD

**Issue by dnestico** [music-assistant/hass-music-assistant#1292]
**Not really an issue Im kinda asking for help / a solution if possible instead**

### What version of Music Assistant has the issue?

2023.6.0b0

### The problem

So I am running music assistant on docker/unraid, I want to be able to access the server UI inside home assistant so I embded the server URL with iframe, this works fine when at home but it seems the iframe doesn't allow servers URLs to be embedded away from home/local network. 

I think because I am running the docker version there is no sidebar tab like there was without docker version I remember.

### How to reproduce

1. Get Music Assistant server URL
2.  Put the server URL in iframe
3.  Turn off WiFi and access via data
4. Music Assistant iframe will not work

![Screenshot_20230606-213418](https://github.com/music-assistant/hass-music-assistant/assets/3034555/2d6dc5fc-8232-41c8-bd7e-9443f4695a0b)

### Relevant log output

none

### Additional information

Running on unraid server on my laptop

### What version of Home Assistant Core are your running

2023.5.4

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
The error you are seeing there is associated with HA not MA. We can’t fix that. You should access the MA addon directly when away as this is a secure way to do so.

**Comment by dnestico** [comment]
Thanks, that's fine. Ill use the media player cards instead of the iframe. 👍

**Comment by skavan** [comment]
Actually, just got this working using caddy 2.
1. My router points incoming requests for mydomain.com:8080 to my local homeassistant ip (192.xxx.xxx.xxx).
2. Then in caddy 2 a super simple config:
```
email: myemail@gmail.com
domain: mydomain.com
destination: localhost
port: 8095
```
and finally in your iframe:
```
- type: iframe
   url: https://mydomain.com:8080/#/home
   aspect_ratio: 50%
```

At some point I should set caddy to handle and reverse proxy multiple inbounds and send them to different places. But for now this works through my phone via nabucasa and then to my HA. And of course, it works locally too.
Hope it helps.
