### ISSUE TITLE
Security concerns with the HA addon

### ISSUE THREAD

**Issue by molly200** [music-assistant/hass-music-assistant#1295]
### What version of Music Assistant has the issue?

Music Assistant BETA Current version: 2.0.0b32

### The problem

Great concept and good work!

Just wondering why the open access via telnet on port 9090? Is there a needed functionality for this addon to work properly?

Thanks

### How to reproduce

N/A

### Relevant log output

N/A

### What version of Home Assistant Core are your running

2023.6

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Assuming this has been answered adequately. FYI questions such as this would be better as a Q&A in our discsussion area next time.
