### ISSUE TITLE
v1.0.15 - Artists not fully populated

### ISSUE THREAD

**Issue by vk2him** [music-assistant/hass-music-assistant#130]
I'm seeing strange behaviour with v1.0.15. 

I only have 15 Artists listed, all starting with Letter A, one starting with letter B and one with letter E. If I look at Albums, I have 355 and the Artists names are all listed, but these artists don't appear in the Artists list. Screen shots:

![Image 007](https://user-images.githubusercontent.com/22878629/167744316-92f75e0b-2c89-443b-a046-793b10a25677.jpg)
![Image 008](https://user-images.githubusercontent.com/22878629/167744328-733456f5-20cb-4caf-a7c8-19f13bfa8321.jpg)

**Comment by vk2him** [comment]
Update - I did a clean install of Music Assistant by removing from HACS and Integrations, restarting then reinstalling. After the initial scan it has now found 223 Artists, and 355 Albums.  Maybe my database was corrupted due to previous issues so a rebuild fixed? Maybe this can be closed?

**Comment by vk2him** [comment]
Update - may be related to the other issue where network music in database doesn't survive a restart?

**Comment by marcelveldt** [comment]
It's related to the other issue (the race condition). I'll close this one.
