### ISSUE TITLE
Players disappeared / won't work 

### ISSUE THREAD

**Issue by iamthetrees** [music-assistant/hass-music-assistant#1302]
### What version of Music Assistant has the issue?

2023.6.bx

### The problem

I configured the integration and it worked on my DLNA xbox media player. I couldn't get it to work on my homepod. I added a universal group player where I added the xbox and homepod, then all the sudden the xbox stopped working. I tried deleting the universal group player then all the players disappeared. I've tried deleting and reconfiguring the integration, restarting the xbox, restarting home assistant, nothing works. I can get the xbox player to appear again but on the xbox itself it gives an error suggesting the format of the song is incompatible even though it played previously. Also when I try and play a song directly from the dlna xbox media player it gives a failed to call service error: [139656334076496] Resume queue requested but queue uuid:d6449a06-f8a8-436d-b3e7-b4afe1158d7b is empty

### How to reproduce

I dunno, just trying to play a track on music assistant and none of the players appear any more, unless I add them to a universal group player, they then appear in the player list but still won't play. 

### Relevant log output

Logger: homeassistant.components.media_player
Source: helpers/entity_platform.py:570
Integration: Media Player ([documentation](https://www.home-assistant.io/integrations/media_player), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+media_player%22))
First occurred: 19:58:01 (14 occurrences)
Last logged: 21:46:12

Platform mass does not generate unique IDs. ID mass_67bd243d-babe-5bcb-829c-e473fca6992d already exists - ignoring media_player.family_room_tv
Platform mass does not generate unique IDs. ID mass_aa:aa:80:3d:1a:d9 already exists - ignoring media_player.living_room_2
Platform mass does not generate unique IDs. ID mass_uuid:d6449a06-f8a8-436d-b3e7-b4afe1158d7b already exists - ignoring media_player.xbox_systemos
Platform mass does not generate unique IDs. ID mass_universal_group already exists - ignoring media_player.universal_group_player
Platform mass does not generate unique IDs. ID mass_universal_group2 already exists - ignoring media_player.universal_group_player_2

### What version of Home Assistant Core are your running

2023.6.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Linux

**Comment by marcelveldt** [comment]
Please remove the HA integration as first step, just remove the configuration entry for Music Assistant from HA settings --> Integrations. Then first make sure that everything within MA itself works again. So try to play something on the xbox and try to play something on the Homepod. Both should work fine in MA. For the Xbox I'm not sure but you might want to select a different codec (default is FLAC) in the settings for player (within MA).

If both confirmed working, next step is the HA integration. Set that up again, it should auto discover your running MA server so just a couple of clicks. If everything is working standalone you could try to setup the Universal Group again to group these players together.

**Comment by OzGav** [comment]
Please provide the outcome of what Marcel advised above. We will close this soon assuming all is well if nothing further is heard.

**Comment by OzGav** [comment]
Closing..stale.
