### ISSUE TITLE
Music Assistant not in Menu Bar

### ISSUE THREAD

**Issue by FlyingFabi** [music-assistant/hass-music-assistant#1309]
### What version of Music Assistant has the issue?

2023.06.1

### The problem

Music Assistant is not shown in the menu bar. 

### How to reproduce

It was fresh installed from HACS and was able to setup the integration. Also the players were found.

### What version of Home Assistant Core are your running

2023.06.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Alternative

**Comment by OzGav** [comment]
What menu bar are you referring to?

**Comment by FlyingFabi** [comment]
I mean the Home Assistant menu bar on the left side of the UI.Am 12.06.2023 um 13:06 schrieb OzGav ***@***.***>:﻿
What menu bar are you referring to?

**Comment by OzGav** [comment]
Have you selected that option in the addon INFO page "SHOW IN SIDEBAR"?

**Comment by FlyingFabi** [comment]
Now I feel stupid. Thanks for the hint. Now it’s working!

**Comment by jimmisavage** [comment]
I have the same issue - but I have the music assistant docker container running with HA is docker as well. I can connect and assign speakers and connect to music assistant via local port but it';s not showing in the HA sidebar. Obviously i don't have an addon INFO page but i did add SHOW IN SIDEBAR=true to the music assistant docker variables without any joy.

**Comment by marcelveldt** [comment]
show in sidebar is only available for the add-on install.
if you're running HA+MA as container based install, you'll have to open the MA interface yourself manually

**Comment by OzGav** [comment]
You can use an iframe and point to port 8095

**Comment by Vansmak** [comment]
> Have you selected that option in the addon INFO page "SHOW IN SIDEBAR"?

where is this page?  i have the integartion added and is shows my devices but i cannot see an info page anywhere. i do no know how to access mass. running on hass
