### ISSUE TITLE
Cannot Play to Shairport 

### ISSUE THREAD

**Issue by PablaV** [music-assistant/hass-music-assistant#1316]
### What version of Music Assistant has the issue?

2.0.0b36

### The problem

My shairport is built using Airplay 2 but it shows up in MA as a player and to my understanding airplay 2 is backwards compatible with airplay 1. Whenever I try to play anything from MA to my Shairport player nothing happens. Logs below

### How to reproduce

Connect to Shairport player and play any media 

### Relevant log output

2023-06-13 15:23:47 WARNING music_assistant.providers.slimproto.cli  -- No handler for  (player:  - args: [] - kwargs: {})
2023-06-13 15:23:47 WARNING music_assistant.providers.slimproto.cli  -- No handler for  (player:  - args: [] - kwargs: {})
2023-06-13 15:24:31 WARNING asyncio  -- Executing <Task pending name='Task-8292' coro=<SlimprotoProvider._handle_connected() running at /usr/local/lib/python3.11/site-packages/music_assistant/server/providers/slimproto/__init__.py:722> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/local/lib/python3.11/asyncio/futures.py:387, Task.task_wakeup()] created at /usr/local/lib/python3.11/asyncio/base_events.py:427> cb=[MusicAssistant.create_task.<locals>.task_done_callback() at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:291] created at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:284> took 0.102 seconds

### What version of Home Assistant Core are your running

2023.6.0

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

ODROID

**Comment by OzGav** [comment]
Did you see Marcels response to you on discord?

> What is there to support on Airplay 2? That is just an extension for video primary and a few extras. You can use airplay 1 (RAOP) to stream to airplay targets. If you have issues playing to shairport targets, try to enable the encryption setting on the airplay player in MA.

**Comment by OzGav** [comment]
A previous issue noted 

> But now I have found a solution. I reconfigured shairport so that only Airplay 1 is used. Now it works.

Is yours similarly configured?

**Comment by PablaV** [comment]
Mine is configured to use Airplay 2 but my understanding from talking with Marcel on discord is that Airplay 2 is backwards compatibility with Airplay 1

**Comment by OzGav** [comment]
Just letting you know what others have found. So I suggest you change it to Airplay 1 and try it.

**Comment by marcelveldt** [comment]
Well, so far every Airplay 2 capable speaker I have tested, accepted Airplay 1 commands/audio just fine. The Shairport documentation is also mentioning it will fallback to AP1 for audio streaming if needed but maybe that does not work as well ?

**Comment by OzGav** [comment]
@PablaV Have you tried setting shairport to airplay 1 to see if that fixes the problem?

**Comment by PablaV** [comment]
I have not tried that yet, I spoke with the Shairport dev and he mentioned its some sort of authentication issue on Shairport end. I will test with Airplay 1 to see if its an issue though

**Comment by OzGav** [comment]
Any updates. We will close this soon if no further info is provided.

**Comment by PablaV** [comment]
No updates right now, the Shairport dev said he will look into it though. I will be trying Shairport with Airplay 1 to confirm MA works with airplay 1.

**Comment by OzGav** [comment]
Yes please.

**Comment by PablaV** [comment]
Tested with Shairport classic (airply 1) and MA can play to it no problem

**Comment by OzGav** [comment]
Would seem to be a shairport problem as Marcel had no problems with other airplay capable speakers. I’m inclined to close this as it is possible to play to shairport by using the classic mode?

**Comment by PablaV** [comment]
Yes absolutely, this is a Shairport problem more or so a Music Assistant. Safe to close this issue!

**Comment by PablaV** [comment]
update: The Shairport dev was able to fix the issue and in the coming version of Shairport, Music Assistant will be able to play to it regardless of what Airplay version you have set for Shairport

**Comment by OzGav** [comment]
Legend. Thanks for following that up!
