### ISSUE TITLE
Delete from playlist not working correctly 

### ISSUE THREAD

**Issue by OzGav** [music-assistant/hass-music-assistant#1319]
In my testing it appears that delete from playlist is deleting the following track. If there is only one track in the playlist then the track is not removed. Is that what you are seeing?

_Originally posted by @OzGav in https://github.com/music-assistant/hass-music-assistant/discussions/1219#discussioncomment-6213969_

**Comment by marcelveldt** [comment]
will be fixed in b60

**Comment by OzGav** [comment]
In b61 I can’t seem to add or delete from a playlist?
