### ISSUE TITLE
v1.0.15 - after a restart of HA, I've lost Albums and Artists in list

### ISSUE THREAD

**Issue by vk2him** [music-assistant/hass-music-assistant#132]
After upgrading to v1.0.15 I let the scan finish and it found 355 Albums and 18 Artists. 

I restarted HA about an hour after the initial scan finished and I now only have 2 Artists and 25 Albums listed - a rescan is also underway so potentially the "missing" ones will be rediscovered? Wondering why they were lost?

Was:
![Image 008](https://user-images.githubusercontent.com/22878629/167746639-41eba57c-a2d1-4a41-8c5d-48c99cb9b6b9.jpg)

Now:
![Image 015](https://user-images.githubusercontent.com/22878629/167746680-8be7847d-62df-443b-bdba-5417e6d204aa.jpg)

**Comment by vk2him** [comment]
Update - after the restart the scan only took a few minutes. It found no extra files. It seems the ones listed are on my Local HA - any files on my network NAS have not been saved (refer to the other thread where I discuss how to access remote files). Seems non local files don't survive a restart?

**Comment by marcelveldt** [comment]
This is called a "race condition" in developers code.
You mount the network location from Home Assistant. At startup, Music Assistant runs a scan for library changes. At that time the network drive is not yet available and thus it fails to find those fails. If you wait another 3 hours it will discover them.

I will add a small delay in the initial sync to prevent this from happening.
