### ISSUE TITLE
Airplay player turns to Idle after every track

### ISSUE THREAD

**Issue by MarvinSchenkel** [music-assistant/hass-music-assistant#1320]
### What version of Music Assistant has the issue?

beta 38

### The problem

`media_player` entities in HA flip between `Playing` and `Idle` state after a track has finished and before a new track starts in standard_mode (no flow mode). This make creating automations based on the `state == playing` a bit hard:

![image](https://github.com/music-assistant/hass-music-assistant/assets/17671719/7aabbf79-8c6c-429a-91da-c99d4729e291)

### How to reproduce

* Start playing a queue of items
* Watch the state of the `media_player` in HA

### What version of Home Assistant Core are your running

2023.6.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by marcelveldt** [comment]
this should have been fixed in previous version, if not re-open.
