### ISSUE TITLE
Enhance squeeze box functionality

### ISSUE THREAD

**Issue by OzGav** [music-assistant/hass-music-assistant#1323]
There are some things left that are not functioning well (but maybe there is already worked on):

- On the squeezebox controller (belonging to Duet) and Squeezeplay in the "My Music"-tab the in Music Assistant choosen presets are shown. So the music library as scanned in Music Assistant is not shown. Consequently the controller (Duet and Squeezeplay) cannot be applied for selecting music from the music library.
- The power on/power off button of the Boom isn't activated. Also the control-light on the Duet-player keeps on blinking when power off the device in Music Assistant.
- The preset-tabs on the Boom are not corresponding with the presets in the corresponding player in Music Assistant. I have the impression that the preset-tabs on the Boom are not functioning at all.

But on the whole a lot of progress has been made the last month concerning the application of the squeezebox hardware in Music Assistant. Thank you for all your effort!

_Originally posted by @poerlemans in https://github.com/music-assistant/hass-music-assistant/issues/1273#issuecomment-1600700268_

**Comment by poerlemans** [comment]
Some more detailed information about my experiences:

I tested Squeezebox Duet, Boom, Touch and Classic.
Sync (pause, play, volume) between MA and hardware (buttons on device) seem to work oke. When I press power-off button on the player (Boom, Touch, Classic), the player in MA is also powered-off, but player can only be powered-on again in MA. So power-on on the device in not possible.
This power-on process cannot be tested on the Duet because the Duet cannot be powered-off (led keeps blinking).

The remarks concerning the "My Music"-tab hold true for all four devices.

**Comment by marcelveldt** [comment]
MA is not a fully fledged alternative for Logitech Music Server. Implementing the full menu structure with all bells and whistles will take me weeks, if not months and at this time I have other priorities. I prepared all code to create the complete menu system to finish later (when we released 2.0 stable) or someone wants to contribute it. As an alternative I now show the presets in the menu structure which will already solve 80% of the usecase.

Note that actual squeezebox hardware is getting sparser everyday, its an aged platform. MA focusses more on the software alternatives like squeezelite and the esp32 incarnation of it.

That said, I do my best to make the important controls work on the hardware players, so things like volume control and buttons. So if something is not working, create a report per issue and I'll pick it up from the queue and fix it.

At some point we might actually want to consider having LMS as a player provider for MA for the more advanced usecases. The slimproto provider within MA is targeted at straight forward playback in high quality

**Comment by poerlemans** [comment]
@marcelveldt 
I understand your remarks completely.
At this moment playing music from the squeezebox devices is functioning quit well.
Further improvements can wait.

**Comment by OzGav** [comment]
This should be fixed in b107. Let us know if not.

**Comment by ClearlyDazed** [comment]
Having music assistant working with home assistant is an excellent project, extending the ability's of  logitech music server. One caveat that I find unsurmountable at this time is the elimination of my squeezebox functionality. It can no longer access the music library and select items to play. I know this hardware is quite old but it is still very useful. Not having the squeezebox menu is a game changer.
