### ISSUE TITLE
Music Assistant (BETA) never display on sidebar

### ISSUE THREAD

**Issue by Yumega** [music-assistant/hass-music-assistant#1325]
### What version of Music Assistant has the issue?

2023.6.0b0

### The problem

I can't find the Music Assistant on sidebar no matter how restarted the Home Assistant

### How to reproduce

I don't know

### What version of Home Assistant Core are your running

20230608.0

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
Please don’t post multiple queries about the same problem and issues are for problems with MA so your discussion is the correct place for this question
