### ISSUE TITLE
Music added from Albums or Artists don't play

### ISSUE THREAD

**Issue by vk2him** [music-assistant/hass-music-assistant#133]
After a bit of trial and error, I've seen that any music I try to play or add to the queue from the Albums or Artists won't play and no log errors are logged. I can only play music if I select from Tracks. The following screenshot shows the queue - any music starting with database://  was added from Tracks and will play fine - any starting with filesystem:// were added from Artists/Albums and wont play - you'll see that Hells Bells is listed in both - database:// will play and the others won't

![Screen Shot 253](https://user-images.githubusercontent.com/22878629/167765573-6e6016fe-ec70-46ff-a2c0-2bf422bb96b3.jpg)

**Comment by vk2him** [comment]
Note these are all on a Network drive

**Comment by marcelveldt** [comment]
I've just published version 1.0.16 which contains a fix for this issue.
