### ISSUE TITLE
MA server with multiple eth interfaces

### ISSUE THREAD

**Issue by Sonusss** [music-assistant/hass-music-assistant#1332]
### What version of Music Assistant has the issue?

ghcr.io/music-assistant/server:latest  (2 days ago)

### The problem

Running the server as docker container on a multi homed (multiple NIC) host with --network host seems causing problem with DLNA discovery
So I tried to use --network bridge but MA server seems not responding at all in this mode

### How to reproduce

having a docker host with multiple network interfaces

### Relevant log output

None

### What version of Home Assistant Core are your running

None

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by Sonusss** [comment]
I tried specifying a dedicated NIC with --IP xx.xx.xx.xx 
but same result server not responding

**Comment by OzGav** [comment]
Do you think this is actually an MA issue or is it a networking problem?

**Comment by Sonusss** [comment]
Well I made a lot of tests and I think it's both...
Normally I run a firewall on this host (Shorewall)
But even booting the host without starting the firewall gives barely the same results.
with docker option --network host  MA server is running but UpnP/DLNA don't see any players
with docker option --network bridge  MA server is running but not reachable...
So I believe it is networking related but inside MA server container
I would say that the DLNA  provider is not compatible with multiple NIC

**Comment by OzGav** [comment]
From the docs “MA must be able to be reached LOCALLY on port 8095. Running behind VPNs, across subnets, behind firewalls or inside other than docker containers is not supported (it might work but we can’t troubleshoot for you)” Additionally, Marcel said on discord “ Discovery of dlna players depends on your network and if multicast traffic can travel freely.”

I am inclined to close this as you are running in an unsupported environment. We only have so much person power to deliver this project and unfortunately can’t support every combination of hardware and software that is out there….

**Comment by marcelveldt** [comment]
One of the next updates will bring a setting to set the network interface IP manually which will help with these kind of issues.
Still the MA container must run in host networking mode (or bridge, that is also fine if your setup supports that).

Multi homed NIC's are not supported atm until the above mentioned setting is included in the code.

**Comment by Sonusss** [comment]
I fully understand. THX for your time, support and great job !

**Comment by Sonusss** [comment]
I confirm, being able to set server IP address would be nice...
I made a docker commit with fixed IP address in the code and it's working like a charm on my multi NIC host ;-)
(slimproto only, I throwed away DLNA for it's crap)

**Comment by Sonusss** [comment]
May I suggest to have an entry in settings.json to specify eventually a specific IP address ?

**Comment by marcelveldt** [comment]
I'd rather not have people manually editing the config files, that is error prone and not very user friendly.
There will be a UI config option for this, just a bit of patience please.

**Comment by sdrapha** [comment]
@Sonusss Would you be so kind to point me at which line of code you manually edited? 
so I can also manually modify my instance. My music assistant server container is in a different subnet than homeassistant. So I guess I will have to explicitly tell which IP to look for on the homeassistant component side.

**Comment by marcelveldt** [comment]
There is no more need for that. The recent version has support for that built in.

**Comment by Sonusss** [comment]
I confirm , working like a charm 
@ marcelveldt  Great job with the core panel. THX (might be a good place for the version info...)
