### ISSUE TITLE
Filesystem (local share) Not fully syncing, missing files

### ISSUE THREAD

**Issue by triosniolin** [music-assistant/hass-music-assistant#1339]
### What version of Music Assistant has the issue?

2023.6.0b0

### The problem

I have a rather small music library, 402 files, mostly MP3s and a couple FLAC. I had MusicBee, my desktop PC's media library, place these tracks in the local media folder for Home Assistant. The file structure is `Media\<Artist>\<Title>`. I then added a file system media provider to Music Assistant and told it to use the HA `Media` folder. 

It only detected 167 of the 402 files. If I `browse` and attempt to view a folder where a missing track is located, MA will not open the folder. No error message is displayed, the folder just doesn't open. The animation for having clicked on it works.

I can use the default `Media` service in Home Assistant to find and play these tracks fine, so it isn't an issue with the files themselves.

The only relevant log output appears to be that MA can't find the album artist tag on these tracks and that's screwing it up, but that seems....silly to me if that's what's going on? I haven't gone through all the logs to make sure that only the missing tracks have these log entries, but it appears so.

### How to reproduce

I suppose I could share my music library, but otherwise I don't know how to reproduce this issue.

### Relevant log output

2023-06-29 12:01:56 ERROR music_assistant.websocket_api  -- [139920709261776] Error handling message: CommandMessage(message_id=59, command='music/browse', args={'path': 'filesystem_local://Bon Jovi'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/websocket_api/__init__.py", line 237, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 242, in browse
    return await prov.browse(path)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/filesystem_local/base.py", line 246, in browse
    elif track := await self.get_track(item.path):
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/filesystem_local/base.py", line 393, in get_track
    return await self._parse_track(file_item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/filesystem_local/base.py", line 654, in _parse_track
    raise InvalidDataError("missing ID3 tag [albumartist]")
music_assistant.common.models.errors.InvalidDataError: missing ID3 tag [albumartist]

### What version of Home Assistant Core are your running

2023.06.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by will-cole-oe** [comment]
I have verified that all of my tracks are tagged with an `AlbumArtist` tag in Picard.

**Comment by OzGav** [comment]
Just confirming have you actually retagged them all with Picard or just inspected them? Please retag them if you haven’t. 

Try removing the Bon Jovi folder and see if everything works ok then. If so there is a problem with something in that folder. Slowly add the tracks back until you find the offending one.

**Comment by OzGav** [comment]
You can also change the setting in the file system provider advanced settings to not skip the track but it is better if you can tag it properly

**Comment by will-cole-oe** [comment]
> You can also change the setting in the file system provider advanced settings to not skip the track but it is better if you can tag it properly

When I set it to `use track artists`, the number of tracks that MA is willing to play went from 167 down to 12. 


> Just confirming have you actually retagged them all with Picard or just inspected them? Please retag them if you haven’t.
> 
> Try removing the Bon Jovi folder and see if everything works ok then. If so there is a problem with something in that folder. Slowly add the tracks back until you find the offending one.

I verified the tags.  I should have mentioned that the Bon Jovi folder was just an example, I have hundreds of errors of this type being thrown.

**Comment by triosniolin** [comment]
> You can also change the setting in the file system provider advanced settings to not skip the track but it is better if you can tag it properly

When I set it to `use track artists`, the number of tracks that MA is willing to play went from 167 down to 12. 


> Just confirming have you actually retagged them all with Picard or just inspected them? Please retag them if you haven’t.
> 
> Try removing the Bon Jovi folder and see if everything works ok then. If so there is a problem with something in that folder. Slowly add the tracks back until you find the offending one.

I verified the tags.  I should have mentioned that the Bon Jovi folder was just an example, I have hundreds of errors of this type being thrown.

**Comment by OzGav** [comment]
There is something wrong with your tags. Retag all of your tracks with Picard. We hav also seen issues with artwork embedded with iTunes which used a non-standard approach. If you retag with Picard all should be well.

**Comment by triosniolin** [comment]
Ok, so I deleted everything from my media share and set it as the output directory for Picard, verifying the tags were saved and that Picard was the only thing updating and saving the media. It's now in a different file system format, but it works fine.

However, Music Assistant still only shows 149 tracks. It shows 158 artists, and 184 albums. 

I no longer see the errors for missing `AlbumArtist` but I still am missing many many tracks. An example of a track that is physically on the disk but is not showing on the list of tracks:
![image](https://github.com/music-assistant/hass-music-assistant/assets/25272137/09129708-89ea-465c-a295-f780a0cdcb2a)

**Comment by OzGav** [comment]
Try browsing to that particular track and see what happens. Check the log after doing so.

**Comment by OzGav** [comment]
Also what if you navigate to the album Narrow Stairs. Can you see the track there?

**Comment by triosniolin** [comment]
I logged in to HA/MA today to this test, and it is now showing all 415 tracks.

Is it possible it just needed several *days* to build the database?

**Comment by OzGav** [comment]
Not necessarily days but it does take a little time to scan everything although 415 tracks is not much. Many people have thousands. But sounds like everything is working now so I will close this.
