### ISSUE TITLE
Preview not available for music on Network drives

### ISSUE THREAD

**Issue by vk2him** [music-assistant/hass-music-assistant#134]
Any music that's on a network drive doesn't have a preview available - see screenshot - same music file locally and on network - only the local can be previewed.  Perhaps some of the other issues I'm seeing are due to music being on a network drive?

![Screen Shot 254](https://user-images.githubusercontent.com/22878629/167767240-e9ce1a5c-0d19-4668-a601-8104489f6166.jpg)

**Comment by marcelveldt** [comment]
I've just published version 1.0.16 which contains a fix for this issue.

**Comment by vk2him** [comment]
Working fine now thanks
