### ISSUE TITLE
update fail 2.0.0b40

### ISSUE THREAD

**Issue by platini76** [music-assistant/hass-music-assistant#1342]
### What version of Music Assistant has the issue?

2.0.0b39

### The problem

message is connection lost

### How to reproduce

update

### What version of Home Assistant Core are your running

2023.7.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by rufjame** [comment]
Similar error message when running update on same above versions but virtualized hardware

![image](https://github.com/music-assistant/hass-music-assistant/assets/6258478/0f55935e-7b34-4e27-831d-a95458f54fee)

**Comment by JimmyMPage** [comment]
Same error here. Tried rolling Home Assistant Core back to 2023.6.3, but that did not fix the issue.

What version of Music Assistant has the issue?
2.0.0b39

The problem
message is connection lost

How to reproduce
update

Relevant log output
No response

Additional information
No response

What version of Home Assistant Core are your running
2023.6.3

What type of installation are you running?
Home Assistant OS

On what type of hardware are you running?
ODROID N2+

**Comment by OzGav** [comment]
Tracking it here https://github.com/music-assistant/hass-music-assistant/issues/1343
