### ISSUE TITLE
Can't install Beta from Add-On Store

### ISSUE THREAD

**Issue by charliesoap4** [music-assistant/hass-music-assistant#1343]
### What version of Music Assistant has the issue?

2.0.0b40

### The problem

When I try to install the add-on, I get the following error message.

Can't install ghcr.io/music-assistant/server:2.0.0b40: 500 Server Error for http+docker://localhost/v1.42/images/create?tag=2.0.0b40&fromImage=ghcr.io%2Fmusic-assistant%2Fserver&platform=linux%2Farm64: Internal Server Error ("manifest unknown")

### How to reproduce

Click Install from Music Assistant BETA Add-on page

### Relevant log output

Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:130
Integration: Home Assistant Supervisor ([documentation](https://www.home-assistant.io/integrations/hassio), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+hassio%22))
First occurred: 10:26:42 PM (2 occurrences)
Last logged: 10:28:23 PM
Failed to to call /addons/d5369777_music_assistant_beta/install - Can't install ghcr.io/music-assistant/server:2.0.0b40: 500 Server Error for http+docker://localhost/v1.42/images/create?tag=2.0.0b40&fromImage=ghcr.io%2Fmusic-assistant%2Fserver&platform=linux%2Farm64: Internal Server Error ("manifest unknown")

### What version of Home Assistant Core are your running

2023.7.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Confirmed. Thanks for the report

**Comment by marcelveldt** [comment]
Github had some hiccups last night so the image building failed for beta40
It is now resolved again
