### ISSUE TITLE
MA Server dont start up Beta40

### ISSUE THREAD

**Issue by collateral87** [music-assistant/hass-music-assistant#1346]
### What version of Music Assistant has the issue?

2.0.0b40

### The problem

The MusicAssistant beta40 server-addon stucks on startup and i could not reach the webUI. Beta39 load without any issues and i could open the webUI.

![grafik](https://github.com/music-assistant/hass-music-assistant/assets/97076257/041d7607-967f-4204-bc74-97b5e5abf080)

### How to reproduce

I uptated to Beta40 and since than, the issue exists.
I tried restarts of core and host and reinstalling the server-addon.

### What version of Home Assistant Core are your running

2023.7.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
The ingress access is temporarily unavailable. You can access the UI on port 8095
