### ISSUE TITLE
MA  no longer play the playlist after the first track is finished 

### ISSUE THREAD

**Issue by molly200** [music-assistant/hass-music-assistant#1349]
### What version of Music Assistant has the issue?

version: "2.0.0b41"

### The problem

After the addon update, playlist stops playing the next track after the first track is finished. Manual track action move to the next track down the list.

### How to reproduce

N/A

### Relevant log output

N/A

### Additional information

Uninstalled and reinstalled the addon with no change

### What version of Home Assistant Core are your running

2023.7.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Confirm if this is still a problem with b43?

**Comment by molly200** [comment]
I can confirm that this is still a problem with b48.

**Comment by molly200** [comment]
Tried to enable "flow mode" in the player's settings and appears to be working...including the loop and random functions!
