### ISSUE TITLE
[v2b43] track preview feature not working for fileprovider

### ISSUE THREAD

**Issue by DutchJaFO** [music-assistant/hass-music-assistant#1352]
### What version of Music Assistant has the issue?

2022.2.43

### The problem

The preview track feature is not working for fileprovider (remote share).
Clicking on the 'play' icon doesn't play music for me.

![image](https://github.com/music-assistant/hass-music-assistant/assets/39138434/995d5ee2-6649-4130-bd4e-21c9bcb19105)

Spotify tracks appear to be working :
![image](https://github.com/music-assistant/hass-music-assistant/assets/39138434/18e05e18-6c67-4d85-900e-9965ea8f1e0c)

### How to reproduce

go to track view of any track in the library
click on the provider icon in the top right of the screen
you will see a bit of information and the track preview feature

clicking on the 'play' button should start playback of the track on your webbrowser
![image](https://github.com/music-assistant/hass-music-assistant/assets/39138434/e37ba779-6162-4823-bf8d-7ecfaadf52fc)

### Additional information

note : I can't see which track version on spotify those two tracks are, although the link will take me there.
Maybe a bit more info ?

### What version of Home Assistant Core are your running

2023.07.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
What IP is that then?

**Comment by marcelveldt** [comment]
this one should be fixed in beta59

**Comment by OzGav** [comment]
Seems to work fine for me. Closing but can reopen if needed.
