### ISSUE TITLE
custom_components.mass.media_player.MassPlayer

### ISSUE THREAD

**Issue by Sarnog** [music-assistant/hass-music-assistant#1356]
### What version of Music Assistant has the issue?

2023.06b0

### The problem

Logger: homeassistant.helpers.entity
Source: helpers/entity.py:371
First occurred: 03:05:46 (6 occurrences)
Last logged: 03:05:46

Entity None (<class 'custom_components.mass.media_player.MassPlayer'>) is implicitly using device name by not setting its name. Instead, the name should be set to None, please report it to the custom integration author.

### How to reproduce

Logger: homeassistant.helpers.entity
Source: helpers/entity.py:371
First occurred: 03:05:46 (6 occurrences)
Last logged: 03:05:46

Entity None (<class 'custom_components.mass.media_player.MassPlayer'>) is implicitly using device name by not setting its name. Instead, the name should be set to None, please report it to the custom integration author.

### What version of Home Assistant Core are your running

2023.7.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by marcelveldt** [comment]
Please install the 2023.6.0b1 version (beta 1) which has this fixed.
