### ISSUE TITLE
[feature request] Receive ICY metadata from radio audio streams

### ISSUE THREAD

**Issue by nagyrobi** [music-assistant/hass-music-assistant#136]
Since the streams on TuneIn are actually created by the radio station operators themselves, and these are in many cases Shoutcast or Icecast streams, containing embedded ICY metadata in the structure of `Artist - Title` or just `Show name`, this could be extracted from the stream if found in it.

A hacky way to extract data can be seen [here](https://github.com/nagyrobi/home-assistant-custom-components-linkplay/blob/7ff9153327296274d4384cb7b31c178634e0a1ca/custom_components/linkplay/media_player.py#L1818). This is far from optimal because it doesn't actually play the stream it just connects to the server and grabs the headers periodically. The correct way would be (and can be done with MA) to get this info from the original stream before transcoding, and that could update metadata in real time.

This is just textual information, and ICY metadata usually don't contain coverart links. So for radio stations one could keep the radio station logo as cover art.

**Comment by marcelveldt** [comment]
Good idea!

This is possible and in fact not that hard. All I have to do is request the ICY-Meta header and parse the packet at each interval. Not something I will do right away but within a few weeks is possible.

**Comment by erkr** [comment]
relates to #126

**Comment by marcelveldt** [comment]
I actually implemented this in the latest beta because it was a real quick win to add to the code as I was already chunking the audio from the radio provider. @nagyrobi you should see a "streamtitle" attribute on the streamdetails object within a queue event. That contains the title as received from the ICY metadata chunk
