### ISSUE TITLE
Can't add Samba share

### ISSUE THREAD

**Issue by mrslvd** [music-assistant/hass-music-assistant#1361]
### What version of Music Assistant has the issue?

The latest BETA 2023.6.b51

### The problem

I can't add Samba share as a provider.
Remote drive is connected to Asus router and allows guest login. For all other devices I am not using user name (leaving the field blank) and pass (leaving the field blank). In MA user must not be left blank and I was trying with Guest or guest.
Home assistant is connecting to it with SMB version 2.0.
All other home devices can connect with no issues to the remote drive.

### How to reproduce

![image](https://github.com/music-assistant/hass-music-assistant/assets/67948421/8c02d864-d5fd-4454-8d46-26f0d0f332a5)
![image](https://github.com/music-assistant/hass-music-assistant/assets/67948421/d8b31708-5e80-4fae-a2c5-a0f4843487ac)
![image](https://github.com/music-assistant/hass-music-assistant/assets/67948421/3a61c55c-4700-4d03-b592-593e9adc8d51)

### What version of Home Assistant Core are your running

2023.7.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Might be because the password is blank but you have supplied a user name?

**Comment by mrslvd** [comment]
Thanks for your reply! I'll try this when I am in home. Just to test it. I prefer not to use this as a final solution because this means one more add-hoc configuration.

**Comment by OzGav** [comment]
I understand. This is not an issue with MA though as the underlying OS is used for this connection.

**Comment by mrslvd** [comment]
I don't have such a problem with Home Assistant itself. After the Home Assistant last update (2023.7.1) guest login is supported by Home Assistant. And I don''t have to create any additional user or configuration but just left User and Password fields empty.

**Comment by mrslvd** [comment]
At the moment I am trying as a music provider already mounted by HASS remote drive and use it as a local disk ( /media/xxx/yyy )
I am not sure whether this is not right or whether adding remote drive in MA is better....

**Comment by OzGav** [comment]
If you already have the drive mounted via HA you should be able to the local disk provider and access it via that

**Comment by marcelveldt** [comment]
> I don't have such a problem with Home Assistant itself. After the Home Assistant last update (2023.7.1) guest login is supported by Home Assistant. And I don''t have to create any additional user or configuration but just left User and Password fields empty.

yes, home assistant supports guest logins and the old, insecure CIFS (smbv1) since the last update. We also support that but you need to manually edit the mount command for that in the advanced section.

**Comment by marcelveldt** [comment]
> If you already have the drive mounted via HA access it via that as it is exactly the same

Mounting it in HA and then accessing it in MA as local folder is perfectly fine and in fine the exact same thing under the hood as using the remote files provider. The remote files provider is mainly there for those who are running Music Assistant as separate docker container (so no HAOS) or just don't want to mount their media files in HA.

**Comment by OzGav** [comment]
You may not have the album artist tag set. Look at the option in the provider

**Comment by OzGav** [comment]
Actually if albums are artists the probably some other tag problem…. we recommend you retag all your music with Picard

**Comment by mrslvd** [comment]
I already retaged files with mp3tag (If needed I can try with  Picard)

**Comment by OzGav** [comment]
Yes you will get way more tag information and it is all standardised…

**Comment by ov1d1u** [comment]
I'm having a similar issue. I cannot connect to my NAS via Samba using a guest user. Using a user and a password works. I get the same error:

> Connection failed for the given details: replace() argument 1 must be str, not None

**Comment by OzGav** [comment]
You have to use a login and password. Also if you want a reply don't post in year old issues. It was lucky I noticed

**Comment by Zockerherz** [comment]
And very important: The password should not contain any specific special characters. Otherwise you will get a connection error. The # worked for me. It is better to start with a simple password with uppercase and lowercase letters and numbers.

I ran into the problem because I have all passwords generated with a password manager.
