### ISSUE TITLE
Config Flow Could Not Be Loaded

### ISSUE THREAD

**Issue by gadgetbazza** [music-assistant/hass-music-assistant#1371]
### What version of Music Assistant has the issue?

2023.2.1

### The problem

Have installed Music Assistant Server without issue and have this running with my Plex library and DLNA clients using the native web interface.

When I try to install the HA integration via HACS, following the restart and then adding the integration, I get an error message as per the thread title and the attached image.

My HA has the internal network set to the internal IP and port over HTTP and the external set to a HTTPS Url.  I am trying to connect all this up on the internal network and can confirm that access to HA on the local network is without issue.

Is there something I am doing wrong as I don't have much opportunity to set any values for the integration, I just get the error.
![Screenshot 2023-07-13 at 14 20 31](https://github.com/music-assistant/hass-music-assistant/assets/99490699/4321f857-73cb-4aef-a5d9-202279d06940)

### How to reproduce

Download Add on via HACS, reboot, try to install integration.

### Relevant log output

Logger: homeassistant.util.package
Source: util/package.py:107 
First occurred: 13:59:51 (3 occurrences) 
Last logged: 14:00:00

Unable to install package music-assistant==1.8.7.4: ERROR: Cannot install music-assistant because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

### Additional information

HA version is 2023.6.2

### What version of Home Assistant Core are your running

2023.6.2

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
You have the incorrect version of the HA integration. Make sure you have selected the show beta option and then install the latest.
