### ISSUE TITLE
HACS - Music Assistant - You are running version 2023.6.0b0, version 2023.6.0b1 is available

### ISSUE THREAD

**Issue by alfwro13** [music-assistant/hass-music-assistant#1372]
### What version of Music Assistant has the issue?

2023.6.0b0

### The problem

After recent update of Music Assistant I noticed a message in HACS saying that there is an update to Music Assistant.
However when I click on it to update nothing happens.
When I go to HACS --> Integrations and click on Music Assistant I get Unknown error message

### How to reproduce

try to update

### Relevant log output

<QueueManager> No manifest.json file found 'custom_components/None/manifest.json'

### Additional information

Tried

### What version of Home Assistant Core are your running

2023.7.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
I have the same problem. I expect it is a HACS problem. I was going to try and uninstall HACS then reinstall it to see if that fixes it but haven’t had time as yet

**Comment by marcelveldt** [comment]
I will publish a new beta version either today or tomorrow, please check if that resolves it. We had some CI issues when releasing the 2023.6.0b1 version so maybe something just messed up in the metadata.

**Comment by alfwro13** [comment]
I don't know if that update was published but my MA HACS integration is still stuck.

**Comment by OzGav** [comment]
No update yet

**Comment by marcelveldt** [comment]
2023.6.0b2 is released, can that be installed ?

**Comment by OzGav** [comment]
No. I’ll have to and reinstall HACS I think

**Comment by alfwro13** [comment]
I have updated the addon to 2.0.0b59 but that made no difference to the HACS integration. Still stuck. On top of that my HA is no reporting this in Repairs:


The Music Assistant server is not the correct version

Check if there are updates available for the Music Assistant Server and/or integration

**Comment by marcelveldt** [comment]
@alfwro13 you need to update the HACS version.... 2023.6.0b2 (and actually b3 already) is available

**Comment by OzGav** [comment]
I’ve opened an issue in HACS https://github.com/hacs/integration/issues/3201#issuecomment-1645273776

**Comment by OzGav** [comment]
I'll followup if I get a response to my HACS issue that I opened but I have now completly deleted and then reinstalled HACS and that has fixed it. Make sure you follow the directions here to uninstall https://hacs.xyz/docs/setup/remove
