### ISSUE TITLE
Failed to load integration (Player has invalid value 'off')

### ISSUE THREAD

**Issue by madtoko** [music-assistant/hass-music-assistant#1373]
### What version of Music Assistant has the issue?

2023.6.b1

### The problem

Failed to load integration when player states is off

### How to reproduce

Restart Home Assistant or switch player to off

### Relevant log output

Logger: homeassistant
Source: lib/python3.11/site-packages/music_assistant/client/players.py:302
First occurred: 08:46:56 (9 occurrences)
Last logged: 08:52:08

Error doing job: Exception in callback Players._handle_event(MassEvent(eve...ra_data': {}}))
Traceback (most recent call last):
  File "<string>", line 62, in from_dict
  File "/data/data/com.termux/files/usr/lib/python3.11/enum.py", line 715, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/enum.py", line 1131, in __new__
    raise ve_exc
ValueError: 'off' is not a valid PlayerState

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/data/data/com.termux/files/home/.hass/lib/python3.11/site-packages/music_assistant/client/players.py", line 302, in _handle_event
    self._players[event.object_id] = Player.from_dict(event.data)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 64, in from_dict
mashumaro.exceptions.InvalidFieldValue: Field "state" of type PlayerState in Player has invalid value 'off'

### What version of Home Assistant Core are your running

core-2023.7.2

### What type of installation are you running?

Home Assistant Core

### On what type of hardware are you running?

Alternative

**Comment by marcelveldt** [comment]
please update the server to the latest version

**Comment by madtoko** [comment]
Hi Marcel, thank you.
My Mass server is 2.0.0 BETA 39, what is Mass server version fix this error please? 
Regards

**Comment by marcelveldt** [comment]
2.0.0 beta 58

**Comment by OzGav** [comment]
We will close this soon unless we hear more.
