### ISSUE TITLE
issue chromecast with 2 zones (Onkyo TX-NR686)

### ISSUE THREAD

**Issue by Maximus48p** [music-assistant/hass-music-assistant#1376]
### What version of Music Assistant has the issue?

2023.6.0b1

### The problem

- it is detecting my TX-NR686
- It detects it only as one zone
- not able to turn on
- not able to play music, even when turning on manually.
 
Been tested directly on URL of Music Assistant Server. So not via HA.

### How to reproduce

fresh install of Music Assistant Server in docker in combination with HACS

### What version of Home Assistant Core are your running

2023.7.2

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
So is it not detecting your main zone? I have a Yamaha and it is only seeing the main zone but if I select that Airplay player the amplifier automatically turns on. Maybe have a look around the amplifier settings to see if that is an option.

**Comment by OzGav** [comment]
just need some more info otherwise we will close this.

**Comment by Maximus48p** [comment]
Unfortunately i'm not able to work on this functionality on a daily basis, will do some more investigation in the next coming weeks. Sorry.

**Comment by OzGav** [comment]
Just following up on this. We will need to close this if we don't hear back soon. Just note that MA doesn't necessarily actually POWER on the device. The power icons in MA should be seen as enable or disable the streaming to the player. Depending on the device you may need to physically power it on first. As I said my Yamaha happens to have the functionality that it will auto power on when it starts receiving a signal

**Comment by OzGav** [comment]
Also unless your receiver can play two different chomsecast streams at the same time then not seeing the second zone is also normal for MA. You need to select the chromsecast input for the second zone via another means and then MA will be heard through that zone.

**Comment by OzGav** [comment]
I believe the above explains what you are seeing the first two points you make in your description of the problem. Unless you can supply more info about what happens when you try and play music to your amp we will close this soon
