### ISSUE TITLE
Track order for multi disc releases on filesystem provider mixes discs

### ISSUE THREAD

**Issue by AvdWerfhorst** [music-assistant/hass-music-assistant#138]
Unfortunately for multi disc releases the default track order seems to be wrong.
![Track order multidisc](https://user-images.githubusercontent.com/35181252/167888180-49a950dd-307d-4087-996c-a9373da1409e.PNG)

**Comment by marcelveldt** [comment]
This should be fixed with the 1.0.17 release, thanks for reporting!
