### ISSUE TITLE
Mapped provider section showing link to local provider

### ISSUE THREAD

**Issue by OzGav** [music-assistant/hass-music-assistant#1382]
### What version of Music Assistant has the issue?

2.0.0b59

### The problem

The mapped provider filesystem entry show a link button which 404s

![IMG_0828](https://github.com/music-assistant/hass-music-assistant/assets/19848947/f7eff5c5-942a-4c93-a492-a34ea5a43744)

### How to reproduce

Navigate to mapped provider section in the frontend. Click on link icon

### What version of Home Assistant Core are your running

202.7.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by marcelveldt** [comment]
fixed in new frontend update (beta 60)
