### ISSUE TITLE
Config-flow error can't be load

### ISSUE THREAD

**Issue by AFPhome** [music-assistant/hass-music-assistant#1386]
### What version of Music Assistant has the issue?

2023.2.2

### The problem

Error message
Config-flow can't be load.
500 internal server error git itselfs in trouble.

Don't know what this means and how to solved it.
Anyone ideas?

### How to reproduce

When add intergation.

### What version of Home Assistant Core are your running

Last one

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by marcelveldt** [comment]
read the readme maybe ?
you need to install the BETA version on recent HA installs

**Comment by Shaunpottie** [comment]
Same error with Beta

**Comment by OzGav** [comment]
Are you sure you are installing the beta version of the integration via HACS? Please provide a screenshot of the screen where you select the version to install

**Comment by dNsl9r** [comment]
I also do have problems using the current Beta (2023.6.0b3). Log:

> Logger: homeassistant.util.package
> Source: util/package.py:108
> First occurred: 14:53:40 (3 occurrences)
> Last logged: 14:53:59
> 
> Unable to install package music-assistant==2.0.0b59: ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them. music-assistant==2.0.0b59 from https://files.pythonhosted.org/packages/03/aa/514891dfa8f7e0405839ebe4c476ada92081c451b268bf8c8dd994a06f19/music_assistant-2.0.0b59-py3-none-any.whl: Expected sha256 9ec0fa5fe810a2942f4e3b97b791a913ea4c43ecbbc0d7311c9a72fd21b52743 Got 16563b66f8870bee4363db9ce8d62c928b7660d461cb812337e650afcc226df5 [notice] A new release of pip is available: 23.1.2 -> 23.2.1 [notice] To update, run: pip install --upgrade pip

With Beta 2023.6.0b2 this error does not occur, but I get the following:

> Failed to install the Music Assistant Server add-on: Can't install ghcr.io/music-assistant/server:2.0.0b73: 404 Client Error for http+docker://localhost/v1.42/images/ghcr.io/music-assistant/server:2.0.0b73/json: Not Found ("No such image: ghcr.io/music-assistant/server:2.0.0b73")

I am running HA:
Home Assistant 2023.9.3
Supervisor 2023.09.2
Operating System 10.5
Frontend 20230911.0 - latest

Running on a Dell OptiPlex 7040 with Win 10 Pro in an Oracle VirtualBox virtualization.

**Comment by OzGav** [comment]
We only offer limited support for non HAOS install but try  and install the server first directly through the add ons page. (That first error is odd as it is trying to install an old version of the server?)

**Comment by dNsl9r** [comment]
Will try that, thanks 👍🏻
