### ISSUE TITLE
not working whn i try to install that

### ISSUE THREAD

**Issue by The-cpu-max** [music-assistant/hass-music-assistant#1394]
### What version of Music Assistant has the issue?

the new ver

### The problem

![image](https://github.com/music-assistant/hass-music-assistant/assets/102416233/3dcd57fd-e5d7-4edf-8319-11c9c3507cd6)
![image](https://github.com/music-assistant/hass-music-assistant/assets/102416233/ef5089b1-f2d0-4bc2-baa2-7d66dbcdcc1c)

### How to reproduce

It is not clear why, but the entire error message is empty without content
And I can't move forward either

### Additional information

What else do I need to do?

### What version of Home Assistant Core are your running

10.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Windows

**Comment by OzGav** [comment]
Firstly is the music assistant addon installed under SETTINGS>>ADDONS?

Then have you installed the BETA version of the HA integration via HACS?

it isn’t clear from your screenshots or description what you have done so far
