### ISSUE TITLE
Filesystem and Spotify Linking Error

### ISSUE THREAD

**Issue by OzGav** [music-assistant/hass-music-assistant#1399]
### What version of Music Assistant has the issue?

2.0.0.b60

### The problem

MA has linked a live version of a song to the original and overridden the track name on the original album

![image](https://github.com/music-assistant/hass-music-assistant/assets/19848947/45d9bdd0-216f-4c8e-b3b4-1eb443d439af)

### How to reproduce

I had the local albums successfully loaded in MA. Browsing through Spotify I noted a live album I liked and so added it to the library. Suubsequently when viewing the original album I noticed the track name had been changed to the live version. Playing the track from the original album plays the original track from disk however trying to play the live version also results in playing the original track from disk :-( This occurs even if I change the filter toggle at the top to Spotify. (I can tell immediately because when playing FLAC is shown)

### What version of Home Assistant Core are your running

2023.7.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by marcelveldt** [comment]
It must have done this for a reason. Normally this is 100% not possible. 
Look at the tags, what isrc or musicbrainz id is there ? 

And was the track on disk really not the live version ?

**Comment by OzGav** [comment]
Correct it is the original album recording. Same thing happened on the Greatest Hits album as well.

**Comment by OzGav** [comment]
From Picard the track:
![image](https://github.com/music-assistant/hass-music-assistant/assets/19848947/f12397ad-f378-4aa1-8a36-418e2423e26b)

Can I get the ISRC from Spotify?

**Comment by marcelveldt** [comment]
Did you check the MB id and isrc's it collected against the Musicbrainz db ?

**Comment by OzGav** [comment]
Noob question: How di I do that?

**Comment by OzGav** [comment]
This is what MB has for the live track 
![image](https://github.com/music-assistant/hass-music-assistant/assets/19848947/280af4ea-5b86-40a8-8e2e-50a20d41505d)

**Comment by marcelveldt** [comment]
hmm so it seems that it indeed linked the wrong version. Question now is how. Can you PM me this album/file so I can try to repro ?

**Comment by OzGav** [comment]
Here is the Spotify album link https://open.spotify.com/album/4zziqp3wOBkfWmxwlILVBZ

I have put four files in your Google Drive. Tracks 1-3 are from the Greatest Hits Volume 3 album and track 4 is from his Stranger album. All of these have been linked to the Spotify album and the name of all of them has been changed to the Live version but all of them including the Spotify album actually play the local track.

**Comment by marcelveldt** [comment]
Thanks, this was a tough one to crack but I managed to reproduce it and finally find the cause. Will be fixed in next beta release.

**Comment by OzGav** [comment]
Excellent!
