### ISSUE TITLE
minor visual darkmode glitch

### ISSUE THREAD

**Issue by da-anda** [music-assistant/hass-music-assistant#1405]
### What version of Music Assistant has the issue?

2023.6.0b3

### The problem

When using a dark theme, some elements (icons, text) in the lower playback bar have the wrong color and are barely readable.

![grafik](https://github.com/music-assistant/hass-music-assistant/assets/1159249/cecb7f24-5404-4bc6-ad9c-42c4dacf5a83)

I tried to report it in the frontend repo, but issues are disabled on that repo, so I hope reporting it here is ok.

### How to reproduce

switch to a dark theme

### What version of Home Assistant Core are your running

2023.07.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by marcelveldt** [comment]
please join our discord channel if you want, things like this have been discussed there too.
The frontend is being worked on atm and has a few glitches which will be resolved in next version(s).

To respond to this specific issue report: yes, it's a known issue and fixed in next version.

**Comment by da-anda** [comment]
thanks, feel free to close the issue then.

**Comment by marcelveldt** [comment]
Regardless thanks for taking the time to report the issue and get involved. Let us know if you may still find glitches after next release.
