### ISSUE TITLE
Database problem when removing a track from library and re-adding

### ISSUE THREAD

**Issue by OzGav** [music-assistant/hass-music-assistant#1406]
### What version of Music Assistant has the issue?

2.0.0b60

### The problem

When removing a local track from the database there is some problem when it is re-added. It reappears in the album view but when viewing the artist track list the re-added track appears athe bottom of the list (when sorting by album) instead of with the other tracks in the album. 

Additionally, doing a resync doesn't bring the track back I had to browse for it?

### How to reproduce

Go to ARTIST>>TRACKS and select SORT BY ALBUM (Use an artist which has more than one album)
Remove from the library a local track from an album (not the last album in the list)
Observe that the track is now gone from the ARTIST>>TRACKS LIST
Go to SETTINGS>>FILESYSTEM PROVIDER and select SYNCHRONISE NOW
Observe that the track is still gone from the ARTIST>>TRACKS LIST
Go to BROWSE>>FILESYSTEM>>ARTIST(as selected)>>ALBUM(as selected)
Go back to ARTIST>>TRACKS LIST and observe that the track has returned but is at the bottom of the list and not with the rest of the tracks in the album
Select the offending track and SHOW INFO and View the ALBUM. Observe that the track is correctly listed in the album

### What version of Home Assistant Core are your running

2023.7.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by wr420** [comment]
I'm also having a similar problem.  On the latest HAOS and MA.  Decided to retag LOTS of music so I copied it all out of the NAS music directory and retagged the first few directories and then copied back only the freshly "tagged with Pickard" files.
I have tried to re-synchronize and reload, reboot etc.  All the old music still shows in MA. with paths to the deleted files.  Browse filesystem shows the correct folders/music.
