### ISSUE TITLE
Setting song to repeat only plays twice

### ISSUE THREAD

**Issue by Tekno-man** [music-assistant/hass-music-assistant#1412]
### What version of Music Assistant has the issue?

2.0.0b61

### The problem

When playing a song either through music assistant add on or through a home assistant script when selecting single song loop or play list loop the song only plays twice the stops. This has been tried on multiple nest speakers and displays. 

### How to reproduce

Select one song, play song on a target device with loop option selected song only plays twice m

### What version of Home Assistant Core are your running

2023.7.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Can't confirm. I added a single 10sec long MP3 to my queue and it continued to loop correctly and eventually stopped when I selected loop off using the icon at the bottom of the UI?

**Comment by Tekno-man** [comment]
What media player was this on? Could it be a nest speaker only issue?

**Comment by Tekno-man** [comment]
Reassuring that it isn't just me. Thanks for looking into it.

**Comment by marcelveldt** [comment]
this should be fixed in the next beta (b64) but please re-test.

**Comment by OzGav** [comment]
yes fixed

**Comment by Tekno-man** [comment]
Thanks so much, works great. Cheese
