### ISSUE TITLE
Media_Players from Fully Kiosk Browser are not listed.

### ISSUE THREAD

**Issue by pickonedev** [music-assistant/hass-music-assistant#1419]
### What version of Music Assistant has the issue?

2.0.0b61

### The problem

media_player entities from Fully Kiosk Browser are not seen by Music Assistant
these entities support playing URL's with mp3 files
If I use Standard Media Services from Home Assistant, I can play through these entities with no problem

### How to reproduce

Install Fully Kiosk Browser Integration and use it with a device.

### What version of Home Assistant Core are your running

2023.7.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Only certain player types are supported natively. Please see the docs. If you want to add to the player provider poll to try and get some support from others to get this included you can do so here https://github.com/orgs/music-assistant/discussions/1200
