### ISSUE TITLE
b62 Frontend Scroll Bar Goes Too Far

### ISSUE THREAD

**Issue by OzGav** [music-assistant/hass-music-assistant#1423]
### What version of Music Assistant has the issue?

2.0.0b62

### The problem

When pulling down on the scroll bar in a view, in order to show the very ast item in the view the bar has to almost fully disappear behind the player controls at the bottom. I would expect the bar would finish at the top of the controls.

### How to reproduce

Scroll all the way to the bottom of your view and the bar has to disappear behind the player row in order to see the final entry

![image](https://github.com/music-assistant/hass-music-assistant/assets/19848947/36265433-a022-4693-9942-4cf56636c443)

### What version of Home Assistant Core are your running

2023.7.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by marcelveldt** [comment]
Who still uses the scrollbar nowadays ? Don't we all just scroll or swipe ? :-)

I believe this issue is unavoidable as that is the way modern web frameworks work with manipulating the DOM to fill in the content. At least I do not have a single clue to fix it

**Comment by OzGav** [comment]
Ok it still works so all good.
