### ISSUE TITLE
Tidal - Track functions missing when using Mobile Version (porttrait mode only)

### ISSUE THREAD

**Issue by oneofthemany** [music-assistant/hass-music-assistant#1429]
### What version of Music Assistant has the issue?

2.0.0b63

### The problem

Image below shows no previous or next track option - only play/pause:

![image](https://github.com/music-assistant/hass-music-assistant/assets/44924639/4040fab0-21e1-4739-9530-60b3198355aa)

### How to reproduce

Open mobile version in portrait orientation

### Additional information

Everything is fine with in landscape:

![image](https://github.com/music-assistant/hass-music-assistant/assets/44924639/3a462dbb-8ca3-4bf7-96da-6eb1b3bc6ef8)

### What version of Home Assistant Core are your running

2023.7.3

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
I believe this is by design as there isnt enough space in portrait

**Comment by OzGav** [comment]
You just have the ability to play and pause

**Comment by oneofthemany** [comment]
so you couldn't have a top and a bottom, and have the Media info at the top and the functions on the bottom???

**Comment by OzGav** [comment]
Feel free to open a discussion and see if you get traction by anyone else there but as this is by design it is not an issue.

**Comment by oneofthemany** [comment]
> Feel free to open a discussion and see if you get traction by anyone else there but as this is by design it is not an issue.

No worries

**Comment by marcelveldt** [comment]
@oneofthemany did you already discover that you can simply click the thumb image ?
That will show a full screen player with all controls

**Comment by oneofthemany** [comment]
> @oneofthemany did you already discover that you can simply click the thumb image ?
> That will show a full screen player with all controls

I have now haha

Thanks
