### ISSUE TITLE
Album art overwritten incorrectly

### ISSUE THREAD

**Issue by OzGav** [music-assistant/hass-music-assistant#1437]
### What version of Music Assistant has the issue?

2.0.0b67

### The problem

I am yet to see if it is easily reproducible as I was creating a playlist and doing lots of global searches and clicking in an out of tracks to find th eone I wanted to add. Then I identified a song I though maybe I had locally so I clicked through the Artist view to the Beach Boys and noticed that some album thumbs were changed to that of albums I had seen during the global search. See below the Forrest Gump Soundtrack thumb and two tracks from Summer Dreams have been changed.

![image](https://github.com/music-assistant/hass-music-assistant/assets/19848947/082f9c95-4c5c-47a8-86da-aeff6975d7b8)

However, when I SHOW INFO on Sloop John B. I see this correct thumbs?

![image](https://github.com/music-assistant/hass-music-assistant/assets/19848947/3a527f1e-610f-4b90-9aa7-9a11ea12fd6a)

### How to reproduce

Likely it is browse through a streaming provider and select Artists or Tracks that are available locally and observe an eventual change of some local thumbs. 

### What version of Home Assistant Core are your running

2023.8.0

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Actually I just looked again and saw one track that has had its album thumb overwrriten by another local album. See "Good Vibrations" but note there are lots of others that are unchanged as well.

![image](https://github.com/music-assistant/hass-music-assistant/assets/19848947/1d36ae99-d92a-4b07-8a7c-a72a5e78a178)

**Comment by marcelveldt** [comment]
I can see what's going on here... the track itself has an image in these cases and that has preference over any album cover.
What level is this ? Main tracks listing or artist level ?

**Comment by OzGav** [comment]
It was Artist level

**Comment by marcelveldt** [comment]
Fixed in next version

**Comment by OzGav** [comment]
Sorry @marcelveldt seems worse. Most tracks have no thumb displayed and those that do are mostly incorrect 

![IMG_0841](https://github.com/music-assistant/hass-music-assistant/assets/19848947/dcc1616a-4ab2-4521-9cb1-5ac83eca4505)
