### ISSUE TITLE
Error trying to seek from the mass media player

### ISSUE THREAD

**Issue by jhansche** [music-assistant/hass-music-assistant#1439]
### What version of Music Assistant has the issue?

2.0.0b68

### The problem

Trying to seek on the media player card results in an error toast and no change in playback.

### How to reproduce

1. Begin playing media on a player.
2. From the Lovelace card, attempt to seek to any position on the seek bar.
3. Observe error toast.

### Relevant log output

```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/mass/media_player.py:284
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 10:41:58 PM (1 occurrences)
Last logged: 10:41:58 PM

[139790677464128] Value 48.421487603305785 of type <class 'float'> is invalid for position, expected value of type <class 'int'>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 226, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1974, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2011, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 870, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 942, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/mass/media_player.py", line 284, in async_media_seek
    await self.mass.players.queue_command_seek(queue.queue_id, position)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/client/players.py", line 239, in queue_command_seek
    await self.client.send_command("players/queue/seek", queue_id=queue_id, position=position)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/client/client.py", line 168, in send_command
    return await future
           ^^^^^^^^^^^^
music_assistant.common.models.errors.MusicAssistantError: Value 48.421487603305785 of type <class 'float'> is invalid for position, expected value of type <class 'int'>
```

### Additional information

This may also be why tts.speak does not properly resume where the player left off, as documentation implies it should?

### What version of Home Assistant Core are your running

2023.8.0

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by jhansche** [comment]
Looking further, I see that the media player seek service schema, as well as the MediaPlayerEntity seek functions, all expect a float, but both the mass entity and the mass client are declaring the position arg as int. The media player entity signature has been float since 3 years ago, so I don't think this is new.

https://github.com/home-assistant/core/blob/0cc80a9d29962341e45910e1edc7a594704e513a/homeassistant/components/media_player/__init__.py#L770
https://github.com/home-assistant/core/blob/0cc80a9d29962341e45910e1edc7a594704e513a/homeassistant/components/media_player/__init__.py#L360
https://github.com/music-assistant/hass-music-assistant/blob/02ef835330103b281ced6140694753380e8b3efc/custom_components/mass/media_player.py#L286

**Comment by derandiunddasbo** [comment]
Same here.

> Looking further, I see that the media player seek service schema, as well as the MediaPlayerEntity seek functions, all expect a float, but both the mass entity and the mass client are declaring the position arg as int. The media player entity signature has been float since 3 years ago, so I don't think this is new.

The data type doesn't seem to have changed recently in MASS as well. Strange...

On the other hand, the HA media player documentation states, that the "format is platform dependent". In this context I assume "platform" means the integration providing the media player entity. The term "format" is also a bit ambiguos but when reading it as a developer, I'd read this as this attribute's data type is defined by the integration and not hard coded as float by HA:

<html>
<body>
<h4 style="box-sizing: border-box; margin: 2em 0px 1.5rem; padding: 0px; font-size: 1.1rem; line-height: 1.2; color: rgb(34, 34, 34); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(245, 245, 245); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Service media_player.media_seek</h4>

Service data attribute | Optional | Description
-- | -- | --
entity_id | yes | Target a specific media player. To target all media players, use all.
seek_position | no | Position to seek to. The format is platform dependent.


</body>
</html>

**Comment by marcelveldt** [comment]
Probably a bug that has always been there, there is still a lot to improve on the HA integration. Will get a bit more focus in a few weeks. First some more important bugs in the server to fix.

Looking at the log the fix can be as simple as coercing into an int

**Comment by OzGav** [comment]
@derandiunddasbo Marcel always welcomes PRs to help out…

**Comment by jhansche** [comment]
> The term "format" is also a bit ambiguos but when reading it as a developer, I'd read this as this attribute's data type is defined by the integration and not hard coded as float by HA

I agree it's confusing and ambiguous. But the data type actually is defined by HA (float). What they may be referring to, is that the definition of "position" may be integration dependent. For example, whether it expects a 0-100 (%), vs seconds, vs ms, etc.

@OzGav yup, I was planning to get to it, but I always open an issue first, in case someone else gets to it first.

**Comment by jhansche** [comment]
In preparing a PR for this, would it be best to ignore HA's preference for `float` and just cast it to `int` before sending it to the client? Or would it be better to update the rest of the pipeline as well, including `client.players.queue_command_seek()`, `player_queues.seek()`, and `player_provider.cmd_seek()`?

Just casting to int from the integration would be extremely easy to do, but loses that additional precision (i.e., cannot seek to sub-second locations). Obviously not all providers may be able to handle sub-second seeking, but that seems like something that could be handled on a per-provider basis rather than truncating it everywhere, which feels to me like a more appropriate fix.

I have local mods prepared for both, so it's not a big deal either way. In the stacktrace, the error is not being raised at the `mass/media_player.py` layer on the integration (so it's not an issue with HA or python), but instead it's interpreted by `parse_value` on the server, and that's where it rejects the incoming float argument due to the server's signature of player_queues.seek(). Oddly enough however, we still then go on to cast the position to int anyway, in `play_index()`.

Final question, what's the best way to test a change to the add-on? I haven't done much work on add-ons.

**Comment by marcelveldt** [comment]
I would just cast to int in the HA integration. The seek is not sub-second accurate anyway. If somebody gets bored at some day we could adjust the entire stack into 10th of seconds precise seeking but for now there are other nuts to crack imo.

As you are the first one to notice the seek not working, we know that tells how much seeking is actually used by people...

**Comment by jhansche** [comment]
Fair enough 😂  I wasn't even really trying to seek, per se, from the card. This was something I started looking into because I was testing a tts.speak on the playing speaker, and instead of resuming like I expected it to, it restarted the entire queue (not even just the current song, it went all the way back to the first song). So from that I tested out seeking from the card, and saw the error.

**Comment by marcelveldt** [comment]
Yeah, sending "announcements" with TTS is a more urgent matter to implement. I prepared some stuff but it's far from finished. I have in mind to look at that somewhere in the next few days, probably I can just restore what we had in V1

**Comment by dominiclesinski** [comment]
seems this is broken again fyi. HA native media player shows the position bar but doesn't allow seeking and mini-media-player allows seeking but fails with failed to call service media_player/media_seek reporting that the MASS player doesn't support that functionality. 

`Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:241
integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 9:15:35 AM (6 occurrences)
Last logged: 4:35:10 PM

[140302500297120] Unexpected exception
[140302482900736] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 241, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2731, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2774, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 981, in entity_service_call
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity media_player.buro does not support this service.`
