### ISSUE TITLE
Log reports on Missing ID3 tag, but is there any way to handle that more gracefully? 

### ISSUE THREAD

**Issue by adekloet** [music-assistant/hass-music-assistant#1440]
### What version of Music Assistant has the issue?

2.0.0b67 

### The problem

I see a lot of my local stored music is missing ID3 tags and it's reported in the log. Is there a way for music assistant to alert me in the front-end to go an fix those issues? (either by using external sotware or adding it via music assitant)?

Any insights on this one (forgive me beeing a apprentice at music assistant)?

Running as an add-on on HA 2023.8.0 Pi4 with a fairly large local music library (> 40.000 files)

### How to reproduce

Index music with missing ID3 tags

### Relevant log output

 File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/filesystem_local/base.py", line 719, in _parse_track
    raise InvalidDataError("missing ID3 tag [albumartist]")
music_assistant.common.models.errors.InvalidDataError: missing ID3 tag [albumartist]
2023-08-04 10:10:36.251 ERROR (MainThread) [music_assistant.providers.filesystem_local] Error processing Muziek/Peter_Cetera/One_More_Story/01-Best_Of_Times.mp3 - missing ID3 tag [albumartist]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/filesystem_local/base.py", line 347, in sync_library
    track = await self._parse_track(item)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

### What version of Home Assistant Core are your running

2023.8.0

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Yes. Look in the advanced settings for the provider

**Comment by adekloet** [comment]
Thanks @OzGav I don't see any advanced settings under the providers except for the log levels. I will have a look at Picard, thanks for that, for now it's still indexing and using filename etc. as explained in the readme.

**Comment by OzGav** [comment]
We are talking about the filesystem providers. These are the advanced options
![IMG_0847](https://github.com/music-assistant/hass-music-assistant/assets/19848947/1b2601b6-e12a-45c1-b45f-03eafa042471)
