### ISSUE TITLE
I am getting a Login Failure everytime I click Home Icon 

### ISSUE THREAD

**Issue by jweston2112** [music-assistant/hass-music-assistant#1441]
### What version of Music Assistant has the issue?

2.0.0b68

### The problem

I get a login failure when I click the Home Icon (Top icon)

### How to reproduce

See the problem... above

### Relevant log output

```
Logger: homeassistant.components.http.ban
Source: components/http/ban.py:82
Integration: HTTP (documentation, issues)
First occurred: 7:05:12 AM (2 occurrences)
Last logged: 8:13:57 AM

Login attempt or request with invalid authentication from 143.55.XXX.XXX (143.55.XXX.XXX). Requested URL: '/media/local/Music/Rush/The_Spirit_of_Radio-_Greatest_Hits_1974%E2%80%931987/(01)_Working_Man.mp3'. (Lavf/59.27.100)

```

### What version of Home Assistant Core are your running

Home Assistant 2023.8.0 Supervisor 2023.08.0 Operating System 10.4 Frontend 20230802.0 - latest

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Please check  again with HA 2023.8.x and MA 2.0.0b69 or higher

**Comment by marcelveldt** [comment]
This is the auth security mechanism of HA kicking in due to invalid file characters. Can you check the file below what characters it has:

/media/local/Music/Rush/The_Spirit_of_Radio-_Greatest_Hits_1974%E2%80%931987/(01)_Working_Man.mp3

**Comment by jweston2112** [comment]
Thanks for getting back to me .... 
Do you mean in the File Name? or In a MP3 tag... 

I updated to Beta69 and it still does it.       

It looks good so far... I have been watching since beta 1

**Comment by marcelveldt** [comment]
The actual filename, can you have a look what is so special about it ?

**Comment by OzGav** [comment]
I wonder if it is the %e2%80%93 can you just change that to a - instead?

**Comment by jweston2112** [comment]
Well  I renamed the folder.... I actually removed the "_1974%E2%80%931987" part of the folder name and it still did gave me the login error .... not sure how to make the application refresh.... 

would having a Self Signed Certificate for the Local Address have an effect ?

**Comment by OzGav** [comment]
Yes it could. See the second last item here https://github.com/orgs/music-assistant/discussions/710#discussion-4240092

**Comment by OzGav** [comment]
The frontend is being progressively updated and things are being tried and changed. Seems like this issue has resolved so I will close this.
