### ISSUE TITLE
Some files just wont play

### ISSUE THREAD

**Issue by digginsa** [music-assistant/hass-music-assistant#1448]
### What version of Music Assistant has the issue?

2.0.0b69

### The problem

When I add some files no matter what I do they will not play, however if i choose the files directly from Home Assistant media they do play. 

### How to reproduce

Added files to remote share, select file to play but nothing happens

### Relevant log output

File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/filesystem_local/base.py", line 412, in get_track
    return await self._parse_track(file_item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/filesystem_local/base.py", line 698, in _parse_track
    raise InvalidDataError("missing ID3 tag [albumartist]")
music_assistant.common.models.errors.InvalidDataError: missing ID3 tag [albumartist]
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/webserver.py", line 372, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 197, in play_media
    raise MediaNotFoundError(f"Invalid uri: {item}") from err
music_assistant.common.models.errors.MediaNotFoundError: Invalid uri: filesystem_smb://track/Ray Wilson/RayVent 2004/03 Fading Lights (live).mp3

### What version of Home Assistant Core are your running

2023.7.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Looks like you might have errors in your tags. Please retag your music preferably with Picard. This will give you the best experience with MA as it needs this information to work best. If for some reason you don’t want to do that you can change the way missing album artist tags are handled in the advanced settings for the filesystem provider.

**Comment by OzGav** [comment]
Please let me know if retagging fixes this so I can close this issue...
