### ISSUE TITLE
v1.0.17 - double left hand menus

### ISSUE THREAD

**Issue by vk2him** [music-assistant/hass-music-assistant#145]
![Screen Shot 255](https://user-images.githubusercontent.com/22878629/167993209-d4f9a074-85ef-4071-8d85-7f992477b204.jpg)

Per the above screenshot, a double left hand menu displays if you follow these steps:

1. Click Music Assistant in left menu
2. Click on Album,Artists or Tracks
3. Click the back arrow next to Album,Artists or Tracks

![Screen Shot 258](https://user-images.githubusercontent.com/22878629/167993860-227f312b-0c7f-481a-b88f-fdc3005191be.jpg)

4. Click arrow next to Music Assistant

![Screen Shot 257](https://user-images.githubusercontent.com/22878629/167993640-04a7ba0a-28ef-4d6b-a8ca-e5df24bab449.jpg)

5. Double menu is displayed

![Screen Shot 259](https://user-images.githubusercontent.com/22878629/167993964-e13bcb05-8d10-4dd1-894b-e983f4b72483.jpg)

**Comment by marcelveldt** [comment]
see this one: #73

**Comment by vk2him** [comment]
#73 is a different problem?

**Comment by marcelveldt** [comment]
Nope it is a side effect of the current workaround.

**Comment by vk2him** [comment]
Refer #73
