### ISSUE TITLE
Unable to "Add to Playlist" from "Appears On" section of track view

### ISSUE THREAD

**Issue by OzGav** [music-assistant/hass-music-assistant#1450]
### What version of Music Assistant has the issue?

2.0.0b70

### The problem

When selecting SHOW INFO for a track the resulting view does not have an option in the menu for add to playlist for the APPEARS ON tracks. The option is there in the OTHER VERSIONS 

### How to reproduce

As above

### What version of Home Assistant Core are your running

2023.8.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by JeffersonBledsoe** [comment]
@OzGav Just to confirm, do you mean that the overflow 'three dots' menu that appears just below the title of the page after pressing "Show info" doesn't (1st image shown below) include "Add to playlist" but the overflow menu for a track that is in the "Tracks" list does (2nd image below)?

<img width="968" alt="" src="https://github.com/music-assistant/hass-music-assistant/assets/30210785/0cd03000-69d5-45de-92e7-bef3a29b2759">

<img width="968" alt="track-menu" src="https://github.com/music-assistant/hass-music-assistant/assets/30210785/de353c4e-c02a-4c7c-bac6-7b2f4c4d947e">

**Comment by OzGav** [comment]
Option C
![image](https://github.com/music-assistant/hass-music-assistant/assets/19848947/5b68f89c-79dd-4e52-9ed6-175d7512c774)

You then see this:
![image](https://github.com/music-assistant/hass-music-assistant/assets/19848947/c015c850-d6c9-45e1-831e-cd38c1608707)

But if you right click on the next section down which is OTHER VERSIONS you see 

![image](https://github.com/music-assistant/hass-music-assistant/assets/19848947/e739d6b8-f89e-430e-86cf-319241b6506b)

**Comment by OzGav** [comment]
So from image you pasted click on the overflow menu on the far right of the track name and SHOW INFO

**Comment by JeffersonBledsoe** [comment]
@OzGav Looks like this behaviour is intentional, so you can only add a single track to a playlist. "Appears on" only shows the albums a track appears on so it'll never show the "Add to playlist" button. Do we want a similar functionality to Spotify where it will add all tracks from an album into a playlist maybe?

**Comment by OzGav** [comment]
🤦‍♂️ of course. I couldn’t see the forest for the trees! Let’s leave this particularly as I am not sure the backend allows adding an album to a playlist yet.
