### ISSUE TITLE
No Devices and entities - configuration not possible

### ISSUE THREAD

**Issue by Romero-KCBS2003** [music-assistant/hass-music-assistant#1454]
### What version of Music Assistant has the issue?

2023.6.0b3

### The problem

I installed the "Music Assistant" via HACS and added the integration. This also worked without any problems. Unfortunately, no devices or entities are displayed to me.
Likewise, "Music Assistant" is not displayed to me in the sidebar.

![image](https://github.com/music-assistant/hass-music-assistant/assets/135272332/90a3617a-8281-45ff-a285-a44a6ac6eedb)

![image](https://github.com/music-assistant/hass-music-assistant/assets/135272332/0d545c3e-958b-4109-bff1-e6ba042bd52a)

After the successful confirmation, nothing comes to the setup.

![image](https://github.com/music-assistant/hass-music-assistant/assets/135272332/96c80107-c5cd-4139-82b6-8a05f72c4381)

I don´t know what went wrong or where the problem is.

Best regards

### How to reproduce

reinstall 

### What version of Home Assistant Core are your running

2023.8.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Please all the info here on GitHub. Have you installed player providers? Read the How To which explains how get MA on the sidebar.
