### ISSUE TITLE
Squeezelite player display suddenly useless

### ISSUE THREAD

**Issue by wryandginger** [music-assistant/hass-music-assistant#1455]
### What version of Music Assistant has the issue?

2.0.0b70

### The problem

Since I updated to 2.0.0b70 from 68 the display on my squeezelite devices only display the IP address of the MA server. 

Previous versions would show Artist-Title and a visualizer on the display. BT, AirPlay, and Spotify show correct metadata.

### How to reproduce

Update MA2.0 to the most recent version, play a track or a radio station. Display doesn’t change from: 192.168.68.100:8096

### What version of Home Assistant Core are your running

2023.8.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Have you tried restarting MA or rebooting the host?

**Comment by wryandginger** [comment]
Yes, I've tried both. No change after a full restart of the host.

These are ESP32-A1S SqueezeESP32 boards to be specific (Firmware: squeezelite-esp32-master-v4.3-I2S-4MFlash-16-21335)

**Comment by OzGav** [comment]
Ok will have to wait and see if this can be replicated as I don’t have one of these devices.

**Comment by eavyon** [comment]
Today I connected a display to the Muse Luxe with squeezelite 2.1652-16#v4.3#Muse#master-v4.3. Tested it with bluetooth and airplay which displays correctly. Does not work with slimproto and only show double characters on one line. MA2.0.0b75

**Comment by OzGav** [comment]
Is this still a problem?

**Comment by OzGav** [comment]
We will close this soon due to no followup
