### ISSUE TITLE
Keep getting an error when installing

### ISSUE THREAD

**Issue by Shaunpottie** [music-assistant/hass-music-assistant#1459]
### What version of Music Assistant has the issue?

2023.2.2

### The problem

Added music assistant via HACS rebooted, tried installing and just get this error.

Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

I'm following "The Bearded Tinkers YT Video"

### How to reproduce

I'm following "The Bearded Tinkers YT Video"

### What version of Home Assistant Core are your running

2023.8.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by gieljnssns** [comment]
https://github.com/music-assistant/hass-music-assistant/issues/1386#issuecomment-1645669146
