### ISSUE TITLE
[feature request] send commands to MA queues 

### ISSUE THREAD

**Issue by marcelveldt** [music-assistant/hass-music-assistant#146]
For player integrations (or other integration) that want to interact with MA and it's playerqueues it would be nice they are able to send commands to MA, e.g. through eventbus.

**Comment by nagyrobi** [comment]
Like Next/Prev, Seek, set Shuffle/Repeat etc.

**Comment by marcelveldt** [comment]
I have just implemented this so it will be included in next release.
Implemented as service to make it more universal (and events are meant to signal events, not send commands).

Service can be called from HA frontend/automations etc. or from other integrations.

![Schermafbeelding 2022-05-17 om 12 55 44](https://user-images.githubusercontent.com/6389780/168795613-174b6b19-0e45-4491-9db6-3c0d26dd0b54.png)

**Comment by marcelveldt** [comment]
From a (media_player) integration use:

`await hass.services.async_call(
           "mass","queue_command", 
           service_data = {
               "entity_id": "media_player.yourplayer",
               "command": "play_media",
                "uri": "spotify/playlist/aabbccddee",
                "mode": "play_media_play_now"
            }
        )`


`uri` and `mode` are optional parameters

**Comment by nagyrobi** [comment]
we would need also `seek` to position...

**Comment by marcelveldt** [comment]
> we would need also `seek` to position...

https://github.com/music-assistant/hass-music-assistant/issues/147

**Comment by nagyrobi** [comment]
how do we set shuffle and repeat? what are the parameters?

**Comment by marcelveldt** [comment]
Look in the developer tools (when the new version is released), all options are listed there....

![Schermafbeelding 2022-05-17 om 14 17 32](https://user-images.githubusercontent.com/6389780/168808937-ab430c98-e99a-4dd0-ba08-7e955c3232bd.png)
