### ISSUE TITLE
Music Assistant Addon starts automatically.

### ISSUE THREAD

**Issue by nehasjains** [music-assistant/hass-music-assistant#1474]
### What version of Music Assistant has the issue?

2.0.0b72

### The problem

I have disabled auto start of the Music Assistant addon.

But still the addon automatically starts on every reboot.

Even if I manually stops the addon, it starts again after few seconds.

I have already tried reinstalling the addon after still is starts automatically. I have disabled "Start on boot".

Kindly help

### How to reproduce

Disable "Start on boot" 

Start the addon, wait for few seconds, stop the addon.

Go back to main page. Come back to addon page the addon would be still running or it gets auto start

### What version of Home Assistant Core are your running

2023.8.2

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Sounds like an OS problem? Do other addons behave the same way?

**Comment by nehasjains** [comment]
No, just this one.

**Comment by marcelveldt** [comment]
Disable the HA integration

**Comment by nehasjains** [comment]
> Disable the HA integration

You are right disabling the integration doesn't start the addon automatically. But this shouldn't happen right ? 

I have automation to start the addon only when needed but then I can't control the enable the integration if ita disabled.

I hope developers would look into this and would fix this issue.

Thanks @marcelveldt.

**Comment by OzGav** [comment]
Why do you not want the addon running?

**Comment by marcelveldt** [comment]
The addon is managed by the integration (because you choose to use to let the integration manage the add-on when you installed the HA integration). So it's by design. And like @OzGav said, why NOT have the add-on running ? The whole purpose is to have it running...

**Comment by nehasjains** [comment]
Currently using MPD for playing music and podcasts(hls based playlist). MPD addon is not maintained by the developer and the version is very old.  So made a shift to squeezebox addon. Re-wrote some of the scripts and while in the process I found "Music Assistant" addon.

Now if music assistant addon is running sometime the squeezebox addon refuses to start saying that another instance is already running. So I have to stop Music Assistant addon first and  then start squeezebox addon again to get it to work.

I can't completely shift to Music Assistant yet. But the process in on.

Keep up the good work guys.

Looking forward for mpd and alexa integration.

**Comment by OzGav** [comment]
If it is a port conflict MA is configurable. However, Marcel has said before that LMS and MA cannot co-exist

**Comment by nehasjains** [comment]
> If it is a port conflict MA is configurable. However, Marcel has said before that LMS and MA cannot co-exist

I am waiting for MPD and alexa integration in Musuc Assistant.  Will let LMS go then

**Comment by OzGav** [comment]
Vote for MPD here https://github.com/orgs/music-assistant/discussions/1200

Alexa discussion here https://github.com/orgs/music-assistant/discussions/431
