### ISSUE TITLE
Zero Volume Doesn't Work on Squeezelite

### ISSUE THREAD

**Issue by rjgrandy** [music-assistant/hass-music-assistant#1484]
### What version of Music Assistant has the issue?

2.0.0b73

### The problem

When I set the volume on any squeezelite player to 0 in the UI, the volume decreases but does not go to 0. Instead it continues to have a low volume

### How to reproduce

Play music to a squeezelite player and set volume to 0

### Relevant log output

na

### Additional information

na

### What version of Home Assistant Core are your running

2023.7.3

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
Yes I can confirm this. Added to backlog

**Comment by OzGav** [comment]
This has been fixed in b107.
