### ISSUE TITLE
Radio Station Optional URL parameters do not survive a restart

### ISSUE THREAD

**Issue by Rendrik** [music-assistant/hass-music-assistant#1485]
### What version of Music Assistant has the issue?

2023.6.0b3

### The problem

Radio stations with URL parameters (used for authentication usually) added by the "Add item from URL" will play initially.  However after restarting Music Assistant, the station seems to be missing optional URL parameters.

It's common for some subscription stations to include URL parameters for authentication.

### How to reproduce

1. In music assistant, select Radio from the menu
2. From the triple-dot drop down, select "Add item from URL"
3. Paste in a URL for a radio station, with a URL parameter.  In my case I'm using a digitally imported URL, with the auth key.  It looks like this: `http://prem4.di.fm:80/lofihiphop?24digitauthkey`
4. Accept the station label; it auto-populates correctly from the stream.
5. Once added, press the content refresh button at the top of the page.
6. Click on the new station and play it on a device - The stream should play OK.
7. Restart Music Assistant.  I did this by way of HA Settings -> Addons -> MA -> Restart
8. Once restarted, navigating back to radio and playing the station will fail (if the server relied on URL parameters for auth)
9. Open the "More Info" view of the station; The station URL will be `http://prem4.di.fm:80/lofihiphop`.

### Relevant log output

This is the log entry generated after step 8 above.
```
2023-08-20 21:12:05.139 INFO (ThreadPoolExecutor-0_0) [pychromecast.controllers] Receiver:Launching app CC1AD845
2023-08-20 21:12:07.889 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue Ceiling Speakers
2023-08-20 21:12:08.643 WARNING (MainThread) [music_assistant.streams] Stream error on url://radio/http://prem4.di.fm:80/lofihiphop
```

### Additional information

The log file as well as the Station 'More Info" view show the URL without additional parameters.  However it's not clear to me if those are stripped for security reasons, or if is not persisted.

### What version of Home Assistant Core are your running

2023.8.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Just looking at the code for this. The stripping of data after the ? is actually deliberate to avoid storing any data which is temporary like auth keys. So in regards to the 24 digit auth key you refer to in your post is that permanent or does it expire at some point?

**Comment by OzGav** [comment]
I will close this soon if no firther updates

**Comment by Rendrik** [comment]
This is a unique security code which can be rotated, but at least in my case, does not expire.
I was adding the station including the key with the expectation that should I ever rotate the key, I'd have to re-add the station.

**Comment by OzGav** [comment]
I’ll have to speak to the devs about how this may be overcome. In the meantime you can try and just put the url in a playlist file

**Comment by OzGav** [comment]
This will be fixed in due course. Thanks for the report.

**Comment by OzGav** [comment]
Please report if this still an issue after beta79 is released
