### ISSUE TITLE
AirPlay Equalizer does not work correctly

### ISSUE THREAD

**Issue by gost4711** [music-assistant/hass-music-assistant#1489]
### What version of Music Assistant has the issue?

2.0.0.b73

### The problem

I have a problem with the AirPLay Equalizer. (Settings / players / my player / configuration /Advance settings)
When I adjust the values, I don't hear any change. After the player restarts, the new values ​​will take effect. So the sound can be adjusted very badly.
Nothing can be seen in the LOG.

### How to reproduce

I choose "settings / players / my player / configuration /Advance settings" then I set the values

### What version of Home Assistant Core are your running

2023.8.2

### What type of installation are you running?

Home Assistant Core

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by marcelveldt** [comment]
I've added a temporary fix that restarts the stream to the player as soon as you change any settings.
Long term solution is to adjust the equalizer in realtime but due to the large buffer we maintain that is not that easy.

**Comment by OzGav** [comment]
Please report if this still an issue after beta79 is released
