### ISSUE TITLE
Slimproto provider is always enabled also if i disabled and deleted

### ISSUE THREAD

**Issue by mfabiani53** [music-assistant/hass-music-assistant#1491]
### What version of Music Assistant has the issue?

b73

### The problem

I disabled and deleted the slimproto provider, but everytime MA restart or updated to the latest release, i can see this provider enabled again.

### How to reproduce

Disable and delete SlimProto provider, then restart or update MA to the latest release and you will see that provider enabled again.

### What version of Home Assistant Core are your running

2023.8.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Thanks. Same with Sonos as well. This will get looked at soon.

**Comment by marcelveldt** [comment]
You can't delete the builtin player providers (we should hide delete in the UI) you can only disable them

**Comment by OzGav** [comment]
Fixed in beta74. Please report any further issues
