### ISSUE TITLE
Hebrew Translation

### ISSUE THREAD

**Issue by kaaspad** [music-assistant/hass-music-assistant#1493]
### New language

hebrew

### Additional remarks

I'd be happy to add Hebrew translation

**Comment by jozefKruszynski** [comment]
Hi, I added the language. Please follow the link here and select Hebrew as your contribution language
https://app.lokalise.com/public/321419046440c0f2bba414.05634832/

**Comment by kaaspad** [comment]
hebrew completed

**Comment by jozefKruszynski** [comment]
Brilliant, thanks for the contribution. I have created a pull request to the frontend repo from Lokalise and whenever we drop the next beta, Hebrew should be available
