### ISSUE TITLE
AirPlay-based players still show up in sidebar after deleting from settings-> providers & settings->players

### ISSUE THREAD

**Issue by embowles93** [music-assistant/hass-music-assistant#1494]
### What version of Music Assistant has the issue?

2023.6.0b3

### The problem

After setting up Music Assistant in HA, a number of AirPlay players were discovered by the system. I do not need these, so removed them from the settings->players section. I also deleted the AirPlay player provider. However, they still show up in the sidebar when choosing a player to play music from.

I've also tried clearing the cache, reloading the integration and restarting HA.

### How to reproduce

Clean install of Music Assistant, removed AirPlay provided players and still see in sidebar.

### Relevant log output

Please advise is log output is needed.

### Additional information

Is there anything I need to do to disable these fully? Or is this normal behavior. Appreciate any help!

### What version of Home Assistant Core are your running

2023.8.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Thanks. Looks related to another recent issue. Will get looked at soon

**Comment by embowles93** [comment]
Thank you!love the platform by the way...keep up the great work.

**Comment by DarkFox** [comment]
I'm having the same issue with Cast players, so this most likely applies to all the player platforms.

**Comment by OzGav** [comment]
Fixed in beta74. Please report any further issues
