### ISSUE TITLE
Volume control of Chromecast group issue

### ISSUE THREAD

**Issue by mindtripper** [music-assistant/hass-music-assistant#1504]
### What version of Music Assistant has the issue?

2023.6.0b3

### The problem

Cast groups work and I can play music, but when I change (increase and then decrease) volume of the group where the speakers are on different volume levels.  As soon as any member speaker reaches 0. It stays on 0. It will never increase no matter what I set the group to. 

If the individual speakers in the group are at the same volume level. Then it works very well. The member speaker(s) follow the group. But when the group is set to 0. The members stay on 0 no matter what I set the group to afterwards.

This problem is the same for MA and HA.

### How to reproduce

In MA (or HA), have group and members speaker(s) at a level above 0. Change the group volume 0. Then try to increase the volume. Each member will stay at 0.

![](https://cdn.discordapp.com/attachments/1098864088806867015/1147128924728467467/image.png)

### Relevant log output

2023-09-01 13:22:39.534 INFO (ThreadPoolExecutor-0_2) [pychromecast.controllers] Receiver:setting volume to 0.0
2023-09-01 13:22:40.273 INFO (ThreadPoolExecutor-0_1) [pychromecast.controllers] Receiver:setting volume to 0.0
2023-09-01 13:22:40.273 INFO (ThreadPoolExecutor-0_5) [pychromecast.controllers] Receiver:setting volume to 0.0

### What version of Home Assistant Core are your running

2023.8.4

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

**Comment by mindtripper** [comment]
Hi!

I've made a microscopic change to the code that helps.
/music-assistant/server/music_assistant/server/controllers/players.py#L466
From:
`cur_child_volume = child_player.volume_level`
To
`cur_child_volume = child_player.volume_level + 1`

This ensures that the next line of code
`new_child_volume = int(cur_child_volume + (cur_child_volume * volume_dif_percent))`
does not multiply by 0 when a member speaker is set 0. Since this will result in 0 no matter what group volume is set.

I can live with this "hotfix" until you get around to this bug :)

**Comment by OzGav** [comment]
Fixed in beta74. Please report any further issues
