### ISSUE TITLE
v1.0.18 - Album art source

### ISSUE THREAD

**Issue by AvdWerfhorst** [music-assistant/hass-music-assistant#151]
First of all, compliments with the great progress. This software fills a gap that I really was missing in my smart home setup.

Not really a big deal, but something I wonder. I have included in my flac files jpegs with album art. I do notice in some cases that the art I see in Music Assistant is another version of the album's art than included in the files. So I expect that it is sourced online. Is there perhaps a way to prioritize the artwork included in the local files?

**Comment by marcelveldt** [comment]
Album art is derived from the ID3 tags of the actual track (in case of local filesystem audio) and, if the artist/album/track could be matched on Musicbrainz, metadata from metadata sources like Fanart.tv and the audiodb.

At this time there is not (yet) support for albumart as jpg files in the directories but that will be pretty easy to add.

Besides that I have plans for a built-in info editor to update the metadata yourself including the images and prioritize those. The backend plumping is already present for that but need to find some time some day to create the UI

**Comment by marcelveldt** [comment]
Just wanted to let you know that since v1.1 the embedded/local metadata is prioritized over online metadata.

**Comment by AvdWerfhorst** [comment]
Awesome. I must say, I like the speed on which you are developing this all.

**Comment by marcelveldt** [comment]
Thanks!
