### ISSUE TITLE
Failed Setup

### ISSUE THREAD

**Issue by BlueMoon23** [music-assistant/hass-music-assistant#1523]
### What version of Music Assistant has the issue?

2023.6.0b3

### The problem

I installed Music Assistant yesterday and it appeared to work, i.e. on the Integrations Page there were no issues. I planned to connect to my music server at a later date. I rebooted HA today and noticed that it was reporting failed set up, will retry, this keeps repeating. Logs turned on and the following error reported "2023-09-12 17:55:50.845 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Music Assistant' for mass integration not ready yet: Failed to connect to music assistant server; Retrying in background"

When I selct Music Assistant in the side bar the screen is blank, yesterday it was populated.

### How to reproduce

Nothing required to reproduce, the error remains on the settings page.

![image](https://github.com/music-assistant/hass-music-assistant/assets/21972216/71f1a0bc-8560-404b-8a8b-e73733a24d13)

### Relevant log output

2023-09-12 17:55:50.845 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Music Assistant' for mass integration not ready yet: Failed to connect to music assistant server; Retrying in background

### What version of Home Assistant Core are your running

2023.9.1

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Alternative

**Comment by OzGav** [comment]
Where is the server running?

**Comment by BlueMoon23** [comment]
Hi,

My home assistant is running on a QNAP Virtualization Station, my music is
also on the QNAP, but I have not connected yet, that was what I was
planning to do when I found the issue.

**Comment by OzGav** [comment]
The integration you install via HACS is not the MA server. It doesn’t sound like you have installed the server. Please read the docs. We recommend you use HAOS so everything is done for you. If you do not wish to then you need to install the server in docker.

**Comment by BlueMoon23** [comment]
HI,

I have read the documents, they say if I am running HA Supervisor I can
skip this step (install the server); I may be running it on a QNAP, but it
is HA Supervisor (2023.08.03). When I first installed the beta integration,
I added Music Assistant to the Sidebar, on clicking this I had a full page
to interact with; now I have nothing, other than a warning as follows:

[image: image.png]

Any ideas what to try next?

**Comment by OzGav** [comment]
In HA SETTINGS go to ADDONS and see if MA is still installed and running.

**Comment by BlueMoon23** [comment]
Hi,

Yes it is installed and running:

[image: image.png]

**Comment by OzGav** [comment]
Unfortunately the images aren’t coming through when you respond via email. I would try removing the INTEGRATION but leave the ADDON and then reinstall the integration ensuring you select the latest BETA.

**Comment by BlueMoon23** [comment]
Hi,

That worked, I now have the add on working again, thanks. One query on
setting up though, in my HA Media, I have several sources, how do I
transfer these into Music Assistant? I know they are linked as I have just
played a track via HA Media, and it has appeared in Music Assistant as
recently played, but I was expecting to see all the media available in
Music Assistant.

Regards

John

**Comment by OzGav** [comment]
You have to add all sources as music providers. This is done in the settings.
