### ISSUE TITLE
I don't see MA2 inside HA.

### ISSUE THREAD

**Issue by Africa67** [music-assistant/hass-music-assistant#1533]
### What version of Music Assistant has the issue?

2023.6.0b3

### The problem

I don't see Music Assistant inside HA. Music installed as server via docker.
HA in https. MA works well and I access via http

### How to reproduce

Installing MA Server 2.0 on Docker
installation via HACS of the beta version of MA

### What version of Home Assistant Core are your running

2023.9.2

### What type of installation are you running?

Home Assistant Core

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
What do you expect to see? You say the MA works well?

**Comment by Africa67** [comment]
in the left bar, as was the case previously and the MA interface was inside HA. 
Now to access MA I have to call it from external http://192.168.1.1:8095

**Comment by OzGav** [comment]
When you say " the case previously" are you coming from MA1 or a previous beta of MA 2?

**Comment by Africa67** [comment]
Yes, I come from MA1. But I made several attempts to uninstall MA1 and then I installed MA2 server in docker and then MA2 Beta in HA

**Comment by OzGav** [comment]
MA2 has been completely rewritten and for a variety of reasons is no longer a big integration. It is now a standalone addon that can work with HA but does not have to. If you want a more seamless experience then we recommend you use HAOS. If you install via docker as you have done then you have to access it via port 8095 as you have found. Read the FAQs for how to add that to the sidebar. 
The integration, which is not yet at the feature level of MA1, allows for scripts and automations to target MA just as was the case before.

**Comment by Africa67** [comment]
Thanks, I'll check the FAQ
