### ISSUE TITLE
Deezer - cannot authenticate

### ISSUE THREAD

**Issue by dc1983** [music-assistant/hass-music-assistant#1536]
### What version of Music Assistant has the issue?

2023.6.0b3

### The problem

Hi,

jonathanbangert.com is no longer reachable so the redirect_uri deezer.oauth.jonathanbangert.com is no longer valid.

### How to reproduce

attempt to authenticate Deezer

### What version of Home Assistant Core are your running

2023.9.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
You have listed the integration version. What version of the addon are you running?

**Comment by dc1983** [comment]
> You have listed the integration version. What version of the addon are you running?

Sorry, the addon version is 2.0.0b73

**Comment by OzGav** [comment]
@arctixdev

**Comment by arctixdev** [comment]
Oh god sorry. I completely missed that. Fix should be up in 10 minutes or so no need to update anything.

**Comment by dc1983** [comment]
Working perfectly, thanks for looking at this so quickly.

**Comment by arctixdev** [comment]
Of course :slightly_smiling_face: Sorry for the issue in the first place! Just a dumb mistake on my part
