### ISSUE TITLE
Chromecast - Failed to connect to service ServiceInfo / Error reading from socket

### ISSUE THREAD

**Issue by Dillton** [music-assistant/hass-music-assistant#1539]
### What version of Music Assistant has the issue?

2023.6.0b3

### The problem

Hello,
I have several Chromecast devices and I have observed in HA logs there are errore with connecting to them.
Initially I thought this comes from HA Cast integration but I believe it's coming from MASS.
![image](https://github.com/music-assistant/hass-music-assistant/assets/68992112/8b5764a4-9bac-4a99-8e36-8106d3d47585)

Currently I am running latest MASS version b73.

### How to reproduce

Just have one chromecast device enabled in MASS

### Relevant log output

Logger: pychromecast.socket_client
Source: /usr/local/lib/python3.11/site-packages/pychromecast/socket_client.py:398
First occurred: 02:46:11 (6 occurrences)
Last logged: 03:58:53

[Living Room audio(10.0.0.18):8009] Failed to connect to service ServiceInfo(type='host', data=('10.0.0.18', 8009)), retrying in 5.0s
[Home Speakers([::ffff:a00:3c]):32073] Failed to connect to service ServiceInfo(type='host', data=('[::ffff:a00:3c]', 32073)), retrying in 5.0s
[Bedroom speaker(10.0.0.60):8009] Failed to connect to service ServiceInfo(type='host', data=('10.0.0.60', 8009)), retrying in 5.0s
[Living Room speaker(10.0.0.61):8009] Failed to connect to service ServiceInfo(type='host', data=('10.0.0.61', 8009)), retrying in 5.0s
[Office speaker(10.0.0.62):8009] Failed to connect to service ServiceInfo(type='host', data=('10.0.0.62', 8009)), retrying in 5.0s

Logger: pychromecast.socket_client
Source: /usr/local/lib/python3.11/site-packages/pychromecast/socket_client.py:623
First occurred: 02:57:33 (2 occurrences)
Last logged: 02:58:13

[Home Speakers(10.0.0.60):32073] Error reading from socket.
[Home Speakers(10.0.0.61):32073] Error reading from socket.

### What version of Home Assistant Core are your running

2023.9.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Have you reviewed the troubleshooting FAQ?

**Comment by Dillton** [comment]
Yes I did.
The thing is I don't have any problem with setting up the addon, discovering the devices or playing music.
I have also double checked my network settings and there is nothing that would block multicast traffic etc..
It's just this error in log few times per day.

**Comment by OzGav** [comment]
I am not sure a disconnection is a big deal if it reconnects again. I’m inclined to close this and ask you to report again if this has a negative impact on your use of MA?

**Comment by Dillton** [comment]
Yeah you are right it's not causing any problem with playback etc. so we can theoretically close this thread but as it's coming from MASS it could be and it was at least for me confusing because I was looking for issue on HA side for some time as I found those errors in HA log first and then I have discovered that it's actually coming from MASS.
So at least some minor change in logging maybe add some flag that it's coming from MASS component would be nice
.
In addition I can try to raise a question on pychromecast lib maybe the root cause is there? What do you think?

**Comment by OzGav** [comment]
That is the MA log though isn’t it?

**Comment by Dillton** [comment]
Yes it is.

**Comment by OzGav** [comment]
Well we don’t need to flag that it is coming from MA as it is the MA log. Everything in there is coming from MA

**Comment by Dillton** [comment]
Ok understand but to clarify this the screenshot log is MA and the text log is HA.

**Comment by OzGav** [comment]
I think the answer is you can tell from the entity name? Unless you have them named the same as your HA entities….

**Comment by OzGav** [comment]
Your chromecasts are reconnecting in less that 10 secs and it’s not causing a problem. I see similar. Just see how you go with this and report again if it starts causing troubles.
