### ISSUE TITLE
[Feature Request] Multiple Spotify accounts

### ISSUE THREAD

**Issue by Urchin73** [music-assistant/hass-music-assistant#154]
Multiple Spotify accounts management... the only feature I miss to this mindblowing integration. Thumbs up ! Thanks !

**Comment by nagyrobi** [comment]
Interesing that MA doesn't use the same API method as HA Spotify integration. It requires a username and password instead of some API keys...

**Comment by marcelveldt** [comment]
That's because MA is based on librespot. I still need to add Spotify connect auth. That way there are no username and password needed but you authenticate with the spotify app on your phone.

**Comment by marcelveldt** [comment]
> Please keep the current user/password option in. I deliberately didn't use the account in my phone, but reserved a free family user slot for HA, so Spotify doesn't complain I'm running with that account already on another device.

I have exactly the same usecase hence I implemented the username/password login first :-)

**Comment by erkr** [comment]
Releated to issue: https://github.com/music-assistant/hass-music-assistant/issues/243

**Comment by erkr** [comment]
Duplicate
