### ISSUE TITLE
ESP32 + i2s_audio MediaPlayer 

### ISSUE THREAD

**Issue by sergiosafer** [music-assistant/hass-music-assistant#1540]
### What version of Music Assistant has the issue?

Beta 2.0.0b73 

### The problem

Hello. Congratulations for the tremendous application that you created, as for the aesthetic and functional, I take off my hat!!!!!
I have armed with the library i2s_audio + esp32 and player that works very well with the radio browser inside HA, but I do not appear as Players within the Music Assistant.

Is there any way to have it available?

Thank you very much Sergio

### How to reproduce

I can't find the playback device in the list of players

### What version of Home Assistant Core are your running

2023.09.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
ESP boards are only supported if you load squeezelite on them

**Comment by juanitoddd** [comment]
Ohhh that explains why I cant link my ESP-muse to it :D 
Thanks !
