### ISSUE TITLE
Youtube: not showing uploaded albums

### ISSUE THREAD

**Issue by AviFix** [music-assistant/hass-music-assistant#1545]
### What version of Music Assistant has the issue?

2023.2.2

### The problem

Youtube: not showing uploaded albums

### How to reproduce

Go to Browser => youtubeMusic=>albums

### What version of Home Assistant Core are your running

2023.8.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Here is the comment from the Dev on this:

> This is something I fixed a while ago, so people should be able to load them when they are in a playlist. Not sure what happens if it's just a single track they're trying to search, since often those own songs don't have proper metadata. Guess it'll be hard to find them via the UI in MA

**Comment by AviFix** [comment]
I have full albums with correct metadata.
They don't show anywhere.

Should it sho while using a free YouTube account?

**Comment by OzGav** [comment]
Why do you say they have “correct metadata”? Can you see all the metadata is preserved when uploaded to YTM?

**Comment by AviFix** [comment]
When I look on YouTube music site they are all sorted by albums by artist as expected

**Comment by AviFix** [comment]
It does read all my playlists
Although it's a free account

**Comment by OzGav** [comment]
The trouble is MA doesn’t support free accounts. If you have all that uploaded music locally then use the local filesystem  provider.
