### ISSUE TITLE
Download/Installation Fail Integration: 500 Internal Server Error Server got itself in trouble

### ISSUE THREAD

**Issue by Imnotcreativesoicantthinkofaname** [music-assistant/hass-music-assistant#1547]
### What version of Music Assistant has the issue?

2023.2.2

### The problem

Downloadet via HACS and tryed to install the Integration and got this error:
Der Konfigurationsfluss konnte nicht geladen werden: 500 Internal Server Error Server got itself in trouble
(It says like the configuration flow could not be loadet)
I read that its solved by now on that thread: https://github.com/music-assistant/hass-music-assistant/issues/1143
Idk am i stupid or is that a bug

### How to reproduce

Downloadet via HACS and tryed to install the Integration and got this error

### Relevant log output

idk where do i get further logs than the error message?

### Additional information

thanks for your work :)

### What version of Home Assistant Core are your running

2023.9.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
As per that thread that you linked make sure you are installing the BETA version of the integration

**Comment by Imnotcreativesoicantthinkofaname** [comment]
Im dumb im sorry thanks a lot :)
