### ISSUE TITLE
Resume after tts.speak 

### ISSUE THREAD

**Issue by GaWr26** [music-assistant/hass-music-assistant#1557]
### What version of Music Assistant has the issue?

2.0.0b73 

### The problem

If I send an announcement via the contemporary tts.speak service to a cast device, Music playback doesn't resume. 
I'm new to Music Assistant and read quite a lot here about resuming music after a tts announcement. I assume, this only works with the legacy tts.google_translate_say or am I missing something completely?

### How to reproduce

Play any Music and trigger a tts announcement:

`service: tts.speak
target: tts.google_de_de
data:
  media_player_entity_id: media_player.kitchen
  message: "May the force be with you."`

### What version of Home Assistant Core are your running

2023.10.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
TTS announce support in MA2 is still coming. It is already on the backlog https://github.com/orgs/music-assistant/projects/2
