### ISSUE TITLE
[Server] CPU issue when adding tracks to playlists

### ISSUE THREAD

**Issue by krisnoble** [music-assistant/hass-music-assistant#1566]
### What version of Music Assistant has the issue?

2.0.0b73

### The problem

There seems to be an issue with CPU use when adding tracks to playlists via the GUI. On my system, a single track added to a playlist will add to the m3u file right away but will take CPU usage from 2-4% in normal operation, to over 50% for a few minutes before coming back down. 

If I add another track to a playlist in that time, it will not appear in the m3u file, CPU usage will hit 100% but it does seem to come back down eventually at which point the track appears in the m3u.

I found this after trying to add ~30 tracks to a playlist (one at a time due to the multiple add bug) and all failed except the first although that may be because I restarted MA after noticing the CPU issue, at which point it had been at 100% for over 5 minutes.

I've tried this with different playlists and tracks, and had the same results.

### How to reproduce

1. Check CPU use
2. Use the GUI to add a track to a playlist
3. Watch CPU use spike before eventually coming back down

### What version of Home Assistant Core are your running

2023.10.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Looping back to this. How big in GB is all your music?

**Comment by krisnoble** [comment]
Currently 20.92 GB. Good timing, I've been digitising more of my CD collection over the last few days so will have a fair chunk more to add at some point as well 😆

**Comment by OzGav** [comment]
Let us know if it is still happening and if so what hardware are you using

**Comment by krisnoble** [comment]
Just done some quick tests. After adding tracks I see a brief spike in power usage, from baseline 15W up to 30W for a few seconds before coming back down, and also on CPU where it looks like goes from baseline 5% up to 15% before coming down over the course of a couple of minutes. No impact on system performance AFAICT.

Looks like all the tracks get added right away though, and seems to be similar behaviour between a single track and batches (I tried 1, 2, 4 and 10). 

Hardware wise not actually a NUC specifically but similar specs on an old laptop running HAOS as a Proxmox VM, just in case some obscure system-related stuff shows up.

So looks like whatever was causing my specific issue is mitigated if not eliminated - I assume some level of increased resources is to be expected as long as it doesn't impact anything negatively. I can do more testing though if it's helpful.

**Comment by OzGav** [comment]
No that sounds fine. Report again if you have further issues,
