### ISSUE TITLE
V1.0.18: exported mass media player out of sync 

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#157]
The exported mass media players can easily get out of sync with source players.
scenario:
1. In MA start a cast of a Spotify playlist to a single CC / CC group of a Spotify playlist(group or single doesn't make a difference in behavior)
2. Connected a mobile Spotify app to the same  CC / CC group (other Spotify account)
3. Then I started a new cast from my mobile 
4. Although the mobile Spotify playlist took over the CC group, MA still thinks the original playlists are playing

State of the source CC (media_player.audio57keuken):
```
volume_level: 0.5099946856498718
is_volume_muted: false
media_content_id: spotify:track:2OgWVJt6yELd5r9z9iMWTH
media_content_type: music
media_duration: 325.653
media_position: 0.326
media_position_updated_at: '2022-05-13T17:37:52.632076+00:00'
media_title: Black Hole Sun
media_artist: Peter Frampton
media_album_name: Fingerprints
app_id: 705D30C6
app_name: Spotify
entity_picture_local: >-
  /api/media_player_proxy/media_player.audio57keuken?token=cf778e934774750e4ba7553b8f83b809601ea366f3efc85d0a8f945055193863&cache=86986adafecddd87
entity_picture: https://i.scdn.co/image/ab67616d0000b273b8a488db20878516dc9ed562
friendly_name: Audio57keuken
supported_features: 152511
```

State of the exported CC (media_player.mass_audio57keuken):
```
volume_level: 0.5
media_content_type: music
media_duration: 233
media_position: 0.326
media_position_updated_at: '2022-05-13T17:37:52.712540+00:00'
media_title: Cesair - Enuma Elish
shuffle: false
repeat: 'off'
entity_picture_local: >-
  /api/media_player_proxy/media_player.mass_audio57keuken?token=4fa62f68b1cf83451845771d511d1063adcea3db3742ccdadef8c98b00bbdb43&cache=b52e2cc999e886e9
source_entity_id: media_player.audio57keuken
is_group: false
group_childs: []
group_parents:
  - media_player.everywhere_57
active_queue: media_player.audio57keuken
items_in_queue: 3679
device_class: speaker
entity_picture: https://i.scdn.co/image/ab67616d0000b2738712200d9df0ce17719d8484
friendly_name: Audio57keuken
supported_features: 456629
```
State of the exported CC  also didn't get back in sync after a while (after the next number or so). MA in the UI still suggests that each CC is playing their queue assigned by MA to that CC. Not the queue of the CC group that was playing !!!

Best 
Eric

**Comment by marcelveldt** [comment]
Thanks for reporting. That should be easy fixable. Will have a look later

**Comment by marcelveldt** [comment]
Can you please check if this is fixed for you in the 1.1 release ?

**Comment by erkr** [comment]
I will test that today

**Comment by erkr** [comment]
Yes, verified all media_player entities and they all have the same track ID and That track ID  in the players is one casted from my Spotify. So issue is solved!  I noticed one cosmetic issue, not meta data presented, only the track ID.
The template players:
![image](https://user-images.githubusercontent.com/4363599/168466895-f295fe34-8b2c-4aac-9a47-9a3da9587dac.png)
The mass* player:
![image](https://user-images.githubusercontent.com/4363599/168466874-a9e929eb-a6aa-49d4-947f-7a21cd25c635.png)

**Comment by erkr** [comment]
While switching between MA and the Mobile Spotify app raised this error. Not an issue I guess:
```
Logger: homeassistant
Source: /usr/src/homeassistant/homeassistant/runner.py:96
First occurred: 11:55:10 (1 occurrences)
Last logged: 11:55:10

Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/helpers/process.py", line 103, in write
    await self._proc.stdin.drain()
  File "/usr/local/lib/python3.9/asyncio/streams.py", line 387, in drain
    await self._protocol._drain_helper()
  File "/usr/local/lib/python3.9/asyncio/streams.py", line 197, in _drain_helper
    await waiter
BrokenPipeError

```

**Comment by marcelveldt** [comment]
The BrokenPipe error can be ignored. That is one I need to solve with the HA core devs to hide it.
It means that the stream got interrupted, hence the "broken pipe". It happens when you skip a song or stop it. Somehow the HA eventloop ignores the fact this this error should suppressed. So just ignore it, just like the "stream error" this is an "expected" error. For me good while in beta stage to keep track how MA is behaving and I have to hide it all once we move to a more stable/definitive situation.

Great to hear that the initial issue is resolved. At this time MA just completely ignores the player when it is playing from another source. I guess you're right that I could display the "origin" metadata on the HA media player object. I'll take a look at adding that

**Comment by marcelveldt** [comment]
I've added the additional metadata. Fix will be in the next release.
