### ISSUE TITLE
Back Button for Full Kiosk Mode to my Dashboard

### ISSUE THREAD

**Issue by MorreMor** [music-assistant/hass-music-assistant#1571]
### What version of Music Assistant has the issue?

2023.beta(last)

### The problem

Can you make a Button to come back in my Dashboard in Full Kiosk Mode? It's impossible actually. Thank you!

### How to reproduce

.

### What version of Home Assistant Core are your running

2023 last beta

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Please raise his as a feature request in the discussions area. Thanks.
