### ISSUE TITLE
HomePod (big 2. Gen) not show

### ISSUE THREAD

**Issue by MorreMor** [music-assistant/hass-music-assistant#1572]
### What version of Music Assistant has the issue?

2023. last beta

### The problem

the new big HomePod gen2 is not shown play now. I find it but its doesn't show to play on it

### How to reproduce

,

### What version of Home Assistant Core are your running

2023

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Please supply the logs when MA starts which shows the player discoveries

**Comment by OzGav** [comment]
Please also go through the trouble shooting FAQ. We will close this soon if there is no further follow up.
