### ISSUE TITLE
Songs play twice on generated playlists

### ISSUE THREAD

**Issue by OzGav** [music-assistant/hass-music-assistant#1573]
### Discussed in https://github.com/orgs/music-assistant/discussions/1517

<div type='discussions-op-text'>

<sup>Originally posted by **al090187** September 10, 2023</sup>
Hi, when I select a song, and "start radio" it generates a playlist with songs listed once, but then plays each song twice. 

This doesn't happen when I play an album locally, or from Youtube Music integration. Only when I "start radio" where it generates the playlist itself.

Any suggestions?</div>

**Comment by OzGav** [comment]
As per the discussion this also happens with normal playlists as well

**Comment by marcelveldt** [comment]
Does this ONLY happen with Chromecast players ?

**Comment by marcelveldt** [comment]
Been playing some playlist for half a day on a chromecast player and not a single duplicated song so there must be something very specific triggering this.

**Comment by OzGav** [comment]
@al090187 Can we have some followup on this issue. I am trying to reproduce on beta 74 without luck. If you can reproduce it then change the logging for the player to debug and capture everything over the period of duplicated playback.

**Comment by OzGav** [comment]
This should be fixed in beta 75. Let us know if not.

**Comment by al090187** [comment]
4 songs in, and no repeats yet....... so touch wood! Thank you :) I can finally have song details on my screen again 😂
