### ISSUE TITLE
Squeezelite player constantly goes to idle state

### ISSUE THREAD

**Issue by dukicn** [music-assistant/hass-music-assistant#1575]
### What version of Music Assistant has the issue?

2023.6.0b3

### The problem

Squeezelite player goes to idle state after couple of seconds. It still continues to play and plays all the music from the queue, but the state changes to Idle after couple of seconds. If I do any operations on the player (like next song, increase / decrease volume, etc.) it moves back to state Playing and after couple of seconds moves back to state Idle again. This has an affect on my media player in Home Assistant as it doesn't show the correct song (the current song is shown as currently playing even though the player plays the net song in the queue). Same player normally works with LMS server and shows the correct status.

Squeezelite version is Squeezelite v1.9.9-1432, running on Raspberry Pi4 with DietPi v8.22.3.

### How to reproduce

This happens constantly, don't know how to reproduce it.

### Relevant log output

No errors in the log file that I could connect with this issue.

### What version of Home Assistant Core are your running

2023.10.2

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Please confirm you are looking at the MA entity in HA not a native HA one. I just tried this with Squeezelite running on Windows and it worked fine?

**Comment by dukicn** [comment]
Yes, I am looking at MA entity. I also checked on the MA web interface directly as well and it shows the same behaviour. It starts and shows state 'Playing', after couple of seconds state switches to 'Idle'. If I do anything with the player, for example increase volume, it changes state to 'Playing' and then couple of seconds later, shows 'Idle' again.

**Comment by dukicn** [comment]
Also, to make sure it's not caused by some networking issue, I installed shairport-sync on the same device where I run squeezelite and configured Airplay provider. I didn't have any issues with airplay provider, it never changes it's state to 'Idle' and works correctly.

**Comment by OzGav** [comment]
Sounds like it might be a problem with that version of squeezelite then

**Comment by dukicn** [comment]
I don't think that is the case since the same squeezelite client works normally with Logitech Media Server. It always shows correct state there.

**Comment by OzGav** [comment]
All I could add to that is Marcel has in the past said LMS has a number of hacks within that to make things work that shouldnt according to the specs. What have you got this running on? If it is a Pi try running picoreplayer on it and see what happens.

**Comment by dukicn** [comment]
I'll try with picoreplayer for testing, but I can't change my setup permanently. Unfortunately, I'll have to revert back to my old LMS setup which is too bad as I really like MA. Thanks for the help.

**Comment by OzGav** [comment]
Yeah I have just tried picoreplayer and it also is working fine. So if yours isnt you could try different versions of whatever software you are using. Just confirm you have got the LMS shutdown on your network while trying to do this?

**Comment by dukicn** [comment]
Yes, LMS is turned off.

**Comment by OzGav** [comment]
Im running out of ideas then. If picoreplayer works then defintiely points to something with the software you are using

**Comment by dukicn** [comment]
Possibly. What version of picoreplayer you tested? I'll try to use the same one.

**Comment by OzGav** [comment]
I just updated it to see if that made any difference. It is now on 1.9.9-1430 and working fine

**Comment by OzGav** [comment]
How did you go with picoreplayer?

**Comment by dukicn** [comment]
Yes, you were right. pCP works. Unfortunately, I was never able to make pCP work for me. I use FanShim to cool of my device and their python library just doesn't want to install due to some dependencies. But since my RPi4 sits in the closed cabinet with other equipment, it gets very hot, over 75C so I can't run it without fan. Anyhow, thank a lot for your help, this is clearly something with the squeezelite client.

**Comment by OzGav** [comment]
Thanks.

**Comment by dukicn** [comment]
Hi @OzGav,

opening this again as after upgrade of my Music Assistant server to 2.0.0b74, the same issue appears with piCorePlayer. Any ideas? I run pCP 8.2.0 with Squeezelite v1.9.9-1430-pCP.

Thanks

**Comment by OzGav** [comment]
Where are you seeing the idle state? I see playing in the MA player list as well as the HA entity. Are you seeing idle everywhere?

**Comment by dukicn** [comment]
I see idle state in both the HA entity as well as MA player in MA web interface. This started to happen after the upgrade for MA server. It worked before with pCP (but didn't work with my custom installation).

**Comment by OzGav** [comment]
See if you can think of something else that is different with your setup. Maybe this is a networking issue? No one else has so far reported this type of issue.

**Comment by dukicn** [comment]
Hi @OzGav, seems I found the issue but have no clue why is this causing squeezelite player to go to idle state. I was using internal stream and output buffer size switch (-b 1048576:1048576) for my squeezelite command. When I remove it, everything works ok and player correctly shows the status and never goes to idle state. I can reproduce the issue since it happens every time I start squeezelite player with -b switch.

**Comment by OzGav** [comment]
Cool. Thanks for the fault finding. Hopefully this will help someone else in the future
