### ISSUE TITLE
Failed to connect

### ISSUE THREAD

**Issue by piotrek2555** [music-assistant/hass-music-assistant#1580]
### What version of Music Assistant has the issue?

2023.6.0b3

### The problem

Failed to connect

### How to reproduce

I go to integration and add integration, music assistant beta. 
In music assistant server is http://mass.local:8095 , click next failed to connect.

### Additional information

I try on other ip and ports, this same problem

### What version of Home Assistant Core are your running

2023.9.1

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Replace `mass.local` with the actual ip address

**Comment by BrakkF** [comment]
I'm experiencing the same issue and when I replace mass.local with the the IP address of my homeassistant docker instance, it still fails.

**Comment by BrakkF** [comment]
I can't access the web server at the homeassistant ipaddress:8095 on a separate browser window.  I also tried running a separate docker container based off of this (https://github.com/music-assistant/server/blob/main/docker-compose.example.yml) and it almost seems like the docker container is unable to grab an IP address.

**Comment by OzGav** [comment]
I assume from what you have said that you have initially added MA as an addon. If that is the case then just go to the addon page and access the server from there. In this situation the websever on port 8095 is not enabled by default.

if you have issues with the docker version check the instructions carefully and ensure you have created the container in host networking mode.

**Comment by nocalla** [comment]
I'm getting this issue too. The MA server is running perfectly in a docker container on my network and the web interface is accessible at `http://HOSTNAME:8095`, but when I go to connect the integration, I just get a non-specific "Failed to connect" error message. Nothing shows up in Logs, so unsure what to try. I've unticked the box to use the official add-on as the server is already running separately.

**Comment by danielgomezrico** [comment]
Using homeassistant.local:8095 it worked for me
