### ISSUE TITLE
Cannot seek or change song progress in local tracks

### ISSUE THREAD

**Issue by Traxtar928** [music-assistant/hass-music-assistant#1583]
### What version of Music Assistant has the issue?

2023.6.0b3

### The problem

Cannot seek progress in tracks playing from local source or NAS. Seeking works fine using Home Assistant built in Media storage method, but gives errors when using music assistant.

Error is:

Failed to call service media_player/media_seek. Value xxx.xxxxxxx of type <class 'float'> is invalid for position, expected value of type <class 'int'>

![Screenshot_20231028_134821_Home Assistant](https://github.com/music-assistant/hass-music-assistant/assets/46948982/da5eb4ac-e37a-4ceb-9745-c03c706f6735)

### How to reproduce

Use front end card type custom: mini-media-player

Play song using Media Assistant on speaker defined in card.

Attempt to seek anywhere in track.

![Screenshot_20231028_135523_Home Assistant](https://github.com/music-assistant/hass-music-assistant/assets/46948982/d834f203-1dae-43fc-bb5a-c7940a754d89)

### Additional information

Of

### What version of Home Assistant Core are your running

2023.10.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Thanks. Confirmed.

**Comment by OzGav** [comment]
@Traxtar928 please confirm this has been fixed.

**Comment by Traxtar928** [comment]
![Screenshot_20231109_072437_Home Assistant](https://github.com/music-assistant/hass-music-assistant/assets/46948982/8b29a539-502c-4c2f-936a-dfff5a66d874)

![Screenshot_20231109_072159_Home Assistant](https://github.com/music-assistant/hass-music-assistant/assets/46948982/c91f3f55-558f-43fc-8f85-4d3f0d28dcf9)

![Screenshot_20231109_071523_Home Assistant](https://github.com/music-assistant/hass-music-assistant/assets/46948982/bfab0d4f-91a8-4a0d-913f-fcfe92ad0c16)

Seek bar is now missing from the mini media player card. Present earlier, shown in orange... Now missing entirely.

Music Assistant server window - 

The media player control interface text is greyed out and cannot be interacted with for seeking.

Pressing anywhere on the media player control interface (besides the speaker icon, volume icon, or play/pause icon, album art, artist text, track text) will not seek.

Selecting the artist in the media player changes server window to "track", not artist.

Selecting the track title in the media player changes server window to "artist", not track.

User expects pressing on media player will cause track currently playing to seek to that location (pressing the middle of the media player will seek to 50% progress), but instead the server screen will switch from 'Home' to 'Artists' or 'track'. Only way to seek is to press album art square, which opens currently playing track info and shows progress bar.

Ideally, a clearly-defined dedicated progress meter would be implemented into the server window built in media player control interface. Currently, the media player control interface shows a different lighter color move across the interface from left to right to indicate track progress, which cannot be interacted with.

https://github.com/music-assistant/hass-music-assistant/assets/46948982/b54f557e-2b2b-4f83-9bcd-ea4391ff6300

**Comment by OzGav** [comment]
Will look at the track progress indication but all those other frontend quirks you listed I cannot recreate. Can you make sure your browser cache is cleared and try again.

**Comment by Traxtar928** [comment]
Can you provide your code and front end screenshot of mini media player card showing progress bar? 

I just created a card from scratch and selected a media player entity generated by the music assistant integration, and there is no progress bar shown.

What version of mini media player are you using? I'm using v1.16.5

![Screenshot_20231109_182601_Home Assistant](https://github.com/music-assistant/hass-music-assistant/assets/46948982/843a2b62-b0d6-4f5b-9879-422d232dd833)

**Comment by OzGav** [comment]
No I was referring to the other things you said like “click on artist and get track view”. I don’t see the progress bar either which is why I said we will look at that indication

**Comment by Traxtar928** [comment]
Understood. After reviewing the track list further, my issue appears to be a metadata problem. 

Lack of a dedicated seek bar and greyed out text in the music assistant media player is ongoing. I can move that to a new request if you prefer.

**Comment by OzGav** [comment]
Actually do open an issue for missing seek bar and see what happens there. The greyed out text you refer to is possibly already reported here? https://github.com/music-assistant/hass-music-assistant/issues/1606
