### ISSUE TITLE
Changing player provider log level causes adverse effects

### ISSUE THREAD

**Issue by OzGav** [music-assistant/hass-music-assistant#1584]
### What version of Music Assistant has the issue?

2023.2.b74

### The problem

When changing the chromecast provider log level from global to debug all chromecast players became unavailable. Fixed by disabling and then enabling the player provider.

when changing the airplay provider from debug to global the player view in settings became unavailable, fixed by restarting the addon.

### How to reproduce

As above

### What version of Home Assistant Core are your running

2023.10.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by marcelveldt** [comment]
Can you check is this is still an issue ?

**Comment by OzGav** [comment]
Can’t check as there is a new problem now (same problem for Chromecast and Airplay providers)

<img width="742" alt="image" src="https://github.com/music-assistant/hass-music-assistant/assets/19848947/29ecfeed-3e0f-4ee8-ac8a-4ca8ad076bc9">

**Comment by marcelveldt** [comment]
can you recheck again please ?

**Comment by OzGav** [comment]
Yes fixed
