### ISSUE TITLE
Cannot upgrade or install MASS

### ISSUE THREAD

**Issue by wilfredsmit** [music-assistant/hass-music-assistant#159]
I first tried to upgrade to the new v1.1.0 version. This didn't worked. Then I removed MASS completely and tried to re-install it. Doesn't work either.

**Comment by marcelveldt** [comment]
Do you an error in the log ?
Maybe the pypi package is not yet available on all mirrors. I literally just published the 1.1.0 package

**Comment by wilfredsmit** [comment]
`2022-05-14 16:41:13 ERROR (MainThread) [custom_components.hacs] <Integration music-assistant/hass-music-assistant> No assets found for release 'tags/1.1.0'
2022-05-14 16:41:13 ERROR (MainThread) [custom_components.hacs] Could not download, see log for details`

**Comment by marcelveldt** [comment]
Ah, i see the fuild failed. I'll re-push the release.
Thanks for your message

**Comment by marcelveldt** [comment]
Build succeeded. Can you try again ?

**Comment by wilfredsmit** [comment]
Installed and rebooting! 👍🏼

**Comment by wilfredsmit** [comment]
Thanks for your quick response!
