### ISSUE TITLE
Two albums that both have the same track are merged into one album

### ISSUE THREAD

**Issue by codeblue11** [music-assistant/hass-music-assistant#1601]
### What version of Music Assistant has the issue?

2023.10.1

### The problem

I'm having an issue where if two albums have the same song then MA will 'merge' the two albums and put them all as one album with all the songs from both albums.

### How to reproduce

I have two albums, Album A and Album B. Album A is by Artist A and Album B is a mixtape by Various Artists. All tracks are tagged to the correct album. Both albums have the same song that is by Artist A.

What happens is that ONLY Album B shows up in MA and it contains all tracks from both Album A and Album B and the album artwork for Album A. 

### Additional information

Screenshot showing Album A details (Welcome Interstate Managers by Fountains of Wayne)
![Screen Shot 2023-11-02 at 11 21 20 AM](https://github.com/music-assistant/hass-music-assistant/assets/67980776/26a389ce-ceb1-44dc-a373-a6dd53b21808)
Screenshot showing Album B details (Kyle's CD 2 by Various Artists)
![Screen Shot 2023-11-02 at 11 22 07 AM](https://github.com/music-assistant/hass-music-assistant/assets/67980776/8aaf0ed4-e0a2-4e3c-b13d-29eb5d667f1d)

In MA the album Welcome Interstate Managers does not exist. Only Kyle's CD 2 exists and contains the tracks from Welcome Interstate Managers. Screenshot of Kyle's CD 2 shown below. 
![Screen Shot 2023-11-02 at 11 31 18 AM](https://github.com/music-assistant/hass-music-assistant/assets/67980776/8cbf3e89-1b05-4037-b48b-132e4a2e3dfb)
![Screen Shot 2023-11-02 at 11 31 37 AM](https://github.com/music-assistant/hass-music-assistant/assets/67980776/3b571f11-e138-47fd-bb96-92a6f5f82ea0)

### What version of Home Assistant Core are your running

2023.10.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
What additional tagging has been done to those tracks. Do they have Musicbrainz tags for example?

**Comment by codeblue11** [comment]
> What additional tagging has been done to those tracks. Do they have Musicbrainz tags for example?

Yes they have full Musicbrainz tags, except for the "Various Artists" album I changed the Album and Album Artist tags to 'Kyle's CD 2' and 'Various Artists'. So the song title and artist for the song Mexican Wine by Fountains of Wayne would be the same on both cd's, but each copy of the song has different tagged information for album and album artist.

**Comment by OzGav** [comment]
If they still have the same Musicbrainz ID tags then that is why these would be grouped together. Those unique tags are used over ambiguous ones such as the artist and album names.

**Comment by codeblue11** [comment]
Ok, so I can probably fix it by removing the Musicbrainz ID tags from my Various Artists album? 

It still seems odd that it grouped the entire albums together when there was only one song in common.

**Comment by OzGav** [comment]
True. It’s hard to say when I can’t see all the tags. But know that it is the special MB tags that MA prefers. So if you had a simply tagged series of tracks and you changed the album title then you would get what you expect. However, when it is tagged with Picard then there is a rich series of tags that MA is using to link tracks and albums across multiple providers. So it is these tags that are preferred. Manually changing just a couple of tags on a couple of tracks can have unexpected consequences.

Im not completely ruling out a bug but given you have manually edited the tags that is the first place to look.

**Comment by OzGav** [comment]
And really if you are wanting to make your own various artist album you should actually use a playlist instead of creating multiple versions of the same track.

**Comment by codeblue11** [comment]
Thanks for the help on this. I was able to fix the issue by removing the special MusicBrainz ID tags from the 'Various Artists' albums. 

I still think there's something odd/buggy about the way the entire albums were combined. If you look at my example in the initial issue report even though they only have one song in common (with the same MB tags), the entire first album was put into the second album. The first album ( Welcome Interstate Managers by Fountains of Wayne ) would have been properly tagged, the second album (Kyle's CD 2) would have the special MB ID tags attached to each individual song, but I changed the Album and Album Artist tags after tagging with MusicBrainz.

**Comment by OzGav** [comment]
Yeah I think manually changing the tags is probably the issue. Note thie following from here https://kodi.wiki/view/Music_tagging

> Once the music files are tagged, avoid modifying the MusicBrainz tags unless you clearly understand the relationship of the MBID's and the other related tags. For example, embedding MBID tags, but then editing the Artist tag or Album Artist tag will result in incorrect entries in the library.
