### ISSUE TITLE
[Plex] Error when adding Provider ("library_id has unexpected type")

### ISSUE THREAD

**Issue by Michi0606** [music-assistant/hass-music-assistant#1602]
### What version of Music Assistant has the issue?

2023.6.0b6

### The problem

Error Message when adding Plex Music Provider

![image](https://github.com/music-assistant/hass-music-assistant/assets/128812272/6ebb9e42-d774-45cd-9390-5778993afb88)

### How to reproduce

Try to add Plex Music Provider

### Relevant log output

2023-11-03 14:07:35.364 ERROR (MainThread) [music_assistant.webserver] [140259477570576] Error handling message: CommandMessage(message_id=220, command='config/providers/save', args={'provider_domain': 'plex', 'values': {'token': '**XXXX**', '**library_id': {'title': 'syn1 / Musik', 'value': 'https://HIDDEN/ syn1 / Musik'}**, 'log_level': 'GLOBAL'}})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/webserver.py", line 372, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/config.py", line 256, in save_provider_config
    config = await self._add_provider_config(provider_domain, values)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/config.py", line 699, in _add_provider_config
    config: ProviderConfig = ProviderConfig.parse(
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/common/models/config_entries.py", line 170, in parse
    conf.values[entry.key].parse_value(
  File "/usr/local/lib/python3.11/site-packages/music_assistant/common/models/config_entries.py", line 140, in parse_value
    raise ValueError(f"{self.key} has unexpected type: {type(value)}")
ValueError: library_id has unexpected type: <class 'list'>

### Additional information

Plex Account is linked to a private Plex Server which is running on a Synology NAS (DSM Plex Server Package) and has the Server-Adress "https://HIDDEN" (at the moment, because public IP of NAS-Server changes once a day). I can open this Link in my Browser and it shows all the content of the private Plex Server, but the content is also shown in my "app.plex.tv"

**Direct Link to private Server (at the moment)**
https://HIDDEN

**app.plex.tv**
![image](https://github.com/music-assistant/hass-music-assistant/assets/128812272/9840bff0-4c41-4dcb-90c6-a7b4d44e0987)

### What version of Home Assistant Core are your running

2023.11.0

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Alternative

**Comment by OzGav** [comment]
For your security don’t publish your public URL.. I have edited your post

**Comment by OzGav** [comment]
Have you carefully followed the installation instructions here https://github.com/orgs/music-assistant/discussions/1168

**Comment by rtrabig** [comment]
Has anyone resolved this?  I am getting the same error and I have followed the instructions in the link above, which seems out dated as the authentication occurred now through the plex account auth api.  The authentication token is added as well as the library but I get the unexpected type: <class 'list'> error when trying to save.

**Comment by OzGav** [comment]
Unfortunately this might take a while to get looked at as the dev that was running with this is not currently available…. Sorry.

**Comment by SeeDborg** [comment]
Same problem for me... 👎

**Comment by portigui** [comment]
Add my name to the list with this problem.

**Comment by welle** [comment]
Same issue :(

**Comment by OzGav** [comment]
Try Plex again with beta 83. Advise if this issue is fixed.

**Comment by OzGav** [comment]
I will close this soon assuming it has been fixed…

**Comment by Michi0606** [comment]
Hi, thanks for fixing the issue. I can not test at the moment, maybe someone else who had the issue can confirm that it is fixed.

Best regards Michael
