### ISSUE TITLE
Front end style issue: music bar not readable

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#1606]
### What version of Music Assistant has the issue?

b74

### The problem

This issue is there for several releases. The problem is that the music bar is not readable when there is no album art. The icons and text are white on a white background.
This seems to happen in the mobile version of the music bar  as I see it only happen in portrait mode on my iPhone

### How to reproduce

Play an external source (no art). 

Portrait view but readable:
<img width="375" alt="image" src="https://github.com/music-assistant/hass-music-assistant/assets/4363599/e994948b-e5c1-4c70-a8f4-3bf4e29d99d4">

Landscape view is OK:
<img width="812" alt="image" src="https://github.com/music-assistant/hass-music-assistant/assets/4363599/130cd7eb-8a18-4097-97db-957b5db53213">

### Relevant log output

Na

### Additional information

Na

### What version of Home Assistant Core are your running

Na

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by Traxtar928** [comment]
![Screenshot_20231109_072159_Home Assistant](https://github.com/music-assistant/hass-music-assistant/assets/46948982/f0b2f9b2-0085-46a0-8de9-6e3d447110ec)


![Screenshot_20231109_071523_Home Assistant](https://github.com/music-assistant/hass-music-assistant/assets/46948982/0cdebb88-b399-4e31-97b0-511fe08edb48)

Confirming this is also an issue on dark themes... Text should default to inverse colors for easier viewing. Light themes have black text, and dark themes have white text.

The current text colors are even more difficult to read as the progress bar moves across the player with a lighter shade.

**Comment by OzGav** [comment]
Should be fixed in b105. Please advise if not.
