### ISSUE TITLE
Airplay radio issue returned after 2.0.0b74 upgrade

### ISSUE THREAD

**Issue by davyrolink** [music-assistant/hass-music-assistant#1615]
### What version of Music Assistant has the issue?

2023.6.0b3

### The problem

After upgrading music-assistant/server from 2.0.0b73 to 2.0.0b74, I am experiencing an issue which also existed before, but which works without problems in 2.0.0b73.

If I steam a radio station to an AirPlay device, the stream changes from normal music to loud white-noise-ish after 78-79 minutes. I have tested this several times, using tunein and the radio stations 538 and slam. Streaming the same radio stations to a chromecast audio device goes all day without problems.

I have also tested that after downgrading to 2.0.0b73 the problem no longer occurs, after upgrading again to 2.0.0b74 the problem reappears.

### How to reproduce

Upgrade music-assistant/server from 2.0.0b73 to 2.0.0b74, start a radio station using tunein (538/slam tested), play it to a AirPlay device for 78-79 minutes.

### What version of Home Assistant Core are your running

2023.11.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Thanks for the report. This will get reviewed in due course

**Comment by Paul-Vdp** [comment]
Aha ... I think that's what happened yesterday to me too - after playing a radio station on my Airplay speaker for some time (cannot vouch for it to be around 78 mins, but that sounds about right). As this was a first for me, I thought it was a just a one-off glitch, so didn't think much of it ...

**Comment by OzGav** [comment]
This should be fixed in beta 75. Let us know if not.
