### ISSUE TITLE
Multi-artist tracks not imported as expected

### ISSUE THREAD

**Issue by wmvos** [music-assistant/hass-music-assistant#1619]
### What version of Music Assistant has the issue?

2023.6.0b6

### The problem

Not really sure whether this is a bug or just a design choice but multi artist tracks are not displayed as a expected them to be. The information from the ID3 tags seems to be ignored and most metadata concerning supporting artists seems to be lost.

Every song on an album is just attributed to the Album artist (not in case off various artist although I don't know about multi artist in that specific case).

The only thing that I could find was multiple artists attributed to a single album (so not the individual tracks of that album). This appears to happen when the Artist folder name does not match the Album artist tag so both are added.

I've attached the tags and folder structures for two tracks and the resulting album pages.

### How to reproduce

\Library\Alice Coltrane featuring Pharoah Sanders\\[1971] Journey in Satchidananda [1997] [mp3]\01 Journey in Satchidananda.mp3

| Relevant Tag | Value | 
| ---- | ---- |
| Title | Journey in Satchidananda |
| Artist | Alice Coltrane |
| Album | Journey in Satchidananda |
| Album Artist | Alice Coltrane featuring Pharoah Sanders |
| Album Artist Sort Order | Coltrane, Alice featuring Sanders, Pharoah |
| Artist Sort Order | Coltrane, Alice |
| Artists | Alice Coltrane |
| MusicBrainz Artist Id | d24fc285-7b2f-47da-8ac5-4070b08570b1 |
| MusicBrainz Recording Id | cc789d0a-8423-45fe-be44-7dc392744592 |
| MusicBrainz Release Artist Id | d24fc285-7b2f-47da-8ac5-4070b08570b1; b3a0912a-a62a-4388-9368-7cb21ed5caf9 |
| MusicBrainz Release Group Id | cf154081-2678-3778-95cf-cd31c4ea5dfe |
| MusicBrainz Release Id | a73f9292-912a-4cda-bd5b-3f52282ffc1e |
| MusicBrainz Track Id | 2e625d5f-2a2c-3c3f-85b3-fe8b58561096 |

![Journey in Satchidananda](https://github.com/music-assistant/hass-music-assistant/assets/64206115/f652fab7-0c26-471f-8c3b-bf30b283d8f0)

\Library\deadmau5\\[2012] _ album title goes here _ [mp3]\1-05 deadmau5 feat. Gerard Way - Professional Griefers.mp3

| Relevant Tag | Value | 
| ---- | ---- |
| Title | Professional Griefers |
| Artist | deadmau5 feat. Gerard Way |
| Album | > album title goes here < |
| Album Artist | deadmau5 |
| Album Artist Credit | deadmau5 |
| Album Artist Sort Order | deadmaus |
| Artist Credit | deadmau5 feat. Gerard Way |
| Artist Sort Order | deadmaus feat. Way, Gerard |
| Artists | deadmau5; Gerard Way |
| MusicBrainz Artist Id | 4a00ec9d-c635-463a-8cd4-eb61725f0c60; 53dc88bd-cdcb-440d-81aa-51a40ef07848 |
| MusicBrainz Recording Id | 5ee43904-766c-4ff3-a71c-765ea93e71b9 |
| MusicBrainz Release Artist Id | 4a00ec9d-c635-463a-8cd4-eb61725f0c60 |
| MusicBrainz Release Group Id | 5e6e08c0-fd41-46f4-8c43-768b57214804 |
| MusicBrainz Release Id | 1881bbb9-7949-416e-816d-e63ed059f49a |
| MusicBrainz Track Id | 5c9fa00c-e6b9-3f6f-8c2b-1990b37165c4 |

![deadmau5](https://github.com/music-assistant/hass-music-assistant/assets/64206115/1aebbbd9-958e-4cf4-8324-3261a02a97c9)

### What version of Home Assistant Core are your running

2023.11.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
Looking at one of mine I see both attributed and I can search for either artist 
![image](https://github.com/music-assistant/hass-music-assistant/assets/19848947/2994807f-48d7-42dd-a800-fc9ba70a72fa)

![image](https://github.com/music-assistant/hass-music-assistant/assets/19848947/355513bf-ed2a-42a0-a8ae-d6c4bb6d53ba)

You have the three issue reports with different problems which I don't recall others experiencing. Have you imported and then retagged and then tried to resync or was everything tagged with Picard before you tried to import into MA?

**Comment by wmvos** [comment]
I had imported them previously without tagging and letting MA tag by 'Use Track Artist(s) but that was a mess so I then removed the Filesystem entry from MA so there were no tracks in MA, tagged everything with Picard, and then added the folder again.

Does that leave any residual information in the database that could be causing these things?

**Comment by OzGav** [comment]
Yeah I am wondering if it has. Marcel would say that he wants MA to handle these sorts of circumstances but depending on how long you want to wait you could completely uninstall MA and then reinstall and start over again. If you do that though we will likely close the three issues as you wont be able to help with any further fault finding required. However if it remains a problem then we will have a clean slate to carefully look at the problems (and keep debug logging off unless we ask for it to be turned on as it spams the logs for no gain in most circumstances)

**Comment by wmvos** [comment]
Ok, I know for sure there was at least one 'deadmau5 feat. someone' (can't remember which) artist in the previous situation so you'd at least expect that one to persist. But when I re added the folder it had to download all artist information again so it would seem everything was removed before.

I'll spin up a fresh HA/MA install and try to see if that clears it, than we could still go back to see if there is something to find.

If it turns out to be some previous data maybe a 'Clear Database' button would be an option.

**Comment by OzGav** [comment]
The database should be cleaned up when you remove the provider. However it isn't instant and if you restarted MA before that completed then it wont start again and you could have DB corruption

**Comment by wmvos** [comment]
Ok I cloned my HA vm, removed MA from add-ons/HACS/integrations, reinstalled and imported my music folder. That seems to have solved #1618. 

Unfortunately the artist attribution hasn't changed:

![10 73 21 128_8123_d5369777_music_assistant_beta_ingress (3)](https://github.com/music-assistant/hass-music-assistant/assets/64206115/52d34932-7a38-4f30-b984-40a22c1fc73a)

Also concerning #1617 every self-titled album is now attributed to a different artists album:

![10 73 21 128_8123_d5369777_music_assistant_beta_ingress](https://github.com/music-assistant/hass-music-assistant/assets/64206115/55298d76-a398-4430-a9cf-e3074e3b8bb3)

![10 73 21 128_8123_d5369777_music_assistant_beta_ingress (1)](https://github.com/music-assistant/hass-music-assistant/assets/64206115/f114496b-115a-4ee8-afef-8bb1d1f3ec6f)

![10 73 21 128_8123_d5369777_music_assistant_beta_ingress (2)](https://github.com/music-assistant/hass-music-assistant/assets/64206115/dc2bad8f-826a-4a7a-9121-26149f68d2cc)

![10 73 21 128_8123_d5369777_music_assistant_beta_ingress_auth_callback=1 code=0138dfaa98c845fe8abf51bace1c11ac state=eyJoYXNzVXJsIjoiaHR0cDovLzEwLjczLjIxLjEyODo4MTIzIiwiY2xpZW50SWQiOiJodHRwOi8vMTAuNzMuMjEuMTI4Ojgx](https://github.com/music-assistant/hass-music-assistant/assets/64206115/d7d1ed74-79e2-4580-81c4-974e2e5c2cea)

**Comment by wmvos** [comment]
Ah I did find a change:

![10 73 21 128_8123_d5369777_music_assistant_beta_ingress (4)](https://github.com/music-assistant/hass-music-assistant/assets/64206115/72194237-a307-4f0d-9f06-ccc505fe122e)

**Comment by OzGav** [comment]
I am wondering if your directory structure is confusing things. For example this
`\Library\Alice Coltrane featuring Pharoah Sanders[1971] Journey in Satchidananda [1997] [mp3]\`

should be 

`\Library\Alice Coltrane\Journey in Satchidananda\`

with all the tracks in the folder named after the album. I assume you are embedding your artwork because if you try to put in local artwork it will only work if artist and album names exactly match. MA expects the structure shown here https://kodi.wiki/view/Music_tagging It might cope with other structures but something about what you are doing is causing problems...

What I suggest is spin up your VM again but move just one of these albums to a separate share. Redo the folder structure so it is as per the recommendation above and try and import that one album. Look in the logs for errors when you do that.

**Comment by wmvos** [comment]
Ah I see one of the backslashes got cancelled out. Just to be clear the current folder structure is:

Library\
Artist Name\
[Original Release Year] Album Name [Version Release Year] [format]\
Disc#(if multidisk)-Track# Artist(if multi-artist) Trackname.ext

Thus:
Library\
Alice Coltrane featuring Pharoah Sanders\
[1971] Journey in Satchidananda [1997] [mp3]\
01 Journey in Satchidananda.mp3

So every album is in it's own folder which would pretty much be the same as the Kodi example (except for the use of brackets). None of the folders contain any additional artwork/nfo.

I'll try and play around for a bit with importing some single albums and changing the folder structure!

**Comment by OzGav** [comment]
OK. Yeah see if simplifying things makes any difference.

**Comment by wmvos** [comment]
This one remains a complete mystery, stripping all dates and brackets from the folder structure has not made a difference.

I looked through my library and there are two cases where is does work (sort of):

![10 73 21 130_8123_d5369777_music_assistant_beta_ingress](https://github.com/music-assistant/hass-music-assistant/assets/64206115/24f5ecfd-bb78-45ce-bb10-5383cc1bbd37)
![image](https://github.com/music-assistant/hass-music-assistant/assets/64206115/1e10dc80-b8f7-48b2-a66d-93505a871562)

![10 73 21 14_8123_d5369777_music_assistant_beta_ingress](https://github.com/music-assistant/hass-music-assistant/assets/64206115/4c8fc825-1b46-4a6b-8d08-b071682bea43)
![image](https://github.com/music-assistant/hass-music-assistant/assets/64206115/cb063331-92b2-4bae-9533-59074d9f5417)

These are from my primary HA/MA, in the new HA vm the first one works fine but the second one will only tag an album for one of the five tracks.

![10 73 21 130_8123_d5369777_music_assistant_beta_ingress (1)](https://github.com/music-assistant/hass-music-assistant/assets/64206115/8e193850-f131-4d49-8d98-dae1111a427d)

I tried to look for any commonalities between these two and the example you showed and the only thing I could think of was that the tags for Artists don't match with what is in the Album Artists tag, so I tried changing things a bit with the deadmau5 songs but that just make albums disappear or is simply ignored.

I cannot for the life of me figure out why these work and all the other ones don't

**Comment by wmvos** [comment]
I don't understand how this:
![image](https://github.com/music-assistant/hass-music-assistant/assets/64206115/ce1cf09a-7bb5-4c0b-adf5-431d95b9eb10)

Becomes this:
![image](https://github.com/music-assistant/hass-music-assistant/assets/64206115/1b19f908-6ea8-40fc-9cf7-b983661e0e97)

While this:
![image](https://github.com/music-assistant/hass-music-assistant/assets/64206115/6149411d-013f-45cc-b916-3f034636859f)

Becomes this:
![image](https://github.com/music-assistant/hass-music-assistant/assets/64206115/7ff4630c-ab60-46c0-b0bd-cf87d64ef359)

**Comment by OzGav** [comment]
You need to look in the logs and see if there was a problem pulling the info for Gerard Way from Musicbrainz….

**Comment by OzGav** [comment]
The latest updates improved the way tags are read and the library is built. Please check if this issue has been resolved.

**Comment by OzGav** [comment]
This will be closed soon if no further info is received.
