### ISSUE TITLE
Can't modify "Authentication token for MyPlex.tv" field

### ISSUE THREAD

**Issue by riddley** [music-assistant/hass-music-assistant#1622]
### What version of Music Assistant has the issue?

2.0.0b74

### The problem

My Plex token expired I guess because the Provider has a red ! so I went to update the Authentication Token and I'm not able to modify the contents of that text input. If I click the mouse-over X icon, that makes the hide/show icon visible and then I can see that the X icon has set the value to #CLEAR# but I still can't change the text.

Inspecting the element, it has 'readonly=""' as an attribute. If I remove that, I'm now able to modify the text field. I then tried to empty the field so I could paste the token I got from viewing XML and when the field was emptied I was taken to a Plex login which seems like it succeeded but when I click "Save" (back on the MA config page) I get a javascript alert that says 'library_id has unexpected type: < class "list">' If I then re-choose my library from the drop down, it appears to save correctly.

### How to reproduce

Described above.

### What version of Home Assistant Core are your running

2023.11.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Alternative

**Comment by OzGav** [comment]
So to confirm in the end you got it sorted but it was difficult?

**Comment by riddley** [comment]
Correct. Still bug(s) though, right?

**Comment by OzGav** [comment]
Yeah just trying to understand. The Plex provider is currently unmaintained so wanted to know if your process ended up working in case someone else has the same issue.

**Comment by arsenicks** [comment]
Just to let you know, I'm on a fresh install of 2023.12.0 on home assistant 2023.12.4, trying to setup the plex provider for the first time and got the same "library_id has unexpected type: <class 'list'>" error.

Just to confirm for others that could face the issue, the workaroung suggested in the original repost did work.


**Click the "Authenticate on myplex.tv" you'll be redirected to the Plex login which seems like it succeeded but when I click "Save" (back on the MA config page) I get a javascript alert that says 'library_id has unexpected type: < class "list">' If I then re-choose my library from the drop down and click save again, it save correctly.**

**Comment by arsenicks** [comment]
> Yeah just trying to understand. The Plex provider is currently unmaintained so wanted to know if your process ended up working in case someone else has the same issue.

It did work for me at least, so yeah probably a low priority small fix.

**Comment by OzGav** [comment]
Beta 83 requires you to remove and reinstall the Plex provider. Remember to give MA some time to clean up the db. Do NOT restart MA or the host until that is completed. Let us know if this issue is then fixed.

**Comment by OzGav** [comment]
I will close this soon assuming it is fixed in the latest version….
