### ISSUE TITLE
Non-consecutive Filesystem entries breaks adding new entries

### ISSUE THREAD

**Issue by wmvos** [music-assistant/hass-music-assistant#1625]
### What version of Music Assistant has the issue?

2023.6.0b6

### The problem

When using multiple filesystem entries the removal of some entries does not seem to be handled correctly. 

If the remaining filesystem entries are non-consecutive based on the initial time they were added, for example:

~~1~~2
1~~2~~3
1~~23~~4
1~~2~~3~~4~~

Adding a new filesystem entry will simply replace the last filesystem entry that already exists. So in case of the last example entry 3 is replaced by the new entry.

Restoring the consecutive order or completely removing all entries fixes things, so:

12~~3~~4 Adding replaces entry 4
12~~34~~ Adding creates new entry 3

### How to reproduce

- add 2 or more filesystem entries
- remove one or multiple entries so that the remaining filesystems are non consecutive in terms of how they were added
- add a new filesystem entry

### What version of Home Assistant Core are your running

2023.11.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Alternative

**Comment by marcelveldt** [comment]
I do not understand a single thing of your report. What do you mean with "filesystem entry" ?

**Comment by OzGav** [comment]
He was adding multiple file system providers

**Comment by wmvos** [comment]
Yup, so adding multiple separate folders/directories.

**Comment by OzGav** [comment]
This should be fixed in beta 82 please advise if not
