### ISSUE TITLE
V1.1.2: significant less CPU load😀

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#163]
This is not an issue but a as positive observation worth to share 😊:
![image](https://user-images.githubusercontent.com/4363599/168471593-af5daee2-82fe-461b-af77-646411388f52.jpeg)

**Comment by marcelveldt** [comment]
Great! That was where the v1.1 release was all about

**Comment by erkr** [comment]
You don't need close this issue then, let's keep this in :-)

**Comment by marcelveldt** [comment]
haha, I will close this issue but the low resource consumption stays, deal ?

**Comment by erkr** [comment]
Deal 👍
