### ISSUE TITLE
Installation hangs - Music Assist Server add-on is not available anymore

### ISSUE THREAD

**Issue by drosner** [music-assistant/hass-music-assistant#1633]
### What version of Music Assistant has the issue?

2023.6.0b6

### The problem

Installed from HACS with no errors, then restarted HA, then went to integrations to install there.  Hit install with the server-add-on option selected. The window shows "the add-on installation has started" and it hangs here indefinitely. I've scanned the logs and get an error in Home Assistant Core saying "Music Assistant Server Add-on is not available anymore" and an error in the Supervisor saying "github.music-assitant/home-assitant-addon, already in the story". I've deleted and reloaded a few times as i assume something got half installed somewhere. I am on the latest HA core and supervisor as i updated ahead of installing this.

### How to reproduce

each time i do an install of the integration

### Relevant log output

`This error originated from a custom integration.

Logger: custom_components.mass
Source: custom_components/mass/config_flow.py:85
Integration: mass (documentation, issues)
First occurred: 2:38:57 PM (1 occurrences)
Last logged: 2:38:57 PM

Music Assistant Server add-on is not available anymore`

`

23-11-13 14:38:57 ERROR (MainThread) [supervisor.store] Can't add https://github.com/music-assistant/home-assistant-addon, already in the store`

### What version of Home Assistant Core are your running

2023.11.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Try adding the addon manually first

**Comment by drosner** [comment]
Ok I'm getting an error saying my RaspPi4 with HA OS isn't supported. So sounds like not a bug...

**Comment by OzGav** [comment]
It is but you need the 64bit version of the OS
