### ISSUE TITLE
"White noise" when playing on Apple Airport

### ISSUE THREAD

**Issue by sergiosafer** [music-assistant/hass-music-assistant#1634]
### What version of Music Assistant has the issue?

Beta 2.0.0b73 

### The problem

I have 3 Airports installed in different Home Assitant and in all locations, I have the following error: After a random playback time (30-60 minutes) it starts to play a "white noise" and the only way it disappears is to pause Mussica Assitant or play the next track.

Thank you very much for your help.

### How to reproduce

I play a Spotify playlist in Mussica Assistant, it plays correctly on my Airport and after a while it starts a white noise.

### What version of Home Assistant Core are your running

2023.09.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Firstly please upgrade to beta 75

**Comment by OzGav** [comment]
Next, I’m not sure what you mean by “I have 3 airports installed in different home assistant”
