### ISSUE TITLE
Mounted cifs folder is visible in HA Media but not in music-assistant 

### ISSUE THREAD

**Issue by DrNaughtyDog** [music-assistant/hass-music-assistant#1638]
### What version of Music Assistant has the issue?

2023.6.0b6

### The problem

I mounted a NAS shared folder with this command:
mount -t cifs -o vers=3.0,username=username,password=passwd" //192.168.1.10/music" "/media/music_nas"
I tested it within HAOS Shell and then put it as automation to run at server startup.
This works so far as i can access the files and play them in the haos media tab, cool.
However, if i add the folder in MA, it shows up as empty.

### How to reproduce

Add a NAS shared folder through smb/cifs
Add the mounted folder in MA as local file provider
Try top Access the folder through MA

### What version of Home Assistant Core are your running

2023.11.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by DrNaughtyDog** [comment]
I run HAOS as VM in proxmox, If thats relevant.

**Comment by OzGav** [comment]
You need to add the share via the MA settings

**Comment by OzGav** [comment]
You don’t use the mount anymore. Just add the share directly to MA via File System (Remote Share)

**Comment by DrNaughtyDog** [comment]
Good Point, i tried that first, then the files show up, but cannot be played (mp3). I click on a File, select the Speaker, then nothing Happens. Should i Open a new issued for this behaviour?

The cifs mount way is from a discussion btw https://github.com/orgs/music-assistant/discussions/452 not my own head

**Comment by OzGav** [comment]
Yes please open a new issue for that with relevant logs.

that thread is from MA1. I’ll see what we can do about making that clear.

**Comment by OzGav** [comment]
Actually the marked answer in that discussion makes it clear that it is for MA1
