### ISSUE TITLE
Errors while importing local media

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#165]
Hi Marcel

I fixed most ID3 info for my local collection (ca 8000 tracks) and started importing them with debug logging on :-). Importing for most of the tracks goes well. Don't see many albums/artists (yet), only many tracks. But it's worth mentioning some errors and the related debug logging around that time:
```
Job [Add file://album/variousartistsfantasydancehitsvolume1 to database] failed with error 'NoneType' object has no attribute 'name'.
21:20:35 – (ERROR) /usr/local/lib/python3.9/site-packages/music_assistant/mass.py - message first occurred at 21:20:28 and shows up 2 times
[547391316272] Error handling message: Unknown error (unknown_error)
21:20:35 – (ERROR) Home Assistant WebSocket API (custom integration)
[547391316272] Error handling message: Unknown error (unknown_error)
21:20:28 – (ERROR) Home Assistant WebSocket API (custom integration)
[547391316272] Error handling message: Unknown error (unknown_error)
21:19:33 – (ERROR) Home Assistant WebSocket API (custom integration) - message first occurred at 21:15:26 and shows up 2 times
Job [Add file://playlist/varioushithistory1955198555m3u to database] failed with error argument of type 'NoneType' is not iterable.
21:19:33 – (ERROR) /usr/local/lib/python3.9/site-packages/music_assistant/mass.py - message first occurred at 21:15:26 and shows up 2 times
```
I attached also the debug log around these errors:
[debug.log](https://github.com/music-assistant/hass-music-assistant/files/8695793/debug.log)
`

**Comment by marcelveldt** [comment]
Haha you're feeling adventurous with running a scan of 8000 tracks with debug log on ;-)
That will be A LOT of logging coming your way.

By default only artists in their own folder will be marked as "library" artist.
The same applies to Albums.

So, if you have this structure `Artist\Album\Track.flac` the Artist will be marked as favorite, the Album and the track.
Tracks without any structure just dumped in the root of the disk will be added to the library but their artist and album will NOT be marked as favorite.

**Comment by erkr** [comment]
memory usage is exploding:
![image](https://user-images.githubusercontent.com/4363599/168491194-b1b5d794-a381-4d17-ab7b-f3d00fbbb0df.png)

**Comment by erkr** [comment]
What is the best way to stop the scan?

**Comment by marcelveldt** [comment]
1) The errors your shared in the logfile I just fixed so available in next release.
2) The initial sync caches the entire listing in memory, it should free memory again once initial scan is done.

**Comment by marcelveldt** [comment]
> What is the best way to stop the scan?

Just reload the integration and it will continue where it left off. 
Maybe do that a couple op times until the full collection is synced. 

That said, I'm going to change the logic a bit to make it free memory

**Comment by erkr** [comment]
Thanks I will do that

**Comment by erkr** [comment]
> By default only artists in their own folder will be marked as "library" artist. The same applies to Albums.
> 
> So, if you have this structure `Artist\Album\Track.flac` the Artist will be marked as favorite, the Album and the track. Tracks without any structure just dumped in the root of the disk will be added to the library but their artist and album will NOT be marked as favorite.

I don't fully understand yet. I added ID3 album and Artist info to avoid folder naming issues. I thought the folder names were only used as fall back when the ID3 tags are missing

Example of two folders mapped as one album:
`\Albums\Blind Guardian\Battalions of Fear`
`\Albums\Blind Guardian\Imaginations from the Other Side`
These two folders are tagged like this:
![image](https://user-images.githubusercontent.com/4363599/168492472-7ca70dfa-a628-4dd5-b299-4199537c477a.png)
![image](https://user-images.githubusercontent.com/4363599/168492519-90e7a53b-3b95-44aa-9af3-bc3cc2e56154.png)
Based on these tags, I hoped, these would be recognized as two separate albums

**Comment by erkr** [comment]
I expected a kind of memory use reset, but after one reload the memory became flat (much better): 
![image](https://user-images.githubusercontent.com/4363599/168492887-9c5d1440-504e-4825-90a3-f71209308d65.png)

**Comment by marcelveldt** [comment]
Actually, separate folder names are preferred over the ID3 tags, as is common in media software so I just blindly copied that behavior :-)

This is what I used as reference (including the nfo files support):
https://kodi.wiki/view/NFO_files/Artists

AlbumArtist\Album\Track.ext
Looks like you have the structure like this: Album\AlbumArtist\Track ?

If the structure Album\Artist\Track is found on disk, that will be used as metadata (and the other tags from ID3)
If that structure is NOT found it will take all tags from ID3.
ContributingArtists/Performers are always taken from ID3 tags.

An artist or album is only marked as favorite when it has its own dedicated folder (=Album Artist).
This is to prevent the library getting cluttered with "one day flies" and cooperating artists on tracks.
I guess I could change that to "album artists" only, either from ID3 or dedicated folder on disk ?

**Comment by marcelveldt** [comment]
> I expected a kind of memory use reset, but after one reload the memory became flat (much better): ![image](https://user-images.githubusercontent.com/4363599/168492887-9c5d1440-504e-4825-90a3-f71209308d65.png)

OK, please keep an eye on it because after a few hours the cache should auto free memory. If not I'll have to make some fun with garbage collector ;-)

**Comment by erkr** [comment]
It certainly memory will drop eventually with the Garbage Collector. Very glad the steep incline stopped after a reload :-)
> I guess I could change that to "album artists" only, either from ID3 or dedicated folder on disk ?

Not fully sure if I understand. if "album artists" means only when both album and artist are known (where it doesn't matter if that is retrieved from folder of ID3's). Yes, that sounds good to me :-)

Some more info on my folders (I can fix some issues of course). My music is organized in two structures:
Albums (not all that structured):
`\Albums\Avril Lavigne - My World\Mp3`
Collection CD's:
`Various\80s - Verantwoord CD1\Mp3`
`Various\Air Guitar - Compilation CD1\Mp3`
etc. Here Every directory ends in a MP3 folder. That I can fix. But these collection CDs have the album as a folder name only (no artists). But still some of these folders are recognized as albums.

PS: How can I start a new scan (clean slate) if I have fixed more isuses? By a reinstall of the integration, or some other way?
Best Eric

**Comment by erkr** [comment]
I survived the full scan in debug mode. 
![image](https://user-images.githubusercontent.com/4363599/168494725-0999d40a-d97a-4ddc-b6ba-6ddacb66a806.png)
Are you interested in the log file? Especially with *.m3u files there are errors

**Comment by marcelveldt** [comment]
OK cool!

I will adjust things on my side in the code and just treat the artist/album folders as extra.
Small change and then it will work in all scenario's, including yours.

And yes, the log would be great to check the issue with the playlists.
You may send me them by PM on discord if you prefer

**Comment by marcelveldt** [comment]
You can trigger a rescan by just deleting the music_assistant.db in your HA config folder.
Reinstalling the integration will also reset the db but then you need to redo the setup

**Comment by marcelveldt** [comment]
Reminds me of a feature request to just create a button for this somewhere in the UI:
- resync
- reset database

**Comment by erkr** [comment]
The full log:
[home-assistant full scan.log](https://github.com/music-assistant/hass-music-assistant/files/8696150/home-assistant.full.scan.log)

> You can trigger a rescan by just deleting the music_assistant.db in your HA config folder

Great, and for some reason, I notice a lot of double tracks in my track list. When l look up the details, the link points to the same file. So I will wait for some fixes and run a clean scan. 

Good night
Eric

**Comment by marcelveldt** [comment]
This one can be closed now, right ? It should all be fixed, including the memory usage.

**Comment by erkr** [comment]
I prefer to give it a test run with your next version

**Comment by erkr** [comment]
Hi Marcel
I just installed v1.1.4 and will do exactly the same import test of local media as done last time with Debug logging. That will allow me to test for both the doubles (1st import had too many tracks) and memory usage behavior. That will be done tomorrow as I don't want to interfere with my evening jobs

**Comment by erkr** [comment]
Yes, this import went way MUCH better in many aspects:
- Much faster; ca 45 minutes (even with debug logging for mass) instead of hours
- No mass errors in the log during the whole import
- Less memory usage
![image](https://user-images.githubusercontent.com/4363599/169007954-dab51369-977b-4436-bfe2-13843f42a063.png)

- slightly less CPU load
![image](https://user-images.githubusercontent.com/4363599/169008077-9d4ce7d2-6997-4dbd-a1f5-b1e00e927dae.png)

- Fewer tracks (no double ones I guess, this time it's close to my expectation of ca 8000):
![image](https://user-images.githubusercontent.com/4363599/169008240-2c7b0a0c-40bb-4ff0-a76b-4651cacb1222.png)

I only see too many albums, many with just one track! I will look into that later, I guess that can be caused by my automatic ID3 tag injection ;-)
