### ISSUE TITLE
[Server] Webserver component log level not taking effect

### ISSUE THREAD

**Issue by krisnoble** [music-assistant/hass-music-assistant#1656]
### What version of Music Assistant has the issue?

2.0.0b75

### The problem

Following up on #1477, I think the webserver component is still taking the global log value rather than the component-level one. I have global logs set to warning and webserver set to error but I'm getting warning-level logs.

I have the webserver exposed on port 8095 and open in a pinned tab in Chrome on my laptop so I'm guessing that's what's causing the warnings, haven't tested yet but have closed the pinned tab to see if that stops the warnings.

### How to reproduce

1. Set global log level to a more verbose setting e.g. warning
2. Set webserver log level to a less verbose setting e.g. error
3. See warning-level logs from webserver component

### Relevant log output

2023-11-27 07:21:53.026 WARNING (MainThread) [music_assistant.webserver] [140451541683472] Disconnected: Received non-Text message.
2023-11-27 09:09:26.844 WARNING (MainThread) [music_assistant.webserver] [140451300778128] Disconnected: Received non-Text message.
2023-11-27 09:10:52.026 WARNING (MainThread) [music_assistant.webserver] [140451311986896] Disconnected: Received non-Text message.

### What version of Home Assistant Core are your running

2023.11.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Can you please check if this is still a problem

**Comment by krisnoble** [comment]
Sure, probably won't have time until next week but it's on the to do list 👍🏻

**Comment by OzGav** [comment]
Hi Kris,
Just checking in again about this. I think there might still be a problem but would like you to confirm or otherwise.
Thanks!

**Comment by krisnoble** [comment]
Sorry for the delay, yeah I think so too, In fact not just limited to the webserver - I have global set to info, everything else set to warning or above but I'm getting info-level logs e.g. music controller syncs

**Comment by OzGav** [comment]
Thanks.This  is on the list for fixing before the 2.0 release.

**Comment by marcelveldt** [comment]
this one should be fixed in b125

**Comment by OzGav** [comment]
Closing assuming this is fixed. Please advise if not and we will reopen.
