### ISSUE TITLE
CPU usage increases each two hours during one hour

### ISSUE THREAD

**Issue by alvarossac** [music-assistant/hass-music-assistant#1659]
### What version of Music Assistant has the issue?

2.0.0b75

### The problem

I have noticed while checking CPU temperatures that each two hours CPU usage increases a lot during one hour, checking where that usage cames from I saw that it was Music Assistant. 

![imagen](https://github.com/music-assistant/hass-music-assistant/assets/6680922/47292a91-978f-473c-8c8c-d710f227b0fa)

(Congratulations, the add-on is superb)

### How to reproduce

I just have the addon running.

### What version of Home Assistant Core are your running

2023.11.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Check your sync interval. That normally runs every three hours but maybe you have changed it?

**Comment by alvarossac** [comment]
Sorry, weekend I was out, I just set the sync interval to 12 hours, I will let you know tomorrow morning if now the CPU spikes are each 12 hours that will confirm the sync process is the one hitting the CPU. 

Anyway, is it supposed to be so CPU intensive? can it be set to more than 12 hours?

Thank you!

**Comment by OzGav** [comment]
This would depend on the CPU of your device as well as the size of the library that is being scanned.

**Comment by alvarossac** [comment]
Nope, is exactly the same, first time maybe I don't explain it right as two hours is the "idle" time between spikes, so each three hours CPU goes up, it last for one hour and then there are two hours of normal activity, as soon as I stop Music Assistant those CPU spikes are gone.

**Comment by OzGav** [comment]
Can’t be the sync then…? Are you running MA in docker?

**Comment by alvarossac** [comment]
Yes it is running in docker, indeed I discovered that MA was the one taking the CPU while running "docker stats" in the middle of one of the spikes.

**Comment by alvarossac** [comment]
Going for it!

**Comment by OzGav** [comment]
I will close this soon if no firther updates

**Comment by alvarossac** [comment]
Sorry, Spain had a few bank holidays last week and I have not been home.

Since I removed the file system provider MA has been runing without CPU spikes. Do you want me to add the file system provider with a smaller library? or to check the logs when I add it just in case?

**Comment by OzGav** [comment]
yes try a smaller library. Mine is around 95GB and works fine but yours is four times bigger which is a large increase

**Comment by alvarossac** [comment]
Just in case I uninstall and install MA again. Now added a remote file system with 42.3GB, if it works ok I will let you know and I will keep adding until I add the full library again.

**Comment by OzGav** [comment]
In theory it would be possible to not sync automatically but that is not currently possible. Will see if @marcelveldt thinks this is possible to improve or if this is just what is going to happen if you are trying to load up such a large amount of data.

**Comment by alvarossac** [comment]
Thanks! I love MA and my music libraries are fairly stable (and if at some point I really want to sync early is not an issue to do it manually) and that way I will avoid hitting so hard the CPU (for energy consumption and lifespan of the hardware). 

One extra question, that library is already being served by a DLNA/UPnP media server, is there a way to add that media server as a Music Provider? That will solve my issues :P

**Comment by OzGav** [comment]
Understood. No DLNA servers are not currently supported

**Comment by alvarossac** [comment]
Ok, so now I think we have a better image of the situation. 

High CPU usage when syncing a large remote file system library.

I don't know if this qualifies as an issue, from my side is ok to close it. I will move a big chunck (if not all) to a local HA disk to see if in a local file system there is also such high CPU usage while syncing (my remote file system is fairly slow). In the meantime I will stop MA and start it when I want to use it, I hope moving to a local disk will help and I can have it running all the time. 

Will be great if someone else with a large library can check if it is also happening for him/her. If at some point disable sync (or setting the sync value to a very high number like once per week or month) will be great for me but I understand that there some other items with much higher priority.

Thanks for all the time and following me in this slow process hahaha.
