### ISSUE TITLE
Randomly stops playing

### ISSUE THREAD

**Issue by kesson1029** [music-assistant/hass-music-assistant#1664]
### What version of Music Assistant has the issue?

2.0.0b75

### The problem

Local music randomly stops playing. Or stops after one song with a full Queue.

### How to reproduce

Add additional songs to the queue

### Relevant log output

Seems that any adding of track or clicking of tracks or the play next track option will stop the playing of the queue.

### Additional information

Windows 10
VM Virtual Box
Core 2023.11.3
Supervisor 2023.11.6
Operating System 7.6
Frontend 20231030.2

### What version of Home Assistant Core are your running

Core 2023.11.3

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Windows

**Comment by OzGav** [comment]
Are you playing to a chromecast?

**Comment by OzGav** [comment]
We need some more information here or I will close this as stale.
