### ISSUE TITLE
v1.1.3 - Duplicate tracks created from "Show info"

### ISSUE THREAD

**Issue by vk2him** [music-assistant/hass-music-assistant#167]
I did a search on Rubber Bullets from the Artists tab and it found a single file with no Album art. NOTE there are 6,299 Tracks:

![Image 026](https://user-images.githubusercontent.com/22878629/168526052-8261cae3-f6e3-4518-9c42-2d3111ef6e17.jpg)

From the single search result I looked at the "Show info" screen by clicking the three dots:

![Image 028](https://user-images.githubusercontent.com/22878629/168526128-11b1be5a-90c0-45a5-868f-999d71e550b3.jpg)

I did a search again on Rubber Bullets from the Artists tab and this time there are two files, one with Album art. NOTE there are now 6,300 tracks:

![Image 027](https://user-images.githubusercontent.com/22878629/168526241-0bcbd7cb-c2d5-431b-83ab-bf00177d0e23.jpg)

The Show info for both look identical?

**Comment by erkr** [comment]
Yes observed the same in v1.1.2, same happened when playing a single track https://github.com/music-assistant/hass-music-assistant/issues/166

**Comment by marcelveldt** [comment]
It's not a bug it's a feature. You get 2 for the price of one ;-)

Of course I'm just joking. I'll have a look what went wrong.

**Comment by marcelveldt** [comment]
should be fixed in 1.1.4

**Comment by vk2him** [comment]
Testing it now - rebuilding db first

**Comment by vk2him** [comment]
Confirmed fixed on 1.1.4 - thanks!
