### ISSUE TITLE
Active filter is not visible to the user when the the search input is hidden

### ISSUE THREAD

**Issue by fuslwusl** [music-assistant/hass-music-assistant#1676]
### What version of Music Assistant has the issue?

2.0.0b77

### The problem

Hiding the search input filter in the header on the artist, albums or tracks view leads to confusion because the filter is still active when the input is hidden and there is no indicator that a filter is still active.

A very easy fix would be to clear the search input filter when the search input gets hidden. This will avoid confusion and I think this is what most users would expect.

### How to reproduce

It you filter artist, albums or for example your 6952 tracks by clicking on the search icon in the header and enter something f. e. "Metallica" you will see a reduced list with only f. e. 28 Metallica tracks. So far so good - this is what is expected.
But when you now click on the search icon in the header to hide the search input you will still see only the reduced list with 28 Metallica tracks and you don't have any indicator that a filter is currently active.
So a user will think he only has Metallica stuff and his other content is gone.

### What version of Home Assistant Core are your running

2023.12.0

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Complete list of the 4649 tracks**
![SCR-20231208-ftj](https://github.com/music-assistant/hass-music-assistant/assets/33591021/8aedca1c-9608-4cc1-a197-d76112dab34e)

**Filter set to "Rock" shows 29 tracks - this is fine**
![SCR-20231208-ftv](https://github.com/music-assistant/hass-music-assistant/assets/33591021/30f23811-e08a-4e00-b932-78dc2fc5fe9d)

**Filter still set to "Rock" and 29 tracks shown but nothing indicates this and the user would expect a list with all songs or an indicator that a filter "Rock" is active!**
![SCR-20231208-fu2](https://github.com/music-assistant/hass-music-assistant/assets/33591021/5deaf293-54b4-49b6-bee8-2c4743d6f243)

**Comment by marcelveldt** [comment]
We now have a badge when search is filtering items but I think that introduced another bug. If you clear the search box, all filter options seem to disappear. Can anyone confirm that issue ?

Also, I have the feeling that clearing the search is still a good idea when hiding the search bar

**Comment by jozefKruszynski** [comment]
It's worse than that, when I clear search via the button in the search box, then it removes the text, but leaves the active filter badge, and doesn't actually seem to update any view.

**Comment by OzGav** [comment]
A red dot is now shown on the search icon to indicate that the viewed results are the result of a filter
