### ISSUE TITLE
Heart icon is not shown in album or artist overview

### ISSUE THREAD

**Issue by fuslwusl** [music-assistant/hass-music-assistant#1677]
### What version of Music Assistant has the issue?

2.0.0b77

### The problem

In the view albums or artists there is no way to see if an item is starred or not (has a heart icon or not). In the tracks list this is fine.

Please add the icon in the albums or artists list, too.

### How to reproduce

Filter set to favorites so all items should have an heart icon. So you will not see if an album is a favorite or not in the unfiltered list.

![SCR-20231208-heo](https://github.com/music-assistant/hass-music-assistant/assets/33591021/05d5dbf7-f903-4dbd-a105-4634d1eec98f)

### What version of Home Assistant Core are your running

2023.12.0

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
There is if you change to list view. I will ask if there is a design reason why it isn't shwon in thumbs view.

**Comment by JeffersonBledsoe** [comment]
I've started a quick PR to add a 'favorite' icon: https://github.com/music-assistant/frontend/pull/300

Could do with some additional testing (And I need to figure out how internationalization works in vue to fix the aria-label for the icon to be read out as text with assistive technology such as a screen reader)

**Comment by OzGav** [comment]
Fixed in b103
