### ISSUE TITLE
[feature request] button to refresh the playlists (i.e from Spotify)

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#168]
In Order to fetch my latest playlists from Spotify, I now reload the integration. An update button would be nice.

**Comment by marcelveldt** [comment]
You can refresh a playlist from the contextmenu

**Comment by erkr** [comment]
Hi, 
Your are right, there is a refresh option for a playlist, but I was referring to refreshing the list of playlists😉
Best
Eric

**Comment by marcelveldt** [comment]
fixed in latest version (2022.6 beta 2)
