### ISSUE TITLE
some files don't work anyome

### ISSUE THREAD

**Issue by ignacio82** [music-assistant/hass-music-assistant#1684]
### What version of Music Assistant has the issue?

2.0.0b78

### The problem

Some mp3 files that used to play fine no longer work

### How to reproduce

Download https://www.gstatic.com/voice_delight/sounds/long/rain.mp3 and try to play it

![image](https://github.com/music-assistant/hass-music-assistant/assets/1833309/6cec4d51-eb2d-404b-af2b-db66900c8025)

### Relevant log output

  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 197, in play_media
    raise MediaNotFoundError(f"Invalid uri: {item}") from err
music_assistant.common.models.errors.MediaNotFoundError: Invalid uri: filesystem_local://track/wav/rain_3600.mp3

### What version of Home Assistant Core are your running

2023.12.1

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
Do all the other files in that folder play ok?

**Comment by ignacio82** [comment]
No. Some files play okay and some files do not. These are all files that
used to work perfectly fine, and still work fine on my computers. I pointed
to one that you can download to test.

**Comment by OzGav** [comment]
Can you see any pattern to which ones are working and which ones aren’t. For example, do all the ones that don’t work have the underscore in the file name?

**Comment by ignacio82** [comment]
No, I cannot identify a pattern. I tried changing the file names and that
made no difference. Does the rain file from the link I provided work for
you?

**Comment by OzGav** [comment]
No I haven’t tried it but the error is saying that MA can’t find the file. Do you have those few files added via a different provider or are they just a sub folder of all your other music?

**Comment by ignacio82** [comment]
all the files, the ones that work and the ones that do not, are added in
the same way. And all of those files used to work fine.

**Comment by OzGav** [comment]
Ok give me some time to try and recreate the problem.
