### ISSUE TITLE
Initialisation fails with "Invalid command: players/all"

### ISSUE THREAD

**Issue by kranzhoff** [music-assistant/hass-music-assistant#1685]
### What version of Music Assistant has the issue?

2023.6.0b6

### The problem

Initialisation of Music Assistant fails with "Invalid command: players/all".
As a result no players are available when clicking the speaker icon in the bottom right of Music Assistant page.
Media players are available and work fine in HomeAssistant though.

Reloading the integration or restarting HA does not solve the issue.

### How to reproduce

The error occurs since the 2023.6.0b6 update.
It worked fine before.

### Relevant log output

Logger: homeassistant
Source: /usr/src/homeassistant/homeassistant/runner.py:145
First occurred: 12:59:10 (1 occurrences)
Last logged: 12:59:10

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/client/client.py", line 201, in fetch_initial_state
    await self._players.fetch_state()
  File "/usr/local/lib/python3.11/site-packages/music_assistant/client/players.py", line 294, in fetch_state
    for player in await self.get_players():
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/client/players.py", line 65, in get_players
    return [Player.from_dict(item) for item in await self.client.send_command("players/all")]
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/client/client.py", line 168, in send_command
    return await future
           ^^^^^^^^^^^^
music_assistant.common.models.errors.InvalidCommand: Invalid command: players/all

### What version of Home Assistant Core are your running

2023.12.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
https://github.com/music-assistant/hass-music-assistant/issues/1678

**Comment by djtrao** [comment]
+1
