### ISSUE TITLE
Stream error and "no attribute 'decode'"

### ISSUE THREAD

**Issue by kongjudas** [music-assistant/hass-music-assistant#169]
I can't play anything from Spotify. My Google speakers pling as if they're ready, and then nothing. The process icon keeps spinning for a while and then everything stops. I have tried all of my 8 Nest speakers.

I get the following errors:

Stream error on spotify://track/************

Job [Analyze audio for ProviderType.SPOTIFY://track/*************] failed with error 'NoneType' object has no attribute 'decode'.

Error executing service: <ServiceCall media_player.play_media (c:0180cbfc99f4695aec51c265dc80501f): entity_id=['media_player.stuen_hoyttaler'], extra=enqueue=True, media_type=music, media_id=http://192.168.86.45:8095/media_player.stuen_hoyttaler.flac, enqueue=True>

In the last error, there's a reference to FLAC. Could there be something wrong with the decoder vs Spotify's file type?
***** = tracks

**Comment by marcelveldt** [comment]
Strange, Google cast platform should work rock solid with this integration.
Can you tell me a little bit about your Home Assistant setup ? What installation type hardware etc...
Are you running version 1.1.3 of the integration ?

Music Assistant internally works with PCM audio (so it decodes ogg vorbis) to do volume normalization, crossfading, gapless etc. The audio sent to the player is a long stream of the queue tracks, encoded as flac (instead of the raw pcm) to save bandwidth. So that's where the reference to FLAC comes from. In your setup the whole decode from Spotify seems to be failing, hence my questions about your setup.

**Comment by ullebe1** [comment]
I am also seeing this on version 1.1.18 on HASS core-2022.5.5, installed on Home Assistant OS (OVA) with HACS.

## System Health

version | core-2022.5.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.15.41
arch | x86_64
timezone | Europe/Copenhagen

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4635
Installed Version | 1.25.2
Stage | running
Available Repositories | 1129
Downloaded Repositories | 28

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | May 28, 2022, 2:00 AM
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | eu-west-2-0.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 8.1
-- | --
update_channel | stable
supervisor_version | supervisor-2022.05.3
docker_version | 20.10.14
disk_total | 20.0 GB
disk_used | 11.3 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Check Home Assistant configuration (3.10.0), File editor (5.3.3), Genie (3.0.0), ZeroTier One (0.13.3), Node-RED (11.1.2), AirCast (3.3.0), SSH & Web Terminal (10.1.3), Nginx Proxy Manager (0.11.0), AppDaemon (0.8.2), MariaDB (2.4.0), Samba share (9.6.1), ESPHome (2022.3.1), Zigbee2mqtt (1.25.1-1)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 14
views | 11
mode | storage

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

**Comment by marcelveldt** [comment]
@ullebe1 what do you experience exactly ?
Please describe step by step what you did...

Please be aware that port 8095 needs to be reachable between your media player and HA

**Comment by ullebe1** [comment]
@marcelveldt Steps to replicate the problem shown below. I have the Cast devices and the VM running Home Assistant OS on the same network with no firewalling in between. Do I need to do anything on the Home Assistant OS side to open the port?


Installation and setup:

- Install with HACS
- Add as integration in HASS
  - Set up Spotify as only account
  - Leave everything else at defaults
    - Kodi is only media player found in the next screen, not setting room
    - Observe that the rest of my players are added when refreshing integrations page

Use:

- Open Music Assistant pane
- Select playback device (single Google/Nest Home or a speaker group) 
- Select an album
- Press play
- Press play now
- Hear cast device say the "pling" sound indicating a connection
- First song is shown on bottom bar, but playback doesn't start
- Press the play button
- Nothing continues to happen
- Observe error logs appearing


```
Logger: music_assistant.mass.stream
Source: /usr/local/lib/python3.9/site-packages/music_assistant/controllers/stream.py:525
First occurred: 7:16:26 PM (22 occurrences)
Last logged: 7:16:52 PM

Stream error on spotify://track/3OfLNqMm0llO3uVi7rH9jf
Stream error on spotify://track/3mnkwuW3cUvpNuG0nw9zFx
Stream error on spotify://track/12Nel1DynDYCV8jwvPRqFn
Stream error on spotify://track/5bnLFoPAVzWaWLfhGYgL8Q
Stream error on spotify://track/6LyawiMzyPI1mbk3GMHjpW
```

```
Logger: audio
Source: /usr/local/lib/python3.9/site-packages/music_assistant/helpers/audio.py:172
First occurred: 7:16:26 PM (22 occurrences)
Last logged: 7:16:52 PM

Could not determine integrated loudness of spotify/3OfLNqMm0llO3uVi7rH9jf - received empty value
Could not determine integrated loudness of spotify/3mnkwuW3cUvpNuG0nw9zFx - received empty value
Could not determine integrated loudness of spotify/12Nel1DynDYCV8jwvPRqFn - received empty value
Could not determine integrated loudness of spotify/5bnLFoPAVzWaWLfhGYgL8Q - received empty value
Could not determine integrated loudness of spotify/6LyawiMzyPI1mbk3GMHjpW - received empty value
```

```
Logger: homeassistant.core
Source: components/cast/media_player.py:715
First occurred: 7:16:35 PM (5 occurrences)
Last logged: 7:17:15 PM

Error executing service: <ServiceCall media_player.play_media (c:01810684f298c350833f838bc52ce230): entity_id=['media_player.nestmini2383'], extra=, media_type=music, media_id=http://192.168.1.164:8095/media_player.nestmini2383.flac>
Error executing service: <ServiceCall media_player.play_media (c:01810684f4c13a9b0cccc80db6b2fb89): entity_id=['media_player.nestmini2383'], extra=enqueue=True, media_type=music, media_id=http://192.168.1.164:8095/media_player.nestmini2383.flac, enqueue=True>
Error executing service: <ServiceCall media_player.play_media (c:01810684f528f31b4dd86063bbadf27d): entity_id=['media_player.nestmini2383'], extra=enqueue=True, media_type=music, media_id=http://192.168.1.164:8095/media_player.nestmini2383.flac, enqueue=True>
Error executing service: <ServiceCall media_player.play_media (c:01810684f58e629fbef302bda184b0ba): entity_id=['media_player.nestmini2383'], extra=enqueue=True, media_type=music, media_id=http://192.168.1.164:8095/media_player.nestmini2383.flac, enqueue=True>
Error executing service: <ServiceCall media_player.play_media (c:01810684f5f27ab3f74bb5a4fb55093f): entity_id=['media_player.nestmini2383'], extra=enqueue=True, media_type=music, media_id=http://192.168.1.164:8095/media_player.nestmini2383.flac, enqueue=True>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1645, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1664, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 677, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 964, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 714, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/cast/media_player.py", line 715, in async_play_media
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/pychromecast/quick_play.py", line 77, in quick_play
    controller.quick_play(**data)
  File "/usr/local/lib/python3.9/site-packages/pychromecast/controllers/media.py", line 544, in quick_play
    raise PyChromecastError()
pychromecast.error.PyChromecastError

```
 
```
Logger: homeassistant.components.cast.media_player
Source: components/cast/media_player.py:388
Integration: Google Cast (documentation, issues)
First occurred: 7:18:25 PM (1 occurrences)
Last logged: 7:18:25 PM

Failed to cast media http://192.168.1.164:8095/media_player.nestmini2383.flac. Please make sure the URL is: Reachable from the cast device and either a publicly resolvable hostname or an IP address
```

**Comment by marcelveldt** [comment]
Thanks for the detailled response, that is very helpful!
So it looks like the whole Spotify session fails somehow. Note the "stream error" where there was no audio data received from "librespot", the open source spotify client.

I think that if you try a radio station or local music file it will work.
I'm trying to understand the issue and why it fails. Anything special about your internet connection ?
Just to be sure: You do have a Spotify premium account right? Free accounts will not work.

**Comment by marcelveldt** [comment]
@kongjudas can you confirm that you have a Spotify premium account ?

**Comment by ullebe1** [comment]
@marcelveldt Thanks for looking into it. This component is really cool!

I can confirm that I have a Premium account - it is a family subscription if that makes a difference.

Shouldn't be anything special about the the internet connection. I have an ordinary OPNsense firewall with no special rules. I'm also running an Adguard Home, I'll try to see if there is any logs there indicating something being blocker. Spotify works for both streaming and casting for other devices, so at least in most cases connecting to Spotify isn't a problem.

I'll try adding some local files or a radio station and let you know how that goes.

**Comment by marcelveldt** [comment]
OK great. Please note that in this case the spotify playback device (=librespot) is actually the Home Assistant device so maybe that is important for your firewall rules ?

If changing the firewall rules has no impact, I'd like to do some more tests together with you to find out the issue.

**Comment by marcelveldt** [comment]
I've discovered a low level issue today which might have caused the issue mentioned in this issue report. Please give the latest version 2022.6 a testdrive as it might fix it, thanks!

**Comment by ullebe1** [comment]
My firewall allows any outgoing connection, so that shouldn't be an issue. 
I've also tried disabling my DNS filtering, also didn't help.

I've updated to the newest `2022.6.0b2` but unfortunately my issue wasn't one of the ones that has been fixed.

Is there anything I can do to get more detailed logs or debug information, to help pinpoint the issue?

**Comment by ENGBERG80** [comment]
I have the same problem :(

**Comment by ENGBERG80** [comment]
Hey Marcel. I have now updated, but now i Can not select any speakers (in my case Chrome cast audio)

**Comment by marcelveldt** [comment]
Click "configure" on the Music Assistant card in "Integrations" and select which players you want to use with Music Assistant. I think that will do the trick.

**Comment by marcelveldt** [comment]
Please give step by step details of what is not working and details about your setup please:

1) Home Assistant installation method (HAOS, Supervised, Core)
2) Hardware running HA e.g. raspberry pi 4, Intel NUC etc)
3) Type of speaker(s) you are trying to control with Music Assistant
4) What is the issue exactly ? What did you do and what was the expectation ?
5) Please share your Home Assistant logfile (homeassistant.log) or any relevant parts from it.

**Comment by ENGBERG80** [comment]
I have HAos installed on a rpi 4, i have a chromecast audio, that plays fine with a internet radio addon in homeassistant.

the problem is, when i Press the little speaker in Music Assistant then there is no options. When i start Spotify and cast it to chromecast and go to media in homeassistant, then i Can se the son and artist just fine.


Shall i send the log file on mail to you ?

**Comment by marcelveldt** [comment]
There's a small error in the config flow at the moment, you need to manually select the players you want to use with Music Assistant:

Home Assistant settings --> Integrations --> Click "configure" on the Music Assistant card --> select your chromecast players there

**Comment by ENGBERG80** [comment]
![3DBB435A-4C1B-435F-BE7F-3841EB583F3B](https://user-images.githubusercontent.com/92541679/173890802-5584558e-122e-4cbf-9e55-fea494168a4e.jpeg)

**Comment by ENGBERG80** [comment]
I have done that. Its the One Callesen bang Olufsen

**Comment by marcelveldt** [comment]
@ENGBERG80 I'm not familiar with the B&O device to know if it should support "play url".
Can you play something like a radio stream from the built-in Media panel ?

What integration is used for the B&O streamers ? Is it a predefined standard like DLNA or does it have it's own integration ? Please note that Airplay based devices do still not work with MA due to lack of support in the apple_tv integration

**Comment by ullebe1** [comment]
I can confirm this was still an issue on BETA 5, will retest on the stable release.

I also had the same issue as @ENGBERG80 where even after selecting the player entities in the configuration they would fail to show up in Music Assistant. This was however a temporary issue. It lasted at least half an hour, but then I went to sleep and didn't check until next morning where they were present. Unfortunately I was quite busy and didn't have time to fill out a proper bug report.

I'll retest during the weekend to see which of these issues are still actual and then do a proper bug report. I'll probably also be available in the Discord for interactive bug-hunting, if that will help.

**Comment by marcelveldt** [comment]
See here if you are located in Denmark. A fix is on the way:
https://github.com/music-assistant/hass-music-assistant/issues/352

**Comment by ullebe1** [comment]
@marcelveldt I am. That's awesome, thanks! What a weird issue.

**Comment by marcelveldt** [comment]
Yeah... I was like WTF when I found out that it was specific to Denmark. Appears there is one server unreachable.

**Comment by marcelveldt** [comment]
Fix available in 2022.6.1

**Comment by ullebe1** [comment]
This issue has been solved and Spotify playback works for me, as of 2022.6.1. Thanks for all your work!

**Comment by ENGBERG80** [comment]
Its alive 😃😃😃😃😃 now it would be cool if you could make a script that starts a playlist 👍 i have tried throug HA media but Music assistent does noget work there

**Comment by erkr** [comment]
Thanks for verifying!
