### ISSUE TITLE
Music Assistant is not showing up as a media source

### ISSUE THREAD

**Issue by Mastermindaxe** [music-assistant/hass-music-assistant#1692]
### What version of Music Assistant has the issue?

2.0.0b78

### The problem

When trying to setup an automation to play music I was researching how to do this and stumbled upon https://github.com/orgs/music-assistant/discussions/710#discussioncomment-7440789. This `mass.play_media` does not show up for me. I can see the players that I have set up (Chromecast device and UPnP) but I neither see any service starting with `mass`, nor do I see Music Assistant under my media files to start a track or sth for my Chromecast device from a Music Assistant source
![Screenshot 2023-12-12 at 15 30 10](https://github.com/music-assistant/hass-music-assistant/assets/33257997/9890f249-cb88-4543-a887-60bf47d6bb9e)
![Screenshot 2023-12-12 at 15 30 33](https://github.com/music-assistant/hass-music-assistant/assets/33257997/2a336d1a-6654-4f43-8294-44bba7d01ee7)

If you guys need any more information I'll be happy to supply that. Beginner with Home Assistant, but being a developer relatively tech savvy I'd say. Happy to help

(Maybe I'm just dumb and forgot a config step or sth 😅)

### How to reproduce

Developer Tools -> Services -> Type `mass` into the service field. Nothing shows up

OR

Go to the media tab on the left sidebar.

### Additional information

I've set up Spotify and Tidal as providers. I was also able to successfully play back music from Tidal using the Chromecast device and/or UPnP.

### What version of Home Assistant Core are your running

2023.12.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Home Assistant Green

**Comment by OzGav** [comment]
Have you installed the integration from HACS?

**Comment by OzGav** [comment]
This will be closed soon due to no follow up

**Comment by Mastermindaxe** [comment]
Sorry for the late response, life got in the way. I have not. I just saw that it's the first sentence in the installation instruction... Totally my bad I suppose. Thanks for the amazing work on the plugin. I suppose everything will work when I install it via HACS
