### ISSUE TITLE
Can't add multiple radio URL.

### ISSUE THREAD

**Issue by ohnggni** [music-assistant/hass-music-assistant#1699]
### What version of Music Assistant has the issue?

2.0.0.b78

### The problem

I can't add more than one URL in Radio section.
For the first URL, I can successfully add it. But when I try the 2nd one, the added URL isn't shown on screen. I didn't face any error message.

### How to reproduce

1) Click the radio section
2) Add item from URL
3-1) Enter the first URL: e.g. http://localhost:3005/radio?keys=aaa_fm&token=abcdef
3-2) Enter the first one's name: e.g. aaa
-> the first one can be seen.
4-1) Enter the 2nd URL: e.g. http://localhost:3005/radio?keys=bbb_fm&token=abcdef
4-2) Enter the 2nd one's name: e.g. bbb
-> can't see the 2nd one in the list.
-P

### What version of Home Assistant Core are your running

2023.12.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
I'd say this is because MA sees them as the same thing as the URL is identical. The AUTH keys are not saved. This is is the subject of a separate issue.

**Comment by OzGav** [comment]
Please followup or we will have to close this

**Comment by ohnggni** [comment]
Okay. Thanks

**Comment by OzGav** [comment]
Keep an eye out for future updates where this may be supported. This is the related issue https://github.com/music-assistant/hass-music-assistant/issues/1485
