### ISSUE TITLE
Scroll position gets lost when switching between views

### ISSUE THREAD

**Issue by fuslwusl** [music-assistant/hass-music-assistant#1704]
### What version of Music Assistant has the issue?

2.0.0b77

### The problem

Switchin between views looses the scroll position.
This is not what i would expect and this is very annoying because the list has to be realoaded completely and you have to scroll a lot again everytime.

The context and states of the views (artist, tracks, albums, playlists, radio,...) should be kept separate so a reaload of all items could be completele avoided and this would speed things up a lot for the users when switching views.

I hope this can be fixed in one of the next versions.

### How to reproduce

1. Scrolled down to an artist for example Metallica
2. Switch to another views for example Tracks by clicking the sidebar icon
3. Switch back to the artist view by clicking the sidebar icon
Then you lost the scroll position and start on top of the list everytime.

### What version of Home Assistant Core are your running

2023.12.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by marcelveldt** [comment]
I agree with you but this is really difficult to get right as it involves storing state and scroll positions and that combined with a paged listing. 

We tried to prevent this but it was not really possible without side effects. For example keeping the list in memory is impossible when people have very large libraries etc.

If somebody wants to take a plunge at this, be my guest but now I consider it as not fixable until we get some help on the frontend.

**Comment by marcelveldt** [comment]
This is implemented in the next beta (b144)

**Comment by OzGav** [comment]
Doesn't seem to be working consistently for me but I will keep playing with it

**Comment by marcelveldt** [comment]
> Doesn't seem to be working consistently for me but I will keep playing with it

It only remembers the scroll position of the main library views and only in memory (so refresh will reset it).
The browser may limit when the listing becomes too large and then starts removing previous caches.
