### ISSUE TITLE
Limiting the number of search results is not working with Youtube Music

### ISSUE THREAD

**Issue by ipernjakovic** [music-assistant/hass-music-assistant#1710]
### What version of Music Assistant has the issue?

2023.6.0b6

### The problem

Executing a "mass.search" service call with the "limit" option set to 1 (or any other number) doesn't seem to make any difference, i always get full results back. I'm searching YTMusic provider, only for track name.

### How to reproduce

service: mass.search
data:
  name: Diary of Jane
  media_type: track
  limit: 1

### What version of Home Assistant Core are your running

2023.12.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by skyw33** [comment]
I have reproduced the problem using YTM.  Using the same setup as OzGav, I get 20 results.

**Comment by OzGav** [comment]
Thanks @skyw33 I will adjust the title...

**Comment by OzGav** [comment]
@MarvinSchenkel will you have time to check this?
