### ISSUE TITLE
Chromecast Audio Players don't play music (sound effects work though)

### ISSUE THREAD

**Issue by whoinow** [music-assistant/hass-music-assistant#1719]
### What version of Music Assistant has the issue?

2023.6.0b6

### The problem

When casting to a Chromecast Audio using Spotify as a source (or SMB), the UI shows the playhead time moving, but I can't hear anything with the speaker connected. When moving the volume slider, I hear the beep/dong on the speaker however. I chose a song to play and it shows playing, but pause and skip forward/back song buttons do not work.  I just played something directly from the Spotify app to the chromecast audio and that works fine. Lastly, looking at the Google Home app, it shows "Playing Default Media Receiver" as the speaker's status. When you first select a song to play, it shows it on the Google Home app, but the playhead never moves and goes back to the status message previously mentioned.

Note: After more testing, I found that a SMB share also has the same behavior (with MP3 files). Once I select a song and play on a chromecast device, it shows playing, but I never hear anything. Also selecting another song and playing it doesn't do anything either.

### How to reproduce

1. Add Spotify account source (or an SMB share)
2. Select song to play and select a Chromecast Audio to play it on

### Additional information

Home Assistant Addition versions:
Supervisor 2023.12.0
Operating System 11.2
Frontend 20231208.2

### What version of Home Assistant Core are your running

2023.12.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Do you have any other players that work?

**Comment by whoinow** [comment]
> Do you have any other players that work?

I don't have others to test (other then other chromecast devices, which none work).

**Comment by OzGav** [comment]
Could be a network problem then. Have you got a completely simple network setup or do you have firewalls, VLANs, multiple subnets, enterprise grade equipment or anything else that might interfere with mdns broadcasts?

**Comment by whoinow** [comment]
The mDNS seems resolving properly since when I attempt to us Music Assistant to cast, the chomecast device makes the connect noise and also changing volume via MA makes the bong/ding noise.  Also, using the spotcast integration in my HA instance works. Casting from my phone from Spotify to the same chromecast device works.

If there is logging or something I can enabled to provide more information, let me know.

**Comment by OzGav** [comment]
Are these the original chromecast audio devices (he little dongle) or are they nest speakers or something else?

**Comment by whoinow** [comment]
I have tried the Chromecast Audio and the original small Google Home devices (before Nest). I have a Nest Audio (bigger speaker) I thought I tried as well and it didn't work, but I could test again.

**Comment by OzGav** [comment]
If none of them work then it points to something with your setup as no one else is reporting this problem and I use the original home speaker as well as the small nest speakers just fine. 
Do you have any other software running on your network, like LMS, that might be interfering? Again what is your network setup?

**Comment by OzGav** [comment]
just need some surther follow up or we will have to close this

**Comment by whoinow** [comment]
You can close it, literally everything else works, so its not a a network issue. I will use spotcast.

**Comment by whoinow** [comment]
You can close it, literally everything else works, so its not a a network issue. I will use spotcast.
