### ISSUE TITLE
Listings mass_event not working

### ISSUE THREAD

**Issue by Dabbadoeber** [music-assistant/hass-music-assistant#1727]
### What version of Music Assistant has the issue?

2023.6.0b6

### The problem

The event handler does not show any event when trying to listen to mass_event.

### How to reproduce

Start listing in developer events

### What version of Home Assistant Core are your running

2023.12.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by marcelveldt** [comment]
May I first ask what you're trying to accomplish ?
So why you are listening to mass_event ? I don't think we're still forwarding those events (I think we did in V1)

**Comment by marcelveldt** [comment]
OK, I have added an extra attribute to the media_player's attributes called "stream_title" which will include the title as it is broadcast by the radio station (if exists). This change will be available in the next update of the HA integration for MA so keep an eye on HACS updates.

<img width="537" alt="Scherm­afbeelding 2023-12-30 om 02 25 29" src="https://github.com/music-assistant/hass-music-assistant/assets/6389780/1d1a4564-f25c-4253-a446-9e1f19aa8c79">

**Comment by OzGav** [comment]
Please report if this still an issue after beta7 of the integration is released
