### ISSUE TITLE
SlimProto integration players not detected

### ISSUE THREAD

**Issue by shamrt** [music-assistant/hass-music-assistant#1748]
### What version of Music Assistant has the issue?

2023.6.0b3

### The problem

I have a few DIY satellite RPis running [Squeezelite](https://github.com/ralph-irving/squeezelite) along with [the official SlimProto integration](https://www.home-assistant.io/integrations/slimproto). The satellites are present (and play media) in the Media section of HA, but they aren't in the list in Music Assistant.

### How to reproduce

- Install SlimProto integration
- Grab another RPi (that has Raspbian lite, along with an attached audio device)
  - Download and install a [recent squeezelite release](https://sourceforge.net/projects/lmsclients/files/squeezelite/) (I use the pulseaudio variant, so you may want to install `pulseaudio`, too). 
  - Check available output devices: `./squeezelite -l`
  - Run the binary with the output device specified: `./squeezelite -o [your device from above list]`
 - HA should quickly identify and auto-config with the Squeezelite entity
 - Check that the new entity is available in the HA Media section
 - Check that the entity is _not_ available in Music Assistant

### What version of Home Assistant Core are your running

2023.12.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Have you been through the trouble shooting FAQ?

**Comment by shamrt** [comment]
No, I haven't :frowning: 

Let me do that now!

**Comment by OzGav** [comment]
I can't remember if it is in there but try and play a TTS message from HA as well

**Comment by shamrt** [comment]
Apologies, I didn't notice the FAQ in the README.

So, per the [SlimProto FAQ](https://github.com/orgs/music-assistant/discussions/1123), I disabled the SlimProto integration in HA and restarted Music Assistant, and the the speaker now displays in the MA player list. 

Unfortunately, the speaker is no longer available from the HA side.

I take it you can't have more than one LMS running on a network? It's a shame I can't make full use of the speaker within HA as well. AFAICT, MA development is HA-agnostic. Are there plans for a more direct integration with HA so this sort of thing can be avoided?

**Comment by OzGav** [comment]
Correct MA is a LMS replacement they currently cannot coexist. Yes there are plans. In the first instance HA players will be exposed to MA. There has been some talk of allowing an LMS to run alongside MA but that is some way down the track.

**Comment by OzGav** [comment]
If all the slimproto players are now visible why do you still want the LMS?

**Comment by shamrt** [comment]
Okay, lovely! This will have to do for now; the MA integration is much more useful for my purposes.

> If all the slimproto players are now visible why do you still want the LMS?

I'm assuming SlimProto is more-or-less an LMS replacement; I was using LMS as shorthand, but more precisely, it seems two SlimProto servers cannot coexist either :smile: 

Anyway, thanks for the super-speedy response and happy new year! I bought you a couple coffees yesterday. You're doing wonderful work!
