### ISSUE TITLE
Attempting to Add M3U8 stream using Radio results in "Unable to retrieve info for:" "no such file or directory"

### ISSUE THREAD

**Issue by minideezel** [music-assistant/hass-music-assistant#1749]
### What version of Music Assistant has the issue?

2024.1.0b2

### The problem

I'm attempting to play a music stream that is generated using a siriusxm [python streaming server](https://github.com/PaulWebster/SiriusXM/tree/PaulWebster-cookies) I can access the stream on the network using vlc by going to: http://ip:8888/36.m3u8 (for channel 36)

I have attempted to add the stream to the Radio section by "Add item from URL" and inputting that URL. I can see in my SiriusXM log that it hits the url, but then Music Assistant generated the "Unable to retrieve info for" error with the, I'm assuming, chunk url of the music. 

I also tried creating a m3u playlist file with that above url in the in the body and including that in the filesystem /media dir. It shows up but says there are no playlist tracks.

I was hoping this would be a easy shortcut for getting SiriusXM as a source since that's my primary music source.

### How to reproduce

1. Setup streaming on a server using the siriusXM script linked above
2. Add m3u8 url to Music Assistant's Radio URL

### Relevant log output

```
2024-01-02 13:22:41.858 ERROR (MainThread) [music_assistant.webserver] [140173703066000] Error handling message: CommandMessage(message_id=17, command='music/item', args={'media_type': 'radio', 'item_id': 'http://10.0.2.186:8888/36.m3u8', 'provider_instance_id_or_domain': 'url'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/tags.py", line 398, in parse_tags
    raise InvalidDataError(error["string"])
music_assistant.common.models.errors.InvalidDataError: No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/webserver.py", line 372, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 331, in get_item
    return await self.mass.get_provider("url").parse_item(item_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/url/__init__.py", line 116, in parse_item
    item_id, url, media_info = await self._get_media_info(item_id_or_url, force_refresh)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/url/__init__.py", line 179, in _get_media_info
    media_info = await parse_tags(url)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/tags.py", line 409, in parse_tags
    raise InvalidDataError(f"Unable to retrieve info for {file_path}: {str(err)}") from err
music_assistant.common.models.errors.InvalidDataError: Unable to retrieve info for AAC_Data/altnation/HLS_altnation_256k_v3/altnation_256k_1_010251760754_00193379_v3.aac: No such file or directory
```

### What version of Home Assistant Core are your running

2023.12.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Alternative

**Comment by OzGav** [comment]
Amazingly today someone popped up on discord today saying they were writing a SiriusXM provider. Not sure how long that will take. From my quick skim of the discussion it seems SiriusXM has some robust authentication so that is possibly your problem. So you will have to be patient and see if this new provider gets off the ground.

**Comment by minideezel** [comment]
@OzGav That's fantastic news that someone is working on a SXM provider, this is a fantastic project and I'm definitely looking forward to it! 

However I don't think my issue has anything to do with authentication since the python program is doing all of the auth and providing the channels as generic, no-auth .m3u8 streams that play without any authentication in VLC. I will agree it's not a typical radio stream, but recommendations on what could be causing the issue would be appreciated.

Thanks!

**Comment by OzGav** [comment]
I wonder if it is because it is streaming in AAC? Can you change that to FLAC or MP3?

**Comment by deboy69** [comment]
@minideezel were you able to get this figured out? Running into a similar issue?

**Comment by minideezel** [comment]
@deboy69, nope. I haven't adopted Music Assistant because of this, but I also haven't spent much time trying to figure it out.
