### ISSUE TITLE
Snapcast not seems work

### ISSUE THREAD

**Issue by SiriosDev** [music-assistant/hass-music-assistant#1752]
### What version of Music Assistant has the issue?

 2.0.0b80 

### The problem

im not sure, but it says this error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/ffmpeg/asyncio/ffmpeg.py", line 197, in execute
    raise FFmpegError.create(message=tasks[2].result(), arguments=self.arguments)
ffmpeg.errors.FFmpegError: tcp://librespot: Invalid argument
```

### How to reproduce

connect snapcast server on 1705 port, as default, and start a song on a detected client

### What version of Home Assistant Core are your running

2023.12.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Clients should be connecting on port 1780?

**Comment by SiriosDev** [comment]
idk, i have tried with snapweb

**Comment by OzGav** [comment]
Yeah so your URL to access snapweb should be <Snapcast Server IP>:1780

**Comment by SiriosDev** [comment]
Yes, exactly

**Comment by OzGav** [comment]
Ok then why did you mention port 1705 in your issue report? Do you have other player providers working ok?

**Comment by SiriosDev** [comment]
> Ok then why did you mention port 1705 in your issue report? Do you have other player providers working ok?

well, music assistant connects to the snapcast server on that port

**Comment by SiriosDev** [comment]
my bad, I meant server not client

**Comment by OzGav** [comment]
Ok so MA sees the server ok. The client (browser via snapweb in your case) sees the server ok. But an error is thrown when trying to stream. Is that the summary?

**Comment by SiriosDev** [comment]
yep, and on client nothing is playing

**Comment by OzGav** [comment]
Do you an Android phone you can test with snapdroid? Do other player providers (not Snapcast) work ok?

**Comment by SiriosDev** [comment]
I'll try immediately

**Comment by SiriosDev** [comment]
nope

**Comment by SiriosDev** [comment]
maybe my config is wrong, I looked on this repo but I didn't quite understand which stream I should have enabled on the SnapServer to make sure I'm doing the right thing?

**Comment by OzGav** [comment]
Just use everything in the defaiult setting. The only thing you have to check is that the snapweb server is enabled - which again usually is by default

**Comment by SiriosDev** [comment]
to be safe I deleted the old conf file to have it regenerated and the only active streams are this:

```cfg
source = librespot://librespot?name=LibreSpot&bitrate=320&sampleformat=44100:16:2
source = pipe:////audio/snapcast_fifo?name=Mopidy
```

I also tried to install snapserver on another machine and the conf contains only the stream:

```cfg
source = pipe:///tmp/snapfifo?name=default
```

with both Sservers MA sees the players but in the first of the two, you can't hear anything once you play something while in the second one when i try to play a chrome pop up appears on MA saying `librespot?`

**Comment by OzGav** [comment]
What version of snapserver are you installing?

**Comment by SiriosDev** [comment]
0.27.0 (the latest)

**Comment by OzGav** [comment]
OK you also have a doc_root entry in your config to enable snapweb

**Comment by SiriosDev** [comment]
yep, but i remember you also snapdroid not work

**Comment by SiriosDev** [comment]
i can only hear a "not silence sound" when a player is enabled

**Comment by OzGav** [comment]
Please provide details of your network setup and HA, MA and snapserver installations. It sounds like you have some setup problem as no one else is reporting this problem.

**Comment by SiriosDev** [comment]
I'm on Home Assistant OS, BUT it's installed via addon, and snapserver is on a container of the same machine (with access via portainer) opened port: `1704`, `1705`, `1780`, consequently everything is on `127.0.0.1 ` except my devices and the second test machine which is in mine Classic LAN `192.168.x.x/24`

If you want more info just tell me

**Comment by OzGav** [comment]
OK complicated setups are difficult for us to help with. I'll tag @SantiagoSotoC and see if he has time to help you with this.

**Comment by SiriosDev** [comment]
so, to skim some of the possible problems, the config:
> ```cfg
> source = librespot://librespot?name=LibreSpot&bitrate=320&sampleformat=44100:16:2
> ```

is correct

**Comment by snootched** [comment]
In the snapcast documentation the source is `spotify:///` and not `librespot://`
`source = spotify:///librespot?name=Spotify[&username=<my username>&password=<my password>][&devicename=Snapcast][&bitrate=320]`

These are source examples that work for me:

```
[stream]

source = spotify:///librespot?name=<some name>&username=<spotify username>&password=<spotify password>&devicename=<some name>&bitrate=320&volume=100&killall=false&params=--device-type%20avr
source = airplay:///shairport-sync?name=<some name>&devicename=<some name>&port=5000
source = pipe:///tmp/snapfifo?name=default

#auto-select active source based on priority - 1. spotify 2. airplay 3. anything on the pipe like mpd
source = meta:///<my spotify name>/<my airplay name>/default?name=Auto-Select
```

**Comment by SiriosDev** [comment]
spotify? why?

maybe it even makes sense but what should I put as user and password since but not either of these two

**Comment by snootched** [comment]
> spotify? why?
> 
> maybe it even makes sense but what should I put as user and password since but not either of these two

I thought you were asking for help on your snapserver.conf source entry for librespot, so that's what I was referring to. 
 Consequently this has nothing to do with MusicAssistant.


For snapcast and MA, you don't need those sources in your snapserver.conf at all.
Playing music from MA will dynamically create a source stream for your client(s) when you send music to the player. 

![image](https://github.com/music-assistant/hass-music-assistant/assets/11273374/4be3ac6f-c968-4098-8eea-bc23d1893653)

If you then link another snapcast client (in MA..) it will group them on the snapcast server and play the dynamic source to the group. 

![image](https://github.com/music-assistant/hass-music-assistant/assets/11273374/abd34509-7100-44b1-8e86-630a6cba0002)

![image](https://github.com/music-assistant/hass-music-assistant/assets/11273374/8c033bc0-1a38-4888-8600-7355710aa0ba)


If MA can communicate to your snapserver on tcp/1705, and it can pull in your clients as players, this should be all that you need.  Your players will connect to the snapcast server on tcp/1704.

**Comment by SiriosDev** [comment]
> For snapcast and MA, you don't need those sources in your snapserver.conf at all.


apparently it is needed instead
![image](https://github.com/music-assistant/hass-music-assistant/assets/26876994/45ada607-fba2-4e14-89a2-e3a10926f630)
in eng: `<my domain>.it says:`

**Comment by SantiagoSotoC** [comment]
We have a problem with beta 79 and 80, I'm trying to solve it, I have the problem more or less solved, but I'm working on other bugs, try beta 78.

**Comment by SiriosDev** [comment]
ah ok, no prob

**Comment by SantiagoSotoC** [comment]
Let me know, if in beta 78 it works or gives you error too.

**Comment by SiriosDev** [comment]
yes I can try, but how do to downgrade an addon?

**Comment by SantiagoSotoC** [comment]
Do you have a Snapshot ? or is it the first time you use MA ?

**Comment by SiriosDev** [comment]
ah yes

**Comment by SiriosDev** [comment]
> Do you have a Snapshot ? or is it the first time you use MA ?  

Ok, 78 actually work, with 3/4s of latency, but nothing that make it unusable

**Comment by SantiagoSotoC** [comment]
> > Do you have a Snapshot ? or is it the first time you use MA ?  
> 
> Ok, 78 actually work, with 3/4s (~10s with flow mode enabled) of latency, but nothing that make it unusable 

Ok the other streams you have work fine ? MA ignores them ? Only the case of the named pipes is contemplated, but the rest I did not test, the idea is that it works first with the default configuration.
By latency do you mean the time it takes to start playing ?

**Comment by OzGav** [comment]
Please check if this has been fixed in beta81

**Comment by SiriosDev** [comment]
I tried to try, but in 81 yt music doesn't work at all it only loads the previews but not the music

**Comment by OzGav** [comment]
The YTM code wasn’t changed so I am going to guess it has just become apparent due to the server restart. While that gets looked at you could use a radio provider?

**Comment by SiriosDev** [comment]
I'll try

**Comment by SiriosDev** [comment]
Nope, not work, at the end i've tried with local

**Comment by OzGav** [comment]
Ok we will provide more updates when they are available.

**Comment by SantiagoSotoC** [comment]
Is snapcast working with local ?

**Comment by SiriosDev** [comment]
> Is snapcast working with local ? 

You mean local file? Or client in lan

**Comment by SantiagoSotoC** [comment]
Local file

**Comment by SiriosDev** [comment]
> Local file

no stream from a local file with MA on Snapcast not work

**Comment by SantiagoSotoC** [comment]
In the last beta, that is rare, we have other problems but not that it does not play, if you want I can help you to debug it in discord

**Comment by OzGav** [comment]
> I tried to try, but in 81 yt music doesn't work at al

YTM should be fixed in beta 82

**Comment by SiriosDev** [comment]
Yep ytm is back

**Comment by SiriosDev** [comment]
> Remind me how you run snapcast, do you have a firewall ?

No firewall in a container, managed with portainer on HA OS

**Comment by SantiagoSotoC** [comment]
Container in host mode ?

**Comment by SiriosDev** [comment]
nope looks like a network that automatically created itself with bridge name.

I try to pass it on host?

**Comment by SiriosDev** [comment]
> > nope looks like a network that automatically created itself with bridge name.
> > I try to pass it on host?
> 
> Yes, the ports where MA sends audio to snapcast are dynamic, and docker is not one of the supported snapcast configurations.

yes now work, like the ver 78 of MA

**Comment by SantiagoSotoC** [comment]
I'm glad, I already have the solution to the current problem with the order of the songs, Marcel is going to make some changes so that the flow mode is the default, which is what makes the most sense in snapcast.
