### ISSUE TITLE
Voice Command - When using Voice Command, existing queued music continues to play unless queue is cleared

### ISSUE THREAD

**Issue by nikito** [music-assistant/hass-music-assistant#1764]
### What version of Music Assistant has the issue?

2024.1.0b2

### The problem

When we use a voice command such as "Play music by <artist>", if music is already playing, or music was playing and paused/stopped but the queue not cleared, then the old music resumes playing instead of the requested music, and the request music is instead queued

### How to reproduce

Ask for a particular music track or artist, pause player, then ask for a different song or artist.

### What version of Home Assistant Core are your running

2024.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
This is currently by design but we are discussing it. You should find however that the new.y requested music is added to the start of the queue?

**Comment by nikito** [comment]
Just tried again and from what I see it seems to depend on the artist. I cleared queue and asked for first artist. Then while playing I asked to play a different artist and that played immediately. However upon asking for a third artist it played a different song by the artist that was already playing. Upon inspecting the queue, it looks like the songs by all three artists are all shuffled together.

**Comment by nikito** [comment]
Aha, I found the culprit! Turns out shuffle was set on the player, even though I had stopped and powered it off (guessing it persists?). So it was adding the new items to the top, but then the shuffle was mixing things up before resuming playback.

**Comment by OzGav** [comment]
Yes that is correct
