### ISSUE TITLE
Frontend: Add album to playlist

### ISSUE THREAD

**Issue by OzGav** [music-assistant/hass-music-assistant#1768]
### Discussed in https://github.com/orgs/music-assistant/discussions/1767

<div type='discussions-op-text'>

<sup>Originally posted by **maste9** January  6, 2024</sup>
When I yet wanted to summarize two albums into one playlist I had to notice that there's no way to that except of choosing one track at a time and add it to playlist.

 * It would be nice, if there was an __Add to playlist__ button in the play button's context menu of an album.

[rest of discussion snipped]: </div>

**Comment by OzGav** [comment]
@jozefKruszynski Just tried this but it didn't work properly. I have my test playlist which had one track in it. I then added an album and it became this:

```
filesystem_smb://track/The Beatles/1/Disc 1/02. From Me To You - Beatles.flac
filesystem_smb://track/Oasis/(What's the Story) Morning Glory/03. Wonderwall - Oasis.flac
filesystem_smb://track/Oasis/(What's the Story) Morning Glory/10. Morning Glory - Oasis.flac
filesystem_smb://track/Oasis/(What's the Story) Morning Glory/09. She's Electric - Oasis.flacOasis.flac
filesystem_smb://track/Oasis/(What's the Story) Morning Glory/11. [Untitled Track] - Oasis.flac
filesystem_smb://track/Oasis/(What's the Story) Morning Glory/12. Champagne Supernova - Oasis.flac
filesystem_smb://track/Oasis/(What's the Story) Morning Glory/06. [Untitled Track] - Oasis.flac
```

Tried to create a new playlist with a different album and you can see there is corruption in the file:

```
filesystem_smb://track/Simon & Garfunkel/20 Greatest Hits/05. The 59th Street Bridge Song - Simon & Garfunkel.flacflac
filesystem_smb://track/Simon & Garfunkel/20 Greatest Hits/07. At The Zoo - Simon & Garfunkel.flac
filesystem_smb://track/Simon & Garfunkel/20 Greatest Hits/20. Song For The Asking - Simon & Garfunkel.flac- Simon & Garfunkel.flac
filesystem_smb://track/Simon & Garfunkel/20 Greatest Hits/10. We've Got A Groovy Thing Goin' - Simon & Garfunkel.flac 
```

**Comment by jozefKruszynski** [comment]
File provider still has issues with multiple tracks being added to a playlist right. I'll try to look at that one and this today.

**Comment by OzGav** [comment]
@jozefKruszynski any progress on this one?

**Comment by marcelveldt** [comment]
this one should be fixed - can you confirm @OzGav ?

**Comment by OzGav** [comment]
Yes. There are some other issues with what playlists are available to be added to but the option is there in the menu and it works when a playlist is selected.
