### ISSUE TITLE
One track keeps playing on repeat

### ISSUE THREAD

**Issue by xteaun** [music-assistant/hass-music-assistant#1772]
### What version of Music Assistant has the issue?

2024.1.0b2

### The problem

I try to play a whole album and the very first track will keep playing on repeat even though repeat is turned off. I can manually skip to the next track. Then that track will endlessly play on repeat.

### How to reproduce

Start playback of an album on Music Assistant

### What version of Home Assistant Core are your running

2024.1.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
What music provider and what player provider are you using?

**Comment by weakspot** [comment]
Hi, 

pitching in as I have this same problem as well and hoping my data helps to solve the issue.

Just today installed Music Assistant and just testing it out by playing one single .mp3 file from local folder on HA: This file keeps on playing endlessly until I go to current playlist (bottom bar), options (three dots top right) and "Clear all items from queue". Tested the same with Spotify random album, same thing. First song keeps on repeating. I too can skip the current song, after that the next song keeps on playing repeatedly.

It does the same by just calling the service, like this: Same way to stop - go to current playlist and clear queue.

```
service: mass.play_media
target:
  entity_id: media_player.kaiutin_ruokasali_2
data:
  media_id: https://HA_IP:8123/local/audio/doorbell-1.mp3
```

Home Assistant Core: 2024.1.2
Music Assistant: 2023.12.0 (from HACS page)
Music Assistant Addon page says: Current version: 2.0.0b81

Player: UPnP/DLNA Player (HEOS 1 with latest firmware  3.1.232)

**Comment by xteaun** [comment]
> What music provider and what player provider are you using?

Hi there! Thanks for your reply. I am using Spotify and SONOS.

**Comment by OzGav** [comment]
There is work being done on the queuing. In the meantime try queue flow mode in the player settings.

**Comment by xteaun** [comment]
Flow mode solves the issue for now. BUT with flow mode enabled the player shows the wrong song title. The last one that was played instead of the current one.

**Comment by OzGav** [comment]
This should be fixed in beta 83 please advise if not

**Comment by bzerangue** [comment]
I am seeing the same thing with the latest version, while using Spotify and YouTube Music
Home Assistant Core: 2024.5.3
Music Assistant from HACS: 2024.5.1
Music Assistant Add-On: 2.0.2 Stable
Home Assistant Player: VLC Player Add-On (0.3.0)

Enabling Queue Flow Mode fixes the problem.
