### ISSUE TITLE
Autoplay plays new Song, but shows another

### ISSUE THREAD

**Issue by GregorEstebanCardosoSchiller** [music-assistant/hass-music-assistant#1782]
### What version of Music Assistant has the issue?

2.0.0b81

### The problem

A song plays and when it ends the next one plays. For example: 

The Player shows "Tool - Parabola" but I here "Metallica - For whom the bell tolls". 

### How to reproduce

Enable Queue Flow, Play on DLNA Player (Pioneer VSX-923)
Same bug on Chromecast (4k).

### Relevant log output

2024-01-11 15:51:51.795 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue AVR-DLNA
2024-01-11 15:53:20.665 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue AVR-DLNA
2024-01-11 15:53:57.112 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue AVR-DLNA

### Additional information

In general the synchronization of the dlna and the server seems to be of. Sometimes the Song shows the correct position after a while, but it hops a lot.

Sometimes it stops. Just now had a one time log when it stopped in the middle of a song:

2024-01-11 16:01:32.230 WARNING (MainThread) [async_upnp_client.profiles.dlna] Only InstanceID 0 is supported

### What version of Home Assistant Core are your running

2023.12.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Try with queue flow mode off on both the DLNA player and chromecast

**Comment by GregorEstebanCardosoSchiller** [comment]
> Try with queue flow mode off on both the DLNA player and chromecast

Then it stops after one song. Thats why I tried it with it according to the threads I read here.

**Comment by OzGav** [comment]
Yeah ok I think you might be caught up in the queuing bug which is being worked on. Wait for an update to see if this is fixed.

**Comment by xteaun** [comment]
Yeah, same problem here. With flow mode enabled the wrong song title is shown. Not the current, but the one played before. And without flow mode, one track gets repeated endlessly with Spotify and Sonos.

**Comment by marcelveldt** [comment]
Where is this wrong info shown? In the UI of Music Assistant ?

**Comment by GregorEstebanCardosoSchiller** [comment]
> Where is this wrong info shown? In the UI of Music Assistant ?

Yes.

**Comment by xteaun** [comment]
Also the entity shows the wrong song info.

**Comment by OzGav** [comment]
This should be fixed in beta 83 please advise if not

**Comment by GregorEstebanCardosoSchiller** [comment]
Cross Fade (Queure shows) the same problem. Without Crossfade it seems to works. (Just tested 2 songs with skip to the end).

**Comment by GregorEstebanCardosoSchiller** [comment]
But it seems it has to do with the bug:

![image](https://github.com/music-assistant/hass-music-assistant/assets/65222903/3e919695-c973-4f88-992b-8dc776898467)

2024-01-21 11:02:07.178 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback Players._handle_event(MassEvent(eve...ra_data': {}}))
Traceback (most recent call last):
  File "<string>", line 37, in __mashumaro_from_dict__
  File "<string>", line 37, in <listcomp>
  File "/usr/local/lib/python3.11/enum.py", line 712, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 1135, in __new__
    raise ve_exc
ValueError: 'enqueue_next' is not a valid PlayerFeature

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/client/players.py", line 302, in _handle_event
    self._players[event.object_id] = Player.from_dict(event.data)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 39, in __mashumaro_from_dict__
mashumaro.exceptions.InvalidFieldValue: Field "supported_features" of type tuple[PlayerFeature, ...] in Player has invalid value ['power', 'volume_mute', 'volume_set', 'enqueue_next', 'pause']

**Comment by OzGav** [comment]
Have you updated the integration as well?

**Comment by GregorEstebanCardosoSchiller** [comment]
If its easy its no fun :-D Now working. Testing the queues and skips with integrated Music Assistant player.

**Comment by OzGav** [comment]
Open a new issue with the details thanks.

**Comment by GregorEstebanCardosoSchiller** [comment]
It is exactly the same behaviour, as described in opening post. Tested on chromecast. But it is working now without Crossfade. When crossfade, then same behavior!

**Comment by OzGav** [comment]
Ok crossfade is flow mode under the hood so it seems it is a problem with flow mode. Try your DLNA player without flow mode as well please

**Comment by GregorEstebanCardosoSchiller** [comment]
DLNA did not work properly at all (but I think that is a pioneer problem). It had hickups a lot. Now for example it does not work anyhow :-/ Sorry, cannot properly test this one. 

With the crossfade it seems, that there are 2 playlists parallel, like 2 different streams.

**Comment by OzGav** [comment]
> With the crossfade it seems, that there are 2 playlists parallel, like 2 different streams.

What do you mean by this?

**Comment by GregorEstebanCardosoSchiller** [comment]
I know the "phenomenon" from Spotify on Chromecast. The chromecast is not a streaming device. It is a self sufficient cpu which gets a command to use its own app client to play a song. So when I look onto my phone after a while, it might be, that my phone shuffled through a playlist differently, as the chromecast. 

This means with the phone I hit "play" and then the chromcast is self sufficient. 

I do not know, how your code "speaks" to the player, but hence it was the same with the dlna, I do not think, that it is the exact same problem. Although it seems to be working without "flow mode".

Another thought to parallel streams comes to mind, when you switch between tracks and playlists. When you start a playlist, then switch to a track...it happens that the stream changes after the track directly back into the formerly stopped playlist song. If I knew more about the code mechanics, I could assist you more precisely. I do not know if you have to stop a stream or "kill" a stream, when changing tracks or playlists. But it seems as if there are more than one queue.

**Comment by OzGav** [comment]
You are correct that is how an app and. Chromecast device normally works but it is not how MA works as it is building its own streams.
MA has 3 ways of enqueuing tracks to players:

**BASIC/FALLBACK**
send tracks from the queue one by one. We just watch the player and if we see that it stopped playing at the end of a track, we tell it to play the next. This is the most basic form of enqueuing and completely handled by the MA queue controller and thus works with ALL players. This will NOT support gapless or crossfade. This setting is the default if the player has no native enqueue support or flow mode enabled. By default DLNA players use this option as well as the upcoming Home Assistant based players. Full metadata is sent to the player of what is playing.

**NATIVE ENQUEUE SUPPORT**
The player has native enqueue support so we tell it what the next track will be right before the current one ends. This is a special feature that not all players support. Its supported (and by default enabled) for Slimproto, Google Cast and Sonos players. Some DLNA players support it but others don't so we offer a player setting to enable it so a user can try himself if the player accepts it. benefit is full support gapless playback and in case of Slimproto and Sonos also crossfade. Also full metadata will be sent to the player what is currently playing.

**FLOW MODE**
As an alternative to native enqueuing we can also send one stream of audio to the player and let Music Assistant stitch the songs together (with gapless or crossfade). This mode is used by default for Airplay and snapcast and will be used by DLNA and Cast if crossfade gets enabled. Downside of this approach is that Google cast (and most DLNA players) looses metadata display (on the speaker itself). Some DLNA players support "icy metadata" which is what we send to inform what is playing.

**Comment by OzGav** [comment]
Can you confirm that when your issue occurs if the track position counter continues past the end length of the song

<img width="802" alt="image" src="https://github.com/music-assistant/hass-music-assistant/assets/19848947/dc4ed3c2-68fd-4c10-b53f-8f4a5288eb0b">

**Comment by OzGav** [comment]
We will close this soon due to no followup

**Comment by ogoor93** [comment]
I encountered similar issues when playing music from a local NAS or Tidal via UPnP/SlimProto on a Raspberry Pi renderer. Queue flow mode helps, but the music is always upsampled (44.1kHz files show as 192kHz on the DAC). Without queue flow, the DAC displays the correct bitrate, but the synchronization between the currently playing song and the track shown on the player breaks
