### ISSUE TITLE
v1.1.3: Playlist continues when streaming radio

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#179]
Another very stange glitch:
- Play a Spotify Playlist (to the CC group)
- in MA select a tunein radio station 
- the radio station stream starts 

But then intermittently the media displayed in the players still is the Playlist, and other times the radio banner occurs.

What seems reproducible is leaving MA and then reopen:
The playlist media is displayed in stead of the radio banner:
![image](https://user-images.githubusercontent.com/4363599/168661111-8efbf529-f144-474b-8b23-be4b56374a03.jpeg)

Even the progress bar suggests the Spotify playlist is running in the player, while the radio station station is still streaming to the CC's.
This is how the mass players look like (the correct content):
![image](https://user-images.githubusercontent.com/4363599/168661206-645b861f-8229-4c5c-80c4-f5bcd88cf92b.jpeg)

**Comment by erkr** [comment]
After a while the mass players are not all correct anymore (but still all playing the radio):
![image](https://user-images.githubusercontent.com/4363599/168663759-c1dd2c14-d0f4-4e29-baed-5c2e55cd8961.jpeg)

**Comment by erkr** [comment]
Yes, only the meta data displayed is wrong, the CC's are streaming the right content (radio 040)

**Comment by marcelveldt** [comment]
fixed in 1.1.4

**Comment by erkr** [comment]
Yes definitely fixed 👍
