### ISSUE TITLE
YT Music goes out of sync with playback information

### ISSUE THREAD

**Issue by Gvolten** [music-assistant/hass-music-assistant#1793]
### What version of Music Assistant has the issue?

2024.1.0b2

### The problem

When I play a playlist from YouTube Music on one of my Google Home speakers, everything seems normal from the start. The first few tracks play normally and correct information is displayed in Music Assistant. But then, after a few tracks pass and I look back to the UI, there is a completely different track displayed compared to the one actually being played. Also, the queue does not match with what song plays next. The Music Assistant entity in Home Assistant also reports incorrect information.

### How to reproduce

1. Enable queue flow mode on a Google Home (Chromecast) speaker.
2. Enable crossfade.
3. Set the speaker to shuffle and repeat.
4. Play a YT Music playlist using the `mass.play_media` service.
5. Observe the song information after a few songs pass.

### What version of Home Assistant Core are your running

2024.1.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by Gvolten** [comment]
Oh, now after a quick look through the issues not related to YT Music (I was searching for that specifically), I found this. It seems to be the same problem. https://github.com/music-assistant/hass-music-assistant/issues/1782

**Comment by OzGav** [comment]
Follow that issue then. Thanks.
