### ISSUE TITLE
how to clean recently and artists when i remove the smb line

### ISSUE THREAD

**Issue by 810517583** [music-assistant/hass-music-assistant#1794]
### What version of Music Assistant has the issue?

2024.1.3

### The problem

After removing the directory, the original historical playback records are still present and the cleaning button cannot be found

### How to reproduce

removing the directory,

### What version of Home Assistant Core are your running

2024.1.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
What do you mean by “historical playback records”?

**Comment by OzGav** [comment]
We need some followup on this or we will have to close it

**Comment by 810517583** [comment]
播放列表，就是我删除了挂载目录，播放列表还在，歌曲只能一个删除，不可能全部删除
——
The playlist ， I means when I deleted the mounting directory but the playlist is still there. that can only delete one song, but not all of them.

**Comment by OzGav** [comment]
If you remove a music provider then the database will be cleaned automatically UNLESS you restart MA or the host before it is completed. If the cleanup has been interrupted then either manually remove all the items from the library or uninstall and reinstall Music Assistant.

**Comment by OzGav** [comment]
Does this answer your question? This issue will be closed soon if there is no further followup
