### ISSUE TITLE
Audio not playing in Samsung Soundbar Q935

### ISSUE THREAD

**Issue by samuelspagl** [music-assistant/hass-music-assistant#1796]
### What version of Music Assistant has the issue?

2.0.0 BETA 82

### The problem

Currently when trying to play a song from Spotify (provider) on the soundbar (via airplay) no sound can be heard. 
Selecting a HomePod Mini in the same network works great and is playing the song as expected.

### How to reproduce

Having a Samsung Q935 and selecting it as speaker.

### What version of Home Assistant Core are your running

2024.1.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
It’s probably this https://github.com/orgs/music-assistant/discussions/1165#discussioncomment-6636260

**Comment by OzGav** [comment]
Closing as this is likely a Samsung specific problem with Airplay. If you have any additional info because you think this isn’t right then let us know.

**Comment by vmonkey** [comment]
@OzGav this has not fixed the issue on my Samsung hw s61b soundbar, unfortunately. It would be so great if this gets fixed but I understand it is really difficult to debug

**Comment by OzGav** [comment]
Yeah we are not hopeful as this is a Samsung specific problem. Maybe if Marcel is donated a soundbar he could look at it but not possible at the moment. Sorry.
