### ISSUE TITLE
Album art not shown on Supervised installation

### ISSUE THREAD

**Issue by Bram-diederik** [music-assistant/hass-music-assistant#1800]
### What version of Music Assistant has the issue?

2023.12

### The problem

The album art of a music assistant media player is not shown when using Supervised installation.  
the art src resolves to http://172.30.32.1:8095/imageproxy?path=[mymusic]&provider=filesystem_smb 
which is not resolvable outside home assistant. 

It works prefect on my main libvirt OS installation.

the Supervised is a PI4 with debian as main libvirt OS for HA. Its a small system for a girlfriend of mine. 

### How to reproduce

on a Supervised system.  go to a music assistant media player in your lovelace (or open it using the settings integration page)  browse trough media. select albums. 
art not generated. 
Inspect a img src it begins with  http docker ip

### What version of Home Assistant Core are your running

2024.1.3

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Raspberry Pi

**Comment by marcelveldt** [comment]
hmm strange, this should have gone through the image proxy of HA itself to resolve. where did you see this path ?

**Comment by Bram-diederik** [comment]
When i add a mass media player to locelace and browse trough mass music

**Comment by marcelveldt** [comment]
> When i add a mass media player to locelace and browse trough mass music

please be more specific. Add screenshots to clarify.

Do you mean the media browser from HA itself ? Or the image shown on the media player card ?

**Comment by Bram-diederik** [comment]
last comment updated.

**Comment by OzGav** [comment]
Please add a screenshot to clarify

**Comment by OzGav** [comment]
We will close this soon due to no followup
