### ISSUE TITLE
Container does not start successfully

### ISSUE THREAD

**Issue by SteveDinn** [music-assistant/hass-music-assistant#1804]
### What version of Music Assistant has the issue?

I pulled the latest version of `ghcr.io/music-assistant/server` as of the morning of Jan 20, 2024.

### The problem

I assume that I'm doing something wrong here, as several other people are using Music Assistant. But, perhaps there are not many using it in a separate container? Anyway, container output is in the `logs` section down below, and my docker-compose configuration is included as well.

Can anyone help me figure out what I'm doing wrong?

If it matters, I'm running HA in a docker container with MariaDB on Debian 11 (bullseye).

### How to reproduce

I just attempted to bring up the container using a `docker-compose.yml` file, configuration below.

### Relevant log output

**container output**
```
$ docker-compose up -d music-assistant && docker-compose logs -f music-assistant
homeassistant_music-assistant_1 is up-to-date
Attaching to homeassistant_music-assistant_1
music-assistant_1  | 2024-01-20 13:12:17.791 ERROR (MainThread) [asyncio] Task exception was never retrieved
music-assistant_1  | future: <Task finished name='Task-1' coro=<run.<locals>.new_coro() done, defined at /usr/local/lib/python3.11/site-packages/aiorun.py:209> exception=OSError(105, 'No buffer space available')>
music-assistant_1  | Traceback (most recent call last):
music-assistant_1  |   File "/usr/local/lib/python3.11/site-packages/aiorun.py", line 219, in new_coro
music-assistant_1  |     await coro
music-assistant_1  |   File "/usr/local/lib/python3.11/site-packages/music_assistant/__main__.py", line 174, in start_mass
music-assistant_1  |     await mass.start()
music-assistant_1  |   File "/usr/local/lib/python3.11/site-packages/music_assistant/server/server.py", line 105, in start
music-assistant_1  |     self.zeroconf = Zeroconf(interfaces=InterfaceChoice.All)
music-assistant_1  |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
music-assistant_1  |   File "/usr/local/lib/python3.11/site-packages/zeroconf/_core.py", line 176, in __init__
music-assistant_1  |     listen_socket, respond_sockets = create_sockets(interfaces, unicast, ip_version, apple_p2p=apple_p2p)
music-assistant_1  |                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
music-assistant_1  |   File "/usr/local/lib/python3.11/site-packages/zeroconf/_utils/net.py", line 373, in create_sockets
music-assistant_1  |     if add_multicast_member(cast(socket.socket, listen_socket), i):
music-assistant_1  |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
music-assistant_1  |   File "/usr/local/lib/python3.11/site-packages/zeroconf/_utils/net.py", line 288, in add_multicast_member
music-assistant_1  |     listen_socket.setsockopt(socket.IPPROTO_IP, socket.IP_ADD_MEMBERSHIP, _value)
music-assistant_1  | OSError: [Errno 105] No buffer space available
```

### Additional information

Note that I have left out the `privileged` flag because I do not require SMB share access. I'm planning to use my existing Navidrome instance via the new subsonic server integration. 

**docker-compose.yml section**
```yaml
  ## Music Assistant
  music-assistant:
    image: ghcr.io/music-assistant/server
    restart: "no"
    network_mode: host
    volumes:
      - ./music-assistant:/data
```

### What version of Home Assistant Core are your running

2024.1.3

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
See if any of this helps https://github.com/music-assistant/hass-music-assistant/issues/1172

**Comment by SteveDinn** [comment]
That did it. Thanks.

For completeness, I added the following lines to my `/etc/sysctl.conf` file:
```
# For Music Assistant
net.ipv4.igmp_max_memberships = 50
net.ipv4.igmp_max_msf = 30
```

And then ran the following commands so I didn't have to reboot.
```
sysctl -w net.ipv4.igmp_max_memberships=50
sysctl -w net.ipv4.igmp_max_msf=30
```
