### ISSUE TITLE
Sonos beam doesn’t switch from hdmi input.

### ISSUE THREAD

**Issue by dragon2611** [music-assistant/hass-music-assistant#1808]
### What version of Music Assistant has the issue?

2024.1.0

### The problem

If the Sonos beam (gen1) was last used with the tv (so is on its hdmi input) when it is selected in music assistant no audio is heard but music assistant thinks it’s playing.

### How to reproduce

Use the beam for tv audio then try to play something from music assistant.

### Additional information

Plays fine if the Sonos is not on hdmi in

### What version of Home Assistant Core are your running

2024.1.5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Alternative

**Comment by OzGav** [comment]
Not sure if this is a MA problem. Has this ever worked?

**Comment by dragon2611** [comment]
I only discovered Music Assistant yesterday, so it's never worked for me in Music Assistant, However I just tested re-enabling the native Sonos integration in home assistant and playing something from the Hass mediaplayer (it was one of the radio stations) and that switched to the audio stream automatically.

I'm wondering if there's a command it's sending when the stream starts.

**Comment by marcelveldt** [comment]
Music Assistant is also based on soco, just like Home Assistant

**Comment by marcelveldt** [comment]
I think its unrelated. Did you even check to play music to that Beam when Tv was not active ?
I cant tell from your error report if the issue only occurs when tv playback is active.

Also, can you check the log of the music assistant server after attempting the playback ?

**Comment by dragon2611** [comment]
If the TV Input is active or was the last used device (I’m not sure if it does time out if left idle long enough) it doesn’t seem to work.

if however the last thing played on the beam was a stream (usually Spotify) then music assistant works.

If using the official Sonos controller you get asked if you want to switch away from the TV Input if you try to use something else, Spotify connect / home assistant will just auto switch it

**Comment by marcelveldt** [comment]
I have been testing this using Line-In on a sonos device (as I dont have a soundbar to tets it with) and I think I have fixed it.
Please test the next beta of MA, beta 89 and let us know if its resolved.

**Comment by OzGav** [comment]
@dragon2611 we will close this soon
