### ISSUE TITLE
No audio coming from MASS media players, media controls do not work - Chromecast Audio/Nest Mini 2 audio

### ISSUE THREAD

**Issue by vhsdream** [music-assistant/hass-music-assistant#1809]
### What version of Music Assistant has the issue?

2024.1.0

### The problem

No sound comes out of any of my MASS-created media players. These were created by enabling the Chromecast provider in Music Assistant settings. They are autodiscovered just fine and I can tell MASS to play something on a speaker. The UI shows the music as playing, I hear the chromecast chime of something connecting to them, but there is no music. In the MASS UI I am also unable to change the volume or use any controls. In order to stop playing I need to select the overflow menu and 'turn off' the speaker.

**Editing to add:** There is no audio output via these media_players even when played through the default media browser.

### How to reproduce

 - Install MASS Beta from HACS
 - Install MASS Beta add-on, reboot
 - Add MASS Beta Integration, reboot
 - Add music library (Plex, YT Music)
 - Confirm new MASS media_players created
 - Try to play music on any of the media_players

### Relevant log output

2024-01-21 17:53:43.950 INFO (ThreadPoolExecutor-0_11) [pychromecast.controllers] Receiver:setting volume to 0.5
2024-01-21 17:53:45.511 INFO (ThreadPoolExecutor-0_12) [pychromecast] Quitting current app
2024-01-21 17:53:45.512 INFO (ThreadPoolExecutor-0_12) [pychromecast.controllers] Receiver:Stopping current app 'CC1AD845'
2024-01-21 17:58:13.966 INFO (ThreadPoolExecutor-0_0) [pychromecast.controllers] Receiver:Launching app CC1AD845
2024-01-21 17:58:47.465 INFO (ThreadPoolExecutor-0_17) [pychromecast.controllers] Receiver:setting volume to 0.8
2024-01-21 17:58:59.647 INFO (ThreadPoolExecutor-0_19) [pychromecast] Quitting current app
2024-01-21 17:58:59.647 INFO (ThreadPoolExecutor-0_19) [pychromecast.controllers] Receiver:Stopping current app 'CC1AD845'

### What version of Home Assistant Core are your running

2024.1.5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Alternative

**Comment by senderbell** [comment]
I am experiencing the same problem. The music does not play on either TuneIn or Spotify.

**Comment by OzGav** [comment]
@vhsdream did MA work before or are you a new user?

**Comment by senderbell** [comment]
In my case, the problem started today. Yesterday, I updated MA to the latest version, just like HA.

**Comment by OzGav** [comment]
@senderbell so this is different to your other problem? Can you explain what does work and what doesn’t work in terms of music provider and player combinations and if players are in groups. If they are in groups is anything different if you play to an individual speaker?

**Comment by senderbell** [comment]
Both problems are not related. Simply from today MA is not working exactly as the author of this issue described. I tried to restart everything possible but to no avail. When I get back from work, I will try to look more closely for the cause on my side.

**Comment by vhsdream** [comment]
> @vhsdream did MA work before or are you a new user?

I'm an on and off user. Updated to the newest version and it stopped working. So I completely cleaned HA of MASS, redownloaded it, re-added the integration, and found I still had the issue. Do you want one of us to provide debug logs?

**Comment by marcelveldt** [comment]
So if I read it correctly the audio is also not playing from Home Assistant ?

**Comment by vhsdream** [comment]
Correct. I tried using the default media browser, tried playing a local audio file, tried the Radio plugin, and got the same result when I used the MASS media_players. The regular Google Cast-created media_players still work.

The MASS media_players indicate they are playing but there is no sound, and the only control that works is the power button to turn them off.

**Comment by OzGav** [comment]
Ok are you talking about controlling via HA? If so, what happens if you try via the MA UI?

**Comment by Traxtar928** [comment]
I'm also experiencing this... All my player devices are Chromecast audio or nest hubs (Google speakers), and every speaker entity created by the MASS integration is currently unavailable, and the integration fails setup.

When "configure" is selected in the integration options, an IP address and port I do not recognize is displayed.

**Comment by vhsdream** [comment]
I am talking about via both - the MA UI and the default - the only control that works is powering the media_player off and on. No other controls work, and there is no sound.

**Comment by Traxtar928** [comment]
Indeed, the media player entities that are part of the Google Cast integration are working fine, and the same entities that are part of the Music Assistant integration are unavailable.

**Comment by OzGav** [comment]
Ok so you are now saying that the little hour glass icon is showing against all the players in the MA settings? If so, restart the addon and then go and look at the settings again and see if they are available for any period.

**Comment by Traxtar928** [comment]
I haven't changed what I'm saying from the start, so perhaps we're just not communicating well.

To reiterate, the music assistant integration is not communicating with the add-on. I can play music using the web interface, without issue.

The front end in home assistant is broken. All entities are showing unavailable, and the integration has failed setup. Restarting the add-on is not a solution.

**Comment by OzGav** [comment]
Have you updated the integration to the latest? If so, then trying removing the integration from HA settings then via HACS. Restart HA. Install the integration via HACS then via HA settings.

**Comment by OzGav** [comment]
> I haven't changed what I'm saying from the start, so perhaps we're just not communicating well.

In regards to this you said “I’m also experiencing this” in your first post and this issue was raised by someone that can’t play via HA or MA hence the confusion. Looking back I see you did say the MA UI works for you so in this case you should have opened a new issue as this one does not actually apply to you.

**Comment by Traxtar928** [comment]
Understood... Sorry to add to the confusion. I did a full power-cut reboot of Home Assistant and it does appear to have fixed my issues, after repeated restarts did not. Everything was updated in HACS.

A bit more involved than the typical "turn it off and turn it on again", but the saying worked as it usually does.

**Comment by OzGav** [comment]
As noted above can e everyone try a full HOST REBOOT and see if that fixes things.

**Comment by vhsdream** [comment]
I guess in my case you mean completely restarting the VM; HA is running in Proxmox and I'm not going to reboot the host for a Home Assistant/Music Assistant issue. After rebooting the VM from Proxmox (instead of through the Home Assistant UI), the problem remains - no music coming from the MA media_players; tried again both via MA UI and the HA default media browser. I can change the volume on the speaker via MA and HA, and I can hear the feedback of the volume being changed, but again, no music.

Tested on the most recent MA beta.

**Comment by OzGav** [comment]
Since you are running in a VM have you made any changes to the STREAMSERVER settings?

**Comment by OzGav** [comment]
@senderbell are you using HAOS or some sort of container install? And please confirm you are using Chromecast devices only

**Comment by OzGav** [comment]
BREAKING NEWS. Might have identified the cause. Can everyone check the advanced settings for each chromecast player and see if “Use Alternate Media App” is selected. If it is then turn it off.

**Comment by senderbell** [comment]
Now everything works fine. The only thing I did yesterday was to reload the integration and restart the add-on. Nothing else. It just started working. The switch “Use Alternate Media App” is off and it was off before.

**Comment by OzGav** [comment]
Might be the addon restart that did it for you same as Traxtar. Good news though. Will see if we can resolve it for the OP

**Comment by vhsdream** [comment]
> Since you are running in a VM have you made any changes to the STREAMSERVER settings?

I have not made any changes to any MA settings, everything is default. 'Use Alternate Media App' is not used for any of the Chromecast players.

I should add that the Chromecasts are on a different subnet than Home Assistant - I didn't think this was the issue since MA was able to discover the players just fine as I am using an mDNS repeater/UDP boradcast relay service on my firewall. I also have given HA a second NIC in the same subnet as the Chromecasts.

Streamserver settings:
![image](https://github.com/music-assistant/hass-music-assistant/assets/67816022/5bf73200-b9e7-4aae-890b-af9e3ad04f20)

When I am able to do further testing (too early in the morning right now) I think I will change the published IP to the one used by the second NIC and see if that improves the situation.

I know you don't typically support non-standard network configurations and I appreciate your help and patience so far. Will update when I can!

**Comment by vhsdream** [comment]
Solved. In my case it was the 'Published IP address' - I changed it to the IP that shares the subnet with the Chromecast devices. I have audio!

Thank you for your help!

**Comment by jodewee** [comment]
> “Use Alternate Media App”

where can i find that setting? is that in music assistant itself? of in the cast device?

**Comment by OzGav** [comment]
That was removed months ago
