### ISSUE TITLE
v1.1.4: Content of more albums listed under album, that shares the name with the artist

### ISSUE THREAD

**Issue by AvdWerfhorst** [music-assistant/hass-music-assistant#181]
I was looking into Led Zeppelin's debut album, as for some reason no image loads. What I did find, instead of just their first album, is a collection of all Led Zeppelin albums which I have. Same issue happens with Queen's first album.

![Multi album select](https://user-images.githubusercontent.com/35181252/168796200-55a929a0-8038-4a75-bc43-bbdc10da3e42.PNG)

**Comment by marcelveldt** [comment]
You mean that tracks from other albums by the same artist are displayed ?

**Comment by AvdWerfhorst** [comment]
That is exactly what I mean.

**Comment by AvdWerfhorst** [comment]
Maybe good to know, I only use the Filesystem Provider. I found that Metallica's album Metallica (also known as black album, but not tagged under that nickname), The Beatles album The Beatles (white album) have exactly the same behaviour when I open/select them. A lot of tracks from other albums.

**Comment by marcelveldt** [comment]
I found what's going on. Fix in next release

**Comment by AvdWerfhorst** [comment]
Awesome

**Comment by marcelveldt** [comment]
this should be fixed in version 1.1.5

**Comment by marcelveldt** [comment]
1.1.8 released. Can you check if the issue is resolved ?
