### ISSUE TITLE
Sonos/Spotify - Some songs play twice.

### ISSUE THREAD

**Issue by dragon2611** [music-assistant/hass-music-assistant#1820]
### What version of Music Assistant has the issue?

2024.1.0

### The problem

Some tracks in the queue get played twice even though they are listed once and repeat is off. - https://github.com/music-assistant/hass-music-assistant/issues/1554

Using Sonos speakers and mostly spotify (although I do also have youtube music enabled)

### How to reproduce

Start playing music from spotify, At the moment it's the "Discover Weekly" playlist but I don't believe it makes much difference what you play.

### What version of Home Assistant Core are your running

2024.1.5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by erkr** [comment]
I have the same. Randomly in the playlist it repeats a track until I press next.
Spotify, chromecast group play. Default queue options (No shuffle, no repeat)

**Comment by OzGav** [comment]
Can you check the played items in the queue. Do you see both tracks there?

**Comment by dragon2611** [comment]
No, what seems to happen is instead of moving onto the next track (which then causes the previously played one to disappear from the top of the queue) it just plays the existing one again.

I did notice just now when the track switched the new track started playing briefly before the queue updated in the UI

**Comment by OzGav** [comment]
Can you clarify what you meant in the last sentence?

**Comment by dragon2611** [comment]
I happened to be watching the UI at the end of the last song/track playing and noticed that it takes a few seconds after the next song/track has started playing before the UI shows it.  It's probably not relivant

**Comment by OzGav** [comment]
Yeah ok so I assume you mean when the track progress marker jumps back to the start. Do you see the track name change as well?

**Comment by dragon2611** [comment]
Yes when it's working properly the name changes, when a track repeats then it doesn't it just jumps back to the start without the track changing.  It seems the queue is correctly tracking what's playing but for some reason occasionally it doesn't advance to the next track.

**Comment by dragon2611** [comment]
I had debug on for the queuecontroller and streamserver.

`2024-01-24 14:11:37.259 DEBUG (MainThread) [music_assistant.streams] Start serving audio stream for QueueItem spotify://track/1JXr4CDmzUqvDJ0PG3Pepp to Office Sonos
2024-01-24 14:11:38.633 DEBUG (MainThread) [music_assistant.streams] Got HEAD request to /RINCON_949F3E00CD7801400/single/2af179c58345461f93cd801abe447f5d.flac from 192.168.5.86
headers: <CIMultiDictProxy('Connection': 'close', 'Host': '192.168.5.20:8096', 'User-Agent': 'Linux UPnP/1.0 Sonos/76.2-47270 (ZPS12)', 'X-Sonos-SWGen': '2', 'X-Sonos-Firmware': '76.2-47270', 'X-Sonos-Muse-Api': '1.37.1', 'X-Sonos-Id-Hash': 'hashremoved')>

[flac @ 0x55ba5a733700] unable to rewrite FLAC header.
2024-01-24 14:14:45.423 DEBUG (MainThread) [music_assistant.streams] Got GET request to /RINCON_949F3E00CD7801400/single/2af179c58345461f93cd801abe447f5d.flac from 192.168.5.86
headers: <CIMultiDictProxy('Connection': 'close', 'Host': '192.168.5.20:8096', 'Accept': '*/*', 'User-Agent': 'Linux UPnP/1.0 Sonos/76.2-47270 (ZPS12)', 'X-Sonos-SWGen': '2', 'X-Sonos-Firmware': '76.2-47270', 'X-Sonos-Muse-Api': '1.37.1', 'X-Sonos-Id-Hash': 'hashremoved')>

2024-01-24 14:14:45.565 DEBUG (MainThread) [music_assistant.streams] Start serving audio stream for QueueItem spotify://track/1JXr4CDmzUqvDJ0PG3Pepp to Office Sonos
2024-01-24 14:14:46.509 DEBUG (MainThread) [music_assistant.streams] Got HEAD request to /RINCON_949F3E00CD7801400/single/2af179c58345461f93cd801abe447f5d.flac from 192.168.5.86
headers: <CIMultiDictProxy('Connection': 'close', 'Host': '192.168.5.20:8096', 'User-Agent': 'Linux UPnP/1.0 Sonos/76.2-47270 (ZPS12)', 'X-Sonos-SWGen': '2', 'X-Sonos-Firmware': '76.2-47270', 'X-Sonos-Muse-Api': '1.37.1', 'X-Sonos-Id-Hash': 'hashremoved')>`

**Comment by vhsdream** [comment]
Rocking the most recent beta, this issue seems to have been resolved, for me at least.

Latest HA, latest MA beta, chromecast players, using my Plex library as well as Youtube Music.

**Comment by dragon2611** [comment]
Can you confirm which version? - I'm on 2024.1.0 with addon 2.0.0b85 and was still seeing the problem.

**Comment by vhsdream** [comment]
Yes that is the version I am on - bleeding edge version, on most recent HA as well. Did you restart HA after updating?

**Comment by dragon2611** [comment]
Yes I was already on 2024.1.0 anyway, but did get an update of the add-on from 2.0.0.b84 to 2.0.0.b85

**Comment by OzGav** [comment]
As suggested if you are on HAOS then try a full host reboot or restart the container if not. See if that makes any difference….

**Comment by dragon2611** [comment]
I'd already restarted the add-on container earlier, but I'll reboot the entire HassOS VM

**Comment by dragon2611** [comment]
It's still doing it.

**Comment by OzGav** [comment]
Thanks. We will get back to you.

**Comment by dragon2611** [comment]
If I remember next time I'll try playing from YouTube music instead of Spotify as it will be interesting to see if the problem occurs then.

**Comment by OzGav** [comment]
More people have reported YTM when they have reported similar issues so it will be interesting if it doesn't occur for you when using that.

**Comment by dragon2611** [comment]
It looks like it also happens on youtube music.

**Comment by dragon2611** [comment]
Requesting next track from the sonos controller (app) was also causing the current song to repeat

**Comment by OzGav** [comment]
This should be fixed in beta 86 please advise if not

**Comment by dragon2611** [comment]
I think this is fixed, I thought I had a repeat of the last track in the queue but as I just had spotify playing as "background music" it's also completely possible I just had 2 similar sounding tracks next to each other (Such as you sometimes get an alternate version of the same song)
