### ISSUE TITLE
Music Assistant does not support the opus file format

### ISSUE THREAD

**Issue by gomerust** [music-assistant/hass-music-assistant#1825]
### What version of Music Assistant has the issue?

2024.1.x

### The problem

opus files are not recognized by Music Assistant

### How to reproduce

when i put  opus files in the local media folder they are not shown. Other file formats are

### Additional information

the following Feature request  https://github.com/orgs/music-assistant/discussions/855 was asking for it too,

### What version of Home Assistant Core are your running

2024.1.5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Should be fixed in beta 86 when it is released. Report here after then if not and I will reopen.

**Comment by mwaterbu** [comment]
While Opus playback is working fine, I did notice a very small bug in that the format icon shown in now playing from the queue is for Ogg Vorbis, not Ogg Opus.
![image](https://github.com/user-attachments/assets/c9b1e50e-95d0-4250-9e56-ee19ab7e5267)

**Comment by mwaterbu** [comment]
It also appears that other metadata may not be read correctly. Most of the opus files I added to my library have the track title as "Cover" instead of the actual title.
If the same song was already in my library but under a different format, the title is correct, as it just matches up with the existing track.

**Comment by OzGav** [comment]
Open a new issue with all of the required information from the troubleshooting page
