### ISSUE TITLE
Audio files are stuck on endless repeat.

### ISSUE THREAD

**Issue by arretx** [music-assistant/hass-music-assistant#1827]
### What version of Music Assistant has the issue?

2.0.0b85

### The problem

Since the most recent update (as far as I can tell), any audio file that's being played that's found in the media folder or mapped media folder plays on repeat indefinitely.

Every 15 minutes NodeRED processes a flow that triggers one of a given number of audio files for a virtual grandfather clock. When one of those sounds is triggered, it is played through the Picore player, and if you watch the playhead in MA, it repeats but the playhead continues to increase in time.  I watched an 8 second long mp3 file repeat over and over again and the playhead showed a cumulative time of over 3 minutes before I had to pull the plug on the automation.

### How to reproduce

I can't figure out what's causing it.

### What version of Home Assistant Core are your running

2024.1.5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Are you saying that if you use a non-local track in your automation this doesn't happen?

**Comment by arretx** [comment]
By non-local, do you mean something from Spotify, for example?

**Comment by OzGav** [comment]
yes because your first sentence suggests that and I want to confirm

**Comment by OzGav** [comment]
This is getting looked with priority. FYI the repeat mode can be changed via the button to the right of the play button or via the menu top right when viewing the queue

**Comment by OzGav** [comment]
This should be fixed in beta 86 please advise if not
