### ISSUE TITLE
HA Restart stalls if MA playing

### ISSUE THREAD

**Issue by TheWebMachine** [music-assistant/hass-music-assistant#1828]
### What version of Music Assistant has the issue?

2.0.0b85

### The problem

If you are playing music with MA and attempt to restart HA, the restart process stalls, MA doesn't shutdown, and everything just hangs there until you stop music playback some other way (Android GHome Notification, in my case).

### How to reproduce

1. Stream music from MA to a speaker (Google Home Max, in my case)
2. Request HA to restart itself
3. See HA begin shutdown and stall while music continues to play
4. Leave like this as long as you'd like, then stop playback on the speaker some other way (HA interface is offline at this time)
5. As soon as you stop playback, HA shutdown completes and restarts immediately

### Additional information

Factors involved:
Google Home Max Speaker
YT Music Streaming
Crossfade enabled
Continued playing through 2 full songs before I manually stopped playback and HA restarted

### What version of Home Assistant Core are your running

2024.1.5

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
Interesting as playback is supposed to just continue....

**Comment by OzGav** [comment]
Please provide more details of your installation.

**Comment by TheWebMachine** [comment]
> Interesting as playback is supposed to just continue....

What do you mean? Isn't MA supposed to restart along with HA, since it is an Add-On?

> Please provide more details of your installation.

Can you be more specific?

**Comment by OzGav** [comment]
I don't know how you have installed your system. If you were running HAOS then HA and MA are installed in separate docker containers (as are all other addons) and therefore restarting HA (in its container) shouldn't affect MA. The connection between the two containers is the integration.

Hence why we would be interested in exactly how you have HA installed and how you have MA installed.

**Comment by TheWebMachine** [comment]
> I don't know how you have installed your system. If you were running HAOS then HA and MA are installed in separate docker containers (as are all other addons) and therefore restarting HA (in its container) shouldn't affect MA. The connection between the two containers is the integration.
> 
> Hence why we would be interested in exactly how you have HA installed and how you have MA installed.

Thank you for clarifying. It's HAOS running in OVA, MA was installed via HACS, which would imply it is containerized, as you mention. 

I am still testing. MA is playing YT Music on a speaker and I asked HA to restart. webGUI disconnects and my shutdown automation fired (flashes a lamp). This time, I let it go and waited...well over 5 minutes later, HA finally completed its restart. This is nearly 5x longer than restarting HA without MA running. 

I doubt this is a resource issue. MA container itself is only using 3-4% CPU and 15-18% RAM at most...it normally hovers around 0.5% CPU and 6% RAM outside of a sync interval. Resource usage on the VM doesn't spike above about 60% during an HA restart in either case. I have the VM rather oversized to maintain "snappy" response times for more complicated automations. So, I'm not sure what holds it up when MA is playing music.

I'll see if I can find anything noteworthy in HA's logs.

**Comment by OzGav** [comment]
Look in the supervisor logs. There may be something going on with the integration

**Comment by TheWebMachine** [comment]
I can't find anything even remotely related in Supervisor logs and replicating it hasn't panned out 100% (more like 70%), so I'm going to chalk it up as a fluke unless/until I have something more concrete.
