### ISSUE TITLE
Randomly plays last track on its own

### ISSUE THREAD

**Issue by Lezcarr** [music-assistant/hass-music-assistant#1837]
### What version of Music Assistant has the issue?

music_assistant_beta_2.0.0b85

### The problem

Randomly plays last track on its own, after google cast has taken place

### How to reproduce

try casting to google speaker and see if it plays the last track you played

### What version of Home Assistant Core are your running

music_assistant_beta_2.0.0b86

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
There is no where near enough info here to determine what the problem is.
