### ISSUE TITLE
Freezing webpage when add filesystem/remote music provider or try to use any "Advanced Settings"

### ISSUE THREAD

**Issue by pickonedev** [music-assistant/hass-music-assistant#1840]
### What version of Music Assistant has the issue?

2024.1.0

### The problem

When I try to add a FileSystem or Remote music provider, the webpage freezes, I tried on edge, firefox and chrome, all are asking me if I want to stop/exit page or wait to load. There is nothing to load, I can't use the page anymore, I just need to close the page and open another one.
The same problem happens when I press any of the "Advanced Settings" dropdown buttons
I waited 10 minutes, the page was still frozen.
Here I just pressed the "Advanced Settings" and this happened

![image](https://github.com/music-assistant/hass-music-assistant/assets/34201387/dda4e08e-0f6d-4323-b7c5-6394540a688f)

### How to reproduce

Just try to configure a FileSystem/Remote music provider or just press "Advanced Settings" on any of Music Assistant addon

Edit: BTW, when I had the FileSystem music provider already configured, none of the mp3s from that location could be played. This was the reason which made me delete the filesystem music provider and try adding it back again...  which fails

### What version of Home Assistant Core are your running

2024.1.5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by Xhelliom** [comment]
Just to report same issue; also when trying to add plex / tidal provider.

**Comment by OzGav** [comment]
Yes there is a problem with beta 87. Please revert to b86 or b85 if you can otherwise please be patient until the next beta.

**Comment by talmuth** [comment]
Same story with docker setup for almost every provider

**Comment by Mustreg** [comment]
All the recent versions of MASS are suffering from these problems (freezing webpage when add filesystem/remote music provider or try to use any "Advanced Settings") **including 2023.6.0b6** with the **latest version** of Home Assistant.

**Comment by OzGav** [comment]
Please try again with beta88

**Comment by canedje** [comment]
Last update dit fix the problem.
Thanks

**Comment by pickonedev** [comment]
@OzGav Yes, the new update solves all the freezing problems. Thank you!
Now, the only hope I have with this addon, is that maybe the fully kiosk sync could have a bit of improvment. It is not bad right now, it is almost good, like 93,6% good :-D

**Comment by pickonedev** [comment]
Yes, I thought about something like this. BTW, when the music is playing on multiple tablets throught Fully, if I move forward the music, it gets a better sync.

I meet a new bug, I think. If I play a song right now, I cannot change to other song. It remains on the same as first played, stuck on (currently playing). I do something worng or it is just a bug?

**Comment by OzGav** [comment]
If you mean with Fully please open a new issue
