### ISSUE TITLE
Enqueue "add" attribute no longer working

### ISSUE THREAD

**Issue by Mikerodocker** [music-assistant/hass-music-assistant#1842]
### What version of Music Assistant has the issue?

2.0.0b87

### The problem

After 2.0.0b87 update can not add to the queue. Replace still works.

### How to reproduce

The following works if you replace "add" with "replace" but the "add" attribute no longer works.

_service: mass.play_media
metadata: {}
data:
  media_id: library://album/436
  enqueue: add
target:
  device_id: 5f79c753a66689d68764db64ea6f0cc1_
  

### What version of Home Assistant Core are your running

2024.1.5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Please try again with beta88

**Comment by Mikerodocker** [comment]
Fixed.

Thanks!
