### ISSUE TITLE
Last.fm scrobbling w/Plex

### ISSUE THREAD

**Issue by TheMinecraftGuyGuru** [music-assistant/hass-music-assistant#1847]
### What version of Music Assistant has the issue?

2.0.0b86

### The problem

I use Last.FM scrobbling through the official Plex integration, and Music Assistant is authenticated to the same account on Plex, but for some reason scrobbling doesn’t happen when played through MA, but it works fine with official Plex apps. Does MA stream in a specific way to prevent Plex from knowing?

### How to reproduce

Authenticate Plex with Last.FM, and authenticate MA with Plex. Play any song from Plex through MA, and it won’t scrobble to Last.FM.

### What version of Home Assistant Core are your running

2024.1.5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Alternative

**Comment by OzGav** [comment]
Plex is not currently maintained. This may take some time to get looked at.

**Comment by marcelveldt** [comment]
will be fixed in the next beta (b144)

**Comment by instantdreams** [comment]
I think my issue [#3757](https://github.com/music-assistant/support/issues/3757) relates to this - nothing shows as playing in Plex but the track finishing triggers the Plex scrobbling integration to last.fm.
