### ISSUE TITLE
Volume slider stuck

### ISSUE THREAD

**Issue by rVlad93** [music-assistant/hass-music-assistant#1849]
### What version of Music Assistant has the issue?

2.0.0b90

### The problem

Volume slider becomes stuck but you can still control the volume but the value reamains the same in the UI.

https://github.com/music-assistant/hass-music-assistant/assets/60452666/b1c1852a-acd8-44c3-bf56-879a69c557bd

### How to reproduce

Switch from other tab to music assistant

### What version of Home Assistant Core are your running

2024.1.5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Please review existing issues first https://github.com/music-assistant/hass-music-assistant/issues/1773
