### ISSUE TITLE
HA media_position does not update

### ISSUE THREAD

**Issue by GekoCH** [music-assistant/hass-music-assistant#1852]
### What version of Music Assistant has the issue?

2024.1.0

### The problem

The state `media_position` is not updated while a song is playing.

### How to reproduce

play a song and watch the state of `media_position`

### What version of Home Assistant Core are your running

2024.1.5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
I see the same thing if I cast directly to a apeaker from Spotify and view the attributes of that speaker in HA. So this may not be an MA issue?

**Comment by GekoCH** [comment]
> I see the same thing if I cast directly to a apeaker from Spotify and view the attributes of that speaker in HA. So this may not be an MA issue?

Interesting but when i use LMS (Logitech Media Server) together with squeeze lite i can see the media_position correctly

**Comment by OzGav** [comment]
Still might be a HA issue. A dev will glance at this eventually and we will see what they think

**Comment by marcelveldt** [comment]
media_position may not update as that causes state changes. 
You will have to calculate it yourself from the media_position and the media_position_last_updated timestamp.

If media_position gets updated by LMS in HA that is a bug and one you want to fix as that causes database pollution.
