### ISSUE TITLE
Music assistant bug plays music after TS.speak service is run.

### ISSUE THREAD

**Issue by miketarg** [music-assistant/hass-music-assistant#1853]
### What version of Music Assistant has the issue?

Previous 4 versions 2.0.0.b.90 currently 

### The problem

Music assistant plays music after TS.speak service has run. But only on one Google mini speaker.

### How to reproduce

Just run a ts.service in the effected speaker 

### Relevant log output

Nothing in logs that seem to be useful.

### Additional information

No additional information 

### What version of Home Assistant Core are your running

2024.1.5

### What type of installation are you running?

Home Assistant Core

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
This is expected as TTS is not implemented. TTS implementation expected in he next couple of weeks.
