### ISSUE TITLE
Spotify Loved Tracks being ignored 

### ISSUE THREAD

**Issue by DerPicknicker** [music-assistant/hass-music-assistant#1854]
### What version of Music Assistant has the issue?

Beta 83

### The problem

The current status also in later betas than B83 the Spotify Loved tracks aren’t synced to MA. For me it’s a great feature because I can save my music first and sort them soon or create a great mix of all my genres. 

Here you see the sorting of the Spotify App: 
![image](https://github.com/music-assistant/hass-music-assistant/assets/64746593/7cbe61ad-1351-4e7b-9581-21bbde0817d7)

And here of  MA:
![image](https://github.com/music-assistant/hass-music-assistant/assets/64746593/d7ac687f-d128-4b3e-9cdd-40453658131b)

But this order is only available if you go via the file provider. Which shouldn’t be the way of using your music. 

The provider should support the information when it was added in Spotify. Spotify supports it: https://developer.spotify.com/documentation/web-api/reference/get-users-saved-tracks

I see two options: 
- Create anArea for File-System players and for streaming services which supports liking a song.
- Use the API and write into the DB the correct date of the song and when it was added and make the tracks filtered by music sources.

### How to reproduce

It’s the current behaviour. No steps needed for reproducing. 

### What version of Home Assistant Core are your running

Under Portainer

### What type of installation are you running?

Proxmox

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
I am just looking at this. I don't think this is a problem amymore. My Spotify liked tracks are in the library and recently the liked songs playlist was added as a feature. We will close this soon if there is no more followup

**Comment by OzGav** [comment]
We will close this soon due to no follow up
