### ISSUE TITLE
Cannot communicate with Nextcloud Music through subsonic API

### ISSUE THREAD

**Issue by perillamint** [music-assistant/hass-music-assistant#1856]
### What version of Music Assistant has the issue?

2024.1.0

### The problem

Nextcloud Music plugin provides subsonic API, but Music Assistant cannot communicate with it because Nextcloud does not provide Subsonic MD5 token-based authentication. (it seems they decided to [use SHA-256 to store the token](https://github.com/owncloud/music/blob/master/lib/Middleware/SubsonicMiddleware.php#L118) instead of MD5, which is broken decades ago. Also, TLS being omnipresent in these days, so "legacy" authentication is no longer a security risk anyway)

### How to reproduce

1. Set up the Nextcloud instance with the music plugin.
2. In Nextcloud Music settings, create a new subsonic credential.
3. Attempt to use that credential on Music Assistant Subsonic Music provider
4. Watch it fail with the "Token authentication not supported" error message.

### Additional information

Exposing configuration UI to set value passed to `legacyAuth=[bool]` https://github.com/khers/py-opensonic/blob/master/src/libopensonic/connection.py#46 to user interface will solve the problem.

Relevant codes:
https://github.com/music-assistant/server/blob/main/music_assistant/server/providers/opensubsonic/sonic_provider.py#L72

### What version of Home Assistant Core are your running

2024.1.5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
@khers

**Comment by OzGav** [comment]
Fixed in beta93. Thanks for the PR

**Comment by Kimono8137** [comment]
I'm able to connect and Music assistant shows artists but no tracks even after multiple attempts to syncronize

**Comment by khers** [comment]
How long have you waited for the initial sync? My library is ~12k songs with 1100 artists and 1200 albums and my first sync took ~20 minutes.

One thing you can check (if you are comfortable in python) is to try and connect to your server with the py-opensubsonic library and make sure that you can interact with it at a reasonable pace. The initial scan will push your server a little and if you are hosting on something like a raspberry pi it may struggle to get through quickly.

**Comment by perillamint** [comment]
Note that Nextcloud/Owncloud Music album fetch issue:

You NEED to apply this patch on your Nextcloud/Owncloud Music app: https://github.com/owncloud/music/pull/1125

This is NOT a Music Assistant bug, but Owncloud Music app bug. Wait for the next release of Owncloud Music or patch it by yourself.

**Comment by perillamint** [comment]
Additional update: If you are experiencing this issue, Check your Music app is updated to v1.11.0

https://github.com/owncloud/music/issues/1123#issuecomment-2068189724
