### ISSUE TITLE
HomePod Mini/Airplay keeps getting unavailable

### ISSUE THREAD

**Issue by niteguide** [music-assistant/hass-music-assistant#1877]
### What version of Music Assistant has the issue?

2024.1.0

### The problem

As [this issue](https://github.com/music-assistant/hass-music-assistant/issues/1247) has already been closed and marked as resolved, I have to open a new one. 
Unfortunately this problem still persists: HomePod Mini shows up as available for two minutes every 60 minutes and then goes back to unavailable the rest of the time. I am aware of the setting "Remove Timeout" within Music Assistant - but both setting it to -1 or 3600 does not change a thing unfortunately. 
My router is from Synology (SRM 1.3).

### How to reproduce

Here is what I see in Home Assistant: 
<img width="620" alt="Bildschirmfoto 2024-02-06 um 10 25 27" src="https://github.com/music-assistant/hass-music-assistant/assets/58639459/f04fd8c8-09d2-4972-b997-cfd68e60d667">

### What version of Home Assistant Core are your running

2014.1.5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by niteguide** [comment]
While reading through some discussions regarding MA & Airplay on this site I did some testing with different router settings - nothing was successful. Here are my latest settings - maybe this helps for further investigating the issue:

- Synology SRM 1.3.1-9346
- Wifi settings: 
      - WPA2-Personal
      - PMF Support: deactivated
      - Key Rotation: 0
      - DTIM: 1
      - Multicast translation: deactivated
      - AMPDU: activated
      - U-APSD: deactivated
      - AP-isolation: deactivated
      - MU-MIMO: deactivated
      - 802.11r: deactivated
      - Disable Smart Connect for Devices not supporting 802.11v: activated
      - Reginal compatibility: deactivated
 - Network Settings: 
     - Network isolation: deactivated (however seems to be irrelevant in my opinion thus MA/HA and HomePod Mini are in the same Wifi network) 
     - IPv6: deactivated (not yet supported by provider)
     - IGMP Snooping: activated
     - NAT: activated
     - UPnP: activated
     - Automatically change LAN IPs when detecting conflicts with the WAN subnet: activated
     - DoH (DNS over HTTPS): deactivated
     - Multicast DNS relay: deactivated

**Comment by OzGav** [comment]
Do you have any other players? If so, do they work ok?

**Comment by niteguide** [comment]
Besides the HomePod Mini I also have an Airport Express as an Airplay device in the network. The Airport Express shows the same problems as the HomePod Mini. Furthermore I have one Google Home (Nest) Mini that works absolutely reliably.

**Comment by niteguide** [comment]
I did some further testing and might have found something: After setting up the "Apple Air Player" integration for the HomePod Mini and reinstalling MA the player stays connected (state "idle"). My other Airplay device I have not added to the  "Apple Air Player" Integration and it keeps disconnecting. I do not know if this has some logical background ... I was thinking  (maybe wrongly) that MA fully adds the player to HA and that there is no need for another integration ...
I will continue to report if the HomePod Mini stays connected - maybe after some weeks.

**Comment by OzGav** [comment]
That is useful info. FYI MA does not “fully add the player to HA”. It creates an entity in HA that when interacted with that data flows through the integration back to MA. 
What might be happening is the HA integration is keeping the player alive which we need to replicate in MA.

**Comment by OzGav** [comment]
Please confirm what server version you are running. Latest is 2.0.0b103

**Comment by niteguide** [comment]
Thanks for asking! Running 2.0.0.b104 now. HomePod Mini works - as it did before. But no matter what I do - MA won't play any music on the older Airport Express (that I now have also added via the Apple Air Player integration). The Airport Express appears to be available under devices, I  can choose it as an option in MA but song will not start.

**Comment by OzGav** [comment]
Looks like an incompatability with the older hardware. What year was it manufactured? Looking at Wikipedia it says the 2012 model was given Airplay 2 support in 2018. Is that your model? If so, is there a setting to force Airplay 1?

**Comment by OzGav** [comment]
Also have you triedturning on encryption in the advanced settings?

**Comment by niteguide** [comment]
I agree that this is old hardware - the Airport Express got the Airplay 2 update in 2018, yes! No option to downgrade as far a I can see. I have definitely tried it with encryption on and off!

**Comment by OzGav** [comment]
OK will try and have a look at this further in due course

**Comment by OzGav** [comment]
Oh and the separate issue of the Homepod Mini going unavailable every few minutes is that still a problem?

**Comment by niteguide** [comment]
The problem with the Home Pod Mini going unavailable in my case does not occur at the moment or I should say does not occur since I also added the Home Pod Mini to HA via Apple Air Player integration (three weeks ago). Since then the HomePod Mini was Available without any interruptions.

**Comment by OzGav** [comment]
Yeah ok maybe the HA integration is pinging it and keeping it alive somehow. Will see what we can do here once workload allows. Thanks for all the info.

**Comment by OzGav** [comment]
News on the AirPort Express is that due to the age of the player support was not added in the recent Airplay rewrite. It will be added in due course. You can follow progress on that issue here https://github.com/music-assistant/hass-music-assistant/issues/1954

**Comment by OzGav** [comment]
The airport express should be working in b106. Please advise if not.

Also confirm the Homepod mini is still cycling between available and unavailable and if so provide the logs from before it is available, for the two minutes it becomes available and then for a short period after if goes unavailable again.

**Comment by marcelveldt** [comment]
I have a few Home Pod minis myself here and these stay online since the airplay provider rewrite.
So let's close this issue as it should be solved. The airport express issue is tracked in a separate issue.
