### ISSUE TITLE
v1.1.5: No media info mass players

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#188]
When playing Spotify playlists, the mass* plays display media info,
With local media I only see the the media info in the MA p player, the mass* players are out of sync.
Status mass:
```
volume_level: 1
media_content_type: music
media_position: 13
media_position_updated_at: '2022-05-18T11:01:33.033163+00:00'
app_id: mass
app_name: Music Assistant
shuffle: false
repeat: 'off'
entity_picture_local: null
source_entity_id: media_player.audio57woonkmr
is_group: false
group_childs: []
group_parents: []
active_queue: media_player.audio57woonkmr
items_in_queue: 0
device_class: speaker
friendly_name: Audio57WoonKmr
supported_features: 456629
```

In Lovelace, the MA player:
![image](https://user-images.githubusercontent.com/4363599/169036450-3e55fe12-ea11-4675-b3b3-8110b73f11e2.jpeg)
And the mass player:
![image](https://user-images.githubusercontent.com/4363599/169036464-9df8bb88-1efe-4f6d-b198-638b72f2ea4a.jpeg)

**Comment by marcelveldt** [comment]
You mean this happens only when playing local files ?

**Comment by erkr** [comment]
Yep

**Comment by erkr** [comment]
Fixed ✊
