### ISSUE TITLE
Disable auto play after automation with sound

### ISSUE THREAD

**Issue by FelixM93** [music-assistant/hass-music-assistant#1883]
### What version of Music Assistant has the issue?

2.0.0b92

### The problem

Through an automation in which a sound is played on a box, the previously selected playlist is then played although no music was heard beforehand. 
If music was playing beforehand, it will continue to play after the sound, which is correct. 
Issue was already which previous version but couldn‘t find a solution to fix. 

### How to reproduce

Stop the music and start the automation again.

### What version of Home Assistant Core are your running

11.5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
That is normal as you are starting the queue. If you don’t want the queue to continue playing then clear the queue as part of your automation

**Comment by FelixM93** [comment]
Thanks. I will try it :)
