### ISSUE TITLE
Popping Sounds from speakers when playing a radio station to Chromecast audio

### ISSUE THREAD

**Issue by miketarg** [music-assistant/hass-music-assistant#1899]
### What version of Music Assistant has the issue?

2024.1.0

### The problem

If I use music assistant to stream radio via scripts then I get popping noises coming from the speakers. I have confirmed that this isn't a speaker or cable issue, as if I ask Google to play the same radio station via it own service this doesn't happen, it only happens with radio stations and not music from Spotify and only when this is done via music assistant. This is a relatively new issue not experienced on older versions of the plugin. Unfortunately I'm unsure when it actually started.

### How to reproduce

Using music assistant to play radio stations

### What version of Home Assistant Core are your running

2024.2.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
You have specifically said it only happens when using scripts. Is that true? Are you saying that if you just play the radio station from the UI the phenomenon doesn’t occur?

**Comment by miketarg** [comment]
Hey, sorry I haven't worded that very well.

It only happens when I use music assistant, either with the UI or scripts.

It never happens when I use music services from a Google speaker.

I hope this makes sense.

It never used to happen it stated a few weeks ago, unfortunately I didn't
notice it and make a note of what update caused this behaviour.

Mike

**Comment by OzGav** [comment]
and please confirm it only happens when playing a radio station. That is, other music providers work ok.

**Comment by miketarg** [comment]
I will double check when I get home.

**Comment by miketarg** [comment]
Hello all,

I have just confirmed that it only does it on the radio and only when using
it via music assistant.

It doesn't do it when using Music Assistant playing a playlist or song from
Spotify. It doesn't do it when playing radio via Google speaker if
requested via voice. But it does it a lot when using the radio via music
assistant.

There is definitely something wrong here.

What if anything can I provide to help solve this issue?

Mike.

**Comment by OzGav** [comment]
Does it happen with all radio stations? If not supply the station names and the integration you are using to access them.

**Comment by miketarg** [comment]
Yes all radio stations

**Comment by OzGav** [comment]
Confirm what radio station provider you are using and provide one radio station that is showing this behaviour

**Comment by miketarg** [comment]
I'm using radio browser. And radio X is particularly bad.

Regards Mike.

**Comment by OzGav** [comment]
I’m playing this one 
<img width="340" alt="image" src="https://github.com/music-assistant/hass-music-assistant/assets/19848947/ed27a795-8857-4a7c-80ca-a02ca788524a">

No problems noted after five minutes. Is that the station you meant?

**Comment by miketarg** [comment]
Yes, that's it.

**Comment by OzGav** [comment]
We will have to think about it some more since we can’t recreate it. I assume you are using a Chromecast device? Do you have other devices you can test with?

**Comment by miketarg** [comment]
Hi yes it's an Chromecast Audio. I have 6 in total and they all behave the
same way.

Unfortunately I don't have anything other than this to test with ATM.

I believe it started doing this around 1 month ago. I'm sorry I didn't make
a note of the update version as I thought I had an issue with the
connections at first.

Once I had ruled that out I began testing if it behaves like it with Google
(and it doesn't)

I am open to testing here but I don't have anything other than the
Chromecast audio to this on.

I do have Google minus too however.

**Comment by OzGav** [comment]
Do try the minis, that is what I tested on here.

**Comment by miketarg** [comment]
I have just tested it on the mini and it appears to be working without the
issue.

So it seems to only happen on a Chromecast audio for some reason.

I have also double by asking "hey Google" play radio X in the kitchen, and
it works fine in this instance. This uses global player to do this if this
helps you narrow it down.

**Comment by OzGav** [comment]
Thanks. We will get back to you in due course

**Comment by miketarg** [comment]
Thank you for your response.

**Comment by miketarg** [comment]
Hello is there any update on this issue, it's still persisting?

**Comment by OzGav** [comment]
When there is an update you will hear about it here.

**Comment by marcelveldt** [comment]
I can't reproduce this issue on any chromecast target I've tried. I'll see in some cabinet if I still have a chromecast audio lying around somewhere later this week.

**Comment by miketarg** [comment]
Ok thanks for letting me know, I have started to use the play media service
instead, it's a shame as I really like Music Assistant but it's very buggy
at the moment.

**Comment by marcelveldt** [comment]
What you call buggy is used by 10000s of people on a daily base, comments like that do not help your case.

**Comment by miketarg** [comment]
Thanks, but in my experience it is buggy at the moment. It's a shame as I
find it far better than the built in audio options on offer. It's not a
personal attack on MA, just a statement of the facts.

**Comment by miketarg** [comment]
Thanks for the tip!

Will try this 👍🏻
