### ISSUE TITLE
V1.1.5: input player state wrong

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#190]
Scenario:
-Casting Spotify to a CC group with just one CC powered on (woonkamer)
-Powering on a second CC (serre)
-the second CC automatically joins by Casting the same music

In MA the state is uit off sync:
![image](https://user-images.githubusercontent.com/4363599/169139532-8ac9dc5c-e1e9-4caf-85db-de58a7068731.jpeg)

The input player seems in the correct state:

```
volume_level: 0.3199999928474426
is_volume_muted: false
media_position_updated_at: '2022-05-18T19:03:12.274274+00:00'
app_id: 705D30C6
app_name: Default Media Receiver
entity_picture_local: null
friendly_name: Audio57Serre
supported_features: 152461

```

**Comment by marcelveldt** [comment]
I'm not sure if this is even fixable due to the fact you entirely turn off the cast player.
Looking at the attributes, the media position is missing.
I guess the state corrects itself as soon as you change something on the player like volume ?

**Comment by erkr** [comment]
I will try that

**Comment by erkr** [comment]
I noticed that the mass* players for the second CC had the right artwork, but the wrong state (paused). After pressing play, the state of both the mass* players and the status in MA is correct indeed.

**Comment by marcelveldt** [comment]
I'm not sure if I can fix that because the state of the origin player (cast) is not updated.
For MA to properly determine the state it is important that both the "media_content_id" and "media_position" are set on the origin player. It does look like the cast player is not updated when it is powered on (and the group already playing)

**Comment by marcelveldt** [comment]
Temporary workaround: Create automation in HA, triggered by the state of the client to go from unavailable to "playing". pause, delay of 100ms and play. 

A short pause and resume makes the metadata info present on the cast player.
Although a bit of an edge case this could be considered a (very tiny) bug on the cast integration.

**Comment by erkr** [comment]
That is a good option. Will give it a try😊
And agreed this probably is a cast issue. Will close this one. Thx!
