### ISSUE TITLE
OpenAI Integration not working

### ISSUE THREAD

**Issue by monogoat** [music-assistant/hass-music-assistant#1905]
### What version of Music Assistant has the issue?

2024.1.0

### The problem

Using the provided prompt for the openai integration, and the provided yaml file for the custom_sentences/en folder, I cannot get anything to work with the assistant. I was able to get it to function with Jlo's automation blueprint, but I wanted to use the built in handling for other rooms / devices.

### How to reproduce

I followed all instructions provided in the FAQ, and typed "play linkin park on rbr speaker" or any other device name, artist name, etc.

### Relevant log output

Unexpected error during intent recognition
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 988, in recognize_intent
    conversation_result = await conversation.async_converse(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/conversation/__init__.py", line 543, in async_converse
    result = await agent.async_process(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/conversation/default_agent.py", line 221, in async_process
    result = await self.async_recognize(user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/conversation/default_agent.py", line 195, in async_recognize
    lang_intents = await self.async_get_or_load_intents(language)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/conversation/default_agent.py", line 544, in async_get_or_load_intents
    return await self.hass.async_add_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/conversation/default_agent.py", line 631, in _get_or_load_intents
    merge_dict(intents_dict, custom_sentences_yaml)
  File "/usr/local/lib/python3.12/site-packages/hassil/util.py", line 20, in merge_dict
    assert isinstance(
AssertionError: Not a dict: None

### Additional information

Server is running in a docker container on an unraid machine, version 2.0.0b93.

### What version of Home Assistant Core are your running

2024.2.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
That is an error in the HA pipeline so not a problem with MA. Have you removed the Blueprint?

**Comment by monogoat** [comment]
I removed the automation, yes. Now testing stuff, it seems like built in intents aren't working either. I guess something is broken in my instance. 

I realized I can source the automation details from within the blueprint yaml file, so I just made my own automation using his as a basis. I guess I'll just build my own out for room awareness and device specific playback like I've done for lights, fans, etc. It is working fine this way at least.

**Comment by OzGav** [comment]
I didnt ask about the automation I asked about whether you had removed the blueprint.

**Comment by OzGav** [comment]
You might run into issues doing it that way but god luck!

**Comment by monogoat** [comment]
The blueprint template was left there available to use, but I removed the automation that was created by the template. I think we are on the same page now? Unless having a template downloaded is a problem.

Thanks for the assist!

**Comment by OzGav** [comment]
Could be I am not sure as I don't use them. I would remove that if you aren't using it. With the new assist feedback sentences you should be able to get some useful info. You can also add the following to your configuration.yaml so you can see more detail about the intent failure

```
    logger:
      default: warning
      logs:
        homeassistant.components.conversation: debug
        homeassistant.components.intent: debug
```

**Comment by loryanstrant** [comment]
@monogoat I've only just set it up today and it's not working for me, so I'm keen to see if you had any luck getting it going.
