### ISSUE TITLE
Deezer integration - error

### ISSUE THREAD

**Issue by wernervanblom** [music-assistant/hass-music-assistant#1909]
### What version of Music Assistant has the issue?

2024.1.0

### The problem

1) Deezer integration worked with previous version of MAss
2) I have updated MAss to 2024.1.0
3) The Deezer integration asked for re-authorization after the update
4) I did the re-auth process successfully and an access token got send back to MAss from the Deezer auth website.
5) Clicking on Save to finish the process of linking to Deezer results in error message

Error message: "Provider Deezer did not load within 30 seconds"
I could not find any timeout setting to increase it.

Attached please find the following files:
* HA information
* HA logs 
* MAss logs
* Error message

[home-assistant-system information.txt](https://github.com/music-assistant/hass-music-assistant/files/14298238/home-assistant-system.information.txt)
[d5369777_music_assistant_beta_2024-02-15T14-51-57.263Z.log](https://github.com/music-assistant/hass-music-assistant/files/14298339/d5369777_music_assistant_beta_2024-02-15T14-51-57.263Z.log)
[home-assistant_2024-02-15T14-18-41.064Z.log](https://github.com/music-assistant/hass-music-assistant/files/14298241/home-assistant_2024-02-15T14-18-41.064Z.log)
![Screenshot](https://github.com/music-assistant/hass-music-assistant/assets/159584657/c4e4aa69-b5ff-473d-8b8b-ef129d666d9e)

### How to reproduce

1) Goto MAss
2) Click Settings 
3) Click Add Music Provider and select Deezer
4) Click the Authenticate with Deezer" button
5) Login if required on the Deezer site that just opened
6) You should be re-directed back to HA site.
7) Access token should be populated.
8) Click on SAVE

### Additional information

Core
2024.2.1
Supervisor
2024.01.1
Operating System
11.5
Frontend
20240207.1

### What version of Home Assistant Core are your running

2024.2.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
This is known about and is being worked on.

**Comment by AlWolf98** [comment]
Same issue on my end as well. Same repro steps and actual results.

**Comment by kiki35290** [comment]
Same for me

**Comment by OzGav** [comment]
Temporary fix available in b100. You can manually enter the token

**Comment by OzGav** [comment]
The devs are working on it. It is a very difficult problem and maybe this is the final solution. Time will tell but there is no need to leave it open as we know what has happened, a fix has been provided and other possible solutions are being researched.
