### ISSUE TITLE
Volume setting still not working properly 

### ISSUE THREAD

**Issue by papabak** [music-assistant/hass-music-assistant#1914]
### What version of Music Assistant has the issue?

2.0.0b94

### The problem

The volume has improved in that it can be changed and the value changes correspondingly, but when changing the volume a second time the value of the slider does not change. The sound level however does change

### How to reproduce

Can be reproduced 

### What version of Home Assistant Core are your running

2024.2.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

ODROID

**Comment by OzGav** [comment]
Try beta100

**Comment by OzGav** [comment]
We will close this soon due to no follow up

**Comment by OzGav** [comment]
Try b103

**Comment by papabak** [comment]
I have b103 installed. Works fine now!
________________________________
Van: OzGav ***@***.***>
Verzonden: Tuesday, February 20, 2024 11:05:12 PM
Aan: music-assistant/hass-music-assistant ***@***.***>
CC: papabak ***@***.***>; Author ***@***.***>
Onderwerp: Re: [music-assistant/hass-music-assistant] Volume setting still not working properly (Issue #1914)


Try b103
