### ISSUE TITLE
Player Provider not been rename for BEO Soundstage

### ISSUE THREAD

**Issue by MarcMTLDK** [music-assistant/hass-music-assistant#1915]
### What version of Music Assistant has the issue?

2.0.0b94

### The problem

The problem is concerning the Player Provider which seems to use the device type name plus the serial number of the device. 
I guess, the Entity could include the Serial Number but the name should be the Name of the device which can be used as we wish. The device name can be change in the device itself. 

There is also some inconsistency (I believe) between what is available in Home Assistant "Music Assisant" and the other source available. 

Ex:

The device in the  Player Provider is called: Beosound-stage-34146xx. 
When I Click on configuration for the player and I change the name for BEOSoundStage, the value is not reflected int he player itself from the list shows in the right side panel. We can stil see the initial name which is : Beosound-stage-34146xx. 

But the DLNA seems to work prettty welll.

### How to reproduce

Music Assistante / configuration / provider / change the name 

Below is the Log File when renaming the player

### Relevant log output

[d5369777_music_assistant_beta_2024-02-16T17-54-42.546Z.log](https://github.com/music-assistant/hass-music-assistant/files/14314411/d5369777_music_assistant_beta_2024-02-16T17-54-42.546Z.log)

### Additional information

I'm running the supervised version on Debian 12,

### What version of Home Assistant Core are your running

 Core 2024.2.1 Supervisor 2024.01.1 Operating System Interface utilisateur 20240207.1

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
I can’t recreate this. I tried renaming a Fully Kiosk player as well as a Chromecast and both worked as expected. Have you tried clearing the browser cache? Have you tried a different browser?

**Comment by OzGav** [comment]
Oh hang on I see it. You are changing the PROVIDER name. You need to select PLAYERS in the top right of the settings and then change the PLAYER name

**Comment by MarcMTLDK** [comment]
I’ll try it
