### ISSUE TITLE
[Bug] pyatv not found after upgrading by from B94 to B95

### ISSUE THREAD

**Issue by zimmra** [music-assistant/hass-music-assistant#1916]
### What version of Music Assistant has the issue?

B95

### The problem

Settings page does not load

logs throw error from module `pyatv` not being found

this is on x86 Home Assistant OS

### How to reproduce

Upgrade from B94 to B95

attempt to view settings page

### Additional information

Manually running `pip install pyatv` within the addon’s docker container cleared the issue

### What version of Home Assistant Core are your running

2024.2.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
This is known and will be fixed in the next beta

**Comment by OzGav** [comment]
Fixed in b96
