### ISSUE TITLE
InvalidFieldValue: Field "supported_features" of type tuple[PlayerFeature, ...] ...

### ISSUE THREAD

**Issue by maisen20** [music-assistant/hass-music-assistant#1917]
### What version of Music Assistant has the issue?

2024.1.0b2 (2.0.0b94)

### The problem

I can use Music Assistant and it seems to work as it should, but in the logs I have the following error message that keeps appearing. I have no idea what the problem is.

### How to reproduce

Play music/radio stations

### Relevant log output

Error doing job: Exception in callback Players._handle_event(MassEvent(eve...ra_data': {}}))
Traceback (most recent call last):
  File "<string>", line 37, in __mashumaro_from_dict__
  File "/usr/local/lib/python3.12/enum.py", line 744, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/enum.py", line 1158, in __new__
    raise ve_exc
ValueError: 'enqueue_next' is not a valid PlayerFeature

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.12/site-packages/music_assistant/client/players.py", line 302, in _handle_event
    self._players[event.object_id] = Player.from_dict(event.data)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 39, in __mashumaro_from_dict__
mashumaro.exceptions.InvalidFieldValue: Field "supported_features" of type tuple[PlayerFeature, ...] in Player has invalid value ['sync', 'volume_mute', 'volume_set', 'enqueue_next', 'pause']

### What version of Home Assistant Core are your running

2024.2.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
What players are you using?

**Comment by maisen20** [comment]
Sorry, I had overlooked the notification. The problem has arisen since I started using the Ikea SYMFONISK (Sonos):
https://www.ikea.com/us/en/p/symfonisk-sonos-wifi-bookshelf-speaker-black-smart-gen-2-20506584/

**Comment by marcelveldt** [comment]
You need to update the server to a newer beta. Looks like you're running into an incompatibility between HA integration and the server.

**Comment by maisen20** [comment]
I have done the update and wanted to test it first before I write that everything is ok. But yesterday the problem no longer occurred, but I wasn't able to test it today. It seems to be solved with the update.  Thank you!
