### ISSUE TITLE
No players showing in UI / Ingress

### ISSUE THREAD

**Issue by spycle** [music-assistant/hass-music-assistant#1919]
### What version of Music Assistant has the issue?

2024.1.0

### The problem

Since the addon updated to 2.0.0b98 (first noticed in 2.0.0b96 when AirPlay was broken, then fixed in 2.0.0b97 but now broken again in 2.0.0b98) , I can no longer configure any players in the UI. The page is empty. If I click on the speaker icon however then I can see all my receivers.

The providers tab and the core tab appear to be fine.

### How to reproduce

Update addon to 2.0.0b98
Lose ability to configure players in the UI

### Relevant log output

Nothing useful that I can see

### What version of Home Assistant Core are your running

2024.2.2

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by spycle** [comment]
![image](https://github.com/music-assistant/hass-music-assistant/assets/48740594/0f67bb14-cf2e-4473-8e34-dfb407e8258c)
![image](https://github.com/music-assistant/hass-music-assistant/assets/48740594/07e36c72-580f-4887-8482-6f73b3167ea7)

**Comment by spycle** [comment]
Fixed in 2.0.0b97 thanks

**Comment by spycle** [comment]
Broken again in 2.0.0b98

**Comment by OzGav** [comment]
This is working fine for everyone else as far as I am aware. Try b99

**Comment by spycle** [comment]
Fixed in 2.0.0b100 thanks. I think it was somehow linked to AirPlay receivers not working

**Comment by jaymunro** [comment]
Seems broken again in 2.0.0b107

The only player showing is a new speaker just added yesterday (it has 2 versions Google Cast & AirPlay) plus a GoogleCast group, also added yesterday. Others added prior are missing in Settings > Players but are showing in the speaker selection list.

![IMG_0503](https://github.com/music-assistant/hass-music-assistant/assets/1166024/b50776ca-4fa6-474e-a916-f6bc9a6014ee)
