### ISSUE TITLE
Volume slider and play/pause button issue

### ISSUE THREAD

**Issue by rVlad93** [music-assistant/hass-music-assistant#1922]
### What version of Music Assistant has the issue?

2.0.0b99

### The problem

Volume slider and play/payse button not doing working.

### How to reproduce

When trying to change the volume the slider moves but the volume remains the same.
When pressing the play/pause button doesn't do anything. The animation changes from play to pause and vice-versa but the music keeps playing.

### What version of Home Assistant Core are your running

2024.2.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by marcelveldt** [comment]
fixed in beta 100
