### ISSUE TITLE
Error on import HA player (and fullykiosk/snapcast)

### ISSUE THREAD

**Issue by collateral87** [music-assistant/hass-music-assistant#1923]
### What version of Music Assistant has the issue?

2024.1.0

### The problem

When i import a HA music player from the dropdown list i get the following error in the logs and the loading animation stucks in an endless loop:

![grafik](https://github.com/music-assistant/hass-music-assistant/assets/97076257/aeb15071-0dd6-4c5b-9a31-5bd8a78b7eed)
![305711851-ad64f458-854c-4ab7-80d2-dd36b2de095b](https://github.com/music-assistant/hass-music-assistant/assets/97076257/7c86dd17-65fa-4a6b-be96-10c52649d531)

### How to reproduce

import a HA music player in MA

### Relevant log output

please see above

### What version of Home Assistant Core are your running

2024.2.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
Have you tried importing any other player?

**Comment by collateral87** [comment]
Yes, nearly all i have.
Can you tell me, what i have to enter in the input fields for url and token in the plugin setup. Maybe i did something wrong here?

**Comment by OzGav** [comment]
From Discord

```
The Home Assistant integration consists of 2 parts:

**1) The Home Assistant Plug-in provider**

This is mandatory and here you set-up the connection to the HA server.
This plugin is now an empty placeholder but will in the future contain some additional features such as the player controls we talked about yesterday.
--> on the Music Assistant add-on (so on HAOS), you wont need any server details or whatever, it should auto connect to the local HA instance.
--> on the docker version of the HA server, it will ask you to enter the URL to your HA instance and then authenticate.


**2) The Home Assistant Player Provider**

Allows you to use your HA players within MA, a bit like how v1 of MA worked back then.
--> You need the HA plug-in first before you can use/install this provider.
--> In the provider settings, you select which players you want to utilize.
--> You can only use players that support "play_media", other players will be filtered out.
--> MA players will also be filtered out.
--> Features are most likely limited. Always prefer a native player provider if it exists in MA as that is optimized to work with MA
```

**Comment by collateral87** [comment]
Thank you for the instructions. 

Hm unfortunatly, this is exactly, what i did.

**Comment by Smarthome-Creator** [comment]
@collateral87 , in such a case, I would advise you to reinstall the add-on.
Uninstall the add-on, restart HA completely, reinstall the add-on and try again.

**Comment by collateral87** [comment]
i did this today and the problem persists..

additional, now i cant add snapcast and fullykiosk player provider anymore...

![grafik](https://github.com/music-assistant/hass-music-assistant/assets/97076257/fb567eaa-c6a6-43fc-b9e6-75d2985ab3c3)
![grafik](https://github.com/music-assistant/hass-music-assistant/assets/97076257/1a895ad3-d337-4a9d-b4f8-725db258804e)

iam out of solutions

**Comment by collateral87** [comment]
![grafik](https://github.com/music-assistant/hass-music-assistant/assets/97076257/d8edad35-5002-4fc1-bbc8-3de6584d3d39)

these are the logs from the fullykiosk provider. snapcast is similar

**Comment by OzGav** [comment]
The Snapcast and fully kiosk issue will be fixed in the next update

**Comment by collateral87** [comment]
Thank you for the information.

When you need additional information or testing for the issue with the endless loading screen on HA player setup, just get in touch.

**Comment by n8ohu** [comment]
Any timeline on the next update, since I'm running into this exact error trying to add back snapcast after removing and reinstalling the addon.

**Comment by OzGav** [comment]
Should be fixed in b102
