### ISSUE TITLE
Spotify Discover Weekly Playlist doesn't seem to refresh

### ISSUE THREAD

**Issue by dragon2611** [music-assistant/hass-music-assistant#1925]
### What version of Music Assistant has the issue?

2024.1.0

### The problem

On Monday Spotify updates the Discover Weekly Playlist, but MA still shows last week's playlist, pressing refresh doesn't seem to update the playlist either.

### How to reproduce

Wait for Spotify to update playlist, MA still has old playlist content.

### Additional information

If I clear the cache in Settings > Core > Cache controller then I can pull the current version of the Discover Weekly playlist.

### What version of Home Assistant Core are your running

2024.2.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Have you waited a long time to see if it eventually gets pulled down. I have seen slow updates after adding to playlists so wondering if that is related

**Comment by OzGav** [comment]
Can you recheck with b128

**Comment by OzGav** [comment]
We will need to close this soon due to no follow up.

**Comment by dragon2611** [comment]
If I remember I will check, I believe the playlist changes on a Monday

**Comment by dragon2611** [comment]
Sadly I forgot to check yesterday and it had refreshed when I checked it today.
