### ISSUE TITLE
HA integration - server address

### ISSUE THREAD

**Issue by Sonusss** [music-assistant/hass-music-assistant#1937]
### What version of Music Assistant has the issue?

2024.1.0

### The problem

I had to change the network location of my MA server.
Seems impossible to change/override a previous setup of MA integration in HA.
Always comes up with a connection error "Failed setup" on the **old server IP address**...

### How to reproduce

Remove HA integration, restart HA, install HA integration

### Additional information

Same behavior with previous version 2023.6.0b6

### What version of Home Assistant Core are your running

2023.10.1

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
After removing the HA integration, try removing via HACS as well, restart HA and then reinstall

**Comment by marcelveldt** [comment]
Did you restart the MA server after changing the IP ? Otherwise its still broadcasting discovery info with the wrong IP.
You also might need to check the publish IP in the MA settings for webserver and streamserver
