### ISSUE TITLE
Sort order for radio stations erratic

### ISSUE THREAD

**Issue by andreasbrett** [music-assistant/hass-music-assistant#1938]
### What version of Music Assistant has the issue?

2.0.0b102

### The problem

Radio station sort order is erratic. When setting sort order to alphabetical, only some radio stations are correctly sorted (see screenshot).

![image](https://github.com/music-assistant/hass-music-assistant/assets/6610451/7e890170-3a7a-4ce1-9303-aaf7fe6a6d88)

### How to reproduce

Open radio stations overview and sort alphabetically.

### What version of Home Assistant Core are your running

2024.2.2

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

**Comment by andreasbrett** [comment]
All radio stations were imported via TuneIn provider

**Comment by OzGav** [comment]
@marcelveldt I am not sure if this is fixed. When I sort by recently added it seems to be alphabetical but otherwise I see

![IMG_1244](https://github.com/music-assistant/hass-music-assistant/assets/19848947/1d83a9a9-2c9c-47cf-b435-746d4e8fd7e9)

**Comment by OzGav** [comment]
Just reopening to check this behaviour. I have one station that when sorted Alphabetically is in the correct spot with the correct thumb but when I sort by SORT NAME it moves and the thumb nail letters are wrong?

![image](https://github.com/music-assistant/hass-music-assistant/assets/19848947/d34f9e24-c332-437b-bf57-2c6df2333d79)

![image](https://github.com/music-assistant/hass-music-assistant/assets/19848947/da25b122-a4a2-41f4-9dcc-f7cbf0bb7d35)

**Comment by marcelveldt** [comment]
You will need to do a full rescan (or simply re-setup the Tune In provider) to fix that - Tune-In filled the sort name with the wrong info a while ago which is fixed in code but not in your data.

**Comment by OzGav** [comment]
Is that the same for radio browser because that Essex station is from there?

**Comment by OzGav** [comment]
I just deleted and added it again and seems good.
