### ISSUE TITLE
Wrong link in Settings > Setup providers > Soundcloud

### ISSUE THREAD

**Issue by SnelleJelle019** [music-assistant/hass-music-assistant#1941]
### What version of Music Assistant has the issue?

2.0.0b103

### What version of the Home Assistant Integration have you got installed?

2024.1.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

The "checkout documentation" link on the Soundcloud setup links to https://music-assistant.github.io/music-providers/soundcloud/
This link does not exist anymore, and should be https://music-assistant.io/music-providers/soundcloud/

### How to reproduce

Go to Settings > Setup providers > Soundcloud > "Checkout documentation"

### Music Providers

-

### Player Providers

-

### Relevant log output

-

### Additional information

-

### What version of Home Assistant Core are your running

2024.2.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Alternative

**Comment by OzGav** [comment]
As it turns out I just submitted a PR to fix all the links. Thanks!
