### ISSUE TITLE
Cannot browse media (albums) from within Home Assistant

### ISSUE THREAD

**Issue by simowilso** [music-assistant/hass-music-assistant#1946]
### What version of Music Assistant has the issue?

2.0.0b103

### What version of the Home Assistant Integration have you got installed?

2024.1.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Browsing media from a media player device on home assistant works fine, except when browsing albums which results in an unknown error.

### How to reproduce

Select a media player device in Home Assistant (eg Sonos).
Click on "browse media"
Click on "albums"
Click on an album

Result:

Media Browsing Error
Unknown error

### Music Providers

smb files system (remote share)

### Player Providers

Sonos, not grouped.

### Relevant log output

2024-02-22 18:21:08.155 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [281470290935616] Error handling message: Unknown error (unknown_error) XXXXXXXXX  from 192.168.0.234 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 1310, in websocket_browse_media
    payload = await player.async_browse_media(media_content_type, media_content_id)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mass/media_player.py", line 496, in async_browse_media
    return await async_browse_media(self.hass, self.mass, media_content_id, media_content_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mass/media_browser.py", line 103, in async_browse_media
    return await build_album_items_listing(mass, media_content_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mass/media_browser.py", line 254, in build_album_items_listing
    tracks = await mass.music.get_album_tracks(album.item_id, album.provider)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/client/music.py", line 155, in get_album_tracks
    for item in await self.client.send_command(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/client/client.py", line 168, in send_command
    return await future
           ^^^^^^^^^^^^
music_assistant.common.models.errors.InvalidCommand: Invalid command: music/album/album_tracks

### What version of Home Assistant Core are your running

2024.2.0

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Have you other players to try? I just tried with a chromecast and a slimproto device and both worked fine.

**Comment by OzGav** [comment]
Try removing the integration from HA, then remove it from HACS, restart HA then reinstall

**Comment by simowilso** [comment]
> Try removing the integration from HA, then remove it from HACS, restart HA then reinstall

Unfortunately still the same

**Comment by OzGav** [comment]
OK this sill get looked at in due course

**Comment by marcelveldt** [comment]
This is fixed in the 2024.2.x version of the HA integration.

**Comment by simowilso** [comment]
Just updated and yes looks like it's ok, thank you!

**Comment by OzGav** [comment]
This has been fixed in b110

**Comment by hazzapatcher** [comment]
Hi all, 

I'm suffering from the same issue when attempting to create an automation using media player media picker. When a music assistant player is selected, the options for Tracks/Playlist appear, but when selected, the 

Media Browsing Error
Unknown error

Appears. 

**HA versions:**

Core
2024.10.4
Supervisor
2024.10.3
Operating System
13.2
Frontend
20241002.4


**MA version:** 

Music Assistant Server
Current version: 2.3.2 

Thanks!

**Comment by OzGav** [comment]
@hazzapatcher you have asked a question in a closed issue from six months ago. You can ask your question in the discussions area. I would attach a screenshot or two as I am not sure what you are trying to do (not surprising though asI do all my automations in yaml)
