### ISSUE TITLE
404 in github pages

### ISSUE THREAD

**Issue by basings** [music-assistant/hass-music-assistant#1947]
### What version of Music Assistant has the issue?

2022

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

404 https://music-assistant.io/installation/

### How to reproduce

go to https://music-assistant.io/installation/

### Music Providers

https://music-assistant.io/installation/ 

### Player Providers

https://music-assistant.io/installation/

### What version of Home Assistant Core are your running

2024

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Yep we are looking at it.

**Comment by OzGav** [comment]
Now fixed
