### ISSUE TITLE
Feature: option to enable including provider name in device

### ISSUE THREAD

**Issue by dragon2611** [music-assistant/hass-music-assistant#1948]
### What version of Music Assistant has the issue?

2024.1.0

### What version of the Home Assistant Integration have you got installed?

2024.1.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Some speakers support multiple providers (such as newer Sonos speakers supporting AirPlay).

This causes them to show up twice in music assistant, since both devices have the same name it’s not that easy to tell which player provider you are using when selecting the speaker which may cause issues for grouping via music assistant.

### How to reproduce

Have a player/speaker that supports multiple protocols 

### Music Providers

Any

### Player Providers

Sonos
AirPlay 

### What version of Home Assistant Core are your running

2024.2.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by dragon2611** [comment]
I did find the option to change the name of a device which works but it would be nice if there was an option to show the provider to avoid the need to manually rename each device

**Comment by OzGav** [comment]
In the player list in the settings the provider is shown against each player by an icon and text. The expectation is you would disable any duplicate players so you only have one per device.

**Comment by dragon2611** [comment]
> In the player list in the settings the provider is shown against each player by an icon and text. The expectation is you would disable any duplicate players so you only have one per device.

I thought I had done that previously but they seemed to appear again after one of the updates.

**Comment by OzGav** [comment]
I am going to guess you actually DELETED it. You need to DISABLE it otherwise it just gets discovered again after a restart
