### ISSUE TITLE
[BUG] Custom Radio Station Names inconsistently persisting across updates

### ISSUE THREAD

**Issue by starsoccer** [music-assistant/hass-music-assistant#1951]
### What version of Music Assistant has the issue?

2.0.0b103

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Inconsistently when updating Music Assistant custom names I have set for radio stations will be wiped and replaced with seemingly generic names. This causes automations which are relying on my custon names to break as well

### How to reproduce

Add a radio station with a custom name. Update Music Assistant. Name should be replaced with something generic

### Music Providers

Radio

### Player Providers

N/A

### What version of Home Assistant Core are your running

2024.2.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Ok thanks. We will have a look at this in due course.

**Comment by OzGav** [comment]
Also you used the word “inconsistently” in your title. Are you saying that some stations persist and some don’t or are you saying that sometimes after a restart the name resets and sometimes it doesn’t?

**Comment by starsoccer** [comment]
Sorry for being unclear. I am saying sometimes when I update music assistant it resets. I have not noticed it resetting purely from a restart/reboot. 

In case it helps at all, I basically have an automation that functions like a music alarm clock. It goes off at a set time every morning, says an announcement, and then starts to play a radio station. Example of the service call below

```
service: mass.play_media
data:
  media_type: radio
  media_id: STATION NAME HERE
target:
  device_id: DEVICE ID HERE
```

Ive only noticed this issue because I use a specific name for this one radio station and sometimes after I upgrade music assistant it stops working and nearly every time that has happened its due to the name being reset. I am not 100% sure if its the integration or the addon that is breaking it, but my guess is its the addon updates that break it but cant quite confirm.

**Comment by OzGav** [comment]
OK this will get looked at in due course

**Comment by marcelveldt** [comment]
b120 includes a fix so this should no longer happen (from now on) - so if you add a manual url with name and/or image, that info will stay in the db and not get overwritten by the streamscanner.

**Comment by starsoccer** [comment]
Awesome, thanks so much for fixing. I am closing this, but will reopen if it reoccurs.
