### ISSUE TITLE
Music starts automatically after having played a tts message

### ISSUE THREAD

**Issue by pmkruyen** [music-assistant/hass-music-assistant#1952]
### What version of Music Assistant has the issue?

2.0.0b103

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

* Song (album) from Spotify is played on Google Nest Speaker through / on MA
* Song (album) is paused or the speaker in MA is turned off.
* Through HA a tts message is being played on this Nest Mini Speaker
* Song (album) is unpaused and is played, but that is not what I want in this situation.

(I cannot seem to unload the song from the nest speaker

### How to reproduce

See above

### Music Providers

Spotify

### Player Providers

Only have Google Nest Minis (which all have this problem)

### Relevant log output

NA

### Additional information

Let me know if more info needs to be provided or if this is intended behaviour.

### What version of Home Assistant Core are your running

2024.2.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

ODROID

**Comment by OzGav** [comment]
You ticked the box saying you looked at the closed issues https://github.com/music-assistant/hass-music-assistant/issues/1853

**Comment by pmkruyen** [comment]
Sorry, missed this. 🫣 thanks for all the work!
