### ISSUE TITLE
Can´t initialize Music Assistant in Home Assistant

### ISSUE THREAD

**Issue by medienassi** [music-assistant/hass-music-assistant#1956]
### What version of Music Assistant has the issue?

can´t find

### What version of the Home Assistant Integration have you got installed?

2024.2.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

The Music Assistant integration found autmaticly the url of the running Music Assistant, but it´s not able to initialize the Music Assistant, No devices or Entities found.

Both running in Docker (Home Assistant and Music Assistant) on a Synology NAS. Both have access to the direcotories.
Music Assistant is running fine from the url

![_config_integrations_integration_mass(vn_desktop)](https://github.com/music-assistant/hass-music-assistant/assets/57039724/cd85ebad-c83e-4c1d-9dbe-2ff355c1b7c9)

### How to reproduce

I don´t know how, only tried to setup from Home Assistant Integration message.

### Music Providers

no problem with providers

### Player Providers

no problem with providers

### Relevant log output

Where do I find, sorry....

### What version of Home Assistant Core are your running

2024.1.5

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Alternative

**Comment by OzGav** [comment]
Try removing the integration from HA, remove it from HACS, restart HA, reinstall the integration.

**Comment by medienassi** [comment]
Hey, thanks, but I´ve tried this yesterday bevor my post, only to make sure

**Comment by OzGav** [comment]
Look in the HA logs. HA SETTINGS>>SYSTEM>>LOGS

**Comment by medienassi** [comment]
I´m so sorry, maybe I´m a little bit dumb, but I can´t find CORE at the Music Assistant Settings:

![_(vn_desktop)](https://github.com/music-assistant/hass-music-assistant/assets/57039724/19cb0304-b563-4235-8742-fb775de92b68)
![hacs_repository_476357279(vn_desktop)](https://github.com/music-assistant/hass-music-assistant/assets/57039724/86c32084-09df-4a6b-b06b-a67a92da6702)

And thats the only things I´ve found in the logs....

[music_assistant.client] Connected to Music Assistant Server 342056f551024acfad65992020edd9df using WebsocketsConnection, Version 2.0.0b39, Schema Version 22

"name_by_user":null,"name":"Music Assistant","serial_number":null,"sw_version":null,"via_device_id":null},{"area_id":null,"configuration_url":null,"config_entries":["48a5083818deee22cc9c52b0c92635be"],"connections":

**Comment by OzGav** [comment]
![image](https://github.com/music-assistant/hass-music-assistant/assets/19848947/040d741a-810b-4286-8402-24ca0f68af6f)

**Comment by medienassi** [comment]
interessting why is this missing?
![(vn_desktop) (1)](https://github.com/music-assistant/hass-music-assistant/assets/57039724/34cc5c7a-39e9-4b59-a374-0bd1be446418)

**Comment by OzGav** [comment]
@marcelveldt ?
