### ISSUE TITLE
Auto stop at track change

### ISSUE THREAD

**Issue by rVlad93** [music-assistant/hass-music-assistant#1964]
### What version of Music Assistant has the issue?

2.0.0b106 

### What version of the Home Assistant Integration have you got installed?

2024.2.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When clicking on another track in the playlist playback starts but stops after 8 seconds.

### How to reproduce

1. Start playlist
2. Click on another track
3. Playback starts but stops 8 seconds in

### Music Providers

YT Music

### Player Providers

AirPlay

### What version of Home Assistant Core are your running

2024.2.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by marcelveldt** [comment]
Can you provide a bit more info ? Does this happen every time or sometimes ?
What kind of airplay player is it ?
Can you inspect the log please what is logged there and share it here ?
Does this only happen with Youtube Music or also with other providers such as online radio ?

**Comment by rVlad93** [comment]
Not every time, no. It appears that this only happens first time I'm trying to change the track in a new playlist. 
The airplay player is a Sonos One. I tried it with yt music and local files and it does the same thing. I'll attach the log file as well.
[d5369777_music_assistant_beta_2024-02-29T03-34-19.195Z.log](https://github.com/music-assistant/hass-music-assistant/files/14442499/d5369777_music_assistant_beta_2024-02-29T03-34-19.195Z.log)

**Comment by drjjr2** [comment]
I have a similar problem with Airplay on Denon AVR-x4400h. I start the playlist, let it play a few tracks, then hit skip track and it turns off the Denon AVR-x4400h Airplay player.

**Comment by rVlad93** [comment]
It seems this was fixed in the last version. Thanks!
