### ISSUE TITLE
Mass browser-mod player for Iphone restarts song after certain time 

### ISSUE THREAD

**Issue by Wim-github** [music-assistant/hass-music-assistant#1966]
### What version of Music Assistant has the issue?

2.0.0b106

### What version of the Home Assistant Integration have you got installed?

2024.2.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When i play a /media file with only browser-mod/webbrowser After the first 90 seconds, mass starts again at the beginning, but now it stops after about 25 seoonds aan restarts again. This is repeated every 25-30 seconds

### How to reproduce

Install Browser-mod
Make browser-mod player on HA on Iphone
Add Home Assistant Mediaplayers to MASS
Select  browser-mod player Iphone in Home Assistant Mediaplayers
Select browser-mod Iphone player in MASS in PLAYERS
Enforce (lossy) mp3 stream 
play a song

### Music Providers

local disk, spotify

### Player Providers

browser-mod

### What version of Home Assistant Core are your running

2024.2.5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
You haven’t attached any logs?

**Comment by Wim-github** [comment]
What kind of logs do you want to have?Kind regardsWimOp 14 mrt 2024 om 23:35 heeft OzGav ***@***.***> het volgende geschreven:﻿
You haven’t attached any logs?

**Comment by OzGav** [comment]
The full logs from MA settimgs>> CORE. For the cleanest, restart MA, starting playing until it stops then download the logs then drag and drop the file into a reply here

**Comment by Wim-github** [comment]
Please find attached the logs that I made with version b111

The first one is a log  (log-music assistant  issue#1966.*) of the situation that MA restarts after a while. 

 

In this version it looks a little bit better. I.so of 90 sec, the music restart after more than 140 sec, and sometimes 180 sec.

I also see that the Music Assistant behaviour is not good predictable regarding the controls , like Volume and  connection with the player on the Iphone. 

 

The second part (log-music assistant  issue#1966 after reboot and no iphone connection*) is a situation where, after a reboot of home Assistant, the connection with the Iphone is showing an hour glass and I cannot play muic from MA on the Iphone.

 

In case you require additional info, please let me know

With kind regards,

Wim Hamers

 

Van: OzGav ***@***.***> 
Verzonden: donderdag 14 maart 2024 23:36
Aan: music-assistant/hass-music-assistant ***@***.***>
CC: Wim-github ***@***.***>; Author ***@***.***>
Onderwerp: Re: [music-assistant/hass-music-assistant] Mass browser-mod player for Iphone restarts song after certain time (Issue #1966)

 

You haven’t attached any logs?

**Comment by OzGav** [comment]
Unfortunately no logs were attached. As for the second point the hour glass just means MA cannot connect to the player

**Comment by Wim-github** [comment]
THanks for your fast response.

SOmething went wrong with my mail.

 

As for your remark: ‘As for the second point the hour glass just means MA cannot connect to the player’

I understand this, but with Browser-mod in HA it  is always to play the media files on my iphone.

So I wonder why what’s wrong. What is the difference on how browser-mod connects and hoe MA connects to the Iphone?

With kind regards

Wim

 

Van: ***@***.*** ***@***.***> 
Verzonden: zondag 17 maart 2024 22:31
Aan: 'music-assistant/hass-music-assistant' ***@***.***>
Onderwerp: RE: [music-assistant/hass-music-assistant] Mass browser-mod player for Iphone restarts song after certain time (Issue #1966)

 

Please find attached the logs that I made with version b111

The first one is a log  (log-music assistant  issue#1966.*) of the situation that MA restarts after a while. 

 

In this version it looks a little bit better. I.so of 90 sec, the music restart after more than 140 sec, and sometimes 180 sec.

I also see that the Music Assistant behaviour is not good predictable regarding the controls , like Volume and  connection with the player on the Iphone. 

 

The second part (log-music assistant  issue#1966 after reboot and no iphone connection*) is a situation where, after a reboot of home Assistant, the connection with the Iphone is showing an hour glass and I cannot play muic from MA on the Iphone.

 

In case you require additional info, please let me know

With kind regards,

Wim Hamers

 

Van: OzGav ***@***.*** ***@***.***> > 
Verzonden: donderdag 14 maart 2024 23:36
Aan: music-assistant/hass-music-assistant ***@***.*** ***@***.***> >
CC: Wim-github ***@***.*** ***@***.***> >; Author ***@***.*** ***@***.***> >
Onderwerp: Re: [music-assistant/hass-music-assistant] Mass browser-mod player for Iphone restarts song after certain time (Issue #1966)

 

You haven’t attached any logs?

**Comment by OzGav** [comment]
The difference would be that browser-mod is a custom component compared to the core players that are supported by HA. So we don't recommend its use an dinstead recommend using a snapcast server to play to any browser.

When you can get to your PC please upload those logs then

**Comment by Wim-github** [comment]
[log-music assistant  issue#1966 after reboot and no iphone connection.log](https://github.com/music-assistant/hass-music-assistant/files/14629334/log-music.assistant.issue.1966.after.reboot.and.no.iphone.connection.log)
![log-music assistant  issue#1966 after reboot and no iphone connection players hourglasses](https://github.com/music-assistant/hass-music-assistant/assets/60078325/66b4f5ac-29b3-407c-9750-e2ad67a54093)
![log-music assistant  issue#1966 players](https://github.com/music-assistant/hass-music-assistant/assets/60078325/aaee0375-5acb-458e-a7dc-40e8fd1e2c0e)
[log-music assistant  issue#1966.log](https://github.com/music-assistant/hass-music-assistant/files/14629335/log-music.assistant.issue.1966.log)

**Comment by Wim-github** [comment]
I have uploaded the files

 

Van: OzGav ***@***.***> 
Verzonden: maandag 18 maart 2024 00:41
Aan: music-assistant/hass-music-assistant ***@***.***>
CC: Wim-github ***@***.***>; Author ***@***.***>
Onderwerp: Re: [music-assistant/hass-music-assistant] Mass browser-mod player for Iphone restarts song after certain time (Issue #1966)

 

The difference would be that browser-mod is a custom component compared to the core players that are supported by HA. So we don't recommend its use an dinstead recommend using a snapcast server to play to any browser.

When you can get to your PC please upload those logs then

**Comment by Wim-github** [comment]
I think that the problem with a snapcast server is that you need to install it somewhere. I could do this on home assistant, but this is not possible within home assistent itself, as far as i know. Off course i could install it directly on the  OS cmdline with Pt-get, but i do not like to install outside home-assistant. And i need to have snapchat client on the iphone.
Browser-mod does not need addional installations. That is why i prefer this

**Comment by OzGav** [comment]
Fair enough. We are looking at bundling Snapcast with MA to resolve this. Not sure of an eta at the moment.

**Comment by Wim-github** [comment]
I just saw b115 with the snap server. How lucky i will be. I will try it

**Comment by OzGav** [comment]
Just don’t try and use the iOS snapclient app. It is broken.
