### ISSUE TITLE
Issue with repeat single track on Airplay

### ISSUE THREAD

**Issue by agdamsbo** [music-assistant/hass-music-assistant#1967]
### What version of Music Assistant has the issue?

2.0.0b106

### What version of the Home Assistant Integration have you got installed?

2024.2.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Playing to an Airplay speaker. I have some tracks in the queue playing. I then select a track, "play now", then in the player I select " repeat single track". Then the desired track will repeat on the speaker but the player/interface will show like it is continuing the queue. 
If I then pause the playback and press play again, the track shown in the interface and not the repeated track will play.

### How to reproduce

As above. The same on different speakers with airplay

### Music Providers

Spotify

### Player Providers

Airplay

### What version of Home Assistant Core are your running

2024.2.5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Is this still a problem? If so you need to ATTACH the full log file. Do NOT paste it.

**Comment by OzGav** [comment]
You said:

> then in the player I select " repeat single track"

Those words don't appear in the MA interface to my knowledge. Where are you seeing that?

**Comment by agdamsbo** [comment]
It is still an issue. Log attached. [log.txt](https://github.com/music-assistant/hass-music-assistant/files/14663600/log.txt)

The wording might not be perfectly accurate. I am on a translated instance. When I'm on the player queue, I select repeat from the three-dot drop down. It is the same behavior however, when activating repeat when clicking on the icon in MA or in the HA media_player interface.

The player I am testing on has some connection issues as well, discussed on [Discord](https://discord.com/channels/753947050995089438/1098864054023499889/1212766407624892468)

**Comment by OzGav** [comment]
OK I can recreate this using Airplay but not slimproto (picoreplayer) so it looks like an Airplay issue. It will get looked at in due course.

**Comment by marcelveldt** [comment]
It will still be an issue until its fixed, please be patient.

**Comment by agdamsbo** [comment]
No problem. I dont mind the wait, I just want to help out the bit I can. Keep up the steam!

**Comment by OzGav** [comment]
Please confirm is this is still an issue with b136

**Comment by agdamsbo** [comment]
Fantastic! Issue solved as far as I can tell.
