### ISSUE TITLE
Can't change Spotify Chromecast group via  automation or script.

### ISSUE THREAD

**Issue by starman2k01** [music-assistant/hass-music-assistant#1970]
### What version of Music Assistant has the issue?

2.0.0b106

### What version of the Home Assistant Integration have you got installed?

2024.2.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Once I start playing on a Chromecast group, I can't change target device nor entity. It always plays on the originally chosen group of speakers via automation or script.

### How to reproduce

- Start playing group via sidebar UI or automation. Change chromecast speaker via script execution or automation. Group restarts music on original speaker group.

### Music Providers

Spotify.

### Player Providers

Chromecast.

### What version of Home Assistant Core are your running

2024.2.5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Sorry this report isn’t clear at all.

> Once I start playing on a Chromecast group, I can't change target device nor entity.

Ok so you have a queue playing on the group. What do you mean you can’t change device. Change what device? In order to do what?

**Comment by starman2k01** [comment]
![MA1](https://github.com/music-assistant/hass-music-assistant/assets/66963945/644dfeae-15bd-4cbf-8312-3ca9e3a5d5dd)
![ma2](https://github.com/music-assistant/hass-music-assistant/assets/66963945/9708e2c3-a0a3-406c-b437-0f3c5a48fed9)
Target is defined clearly. You can't change the target.

**Comment by OzGav** [comment]
Ok so I understand you are talking about using the service tab inside the HA devtools. If you want to select a different target there then just press the little x beside “big inside”

**Comment by OzGav** [comment]
Has the above explained how this works?

**Comment by OzGav** [comment]
We will close this soon due to no followup

**Comment by starman2k01** [comment]
We aren't communicating so I'll let someone else identify this issue. Obviously I've changed the target that way. It doesn't start the new target. I can't explaining it any more basically than that.

**Comment by marcelveldt** [comment]
I have read the report 3 times and I also do not understand what is going on, sorry. Maybe create a small video to explain it ?

**Comment by OzGav** [comment]
I just tried this. Through the dev tools service tab I started playback on one speaker. I then pressed the little x beside that “target” and then selected another speaker and started playback. I then did the same thing with a Google speaker group. There is no problem with the HA service call or the MA integration.

Perhaps you have a problem with the player (target) that you are trying to change to.

**Comment by OzGav** [comment]
Closing due to no follow up. Feel free to contact us again if you need more help.
