### ISSUE TITLE
Now playing card has player name cutoff when it extends to a second line

### ISSUE THREAD

**Issue by OzGav** [music-assistant/hass-music-assistant#1972]
### What version of Music Assistant has the issue?

2.0.0.b106

### What version of the Home Assistant Integration have you got installed?

2024.2.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When the Player name extends to a second line the text is partially cutoff by the bottom of the card

![image](https://github.com/music-assistant/hass-music-assistant/assets/19848947/6ad0ca94-1a28-4163-b4d2-fecda0019c85)

### How to reproduce

Find a player with a long name and observe the Now Playing cards

### Music Providers

All

### Player Providers

Airplayer, Slimproto, Chromecast

### What version of Home Assistant Core are your running

2024.2.0

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by jozefKruszynski** [comment]
Yup, I also noticed this and have looked at it briefly. It happened after a recent refactor.

**Comment by OzGav** [comment]
Latest UI has a font size that seems to have fixed this
