### ISSUE TITLE
Mark spotify song as favorite

### ISSUE THREAD

**Issue by eric1905** [music-assistant/hass-music-assistant#1973]
### What version of Music Assistant has the issue?

2.0.0b106

### What version of the Home Assistant Integration have you got installed?

2024.2.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When I am showing the infos of a song in Music Assistant and press the heart button on the UI to mark it as favorite it is not marked as favorite in spotify.

### How to reproduce

Go to the infos of a song.
Klick on the heart button.
Check spotify in Android App or web UI of spotify.
It is still not marked as favorite

### Music Providers

Spotify

### Player Providers

Spotify

### What version of Home Assistant Core are your running

2024.2.5

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
> Go to the infos of a song.

What do you mean by this? Where are you finding this song? Is it in your library, is it on the global search page? Is the track actually on Spotify?

**Comment by OzGav** [comment]
We will close this soon due to no followup
