### ISSUE TITLE
Universal Group Player - playback not working

### ISSUE THREAD

**Issue by ChristianEvc** [music-assistant/hass-music-assistant#1989]
### What version of Music Assistant has the issue?

2.0.0b107

### What version of the Home Assistant Integration have you got installed?

2.0.0b107

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When I try to play music to a group (specifically in my case a snapcast device and a chromecast audio in the same group), I get an error like the below:

"2024-03-11 19:18:18.831 ERROR (MainThread) [music_assistant.webserver] [139871339617104] Error handling message: players/queue/play_media: unhandled errors in a TaskGroup (1 sub-exception)"

The chromecast plays it just fine, but the Snapcast does not. The Snapcast gives the following error:

"2024-03-11 18-24-53.312 [Error] (Server) Server::onMessageReceived JsonRequestException: {"error":{"code":-32603,"data":"Stream not found","message":"Internal error"},"id":980,"jsonrpc":"2.0"}, message: {"id":980,"jsonrpc":"2.0","method":"Group.SetStream","params":{"id":"128365df-afb0-8f64-3dcc-4ea9c8140cae","stream_id":"default"}}"

I've also tried with an AirPlay device (a Macbook Air M2) and the Chromecast, and that also fails, albeit silently. There are no errors, but the Macbook doesn't play anything.

### How to reproduce

Create a Universal Group Player.
Attempt to play to it.

### Music Providers

Spotify

### Player Providers

Snapcast
Chromecast
(AirPlay)

### Relevant log output

"2024-03-11 19:18:18.831 ERROR (MainThread) [music_assistant.webserver] [139871339617104] Error handling message: players/queue/play_media: unhandled errors in a TaskGroup (1 sub-exception)"

### Additional information

I'm running both Snapcast and Music Assistant via Home Assistant

### What version of Home Assistant Core are your running

2024.3.0

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by Alundran** [comment]
This seems like the same issue I'm having albeit I don't seem to have any errors. Upon upgrading to b107, my Universal Group Player doesn't play any media. If I play media to each individual player (SlimProto) then that continues to work. I've tried deleting and re-creating the group adding the two players but same issue - no media playing. I also tried just adding one player in the group but the same issue occurred.

**Comment by ChristianEvc** [comment]
Thanks @Alundran 
I’ll see if reverting solves it for me too.

**Comment by OzGav** [comment]
Please check if this is still an issue in b109

**Comment by Alundran** [comment]
Seems resolved for me (Slimproto players in a Universal Player Group).

**Comment by ChristianEvc** [comment]
Confirming this is fixed on my end too! Thank you so much @OzGav !
