### ISSUE TITLE
Can't exit Universal Group Playback

### ISSUE THREAD

**Issue by ChristianEvc** [music-assistant/hass-music-assistant#1990]
### What version of Music Assistant has the issue?

2.0.0b107

### What version of the Home Assistant Integration have you got installed?

2.0.0b107

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

After attempting to play to a Universal Group Player (this isn't working for me, I have a separate ticket open for this), I can't get the player to stop interacting with the group.

For example, after a restart of Music Assistant, I can stream music to either one of them with no issues. I can even play two separate audio streams to my snapcast satellite and my chromecast device at the same time with no issues. 

However, if I try to stream to the Universal Group Player that includes both of them, only the chromecast plays (again, separate ticket for this, so thats not the issue for this one). If I try to play something to the snapcast satellite after having attempted to play to the group, it just plays to the chromecast device, even if I specifically set "Play On" to the Snapcast device. Even if I turn off the chromecast, or even turn off the Universal Group Player, it still only streams to the chromecast no matter what.

### How to reproduce

See above

### Music Providers

Spotify

### Player Providers

Snapcast 
Chromecast

### What version of Home Assistant Core are your running

2024.3.0

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Do you have a different player you can trying grouping with the chromecast to see if this is a problem with Snapcast?

**Comment by OzGav** [comment]
Please check if this is still an issue in b109

**Comment by OzGav** [comment]
We will close this soon due to no followup

**Comment by ChristianEvc** [comment]
Confirming this is fixed with b109! Works as expected again. Thanks very much @OzGav
