### ISSUE TITLE
Song title shows as "Music Assistant" when playing on UPnP player (Cambridge Audio Evo 150)

### ISSUE THREAD

**Issue by SirJohnDoe** [music-assistant/hass-music-assistant#1991]
### What version of Music Assistant has the issue?

2.0.0b107

### What version of the Home Assistant Integration have you got installed?

2024.2.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

The song title is not displayed, instead my player shows "Music Assistant" where the title should be. The album title and artist are displayed correctly.

Looks like this: 
![20240311_195947](https://github.com/music-assistant/hass-music-assistant/assets/11654657/df3d6d00-8a2f-4158-a5b6-9980a7969b52)

### How to reproduce

Play anything on a UPnP player.

My hardware is an Cambridge Audio Evo 150 player. It supports both Casting and UPnP (including gapless) playback.

### Music Providers

Plex --> Plays, but doesn't show title.
Tidal --> Same thing

### Player Providers

UPnP --> Doesn't show title
Cast --> Shows title

### Additional information

It happens both when using the service in HA aswell as playing directly from the addon. I also use other UPnP players (Symfonium), it does not happen there.

In HA: the DLNA entity from my media player shows the media title correctly, the UPnP player entity created by MA as well. It shows the song title and none of the attributes show "Music Assistant". For some reason it does send "Music Assistant" title along, as the 'media_content_id:' from my DLNA player entity shows the following in VLC when I open it there:
![image](https://github.com/music-assistant/hass-music-assistant/assets/11654657/c1eb9d36-b0ee-4d3d-b4dd-3a760babecba)

My mediaplayer in HA:
![image](https://github.com/music-assistant/hass-music-assistant/assets/11654657/76a892bf-96e9-4c24-b654-143ee31b7039)

(default) DLNA entity of my mediaplayer:
![image](https://github.com/music-assistant/hass-music-assistant/assets/11654657/1c850a70-d05d-4be0-8364-b8393e216161)

UPnP player entity created by MA integration:
![image](https://github.com/music-assistant/hass-music-assistant/assets/11654657/a709df7f-fcff-484e-bc93-a52f8dcf7a80)

### What version of Home Assistant Core are your running

2024.3.0

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Windows

**Comment by marcelveldt** [comment]
This is actually a device specific issue. It somehow prefers the metadata in the file headers over the metadata that is explicitly sent over dlna. That is just wrong.

**Comment by SirJohnDoe** [comment]
> This is actually a device specific issue. It somehow prefers the metadata in the file headers over the metadata that is explicitly sent over dlna. That is just wrong.

Is there any chance you can leave it empty on the file? Or does it have a specific purpose? All the other fields, Artist/Album/Genre are empty and those are reported correctly.

**Comment by marcelveldt** [comment]
> Is there any chance you can leave it empty on the file? Or does it have a specific purpose? All the other fields, Artist/Album/Genre are empty and those are reported correctly.

It is there as fallback for if a device does not support metadata. 

I can leave it empty but I still find this very crappy from the device implementation-side. This is also actually the first time I hear this.

Keep an eye on the next update to test this without the default/fallback name in the stream file headings

**Comment by marcelveldt** [comment]
Please give the next beta 108 a try, should be available within now and 30 minutes.

**Comment by SirJohnDoe** [comment]
> Please give the next beta 108 a try, should be available within now and 30 minutes.

Yay, thanks! It's showing the song title now :)

![20240312_215503](https://github.com/music-assistant/hass-music-assistant/assets/11654657/a77e9006-78fc-4819-b63a-3f4cc9f1af73)
