### ISSUE TITLE
Duration is reported in (MA) UPnP entity, but not send to player (Cambridge Audio Evo 150)

### ISSUE THREAD

**Issue by SirJohnDoe** [music-assistant/hass-music-assistant#1992]
### What version of Music Assistant has the issue?

2.0.0b107

### What version of the Home Assistant Integration have you got installed?

2024.2.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Even though the UPnP player created by the MA integration in HA reports the 'media_duration', it is not send to the player. On the display it shows 0:00 as duration of the track:

![image](https://github.com/music-assistant/hass-music-assistant/assets/11654657/570073a2-17fd-4948-a72f-172f66019f31)

The entity created by the MA integration shows the duration:
![image](https://github.com/music-assistant/hass-music-assistant/assets/11654657/40138835-b3dc-4e74-946c-db73482285b2)

The default DLNA entity of my mediaplayer just reports 0:
![image](https://github.com/music-assistant/hass-music-assistant/assets/11654657/47b578d8-d281-4fd5-89c3-584fc857b9c2)

The mediaplayer entity of my player also reports 0:
![image](https://github.com/music-assistant/hass-music-assistant/assets/11654657/df9c0acc-6c47-48b0-8f0e-cbea7645f4d6)

With Symfonium (an Android player that supports Plex playback through UPnP) I do not have this issue, and the track duration is reported.

### How to reproduce

Play anything on a UPnP player.

My hardware is an Cambridge Audio Evo 150 player. It supports both Casting and UPnP (including gapless) playback.

### Music Providers

Plex --> Plays, but doesn't show duration.
Tidal --> Same thing

### Player Providers

UPnP --> Shows the position, but not the duration
Cast --> Doesn't show either position or duration, only the position is reported by the Cast entity from my media player. The cast entity created by MA does show the duration and position.

### What version of Home Assistant Core are your running

2024.3.0

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Windows

**Comment by marcelveldt** [comment]
Sorry, we can't help this. Yet another device specific issue with your device. DLNA is a shitty protocol, implemented in 999999 different ways by manufacturers who don't care about sticking to a standard. We send the metadata using the DIDL format and that works with most DLNA players we tested with but every once in a while some awkward issue pops up like this. If you can get a hold on the support department of this device that tells what device specific quirk or additional metadat is needed, I can fix it, otherwise we're out of luck. I may hope playback works well and its just a metadata issue ?

**Comment by SirJohnDoe** [comment]
I've send in a request to the support department of Cambridge Audio. Hopefully they'll share the documentation so this mystery can be resolved. Thanks for your reply.
