### ISSUE TITLE
Impossible to add album in a local playlist

### ISSUE THREAD

**Issue by michaeldufour** [music-assistant/hass-music-assistant#1994]
### What version of Music Assistant has the issue?

2.0.0b107

### What version of the Home Assistant Integration have you got installed?

2.0.0b107 

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When I try to add album in a local playlist, nothing apear in the local playlist

### How to reproduce

Click "Add Play list" on the album and select the local playlist
![Capture](https://github.com/music-assistant/hass-music-assistant/assets/102390800/ef3a7b71-ecb2-493e-a46f-66b4fe5da20c)
![Capture2](https://github.com/music-assistant/hass-music-assistant/assets/102390800/d3a1a98e-012b-4e2a-ba46-cbe1aa4cd00d)

### Music Providers

Files System
Youtube Music

### Player Providers

Chromecast

### Relevant log output

No error in the log

### What version of Home Assistant Core are your running

2024.3.0

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Please don’t casually tick the box to say you looked at the existing open issues https://github.com/music-assistant/hass-music-assistant/issues/1768
