### ISSUE TITLE
black screen

### ISSUE THREAD

**Issue by fax13** [music-assistant/hass-music-assistant#200]
after installing the latest version of may 2022 the application is not loading anymore.
"Error occurred loading configuration flow for integration mass: No module named 'aiofiles.ospath'
08:13:48 – (ERROR) config_entries.py
Setup failed for custom integration mass: Unable to import component: No module named 'aiofiles.ospath'
08:04:18 – (ERROR) setup.py"
this is the message i get
![image](https://user-images.githubusercontent.com/76689575/169465103-4e800a76-a686-4a74-8ede-55cba47b7130.png)

**Comment by marcelveldt** [comment]
How did you install ? HACS ? 
You're missing a component on your setup that should be there

**Comment by marcelveldt** [comment]
OK, I found the issue and it is with a dependency. You probably have "aiofiles" installed at version 0.7 and I've implemented some logic that depends on 0.8 but apparently while the minimum version is still pinned to 0.7.
I will change this so next release will include a fix for you.

**Comment by fax13** [comment]
thanks for the swift reply Marcel,
can i just past the zip file folder of the next release directly into the custom components folder?
i tried to uninstall but it doesn't work either and stays on "not loaded"

**Comment by marcelveldt** [comment]
Best to install with HACS to ensure you are notified about updates.
You should be able to install updates with HACS too when they arrive. 

I will provide a new version this evening (Dutch local time). If you want a solution now, you could try to log in to your HA machine and upgrade the aiofiles package: "pip install aiofiles==0.8.0" - after that reload the integration

**Comment by fax13** [comment]
i am patient and await your update because i am quit new with home assistant and not familiar yet with HA
