### ISSUE TITLE
Installation fails with latest version

### ISSUE THREAD

**Issue by niteguide** [music-assistant/hass-music-assistant#2012]
### What version of Music Assistant has the issue?

2024.3.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [x] Yes

### The problem

<img width="583" alt="Bildschirmfoto 2024-03-16 um 14 13 48" src="https://github.com/music-assistant/hass-music-assistant/assets/58639459/88e73b03-2973-4f52-b916-6512e4c98c24">

I had several problems with the latest MA install 111 (songs started up to 30 seconds after clicking the play-button ...) and decided to reinstall MA. So I deleted the integration and redownloaded it from HACS. Unfortunately I now get the error shown on the screenshot and I am kind of clueless where it comes from. 

### How to reproduce

New installation of MA. 

### Music Providers

- 

### Player Providers

- 

### What version of Home Assistant Core are your running

2024.3.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
As per the docs. Uninstall integration, uninstall from HACS, restart HA, reinstall. While you are there make sure the addon is running.

**Comment by OzGav** [comment]
Furthermore removing the integration does not remove “MA”

**Comment by niteguide** [comment]
oh my! add-on was not running! i clicked away too fast. 
will test if playback is back to normal now!
