### ISSUE TITLE
Can't login to Youtube Music

### ISSUE THREAD

**Issue by patienttruth** [music-assistant/hass-music-assistant#2013]
### What version of Music Assistant has the issue?

2.0.0b111

### What version of the Home Assistant Integration have you got installed?

2024.3.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

During the oath process I get to the page with "YouTube on TV wants to access your Google Account" and I click "allow".

Click Next > "Sorry, something went wrong there. Try again."

Click Next > Goes to Google account.

No authentication happens with MA.

### How to reproduce

Followed login process starting at add provider > Youtube Music within MA

### Music Providers

Youtube Music

### Player Providers

NA

### What version of Home Assistant Core are your running

2024.3.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
Have you tried different browsers?

**Comment by OzGav** [comment]
We will close this soon due to no followup

**Comment by patienttruth** [comment]
> Have you tried different browsers?

I hadn't, but thanks for the idea. I gotta remember to try that early as Libre Wolf does occasionally give some issues.

I just tried authentication from my phone and it was immediate. Thanks!
