### ISSUE TITLE
JellyFin provider is not verifying certificates, resulting in log spam

### ISSUE THREAD

**Issue by jurgenhaas** [music-assistant/hass-music-assistant#2025]
### What version of Music Assistant has the issue?

2.0.0b115

### What version of the Home Assistant Integration have you got installed?

2024.3.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

My music provider is JellyFin and all is working just fine in the frontend, but the docker logs are full of these:

```
2024-03-18 13:16:42.742 WARNING (MainThread) [py.warnings] /usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py:1103: InsecureRequestWarning: Unverified HTTPS request is being made to host 'media.myserver.de'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
```

That host is using a valid SSL certificate and the configuration is with `https://media.myserver.de`, so there must be some code that uses the urllib3 in a way that doesn't verify the SSL cert.

### How to reproduce

Not sure

### Music Providers

JellyFin

### Player Providers

Chromecast

### What version of Home Assistant Core are your running

2024.3.1

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
I recommend you remove the url for your server from the log above

**Comment by jurgenhaas** [comment]
That URL is made up, it's not real.

**Comment by OzGav** [comment]
Well its someones URL! Try it!

**Comment by jurgenhaas** [comment]
Interesting. The http port redirects to https, which then responds with a bad SSL certificate which is for webmail.my-server.de

So, nothing to worry about.

**Comment by jurgenhaas** [comment]
@marcelveldt sorry, this is not resolved. The usage of urllib in MA is still not verifying certificates. My logs are full of warnings as described above. Could you please reopen this issue?

**Comment by marcelveldt** [comment]
Sorry, I misread your last comment. Where you said nothing to worry about.

Anyways, looked into this a bit. We are not using urllib in MA at all (we're using aiohttp as we're an async project).
Its originating from the library used to connect to JellyFin. I think they should make some adjustments to tell urllib to verify.

https://github.com/jellyfin/jellyfin-apiclient-python

Their code is a bit hard to read as its barely typed, undocumented and without a clean way to tell how the connection is initiated but it looks like their idea was that when auth.ssl is True in the config, it should also set verify but that's as far as I can read it and I have no further clue.

Maybe the maintainer of the Jellyfin provider in MA can have a look and maybe create an issue report upstream ?
@lokiberra ?

**Comment by marcelveldt** [comment]
Marking as pinned issue because its a known issue (and I now see it more often in user logs) - Someone needs to fix this in that upstream jellyfin library.

**Comment by OzGav** [comment]
@lokiberra were you able to open an issue on the upstream library?

**Comment by marcelveldt** [comment]
Now that the PR is merged to switch Jellyfin to the new async library, this issue should be resolved.
Please test with the next update (2.0.8 or beta 2.1.0b7) which should be released within a couple of days.

**Comment by OzGav** [comment]
@jurgenhaas This should be fixed. Let us know if not.

**Comment by jurgenhaas** [comment]
@marcelveldt Thanks, I have noticed that already, waiting for 2.0.8 so that I can test.

**Comment by jurgenhaas** [comment]
Sorry, mentioned the wrong person. Correction: @OzGav Thanks, I have noticed that already, waiting for 2.0.8 so that I can test.

**Comment by OzGav** [comment]
Yes please check that it has been resolved.

**Comment by jurgenhaas** [comment]
That's what I did in my previous comment. It was to confirm that it IS resolved.
