### ISSUE TITLE
additional settings

### ISSUE THREAD

**Issue by fax13** [music-assistant/hass-music-assistant#203]
Hi guys,
as i am so happy to finally have a multi speaker player system that solves my multi room installation to be build.
After playing around with the integration i stumbled upon this missing option;

- selection option such as select single or select all mode. for example to create playlists 
- a select function to play a selected group of songs out of the play list or folder
is that possible in the future?

**Comment by marcelveldt** [comment]
1) You should be able to select multiple items by clicking on the image thumb (in list view only)
2) when you figured out 1, that is also already possible.

See below screenshots (sorry they're from my production/family setup and so in Dutch, but you get the point).
Btw I now spot some glitches in the UI that the checkboxes get lost. I will fix that. The functionality exists however.

![Schermafbeelding 2022-05-20 om 12 54 37](https://user-images.githubusercontent.com/6389780/169513580-4573951c-4792-4cb9-afe4-80a43b0fc780.png)


![Schermafbeelding 2022-05-20 om 12 55 05](https://user-images.githubusercontent.com/6389780/169513666-25cac20d-33e8-4a99-91bf-c9e8e3e7b02a.png)


![Schermafbeelding 2022-05-20 om 12 55 22](https://user-images.githubusercontent.com/6389780/169513717-8734c253-9662-4715-a3ca-b98233f8471c.png)

**Comment by fax13** [comment]
geen probleem met Nederlands hoor, ben zelf een Vlaming ;)
toch bedankt weerom voor de info. als het weer werkt ga ik dat direct testen.
en terzijde, wat is de stand voor de Alexa integratie?

**Comment by marcelveldt** [comment]
Sorry, back to English again for the fellow international Githubbers. I will add a Dutch channel on the discord server to talk Dutch there ;-)

Alexa integration can be followed here:
https://github.com/music-assistant/hass-music-assistant/issues/101

**Comment by fax13** [comment]
no problem, thanks

**Comment by fax13** [comment]
hi Marcel, i updated the application and all is back and running.
as you replied on my question of selecting multiple songs, now that i figured out and that works too.
when i have selected the songs i selected add to playlist  or create a new one is not working.
i can click on that button but nothing happends, it stays grey.
any tips?

**Comment by marcelveldt** [comment]
Sorry, missed this message and I just released a new version. I will take a look at it tomorrow. I did however fix the UI glitch

**Comment by fax13** [comment]
hi Marcel,
this popped up again after installingthe latest version.

Logger: homeassistant.setup
Source: setup.py:162
First occurred: 19:21:36 (1 occurrences)
Last logged: 19:21:36

Setup failed for custom integration mass: Unable to import component: No module named 'aiofiles.ospath'

**Comment by marcelveldt** [comment]
I'm afraid you have another custom integration that is messing with the aiofiles dependency...

**Comment by fax13** [comment]
I will try to figure it out by deleting historically

**Comment by fax13** [comment]
hi , it seems that organizr disturbed the situation. after removal all worked well at the moment
