### ISSUE TITLE
Stream stopped all of a sudden 

### ISSUE THREAD

**Issue by andreasbrett** [music-assistant/hass-music-assistant#2032]
### What version of Music Assistant has the issue?

2.0.0b116

### What version of the Home Assistant Integration have you got installed?

2024.3.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

After some time of flawless playing the stream stops on my hardware receiver. In MASS the stream is still playing. 

### How to reproduce

It happens from time to time but mostly after several minutes of playing an album. The below output was roughly after 20min of starting the album. 

### Music Providers

Tidal

### Player Providers

AirPlay

### Full log output

```
2024-03-19 22:32:14.785 WARNING (MainThread) [asyncio] child process pid 339 exit status already read:  will report returncode 255
2024-03-19 22:32:23.286 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 350, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp/_http_parser.pyx", line 557, in aiohttp._http_parser.HttpParser.feed_data aiohttp.http_exceptions.InvalidURLError: 400, message:
  Invalid char in url query:                                                              
    b'GET /imageproxy?pa\x07 HTTP/1.0'
```
                        ^

### What version of Home Assistant Core are your running

2024.3.1

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
Please actually read the troubleshooting page inthe docs and resubmit this meeting the requirements
