### ISSUE TITLE
Exception when playing track directly from Spotify using built-in Snapcast server

### ISSUE THREAD

**Issue by JeffersonBledsoe** [music-assistant/hass-music-assistant#2035]
### What version of Music Assistant has the issue?

2.0.0b116

### What version of the Home Assistant Integration have you got installed?

2024.3.3

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

After trying to play a track directly from Spotify, the snapcast server crashed with the below exception

### How to reproduce

.

### Music Providers

Spotify

### Player Providers

Snapcast

### Full log output

```
2024-03-20 18:51:48.579 WARNING (MainThread) [snapcast.control.server] could not send request
2024-03-20 18:51:48.595 ERROR (MainThread) [music_assistant] Error doing task: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/providers/snapcast/__init__.py", line 336, in _streamer
    writer.write(pcm_chunk)
  File "/usr/local/lib/python3.12/asyncio/streams.py", line 346, in write
    self._transport.write(data)
  File "uvloop/handles/stream.pyx", line 674, in uvloop.loop.UVStream.write
  File "uvloop/handles/handle.pyx", line 159, in uvloop.loop.UVHandle._ensure_alive
RuntimeError: unable to perform operation on <TCPTransport closed=True reading=False 0x7f78391850>; the handler is closed
```

[log.txt](https://github.com/music-assistant/hass-music-assistant/files/14696474/log.txt)

### What version of Home Assistant Core are your running

2024.3.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Please supply the full logs as requested in the issue template and ATTACH them

**Comment by marcelveldt** [comment]
The builtin snapserver will only work for MA audio sources. So MA will play the spotify content to the snapcast stream.

**Comment by JeffersonBledsoe** [comment]
@marcelveldt Sorry for not being clear in the issue, I was a little sleep deprived when filling this. I had an issue trying to play from the MA library version of a track, so I opened the Spotify version using the version switcher. Pressing play caused the above exception. I do have uvloop enabled as you can see

This was the only relevant part, but I'll see if I can reproduce this again and update with the full logs

**Comment by OzGav** [comment]
Please try again with b118

**Comment by marcelveldt** [comment]
This one can be fixed. We removed uvloop from the project completely as it was causing a lot of troubles (like this one)
