### ISSUE TITLE
V1.1.11: cosmetics issue again

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#204]
I just saw a variation on the cosmetic issue https://github.com/music-assistant/hass-music-assistant/issues/177 that is closed:
![image](https://user-images.githubusercontent.com/4363599/169566943-97f653fa-1f25-4ac2-a442-06a09fd495a1.jpeg)
The only difference is that now the secondary text is very long

**Comment by erkr** [comment]
Fix scheduled for 2022.6.3?

**Comment by erkr** [comment]
Still not fixed in 2022.6.10

**Comment by marcelveldt** [comment]
this is fixed in 2022.7
