### ISSUE TITLE
Unable to remove album from library

### ISSUE THREAD

**Issue by JeffersonBledsoe** [music-assistant/hass-music-assistant#2040]
### What version of Music Assistant has the issue?

2.0.0b117

### What version of the Home Assistant Integration have you got installed?

2024.3.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When trying to remove an album, the album fails to be removed and remains in my library.

May be related to https://github.com/music-assistant/hass-music-assistant/issues/1974

### How to reproduce

I already had  the album ["Liquid Swords - GZA](https://open.spotify.com/album/3k8xoyOXkGgZxUKgpmxz4P) in my library from liking it in Spotify and MA syncing it.

1. Visit the album in Music Assistant
2. Press the 'more' kebab menu and press 'Remove from library'

### Music Providers

Spotify

### Player Providers

N/A

### Full log output

Relevant execption from log
`2024-03-21 14:25:08.634 ERROR (MainThread) [music_assistant.webserver] Error handling message: music/library/remove_item: 400, message='Bad Request', url=URL('https://api.spotify.com/v1/me/albums')`

MA log
[log2.txt](https://github.com/music-assistant/hass-music-assistant/files/14696618/log2.txt)

Frontend command for removal:
```{
    "command": "music/library/remove_item",
    "message_id": 21,
    "args": {
        "media_type": "album",
        "library_item_id": "13"
    }
}```

### Additional information

_No response_

### What version of Home Assistant Core are your running

2024.3.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Marcel believes this is fixed. We will close this soon unless advised otherwise
