### ISSUE TITLE
Music Assistant Server doesn't load stored settings.json

### ISSUE THREAD

**Issue by kvj** [music-assistant/hass-music-assistant#2042]
### What version of Music Assistant has the issue?

2.0.0b112

### What version of the Home Assistant Integration have you got installed?

2024.3.4

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Music Assistant Server doesn't load previously stored settings.json.
The settings file name is incorrectly constructed on load: config folder name is prepended two times: once [here](https://github.com/music-assistant/server/blob/8d10f08a51009c52ec8060535b6da594aa39c179/music_assistant/server/controllers/config.py#L68) and second time [here](https://github.com/music-assistant/server/blob/8d10f08a51009c52ec8060535b6da594aa39c179/music_assistant/server/controllers/config.py#L671)

`def save()` doesn't have such issue as `self.filename` is being used as-is

### How to reproduce

Start `mass` using `-c` flag, stop it and start again. A new `settings.json` will be created and all previously configured providers will be gone

### Music Providers

local disk, spotify

### Player Providers

slimproto

### What version of Home Assistant Core are your running

2024.3.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Linux

**Comment by kvj** [comment]
Thanks for fixing.

I've played a bit with the code. It's environment dependent. Because of:

```python3
>>> import os
>>> assert "/data/file.json" == os.path.join("/data", "/data/file.json")
>>> assert "./data/./data/file.json" == os.path.join("./data", "./data/file.json")
```

That's why, if you use an absolute path to the config folder, you won't face it. but relative paths cause it. After the fix both types work

**Comment by marcelveldt** [comment]
Out of curiosity: Why are you running the server manually btw if you have Home Assistant OS ?

**Comment by kvj** [comment]
If possible, I stay away from debian-based docker images.

1Gb+ docker image vs. 200Mb venv folder makes a big difference.
Additionally, I run HA on Home Assistant Green and its hardware performance is already a stretch when running HA only, so anyway I now run Music Assistant on a more performant Linux server, some custom installation is required

**Comment by OzGav** [comment]
As a Marcel has indicated to you before, you are welcome to do custom builds and installs but we don’t have time to support it. Sorry.

**Comment by marcelveldt** [comment]
> If possible, I stay away from debian-based docker images.
> 
> 1Gb+ docker image vs. 200Mb venv folder makes a big difference. Additionally, I run HA on Home Assistant Green and its hardware performance is already a stretch when running HA only, so anyway I now run Music Assistant on a more performant Linux server, some custom installation is required

diskspace is just diskspace, which we have plenty nowadays. 
The MA add-on should run great on a green or pi 4, most people run it that way.

Keep in mind that we optimize all development for the docker image and your're not supposed to run it in a venv (or ask support for that setup), basically as that is not how its intended to run. We're very limited in capacity so we really can not support every itch.
