### ISSUE TITLE
Some radios don't work

### ISSUE THREAD

**Issue by freedomanonyme** [music-assistant/hass-music-assistant#2043]
### What version of Music Assistant has the issue?

2.0.0b117

### What version of the Home Assistant Integration have you got installed?

2024.3.4

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Some radios don't play. Tried on devices : Chromecast or HomePod. Nothing. An example is "Radio Canada ici première Quebec city, QC". The same radio from Tune-In works. I can also play the station outside Music Assistant with the link : https://rcavliveaudio.akamaized.net/hls/live/2006953/P-2QQUE0_QUE/master.m3u8

### How to reproduce

Go find the station from Canada and try to play.

### Music Providers

An example is "Radio Canada ici première Quebec city, QC". The same radio from Tune-In works. I can also play the station outside Music Assistant with the link : https://rcavliveaudio.akamaized.net/hls/live/2006953/P-2QQUE0_QUE/master.m3u8

### Player Providers

Chromecast audio and HomePod don't work.

### Full log output

[log.txt](https://github.com/music-assistant/hass-music-assistant/files/14711896/log.txt)

### What version of Home Assistant Core are your running

2024.3.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by marcelveldt** [comment]
Did you add this radio station manually in the frontend or did you look for it in in the radio browser or tune in provider ?

**Comment by freedomanonyme** [comment]
> Did you add this radio station manually in the frontend or did you look for it in in the radio browser or tune in provider ?

No, I added the radio from radio-browser. I tried manually with the URL and it doesn't work. It works from Tune-in or if a copy the link in the web browser. But now, I have more problem, since I made the last update (following this Issue #2031), nothing play (Spotify, radios, etc.).

**Comment by OzGav** [comment]
Try physically restarting the player devices.

**Comment by freedomanonyme** [comment]
Yes I restarted everything. I also updated Home assistant core to the last one this morning. Chromecast TV, Chromecast audio and Apple HomePod don't work. It weird.

**Comment by freedomanonyme** [comment]
I uninstalled Music Assistant and installed it back. Now Spotify works. Unfortunately, the present issue isn't revolved. The station and some others don't play.

**Comment by OzGav** [comment]
Yes that will get looked at in due course

**Comment by marcelveldt** [comment]
These are HLS-based radio stations, the new trend in radio streaming, basically coming from popular video streaming services such as Netflix. I'm implementing a fix to handle these stations in MA.

**Comment by marcelveldt** [comment]
This should be fixed in b120 (which will be released later today). I have tested 100s of radio streams and they all work now, even the shiny ones based on HLS

**Comment by KE55ARD** [comment]
How does one update to this once released? I had to install using docker...

**Comment by OzGav** [comment]
https://github.com/music-assistant/server/blob/main/docker-compose.example.yml

**Comment by freedomanonyme** [comment]
Hi! I Updated to b121 this morning. Tried with 2 stations and results : 

1. [Radio-Canada Musique](https://www.radio-browser.info/history/b7aefb22-0ab1-403d-950e-237773113269)

- URL Manually added from www.radio-browser.info : It works (wasn't before).
- Browsing to the station from MA : don't work (same as before); one difference : player shows time elapsed and wasn't before.
- Using Tune-In provider : it works (same as before).

2. [Radio Canada Première Quebec city](https://www.radio-browser.info/history/a920b1af-979f-4040-a154-f25e7dbf21b5)
 - URL Manually added from www.radio-browser.info : It works (wasn't before).
- Browsing to the station from MA : don't work (same as before); one difference : player shows time elapsed and wasn't before.
- Using Tune-In provider : doesn't work (was working before).

Note : All radios from tune-in worked before. Only Radio Canada premier Quebec City don't work now.

Tell me if you need more.

**Comment by freedomanonyme** [comment]
With b122 Radio-Browser, Tune-in and URL don't work.

**Comment by marcelveldt** [comment]
Can you please go to the MA settings --> Core tab --> Cache controller --> Press the clear cache button ?
And then try the radio stations again from Tune In and Radio Browser.

**Comment by freedomanonyme** [comment]
> Can you please go to the MA settings --> Core tab --> Cache controller --> Press the clear cache button ? And then try the radio stations again from Tune In and Radio Browser.

Unfortunately, no improvement.

**Comment by KE55ARD** [comment]
The radio stations which weren't working for me yesterday do now, but the process keeps crashing now, and I end up needing to restart the docker instance all the time.

**Comment by freedomanonyme** [comment]
Good job! Everything works with b124. I'm closing the case

**Comment by freedomanonyme** [comment]
Good job! Everything works with b124. I'm closing the case

**Comment by marcelveldt** [comment]
Great to hear, thanks for the patience and providing good details

**Comment by TobiasLe** [comment]
One stream that is still not working for me in 2.0.0b129 is: https://orf-live.ors-shoutcast.at/fm4-q2a
The same url works when I paste it in chrome.

**Comment by marcelveldt** [comment]
> One stream that is still not working for me in 2.0.0b129 is: https://orf-live.ors-shoutcast.at/fm4-q2a The same url works when I paste it in chrome.

TIP: Next time do not reply on a closed issue report!
I only discovered your message by accident. Just create your own issue report and refer to an existing one if you think its related,

Anyhow... This radio station should work in the next beta update.

**Comment by TobiasLe** [comment]
> Anyhow... This radio station should work in the next beta update.

Awesome, thank you!

**Comment by KE55ARD** [comment]
Apologies if this is annoying. But I just want to drop this here if anyone stumbles across this thread as I was having the original issue and switched to running the beta version which solved that problem.

However I then kept getting really frequent MASS server crashes requiring a restart of the docker container, and couldn't figure out how to actually update my docker instance.

So for anyone else stuck at this stage, I ended up stopping & removing the container entirely. And then removing the image too and reinstalling it to get it up to date to a version the worked.

Feel free to point out a proper way of updating a docker container as I assume there is one, but I'm pretty new to this so couldn't find it.

**Comment by Airfronze** [comment]
Same issue with me. Most radio stations work well, but with MacJingle (http://host6.cartwall.at:7200/;stream.nsv) no fun.
Tried to add it from Radio Browser, TuneIn and manually. No way to get it playing. In the TuneIn app the stream is working well. Any chance to help? Server version 2.1.0b1
