### ISSUE TITLE
Port dissappearing from the HA integration config

### ISSUE THREAD

**Issue by melwinek** [music-assistant/hass-music-assistant#2046]
### What version of Music Assistant has the issue?

2.0.0b118

### What version of the Home Assistant Integration have you got installed?

2024.3.4

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Addon HA does not reconnect after restarting the docker container.
![image](https://github.com/music-assistant/hass-music-assistant/assets/10649327/3c2ae1e2-c88e-4a0e-8c09-e8aca9f44e52)
:8095 is missing in the configuration, even though it was there.
![image](https://github.com/music-assistant/hass-music-assistant/assets/10649327/6598c16b-79b2-4719-bef5-189e60b1e0b7)
Then I add :8095 in the configuration and it starts working.
To test, I restart the container and the port disappears from the configuration again.
This is a repeatable error.

### How to reproduce

I described above

### Music Providers

Any

### Player Providers

Any

### Full log output

```
2024-03-22 09:21:01.764 DEBUG (MainThread) [music_assistant.client.connection] Received message:
WSMessage(type=<WSMsgType.TEXT: 1>, data='{"event":"application_shutdown","object_id":null,"data":null}', extra='')

2024-03-22 09:21:01.764 DEBUG (MainThread) [music_assistant.client] Received event: MassEvent(event=<EventType.SHUTDOWN: 'application_shutdown'>, object_id=None, data=None)
2024-03-22 09:21:01.766 DEBUG (MainThread) [music_assistant.client.connection] Closing client connection
2024-03-22 09:21:01.766 DEBUG (MainThread) [custom_components.mass] Disconnected from server. Reloading integration
2024-03-22 09:21:01.766 DEBUG (MainThread) [music_assistant.client.connection] Closing client connection
2024-03-22 09:21:01.767 DEBUG (MainThread) [music_assistant.client.connection] Trying to connect
2024-03-22 09:21:07.051 DEBUG (MainThread) [music_assistant.client.connection] Trying to connect
2024-03-22 09:21:15.760 DEBUG (MainThread) [music_assistant.client.connection] Trying to connect
2024-03-22 09:21:30.948 DEBUG (MainThread) [music_assistant.client.connection] Trying to connect
2024-03-22 09:21:30.957 DEBUG (MainThread) [music_assistant.client.connection] Received message:
WSMessage(type=<WSMsgType.TEXT: 1>, data='{"server_id":"cb8ebee3e2e04fadace521e904883457","server_version":"2.0.0b118","schema_version":24,"min_supported_schema_version":24,"base_url":"http://192.168.3.3","homeassistant_addon":false}', extra='')

2024-03-22 09:21:30.958 INFO (MainThread) [music_assistant.client] Connected to Music Assistant Server cb8ebee3e2e04fadace521e904883457 using WebsocketsConnection, Version 2.0.0b118, Schema Version 24
2024-03-22 09:21:30.959 DEBUG (MainThread) [music_assistant.client.connection] Publishing message:
{'args': {},
 'command': 'players/all',
 'message_id': 'd1aa183fae0049889d2acdb268eb51cd'}

2024-03-22 09:21:30.960 DEBUG (MainThread) [music_assistant.client.connection] Received message:
WSMessage(type=<WSMsgType.TEXT: 1>, data='{"message_id":"d1aa183fae0049889d2acdb268eb51cd","result":[{"player_id":"b8:27:eb:aa:35:03","provider":"slimproto","type":"player","name":"Salon","available":true,"powered":false,"device_info":{"model":"SqueezeLite","address":"192.168.3.30","manufacturer":"squeezeplay"},"supported_features":["power","sync","volume_set","pause","volume_mute","enqueue_next"],"elapsed_time":0.0,"elapsed_time_last_updated":1711095670.62466,"state":"idle","volume_level":94,"volume_muted":false,"group_childs":[],"active_source":"b8:27:eb:aa:35:03","current_item_id":null,"can_sync_with":[],"synced_to":null,"max_sample_rate":384000,"supports_24bit":true,"enabled_by_default":true,"enabled":true,"hidden":false,"group_volume":94,"display_name":"Salon","extra_data":{},"announcement_in_progress":false}]}', extra='')

2024-03-22 09:21:30.961 DEBUG (MainThread) [music_assistant.client.connection] Publishing message:
{'args': {},
 'command': 'players/queue/all',
 'message_id': '2e07885b552e4681b11b5d7f9ae420f4'}

2024-03-22 09:21:30.962 DEBUG (MainThread) [music_assistant.client.connection] Received message:
WSMessage(type=<WSMsgType.TEXT: 1>, data='{"message_id":"2e07885b552e4681b11b5d7f9ae420f4","result":[{"queue_id":"b8:27:eb:aa:35:03","active":false,"display_name":"Salon","available":true,"items":1,"shuffle_enabled":false,"repeat_mode":"off","current_index":0,"index_in_buffer":null,"elapsed_time":19.0,"elapsed_time_last_updated":1711093186.1107972,"state":"idle","current_item":null,"next_item":null,"radio_source":[],"flow_mode":false,"flow_mode_start_index":0}]}', extra='')

```

### What version of Home Assistant Core are your running

2024.3.1

### What type of installation are you running?

Home Assistant Core

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Can you please stop pasting in partial log entries and folllow the instructions to attach complete logs.

**Comment by melwinek** [comment]
Full logs from HA ???. What I pasted was from HA, not MA.

**Comment by OzGav** [comment]
Please don’t paste the logs. Just attach them.

**Comment by marcelveldt** [comment]
In this case its a HA-only issue. I don't (yet) need extra logs.

**Comment by melwinek** [comment]
This port disappears not only when the container is restarted. But also every several minutes :(
![image](https://github.com/music-assistant/hass-music-assistant/assets/10649327/3c30aec2-04f3-4609-b961-94bc349d2983)

**Comment by melwinek** [comment]
In version v2024.3.5 it still loses the port every few minutes and MA becomes unavailable from HA.

**Comment by melwinek** [comment]
I brutally changed line:
`base_url = discovery_info.properties["base_url"] + ":8095"`
In file:
`config_flow.py`
And the problem went away. But this is not a solution to the problem, just a temporary workaround.

**Comment by marcelveldt** [comment]
Did you setup your configuration correctly ?
In the MA config for the webserver, please make sure that all settings are done correctly, most important the publish address, as that is whats being broadcast over mdns to discover the server. If that info is incorrect it might explain your situation.

**Comment by marcelveldt** [comment]
So your hack fix confirms it: your base url is wrong in the MA config!

**Comment by OzGav** [comment]
We will close this soon as it appears to be an issue with the OPs configuration.

**Comment by melwinek** [comment]
@marcelveldt  You're right. Some time ago I removed the port from Base URL from "Web Server (frontend and api)", because when it was entered, sometimes after restarting the container it did not start correctly because there was a port conflict.
