### ISSUE TITLE
Seeking bar is broken in the frontend if cursor exceeds the bounds of the slider

### ISSUE THREAD

**Issue by PatrikTheDev** [music-assistant/hass-music-assistant#2050]
### What version of Music Assistant has the issue?

2.0.0b119

### What version of the Home Assistant Integration have you got installed?

2024.3.4

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When I try to use the seek bar in the music player, if my mouse cursor exceeds the bounds before letting go, nothing happens and the seek bar breaks until I drag it to another value. No server request gets made, nothing gets logged in neither the browser console nor server logs. This is especially a problem on mobile as you are way more likely to overshoot when you can't see the exact touch point.

### How to reproduce

Play a song, then try to seek the music to any point. This should work fine, now drag the seek bar "beyond 0" (just go outside the bounds), now the seek bar will break.

https://github.com/music-assistant/hass-music-assistant/assets/25883885/65c412f0-7ca5-48e1-b1d8-899b5d766607

### Music Providers

Issue happens regardless of music provider but I'm using Spotify and YouTube Music

### Player Providers

I'm seeing this issue when playing to an AirPlay device but I don't believe this is player-specific as no server request gets made from the frontend in the first place (as shown by the console)

### What version of Home Assistant Core are your running

2024.3.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by githrdw** [comment]
@marcelveldt this is caused by `@mouseup` in https://github.com/music-assistant/frontend/blob/2c4dd24a489bbed556f02d4f6407aca5168ba202/src/layouts/default/PlayerOSD/PlayerTimeline.vue#L38

The mouseup will never be called when the mouse is outside of the component.

Since Vuetify 3.2.0 there are these `@start` and `@end` events that can be used instead of mouseup/mousedown.
