### ISSUE TITLE
Heos by Marantz and Denon

### ISSUE THREAD

**Issue by chrismdann** [music-assistant/hass-music-assistant#206]
It doesn't appear to work with HEOS.

**Comment by marcelveldt** [comment]
What is not working ? Please define your steps...
Anything helpful in your logs that give me a clue ?

**Comment by marcelveldt** [comment]
I had a quick peek at the source code of the Heos integration in HA and that should theoretically work fine with Music Assistant. So it would really help if you provide a step for step walkthrough what you did and where it went wrong and if you see any errors somewhere.

**Comment by marcelveldt** [comment]
@chrismdann can you share some more info what is not working otherwise I'll have to close this report

**Comment by marcelveldt** [comment]
closed due to no response
