### ISSUE TITLE
Music Assistant Server just stops to respond.

### ISSUE THREAD

**Issue by M0uC0** [music-assistant/hass-music-assistant#2063]
### What version of Music Assistant has the issue?

 2.0.0b122

### What version of the Home Assistant Integration have you got installed?

2024.3.4

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Since the updates of last weekend (beta 120/121 and 122 don't know wich one) i haven't managed to listen to music in my system.
I start playing random picked music and after a few minutes server just stops responding.. i don't even get to finish the music.

No access from ingress.. No access from http://my_host:8095.. No access with companion app on windows...
If i check cpu usage on my server, its high.. and Mass server is responsible for the high cpu usage... if i restart the mass addon... cpu gets back to low values and i manage to acess mass interface again..
If i start to play another song.. after a shot while.. stops responding again.
Everything was fine till this last updates.. i used to get home from work.. start playing music in my home speakers and no problem whatsoever.. now i just can't hear anything..

Tried with google cast speaker.. tried with squeezlite speaker.. the same.

### How to reproduce

Just simply press play.. and wait.

### Music Providers

Filesystem (Local disk)

### Player Providers

Slimproto and Chromecast.
The only ones i have.

### Full log output

[log.txt](https://github.com/music-assistant/hass-music-assistant/files/14749686/log.txt)

### What version of Home Assistant Core are your running

2024.3.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by marcelveldt** [comment]
fixed in b123

**Comment by OzGav** [comment]
Please check with beta 24

**Comment by M0uC0** [comment]
updated remotely to the latest one (b124).
It appears to be working ok... cpu load normal.. and ui access ok.. just the sound was not tested because i'm not home.
as soon as i get home i'll see.

**Comment by M0uC0** [comment]
Problem solved. :)

**Comment by erkr** [comment]
Thanks for reporting back. Enjoy MA 😊
