### ISSUE TITLE
Cannot Load YouTube Music Playlist's Songs

### ISSUE THREAD

**Issue by BrilliantStanley** [music-assistant/hass-music-assistant#2066]
### What version of Music Assistant has the issue?

2.0.0b124

### What version of the Home Assistant Integration have you got installed?

 2024.3.4

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Unable to load public and private Youtube Music playlist's songs (return blank page). Used to work on server version (2.0.0b106). Have not tried to restore back to that version. 

Free youtube music account was used.

### How to reproduce

Search a public playlist and then clik on it.

### Music Providers

Youtube Music

### Player Providers

NIL

### Full log output

[log.txt](https://github.com/music-assistant/hass-music-assistant/files/14760616/log.txt)

### What version of Home Assistant Core are your running

2024.2.0

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

.ova

**Comment by OzGav** [comment]
Free accounts are not supported https://music-assistant.io/music-providers/youtube-music/
