### ISSUE TITLE
If addon repo is already installed, setup of the integration will fail

### ISSUE THREAD

**Issue by raman325** [music-assistant/hass-music-assistant#2076]
### What version of Music Assistant has the issue?

2.0.0b125

### What version of the Home Assistant Integration have you got installed?

2024.3.5

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

If you have already installed the Music Assistant repo for the addon store, and then you attempt to set up the integration and select use the official addon, it will try to install the MA repo, which will fail because it already exists

### How to reproduce

1. Manually add MA add-on repo to add-on store repo list
2. Set up integration
3. Check "use the addon" (I don't remember the details)
4. Click install/configure

### Music Providers

n/a

### Player Providers

n/a

### Additional information

config flow shows an unknown error. Logs show an uncaught exception here: https://github.com/music-assistant/hass-music-assistant/blob/main/custom_components/mass/config_flow.py#L313 when the command gets sent to the API

### What version of Home Assistant Core are your running

2024.4.0b0

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by marcelveldt** [comment]
Thanks for the catch Raman!

**Comment by marcelveldt** [comment]
This one was fixed a few versions back - forgot to update here
