### ISSUE TITLE
Soundcloud issue

### ISSUE THREAD

**Issue by collateral87** [music-assistant/hass-music-assistant#2077]
### What version of Music Assistant has the issue?

2.0.0b127

### What version of the Home Assistant Integration have you got installed?

2024.3.5

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Songs from soundcloud doesn't play any sound. Playback is starting but without Sound. I tried different players.

### How to reproduce

Play a track on any player with soundcloud

### Music Providers

Soundcloud

### Player Providers

All

### What version of Home Assistant Core are your running

2024.3.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
Try again with b128

**Comment by collateral87** [comment]
I tried it right a way, but still no sound.
Are there specific tests, that i can try after update?

**Comment by OzGav** [comment]
Clear the MA cache

**Comment by collateral87** [comment]
I tried this as well but it doesn't fix it.

**Comment by OzGav** [comment]
Does a different music provider work?

**Comment by collateral87** [comment]
Yes, i noticed this only on Soundcloud music provider

**Comment by collateral87** [comment]
b129 doesnt fixed it too

**Comment by OzGav** [comment]
@gieljnssns ?

**Comment by marcelveldt** [comment]
This issue is fixed in the next beta (beta 131)!

**Comment by collateral87** [comment]
Yes it's fixed but on my homeassistant i must enable "lossy mp3" in the player options, but then the track stops after 4 seconds (only on soundcloud). Can you fix this?

Thank you for your great support

**Comment by marcelveldt** [comment]
> Yes it's fixed but on my homeassistant player (esphome) i must enable "lossy mp3" in the player options, but then the track stops after 2- 5 seconds (only on soundcloud). Can you fix this?
> 
> Thank you for your great support

Please create a new issue for that and also mention (and test!) if this happens to all media sources and only to this player(type) or also others. Do notice that the esphome mediaplayer was never designed for actual music playback but mre for short audio clips or some low bandwidth radio streaming. If you want music player on ESP32 products, use squeezelite32 or snapcast firmware which are optimized for music playback.
