### ISSUE TITLE
Codec Settings missing

### ISSUE THREAD

**Issue by GaWr26** [music-assistant/hass-music-assistant#2088]
### What version of Music Assistant has the issue?

2.0.0b129

### What version of the Home Assistant Integration have you got installed?

2024.3.5

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

As TuneIn streams via Chromecast stutter I wanted to change Codec Settings. These are somehow gone. Is this a Bug or did the way of changing Codec Settings change?

### How to reproduce

Goto Settings -> Player -> select any Chromecast player or group -> No Codec Settings

### Music Providers

Any

### Player Providers

Chromecast 

### Additional information

I remember I had the Codec settings in a previous version

### What version of Home Assistant Core are your running

2024.3.3

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
As MA is designed with high quality playback in mind that option was removed. If your problem is bandwidth related then you need to improve your wifi coverage.
