### ISSUE TITLE
Cover not showed up if file has multiple covers

### ISSUE THREAD

**Issue by de666** [music-assistant/hass-music-assistant#2090]
### What version of Music Assistant has the issue?

2.2.0b129

### What version of the Home Assistant Integration have you got installed?

N.A.

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

If file has multiple covers (eg. front + back etc.) and not only the front one, the cover is shown as broken image icon in the web interface (as below).
![Screenshot 2024-04-04 140458](https://github.com/music-assistant/hass-music-assistant/assets/4525838/7320fca1-8200-4aec-9117-bf48f468a42e)

### How to reproduce

- embed two ore more covers to a music file
- refresh the library
- open the web UI at the correspinding artist
- look for the music file

### Music Providers

Filesystem (local)

### Player Providers

Chromecast

### Full log output

```
2024-04-04 12:04:45.760 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/metadata.py", line 375, in handle_imageproxy
    image_data = await self.get_thumbnail(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/metadata.py", line 355, in get_thumbnail
    thumbnail = await get_image_thumb(
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/helpers/images.py", line 55, in get_image_thumb
    return await asyncio.to_thread(_create_image)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/helpers/images.py", line 49, in _create_image
    img = Image.open(BytesIO(img_data))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/PIL/Image.py", line 3309, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f31f3fb38d0>

```

### What version of Home Assistant Core are your running

N.A.

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

**Comment by marcelveldt** [comment]
We will look into this. 

That said, its kind of a bad thing to embed multiple covers into the media file itself.
Better use a directory structure with the image files. Its common to only have the front cover embedded in the media file.

**Comment by de666** [comment]
>We will look into this.

Thankyou @marcelveldt 
> That said, its kind of a bad thing to embed multiple covers into the media file itself.

I agreed with you but in this case "kind of a bad thing" doesn't mean "forbidden"

>Better use a directory structure with the image files. Its common to only have the front cover embedded in the media file.

"common" doesn't mean "mandatory" and since the tagging system allows to do that, I think it has to be handled correctly, that's why I open the issue which, in my opinion, is a sort of bug (not a "serious" one obviously), not an enhancement.

**Comment by marcelveldt** [comment]
this one is fixed in beta 138

**Comment by OzGav** [comment]
@de666 please confirm this has been fixed.

**Comment by OzGav** [comment]
Closing due no further followup. Assuming fixed.
