### ISSUE TITLE
I can't remove MA

### ISSUE THREAD

**Issue by Friedi1970** [music-assistant/hass-music-assistant#2093]
### What version of Music Assistant has the issue?

2.0.0b*

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I want to get rid of MA, therefore I removed the integration first and from HACS afterwards and I thought it is done after reeboot.
Unfortunately it is not. Today I got an update message within the HA settings.
Please help!

### How to reproduce

No idea.

### Music Providers

none

### Player Providers

none

### Full log output

n/a

### What version of Home Assistant Core are your running

20243.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by marcelveldt** [comment]
Out of curiosity: Why do you "want to get rid of MA" ? 

Secondly: Normally the add-on should be uninstalled when uninstalling the integration but looks that in your situation the add-on got left behind. Go To HA settings --> Add-ons --> Music Assistant --> click remove.

**Comment by Friedi1970** [comment]
> Out of curiosity: Why do you "want to get rid of MA" ?
> 
The thing is that I am using Apple Music which is still not supported. Therefore it makes no sense to me 🤷‍♂️

> Secondly: Normally the add-on should be uninstalled when uninstalling the integration but looks that in your situation the add-on got left behind. Go To HA settings --> Add-ons --> Music Assistant --> click remove.

Thanks man! I wasn't aware about the add on 🙈

**Comment by marcelveldt** [comment]
Ah well, I heard some whispers that somebody is looking into Apple Music support so who knows we'll see you back soon ;-)
Glad you sorted it out.

**Comment by Friedi1970** [comment]
Be sure I'll be back as soon as this works :)
