### ISSUE TITLE
Album art not showing for Tidal tracks

### ISSUE THREAD

**Issue by drjjr2** [music-assistant/hass-music-assistant#2094]
### What version of Music Assistant has the issue?

2.0.0b130

### What version of the Home Assistant Integration have you got installed?

2024.3.5

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Artwork for several tracks is not showing in playlists nor when the track is playing.
Additionally artwork for the current track is also not showing up in the Home Assistant media player card.

The current state for the media player in HA shows "null" for the entity_picture_local attribute. When playing a Spotify track this 
attribute is the URL for the artwork.

### How to reproduce

Play Tidal track, artwork is not showing in MA and is notshowing in HA.

### Music Providers

Tidal

### Player Providers

DLNA, Airplay

### Full log output

No relevant logs. 

### What version of Home Assistant Core are your running

2024.3.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
This should be fixed in the next beta

**Comment by marcelveldt** [comment]
please test with beta 131, this should be fixed.

**Comment by drjjr2** [comment]
This does seem to be fixed. Do I need to reload Tidal to get artwork for tracks that don't currently have it loaded?

**Comment by OzGav** [comment]
Does the refresh button not help?

**Comment by drjjr2** [comment]
> Does the refresh button not help?

It didn't seem to. I ended up removing and reinstalling MA and then Tidal and now it seems happier. I see a lot of:
```
2024-04-06 08:37:41.159 WARNING (ThreadPoolExecutor-0_20) [tidalapi.request] HTTP error on 429
2024-04-06 08:37:41.159 INFO (ThreadPoolExecutor-0_20) [tidalapi.request] Got exception 429 Client Error: Too Many Requests for url: https://api.tidal.com/v1/albums/54266170?sessionId=19bd3eb7-23ae-4927-b816-49caf880559d&countryCode=US&limit=10000
2024-04-06 08:37:41.160 WARNING (MainThread) [music_assistant.providers.tidal] Skipping sync of item tidal--dVb6xkHa://track/54266195 - error details: album://54266170 not found on provider tidal--dVb6xkHa
```
Does it eventually sync those items on the periodic refreshes?

**Comment by OzGav** [comment]
Please ask your question either here or discord but not both

**Comment by drjjr2** [comment]
Understood.
