### ISSUE TITLE
[HA ADD-ON] The add-on starts on boot even with the option disabled

### ISSUE THREAD

**Issue by txitxo0** [music-assistant/hass-music-assistant#2096]
### What version of Music Assistant has the issue?

2.0.0b131

### What version of the Home Assistant Integration have you got installed?

2024.3.6

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

If you don't select the option "start on boot" on the add-on, and restart HA core or the whole host, the add-on starts anyway

### How to reproduce

If you don't select the option "start on boot" on the add-on, and restart HA core or the whole host, the add-on starts anyway

### Music Providers

no applicable

### Player Providers

no applicable

### Full log output

Nothing related in the supervisor...
2024-04-07 22:51:23.066 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/music-assistant/home-assistant-addon repository

### What version of Home Assistant Core are your running

2024.04.01

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by marcelveldt** [comment]
the add-on is managed by the integration (in fact while installing the integration you selected that option). if you disable the integration, it will also disable the add-on. Start on boot is required for the integration to operate, the integration depends on the add-on. A nice improvement on the HA-side would be if the "auto start" option would be disabled in this case.

**Comment by txitxo0** [comment]
Ahm, I got you. Okay!

So nothing to report in here.

I was having always the add-on started but my problem is about the port it is using (8095 and following in case of problems), in my installation apparently the 8095 is already in use so it is taking the 8096 which is though to be used by Emby/jellyfin. So, finally I have a lot of problems to get my installation ready to use after a reboot because I can not manually set the port in any of the add-on mentioned.

Thank you!

**Comment by Mr-HaleYa** [comment]
@txitxo0 If your issue is solved don't forget to close it
