### ISSUE TITLE
Tidal - Favorite Tracks - Sorting

### ISSUE THREAD

**Issue by danilichti** [music-assistant/hass-music-assistant#2098]
### What version of Music Assistant has the issue?

2024.4.1

### What version of the Home Assistant Integration have you got installed?

2024.4.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Favorited tracks in Tidal are not displayed in the correct order in Music Assistant. 

The standard sorting in Tidal is "Newest -> Oldest", whereas Music Assistant sorts them alphabetically.

### How to reproduce

1. Add Tidal
2. Check Favorite Tracks

### Music Providers

Tidal

### Player Providers

Sonos

### What version of Home Assistant Core are your running

2024.4.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
This seems to be personal preference vice an issue but see what @jozefKruszynski thinks.

**Comment by jozefKruszynski** [comment]
> This seems to be personal preference vice an issue but see what @jozefKruszynski thinks.

Definitely a personal preference thing here. We are in no way trying to emulate what each and every provider does or does not do, so I would suggest closing this.

Perhaps in future this could be a setting in MA if it isn't already, but we already respect the setting that is selected by the user on each page even after reload

**Comment by OzGav** [comment]
@danilichti you are welcome to open a feature request discussion and see how much traction that gets. Thanks for the idea.
