### ISSUE TITLE
Tidal provider initialization encounters 404 and 429 errors, does not later retry

### ISSUE THREAD

**Issue by drjjr2** [music-assistant/hass-music-assistant#2103]
### What version of Music Assistant has the issue?

2.0.0b133

### What version of the Home Assistant Integration have you got installed?

2024.3.6

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When Tidal loads for the first time it encounters 404 errors and later 429 errors (too many requests) for albums that do exist in Tidal. It doesn't look like there is ever another attempt to load the offending albums on subsequent syncs. If Tidal is throttling the requests then we somehow need to retry them later.

### How to reproduce

If already installed, delete Tidal provider. Wait for tracks, artists, playlists to clear.
Install Tidal provider
Errors in log for albums that do exist. For example, the first one in the attached log (album 574874) that generates the first 404 error can be found at [https://tidal.com/browse/album/574874](https://tidal.com/browse/album/574874)

### Music Providers

Tidal

### Player Providers

DLNA, Airplay

### Full log output

[ma-040824-2.txt](https://github.com/music-assistant/hass-music-assistant/files/14909938/ma-040824-2.txt)

### What version of Home Assistant Core are your running

2024.4.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
@jozefKruszynski

**Comment by jozefKruszynski** [comment]
Will look at it when I have time. Life is very much in the way of things at the moment

**Comment by jozefKruszynski** [comment]
@drjjr2 Are you using only a single provider instance for Tidal, also, do you have any other systems that may be making requests to Tidal at the same time as the sync is going on?

**Comment by drjjr2** [comment]
I only have Music Assistant connected to this account in Tidal. I do have some 2000+ track playlists so I'm wondering if we're just hammering the system trying to load all the tracks and artists.

**Comment by OzGav** [comment]
Some potential problems have been identified. Hopefully next beta will have some improvements

**Comment by marcelveldt** [comment]
b137 should already have improvements to do less loading - the handling of the 429 errors is still being worked on

**Comment by drjjr2** [comment]
Here is the log after updating to b137. Still some 404 errors...
[ma-04.16.2024.txt](https://github.com/music-assistant/hass-music-assistant/files/15003499/ma-04.16.2024.txt)

**Comment by OzGav** [comment]
@drjjr2 This should be fixed. Please confirm.

**Comment by OzGav** [comment]
Closing assuming fixed after no follow-up
