### ISSUE TITLE
Soundcloud + HA-Player + lossy mp3

### ISSUE THREAD

**Issue by collateral87** [music-assistant/hass-music-assistant#2104]
### What version of Music Assistant has the issue?

2.0.0b133

### What version of the Home Assistant Integration have you got installed?

2024.3.6

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

The combination Soundcloud + HA-Player + lossy mp3 results in 2-4 second of playing, then the player stops. When i resume it starts again from the beginning and after 2-4 seconds it stops again.

This affects only soundcloud and only ha-player provider

### How to reproduce

See above

### Music Providers

Soundcloud

### Player Providers

Homeassistant-Player

### Full log output

No logs

### What version of Home Assistant Core are your running

2024.4.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Linux

**Comment by marcelveldt** [comment]
What is the player on the HA side ?

**Comment by collateral87** [comment]
Its a ESPHome mediaplayer.
(I know that this is not ideal, but it is a voice assistant and so i cant run snapcast or squeezelite firmware on that thing)

Radio, Spotify, YT-Music works without any issues. Only soundcloud give me this strange result.

**Comment by marcelveldt** [comment]
Please re-test with beta134 released today, I made a small modification that should help players with small buffers.

**Comment by collateral87** [comment]
i cleared the cache and restarted the MA-Addon, delete and added soundcloud again, but no difference so far.
I made a video:

![11-04-_2024_00-04-28](https://github.com/music-assistant/hass-music-assistant/assets/97076257/10053c97-d62b-4b6b-835a-473f0041bf03)

**Comment by collateral87** [comment]
(on my Chromecast devices, this happens too. Airplay works)

**Comment by OzGav** [comment]
There is a chromecast issue in the lastest beta. Don't be confused by that with your original report

**Comment by marcelveldt** [comment]
This should be fixed in b136 - which will be released later today or tomorrow.

**Comment by collateral87** [comment]
You are the best. Keep up the good work

**Comment by OzGav** [comment]
b136 is released please confirm this is fixed.

**Comment by OzGav** [comment]
We will close this soon if there is no further followup

**Comment by collateral87** [comment]
I can confirm, that this issue is fixed.
You can close. Thank you
