### ISSUE TITLE
Snapcast group player volume not using the group volume as snapweb does

### ISSUE THREAD

**Issue by ronluna** [music-assistant/hass-music-assistant#2105]
### What version of Music Assistant has the issue?

2.0.0b133

### What version of the Home Assistant Integration have you got installed?

n/a

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Snapcast players volume works fine when being controlled individually but when a player group is created the slider volume of the group resets the volume level of all the members in the group and sets it to the volume the group volume is being set.

### How to reproduce

Create a snapcast player group and set each player at different volume levels then interact with the group's volume level. You will noticed that instead of averaging the volume level of the group it would simple reset al levels to whatever level the group has which differs of how the official group level for snapcast player behave.

### Music Providers

Spotify

### Player Providers

Snapcast players

### Full log output

The logs do not show anything relevant

### What version of Home Assistant Core are your running

n/a

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Alternative

**Comment by SantiagoSotoC** [comment]
I talked about it with @marcelveldt some time ago, I guess I didn't explain myself well. I tried to look for the cause, but so far I haven't found anything, neither in the supplier nor in Marcel's code. 

I'm going to take another look at it, luckily my family problems are over and I can dedicate some time to the project again.

**Comment by SantiagoSotoC** [comment]
I'm going to take a look at it, I've been away from the project for a while and there are several important changes in the provider, luckily the family problems are over and I can dedicate some time to the project again.

**Comment by OzGav** [comment]
If this isn't the same it is likely related https://github.com/music-assistant/hass-music-assistant/issues/2106

**Comment by ronluna** [comment]
and perhaps to this as well #2108

**Comment by ronluna** [comment]
Just trying to get an update on the bug @SantiagoSotoC

**Comment by OzGav** [comment]
@ronluna Updates will be provided when available

**Comment by SantiagoSotoC** [comment]
@marcelveldt , is there any change at the core level that has to do with the volume ? because in my last tests in the development version it seems to be solved.
