### ISSUE TITLE
Snapclient Player's volume level won't reflect the actual level

### ISSUE THREAD

**Issue by ronluna** [music-assistant/hass-music-assistant#2106]
### What version of Music Assistant has the issue?

2.0.0b133

### What version of the Home Assistant Integration have you got installed?

n/a

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

If volume levels are changed from within snapweb or any other interface, Music assistant does not show the new value causing confusion, this also happens from within Musica assistant and changing the volume level of any snapcast group player. 

### How to reproduce

Change the volume leve of any group player or change the volume level from within snapweb . 

### Music Providers

Spotify

### Player Providers

Snapcast

### Full log output

nothing in the log relevant.

### What version of Home Assistant Core are your running

n/a

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Alternative

**Comment by OzGav** [comment]
Again you are not providing enough information. Provide a step by step of what you are doing to get this behaviour. Its not clear if you are talking about grouped players, individual players or both? I have tried a grouped player and there are some problems there but we need you to be specific about the problem that you are observing.

**Comment by ronluna** [comment]
In the video it can be seen how after interacting with the group player volume bar does not update the players that are linked to it and viceversa.  this also happens when interacting with any other inteface (Snapweb) . If the volume is to any of the snapclients in snapweb, music assistant won't display the new levels unless the web interface is refreshed. 

https://github.com/music-assistant/hass-music-assistant/assets/9822111/5569bc43-76e1-4f03-abca-17a721d4b8fa

**Comment by OzGav** [comment]
This is hopefully fixed in the next update. Please advise if not.

**Comment by OzGav** [comment]
@ronluna we will close this soon assuming fixed
