### ISSUE TITLE
Blank snapclient settings in Music assistant  when multiple instances running on the same host 

### ISSUE THREAD

**Issue by ronluna** [music-assistant/hass-music-assistant#2108]
### What version of Music Assistant has the issue?

2.0.0b133

### What version of the Home Assistant Integration have you got installed?

n/a

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Music Assistant is unable to configure properly snapclients that are running  on the same host with different usb sound card and different hostID as well as instances id .

--hostID snapclient0 -i 0

Music assistant will only allow to configure the snapclient, all other client will show a blank page.

Screenshot of the first snapclient 
<img width="1043" alt="image" src="https://github.com/music-assistant/hass-music-assistant/assets/9822111/809b0db5-fc17-4b2a-bbe0-28bb222bcc56">

all other snapclient would show a blank page as shown below
<img width="1045" alt="image" src="https://github.com/music-assistant/hass-music-assistant/assets/9822111/f191fcef-d5bf-4b1b-8296-12fecf0678b3">

### How to reproduce

run more than one snapclient on any of your existing snapclients. It is required to set a unique instance id for  each client running on the same machine (using the -i argument)

### Music Providers

Spotify

### Player Providers

Snapcast

### Full log output

2024-04-09 22:20:49.980 ERROR (MainThread) [music_assistant.webserver] Error handling message: config/players/get: 'No config found for player id snapclient0'
2024-04-09 22:21:34.241 ERROR (MainThread) [music_assistant.webserver] Error handling message: config/players/get: 'No config found for player id snapclient7'

### What version of Home Assistant Core are your running

n/a

### What type of installation are you running?

Home Assistant Core

### On what type of hardware are you running?

Alternative

**Comment by OzGav** [comment]
Firstly why would you run multiple snap clients  on one device? Secondly, have you tried this with a separate snap server to ensure this is a MA issue as at the end of the day all that has been done is bundle the off the shelf snap server

**Comment by ronluna** [comment]
Snapcast server see the players just fine and the snapweb is able to properly configure them.

<img width="864" alt="image" src="https://github.com/music-assistant/hass-music-assistant/assets/9822111/1504d0f0-1e1b-48db-a4e6-72e2955533a4">

**Comment by OzGav** [comment]
@SantiagoSotoC

**Comment by marcelveldt** [comment]
we use the mac as player id so that is a challenge

**Comment by ronluna** [comment]
snapcast added --hostID and --instance flag for that precise reason. Hopefully there is a way for MA to use the instance id.

**Comment by SantiagoSotoC** [comment]
I've already started working on the problem, it's not going to be a quick fix. It doesn't require so many changes in Music Assistant, but in the python-snapcast library.

**Comment by SantiagoSotoC** [comment]
I think I have the problem identified, it's a problem with the frontend, snapserver uses the mac#id format for all clients where the id is different from 1 and only the mac for when it is equal to one, but http://localhost:8095/#/settings/editplayer/38:d5:7a:0f:3f:79  
return the same client as  
http://localhost:8095/#/settings/editplayer/38:d5:7a:0f:3f:79#2

@marcelveldt , can I fix this at provider level or is it a frontend issue?

**Comment by marcelveldt** [comment]
You should not be using # in a player id, so my suggestion would be that you change that to underscore or a dash.

**Comment by SantiagoSotoC** [comment]
@ronluna Theoretically it should be fixed in the latest BETA, thank you if you can test it.

**Comment by ronluna** [comment]
Hello @SantiagoSotoC , yes this indeed if working as expected on the latest beta.  Music Assisstant is able to properly configure each player settings. 

BTW, I know this is unrelated to this issue, but the snapcast player's group volume still misbehaving. any ideas ?

**Comment by SantiagoSotoC** [comment]
> Hello @SantiagoSotoC , yes this indeed if working as expected on the latest beta. Music Assisstant is able to properly configure each player settings.
> 
> BTW, I know this is unrelated to this issue, but the snapcast player's group volume still misbehaving. any ideas ?

Thanks for your quick reply, for the volume I have a solution on the way, but I am trying to fix it at the library level, as I understand it is a bug of theirs. I am waiting for your reply
