### ISSUE TITLE
Under Voltage Raspberry Pi 4

### ISSUE THREAD

**Issue by Joe-githubby** [music-assistant/hass-music-assistant#2109]
### What version of Music Assistant has the issue?

2.0.0b129

### What version of the Home Assistant Integration have you got installed?

2024.03.5

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When using MA, my Raspberry Pi reports under voltage.

### How to reproduce

Play music via MA to google home speaker. 

### Music Providers

All. 

### Player Providers

Google home speaker. 

### Full log output

401: Unauthorized

### Additional information

I have an SSD running home assistant on Raspberry Pi 4 

### What version of Home Assistant Core are your running

2024.4.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Sounds like you need a better power supply

**Comment by Joe-githubby** [comment]
I will try this and see from there. I will report back once tested to see if symptoms still persist after the change in power supply.

Thanks.

**Comment by OzGav** [comment]
The Pi 4 needs a 3A/15W supply

**Comment by Joe-githubby** [comment]
I am using exactly that, but not sure if perhaps the power supply is now bad due to its age. Replacing it with an official power supply.

**Comment by Joe-githubby** [comment]
Seems to be working perfectly now.

Sorry for opening the issue.

Truly an amazing piece of software that I didn't want to uninstall due to power usage.
