### ISSUE TITLE
Duplicate players in player selection

### ISSUE THREAD

**Issue by radinsky** [music-assistant/hass-music-assistant#2115]
### What version of Music Assistant has the issue?

2.0.0b135

### What version of the Home Assistant Integration have you got installed?

2024.3.6

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Duplicate media players in player selection

### How to reproduce

Open players list

### Music Providers

All

### Player Providers

All

### What version of Home Assistant Core are your running

2024.4.2

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by radinsky** [comment]
![image](https://github.com/music-assistant/hass-music-assistant/assets/4540268/f98c45b2-03b8-4104-af26-03fc6cd5a1ce)


![image](https://github.com/music-assistant/hass-music-assistant/assets/4540268/50d94fc7-2bdb-43ca-8265-8fe87af9d2a5)

**Comment by marcelveldt** [comment]
Kodi supports both DLNA and Airplay so I assume it got detected by both.
In MA settings --> Players, you can disable the ones you don't want. If you have any other airplay compatible speakers/players and you want to be able to sync them, choose airplay. Otherwise pick dlna.

**Comment by OzGav** [comment]
Please confirm Marcel's assessment is correct. We will close this soon if there is no further follow up.
