### ISSUE TITLE
TTS announcements crashes without volume adjustment

### ISSUE THREAD

**Issue by mondbaron** [music-assistant/hass-music-assistant#2116]
### What version of Music Assistant has the issue?

2.0.0b135

### What version of the Home Assistant Integration have you got installed?

2024.3.6

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Home Assistant TTS announcement on a Music Assistant device fail, if players volume strategy is set to "Do not adjust volume".
According to the debug log, the error occurs due to a NoneType cast.

### How to reproduce

- Set a player to "Do not adjust volume".
- Call a TTS service on the Music Assistant player entitiy in Home Assistant

### Music Providers

TTS on Home Assistant

### Player Providers

Home Assistant

### Full log output

```
2024-04-12 21:18:51.606 ERROR (MainThread) [music_assistant.webserver] Error handling message: CommandMessage(message_id='258817d64bfe412f87425a0e64458db1', command='players/cmd/play_announcement', args={'player_id': 'media_player.xxx', 'url': 'http://xxx:8123/api/tts_proxy/eaf108a9759b216f52344441f9252ab373b7ed09_de-de_-_picotts.mp3', 'use_pre_announce': None, 'volume_level': None})
  + Exception Group Traceback (most recent call last):
  |   File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/webserver.py", line 364, in _run_handler
  |     result = await result
  |              ^^^^^^^^^^^^
  |   File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/players.py", line 693, in play_announcement
  |     await self._play_announcement(player, announcement, volume_level)
  |   File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/players.py", line 1107, in _play_announcement
  |     async with asyncio.TaskGroup() as tg:
  |   File "/usr/local/lib/python3.12/asyncio/taskgroups.py", line 145, in __aexit__
  |     raise me from None
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/players.py", line 1119, in _play_announcement
    |     announcement_volume = self.get_announcement_volume(volume_player_id, volume_level)
    |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/players.py", line 865, in get_announcement_volume
    |     return int(volume_level)
    |            ^^^^^^^^^^^^^^^^^
    | TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
    +------------------------------------
```

### Additional information

Enabling the volume adjustment avoids the error, but is not a solution if one wants to control announcement volume in Home Assistant.

### What version of Home Assistant Core are your running

2024.4.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by marcelveldt** [comment]
Out of curiosity...
Why do you want to control the announcement volume from Home Assistant ?
This service provides an all-in one solution of pausing the music, playing the announcement and resuming (if needed).
You can even give your preferred volume level in the service call to override it if you want.

Anyways, the bug with the None volume has been fixed, so that is available in the next version.

**Comment by OzGav** [comment]
@mondbaron Please continue to ask questions regarding the way MA can be the one stop solution for controlling the players but I have just tested this and it works for me so we are closing.

**Comment by mondbaron** [comment]
Thanks for the lightning fast fix - this is such an amazing project!

@marcelveldt, sure, here the rationale:
I want to play the announcement at the exact same volume to wich the player is already set by previous Automations. In the logic of MA announcements, this can also be solved by setting relative adjustment to 0% with min 0 and max 100, but choosing the "no adjustment" just seemed to be the cleaner config - maybe I misunderstood it and missed a difference?
Also overwriting the the volume in the service call sounds like a very promising options, where I could improve the logic in some cases. Is this an additional parameter in the TTS service call? Can you kindly point me to the documentation of this!

@OzGav: Also thank you! I really like the simplicity of the MA announcement implementation and would love to make it my single solution for everything, too.

**Comment by OzGav** [comment]
Ok in your original post it sounds like you are setting the announcement volume with HA just before sending the TTS. With your clarification above you are doing things the optimal way I would think.
