### ISSUE TITLE
TTS Announcement plays (resumes) queue, even if player was not playing before

### ISSUE THREAD

**Issue by mondbaron** [music-assistant/hass-music-assistant#2117]
### What version of Music Assistant has the issue?

2.0.0b135

### What version of the Home Assistant Integration have you got installed?

2024.3.6

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Music Assistans resumes the queue and starts playing music after a TTS announcement from Home Assistant, even if the player was not playing music before. Announcements on "silent" devices are not possible that way.

### How to reproduce

- Stop playing music on a player
- Call TTS announcement service from Home Assistant on that player

### Music Providers

Spotify + Home Assistant TTS

### Player Providers

Home Assistant

### Additional information

Maybe related issue: sometimes announcements are looped or played twice.

### What version of Home Assistant Core are your running

2024.4.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by marcelveldt** [comment]
Sounds like a problem with the specific player - what kind of player is it exactly in HA that you mapped to MA ?
Is there no native player provider available for that player within MA ?

**Comment by OzGav** [comment]
I just tried this with a song paused on a Chromecast, picoreplayer and a HA player (Fully kiosk browser but using the HA plugin entity) and the music did not resume on any. Using beta 136. @mondbaron please try again with beta 136. If you still have a problem then provide a high level of detail in the steps to reproduce section.

**Comment by marcelveldt** [comment]
Yeah, same here, I tried several player combinations and that all worked.

**Comment by mondbaron** [comment]
Sure, I'll try with the beta 136. 

One additional information I can already add ist about the players I'm using:
- one is an ESPHome i2s media player
- the other is a local USB player I user over the HA VLC Add-On
Both are naively bound to HA, that's why I really appreciate the new integration of HA players.

Of course it might be, that those players trigger the resume, because of an badly implemented Announcement feature, but to be honest, I don't think they are that smart to query the next song from HA. But I'll share a more detailed procedure to reproduce and log files if applicable if the problem persists. I'm happy to take suggestions if I should try something specific.

**Comment by marcelveldt** [comment]
Ah those actually both players with very bad state feedback so I can assume that can induce some race conditions. Within a few days I'll create a testsetup here with both players to see what we can do to improve that

**Comment by Jab2870** [comment]
Hi,

I am experiencing similar behaviour.

MA Server: 2.1.0b2
HA Extension: 2024.5.1

If everything is paused initially, making the following service call in HASS:

```
service: mass.play_announcement
target:
  entity_id:
    - media_player.bedroom_alarm_3
    - media_player.kitchen
    - media_player.hall_tablet_2
data:
  url: https://my-hass-instance/local/doorbell.mp3
```

Will result in the announcement playing, but then music will resume, despite being paused before the announcement.

All players at the moment are snapcast.

**Comment by marcelveldt** [comment]
Please test this again with version 2.0.6 (or beta 2.1.0b5) as we had some fixes last couple of days.

**Comment by OzGav** [comment]
@mondbaron @Jab2870 Has this been resolved?

**Comment by Jab2870** [comment]
Hi, as discussed on discord, i don't think the snapcast server supports pausing any more
https://discord.com/channels/753947050995089438/1083643113484070953/1251205715230588930

**Comment by OzGav** [comment]
@Jab2870 How is that related to this issue?

**Comment by Jab2870** [comment]
> @Jab2870 How is that related to this issue?

The issue I experienced and noted here was that if music was paused, and I played an announcement, music would resume after the announcement. If I can no longer pause, I can't confirm if this is fixed or not

**Comment by OzGav** [comment]
@Jab2870 ok that is being looked at separately
