### ISSUE TITLE
[music_assistant.metadata] en-us is not a valid language

### ISSUE THREAD

**Issue by T3chArmy** [music-assistant/hass-music-assistant#2119]
### What version of Music Assistant has the issue?

2.0.0b136

### What version of the Home Assistant Integration have you got installed?

2024.3.6

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

music_assistant.metadata throws error for invalid language.

### How to reproduce

Each time the web UI is loaded this error is thrown.

### Music Providers

URL
YouTube Music
Filesystem
Radio Browser

### Player Providers

Slimproto
Chromecast

### Full log output

[log-041224.txt](https://github.com/music-assistant/hass-music-assistant/files/14965037/log-041224.txt)

### What version of Home Assistant Core are your running

2024.4.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by marcelveldt** [comment]
Thanks for reporting, just fixed this one. So next beta will no longer show this error.

**Comment by OzGav** [comment]
Still seeing this in b137

**Comment by T3chArmy** [comment]
This appears to be resolved in b138.

**Comment by OzGav** [comment]
Random people are reporting this again in b143

**Comment by SirJohnDoe** [comment]
I get "[music_assistant.metadata] en_nl is not a valid language"

**Comment by marcelveldt** [comment]
found another typo in the code, fixe din next beta (b145)

**Comment by OzGav** [comment]
Closing assumed fixed. Please advise if not.

**Comment by daizusikatabenai** [comment]
WARNING (MainThread) [music_assistant.metadata] ja_jp is not a valid language

**Comment by OzGav** [comment]
I will have a look at this but are you interested in translating? https://music-assistant.io/help/lokalise/

**Comment by daizusikatabenai** [comment]
thank you

**Comment by OzGav** [comment]
@daizusikatabenai The warning will be fixed in the next update although you won't get a Japanese translation as that has not  been contributed as yet
