### ISSUE TITLE
V1.1.14: corner case-queueing without players

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#212]
A real corner case: When all my players are unavailable (physically powered off), I can still add tracks to a queue, but that queue is not related to any player.

**Comment by marcelveldt** [comment]
It's not a bug but a feature. It's the surprise jukebox. It will be a surprise which player is later going to play those songs ;-)

I'll do some more testing with unavailable players.

**Comment by erkr** [comment]
surprise feature 🫠

**Comment by erkr** [comment]
Still little confusing for v1.1.19. Would be nice is actions like add to queue are disabled when not player is selected

**Comment by marcelveldt** [comment]
I think I fixed this but please test and let me know where I missed spots

**Comment by erkr** [comment]
I will check it

**Comment by erkr** [comment]
The original case is solved: When I restart HA, the play button is disabled as there are no players.
But as showed in the previous comment above, after powering off the players, the play button remains enabled and the behavior is unclear

**Comment by marcelveldt** [comment]
only the play button or more buttons ?

**Comment by erkr** [comment]
Not really sure what your question is. This is the same view when MA didn't see the players at start up:
![image](https://user-images.githubusercontent.com/4363599/180489418-1ed34d53-f427-4094-ad90-c55198b64b87.png)

As you can see, the blue play button is disabled now. I think the same should apply when all players became unavailable after starting MA

**Comment by marcelveldt** [comment]
What I meant was what places need something disabled but in the meanwhile I discovered myself and should have fixed them all. Play actions become disabled once there is no player available and available again once there's a player

**Comment by erkr** [comment]
I only noticed the blue play button behaving inconsistently

**Comment by marcelveldt** [comment]
Fix available in the 2022.7 release!
Please reopen (or create a new issue) if you still may experience issues. Thanks!

**Comment by erkr** [comment]
It's fixed👍
