### ISSUE TITLE
play_announcement: unhandled errors in a TaskGroup

### ISSUE THREAD

**Issue by T3chArmy** [music-assistant/hass-music-assistant#2120]
### What version of Music Assistant has the issue?

2.0.0b136

### What version of the Home Assistant Integration have you got installed?

2024.3.6

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

While streaming music to Chromecast Stereo Pair playing an announcement causes stream to stop unexpectedly. 

### How to reproduce

Couldn't get exact steps to reproduce, this appears to be due a socket failure trying to send a command to chromecast device. Likely causing an uncaught exception.

### Music Providers

YouTube Music

### Player Providers

Chromecast

### Full log output

[log-041224.txt](https://github.com/music-assistant/hass-music-assistant/files/14965072/log-041224.txt)

### What version of Home Assistant Core are your running

2024.4.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
@T3chArmy Can you please check this again with the latest addon beta and HA integration (2024.5.0)

**Comment by T3chArmy** [comment]
I will check this tomorrow!
