### ISSUE TITLE
Home Assistant Provider - Sonos does not show correct Play/Pause status. 

### ISSUE THREAD

**Issue by Herazio** [music-assistant/hass-music-assistant#2123]
### What version of Music Assistant has the issue?

2.0.0b136

### What version of the Home Assistant Integration have you got installed?

2024.3.6

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Since there is an issue if you use the Sonos provider in MA together with the Sonos integration in HA (both integrations try to listen on port 1400, which obviously doesn’t work) I have tried to add a workaround by adding my Sonos speakers from HA towards MA via the Home Assistant MediaPlayers provider. 

This works correctly. I see both of my devices. I can even play music on the Sonos speakers and MA will show the correct data together with the correct playing status. 

When I press “Pause” my speaker effectively pauses, however MA believes the speaker is still playing. I see the time of the track continuing to tick and I am unable to resume playback on the speaker. 

### How to reproduce

Use the HA Sonos integration to add your Sonos speakers to HA. 
In MA remove the sonos provider and add the Home Assistant MediaPlayers provider towards MA. 
Expose your Sonos speakers to MA. 
Play a song from a music provider. In my case “Spotify”. 
Pause the track. The music will stop playing and MA will not see that the track/speaker is paused. 
![IMG_1916](https://github.com/music-assistant/hass-music-assistant/assets/70535683/08e3985d-6194-4c08-913d-c53b4f51a93b)

### Music Providers

Spotify

### Player Providers

Home Assistant MediaPlayers. Tried initially with the Sonos provider. This does not work apparently when used in conjunction with the Sonos integration on HA. 

I did not try playing to group players. 

### What version of Home Assistant Core are your running

2024.4.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
I have edited your post to remove the pasted log. Please follow the instructions and ATTACH the log file.

You should always use a native MA player when one exists to get the optimum results. Why do you want to use the HA player?

**Comment by marcelveldt** [comment]
Using the HA provider towards Sonos speakers will most likely not work, we should even filter those out.

question a: What makes you think you can not use sonos in both HA and MA ?
question b: Why still use Sonos integration in HA while using MA ?

**Comment by Herazio** [comment]
Hey goodevening!

Sorry it could just be me of course and maybe I’m doing something wrong so in that case I truly apologize. Just want to help the product come along 😄

Well there’s a reason actually that I started using the HA provider. When I use the Sonos provider I see that my 2 speakers are indeed showing up but as disconnected even though they are effectively reachable on the network. 
What I noticed was that in the logs from MA I saw an error stating “Cannot bind to address 192.168.1.10:1400. Socket in use” meaning another service is already running on my HA server. When disabling the Sonos integration in HA I notice that effectively the binding works correctly. 

To answer your question B: I use some special services in HA to snapshot my speakers. For example when I let a doorbell sound go through my speakers. That allows me to restore the last state of my Sonos speakers towards what they were doing before the doorbell sound had rang. Perhaps MA has a similar feature. I’ll have a look in the documentation. Who knows. Maybe I’m just complaining about nothing 😅. 

Thanks for your feedback and wishing you a good evening, morning, day. Wherever you may be!

B

**Comment by OzGav** [comment]
The snapshot you are describing is exactly how MA works. You have discovered that you cannot use MA and the HA integration simultaneously. You need to choose one or the other.

**Comment by OzGav** [comment]
We will close this soon unless you can identify an actual issue with MA. Thanks.

**Comment by marcelveldt** [comment]
> Cannot bind to address 192.168.1.10:1400. Socket in use

It should be safe to ignore that error as we will bind to another address instead (at least that is how it should work) but still Sonos speakers do not like to receive too many requests so while running Sonos i both HA and MA at the same time might work I still do not recommend it because you will have all players duplicated and the speakers are hammered with duplicated connections. 

The Sonos provider in MA uses the same library under the hood as HA so it should not really matter, for music playback, we have loads of optimizations for Sonos in the MA code that are simply absent in the HA implementation, another reason to use the MA Sonos provider.
