### ISSUE TITLE
The volume is stuck and does not change on DLNA players

### ISSUE THREAD

**Issue by sp0ngeboobs** [music-assistant/hass-music-assistant#2127]
### What version of Music Assistant has the issue?

2.0.0b136

### What version of the Home Assistant Integration have you got installed?

2024.3.6

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

The sound level is displayed incorrectly.
1. When I change the sound in HA, the volume of the speakers changes, but the slider is stuck at one level. Also, the level in MA is stuck.
2. When I change the sound level in MA, then the slider remains in the right position, but when I load the page, the sound level is not correct, it is taken from HA.

as I understand MA always takes the sound level from HA player attributes ( volume_level: ) which are always at the same level. And if you set a level ( volume_level: ) in developer tools, it will be stuck at that level in the future.

### How to reproduce

try changing the sound level in HA and MA

### Music Providers

DLNA

### Player Providers

radio stream from URL
Soundcloud.

### Full log output

I am attaching the log, but there is nothing displayed about the sound level.
[log.txt](https://github.com/music-assistant/hass-music-assistant/files/14981510/log.txt)

### What version of Home Assistant Core are your running

2024.4.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Do you have other players that do work?

**Comment by OzGav** [comment]
Please adjust the title then to properly reflect that this is only a DLNA issue

**Comment by marcelveldt** [comment]
I am super confused. You say you are using DLNA players but you're talking about HA attributes ?
Which one is it, dlna player in MA or HA players ?

**Comment by OzGav** [comment]
If you are happy it is not MA then yes we will close
