### ISSUE TITLE
Home view not loading

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#2131]
### What version of Music Assistant has the issue?

2.0.0b136

### What version of the Home Assistant Integration have you got installed?

not installed

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

The home view doesn't properly  load. Restarting MA didn't help. I had this boring screen for minutes:
![image](https://github.com/music-assistant/hass-music-assistant/assets/4363599/a3fc3c62-dc32-4e51-a31d-1f2bf674beb1)

### How to reproduce

I only know it started after spotify got interrupted. But don't understand why a reload of MA doesn't fix it.
After a restart and choosing a radio station instaed of spotify , it took 5 minutes before the home page shortly loaded, and than the loading screen reappeared 

### Music Providers

Spotify, radio

### Player Providers

chromecast

### Full log output
I thinks the loading issue started after the errors during startup. But it can be unrelated:
[log.txt](https://github.com/music-assistant/hass-music-assistant/files/14997078/log.txt)

### What version of Home Assistant Core are your running

2024.4.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Try b137 Eric

**Comment by erkr** [comment]
a new one, Okidoki
