### ISSUE TITLE
Jellyfin integration is not receiving any tracks from the Jellyfin server

### ISSUE THREAD

**Issue by TastaturCrasher** [music-assistant/hass-music-assistant#2135]
### What version of Music Assistant has the issue?

2.0.0b137

### What version of the Home Assistant Integration have you got installed?

2024.3.6

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

The Jellyfin integration fails to load any tracks or albums from my Jellyfin instance.
The only things that are received by jellyfin are playlists (only the name of playlist and cover picture of the playlist)
But the playlist in MA is completely empty, no songs are shown and there is an infinite loading bar displayed.
If I search for tracks from my Jellyfin server, no results are displayed

My Jellyfin instance is running just fine and is able to provide the mentioned missing data in other 3rd party applications.
The Jellyfin server is reachable and pingable from my HA instance.

To resolve this problem, I did try the following:
- Restart my Jellyfin server
- Delete the Jellyfin provider and add it again
- Restart Home Assistant

### How to reproduce

Adding Jellyfin Media Server Library as a provider and fill in all appropriate login data (server IP, username, password)

### Music Providers

Not working:
- Jellyfin Media Server Library

Working fine and without any issues:
- Spotify

### Player Providers

-

### Full log output

[log.txt](https://github.com/music-assistant/hass-music-assistant/files/15014899/log.txt)

### What version of Home Assistant Core are your running

2024.4.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Alternative

**Comment by OzGav** [comment]
@TastaturCrasher are you the same as Swifty7640 on Discord?

**Comment by TastaturCrasher** [comment]
@OzGav No, sorry 😅

**Comment by OzGav** [comment]
@lokiberra second report

**Comment by marcelveldt** [comment]
Please test with b140 - I spotted some quick fixes base don the log reports, not sure if they actually work as I only have a very limited jellyfin test server installed.

**Comment by lokiberra** [comment]
@marcelveldt I tested you fix with a playlist track that I removed the 'Album' metadata (aka ITEM_KEY_ALBUM). It proceeded to add the track to the playlist without error. I will do a update to also handle if ITEM_KEY_ALBUM is missing, but the parent ID is not (ITEM_KEY_PARENT_ID). This should also be able to find the album of the track.

**Comment by OzGav** [comment]
@TastaturCrasher Can you please check with b147 and advise of any improvements or change in behaviour

**Comment by TastaturCrasher** [comment]
Tested with b147.
Currently I have two playlists created in Jellyfin. Only one of them now has the tracks showing up in Music Assistant.
But the tracks can not be played and the cover images are missing. (see screenshot below)
![image](https://github.com/music-assistant/hass-music-assistant/assets/66208999/f4d58cc2-c83f-4132-8f26-6d5e9457b195)

The other playlist comes with an error message 'Album Artist' and no tracks loaded.
No albums or tracks are showing up in the respective Music Assistant menus.
Log File Attached.
[log3.txt](https://github.com/music-assistant/hass-music-assistant/files/15252330/log3.txt)

**Comment by OzGav** [comment]
@lokiberra some more info

**Comment by lokiberra** [comment]
@TastaturCrasher Do you have no metadata for these tracks in Jellyfin? They should all have Artist tags if they have been correctly scraped and matched using Jellyfin. Otherwise Music Assistant will have to initially flag it as Various Artists.

**Comment by TastaturCrasher** [comment]
I just checked it and all the tracks do have an artist listed in their metadata. Not every artist may be set correctly as all tracks are converted YouTube videos and the metadata was set automatically, but I assume this shouldn't be a problem.

I loaded new tracks into Jellyfin yesterday, created a new playlist and reloaded everything from the Jellyfin provider in the Music Assistant settings (Synchronize now and Reload). Now all playlists show up correctly and all tracks are also loaded and can be played. In the playlists themselfes no cover images of the songs are showing up but in some areas they do. See the below screenshots.

Still all tracks are only accessible inside the playlists and don't show up in any other menu like artists, albuns or tracks.
This is now on **version 2.1.0b0** by the way.

![image](https://github.com/music-assistant/hass-music-assistant/assets/66208999/ba12fb64-5e75-4200-b118-7ce79de48548)
![image](https://github.com/music-assistant/hass-music-assistant/assets/66208999/5e98c409-ca6c-4373-9d77-d3d9c1783ffb)
![330846760-e04d2e81-1eb7-4c88-abd7-ecf9225550cc](https://github.com/music-assistant/hass-music-assistant/assets/66208999/de2be109-e20f-4c20-a694-5179ab9e4a8f)

**Comment by beankylla** [comment]
fun fact: with latest beta the scan of music takes 22h to complete and i only have ~1'000 songs in there (vs 1924 album found, so quite the gap)

**Comment by florian-asche** [comment]
> fun fact: with latest beta the scan of music takes 22h to complete and i only have ~1'000 songs in there (vs 1924 album found, so quite the gap)

Hi, can you give me some hint, how did you configure your jellyfin instance? Mine is not loading any music info.
Jellyfin 10.9.2
music assistant server 2.1.0b0, just updating to 2.1.0b1

I have an admin user just for musicassistant in jellyfin, pointed to jellyfin with port in the music-assistant configuration.

Why is it not working :/

**Comment by OzGav** [comment]
@lokiberra

**Comment by lokiberra** [comment]
@florian-asche @beankylla Could you provide logs to assess? The previous logs in this issue indicated and issue with metadata keys missing (ex. Artist) when MA was trying to parse a track. Logs would be helpful to see if it is the same issues or if there is another issue I can recreate to debug.

I have connect successfully with a 10.9.2 Jellyfin instance and had albums/artist/tracks/artist/playlists added. The user shouldn't matter as long as they have access to a 'Music' type of library. If your libraries are set up as another type they will be ignored. Has Jellyfin matched all your albums and added metadata using Musicbrainz or TheAudioDB? Do you files have correct tags and folder structures for Jellyfin to use when matching albums? Have you tried using the Home Assistant Jellyfin integration? Does it find all your albums and tracks? It also uses the Python API so it should be similar in functionality.

**Comment by OzGav** [comment]
I would assume if missing Artist is being reported then there is a tagging problem at the file level or a metadata problem at the Jellyfin level. Would you consider bypassing Jellyfin and just sharing the files with MA directly?

**Comment by TastaturCrasher** [comment]
I added some tracks via the local file system provider - no issues whatsoever.
Tracks show up in the tracks, the artist, and the album section. 
Also showing all the metadata in MA including the cover image.

**Comment by OzGav** [comment]
@TastaturCrasher does the post above help you?

**Comment by TastaturCrasher** [comment]
Nope, I use Jellyfin with an admin account and this option was already enabled all the time.

**Comment by florian-asche** [comment]
> MusicAssistant Version: 2.0.4 (installed using docker) Jellyfin Version: 10.9.2 (tested also with 10.8.3)
> 
> I'am using MusicAssistant with a specific non-Admin user for Jellyfin. The Jellyfin user wasn't able to stream any songs from MusicAssistant until I enabled "consent media download" for the user in the jellyfin server.
> 
> It seems like MusicAssistant is accessing the media provided by Jellyfin not as the other players (like Finamp, Gelli or Symfonium) so the user must have "media download" enabled.
> 
> I also found that a consequence of the way MusicAssistant consumes Jellyfin media is that jellyfin's scrobbler plug-ins (like last.fm or listenbrainz) don't report any song to the respective service.

how do you run your music-assistant? with docker-compose or homeassistant addon?

**Comment by beankylla** [comment]
> I would assume if missing Artist is being reported then there is a tagging problem at the file level or a metadata problem at the Jellyfin level. Would you consider bypassing Jellyfin and just sharing the files with MA directly?

hmmm i think if there is a solid jellyfin integration i would prefer that over sharing the files directly. It is the way i consume media so i hope in the future there will be sync in favorite songs etc,

Otherwise it's like maintaining 2 different databases ^^

**Comment by Jc2k** [comment]
Can anyone having problems try the latest beta? Obviously it's a beta, might eat your kitten, etc. Maybe try a second instance.

https://github.com/music-assistant/server/releases/tag/2.1.0b7

Quite a few changes have landed, and it fixed at least one case of "nothing synced" so far.

5000 tracks, 400 albums, sync in about 1 minute here when MA has an SSD and 10 minutes on 10 year old spinning rust (that's initial sync, updates are a minute).

**Comment by florian-asche** [comment]
I am not sure, but since the update of Jellyfin and MusicAssistant Beta it is working now ;)

**Comment by beankylla** [comment]
hmm  not sure for who it works or how it should work but it does not work for me.
i have v2.1.0b8 and when i click sync jellyfin provider it does not add the remaining songs.
For those with whom it worked how did you get it to work?

Best,

**Comment by Jc2k** [comment]
Can you start a new issue as it's likely a different issue.

Let me know if you see a message like "sync completed but with errors" in your logs. If you do, make sure you have debug logs turned on for the music controller and try to sync again. It should include the error if you do that correctly.

**Comment by florian-asche** [comment]
> hmm not sure for who it works or how it should work but it does not work for me. i have v2.1.0b8 and when i click sync jellyfin provider it does not add the remaining songs. For those with whom it worked how did you get it to work?
> 
> Best,

Yeah its best to make seperated issues. I have an idea. Ive seen a setting, for how often it should sync with jellyfin, and my default was every 5min. If your sync takes longer, not sure, how it will handle that. Maybe it stops and restart again. 

I synced 500+ Albums without issue. But it took a very long time. I am currently thinking about just buying a spotify account since all my songs i play often are there.

**Comment by Jc2k** [comment]
> Yeah it's best to make seperated issues. I have an idea. Ive seen a setting, for how often it should sync with jellyfin, and my default was every 5min. If your sync takes longer, not sure, how it will handle that. Maybe it stops and restart again. 

There is a lock to stop concurrent syncs.

> I synced 500+ Albums without issue. But it took a very long time. I am currently thinking about just buying a spotify account since all my songs i play often are there.

How slow? How many albums? How many artists and tracks? How fast was the 2nd sync?

I can pull 400 albums in a minute *over a vpn* if the MA db is on SSD (a 7 year old one at that). Even though my jellyfin instance is on spinning rust. It's much slower if the MA db is on a slow disk. Maybe 15-20 minutes. But then the follow up sync is fast.

There is still performance fruit on the table. I think I can squeeze a bit more speed out of jellyfin by doing prefetching pagination. And I haven't looked at db tuning yet.

**Comment by beankylla** [comment]
Hi 

I had to activate verbose to see this it would not show up on info logs:

is this a known issue?

2024-07-07 07:56:14.461 WARNING (MainThread) [music_assistant.music] Sync task for xx.com  completed with errors
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/music.py", line 700, in run_sync
    await provider.sync_library(media_types)
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/models/music_provider.py", line 396, in sync_library
    async for prov_item in self._get_library_gen(media_type):
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/providers/jellyfin/__init__.py", line 354, in get_library_tracks
    yield parse_track(self.logger, self.instance_id, self._client, track)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/providers/jellyfin/parsers.py", line 170, in parse_track
    content = jellyfin_track[ITEM_KEY_MEDIA_STREAMS][0][ITEM_KEY_MEDIA_CODEC]
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

**Comment by Jc2k** [comment]
As I said before it's best to start a new issue now. Multiple different errors ended up getting lumped together in this issue making things hard to track.

It sounds like you have one of more tracks without a list of MediaStream. I don't know whether that's a configuration issue (maybe a permission thing), a problem with the file formats (there's another ticket about ogg for example) or something else.

**Comment by beankylla** [comment]
you're right my apologies. New issue opened!
