### ISSUE TITLE
Radio station Now Playing clicks through to unrelated track

### ISSUE THREAD

**Issue by OzGav** [music-assistant/hass-music-assistant#2137]
### What version of Music Assistant has the issue?

2.0.0b137

### What version of the Home Assistant Integration have you got installed?

2024.3.6

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

In both full and mobile views when listening to a radio station the station name is shown in the Now Playing view. Clicking on the radio station name takes you to an unrelated track in the library. 

### How to reproduce

Play any radio station then click on station title in Now Playing view

![image](https://github.com/music-assistant/hass-music-assistant/assets/19848947/82cdfd90-e650-43bf-9301-f76f4c0d938d)

### Music Providers

Radio browser

### Player Providers

All

### Additional information

Suggested fix is to open the radio view if this is clicked?

### What version of Home Assistant Core are your running

2024.4.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by sprocket-9** [comment]
This bug is fixed once https://github.com/music-assistant/frontend/pull/458 goes in.  The stream title will also show below the station name.

**Comment by OzGav** [comment]
Love your work
