### ISSUE TITLE
CPU temp spikes pretty good when syncing every 3 hrs. x86 HAOS image on 2011 Mac Mini

### ISSUE THREAD

**Issue by ballakers** [music-assistant/hass-music-assistant#2138]
### What version of Music Assistant has the issue?

2.0.0b137

### What version of the Home Assistant Integration have you got installed?

2024.3.6

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

![Screen Shot 2024-04-18 at 20 38 17 PM](https://github.com/music-assistant/hass-music-assistant/assets/69597117/f3686fb4-238b-496d-aede-c2ee3b2f3aa3)
Installed Music assistant and when it syncs every 3 hrs the temp spikes quite a bit. Just an FYI and maybe a way to decrease this impact? For now I just set sync to the highest interval.  Not too concerned - just an Old i7 mac mini server running HAOS on SSD with 16GB ram.  Props to the project though - it is working great with airplay devices and HA network storage from a pi4 testing with OMV to get the music.  

### How to reproduce

3hrs to the second the temp spikes and that's what sync interval was set to.  (not sure the mega spikes - probably one was installing Music Assistant add-on and integration)

### Music Providers

All good. local files OMV network storage through HA network storage - using native HA media folder.

### Player Providers

All good

### Additional information

Seemed to spike with previous version also prior to latest upgrade of the integration. Thanks again for the hard work everyone!

### What version of Home Assistant Core are your running

2024.4.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Well it does take CPU time to do the sync particularly if you have a large library. I don’t see this as an issue

**Comment by ballakers** [comment]
maybe if I try and purge the files that cause errors in the log that may help too - 60gb of old music files. I just though 15celcius was a decent jump - this HA machine runs a lot of stuff and doesn't seem to change in temp so was another reason I brought it up.

Also forgot to clarify the pic Apr 14 is when I started using Music Assistant.

**Comment by OzGav** [comment]
60 GB is a lot. I would say what you are seeing is normal. But yes properly tagging all those files so MA is not going over all of them every time looking to see if they have been fixed will probably help.
