### ISSUE TITLE
Translation Request Music Assistant. Language: Serbian

### ISSUE THREAD

**Issue by PengBG** [music-assistant/hass-music-assistant#2139]
### New language

Serbian

### Additional remarks

Serbian language used in Serbia, Cyrillic alfabet

**Comment by jozefKruszynski** [comment]
Would this be correct?
<img width="304" alt="image" src="https://github.com/music-assistant/hass-music-assistant/assets/60214390/c84c3267-2982-4e32-826e-baddeb7b173d">

**Comment by jozefKruszynski** [comment]
These are the available options
<img width="471" alt="image" src="https://github.com/music-assistant/hass-music-assistant/assets/60214390/65be046a-64e7-48d6-9d24-cb28e9c51371">

**Comment by PengBG** [comment]
Serbian (sr) for this request since Cyrilic is default in Serbia. when I use tts in HA, I use (sr) for cyrilic input

**Comment by jozefKruszynski** [comment]
I added Serbian (sr)
https://app.lokalise.com/public/321419046440c0f2bba414.05634832/
