### ISSUE TITLE
Translation Request Music Assistant. Language: Serbian (Latin)

### ISSUE THREAD

**Issue by PengBG** [music-assistant/hass-music-assistant#2140]
### New language

Serbian (Latin)

### Additional remarks

Serbian language used in Serbia, Latin alfabet

**Comment by PengBG** [comment]
here language selection shoud be 
Serbian (Latin) (sr_Latn)

**Comment by jozefKruszynski** [comment]
Added Serbian (Latin) (srt_Latn)
https://app.lokalise.com/public/321419046440c0f2bba414.05634832/
