### ISSUE TITLE
Impossible to delete item in the Music Assistant playlist

### ISSUE THREAD

**Issue by michaeldufour** [music-assistant/hass-music-assistant#2141]
### What version of Music Assistant has the issue?

2.0.0b138

### What version of the Home Assistant Integration have you got installed?

 2024.3.6

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I open a Music Assistant playlist, I try to delete a track but it not disapear of the playlist.

![image](https://github.com/music-assistant/hass-music-assistant/assets/102390800/1b18b3c8-e48e-434c-98cd-569c42a40d44)

### How to reproduce

Click on a playlist 
Click on tree point of the track need to be deleted
Click Delete of playlist

### Music Providers

YTM and File System

### Player Providers

Chromecast

### Full log output

2024-04-19 09:32:49.824 ERROR (MainThread) [music_assistant.webserver] Error handling message: music/item_by_uri: ytmusic is not available
2024-04-19 09:33:19.194 ERROR (MainThread) [music_assistant] Error doing task: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/music_assistant/common/helpers/uri.py", line 67, in parse_uri
    raise KeyError
KeyError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/providers/filesystem_local/__init__.py", line 245, in migrate_playlists
    await self.mass.music.playlists.add_playlist_tracks(new_playlist.item_id, all_uris)
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/media/playlists.py", line 215, in add_playlist_tracks
    media_type, provider_instance_id_or_domain, item_id = await parse_uri(uri)
                                                          ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/common/helpers/uri.py", line 70, in parse_uri
    raise InvalidProviderURI(msg) from err
music_assistant.common.models.errors.InvalidProviderURI: Not a valid Music Assistant uri:

### What version of Home Assistant Core are your running

2024.4.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Why do you mention YTM? Is that where the track is originally from? Are there other tracks in the playlist? If so, can they be deleted?

**Comment by michaeldufour** [comment]
> Why do you mention YTM? Is that where the track is originally from? Are there other tracks in the playlist? If so, can they be deleted?

It's a YTM track and the log of error mentionne YTM.

I try with other YTM track and have the same issue

**Comment by OzGav** [comment]
I just tried myself and I was able to delete tracks although it was deleting the track AFTER the one I selected. Do your playlists have more than one track in them?

**Comment by michaeldufour** [comment]
> I just tried myself and I was able to delete tracks although it was deleting the track AFTER the one I selected. Do your playlists have more than one track in them?

Yes a lot

**Comment by OzGav** [comment]
Do you have any other providers to try. We would like to ‘now if this is a YTM music problem or something else

**Comment by michaeldufour** [comment]
> Do you have any other providers to try. We would like to ‘now if this is a YTM music problem or something else

I tried with file system and I have the same issue

**Comment by OzGav** [comment]
How are you creating the playlist?

**Comment by michaeldufour** [comment]
I added file system and YTM album in a playlist

![image](https://github.com/music-assistant/hass-music-assistant/assets/102390800/a36bd064-afe3-43dd-baf1-616aa889449e)

**Comment by michaeldufour** [comment]
I'm able to delete 3 track of 4 but the last impossible to delete

**Comment by OzGav** [comment]
Ok did you notice if it was actually deleting the track AFTER the one you selected?

**Comment by michaeldufour** [comment]
> Ok did you notice if it was actually deleting the track AFTER the one you selected?

Yes delete track after and at the end not able to delete the last track

**Comment by michaeldufour** [comment]
> Ok seems like two problems here. One when adding album to playlist and one when adding individual tracks same as this old issue (#1319 ) This will get looked at in due course. Thanks for he report.

You welcome :)

**Comment by OzGav** [comment]
@michaeldufour Can you try with beta 144 as this is now working fine for me?

**Comment by michaeldufour** [comment]
> @michaeldufour Can you try with beta 144 as this is now working fine for me?

Yes work fine for me.

Regards
