### ISSUE TITLE
The speakers keep cutting out during playback every so often

### ISSUE THREAD

**Issue by senderbell** [music-assistant/hass-music-assistant#2143]
### What version of Music Assistant has the issue?

2.0.0b138

### What version of the Home Assistant Integration have you got installed?

2024.3.6

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

During music playback, after a certain amount of time the speakers start cutting out. Sometimes it's one speaker for a few seconds, sometimes the other, and sometimes both at the same time. The problem appears after prolonged listening, for example after 30-40 minutes. The symptom is as if something is getting clogged.
The problem occurs in all versions from 2.0.0b134b onwards. The last good version was 2.0.0b133."

### How to reproduce

Start listen to music on chromecast group speakers.

### Music Providers

Spotify
TuneIn radio

### Player Providers

Chromecast speakers group (2x Google nest mini, 2x JBL Link, 1x Mi Speaker)
The group of speakers created in the Google Home app.

### Full log output

2024-04-20 11:14:32.474 WARNING (Thread-9) [pychromecast.socket_client] [Link(192.168.1.111):8009] Heartbeat timeout, resetting connection
2024-04-20 11:14:36.482 WARNING (Thread-10) [pychromecast.socket_client] [Speakers(192.168.1.111):32013] Heartbeat timeout, resetting connection
2024-04-20 11:15:02.502 ERROR (Thread-9) [pychromecast.socket_client] [Link(192.168.1.111):8009] Failed to connect to service MDNSServiceInfo(name='JBL-Link-Music-ebce566927442ff2cde66642731fd0b4._googlecast._tcp.local.'), retrying in 5.0s
2024-04-20 11:15:06.525 ERROR (Thread-10) [pychromecast.socket_client] [Speakers(192.168.1.111):32013] Failed to connect to service HostServiceInfo(host='192.168.1.111', port=32013), retrying in 5.0s

### What version of Home Assistant Core are your running

2024.4.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
Possibly related to this discussion https://github.com/orgs/music-assistant/discussions/2133#discussioncomment-9172899

**Comment by senderbell** [comment]
I'm not sure if it's the same issue. I don't have a problem with tracks repeating or too long a pause between tracks. In my case, the speakers cut out and become unavailable, then reconnect after a while.
Interestingly, it doesn't interrupt the entire track, just one or more speakers.
This problem does not occur at all in version b133."

However, there may be something to it generally with speaker groups created in Google Home, even though the symptoms may differ.

**Comment by marcelveldt** [comment]
Please re-test with beta140 as I may have found an actual cause for this, and its indeed related to cast groups.

**Comment by senderbell** [comment]
I tested it. It looks like everything is fine. I didn't notice any problems with playback. Thanks.
