### ISSUE TITLE
Search results are duplicated when typed fast

### ISSUE THREAD

**Issue by FreyrPL** [music-assistant/hass-music-assistant#2145]
### What version of Music Assistant has the issue?

2.0.0b139

### What version of the Home Assistant Integration have you got installed?

2024.4.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Search engine doesn't find all the results it should. Problem occured during past 3 weeks after one of recent updates. Already tried reinstalling. No luck.
Example.on screenshot. Missing result also has wrong icon but it's same file type as others and it is playable as track.

![Screenshot_2024-04-21-10-28-08-551_io homeassistant companion android](https://github.com/music-assistant/hass-music-assistant/assets/94012672/1e32a8bd-7496-41b8-b586-0ab2fd4ee919)
![Screenshot_2024-04-21-10-27-21-878_io homeassistant companion android](https://github.com/music-assistant/hass-music-assistant/assets/94012672/9f610ad7-7ff9-4b7c-b9c7-a625d8fce5b2)

### How to reproduce

Use search function

### Music Providers

Filesystem -remote share

### Player Providers

DLNA/Airoplay (onkyo)

### What version of Home Assistant Core are your running

2024.4.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Alternative

**Comment by OzGav** [comment]
It’s not clear from the images what the problem is. In the first image I see you are browsing and there are two files and one folder and it isn’t clear what is in that folder. Then in the second image there are two tracks? It is unlikely it is the search failing. Just look through the library and see if they are even in there.

**Comment by FreyrPL** [comment]
As i mentioned before-the icon is wrong. There are 3 files. No folders. This file with folder icon is not shown in search results but it can be played. This is just example. Problem applies to many files.

Screenshot fron android phone:
![Screenshot_2024-04-21-12-09-25-096_com mi android globalFileexplorer-edit](https://github.com/music-assistant/hass-music-assistant/assets/94012672/26b49155-3443-4c97-a2c7-96553131e72b)

**Comment by OzGav** [comment]
I know Marcel has said before the browse function has limitations. The real question is why the file isn’t in the library. The log should reveal why but typically the reason is tagging problems

**Comment by FreyrPL** [comment]
It worked perfectly fine until last 2-3 weeks. Unfortunately i don' know which update broke browsing and i i don't have 'working' backup. I'll add logs aflter i solving 401 error while downloading.

**Comment by OzGav** [comment]
You should not be worried about browsing. That is like a fallback option. The question is why the third track hasn’t been loaded into the library. What do you see if you go to Aronchupa in the Artist view?

**Comment by FreyrPL** [comment]
Im not worried :) Browsing works, but i need to remember exactly where is everything, because track search doesn't.

I'll check tagging ( done long ago with Picard) when i get access to PC

Track searching "Trombone":
![Uploading Screenshot_2024-04-21-14-24-23-785_io.homeassistant.companion.android.jpg…]()
After deleting 'e' from search above:
![Screenshot_2024-04-21-14-25-01-737_io homeassistant companion android](https://github.com/music-assistant/hass-music-assistant/assets/94012672/1b2d9214-97f7-44c3-85b8-14f41ed2cac4)

**Comment by OzGav** [comment]
So it looks like all of the tracks have been loaded into the library but there is some sort of linking problem as even though both Trombone tracks are there only one is linked to Aronchupa. Why you are seeing multiple when the full word is typed is also unusual. I assume you only see those two tracks until you type that last e?

**Comment by FreyrPL** [comment]
It's more complicated ;)
If i type slow, then there are just 2 results (ok)
If i type fast, then there are multiple...and if i scroll down, there is every track from library:

![Screenshot_2024-04-21-16-35-09-103_io homeassistant companion android](https://github.com/music-assistant/hass-music-assistant/assets/94012672/1fde4354-024c-4a17-a616-4caf025069e2)


, but if i go back and forth (search already typed in), there are just two results.
Weird...

**Comment by OzGav** [comment]
Yeah sounds like a frontend bug although I don’t see it. Does it happen only on your phone?

**Comment by FreyrPL** [comment]
Same on chrome (win11 pc).
One more observation on pc. When i type slowly:
"Trom" - 2 results
"Tromb" - 2 results
"Trombo" - no results
"Trombon" - 2 results
"Trombone" - 2 results
Same everytime. With "o" at the end -no results 

Fast/slow typing is related with animated progress bar. If it finishes searching before next character is typed - no multiplication in results.

**Comment by OzGav** [comment]
Ok we will try and reproduce this or will come back and ask for more info.

**Comment by OzGav** [comment]
OK I see the issue when typing quickly. Would it be fair to say the title of this should be changed to "Search results are duplicated when typed fast"?

**Comment by FreyrPL** [comment]
No problem. And with update b140 missing results are gone. To be fair, i did run picard again on all the music i have and it did a lot of changes to tags, but files missed in results were not touched. They appear correctly in Track Search.

@ edit 
Nothing happens after A. Typing second character gives results. (Update b140)

**Comment by OzGav** [comment]
OK so I will change the title as the issue of duplicated results when typing fast I can reproduce. 

Interesting that nothing happens for you when you type an A. I experience a loop refrsh problem then. But if I type a B then I dod get results so not sure why you don't see any with A.... Confirming we are talking about in this search box 
![image](https://github.com/music-assistant/hass-music-assistant/assets/19848947/44f67d30-d000-4cba-a775-bb4cc6e9a49a)

**Comment by FreyrPL** [comment]
Same search. Global.
I wasn't patient enough. At first, nothing happens. Then i get results. Then everything disappears. Like on screenshot.
![Screenshot_2024-04-23-07-32-48-179_io homeassistant companion android](https://github.com/music-assistant/hass-music-assistant/assets/94012672/44fb9cce-a456-4472-b11f-425c3f7f6838)

**Comment by OzGav** [comment]
Interesting. We are digressing from your original problem but is the screen constantly refreshing or is it just sitting there blank? And it looks like you can’t type anything else now? Maybe check the logs to see if there is an error

**Comment by FreyrPL** [comment]
As i mentioned before, on update b140 i can't reproduce missing results, so the true, original problem seems gone.

Screen is blank. No, i can't type anything.

In the meantime mass updated to b141 and the problem with global search is gone.
Multiplication is also gone, but there is still all the library below results
![Screenshot_2024-04-23-08-08-55-680_io homeassistant companion android](https://github.com/music-assistant/hass-music-assistant/assets/94012672/ffc52553-5839-4094-9a39-5608a26ce056)
![Screenshot_2024-04-23-08-06-32-147_io homeassistant companion android](https://github.com/music-assistant/hass-music-assistant/assets/94012672/104beefd-8932-444a-bbc3-0cbb24fdce4b)

**Comment by OzGav** [comment]
Because of the frontend bug with typing in the search field, type in Aron then remove the n and then add it again (or type slowly). See if you only get results for that now?

**Comment by FreyrPL** [comment]
Upd b141

After removing n, and retyping it, i only get results for that, what i was searching for.

**Comment by OzGav** [comment]
OK would you agree that there are no problems with the search function rather it is a frontend bug with the speed that the text is typed?

**Comment by marcelveldt** [comment]
this one can be closed ? all good now ?

**Comment by FreyrPL** [comment]
On ver. 0b142 seems ok.

**Comment by OzGav** [comment]
Unfortunately I am still seeing this
![image](https://github.com/music-assistant/hass-music-assistant/assets/19848947/d312b167-3b03-4775-9ba2-25d8a0df9596)

![image](https://github.com/music-assistant/hass-music-assistant/assets/19848947/8b30eb3f-0116-4ddb-9ffd-3dc8cf5052d6)

**Comment by OzGav** [comment]
In beta 144 this seems ok!
