### ISSUE TITLE
Issues playing from Quboz

### ISSUE THREAD

**Issue by milkplus27** [music-assistant/hass-music-assistant#2147]
### What version of Music Assistant has the issue?

2.0.0b139

### What version of the Home Assistant Integration have you got installed?

2024.4.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Having a weird issue since the latest update (2.0.0b139). Not sure if it's specifically related to Qobuz, but that's the only provider I use, hence posting here 🙂

Firstly, the icon to switch between what's in my Library and whats available in Qobuz has disappeared. You can still click where the icon normally is, you just can't see it.

But then when you do click and, for instance, choose one of the Qobuz albums - it does not load any tracks and you can't play anything. 

Albums from Qobuz that are already saved to my favorites seem to be working ok.

Rolled back to 2.0.0b138 and the problem is gone.

![Screenshot_20240421-071232](https://github.com/music-assistant/hass-music-assistant/assets/20435315/82fb54d4-4aae-4be7-a26d-8d6244abeaad)
![Screenshot_20240421-070929](https://github.com/music-assistant/hass-music-assistant/assets/20435315/816cfffd-1383-4451-8ad5-3b527eade872)

Adding screenshots for reference

### How to reproduce

Update to 2.0.0b139, try to play an album from Qobuz that it's already favorited. No dice.

### Music Providers

Qobuz

### Player Providers

Sonos, UPnP

### What version of Home Assistant Core are your running

2024.4.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by marcelveldt** [comment]
Issue confirmed - I'm looking into it.

**Comment by marcelveldt** [comment]
should be fixed in b140/b141 !

**Comment by OzGav** [comment]
@milkplus27 please confirm this has been fixed

**Comment by milkplus27** [comment]
Yes, that seems to have cleared it up. Also, nice new interface. I dig it.
