### ISSUE TITLE
Feature Request: Limit initial Albums, Tracks view and or options.

### ISSUE THREAD

**Issue by darrenblanchard** [music-assistant/hass-music-assistant#215]
I have a very large library, when opening the track list it tries to Query all the tracks, I would be fine with either a setting or limiting the results to the top 1000, anything beyond that I would be using search to locate anyway, I'm not suggesting creating routines to enable forward and backwards a page at a time through results, I'm suggested a hard limit of 1000 returned results

This is the same for Artist, and Albums 1000 results max would be fine.

Having the ability to include or view hidden database entries in the views would be nice as well as including the "in database" field in the view.

Thanks, Keep up the great work.

**Comment by marcelveldt** [comment]
Uhm, why do you have so many favorited artists if you're only interested in 1000 of them ?
Maybe I'm missing the point here but the "Library Artists" (or albums and tracks) are there for you to just have an overlook of those artists, albums, tracks that you're really following, ALL OTHER should not be library artists but just items you can reach through search, playlists etc.

I made a major change yesterday to the way stuff gets loaded into the frontend which might be of your interest.
Please give version 1.1.4 a testdrive if that works better for you. All library items are still cached into the browser (allowing you to quickly search it) but it's loaded upfront and kept up to date.

Implementing a hard limit is not something I would ever consider ad a viable solution. What if the one artist you want to browse today is at position 1001?

I'd rather work with you in exploring the underlying usecases and make that work.


> Having the ability to include or view hidden database entries in the views would be nice as well as including the "in database" field in the view.

You can already do that. That's where the "heart" button/icon is for, to add/remove items from your library.
Whether that is stored in a database is completely irrelevant ;-)

Please note that I'm still working on the global search functionality. More ideal would be that you can search all items (boh offline and online) from the home screen.

**Comment by darrenblanchard** [comment]
I'm running 1.1.14 I think tonight I will delete database and let it rebuild because of the changes, if you have a 15 being released to address the artist missing i may wait until then too. I think my brain block may be the distinction between favorite and "In Library", i get when you select music from a streaming service i.e. spotify it's a favorite, when i scan my filesystem provider they are all "in Library" by default, so my cards for artist (350), albums (3700) and titles (40,000) are huge, I have almost 40,000 titles after the filesystem scan that are available in the tile views without me doing anything. This makes loading the Titles tile very cumbersome for me because it's trying to display all 40K. For my particular library displaying the titles when the tile comes us is not helpful as I would always be doing a search anyway, My experience so far is if the item isn't selected as being in library the search will not find it.

Not to add work but is there a database maintenance that will remove items from the library/playlist if they are no longer accessible in disk for filesystem provider? I had some M3U files i removed from my music share and they still appear in the playlist.

**Comment by marcelveldt** [comment]
- .15 will be released within an hour or so, including the artists fix.

- Yes, files on disk are always imported as "library" items but I could make that a preference. In that case it works the same as the streaming providers. You can browse all items and favorite the ones you like most yourself.

- Like I said, I need to optimize the tiles listings for large collections. I advice you to use the lists view instead. It is optimized to display up to a million entries fast and responsive.

- Items removed from disk should be removed automatically from the library. Do note that scans are only ran at startup and every 3 hours.

**Comment by darrenblanchard** [comment]
OK I'll wait for 15 delete database and restart to test

On May 22, 2022 4:18 PM, Marcel van der Veldt ***@***.***> wrote:

  *   .15 will be released within an hour or so, including the artists fix.

  *   Yes, files on disk are always imported as "library" items but I could make that a preference. In that case it works the same as the streaming providers. You can browse all items and favorite the ones you like most yourself.

  *   Like I said, I need to optimize the tiles listings for large collections. I advice you to use the lists view instead. It is optimized to display up to a million entries fast and responsive.

  *   Items removed from disk should be removed automatically from the library. Do note that scans are only ran at startup and every 3 hours.
