### ISSUE TITLE
Today Upgrade

### ISSUE THREAD

**Issue by sborja** [music-assistant/hass-music-assistant#2154]
### What version of Music Assistant has the issue?

2,0,0b140

### What version of the Home Assistant Integration have you got installed?

2024.4.3

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

The New versión has a bug within speakers selection. This Windows remain freezed and dont hide after press to the cross and the speakers doesnt expand to select volume and group speakers.

### How to reproduce

Installing New version

### Music Providers

No music provider error

### Player Providers

No player problems

### What version of Home Assistant Core are your running

2024.2.0

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by marcelveldt** [comment]
confirmed issue, an update of vue (our frontend framework) broke our UI. We'll release a patch soon

**Comment by marcelveldt** [comment]
b141 released with a patch for the broken frontend
