### ISSUE TITLE
Media player attributes are missing stream_title: in HA

### ISSUE THREAD

**Issue by OzGav** [music-assistant/hass-music-assistant#2157]
### Discussed in https://github.com/orgs/music-assistant/discussions/2156

<div type='discussions-op-text'>

<sup>Originally posted by **sp0ngeboobs** April 24, 2024</sup>
after b139, the "stream_title:" attribute, which contained the name of the track when I was listening to radio streams, disappeared in the attributes of media players.</div>

**Comment by erkr** [comment]
@sp0ngeboobs thanks confirming!
