### ISSUE TITLE
Jellyfin provider requires a password

### ISSUE THREAD

**Issue by IAmTheMilkManMyMilkIsDelicious** [music-assistant/hass-music-assistant#2160]
### What version of Music Assistant has the issue?

2.0.0b141

### What version of the Home Assistant Integration have you got installed?

2024.4.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When adding jellyfin as a provider, entering a password is required.

This should not be the case, as it's possible in jellyfin to have a user without no password.

Inputting text into the password field should not be a requirement for saving the provider.

### How to reproduce

1. Go to `/#/settings/addprovider/jellyfin`
2. Type in the jellyfin server address
3. Type in the jellyfin username
4. Do not type a password, the save button is disabled.

### Music Providers

Jellyfin

### Player Providers

-

### What version of Home Assistant Core are your running

2024.4.4

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
@lokiberra

**Comment by lokiberra** [comment]
@IAmTheMilkManMyMilkIsDelicious This has been removed in the 2.0.3. Does it work for you now?

**Comment by OzGav** [comment]
We will close this soon due to no follow up

**Comment by IAmTheMilkManMyMilkIsDelicious** [comment]
This works well now thank you.

**Comment by IAmTheMilkManMyMilkIsDelicious** [comment]
This works well now thank you.
