### ISSUE TITLE
Intent handling error when requesting to play music by voice and more than one Media Player is assigned to the area

### ISSUE THREAD

**Issue by nikito** [music-assistant/hass-music-assistant#2161]
### What version of Music Assistant has the issue?

2.0.0b141

### What version of the Home Assistant Integration have you got installed?

2024.4.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When requesting to play music, such as "Play music by <artist>", when intent processing kicks in and tries to get the media player for the area the corresponding to the voice satellite the request was made on, an intent processing error occurs if that area has more than one applicable device present:
`Logger: homeassistant.components.conversation.default_agent
Source: components/conversation/default_agent.py:303
integration: Conversation (documentation, issues)
First occurred: 11:23:13 AM (1 occurrences)
Last logged: 11:23:13 AM

Intent handling error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/conversation/default_agent.py", line 303, in async_process
    intent_response = await intent.async_handle(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/intent.py", line 117, in async_handle
    result = await handler.async_handle(intent)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mass/intent.py", line 72, in async_handle
    state = await self._get_matched_state(intent_obj, name, area)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mass/intent.py", line 159, in _get_matched_state
    raise intent.IntentHandleError(
homeassistant.helpers.intent.IntentHandleError: Multiple entities matched for: name=None, area=AreaEntry(name='Workshop', normalized_name='workshop', aliases=set(), floor_id='garage', icon=None, id='workshop', labels=set(), picture=None)
`

### How to reproduce

Prerequisites:
- Have voice satellite assigned to an area
- Have at least two Music Assistant media players assigned to that same area

Make a request to play music without specifying a media device, allowing the intent handler to determine it based on the location of the satellite that the request was made to.

### Music Providers

Spotify

### Player Providers

Chromecast

### Full log output

`Logger: homeassistant.components.conversation.default_agent
Source: components/conversation/default_agent.py:303
integration: Conversation (documentation, issues)
First occurred: 11:23:13 AM (1 occurrences)
Last logged: 11:23:13 AM

Intent handling error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/conversation/default_agent.py", line 303, in async_process
    intent_response = await intent.async_handle(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/intent.py", line 117, in async_handle
    result = await handler.async_handle(intent)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mass/intent.py", line 72, in async_handle
    state = await self._get_matched_state(intent_obj, name, area)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mass/intent.py", line 159, in _get_matched_state
    raise intent.IntentHandleError(
homeassistant.helpers.intent.IntentHandleError: Multiple entities matched for: name=None, area=AreaEntry(name='Workshop', normalized_name='workshop', aliases=set(), floor_id='garage', icon=None, id='workshop', labels=set(), picture=None)
`

### What version of Home Assistant Core are your running

2024.4.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
As per the docs that is a known limitation https://music-assistant.io/integration/installation/

**Comment by OzGav** [comment]
Yes correct
