### ISSUE TITLE
Artist not removed from library when all local tracks removed and no streaming providers available

### ISSUE THREAD

**Issue by OzGav** [music-assistant/hass-music-assistant#2167]
With only the local provider loaded if all tracks from an artist are removed then the library is updated on the next sync but the artist is not removed automatically. 

### Discussed in https://github.com/orgs/music-assistant/discussions/2159

<div type='discussions-op-text'>

<sup>Originally posted by **accollie** April 25, 2024</sup>
I think it would be cool to remove missing or edited files from the library on sync. For example if i change a file on my server or delete it. When i sync it should be removed from the music assistant library.</div>

**Comment by marcelveldt** [comment]
this one should be fixed in the next beta (b143) - but please test all (edge) cases

**Comment by OzGav** [comment]
Sorry no change in behaviour noted

![image](https://github.com/music-assistant/hass-music-assistant/assets/19848947/7341a15b-80b2-460e-ae73-b3b270c01ccc)

**Comment by marcelveldt** [comment]
I have tested this a couple of time and works perfectly fine so maybe retest and if it still happens, try to spot some common factor when/why it happens ?

**Comment by OzGav** [comment]
I can't see a pattern. I tried an artist that was only on one track of a various artists compilation album. For this one I just deleted the file from the NAS.

Then I tried an artist that only had a single song. For this one I removed the whole artist folder.

Then I tried an artist that had a single track on a single album. For this on I also removed the whole artist folder.

In all cases the artist remained with no albums or tracks.

**Comment by madbrain76** [comment]
I had artists remaining after deleting all the music providers, but also 4 albums, and 2051 tracks remaining - all greyed out.

My 2 cents - obviously, when deleting the providers, the associated content should be deleted as well.
When disabling the providers, I think the associated content should be hidden, the same way players are hidden in the "Players" tab when disabling a player provider.

**Comment by OzGav** [comment]
confirmed fixed on my end on 2.1.0b3
