### ISSUE TITLE
Streaming provider still shown in artist view after being removed

### ISSUE THREAD

**Issue by OzGav** [music-assistant/hass-music-assistant#2168]
### What version of Music Assistant has the issue?

2.0.0b141

### What version of the Home Assistant Integration have you got installed?

2024.4.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I removed Spotify as a provider. I observed two problems. Firstly for an Artist where I don't believe I had any items added to the library from Spotify I still see this at the bottom of the artist view

![image](https://github.com/music-assistant/hass-music-assistant/assets/19848947/477c7e19-7732-4dd9-9b6f-189437fc8f7b)

Then in an artist which did have a Spotify album added the album is still there but greyed out. No change after a MA restart nor a REFRESH ITEM

![image](https://github.com/music-assistant/hass-music-assistant/assets/19848947/122ac2af-746a-4b7b-9b5b-50f4ab005f49)

### How to reproduce

Add a local file system provider.
Add Spotify
Add an album from Spotify to Artist A
Observe Artist B has Spotify in the Provider Details section of the Artist view due to linking
Remove Spotify
Restart MA
Observe Album in Artist A still visible but greyed out
Observe Artist B still showing Spotify in the Provider Details section 

### Music Providers

Local Provider
Spotify

### Player Providers

Not relevant

### What version of Home Assistant Core are your running

2024.4.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by marcelveldt** [comment]
this one should be fixed in the next beta (b143)
