### ISSUE TITLE
Artist list sorted alphabetically and by case in two parts

### ISSUE THREAD

**Issue by OzGav** [music-assistant/hass-music-assistant#2174]
### What version of Music Assistant has the issue?

2.0.0b143

### What version of the Home Assistant Integration have you got installed?

2024.4.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When scrolling down the artist list the bands starting with Z were reached but then another alphabetically sorted list of remaining artists was then observed

![image](https://github.com/music-assistant/hass-music-assistant/assets/19848947/b4b420f5-0617-411f-a3c7-a1fa34244b18)

### How to reproduce

as above

### Music Providers

Observed on instance #1 running file provider, tunein and radio browser as well as instance #2 running file provider, Spotify, Tidal , tunein and radio browser

### Player Providers

N/A

### What version of Home Assistant Core are your running

2024.4.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
The original problem seems to be resolved in b144. However, I now note that the list is sorted in twi parts by case which I don't think it should do? 

![image](https://github.com/music-assistant/hass-music-assistant/assets/19848947/3a40482b-0f67-4fd3-9e16-99f84f192ca7)

**Comment by marcelveldt** [comment]
are you sorting by name or sort name ?

**Comment by OzGav** [comment]
I am sorting by name and I'm sure you are going to say that is correct due to the ASCII values! If you believe this is how it should go then no problems. I just did not expect bands that just happen to use lower case characters to end up at the bottom. I just can't find a sort I am happy with! Sort name I don't like as it uses surname (and I have too many to manually edit the tags!) and alphabetical is a pain as it considers "The" to be part of the name... First world problems I know...

**Comment by marcelveldt** [comment]
1) Why not just correct those lowercase entries in your tags ?
2) You can fill the sortname tag if you want - it should be read by the tag scanner

**Comment by OzGav** [comment]
Yep I can. I will probably go with fixing the lowercase letters and live with the bands with The in their name being down in T

**Comment by OzGav** [comment]
INteresting this came up years ago and you fixed it! https://github.com/music-assistant/hass-music-assistant/issues/755
