### ISSUE TITLE
Youtube Music provider doesn't load playlists.

### ISSUE THREAD

**Issue by NicusorFlorinBaluta** [music-assistant/hass-music-assistant#2177]
### What version of Music Assistant has the issue?

2.0.0b143

### What version of the Home Assistant Integration have you got installed?

 2024.4.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

![image](https://github.com/music-assistant/hass-music-assistant/assets/19803113/118d3eff-aeb6-40a0-ad6e-21492e00c670)

The playlists fail to load, and they do not appear in the Playlists tab, i can reach them via the browse functionality but they fail to load

### How to reproduce

Add Youtube Music Provider, wait for sync to complete, navigate to Playlists / browse to a youtube music playlist

### Music Providers

Youtube Music doesn't work

Plex works fine

### Player Providers

Not a player issue

### Full log output

[ma_logs.txt](https://github.com/music-assistant/hass-music-assistant/files/15165675/ma_logs.txt)

### What version of Home Assistant Core are your running

2024.4.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by hundredfire** [comment]
Same problem at mine. Apparently yt music changed how they integrate album art into playlists and it bugs the playlist parser?

**Comment by OzGav** [comment]
@MarvinSchenkel

**Comment by hundredfire** [comment]
[Great news!](https://github.com/sigma67/ytmusicapi/pull/573)

**Comment by NicusorFlorinBaluta** [comment]
After b148 it seems to be fine.
Though the Desktop Companion player cannot be played to though (cannot select it) but that is another story. 
Thanks for the fix!
