### ISSUE TITLE
MA 2.0.0b143: Albums are in the database twice (or more)

### ISSUE THREAD

**Issue by rvandet** [music-assistant/hass-music-assistant#2178]
### What version of Music Assistant has the issue?

2.0.0b143

### What version of the Home Assistant Integration have you got installed?

2024.4.4

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Album is presented in the database as many times as there is a Album artist in a Tag.
So two Album artists (seperated by ;) in the Album artist tag, leads to two album entries.
This happend also after removing the Source (a NAS in my case), restart HA, add Source.

### How to reproduce

Install latest MA

### Music Providers

NAS
Spotify works correct

### Player Providers

Any Player provider, it is in the Album database

### What version of Home Assistant Core are your running

2024.4.4

### What type of installation are you running?

Home Assistant Core

### On what type of hardware are you running?

Raspberry Pi

**Comment by marcelveldt** [comment]
How did you determine they are duplicated in the database ?
Shouldnt the issue report be that they are duplicated in the listing ?

or did you confirm that they have a different library id.

**Comment by rvandet** [comment]
I do not know if it are double entries in the database. I do not know where to find the library id.
But i can see Albums twice (sometimes more) in the GUI of the Albums, you call that the listings i suppose.

**Comment by rvandet** [comment]
Ordening did not solve it. Delete MA, reinstall neither.
Now i am reformatting the NAS.

**Comment by DerPicknicker** [comment]
> Now i am reformatting the NAS.

Only one question:WHY?

**Comment by rvandet** [comment]
Because i removed some double files. Maybe the file index remained behind somehow. And i removed / improved some tags.

**Comment by marcelveldt** [comment]
Issue will be fixed in the next beta (b144)

**Comment by OzGav** [comment]
@rvandet Please confirm this is fixed in b144

**Comment by rvandet** [comment]
This issue is Fixed.

**Comment by rvandet** [comment]
I got another issue now: 
https://github.com/music-assistant/hass-music-assistant/issues/2189

**Comment by DerPicknicker** [comment]
Issue is on my side also resolved 👍🏻
