### ISSUE TITLE
V1.1.14: increasing CPU load

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#218]
Yesterday I had music running and I noticed the cpu load increased over time. Not seen that before;
![image](https://user-images.githubusercontent.com/4363599/169781976-d3b6d233-b32b-4f56-9f08-2bc33a050244.jpeg)
Will check today with the update.
Just installed 1.1.15. Rebuild database is running

**Comment by marcelveldt** [comment]
Hard to say if this is even caused by MA without seeing more details.Playing music takes a small bit of cpu but nothing fancy.

**Comment by erkr** [comment]
Before v1.1.14 the cpu load was relatively low and stable over time. I'm now running the same test against v1.1.15. A little early to conclude but it seems to increase as well:
![image](https://user-images.githubusercontent.com/4363599/169814530-9533da1e-9b95-4f63-ba6e-992166c1d1dc.jpeg)
The red circle was the rebuild of the database. After that I started music. The red line

**Comment by erkr** [comment]
Before v1.1.14 the cpu load was only slightly elevated (part after the red arrow):
![image](https://user-images.githubusercontent.com/4363599/169815379-fa24c3d2-1ce5-4096-a737-63c200dc5289.jpeg)

**Comment by erkr** [comment]
Hi

I zoomed in on the CPU graph, and since v1.1.14 there are cpu spikes every few minutes (1 per track?) . These spikes where not there before. The base cpu level in not higher then before and when zooming in it looks stable. 
So the increasing CPU was configured to quick from my side😌

The grey time label is where I stopped the music:
![image](https://user-images.githubusercontent.com/4363599/169824860-d7ccaea7-4345-4535-b20d-f8b7f6afd73f.jpeg)

The same zoomed out v1.1.14:
![image](https://user-images.githubusercontent.com/4363599/169825074-399cc0b9-82fa-4b46-8f93-b6c05d0e2b52.jpeg)

And the 1.1.13 version:
![image](https://user-images.githubusercontent.com/4363599/169825165-8066afa6-714f-4f8e-b3c2-fd489dec29c2.jpeg)

Are these spikes, as intended, you can close the issue. I just want to share the changed behavior.

**Comment by marcelveldt** [comment]
Those graphs look perfectly fine to me. A small (but not alarming) peak whenever a track is fetched. Do note that a lot of the metadata retrieval has moved from "all upfront" to "just in time" So for a track/album/artist that is played for the very first time, the metadata will be retrieved as soon as you play it or show the info. Open the same item once again after that just returns the db infos.

I would be alarmed if there was a constant cpu pressure or if those metadata lookups cost more than 50% of cpu.
I don't know how realtime your cpu info is but maybe you can do the test with opening an artist for the first time (results in cpu peak) and then the same artist one more time.

**Comment by erkr** [comment]
I agree only the condensed graphs looked alarming, the detailed one just behaves different matching  your explanation perfectly. 
My CPU is just the default systemmonitor one. 
Sorry for the false alarm. I will try to record looking up of an artist twice.

**Comment by erkr** [comment]
Hi 

I did some CPU recoding. Two experiments; radio stations, and playing the same track multiple times:
![image](https://user-images.githubusercontent.com/4363599/169878220-f07b5b54-0788-4b17-943d-f4957eb19018.png)

- Red part is listening two radio stations on two CC's; as expected no peaks!
- Green, Blue and Yellow are the same track played 3 times. Not really a big difference in start CPU load, but the first two times there was also a small CPU peak when finishing the tracks (circles) .

**Comment by erkr** [comment]
Just aan update for v1.1.18: cpu/spikes are reduced:
![image](https://user-images.githubusercontent.com/4363599/170496901-cf92588d-fe6a-4cea-834e-b4381bec453a.jpeg)

**Comment by marcelveldt** [comment]
That looks good. Thanks for the test. That will flatten out even more when more tracks are played and the metadata and audio analysis is gathered in the db
