### ISSUE TITLE
Snapcast track changing fail

### ISSUE THREAD

**Issue by JeffersonBledsoe** [music-assistant/hass-music-assistant#2182]
### What version of Music Assistant has the issue?

2.0.0b143 

### What version of the Home Assistant Integration have you got installed?

2024.4.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Sometimes when changing tracks while using Snapcast, the next track fails to start and the snapcast server crashes.

### How to reproduce

Unsure, it seems to sporadically happen whilst trying to play another track while another is in-progress

### Music Providers

Spotify
Local

### Player Providers

Snapcast

### Full log output

[log.txt](https://github.com/music-assistant/hass-music-assistant/files/15179728/log.txt)

### Additional information

The lines in the log from when the error happened are:

```
2024-05-01 19:03:29.278 WARNING (MainThread) [music_assistant.providers.snapcast.ffmpeg] write called while process already done
2024-05-01 19:04:15.792 WARNING (MainThread) [music_assistant.providers.snapcast] {'code': None, 'message': 'Server not connected'}
2024-05-01 19:04:15.794 ERROR (MainThread) [music_assistant.webserver] Error handling message: players/queue/play_pause: Unable to create stream - No free port found?
```

### What version of Home Assistant Core are your running

2024.4.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Alternative

**Comment by SantiagoSotoC** [comment]
Do you use the embedded snapserver or an external one ?

**Comment by JeffersonBledsoe** [comment]
Built-in

**Comment by JeffersonBledsoe** [comment]
I found this happens more regularly when trying to go 'previous' than next, but it's been a little bit more stable as of late

**Comment by SantiagoSotoC** [comment]
And you are using which version of ma ? 
Because according to the log you have a lot of connection problems, not only with snapcast

**Comment by JeffersonBledsoe** [comment]
I've upgraded the hardware since which solved alot of the connection problems in the log (I was on a 2GB RPi4). I've been using the Beta and keeping up with releases.

**Comment by SantiagoSotoC** [comment]
And now how much ram do you have ?

**Comment by SantiagoSotoC** [comment]
Can you send a new log, when this happens ?

**Comment by JeffersonBledsoe** [comment]
I've not experienced this for a little while now so happy to close and re-open it if it is reproduced
