### ISSUE TITLE
No file can be indexed on local filesystem provider.

### ISSUE THREAD

**Issue by Dieghito72** [music-assistant/hass-music-assistant#2184]
### What version of Music Assistant has the issue?

2.0.0b143

### What version of the Home Assistant Integration have you got installed?

2024.4.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

No file can be indexed on local filesystem provider, logs shows error accessing the files.

### How to reproduce

Problems started with 2.0.0b141, I tried to clear cache, but nothing changed.
Since I read that the database need to be reconstructed with 2.0.0b143 I decided to start from scratch and I reinstalled the docker, but problems still persists. 

### Music Providers

File system provider only.

### Player Providers

Airplay player only.

### Full log output

[musicassistant.log](https://github.com/music-assistant/hass-music-assistant/files/15184559/musicassistant.log)

### Additional information

Music Assistant runs inside a docker that have access to a volume that maps to a an Unraid folder. 
Everything worked well since 2.0.0b141.

### What version of Home Assistant Core are your running

2024.4.0

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
Please roll back via your backup to confirm this is actually a MA problem and not a permission issue at your end

**Comment by Dieghito72** [comment]
Thank you very much for your response and for your hard work, unfortunately I don't have a backup.
I forgot to mention that using **Browse** functionality of MA I'm able to list files, but I click on **Show info** an empty page is shown.

Below a screenshot of a **ls** performed inside the MA docker on the mapped folder:

![image](https://github.com/music-assistant/hass-music-assistant/assets/109356631/921e19ff-0336-46b5-9d1d-3f717f0bf478)

**Comment by OzGav** [comment]
Ok please be patient until this can get looked at further

**Comment by marcelveldt** [comment]
This has nothing to do with MA but is an access rights issue. Make sure that you create the docker container with the correct (elevated!) access rights and that MA has read rights to your media files.

**Comment by Dieghito72** [comment]
@marcelveldt thank you very much, yes the container wasn't privileged, now it works.
I'm quite sure that before b141 everything was working even without privileged flag, but anyway thank you for your work! 👍
