### ISSUE TITLE
MA always shows media device as off in UI unless manually turning it on

### ISSUE THREAD

**Issue by dinki** [music-assistant/hass-music-assistant#2186]
### What version of Music Assistant has the issue?

2.0.0b143

### What version of the Home Assistant Integration have you got installed?

2024.3.6

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

On boot of my ESP32 satellites using the HA MediaPlayers source the device appears to be off to MA. 

https://i.imgur.com/CySasSa.png

In the MA interface I can start playing music to the device while it is in the off state but the device never switches from the off state.

### How to reproduce

I am guessing that this happens with all ESP32 satellite devices which expose a media_player device to HA/MA.  Power one on and notice that MA shows state as off.

### Music Providers

Spotify and TuneIn

### Player Providers

Home Assistant MediaPlayers

### What version of Home Assistant Core are your running

2024.5.0

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Actually I think this is normal. If I look at all my Chromecast devices they are also showing OFF at the moment even though they are physically powered. OFF in this context means MA has no queue loaded for the player and is not controlling it.

From the HA docs: 

> OFF: Entity is turned off and is not accepting commands until turned on. IDLE: Entity is turned on and accepting commands, but currently not playing any media.

After pressing the MA power button on a Google Home it changed to IDLE then after about 5 mins it just sent back to OFF. If the player was physically powered off it would be UNAVAILABLE

What is unusual is where you say

> In the MA interface I can start playing music to the device while it is in the off state but the device never switches from the off state.

That might be related to what Marcel says here https://github.com/music-assistant/hass-music-assistant/issues/2117#issuecomment-2053648519

**Comment by OzGav** [comment]
@dinki I assume you are happy with the information above. I will close this soon.

**Comment by dinki** [comment]
Sorry.  Will confirm today or tomorrow and close.  Thanks
