### ISSUE TITLE
Musicbrainz errors in logfile when starting MA, how to prevent?

### ISSUE THREAD

**Issue by rvandet** [music-assistant/hass-music-assistant#2189]
### What version of Music Assistant has the issue?

2.0.0b144

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Players do not show up in MA

### How to reproduce

Restart MA and HA

### Music Providers

Spotify, NAS

### Player Providers

Spotify, CC, MPD

### Full log output
Attached in additional post

### Additional information

Issues introduced when upgrading to latest MA.

### What version of Home Assistant Core are your running

2024.5.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Have you checked to see if the providers have been added? 

P.S. *Please* follow the instructions and just attach the log file instead of pasting it

**Comment by rvandet** [comment]
Yes, after restart of HA, players are available in HA, but not in MA.

**Comment by rvandet** [comment]
[log.txt](https://github.com/music-assistant/hass-music-assistant/files/15209294/log.txt)

**Comment by OzGav** [comment]
The problem seems to be invalid ISRC. How have you tagged these tracks?

**Comment by rvandet** [comment]
I use MP3TAG. 

There are mp3, wav and flac files. 
so many different tag formats as well. 

How can I find the file where it goes beserk?

**Comment by OzGav** [comment]
In the log you can find the http calls that are failing. I plugged that into my browser and MB returned an invalid ISRC error. If you can load up your tracks in the MP3Tag maybe it has a search function?

For example the first one is http://musicbrainz.org/ws/2/isrc/ushm80323691?fmt=json

**Comment by OzGav** [comment]
We will close this soon unless you think it is not a tagging problem

**Comment by rvandet** [comment]
You can close this ticket. Thx.
