### ISSUE TITLE
Previous track not working in playlists generated by Music Assistant

### ISSUE THREAD

**Issue by bollewolle** [music-assistant/hass-music-assistant#2190]
### What version of Music Assistant has the issue?

2.0.0b144

### What version of the Home Assistant Integration have you got installed?

2024.5.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I used the "100 Random tracks (form Library)" playlist, a VERY nice addition by the way. I understood those MA playlists might still need some work, so to add to that, I noticed that for that playlist when I'm on song N and click the back button, it quickly shows N-1 as song but then jumps to N+1 and starts playing that one (so ignoring both N-1 and N as songs). It seems that the back doesn't work for that playlist (or at least for me). I checked other playlists, like those of Spotify, they do seem to have a working back function.

I tested also playlists "All favorited tracks" and "Random Album (from Library)" which both had the same behaviour

### How to reproduce

- Navigate to the playlist "100 Random tracks (form Library)"
- click Play --> Play Now
- let is play until the next song (I noticed that when you click next first that sometimes the previous does work, but sometimes it also there does something strange)
- click Previous once the next song started playing, and notice how it doesn't go to the Previous song but somehow also skips the song that was playing and jumps to the next song

### Music Providers

I think the MA playlists us the library which for me would be the filesystem (mostly with FLAC files).

### Player Providers

DLNA to a Marantz/HEOS receiver.

### What version of Home Assistant Core are your running

2024.5.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Yes this is possibly due to the way these are dynamically generated. This will be looked at in due course.

**Comment by OzGav** [comment]
Yes this works for me in b148
