### ISSUE TITLE
MA generated playlists are not adding to the queue what was in the playlist

### ISSUE THREAD

**Issue by bollewolle** [music-assistant/hass-music-assistant#2191]
### What version of Music Assistant has the issue?

2.0.0b144

### What version of the Home Assistant Integration have you got installed?

2024.5.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When I go to one of the MA generated playlists like "100 random tracks (from library)" I get to see a list like so:
<img width="1463" alt="image" src="https://github.com/music-assistant/hass-music-assistant/assets/368306/5869a31c-9a1e-48b5-a25f-06ec6e0be588">

Then I click Play --> Play Now:
<img width="1439" alt="image" src="https://github.com/music-assistant/hass-music-assistant/assets/368306/59b7d083-d7e9-45ea-b3c5-c3e5d41aba2d">

The queue is replaced but NOT with the songs that were shown in the playlist (see screenshot above to compare):
<img width="1447" alt="image" src="https://github.com/music-assistant/hass-music-assistant/assets/368306/9857074e-3cf3-43ce-9c16-95ab51d06859">

I assume this is unwanted behaviour so thought I'd log it

### How to reproduce

See "The problem" section where the steps are explained with screenshots

### Music Providers

MA playlists seem to use the filesystem library, which are FLAC's mostly in my case

### Player Providers

DLNA towards a Marantz/HEOS receiver

### What version of Home Assistant Core are your running

2024.5.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by marcelveldt** [comment]
This is correct, these playlists are completely dynamic all the time.

**Comment by OzGav** [comment]
It’s an interesting question then. Should they refresh also when played or only when viewed? If both there is not much point being able to view the list as it will change when played?

**Comment by bollewolle** [comment]
My assumption would indeed be that the list you see when you click the Play button is the list added to the queue. It's great that it's a random list, I refreshed the browser a few times to get a new list and if I liked it pressed the Play button. That's when I indeed noticed that there's yet another list added to the queue, which was unexpected.

**Comment by OzGav** [comment]
This should be fixed in b148
