### ISSUE TITLE
 V1.1.15: Secondary artist tags not being detected?

### ISSUE THREAD

**Issue by AvdWerfhorst** [music-assistant/hass-music-assistant#220]
Last few days I have been looking into improving my tags. And I did read somewhere that for FLAC the recommended way of tagging song or albums on which artist coöperate under their own individual names, is to repeat the ARTIST or ALBUMARTIST tags for each artist individually. I did do this for instance with the Barcelona album by Freddie Mercury and Montserrat Caballé. Originally I had this tagged as Freddie Mercury & Montserrat Caballé as ALBUMARTIST tag. But I find it more logical to be able to browse to there through the individual names. So now both have their own ALBUMARTIST tags (And also ARTIST tags for each individual song).

Only when I look at the detected artists, I can find Freddie Mercury, but not Montserrat Caballé. His name is tagged first in all my files, so to me it looks to me like only the first tag is picked up and the others with the same name are ignored. What seems to be what I also see in the album view. Would it be possible in the future to detect all ARTIST and ALBUMARTIST tags in a FLAC file?

![JustFred](https://user-images.githubusercontent.com/35181252/169813128-5d97ec88-6f3c-4c6f-9667-90d30c16d499.PNG)

**Comment by marcelveldt** [comment]
In the above example you see this album where Freddy Mercury is the (main) album artist and both Freddy and Montserrat are song artists.

Now I could support multiple album artists but that's (another) breaking change to the data model.
So it's kind of now or never to support it before the stable release. Adding support now is easy if people accept a full rescan. Once stable is released I'll have to write db migration logic ;-)

**Comment by erkr** [comment]
You have my support for another breaking change👍 That's what beta testing is for

**Comment by marcelveldt** [comment]
@AvdWerfhorst I'm currently implementing this and I have one more question: What's the name of the artist folder on disk ?
I assume it is one of the album artists so in this case "Freddy Mercury" ?

**Comment by AvdWerfhorst** [comment]
@marcelveldt Except for the spelling of the name Freddie, you are absolutely correct.

**Comment by marcelveldt** [comment]
@AvdWerfhorst oops, although I'm a fan of his work I had never noticed the spelling of his name. Corrected it above and I'll try to remember to type it right from now on :-)

OK, I've adjusted the code and currently testing it.
I've decided to in fact write a db migrate script for the sake of testing the migration logic.
Next release should include this change and a new scan of files on disk is triggered, which should auto-correct the multi artists on albums.

**Comment by marcelveldt** [comment]
Fix released in 1.1.17
To correct this album (after installing 1.1.17), Open the contextmenu and click "Refresh info".

**Comment by marcelveldt** [comment]
@AvdWerfhorst did you have a chance yet to play with version 1.1.18 (or 1.1.19) to test the recent changes ?
Is everything in order now and can this issuereport be closed ?

**Comment by marcelveldt** [comment]
No worries. Enjoy your holidays!

**Comment by marcelveldt** [comment]
Issue closed for better overview. Please reopen if it is not yet fixed. Thanks!

**Comment by marcelveldt** [comment]
Wow that sounds very cool!
And great to hear that it's working as expected now!
