### ISSUE TITLE
Music Assistant removing tracks from Tidal playlist immediately after adding them

### ISSUE THREAD

**Issue by mikeb9x** [music-assistant/hass-music-assistant#2205]
### What version of Music Assistant has the issue?

2.0.0b145

### What version of the Home Assistant Integration have you got installed?

2024.4.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When I create a new Tidal playlist or add new tracks to an old one, they are immediately starting to disappear. Music Assistant shows the playlist as empty, Tidal shows it right, but the number of tracks keeps decreasing. If I stop the Music Assistant Add-on, disappearing stops. After I start add-on it again Music Assistant finds missing tracks and doesn't continue to remove them.

### How to reproduce

Add some tracks to a new playlist (let's say 100 tracks to see the process) > check Tidal and they are there > number of tracks starts to decrease > after some time the playlist is empy

### Music Providers

Tidal

### Player Providers

-

### What version of Home Assistant Core are your running

2024.5.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Please try with beta 146 just to check there are no changes.

**Comment by OzGav** [comment]
We will have a look at the error. You can add a whole artist direct to the playlist or a whole album. In the tracks view select the menu top right and you have the option SELECT MULTIPLE ITEMS

**Comment by OzGav** [comment]
Try clearing the cache MA SETTINGS>>CORE>>CACHE CONTROLLER>>CONFIGURE>>CLEAR CACHE

**Comment by marcelveldt** [comment]
We will look into this, sounds like a bug. Hold on until we get back on this, thanks

**Comment by marcelveldt** [comment]
fixed in b148

**Comment by OzGav** [comment]
@mikeb9x Please confirm if this is fixed

**Comment by OzGav** [comment]
Ok I tried this by adding an album and then a single trackand it worked fine. What are you trying to add and how?

What I did notice an aside is that the first track does not have a track number.

**Comment by marcelveldt** [comment]
> No more 'async for' error, but the original issue is still there. Actually it's worse - now adding tracks to a Tidal playlist doesn't seem to do anything. If I create a new playlist it's just empty (visible in MA and in Tidal). 

Works fine for me, tested several playlists - did you wait long enough as it can take a while, we should probably pop up some message that the request will be processed in the background
