### ISSUE TITLE
Cannot play youtube music playlist: "'async for' requires an object with __aiter__ method, got coroutine"

### ISSUE THREAD

**Issue by hundredfire** [music-assistant/hass-music-assistant#2208]
### What version of Music Assistant has the issue?

2.0.0b146

### What version of the Home Assistant Integration have you got installed?

2024.5.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Following the A/B testing of new playlists display in YT music, the parser for the library ytmusic-api was broken. This recently got fixed with version 1.7.0 of said library.
Now, I can actually browse my playlists using Music assistant server on home assistant. However, when I try to play any playlist, the following error is displayed: 
`'async for' requires an object with __aiter__ method, got coroutine`
and nothing happens.

Here are the relevant log entries:
```
2024-05-07 23:35:25.510 INFO (MainThread) [music_assistant] Loaded music provider YouTube Music
2024-05-07 23:37:24.585 WARNING (MainThread) [music_assistant.music] Sync task for YouTube Music completed with errors
2024-05-07 23:40:54.545 WARNING (MainThread) [py.warnings] /usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/player_queues.py:345: RuntimeWarning: coroutine 'PlaylistController.tracks' was never awaited
  async for playlist_track in ctrl.tracks(

2024-05-07 23:40:54.546 ERROR (MainThread) [music_assistant.webserver] Error handling message: player_queues/play_media: 'async for' requires an object with __aiter__ method, got coroutine
```
This is quite troublesome as playlists can't work at all neither in the front-end, nor in automations. (Again, albums and single tracks can be played without any issues)

### How to reproduce

Browse a YT music playlist, press play

### Music Providers

Youtube Music

### Player Providers

Chromecast audio group

### Full log output

[log.txt](https://github.com/music-assistant/hass-music-assistant/files/15241478/log.txt)

### What version of Home Assistant Core are your running

2024.0.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by senderbell** [comment]
I have exactly the same issue on Spotify. TuneIn works well

**Comment by OzGav** [comment]
Please try again with b147

**Comment by hundredfire** [comment]
> Please try again with b147

Works perfectly! Great job, thank you for your work
