### ISSUE TITLE
sonos integration stopped working

### ISSUE THREAD

**Issue by axwell** [music-assistant/hass-music-assistant#2213]
### What version of Music Assistant has the issue?

2.0.0b147

### What version of the Home Assistant Integration have you got installed?

Installed via addon store

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

no media players listed from sonos after updating to [2.0.0 BETA 147] - 07.05.2024 from [2.0.0 BETA 145] - 06.05.2024
Error is thrown in logs, request to 192.168.88.1 fails, which is weird because that is the router IP

### How to reproduce

start addon, enable SONOS

### Music Providers

any provider, youtube, soundcloud

### Player Providers

Sonos

### Full log output

[log.txt](https://github.com/music-assistant/hass-music-assistant/files/15247080/log.txt)

### What version of Home Assistant Core are your running

2024.4.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi 4, 8 GB RAM, SSD

**Comment by OzGav** [comment]
Please follow the instructions which are in multiple places and attach the log instead of pasting it.

**Comment by codeblue11** [comment]
For the record all of my Sonos media players are working fine after updating to b147

**Comment by axwell** [comment]
It looks like it's an issue on my network. I'll leave more details here if someone else runs into this issue.

I'm using a [mikrotik](https://mikrotik.com/product/RB3011UiAS-RM#fndtn-specifications) router that has 10 ports, but 5 are assigned to a hardware switch chip and the other 5 to another.

Ports are all bridged together so it should not be an issue but it looks like something is preventing music assistant to talk properly with Sonos, even if the official app works just fine.

Inserting sonos cable and the home assistant cable in the same switch group solves the issue.
