### ISSUE TITLE
Service "media_player.clear_playlist" throws unknown error

### ISSUE THREAD

**Issue by xteaun** [music-assistant/hass-music-assistant#2216]
### What version of Music Assistant has the issue?

2.0.0b147

### What version of the Home Assistant Integration have you got installed?

2024.5.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Since the last update the service call to media_player.clear_playlist throws an unknown error.

### How to reproduce

Call "media_player.clear_playlist" from Home Assistant Developer Console.

### Music Providers

Spotify

### Player Providers

Sonos

### What version of Home Assistant Core are your running

2024.5.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by senderbell** [comment]
I have the same problem. Additionally, in the graphical interface I can no longer see the playback queue - only the currently playing track is visible.

**Comment by OzGav** [comment]
@senderbell the queue view is being worked on which is why it is temporarily disabled.

@xteaun pllease add to your report the exact service call you are using, that is, the whole yaml.

**Comment by OzGav** [comment]
@senderbell the queue is back with b148

@xteaun In the meantime I have reproduced this so this will be fixed in due course

**Comment by marcelveldt** [comment]
Fixed in 2.0.0 (and HA integration 2024.5.1)

**Comment by OzGav** [comment]
Confirmed fixed
