### ISSUE TITLE
Bug: Long song or album title misalignes info in now playing screen

### ISSUE THREAD

**Issue by starfetch** [music-assistant/hass-music-assistant#2220]
### What version of Music Assistant has the issue?

2.0.0b147

### What version of the Home Assistant Integration have you got installed?

2024.5.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

The song information in the "now playing" view is not aligned correctly if the song or album title is longer than the screen. Could not check for long artist names, but likely there as well.
Observed when using the HA companion app to access MA on mobile (Android), see attached screenshots.
![5a95d5c0-16a4-4d7c-8d59-565224499a9e](https://github.com/music-assistant/hass-music-assistant/assets/80041179/aefea9eb-7f78-40dc-a463-71db612282ad)

![7996525a-f5ee-44d5-ae74-a09b57fb6b53](https://github.com/music-assistant/hass-music-assistant/assets/80041179/e13abd85-2802-49a0-9c25-cf26ba543aa9)

This started to appear around the time the album info was added, before that long titles used to scroll (I think).

Tried restarting HA and MA, no change.

System info: HAOS, Spotify provider, Snapcast Player with external server.

### How to reproduce

- play a song with a long title or album name
- open now playing view in the HA companion app mobile

### Music Providers

Spotify is only provider present, but problem is likely independent of provider.

### Player Providers

Snapcast is the only provider present, but problem is likely unrelated to provider.

### What version of Home Assistant Core are your running

2024.5.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by marcelveldt** [comment]
this is fixed in beta148, please test/confirm

**Comment by starfetch** [comment]
Wow, you're fast. New beta between checking and typing up the bug report.

The original issue of the alignment is fixed, but long titles now overlap with the cover art:
![55d372ef-4925-4e32-8614-0bb2fc1440c3.jpg](https://github.com/music-assistant/hass-music-assistant/assets/80041179/d1677ae0-3cf8-40c2-b061-82157f8716ee)

Long album titles are cut off with three dots which is probably fine.

**Comment by OzGav** [comment]
Is that on mobile?

**Comment by starfetch** [comment]
Yes, HA Companion App on Android as in the original issue above.

**Comment by starfetch** [comment]
(Also, not directly related, but in the album view long titles also just run off the screen. This is again probably only noticeable when on mobile with limited horizontal space:
![4eac2cfc-014b-4f10-9c4b-7169aaf62a22.jpg](https://github.com/music-assistant/hass-music-assistant/assets/80041179/d4db0b83-0f0d-42b2-8ef4-5120bf281094)
)

**Comment by marcelveldt** [comment]
should be fixed in next patch release (2.0.4)

**Comment by OzGav** [comment]
@starfetch i am closing assuming fixed. We can reopen if not
