### ISSUE TITLE
Cannot remove artist from ytm library

### ISSUE THREAD

**Issue by barrelltitor** [music-assistant/hass-music-assistant#2222]
### What version of Music Assistant has the issue?

v2.0.0b148

### What version of the Home Assistant Integration have you got installed?

unrelated

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I am unable to remove an artist from the library if they are provided by ytm

### How to reproduce

1. Add a youtube music provider
2. try removing an artist from the library
3. get the error

### Music Providers

Youtube Music

### Player Providers

unrelated

### Full log output

2024-05-09 14:00:55.738 ERROR (MainThread) [music_assistant.webserver] Error handling message: music/library/remove_item: Server returned HTTP 400: Bad Request.

Error unsubscribing, try again

### What version of Home Assistant Core are your running

unrelated

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
You have pasted a single line from the log when the instructions ask you to ATTACH the full log.

You also haven’t explained whether this artist was already in the YTM provider library before adding it to MA or if you added it through MA.

Fuethermore, as per the instructions you haven’t advised what does work and what you have tried. Please review the issue template instructions and the troubleshooting docs which you have ticked a box saying you have read and provide all of the requested information.

**Comment by barrelltitor** [comment]
Hello OzGav,


> You have pasted a single line from the log when the instructions ask you to ATTACH the full log

That is literally the only log after taking the action. I assumed providing relevant logs would be better. After asking in the discord, [Marcel seemed to know what's going on just based on that log](https://discord.com/channels/753947050995089438/1098863037458415626/1238129326298238976)

I have attached the full log file which also contains the first 13 lines of the startup on a clean installation after following the provided instructions.

[log.txt](https://github.com/music-assistant/hass-music-assistant/files/15267807/log.txt)

> You also haven’t explained whether this artist was already in the YTM provider library before adding it to MA or if you added it through MA
As explained in the steps to reproduce, the artist to be removed is from the just added youtube music library, it was added by this library. If the steps are followed on a clean installation, this error will appear. 


> Furthermore, as per the instructions you haven’t advised what does work and what you have tried. Please review the issue template instructions and the troubleshooting docs which you have ticked a box saying you have read and provide all of the requested information.

If you believe there's something relevant in there to try out for this issue, please point me to specifically what it is. I haven't found anything in there to assist, so I have not tried or mentioned anything.

**Comment by OzGav** [comment]
You didn’t say this was already discussed on discord. Additionally, in the post above you say you have tried with a clean install that you didn’t mention before. The full logs are always required but you may do small excerpts to highlight what you believe is the problem. 

This will be looked at in due course

**Comment by OzGav** [comment]
This will be closed soon if there is no further update.

**Comment by marcelveldt** [comment]
I think this issue is still relevant and @MarvinSchenkel needs to check it at some point

**Comment by OzGav** [comment]
@MarvinSchenkel any thoughts?

**Comment by MarvinSchenkel** [comment]
I will go through all of this functionality soon :)

**Comment by barrelltitor** [comment]
Sorry, been insanely busy over the months.

I don't think what I wanted was to remove the artist from YouTube itself, but to just get them out of my library. I wanted to use YouTube just as a sort of search for things that I don't yet locally have, and other than that fully use my local music without having to see anything from youtube inside my library

Before when you could separate the local library and main one it would be okay and it was perfectly possible, but it's a mess without that ability. I listen to a lot of new music on youtube, and I do hit like on a bunch of them as I'd like to think it somehow helps the artist, but I don't want them forever being in my library unless I unlike it.

You know the old "this break my workflow" meme with the overheating spacebar, though I think my use case here of separating owned media from youtube et al is a bit more legitimate

I believe there were talks for a future version about not automatically importing yt artists and having the ability to just keep the search and opt-in-ly, manually add the artists from there you do want to add, which would completely solve this issue as well

**Comment by OzGav** [comment]
Yes that is not really possible. Whilst you can remove items from the MA library that will either also remove them from the provider library or they will come back with MA restarts.

You are correct that there is on the roadmap an item to allow better control over the import of items from the providers. ETA for that is not possible to provide. 

So it sounds like there is no issue here but a feature request that is already on the backlog? If so we could close this.

**Comment by barrelltitor** [comment]
The removed toggle for only showing local library music being added back in would also sort of fix this issue.

At the moment I am unable to actually remove a YTM artist, so regardless of what that button is supposed to do: either remove the artist from MA or from YT, it is not functional and this issue is still accurate

**Comment by OzGav** [comment]
> The removed toggle for only showing local library music being added back in would also sort of fix this issue.

What toggle are you referring to? This one?

![image](https://github.com/user-attachments/assets/5d750b7a-b4e2-4d71-aa4f-f4231cdd0398)

I don't use YTM but looking at the docs it appears it doesn't function like the other providers in that removing from the MA library probably has no effect on the YTM library. So I guess that is what @MarvinSchenkel meant when he would look at the functionality. I would expect though that selecting REMOVE FROM LIBRARY would at least remove the item from the MA library at least until the next sync. In any case lets wait and see what Marvin has to say when he gets a chance.

**Comment by marcelveldt** [comment]
this one will be fixed in 2.2.0rc2

**Comment by OzGav** [comment]
@barrelltitor please confirm this has been fixed and close if so. Thanks!

**Comment by OzGav** [comment]
This will be closed soon due to no followup

**Comment by barrelltitor** [comment]
I can confirm this now works, with the caveat that on resync artists are imported  again if they have songs in a playlist, though I think that's a completely separate topic

Thank you, and my apologies for the delay in testing!
