### ISSUE TITLE
Back button not working in some cases

### ISSUE THREAD

**Issue by michaeldufour** [music-assistant/hass-music-assistant#2224]
### What version of Music Assistant has the issue?

2.0.0rc1

### What version of the Home Assistant Integration have you got installed?

2024.3.6

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When I'am in a playlist and press return button nothing happened

![image](https://github.com/music-assistant/hass-music-assistant/assets/102390800/a34a16dc-0ef9-4d2f-ad0d-c447e1a47420)

### How to reproduce

Press the return arrow in a playlist

### Music Providers

YTM 

### Player Providers

Chromecast

### Full log output

No specific log for this

### Additional information

This issue is with any playlist

### What version of Home Assistant Core are your running

2024.5.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by marcelveldt** [comment]
This issue has just been fixed and will be in the 2.0 release

**Comment by michaeldufour** [comment]
> This issue has just been fixed and will be in the 2.0 release

Oh nice Marcel, thanks

**Comment by OzGav** [comment]
@michaeldufour please close this if you are satisfied it has been resolved

**Comment by michaeldufour** [comment]
Resolved, thanks!
