### ISSUE TITLE
Sorting issue Spotify Playlist

### ISSUE THREAD

**Issue by apedance** [music-assistant/hass-music-assistant#2230]
### What version of Music Assistant has the issue?

2.0 stable

### What version of the Home Assistant Integration have you got installed?

latest to this date (stable)

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

For some reason my Spotify playlist only display sort.default as seen in the picture. Any way to fix this?

![image](https://github.com/music-assistant/hass-music-assistant/assets/4264240/b601fe65-6f04-41b0-b84a-1049879e6c3c)

Thank you.

### How to reproduce

Sorting issue

### Music Providers

Spotify

### Player Providers

Chromecast, Airplay, UPnP

### What version of Home Assistant Core are your running

2024.5.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
It’s being discussed internally
