### ISSUE TITLE
Union type containing 'str' and 'bool' will be coerced

### ISSUE THREAD

**Issue by tomlut** [music-assistant/hass-music-assistant#2235]
### What version of Music Assistant has the issue?

2.0.0

### What version of the Home Assistant Integration have you got installed?

2024.5.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

The following is logged after restarting Home Assistant:
```
This error originated from a custom integration.

Logger: py.warnings
Source: custom_components/mass/__init__.py:21
integration: Music Assistant (BETA) (documentation, issues)
First occurred: 20:23:35 (3 occurrences)
Last logged: 20:23:35

/usr/local/lib/python3.12/site-packages/mashumaro/core/meta/types/unpack.py:182: UserWarning: music_assistant.common.models.config_entries.ConfigValueOption.value (typing.Union[str, int, float, bool, tuple[int, int], list[str], list[int], list[tuple[int, int]], None]): In the next release, data marked with Union type containing 'str' and 'bool' will be coerced to the value of the type specified first instead of passing it as is warnings.warn(
/usr/local/lib/python3.12/site-packages/mashumaro/core/meta/types/unpack.py:182: UserWarning: music_assistant.common.models.config_entries.ConfigEntry.default_value (typing.Union[str, int, float, bool, tuple[int, int], list[str], list[int], list[tuple[int, int]], None]): In the next release, data marked with Union type containing 'str' and 'bool' will be coerced to the value of the type specified first instead of passing it as is warnings.warn(
/usr/local/lib/python3.12/site-packages/mashumaro/core/meta/types/unpack.py:182: UserWarning: music_assistant.common.models.config_entries.ConfigEntry.value (typing.Union[str, int, float, bool, tuple[int, int], list[str], list[int], list[tuple[int, int]], None]): In the next release, data marked with Union type containing 'str' and 'bool' will be coerced to the value of the type specified first instead of passing it as is warnings.warn(
```

### How to reproduce

Install MA.
Restart HA.

### Music Providers

File System

### Player Providers

Home Assistant
Universal Group

### Full log output

[log.txt](https://github.com/music-assistant/hass-music-assistant/files/15273836/log.txt)

### What version of Home Assistant Core are your running

core-2024.5.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by marcelveldt** [comment]
HA already switch to orjson 3.13 as it seems, creating this issue now.
I've asked for help upstream: https://github.com/Fatal1ty/mashumaro/issues/221
