### ISSUE TITLE
Unlinking Airplay players not working correctly

### ISSUE THREAD

**Issue by OzGav** [music-assistant/hass-music-assistant#2239]
### What version of Music Assistant has the issue?

2.0.0

### What version of the Home Assistant Integration have you got installed?

2024.5.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Two  airplay players link correctly but fail to unlink correctly as shown in this video

https://github.com/music-assistant/hass-music-assistant/assets/19848947/6c3d1873-0489-440b-9d95-616a75b7ae63

Sometimes it takes a tab refresh to get the kodirumpus player to show the grouping was removed but the suffix remains

![image](https://github.com/music-assistant/hass-music-assistant/assets/19848947/94135071-c39d-4744-aa19-5f3169eefd2a)

And then when I tried to group the other way (Kodirumpus to the amplifier) I get

![image](https://github.com/music-assistant/hass-music-assistant/assets/19848947/79d4f472-b74c-4a2d-8e98-b0d6acc13159)

### How to reproduce

Start playback on Airplayer A
Link Airplayer B to Airplayer A
Unlink Airplayer B from Airplayer A
Stop playback on Airplayer A
Start playback on Airplayer B
Attempt to link Airplayer A to Airplayer B

### Music Providers

All

### Player Providers

Airplay

### What version of Home Assistant Core are your running

2024.5.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by marcelveldt** [comment]
Please re-test with 2.0.6 / 2.1.0b5

**Comment by OzGav** [comment]
I see the fronted has changed but I can’t see how to unlink them?

<img width="281" alt="image" src="https://github.com/music-assistant/hass-music-assistant/assets/19848947/0883635b-8e93-48f8-b420-dcb5eae3ac4b">

**Comment by marcelveldt** [comment]
> I see the fronted has changed but I can’t see how to unlink them?

Just turn off or click the link icon again

**Comment by OzGav** [comment]
But the link icon is no longer there. See picture.

**Comment by OzGav** [comment]
OK I see the turn off works. Closing and can look at the missing link icon later (unless that is expected behaviour)
