### ISSUE TITLE
Sonos Port Fixed Volume UPnP Error 501 When Setting Group Volume

### ISSUE THREAD

**Issue by sdoowo200leldls** [music-assistant/hass-music-assistant#2244]
### What version of Music Assistant has the issue?

2.0.1

### What version of the Home Assistant Integration have you got installed?

2024.05.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

My Sonos Port is set to a fixed volume setting where the volume cannot be changed within the device. When changing the group volume the error "ERROR (MainThread) [music_assistant.webserver] Error handling message: players/cmd/volume_set: UPnP Error 501 received: Action Failed from 192.168.1.231" is produced. Additionally, the speaker group volume treats the Sonos Port as being at 100 volume which throws the entire speaker groups combined volume off.

### How to reproduce

Create a Sonos speaker group that contains a fixed volume device like the Sonos Port.

### Music Providers

Tidal

### Player Providers

Sonos

### Full log output

[log.txt](https://github.com/music-assistant/hass-music-assistant/files/15281691/log.txt)

### What version of Home Assistant Core are your running

2024.5.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by marcelveldt** [comment]
ah, yes, this is a small oversight of me (didnt account for fixed volume). I will try to fix it within the next couple of days.
