### ISSUE TITLE
Playlists are starting at track 0

### ISSUE THREAD

**Issue by OzGav** [music-assistant/hass-music-assistant#2251]
### What version of Music Assistant has the issue?

2.0.1

### What version of the Home Assistant Integration have you got installed?

2024.5.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Observe any playlist that is NOT built in and the first track is track ZERO

### How to reproduce

As above

### Music Providers

N/A

### Player Providers

N/A

### Full log output

N/A

### What version of Home Assistant Core are your running

2024.5.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by marcelveldt** [comment]
yeah, is this a problem ?

**Comment by OzGav** [comment]
The built in ones dont nor do the provider equivalents so it is bit inconsistent. Though it might be a one line fix?

**Comment by marcelveldt** [comment]
> The built in ones dont nor do the provider equivalents so it is bit inconsistent. Though it might be a one line fix?

Welcome to the world of streaming providers, talking about (in)consistency

**Comment by marcelveldt** [comment]
I think most entries will start counting at 0 (as that is the default) and maybe just a few start at 1.
I can change the default to 1 but then again you might still have providers that start at 1 and there's a risk (at least for the internal ones) that we pick a wrong index so 0 is a safer choice.

Its important that is the correct order, I'm not sure its a big deal if counting starts at 0 or 1 tbh

**Comment by OzGav** [comment]
I am approaching this from a user perspective and just felt it odd to see a list start at zero and if you don’t notice that but see 50 in the total number but get to the bottom and see 49. Looking at the native Tidal and Spotify apps they don’t number their lists at all. The built in lists all start at 1.
So it’s just a display query. I think the options are (1) leave it as is, (2) change the underlying code to start at 1, or (3) just change the display to show it starting at 1 (if it starts at 0)

I think option 3 as there will then be consistency across the MA playlists but you should hopefully not run into issues with indexes.

I opened this as I though there was an error but since it is intentional I will close and leave it with you.
