### ISSUE TITLE
Translation Request Music Assistant. Language: pt-BR - Portuguese (Brazil)

### ISSUE THREAD

**Issue by enazevedo** [music-assistant/hass-music-assistant#2255]
### New language

pt-BR - Portuguese (Brazil)

### Additional remarks

Being using MA for quite some time, and would feel great to give some of my time back to community. Thanks!

**Comment by jozefKruszynski** [comment]
This was actually already added a couple of days ago to Lokalise, you should be able to add yourself as a contributor.
