### ISSUE TITLE
Cannot add a Radio with a logo

### ISSUE THREAD

**Issue by avbfr** [music-assistant/hass-music-assistant#2264]
### What version of Music Assistant has the issue?

2.0.2

### What version of the Home Assistant Integration have you got installed?

2024.5.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [x] Yes

### The problem

When adding a radio and giving an image URL, the radio doesn't appear in the list but it's present in settings.conf.[backup]

The logfile provides an error: ERROR (MainThread) [music_assistant.webserver] Error handling message: music/library/add_item: 'MediaItemImage' object has no attribute 'startswith'

### How to reproduce

Click on the radio button > Add item from URL > Provide an URL > Provide a title > Provide an Image URL ==> The Radio doesn't appear in the list

Click on the radio button > Add item from URL > Provide an URL > Provide a title > DO NOT Provide an Image URL ==> The Radio appears in the list

### Music Providers

Music Assistant

### Player Providers

N/A

### Full log output

The logfile provides an error: ERROR (MainThread) [music_assistant.webserver] Error handling message: music/library/add_item: 'MediaItemImage' object has no attribute 'startswith'

### What version of Home Assistant Core are your running

2024.5.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by avbfr** [comment]
An Exemple: 

URL : http://icecast.radiofrance.fr/franceinter-hifi.aac
Name: France Inter
URL: https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/France_Inter_logo_2021.svg/1200px-France_Inter_logo_2021.svg.png

Tried with at least 4 differents radios and different image sources. Same issue.

Thanks for your help and the great job you do !! :-)

**Comment by marcelveldt** [comment]
fixed in 2.0.4 patch release

**Comment by avbfr** [comment]
Confirmed ! 

Thanks :-).
