### ISSUE TITLE
Config flow deprecation warning and start add-on error

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#2267]
### What version of Music Assistant has the issue?

2.0.2

### What version of the Home Assistant Integration have you got installed?

2024.5.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I noticed a deprecation warning with a fresh setup, a little later I got an error stating the add-on coudn't be started.
Went into settings/add-on's and the MA add-on was running fine. Maybe related to the missing progress task in the warning

### How to reproduce

Fresh install of integration without a run in by add on

### Music Providers

Na

### Player Providers

Na

### Full log output
The warning:
```
Logger: homeassistant.data_entry_flow
Source: data_entry_flow.py:817
First occurred: 21:20:28 (1 occurrences)
Last logged: 21:20:28

custom_components.mass.config_flow::ConfigFlow calls async_show_progress without passing a progress task, this is not valid and will break in Home Assistant Core 2024.8. Please report it to the custom integration author
```

And the error
```
This error originated from a custom integration.

Logger: custom_components.mass
Source: custom_components/mass/config_flow.py:167
integration: mass (documentation, issues)
First occurred: 21:25:07 (1 occurrences)
Last logged: 21:25:07

Failed to start MusicAssistant Server add-on: timeout
```

### What version of Home Assistant Core are your running

2024.5.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by marcelveldt** [comment]
Can somebody reproduce this or was this just a random fluke once ?

**Comment by erkr** [comment]
I think this issue is related: https://github.com/music-assistant/hass-music-assistant/issues/2445

**Comment by marcelveldt** [comment]
The addon manager is now removed from the HA integration so this issue is now obsolete.
