### ISSUE TITLE
BUG: .ogg file support:  issue missing 'Channels' from Jellyfin Music Provider

### ISSUE THREAD

**Issue by Thijzer** [music-assistant/hass-music-assistant#2269]
### What version of Music Assistant has the issue?

2.0.0RC1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I recently setup music-assisant and noticed I couldn't get my Albums to work.
All my music is ripped in .ogg format and it's giving me an error 'Channels'

```log
music-assistant-music-assistant-1  | 2024-05-12 19:39:19.702 ERROR (MainThread) [music_assistant.webserver] Error handling message: player_queues/play_media: 'Channels'
```
No expert here but he can't seem to match the .ogg format

![image](https://github.com/music-assistant/hass-music-assistant/assets/3798321/9bdc5567-4bd2-4189-bd30-b2aba267b925)

I tried an .mp3 album and that seem to work fine.

![image](https://github.com/music-assistant/hass-music-assistant/assets/3798321/1e6b3ea1-b8d4-4c56-9ad1-473ca68b4bd1)

I had a similar issue with finamp APK, but was able to bypass it enabling trancoding in the settings.
I had no issues using the Jellyfin APK, the container is detected as ogg. 

### How to reproduce

Try to stream a .ogg file format from Jellyfin Music Provider

### Music Providers

 Jellyfin Music Provider

### Player Providers

Chromecast

### What version of Home Assistant Core are your running

2024.5.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
@lokiberra do you think a provider problem or core MA?

**Comment by lokiberra** [comment]
@OzGav  not sure yet....l will try to reproduce. I don't think anything is currently limiting transcoding and I don't see any function in the python api to enable or disable transcoding.

**Comment by Thijzer** [comment]
I already de-.ogg'd my library and now everything works fine.

**Comment by OzGav** [comment]
@lokiberra let me know if we should add a note about ogg not working or if this something we should ask Marcel about.

**Comment by Thijzer** [comment]
For context when relating to https://github.com/music-assistant/hass-music-assistant/issues/2313. I Used ffmpeg to encode my .ogg files + inherited the metadata of the source material also within ffmpeg.

**Comment by OzGav** [comment]
New version of ffmpeg is in use with 2.3.0b16 and above. Will track any further issues in #2313
