### ISSUE TITLE
Browser view duplication / formatting issues

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#2270]
### What version of Music Assistant has the issue?

2.0.2

### What version of the Home Assistant Integration have you got installed?

2024.5.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I noticed a bunch of browser issues on but my PC ( chrome) and iPhone (safari). It mainly concerns duplications in the listings.

### How to reproduce

I described a flow in discord: https://discord.com/channels/753947050995089438/1098939316861935698/1239299611990954067

### Music Providers

Spotify and TuneIn

### Player Providers

Na

### Full log output

No related log

### What version of Home Assistant Core are your running

2024.5.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by marcelveldt** [comment]
2.0.4 should fix the weird items listings

**Comment by erkr** [comment]
Not properly fixed yet. Still have to test on my PC tonight, but on my iOS app radio stations take a very long time to load (20+ seconds) and then still duplicates:
![image](https://github.com/music-assistant/hass-music-assistant/assets/4363599/1eef9bf2-4553-41a4-97a1-dd207bb6f77c)

**Comment by jonwaland** [comment]
Just pulled the 2.0.4 server, and seems to have fixed the duplicate entries issue I had.

**Comment by erkr** [comment]
For me 2.0.4 only fixed duplicate enties for Spotify, not for Tune-in Radio
The weird pathnames are stiull three (also for Spofity)
Showing the radio stations via the browser takes a long time, ca 25 seconds). Via the radio tab , this is instantly!
I tested on iOS companion, PC chrome and Edge
Example radio browser with weird path and double entries:
![image](https://github.com/music-assistant/hass-music-assistant/assets/4363599/b06207fe-4a00-42dc-8317-a1828dd73fd5)
On the mobile you don't see the path part. 

There are no related errors in the log file

**Comment by OzGav** [comment]
I can confirm the duplication for tunein

**Comment by OzGav** [comment]
Confirming this appears fixed in 2.1.0b4
