### ISSUE TITLE
Fully Kiosk Player Provider does not advance to next track in queue, does not properly display track progress

### ISSUE THREAD

**Issue by mterry63** [music-assistant/hass-music-assistant#2274]
### What version of Music Assistant has the issue?

2.0.2

### What version of the Home Assistant Integration have you got installed?

2024.5.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I have configured a Fully Kiosk Player provider with the IP address of a Fire Tablet 10" running Fully Kiosk 1.55.2 (newest version at time of testing). When selecting an album from any music provider, the first song will play and then music stops after the first song in the queue but play progress in the web interface continues to count past the run time of the song. Pressing next will play the next song with the same results at the end of the song. When testing with YouTube Music playlist, the first song plays then nothing else will play. 

Adding the FK media player into a Home Assistant dashboard, the progress bar shows complete during the song playing and doesn't change progress.

Changing queue settings in the player doesn't change the results. 

Adding the FK player into a universal group with a working Snapcast player and playing the group, the FK player does progress from track to track normally. In this test, the individual FK player in a dashboard does show the progress bar correctly.

### How to reproduce

See above problem description. In discussion on the Home Assistant Forum, it appears that Oz Gav confirmed that this is reproducible.

### Music Providers

Tested Music Assistant, YouTube, Plex music providers, all exhibit the problem. Did not find a music provider that did not exhibit the problem.

### Player Providers

Fully Kiosk provider exhibits the problem.

Snapcast provider dies not exhibit the problem.
Chromecast provider does not exhibit the problem.

As part of a universal group the FK player provider did not exhibit the problem.

### Full log output

[core_log.txt](https://github.com/music-assistant/hass-music-assistant/files/15288082/core_log.txt)

### Additional information

All testing directly from the Web UI. MASS running as a docker container. Both MASS and HA are running under Proxmox.

### What version of Home Assistant Core are your running

2024.5.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
I’ll put this up as an example of a perfect report! Thanks this will be looked at in due course

**Comment by mattdchap** [comment]
Same happening for me.  Thanks for adding to the backlog!

**Comment by marcelveldt** [comment]
Fully Kiosk players need to use the "flow mode" option in the player settings as they do not properly report they have stopped playing. This should be the default though (but apparently not)

**Comment by OzGav** [comment]
I have updated the backlog to catch that but there is still an issue as I tried with flow mode ON.

**Comment by pgale** [comment]
I have the same issue on my Lenovo ThinkSmart View devices running Fully Kiosk Browser. I have tried flow mode on and off and no difference. The track gets to the end and doesn't advance to the next and the timer keeps counting up. Manually advancing works but the position in the track seems to then get messed up.

**Comment by mikebumpus** [comment]
Having same issues as well on Fully Kiosk Browser with Spotify as the source. Have toggled Flow Mode and have same results both on and off.

**Comment by OzGav** [comment]
Yes this will be fixed in due course.

**Comment by pgale** [comment]
> Yes this will be fixed in due course.

Is this fixed in 2.0.6?

**Comment by OzGav** [comment]
I don’t see anything about it in the notes but do give it a try

**Comment by pgale** [comment]
> I don’t see anything about it in the notes but do give it a try 

I will this morning. 

Is there a prioritised list of fixes that are being worked on? Thanks.

**Comment by OzGav** [comment]
https://github.com/orgs/music-assistant/projects/2

That isn’t prioritised though. Marcel decides what to work on. I would say the priority is critical first then first in first out.

**Comment by pgale** [comment]
Ok thanks. 
I've just seen a breaking issue with SMB remote file share so need to log that too.

**Comment by marcelveldt** [comment]
This one should be fixed in 2.0.6 - it is at least on the test device I have here

**Comment by OzGav** [comment]
Yes seems to work here as well.

**Comment by mterry63** [comment]
It worked for me yesterday, but not today. I added 3 Fully Kiosk players and none of them will show track duration. They start for 2-3 seconds then stop and the play controls go to stopped, but music continues to play.

Also, the Fully Kiosk player process is not like the other player providers. In order to add a Fully Kiosk player you actually create the player provider, which automatically creates a player. If you delete the player, you have to delete the player provider before you can add it again. Also, to add a second Fully Kiosk player, you have to create a second player provider, which is not consistent with Snapcast for example.

**Comment by pgale** [comment]
I moved away from the media player in Fully Kiosk as there were several shortcomings. I installed snapcast on each Android device FKB is running on. Much better reporting of status and works :)
