### ISSUE TITLE
New DLNA/UPNP devices are created after each update

### ISSUE THREAD

**Issue by Smarthome-Creator** [music-assistant/hass-music-assistant#2275]
### What version of Music Assistant has the issue?

2.0.2

### What version of the Home Assistant Integration have you got installed?

2024.5.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Whenever an update of Music Assistant is installed, new DLNA devices are created that actually already exist. In this particular case, my Philips TV.
![image](https://github.com/music-assistant/hass-music-assistant/assets/61153058/45d8ba26-fd72-455f-873f-935309c2aed0)

I have already deactivated it as a target player, but it is always created again and cannot be used.

![image](https://github.com/music-assistant/hass-music-assistant/assets/61153058/2c921912-f5cd-44b4-af4c-48edb5893716)

I have other UPNP players on the network (HiFi-Pi) where this problem does not occur.
I therefore suspect that it is related to the Android TV itself. 

### How to reproduce

1. Delete the newly created players.
2. Updating the Music Assistant.
3. New players are created again.

### Music Providers

-

### Player Providers

UPNP/DLNA

### What version of Home Assistant Core are your running

2024.5.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
That is actually normal because the player just gets rediscovered. I think you just want to disable it.

**Comment by OzGav** [comment]
Oh actually maybe that is what you meant when you said deactivated…. Let me ask why multiple versions of the same player would appear

**Comment by Smarthome-Creator** [comment]
@OzGav , I don't know, this always happens when an update for Music Assistant is installed and only for the Philips Android TV.
It doesn't happen with my HiFi Berry with DLNA.

**Comment by OzGav** [comment]
OK not sure about this one. It will get looked at eventually. For now you will just have to keep deleting them!

**Comment by marcelveldt** [comment]
I have no idea what we can do about this as it seems that your TV has a bug and creates a new ID every time ?

**Comment by OzGav** [comment]
This doesnt seem like a MA issue so will be closed soon unless any new info can be provided?

**Comment by Smarthome-Creator** [comment]
Hi @marcelveldt , @OzGav ,I have now also switched from beta to stable release and deactivated DLNA. I'll just test it again when I get the chance and see how it behaves when an update comes on the stable channel.
Nevertheless, many thanks for your great work. It's simply a great project.
