### ISSUE TITLE
Sonos devices on different VLAN not found 

### ISSUE THREAD

**Issue by cskiwi** [music-assistant/hass-music-assistant#2276]
### What version of Music Assistant has the issue?

2.0.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I have 2 different VLAN's

One for my servers where I assign ip-addresses manually so I can easily remember them
And then the default one for any other device, where the dhcp is enabled
 
The global config is as following:

![image](https://github.com/music-assistant/hass-music-assistant/assets/847540/1a554adc-5c27-4c49-86a5-4f5bffb84c17)

From what I can see it doesn't scan the 192.168.1.0/24 network (see attached logs). and I have no option to configure it to do so

### How to reproduce

create 2 vlans and set your HA/MA in one, and add sonos devices to the other

### Music Providers

N/A

### Player Providers

SONOS

### Full log output

[log file](https://github.com/music-assistant/hass-music-assistant/files/15292620/ma.log)

### Additional information

Home assistant itself is able to find the SONOS players.

### What version of Home Assistant Core are your running

2024.5.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Alternative

**Comment by OzGav** [comment]
Please review the docs. We do not support complex network setups for this reason. Sorry.

**Comment by cskiwi** [comment]
Ah, found a solution. I was running on proxmox, So by adding a second virtual network interface running on the other VLAN. It scans it and adds the players
