### ISSUE TITLE
Media title repeated twice on Cast devices

### ISSUE THREAD

**Issue by OzGav** [music-assistant/hass-music-assistant#2282]
### Discussed in https://github.com/orgs/music-assistant/discussions/2268

<div type='discussions-op-text'>

<sup>Originally posted by **howesey2k** May 13, 2024</sup>
Hi, I was wondering if anyone can help me or has the same problem. When I play any song through the YouTube or Spotify add on in music assistant the media artist and media album show as the media title. They show correctly in the music assistant add-on. This seems to be since I have changed over from beta to stable. I have shutdown my pi and tried reinstalling the beta but still have the same problem.
![Screenshot_20240512-204650](https://github.com/music-assistant/hass-music-assistant/assets/76223973/49c39895-5bff-42c4-a8e4-b681522f8a61)
![Screenshot_20240512-204629](https://github.com/music-assistant/hass-music-assistant/assets/76223973/c84112c7-eaa0-47c1-8427-f3b21047ee28)
</div>

**Comment by OzGav** [comment]
It appears that the track name is shown twice, the album title is shown but the artist name is not.

**Comment by marcelveldt** [comment]
This is a bug in the HA integration, not the MA server

**Comment by marcelveldt** [comment]
Fixed in the next patch release (2.0.4)
