### ISSUE TITLE
FLAC + Cue albums are detected as a single track with duration of the full album.

### ISSUE THREAD

**Issue by Particpant** [music-assistant/hass-music-assistant#2284]
### What version of Music Assistant has the issue?

2024.5.1

### What version of the Home Assistant Integration have you got installed?

2.0..3

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

A library of albums ripped as single-file .flac, some with embedded, some with separate cuesheets are interpreted as Music Assistant as an album containing a single track, the full length of the album. The same library in LMS is properly detected as albums with multiple tracks.

### How to reproduce

Have a local library containing albums as single files with either embedded or separate cuesheets for thetags.

### Music Providers

Filesystem - remote share

### Player Providers

n/a

### What version of Home Assistant Core are your running

2024.5.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
This is not an issue it is a feature request. Kindly open a feature request discussion
