### ISSUE TITLE
Cannot install music-assistant==1.1.15 because these package versions have conflicting dependencies.

### ISSUE THREAD

**Issue by Mariusthvdb** [music-assistant/hass-music-assistant#229]
2022-05-24 09:38:54 ERROR (SyncWorker_5) [homeassistant.util.package] Unable to install package music-assistant==1.1.15: ERROR: Cannot install music-assistant==1.1.15 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
WARNING: You are using pip version 22.0.3; however, version 22.1.1 is available.
You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.

HA 2022.6.0.dev20220524

**Comment by marcelveldt** [comment]
Was there some additional info in there which packages conflicted ?

**Comment by Mariusthvdb** [comment]
not in the regular logs, no, this was all that was reported. and this:
```
Logger: homeassistant.setup
Source: setup.py:162 
First occurred: 10:44:46 (1 occurrences) 
Last logged: 10:44:46

Setup failed for custom integration mass: Requirements for mass not found: ['music-assistant==1.1.15'].
```
as a consequence.
Yesterdays dev nightly was still fine...

**Comment by marcelveldt** [comment]
OK, Frenck found out it is the Pillow dependency that has been bumped in HA core. 
I will adjust the MA library too. Fix in next release.

Thanks for reporting!

**Comment by marcelveldt** [comment]
Pushed version 1.1.6 which includes a fix for this issue. Thanks for reporting!

**Comment by Mariusthvdb** [comment]
confirmed. Back up and running!
thx for the quick fix.
