### ISSUE TITLE
Tracks are displayed before albums in artist view, the opposite would be more usable

### ISSUE THREAD

**Issue by elafargue** [music-assistant/hass-music-assistant#2293]
### What version of Music Assistant has the issue?

2.0.3

### What version of the Home Assistant Integration have you got installed?

2024.5.3

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Usability issue: when displaying an artist, the UI displays a list of all the tracks for that artist, before displaying the albums. For artists with a lot of tracks, this is not very usable, since there can be hundreds of individual tracks, meaning the user either needs to collapse the tracks or to scroll a long time before reaching the albums.

It would be nicer and more logical to start with the albums, and then display the tracks, since there usually be a lot fewer albums than tracks for a given artist.

### How to reproduce

Display an artist, tracks are showed first, albums second

### Music Providers

Subsonic

### Player Providers

uPNP, Airplay

### What version of Home Assistant Core are your running

2024.5.3

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by marcelveldt** [comment]
This is debatable because 50% of the users think it should be the other way around ;-)

Normally only a top X of artist tracks are shown (for streaming providers at least), do you have a lot of local tracks maybe ?

**Comment by elafargue** [comment]
Indeed, there’s definitely a personal preference aspect there.

With the Subsonic integration and a server with lots of tracks, it does lead to a list of up to 50 tracks for each artist. Maybe that could be a config option?

**Comment by OzGav** [comment]
The list of tracks is collapsible with one click. This is not an issue. You can open a Feature request in the discussions area if you wish.
