### ISSUE TITLE
V1.1.15: very long startup time

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#230]
This happened just one time: the startup time for MA took over 10 minutes:
![image](https://user-images.githubusercontent.com/4363599/170002130-6baea547-2a66-4d04-a3c2-5c992a37ce6b.jpeg)

The reason seemed to be a failed logon to Spotify:
```
This error originated from a custom integration.

Logger: custom_components.mass
Source: custom_components/mass/__init__.py:105 
Integration: Music Assistant (documentation, issues) 
First occurred: 10:57:38 (1 occurrences) 
Last logged: 10:57:38

Setup failed of provider spotify: Login failed for user ***Redacted***
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/__init__.py", line 351, in _register_provider
    if await provider.setup():
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/providers/spotify.py", line 72, in setup
    raise LoginFailed(f"Login failed for user {self.config.username}")
music_assistant.models.errors.LoginFailed: Login failed for user ***Redacted***

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/mass/__init__.py", line 105, in async_setup_entry
    await mass.setup()
  File "/usr/local/lib/python3.9/site-packages/music_assistant/mass.py", line 83, in setup
    await self.music.setup()
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/__init__.py", line 57, in setup
    await self._register_provider(prov_cls(self.mass, prov_conf), prov_conf)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/__init__.py", line 354, in _register_provider
    raise SetupFailedError(
music_assistant.models.errors.SetupFailedError: Setup failed of provider spotify: Login failed for user ***Redacted***
```
This is the log like just after the restart:
![image](https://user-images.githubusercontent.com/4363599/170004443-6795b551-bfc8-4eb0-92a9-dca9c2e9dff0.jpeg)

The next restart, it started fully normal within 6 seconds. 

If the failed logon indeed was causing a 10 minutes delay in starting HA, I think MA should not wait that long during startup.

**Comment by marcelveldt** [comment]
MA doesn't wait that long, HA waits for MA to finish setup. Unclear why it didn't continue after the failed setup.
Normally MA should report "I'm failed" and HA continues setup and retries MA setup a bit after.
As you can see these were all "handled" exceptions (thrown by my code) and nothing unhandled or unexpected

**Comment by erkr** [comment]
Yes that is correct, and nothing, as far I know of, was broken. 
I raised the issue because MA was the only integration with errors. The log didn't show more information.
It dient reproduce (tried some restarts).
I didn't try a restart with wrong credentials. I'm a little reluctant to do that, what to do if it hangs?

**Comment by marcelveldt** [comment]
Tested this and it behaves as designed. It will auto retry the setup as long as the setup failed on a known reason.
In this case there was likely some internet outage or just some spotify server that couldn't be reached.
So this is not an issue but actually good behavior given the fact that it manage to survive the failure after/within 10 minutes ;-)

**Comment by erkr** [comment]
Thanks for looking into it. Good to know it behaves correctly and it will not block a HA startup. 
Didn't happen again. Close the issue?

**Comment by erkr** [comment]
Not seen anymore....
