### ISSUE TITLE
Soundcloud doesn't work -'Attempt to decode JSON with unexpected mimetype'

### ISSUE THREAD

**Issue by swiftbird07** [music-assistant/hass-music-assistant#2301]
### What version of Music Assistant has the issue?

2.0.4 (Docker)

### What version of the Home Assistant Integration have you got installed?

2024.5.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I am unable to connect Soundcloud:

I will just print the error:
`0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://api-v2.soundcloud.com/me')`

### How to reproduce

1) Follow instructions at https://music-assistant.io/music-providers/soundcloud/
2) Get error

### Music Providers

Soundcloud

### Player Providers

None

### Full log output

[log.txt](https://github.com/music-assistant/hass-music-assistant/files/15320205/log.txt)

### Additional information

Screenshot: <img width="1504" alt="Screenshot 2024-05-15 at 12 51 18" src="https://github.com/music-assistant/hass-music-assistant/assets/48106483/54f13c1b-cbe7-4317-9f96-cfb39a9149b5">

I am using the docker install method as I don't have HAOS.

### What version of Home Assistant Core are your running

2024.4.4

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
@gieljnssns

**Comment by OzGav** [comment]
@swiftbird07 have you tried a different browser to setup the provider?

**Comment by danielkleinert** [comment]
I have the same issue in regardless of the browser I am using.

**Comment by The-Erf** [comment]
I have the same problem on all 3 versions, stable - beta - dev, on homeassistant, on other music providers, I have no problem

**Comment by OzGav** [comment]
Closing assumed fixed

**Comment by danielkleinert** [comment]
Sorry forgot to look into this earlier. The issue still persists. 

Maybe the Patch is not included in my version? HACS says I am on 2024.5.1 with MA saying it's on 2.0.4. 
I also could not find the fix in the commits....  🧐

**Comment by OzGav** [comment]
Will be in the beta and 2.0.5 when it comes out. Let us know if it isn’t working when that happens

**Comment by danielkleinert** [comment]
Does work in the current stable. 🎉

(Also i was trying to paste the track_authorisation from the URL and not the authorisation from the headers - probably contributed to the issue....)

**Comment by nimbling** [comment]
I'm getting the same error
`2024-08-27 09:17:03.356 ERROR (MainThread) [music_assistant.webserver] Error handling message: config/providers/save: 401, message='Attempt to decode JSON with unexpected mimetype: ', url='https://api-v2.soundcloud.com/me'`

I'm getting the:
O-Auth token (without "O-Auth ") from the inspect > Application tab > Storage > Cookies > https://soundcloud.com
client id from a search for "client_id" in the inspect > Network Tab

2.3.0b7 version of MAS

Does it matter that I'm trying this remotely?

**Comment by OzGav** [comment]
@nimbling Possibly. Try again when you are home

**Comment by nimbling** [comment]
I'm getting the same error at home using Safari and Chrome. Should I try setting the log level to more verbose?

[MAS.log](https://github.com/user-attachments/files/16806231/MAS.log)

**Comment by OzGav** [comment]
Please open a new issue and do NOT increase the log level but do include the whole thing from MA SETTINGS>> CORE

**Comment by nimbling** [comment]
Will do, thanks!

**Comment by nimbling** [comment]
Using Brave, this is working for me (just now) -now!

**Comment by nimbling** [comment]
By the way, I think the error was because I somehow managed to find and use the wrong OAuth key. There's more than one I think, and using the one mentioned in the readme (which I could not find at first) fixed this for me.

**Comment by maphouse** [comment]
I am having this exact issue. Was only able to find the oauth key via Inspect > Application > Storage > Cookie > oauth

**Comment by kristianschneider** [comment]
I'm afraid I am seeing the same issue

**Comment by OzGav** [comment]
Thanks we will have a look and make a note in the docs.
