### ISSUE TITLE
http://x.x.x.x:8095/#/playerqueue/ no longer works

### ISSUE THREAD

**Issue by cooljimy84** [music-assistant/hass-music-assistant#2302]
### What version of Music Assistant has the issue?

2.0.0148

### What version of the Home Assistant Integration have you got installed?

2024.5.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I have an automation to open http://x.x.x.x:8095/#/playerqueue/ on a tablet next to the sonos speaker when it's playing so you can quickly jump tracks etc, is there any why to jump straight to a players queue on the web interface.
This on longer goes any where when you open it

### How to reproduce

start playing music then try to access the /playerqueue/ 

### Music Providers

local, deezer

### Player Providers

sonos

### What version of Home Assistant Core are your running

2024.5.2

### What type of installation are you running?

Home Assistant Core

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
Sorry his was only temporarily available and has now been removed. However, functionality to do what you are after is being looked at so keep your eye on future updates.

**Comment by skavan** [comment]
Damn. Was so useful in HA dashboard. How else do we get one click to the current playlist?

<img width="340" alt="image" src="https://github.com/music-assistant/hass-music-assistant/assets/2557753/7a7ae1bd-67d2-484d-83a5-d5463202cc9c">
