### ISSUE TITLE
The Plex Music Provider marks every artist, album, and song as favorite.

### ISSUE THREAD

**Issue by cnf** [music-assistant/hass-music-assistant#2307]
### What version of Music Assistant has the issue?

2.0.4

### What version of the Home Assistant Integration have you got installed?

2024.5.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Every single Artist, Track, and Album from the Plex provider is marked as favorited.

I can manually unfavor them, but they should not be favored by default.

### How to reproduce

Add the Plex provider, and add your Plex music library

### Music Providers

Plex

### Player Providers

Not Applicable

### Full log output

No relevant log output found.

### Additional information

Creating issue on the request of @marcelveldt re this discord thread https://discord.com/channels/753947050995089438/1098863624073785364/1240278225423175801

### What version of Home Assistant Core are your running

2024.5.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
@cnf please confirm this is fixed in 2.1.0b4

**Comment by vhsdream** [comment]
Was having the same issue as @cnf and I can confirm that it appears to be fixed in 2.1.0b4

**Comment by cnf** [comment]
Sorry for the late response, I have been dealing with some personal things.

Can confirm Plex no longer favorites everything in 2.2.5

It also won't favorite anything starred, is this expected/intended?

Thanks!

**Comment by OzGav** [comment]
I don't use Plex so is a STAR the same as a favourite or can you give a item multiple stars (like a rating)?

**Comment by cnf** [comment]
Yep, it is a multiple star rating system, so no direct match to "favorite"

A setting to match "more than X stars maps to favorite in MA" would be nice, but that's a feature request, not a bug 
The report issue is no longer showing up in my current version, 2.2.5.

Thanks!
