### ISSUE TITLE
Incorrectly matches ISRCs for multi-movement pieces of music

### ISSUE THREAD

**Issue by MelHarbour** [music-assistant/hass-music-assistant#2316]
### What version of Music Assistant has the issue?

2.0.4

### What version of the Home Assistant Integration have you got installed?

2024.5.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Add a folder for a specific CD release via the Remote File Provider. If I add just the first track, it appears in Music Assistant. If I add the second file as well, then only the second file appears.

### How to reproduce

Add the remote file provider as a new provider, pointed at any empty share. Add the folder structure and the first mp3 and it appears. Add the second one, and the first one disappears. I can supply the files easily if requested.

### Music Providers

Remote File Provider shows the problem.

### Player Providers

N/A

### Full log output

[d5369777_music_assistant_2024-05-16T19-08-01.657Z.log](https://github.com/music-assistant/hass-music-assistant/files/15344856/d5369777_music_assistant_2024-05-16T19-08-01.657Z.log)

### What version of Home Assistant Core are your running

2024.5.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
The log shows access problems for your share that you need to resolve

**Comment by MelHarbour** [comment]
Yeah, I already resolved those. The problem is still showing after resolving them.

**Comment by MelHarbour** [comment]
I've also noticed that neither file appears under the Browse section:

![image](https://github.com/music-assistant/hass-music-assistant/assets/4092769/fec42ee5-568e-4896-999e-e76e891961cd)

**Comment by OzGav** [comment]
Please post another log without those access errors. There is likely something wrong with the tags in those files. However, I must admit I am not sure exactly what you are doing as you say you connect the share and then add a track. Normally all the tracks are already in the folder which you share?

**Comment by MelHarbour** [comment]
I'll try and get a cleaner log file this evening when I get home. Essentially I was trying to work towards as much of a minimal case as possible to isolate the problem. The files were part of a multi-disc release of about 150+ tracks, and I noticed the problem when MA was reporting only 80ish tracks within the album. Weirdly, if I asked the provider to resynchronise, exactly which tracks it was showing would vary (between a couple of common options). To try and isolate the problem I've reduced the number of files within the folder to just two, as the problem shows with just that many, rather than more. I created a whole new file share on a blank MA instance. I dropped in the folder structure and one track and ran synchronise and refresh so that it shows up. I then added the other track from my test case and ran synchronise and refresh again, and the first track, which was previously visible, disappears and the other one (the new one) appears.

**Comment by OzGav** [comment]
Are they all properly tagged with Picard?

**Comment by MelHarbour** [comment]
As far as I can tell, yes. The tracks I've got the minimal case with at the moment are the first two from this release:

https://musicbrainz.org/release/6fb68252-0c38-4d5a-8c1a-b3ea211bd8d2

They're tagged using Picard, and I've also told it to remove previous/unused tags to clean it up before applying them. I can't see anything obviously wrong.

**Comment by MelHarbour** [comment]
One thought - if you look at the Disc ID for the first disc in Musicbrainz, it's been used in a number of different releases:

https://musicbrainz.org/cdtoc/dQUYsj49JNdePZgktYiBd3vjHEo-

Is it possible that that's in some way confusing things?

**Comment by OzGav** [comment]
Ok will see what the log says then when you get the chance to upload it.

**Comment by MelHarbour** [comment]
Right, I've uninstalled and reinstalled, and have a fairly minimal test case to set out. First up, here's the log:
[log.log](https://github.com/music-assistant/hass-music-assistant/files/15355677/log.log)

I've put the two example files in a Google Drive share here:

https://drive.google.com/drive/folders/1_n_9YsRHsu7bKg8XD6iqN9JpOWMZMC-3?usp=drive_link

When I added the provider, I only had the first track in the relevant folder. The track listing for the album looks like this:
![Screenshot 2024-05-17 193135](https://github.com/music-assistant/hass-music-assistant/assets/4092769/2fe8adb4-06cc-44f7-8786-b8ed8ea63706)
I then add the second file to the folder and push synchronise. Following a refresh, the track listing now looks like this:
![Screenshot 2024-05-17 193250](https://github.com/music-assistant/hass-music-assistant/assets/4092769/26de8518-9912-41dc-b855-f785642b694b)

Note that the first track has now disappeared from the track listing for that album. The file is still there on the share. At no stage does the Browse view show any files at all.

**Comment by OzGav** [comment]
Thanks. I’m not home at the moment to try but I note that a significant part of the track name is the same and I wonder if we have a bug where it is only comparing the first x characters. Can you try taking one of those files and go into the tags and change the start of the track name slightly and see what happens? You could also post a side by side image of the tag info from Picard so we can see what is the same and what is different between the two tracks

**Comment by MelHarbour** [comment]
Changed the track Title tags to be Track A and Track B respectively. It just shows "Track B", so same behaviour as with the correct names.

Comparison of the tags for the two files:
![image](https://github.com/music-assistant/hass-music-assistant/assets/4092769/db0851f4-2c85-4a05-b3f1-f03457f5754a)

I can post the individual images of the two sets of tags as well if that helps.

**Comment by MelHarbour** [comment]
I tried putting it in debug logging mode (there were no revealing insights from the log, so not bothering posting it). After synchronising, it still only showed one track, but it was now the _first_ not the second one. I switched back to Info logging and it returned to showing the second track. Returning to debug again didn't move it back to the first track again.

That makes me feel like there's a race condition somewhere.

**Comment by OzGav** [comment]
Ok let’s wait for Marcel to have a look

**Comment by MelHarbour** [comment]
Having another play around this to see if I can get any more information. Currently both tracks appear under Browse:
![image](https://github.com/music-assistant/hass-music-assistant/assets/4092769/07386dd8-562a-4a1c-afe2-3974de7594a9)

But still only one showing when looking at the album, or tracks view.

**Comment by MelHarbour** [comment]
Clicking through to 'Info' on the track that doesn't appear gives this screen, which has an interesting contradiction:
![image](https://github.com/music-assistant/hass-music-assistant/assets/4092769/121921c0-58a3-4e25-9eda-220e38207eda)
Notice that near the top, it's aware of the album that it relates to, but the 'Appears on' section is blank. So it's like, for whatever reason, it's only half hooking it up.

**Comment by MelHarbour** [comment]
And further odd behaviour to try and help pin it down. If I favourite the track that doesn't appear, via the Browse interface, the album listing switches over so it's now only displaying that track. But now when I look at the individual items, one of them has its providers horribly confused, and lists the provider information for both tracks. So it does appear to be conflating them in some way.

**Comment by OzGav** [comment]
Yeah it is an interestng one as everything seems OK. Can you update the original post with a clean log that doesn't show those access errors just so it is easier to read. What happens if you try and import the whole CD do other tracks also not appear? Do other albums of yours import OK, that is, is it just this one?

**Comment by MelHarbour** [comment]
I'll try and get a clean run captured tomorrow. I fed it the entire disc, and it displayed two tracks. The structure of that disc is that there are 8 tracks, but split up as two sets of 4 (two symphonies, with four movements each). It displayed the first movement of each symphony. That would tend to suggest it may be something to do with their names. I'll try and do a clean run and then play around with either the file names, or the tagged track names.

I'll have a look as well at when MA generates a URI, unique ID or hash for each track and see whether there's anything in there that would generate something that collides in some way.

**Comment by OzGav** [comment]
Yes it sounds like MA is linking these together but the tags look good and you tried renaming so I am missing something.

**Comment by MelHarbour** [comment]
I think from the sound of it this issue is probably at least partially a duplicate of mine:

https://github.com/music-assistant/hass-music-assistant/issues/2425

I'll continue to try and get a clean log file. I tried a more 'interesting' set of imports that I think helps gradually close in on what's going on. I imported three CDs. Two of them are actually the same (Carlos Kleiber) one, that were released in different releases. The albums are deduplicated by MA, so only one of them shows in the UI. The other was more like a regular 'modern' album (Dire Straits, FWIW!) and all the tracks are correctly imported. So it definitely appears that it's something to do with the way MA is handling the import of multi-movement pieces of music.

Nothing completely concrete yet on what's going on, but adding observations as I come up with them.

**Comment by MelHarbour** [comment]
Got it (I think!).

![image](https://github.com/music-assistant/hass-music-assistant/assets/4092769/e63183a0-c948-4a63-992a-503d7c52227f)

Based on reading the other issue that was raised, I had a look at the ISRC field. Note that for one of these tracks, it lists two ISRCs. The first is the same on each track in a movement, the second changes each time. As an experiment I deleted the unchanging one, and the tracks start appearing correctly.

I'll have a read through the code and see if I can see where it mis-parses the ISRCs.

**Comment by OzGav** [comment]
@marcelveldt an interesting find here I think

**Comment by marcelveldt** [comment]
Why does it have the same ISRC on multiple tracks of the same album? isrc is supposed to be unique per recording

**Comment by MelHarbour** [comment]
I'm looking into that - I'm not sure.

The behaviour is definitely from this code:

https://github.com/music-assistant/server/blob/de95ebf314576d566b00beb982c26380a3af8cde/music_assistant/server/helpers/compare.py#L321

Which is matching the ISRCs and deciding they're the same piece of music. I wonder if it's to do with how multi-movement pieces of music are tagged. So in this instance, both of the files represent a part of Beethoven's 5th Symphony. Thinking aloud, I wonder whether some release of it considered them to be all in the same piece of music, and then in a remaster at some point they got split into tracks. I'll let you know what I find.

**Comment by marcelveldt** [comment]
Oh crap what an edge case - who on earth decided its a good idea to just assign the same unique id to multiple parts ?!!
Why not postfix it with something.

Note that you can have multiple ISRC's per track as one recording can have multiple releases (per country/catalog etc).
I'm going to have a good think about how to handle this but for now I would recommend you to simple remove the ISRC's from the music so its not used for matching at all anymore.

**Comment by marcelveldt** [comment]
Question: would the title and/or track number differ in these cases ? Because we could consider adding an additional sanity check and only accept ISRC match if there is a secondary match as well, such as title or disc number

**Comment by MelHarbour** [comment]
I'll try and have a think about that suggestion.

In the meantime, that overall release (a multi-disc combination) isn't even consistent on whether it has 'symphony-wide' ISRCs:

https://magicisrc.kepstin.ca/?mbid=6fb68252-0c38-4d5a-8c1a-b3ea211bd8d2

Note that the first disc has an extra ID per symphony, but some of the later discs don't. Gotta love some consistency...

**Comment by MelHarbour** [comment]
I feel like whichever way you go, you're going to get errors!

Reading the comments online, ISRC is a bit of a minefield as some publishers have a habit of reissuing ISRCs 'just because'.

**Comment by MelHarbour** [comment]
> Question: would the title and/or track number differ in these cases ? Because we could consider adding an additional sanity check and only accept ISRC match if there is a secondary match as well, such as title or disc number

Thinking about it, I don't think either cuts it. In my test example, I have the same track with two different titles ("Symphony" vs "Symphonie") and different tracks with the same ISRC and disc number.

**Comment by MelHarbour** [comment]
In my case, given the metadata autopopulated from MusicBrainz via Picard, the best item for discriminating would be MusicBrainz Recording ID. But that may well not be a universally held truth. Suggestion @marcelveldt would be check if ISRCs match, and then if different MB Recording IDs, invalidate that match. How would that sound? I could drop a PR in for that if not clear what I mean.

**Comment by marcelveldt** [comment]
Ah yes that is a good idea. So the MusicBrainz Recording ID IS in fact different then in this case?
But we already have that check in place. We consider musicbrainz id's as a strong identifier so if that is present in both A and B and differs, it will reject the match. Problem is that that code is in the same comparison as isrc and whoever wins, wins.

So we need to make a difference between the 2 here
https://github.com/music-assistant/server/blob/de95ebf314576d566b00beb982c26380a3af8cde/music_assistant/server/helpers/compare.py#L116

MusicBrainz ID match --> STRICT = reject if both present and A != B
ISRC match --> SOFT MATCH = requires one other soft match like title or whatever

And then we need to make sure that the strict ID match is always executed before the soft match

Can you follow and do you agree ?

**Comment by MelHarbour** [comment]
I certainly agree on the first part. If MBID don't match, it should reject the match.

I'm less clear on the second.

I would probably go for just adding the first part in and see how it plays. I've created a PR with that as an example.

https://github.com/music-assistant/server/pull/1370

**Comment by MelHarbour** [comment]
Just tried it again on beta 7 and the problem still happens. I'll have a bit more of a look through.

**Comment by MelHarbour** [comment]
From discussion on Discord, turns out the problem is to do with a bug in ffmpeg, where it's not parsing the MB recording id correctly from the file. Looking into how to make this a bit more robust.

**Comment by marcelveldt** [comment]
> From discussion on Discord, turns out the problem is to do with a bug in ffmpeg, where it's not parsing the MB recording id correctly from the file. Looking into how to make this a bit more robust.

I just added a small workaround for reading the music brainz recording id for mp3 files - apparently ffmpeg skips this tag only for mp3 files, other filetypes work just fine

**Comment by MelHarbour** [comment]
Still broken on beta 8, unfortunately.

![image](https://github.com/music-assistant/hass-music-assistant/assets/4092769/85b12980-2daf-4c44-b133-e1d296585f48)

**Comment by MelHarbour** [comment]
Confirmed fixed in beta 11
