### ISSUE TITLE
TTS from does not play and does not stop the music on squeezelite (PiCorePlayer)

### ISSUE THREAD

**Issue by pzdpro** [music-assistant/hass-music-assistant#2318]
### What version of Music Assistant has the issue?

2.1.0b0

### What version of the Home Assistant Integration have you got installed?

2024.5.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When MA plays music i cannot send TTS to the speaker. Just nothing is happening.

### How to reproduce

Start music on MA 
Try to play announcements from node red

### Music Providers

YT
TIDAL

### Player Providers

PiCorePlayers by slimproto

### Full log output

[log.txt](https://github.com/music-assistant/hass-music-assistant/files/15346165/log.txt)

### Additional information

I play annoucements from node red. Using LMS it works propertly. when i run MA i play on the speaker any music and then stop it the player is "blocked"

### What version of Home Assistant Core are your running

2024.5.3

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
You have ticked the box saying you have wad the troubleshooting page but you have not supplied all of the required information. Please do so.

**Comment by pzdpro** [comment]
Hi OzGav,
I added additional information. I search in all issues but cannot find any answer. Just like i wrote:
I play annoucements from node red. Using LMS it works propertly. When i run MA i play on the speaker any music and then stop (or not) it the player is "blocked"
After rebooting HA annoucements works. It stops working only when i start use MA.

**Comment by pzdpro** [comment]
So sorry mates. I just see that i had running two MA (old and beta).
It works. Thank you!
