### ISSUE TITLE
Music Assistant add-on won't start

### ISSUE THREAD

**Issue by madbrain76** [music-assistant/hass-music-assistant#2322]
### What version of Music Assistant has the issue?

Cannnot access settings

### What version of the Home Assistant Integration have you got installed?

2024.5.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

The add-on won't start after initial installation

### How to reproduce

Install the add-on
Press "start".

### Music Providers

N/A

### Player Providers

N/A

### Full log output

I cannot access MA settings, as the add-on is not starting up. Providing the debug log instead, since that's the only thing I have got.
[madebug.log](https://github.com/music-assistant/hass-music-assistant/files/15359399/madebug.log)

### Additional information

I have a pretty big LAN/WLAN with nearly 170 IP devices. But nothing unusual, no VLANs.
In terms of audio devices, this includes 12 Wiim Pro Plus devices, maybe 5 Google cast devices, some Fire sticks. 

It appears MA might be stuck on the zeroconf broadcast.

### What version of Home Assistant Core are your running

2024.5.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Windows

**Comment by OzGav** [comment]
Are you deliberately starting in safe mode?

**Comment by madbrain76** [comment]
> Are you deliberately starting in safe mode?

Yes. When starting normally,  it fails too, but with much less information.

**Comment by OzGav** [comment]
Please attach a log not in safe mode so we can see what that looks like

**Comment by madbrain76** [comment]
> Please attach a log not in safe mode so we can see what that looks like
> 
> edit: I just saw your post on the forum. Why do you think the addon has not started?

The log without safe mode is atttached in this post - same as in the forum.

[ma_nodebug.log](https://github.com/music-assistant/hass-music-assistant/files/15359696/ma_nodebug.log)

As to why I believe it's not running, it's because HA says "The add-on is not running" when I open the Music Assistant tab.

![image](https://github.com/music-assistant/hass-music-assistant/assets/57333073/6328c406-37ee-4404-ba77-90953531f842)

**Comment by frawau** [comment]
What does it show if you go to
    Setttings - > Add-ons -> Music Assistant ?

FWIW I have a similar set-up and it works fine. (Only 112 devices on my LAN ;)
    Core 2024.5.4
    Supervisor 2024.05.1
   Operating System 12.3
   Frontend 20240501.1

running on a Raspberry Pi 5

**Comment by madbrain76** [comment]
Not seeing anything unusual in settings/add ons/Music assistant.  Screenshot attached.

![Screenshot_20240517_234219_Home Assistant](https://github.com/music-assistant/hass-music-assistant/assets/57333073/6d5a431d-054c-4940-a70c-5bac1771fa1b)

Looks like the add on is running automatic cleanup every hour, but the MA tab still says it's not running.

**Comment by madbrain76** [comment]
I do get the expected 

  <body>
    <noscript>
      <strong
        >We're sorry but musicassistant-frontend doesn't work properly without
        JavaScript enabled. Please enable it to continue.</strong
      >
    </noscript>
    <div id="app"></div>
    
  </body>
</html>

Output when I run

curl 172.30.32.1:8095

**Comment by OzGav** [comment]
Have you restarted HA? Have you restarted the host?

**Comment by madbrain76** [comment]
HAOS yes. The host no. Will try now.

**Comment by madbrain76** [comment]
Rebooting the host fixed it. I find that exceedingly strange. Any reason why this should be required ?

**Comment by OzGav** [comment]
I assume it isn HA supervisor problem.
