### ISSUE TITLE
HomePod control with iPhone (iOS) is missing

### ISSUE THREAD

**Issue by chochb** [music-assistant/hass-music-assistant#2324]
### What version of Music Assistant has the issue?

 2.1.0b0

### What version of the Home Assistant Integration have you got installed?

2024.5.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

There are 2 problems that have the same cause, I think.

When I start a stream from MA on a HomePod, I can't control the music from an iPhone/Siri.

When I start a stream with Siri or from the iPhone on a HomePod, I can't control it with MA.

### How to reproduce

Start music and check whether you can control it on the iPhone or with Siri.

### Music Providers

MA: Local, TuneIn
HomePod: AppleMusic

### Player Providers

AirPlay

### What version of Home Assistant Core are your running

2024.5.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
This is not an issue. MA does not have this functionality. Search for “Siri” in the discussion area for more info
