### ISSUE TITLE
Recently Played Tracks page sometimes repeats the list infinitely

### ISSUE THREAD

**Issue by lordbah** [music-assistant/hass-music-assistant#2325]
### What version of Music Assistant has the issue?

2.0.4

### What version of the Home Assistant Integration have you got installed?

None

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Recently Played Tracks page appends infinite copies of the list as you scroll down.

### How to reproduce

Click on the Recently Played Tracks playlist. Try to scroll down to the end. You can't because it keeps appending more copies of the list and lets you scroll down infinitely.

I can not reproduce this today. I saw it yesterday and someone else in Discord confirmed seeing it.

### Music Providers

Plex is the only music provider installed

### Player Providers

Chromecast is the only player provider installed

### Full log output

If I am able to reproduce the issue then I will attach the log.

### Additional information

Firefox 125.0.2.

### What version of Home Assistant Core are your running

N/A

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
Please try and find a way to reproduce,

**Comment by OzGav** [comment]
I just tried this and I had 250 unique tracks in the list. If you aren’t able to reproduce this we will close soon and ask you to monitor and report again if/when it is reproducible.

**Comment by OzGav** [comment]
Can reopen if this can be reproduced
