### ISSUE TITLE
Use Navidrome Playing Ape format music usually stops after about 10 seconds of normal playback, then skips and plays the next track,

### ISSUE THREAD

**Issue by ray154856235** [music-assistant/hass-music-assistant#2329]
### What version of Music Assistant has the issue?

2.0.4

### What version of the Home Assistant Integration have you got installed?

2024.5.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Use Navidrome Playing Ape format music usually stops after about 10 seconds of normal playback, then skips and plays the next track,

The media library is connected to the navidome media server using the Open Subsonic Media Server Library, and the music in the navidome media library is stored on a network drive,

### How to reproduce

use the Open Subsonic Media Server Library Play Ape format music

### Music Providers

when use SMB is fine

### Player Providers

There is no problem with the MP4 Flac format

### What version of Home Assistant Core are your running

2024.5.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
@khers

**Comment by khers** [comment]
I don't have any music in this formal but am happy to convert some, do you have a working ffmpeg command line that will do it?

**Comment by OzGav** [comment]
We will close this soon if there is no further followup (apologies if there has been private comms)
