### ISSUE TITLE
Confusing heart-icon outline/fill was is what?

### ISSUE THREAD

**Issue by GrumpyMeow** [music-assistant/hass-music-assistant#2332]
### What version of Music Assistant has the issue?

2.1.0b0

### What version of the Home Assistant Integration have you got installed?

2024.5.4

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I'm giving Music Assistant a try again. I keep switching between Plex, Jellyfin, Music Assistant, etc.
So far i'm happy with the experience of Music Assistant. Good job!

Not really a problem, but i find the favourite icon (heart) very confusing about what icon-version indicates that it's marked as a favourite. This is probably because i'm a new user. My advise would be to give the icon a red-color to indicate it is a favourite. This is a more universal approach.

![image](https://github.com/music-assistant/hass-music-assistant/assets/12073499/175ee443-16d6-4da0-9012-a4df57a310ba) Thanks!![image](https://github.com/music-assistant/hass-music-assistant/assets/12073499/bbbfc8ad-f24c-48e9-a40c-8153750519f3)

### How to reproduce

Take the screenshot below as example.. 
* White (only outline) icon is "brighter", than the "filled" icon version. So that might mean "marked as favourite".
* But when i think of a "radiobutton" then a "filled" icon version, means selected. So that might also mean "marked as favourite".
It makes my brain hurt 
![image](https://github.com/music-assistant/hass-music-assistant/assets/12073499/c63463e1-d2a6-4110-9a87-994e7ba33243)

### Music Providers

N/A

### Player Providers

N/A

### What version of Home Assistant Core are your running

2024.5.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
This is a feature request not an issue. Raise it in the discussions area and see if it gets any traction
