### ISSUE TITLE
unable to find 'musicVisualHeaderRenderer'

### ISSUE THREAD

**Issue by backslashV** [music-assistant/hass-music-assistant#2335]
### What version of Music Assistant has the issue?

2.0.4

### What version of the Home Assistant Integration have you got installed?

N/A

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Error when selecting a YT Music track.
![image](https://github.com/music-assistant/hass-music-assistant/assets/8752221/70ae69d0-4230-4f92-8f7f-cc755c163081)

### How to reproduce

Like [this ](https://www.youtube.com/watch?v=T2HRyIQnpvo)song on YT. Try to play it in MA.

### Music Providers

YT Music

### Player Providers

Sonos Move

### Full log output

[log.log](https://github.com/music-assistant/hass-music-assistant/files/15370701/log.log)

### What version of Home Assistant Core are your running

2024.5.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
@MarvinSchenkel

**Comment by backslashV** [comment]
Hi, any comments on the issue? it's still seen on v2.0.6

**Comment by MarvinSchenkel** [comment]
> Hi, any comments on the issue? it's still seen on v2.0.6

Sorry I have been very busy with the Apple music provider. Will give YTM some more love soon :-). The error is definitely coming from the downstream library that is used. One thing I did notice is that the 'song' is actually a video. This should be supported, but hey, YTM has lots of edge cases so I will need to dive into this one.

**Comment by MarvinSchenkel** [comment]
Implemented a workaround which will be available in the next patch release.

**Comment by backslashV** [comment]
> Implemented a workaround which will be available in the next patch release.

Hi, when will this release be out?

**Comment by MarvinSchenkel** [comment]
> > Implemented a workaround which will be available in the next patch release.
> 
> Hi, when will this release be out?

We are currently testing the next major release. If you want you can check it out in the beta channel
