### ISSUE TITLE
no shortcut added to sidebar 

### ISSUE THREAD

**Issue by elgatho** [music-assistant/hass-music-assistant#2339]
### What version of Music Assistant has the issue?

2024.5.1

### What version of the Home Assistant Integration have you got installed?

2024.5.4

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

when installing docker instance and adding plugin to home assistant no shortcut, on sidebar

### How to reproduce

install addon on homeassistant

### Music Providers

n/a

### Player Providers

n/a

### What version of Home Assistant Core are your running

2024.5.1

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
https://music-assistant.io/faq/how-to/#get-the-ma-icon-in-the-ha-sidebar
