### ISSUE TITLE
Unable to play music to RoPiee Airplay player

### ISSUE THREAD

**Issue by kcossabo** [music-assistant/hass-music-assistant#2341]
### What version of Music Assistant has the issue?

2.0.4

### What version of the Home Assistant Integration have you got installed?

not found might be the issue

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I started the install from https://www.home-assistant.io/blog/2024/05/09/music-assistant-2/

Clicked on the 'show add-on' - https://my.home-assistant.io/redirect/supervisor_addon?addon=d5369777_music_assistant&repository_url=https%3A%2F%2Fgithub.com%2Fmusic-assistant%2Fhome-assistant-addon

This did the install

I added my files via SMB and MA sees the music

I added AirPlay and MA sees my speakers

I can not play anything, nothing actually plays.

Select a speaker, see music in the queue, but the play button does nothing.

Log showing 

`2024-05-21 08:25:26.613 WARNING (MainThread) [music_assistant.players] Ignoring command cmd_volume_set for unavailable player ap9c760e8978bc
2024-05-21 08:25:27.609 DEBUG (MainThread) [music_assistant.helpers.process.ffmpeg_image] Process ffmpeg_image started with PID 528
2024-05-21 08:25:27.624 DEBUG (MainThread) [music_assistant.helpers.process.ffmpeg_image] Process ffmpeg_image started with PID 529
2024-05-21 08:25:28.670 DEBUG (MainThread) [music_assistant.helpers.process.ffmpeg_image] Process ffmpeg_image with PID 528 stopped with returncode 0
2024-05-21 08:25:28.729 DEBUG (MainThread) [music_assistant.helpers.process.ffmpeg_image] Process ffmpeg_image with PID 529 stopped with returncode 0
2024-05-21 08:25:30.009 DEBUG (MainThread) [music_assistant.webserver] Handling command player_queues/play_pause
2024-05-21 08:25:30.015 ERROR (MainThread) [music_assistant.webserver] Error handling message: CommandMessage(message_id=53, command='player_queues/play_pause', args={'queue_id': 'ap9c760e8978bc'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/webserver.py", line 351, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/player_queues.py", line 601, in play_pause
    if self._queues[queue_id].state == PlayerState.PLAYING:
       ~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'ap9c760e8978bc'`

the 'error' occured when I tried to play from the Mac Studio I am on as an output.

### How to reproduce

no idea.

Is there suppose to be a HACS integration, beyond the addon? not sure how to get that if there is.

I also installed the unRAID App / Docker version. Same issues, except the Mac Studio will play music, the Airplay do not.

### Music Providers

Local Files

### Player Providers

Juke AMP

### Full log output

[d5369777_music_assistant_2024-05-21T12-41-59.119Z.log](https://github.com/music-assistant/hass-music-assistant/files/15389953/d5369777_music_assistant_2024-05-21T12-41-59.119Z.log)


### Additional information

_No response_

### What version of Home Assistant Core are your running

2024.5.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by kcossabo** [comment]
> You you tried adding the snapcast provider and playing to a browser tab?

Not sure what a 'snapcast' is but will look into this.

> edit: also please review the requirements for submitting these reports. You haven't attached the full log and the log excerpt you have attached is at debug level.

I attached - [d5369777_music_assistant_2024-05-21T12-41-59.119Z.log](https://github.com/music-assistant/hass-music-assistant/files/15389953/d5369777_music_assistant_2024-05-21T12-41-59.119Z.log)

Which was generated from Home Assistant, Settings, logs, Music Assistant. What is the issue, you want a lower level of logging on that? I know that the embedded log is a snap, I provided that as a flow of the discussion, but included, what I assume is being asked.

> We also ask that you list what you have tried from the troubleshooting page that hasn't helped otherwise we just back and forward asking the same questions all the time,

I have HIT THE PLAY BUTTON, not sure what else I can do. I posted the install steps, and I hit play with nothing happening.  I installed a DOCKER version. Those are the steps I took.

I will review the instructions once again, but I do not see trouble shooting steps.

I am sure this is a user error, but the instructions do not help me resolve what should have been a simple 

1 - Push web button to install
2 - add Music via SMB mount
3 - add Airplay
4 - hit play

Open to trouble shooting, but logs give no errors, web interface gives no errors, excluding de-installing, not sure what else I can do.

**Comment by kcossabo** [comment]
With Respect To 'snapcast' I have never used it so not sure what to expect, but, I believe it is not working.

<img width="1568" alt="image" src="https://github.com/music-assistant/hass-music-assistant/assets/6267080/50c43314-08df-4405-9fd4-b4b988ac2b8a">

then for the players there is no new player

<img width="1275" alt="image" src="https://github.com/music-assistant/hass-music-assistant/assets/6267080/71ca999f-3c82-48bd-a53c-a706703af5fb">

there are two Mac's machine names, and they do not play music.

**Comment by OzGav** [comment]
> What is the issue, you want a lower level of logging on that?
 
No we want you to follow the instructions. 
 > Please DOWNLOAD then DRAG and DROP the full log output from MA SETTINGS>>CORE into the field below. Please do NOT use debug logging unless asked to do so.

I appreciate you haven’t used Snapcast before so from the docs 

> Clients are created by pointing a browser or Snapdroid at <YOUR_MA_IP_ADDRESS>:1780. The browser tab must remain open to maintain the stream.

Going back to the troubleshooting docs go through the page and then write here what was suggested and why you think it isn’t relevant or didn’t work. For example, most of these problems are network related so just list why you think your network setup isn’t contributing.

**Comment by kcossabo** [comment]
OkI am out tomorrow and will attempt to better get you what is needed. Thank You for the help. WRT the network it is a 48 port 1GE PoE switch connected to a 24 port 1/10GE PoE switchAll clients are in VLAN 40, and as AirPlay is a MDNS service I would have assumed seeing the speakers would prove the raspberry pi is in the same broadcast domain?What other network issues should I look for? It should present as a single 10.10.0.0/16 network. Sorry about the log levels I assumed when debugging people would want all the information. Will have sometime to work this on Thursday. Thank You again. Sent from my iPhoneOn May 21, 2024, at 7:46 PM, OzGav ***@***.***> wrote:﻿

What is the issue, you want a lower level of logging on that?

No we want you to follow the instructions.

Please DOWNLOAD then DRAG and DROP the full log output from MA SETTINGS>>CORE into the field below. Please do NOT use debug logging unless asked to do so.

I appreciate you haven’t used Snapcast before so from the docs

Clients are created by pointing a browser or Snapdroid at <YOUR_MA_IP_ADDRESS>:1780. The browser tab must remain open to maintain the stream.

Going back to the troubleshooting docs go through the page and then write here what was suggested and why you think it isn’t relevant or didn’t work. For example, most of these problems are network related so just list why you think your network setup isn’t contributing.

**Comment by OzGav** [comment]
Yes make sure that MA and all clients are in the same subnet. We have seen situations where some data gets through and not others. Firewall rules also have blocked access in the past.

**Comment by kcossabo** [comment]
I may just need to delete this and try something else. 

"Full log output
Please DOWNLOAD then DRAG and DROP the full log output from MA SETTINGS>>CORE into the field below. Please do NOT use debug logging unless asked to do so."

[log.txt](https://github.com/music-assistant/hass-music-assistant/files/15417328/log.txt)

With Respect To the 'trouble shooting page" Here is as much detail as I can give;

--- 

> Probably the most common issue is people trying to run MA with complicated network setups. Running behind VPNs, across subnets or VLANs, ....
> 
Not my issue same VLAN

> There are settings available in MA SETTINGS>>CORE>>STREAMSERVER>>CONFIGURE>>ADVANCED that might help you if you have complicated setups. I....

I am not "If you are running MA in your own docker container "

> Most players are discovered using mDNS (broadcast) so if your players do not get discovered it means that your network is blocking that traffic (e.g. IGMP or multicast snooping or filtering).....

Players are being discovered

> Make sure the HA internal url is set correctly. HA SETTINGS>>SYSTEM>>NETWORK>>Home Assistant URL>>Local network (set to automatic or use your internal HA IP). If it is automatic you can try changing it to <http://your.internal.ip:8123/>](http://your.internal.ip:8123/)

Set to http://10.10.0.20:8123/
IP of HA is 10.10.0.20, and MA is set to this in MA->Settings-> core -> Streemserver

> MA streams at high quality which may max out poor network connections. If possible use wired connections for MA players. Input codec is not always the same as the output codec (which is FLAC)....

HA is on a 1GE Wired Connection, the Player is on a 1GE Wired connection both in same VLAN, no Wifi involved.

> Check the physical device settings. There have been numerous reports where the issue was actually a setting external to MA such as receivers set to repeat tracks or ESP devices with incorrect arguments passed on install.

All device work with
- PlexAMP
- ROON
- MooDe

They do NOT WORK with this app (Airplay)

> Ensure local files are [tagged properly](https://music-assistant.io/music-providers/filesystem/#tagging-files).

All files are tagged correctly and work with 
- PlexAMP
- ROON
- MooDe

> Review the applicable player or music provider documentation to see if there are known issues or specific troubleshooting steps or fixes.

All device work with
- PlexAMP
- ROON
- MooDe

> Try power cycling the physical player(s) if they won't connect or if there is no sound.

Done, no effect, except interruption of other services that were working fine.

> If after an update something isn't working then trying clearing the cache MA SETTINGS>>CORE>>CACHE CONTROLLER>>CONFIGURE>>CLEAR CACHE. If that doesn't fix it then check the GitHub Issues and Discord to see if it is a known problem. If not try restarting MA, try restarting HA, and try a full HOST REBOOT (in that order). If it is an integration problem then trying removing it from HA settings and HACS then restart HA then reinstall.

AirPlay has not worked at all

> Before you raise an issue [read this first](https://music-assistant.io/support/). Report issues using the template with as much detail as possible. Often posts aren't clear about exactly what is typed where, how something is configured or what series of menus are selected. Screenshots can be helpful. DOWNLOAD and ATTACH complete logs from MA settings>>CORE. You can also look in the Browser console when you have front end issues which in Chrome browser is --> F12 for developer tools --> console. Please include the following in ALL reports:

Trying to do this, but starting to feel it is not worth the effort.

```
- What music provider is in use when the problem is observed? What other music providers have you tried (if you have no others then make that clear)
```

Local Files

```
- What player provider is in use when the problem is observed? What other player providers have you tried (if you have no others then make that clear)
```

ALL AIRPLAY devices, AppleTV Juke Amp

```
- Are the players grouped?
```

NO

```
- How is playback being instigated (e.g. automation or via the UI)
```

UI

```
- If you aren't using HAOS then exactly how you have installed MA
```

PLEASE see above, detailed this before

```
- What is working (e.g. player works with music provider X but not Y)
```

Though I still have not figured out "Snapcast" I did convert one of the inputs on the JukeAmp to UPnP/DLNA and that does work. AirPlay does not

```
- What you have tried from this page that hasn't helped
```

NO COMMENT

--- 


## Please NOTE

This will work to DLNA but not AIRPLAY, where EVERY OTHER solution (excluding Roon's latest software update that is a bug on ROON) plays to the AIRPLAY devices.

**Comment by OzGav** [comment]
Ok so sounds like it is an Airplay problem. Have you tried with encryptions on and off? Have you tried with compression on and off?

**Comment by OzGav** [comment]
We will close this soon if there is no follow-up

**Comment by kcossabo** [comment]
FineI can not fix the AirPlay issue. You do not want more longs. Not sure how I can resolve this. Sent from my iPhoneOn May 26, 2024, at 8:52 AM, OzGav ***@***.***> wrote:﻿
We will close this soon if there is no follow-up

**Comment by OzGav** [comment]
You haven’t advised if you have tried encryption on and off ?

**Comment by kcossabo** [comment]
Not sure how that did not get updated.I tried Encryption and Compression on / off, each combination and permutation. Fist setting it, then saving testing repeating through the combinations, then repeating each combination, saving and restarting the service.No effect. I also removed the addon, and re-did the install no change.I added two DLNA endpoints, that are on the same subnet but on wireless not wired (all testing to this point is wired) and MA has not scene them through autodiscovery.I have Wire Shark Traces of HA to the Amp of Airplay attempts if you wish them. I can see there is traffic when I attempt to play airplay.Sent from my iPadOn May 26, 2024, at 6:28 PM, OzGav ***@***.***> wrote:﻿
You haven’t advised if you have tried encryption on and off ?

**Comment by OzGav** [comment]
Now that you are advising DLNA is not being discovered this is starting to sound like a network problem. People in the past have identified network rules and router settings that have adversely affected the discovery and playback process.

**Comment by kcossabo** [comment]
Once again, it does discover a DNLA host 100% time. I agree with the WiFi, but the wired DNLA is working 100% discovered.I probably should not have mentioned the WiFi as there are many variables here. The host/speaker is a RoPiee that I have been using with Roon 100% Solid, which also needs to be in the same broadcast domain.Roon - 2 host of RoPiee - 100%Turned on DLNA (never ever tried or used this on the RoPiee before) to have test points. At THIS TIME I can not see them, but, I have no idea if it is the RoPiee or the MA.I totally respect you position you keep going back to the network. I have been at this long enough to not rule it out, thus, I have a wireshark trace if you want it, but as a Cisco System Engineer for 25 years of doing networking, I can not see why this VLAN on Meraki Switches, would have a ‘router’ issue. There is NO LAYER 3 involved all hosts are in the same broadcast domain. Now, WiFi is tricky with mDNS and thus most of the testing is WIRED to remove and mDNS to wifi issues.I will post results, but please to keep it simpleHA———VLAN40——-JukeAMP(DLNA)HA———VLAN40——-JukeAMP(AIRPLAY)JukeAMP has 4 inputs that can be defined. MA sees DLNA but not AIRPLAY. There is not a mDNS issue as the Airplay discovery is working. ,From my novice looking at the wireshark trace there is requests to the JukeAMP and the protocol is just not starting. I was hopeful on the compression as I see in the decodes GZIP which I assumes was a compression request, but I would rather not become a protocol expert on AIRPLAY, I just want to listen to music, and if DLNA would work I am good. DLNA works on the Juke, so now trying to find DLNA Pi hosts to send the music to./KevinSent from my iPadOn May 27, 2024, at 8:02 AM, OzGav ***@***.***> wrote:﻿
Now that you are advising DLNA is not being discovered this is starting to sound like a network problem. People in the past have identified network rules and router settings that have adversely affected the discovery and playback process.

**Comment by OzGav** [comment]
OK thanks. Advising that you are using a RoPiee is helpful as Marcel can probably flash that up and see whether there is an incompatability. This will get looked at in due course.

**Comment by kcossabo** [comment]
May 27, 2024 10:36:47 AM update 


VLAN 40 - 10.10.0.0/16
- 10.10.0.20 - HomeAssistant - port 25 Switch 1, VLAN 40 
- 10.10.0.41 - NAD M33 Amp - Port 10 of Switch 2, connecting port 1 to 47 to switch 2 VLAN40
- 10.10.10.13 - JukeAmp - Port 10 Switch 1, VLAN 40
- 10.10.10.31 - RoPieee-Bedroom - MR46E - Port 23 Switch 3 -connection on Aggregation 0 - Switch 1
- 10.10.102.38  - RoPieee-MA8900 - MR46E - Port 6 Switch 2 -connecting port 1 to 47 to switch 2 VLAN40
- 10.10.100.24 - Amplifier RX-A780 - Port 22 Switch 2 - connecting port 1 to 47 to switch 2 VLAN40
- 10.10.101.91 - Apple HomePod - MR46E - Port 23 Switch 3 -connection on Aggregation 0 - Switch 1


What works

HA/MA ------JukeAmp(DLNA) wired
HA/MA ------ NAD M33 Amp (AirPlay) wired
HA/MA ------ Amplifier RX-A780 (AirPlay) wired
HA/MA ------ RoPieee-MA8900 (airPlay) wired
HA/MA ------ RoPieee-Bedroom (airplay) wireless

What Does not work (Discovered, can not stream)

HA/MA ------JukeAmp(AirPlay) wired
HA/MA ------ Apple HomePod (AirPlay) wireless
HA/MA ------ RoPieee-MA8900 (DLNA) wired

What is not discovered but configured

- RoPiee endpoints (both wired and wireless)

RoPieee-MA8900 (airPlay) worked, but I could not see it on DLNA. Disabled Airplay on the RoPieee-MA8900, now only DLNA service, configured MA for DLNA Service only. MA Can not see the streamer. In summary, the same Pi, Same RoPiee software, can be seen as Airplay, and it works, does not work, and not discovered for DLNA.

Airplay Failures present the same, the endpoint is discovered, when a file is attempted to play the play never starts.

**Comment by kcossabo** [comment]
May 27, 2024 10:36:47 AM updated at May 27, 202412:23:58 PM 

<edits> I went to the main HA Integration page and HA sees
- RoPieee-MA8900 (DLNA)
- RoPieee-Bedroom(DLNA)

MA does NOT See them but HA has them as integrations that I configured to an AREA. HA also sees the JukeAmp(DLNA) as does MA.

I have Media Renderers (HA Term)/ Players (MA Term) that work, and fail in opposite manors.

1) JukeAmp, AirPlay does not work but DNLA works
2) PoPieee, DNLA does not work, but AirPlay Does Work

Also all airplay devices work when streamed from an iPad, iPhone or Mac.

— minor edit to network devices below —  


VLAN 40 - 10.10.0.0/16
- 10.10.0.20 - HomeAssistant - port 25 Switch 1, VLAN 40 
- 10.10.0.41 - NAD M33 Amp - Port 10 of Switch 2, connecting port 1 to 47 to switch 2 VLAN40
- 10.10.10.13 - JukeAmp - Port 10 Switch 1, VLAN 40
- 10.10.10.31 - RoPieee-Bedroom - MR46E - Port 23 Switch 3 -connection on Aggregation 0 - Switch 1
- 10.10.102.38  - RoPieee-MA8900 - Port 6 Switch 2 -connecting port 1 to 47 to switch 2 VLAN40
- 10.10.100.24 - Amplifier RX-A780 - Port 22 Switch 2 - connecting port 1 to 47 to switch 2 VLAN40
- 10.10.101.91 - Apple HomePod - MR46E - Port 23 Switch 3 -connection on Aggregation 0 - Switch 1


What works

HA/MA ------JukeAmp(DLNA) wired
HA/MA ------ NAD M33 Amp (AirPlay) wired
HA/MA ------ Amplifier RX-A780 (AirPlay) wired
HA/MA ------ RoPieee-MA8900 (airPlay) wired
HA/MA ------ RoPieee-Bedroom (airplay) wireless

What Does not work (Discovered, can not stream)

HA/MA ------JukeAmp(AirPlay) wired
HA/MA ------ Apple HomePod (AirPlay) wireless
HA/MA ------ RoPieee-MA8900 (DLNA) wired

What is not discovered but configured

- RoPiee endpoints (both wired and wireless)

RoPieee-MA8900 (airPlay) worked, but I could not see it on DLNA. Disabled Airplay on the RoPieee-MA8900, now only DLNA service, configured MA for DLNA Service only. MA Can not see the streamer. In summary, the same Pi, Same RoPiee software, can be seen as Airplay, and it works, does not work, and not discovered for DLNA.

Airplay Failures present the same, the endpoint is discovered, when a file is attempted to play the play never starts.

**Comment by OzGav** [comment]
Just wanted to say this hasn’t been forgotten. What I can add is only players that support Airplay 1 will work. Additionally, DLNA isn’t great from a standardisation perspective so we have seen problems in the past where some devices work and some don’t. 
If you get any more useful info please add it otherwise your patience is requested.

**Comment by kcossabo** [comment]
Thank You for the update. I have a mixture of Airplay and DLNA to make everything work, so not urgent.Thank You for the great product.Sent from my iPadOn Jun 12, 2024, at 10:02 PM, OzGav ***@***.***> wrote:﻿
Just wanted to say this hasn’t been forgotten. What I can add is only players that support Airplay 1 will work. Additionally, DLNA isn’t great from a standardisation perspective so we have seen problems in the past where some devices work and some don’t.
If you get any more useful info please add it otherwise your patience is requested.

**Comment by marcelveldt** [comment]
Please test this again with version 2.0.6 that has been released yesterday as we found something that could be a cause for no audio on airplay (just do make sure to enable the encryption option still).

**Comment by OzGav** [comment]
Closing due no follow up

**Comment by kcossabo** [comment]
Sorry, was traveling and missed the follow ups.

Will re open with reference to this issue.

**Comment by kcossabo** [comment]
If I need to start another thread, please let me know. Testing today

**Findings**

AirPlay to Juke Amp Still not working
Airplay to RoPieeee is now working
DLNA is inconsistent between servers, based on network discovery.

**HA** 

- Core 2024.7.3
- Supervisor 2024.06.2
- Operating System 12.4
- Frontend 20240710.0

Music Assistant Server
- Current version: 2.1.0

DLNA to Juke Audio amp **working**
Airplay yo Juke Audio amp **not working.**
- tried with and without compression
- with and without encryption 

Airplay to RoPieee 2024.06 (1676) [STABLE]
- **works**
DLNA to RoPieee 2024.06 (1676) [STABLE]
- **not discovered**

I built out a second MA on an UnRAID server as a docker/app

**UnRAID**

Music Assistant Server
- Current version: 2.1.0


Airplay to RoPieee 2024.06 (1676) [STABLE]
- **works**
DLNA to RoPieee 2024.06 (1676) [STABLE]
- **works**


Airplay yo Juke Audio amp **not working**.
- tried with and without compression
- with and without encryption 

DLNA to Juke Audio amp not working.
- **this is not discovered**.

**Comment by OzGav** [comment]
I’m not sure which exact version you have but looking here https://www.jukeaudio.com/ it explicitly states for all devices
>compatible with Airplay 2

If you look here https://music-assistant.io/player-support/airplay/ you will see
> If a device has a bad implementation of Airplay 1 and/or only supports Airplay 2 then it won't work

For the DLNA inconsistency I recommend you start by looking at the container network config.

**Comment by kcossabo** [comment]
OzGav  - Thank You for the reply.
  
​
  
​We covered that the Juke only did Airplay 2, thus all the work on DLNA.
  
​
  
​With Respect To networking, as a network engineer for Cisco for last 25 years, and having looked at all sorts of wireshark traces and such, I am always suspicious until the solution is found.
  
​
  
Same Broadcast domain, MACVLAN on the Docker, and hardware direct to the vlan on the HA. Not sure how they would recieve different bordacst from the DLNA, and how some speakers are making it to both, but the switch is some how filtering specific packets only for the Juke.
  
​
  
​I really like the product, and would like to help how I can on improving it, but, this does not seem like a user network error.
  
​
  
​If you would like me to send information to work through this bug, please let me know.
  
​
  
​I am not trying to make AIRPLAY work with JUKE, but not able to use a playlist is a problem, not having uniform DLNA support over different installs is a problem.
  
​
  
​/Kevin
  
​

**Comment by OzGav** [comment]
The playlist issue should be raised separately. Recently we identified someone had a track with weird characters in the name so that will be looked at eventually. So you should look carefully at the contents of the playlist.

I didn’t say general network config I said _container_ network config. People in the last haven’t enabled network host mode or have had firewalls on the device or have not properly set the MA settings
