### ISSUE TITLE
Music added from new Subsonic provider added as favorites 

### ISSUE THREAD

**Issue by frigi83** [music-assistant/hass-music-assistant#2359]
### What version of Music Assistant has the issue?

2.0.4

### What version of the Home Assistant Integration have you got installed?

2024.5.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Wen I add a new subsonic music provider to my MA, all the music (traces, albums, artists, playlist,...) is added as favorites. 

I have opened an issue because is not optimal (for large music gallery).

The best solution is to have a full synchronization between MA and Subsonic (see the discussion #2358).

### How to reproduce

1. Create a subsonic server (Navidrome or Gonic)
2. Create mark some albums and songs as favorites 
3. In MA add the Subsonic music provider 
4. In MA all the songs, albums and artists are marked as favorites 

### Music Providers

Subsonic

### Player Providers

Sonos

### What version of Home Assistant Core are your running

2024.5.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Thoughts @khers?

**Comment by khers** [comment]
What size library are we talking? I have ~1200 albums, ~1100, and ~12000 tracks and I don't see performance problems.

This doesn't feel like a bug to me, more like a feature request.

**Comment by khers** [comment]
What size library are we talking? I have ~1200 albums, ~1100 artists, and ~12000 tracks and I don't see performance problems.

This doesn't feel like a bug to me, more like a feature request.

**Comment by frigi83** [comment]
> What size library are we talking? I have ~1200 albums, ~1100 artists, and ~12000 tracks and I don't see performance problems.

I apologize, it is probably a misunderstanding due to my bad English.

It is not a performance problem, but a problem with the addition of a Subsonic music provider. The problem is that all music added is automatically added as a favorite in MA. Removing the favorite from all music takes quite a long time (in case of large music collections).

> This doesn't feel like a bug to me, more like a feature request.

I agree that synchronization in both directions is a new requirement and I tried to describe it in the discussion (#2358).

**Comment by khers** [comment]
I am not sure I understand. Where are things marked as favorite in MA? Nothing in my Gonic server is marked as favorite. Are you saying that you want something that is marked as favorite in one to also be marked that way in the other?

As for playlists, I added support for playlists that are in the open subsonic to show up in MA but have not implemented pushing playlist changes back mostly because I don't ever use them. I can look into pushing playlist changes back to the server but that is going be a bit before I can put time into it.

**Comment by frigi83** [comment]
If you take a new instance of MA and try to add a open subsonic server (like Gonic or Navidrome) as new music provider. All the music (artists, albums, playlists and tracks) are marked in MA as favorites. Regardless of whether on the server some items are marked as favorites. 

> As for playlists, I added support for playlists that are in the open subsonic to show up in MA but have not implemented pushing playlist changes back mostly because I don't ever use them. I can look into pushing playlist changes back to the server but that is going be a bit before I can put time into it.

This would be fantastic

**Comment by OzGav** [comment]
Just to confirm when you say marked as favourite you are seeing the filled heart icon next to all of the items?

<img width="810" alt="image" src="https://github.com/music-assistant/hass-music-assistant/assets/19848947/9b87416e-d4c4-4f1d-bef6-4cf46ad7dca1">

**Comment by frigi83** [comment]
> Just to confirm when you say marked as favourite you are seeing the filled heart icon next to all of the items?
> 
> <img alt="image" width="810" src="https://private-user-images.githubusercontent.com/19848947/333851556-9b87416e-d4c4-4f1d-bef6-4cf46ad7dca1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MDczNzgsIm5iZiI6MTcxNjcwNzA3OCwicGF0aCI6Ii8xOTg0ODk0Ny8zMzM4NTE1NTYtOWI4NzQxNmUtZDRjNC00ZjFkLWJlZjYtNGNmNDZhZDdkY2ExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDA3MDQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmYzg1NmUzOTJlYjdjODE5MDAzZGFjZTQ4YmE3OTI0ZmZjZTgxODEwNmEyZTczZTU3ZTlmNjFkMzZlMjdlZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x-tSU_1ahkuOTQzKDk2jcGwnNeKCkLxfoZLF0Hon-fw">

Yes

**Comment by OzGav** [comment]
Sorry can you post the image again as it hasn’t come through.

**Comment by khers** [comment]
I am seeing this same behavior but it is not consistent. The subsonic provider does not set the favorite field for any of the items  so that should default to False.

**Comment by frigi83** [comment]
> I am seeing this same behavior but it is not consistent. The subsonic provider does not set the favorite field for any of the items so that should default to False.

@khers wich Subsonic server do you have? I have tested with Gonic and Navidrome

**Comment by khers** [comment]
I use Gonic

**Comment by khers** [comment]
@marcelveldt mentioned on discord that this is a known issue (outside the subsonic provider) and that a fix is in the works.

**Comment by OzGav** [comment]
Closing at OP request

**Comment by leokeba** [comment]
Sorry to revive a closed issue, but has this been fixed already ? I'm having the same issue with my Navidrome instance, and the favorites features pretty much mandatory for me to be able to navigate anything, my music collection is too big to just scroll into.

**Comment by khers** [comment]
The fix is in the betas for 2.1 for sure, I do now know if it was backported to the stable branch.

**Comment by leokeba** [comment]
Thanks, I'm using the Home Assistant Add-On which advertises itself as "2.0.7", is there a not-too-involved way for me to get the latest beta ?

**Comment by marcelveldt** [comment]
The 2.1 version will be released somewhere between now and 2 weeks so you could also wait for that
