### ISSUE TITLE
Local SiriusXM HLS stream won’t play 

### ISSUE THREAD

**Issue by deboy69** [music-assistant/hass-music-assistant#2361]
### What version of Music Assistant has the issue?

2.0.4

### What version of the Home Assistant Integration have you got installed?

2.0.4

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Music wont stream from player and quits immediately. 

### How to reproduce

Add url for radio

### Music Providers

RadioBroswer

### Player Providers

Airplay

### What version of Home Assistant Core are your running

2024.5.5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
Please review the requirements for submitting reports. Do not provide debug level logs unless asked. Review the troubleshooting docs for what information is required to be provided. When this is done we will look at this further.

**Comment by deboy69** [comment]
> Please review the requirements for submitting reports. Do not provide debug level logs unless asked. Review the troubleshooting docs for what information is required to be provided. When this is done we will look at this further.

if you dont want log files you should probably remove the conflicting information on the github page.

"[Issue tracker](https://github.com/music-assistant/hass-music-assistant/issues) to create bug reports, please include detailed info and logfiles. Please check if your issue has already been reported."

log removed.

**Comment by OzGav** [comment]
Or you could just read the instructions in the form you filled out

> Please DOWNLOAD then DRAG and DROP the full log output from MA SETTINGS>>CORE into the field below. Please do NOT use debug logging unless asked to do so.

So I didn’t say do not attach I said don’t use debug level

**Comment by deboy69** [comment]
Bet your a blast at parties aren't you. 

Never mind I came here for help but I see your more of PIA than support

Have a great day.

**Comment by OzGav** [comment]
You will get help if you just do what is asked and don’t be abusive. This is your only warning. 

You have provided statements that don’t align with common MA language. For example, RadioBrowser is a music provider yet you write

>  Add url for radiobrowser

which isn’t possible within The RadioBrowser provider. Perhaps you mean you are adding a manual URL in the radio view? If this is the case then it is possibly a problem with that specific station. You haven’t advised if you have tried other stations that use different streaming formats.

**Comment by deboy69** [comment]
you are correct it. It is add url to radio.

**Comment by OzGav** [comment]
There have been on and off reports of certain stations not working most usually when they use HLS. As suggested above try other stations and confirm that they work. If you isolate it to a particular station then post the link to it and this will be investigated in due course.

**Comment by deboy69** [comment]
I can load the url into VLC Media Player and it works. So I know they are successfully working.

**Comment by OzGav** [comment]
Here is a random URL to try https://kspcradio887.radioca.st/stream128?type=http&nocache=73

You can provide the link to your SiriusXM station but I believe it is geo-blocked so fixes can’t be tested outside the US. Someone was working on a SiriusXM provider but they have gone silent unfortunately.

**Comment by deboy69** [comment]
Ill give it a try. Here is a log for the url its seems to be improperly formated. 

Start Streaming queue track: builtin--jvajk9D9://radio/http://192.168.1.242:9022/siriushits1.m3u8 (Hits 1) for queue jbl office

**Comment by OzGav** [comment]
Ok would you agree that this issue is actually that a specific station won’t play? If so please supply the actual station URL and change the title of this report. If the stream is geo blocked then it may take some time to identify a solution

**Comment by deboy69** [comment]
URL is included in the post above with the log line.

Title changed

It's local on my network so I don't think it would be geo locked

**Comment by OzGav** [comment]
No I meant it’s geo blocked for the devs as they don’t live in the US but that is because I thought it was from SiriusXM. Are you actually generating your own stream with Icecast or something!

**Comment by deboy69** [comment]
It's a local docker container that pulls the stream from SiriusXm and turns it into a local HLS stream.

**Comment by OzGav** [comment]
Without access to the stream it will be very difficult to fix. You may benefit from fixes to other HLS streams so it may just start working in future updates. If you can change to a different stream type that may also fix the problem.

**Comment by deboy69** [comment]
Because I'd like to integrate it into HA for everyone to enjoy in the house hold.

Stream works in VLC. 

I'm open to suggestions this integration was what came up with a google search. 

Is there bugs with HLS?

**Comment by OzGav** [comment]
MA can be viewed within HA as either a dedicated link to the addon or via an iframe. This would seem to reduce complexity? 

HLS streams have been observed to vary in their implementation and some tweaks were required to support those. This brings us back to the problem though that in order to fix this we need access to the original URL which is probably geo blocked. In case we find a dev in America can you provide the original SiriusXM URL

**Comment by deboy69** [comment]
http://localhost:9022/siriushits1.m3u8

Above access is the url to access the docker container. The docker container logs into SiriusXm online streaming account that creates the HLS stream. Not sure if it's geo locked but a SiriusXm account and maybe a VPN to the states would circumvent that.

https://github.com/AngellusMortis/sxm-docker

**Comment by OzGav** [comment]
Ok I must not understand how SiriusXM works. Isn’t there an originating URL from there? When using that HLS proxy how do you select which channel to listen to?

**Comment by deboy69** [comment]
It's http://ip address of the docker container:port/channel-ID each ID is assigned to a channel on SiriusXm

**Comment by deboy69** [comment]
Any ideas to get this working?

**Comment by OzGav** [comment]
No. Issues get addressed on a first on first off basis unless they affect multiple people. Combine that with the difficulty I mentioned in getting access to the stream this will likely take some time to resolve. There is an unfinished SiriusXM music provider PR that someone can pickup…

**Comment by deboy69** [comment]
Fixed with 2.1.0.

Thank all
