### ISSUE TITLE
Deezer - Infinite loading of playlists (no local songs)

### ISSUE THREAD

**Issue by brian-maher** [music-assistant/hass-music-assistant#2366]
### What version of Music Assistant has the issue?

2.1.0b1

### What version of the Home Assistant Integration have you got installed?

2024.5.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When browsing/playing certain playlists on Deezer, Music Assistant infinitely loads songs from the playlist. In the UI this manifests as an infinitely scrolling looped list of songs. When trying to play such a playlist, no music plays - instead mass appears to get stuck loading songs, with constant elevated CPU usage and increasing memory usage until it runs out of RAM.

Some playlists are affected, some aren't. It does seem to primarily affect Deezer curated playlists - but I haven't been able to narrow it down further than that.

Logs appear to show nothing beyond `DEBUG (MainThread) [music_assistant.music.playlist] Fetching all tracks for playlist Metal Essentials`

### How to reproduce

1. Clear the queue and select a player
2. Load this playlist `/#/playlists/deezer/1367442165`
3. Attempt to play the playlist

### Music Providers

Deezer

### Player Providers

Airplay/Sonos

### What version of Home Assistant Core are your running

2024.5.4

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Alternative

**Comment by OzGav** [comment]
@arctixdev

**Comment by arctixdev** [comment]
Ah cool you found the issue! Sorry I haven't looked at it myself.. This should be fixed relatively quickly now then :+1:

**Comment by marcelveldt** [comment]
This one should be fixed in the next (patch) release

**Comment by OzGav** [comment]
@brian-maher Please confirm if this has been fixed

**Comment by OzGav** [comment]
Thanks. Can you confirm if playlists other than Deezer are working ok for you?

**Comment by OzGav** [comment]
And still only with a multiple of 50 songs?

**Comment by marcelveldt** [comment]
Reproduced and fixed. Fix is available in next (patch) release (2.0.5 / 2.1.0b4)

**Comment by OzGav** [comment]
@brian-maher 2.1.0b4 is released please confirm this is fixed.

**Comment by brian-maher** [comment]
LGTM - Confirmed fixed, all working :)
