### ISSUE TITLE
multi zone support

### ISSUE THREAD

**Issue by zeev-mindali** [music-assistant/hass-music-assistant#2379]
### What version of Music Assistant has the issue?

2.0.4

### What version of the Home Assistant Integration have you got installed?

2024.5.5

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

i have a pionner reciver wich configured as multi zone.
i can only see zone 1 on each reciver

### How to reproduce

using a multi zone reciver will show the error

### Music Providers

spotify

### Player Providers

air cast, dlna

### What version of Home Assistant Core are your running

2024.5.5

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Alternative

**Comment by OzGav** [comment]
Did you really read the troubleshooting FAQ?

**Comment by zeev-mindali** [comment]
i read the FAQ, it's talking about powering up the reciver and select the input, which is not my case.
i can hear on first zone, but i can not move to second zone.
may i missing something?

**Comment by zeev-mindali** [comment]
got it, no support for other zone by software
