### ISSUE TITLE
Spotify playlist not fully loading

### ISSUE THREAD

**Issue by drjjr2** [music-assistant/hass-music-assistant#2381]
### What version of Music Assistant has the issue?

2.1.0.b1

### What version of the Home Assistant Integration have you got installed?

2024.5.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I have a playlist that has 620 tracks on spotify but only 43 load in MA. Things I have tried:
- removing a song to see if it gets replaced with another (it does not)
- removing and adding the Spotify provider
- removing tracks that the provider said could not be found
- shared the playlist with another user, copied it so it would be their own playlist - same issue, same 43 tracks show in MA

Link to the offending playlist: [Island Music](https://open.spotify.com/playlist/5HvLeIKx0htN3nzv7qgJrm?si=1e75fac75bc84a83)

### How to reproduce

Since I tried this with another account you should be able to try to add the above linked playlist to your Spotify, then sync MA. The Spotify list has 620 tracks. 

### Music Providers

Spotify

### Player Providers

DLNA

### Full log output

[MA-051824.txt](https://github.com/music-assistant/hass-music-assistant/files/15472433/MA-051824.txt)

### What version of Home Assistant Core are your running

2024.5.5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by gpgmailencrypt** [comment]
Same happens with "filesystem provider". Only the first 49 songs will be loaded

**Comment by drjjr2** [comment]
I was able to get the Spotify playlist in question to fully load after removing songs that Spotify must have lost the license(s) to. This was similar to a problem I saw with Tidal playlists a few releases ago so there's still some logic that needs to be inserted for missing/unavailable tracks in a playlist. Especially since it seems like the streaming services are continuously losing/gaining licenses for tracks.

**Comment by OzGav** [comment]
We will keep this open to look into this.

**Comment by marcelveldt** [comment]
This one should be fixed in the next patch release

**Comment by OzGav** [comment]
@drjjr2 Are you able to confirm this has been fixed?

**Comment by gpgmailencrypt** [comment]
I can confirm that it works (at least with  filesystem provider). Even a playlist with about 1200 songs loaded correctly
