### ISSUE TITLE
Artwork is either not being returned, or not persistent (primarily seen with the Artists listing)

### ISSUE THREAD

**Issue by Extrapilot1** [music-assistant/hass-music-assistant#2384]
### What version of Music Assistant has the issue?

2.0.4

### What version of the Home Assistant Integration have you got installed?

2025.5.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

On loading a new library, I found that most metadata was missing, and would often be populated by selecting the entry and waiting. I opted to reprocess the entire library through Brainz, with the ID3 tags all updated, and rescan. Same basic problem. I removed the library from Music Assistant, and readded it. Same basic problem- far more album/song info, but Artist thumbnails almost non-existent. If I select the artist, typically I see that graphic load, and often, if I return the artists listing, the image for the artist is present. But often, it will disappear on closing and starting a new session. Its hard to understand how this can be, if the issue is simply extracting an image and linking that filename in the database. So, seems like either the link is bad, or the database entry wasnt made and the process was a local thing for the session, or perhaps the artist image isnt stored within an entity (as an album cover would be for album or song), and it just isnt being handled well. 

In the little refresh all circular arrow thing, I see a red dot (which I believe means a change has been detected, so a scan is needed), but hitting that button does not seem to do anything- the red dot disappears briefly (1 sec) and returns. If I rapidly click 3-4 times as if there were 4 updates in queue) which presumably should be handled by a single refresh, the dot goes away and the circle goes dark. No idea if this is a workaround, or if I did something that is causing re-entrance etc. 

### How to reproduce

As explained, simply load a new library. Most Artists will not have images. And while selecting the artist can return that image, and sometimes it will persist across sessions, for me, about 80% of the time the system reverts to no artist image.

### Music Providers

Local (NAS) share

### Player Providers

na

### What version of Home Assistant Core are your running

2025.5.5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
This is a known problem that is being investigated.

**Comment by marcelveldt** [comment]
Do these artists have local artwork in the media folders ?
Music Assistant will only pickup local artwork if its in the correct directory structure.

So for example media_folder\Queen\Greatest Hits\track1.f;lac

The artist artwork (folder.jpeg, logo, fanart) will be in the Queen folder.
The album artwork (thumb, discart) will be in the album folder

**Comment by OzGav** [comment]
I believe this is the same problem as we have spoken about before whereby for some specific artists the fetched artwork routinely disappears. I don’t believe I have seen it with artists that have local artwork. The text describing the artist also seems to disappear as well,

**Comment by Extrapilot1** [comment]
Hi Marcel et al-
So far as I can tell, none of my catalog have root content (metadata). So, no group image, no group xml/text. MusicBrainz doesnt seem to capture generic data like this- it seems to be limited to specific albums. And there isnt a correlation between the images posted to the subfolders (albums) and the group image; typically, the group photo is not seen anywhere within the directory. Presumably, this is scraped, but not stored. What I find particularly strange is that for my library, with 550+ artists, I tend to see artist images/thumbnails for only those artists I have accessed. Example, I have AC/DC as an artist- with am artist thumbnail that shows immediately on listing artists- where for others- say, Aretha Franklin- I dont. If I access the Aretha folder, I see her photo and the text associated with the artists- same as with AC/DC. But, on returning the main window, even restarting the platform, it reverts- where I never see Aretha as a thumbnail, and AC/DC is always present. In neither case do I see metadata in the artists' folders. So, it seems as if either some is persisted locally in a db or separate file system, OR there is a link to external reference that is not just fast, but is persistent in some way that most are not. I dont know enough about the code to speculate- I could imagine any number of causes, from media type to supplier URL format etc. What I dont understand is- why is the system just no persisting artist info in the artist folder root? Apparently, there is some legal thing with MusicBrainz and copyrights from sources, but apparently they won their lawsuit on this- so not clear why MB isnt capturing this data itself now. But just super strange Im seeing the same 2-5% of artists show thumbnails, and the rest the generic 'disc' icon.

If there is another scraper I should try for this- happy to accommodate, but it remains unclear to me why some artists show content in the overview, and others dont, where there seeming is never metadata in the artists' root folders...

**Comment by OzGav** [comment]
Don’t put too much mental effort into trying to understand it as it is a bug that is difficult to track down. In my case it is the same artists that drop the images. So I have a lot that persist fine and then a number that continue to disappear. So it has been tricky to nail down why that is

**Comment by Extrapilot1** [comment]
Understood. Simply trying to understand why the design decision was made to leverage local data first to save bandwidth/hits on source sites, but that this data isnt persisted as local content within the exposed file system. Since that seems to work for MusicBrainz content, it seems it might make sense to just persist that data (which is clearly being grabbed and presented already) in the same way, where if the internal mechanism (db presumably) returns no data, and the fallback is local content- at least behavior is consistent. I understand that search on metadata isnt possible if it is file/text-based, but so far as I know, that search capability doesnt exist regardless- and it is limited to file structure content (folder and file names). 

Happy to help with testing- as always- 
Good luck with the effort- hopefully it is something simple- an unsupported character in the text, or a blob size limitation, or some weird inherited permission limitation.

**Comment by marcelveldt** [comment]
You need other scrapers to save the artwork locally in your folders.
Music Assistant always prefers local artwork and metadata but it has to exist. If it doesn't exist, it will query the metadata providers and it will only do that on (first) access. It will not do that proactively as we simply do not have the money to pay for such heavy api access.

There is however a feature request to automatically save any local artwork in the folders so maybe that will one day see the light. Until then my recommendation is to use a a tool like Lidarr or alikes if you want to have all that artwork and metadata saved to your music folders.

That said; focus back on the bug report.
Both you and @OzGav mention that you experience artwork dissapearing. So it has been scraped (and visible in the UI) and then all of a sudden its gone again. Actually this morning I fixed a bug I accidentally ran into that may explain this behavior. So I'd like to ask if this issue still manifests itself in the next version; We will provide a 2.0.7 patch release later today or tomorrow.

**Comment by Extrapilot1** [comment]
OK, Ill keep my eyes posted for a new revision. Best- R

**Comment by OzGav** [comment]
This might have been fixed in beta 14 @Extrapilot1 please advise if you still see this

**Comment by Extrapilot1** [comment]
Hi. Im reinstalling; I had a bizarre problem where a recovery from the last full backup for the test was a disaster (post-recovery, database was offline- etc). Just too many weirdnesses to feel comfortable with feedback for you. So, rolled back to an earlier instance, where I dont have the database populated with MA info. Beta 14 was just installed, and it is scraping the NAS share. So far, it seems to be doing well- slow relative to something like Volumio, but I dont know if that is an HA overhead thing (slow callbacks on DB writes etc) or if there is other stuff going on (I had assumed for example that MA was searching the online indexes to flesh out/pre-populate artist info, or perhaps building a cross-referenced database on things like players credited on albums- as we see with actors vs movies in Kodi etc). But yea, may just be a single threaded thing on RPI4 and just a lot of lag on callbacks vs a native OS tweak like Volumio?

More info tomorrow I hope!

**Comment by OzGav** [comment]
I'm about prepared to call it as I would see this all the time and I have been trying to break it but all images are staying put.

**Comment by marcelveldt** [comment]
This one should be fixed with b14 but please test it extensively.

@Extrapilot1 initial scan is indeed a bit slow, on purpose actually, to not completely overload the system with requests

**Comment by Extrapilot1** [comment]
Hi Marcel- the problem I was seeing with artist images being intermittent in the summary list seems to be resolved. I assume this is purely a code thing, and not a reinstall that I did- but I guess it is always possible there is some install script problem or a weird permissions thing that might prevent some file from being updated...

There is a different behavior- which may be related- that I would mention. Where in the past the system tended to pull artist image/summary data for an artist that had neither when that artist was selected, that no longer happens. And that may be a function of throttling, where perhaps you are scraping in the background at 10 per hour or whatever. But, in the past, I never saw that happen- it simply never scraped artist data unless you selected that artist manually- at which point, one some timeout, it grabbed the data from whatever source. But if I select the manual option 'refresh item' from the triple-dot menu, it tends to pull both the image and the description text immediately. 

Additionally- previously, it seemed to show a red dot on the library icon in the artist summary view- suggesting the engine knew the record was incomplete. I dont see that anymore. 

Best
R

**Comment by OzGav** [comment]
The red dot on the library icon tells you the list is being filtered to show in library items only.

The behaviour of pulling data when an item is visitied has been changed. You have to either do the refresh item or wait for it to do done in the background. However, I am looking at a possible bug where this background task is not completing. In terms of this report though it has ben resolved.

**Comment by Extrapilot1** [comment]
Strange on the red dot. I found that selecting the icon when it was in that mode caused content to update, or a scrape to happen for the artist info, when it didnt otherwise. 

Regarding the background scraping, is there any mechanism by which users can easily determine status of the process? It would be great to have something like Volumio- where in the Scan/Rescan subsection- there will be a count as sort of 135/500, incrementing towards 500. And an addition of some new artist or album will likewise be represented as some new ratio (i.e. x/506). It is possible to at least visit that subscreen manually on some schedule, but also- its a good indicator if the process has halted or is unable to process some number of entries. I believe there is a secondary indicator (a spinning icon) on the main screen showing that content scanning is in process.

**Comment by OzGav** [comment]
You can raise a feature request for that
