### ISSUE TITLE
Progress Bar restarts at 0:00 after 2 seconds

### ISSUE THREAD

**Issue by mzurhorst** [music-assistant/hass-music-assistant#2396]
### What version of Music Assistant has the issue?

2.1.0b1

### What version of the Home Assistant Integration have you got installed?

2024.5.5

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Previously reported at:  https://github.com/orgs/music-assistant/discussions/2390

For me, the progress bar is in a loop and progresses only for the first 2 seconds before it resets back to 00:00 again.
![grafik](https://github.com/music-assistant/hass-music-assistant/assets/575190/b07abc28-a420-4fc1-9f36-8c4f099880a0)

As far as I can observe, the album is still played, song after song, but Music Assistant does not display the next title, nor does it display all titles played.

The player in use is a "Home Assistant MediaPlayers" player.  The device is a Linkplay-based player (using the HACS custom integration). Within Home Assistant, the progress bar behaves as expected.

### How to reproduce

n/a

### Music Providers

Plex Media Server Library

### Player Providers

Home Assistant MediaPlayers

### What version of Home Assistant Core are your running

2024.5.5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Alternative

**Comment by mzurhorst** [comment]
What version of the Home Assistant Integration have you got installed?  -->  2024.5.1

**Comment by OzGav** [comment]
Is QUEUE FLOW MODE enabled in the settings?

**Comment by mzurhorst** [comment]
Thank you, @OzGav.

**Comment by marcelveldt** [comment]
Like already explained by OzGav, its always preferred to use one of the native Music Assistant providers, which are optimized for the best user experience and playback quality. Only use the HA MediaPlayer as last resort when there is no "native" option available. So for LinkPlay based players, use the DLNA and/or Airplay provider.

That said, I found some bugs yesterday in the HA Mediaplayer provider actually so its worth trying if this issue is fixed in the next update (2.0.7)

**Comment by OzGav** [comment]
@mzurhorst Please advise if this is still a problem in 2.0.7

**Comment by mzurhorst** [comment]
Hi @OzGav, am I supposed to install anything manually?
My HA updated to 2.1.0.b6 yesterday, but does not offer anything else.   

How would I leave the beta track?

**Comment by OzGav** [comment]
The beta will have the update as well. Is this still an issue?

**Comment by mzurhorst** [comment]
Well, something changed.  The numbers are gone, see below.
But would say, this was introduced with 2.1.0.b5 already.  Not sure.

I still see the bar progressing at in tiny steps, and it is reset afterwards.

![grafik](https://github.com/music-assistant/hass-music-assistant/assets/575190/a18d82c4-a7d6-4739-b969-f94a346e8649)

**Comment by OzGav** [comment]
So if the bar is now increasing would you agree that this issue is fixed?

**Comment by mzurhorst** [comment]
No, it is not.  As I said, the progress bar makes a little progress, and resets.  (=goes back).

I have captured a .gif.  Please see attached.      Here, you also see how this behave in the middle of a track.  
I can click randomly onto the progress bar, and the music jumps to this position.   But it is also the same, when I just select a new song.  

![2024-06-17-16-44-27](https://github.com/music-assistant/hass-music-assistant/assets/575190/32d47ffc-9ef4-4a34-9878-96f811d54474)

**Comment by marcelveldt** [comment]
This is clearly an issue where the player is not reporting progress to HA.
Unless that is fixed, you will not have great results with this player in MA. I suggest you to use the Airplay or DLNA provider in MA with linkplay based players.

**Comment by mzurhorst** [comment]
I will have to look into this in a calm minute.   For the moment, I have raised this topic to the developers of the Linkplay integration. Maybe those have an idea to fix this on their side.

**Comment by OzGav** [comment]
Closing due upstream issue. FYI native linkplay provider support is on the backlog. ETA Unknown.
