### ISSUE TITLE
VInfiniteScroll in ItemsListing.vue won't load more items in some cases

### ISSUE THREAD

**Issue by Thyraz** [music-assistant/hass-music-assistant#2398]
### What version of Music Assistant has the issue?

2.1.0b1

### What version of the Home Assistant Integration have you got installed?

-

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Problem 1) 
When selecting an artist from a search result with more than 50 albums, you can't see more than the first 50 results.
As the v-infinite-scroll isn't in manual mode here, no "load more" button is shown, and more content should be added automatically.

The local search button (inside the artist view) can reveal search results that aren't displayed among these first 50 items.
So it seems like the other albums are already loaded (not just the first 50 ones), just the UI doesn't get updated automatically.

Problem 2)
When a search result is showing more than 8 hits in the badge,
you should be able to view more than the 8 initially displayed results using the load-more-items button.
But this also seems to be broken and no more items are added to the list.

Maybe both problems are a result of the same bug?
(Both are using the same functions in VInfiniteScroll.vue)

### How to reproduce

Problem 1)
- Use Spotify as a music provicer
- Open the global search in MA
- Enter "Johnny Cash"
- In the artist search result section, select "Johnny Cash"
- Notice, that the album-count badge in the artist view shows 105 albums
- Scroll down and count the items in the list. Will be 50 and more items are added when the end of the list is reached

Problem 2)
- Use Spotify as a music provicer
- Open the global search in MA
- Enter "Johnny Cash"
- Press the load-more-items button in the albums column (which shows 8 entries at the beginning)
- The button disappears, but no more items are added to the list

### Music Providers

Tried only with Spotify, as I don't use any other ones.
But is most likely not a related to this music provider and should happen with the other ones too.

### Player Providers

Didn't play anything, so shouldn't matter.
But for the record: Only Sonos is installed in my MA setup.

### What version of Home Assistant Core are your running

2024.5.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
For #1 this is expected behaviour and documented here https://music-assistant.io/ui/#global-search

**Comment by Thyraz** [comment]
I think this describes something different, but I may be wrong:

when clicking on the artist, you are not in a search anymore. 
It’s a list of all albums of an artist. 

The same happens if you add a artist to your library and click on it in the artist section of MA instead of using the search. 
You will also only be able to see the first 50 albums of the artist.

**Comment by OzGav** [comment]
Sorry yes I missed ones of your steps. This is known and has been discussed internally. Was actually just mentioned here https://github.com/music-assistant/hass-music-assistant/issues/2381

**Comment by marcelveldt** [comment]
Should be fixed in 2.0.5 / 2.1.0b4

**Comment by OzGav** [comment]
@Thyraz 2.1.0b4 is released please confirm this is fixed

**Comment by Thyraz** [comment]
@OzGav just wanted to open Github and write you everything works fine, when I found a last problem with paging:
https://discord.com/channels/753947050995089438/1247654189828538389/1250318548174110781

So, "almost" solved. ;-)

**Comment by OzGav** [comment]
I think to keep Marcel sane with keeping up with the issues that it would be good to copy and paste that info from discord into a new issue

**Comment by Thyraz** [comment]
Fine for me. 👍 so this one can be closed.
