### ISSUE TITLE
Error on Synology NAS 218+

### ISSUE THREAD

**Issue by vingerha** [music-assistant/hass-music-assistant#2404]
### What version of Music Assistant has the issue?

2.0.4

### What version of the Home Assistant Integration have you got installed?

n.a.

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Error in log, not clear if can be ignored

### How to reproduce

install MA on Syno, connect to music source and wait. After restart the error comes back, see log

### Music Providers

n.a.

### Player Providers

n.a.

### Full log output

[log.txt](https://github.com/user-attachments/files/15528694/log.txt)

### Additional information

The container is using a insane amount of memory, after 1 night just waiting 2.6Gb, just restarted and within 10mins it is already at 380Mb, with the same log as below, 12 mins: 403

### What version of Home Assistant Core are your running

n.a.

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
I understand reporting of memory is memory in docker is inaccurate. I read that docker stats will display used RAM + available cache - inactive cache. MA caches a lot.

So unless something is actually failing then ignore it.
