### ISSUE TITLE
TuneIn not showing up in radio overview

### ISSUE THREAD

**Issue by dhoeben** [music-assistant/hass-music-assistant#2405]
### What version of Music Assistant has the issue?

2.0.4

### What version of the Home Assistant Integration have you got installed?

2024.5.5

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

TuneIn radio’s not showing up in the radio section. Also search and global search are not working.

### How to reproduce

Add TuneIn plugin to MA.
Look for channel

### Music Providers

TuneIn 

### Player Providers

Sonos

### What version of Home Assistant Core are your running

2024.5.5

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Alternative

**Comment by OzGav** [comment]
What you have written above suggests you have not read the docs. Have you?

**Comment by dhoeben** [comment]
@OzGav, hes I have. My navigation in HA relies on the back button. When using it as a panel, it does not provide one. This is why I said using the webpage view. No need to be this passive aggressive.

**Comment by dhoeben** [comment]
Which I have and they are not showing up :)

**Comment by OzGav** [comment]
Then they might be premium or geo blocked?

**Comment by dhoeben** [comment]
I don't know what it was. I removed the MA container from docker, restarted my server and reinstalled everything. For some reason everything is working correctly now. Maybe it had something to do with an earlier installation (and no reboot after removing the previous installation?)

**Comment by OzGav** [comment]
Not sure. Glad all is working now.
