### ISSUE TITLE
Invalid or misspelled album name causes infinite loop

### ISSUE THREAD

**Issue by sskodje** [music-assistant/hass-music-assistant#2409]
### What version of Music Assistant has the issue?

2.0.4

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Clicking on an artist that has an album with an album name not found in musicbrainz API, it causes a seemingly infinite loop of retries without backing off. The cpu usage is high, and the UI flickers due to rapid refreshes.

The log will show entries like this, repeated rapidly until navigating away from the artist.

```2024-06-03 17:59:35.687 DEBUG (MainThread) [music_assistant.music.artist] updated The Weeknd in database: 1627
2024-06-03 17:59:35.704 DEBUG (MainThread) [music_assistant.music.artist] updated The Weeknd in database: (id 1627)
2024-06-03 17:59:35.710 DEBUG (MainThread) [music_assistant.webserver] Handling command music/artists/get_artist
2024-06-03 17:59:35.744 DEBUG (MainThread) [music_assistant.metadata] Unable to get musicbrainz ID for artist The Weeknd
 - using lookup-album(s): Weeknd Mix
 - using lookup-track(s): Blinding Lights/Can't Feel My Face/False Alarm/Heartless/In Your Eyes/Less Than Zero/Out of Time/Save Your Tears/Starboy ft. Daft Punk/Take My Breath
```
I discovered this problem on a playlist downloaded from youtube, where the album name is "Weeknd Mix".

### How to reproduce

- Tag album with a valid album artist (in my case Weeknd)
- Tag album with album name that does not exist (in my case Weeknd Mix)
- Enter artist in Music Assistant UI.

### Music Providers

Filesystem

### Player Providers

Irrelevant

### What version of Home Assistant Core are your running

2024.5.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
You haven’t provided the full log.

**Comment by sskodje** [comment]
There are no log entries apart from when set to Debug, and the bug report form said not to include debug logs. The only logs when set to debug is the entries i posted, repeated as long as the music assistant is on the artist view.

**Comment by OzGav** [comment]
We will close this soon due to no follow up

**Comment by sskodje** [comment]
Go ahead, i'll do it myself. After reading about the problems with API limits, i find a bug causing possibly thousands of unnecessary requests due to broken retry logic. I suffer through the unnecessary complicated bug report form you have instead of simply letting people report bugs, make a 100% reproducable report, and you close it because i can't be arsed to upload an empty log showing nothing of value 

You can be assured i won't try to help in the future.

**Comment by OzGav** [comment]
Actually you closed it I just asked for some follow up but seems like that has upset you.
