### ISSUE TITLE
Voice commands are no longer with latest release of Home Assistant

### ISSUE THREAD

**Issue by lgcnbento** [music-assistant/hass-music-assistant#2413]
### What version of Music Assistant has the issue?

2.1.0b2

### What version of the Home Assistant Integration have you got installed?

2024.5.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When issuing a voice command, such as "Play music by x on device", the following error occurs:
`Logger: homeassistant.components.conversation.default_agent
Source: components/conversation/default_agent.py:347
integration: Conversation (documentation, issues)
First occurred: 3:27:23 PM (4 occurrences)
Last logged: 3:56:39 PM

Unexpected intent error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/intent.py", line 136, in async_handle
    result = await handler.async_handle(intent)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mass/intent.py", line 72, in async_handle
    state = await self._get_matched_state(intent_obj, name, area)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mass/intent.py", line 145, in _get_matched_state
    intent.async_match_states(
TypeError: async_match_states() got an unexpected keyword argument 'area'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/conversation/default_agent.py", line 347, in async_process
    intent_response = await intent.async_handle(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/intent.py", line 143, in async_handle
    raise IntentUnexpectedError(f"Error handling {intent_type}") from err
homeassistant.helpers.intent.IntentUnexpectedError: Error handling MassPlayMediaOnMediaPlayer`

### How to reproduce

Issue any voice command to play a song on a device.

### Music Providers

Spotify

### Player Providers

Chromecast

### Full log output

[home-assistant_2024-06-05T20-07-36.847Z.log](https://github.com/user-attachments/files/15596004/home-assistant_2024-06-05T20-07-36.847Z.log)

### What version of Home Assistant Core are your running

2024.6.0

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Yes HA changed something. Will be fixed soon

**Comment by jozefKruszynski** [comment]
Fixed in PR #2427

**Comment by OzGav** [comment]
Confirmed fixed
