### ISSUE TITLE
Universal Groups Not Updating properly / UI not Updated properly

### ISSUE THREAD

**Issue by smarthomecircle** [music-assistant/hass-music-assistant#2421]
### What version of Music Assistant has the issue?

2.0.4

### What version of the Home Assistant Integration have you got installed?

Home Assistant Addon

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I have installed MA using the HA addon. 

I tried grouping the speakers, say 3 of them with a name "Group A".. it works fine and I am able to play music well on the 3 of them. 

Bug 1: Now when I try to update the group to remove one of them, the save button still remains disabled. Same thing with updating the name also. The save button is just not clickable.
![image](https://github.com/music-assistant/hass-music-assistant/assets/136709923/e90309ad-c170-49bb-85d5-e6ecf38eedcc)

Bug 2 : Next, If i try to delete the group and recreate it with a new name, the old group is not available in the Players section, but the players are still tagged to it. 
![image](https://github.com/music-assistant/hass-music-assistant/assets/136709923/4f410621-26ea-41ec-b464-a95423566543)
And Hence I cant then use the individual Players again. 

Bug 3: If I try to create a New group the old group still shows up as one of the speakers. 
![image](https://github.com/music-assistant/hass-music-assistant/assets/136709923/68c0dcd1-eb4a-4d5c-b842-4ad2a4d3403f)

I think there is a bug while updating and deleting the group that does not reflect on the UI. 

Once I restart the MA addon, everything is all fine. 

### How to reproduce

Bug 1: 

Step 1: create a group with 2 player
Step 2: Update the group to remove one player

Bug 2: 
Step 1: create a group with 2 Players
Step 2: play something with the group.
Step 3: delete the group. 
Step 4: try playing something selecting a single player 

Bug 3: 
Step 1: create a group with 2 Players
Step 2: delete the group. 
Step 3: create the group, you will see it in the drop down. 

### Music Providers

Soundcloud and local file system

### Player Providers

Home assistant player, air play and universal group provider

### What version of Home Assistant Core are your running

2024.6.0

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Cannot recreate on 2.1.0 please update and advise
