### ISSUE TITLE
Fade-in effect occurs on Chromecast device when changing sampling rate even though crossfade is disabled

### ISSUE THREAD

**Issue by madbrain76** [music-assistant/hass-music-assistant#2424]
### What version of Music Assistant has the issue?

2.0.4

### What version of the Home Assistant Integration have you got installed?

2024.5.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Fade-in effect occurs when changing sampling rate on Chromecast player

### How to reproduce

1. go to settings
2. open the device list on top
3. select the Chromecast player
4. disable crossfade
5. disable volume normalization
6. change the sample rate settings to only support 44.1 kHz 16 bits
7. go to the home menu and tracks
8. select the Chromecast player
9.  start playing the track
10. now, go to settings again, and open the chromecast player setting again
11. change the sampling rate to a value that’s not presently enabled.
12. click save
13. The playback will pause very shortly, and then continue, but start with a fade-in effect, even though I have crossfade disabled for the device.

I realize a pause is inevitable when changing sampling rate, but the fade-in is not mandatory, and the crossfade setting should be respected in this situation. It's definitely a minor problem, but every time I hear a harpsichord change volume, it bugs me, since that instrument doesn't have the ability to change volume.

### Music Providers

Reproduced with :

File system (remote share)
Qobuz

Couldn't find a music provider it didn't happen with. I think this is purely a player problem.

### Player Providers

Chromecast, only using an individual device

### Full log output

It would be helpful if the default log filename was "log.txt" rather than "log", since "log" without extension cannot be dragged and dropped into github.

[log.txt](https://github.com/user-attachments/files/15751599/log.txt)

### Additional information

None

### What version of Home Assistant Core are your running

2024.6.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Windows

**Comment by marcelveldt** [comment]
This is on purpose, its just a restart of the stream with a "resume" effect.
So nothing to worry about.
