### ISSUE TITLE
Can't open remote share or subfolders containing spaces

### ISSUE THREAD

**Issue by madbrain76** [music-assistant/hass-music-assistant#2426]
### What version of Music Assistant has the issue?

2.0.4

### What version of the Home Assistant Integration have you got installed?

2024.5.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

It's not possible to mount an SMB/CIFS share with a space in it, or subfolder with a space in it

### How to reproduce

For the share name issue :
1. Open settings
2. Add music profile
3. Select file system (remote share)
4. enter server hostname, username, and password
5. for the share, choose one that has a space in it. I chose "Space test"
6. leave folder blank
7. click save
8. Observe the error

![image](https://github.com/music-assistant/hass-music-assistant/assets/57333073/fcbafab6-6cad-4c93-8402-f3fd0b0c0e2f)

For the folder name issue :
1. Open settings
2. Add music profile
3. Select file system (remote share)
4. enter server hostname, username, password, and share (without space)
5. enter a subfolder name with a space . I chose "Space Folder"
6. click save
7. Observe the error

![image](https://github.com/music-assistant/hass-music-assistant/assets/57333073/3e2457e0-27df-4604-b125-7363726a7ce0)

I tried escaping the spaces, or using quotes around the strings, but nothing worked.
To be fair, I also have a space in my Windows username, and that worked fine.

### Music Providers

N/A

### Player Providers

File system (remote share)
No issue with local file system with space in folders (share name not applicable)

### Full log output

[log.txt](https://github.com/user-attachments/files/15752008/log.txt)

### Additional information

Not applicable

### What version of Home Assistant Core are your running

2024.6.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Windows

**Comment by marcelveldt** [comment]
Just fixed. Available in next patch release

**Comment by madbrain76** [comment]
Thank you

**Comment by OzGav** [comment]
Confirmed fixed in 2.1.0b3
