### ISSUE TITLE
M3U playlists can not contain backslashes in file path

### ISSUE THREAD

**Issue by clavius11** [music-assistant/hass-music-assistant#2432]
### What version of Music Assistant has the issue?

2.0.4

### What version of the Home Assistant Integration have you got installed?

2024.5.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

My playlist were generated by Windows Media Player.  The file path contains backslashes, which are typical for the Windows file system.  When I add the playlists to MA as a Provider, they appear empty and the MA log contains errors.  

To verify backslashes were the issue, I manually replaced the backslashes with forward slashes and the song appeared in the MA playlist.

### How to reproduce

Create a M3U playlist with a single song entry.  If needed, change the file pathname for the song to use backslashes instead of forward slashes.  Example:
`#EXTM3U`
`#EXTINF:0,01 - Prologue.mp3`
`..\Loreena McKennitt\The Book of Secrets\01 - Prologue.mp3`

### Music Providers

1) Open Windows Media Player
2) create a playlist
3) File > Save Now Playing list as...
4) Save playlist as M3U format

### Player Providers

Filesystem (remote share)

### Full log output

[MA Log.pdf](https://github.com/user-attachments/files/15755154/MA.Log.pdf)

### What version of Home Assistant Core are your running

2024.6.1

### What type of installation are you running?

Home Assistant Core

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Thanks this will be fixed in due course. As you have discovered do a global search and replace for now.
