### ISSUE TITLE
Music Assistant Music Provider "Documentation" menu entry leads to 404 link

### ISSUE THREAD

**Issue by madbrain76** [music-assistant/hass-music-assistant#2433]
### What version of Music Assistant has the issue?

2.0.4

### What version of the Home Assistant Integration have you got installed?

2024.5.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Trying to get help on the Music Assistant provider leads to a non-working page

### How to reproduce

a. Open MA
b. go to settings
c. select the | menu on the Music Assistant music provider
d. select Documentation
e. end up at https://music-assistant.io/music-providers/builtin/ , which is a 404 page

![image](https://github.com/music-assistant/hass-music-assistant/assets/57333073/971a530e-19de-4111-a9ab-a292d3fbbb96)

### Music Providers

Music assistant built-in

### Player Providers

N/A

### Full log output

[log.txt](https://github.com/user-attachments/files/15756047/log.txt)

### What version of Home Assistant Core are your running

2024.6.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Windows

**Comment by OzGav** [comment]
yes known. Fix is awaiting the next update in a day or two. Thanks.
