### ISSUE TITLE
Odd queue / played behavior in player view

### ISSUE THREAD

**Issue by madbrain76** [music-assistant/hass-music-assistant#2435]
### What version of Music Assistant has the issue?

2.0.4

### What version of the Home Assistant Integration have you got installed?

2024.5.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

The queue says it has 18 items in it, but sometimes shows as empty. Also, the "played" list, which has 0 entries, shows unnecessary top/down arrows

### How to reproduce

1. login to native Qobuz app
2. favorite the album by Robert Edward Smith, "Harpsichord in the grand manner"
3. In MA, add the Qobuz music provider
4. Go to the album view
5. Select the above album
6. Select a speaker. I used a CCA
7. Press the blue "Play" button to play the album
8. go to the player view on the bottom left by clicking on the album artwork
9. click the "queue" icon on the bottom right
10. the window shows 18 tracks in the queue
![image](https://github.com/music-assistant/hass-music-assistant/assets/57333073/9de46c14-0323-4d06-b5ac-4561c3467fa6)

12. click "played" on the top right
13. since no track has completed playback yet, it shows an empty list, which is correct. But there are odd-looking top/bottom arrows, that probably could be hidden or greyed out in this situation

![image](https://github.com/music-assistant/hass-music-assistant/assets/57333073/1a5c678a-3be5-4a35-94c5-6bd6571476d8)

14. click "queue"
15. the screen now shows only one track in the queue - the one currently being played, even though the header at the top says here are 18 items in the queue.

![image](https://github.com/music-assistant/hass-music-assistant/assets/57333073/8476587b-a459-45f9-9afe-7ead3567e082)

### Music Providers

Qobuz

Haven't tried the other providers yet . Will try file system (remote share)

### Player Providers

Chromecast

### Full log output

[log.txt](https://github.com/user-attachments/files/15757367/log.txt)

### Additional information

N/A

### What version of Home Assistant Core are your running

2024.6.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Windows

**Comment by OzGav** [comment]
Cant see the little arrows. Might be a browser specific issue. For the other confirmed frontend bug,

**Comment by madbrain76** [comment]
Yes, I was using Firefox. The behavior is different with Chrome. There are no scroll bars at all in either in the "queue" or "played" view on Chrome. It's only possible to scroll down with the scroll wheel.
However, the behavior in step 15 - with the queue listing only 1 track - is the same.

**Comment by OzGav** [comment]
Confirmed fixed
