### ISSUE TITLE
TTS Announcements on Airplay Groups doesn't work correctly

### ISSUE THREAD

**Issue by MrHollowPS** [music-assistant/hass-music-assistant#2436]
### What version of Music Assistant has the issue?

2.1.0b2

### What version of the Home Assistant Integration have you got installed?

2024.5.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When you create a new AIRPLAY group that will be used for TTS Announcements and use it with the tts.speak as the media_player entity in a script (at least that's how i use it), after running for more than 2 times the home assistant chime announcement is enabled and a queue is resumed even if nothing is actually playing.

### How to reproduce

1) in MA create a new airplay group with 2 airplay speakers (I have 2x Denon Home 150)
2) for the airplay group set the settings in the screenshot
![Screenshot 2024-06-10 at 10 52 45](https://github.com/music-assistant/hass-music-assistant/assets/5260147/2dc23e41-0500-456b-ae13-f9c750066e55)
3) in HA create a new script
4) add a TTS Speak service, set something for it to say and choose the MA airplay group
5) run the script two times and it works (but only on one speaker)
6) run the script the third fourth etc times, it will have the chime PreAnnounce TTS enabled and start playing music even though there was nothing playing previously

### Music Providers

Announce

### Player Providers

Airplay

### Full log output
[d5369777_music_assistant_beta_2024-06-10T07-56-46.523Z.log](https://github.com/user-attachments/files/15759045/d5369777_music_assistant_beta_2024-06-10T07-56-46.523Z.log)
[home-assistant_mass_2024-06-10T07-56-26.858Z.log.zip](https://github.com/user-attachments/files/15758954/home-assistant_mass_2024-06-10T07-56-26.858Z.log.zip)

### What version of Home Assistant Core are your running

2024.6.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Might be related to this https://github.com/music-assistant/hass-music-assistant/issues/2117

**Comment by marcelveldt** [comment]
Please re-test this after updating to 2.1.0b5 as I found a few issues and fixed them.

**Comment by OzGav** [comment]
@MrHollowPS please check if this has been fixed

**Comment by OzGav** [comment]
This will be closed soon assumng fixed.
