### ISSUE TITLE
YTM no longer plays with version 2.1.0b3

### ISSUE THREAD

**Issue by TheWebMachine** [music-assistant/hass-music-assistant#2438]
### What version of Music Assistant has the issue?

2.1.0b3

### What version of the Home Assistant Integration have you got installed?

2024.5.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

YTM works fine in b2, but b3 it will not play anything or enqueued anything from YTM. Everything shows up in Playlists etc, but nothing will play when selected. No errors or other information appears in logs. As soon as I roll back to b2, all works normally again.

### How to reproduce

Select any YTM song, playlist, etc and attempt to play on any speaker or group with 2.1.0b3. Nothing will enqueue and nothing will play.

### Music Providers

YTM

### Player Providers

Google Cast

### Full log output

No log output generated during error condition. It's as if the request is entirely ignored by MA.

### What version of Home Assistant Core are your running

2024.6.0

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
@TheWebMachine please confirm this is fixed in 2.1.0b4

**Comment by TheWebMachine** [comment]
All good now on b4! Thanks! 😎
