### ISSUE TITLE
Sonos S1 & S2 coexistence

### ISSUE THREAD

**Issue by mycanaletto** [music-assistant/hass-music-assistant#2439]
### What version of Music Assistant has the issue?

2.0.4

### What version of the Home Assistant Integration have you got installed?

2024.6.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Like many people, I use Sonos S1 and Sonos S2 together.

This subject has already been discussed here
https://github.com/music-assistant/hass-music-assistant/issues/2257

### How to reproduce

If none of the S1 speakers are switched on, MA recognises the Sonos S2 speakers when they are added. On the other hand, if one (or more) speakers in the S1 group are on, it recognises them but never sees those in the S2 group.

Sonos having practised programmed obsolescence, I don't think I'm the only one in this situation, and I was thinking of using MA to get round this problem....

### Music Providers

Local NAS and Spotify

### Player Providers

Sonos

### Full log output

[MA.txt](https://github.com/user-attachments/files/15787282/MA.txt)

### What version of Home Assistant Core are your running

2024.6.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
If you saw the other issue what do you want to achieve from this issue report?

**Comment by mycanaletto** [comment]
OK, sorry, I got that one wrong. So all we can do now is wait....
https://github.com/music-assistant/hass-music-assistant/issues/1184

**Comment by Thyraz** [comment]
But the other one closed ant the last comment was to open a new issue if it happens again.
So maybe this new issue report isn't completely wrong?

**Comment by mycanaletto** [comment]
> But the other one closed ant the last comment was to open a new issue if it happens again.
> So maybe this new issue report isn't completely wrong?

The problem still exists, so I'll wait.

**Comment by OzGav** [comment]
I believe 2284 as linked in the report covers this so closing this duplicate

**Comment by mycanaletto** [comment]
Yesterday I couldn't see everything, but this morning I can see all my devices, grouped or not, S1 or S2 without distinction.

I had activated network scanning in Sonos from the start.

So it seems to take a little time.

Thank you for your help and work on this.
![image](https://github.com/music-assistant/hass-music-assistant/assets/45459269/f0b807ba-0c89-4f80-be98-fb02cfa6cf20)
