### ISSUE TITLE
Unable to locate RAOP Play binary for linux/aarch64

### ISSUE THREAD

**Issue by chasut** [music-assistant/hass-music-assistant#2442]
### What version of Music Assistant has the issue?

2.1.0b4

### What version of the Home Assistant Integration have you got installed?

2024.5.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

After update to the latest beta, attempted to select an airplay player and received this error. "Unable to locate RAOP Play binary for linux/aarch64".

### How to reproduce

Setup airplay or attempt to play to existing airplay player.

### Music Providers

NA

### Player Providers

Airplay

### Full log output

[log.txt](https://github.com/user-attachments/files/15795294/log.txt)

### Additional information

Log is from fresh uninstall/re-install of the add-on.  I did a full uninstall and reinstall of the add-on as well as custom integration.
HAOS on M2 Mac, so generic-aarch64

### What version of Home Assistant Core are your running

2024.6.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

macOS

**Comment by Frederick-G764** [comment]
I have the same setup and the same issue.

**Comment by eamonnsullivan** [comment]
I'm running Music Assistant on a Raspberry Pi, with a Ubuntu 20.04, and when I installed b4, all of my airplay devices stopped working, but the chromecast ones still worked. Sounds like the same issue.

**Comment by sdg05** [comment]
same issue on a RPI4 running HAOS, first install of the beta version, Sonos works, no airplay to the HomePods

Unable to locate RAOP Play binary for linux/aarch64

**Comment by marcelveldt** [comment]
Should be fixed in the last update.

**Comment by OzGav** [comment]
@chasut @Frederick-G764 @sdg05 can one of you confirm this has been fixed

**Comment by sdg05** [comment]
Thank much! That fixed it for me.. On Jun 13, 2024, at 7:37 PM, OzGav ***@***.***> wrote:﻿
@chasut @Frederick-G764 @sdg05 can one of you confirm this has been fixed

**Comment by chasut** [comment]
Yes, looking good!  Thank you.
