### ISSUE TITLE
Beta changelog not up to date in home assistant add-on 

### ISSUE THREAD

**Issue by ministryofsillywalks** [music-assistant/hass-music-assistant#2444]
### What version of Music Assistant has the issue?

2.1.0b4

### What version of the Home Assistant Integration have you got installed?

2024.5.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

The changelog of the home assistant add-on shows the notes for 2.1.0b2 but nothing for b3 and B4
![Screenshot_20240612-070218](https://github.com/music-assistant/hass-music-assistant/assets/10544895/c82a675d-af6d-414b-9327-fecd2bd1ddcf)

### How to reproduce

Change to beta channel of the add-on 
Wait for update 
Check changelog 

### Music Providers

-

### Player Providers

-

### What version of Home Assistant Core are your running

2024.6.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
@jozefKruszynski ?

**Comment by jozefKruszynski** [comment]
Yeah there was an issue with the build recently and the bameta number was manually bumped.

I guess we need to update the changelog manually too 😃

**Comment by OzGav** [comment]
One off then. Closing

**Comment by ministryofsillywalks** [comment]
Update B6 is available and changelog still shows b5
![Screenshot_20240615-113100](https://github.com/music-assistant/hass-music-assistant/assets/10544895/e487721d-5c9e-4963-8d4d-360d5abfc5b2)

**Comment by marcelveldt** [comment]
@jozefKruszynski ideas?

**Comment by ministryofsillywalks** [comment]
FYI
Still broken.
b7 available
b6 installed
Changelog shows b5

**Comment by OzGav** [comment]
Thanks we have made a manual change and are working on the automatics!
