### ISSUE TITLE
VInfiniteScroll in ItemsListing.vue missing items after disabling the "favs only" option

### ISSUE THREAD

**Issue by Thyraz** [music-assistant/hass-music-assistant#2456]
### What version of Music Assistant has the issue?

2.1.0b4

### What version of the Home Assistant Integration have you got installed?

-

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When removing a filter (favorites filter or search filter) in the artist view, the infinity scroller won't load additionally items after the first 50 initially loaded ones.

After switching to a different tab like playlists and back, it's working again.

### How to reproduce

- Open the Artist tab with more than 50 artists in your library (and maybe less than 50 artist marked as favorites).
- Select to see only favorited artists, or use the search inside the artist view (NOT the global search) to only see a subset of your artists
- Remove the filter to see all artists again
- Scroll down to load more than the inital 50 entries

Now the infinity scroller won't add additional items.

### Music Providers

-

### Player Providers

-

### Additional information

Related discussion on Discord that also includes a video demonstrating that problem:
https://discord.com/channels/753947050995089438/1247654189828538389/1250318548174110781

### What version of Home Assistant Core are your running

2024.5.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
@Thyraz please confirm if this has been fixed

**Comment by Thyraz** [comment]
It's fixed 🙂👍
