### ISSUE TITLE
play_media Service Call with Media ID "{{ range(1,99) | list }}" fails with “list indices must be integers or slices, not str”

### ISSUE THREAD

**Issue by fluxor99232** [music-assistant/hass-music-assistant#2465]
### What version of Music Assistant has the issue?

2.0.6

### What version of the Home Assistant Integration have you got installed?

2024.5.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

play_media Service Call with Media ID "{{ range(1,99) | list }}" fails with “list indices must be integers or slices, not str”. Used to work until very recently. Media ID “[1,2,3]” works.

### How to reproduce

![IMG_6231](https://github.com/music-assistant/hass-music-assistant/assets/117677599/2d0a16f5-007f-4352-8e34-29d2120c36eb)
![IMG_6232](https://github.com/music-assistant/hass-music-assistant/assets/117677599/203f337e-8b6a-4459-9e64-de53e2fe2b4a)

### Music Providers

Radio

### Player Providers

AirPlay

### What version of Home Assistant Core are your running

2024.6.2

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
You aren’t using the latest version of the integration
 Please update and try again

**Comment by OzGav** [comment]
But more importantly why do you expect that to even work. That is not a valid uri

**Comment by fluxor99232** [comment]
> You aren’t using the latest version of the integration Please update and try again

Oh, strange that I didn’t get the update notification!

Updated 2024.6.0, tried again. Now I get:

> 'list' object has no attribute 'items'

**Comment by marcelveldt** [comment]
This issue has just been fixed, new update will arrive within an hour

**Comment by fluxor99232** [comment]
> This issue has just been fixed, new update will arrive within an hour

Oh, wow! You guys are next level! 😯
