### ISSUE TITLE
Radio fails to start in YouTube Music

### ISSUE THREAD

**Issue by sspaul1976** [music-assistant/hass-music-assistant#2469]
### What version of Music Assistant has the issue?

2.1.0b5

### What version of the Home Assistant Integration have you got installed?

2024.5.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When attempting to start a radio from a YouTube music, playlist, receive error, "Sample larger than population or is negative".  This seems to happen in playlists where there is a single track.

### How to reproduce

1. Open MA
2. Choose Playlist from YouTube Music 
3. Click arrow on blue Play button 
4. Select Start Radio
5. Error follows... 

![Screenshot_20240614-125921](https://github.com/music-assistant/hass-music-assistant/assets/6181510/066cd043-0ebe-49ed-a5d6-73a1d62a6a0a)

### Music Providers

YouTube Music 

### Player Providers

Chromecast, DLNA

### What version of Home Assistant Core are your running

2023.8.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

ODROID

**Comment by OzGav** [comment]
@MarvinSchenkel

**Comment by MarvinSchenkel** [comment]
Fixed in https://github.com/music-assistant/server/pull/1401

**Comment by MarvinSchenkel** [comment]
Beta 9 should have this fix included, can you verify?

**Comment by OzGav** [comment]
@sspaul1976 We will close this soon assuming it is fixed unless you advise otherwise

**Comment by sspaul1976** [comment]
Sorry for the delay. This has been resolved, thank you!
