### ISSUE TITLE
Add Greek Translation

### ISSUE THREAD

**Issue by mmpalasc** [music-assistant/hass-music-assistant#2470]
### New language

Greek

**Comment by OzGav** [comment]
There are a couple of options. Do you know which one you are after? 

<img width="601" alt="image" src="https://github.com/music-assistant/hass-music-assistant/assets/19848947/9de50ff5-6f4e-449d-aa51-fc5840ed286c">

**Comment by mmpalasc** [comment]
My option is el_GR

**Comment by OzGav** [comment]
Thanks for helping out. That has been added.
