### ISSUE TITLE
Odd Python error stack when installing Plex provider

### ISSUE THREAD

**Issue by madbrain76** [music-assistant/hass-music-assistant#2473]
### What version of Music Assistant has the issue?

2.0.6

### What version of the Home Assistant Integration have you got installed?

2024.6.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Two instances of the MA integration may be inadvertedly created, and this leads to errors

### How to reproduce

Unfortunately, I'm not 100% sure. I have seen the error stack page multiple times since upgrading to 2.0.6, though.
I believe it is related to circumstances in which there are two MA integrations talking to the single add-on instance.
I started writing a test case, but the issue didn't initially come up. But it happened soon after. I just don't know exactly what triggered it, unfortunately. Here are the steps that I believe may still be helpful.

I'm definitely able to reproduce the first error in step 9, though. The second error shown in step 17 is less predictable.

1. delete all instances of MA integration and add-on
2. restart HA
3. install MA add-on
4. start the add-on
5. turn on the watchdog, autoupdate and sidebar
6. a new device is found by HA for the MA integration. Click configure, and submit
7. add an instance of the Plex music provider
8. click save
9. this odd error comes up

![image](https://github.com/music-assistant/hass-music-assistant/assets/57333073/10e2f099-ce05-484d-8c00-08858c338115)

This looks like issue 1602, which was closed earlier this year. But I can reproduce this still.

10. click OK
11. delete the MA add-on
12. repeat steps 3 through 6
13. start the MA add-on
14. there are now two instances of the MA integration, both of which are seemingly active at the same time. I did not notice this the first time around. This is probably not intended, and might deserve its own separate issue.

![image](https://github.com/music-assistant/hass-music-assistant/assets/57333073/3b61a9e6-93eb-4c2e-9bf1-d5799f51d684)
15. open the MA add-on
16. Add Plex music provider
17. this odd error shows up. Or at least, it did once, but I'm not certain how to reproduce from scratch anymore.
![image](https://github.com/music-assistant/hass-music-assistant/assets/57333073/e727ddb1-ad16-4697-b27c-47c832b06742)

### Music Providers

Plex

### Player Providers

N/A

### Full log output

[log.txt](https://github.com/user-attachments/files/15845919/log.txt)

### What version of Home Assistant Core are your running

2024.6.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Windows

**Comment by madbrain76** [comment]
Note that I'm able to get the Plex provider to work after the error in step 9 . I don't believe I could when I ran into the error in step 17. I believed I deleted/reinstalled MA at that point.

I think the step 9 error is due to an HAOS config change I made to get the Piper to work yesterday.

In Settings / System / Networks, I had to set the internal URL like this :

![image](https://github.com/music-assistant/hass-music-assistant/assets/57333073/6bd9e9f5-75bc-4d0e-92ab-a9e9ad667cc6)

I previously had it set to automatic.

Piper failed to play any sample audio until this was changed.

I use SSL because it's required by Z-Wave smart start. And since it's an internal domain, I use a self-managed CA.

If I revert to automatic, HA shows this error :

![image](https://github.com/music-assistant/hass-music-assistant/assets/57333073/231ec46e-db22-4097-b405-fd762fb11975)

Which isn't new, but I had never seen it before as I had not visited this page after adding SSL.

**Comment by madbrain76** [comment]
Yes, after I removed that setting, I immediately got error 17 again. Test case :
1. go to settings / system / network
2. make sure internal URL is automatic (and probably no external URL, also)
3. uninstall MA add-on and integration
4. restart HA
5. install and start add-on
6. install integration
7. add Plex music provider
8. click save
9. get this error :

![image](https://github.com/music-assistant/hass-music-assistant/assets/57333073/5808fdfa-90df-49d6-9ac8-1cd10df0361a)

[log.txt](https://github.com/user-attachments/files/15846308/log.txt)

If step 7 is repeated, I'm actually still able to add this music provider.

**Comment by OzGav** [comment]
Is this still an issue with 2.1.0

**Comment by OzGav** [comment]
We will close this soon if there is no followup
