### ISSUE TITLE
Volume Music Assistant ( Sonos ) not changed by HA on iPhone.

### ISSUE THREAD

**Issue by caro7372** [music-assistant/hass-music-assistant#2474]
### What version of Music Assistant has the issue?

2.0.6

### What version of the Home Assistant Integration have you got installed?

2024.6.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When changing the volume on Macbook ( HA via Browser ) in Music Assistant playing on Sonos I can change the volume.
If I want to do this on my iPhone ( web and native app ) nothing happens when I change the slider.

### How to reproduce

Re-started etc but no change.

### Music Providers

Tune-In & Spotify

### Player Providers

Sonos

### What version of Home Assistant Core are your running

2024.6.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

ODROID

**Comment by marcelveldt** [comment]
Please update to 2.0.7, there was a bug introduced in 2.0.6

**Comment by caro7372** [comment]
Yes, that works! Thanks for the update.
I really like Music Assistant instead of Sonos Native app.

Regards,

Robert
