### ISSUE TITLE
Player view not presenting player name correctly

### ISSUE THREAD

**Issue by madbrain76** [music-assistant/hass-music-assistant#2475]
### What version of Music Assistant has the issue?

2.0.6

### What version of the Home Assistant Integration have you got installed?

2024.6.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

In Firefox on desktop, the player name is shown in a strange location, below the volume control, to the left, partially off-frame, and with a very difficult to read color scheme - blue lettering on brown background.

![image](https://github.com/music-assistant/hass-music-assistant/assets/57333073/62275be4-dc71-485c-adf5-f3b5f4d84550)

### How to reproduce

1. go to the album view
2. select a player on the right. I used a CCA
3. select an album
4. press play
5. click the player view on the bottom left
6. the screenshot above should show up

### Music Providers

- Plex alone
- Plex + FS + Qobuz (album duplicate in all 3

### Player Providers

Chromecast

### Full log output

[log.txt](https://github.com/user-attachments/files/15846213/log.txt)

### Additional information

The player name is not shown at all in the mobile app. I'm not sure if this is intentional, if it is off-screen also. It would be very valuable to me if it were shown in the app also as I have many different players.

### What version of Home Assistant Core are your running

2024.6.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Windows

**Comment by marcelveldt** [comment]
Sigh... more Firefox issues. It used to be a great browser but recently it's becoming a pain. Stuff that is correct on every browser is just crap on Firefox.

I don't have capacity to test every hiccup with Firefox, sorry. Maybe for now, until we get some more help on the frontend, we should ditch Firefox support

**Comment by madbrain76** [comment]
@marcelveldt 

I know FF has dropped to a very low marked share, but I truly hope that doesn't happen.

I think browser monoculture is a very bad thing. In the 1990s we had a tons more web browser engines that were all completely different. Then Microsoft tried to steamroll everyone. Now Google is doing the same with Chromium.
While I never worked on browser GUI, I did work at Netscape and Sun on security components still used by FF to this day.
My HTML 2.0 skills are probably still good, but unfortunately I doubt I can help MA with anything frontend related.

**Comment by madbrain76** [comment]
BTW, the color is still problematic even in Chrome, though the placement is not .

![image](https://github.com/music-assistant/hass-music-assistant/assets/57333073/ca7caf37-005e-4d3d-b6ff-b2f8374e14ee)

I have some macular degeneration, and just can't read this text at all.  I see the edges of the box and the speaker icon, vaguely. But not the speaker name.

If I enlarge it, it gets to a point where the speaker name goes off screen, but there is no scroll bar to go down and see the speaker name.

![image](https://github.com/music-assistant/hass-music-assistant/assets/57333073/8086f90e-5459-4fcd-bd7a-091c3507e9a5)

The lack of scroll bar when enlarging is common to both FF and Chrome. It's not a problem in other HA pages.

Even if you don't want to fully support Firefox right now, consider the accessibility aspect.

**Comment by OzGav** [comment]
Marcel isn’t saying the project will only support one browser just that maybe Firefox is too hard with the VERY limited man hour resources available. Safari isn’t far behind. At some point a line has to be drawn.

As for the colour scheme that came up internally a couple of days ago and is being looked at by the part time frontend dev.

**Comment by marcelveldt** [comment]
Firefox is the new Safari... just joking a it but its becoming true unfortunately.

**Comment by madbrain76** [comment]
Safari and Chrome still have a bunch in common. Safari uses Webkit, and Chrome uses a fork of Webkit. I'm not sure how much that fork has diverged.

That said, I don't think mobile browsers need to be fully supported on devices that have native HA/MA apps.

But for desktop use, browsers really do need to be well supported.

Safari and Firefox now have very similar market share on desktop - both very low.
https://gs.statcounter.com/browser-market-share/desktop/worldwide

It's very sad that FF has gone down 10-fold in 15 years - from 30% to 3%.
I'm not sure what it would take to reverse the decline.

**Comment by OzGav** [comment]
I just downloaded the latest Firefox browser and the player is positioned correctly centre bottom. @madbrain76 please check with Firefox 131.0.3

**Comment by OzGav** [comment]
Closing as this cannot be replicated with the current version of Firefox. Can be reopened if necessary.

**Comment by madbrain76** [comment]
Verified that it now works fine.
