### ISSUE TITLE
Random characters appear in artwork square after clearing the queue in player view

### ISSUE THREAD

**Issue by madbrain76** [music-assistant/hass-music-assistant#2476]
### What version of Music Assistant has the issue?

2.0.6

### What version of the Home Assistant Integration have you got installed?

2024.6.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When going to the player view, and using "| Clear all items in the queue", it results in odd characters being shown, such as :

![image](https://github.com/music-assistant/hass-music-assistant/assets/57333073/c9486f20-8751-4ace-9737-640f0e85854a)

![image](https://github.com/music-assistant/hass-music-assistant/assets/57333073/f7595fb0-ac01-4301-be7c-2e09f31b012e)

### How to reproduce

1. go to the album view
2. select a player on the right. I used a CCA
3. select an album
4. press play
5. click the player view on the bottom left
6. click "`| clear all items in the queue"
7. screenshot similar to the above should appear

### Music Providers

Plex

### Player Providers

Chromecast

### Full log output

[log.txt](https://github.com/user-attachments/files/15846224/log.txt)

### What version of Home Assistant Core are your running

2024.6.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Windows

**Comment by marcelveldt** [comment]
That is called an avatar and it's by design. It contains the letters of your player

**Comment by madbrain76** [comment]
@marcelveldt ,
The letters of my player ? I honestly don't understand what you mean. I looked at the list of players, and I don't see letters.
Kindly point me to what they are/where else they are shown.
