### ISSUE TITLE
core log filename should be compatible with github

### ISSUE THREAD

**Issue by madbrain76** [music-assistant/hass-music-assistant#2477]
### What version of Music Assistant has the issue?

2.0.6

### What version of the Home Assistant Integration have you got installed?

2024.6.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When downloading the log file, the default name is just "log" without an extension. The issue filing instructions say to drag and drop the file, but it is not possible without renaming it to a supported extension, such as .txt . 

### How to reproduce

1. go to MA / settings / core
2. click "download logfile" at the bottom
3. open an issue on MA / HASS
4. drag and drop the file to one of the text boxes, or use the attach button
5. get the following error

![image](https://github.com/music-assistant/hass-music-assistant/assets/57333073/e6660f64-1b70-4337-bf65-7946726b2c95)

### Music Providers

N/A

### Player Providers

N/A

### Full log output

N/A

### Additional information

I would suggest .txt for small logs . For anything over the 25MB default github file limit (or 100MB for paid github plan), use some supported compressed format.

Obviously, this is not the most pressing issue, but anything that shortens the issue filing time is a win in my book. I would submit a PR myself if I knew where to look.

### What version of Home Assistant Core are your running

2024.6.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Windows

**Comment by marcelveldt** [comment]
Makes sense to just append .txt despite the fact that makes reading the log harder in an actual log viewer. Lame restriction if GitHub imo

**Comment by madbrain76** [comment]
@marcelveldt ,
Which log viewing program are you using ?

**Comment by marcelveldt** [comment]
I use the log viewer on MacOS, works great for me.

I'll just add the txt extension that would be the best/easiest in this case

**Comment by madbrain76** [comment]
Thank you very much ! I use Windows & some variants of Linux, mainly. Typically, an old version of SlickEdit is my editor/viewer of choice, featuring good old OS/2 CUA keyboard shortcuts.
