### ISSUE TITLE
Queue terminology could use improvement

### ISSUE THREAD

**Issue by madbrain76** [music-assistant/hass-music-assistant#2478]
### What version of Music Assistant has the issue?

2.0.7

### What version of the Home Assistant Integration have you got installed?

2024.6.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

The word "played" as it relates to the queue in the player view is not always accurate

### How to reproduce

1. select a player
2. select an album
3. press the blue Play button
4. click the player icon on the bottom left
5. click the queue icon on the bottom right
6. the top of the screen shows "Queue 18" and "Played 0"
![image](https://github.com/music-assistant/hass-music-assistant/assets/57333073/46fba846-1883-47ad-b0c5-472e108d4e2b)
7. now, click the BWV 992 VI movement (track 8) to play it. The screen now shows "Queue 11" and "Played 7"
![image](https://github.com/music-assistant/hass-music-assistant/assets/57333073/6cd0e326-9d64-41d0-bb04-56bf46ccd1e4)
Technically, only the first and the 8th track have been played. 6 of them have been skipped.

### Music Providers

All

### Player Providers

All

### Full log output

Not relevant

### Additional information

This may officially be considered a nit, but it still came to mind. A very simple cosmetic change would be to rename "Played" to something more along the lines of "Prior" or "Previous".

Or there also could be a breakdown of "Played" and "Skipped", but that would be a functional change/enhancement.

### What version of Home Assistant Core are your running

2024.6.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Windows

**Comment by OzGav** [comment]
I can only reiterate again that this project is maintained by a small team. Filing an issue report takes your time and our time to respond. This is a semantic point that at best is a feature request but I would disagree with it regardless. The majority use case is people playing back their queue one after the other in which case PLAYED is entirely appropriate.

**Comment by madbrain76** [comment]
Ozgave,

I'm not trying to consume your time doing triage. I clearly denoted this issue as a nit. Github doesn't have a way for the filter to formally give a suggested priority to this kind of issue. I would have set it to low in this case, if there was a way, so you could choose to spend triage time on the higher priority issues first, and get to the lower priority ones later on, even if only to close them as you did this one. Again, this comes down to severe limitations of the github issue tracker.

**Comment by OzGav** [comment]
Its not even an issue though as it is just your preference. So as I mentioned at best this should have been a feature request.

We like to be responsive to issues in this project. If you open a feature request then we often just monitor that for traction from other users.

**Comment by marcelveldt** [comment]
Maybe we just mark such things with a feature request label or whatever if we thinks its sensible (but just low prio) ?
That said, personally I dont think the descriptions are weird at all, I think everyone will understand that if you skip tracks, they will move to the "played" list. I think trying to think up other names for that list will make UX worse, not better.

But that is where a feature request discussion is good for, get some other folks to jump in so you can taste the opinion.

**Comment by madbrain76** [comment]
The line between issue and feature request is sometimes blurry, as I have pointed out several times.
I wasn't sure that something as small as changing one word in the UI merited a full-fledged feature discussion.
But if it really does, then I will file this type of change request in the discussions.

I won't try to argue about the merits of this particular issue, or lack thereof. I accept your judgment.
