### ISSUE TITLE
Homeassistant mass.play_media broken  since 2.1.0b6

### ISSUE THREAD

**Issue by gpgmailencrypt** [music-assistant/hass-music-assistant#2479]
### What version of Music Assistant has the issue?

2.1.0b6

### What version of the Home Assistant Integration have you got installed?

2024.5.5

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

The call below ("How to reproduce") leads to an exception: "list indices must be integers or slices, not str"
It did work with all versions before 2.1.0b5. 

Same happens when a radio station is called

### How to reproduce

service: mass.play_media
target:
  entity_id: media_player.radio_test
data:
  media_id: The Best of Glenn Miller

### Music Providers

- filesystem (local)
- radiobrowser

### Player Providers

Sonos

### Full log output

[musicassistant.log](https://github.com/user-attachments/files/15846385/musicassistant.log)

### What version of Home Assistant Core are your running

2024.5.5

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Linux

**Comment by marcelveldt** [comment]
Please update the HA integration to 2024.6.2

**Comment by OzGav** [comment]
This has been reported as fixed in the latest version of the integration. Please advise if not for you.

**Comment by gpgmailencrypt** [comment]
Just updated, it works now. Thanks
