### ISSUE TITLE
Add new artist from spotify playlist, then it later disappears

### ISSUE THREAD

**Issue by m-milani** [music-assistant/hass-music-assistant#248]
If I look at one of my spotify playlists, and select an artist, then select "add to library", it goes into the list of artists.   I come back later, and it is gone.  This artist does not have any local files associated with it.

**Comment by marcelveldt** [comment]
hmm, this is a classic race condition. When you open an artist details for the very first details a background job is created to fetch all metadata. Once done the artist info metadata is cached in the db. In the meanwhile you're looking at a simplified/basic version of the artist and you press the "add to library button". This is however overwritten by the background task that wrote the artist to db. 

Normally the full artist info is fetched within 2 seconds. I think I will block the "add to library" button while the full info is not there yet to prevent this race condition

**Comment by marcelveldt** [comment]
this one is fixed in the 2022.6.b0 release
