### ISSUE TITLE
Error during start music from YouTube music after paied account

### ISSUE THREAD

**Issue by clpodes** [music-assistant/hass-music-assistant#2487]
### What version of Music Assistant has the issue?

2.0.7

### What version of the Home Assistant Integration have you got installed?

2024.6.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When I use YouTube music with paid account the system returns an error

### How to reproduce

all music gives error

### Music Providers

youtube music

### Player Providers

Google cast

### Full log output

[MASS_log1.txt](https://github.com/user-attachments/files/15848716/MASS_log1.txt)

### Additional information

Core 2024.6.2
Supervisor 2024.06.0
Operating System 12.3
Frontend 20240610.0

### What version of Home Assistant Core are your running

2024.6.2

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Windows

**Comment by Ben00793** [comment]
Same here.
![Screenshot_20240615-225253](https://github.com/music-assistant/hass-music-assistant/assets/132856308/d0a3ddcc-d44f-45ec-add5-3a1946c1d16f)

**Comment by robdepaul** [comment]
I had similar problems, I have MASS under Home Assistant setup. I tried to clear the MASS core cache under settings->core->cache controller (see attached screenshot) and that worked for me
<img width="833" alt="clear MASS cache" src="https://github.com/music-assistant/hass-music-assistant/assets/161502826/e70d9f7e-ae68-48ee-b423-93e93cf00a93">

**Comment by Ben00793** [comment]
> I had similar problems, I have MASS under Home Assistant setup. I tried to clear the MASS core cache under settings->core->cache controller (see attached screenshot) and that worked for me <img alt="clear MASS cache" width="833" src="https://private-user-images.githubusercontent.com/161502826/340078867-e70d9f7e-ae68-48ee-b423-93e93cf00a93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1Mjg5NTcsIm5iZiI6MTcxODUyODY1NywicGF0aCI6Ii8xNjE1MDI4MjYvMzQwMDc4ODY3LWU3MGQ5ZjdlLWFlNjgtNDhlZS1iNDIzLTkzZTkzY2YwMGE5My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNlQwOTA0MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kM2EzYzU5NGJlM2FlYzlhZTg1N2NjZjc3ZjcyZDAwMWIzNzcwMzU3MjZhZGNjNDhkYjA0ZjExYmFmZjAyNTQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.98sKRx6BKHn-qE-sA5HXey9d8ehb5YgZAAHulpi_BWk">

I tried this this morning. Didn't work.

**Comment by VicariousVeteran** [comment]
Same here, i even tried what robdepaul said and cleared the cache under settings->core->cache controller. Only YouTube music stopped working for me, my local library works perfectly. I have had it work a couple of times but most of the time i get that error.
![Screenshot 2024-06-16 191430](https://github.com/music-assistant/hass-music-assistant/assets/25601117/4efddac1-d389-4acf-8ed7-dc9a589e072d)

**Comment by OzGav** [comment]
@Tiernan23 Are you trying to play two streams at once?

**Comment by OzGav** [comment]
And just to confirm you are using a PAID YouTube Music account?

**Comment by OzGav** [comment]
Free accounts are not supported

**Comment by MarvinSchenkel** [comment]
We have never (and will never) support PAID music services for free. The fact that it used to work was just pure luck. 

All others:
1. Are you using a paid account?
2. Are you not listening to music using the same account on another device?
3. Please enable debug logging and provide a full log when trying to play an item using YTM, so I can see if there's anything wrong. (@clpodes your log only contains normal logging, please enable debug logging and try again :-) )

**Comment by clpodes** [comment]
@MarvinSchenkel here the request log with debug.
[nuovo log.txt](https://github.com/user-attachments/files/15909755/nuovo.log.txt)

**Comment by MarvinSchenkel** [comment]
> @MarvinSchenkel here the request log with debug. [nuovo log.txt](https://github.com/user-attachments/files/15909755/nuovo.log.txt)

The log complains about the provider not being available. Can you try removing the YTM music provider from the settings and adding it again and see if that helps?

**Comment by MarvinSchenkel** [comment]
We just release beta 8 that should fix issues with playback. Could you test this using the beta addon?

**Comment by OzGav** [comment]
Closing assumed fixed
