### ISSUE TITLE
Volume slider broken in several places

### ISSUE THREAD

**Issue by formatBCE** [music-assistant/hass-music-assistant#2488]
### What version of Music Assistant has the issue?

2.0.6

### What version of the Home Assistant Integration have you got installed?

2024.6.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Volume adjustment is broken in:
- full-screen player view
- players list (where current player is selected)
- bottom bar with current playback info (collapsed player view) ON MOBILE VIEW (when slider is on the bottom).

On the other hand, it works correctly in:
- HA integration media players 
- bottom bar with current playback info (collapsed player view) ON DESKTOP VIEW (when slider is on the right).

### How to reproduce

Start playback on player. Try to adjust volume.

### Music Providers

- Spotify
- YouTube Music
- Jellyfin

### Player Providers

- Squeezebox
- Fully kiosk
- Chromecast

### Additional information

I use Docker MA installation, if that's important.

### What version of Home Assistant Core are your running

2024.6.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

ODROID

**Comment by OzGav** [comment]
Update to 2.0.7

**Comment by formatBCE** [comment]
> Update to 2.0.7

Same situation.
