### ISSUE TITLE
Chromecast Speaker Groups that contain speakers in a stereo pair do not show as an available player

### ISSUE THREAD

**Issue by athua** [music-assistant/hass-music-assistant#2490]
### What version of Music Assistant has the issue?

2.1.0b6

### What version of the Home Assistant Integration have you got installed?

2024.5.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When using the Chromecast Provider, speaker groups setup in Google Home that contain speakers in a stereo pair do not appear as an available Player, however after a long period/overnight, it does appear as a Player and plays correctly.
However, on restarting Home Assistant or Music Assistant, the speaker group becomes unavailable again.

Google Speaker Groups that do not contain speakers in a stereo pair appear as a Player immediately and plays correctly.

### How to reproduce

1. Create a stereo pair in Google Home with two of the same type of Google Home speakers (in my case I tested with 2 x Google Home Minis as well as 2 x Harmon Kardon Citation One speakers)
2. Create a new Google Home Speaker Group with the stereo pair.
3. Check in Music Assistant and the new Speaker Group does not appear.
4. Create a new Google Home Speaker Group that does not contain a stereo pair.
5. Check in Music Assistant and the new Speaker Group without the stereo pair appears.

### Music Providers

File System (Remote Share) - speaker group does not appear
Spotify - speaker group does not appear

### Player Providers

Chromecast

### What version of Home Assistant Core are your running

2024.5.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Linux

**Comment by marcelveldt** [comment]
Stereo pairs in Google cast are full of bugs - its really a mess tbh.
I have added a few workarounds/bandaids already last couple of days but I cant get it waterproof. Note that in HA you see the same issues with stereo pairs. Try playing to a Cast group and notice that the stereo pair player has no knowledge of that at all, the whole underlying data is just absent.

Anyways, for this particular case, ensure there are also other speakers within that group

**Comment by marcelveldt** [comment]
This is no longer reproduceable - fact remains that the stereo pairs behave a bit funky within google cast:  It may not report its playing something while its added to a group. That is not a MA issue, but a Cast issue.
