### ISSUE TITLE
Docker compose music assistant server fails to start

### ISSUE THREAD

**Issue by mcflexus** [music-assistant/hass-music-assistant#2492]
### What version of Music Assistant has the issue?

2.0.7

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Trying to run the latest version of music assistant server with docker compose but getting errors. I used the docker compose example and changed the volumes but cant`t get it running. I`m using the latest version of debian and docker.

### How to reproduce

Run latest version with docker compose according to the compose example.

### Music Providers

none

### Player Providers

none

### Full log output

`2024-06-16 20:25:26.117 ERROR (MainThread) [music_assistant] Error doing task: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiorun.py", line 219, in new_coro
    await coro
  File "/usr/local/lib/python3.12/site-packages/music_assistant/__main__.py", line 212, in start_mass
    await mass.start()
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/server.py", line 111, in start
    self.aiozc = AsyncZeroconf(ip_version=IPVersion.V4Only)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/zeroconf/asyncio.py", line 166, in __init__
    self.zeroconf = zc or Zeroconf(
                          ^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/zeroconf/_core.py", line 180, in __init__
    listen_socket, respond_sockets = create_sockets(interfaces, unicast, ip_version, apple_p2p=apple_p2p)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/zeroconf/_utils/net.py", line 373, in create_sockets
    if add_multicast_member(cast(socket.socket, listen_socket), i):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/zeroconf/_utils/net.py", line 288, in add_multicast_member
    listen_socket.setsockopt(socket.IPPROTO_IP, socket.IP_ADD_MEMBERSHIP, _value)
OSError: [Errno 105] No buffer space available`

### What version of Home Assistant Core are your running

2024.6.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
Have you googled that error? It doesn’t appear to be a MA problem.

**Comment by mcflexus** [comment]
Running `sysctl -w net.ipv4.igmp_max_memberships=50` on the host fixed the problem.

**Comment by btpv** [comment]
i had the same issue and that solved it does anybody know why that fixes it

**Comment by edekeijzer** [comment]
> > Running `sysctl -w net.ipv4.igmp_max_memberships=50` on the host fixed the problem.
> 
> i had the same issue and that solved it does anybody know why that fixes it

Sonos relies heavily on multicast for device discovery. Apparently, MASS wants to do some multicast subscriptions, but the system already has some and the (conservative) default setting doesn't allow any more. Increasing this value allows you to make a lot more subscriptions so the problem is solved.
