### ISSUE TITLE
Disabled and re-enabled Airplay player is not usable until MA is restarted

### ISSUE THREAD

**Issue by madbrain76** [music-assistant/hass-music-assistant#2502]
### What version of Music Assistant has the issue?

2.0.7

### What version of the Home Assistant Integration have you got installed?

2024.6.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When disabling an Airplay player and its provider, and re-enabling them, the player remains disabled

### How to reproduce

1. add airplay provider
2. disable one (I chose backyard)
3. disable airplay provider
4. enable airplay provider
5. re-enable backyard
6. in the settings / players list, backyard has the hourglass - "this player is not (yet) available"
7. wait as long as you want, even an hour
8. backyard remains unavailable, and doesn't show in the player selection list
9. restart music assistant
10. backyard remains unavailable
11. wait some more, a couple minutes
12. backyard eventually becomes available

### Music Providers

File system (remote)

### Player Providers

Airplay
This issue does not occur on either DLNA/UPNP or Chromecast providers.

### Full log output

[log.txt](https://github.com/user-attachments/files/15879708/log.txt)

### Additional information

This may seem like a contrived case, but I ran into this without trying to break anything. It took a bit of time to isolate and reproduce. With the number of devices I have, and the WiiM 3x duplicated players, disabling a player provider is not so infrequent a task.

### What version of Home Assistant Core are your running

2024.6.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Windows

**Comment by OzGav** [comment]
Might be device specific as my Yamaha Amplifier came back straight away.

**Comment by madbrain76** [comment]
Quite possibly. The device I saw the problem with in this case was a WiiM Pro Plus. I just checked and am still able to reproduce it.

I do have an old Yamaha RX-A1000 receiver, but it only supports DLNA, not Airplay.

**Comment by madbrain76** [comment]
Adding comment. It is not right to automatically close issues for inactivity. This is by far my most hated feature of github. And I'll state it again every time I have to comment to keep a bug active.

**Comment by marcelveldt** [comment]
not stale

**Comment by OzGav** [comment]
Please check if this is still an issue in beta 34

**Comment by madbrain76** [comment]
Verified that this is fixed in 2.3.0rc3 .
