### ISSUE TITLE
DLNA provider: Configuring more than 2 sample rates not possible

### ISSUE THREAD

**Issue by dieneuser** [music-assistant/hass-music-assistant#2503]
### What version of Music Assistant has the issue?

2.0.7

### What version of the Home Assistant Integration have you got installed?

2024.6.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

In the DLNA provider section, if you select more than 2 sample rates, only the first two are saved. However, my AVR supports all offered sample rates.

### How to reproduce

1. In MASS settings: DLNA player
2. Go to _advanced settings_
3. Expand _Sample rates supported by this player_
4. Select all sample rates
![image](https://github.com/music-assistant/hass-music-assistant/assets/28509955/60a183c6-36ce-4b4b-99af-aef397d402bc)
6. Click on _save_
7. Only 2 of the selected items were saved
![image](https://github.com/music-assistant/hass-music-assistant/assets/28509955/0f8bc9a6-2678-4ca7-a687-3ff320dbbfdf)

### Music Providers

Music Assistant
File system (remote share)

### Player Providers

UPNP/DLNA player provider

### What version of Home Assistant Core are your running

2024.6.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Tried with slimproto provider and same problem.

**Comment by OzGav** [comment]
I no longer see this issue. Closing.
