### ISSUE TITLE
Playing playlist from a NAS location gives since few days error TypeError: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by brunobouillon** [music-assistant/hass-music-assistant#2505]
### What version of Music Assistant has the issue?

2.1.0b6

### What version of the Home Assistant Integration have you got installed?

2024.5.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

In Music assistant there is a playlist called 'playlistBruno'
I created a script that calls this script. It worked very well during months.
Since a few days i get the error : TypeError: list indices must be integers or slices, not str
I don't know what to do to repair. I reinstalled the server add-on and the integration.

script:
[Error_script_List_indices.txt](https://github.com/user-attachments/files/15890588/Error_script_List_indices.txt)

alias: Play Playlist from MA
sequence:
  - service: mass.play_media
    data:
      media_id: playlistBruno
      media_type: playlist
      enqueue: replace
    target:
      entity_id: media_player.sonos_move_2

### How to reproduce

when i call the service mass.play_media and i fill-in my playlist i get the error

### Music Providers

NAS Synology

### Player Providers

Sonos move

### Full log output

[log.log](https://github.com/user-attachments/files/15890513/log.log)

### What version of Home Assistant Core are your running

2024.6.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Update the integration

**Comment by brunobouillon** [comment]
I deleted version 2024.5.0. I downloaded the latest version, restarted HA but still version 2024.5.0 was active.
How can i proceed to activate 2024.6.2 ?

**Comment by OzGav** [comment]
Just install it via HACS. If it isn’t showing that is a HACS problem not MA

**Comment by brunobouillon** [comment]
OK. I just copied the new 2024.6.2 files in the mass folder and now the new version is active. Thanks for the effort !!
