### ISSUE TITLE
Track on multiple albums not appearing on all

### ISSUE THREAD

**Issue by MelHarbour** [music-assistant/hass-music-assistant#2506]
### What version of Music Assistant has the issue?

2.1.0b6

### What version of the Home Assistant Integration have you got installed?

2024.6.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I have two compilation albums. The same track is on both albums. They are loaded via the remote filesystem provider. The track only appears on one of the two albums.

### How to reproduce

Clean install with two albums featuring the same track. Observe track listing in the album details view for each. Notice missing track.

### Music Providers

Remote file provider

### Player Providers

N/A

### Full log output

[log.log](https://github.com/user-attachments/files/15891005/log.log)

### What version of Home Assistant Core are your running

2024.6.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by MelHarbour** [comment]
For reference, note missing track here:
![image](https://github.com/music-assistant/hass-music-assistant/assets/4092769/26182131-23c9-4c44-9edd-27e5a5d994f1)

And the tagging in Picard:
![image](https://github.com/music-assistant/hass-music-assistant/assets/4092769/4fffa0f8-f7fe-48f1-b183-22c871f34046)

**Comment by MelHarbour** [comment]
Looking at the info page for the track it only lists as appearing on one album:
![image](https://github.com/music-assistant/hass-music-assistant/assets/4092769/6578b514-adef-4f28-935f-5a7106c60be0)

I assume the intended behaviour is that it would show that it appears on two different albums. I assume therefore that the relevant album_track record is not being added during import.

**Comment by MelHarbour** [comment]
And the answer is the code explicitly causes it to overwrite for the local filesystem provider (and subclasses):

https://github.com/music-assistant/server/blob/642ccbef85bd5a190078563e8572a5aa0dbc0e89/music_assistant/server/controllers/media/tracks.py#L415

https://github.com/music-assistant/server/blob/642ccbef85bd5a190078563e8572a5aa0dbc0e89/music_assistant/server/providers/filesystem_local/base.py#L374

@marcelveldt Any thoughts on how to make the overwrite a little more careful in what it does?

**Comment by marcelveldt** [comment]
Ah this edge case.... 
Problem is when someone intentionally changed the ID3 tags. So they index their files with very bad ID3 tags and then fix them. I guess we just need to better handle that usecase and/or require some additional action.

I'll chew on it a bit - I have an idea.

**Comment by MelHarbour** [comment]
While sorting children's breakfast, a thought:

Perhaps overwrite should force overwrite of the data for a track, but should ignore the album_tracks table?

**Comment by MelHarbour** [comment]
It's probably a minor point as well, but the behaviour of linking the two tracks does mean that technically it will show the listing from one disc wrongly if, like in this case, the title differs between the two listings. I feel like that's a secondary problem though.
