### ISSUE TITLE
Inconsistent behavior between 0-player Airplay and Universal groups

### ISSUE THREAD

**Issue by madbrain76** [music-assistant/hass-music-assistant#2512]
### What version of Music Assistant has the issue?

2.0.7

### What version of the Home Assistant Integration have you got installed?

2024.6.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

It is possible to create both 0-player Airplay groups and 0-player Universal groups. One is unavailable for playback, while the other is

### How to reproduce

1. add the Airplay provider
2. in the settings / player list, select "Add a group player"
3. select "Airplay"
4. click save
5. a new group appears, called "syncgroup_xxxxx", with an hourglass to it, indicating it is not yet available
6. add the DLNA/UPNP provider
7. Add the Universal Group player
8. select "Add a group player"
9. choose "Universal group player"
10. click save
11. a new group appears, called "ugp_xxxxx". No hourglass appears, indicating it is enabled and available
12. go to the player list at the bottom and select it
13. go to albums
14. click an album
15. click the blue "play" button
16. the track seemingly starts playing. However, the sound has nowhere to go, since there are no players associated with the group
17. transport and volume controls still work, but only have a visual impact

### Music Providers

File system (remote)

### Player Providers

Airplay
DLNA/UPNP
Unviersal Group Player

### Full log output

[log.txt](https://github.com/user-attachments/files/15897798/log.txt)

### Additional information

The problematic behavior starts in step 11 of the test case.

The ability to create 0-member groups - or perhaps even 1-member groups - is also questionable, but probably should be a different discussion.

### What version of Home Assistant Core are your running

2024.6.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Windows

**Comment by OzGav** [comment]
Beta 30 has been released. Groups must now contain at least one player.

**Comment by madbrain76** [comment]
> Beta 30 has been released. Groups must now contain at least one player.

That's not quite true, though. While you can't create a 0-player group anymore, you can still remove all the players from an existing group and end up with a 0-player group. The behavior when trying to use those groups for playback is different than I reported, though. But removing all the players from the group probably shouldn't be allowed.

**Comment by OzGav** [comment]
We are aware of some instances where the validation isn’t occurring so this will be looked into eventually

**Comment by marcelveldt** [comment]
Removing all players when dynamic mode is enabled, is allowed.
