### ISSUE TITLE
Chromecast with Google TV (4K) devices are disabled by default

### ISSUE THREAD

**Issue by madbrain76** [music-assistant/hass-music-assistant#2516]
### What version of Music Assistant has the issue?

2.0.7

### What version of the Home Assistant Integration have you got installed?

2024.6.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When adding the Chromecast player provider, Chromecast with Google TV (4K) devices are found, but in disabled state

### How to reproduce

1. add Chromecast player provider
2. open settings/player
3. observe that the CCwGTV4K devices are disabled

![image](https://github.com/music-assistant/hass-music-assistant/assets/57333073/29c4d9a9-c477-45bc-b97b-e8aefbc090b7)

### Music Providers

N/A

### Player Providers

Chromecast

### Full log output

[log.txt](https://github.com/user-attachments/files/15908821/log.txt)

### What version of Home Assistant Core are your running

2024.6.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Windows

**Comment by marcelveldt** [comment]
Yes, that is by design as those are TV devices, we disable those by default

**Comment by madbrain76** [comment]
I see. I would suggest documenting it, then. I looked there before filing this issue.

**Comment by madbrain76** [comment]
BTW, the Chromecast Ultra (A/V casting stick) is enabled by default.

**Comment by marcelveldt** [comment]
> BTW, the Chromecast Ultra (A/V casting stick) is enabled by default.

I think we should add that to the default disabled items as well, as that is also purely targeted to video, right ?

**Comment by OzGav** [comment]
I am not sure what their target is but I use one with MA. You don’t need to interact with it for playback to work and it is always on unlike a TV

**Comment by madbrain76** [comment]
From my point of view, all the sticks prior to the Google TV present only one interface - the cast interface, which you can control only through apps over the network.

The Google TV series are a superset of that - they offer an additional on-screen local interface, which you can control with a remote.

Somewhat orthogonal is the fact that some of the sticks are audio-only (Chromecast audio) and others audio-video (all Chromecast video, Ultra, Google TV). In most cases, with any of the video sticks, the TV (and AVR if there is one) will be turned on automatically when audio or video playback starts. If the goal is to prevent the TVs from being turned on by default, then all the video sticks should be treated equally.

There are a few cases when the TV will not be turned on with video sticks :
a) the TV is very old and doesn't support HDMI-CEC
b) an AVR is in use, without a display attached ;)
c) the TV is a projector, and intentionally doesn't support HDMI-CEC

Case c) applies to one of my setups, in the home theater

The stick would know if it's attached to an HDMI-CEC device (receiver, TV) even if they are turned off - or if HDMI-CEC is completely disabled. - which would apply to cases a), b) and c). But this is very likely not exposed through the cast API.

**Comment by OzGav** [comment]
This is expected behaviour. The docs have been updated.
