### ISSUE TITLE
V1.1.18: can't change queue settings

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#252]
In the latest version the queue settings can't be changed. Tested on PC and iPhone.
It looks like the drop down lists don't open. Only the open close arrow (in the green circle) changes:
![image](https://user-images.githubusercontent.com/4363599/170768370-6235fd45-2519-4ee4-8897-fda1b1cfa656.jpeg)

**Comment by marcelveldt** [comment]
Yeah, it seems there was an update in one of the frontend components causing all the comboboxes to fail.

**Comment by erkr** [comment]
Nice these dependencies ;-)

**Comment by erkr** [comment]
Fixed with downgrade Vuetify in v1.1.19
