### ISSUE TITLE
Swedish is missing

### ISSUE THREAD

**Issue by DewGew** [music-assistant/hass-music-assistant#2529]
### New language

swedish

### Additional remarks

I cant choose swedish in settings. Swedish is 100% translated in Lokalise. When will it be added into frontend?
![swedish](https://github.com/music-assistant/hass-music-assistant/assets/28799807/15ada970-b5ec-46a1-9cc0-dfb82b0aaf06)

**Comment by OzGav** [comment]
Check the latest beta
