### ISSUE TITLE
mass.play_announcement plays the file but return an error and stop any HomeAssistant scripts sequence

### ISSUE THREAD

**Issue by I-G-1-1** [music-assistant/hass-music-assistant#2535]
### What version of Music Assistant has the issue?

2.1.0b8

### What version of the Home Assistant Integration have you got installed?

2024.6.4

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

when using MusicAssistant service "mass.play_announcement" the file is correctly played by the media_player entity, but HomeAssistant give error and if the service call is inside a script it stop the script sequence.

![01](https://github.com/music-assistant/hass-music-assistant/assets/96726059/d044607d-0eff-4c0b-b95d-667fd3832d41)

same problem with the service "tts.google_say" and a MusicAssistant player as media_player entity

### How to reproduce

as said below

### Music Providers

www folder on HomeAssistant installation

### Player Providers

Chromecast

### Full log output

mass.play_announcement error:
```
2024-06-24 15:28:11.099 INFO (MainThread) [music_assistant.players] Playback announcement to player Camera (with pre-announce: True): http://192.168.xxx.xxx:8123/local/01.mp3
2024-06-24 15:28:14.379 ERROR (MainThread) [music_assistant.webserver] Error handling message: players/cmd/play_announcement: file not found: http:/192.168.xxx.xxx:8123/local/01.mp3
```

tts.google_say error:
```
2024-06-24 16:43:45.794 INFO (MainThread) [music_assistant.players] Playback announcement to player Camera (with pre-announce: True): http://192.168.xxx.xxx:8123/api/tts_proxy/1e4e888ac66f8dd41e00c5a7ac36a32a9950d271_en_-_google_translate.mp3
2024-06-24 16:43:46.920 ERROR (MainThread) [music_assistant.webserver] Error handling message: players/cmd/play_announcement: file not found: http:/192.168.xxx.xxx:8123/api/tts_proxy/1e4e888ac66f8dd41e00c5a7ac36a32a9950d271_en_-_google_translate.mp3
```

### Additional information

HomeAssistant error:
```
ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Error for call_service at pos 1: MusicAssistantError: file not found: http:/192.168.xxx.xxx:8123/local/01.mp3
```

### What version of Home Assistant Core are your running

2024.6.4

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Raspberry Pi

**Comment by I-G-1-1** [comment]
for now solved adding in the HomeAssistant scripts:
```
continue_on_error: true
```
for "mass.play_announcement" and "tts.google_say" services

**Comment by OzGav** [comment]
The error seems clear as it indicates the file is not found but you say it actually plays correctly? Please show the whole script. If you look closely at the error you will see a missing / in the url. It shows http:/ not http://

**Comment by I-G-1-1** [comment]
It's not important the whole script as HomeAssistant and MusicAssistant give the error simply using the "developer tools/services" in HomeAssistant (the screenshot i took is from the developer tools).
As consequence of the error any script terminate and doesn't go further.
As workaround using "continue_on_error: true" let HomeAssistant ignore the error and continue to run the script.

```
The error seems clear as it indicates the file is not found but you say it actually plays correctly?
```
Yes the file plays correctly on the media_player. So it seems like MusicAssistant do its job correctly but incorrectly returns an error pretending the file just played doesn't exist.

```
If you look closely at the error you will see a missing / in the url. It shows http:/ not http://
```
I saw that. However you can see the url i set in the developer tools has correctly "http://", only the line that reports the error in the web-ui has "http:/". 
As mentioned before the file plays well on the media_player so I'm more inclined to believe that the "http:/" is a rendering error of the web-ui.

**Comment by OzGav** [comment]
I'm not sure whether the missing / is just a display issue. Someone else reported a similar problem adding a radio URL. Its being looked at.

**Comment by mathfreakmichael** [comment]
I'm having the exact same issue, down to the missing forward slash on http for the error. The only addition I have is that one of my squeezelites won't even play the file. Two of my three using lms lite, play even though it errors. The two that play are esp32 based and an amd manjaro 64 bit. The one not playing the file is a rpi 4b. In addition, chromecast devices using the mass media player also give the error but still play the file for announcements as well.

Just hoped to share in case it bears any fruit.

**Comment by DarkFox** [comment]
I can add that it fails to play on Sonos as well. I'm guessing Chromecast fixes the URL internally, but other platforms don't.

**Comment by N0XIRE** [comment]
I'm having the exact same issue using a Chromecast player provider. The announcement plays successfully but the logs state file not found, this seems to also prevent playing music from resuming.

**Comment by DarkFox** [comment]
The last working version is 2.1.0b7. I'd recommend reverting to that, if house approval is a factor.

**Comment by I-G-1-1** [comment]
Updated to MusicAssistant 2.1.0b9 the issue is still present.

**Comment by I-G-1-1** [comment]
> You don’t need to advise that it still isn’t working unless you are advised that it should be working .

I don't know if I'am allowed to say that (as no one advised me that it should be working nor there was any mention in the changelog), however I updated MusicAssistant to 2.1.0b13 and somehow the issue seems solved: at the moment HomeAssistant doesn't give any error on mass.play_announcement service call.

I have to mention that before MusicAssistant update I also updated to HomeAssistant 2024.7.1, so I don't know what update solved the issue.

Maybe they changed something as I saw that hass-music-assistant use `homeassistant.helpers.config_validation` to validate the url (but I'm not a programmer, so I don't know):

media_player.py
```
...
import homeassistant.helpers.config_validation as cv
...
        SERVICE_PLAY_ANNOUNCEMEMT,
        {
            vol.Required(ATTR_URL): cv.string,
            vol.Optional(ATTR_USE_PRE_ANNOUNCE): vol.Coerce(bool),
            vol.Optional(ATTR_ANNOUNCE_VOLUME): vol.Coerce(int),
        },
...
```

**Comment by OzGav** [comment]
Great news. Let us know if you have any problems in the future.
