### ISSUE TITLE
Search Service Call does not return Plex Playlists

### ISSUE THREAD

**Issue by miniminne** [music-assistant/hass-music-assistant#2541]
### What version of Music Assistant has the issue?

2.0.7

### What version of the Home Assistant Integration have you got installed?

2024.6.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

In Music Assistant 2.0.7, I can't use the mass.search service call to return Playlists from Plex.

This service call does return album, artist, and songs from Plex but never a playlist. When I (briefly) used YouTube Music in my troubleshooting, it did end up returning playlist search results.

Additionally, albums created in Music Assistant did not show up in mass.search calls, but if I had a local .m3u playlist this did show up in search results. 

### How to reproduce

1. Run a mass.search service call for a playlist in Plex that exists
2. Run a mass.search service call for a playlist created/existing in Music Assistant

### Music Providers

Plex
Music Assistant
Local Files
YouTube Music

### Player Providers

Sonos

### Full log output

[mass.log](https://github.com/user-attachments/files/15980890/mass.log)

### What version of Home Assistant Core are your running

2024.6.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Keeping this one open

**Comment by aLTeReGo-SWI** [comment]
I am seeing the very same thing running HA 2024.7.4 on an Intel NUC running Music Assistant  2.1.0 with Plex server 1.40.4.8679-7000

**Comment by OzGav** [comment]
Are the playlists visible in the MA playlist view?

**Comment by OzGav** [comment]
If this is fixed then please close
