### ISSUE TITLE
Requesting to play music by voice when using LLM as the Home Assistant Agent does not use the Voice Satellite Area in the context

### ISSUE THREAD

**Issue by nikito** [music-assistant/hass-music-assistant#2544]
### What version of Music Assistant has the issue?

2.1.0b8

### What version of the Home Assistant Integration have you got installed?

2024.6.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When requesting to play music by voice using a Home Assistant Voice Satellite, we get a response back asking to specify the area to play music in, despite the voice satellite being assigned to the area which would be passed as context to the LLM. When asking to play music, the LLM should assume the user wants to play music in the area of the requesting voice satellite if no explicit area is specified.
Note however, even when specifying area, I am then asked to specify a device despite the area only having one device assigned for music. When specifying a device, it still fails and asks me to clarify further.

### How to reproduce

Have a voice satellite set up and assigned to a location. In that location, have a single Music Assistant Music Player assigned. request to play a song.

### Music Providers

Spotify

### Player Providers

Chromecast

### Full log output

[d5369777_music_assistant_beta_2024-06-27T12-02-57.831Z.log](https://github.com/user-attachments/files/16013544/d5369777_music_assistant_beta_2024-06-27T12-02-57.831Z.log)

### What version of Home Assistant Core are your running

2024.6.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Sorry this is not a MA issue. You need to ask HA.
