### ISSUE TITLE
Can not enter custom name/image for custom radio URL

### ISSUE THREAD

**Issue by ministryofsillywalks** [music-assistant/hass-music-assistant#2548]
### What version of Music Assistant has the issue?

2.1.0b8

### What version of the Home Assistant Integration have you got installed?

2024.6.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I added a radio station via an URL and gave it a name.
Now I wanted to rename the station but there is no option for that.
So I removed the station from the library and tried re-adding it.
The dialog to rename the station shows up when adding but it then just goes back to the old name.
So that seems to be cached somewhere.
I tried restarting after removing and before re-adding.

### How to reproduce

Add radio via URL 
Give station a custom name 
Remove Station 
Add same URL
Enter new name 
Ui shows old name

### Music Providers

URL Radio 

### Player Providers

-

### What version of Home Assistant Core are your running

2024.6.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Keeping this one open

**Comment by chatziko** [comment]
Just to add that I have added radios with custom names in the past (a couple of months ago maybe?), so this seems like a recently introduced bug.

**Comment by BC48329** [comment]
Having the same issue

Home Assistant
Core 2024.7.3
Supervisor 2024.06.2
Operating System 12.4

Music Assistant
2.1.0


Adding radio stations no longer accepts custom name or image link


Beyond the bug there is no way to edit after added

**Comment by d0m1n1qu3** [comment]
confirm this:
> Adding radio stations no longer accepts custom name or image link

same problem is here

Music Assistant
2.1.0

**Comment by OzGav** [comment]
Please check if this has been fixed in 2.2.0rc1

**Comment by DarkFox** [comment]
I've just checked, and it works for me now. 👍
