### ISSUE TITLE
Radio Browser : countries with empty list 

### ISSUE THREAD

**Issue by dutchmendesign** [music-assistant/hass-music-assistant#2553]
### What version of Music Assistant has the issue?

2.0.7

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Error when browsing the radiobrowser. It seems some countries have an empty list.  For example UK and Netherlands.
Some are not, for example Belgium.

When browsing in "HA - Media - Radio Browser" UK and Netherlands do have a list.

### How to reproduce

https://music-assistant.io/music-providers/radio-browser/

### Music Providers

radio browser

### Player Providers

not applicable

### Additional information

ERROR (MainThread) [music_assistant] Error doing task: Task exception was never retrieved
RuntimeError: anext(): asynchronous generator is already running

### What version of Home Assistant Core are your running

2024.6.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Confirmed fixed

**Comment by bjtho08** [comment]
When I go to "browse by country" and select "Denmark" I get a single station, which appears to be from Guatemala, but it has the letters "DK" in its name. I am on 2.1.0rc1. Denmark should have a list of 73 stations.

**Comment by OzGav** [comment]
Please dont post in closed threads as we may not see them. I see 238 stations. Update to rc2 and if that doesn't fix it try MA SETTINGS>>CORE>>CACHE CONTROLLER>>CLEAR CACHE

**Comment by bjtho08** [comment]
> @bjtho08 Please dont post in closed threads as we may not see them. I see 238 stations. Update to rc2 and if that doesn't fix it try MA SETTINGS>>CORE>>CACHE CONTROLLER>>CLEAR CACHE

Sorry about that! Your suggestion about clearing the cache worked like a charm. Thanks a lot!
