### ISSUE TITLE
HA add-on: False ??

### ISSUE THREAD

**Issue by jonwaland** [music-assistant/hass-music-assistant#2565]
### What version of Music Assistant has the issue?

2.0.7

### What version of the Home Assistant Integration have you got installed?

2024.6.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

In the log file I get the following:

`2024-07-03 13:45:24.989 INFO (MainThread) [music_assistant] Starting Music Assistant Server (xxxxxx) version 2.0.7 - HA add-on: False - Safe mode: False`

HA add-on: False - but I have the HA integration running; speaker devices show, and the mass.search service call (example shown in docs of Queen) works.

SO what am I missing?

### How to reproduce

na

### Music Providers

na

### Player Providers

na

### Full log output

[log.txt](https://github.com/user-attachments/files/16076856/log.txt)

### What version of Home Assistant Core are your running

2024.6.4

### What type of installation are you running?

Home Assistant Core

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by marcelveldt** [comment]
You are not running the HA add-on for Music Assistant, that is all that means.
