### ISSUE TITLE
Sort Episode Numbers in a smarter way

### ISSUE THREAD

**Issue by Bockiii** [music-assistant/hass-music-assistant#2566]
### What version of Music Assistant has the issue?

2.0.7

### What version of the Home Assistant Integration have you got installed?

n/a

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Sorting on Albums that include an Episode Number uses the old-school sorting of "digit by digit" instead of evaluating the whole number.

Example:
![image](https://github.com/music-assistant/hass-music-assistant/assets/16492843/48cdc520-a914-4ec8-9b6e-76f8530a4d29)

Instead of sorting episode 11 after 10, MA sorts 100 after 10. In this specific case, there are leading zeros, otherwise it would be Episode 1, Episode 10, Episode 100, Episode 101 etc.

### How to reproduce

Have multiple albums by an Artist that represent Episodes (for example Audiobook series like Paw Patrol, Lego Ninjago etc. It will not be possible to reach an actual "sort by episode" state.

### Music Providers

This is happening with the "Filesystem local disk" provider, I do not have any other sources to test.

### Player Providers

n/a

### Full log output

n/a

### Additional information

Solving this should either be done by improving the Name sort or maybe add a new sort option "Sort by Episode" or something alike, that would look at numbers within the query result set and sort them in relation to each other.

### What version of Home Assistant Core are your running

n/a

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

**Comment by MelHarbour** [comment]
Already fixed by https://github.com/music-assistant/frontend/commit/e4b8a9b0a7b56ce4fba0f17fa3adb1933fcf41d0 in the beta.

**Comment by Bockiii** [comment]
Awesome, code looks like it does what it looks like it does, so I'll close the issue again :) Thx mel
