### ISSUE TITLE
Error message "Could not bind to x.x.x.x:1400: [Errno 98] Address already in use"

### ISSUE THREAD

**Issue by DeepCoreSystem** [music-assistant/hass-music-assistant#2567]
### What version of Music Assistant has the issue?

2.0.7

### What version of the Home Assistant Integration have you got installed?

2024.6.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

For 2 months Music Assistant worked flawlessly with Sonos speakers.
Since yesterday, 2024-07-04, I can't play music on Sonos speakers. In the logs I find a lot of refernces to port 1400 on Home Assistant being "in use"

### How to reproduce

I am unable to provide steps to reproduce the issue, because I am not aware of any update I did since 2024-06-30. 
MA did play on Sonos upto Wendsday evening, 2024-07-03. 
As of evening 2024-07-04 it doesn't work

### Music Providers

Local, Spotify, Radio Browser are okay

### Player Providers

Sonos not okay
SqueezeBox Player is okay

### Full log output

[log.txt](https://github.com/user-attachments/files/16107869/log.txt)

### Additional information

Core 2024.6.4
Supervisor 2024.06.2
Operating System 12.4
Frontend 20240610.1

### What version of Home Assistant Core are your running

2024.6.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Something else on the host is using port 1400

**Comment by OzGav** [comment]
Something else on the host is using port 1400

**Comment by marcelveldt** [comment]
Most likely you have HA running on the same host with the Sonos integration ?
That is not possible unfortunately.

**Comment by OzGav** [comment]
@DeepCoreSystem Unless you can supply additional info which points to a problem with MA we will close this soon

**Comment by hytrek** [comment]
I am having the same issue... I am new to HA... @marcelveldt  What do you mean when saying "Most likely you have HA running on the same host with the Sonos integration ?"

Thanks
LEM

**Comment by OzGav** [comment]
@hytrek HA can have integrations. Have you installed the HA Sonos Intergation?

**Comment by hytrek** [comment]
Yes, I have as I mentioned... :-)

**Comment by OzGav** [comment]
https://music-assistant.io/player-support/sonos/
