### ISSUE TITLE
Filesystem (remote share)  not mounting folder.

### ISSUE THREAD

**Issue by tomf247** [music-assistant/hass-music-assistant#2568]
### What version of Music Assistant has the issue?

2.1.0b10

### What version of the Home Assistant Integration have you got installed?

2024.6.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Filesystem (remote share) in in Music Provider  section no longer mounting share.  An exclamation mark now appears.

### How to reproduce

Add  a remote SMB share.

### Music Providers

Filesystem (remote share)

### Player Providers

N/A

### Additional information

Reverting to version 2.1.0b8 clears the issue.

### What version of Home Assistant Core are your running

2024.7.0

### What type of installation are you running?

Home Assistant Core

### On what type of hardware are you running?

Linux

**Comment by g4sbq** [comment]
I also have this problem at 2.10b10. Log shows permission denied...

2024-07-05 16:42:53.729 INFO (MainThread) [music_assistant.providers.filesystem_smb] Mounting //192.168.14.234/music/Top 40 Singles/2009/Top 40 Singles 2009-07-05 (New Entries) to /tmp/filesystem_smb--N9YA2muk
2024-07-05 16:42:53.842 ERROR (MainThread) [music_assistant] Error loading provider(instance) Filesystem (remote share): Connection failed for the given details: SMB mount failed with error: mount error(13): Permission denied
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs) and kernel log messages (dmesg)

**Comment by marcelveldt** [comment]
Known issue - fixed today - resolved in beta 11

**Comment by g4sbq** [comment]
Confirmed working again in 2.1.0b13
