### ISSUE TITLE
Home Assistant Provider is missing along with all others providers and cannot add it back

### ISSUE THREAD

**Issue by avbfr** [music-assistant/hass-music-assistant#2570]
### What version of Music Assistant has the issue?

2.0.7

### What version of the Home Assistant Integration have you got installed?

2024.6.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

After having tried to reconfigure a speaker, all of my providers disappeared including HA Provider. I cannot add it back, I get the error 'domain'

![image](https://github.com/music-assistant/hass-music-assistant/assets/18286176/221ac5a9-5ca9-4c02-a37d-ecf7534ff0db)

### How to reproduce

I don't know

### Music Providers

Spotify x2
Radio Provider

### Player Providers

HA Speakers Provider

### What version of Home Assistant Core are your running

2027.7.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by avbfr** [comment]
[log.txt](https://github.com/user-attachments/files/16112589/log.txt)
Log file

Thanks for your help.

**Comment by avbfr** [comment]
After another search, it may be a duplicate of #2555 . Do you confirm ? 

As I'm on a stable, any chance to get the fix without having to switch to beta ? ;-)

**Comment by OzGav** [comment]
You will have to be patient. The workaround is to reinstall the server and then do no not remove a provider once it has been added.

**Comment by OzGav** [comment]
This has been fixed
