### ISSUE TITLE
Samsung Music Frame getting Error communicating with socket, resetting connection

### ISSUE THREAD

**Issue by Khengsoon** [music-assistant/hass-music-assistant#2577]
### What version of Music Assistant has the issue?

2.0.7

### What version of the Home Assistant Integration have you got installed?

2024.6.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

The music will stop after a few seconds of playing, this only happens on the Samsung Music Frame

### How to reproduce

Play any music from any source to the player will received the error and music stop playing

### Music Providers

Youtube, Spotify

### Player Providers

Samsung Music Frame

### Full log output

Logger: pychromecast.socket_client
Source: /usr/local/lib/python3.12/site-packages/pychromecast/socket_client.py:412
First occurred: 11:59:05 AM (2 occurrences)
Last logged: 8:32:39 PM

[Music Frame(192.168.1.28):8009] Failed to connect to service HostServiceInfo(host='192.168.1.28', port=8009), retrying in 5.0s
[Music Frame Study Room(192.168.1.21):8009] Failed to connect to service HostServiceInfo(host='192.168.1.21', port=8009), retrying in 5.0s

Logger: pychromecast.socket_client
Source: /usr/local/lib/python3.12/site-packages/pychromecast/socket_client.py:655
First occurred: 8:32:39 PM (1 occurrences)
Last logged: 8:32:39 PM

[Music Frame Study Room(192.168.1.21):8009] Error communicating with socket, resetting connection

### What version of Home Assistant Core are your running

2024.7.1

### What type of installation are you running?

Home Assistant Core

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
What players do you have that do work?

**Comment by Khengsoon** [comment]
B&O M3 is working without issue

**Comment by OzGav** [comment]
If it isn't a networking issue then might be a Samsung problem. They are known to have poorly implemented protocols. Please attach  (drag and drop) the FULL log. This will be looked at in due course

**Comment by Khengsoon** [comment]
Ok sure, I will do it after work. Thank you very much
