### ISSUE TITLE
Music Assistant Server Generates Error in the Log with TuneIn Provider

### ISSUE THREAD

**Issue by indomitableMan** [music-assistant/hass-music-assistant#2584]
### What version of Music Assistant has the issue?

2.0.7

### What version of the Home Assistant Integration have you got installed?

2024.6.4

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

TuneIn encourages users to log in using an email address, and there is no way (_at least from the iPhone app_) to use anything other than an email address to log in. When the TuneIn provider is loaded with Music Assistant and an email address is specified as the username, the following error is displayed in the log:

`2024-07-07 00:11:36.205 WARNING (MainThread) [music_assistant.providers.tunein] Email address detected instead of username, it is advised to use the tunein username instead of email.`

**This message is both misleading and incorrect since it is not possible to use an email address as a TuneIn username.**

### How to reproduce

1. Set up a brand new copy of Music Assistant running in a container.
2. Add the TuneIn provider using a username formatted as an email address (_such as `bugsbunny@warnerbros.com`_)
3. Review the console log of the container running Music Assistant; the misleading error message will appear as a warning.

### Music Providers

TuneIn

### Player Providers

Sonos

### Full log output

[music-assistant-log-TuneIn-issue.txt](https://github.com/user-attachments/files/16117704/music-assistant-log-TuneIn-issue.txt)

### Additional information

Running on a QNAP NAS running QTS v5.1.7.2770 using Container Station v3.0.7.891 (a Docker clone)

### What version of Home Assistant Core are your running

2024.6.4

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
This is normal. It is a warning not an error.
