### ISSUE TITLE
YouTube Music: Playback fails on some tracks with error that "disc_number" field is None

### ISSUE THREAD

**Issue by ImSorryButWho** [music-assistant/hass-music-assistant#2585]
### What version of Music Assistant has the issue?

2.1.0b13

### What version of the Home Assistant Integration have you got installed?

2024.6.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Trying to play back tracks from the album "Descendants (Original TV Movie Soundtrack) (https://music.youtube.com/playlist?list=OLAK5uy_lsRsYDAtiDJ19r_zN_gnBH0kn4mCB0aWQ) from YouTube Music fails with an error stating `Field "disc_number" of type int in Track has invalid value None`.  The same error appears trying to play a playlist which includes any of the tracks from this album.

This playlist worked correctly in 2.1.0b9.

### How to reproduce

Search for this album in Music Assistant from YouTube Music and attempt to play it.

### Music Providers

YouTube Music - displays problem

I don't have any other providers to try.

### Player Providers

Sonos and Chromecast both display the problem.

### Full log output

[musicassistant.log](https://github.com/user-attachments/files/16117747/musicassistant.log)

### What version of Home Assistant Core are your running

2024.7.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by melwinek** [comment]
Try clearing the cache in the controller in settings.

**Comment by MarvinSchenkel** [comment]
^ this. If that does not work, please confirm that it still happens after a fresh install (ie deleting the addon and reinstalling it). Just had a look at the code and there should be no cases of `None` for disc number.

**Comment by ImSorryButWho** [comment]
Thank you - clearing the cache does solve the problem.  Sorry for not trying that myself!

**Comment by OzGav** [comment]
That is in the troubleshooting steps that you said you did…..

**Comment by ImSorryButWho** [comment]
Mea culpa - you're absolutely right.  The issue template refers to, but doesn't link to the troubleshooting FAQ.  In looking for that I found the link to the Q&A section in the README, which links to the Github discussion, which on first glance is empty.  There is a link to a link at the top, but banner blindness struck and I (wrongly) assumed that it wasn't written yet.  I _did_ search the issues, and thought I had done my part.

I'm very sorry.  Could I suggest linking directly to the troubleshooting page in the issue template?

**Comment by OzGav** [comment]
There actually is a link but I have added another one

![image](https://github.com/music-assistant/hass-music-assistant/assets/19848947/b64b6b9b-6ca4-4d00-83ad-15969c85af14)
