### ISSUE TITLE
Spotify Playlists won't load songs

### ISSUE THREAD

**Issue by DastardlyDino** [music-assistant/hass-music-assistant#2599]
### What version of Music Assistant has the issue?

2.0.7

### What version of the Home Assistant Integration have you got installed?

2024.6.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I cannot get any of the songs inside my Spotify playlists to load

### How to reproduce

Connect to Spotify
Select a Playlist
Wait for it to load
It never loads

### Music Providers

Spotify

### Player Providers

Haven't gotten that far

### Full log output

[log.txt](https://github.com/user-attachments/files/16133241/log.txt)

### Additional information

Hopefully the logs are private by default.

### What version of Home Assistant Core are your running

2024.7.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Alternative

**Comment by OzGav** [comment]
What does work?

**Comment by OzGav** [comment]
Can you switch to the beta and try that

**Comment by OzGav** [comment]
We will close this soon due to no followup
