### ISSUE TITLE
Youtube Music not working

### ISSUE THREAD

**Issue by miroslavpetrov** [music-assistant/hass-music-assistant#2607]
### What version of Music Assistant has the issue?

2.0.7

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When I try to play a song from youtube music to any speaker I get this error: 

2024-07-10 22:59:44.101 ERROR (MainThread) [music_assistant.webserver] Error handling message: player_queues/play_media: get_throttling_function_name: could not find match for multiple

Its an old issue with pytube but it doesn't seem to be fixed

### How to reproduce

Just try to play any song from youtube music.

### Music Providers

Youtube music

### Player Providers

Airplay, UPNP

### What version of Home Assistant Core are your running

2024.5.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Alternative

**Comment by OzGav** [comment]
Can you try the beta?

**Comment by moswald14** [comment]
this just happened to me too after a reboot. switching to beta fixed it, it seems

**Comment by MarvinSchenkel** [comment]
We completely rewrote the logic to resolve streaming urls in beta to prevent instabilities like this from happening. Should hit stable in a week or so.

**Comment by MarvinSchenkel** [comment]
Added the 'workaround' fix. Can you restart the addon and see if it works?

**Comment by miroslavpetrov** [comment]
@OzGav I just installed the Beta version and Youtube Music is working fine.

**Comment by OzGav** [comment]
Thanks we will close this. When the 2.1 stable is released soon you can switch back if you wish
