### ISSUE TITLE
music_assistant.common.models.errors.LoginFailed: SMB mount failed with error: mount error(115): Operation now in progress Refer to the mount.cifs(8) manual page (e.g. man mount.cifs) and kernel log messages (dmesg)

### ISSUE THREAD

**Issue by jevans10** [music-assistant/hass-music-assistant#2611]
### What version of Music Assistant has the issue?

2.0.7

### What version of the Home Assistant Integration have you got installed?

2024.6.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

when I try to enter my server details i get this error:
Connection failed for the given details: SMB mount failed with error: mount error(115): Operation now in progress
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs) and kernel log messages (dmesg)

### How to reproduce

Attempt to mount remote share

### Music Providers

Remote Share

### Player Providers

n/a

### Full log output

[](url)

### Additional information

I can use the same credentials to connect on another device.
Home assistant is using tailscale and I've tried both the tailscale and local IP.
I have removed all special characters from the share.

### What version of Home Assistant Core are your running

2024.7.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Alternative

**Comment by MelHarbour** [comment]
Under the advanced settings, mount options, have you tried adding `vers=2.0` to the list of options?

**Comment by jevans10** [comment]
just did, i have 'noserverino,file_mode=0775,dir_mode=0775,uid=0,gid=0,vers=2.0 ' but it still is not working - maybe the syntax is wrong?

**Comment by MelHarbour** [comment]
Any chance you could try with the latest beta? There's a lot of stability fixes gone into it.

**Comment by jevans10** [comment]
just did and unfortunately the issue persists

**Comment by OzGav** [comment]
This is possibly not a MA issue. Have you googled the error?

**Comment by jevans10** [comment]
I have, it seems like a common server mount errors but none of them worked and some diorite replicate well with this issue

**Comment by OzGav** [comment]
Unfortunately we will have to close this soon unless you can provide additional info thtat suggests this is a MA problem as you are the only one reporting it...?

**Comment by ReinhardPrix** [comment]
adding `version=3.0` did it for me.

**Comment by danwador** [comment]
Hello , I adding  ,vers=2.0  
and it's ok  thank's
