### ISSUE TITLE
The hamburger and Actions are broken

### ISSUE THREAD

**Issue by WoAnerges** [music-assistant/hass-music-assistant#2616]
### What version of Music Assistant has the issue?

2.1.0b15

### What version of the Home Assistant Integration have you got installed?

2024.7.1.b0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Hello, there are two buttons broken, Actions and hamburger (menu)

### How to reproduce

Bug 1: The hamburger menu button is broken in the folder browser. When you click the button near a folder, nothing happens. It does not open any menu.

Bug 2: the multi selection tool is broken. When you select multiple folders and click the "Actions" button, nothing happens. It doesn't open the menu.

### Music Providers

local drive

### Player Providers

bluetooth speaker

### What version of Home Assistant Core are your running

2024.7.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by WoAnerges** [comment]
If I can help more with this problem, please let me know how. It there's any log, out anything like that I can share, just let me know what to do, and I'll collect that data for you

**Comment by OzGav** [comment]
No we are already aware of this. There is already two items on the backlog to revisit the browse view. Note that it is not envisaged that users would ordinarily use the browse view.

**Comment by WoAnerges** [comment]
> No we are already aware of this. There is already two items on the backlog to revisit the browse view. Note that it is not envisaged that users would ordinarily use the browse view.

That's great to know that you are already aware of this.

Thank you
