### ISSUE TITLE
YTM fails with "get_throttling_function_name: could not find match for multiple"

### ISSUE THREAD

**Issue by higbyk** [music-assistant/hass-music-assistant#2617]
### What version of Music Assistant has the issue?

2.0.7

### What version of the Home Assistant Integration have you got installed?

N/A (I use the add-on)

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I installed the add-on and configured the YouTube Music music provider, but am unable to use it. Whenever I tried to stream to a device, I get the following error: 
`get_throttling_function_name: could not find match for multiple`
I cleared the controller cache, removed and reconfigured the YTM music provider.

Looking up this error online indicates it's an issue with pytube, but I am surprised to see that nobody else is reporting this issue.

### How to reproduce

Install the add-on and try using the YouTube Music music provider with any player provider.

### Music Providers

YouTube Music

### Player Providers

Home Assistant media_player
DLNA

### Full log output

I am on mobile, I will do this later.

### Additional information

I have the ytubemusic HACS integration configured but doubt they use the same environment.

### What version of Home Assistant Core are your running

2024.7.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Please try with the beta or wait for the 2.1 release candidate which should come out very soon

**Comment by higbyk** [comment]
I can confirm it works in the beta! Thanks, I'll use the beta for now.
