### ISSUE TITLE
Apple Music - "400 - Bad Request"

### ISSUE THREAD

**Issue by ian27ukish** [music-assistant/hass-music-assistant#2618]
### What version of Music Assistant has the issue?

2.1.0rc1

### What version of the Home Assistant Integration have you got installed?

2024.7.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When trying to view any self-created playlist i recieve the error:
"400, message='Bad Request',url=URL('https://api/music.apple.com/v1/me/library/playlists/p.2P6WZOdIG542G/tracks?include=artists,catalog&limit=200&offset=0')

I've made that playlist public for testing purposes https://music.apple.com/library/playlist/p.2P6WZOdIG542G

Apple playlists are fine.

Viewing self created playlists prior to updating to rc1 was working for 90%....i was hoping from reading the issues this release would fix that additional 10% 😃 

Oh, and prior to rc1 the home tab in music assistant was empty for me (i've only been using this a few days) but now its populated.

Appreciate your efforts with this plugin.....i know it can seem like a thankless task but you've done a stellar job so far!

### How to reproduce

Click on playlists, click on any self-created playlist

### Music Providers

Apple Music

### Player Providers

Sonos (but im not playing anything just browsing apple above)

### Full log output

[music-assistant.log.log](https://github.com/user-attachments/files/16203444/music-assistant.log.log)

### What version of Home Assistant Core are your running

2024.7.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by MarvinSchenkel** [comment]
I can reproduce this as well, will dive into it!

**Comment by MarvinSchenkel** [comment]
Fixed in the next release.

**Comment by ian27ukish** [comment]
Thanks @MarvinSchenkel! 

You are a legend 🫡

**Comment by ian27ukish** [comment]
All working after the latest update 👍
