### ISSUE TITLE
Provider ytmusic did not load within 30 seconds after new beta update

### ISSUE THREAD

**Issue by moswald14** [music-assistant/hass-music-assistant#2619]
### What version of Music Assistant has the issue?

2.1.0rc1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

after updating the beta to the new one out today, it has broken [this fix ](https://github.com/music-assistant/hass-music-assistant/issues/2617)

I tried [uninstalling and waiting an hour before reauthenticating](https://github.com/music-assistant/hass-music-assistant/issues/1774) but it didn't work. I guess I will try again for longer.

### How to reproduce

have the issue with the youtube provider detailed in the issue above
fix with old beta
update to new beta 7/13/24
"Provider ytmusic did not load within 30 seconds"
try to delete and reconfigure, same thing
uninstall, wait an hour reinstall, same thing

### Music Providers

youtube

### Player Providers

Home Assistant Speaker? (I had the VLC-Telnet, but this is all irrelevant, issue happens without player provider added)

### Additional information

Pi4B Raspbian lite with Supervised HASS

### What version of Home Assistant Core are your running

2024.7.2

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Raspberry Pi

**Comment by cociweb** [comment]
I can confirm ...this provider is buggy with different errors since 2.1.0b14. last known working version was b13 (at least for me...)

**Comment by tastgr** [comment]
Same issue, running HAOS on a dedicated HA PC

**Comment by MarvinSchenkel** [comment]
Should be solved in https://github.com/music-assistant/server/pull/1497. Keep an eye out for the next rc release

**Comment by cociweb** [comment]
Fix is working. Thank you for your great work - as always!

**Comment by tastgr** [comment]
Confirmed, working for me again also. Cheers!
