### ISSUE TITLE
Plex playback does not trigger webhooks

### ISSUE THREAD

**Issue by arsaboo** [music-assistant/hass-music-assistant#2620]
### What version of Music Assistant has the issue?

2.1.0rc1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When playing music using Plex, I see the play history get updated. However, Music Assistant does not create any webhook that can be used to trigger other services. For example, I am using webhooks in Plex to scrobble to Navidrome:

![image](https://github.com/user-attachments/assets/3505d0c8-b5b6-4932-945a-1004418f938c)

This works perfectly when playing music directly from Plex but does not work when playing music using Music Assistant. Music Assistant does not trigger any events in plex. 

### How to reproduce

We can check the logs 

### Music Providers

Plex

### Player Providers

Sonos

### Full log output

NA

### What version of Home Assistant Core are your running

2024.7.2

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Alternative

**Comment by OzGav** [comment]
Issues are for things that should work but don’t. Why do you think this should work. Has it ever worked? If not this is a feature request.
