### ISSUE TITLE
[Soundcloud] Error in track detail page: Invalid type for item_id

### ISSUE THREAD

**Issue by voydz** [music-assistant/hass-music-assistant#2625]
### What version of Music Assistant has the issue?

2.1.0 rc2

### What version of the Home Assistant Integration have you got installed?

2024.6.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Whenever I navigate to the detail page of a Soundcloud track I get an error like this:

i.e. `Value 560363814 of type ‹class 'int'> is invalid for item_id, expected value of type ‹class str'>`

This happens when using the Music Assistant frontend.

### How to reproduce

1. Setup Soundcloud
2. Search for i.e. "song"
3. Find a track from the Soundcloud provider
4. Open the track details ("show information")

### Music Providers

With the Problem: Soundcloud
Without the Problem: Local disk, Apple Music

### Player Providers

This happens with every player provider I own. I do not think this is related to the issue.

SONOS, AirPlay and Chromecast

### Full log output

[music-assistant.log](https://github.com/user-attachments/files/16230493/music-assistant.log)

### What version of Home Assistant Core are your running

2024.7.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
@gieljnssns can you have a look at this

**Comment by OzGav** [comment]
@voydz plesse check if this is still an issue with beta 10 or later

**Comment by voydz** [comment]
Hi @OzGav seems to be resolved on my side. Big thank you! 👍
