### ISSUE TITLE
Error when trying to play Songs from Spotify

### ISSUE THREAD

**Issue by chicken305** [music-assistant/hass-music-assistant#2640]
### What version of Music Assistant has the issue?

2.0.7

### What version of the Home Assistant Integration have you got installed?

2024.6.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When i try to search a song and click play on it (from spotify) i get the following message.
![image](https://github.com/user-attachments/assets/b5b6c539-09eb-4665-a0bb-40df424786f8)
Also playing my liked songs wont work if i just click play, but when i click a singular song, it does work.

Also Sorting songs does not seem to work properly:
![image](https://github.com/user-attachments/assets/cb61ed31-eac6-4284-a8d6-459bf9c553f5)

### How to reproduce

Click play on the liked Songs Playlist from Spotify

### Music Providers

Spotify

### Player Providers

HA MediaPlayers

### Full log output

[log.txt](https://github.com/user-attachments/files/16265059/log.txt)

### What version of Home Assistant Core are your running

2024.7.0

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Can you see if this is still a problem with the last beta?

**Comment by japyjaap** [comment]
I'm having the same issue with 2.1.0 RC 2 installed

**Comment by chicken305** [comment]
it seems to be working better after clearing all the caches ( had one error before clearing the caches)

**Comment by OzGav** [comment]
Better or fixed?

**Comment by japyjaap** [comment]
Through the search I can find the same playlist and it plays correctly. I can't remove the greyed out playlist. When I try to add the playlist from the search to the library it doesn't show (probably because it's still in there).

**Comment by OzGav** [comment]
I would probably try removing Spotify and see if all those playlists are removed and the re-add

**Comment by chicken305** [comment]
it Is fixed. 

Just had a random occurence where a song restarted in the middle like 2-3 times

also when i have a Queue and select a song to "Play Now" it plays that song but shows the next song from the Queue in the player, and the Song i picked to play now gets sorted into the "played" Tab
And one snippet for example 22 seconds long played twice and restarted once and after that started playing the song i skipped by Playing now that snippet

**Comment by chicken305** [comment]
yea no something is broken. 
it does not finish songs even when i just pick one album to play. the next song starting to early then and bricking it after finishing. While using the song length of the previous song, if it plays at all automatically from the queue. 
![image](https://github.com/user-attachments/assets/0f261b48-61f3-47a5-b766-e317927844ce)

after prematurely starting the next song nothing else plays anymore on its own. If i press play again the first song plays again, but now overflowing the timer of the second song:
![image](https://github.com/user-attachments/assets/21767d4e-a2f6-4e83-856f-ad8e36717048)
if i press Next Song, then the third Song starts playing, but also does not finish

**Comment by OzGav** [comment]
Do you have other than a HA media player?

**Comment by chicken305** [comment]
what do you mean exactly?

**Comment by OzGav** [comment]
In your report you only indicate you have tried Ha media players. These aren’t the best as they rely on code outside of MA. Do you have other player types to try?

**Comment by chicken305** [comment]
as far as i could test it now before sleep it seems to be working when using airplay for example.
So it seems to be the ha media player

**Comment by OzGav** [comment]
Per the docs if there is a native player available you need to use that so continue using the native Airplay provider. As for the other issues they should be fixed in the latest beta. That will get promotoed to stable soon.
