### ISSUE TITLE
Apple Music error in RC3

### ISSUE THREAD

**Issue by Kebo2r** [music-assistant/hass-music-assistant#2649]
### What version of Music Assistant has the issue?

2.1.0 RC3

### What version of the Home Assistant Integration have you got installed?

2024.7.3

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Downloaded the beta yesterday. Now getting this error when trying to play Apple Music:

2024-07-20 07:28:53.597 ERROR (MainThread) [music_assistant.webserver] Error handling message: player_queues/play_pause: ClientSession._request() got an unexpected keyword argument 'encoded'

Worked fine in the previous couple of betas. Have deleted, reinstalled, reconfigured, etc. Local Media works.

Thanks!

### How to reproduce

Add Apple Music provider.  Attempt to play any media.  See error.

### Music Providers

Apple Music

### Player Providers

Fully Kiosk, SnapCast

### Full log output

[music-assistant.log](https://github.com/user-attachments/files/16321235/music-assistant.log)

### Additional information

Other providers work ok and Apple Music worked fine in RC2

### What version of Home Assistant Core are your running

2024.7.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by chasut** [comment]
Seeing this as well.  Apple Music over Airplay on AArch64 HA add-on.

**Comment by bushcraftytim** [comment]
Yes - seeing this in RC3 too.

**Comment by davidlarkins** [comment]
I am also seeing this error with playing anything from Apple Music.

**Comment by OzGav** [comment]
This will be fixed in then next update.

**Comment by davidlarkins** [comment]
Can confirm this is fixed in 2.2.0b0. 
Thanks!

**Comment by Kebo2r** [comment]
Confirmed! Fixed and working!  Thank you!Sent from my iPhoneOn Jul 22, 2024, at 12:38, davidlarkins ***@***.***> wrote:﻿
Can confirm this is fixed in 2.2.0b0.
Thanks!
