### ISSUE TITLE
'NoneType' object has no attribute 'unique_file_ids' error in logs; causes files to be excluded from library

### ISSUE THREAD

**Issue by dmcc** [music-assistant/hass-music-assistant#2656]
### What version of Music Assistant has the issue?

2.1.0

### What version of the Home Assistant Integration have you got installed?

2024.5.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

MP3 files that fail to load with `eyed3` cause this log error:

    ... [music_assistant.providers.filesystem_local] Error processing [filename].mp3 - 'NoneType' object has no attribute 'unique_file_ids'

I believe this comes from [this line](https://github.com/music-assistant/server/blob/ae44f7a9b9434db39fd22bc3291f4a6994af4082/music_assistant/server/helpers/tags.py#L450). As a result of this exception, thes file are not added to the library and not playable.

I've seen [Troubleshooting](https://music-assistant.io/music-providers/filesystem/#tagging-files) and agree that files should be tagged properly...at the same time, I have a large number of files that meet these conditions and would like to be able to play them before I can repair their tags. In the previous version of Music Assistant, these files were playable so a workaround would be great.

### How to reproduce

This is kind of tricky -- I'm not sure what about the files makes their tag unloadable by `eyed3`, but I do know that they hit [this exception](https://github.com/nicfit/eyeD3/blob/5108937485555c81ca992a4def7d74f860ee978d/eyed3/mp3/headers.py#L578) with the warning "Lame tag CRC check failed".

### Music Providers

N/A

### Player Providers

N/A

### What version of Home Assistant Core are your running

2024.6.2

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

**Comment by MelHarbour** [comment]
Yeah, it's one of those where it would be good if eyed3 didn't have a problem reading, but there could be any number of reasons why the library might return NoneType, so it's probably better with a guard clause in regardless.
