### ISSUE TITLE
IP banning

### ISSUE THREAD

**Issue by rodgers86** [music-assistant/hass-music-assistant#2658]
### What version of Music Assistant has the issue?

2.20b0

### What version of the Home Assistant Integration have you got installed?

2024.6.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I’m getting lots of failed logins from
My home assistants own internal IP address. 

Looks like it’s happening hourly and then after so many attempts it’s banning the IP. This is part of the HTTP config. 

However in the logs it seems to be to do with the /media folder which I only just started using with Music assistant. 

`Logger: homeassistant.components.http.ban
Source: components/http/ban.py:135
integration: HTTP (documentation, issues)
First occurred: 00:38:10 (5 occurrences)
Last logged: 06:38:10

Login attempt or request with invalid authentication from 192.168.6.27 (192.168.6.27). Requested URL: '/media/local/doorbell-2.mp3?authSig=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJiMGY2MzRiNjRlMDk0MmYyOGRkZTJmYTgyY2EzODU1NCIsInBhdGgiOiIvbWVkaWEvbG9jYWwvZG9vcmJlbGwtMi5tcDMiLCJwYXJhbXMiOltdLCJpYXQiOjE3MjA1MzA0NjksImV4cCI6MTcyMDYxNjg2OX0.4RxQTIFmyPFo2GbbtHXigLKWZndKwlULsb95eZ2HQeU'. (Lavf/60.3.100) `

### How to reproduce

Happens in the background. 

The mp3 file does work fine in MA when the internal IP is not blocked. But over the period of a few hours. The number of failed logins attempting to access this file is causing it to ban the IP. It then doesn’t work. 

I’m not actually attempting to play or access this file that often. Like last night it banned the IP overnight. 

I’m running on HAOS on Proxmox. 

External access is via cloudflare, but I don’t think that’s the issue here as MA is only accessed locally

### Music Providers

Filesystem (localdisk)

### Player Providers

Only player provider I use is Sonos. But issue appears to be not when I’m actually playing the file

### What version of Home Assistant Core are your running

2024.7.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Are you running MA as an addon or in docker?

**Comment by rodgers86** [comment]
Yes that’s the IP of the HA host.

It’s an automation that’s calling it. But it’s only triggered when a button
is pressed.

Whereas the IP banning was happening after a few hours even when the
automation hadn’t run for days.

Strangely the IP hasn’t been banned for the last few days though.

The automation does work when triggered and play the mp3 via Music
Assistant to my speakers.

**Comment by OzGav** [comment]
OK then let's leave this for now. If the problem goes away please close this, we can always reopen if it comes back.

**Comment by ljmellor** [comment]
I can confirm that I'm having the same issue. Running HAOS on a VM inside unraid, MASS is the addon version. I have an apache reverse proxy for SSL from the outside world. All reported failed urls are using the internal IP which is correct. I'm quite well versed in linux/networking so happy to test any suggestions that come my way

**Comment by OzGav** [comment]
Pleas eupdate to the latest integration via HACS and the latest server version and advise if this is still an issue

**Comment by OzGav** [comment]
This should be fixed in 2.2.0rc1 please confirm

**Comment by OzGav** [comment]
This will be closed soon assuming fixed

**Comment by rodgers86** [comment]
I’ve had no issues since I posted a few weeks back.

Assume it’s fixed for others also
