### ISSUE TITLE
Playlist tracks are not refreshing after new items added

### ISSUE THREAD

**Issue by alfedan** [music-assistant/hass-music-assistant#2669]
### What version of Music Assistant has the issue?

2.1.0

### What version of the Home Assistant Integration have you got installed?

2024.7.1.b0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

impossible to add tracks to a playlist with the home assistant version. Server log indicates the addition to the playlist is ok but the track is not present in the playlist.

### How to reproduce

all time after update music assistant

### Music Providers

local media and same witch Plex

### Player Providers

home assistant

### What version of Home Assistant Core are your running

2024.7.3

### What type of installation are you running?

Home Assistant Core

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Some times it takes a little time to appear. Have you rechecked? Have you pressed the refresh icon in the MA menu bar for the playlist view?

**Comment by OzGav** [comment]
I just tried this and it worked fine

**Comment by robin-hg** [comment]
I am also experiencing this issue.
I've tried adding an album and individual tracks from Jellyfin to a newly created playlist in MA.
I've also tried adding a track from Youtube Music.
Logs display 'Adding X to playlist Y' for each track but they are not present when viewing the playlist even after clicking refresh item.

Version 2.1.0 Home Assistant add-on
HA integration 2024.6.2

**Comment by OzGav** [comment]
Did you press the refresh icon in the menu bar at the top of the list?

**Comment by OzGav** [comment]
If it still hasn’t appeared after another refresh trying restarting MA and see what happens

**Comment by robin-hg** [comment]
Huh, that seemed to have fixed it. Thanks

**Comment by OzGav** [comment]
Thanks. This will get looked at further.

**Comment by OzGav** [comment]
@marcelveldt to summarise here. The issue is that after adding to a playlist the red dot is not appearing on the refresh icon to show a refresh is needed.

**Comment by OzGav** [comment]
This is fixed and indeed now doesn't require a refresh!
