### ISSUE TITLE
Scrubbing in Apple Music does not move songs position and sends to start of song

### ISSUE THREAD

**Issue by DJAMIRSAM** [music-assistant/hass-music-assistant#2670]
### What version of Music Assistant has the issue?

2.1.0

### What version of the Home Assistant Integration have you got installed?

2024.6.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When I scrub in a song (ex go from 1 minute in the song to 2 minutes) the song restarts from the start but MA shows the song as playing from where I left it,

### How to reproduce

Change current position song is playing at

### Music Providers

Apple Music, only provider tried

### Player Providers

Sonos, Snap Cast

### Full log output

[music-assistant.txt](https://github.com/user-attachments/files/16357112/music-assistant.txt)

### What version of Home Assistant Core are your running

2024.7.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
How are you trying to seek? I just tried via the MA UI and it worked fine

**Comment by DJAMIRSAM** [comment]
<img width="1242" alt="Screenshot 2024-07-23 at 9 59 17 PM" src="https://github.com/user-attachments/assets/df9c21f0-a5fa-4c19-b91a-03f6f4cbfebe">
Using this bar, I just drag it to where I want, I have also tried clicking on where I want, I also tried doing it through HA, same thing just goes to the start of the song

**Comment by OzGav** [comment]
Is this a snapcast provider? If so pause doesn't work. What happens with Sonos?

**Comment by DJAMIRSAM** [comment]
> Is this a snapcast provider? If so pause doesn't work. What happens with Sonos?

I am using the snap cast provider but I am pausing in the MA UI, I that also a problem zone? I cannot test Sonos right now but I believe it was the same there. I will test Sonos In the morning so I don't wake my family up 😆

**Comment by OzGav** [comment]
Yes pause is not currently supported https://music-assistant.io/player-support/snapcast/

**Comment by OzGav** [comment]
@SantiagoSotoC

**Comment by DJAMIRSAM** [comment]
Tested and this problem also persists when using home assistant media players

**Comment by SantiagoSotoC** [comment]
That is handled by the playback queue with the flow mode, I can't fix it from the provider, that's probably why the pause doesn't work, but it's something in the core

**Comment by DJAMIRSAM** [comment]
> That is handled by the playback queue with the flow mode, I can't fix it from the provider, that's probably why the pause doesn't work, but it's something in the core

The issue still persists on all other providers, Sonos, HA media players, Snapcast. I tested with and without flow mode on HA

**Comment by SantiagoSotoC** [comment]
In some providers the flow mode is internal, it is not shown to the user. I can speak for snapcast, I know little about how the core works and even less about other providers. 
In snapcast it is expected that you are a few seconds out of sync because of the buffer, but minutes is a lot.

I don't know which ones use the flow mode, but this could be the reason why the pause doesn't work in snapcast, maybe the problem is more than the flow mode then

**Comment by OzGav** [comment]
It is unusual as no one else is currently reporting this problem. This will get looked at more in due course.

**Comment by SantiagoSotoC** [comment]
@marcelveldt  this may be what we talked about the other day with the problems in the queue ?

**Comment by marcelveldt** [comment]
What music provider is this?

**Comment by OzGav** [comment]
@marcelveldt Apple Music i believe

**Comment by DJAMIRSAM** [comment]
> @marcelveldt Apple Music i believe

The provider is Apple Music, I have no other option to test with

**Comment by DJAMIRSAM** [comment]
Hey just wondering if there are any updates on this or more information you need from me?

**Comment by marcelveldt** [comment]
I get a feeling that seeking is not supported by the apple music provider, hence it explains why nobody else is reporting this.
Maybe test if seeking works with a local file for example.

**Comment by MarvinSchenkel** [comment]
Yep that's it, I can reproduce it here for Apple Music. Silly I never noticed this before. I am afraid the solution is gonna be a bit harder, but will see if I can come up with a solution here.

**Comment by MarvinSchenkel** [comment]
@DJAMIRSAcan you please verify if this is working for you on beta 20?

**Comment by DJAMIRSAM** [comment]
Can confirm it's working as expected now

**Comment by SandraCHC** [comment]
I also have this problem in the current beta. Can anyone confirm this?
I use Apple Music and Audiobookshelf
