### ISSUE TITLE
Google home speaker not appearing in groups

### ISSUE THREAD

**Issue by ptrnmgr** [music-assistant/hass-music-assistant#2673]
### What version of Music Assistant has the issue?

2.1.0

### What version of the Home Assistant Integration have you got installed?

2024.6.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When i create speaker group in google home app it shows up in MA. My google home speaker does appear as solo (and works) but not in groups containing it. I reinstalled MA and recreated different groups.

### How to reproduce

1.create speaker group containing google home

### Music Providers

na

### Player Providers

chromecast

### What version of Home Assistant Core are your running

2024.7.3

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Please ATTACH the full log

**Comment by ptrnmgr** [comment]
[log.txt](https://github.com/user-attachments/files/16366004/log.txt)
sorry, i hope i did it well now...

**Comment by OzGav** [comment]
Please also include your screenshots. The logs shows six players are discovered, how many are players and how many are groups?

**Comment by ptrnmgr** [comment]
all seven: group contains 'google home' (not showing up); 'marshalleke' and 'chromecast'
chromecast: single player
google home: single player
lenovo clock: single player
living group: group contains 'google home' (not showing up); 'marshalleke'
living room group (recently created for testing this issue) contains 'google home' (not showing up); 'marshalleke'
marshalleke: single player
![3a0814ab6ec3a9fbf93d9c1c61500b8bdf752973](https://github.com/user-attachments/assets/6ed20cfc-429a-40a3-98d1-4da1ba509abd)
![40586f11eca780c0dc81790150c551fcc4118be3](https://github.com/user-attachments/assets/fdd4dab9-2005-4ce8-b98f-f22e02c9b7d6)

**Comment by OzGav** [comment]
Please confirm that all speakers are in the same subnet/vlan and you have no firewalls in between

**Comment by ptrnmgr** [comment]
afaik all on same subnet, def no firewall in between
MA detects and is able to play music on all of them individually, even the 'in groups dissapearing one' (aka 'google home' speaker). reinstalling MA does not help, recreating groups also without succes. Anything else i can try?

**Comment by OzGav** [comment]
I might have asked this on Discord but to capture it here. When you play to the group does the missing player play?

**Comment by ptrnmgr** [comment]
i've not yet been active on the discord (so maybe i'm not the only one having this issue?)...
No sound (on google home) when trying to make it play in a group

**Comment by OzGav** [comment]
Sometimes I lose track of issues so don’t read anything into that. This will be looked at further in due course.

**Comment by ptrnmgr** [comment]
ok, thx for following up... i'll keep fiddling and report if anything changes

**Comment by ptrnmgr** [comment]
i tried all these steps:

deleted spotcast HA integration
deleted google home speaker and all groups in google home app
deleted  google home speaker and all groups in google cast HA integration
readded google home speaker and groups in google home app

i have same result: google home is absent from groups but is able to play individually (i can however add it trough the 'now playing' in google home app after the group is started in MA)

i attached log just in case
[log.txt](https://github.com/user-attachments/files/16399151/log.txt)

**Comment by ptrnmgr** [comment]
https://github.com/user-attachments/assets/83c2ebf9-f7ca-4916-b6ba-10b4750fbebb

it's not just the one speaker. i tried changing the speakers in the google home app speaker groups while looking live at the result in MA. I can't get my head around what's happening. Some speakers can't be grouped together for some reason?

**Comment by OzGav** [comment]
Yeah will have to wait for Marcel to have a look. I have a bunch of Google Minis and an original Google Home and they all group no problems

**Comment by senderbell** [comment]
I have a similar problem. I have a Chromecast speaker group consisting of 5 speakers, including 2 Google Mini speakers.
When I turn on the music, all speakers start playing except for the Google Mini speakers. Music Assistant does not see them in the group.
I have to open the Spotify app and there activate the speaker group. Then I need to close Spotify and go back to MA.
After this operation, everything works well for the rest of the day. The next morning, I have to repeat the operation again.
It looks like the speakers are going into a very deep sleep and MA is unable to wake them up.

**Comment by senderbell** [comment]
I found this:
[https://www.googlenestcommunity.com/t5/Speakers-and-Displays/Having-trouble-with-Speaker-groups-Read-this-first/m-p/633127/page/7](url)

It looks like a Google software issue that still hasn't been fully resolved yet.

**Comment by ptrnmgr** [comment]
yeah, i circumvented it by banning the google home to another room to be used as an solo player. Groups work as intended now

**Comment by OzGav** [comment]
Are we happy this is a Google problem and therefore this can be closed?

**Comment by ptrnmgr** [comment]
not happy ;-) but you can close it...thx
