### ISSUE TITLE
From 500 Random tracks (from library)  BUG

### ISSUE THREAD

**Issue by ray154856235** [music-assistant/hass-music-assistant#2680]
### What version of Music Assistant has the issue?

2.1.0

### What version of the Home Assistant Integration have you got installed?

2024.6.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

<img width="735" alt="PixPin_2024-07-26_22-34-04" src="https://github.com/user-attachments/assets/568286c0-0a35-4dc3-a9cc-d94a58a51754">

Music added through the Open Subsonic Media Server Library. In the 500 Random tracks (from library) playlist, the same artist's songs will be continuously added to the playlist at the same time. Of course, in reality, they belong to different file paths in the media library, but should not be added repeatedly

### How to reproduce

Different versions of the same music by the same artist can be played randomly in the media library using 500 Random tracks (from library)

### Music Providers

Navidrome   Open Subsonic Media Server Library

### Player Providers

Navidrome   Open Subsonic Media Server Library

### What version of Home Assistant Core are your running

2024.7.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Covered by this issue https://github.com/music-assistant/hass-music-assistant/issues/2286 please add anything additional to there.
