### ISSUE TITLE
Cannot clear the MA Specific Conversation Agent

### ISSUE THREAD

**Issue by tronikos** [music-assistant/hass-music-assistant#2686]
### What version of Music Assistant has the issue?

NA

### What version of the Home Assistant Integration have you got installed?

2024.6.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

If you setup a MA specific Conversation Agent per the [instructions](https://music-assistant.io/integration/voice/#ma-specific-conversation-agent) you cannot clear it. If you select a different agent and hit submit it works. But if you select None and hit submit there is no change. The issue is at this [line](https://github.com/music-assistant/hass-music-assistant/blob/79008cf6139581d9b9d6ecfd3648f8fc6cb14bcb/custom_components/mass/config_flow.py#L205) that provides as the default the current selected agent. If you select None it will use the default value.
I had to manually edit the `core.config_entries` file to clear it.

### How to reproduce

1. In the configure options of the integration select a MA specific Conversation Agent and hit submit
2. Go to configure options again, select None for the agent and hit submit. The agent won't clear.

### Music Providers

NA

### Player Providers

NA

### What version of Home Assistant Core are your running

2024.7.0

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Closing since you have PR'ed the fix.
