### ISSUE TITLE
[Feature Request] Send mp3 streams for ESPHome devices that are in a group

### ISSUE THREAD

**Issue by jesserockz** [music-assistant/hass-music-assistant#269]
#253 added support for ESPHome media players which only support `mp3` based streams. This works well, but if you put an ESPHome `media_player` into a group, then it is sent a `flac` stream which does not work.

**Comment by marcelveldt** [comment]
Ah, yes forgot about that one. group streams are hardcoded to flac. I'll adjust it derive it from the underlying clients.
