### ISSUE TITLE
http://ip:8095/#/home keep on redirect to http://ip:8095/#/settings/providers

### ISSUE THREAD

**Issue by Yumega** [music-assistant/hass-music-assistant#2693]
### What version of Music Assistant has the issue?

image: ghcr.io/music-assistant/server:latest

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I use it on iphone to control the music

http://ip:8095/#/home keep on redirect to http://ip:8095/#/settings/providers

### How to reproduce

everytime I open the link http://ip:8095/#/home, it always redirect to  http://ip:8095/#/settings/providers

### Music Providers

apple music

### Player Providers

airplayer

### What version of Home Assistant Core are your running

not installed 

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
Please search before opening an issue https://github.com/music-assistant/hass-music-assistant/issues/2491
