### ISSUE TITLE
Chromecast: wrong time when paused after seek

### ISSUE THREAD

**Issue by chatziko** [music-assistant/hass-music-assistant#2701]
### What version of Music Assistant has the issue?

2.1.0

### What version of the Home Assistant Integration have you got installed?

2024.6.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

In the chromecast player, if a track is started at time X, and is later paused at time Y, while paused the elapsed time is displayed as X+Y instead of just Y. 

### How to reproduce

Screencast: [Screencast from 29-07-2024 06:44:36 ΜΜ.webm](https://github.com/user-attachments/assets/532bd711-7186-499a-a562-32f681d93312)

- Seek a track at some position (1:11 in the screencast)
- Pause the track at some position (1:16 in the screencast)
- While paused, the time is shown as 2:27 (= 1:11 + 1:16)
- Unpausing shows the correct time 1:16 again
- If the track is paused again (1:24 in the screencast), the time again is shown as 2:35 (=1:24 + 1:11)

### Music Providers

Tried with spotify and local filesystem.

### Player Providers

Chromecast

### Full log output

[music-assistant.log](https://github.com/user-attachments/files/16415873/music-assistant.log)

### What version of Home Assistant Core are your running

2024.7.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Confirmed

**Comment by marcelveldt** [comment]
should be fixed with the 2.2.0 stable release (and 2.3 beta)

**Comment by OzGav** [comment]
Confirmed fixed. Closing.
