### ISSUE TITLE
Spotify [Premium account] Login failed for user [myusername]

### ISSUE THREAD

**Issue by tomoqv** [music-assistant/hass-music-assistant#2702]
### What version of Music Assistant has the issue?

2.1.0

### What version of the Home Assistant Integration have you got installed?

2024.6.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I am trying to login to my Spotify Premium account, but getting the error "Login for user [myusername] or [myemail]". I am using Volumio, which has a Spotify integration working, from HA and I can access the music from there.

I just installed Music Assistant for the first time and it works with my mp3 collection on a network server.

### How to reproduce

Go to Settings
Click on "Add Music Provider"
Select "Spotify"
Input Spotify credentials
Click "Save"

### Music Providers

Spotify

### Player Providers

Only one provider added, Volumio (from HA players)

### Full log output

[MA log file.txt](https://github.com/user-attachments/files/16415920/MA.log.file.txt)

### What version of Home Assistant Core are your running

2024.7.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by jojkopeter** [comment]
I have the same problem

**Comment by LioBoul** [comment]
The same

**Comment by erkr** [comment]
Thanks for reporting the issue. Marcel is looking into it.

**Comment by Someguitarist** [comment]
Just mentioning I'm having the same issue.  Thanks for looking into it.

**Comment by NylonDiamond** [comment]
same

**Comment by OzGav** [comment]
Thanks everyone. No need for anymore +1s. This is an upstream issue and we will have to wait and see.

**Comment by erkr** [comment]
That fully depends on the team that own the library librespot (used by us and many others). I see a lot of activity there, including new code to fix it

**Comment by Someguitarist** [comment]
Edit:  Actually, I just tried to re-add it and it looks like it's syncing!  Might be resolved, or if not yet, hopefully soon!

**Comment by OzGav** [comment]
Yes looks like it is working again. Full disclosure we have done nothing something upstream must have changed again. Will monitor for a bit longer and then close this.

FYI in 2.2.0b2 and later there is an option to add your own clientid which may speed access up to the API. This is OPTIONAL but you can get your own clientid by following the steps here https://developer.spotify.com/documentation/web-api/concepts/apps

**Comment by erkr** [comment]
Upstream I read the assumption  Spotify did a roll back.

**Comment by tomoqv** [comment]
I can confirm it works now.

**Comment by LioBoul** [comment]
Me too! 🙂
