### ISSUE TITLE
Flashing screen on Playlist with HASS embedded web

### ISSUE THREAD

**Issue by kcossabo** [music-assistant/hass-music-assistant#2704]
### What version of Music Assistant has the issue?

2.1.0

### What version of the Home Assistant Integration have you got installed?

2024.6.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Continues screen flashing when viewing playlist.
[Video of the failure](https://image.cossaboon.net/-EvV6XrnaQb)

Same play list viewed using a docker container on unRAID works (Same files storage for both)
[Video of working on unRAID docker of Music Assistant](https://image.cossaboon.net/-iqxF9NidvG)

### How to reproduce

Not sure introduces when moving from an early June 2024 release to 2.1.0

### Music Providers

SMB mount of files from NAS on both working and not working.

### Player Providers

N/A

### Full log output

[music-assistant (1).log](https://github.com/user-attachments/files/16418743/music-assistant.1.log)

### Additional information

Music is stored on a Synology NAS. 

For the [failing HASS embedded](https://image.cossaboon.net/-EvV6XrnaQb) version it is added as a Music Provider via SMB file mount in the MASS 'Music Provider' section. Though the Playlist can not be viewed all the albums and artist can be viewed.

For the [working Docker Container of Music Assistant on unRAID](https://image.cossaboon.net/-iqxF9NidvG) the SMB mount is made on unRAID and is presented to the container as a local file share. (/My_Music in the container is connected to /mnt/remote/10.10.10.3_music on the host, where the host mounts the SMB share to /mnt/remote/10.10.10.3_music)

### What version of Home Assistant Core are your running

2024.7.3

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Possibly the same as https://github.com/music-assistant/hass-music-assistant/issues/2674

**Comment by kcossabo** [comment]
The playlist on a Docker Install with same files does not have an issue. 

1700+ files, I could check them all, but the same release in Docker does not do this, and issue was there in the earlier release.

what would you like me to try?

**Comment by OzGav** [comment]
What does work?

**Comment by OzGav** [comment]
Checking in again. Can you provide more info about what does work? For example, does this affect all playlists? If it is only one can you look carefully at the failing playlist. Is there an item that is no longer available? Is there a track that is in some way unusual, e.g. weird characters in the name.

**Comment by kcossabo** [comment]
so, the screen BLINKS, and no playlist is loaded.

Not sure how to word that different.

the playlist is not working 
the playlist blinks the screen continuesly, (see video) and is not usable.

**Comment by OzGav** [comment]
Yes I understand but is this only ONE playlist or ALL playlists

**Comment by kcossabo** [comment]
Both of them, so all of the .m3u that are scene by the MASS.Sent from my iPadOn Aug 11, 2024, at 7:08 PM, OzGav ***@***.***> wrote:﻿
Yes I understand but is this only ONE playlist or ALL playlists

**Comment by OzGav** [comment]
So how were these playlists created? If they were made external to MA do they comply with the requirements here https://music-assistant.io/faq/how-to/#create-playlists-or-use-m3u-files

**Comment by kcossabo** [comment]
Thank You - they do.I will post the two that I have to show that they do. Created by- Music is recorded from vinyl albums- files are created as (mostly) 96khz, 24bit AAC files- These are added to the Apple Music via the file addition on the Mac- In Apple Music the top songs are added to Apple Play List- Apple Script is then utilized to create a M3U file, that has format explained in your link- m3u file is used by M33 Amp- m3u file is used by Moodle Raspberry Pi- m3u file is used by Roon - m3u file is loaded via postman into PLEX and used by plexAmpAlso the file WAS working with Music Assistant.Sent from my iPadOn Aug 11, 2024, at 8:38 PM, OzGav ***@***.***> wrote:﻿
So how were these playlists created? If they were made external to MA do they comply with the requirements here https://music-assistant.io/faq/how-to/#create-playlists-or-use-m3u-files

**Comment by kcossabo** [comment]
The play list does have the 

> #EXTINF:

As well. Following the format 

https://en.wikipedia.org/wiki/M3U￼


track information: runtime in seconds then optional display title of the following resource
#EXTINF:123,Artist Name – Track Title

File SAMPLE


```
#EXTM3U
Music/#EXTINF:202000,ABBA - S.O.S.
Music/ABBA/Greatest Hits/01 S.O.S..m4a
Music/#EXTINF:187560,ABBA - Ring Ring
Music/ABBA/Greatest Hits/03 Ring Ring.m4a
Music/#EXTINF:193900,ABBA - Another Town, Another Train
Music/ABBA/Greatest Hits/04 Another Town, Another Train.m4a
Music/#EXTINF:216590,ABBA - Mamma Mia
Music/ABBA/Greatest Hits/07 Mamma Mia.m4a
Music/#EXTINF:166000,ABBA - Waterloo
Music/ABBA/Greatest Hits/10 Waterloo.m4a
Music/#EXTINF:255000,ABBA - Fernando
Music/ABBA/Greatest Hits/14 Fernando.m4a
Music/#EXTINF:242000,ABBA - Knowing Me, Knowing You
Music/ABBA/Greatest Hits Vol. 2/02 Knowing Me, Knowing You.m4a
Music/#EXTINF:239000,ABBA - Take A Chance On Me
Music/ABBA/Greatest Hits Vol. 2/03 Take A Chance On Me.m4a
```

over 3,000 lines long

I am trying many variations trying to make this work on older releases to. Seems to be a file limit, as an example if I try to brows the files in the UI, I can only see through to the ‘B’ and never down through all of the alphabet to ‘Z’

Also, if I rebuild the docker container, quite offten the app does not pick up the playlist, and I need to navigate to find it, then open it in the UI, then it recognizes it as a playlist.

/Kevin

**Comment by kcossabo** [comment]
Also note that the 'blinking' screen is only on HASS with MASS, if MASS is in a Docker Container, other issues, but not a blinking screen.
  
​
  
​/k
  
​

**Comment by OzGav** [comment]
> if MASS is in a Docker Container, other issues, but not a blinking screen.

Yes that is unusual but there are some differences between the two. Will just have to wait until this eventually bubbles to the top of the to do list.

**Comment by marcelveldt** [comment]
This issue is actually an issue with HA Ingress where a socket limit is hit. So basically this will happen when trying to load a playlist with many items in it.

**Comment by OzGav** [comment]
@marcelveldt so should we add a note in the docs about this and close?

**Comment by marcelveldt** [comment]
> @marcelveldt so should we add a note in the docs about this and close?

Not yet, I like to have a look at HA supervisor to fix it

**Comment by bruvv** [comment]
I can confirm this! It works now :)
