### ISSUE TITLE
Incompatible Airsonic REST protocol version. Server must upgrade.

### ISSUE THREAD

**Issue by vazquezrodjoel** [music-assistant/hass-music-assistant#2721]
### What version of Music Assistant has the issue?

2.2.0b3

### What version of the Home Assistant Integration have you got installed?

2024.6.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When I try to setup Music Assistant, I get the error:

Incompatible Airsonic REST protocol version. Server must upgrade.

Any way I can fix this or is Airsonic not compatible?  I already tried the stable version (or what ever it is called) and currently installed the beta to try.  Also updated Airsonic-Advanced docker to latest.

Log line:

`2024-08-04 21:59:40.299 ERROR (MainThread) [music_assistant.webserver] Error handling message: config/providers/save: Incompatible Airsonic REST protocol version. Server must upgrade.`

### How to reproduce

Configuring Aisonic as a Subsonic provider.  Enter base url, port, and folder/path and I get the error.

### Music Providers

Subsonic

### Player Providers

Havent go to this point yet.

### What version of Home Assistant Core are your running

2024.7.4

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
It would seem Airsonic is the issue. Have you asked them?

**Comment by OzGav** [comment]
Looking here Airsonic isn’t maintained anymore. You need to move on to a supported implementation https://github.com/airsonic/airsonic

**Comment by OzGav** [comment]
Actually I see that you might be using Airsonic advanced but that has hundreds of open issues and was last updated four years ago

**Comment by vazquezrodjoel** [comment]
yeah thats the one I use, Advance and currently the edge.  I guess I should start looking for replacement, really like airsonic, but dont like that is java based, and this is like the 3rd functionallity that I found that does not fill my bill... Ok thanks.
