### ISSUE TITLE
Unable to load artists from Qobuz

### ISSUE THREAD

**Issue by milkplus27** [music-assistant/hass-music-assistant#2722]
### What version of Music Assistant has the issue?

2.2.0b3

### What version of the Home Assistant Integration have you got installed?

2024.6.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I cant seem to access artists on Qobuz. Gives me the following error (see image)

I think I've narrowed it down a bit. It seems like I'm unable to access an artist page from the MA home screen. But if I go into an Album and then go to the artists page from there it works.

![Screenshot_20240805-090557](https://github.com/user-attachments/assets/a7b79d55-56a9-4cde-b971-11d3fac44404)

### How to reproduce

Click on any artist from MA home screen.

### Music Providers

Qobuz

### Player Providers

Upnp

### What version of Home Assistant Core are your running

2024.7.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by madbrain76** [comment]
I'm also using Qobuz. I'm not seeing this problem now with MA 2.1, nor was I seeing it with the previous release either. Wish I could help.

**Comment by OzGav** [comment]
Please ATTACH the full log from MA SETTINGS to your intial post

**Comment by milkplus27** [comment]
> Please ATTACH the full log from MA SETTINGS to your intial post

Sorry, I'm getting a 401 Unauthorized when trying to download the log

**Comment by OzGav** [comment]
Try and reload the page?

**Comment by milkplus27** [comment]
You know what? I just tried removing my Qobuz account from MA and re-adding and I think that seems to have fixed it. I can now reach Artist pages from the MA home screen again.

Apologies for not trying this earlier...
