### ISSUE TITLE
Random Albums and Tracks showing up in wrong artist page

### ISSUE THREAD

**Issue by Ay1tsMe** [music-assistant/hass-music-assistant#2726]
### What version of Music Assistant has the issue?

2.1.0

### What version of the Home Assistant Integration have you got installed?

2024.7.1.b0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When I play all the tracks from a specific artist, it will also add random songs from my library into that queue. 

If I go to the artist page, it shows songs that are by another artist. These songs have no relation to the artist page but are there for some reason.

I believe the songs that are appearing are located on my remote file system.

Example 1: Artist page for Paul Hardcastle. Contains Kenny loggins and laura branigan incorrectly
![Screenshot_2024-08-05-22-31-27-33_c3a231c25ed346e59462e84656a70e50](https://github.com/user-attachments/assets/093a8ae5-f6f9-4f21-b9bd-e2159b3e29df)

Example 2: Artist page for Michael Jackson. Contains Fred again... Incorrectly
![Screenshot_2024-08-05-22-33-23-15_c3a231c25ed346e59462e84656a70e50](https://github.com/user-attachments/assets/346df101-7d43-4aba-a390-5c90dc3beb36)

### How to reproduce

Go to an artist page that contains a lot of songs. The artists that don't have much content didn't seem to have this issue.

### Music Providers

Spotify
File System

### Player Providers

Using Sonos but shouldn't matter???

### Full log output

[music-assistant.log](https://github.com/user-attachments/files/16499193/music-assistant.log)

### Additional information

I have tried synchronising both Spotify and the remote file system I am using. That didn't seem to fix anything.

### What version of Home Assistant Core are your running

2024.7.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
It’s because you haven’t tagged them properly. Look at your logs it is full of warnings. Not sure how you missed that requirement on the troubleshooting page and in the docs for the file system provider. Why was the troubleshooting page not helpful here as it is the first thing on the page?

**Comment by Ay1tsMe** [comment]
I understand that some of the songs are not tagged properly but that's not the issue here. The issue is that some albums that are tagged properly are appearing under other artist pages. The examples I provided, all those songs are tagged properly.

**Comment by OzGav** [comment]
Until all the errors are removed due to tagging problems it is not possible to say what the issue is.

**Comment by NightHawkATL** [comment]
I am having the same issue and all of my music shows up fine in Plex which is where the music is linked from. It was working fine until the last update or so.

**Comment by OzGav** [comment]
@NightHawkATL Please ATTACH the full log from MA settings

**Comment by NightHawkATL** [comment]
> @NightHawkATL Please ATTACH the full log from MA settings

[MA Logs.txt](https://github.com/user-attachments/files/16504124/MA.Logs.txt)

**Comment by OzGav** [comment]
> I am having the same issue and all of my music shows up fine in Plex which is where the music is linked from. It was working fine until the last update or so.

Nothing interesting in the logs for you. The trouble is MA builds its own database and needs certain tags to be set to work properly. It isn't actually relevant if it works somewhere else. What you need to do is look at the tags of the original tracks. See if the ALBUM ARTIST tag is set. If not, that is likely the problem. (Additionally while you are looking at the tags see if the special MusicBrainz tags are set. Setting those will significantly enhance the experience with MA)

**Comment by OzGav** [comment]
And for everyone reading along I am not saying there isn't a bug but I am saying it isn't possible to tell if the tracks aren't tagged properly. We maintain a variety of test instances and they all work fine but the underlying local tracks are all tagged comprehensively with Picard.

**Comment by NightHawkATL** [comment]
I downloaded Picard and I have it scanning my library now. Majority so far has Album Artist set and the random ones I have looked at do have MusicBrainz IDs and other MusicBrainz info is provided.

**Comment by Ay1tsMe** [comment]
I don't think it's something to do with the metadata on the album. Here is the Laura Branigan Albums tagging info that is appearing in Paul Hardcastle's discography:
[branigan.txt](https://github.com/user-attachments/files/16505002/branigan.txt)

Correct me if I'm wrong but i don't think it's tagged incorrectly even though it is appearing in the wrong artist page.

Like @NightHawkATL said earlier, this also appeared to be an issue after updating the latest server version.

**Comment by OzGav** [comment]
What folder structure are you using? Do you have SHARE>>ARTIST>>ALBUM

**Comment by Ay1tsMe** [comment]
> What folder structure are you using? Do you have SHARE>>ARTIST>>ALBUM

Yes, I believe I'm using the correct folder structure, current example is 
`iPod_songs/Laura Branigan/Branigan`

I'll try a clean install and see what happens.

**Comment by NightHawkATL** [comment]
Now that I have had Picard go through my entire library, it is being updated on Plex. Once that finishes, I will synchronize again in MA and see how things look.

**Comment by NightHawkATL** [comment]
After using Picard to make sure 95% of my music had Album Artist and having Plex rescan then syncing with MA, I still have issues with the wrong albums in artists.

![image](https://github.com/user-attachments/assets/68daf1fc-0dd3-4737-9a83-73204475fbbe)

**Comment by OzGav** [comment]
I would do a reinstall now to start fresh particularly if you noticed improvement.

**Comment by NightHawkATL** [comment]
> I would do a reinstall now to start fresh particularly if you noticed improvement.

Just reinstalled and it is scanning now. Looks good after a reinstall. Just gotta figure out what to do,with a bunch of Album Artists with multiple artists that fill up the list of "Artists".

**Comment by OzGav** [comment]
Can you provide an example of a track with multiple album artists? Usually it is something like “John Travolta & Olivia Newton-John” and you would then see entries against “John Travolta”, “Olivia Newton-John” and “John Travolta & Olivia Newton-John”. The latter would be an album and no tracks and the first two would have tracks but no album.

**Comment by NightHawkATL** [comment]
> Can you provide an example of a track with multiple album artists? Usually it is something like “John Travolta & Olivia Newton-John” and you would then see entries against “John Travolta”, “Olivia Newton-John” and “John Travolta & Olivia Newton-John”. The latter would be an album and no tracks and the first two would have tracks but no album.

![image](https://github.com/user-attachments/assets/4cf00696-c9a5-4864-9b12-17419f9f2822)
![image](https://github.com/user-attachments/assets/e03a2436-f7b9-4b4c-863a-f4713b368db7)
![image](https://github.com/user-attachments/assets/f3909900-5f3e-4515-87c2-9ca51193ff5e)
![image](https://github.com/user-attachments/assets/85e3f746-fe56-415b-a50e-be32f0bb2697)
![image](https://github.com/user-attachments/assets/6202f123-2e10-4edc-bf1f-e0e9a1f283c4)
![image](https://github.com/user-attachments/assets/26b54867-657e-436f-acfc-715830e0a456)
![image](https://github.com/user-attachments/assets/0bb65b91-36cc-4f34-8e6a-37286b575580)
![image](https://github.com/user-attachments/assets/ab95e39e-e40b-4eb5-bd83-4028546eb0da)
![image](https://github.com/user-attachments/assets/13a47f4b-2fc4-49f4-a981-8efbf354c3ae)
![image](https://github.com/user-attachments/assets/2aeb449c-e598-4881-aa39-30577872ec75)
![image](https://github.com/user-attachments/assets/502c93b2-0ed1-4b03-b8d4-e68144d7de83)

**Comment by OzGav** [comment]
Yeah that looks like MA is working correctly if they are all the album artists although surprising Picard has it tagged that way (If you want you can post the tag info so we can look at that further). You could edit the tags manually and, for example, grab all of the Armin van Buuren tracks and change the album artist to just "Armin van Buuren" but leave the track artists as is. That way you can use the album artist filter to remove all the extras but you could still search for "Lauren Evans" (for example).
Changing the album artists en masse might require a start from scratch again though

**Comment by OzGav** [comment]
Unless there is a different view I will close this as identified as a tagging problem?

**Comment by Ay1tsMe** [comment]
yeah uninstalling and reinstalling the server fixed it for me. Closing
