### ISSUE TITLE
Unable to load albums with multiple sources available (Apple Music / Jellyfin)

### ISSUE THREAD

**Issue by awjoyce** [music-assistant/hass-music-assistant#2728]
### What version of Music Assistant has the issue?

2.2.0b3

### What version of the Home Assistant Integration have you got installed?

2024.6.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When trying to load an album that is available through both Apple Music and locally through the Jellyfin provider the UI seems to stall and I'm unable to view or play any of the media.

### How to reproduce

Load an album that has entries in both Jellyfin and Apple music, the interface will stall. I haven't been able to figure out if there is anything specific to the conflict or if it is just whenever available from both of Apple Music and Jellyfin.

### Music Providers

Music Assistant
Apple Music
TuneIn
Jellyfin

### Player Providers

AirPlay

### Full log output

[music-assistant.log](https://github.com/user-attachments/files/16502923/music-assistant.log)

### What version of Home Assistant Core are your running

2024.7.4

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Alternative

**Comment by OzGav** [comment]
@MarvinSchenkel there are a stack of Apple Music errors in the log?

**Comment by MarvinSchenkel** [comment]
The logs point to an error that it cannot find the tracks of that album on Apple music. Can you enable debug logging for Apple Music and try it again? Also, please link the album so I can try to reproduce it here

**Comment by awjoyce** [comment]
Two albums I have found that are experiencing this issue is: Feist, The Reminder. Garth Brooks, No Fences.
Garth Brooks is not normally in Apple Music, but I loaded my own copy of the CD into my iTunes library many years ago and it has continued working. Could there be an issue with content that is "in" my iTunes account, but not available for general streaming? I would expect the Feist album to be part of the Apple library, but it is an other one where I very likely loaded a CD into my iTunes library prior to their full streaming service.

Debug log attached.
[music-assistant-debug.log](https://github.com/user-attachments/files/16563729/music-assistant-debug.log)

**Comment by OzGav** [comment]
Yes I would say there is a very good chance of that if it is a common factor.

**Comment by awjoyce** [comment]
When I look at "File Info" in iTunes tracks on Feist are tagged "cloud status: Matched" Feist/The Reminder is available in the iTunes Store, but is not part of Apple Music.
"File Info" on Garth Brooks shows "cloud status: Uploaded" and the No Fences album is not available in the iTunes Store or on Apple Music.
So I think the question becomes, how can I exclude trying to use Apple Music for tracks that are in my Apple iTunes Library, but are not available on the Apple Music service?

**Comment by MarvinSchenkel** [comment]
Good catch! I will need to figure out a way to *not* include any albums that don't exist in the catalog. To be continued! :)

**Comment by MarvinSchenkel** [comment]
@awjoyce Trying to find a reliable way to check if we can actually playback the album. Can you take a screenshot of the album overview of Feist/The Reminder? Normally, at the bottom, there's a URL under 'Provider details':

![image](https://github.com/user-attachments/assets/2d1db8d3-353c-403c-bdf5-5a4d51c279d3)

I might be able to use this to check whether an album is available for playback if this is missing in your situation.

**Comment by OzGav** [comment]
Please check if this is fixed in the next beta

**Comment by OzGav** [comment]
Beta 20 has been released

**Comment by OzGav** [comment]
This will be closed soon assuming fixed
