### ISSUE TITLE
Playlist (label)names don't work for youtube generated playlists

### ISSUE THREAD

**Issue by HA-TB303** [music-assistant/hass-music-assistant#2730]
### What version of Music Assistant has the issue?

2.1.1 

### What version of the Home Assistant Integration have you got installed?

2024.7.1.b0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Recently playlist names/labels where added which is fantastic, but sadly they do not seem to work for youtube generated playlists like the podcast "**episodes for later/Afleveringen voor later**" and "**Music I like/Muziek die ik leuk vind**"

### How to reproduce

Add multiple youyube music (family)accounts and playlists on each account.

### Music Providers

Youtube Music

### Player Providers

N/A

### Additional information

In this example there are 3 YouTube Music premium accounts (**Michel**, **Linda** and **Timboektoe**):

![CleanShot 2024-08-06 at 12 05 55](https://github.com/user-attachments/assets/f42faa54-dbec-428c-a795-5d3c118dc057)

### What version of Home Assistant Core are your running

2024.7.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by MarvinSchenkel** [comment]
Interesting. Because I assume the 'Phonk' playlist is also coming from YT Music, which has a label applied? Are you sure you configured a 'custom name' for the other YTM instances via the settings? The 'label' you are seeing is actually the custom name if I remember correctly.

**Comment by HA-TB303** [comment]
Yes, but the "Phonk" playlist is a custom playlist, the others (incorrectly labeled) are Youtube generated playlists which can not be removed.

Michel:
![CleanShot 2024-08-06 at 14 15 11](https://github.com/user-attachments/assets/d459668e-7acf-4ae3-934b-0fed5f44b5fb)

Timboektoe:
![CleanShot 2024-08-06 at 14 15 47](https://github.com/user-attachments/assets/4004e829-fbd0-47a8-bd15-c4dcd987b9fe)

**Comment by MarvinSchenkel** [comment]
Then can you tell me the difference between the playlist 'Phonk' and the playlist 'Dance' ? Because the playlist 'Dance' seems to get picked up correctly

**Comment by HA-TB303** [comment]
Hi,

Not sure waht you are saying. 
![CleanShot 2024-08-06 at 14 43 06](https://github.com/user-attachments/assets/c179c016-be04-454a-8da0-eb3f9188e4aa)
This should have said 'Linda' as the Youtube account name is Linda, but then again this is a custom Playlist.

Anyhow, it's not working as intended :)

![CleanShot 2024-08-06 at 14 57 06](https://github.com/user-attachments/assets/67b4dcb6-72d9-440f-9807-a69ff3b74c4c)

Maybe this could be very easily resolved by getting the playlist "label-name"  from here, which is what I suggested first when requesting this feature. In that way you have control over the label and it's no longer your youtube channel name that provides the label-name which is kind of annoying.
![CleanShot 2024-08-06 at 14 58 18](https://github.com/user-attachments/assets/f9075260-4030-4be5-9d18-dcc44d123335)

**Comment by HA-TB303** [comment]
I was able to "resolve" the particular issue with the "Dance" playlist myself, by going into my wife's account, edit her Dance playlist, I then had to activate the YouTube channel and then the 'label'  was correct.
![CleanShot 2024-08-06 at 20 59 30](https://github.com/user-attachments/assets/4ba684e4-1e39-4101-8cba-3db5fd224a2f)

The original bug report still remains, I hope you will consider to use the Music Provider name in Music Assistant as the 'label' in stead, as the youtube channel name is really unwanted. This could be totally different from the actual name of the person, as a youtube channel is a public thing.

**Comment by MarvinSchenkel** [comment]
Just double checking. You want the names of the instances (Michel, Tim and Linda) to show up as labels for the playlists? I'll have a look if I can see what's going wrong

**Comment by HA-TB303** [comment]
Yes, because otherwise we have know way of distinguishing who's playlist we are looking at.

It would be great of you could just take the label-name from the Music Assistant music provider name here, but really anything that works would be great :)

![image](https://github.com/user-attachments/assets/482b899f-239c-4a0d-a6cc-f6efdd165807)

**Comment by HA-TB303** [comment]
Slightly releated to this issue, niw when I look at my screenshots again, I also notice the music provider name is also not appearing consistantly:

These are all youtube music, but only some have the provider name (YouTube Music) behind them.

**Comment by MarvinSchenkel** [comment]
Fixed in #1546.

The logic is:
1. Check if the playlist has a name
2. If not available, use custom name for the music provider instance
3. If not configured and multiple instances exist, use 'Youtube Music - instance_id'
4. If not configured and only one instance exist, use 'Youtube Music'

**Comment by HA-TB303** [comment]
![image](https://github.com/user-attachments/assets/3180e998-225b-4274-aded-7e8e12bfeea0)

**Comment by OzGav** [comment]
@HA-TB303 2.1.2 and 2.2.0b4 have been released with this fix. Please confirm

**Comment by HA-TB303** [comment]
Hi It seems that [2024.7.1 BETA 0] is still the latest I can get.

**Comment by OzGav** [comment]
You are looking at the integration. You need to update the ADDON (server if you are running in Docker)

**Comment by HA-TB303** [comment]
Yes, seems to work great now 👍 
![CleanShot 2024-08-12 at 08 21 50](https://github.com/user-attachments/assets/42fe0b91-9958-47bb-8fe8-d027defc37ee)
