### ISSUE TITLE
Cannot access user token

### ISSUE THREAD

**Issue by mikabill** [music-assistant/hass-music-assistant#2732]
### What version of Music Assistant has the issue?

2.0.0b100

### What version of the Home Assistant Integration have you got installed?

2024.5.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

The path View > Developer > Developer Tools doesn´t exist on neither my laptop (Windows with Chrome) or on my Iphone so I cannot retrieve any user token

### How to reproduce

I can´t reproduce something I cannot reach due to lack of meny?

### Music Providers

Apple

### Player Providers

Apple

### Full log output

No log

### Additional information

No additional info

### What version of Home Assistant Core are your running

2024.2.0

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
This is not a MA problem. You need to a Google how to find the browser developer tools such as https://balsamiq.com/support/faqs/browserconsole/#:~:text=To%20open%20the%20developer%20console,(on%20Windows%2FLinux).

P.S. You are running a very old version of MA
