### ISSUE TITLE
HLS Streams / Specific SoundCloud tracks not playing

### ISSUE THREAD

**Issue by sda3-14** [music-assistant/hass-music-assistant#2739]
### What version of Music Assistant has the issue?

2.1.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I can't play some tracks from SoundCloud, and it will instead keep loading when clicking on these tracks. When checking the logs, it seems like it's because the SoundCloud provider returns an HLS stream for some tracks and a regular URL for others: When the song won't play, I can see a log message `DEBUG (MainThread) [music_assistant.audio.hls_stream] Start streaming HLS stream for url https://cf-hls-media.sndcdn.com/...`. For all other tracks, I see a normal `INFO (MainThread) [music_assistant.streams.media_stream] Detected (input) content type: aac (aac)` at that point.
It seems like this is meant to happen: https://github.com/music-assistant/server/blob/965de438e1bf0bd81726c3bd05b387cbdc39045a/music_assistant/server/providers/soundcloud/__init__.py#L320
However, it seems like HLS streams just won't work for me.
It might be possible to simply fix this by searching for a plain HTTP stream instead of simply choosing the first available stream (https://github.com/music-assistant/SoundcloudPy/blob/987eaab167e4c66f58eadfe6bd6baf6b277ae09c/soundcloudpy/soundcloudpy.py#L258), but I am unsure on the exact inner workings of SoundCloud, and I've tried to send my own requests to the `tracks` endpoint - but I always got back URLs for both HTTP and HLS streams beginning in `https://api-v2.soundcloud.com/media/soundcloud`, while `get_stream_details` checks for `https://cf-hls-media.sndcdn.com`.

### How to reproduce

Try playing some SoundCloud songs - here is one that wouldn't work for me, but I'm unsure whether it's the same in other environments: https://soundcloud.com/boris-brejcha/dimension

### Music Providers

SoundCloud and builtin MA provider only

### Player Providers

Slimproto, also tested with AirPlay, Chromecast and DLNA and had the same issue

### Full log output

[bad.log](https://github.com/user-attachments/files/16561463/bad.log)
[good.log](https://github.com/user-attachments/files/16561465/good.log)

### What version of Home Assistant Core are your running

2024.7.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Thoughts @gieljnssns ?

**Comment by gieljnssns** [comment]
I did some testing and I think this can be solved by just using
```python
stream_type=StreamType.HTTP
```

**Comment by CultusMechanicus** [comment]
I think this may be happening with the BBC Radio streams from Radio Browser too. HLS streams (which is nearly all of them), fail to play, but the rare AAC direct streams work fine. I thought it was the usual BBC control freakery, but the fact it's only the HLS versions makes me suspicious...

**Comment by Tom-hac** [comment]
I have the same question to @gieljnssns as joshuisken. I couldn't find this config on my docker installation.

**Comment by gieljnssns** [comment]
You can’t do that yourself. 
https://github.com/music-assistant/server/pull/1564

**Comment by marcelveldt** [comment]
This will be fixed in 2.2.0 beta 8 - we will also provide a new stable patch version asap
