### ISSUE TITLE
'Search' and partial name-matching does not work for *library* radio stations

### ISSUE THREAD

**Issue by ReinhardPrix** [music-assistant/hass-music-assistant#2745]
### What version of Music Assistant has the issue?

2.1.1

### What version of the Home Assistant Integration have you got installed?

2024.07.1.b0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

**Summary**: radio stations *in the library* (added from any of Tune-in, RadioBrowser or via explicit URLs) don't seem to be findable via 'Search' or playable with partial name matching.

**Details**

- My Radio library setup:
![Radio-library](https://github.com/user-attachments/assets/36aa3c87-b883-4bdd-8561-7cd9ea67c601)

(Grayed out radio stations are from RadioBrowser stations added to library, with the RadioBrowser provider deactivated, see explanation at the end. This is not related to the problem and could all be reproduced without RadioBrowser provider.)

'Radio Nova' was added from Tune-in, explicit URL and from RadioBrowser.
'FM4' was added from Tune-In, and 'oe1-q2a' was added via URL (with the renaming bug mentioned in #2548)

- Things that work:
1. playing (non-grayed-out) radio stations via the UI
2. playing via action `mass.play_media` using the full station name:
```yaml
action: mass.play_media
target:
  entity_id: media_player.vlc_telnet_2
data:
  media_id: radio nova
```
- Things that don't work (but I would expect to work(?)):
1. finding a (library) radio station via UI MA search:
![Search-Radio-via-UI](https://github.com/user-attachments/assets/c4cd149f-0f06-4e43-a494-70e97169f4af)

2. searching via `mass.search`:
```yaml
action: mass.search
data:
  name: Radio Nova
```
returns emtpy lists (with media-type=radio on or not)

3. playing `mass.play` with partial station name:
```yaml
action: mass.play_media
target:
  entity_id: media_player.vlc_telnet_2
data:
  media_id: fm4
```
returns an error `Failed to perform the action mass.play_media. MediaNotFoundError: Could not resolve ['fm4'] to playable media item`

Note that UI search and partial-name action-call `mass.search` and `mass.play_media` *does* actually work with the `RadioBrowser`  provider, but only on the 'provider-side', not with stuff in the MA library, which is why I had de-activated that provider for the above experiments.
(One problem with RadioBrowser provider-side matching is that its is way to unspecific and will match unintended stations, rather than my library/favorites).

### How to reproduce

Turn off or deactivate `RadioBrowser` provider. Add radio stations to library via Tune-in Radio or explicit radio-stream URL providers.

Try UI Search, run Developer->Actions `mass.search` with partial or full station name, or `mass.play_media` with a partial station name.

### Music Providers

- Tune-In Radio
- added radio stream URLs

Search and play works with `RadioBrowser`, but only provider-side, not with items in the library.

### Player Providers

any / irrelevant

### Additional information

Maybe some similarities with #2188 but overall seems to be something else (?).

### What version of Home Assistant Core are your running

2024.8.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Well trying to play something with a partial name is not supported

Something else is going on with your search though as you should have returns for all the item types like this:

![image](https://github.com/user-attachments/assets/483547ed-d337-48a7-a6a1-94c247a34dfd)

**Comment by ReinhardPrix** [comment]
Playing partial names does work though with library tracks/albums/artists and it also works for Radio stations if `RadioBrowser` is active. This is also quite important so that voice commands like 'play radio fm4' just work without having to quote the full name in the library.

Your above search results indicate that all stations are found on `RadioBrowser` though, which also works for me, but not if I have only non-RadioBrowser stations (Tune-In / URL). Also it does not seem to list RadioBrowser stations higher that I have in my library, eg this:

![Search-RadioBrowser-provider](https://github.com/user-attachments/assets/8908710d-4eec-4224-a972-3960273b5a62)

which are 'bad' results in the sense that they are the wrong 'Radio Nova' stations found, even the 'top restult', on the 'RadioBrowser' provider, but not even listing on the first page the one I have added to my library.

**Comment by OzGav** [comment]
It might work trying to play something with a partial media id but there is no guarantee you would get the correct result. Hence why there are options to specify media type, artist name or album names.

It is not possible to search TuneIn. Only TuneIn favourites are imported into the MA library. 

The view you are looking at though is the GLOBAL SEARCH. It is designed to search across all providers so you can find items to add to the library. Thus in library items are not prioritised. If you want to search through your in library items you need to go to the relevant view. 

mass.search works the same way as above. However, there is an item on the backlog to enable the limiting of this search to library or favourited items. ETA for that can't be given.

So I believe MA is working correctly given the current level of functionality.

**Comment by ReinhardPrix** [comment]
mh, I see ... a feature, not a bug :disappointed:   ... thanks for clarifying.

It still seems a bit strange to me that 'search' does not seem to cover the radio library per se, not just for the in-library Tune-in stations, but also the by-hand added URL streams seem to get fully ignored :man_shrugging: 

In any case, being able to limit the search to library items and/or favorites might indeed be a good solution for this, given that at least with RadioBrowser this would work.

However, it seems to me that for assistants and automations to work correctly with radio stations, one basically has to tell *them* what exact radio stations should be considered possible, and one cannot offload this task to MA, despite the stations being in the library/favorites?! ... oh well. (Maybe I still misunderstand ..)

**Comment by OzGav** [comment]
Yes you would have to tell MA which one. Take these as an example. If I said play "Triple M" or "Classic Rock" how could MA know which one I was referring to?

![image](https://github.com/user-attachments/assets/3ed0c67f-7436-47c0-9b39-68f3e2bb5c50)

I don't understand why you want to search for the URL stream you have added. You know what they are are and they are in your library so why search for them?

**Comment by ReinhardPrix** [comment]
Yes, so if I had only one of those 'Triple M ...' stations in my library or favorites, then it should *just work* no? Even if I had a few of them in my library, then it could just pick one, as it usually does with music found in the library.

My main motivation was to be able to tell the OpenAI assistant: "play Radio Nova in the kitchen" or "play FM4 ... " etc, for example, even if
a) the station name is not unique in RadioBrowser or 
b) if it's only a partial match with the full station name ("ORF Radio FM4" from Tune-in). 
as in both cases using my library items would dis-ambiguate what was meant.

So I guess the actual 'missing' features at the moment are:
- search over and do partial-match `play_media()` on Tune-in stations *and* manually-added URL streams
- being able to restrict or preferentially match on library-items/favorites

Right?

But yeh, I'm seeing enough work-arounds to get around this, if this is all intended behavior right now. 
I am very new to HA/MA and so my apologies if I misunderstand the details/ideas of how this is actually supposed to work. Thanks for the feedback!

**Comment by OzGav** [comment]
The other problem you have is the AI may guess what you mean. The prompts we have provided don't allow for radio stations. 

Having said that I expect that it should work for a service call (action as it is now) so let me ask about that.

**Comment by OzGav** [comment]
Ok an adjustment has been made which should prefer local matches even partial ones. Let’s see how that goes after the next update.

**Comment by OzGav** [comment]
Try 2.1.2 or 2.2.0b4 and see how that goes

**Comment by ReinhardPrix** [comment]
Awesome!! :+1: 

Updated to version 2.1.2 and now basically everything works: :tada:
1. global UI search finds radio items in the library (from Tune-In or URLs)
2. service/action `mass.search` finds all library radio items as well 
3. service/action `mass.play_media` finds and plays (incl. partial matched) library radio stations

All this works based on Tune-In and local URL streams, without RadioBrowser provider.
With RadioBrowser the search also covers 'upstream' provider matches, but now gives preference to in-library matches even for partial matches.

Perfect! :)
