### ISSUE TITLE
spotify Login failed for user

### ISSUE THREAD

**Issue by ppiixxii** [music-assistant/hass-music-assistant#2749]
### What version of Music Assistant has the issue?

 2.1.3

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

while using correct spotify credentials, the system states that login has failed

### How to reproduce

go to music provider and key in credentials, 

### Music Providers

spotify

### Player Providers

n/a

### Full log output

[log.txt](https://github.com/user-attachments/files/16586469/log.txt)

### What version of Home Assistant Core are your running

2024.8.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by ppiixxii** [comment]
yes until 2.1.2 it worked, no unusual characeters in password, the account works if i login via web with the same credentials.

**Comment by OzGav** [comment]
Can you roll back using your backup to see if it works again. Nothing was changed with Spotify in this update.

**Comment by OzGav** [comment]
As above. Please roll back and confirm it works with 2.1.2. I use Spotify and it is working fine for me (although I am using my own client id)

**Comment by frodo777** [comment]
the same here:

Only Spotify Premium accounts are supported

**Comment by ppiixxii** [comment]
rolled back to 2.1.2 problem remains, i also have the 2.1.1. version still in the backups, go to that one? (and yes paid spotify)

**Comment by ppiixxii** [comment]
I do not use client ID. only account name and password.

**Comment by OzGav** [comment]
Yeah so maybe it is a Spotify problem again.

**Comment by OzGav** [comment]
I just tried mine on my dev account and it also failed. So could be a temporary Spotify outage or a bigger problem. Everyone will just have to sit tight and wait and see what happens this time,

**Comment by erkr** [comment]
@OzGav Spotify announced, to the Librespot library team, that username / password logins will be removed.  If that is what is happening now, rolling back dormant help.

**Comment by burghs** [comment]
I am on Spotify Family Account which also worked fine and getting a login error in the MASS Server logs "ERROR (MainThread) [music_assistant] Error loading provider(instance) Spotify: Login failed for user". Pretty sure this is on Spotify side.

**Comment by ppiixxii** [comment]
yes, they are forcing me to change the pwd also

**Comment by churchofnoise** [comment]
Also had to change Spotify password after multiple attempts to add Spotify as music provider (I also made an issue, presumably identical to this which I just closed as this issue exists #2750 ).

**Comment by kschmidtlarsen** [comment]
Will just echo the issue today - I'm completely new to MA btw. 

Premium Family account. 
Adding my VT Music account worked great. 
x86 i7 setup with Unraid, Home assistant as a VM and MA installed through HACS in HA. 
Been messing with this for over an hour and then found this - will try to change my Spotify PW to see if this helps.

`2024-08-12 19:26:40.755 WARNING (MainThread) [music_assistant.providers.spotify] Error while retrieving Spotify token after 0.21 seconds, details: 
2024-08-12 19:26:40.962 WARNING (MainThread) [music_assistant.providers.spotify] Error while retrieving Spotify token after 0.21 seconds, details: 
2024-08-12 19:26:41.169 WARNING (MainThread) [music_assistant.providers.spotify] Error while retrieving Spotify token after 0.21 seconds, details: 
2024-08-12 19:26:41.383 WARNING (MainThread) [music_assistant.providers.spotify] Error while retrieving Spotify token after 0.21 seconds, details: 
2024-08-12 19:26:41.616 WARNING (MainThread) [music_assistant.providers.spotify] Error while retrieving Spotify token after 0.23 seconds, details: `

**Comment by dedors** [comment]
Did a Music Assistant update today. A short while later I receive a mail from Spotify to change my password (happened like 6 times since I use MA). Changed password, but can't login with MA now.

**Comment by CultusMechanicus** [comment]
Yep, I set this up this afternoon, with Spotify working, it had just barely finished syncing artist art. Got an email saying "Suspicious activity, change your password". Changed the password, Spotify app accepts new password, Spotify web accepts new password, Music Assistant login fails.

**Comment by erkr** [comment]
Hi all, Spotify phasing out the authorisation mechanism that is used by Librespot library.
Librespot is used in MA, so the coming hours, days, all of us will be locked out using Spotify in MA.
Hopefully there is a witch update of Librespot, so wat can re-author the Spotify provider

**Comment by OzGav** [comment]
Spotify is fixed in beta 6. For those running stable you will have to be a little more patient. Please thank Marcel for the unbelievable effort in turning this around so fast! https://music-assistant.io/help/#donations
