### ISSUE TITLE
Login failed - spotify

### ISSUE THREAD

**Issue by ptrnmgr** [music-assistant/hass-music-assistant#2753]
### What version of Music Assistant has the issue?

2.1.3

### What version of the Home Assistant Integration have you got installed?

2024.7.1.b0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I have four logins for spotify. I recently (two MA updates ago) created and entered their client ID's in MA. Everything worked. Today i got mail from spotify: "Hello To protect your Spotify account, we have reset your password due to suspicious activity we detected."
I succesfully changed pwd for every account. When i try to login in MA i get message: "login failed for user ...". i retried after deleting client ID but no avail. I tried removing an account in MA and adding it back.
Spotify account are still reachable with updated pwd's trough apps and websites.

### How to reproduce

after pasword reset on spotify
add spotify provider
try to login

### Music Providers

Spotify

### Player Providers

NA

### Full log output

[log.txt](https://github.com/user-attachments/files/16595555/log.txt)

### What version of Home Assistant Core are your running

2024.8.1

### What type of installation are you running?

Home Assistant Core

### On what type of hardware are you running?

Raspberry Pi

**Comment by ptrnmgr** [comment]
i restored backup of previous MA version but i cannot login in any of my spotify accounts

**Comment by Rubyman77** [comment]
Same happened to me today. Can no longer log into Spotify through MA

**Comment by ptrnmgr** [comment]
> Same happened to me today. Can no longer log into Spotify through MA. Also got the email from spotify to reset password.

did you also used the 'client ID' option?

**Comment by OzGav** [comment]
https://github.com/music-assistant/hass-music-assistant/issues/2753

**Comment by Rubyman77** [comment]
> > Same happened to me today. Can no longer log into Spotify through MA. Also got the email from spotify to reset password.
> 
> did you also use the 'client ID' option?

Tried with and without but same result.

**Comment by kine90** [comment]
Same here. I am part of a family plan. After updating to the last version I get the error that "only premium accounts are supported" and I received a password reset link from Spotify because of account's suspect activities. I am using a custom Client ID. Everything worked fine with the previous version of MA.

**Comment by Rubyman77** [comment]
Looks like a fix is coming https://github.com/music-assistant/hass-music-assistant/issues/2749

**Comment by ptrnmgr** [comment]
> #2753

i don't understand? why closed? why reference this post? I do not have a lot of experience in github, still learning. Could you explain?
I searched other issues but none seemed the same...

**Comment by Rubyman77** [comment]
> > #2753
> 
> i don't understand? why closed? why reference this post? I do not have a lot of experience in github, still learning. Could you explain? I searched other issues but none seemed the same...

Check link in above post.
