### ISSUE TITLE
Repeat one doesn't work using the AirPlay player provider

### ISSUE THREAD

**Issue by Geweldich** [music-assistant/hass-music-assistant#2755]
### What version of Music Assistant has the issue?

2.1.4

### What version of the Home Assistant Integration have you got installed?

2.1.4

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

The repeat one functionality is not working using the AirPlay player provider. With repeat one active, playback stops after the current song stops.

A working workaround is to create a queue/playlist with only 1 song in it and hit repeat (instead of repeat one), which works fine but is not ideal.

### How to reproduce

1. Configure/use the AirPlay player provider.
2. Start a song with repeat one active OR when listening to album switch on Repeat one.

### Music Providers

Filesystem

### Player Providers

The AirPlay provider.

### Full log output

[ma_log.log](https://github.com/user-attachments/files/16600416/ma_log.log)

### What version of Home Assistant Core are your running

2024.8.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Confirmed. Works OK for me when using repeat all.

**Comment by Geweldich** [comment]
Hi @OzGav @marcelveldt this appears to be fixed now.
