### ISSUE TITLE
Home page fails to load if a recently played URL returns 404

### ISSUE THREAD

**Issue by DarkFox** [music-assistant/hass-music-assistant#2766]
### What version of Music Assistant has the issue?

2.2.0b6 

### What version of the Home Assistant Integration have you got installed?

2024.8.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

If a URL in music/recently_played_items returns 404, the home page fails to load, showing an error "Unable to retrieve info for [url]: Server returned 404 Not Found".
![image](https://github.com/user-attachments/assets/067efc2e-cf9f-448b-95a6-6e828a50bd16)

### How to reproduce

- Play media from a URL using mass.play_media
- Wait for the file to become unavailable (or remove it yourself, if in your control)
- Go to Home in MA

### Music Providers

Music Assistant Built-in/generic

### Player Providers

Sonos, but this doesn't seem player-related

### Full log output

[d5369777_music_assistant_beta_2024-08-16T17-50-01.496Z.log](https://github.com/user-attachments/files/16639935/d5369777_music_assistant_beta_2024-08-16T17-50-01.496Z.log)

### What version of Home Assistant Core are your running

2024.8.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by marcelveldt** [comment]
Ah, so this is just some URL that you manually play that becomes unavailable ?

**Comment by DarkFox** [comment]
Yes. DR seems to have started removing the files for their news broadcast podcast after a few days. But I presume the case of an unavailable file isn't handled at all in this bit of the code, so this would probably apply to a number of situations where that could happen.

**Comment by marcelveldt** [comment]
Yeah, I'll add a guard in the code for this.

**Comment by marcelveldt** [comment]
This is fixed in 2.2.0 beta 8 - if the fix is confirmed working, it will also be included in the patch release 2.1.5 for the stable version

**Comment by DarkFox** [comment]
I can confirm that the issue is fixed and working. Thank you so much for the quick turn-around! <3
