### ISSUE TITLE
Portuguese (Portugal)

### ISSUE THREAD

**Issue by andreclemente** [music-assistant/hass-music-assistant#2770]
### New language

pt-PT

**Comment by OzGav** [comment]
Thanks. Portuguese (Brazil) is 40% done. How different are the two languages? I could see whether it is possible to copy the current translation across if that would speed things for you?

**Comment by OzGav** [comment]
@andreclemente just following up on the above

**Comment by andreclemente** [comment]
Copy the current translation across would speed things up indeed

**Comment by OzGav** [comment]
Ok this language is ready to go. Thanks for the help!

**Comment by andreclemente** [comment]
First draft done. I'll try to review it later
