### ISSUE TITLE
Artist name not shown on Sonos app while it's shown on MA interface

### ISSUE THREAD

**Issue by miniworm** [music-assistant/hass-music-assistant#2772]
### What version of Music Assistant has the issue?

2.1.4

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When playing to Sonos speaker (Era 100) Artist name is not shown on Sonos app while it's shown on MA interface and song title ois shown as album ("No title" is shown as song title).

### How to reproduce

Play sont to Sonos speaker

### Music Providers

Subsonic (Navidrome)

### Player Providers

Sonos (Era 100 speaker)

### Additional information

I have standalone MA server running on Linux using docker.

### What version of Home Assistant Core are your running

2024.2.0

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

**Comment by miniworm** [comment]
Related discussion with additional info and screenshots: https://github.com/orgs/music-assistant/discussions/2759

**Comment by OzGav** [comment]
This will be addressed once the new Sonos provider is released.

**Comment by OzGav** [comment]
Please confirm if this has been fixed with the release of the new Sonos provider in 2.2.0 beta 3

**Comment by OzGav** [comment]
This will be closed soon due to no follow-up
