### ISSUE TITLE
Typo: musicbrainz provider manifest.json

### ISSUE THREAD

**Issue by lwsrbrts** [music-assistant/hass-music-assistant#2779]
### What version of Music Assistant has the issue?

2.1.4

### What version of the Home Assistant Integration have you got installed?

2024.8.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Just a simple typo in the `manifest.json` for musicbrainz.

https://github.com/music-assistant/server/blob/cbcca963db21d676606f295f374bcf6801a44bb8/music_assistant/server/providers/musicbrainz/manifest.json#L5

```json
"description": "MusicBrainz is an open music encyclopedia that collects music metadata and makes it available to the public. Music Assistant uses MusicBrainz primary to identify (unique) media items and therefore the provider can not be disabled. However note that lookups will only be performed if this info is absent locally.",
```

**primary** > **primarily**.

### How to reproduce

Nothing to repro.

### Music Providers

N/A - pertains only to description text.

### Player Providers

N/A - pertains only to description text.

### What version of Home Assistant Core are your running

2024.8.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Thanks will be fixed in the next update.
