### ISSUE TITLE
Most radio stations disappeared in the radio browser

### ISSUE THREAD

**Issue by filipferris** [music-assistant/hass-music-assistant#2780]
### What version of Music Assistant has the issue?

2.2.0b11

### What version of the Home Assistant Integration have you got installed?

2024.8.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Most of the radio stations in the radio browser have disappeared. I can still see them in the built-in radio browser, but they're not available from the Music Assitant plugin. 
Here is e.g. the By Country/Norway/ list in MA radio browser
![image](https://github.com/user-attachments/assets/768db1de-e52d-41e7-98ba-66e1264fe557)
compared with the same list in the built-lin radio browser
![image](https://github.com/user-attachments/assets/33ea6493-3d34-48cd-b08a-651c5cdd0da3)

### How to reproduce

1. Click on "Browse"
2. Select "RadioBrowser"
3. Choose "By country"
4. Choose "Norway"
5. See only one channel listed

### Music Providers

Spotify
Music Assistant
RadioBrowser

### Player Providers

Airplay
UGP
UPnP/DLNA
SONOS
Chromecast

### Full log output

[music-assistant.log](https://github.com/user-attachments/files/16670252/music-assistant.log)

### What version of Home Assistant Core are your running

2024.8.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by marcelveldt** [comment]
Issue confirmed... strange!
We'll look into it.

**Comment by marcelveldt** [comment]
will be fixed with 2.2.0 rc2 (or 2.2 stable)

**Comment by OzGav** [comment]
Browsing Norway looks fine to me. Fixed.
