### ISSUE TITLE
Tidal provider | Login fail in 2.3.0b0 and stable 2.2.0

### ISSUE THREAD

**Issue by mooseBringer** [music-assistant/hass-music-assistant#2787]
### What version of Music Assistant has the issue?

2.3.0b0

### What version of the Home Assistant Integration have you got installed?

2024.8.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When clicking the 'Starts auth process via PKCE on Tidal' button nothing happens. Just blinks and then nothing. 

### How to reproduce

Try to add Tidal as provider in version 2.3.0b0 or 2.2.0

### Music Providers

Tidal

### Player Providers

Chromecast
Airplay

### Additional information

I get 401: Unauthorized when trying to download log file in core settings

### What version of Home Assistant Core are your running

2024.8.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Alternative

**Comment by OzGav** [comment]
The reason for this has been identified and will be fixed in the next patch release

**Comment by mooseBringer** [comment]
Great, many thanks!

**Comment by marcelveldt** [comment]
2.2.1 is now building with a patch for this issue

**Comment by marcelveldt** [comment]
I will also publish a new beta as I see you are running the beta

**Comment by mooseBringer** [comment]
Hate to say it but it still won't open the pop-up. I tried both the beta and the stable version. There seems to be a white frame blinking at the moment I click it. After stressing the button I can see a faint text click here if the pop-up doesn't open but it dissapears instantly. I attached the logfile as I now had access to it. 

[music-assistant-beta.log](https://github.com/user-attachments/files/16708737/music-assistant-beta.log)

[music-assistant.log](https://github.com/user-attachments/files/16708370/music-assistant.log)

**Comment by marcelveldt** [comment]
Can you check another device/browser perhaps ?

**Comment by mooseBringer** [comment]
Yes, now I tested EDGE, Chrome and the webview in android companion app. Same behavior

**Comment by mooseBringer** [comment]
Now it works in 2.3.0b2
Great work, thank you!
