### ISSUE TITLE
Import of album tracks all get track number 1

### ISSUE THREAD

**Issue by ulflulfl** [music-assistant/hass-music-assistant#2789]
### What version of Music Assistant has the issue?

2.3.0b0

### What version of the Home Assistant Integration have you got installed?

none (HACS not installed)

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

As discussed in the chat: After doing a database reset, all album tracks that I import from the local filesystem get the track number 1. The tags of the media files are ok.

### How to reproduce

I've resetted the database.
Reimport started
All tracks I was looking at at various album pages had track number 1

### Music Providers

filesystem local

### Player Providers

HASS

### Full log output

Only DEBUG log available, but nothing suspicious in there.

### What version of Home Assistant Core are your running

2024.8.2

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by ulflulfl** [comment]
lwsrbrts noted in the chat that disc 2 will have track 2 and thats also happens on my side

**Comment by lwsrbrts** [comment]
Also track `3` on disc `3` too.

![image](https://github.com/user-attachments/assets/13559ad4-3e0b-46dd-934a-6ce25711284f)

**Comment by OzGav** [comment]
This will get looked at soon

**Comment by marcelveldt** [comment]
I cant reproduce this - works fine on my end. So would be nice to get some additional info when this happens

**Comment by OzGav** [comment]
This is fixed for new installs.

@marcelveldt existing albums are not getting updated by the looks of it. Tried an Update Metadata and Refresh Item but neither worked. Not sure if it related but I couldn’t REMOVE FROM LIBRARY

**Comment by marcelveldt** [comment]
> This is fixed for new installs.
> 
> @marcelveldt existing albums are not getting updated by the looks of it. Tried an Update Metadata and Refresh Item but neither worked. Not sure if it related but I couldn’t REMOVE FROM LIBRARY either

Does a refresh on the item fix it ?

**Comment by lwsrbrts** [comment]
It didn't for me. I reset my database with the new button in 2.2.2 to resolve it.

**Comment by OzGav** [comment]
Yes it appears that is unfortunately necessary. Will leave this open for now so others can find it.

in summary to fix this. Update to 2.2.2 or later and do a DB reset.

**Comment by ulflulfl** [comment]
at which beta should the fix be in? I don't want to reset the whole database just to find out that my version is still too old ...

**Comment by OzGav** [comment]
Good point. Not in the beta yet!i

**Comment by marcelveldt** [comment]
> It didn't for me. I reset my database with the new button in 2.2.2 to resolve it.

Another less-destructive way is to restore a backup of 2.1.4 first and then upgrade to 2.2.2

**Comment by marcelveldt** [comment]
> Good point. Not in the beta yet!i

I'll release a new beta with this patch included in a bit

**Comment by OzGav** [comment]
2.2.0 beta 3 has been released

**Comment by ulflulfl** [comment]
I've added a new album in 2.3.0b3 and the track numbers are working as expected again
