### ISSUE TITLE
Qobuz playlist name does not update in MA

### ISSUE THREAD

**Issue by madbrain76** [music-assistant/hass-music-assistant#2795]
### What version of Music Assistant has the issue?

2.2.2

### What version of the Home Assistant Integration have you got installed?

2024.8.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

If I rename a playlist in Qobuz, and sync it in MA, the old playlist name continues to show in MA

### How to reproduce

1. Create a playlist using the Qobuz app or web player . I called it "Qobuz playlist"
2. Add the Qobuz music provider to MA
3. Verify that the Qobuz playlist shows under playlists
4. In the Qobuz app, rename the playlist to "Renamed Qobuz playlist"
5. Sync the playlist in MA
6. The playlist name remains "Qobuz playlist"

### Music Providers

Qobuz

### Player Providers

N/A

### Full log output

[ma4.log](https://github.com/user-attachments/files/16727276/ma4.log)

### What version of Home Assistant Core are your running

2024.8.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Windows

**Comment by marcelveldt** [comment]
This is fixed in the current beta 2.3.0b3 - it will eventually also land up in the next stable release

**Comment by madbrain76** [comment]
Great !
