### ISSUE TITLE
Not able to group multiple players

### ISSUE THREAD

**Issue by timbeckss** [music-assistant/hass-music-assistant#2798]
### What version of Music Assistant has the issue?

2.2.2

### What version of the Home Assistant Integration have you got installed?

2024.8.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When I try to group multiple HEOS Speakers (2+), which are integrated through the Home Assistant plugin, I only get a group of two. If I select a third one the other one gets kicked out of the group. It doesn't throw any errors in the log.

![Music Assistant – Home Assistant und 15 weitere Seiten - Persönlich – Microsoft_ Edge 2024-08-24 00-52-35](https://github.com/user-attachments/assets/66d0cdd1-5971-4193-8571-07fd352f8f7a)

Using the grouping feature of the devices that are imported through Airplay works fine. In the HEOS App you can see, that grouping the Airplay devices doesn't actually create a room but plays synced streams on each devices.

### How to reproduce

1. Integrate the speakers through Home Assistant Media Player Plugin
2. Try to group more than two speakers

### Music Providers

Not working:
1. Home Assistant Media Player

Working:
1. AirPlay

### Player Providers

Not working:
1. Spotify
2. Soundcloud

### Full log output

[home-assistant_mass_2024-08-23T22-58-48.571Z.log](https://github.com/user-attachments/files/16734349/home-assistant_mass_2024-08-23T22-58-48.571Z.log)

### What version of Home Assistant Core are your running

2024.8.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Alternative

**Comment by OzGav** [comment]
Why do you want to group HA media players if you can group the Airplay ones?

**Comment by timbeckss** [comment]
For me Airplay has a way bigger delay and some random sound dropouts from time to time.

**Comment by OzGav** [comment]
We will be more interested in that than trying to fix a universal group of HA players but this will get looked at eventually

**Comment by marcelveldt** [comment]
> For me Airplay has a way bigger delay and some random sound dropouts from time to time.

Airplay has a bit of delay at stream-start (1.5 to 2 seconds) but should then be buttery smooth.
Do you still have those dropouts in the last release ? 

As for the grouping of the HEOS speakers, what happens if the stream is already playing and you group them in Home Assistant ? Does that work ?

**Comment by timbeckss** [comment]
> Airplay has a bit of delay at stream-start (1.5 to 2 seconds) but should then be buttery smooth.
Do you still have those dropouts in the last release ?

Yes in a 3 minute song i have like 3 to 5  one second dropouts. Sometimes it's worse.

> As for the grouping of the HEOS speakers, what happens if the stream is already playing and you group them in Home Assistant ? Does that work ?

If the music plays on one speaker and I use an automation to group them: yes that works. The players get grouped correctly and the music plays without stopping.

**Comment by marcelveldt** [comment]
> Yes in a 3 minute song i have like 3 to 5 one second dropouts. Sometimes it's worse.

Sounds like buffer issue - Airplay sends lossless PCM or ALAC by default so its a bit demanding on bandwidth, while sending audio to HEOS with HA will send mp3 compressed audio by default. Did you leave compression on in the Airplay settings ?

> If the music plays on one speaker and I use an automation to group them: yes that works. The players get grouped correctly and the music continues without stopping.

OK, thanks. I'll review the implementation between MA and HA then

**Comment by timbeckss** [comment]
Thanks for your time and effort!

`Sounds like buffer issue - Airplay sends lossless PCM or ALAC by default so its a bit demanding on bandwidth, while sending audio to HEOS with HA will send mp3 compressed audio by default. Did you leave compression on in the Airplay settings ?`

I'm not sure whre to do that. Is it a MA setting or inside the heos app?

**Comment by OzGav** [comment]
In the MA settings for the player

**Comment by OzGav** [comment]
@timbeckss please provide some further information regarding the effect of changing the compression setting

**Comment by dunxd** [comment]
Having some airplay dropout issues and found this.  

> Did you leave compression on in the Airplay settings ?

Is this question also suggesting that dropouts are less likely if compression is enabled or disabled? What is the suggested setting?

**Comment by OzGav** [comment]
If the dropouts are due to network congestion then compression ON should help

**Comment by OzGav** [comment]
Upcoming changes in the beta server will see groups completely rewritten. Hopefully this will fix this issue.

**Comment by timbeckss** [comment]
I will try it as soon it is released. Thanks for your efforts!

**Comment by OzGav** [comment]
Beta 30 has been released. Confirm this hass been fixed

**Comment by timbeckss** [comment]
Sadly I still have the same results I described in my initial post. Grouping with an automation works fine nevertheless. Im going to do a full factory reset with all speakers to rule out any problems with heos.

**Comment by marcelveldt** [comment]
> Upcoming changes in the beta server will see groups completely rewritten. Hopefully this will fix this issue.

That only applies for grouping within any of the native providers. This issue report is about grouping players from the HA provider, and more specifically HEOS players.

**Comment by marcelveldt** [comment]
I have removed the ability to sync players from MA using HA players, it was too much of a hot mess due to the generic approach.
You just need to use HA players to do the grouping or ofcourse use any of the native MA providers.
