### ISSUE TITLE
Tracks play for a while, then restart and play to the end

### ISSUE THREAD

**Issue by stevegroom** [music-assistant/hass-music-assistant#2799]
### What version of Music Assistant has the issue?

2.2.2

### What version of the Home Assistant Integration have you got installed?

2024.7.3

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Music Assistant with Plex as the audio source and SONOS as the target speaker. 

I used the 500 random tracks playlist and started to listen to the songs. Each song plays for a while (in this example 1:20) and then starts over before playing until the end. 

In this image you can see the total played time is longer than the track length !

<img width="1663" alt="image" src="https://github.com/user-attachments/assets/a2bf9688-a092-4d5a-bee6-2ef1ad652142">

### How to reproduce

described above

### Music Providers

Plex 

### Player Providers

SONOS

### Full log output

[music-assistant_core.log](https://github.com/user-attachments/files/16730762/music-assistant_core.log)

### Additional information

Installed Music Assistant for the first time just a few days ago. Was using SONOS playing in home assistant or the SONOS app previously.

### What version of Home Assistant Core are your running

2024.7.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
If you are using Sonos please test the latest beta which includes a rewritten and new pair of Sonos providers. 2.3.0 beta 3 or later is what you need. You can install this along side your stable. Just stop the stable before starting the beta

**Comment by marcelveldt** [comment]
Like @OzGav above already asked, I would be very interested if you could give the beta version of MA a try - you can even install it side by side with the stable version just for testing (just not start them both at the same time).

We have a completely rewritten Sonos provider now in beta, using their new api's. My first testing with this is that it runs so much better than the old/legacy upnp api's. I wouldnt be surprised if this also fixes the playback issues.

**Comment by stevegroom** [comment]
Happy to try the beta, but I'm a bit confused about the version to install.  

In add-ons I have add-on MA 2.2.2
If I open HACS, I don't see any currently installed Music Assistant 
The download proposes 2024.8.1  and with beta enabled it is still the latest version. There is an older 2024.7.1.b0.

Steve

**Comment by marcelveldt** [comment]
> Happy to try the beta, but I'm a bit confused about the version to install.
> 
> In add-ons I have add-on MA 2.2.2 If I open HACS, I don't see any currently installed Music Assistant The download proposes 2024.8.1 and with beta enabled it is still the latest version. There is an older 2024.7.1.b0.
> 
> Steve

Within the addons, you can also install the BETA version of the addon. There is simply another addon for BETA.
So you can stop your current stable add-on and then start the beta addon to give it a try

**Comment by stevegroom** [comment]
Beta installed. On adding Plex, there were several red error message pop ups, that I did not record, but I did manage to get the library connected. Sonos installed without problem. 

I have played several tracks and from beginning to end without any random restarts. 

S. 

The errors were with Plex authentication - I was running MA inside the MacOS Homeassistant App and that does not seem to support pop-ups. Tried again in Safari and authenticated ok. 
[music-assistant copy.txt](https://github.com/user-attachments/files/16737799/music-assistant.copy.txt)

**Comment by stevegroom** [comment]
Better, but still happens

<img width="1334" alt="image" src="https://github.com/user-attachments/assets/c1bbcb6d-a44f-42ba-8e9b-b7ea8afb1997">

Logfile from the time.

2024-08-24 20:50:18.283 WARNING (MainThread) [music_assistant.apple_music] Skipping sync of item apple_music://album/l.3XXGtvw - error details: Album is missing artist(s)
2024-08-24 20:50:21.133 WARNING (MainThread) [music_assistant.apple_music] Skipping sync of item apple_music://album/l.rPzOCTm - error details: Album is missing artist(s)
2024-08-24 20:50:22.552 WARNING (MainThread) [music_assistant.apple_music] Skipping sync of item apple_music://album/l.HQe7JIk - error details: Album is missing artist(s)
2024-08-24 20:50:23.704 WARNING (MainThread) [music_assistant.apple_music] Skipping sync of item apple_music://album/l.VsKP4gj - error details: Album is missing artist(s)
2024-08-24 20:57:58.274 INFO (MainThread) [music_assistant.apple_music] Attempt 1/5 failed: Apple Music API Timeout
2024-08-24 20:57:58.275 INFO (MainThread) [music_assistant.apple_music] Retrying in 15 seconds...
2024-08-24 20:57:58.354 INFO (MainThread) [music_assistant.metadata] Metadata scanner finished.
2024-08-24 20:58:18.678 INFO (MainThread) [music_assistant.apple_music] Attempt 2/5 failed: Apple Music API Timeout
2024-08-24 20:58:18.678 INFO (MainThread) [music_assistant.apple_music] Retrying in 30 seconds...
2024-08-24 21:00:24.905 INFO (MainThread) [music_assistant.apple_music] Attempt 1/5 failed: Apple Music API Timeout
2024-08-24 21:00:24.906 INFO (MainThread) [music_assistant.apple_music] Retrying in 15 seconds...
2024-08-24 21:03:00.327 WARNING (MainThread) [music_assistant.apple_music] Skipping sync of item apple_music://track/265676718 - error details: Track is missing artist(s)
2024-08-24 21:04:13.594 INFO (MainThread) [music_assistant.apple_music] Attempt 1/5 failed: Apple Music API Timeout
2024-08-24 21:04:13.595 INFO (MainThread) [music_assistant.apple_music] Retrying in 15 seconds...

This track just restarted for a second time.

**Comment by OzGav** [comment]
Do you have manually uploaded music anywhere in your Apple Music library?

**Comment by stevegroom** [comment]
Yes

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by OzGav** [comment]
I think that is the cause of the album is missing artists warnings. @MarvinSchenkel can you confirm?

**Comment by stevegroom** [comment]
I would say that is likely, - I’ll have a closer look tomorrow

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by OzGav** [comment]
That is unlikely to be causing a restart and I note your original report was about Plex and Sonos so this Apple Music thing is likely unrelated. Please attach the FULL log from MA SETTINGS >> CORE next time this happens but check and remove any personal URLs

**Comment by stevegroom** [comment]
Just updated to the latest b4 beta, first track played after update restarted as it got to the end. 

The SONOS app and the HomeAssistant web pages are both open - HA starts playing the track and SONOS alert shows what it is doing. The SONOS alert is not repeated when the track restarts.

[2024-08-25 b4 music-assistant.txt](https://github.com/user-attachments/files/16741271/2024-08-25.b4.music-assistant.txt)

let me know if you want a higher level of logging..

**Comment by MarvinSchenkel** [comment]
> I think that is the cause of the album is missing artists warnings. @MarvinSchenkel can you confirm?

Yep, this is usually the case. It just skips the sync but it doesn't affect playback of other tracks.

**Comment by OzGav** [comment]
@stevegroom Please try again with beta 5 and confirm if you are using the S1 or S2 provider?

**Comment by stevegroom** [comment]
A different test. 
In MA Settings, set logging level to Verbose for Core and Plex and restarted. 
Selected one artist, waited for the tracks to appear, clicked on the first track. Sonos shows 'Unable to play ... file cannot be found' 
I can browse to services, Plex, search and find and play the same track in the SONOS app. 
[2024-08-26 b5 music-assistant 2.txt](https://github.com/user-attachments/files/16746193/2024-08-26.b5.music-assistant.2.txt)

suggestions?

**Comment by stevegroom** [comment]
Hi, 
beta 6 installed, and was now able to play the previously queued track. :-) 

I'll do more testing at the end of the day. Thanks' for the work. 
Attached latest debug level log for info. 
[2024-08-26 b5 music-assistant 5.txt](https://github.com/user-attachments/files/16746617/2024-08-26.b5.music-assistant.5.txt)

**Comment by stevegroom** [comment]
Played two tracks, both glitched and restarted. Log attached. 

A different bug - Simon and Garfunkel - no playable tracks found - the album plays on SONOS .

[2024-08-26 b5 music-assistant 6.txt](https://github.com/user-attachments/files/16748274/2024-08-26.b5.music-assistant.6.txt)

**Comment by stevegroom** [comment]
Beta 7 testing. 

Tracks still restarting. I think most tracks restarting, but not after the same time.  

I also note the playing media view lags quite a bit behind the SONOS app. On my MacBook Pro, there is a SONOS pop-up at the moment a new track starts. MA updates a few seconds later. Also I can see the MA time position does not track well and often jumps backward a little when a new track begins - i.e. the track first shows the time at 7s before going to 0s. Occasionally the time will go back a second in the middle of a track.

[2024-08-27 b6 music-assistant 7.txt](https://github.com/user-attachments/files/16762538/2024-08-27.b6.music-assistant.7.txt)

Is it time to setup Wireshark? 

Steve

**Comment by marcelveldt** [comment]
> I also note the playing media view lags quite a bit behind the SONOS app. On my MacBook Pro, there is a SONOS pop-up at the moment a new track starts. MA updates a few seconds later.

Yes, I cant help that - the Sonos API send the event a bit delayed somehow - I guess they temporary patched their own app to use an alternative way after the stormflood of negative feedback. If the issue remains I will look at it on a later time, for now Im going to leave it as-is.

> Tracks still restarting. I think most tracks restarting, but not after the same time.

I have tested like crazy today and I do not see any tracks restarting. It just works perfectly fine.
So only thing I can think of is that its somehow related to the type of speaker or the music provider in MA, I'm a bit clueless.

What music providers did you test so far ? And did you also try different sonos speakers ?

**Comment by stevegroom** [comment]
Hi Marcel,
I tried all three communication solutions from SONOS. Originally I used SONOS net with one wired speaker. It worked but was not always good. I moved over to WiFi and that had problems with congestion, so I decided to take the plunge and move most over to Ethernet.

I thought Ethernet would solve the problems, but instead the (old) STP standard caused router runaway every few days.

My Wifi is now configured differently, so I think I will try SONOS wifi with devices fixed to 2.4Ghz and pinned to certain APs.

I doubt SONOS will ever upgrade to use RSTP – probably some of the earlier equipment is too underpowered.

Steve

From: Marcel van der Veldt ***@***.***>
Date: Friday, 30 August 2024 at 14:12
To: music-assistant/hass-music-assistant ***@***.***>
Cc: Steve Groom ***@***.***>, Mention ***@***.***>
Subject: Re: [music-assistant/hass-music-assistant] Tracks play for a while, then restart and play to the end (Issue #2799)

sonos-net is overrated, I'm glad they abandoned it in the recent line of products. It comes from a time where home wifi was still slow and with not enough coverage but nowadays each home has 100 times better WiFi then crappy sonosnet which also disturbs the frequency and even local network with spanning tree.

Nowadays I always recommend people to disable sonosnet if your home wifi is good.

**Comment by duckbert** [comment]
Hi all not sure if it is related but I also have tracks spontaneously restart. This happens also when I pause the playback, after a few minutes the track will play again. I am using slimproto for playback and stream from plex. My airplay devices don’t have this issue.

**Comment by OzGav** [comment]
Please check 2.2.4 or beta 23

**Comment by duckbert** [comment]
The spontaneous restart is fixed for me with version 2.2.4. Thank you!. However, pausing the playback still does not work, i.e. the playback resumes after a couple seconds with the next track.

**Comment by OzGav** [comment]
@duckbert that is a different issue so open a new one

**Comment by OzGav** [comment]
@stevegroom please confirm your original issue is fixed.

**Comment by OzGav** [comment]
We will close this soon due to no follow up

**Comment by stevegroom** [comment]
I am away at the moment, but can confirm that the latest version on 11th September was still restarting each song.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by OzGav** [comment]
Please provide details about what does work (eg. try different player providers and different music providers). I also note reference to CGNAT so please understand that we don’t have the resources to provide help to users with complex network installs.

**Comment by stevegroom** [comment]
In general the restarting seems to happen less frequently now (Tested on 20th September).

Also tested using a Sonos move - which is WiFi connected, and there were occasional track restarts. 

For these tests I was using my Apple Music Library

**Comment by OzGav** [comment]
Can you try with a different music provider

**Comment by SvenPaterson** [comment]
I also have this issue on tracks sporadically. Latest install of both MAss (2.2.6) and HAss (2024.9.3) Casting Apple Music to a Google chromecast audio. I checked the logs and see this info, time stamp shows the same period I'm listening to music but I'm not knowledgeable enough to know if msg is related to song restarts. 

I will add that I was having issues this morning and last night compiling a device with ESPhome addon because I seem to be running out of system memory. I do plan to move my installation from an RPi3 to RPi5 with 8gigs of RAM. I'll try to remind myself to report back and see if the issue persists. 

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp/_http_parser.pyx", line 563, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    b'\x16\x03\x01\x02'
      ^
2024-09-28 15:35:32.694 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 362, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp/_http_parser.pyx", line 563, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    b'\x16\x03\x01\x02'
