### ISSUE TITLE
Cannot authenticate Spotify

### ISSUE THREAD

**Issue by KE55ARD** [music-assistant/hass-music-assistant#2800]
### What version of Music Assistant has the issue?

2.1.4

### What version of the Home Assistant Integration have you got installed?

2024.8.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I cannot authenticate with Spotify. The Authenticate button does nothing but bring up a loading icon.

### How to reproduce

Click Authenticate button.

### Music Providers

Spotify

### Player Providers

N/A

### Full log output

It won't let me attach it for some reason, it's greyed out (MacOS).

### Additional information

I've been keeping an eye on the documentation recently for the Spotify setup process and noticed it change several times, most recently I noticed this line appeared:
"You can only configure the Spotify provider from a device which is on the same subnet as the MA server (and not via a VPN)"
I am on the same LAN, but I have a fear that when you say "same subnet" that might not actually be what you mean? I am on the same subnet, of actual real IP4 addresses, not NAT. Let me know if this makes a difference...

### What version of Home Assistant Core are your running

2024.8.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by marcelveldt** [comment]
Please update to 2.2.2

**Comment by KE55ARD** [comment]
Ahh I did check to see if there was one, but it's not showing up.

**Comment by OzGav** [comment]
@KE55ARD is this now resolved after updating?

**Comment by KE55ARD** [comment]
Nope not been able to update, not seeing anything newer than the v2.1.4 that I'm on.

**Comment by OzGav** [comment]
Well that is a HA or docker problem that you need to resolve

**Comment by KE55ARD** [comment]
Indeed, I have finally received the update after a HA core update and managed to authenticate again. Thanks!
