### ISSUE TITLE
Errors in log output, snapcast and spotify

### ISSUE THREAD

**Issue by nimbling** [music-assistant/hass-music-assistant#2802]
### What version of Music Assistant has the issue?

2.3.0b3

### What version of the Home Assistant Integration have you got installed?

2024.8.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Errors in log output, concerning snapcast and spotify? Python things?

### How to reproduce

Run Music Assistant, enable snapcast and spotify, have one snapcast satellite

### Music Providers

Spotify

### Player Providers

Snapcast

### Full log output

[d5369777_music_assistant_beta_2024-08-24T18-03-19.583Z.log](https://github.com/user-attachments/files/16737542/d5369777_music_assistant_beta_2024-08-24T18-03-19.583Z.log)

### Additional information

Hi MASS developer, I'm getting these log outputs, and it's generating lots of snapcast group entities (see screenshot) - and I don't know where to start troubleshooting this.

<img width="1050" alt="Screenshot 2024-08-24 at 20 04 48" src="https://github.com/user-attachments/assets/69f44df1-135b-4399-82a4-26f32b670fe4">

I generally assign fixed IP's to the devices on my network, I'm unsure if that is the cause?
Could someone perhaps point me in the right direction?
Much obliged 🙏

### What version of Home Assistant Core are your running

2024.8.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Those entities aren’t being created by MA. Look at the integration column.

**Comment by OzGav** [comment]
@SantiagoSotoC Can you have a quick look at the errors in the log snippet above?

**Comment by nimbling** [comment]
This is a part of the debug log from my snapcast client add-on. Does this help?

[home-assistant_snapcast_2024-08-25T09-14-14.136Z.log](https://github.com/user-attachments/files/16739590/home-assistant_snapcast_2024-08-25T09-14-14.136Z.log)

**Comment by nimbling** [comment]
<img width="671" alt="Screenshot 2024-08-25 at 12 05 41" src="https://github.com/user-attachments/assets/1f124399-6e4c-4f44-a487-a563084c401e">
I do hope this does not mean it has made over 5000 snapcast entries up til now 😅

**Comment by OzGav** [comment]
Again this does not seem to be a MA issue. Why do you have the Snapcast integration installed if you are using MA?

**Comment by nimbling** [comment]
MA’s snapcast did not give me audio output. The snapcast host seems to work
fine though!

**Comment by SantiagoSotoC** [comment]
No, it is asking you because you are using the snapcast integration for home assistant.
It doesn't even make sense to use that. 
Yes, thousands of entities are going to appear, that integration is for use without Music Assistant. The errors that appear there have nothing to do with music assistant.

**Comment by SantiagoSotoC** [comment]
I don't understand what your problem is, do you have a Raspberry pi where you run home assistant and mussic asistant ? 
Also you have a dac connected to that Raspberry pi and you can't get the audio out of the dac ?

**Comment by nimbling** [comment]
I'm sorry!
Yes, I have a raspberry pi 5 with a DAC, that runs HASS and MAS.
I also have a second raspberry 3b with a DAC that works as a snapcast satellite.

I have not been able to get the built in snapcast server to work yet. And since it had the option to "use existing snapcast server" I figured I'd give that a shot. Bu I'm happy to hear that that is not the intended use case :)

I'll reinstall MAS and see if I can get it to play to a snapcast setup that's just the MAS one and a satellite.

In the meantime, here's my latest log before I uninstalled MAS:
[music-assistant-2.log](https://github.com/user-attachments/files/16742058/music-assistant-2.log)

Thank you for your patience 🙏

**Comment by nimbling** [comment]
That setup works well, by the sound of it :)
Thanks for your patience! :)

**Comment by OzGav** [comment]
Can this be closed then?

**Comment by nimbling** [comment]
Yes please, thank you!
