### ISSUE TITLE
Snapcast and group error

### ISSUE THREAD

**Issue by boris19** [music-assistant/hass-music-assistant#2805]
[music-assistantss.log](https://github.com/user-attachments/files/16739106/music-assistantss.log)
### What version of Music Assistant has the issue?

2.3.0b3

### What version of the Home Assistant Integration have you got installed?

2024.8.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Weird behavior combined with Snapcast, when I try to play through a bundled group, every time I switch songs it will only play for 5-10 seconds and then stop. In universal group player this works, but after a long time it seems to click and the audio goes silent but in MA it seems to play. It writes me this error: 

`2024-08-25 06:48:02.224 ERROR (MainThread) [music_assistant] Error doing task: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/music.py", line 715, in mark_item_played
    await self.database.insert(
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/helpers/database.py", line 179, in insert
    await self.execute(sql_query, values)
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/helpers/database.py", line 225, in execute
    return await self._db.execute(query, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiosqlite/core.py", line 193, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
                                 ^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiosqlite/core.py", line 83, in _conn
    raise ValueError("no active connection")
ValueError: no active connection
2024-08-25 06:48:02.228 ERROR (MainThread) [music_assistant] Error doing task: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/music.py", line 715, in mark_item_played
    await self.database.insert(
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/helpers/database.py", line 179, in insert
    await self.execute(sql_query, values)
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/helpers/database.py", line 225, in execute
    return await self._db.execute(query, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiosqlite/core.py", line 193, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
                                 ^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiosqlite/core.py", line 83, in _conn
    raise ValueError("no active connection")
ValueError: no active connection`

### How to reproduce

Play music

### Music Providers

Spotify

### Player Providers

Snapcast

### What version of Home Assistant Core are your running

2024.8.2

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Windows

**Comment by OzGav** [comment]
What is a bundled group?

You haven’t ATTACHED (don’t paste) the full log

**Comment by boris19** [comment]
sorry, i dont know why. But Full log is on top of the first topic. I attach it here too. Thank you for your advice. 
[music-assistantss.log](https://github.com/user-attachments/files/16739638/music-assistantss.log)


bundle group:
![IMG_2078](https://github.com/user-attachments/assets/763b360b-cdae-4660-8edb-fa2d3cb88001)

**Comment by OzGav** [comment]
@SantiagoSotoC can you have a look at this one?

**Comment by marcelveldt** [comment]
Did you try to restart the server first ? Your log indicates some severe issues with the database. Maybe a simple restart helps

**Comment by boris19** [comment]
Yes a reboot always helps, but the error comes back repeatedly.

**Comment by boris19** [comment]
I will correct myself. Restarting Music Assistant doesn't help in some cases, but if in providers I put a reload on Snapcast it helps almost always.

**Comment by marcelveldt** [comment]
OK interesting. This is the first time I have seen this error.

**Comment by boris19** [comment]
What can I do to somehow clarify the problem ? Sometimes Snapcast has trouble changing the music source too. See log. 

`2024-08-26 09:00:52.128 INFO (MainThread) [snapcast.control.server] stream MusicAssistant--5072 not found, synchronize`

The music stops. At that point you also need to do a Snapcast reload.

**Comment by SantiagoSotoC** [comment]
> What can I do to somehow clarify the problem ? Sometimes Snapcast has trouble changing the music source too. See log. 
> 
> `2024-08-26 09:00:52.128 INFO (MainThread) [snapcast.control.server] stream MusicAssistant--5072 not found, synchronize`
> 
> The music stops. At that point you also need to do a Snapcast reload. 

That's not a bug, at least it doesn't say anything, it's just the library we use for snapcast that syncs that way. 
I still don't really know what is the cause of this.

**Comment by PablexXXXX** [comment]
I have a similar problem. I{m using filesystem remote share. The tracks plays for a couple of seconds then the music player info stop refreshing and appears to be idle.

**Comment by PablexXXXX** [comment]
Now trying updating the snapcast clients.

**Comment by PablexXXXX** [comment]
Still, snapclient player shows idle after a couple of seconds. The music keeps playing but the interface shows an inactive player.

**Comment by PablexXXXX** [comment]
Problem solved. I just run an update on the snapclient (Raspberry Pi) and restarted music assistant addon in home assistant. Everithing just fine now. THANKS A LOT FOR THIS BEATIFULL SOFTWARE

**Comment by SantiagoSotoC** [comment]
Test next beta, Marcel has make changes to the snapcast provider

**Comment by OzGav** [comment]
@boris19 please confirm this is fixed.

**Comment by boris19** [comment]
@OzGav thank you. Yes when is shuffle mode disabled, problem not repeat after 2 days.

**Comment by boris19** [comment]
I updated it last night so i will test more it today.

**Comment by boris19** [comment]
I have few more error. See log. 

[log2.log](https://github.com/user-attachments/files/16824726/log2.log)

**Comment by OzGav** [comment]
You have some problem with Spotify which is not related to the original problem here. We would like to confirm that the issue in your original report has been fixed.

**Comment by boris19** [comment]
solved with UGP.
