### ISSUE TITLE
WFAN audio stops, possibly related to commercial breaks.

### ISSUE THREAD

**Issue by dovy6** [music-assistant/hass-music-assistant#2810]
### What version of Music Assistant has the issue?

2.3.0b3

### What version of the Home Assistant Integration have you got installed?

2024.8.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

TuneIn radio WFAN stops playing. It seems to happen just before going to or returning from commercial, although it is possible that it's coincidental. The station is https://tunein.com/wfan660/

### How to reproduce

In Music Assistant, go to radio, select "WFAN Sports Radio 101.9 FM / 66AM New York," and play over any media player. After some time, usually when they cut to commercial, or when they return from commercial, audio just stops.

### Music Providers

TuneIn

### Player Providers

Snapcast media_players

### Full log output

[music-assistant.log](https://github.com/user-attachments/files/16741717/music-assistant.log)

### Additional information

I'm using pfsense with pfblockerng to block ads at DNS level, but I don't see any alerts for 10.1.1.12 (home assistant) nor for 10.1.75.20-22 (the satellite players)

### What version of Home Assistant Core are your running

2024.8.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by dovy6** [comment]
I should add. When playing on my laptop directly on the TuneIn website, I do not experience these audio drop outs mentioned above.

**Comment by marcelveldt** [comment]
Please test this again with 2.3.0 beta 8

**Comment by dovy6** [comment]
I updated and it still seems to be stopping. I'm restarti g home assistant
now I'll let you know of that fixes it

Thanks very much

**Comment by dovy6** [comment]
> Please test this again with 2.3.0 beta 8

Unfortunately does not seem to have fixed the problem. Listening to the Yankees game I had to keep restarting the feed every half inning as it would stop, sometimes when the game went to commercial and sometimes when it returned from commercials.

**Comment by marcelveldt** [comment]
Can you send me a link to the stream so I can test this myself ?

**Comment by dovy6** [comment]
Yes it's https://tunein.com/wfan660/ 
In the MA logs there's another stream link that includes my Lat and Lon as well as birthyear, so it seems that MA is getting a correctly encoded link.

**Comment by marcelveldt** [comment]
I have published beta17 with a special HLS streams handler to fix an issue with BBC streams but this might also fix your issue. Can you give it a try?

**Comment by OzGav** [comment]
@dovy6 please confirm if this has been fixed.

**Comment by dovy6** [comment]
I gave it a quick test this morning, seems to be working so far. I'm hoping
to give a longer test this afternoon in about 2 hours so so during the
Yankees game.

Thanks so much!

**Comment by OzGav** [comment]
Please close this if it is fixed

**Comment by dovy6** [comment]
Appears to be fixed, thank you guys so much. Had one drip out in a 9 inning game that could be random error or even a network blip. Thanks so much!

**Comment by dovy6** [comment]
Unfortunately this seems to have regressed with the most recent beta 2.3.0b26

**Comment by marcelveldt** [comment]
can you recheck with 2.3.0b34 ?

**Comment by dovy6** [comment]
I will asap but might not be able to until next week

**Comment by OzGav** [comment]
Please check with 2.3.2 or 2.4.0b3

**Comment by dovy6** [comment]
My apologies for net responding sooner. I'm currently on 2.3.0b34 and it
seems to be working fine!
Thanks and sorry again for the delay
Dovy
