### ISSUE TITLE
Home Assistant MediaPlayer (VLC Telnet) stop working

### ISSUE THREAD

**Issue by lor74** [music-assistant/hass-music-assistant#2813]
### What version of Music Assistant has the issue?

2.3.0.b6

### What version of the Home Assistant Integration have you got installed?

2024.8.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I use an Homa Assistant MediaPlayer (VLC - [https://github.com/home-assistant/addons/tree/master/vlc](url))  for stream music to DAC (topping E30). Now the streaming stops working with this error:

`File "/usr/local/lib/python3.12/site-packages/aiohttp/web_response.py", line 452, in _prepare_headers
    raise RuntimeError(
RuntimeError: Using chunked encoding is forbidden for HTTP/1.0`

It's somthing I guess similar to this issue [https://github.com/music-assistant/hass-music-assistant/issues/2809](url)

I hope you can apply a similr fix for this old player.

Thanks in advance.

### How to reproduce

Select the palyer 

### Music Providers

all music providers

### Player Providers

Home Assistant MediaPlayer

### Full log output

[ma.log](https://github.com/user-attachments/files/16747632/ma.log)

### What version of Home Assistant Core are your running

2024.8.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Look in the settings for the player and see if you have these options. If so try each one
![image](https://github.com/user-attachments/assets/a2998c8b-baef-46f4-9762-283ee88c6718)

**Comment by lor74** [comment]
Hi OzGav, thanks for your suggestion. It works with Profile 2 - no content length
