### ISSUE TITLE
Music Assistant stops showing a "now playing" bit.

### ISSUE THREAD

**Issue by nimbling** [music-assistant/hass-music-assistant#2817]
### What version of Music Assistant has the issue?

2.3.0b6

### What version of the Home Assistant Integration have you got installed?

2024.8.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

After playing a few tracks, when I open a new tab Music Assistant Tab, it does not show a "now playing" anymore, or it shows just the first track of the playlist. In this case it happened with the built-in "all favorites" playlist, filled with Spotify tracks.

I am listening to a MAS playlist as we speak while MAS is not showing the current track being played, just the first one of the queue when I started playing this list.

### How to reproduce

While playing a playlist, close MAS tab, reopen it later.

### Music Providers

Spotify

### Player Providers

Snapcast

### Full log output

[music-assistant.log](https://github.com/user-attachments/files/16749328/music-assistant.log)

### Additional information

It might have to do with my attempt to play a TTS message, but I'm unsure, as I could just resume the playlist afterwards, and it showed the "now playing" again when I resumed, but lost it about an hour after that.

### What version of Home Assistant Core are your running

2024.8.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by nimbling** [comment]
Worth noting, MAS also does not show track progress in this state.

When I skip to the next song, it will correctly go to the next one from the queue, but still not show the track progress.

For some reason, after two skips, it's now showing the "now playing" again. I'll check the log :) - ooh, after I typed this it disappeared again. Bummer.

[music-assistant (1).log](https://github.com/user-attachments/files/16749631/music-assistant.1.log)

**Comment by nimbling** [comment]
I do get a bunch of these:

```
2024-08-26 17:56:48.315 ERROR (MainThread) [music_assistant.theaudiodb] Failed to retrieve artist-mb.php
2024-08-26 17:57:18.207 ERROR (MainThread) [music_assistant.theaudiodb] Failed to retrieve artist-mb.php
2024-08-26 17:58:18.314 ERROR (MainThread) [music_assistant.theaudiodb] Failed to retrieve artist-mb.php
2024-08-26 17:59:18.278 ERROR (MainThread) [music_assistant.theaudiodb] Failed to retrieve artist-mb.php
2024-08-26 17:59:48.318 ERROR (MainThread) [music_assistant.theaudiodb] Failed to retrieve artist-mb.php
2024-08-26 18:00:18.269 ERROR (MainThread) [music_assistant.theaudiodb] Failed to retrieve artist-mb.php
```

**Comment by OzGav** [comment]
Sorry I am not understanding what you mean by 

> it's now showing the "now playing" again.

Maybe a screenshot will help?

**Comment by nimbling** [comment]
The part circled in green will sometimes not show at all, while the music keeps playing.
The play-bar below, showing the song and the controls, sometimes does not update the time bar (it will stay at zero) - and not update to the currently playing song.

<img width="1405" alt="Screenshot 2024-08-27 at 01 39 24" src="https://github.com/user-attachments/assets/d8b01636-f3cf-4e36-913a-301c03574efd">

**Comment by OzGav** [comment]
What browser and device are you using? If it’s Safari on a mobile device then try Chrome on a PC/Mac

**Comment by nimbling** [comment]
This is safari on OSX.

I'll try switching to a chromium based browser, that might help?

**Comment by OzGav** [comment]
Yes. We have multiple reports of problems with Safari and Firefox which is why the troubleshooting page says to try others.

**Comment by nimbling** [comment]
I promise I actually read most of it when I was asked to confirm so with the checkbox before adding issues here 🙏 

But the "switch browser" bit escaped me. For those like me that missed it, it's here: [https://music-assistant.io/faq/troubleshooting/](https://music-assistant.io/faq/troubleshooting/)

I'll try another browser tomorrow.

Honest question, what level of "issue reports" is the team currently able to deal with? All errors in the log, or just starting at a certain severity?

I'm super happy MAS is where it is right now, big thanks for developing/maintaining this the way you do 💪

**Comment by OzGav** [comment]
Errors will most likely warrant an issue report. Warning not so much. If you are unsure then ask on Discord before hand.

**Comment by OzGav** [comment]
@nimbling how did you go with a different browser?

**Comment by nimbling** [comment]
My apologies, again. I commented on another issue thinking it was this one. I used brave and it worked, but oddly, it also seems to work on Safari now. I was listening to several hour long sets on soundcloud and it's just humming along, displaying this panel :)

I'd consider this closed?  🙏
