### ISSUE TITLE
MA Web Player Not Updating New Song Info

### ISSUE THREAD

**Issue by sdoowo200leldls** [music-assistant/hass-music-assistant#2822]
### What version of Music Assistant has the issue?

2.3.0b7

### What version of the Home Assistant Integration have you got installed?

2024.8.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

If multiple songs are queued and a song finishes, the information for the next song doesn't update in the music assistant player on the MA web interface. In the screenshot below, Florence + the Machine - Mermaids is actively playing but it still shows UPSAHL - Drugs playing in the web player and the runtime exceeds the song's duration.

![image](https://github.com/user-attachments/assets/fc272fd0-b366-4278-93ab-499fe976aa55)

### How to reproduce

Not sure how to reproduce as this is constant for me.

### Music Providers

Tidal

### Player Providers

Sonos

### Full log output

[MA_Log_20240826.txt](https://github.com/user-attachments/files/16754148/MA_Log_20240826.txt)

### What version of Home Assistant Core are your running

2024.8.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
You don’t say what you have tried to confirm this is limited to Sonos.

**Comment by sdoowo200leldls** [comment]
I only have access to Sonos speakers via Tidal so I'm not sure if this is limited to either.

**Comment by OzGav** [comment]
You can try the Snapcast provider.

**Comment by marcelveldt** [comment]
Is this while playing to a single sonos speaker or to a group ?

**Comment by marcelveldt** [comment]
Its working fine here on my end. Is this using the new Sonos (S2) provider or with the Sonos S1 provider ?
Also I'd like to know if the Sonos app does show the correct track and what kind of sonos speaker this is

**Comment by sdoowo200leldls** [comment]
This is using the new Sonos S2 provider. I'm playing to a group of 4 speakers where a stereo pair of Sonos Play 1s are the coordinator. The Sonos app is showing the correct song playing.

**Comment by sdoowo200leldls** [comment]
Here's a side by side of the Sonos app and the MA player with the queue displayed. I did notice this issue started occuring when updating to the beta version which had the new Sonos S2 provider.

![signal-2024-08-27-07-48-41-557](https://github.com/user-attachments/assets/3455b874-d2a2-4b76-bf75-431c27c056ba)

**Comment by sdoowo200leldls** [comment]
I've confirmed this does not occur when I use slimproto (squeezebox) as a player provider. It appears to be Sonos related.

**Comment by sdoowo200leldls** [comment]
It is fixed! Thank you very much!

**Comment by sdoowo200leldls** [comment]
It is fixed on b16! Thank you very much!
