### ISSUE TITLE
Stable conflicts with Beta and cannot start.

### ISSUE THREAD

**Issue by stevegroom** [music-assistant/hass-music-assistant#2826]
### What version of Music Assistant has the issue?

2.2.2

### What version of the Home Assistant Integration have you got installed?

not installed.

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I have been running MA stable and beta in parallel (alternating). After updating to beta 8, I found that I can no longer start the stable version. 

I get a pop-up after pressing start in the add-on panel

Failed to start add-on
Image ghcr.io/music-assistant/server:2.2.2 does not exist for addon_d5369777_music_assistant

### How to reproduce

install current beta and current stable versions. 

### Music Providers

Plex, Apple Music

### Player Providers

SONOS

### Full log output

Nothing in the log today

### What version of Home Assistant Core are your running

2024.8.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
This is a HA problem. I have seen it myself and it self corrects or is also corrected after an update.
