### ISSUE TITLE
Changing the order of items in a playlist doesn't work.

### ISSUE THREAD

**Issue by JulesGrd** [music-assistant/hass-music-assistant#2831]
### What version of Music Assistant has the issue?

2.3.0b8

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When you change the order of a playlist, the display correctly shows the new order, but when you press play, the playback happens in the default order.

It's as if the frontend isn't sending the sort change request to the backend.

### How to reproduce

Select a playlist.
Change the sort order (for example, to descending by position).
Press play.

### Music Providers

Deezer and File System Provider

### Player Providers

Slimproto (Music Assistant Companion)

### Full log output

[music-assistant-2.log](https://github.com/user-attachments/files/16789690/music-assistant-2.log)

### Additional information

Installation with Docker

### What version of Home Assistant Core are your running

docker

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by marcelveldt** [comment]
The sort order for the playlist in the UI has nothing to do with how its played back. If you really want to play a playlist in a specific order, then you could try to select all tracks (CTRL-A will work) and then play.

Maybe you are looking for a way to resort your playlist itself ?

**Comment by JulesGrd** [comment]
It's a bit strange how it works, but it does the job, thank you!

The goal was to play my Deezer favorites playlist in the order of the most recently added favorites first (those added recently) and ending with the oldest favorites (the first ones added) (just like in the Deezer app).

(For me, Ctrl-A works for playlists but not for albums).

**Comment by OzGav** [comment]
@JulesGrd The problem with CTRL-A has been added to the backlog to be fixed. Thanks for finding it.
