### ISSUE TITLE
MASS showing incorrect item playing on Google cast device if started playing from outside MASS

### ISSUE THREAD

**Issue by tbgoose** [music-assistant/hass-music-assistant#2836]
### What version of Music Assistant has the issue?

2.2.2

### What version of the Home Assistant Integration have you got installed?

2024.8.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I am casting a story from Audiobookshelf to my Google cast device. The Google Cast integration correctly displays what is playing, but the MA one shows a random song.

I am pause and play using the MA one, so it just seems to incorrectly label the item, likely as it doesn't know what it is as it's not from within MA.

I presume this is a known issue, but I couldn't find any talk of it. Probably searching for wrong things.

Just wondering what I can do about this, if anything?

![Screenshot_20240830-093132~2](https://github.com/user-attachments/assets/effd4e5e-34c5-4827-93bc-660f85b1820f)
![Screenshot_20240830-093523~2](https://github.com/user-attachments/assets/d5d7b900-ba64-49bf-bef6-768a9cfa795c)
![Screenshot_20240830-093535](https://github.com/user-attachments/assets/77035d8e-c5b5-43da-ae57-0ee3b149ac37)
![Screenshot_20240830-093141](https://github.com/user-attachments/assets/d415fd13-47e5-4bf4-ad05-97273e0ea251)

### How to reproduce

Play media from Audiobookshelf of a Google cast device, check what is playing in MA

### Music Providers

Native MA providers don't have this issue

### Player Providers

Google Cast (only devices I have)

### What version of Home Assistant Core are your running

2024.8.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
No you can’t do anything about this. MA has no visibility of third party applications streaming to supported players at this time. You will notice the same thing with Airplay.

**Comment by OzGav** [comment]
P.S. nice post but if you want to save some time you can ask on Discord about this sort of thing

**Comment by tbgoose** [comment]
Ok cheers. Will head to discord to check if anyone has a solution as I can use visibility filters to only show MA media based players when x condition is true, and if false show standard / google cast ones... Or I live with having two media players showing (no biggie really). 

Just a bit odd it is showing a random song? I would have thought it would have would blank or something.
