### ISSUE TITLE
Update issue beta11

### ISSUE THREAD

**Issue by boris19** [music-assistant/hass-music-assistant#2837]
### What version of Music Assistant has the issue?

2.3.0b11

### What version of the Home Assistant Integration have you got installed?

2024.8.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

when I installed beta11, the providers could not be started, they wrote an environment error. Rolled back to beta8. 

### How to reproduce

Update to beta11. 

### Music Providers

Spotify

### Player Providers

Snapcast

### Full log output

[upeatelog.log](https://github.com/user-attachments/files/16811717/upeatelog.log)

### What version of Home Assistant Core are your running

2024.8.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Windows

**Comment by OzGav** [comment]
Beta 12 is now aviailable
