### ISSUE TITLE
2.3.0b11: Unable to locate RAOP Play binary for linux/x86_64

### ISSUE THREAD

**Issue by ministryofsillywalks** [music-assistant/hass-music-assistant#2838]
### What version of Music Assistant has the issue?

2.3.0b11

### What version of the Home Assistant Integration have you got installed?

2024.8.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

After upgrading from b10 to b11 airplay won't load with the following error:
`Unable to locate RAOP Play binary for linux/x86_64`
Running on a NUC with HomeAssistantOS and MA as an addon

### How to reproduce

Upgrade to b11

### Music Providers

Local & Spotify

### Player Providers

Airplay

### Full log output

[raop.log](https://github.com/user-attachments/files/16812305/raop.log)

### What version of Home Assistant Core are your running

2024.8.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Is being fixed now

**Comment by ministryofsillywalks** [comment]
Not sure if it was intended as a fix, but b12 is still broken for me.

**Comment by OzGav** [comment]
12 fixed something but not that. Wait for 13

**Comment by OzGav** [comment]
Fixed in beta 15
