### ISSUE TITLE
SMB mount dailed

### ISSUE THREAD

**Issue by lexam79** [music-assistant/hass-music-assistant#2842]
### What version of Music Assistant has the issue?

2.3.0b15

### What version of the Home Assistant Integration have you got installed?

2024.8.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

After upgrading to 2.3.0b15, my "Filesystem (remote share)" music provider fails to start with the error:
2024-08-30 15:19:25.372 WARNING (MainThread) [music_assistant] Error loading provider(instance) Filesystem (remote share): Connection failed for the given details: SMB mount failed with error: mount: mounting //titan.lexam.internal/Media/Music-tagged on /tmp/filesystem_smb--cLdtRifQ failed: Permission denied
 (will be retried later)
 
 If I downgrade to 2.3.0b8, it works fine.

### How to reproduce

Just upgrade to 2.3.0b15 (it also happened in 2.3.0b12 and 13 IIRC)

### Music Providers

Filesystem (remote share)

### Player Providers

N/A

### Full log output

[music-assistant.log](https://github.com/user-attachments/files/16816922/music-assistant.log)

### What version of Home Assistant Core are your running

2024.8.3

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
This is working fine here on beta 15. There have been library changes so settings may need to be adjusted. Check the server settings under advanced for the local provider. Recheck your login credentials

**Comment by lexam79** [comment]
It's fixed in 2.3.0b16. Closing, thanks!
