### ISSUE TITLE
Volume change by Scrolling 

### ISSUE THREAD

**Issue by hosh0815** [music-assistant/hass-music-assistant#2846]
### What version of Music Assistant has the issue?

2.2.2

### What version of the Home Assistant Integration have you got installed?

2024.8.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

when open the grouped Player, while adding / removing and scrolling thru, the volume of the speaker where the mouse ist changes quickly to max or min... is there a possibility to set an option how to change volume eg. Clicking oder hold by mouse or somehow... 

### How to reproduce

scoll up or down when grouping some speaker is opend

### Music Providers

apple music

### Player Providers

sonos
<img width="380" alt="SCR-20240831-mxds" src="https://github.com/user-attachments/assets/2ba6731f-df31-47d5-819f-c9bb14225aa0">

### What version of Home Assistant Core are your running

2024.8.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
We will discuss this. Your issue is another person's feature

**Comment by OzGav** [comment]
This will be looked at when resources allow.

**Comment by OzGav** [comment]
I believe the latest changes to the UI that are in beta have fixed this. Please confirm

**Comment by hosh0815** [comment]
![image](https://github.com/user-attachments/assets/dfc3b2f5-335c-4fd1-8475-79e9617207b4)

Green works for scrolling up and down, red changes volume

**Comment by OzGav** [comment]
I just tried this and I am not seeing this on my iPad. If you put your finger anywhere except the volume slider and slide up and down that moves the player list up and down. If you put your finger down on the volume slider then the volume jumps to that value. Are you seeing something different to that? I tried with Safari and the IOS HA APP

**Comment by hosh0815** [comment]
Yes, that's the behavior.

**Comment by OzGav** [comment]
OK then I think that is reasonable and expected behaviour. If you agree I will close this.

**Comment by marcelveldt** [comment]
I get the point - but this is unsolvable - on the one end you want sliders for volume control and on the other hand it needs to be scrollable. You just need to be careful to not touch the slider for the volume when you want to drag down.

Most probably some frontend genius is able to fix this with some delays or whatever but that is not me.
