### ISSUE TITLE
 Squeezelite - Treating channel names in subscriptions as opaque 

### ISSUE THREAD

**Issue by ohuc** [music-assistant/hass-music-assistant#2847]
### What version of Music Assistant has the issue?

2.1.4

### What version of the Home Assistant Integration have you got installed?

2024.8.3

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

In the Squeeze lite addon in Music assistant the type of events to be sent (and whether to send events at all) by interpreting the channel names the client subscribed for instead of looking at the subscription itself. In particular, MA seem to expect the player ID as part of the channel name in its original MAC address form (11:22:33:44:55:66), however colons are not allowed in channel names as per [the cometd spec](https://github.com/cometd/cometd-documentation/blob/master/src/main/asciidoc/bayeux.adoc#user-content-channels) (mind : not being part of mark).

### How to reproduce

-

### Music Providers

-

### Player Providers

Sqeezelite addon

### What version of Home Assistant Core are your running

2.1.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Sorry I don’t understand what the issue is?
