### ISSUE TITLE
No dashboard in HA sidebar

### ISSUE THREAD

**Issue by willthong** [music-assistant/hass-music-assistant#2849]
### What version of Music Assistant has the issue?

2.3.0b7

### What version of the Home Assistant Integration have you got installed?

2024.8.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

No dashboard in HA sidebar. When adding dashboard manually (as webpage) I get:

![Screenshot_2024-08-31-16-18-43-659_io homeassistant companion android-edit](https://github.com/user-attachments/assets/ffe2545c-8c0d-488b-82c5-af6fc8f9baf0)

### How to reproduce

1. Set up HA with external HTTPS address
2. Set up MA on local network with HTTP address
3. No sidebar appears automatically (presumably because it wouldn't work without HTTPS)

My HA container is externally accessible so I don't want to give up HTTPS. Is there a workaround or do I just enable HTTPS on my MA container? Thanks! 

### Music Providers

N/A

### Player Providers

N/A

### What version of Home Assistant Core are your running

2024.8.3

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
https://music-assistant.io/faq/how-to/#run-ma-when-i-have-ssl-setup-on-my-internal-network
