### ISSUE TITLE
V1.1.21/22: can't close queue menu after clearing the queue

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#285]
This is not a easy to reproduce issue, first time encountered in v1.1.21, but also seen in the latest v1.1.22.
What happened a few times is that I clear all queued items. After that I can't close the queue menu. Restarting the iOS companion app solves it.

**Comment by marcelveldt** [comment]
I can't reproduce this one on the desktop browser so this might actually be a browser specific issue (iOS Safari embedded by the companion app)

**Comment by erkr** [comment]
I also don't know (yet) how to reproduce. Most of my testing is using the companion app

**Comment by marcelveldt** [comment]
should be fixed in beta 6
