### ISSUE TITLE
The TTS volume settings are not working.

### ISSUE THREAD

**Issue by senderbell** [music-assistant/hass-music-assistant#2851]
### What version of Music Assistant has the issue?

2.3.0b17

### What version of the Home Assistant Integration have you got installed?

2024.8.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I have set the absolute volume in the TTS settings. However, this setting has stopped working. If the current speaker volume is 0, TTS is played at a volume of 0. Previously, this value was overridden by the value set in the "notification configuration" section. After downgrade to version 2.2.0b6, it works fine.

### How to reproduce

Configure absolute volume in TTS settings, set speaker volume to 0 and play TTS.

### Music Providers

TTS

### Player Providers

chromecast group speakers

### What version of Home Assistant Core are your running

2024.7.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
I just tried this with single players and it worked fine. Can you also check if it is just the group that has the problem by trying single players. The troubleshooting page does ask for you to explain what you have tried and what does work so please do this in all reports.

**Comment by senderbell** [comment]
I have a problem with my speaker group. I just reinstalled the latest version and tried it with a single speaker, and everything works well. However, with the group, it varies; sometimes it doesn't work at all, and other times it doesn't work on all the speakers. This might be related to the still unresolved issue with the new Google software for Chromecast speakers, but I can't confirm that definitively. In any case, everything works fine on 2.2.0b6 version.
From this, I conclude that something has changed in Music Assistant in the meantime.

**Comment by OzGav** [comment]
So this is only for a chromecast group that you have created in the Google Home app?

**Comment by senderbell** [comment]
Yes. I have always had a group of speakers created in the Google Home app.

**Comment by OzGav** [comment]
Just looking at this one again and I can't recreate it as you have described. If I set one speaker to zero it gets set to the minimum specified in the settings. Can you show the announcement settings you have for the Google Cast group. However, I do note that if I set the strategy for relative or absolute volume then I only get the minimum level set.

**Comment by senderbell** [comment]
My settings are as follows:
Strategy = absolute volume,
Notification volume = 40,
Minimum volume = 30,
Maximum volume = 50.
I noticed that:
When TTS playback starts, the volume increases to 40 for half a second, then decreases to 30. The TTS is heard, the volume increases again to 40 for half a second, and then returns to the previous settings.

**Comment by OzGav** [comment]
The last thing you said is probably of interest. This will get looked at in due course.

**Comment by OzGav** [comment]
Actually what I am seeing is that when TTS is sent to the group the group settings are not used but unstead each individual player's settings are. Can you see if this is what your problem is or still something different?

**Comment by senderbell** [comment]
Yes, that's true. Each speaker must have the same settings as the group

**Comment by OzGav** [comment]
Ok then we know this problem and it is being worked on.

**Comment by OzGav** [comment]
In the next beta update where the group functionality has been rewritten you will find groups not long have their own announcement settings except for the pre-announcement sound. Individual player settings will now be used.

**Comment by OzGav** [comment]
Beta 30 has been released.
