### ISSUE TITLE
Playing to a Squeezelite Group Player stops MA from tracking song progress

### ISSUE THREAD

**Issue by Alundran** [music-assistant/hass-music-assistant#2852]
### What version of Music Assistant has the issue?

2.3.0b17

### What version of the Home Assistant Integration have you got installed?

2024.8.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

In the latest beta, if you play media to a Squeezelite Group, the media plays but the progress tracking of the tracks doesn't work. MA will show the first song in the MA interface but doesn't keep track of the progress of the song. When the next song plays, it's not updated in MA. Turning the group off then on again, MA updates with the current song that was in the queue before turning the group off.

### How to reproduce

1. Create a Squeezelite Player Group
2. Play a playlist (I'm using Spotify)
3. Notice that MA will update with the first song in the queue but does not keep track of the playing time
4. Wait until the next song. When the next song starts, see that MA doesn't update
5. Look at the players, see that the group is stuck in 'Idle' instead of 'Playing;
6. Look at the top page in MA home page, notice that it doesn't show now playing

If you play to a single player/speaker, everything works as expected.

### Music Providers

Spotify

### Player Providers

Squeezelite Group

### Full log output

[music-assistant.log](https://github.com/user-attachments/files/16828680/music-assistant.log)

### What version of Home Assistant Core are your running

2024.8.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Please detail what does work

**Comment by Alundran** [comment]
@OzGav Sorry can you clarify what you're looking for? It's pretty easy to dupe, you just don't see any tracking of the songs playing to a slimproto group in the MA interface. Playing to a single slimproto player however does track the song progress.

When I play a song to a slimproto group, it'll show in MA but the time doesn't progress and the group player remains as 'Idle' instead of 'playing'. When the next song comes on, again MA doesn't show it yet the song is playing. If you turn off the group then turn it back on, the song that was playing now shows but we are then stuck again in the same loop.

**Comment by OzGav** [comment]
But we need to know if it is just a slimproto issue or wider. Hence why we want to know what does work. If you can't do anything else our troubleshooting page explains that you just need to make that clear.

**Comment by Alundran** [comment]
Understood. I don't use any other players other than Slimproto so unable to test any others. All I can say is that playing to an individual player seems to track the song fine but playing to a slimproto group doesn't.

**Comment by Alundran** [comment]
Restored to beta 8 and it occurs there too. I'll try restoring further back to confirm when it last worked.

**Comment by Alundran** [comment]
Doesn't occur in beta 6 so seems since beta 7 the issue started.

**Comment by Alundran** [comment]
Just to note, upgraded to beta 21 and still an issue on that version.

**Comment by bennnnnnnn** [comment]
Noticing same issue here. Working in 2.2.2, broken since 2.2.3.
I'm seeing "[music_assistant.server.providers.slimproto.multi_client_stream] No clients connected, stopping stream" in the logs right after starting playback

**Comment by fibergm** [comment]
Hi @Alundran.
I have the same problem but with a local music provider. I have basicly the same setup as you minus the Spotify.
I have the added issue of not being able to fully pause a song. If I click on pause the song just resets to the beginning and then continues playing .
Do you have the same problem?

**Comment by Bottesford** [comment]
I am also experiencing the same problems with a group of two slimproto players (2 x Raspberry Pi). 
I cannot pause and can only start play again and the UI rarely shows the right song playing even less the position within the track.
No errors in the log during the time I was playing.

**Comment by OzGav** [comment]
This has been fixed in upcoming beta group changes.

**Comment by OzGav** [comment]
Beta 30 has been released.
