### ISSUE TITLE
Sound normalization issues when playing to a Squeezelite Group

### ISSUE THREAD

**Issue by Alundran** [music-assistant/hass-music-assistant#2853]
### What version of Music Assistant has the issue?

2.3.0b17

### What version of the Home Assistant Integration have you got installed?

2024.8.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When playing media (I use Spotify) to a Squeezelite Player Group, you will often hear the volume 'jump' up for parts of a song then go back to normal. This happens for the previous/current and next song in the queue and is often quite random when it happens. Only noticed this on the recent beta and only when playing to a group vs individual player.

### How to reproduce

1. Start playing a song/playlist to a Squeezelite Group
2. Observe through the song you will hear some parts vastly increase in volume and then return to normal

See attached for some recordings.
[MA Loudness.m4a.zip](https://github.com/user-attachments/files/16833802/MA.Loudness.m4a.zip)
[MA Loudness 2.m4a.zip](https://github.com/user-attachments/files/16833925/MA.Loudness.2.m4a.zip)

- MA Loudness -> 3 second mark and 13 second mark
- MA Loudness 2 -> 7 second mark and 14 second mark

### Music Providers

Spotify

### Player Providers

Slimproto Group

### Full log output

[music-assistant.log](https://github.com/user-attachments/files/16833764/music-assistant.log)

### What version of Home Assistant Core are your running

2024.8.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by Alundran** [comment]
I don't use any other players other than Slimproto so unable to confirm if it happens outside of that. The issue only seems to happen when using a Slimproto group vs individual players from what I've experienced.

**Comment by Alundran** [comment]
Restored to beta 8 and it doesn't appear to be happening on that version.

**Comment by OzGav** [comment]
Try with beta 21 as there have been changes to volume normalisation

**Comment by Alundran** [comment]
It seems to be resolved. I had to revert due to the other issue (#2852) but from the few songs I played it seemed it was back to normal so I think it's good now.
