### ISSUE TITLE
MA unable to track progress of snapcast client playback

### ISSUE THREAD

**Issue by pantherale0** [music-assistant/hass-music-assistant#2854]
### What version of Music Assistant has the issue?

2.2.2

### What version of the Home Assistant Integration have you got installed?

2024.8.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

It seems that Music Assistant is unable to track playback status of snapcast players despite the actual playback being absolutely fine. As soon as a track starts playing after 1-2s the player in MA goes to "paused" and progress/playlist position is no longer updated.

### How to reproduce

1. Setup snapcast client on an Android device? (maybe, I only really use old phones as players)
1. Enable crossfade on player in MA
1. Setup Navidrome (or similar subsonic compatible server) in MA with default settings
1. Start playing a album

### Music Providers

Open Subsonic Media Server Library (Navidrome)

### Player Providers

Snapcast (crossfade enabled)

### Full log output

[music-assistant.log](https://github.com/user-attachments/files/16834871/music-assistant.log)

### What version of Home Assistant Core are your running

2024.8.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
I can't recreate this but I don't use Navidrome. Can you try with a radio station?

**Comment by OzGav** [comment]
Also if you can try the beta that would also be useful as updates have been made to Snapcast

**Comment by CaldeiraG** [comment]
I can reproduce this, Plex as the source, desktop Firefox 129.0.2. Logs don't seem to have anything. 

Also the snapcast client running on the browser suddenly stops and returns a warning on the console but nothing on logs.

I'm not sure how you can apply the beta version?

**Comment by pantherale0** [comment]
> Also if you can try the beta that would also be useful as updates have been made to Snapcast

I was running beta, however had to move away as had some stability issues where I couldn't get anything to play at all.

I will try a radio station to test.

**Comment by OzGav** [comment]
Additionally, you have ticked the box saying you have read the troubleshooting page but you have not supplied all of the required information particularly what does work?
