### ISSUE TITLE
playback timeline freeze

### ISSUE THREAD

**Issue by boris19** [music-assistant/hass-music-assistant#2858]
### What version of Music Assistant has the issue?

2.3.0b17

### What version of the Home Assistant Integration have you got installed?

2024.8.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

The time line sometimes seems to freeze. See picture. Tracks change, but time continues. 
![IMG_2129](https://github.com/user-attachments/assets/f1058ef7-7457-440b-a6a6-8b2cc8ee1a42)

### How to reproduce

Timeline freeze.

### Music Providers

Spotify 

### Player Providers

Snapcast

### Full log output

[music-assistant.log](https://github.com/user-attachments/files/16839365/music-assistant.log)

### What version of Home Assistant Core are your running

2024.8.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Windows

**Comment by OzGav** [comment]
You have ticked the box saying you have read the troubleshooting page but you have not supplied the required information. Additionally, what you have written in the how to reproduce section is not helpful.

**Comment by boris19** [comment]
I apologize for not providing these details earlier. During long playback from a single playlist (approximately after 3-4 hours), I noticed an issue in MUSIC Assistant. As shown in the attached image, the timeline does not display the actual playback time of the song but instead shows the cumulative playback time (for example, 2 hours or more), as if the timeline didn’t move to the next song.

This issue can be temporarily resolved by restarting the playlist. However, I’m not sure if this is related to Spotify, Snapcast, or MUSIC Assistant. Currently, I am trying Deezer because Spotify was experiencing other issues. I couldn’t determine where the problem might be from the logs.

I hope this information helps in resolving the issue.

Thank you for your assistance and time.

**Comment by OzGav** [comment]
What other player providers do you have?

**Comment by boris19** [comment]
Snapcast only

**Comment by OzGav** [comment]
@SantiagoSotoC

**Comment by boris19** [comment]
I wasnt comf with deezer so i changed it for YT music. Issue not repeat after day today. I don't know if this is related to this error #2858.

**Comment by marcelveldt** [comment]
please test if this is fixed in 2.3.0b18

**Comment by OzGav** [comment]
This will be closed soon assuming fixed
