### ISSUE TITLE
Spotify error

### ISSUE THREAD

**Issue by boris19** [music-assistant/hass-music-assistant#2860]
### What version of Music Assistant has the issue?

2.3.0b17

### What version of the Home Assistant Integration have you got installed?

2024.8.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

After this error stop play song in playlist:

`2024-09-02 18:20:17.365 ERROR (MainThread) [music_assistant.streams.media_stream] Failed to stream spotify://track:1qeV7JbH1rv3ygF6AhZ5x3 - error: 1
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/helpers/audio.py", line 192, in _feed_stdin
    async for chunk in self.audio_input:
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/providers/spotify/__init__.py", line 600, in get_audio_stream
    raise AudioError(
music_assistant.common.models.errors.AudioError: Failed to stream spotify://track:1qeV7JbH1rv3ygF6AhZ5x3 - error: 1`

### How to reproduce

Playing songs. 

### Music Providers

Spotify

### Player Providers

Snapcast

### Full log output

[music-assistant (1).log](https://github.com/user-attachments/files/16839842/music-assistant.1.log)

### What version of Home Assistant Core are your running

2024.8.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Windows

**Comment by OzGav** [comment]
Yes I have seen this.

**Comment by marcelveldt** [comment]
please test if this is fixed in 2.3.0b18

**Comment by boris19** [comment]
b19 same issue.

**Comment by boris19** [comment]
I simulated it in a way that I pressed 3-4 times in a row the next song from the playlist on Spotify. YT MUSIC is fine. 

[music-assistantb19.log](https://github.com/user-attachments/files/16876072/music-assistantb19.log)

**Comment by marcelveldt** [comment]
This is a snapcast issue (your log is full of issues with snapcast!) - not spotify

**Comment by boris19** [comment]
Im running snapserver in MA only.

**Comment by boris19** [comment]
I found this log today while playing. Yes it looks like two Snapcast servers are running. But in reality only one is running in MA. 

`2024-09-05 08:50:44.359 WARNING (MainThread) [music_assistant.snapcast] {'code': -32603, 'data': "bind: Address in use [system:98 at /usr/include/boost/asio/detail/reactive_socket_service.hpp:161 in function 'bind']", 'message': 'Internal error'}`

**Comment by boris19** [comment]
MA puts an extreme load on the CPU and RAM over time. 
![IMG_2151](https://github.com/user-attachments/assets/65a5c8b3-610b-44a7-9550-93729c2163e5)

**Comment by nikito** [comment]
I'm also seeing this without snapcast, just using the Chromecast player provider.

**Comment by OzGav** [comment]
> I found this log today while playing. Yes it looks like two Snapcast servers are running. But in reality only one is running in MA.
> 
Something else on your network is on this address then. You need to resolve that first.

**Comment by boris19** [comment]
Combination of MA version 2.3.0b17 and YT music and Snapcast i have log without any issue and without put load on CPU and RAM after 9hours continuous playback. I will send full log later after end of day in building. 

![IMG_2170](https://github.com/user-attachments/assets/4f7bb67c-6e81-487c-8c92-cca296683aec)

**Comment by boris19** [comment]
I forgot to mention that I completely deleted Spotify from the providers, before that I only had it disabled.

**Comment by JasperTheMinecraftDev** [comment]
Hey, I have this issue too. Only Chromecast provider. 
Logs:
2024-09-06 18:24:04.293 ERROR (MainThread) [music_assistant.streams.media_stream] Failed to stream spotify://track:0SWgf5CW30gZB9zlB8E6V - error: 1
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/helpers/audio.py", line 192, in _feed_stdin
    async for chunk in self.audio_input:
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/providers/spotify/__init__.py", line 601, in get_audio_stream
    raise AudioError(
music_assistant.common.models.errors.AudioError: Failed to stream spotify://track:0SWgf5CW30gZBzZlB8E6V - error: 1
2024-09-06 18:24:09.829 ERROR (MainThread) [music_assistant.streams.media_stream] Failed to stream spotify://track:0AIcr2wW0FiHkNS82AwLE9 - error: None
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/helpers/audio.py", line 192, in _feed_stdin
    async for chunk in self.audio_input:
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/providers/spotify/__init__.py", line 601, in get_audio_stream
    raise AudioError(
music_assistant.common.models.errors.AudioError: Failed to stream spotify://track:0AIcr2wW0FiHkNS82wLE9 - error: None

**Comment by JasperTheMinecraftDev** [comment]
Also this:
2024-09-06 18:32:15.961 ERROR (MainThread) [music_assistant.streams.media_stream] Failed to stream spotify://track:0AIcr2wW0FiHkNS82AwLE9 - error: None
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/helpers/audio.py", line 192, in _feed_stdin
    async for chunk in self.audio_input:
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/providers/spotify/__init__.py", line 601, in get_audio_stream
    raise AudioError(
music_assistant.common.models.errors.AudioError: Failed to stream spotify://track:0AIcr2wW0FiHkNSAwLE9 - error: None

I see the music title appearing on my TV but then it stops playing and empties the queue.

**Comment by boris19** [comment]
So after a full day of playing music in the combination mentioned below the log is clean with no errors. Please see the log stating that it started playing today 2024-09-06 at 8:43 and finished at 20:39, completely without any problems. 

[logb17.log](https://github.com/user-attachments/files/16912072/logb17.log)


> Combination of MA version 2.3.0b17 and YT music and Snapcast i have log without any issue and without put load on CPU and RAM after 9hours continuous playback. I will send full log later after end of day in building.
> 
> ![IMG_2170](https://private-user-images.githubusercontent.com/45606545/365221091-4f7bb67c-6e81-487c-8c92-cca296683aec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2NDk4NzMsIm5iZiI6MTcyNTY0OTU3MywicGF0aCI6Ii80NTYwNjU0NS8zNjUyMjEwOTEtNGY3YmI2N2MtNmU4MS00ODdjLThjOTItY2NhMjk2NjgzYWVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDE5MDYxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxZDM2MTJmY2MxZTg2YjYzMmI2M2ZkMzllZjg1ZTU0MDRmNWIxZDIyNmFlNzA2NTE0OGJiNDFlMmRmNTBiYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BRK9oFnLGlnuJ_0iwO-VIjl0xGe9g1eUmt7IWLqJPa0)

**Comment by OzGav** [comment]
For those reporting the error code 1 you need to advise what server version you are running. If you aren’t on beta 19 or 2.2.3 then you need to update

**Comment by nikito** [comment]
Got the error just now, version 2.3.0b19
`2024-09-06 19:40:58.815 ERROR (MainThread) [music_assistant.streams.media_stream] Failed to stream spotify://track:5N8KsYJ8IEMQVw33JvytW8 - error: 1
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/helpers/audio.py", line 192, in _feed_stdin
    async for chunk in self.audio_input:
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/providers/spotify/__init__.py", line 601, in get_audio_stream
    raise AudioError(
music_assistant.common.models.errors.AudioError: Failed to stream spotify://track:5N8KsYJ8IEMQVw33JvytW8 - error: 1`

**Comment by JasperTheMinecraftDev** [comment]
> For those reporting the error code 1 you need to advise what server version you are running. If you aren’t on beta 19 or 2.2.3 then you need to update

Latest as of the time of writing, which is 2.2.3. Installed it yesterday.

**Comment by OzGav** [comment]
Please test again when beta 20 or later is released

**Comment by OzGav** [comment]
Beta 20:has been released

**Comment by nikito** [comment]
Just tested out a bit, the error is no longer happening which is great! The only issue now is that the playlist will just pause itself after a while (think I got through maybe 5-7 songs before it paused itself again). If I click play it resumes fine though, so maybe something to do with the substitute track being pulled in?

**Comment by OzGav** [comment]
Those are different problems. Review the similar open issues and if yours is not the same then open a new one.
