### ISSUE TITLE
Discover weekly on spotify not available for multiple accounts

### ISSUE THREAD

**Issue by happydasch** [music-assistant/hass-music-assistant#2861]
### What version of Music Assistant has the issue?

2.2.2

### What version of the Home Assistant Integration have you got installed?

2024.8.4

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When using the spotify provider for multiple accounts, the special playlist discover weekly is only available from the first account. At the bottom of the playlist screen, both playlists are listed. Seems to be the same as #2206

### How to reproduce

Add the discover weekly playlist from multiple spotify accounts, only the first spotify account will be used

### Music Providers

Spotify

### Player Providers

Sonos

### What version of Home Assistant Core are your running

2024.8.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
> At the bottom of the playlist screen, both playlists are listed

Please supply a screenshot of what you mean here

**Comment by happydasch** [comment]
<img width="906" alt="Bildschirmfoto 2024-09-03 um 07 48 30" src="https://github.com/user-attachments/assets/6fc45b89-95df-4a65-8a7d-a88daff6c3d9">

This is the discover weekly playlist which is generated for a user. Both playlists, mine and my wifes, are shown as sources at the bottom but the songs only come from the first playlist, the second is ignored.

**Comment by marcelveldt** [comment]
please test if this is fixed in 2.3.0b18

**Comment by marcelveldt** [comment]
You may have to remove the playlist from the library once to trigger the fix

**Comment by happydasch** [comment]
Tested this, works well. Now the discover weekly appears twice with the correct songs for every account.

But a new issue appeared where both spotify accounts have the same playlist. This now appears two times. 

This is the source for one playlist (the other has the same sources):
<img width="955" alt="Bildschirmfoto 2024-09-04 um 10 11 33" src="https://github.com/user-attachments/assets/1d0d7f13-1e6a-4bbf-aa11-834472fab264">

This is the same playlist that both accounts have.
<img width="948" alt="Bildschirmfoto 2024-09-04 um 10 12 44" src="https://github.com/user-attachments/assets/599640ce-21c0-4242-bf19-da48df7eafd7">

**Comment by happydasch** [comment]
tested using the dev release of music assistant

**Comment by marcelveldt** [comment]
> tested using the dev release of music assistant, like i said, the fix works well, both playlists are now seperated

ah ok that makes sense - thanks for testing it on the dev build then!
