### ISSUE TITLE
Heavy audio crackling when chromecasting to Nest Audio

### ISSUE THREAD

**Issue by alucryd** [music-assistant/hass-music-assistant#2865]
### What version of Music Assistant has the issue?

2.2.2

### What version of the Home Assistant Integration have you got installed?

2024.8.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Recent updates have made MASS somewhat unusable with Chromecast as there is quite a lot of crackling in the audio that is played. Not a resource issue I think, it used to work fine on my current setup (N100 mini PC), and even on the previous home of my HASS server (Khadas Vim 3). Also, chromecasting the same music files from my phone works perfectly.

### How to reproduce

- Add a Jellyfin server
- Add the Chromecast provider
- Play a file on a Nest Audio via Chromecast

### Music Providers

Jellyfin

### Player Providers

Chromecast

### Full log output

[music-assistant.log](https://github.com/user-attachments/files/16849822/music-assistant.log)

### What version of Home Assistant Core are your running

2024.8.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by marcelveldt** [comment]
So, did you set the volume normalization to a custom value perhaps ?

**Comment by alucryd** [comment]
Haven't touched volume normalization, in fact I wasn't aware MASS was using these tags, this is great!

**Comment by OzGav** [comment]
If it is a network bandwidth issue note that casting from your phone is not necessarily a valid test as MA sends lossless FLAC which your phone may not

**Comment by marcelveldt** [comment]
bandwidth issues often sounds like hiccups or stuttering - crackling is something else and most often clipping or another issue affecting sound quality

**Comment by marcelveldt** [comment]
> Today I was able to enjoy a crackling-free audio session, I'll keep an eye on the issue, it was always crackling for the better part of a week, not sure what changed, I haven't changed any config or rebooted anything.

OK, keep an eye on it - if the issue returns, please reply here. If not, close the issue. Thanks!

**Comment by alucryd** [comment]
Thanks for the input. Haven't been able to reproduce for several days. I tend to dismiss bandwidth issues as I run a mesh network with no blind spot in the entire house, and all critical paths are wired, in this particular case only the nest audio is on wifi. I wasn't aware MA was sending flac (another great thing) so yeah it does sound like bandwidth issue, maybe I had too much interference for a few days.
