### ISSUE TITLE
Playlist started via automation sometimes repeats first song endlessly

### ISSUE THREAD

**Issue by johnboiles** [music-assistant/hass-music-assistant#2867]
### What version of Music Assistant has the issue?

2.2.2

### What version of the Home Assistant Integration have you got installed?

2024.8.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Sometimes when playing a playlist from a HA automation, the first song repeats endlessly. Once I manually go into Music Assistant and hit the 'next track' button the playlist will continue normally. The logs at level 'info' don't show anything interesting. They show a single 'content type' line when the playlist started, but nothing after. I've confirmed 'Repeat One' is definitely not selected (see screenshot).

Similarly my ESPHome media player logs don't show anything interesting. It doesn't seem to be restarting the stream. In case it's a clue, there seems to be an unusual (maybe 10s) delay between the end of the first song and it repeating itself.

I've never been able to reproduce this when manually selecting a playlist in MA.

I've been running this automation successfully for a few weeks now but this only started happening on 8/22, around the time I upgraded from 2.2.0->2.2.1.

Here's my play queue. The Captain Kidd song (the first one in my 'Sol Office Morning' playlist) repeats endlessly when this issue occurs.
<img width="620" alt="image" src="https://github.com/user-attachments/assets/b5454a7c-960a-4a6f-8675-13a1a2d3f3a9">

Here's my automation:
```
metadata: {}
data:
  media_type: playlist
  media_id: Sol Office Morning
action: mass.play_media
target:
  entity_id: media_player.main_stereo
  ```

### How to reproduce

Play a playlist via Home Assistant automation every morning. First song sometimes repeats endlessly. Coworkers complain about it :)

### Music Providers

Apple Music

### Player Providers

ESPHome I2S Media Player

### Full log output

[music-assistant.log](https://github.com/user-attachments/files/16851975/music-assistant.log)

### Additional information

Home Assistant Yellow 4GB RAM

### What version of Home Assistant Core are your running

2024.8.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Confirm if you start the playlist from the MA UI that it plays back normally

**Comment by johnboiles** [comment]
Yes confirmed. I've only been able to reproduce this via automation. When I trigger the automation manually from the HA Automation list I can't reproduce, so it may be an intermittent issue.

**Comment by OzGav** [comment]
OK the log indicates you have some major Apple Music problem. I'll ask @MarvinSchenkel to have a look

**Comment by johnboiles** [comment]
I have noticed the metadata getting messed up sometimes. It will show the correct song title but the wrong album and artist.

**Comment by johnboiles** [comment]
BTW @OzGav thank you for working on Music Assistant. I know it's early and has some kinks to work out but I love it. I made a [SPDIF out component for ESPHome](https://github.com/gnumpi/esphome_audio/pull/59) to use with it so I get crystal clear audio from MA. I'm using MA all day every day now.

**Comment by MarvinSchenkel** [comment]
This issue is unrelated to Apple Music. The messages in the logs just indicate that your library consists of lots of albums / artists that can not be found in the catalog (probably due to manually uploaded music without proper tags / iTunes migrations etc.).

Does your song actually (i.e. the audio) get repeated? Or is it just the metadata that 'sticks' on one song? I sometimes have this issue in my setup, but have not been able to reliably reproduce it.

**Comment by johnboiles** [comment]
> Does your song actually (i.e. the audio) get repeated?

Yes the song audio repeats. I have noticed the metadata not quite matching generally (song title is typically correct but sometimes it shows the wrong artist) -- but that's a different issue (and one that doesn't bug my coworkers 😀)

**Comment by johnboiles** [comment]
I haven't seen this in a week. My coworkers are happy. I'll close this and reopen if it happens again.
