### ISSUE TITLE
Warning on parsing radio station URL that works

### ISSUE THREAD

**Issue by dunxd** [music-assistant/hass-music-assistant#2868]
### What version of Music Assistant has the issue?

2.2.2

### What version of the Home Assistant Integration have you got installed?

2024.8.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I have a few radio stations I manually added - they all throw an error similar to below:

```
WARNING (MainThread) [music_assistant.audio] Error while parsing radio URL http://lstn.lv/bbc.m3u8?station=bbc_6music&bitrate=320000: 
```
However the radio station does play and it wouldn't work if the URL arguments weren't being parsed so this could be a false positive.

I am having some issues with an Airplay speaker, and in troubleshooting this I saw this warning message, and wondered if it was in any way relevant. But I'm assuming that this error refers to parsing of the URL by Music Assistant not the speaker.

### How to reproduce

Manually add radio station URL `http://lstn.lv/bbc.m3u8?station=bbc_6music&bitrate=320000` then play it.

### Music Providers

Whichever one allows adding radio stations by URL - I have radio browser installed but I'm not sure that is required to add URLs.

### Player Providers

Airplay.

### What version of Home Assistant Core are your running

2024.8.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Changes have been made in the beta for BBC steams. Can you try that?

**Comment by marcelveldt** [comment]
This was already fixed a while ago (and available in beta) but its not yet in the stable version. We'll push a new stable version with these fixes soon.

**Comment by dunxd** [comment]
That's great to hear.  Could you elaborate whether this is a change to the parsing of URLs or relating to Radio Browser.  

The reason I ask is there are so many duplicate indistinguishable entries for BBC radio stations it is hard to select the correct one. And with BBC increasingly cutting off stream sources, I think many of the entries in Radio Browser's database are stale or no longer functioning.  Hence what worked for me was entering URLs I know work today rather than trying every entry in Radio Browser.  So if the fix is to handling the URL great, but if the fix is related to Radio Browser it might technically be fixed, but finding it is rather hit and miss.

**Comment by dunxd** [comment]
I don't see any PRs referencing BBC or lstn.to, so I'm trying to understand exactly how I would verify a fix before I take a risk on exposing my family to the Beta.

**Comment by OzGav** [comment]
This is the PR https://github.com/music-assistant/server/pull/1633

As for radio browser entries you (or someone) needs to fix any broken links in their database. MA can’t do that for you. Your manual entry should work.

**Comment by OzGav** [comment]
Having said that these fixes will roll out in stable very soon

**Comment by dunxd** [comment]
Can confirm that the error message is now gone with 2.2.2
