### ISSUE TITLE
Spotify playback issues

### ISSUE THREAD

**Issue by BassyBoo55** [music-assistant/hass-music-assistant#2871]
### What version of Music Assistant has the issue?

2.3.0b17

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When attempting to play any song on spotify, it instantly skips to the next one until there is nothing left in the queue.

### How to reproduce

Install beta or non beta version using the addon store in home assistant, link spotify and a player the attempt to play spotify.

### Music Providers

SPOTIFY
Soundcloud works but attempting to skip 30seconds forward results in the song being restarted.

### Player Providers

Can only test snapcast. Unsure if happens with other providers.

### Full log output

[music-assistant.log](https://github.com/user-attachments/files/16869838/music-assistant.log)

### Additional information

Running on VMWARE WORKSTATION PRO 17.5.2 build-23775571
Host: Windows 11 23H2 build 22635.4145

### What version of Home Assistant Core are your running

2024.8.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Alternative

**Comment by OzGav** [comment]
Duplicate https://github.com/music-assistant/hass-music-assistant/issues/2860
