### ISSUE TITLE
MA play_media Service Call missing and cant play music from standard call

### ISSUE THREAD

**Issue by TheBartoMan** [music-assistant/hass-music-assistant#2880]
### What version of Music Assistant has the issue?

2.3.0b19

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I cant find the MASS service call reffered to in documentation. When i try to do for example:-

media_play.play_media
i set my speaker as entity id
i set the content to music

but i cant get anything to play if i enter an artist name or album etc in the content id
![Screenshot 06-09-2024 at 10 16 39@2x](https://github.com/user-attachments/assets/7427207e-3512-4ffd-825d-a9a91d5fef45)

What are you meant to enter as a content id, as it seems to want an actual ID

### How to reproduce

Via developer tool and choose media_player.play.music

I cant find the MASS one shown in the documentation

### Music Providers

Spotify
Appl Music

### Player Providers

Home Assistant Media Players

### What version of Home Assistant Core are your running

2024.9.0

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Linux

**Comment by TheBartoMan** [comment]
My mistake - hadnt fully installed

**Comment by lverlaek** [comment]
> My mistake - hadnt fully installed

Could you explain what was missing, because i'm don't see mass actions also, and I'm looking for days now..

**Comment by OzGav** [comment]
@lverlaek you have to install the integration. https://music-assistant.io/integration/
