### ISSUE TITLE
Apple Music wont add - was working

### ISSUE THREAD

**Issue by TheBartoMan** [music-assistant/hass-music-assistant#2881]
### What version of Music Assistant has the issue?

2.2.3

### What version of the Home Assistant Integration have you got installed?

2024.8.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I did have apple music setup. But i removed the whole Music Assistant Installation.

After reinstalling, i cant add Apple Music. I just get...

Failed to install package pywidevine==1.8.0
error: Failed to download and build `construct==2.8.8`
  Caused by: Failed to build: `construct==2.8.8`
  Caused by: Failed to run /tmp/.tmpdizsOs/builds-v0/.tmpkIyJvS/bin/python
  Caused by: Permission denied (os error 13)

As soon as i click to add Apple Music, i get the attached image. Doesnt even show the option to add the key.
![Screenshot 06-09-2024 at 11 38 10@2x](https://github.com/user-attachments/assets/995ba1f8-64bb-4e42-a710-3f372fa2fd16)

### How to reproduce

Music Assistant > Add Music Provider > Apple Music

then i get attached issue with no option to enter key

![Screenshot 06-09-2024 at 11 38 10@2x](https://github.com/user-attachments/assets/049dc864-d1b2-4a53-90bb-bb35e502be6f)

### Music Providers

Spotify

### Player Providers

Home Assistant

### What version of Home Assistant Core are your running

2024.9.0

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
What have your searches for that os error turned up?

**Comment by TheBartoMan** [comment]
I am not searching for anything. I am just trying to add the music provider and i get that error

**Comment by OzGav** [comment]
It’s an operating system error so not MA. Try googling it

**Comment by TheBartoMan** [comment]
It was all working fine i had apple music setup. I uninstalled Music Assistant, and when i reinstalled it this is what happened and i cant add Apple Music

**Comment by OzGav** [comment]
I understand that but it’s an OS error

**Comment by TheBartoMan** [comment]
I appreciate that. I am no Linux expert so hoping for some advice/answers here. The thumb was referring to that I have tried searching and had no luck with an answer.

This morning I installed Music Assistant for the first time and everything installed fine, i added Apple Music and its asked for a key and i got it working.

I since removed Music Assistant as i couldn't find something. Then I reinstalled all fine, but now get the error preventing me from re-adding Apple Music. I was thinking something didnt uninstall clean maybe?

I was hoping for some advice / help here as opposed to just googling it please.

**Comment by OzGav** [comment]
Have you run out of space? Unfortunately because you are running supervised you have to sort out OS problems. We only officially support HAOS and Docker. As a guess have you tried a host reboot or removed MA again, done a host reboot and then reinstall?

**Comment by TheBartoMan** [comment]
Yes there is plenty of space, also tried reinstalling and rebooting.

Just wondering what is is actually trying to run whenm that window opens when you select Apple Music as a provider.

The first time when it worked, I got a box asking for the Apple Key, not that box doesnt appear, just the error (as you see in my image)

Really appreciate any help thank you

**Comment by TheBartoMan** [comment]
in the log file it shows

2024-09-06 16:41:54.807 ERROR (MainThread) [music_assistant.webserver] Error handling message: config/providers/get_entries: Failed to install package pywidevine==1.8.0
error: Failed to download and build `construct==2.8.8`
  Caused by: Failed to build: `construct==2.8.8`
  Caused by: Failed to run /tmp/.tmpg8oE7v/builds-v0/.tmpaGVTkw/bin/python
  Caused by: Permission denied (os error 13)

**Comment by TheBartoMan** [comment]
I turned logging to debug and this is what i got. Any help appreciated.

2024-09-06 21:18:21.650 ERROR (MainThread) [music_assistant.webserver] Error handling message: CommandMessage(message_id=19, command='config/providers/get_entries', args={'provider_domain': 'apple_music', 'values': {'session_id': '5YvsqQ8Imxh'}})
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/webserver.py", line 389, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/config.py", line 233, in get_provider_config_entries
    prov_mod = await load_provider_module(provider_domain, prov.requirements)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/helpers/util.py", line 114, in load_provider_module
    await install_package(requirement)
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/helpers/util.py", line 47, in install_package
    raise RuntimeError(msg)
RuntimeError: Failed to install package pywidevine==1.8.0
error: Failed to download and build `construct==2.8.8`
  Caused by: Failed to build: `construct==2.8.8`
  Caused by: Failed to run /tmp/.tmpxMdbiZ/builds-v0/.tmpE1ITa9/bin/python
  Caused by: Permission denied (os error 13)

**Comment by TheBartoMan** [comment]
Well I think ive cured it myself!

Steps:
1)Turned off protection mode on Terminal
2) from terminal ran **Docker PS**
3) tooke the ID number and then ran **docker exec -it 4455413632cf /bin/sh**
4) in the docker ran - **pip install pywidevine**
5) When i went back to add Apple Music, it didnt error and showed the box to enter the Apple Key.

Im not an Linux Guy, if anyone wants to take this information to explain or fix the app?

**Comment by MarvinSchenkel** [comment]
Are you sure you have followed the installation instructions and are running the container in privileged mode as per https://music-assistant.io/installation/? This smells like the user that is running MA in the container does not have sufficient permissions to install python dependencies. We do install them on the fly (eg when you're adding a provider) to minimalisme the footprint of the app.

**Comment by TheBartoMan** [comment]
It was installed using Method 1 on that guide "Primary installation method: Home Assistant Add-on"

I didnt do anything fancy to install it.

**Comment by OzGav** [comment]
closing as fixed.
