### ISSUE TITLE
docker image requires pywidevine

### ISSUE THREAD

**Issue by TheBartoMan** [music-assistant/hass-music-assistant#2888]
### What version of Music Assistant has the issue?

2024.9.1

### What version of the Home Assistant Integration have you got installed?

2024.8.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I keep getting errors relating to pywidevine not being installed when clicking on Apple Music, and the box doesn't show to enter the "Music User Token"

Failed to install package pywidevine==1.8.0
error: Failed to download and build `construct==2.8.8`
  Caused by: Failed to build: `construct==2.8.8`
  Caused by: Failed to run /tmp/.tmpQPGfeG/builds-v0/.tmpWyTfoW/bin/python
  Caused by: Permission denied (os error 13)

No matter if I use method one to install, or method two (spinning up a docker), I get this error.

**Workaround**
if I shell into the docker and type:-

**pip list**

I dont see pywidevine in the list.

If I then run **pip install pywidevine** it adds it to the docker image.

Then when I go back to music assistant and add Apple Music it works. However on the next update it will break again.

If pywidevine is required, should this not be in the image?

### How to reproduce

Install Music Assistant either method one (the prefered easy way so i get the sidebar) or running the docker commands.

Then when i go to add the the music provider, Apple Music, i get the error:-

Failed to install package pywidevine==1.8.0
error: Failed to download and build `construct==2.8.8`
  Caused by: Failed to build: `construct==2.8.8`
  Caused by: Failed to run /tmp/.tmpQPGfeG/builds-v0/.tmpWyTfoW/bin/python
  Caused by: Permission denied (os error 13)

### Music Providers

Apple Music fails
Spotify is fine

### Player Providers

Home Assistant Players

### What version of Home Assistant Core are your running

2024.9.1

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
Why have you opened an identical issue to the one closed recently?

**Comment by TheBartoMan** [comment]
I thought the issue was a one off and had gone away after solving myself. 

It came back. So I tried some tests. Fully uninstalling it, making sure the docker was gone and the images. 

Tried installing it both ways and both ways have the issue. 

It appears a requested feature is not in the docket image. 

Apologies if I have opened / reported it incorrectly.

**Comment by OzGav** [comment]
It is still an OS error which you need to solve. That’s the downside. Per the Home Assistant docs

> Home Assistant Supervised requires users to maintain their own operating system.

**Comment by OzGav** [comment]
If you would use HAOS instead all this will go away

**Comment by TheBartoMan** [comment]
I'm a user of the system and have been using it for many many years as a supervised install. I've never had a single issue relating to it and I run a lot of plugs and apps etc. none which have ever been an issue. 

I can also say it's the first time when asking for help on this community I've been told to just Google it or be told it wouldn't be an issue if I used a different setup. 

I've tried my best to give clear and concise feedback to what I've found and what it looks like is something to do with the issues.

The app appears to want to use pywidevine and when I look it's not inside the docker image of Music Assistant. 

Tell me what else I should do? This is the community to point out issues you have isn't it?

**Comment by TheBartoMan** [comment]
@MarvinSchenkel Apologies if I have opened this again incorrectly. As a user I'm hoping I have provided valid feedback to a genuine issue I have encountered.

**Comment by TheBartoMan** [comment]
> It is still an OS error which you need to solve. That’s the downside. Per the Home Assistant docs
> 
> 
> 
> > Home Assistant Supervised requires users to maintain their own operating system.

The problem is fixed when I add something inside the Music Assistant docker container. Not the OS itself.

**Comment by TheBartoMan** [comment]
Pywidevine is mentioned in here, but it's not in the docker image when I install it. https://github.com/music-assistant/server/blob/main/requirements_all.txt

Any ideas?

**Comment by marcelveldt** [comment]
@MarvinSchenkel please add pywidevine to the dependencies of the apple music provider so this problem can be solved. Thanks!

**Comment by MarvinSchenkel** [comment]
> @MarvinSchenkel please add pywidevine to the dependencies of the apple music provider so this problem can be solved. Thanks!

Not sure what you expect me to do here. It has been there all along: https://github.com/music-assistant/server/blob/main/music_assistant/server/providers/apple_music/manifest.json

**Comment by TheBartoMan** [comment]
I do appreciate your help here everyone.

Apologies if im asking silly questions as it's new to me. Does the Docker image come with all the components in or does it (attempt) to build / add them when you install it?

I can see that pywinevine is not in it for me. Is that because for some reason it has failed to add?

**Comment by marcelveldt** [comment]
Yes, we need some elevated permissions to run Music Assistant. For Home Assistant add-ons, we describe an apparmor profile to fine grained describe what we need and why. That works fine on Home Assistant OS. For docker we just ask users full elevated rights.

I have a feeling that apparmor is somehow failing on your setup. Unfortunately you are the first to experience this issue. Advice to just try HAOS is meant just to narrow down the issue a bit as that is our reference setup. We only test docker installs and HAOS installs. Supervised is a bit of risk so to say.

Can you please navigate to the system health page and make a screenshot ?

https://my.home-assistant.io/redirect/system_health/

**Comment by TheBartoMan** [comment]
Please find attached screenshot as requested. Thank you
![Screenshot 10-09-2024 at 20 47 06@2x](https://github.com/user-attachments/assets/f3506eb4-b5df-426a-979b-e158207197b6)

**Comment by TheBartoMan** [comment]
@OzGav Turns out it's not just an OS issue that I should Google.

Thanks Team
