### ISSUE TITLE
Crackling/stuttering on AirPlay devices

### ISSUE THREAD

**Issue by Auram** [music-assistant/hass-music-assistant#2889]
### What version of Music Assistant has the issue?

2.2.3

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Anytime I play music to any of my three AirPlay devices (two Philips Soundrings and a Pioneer AVR) the music crackles/stutters quite often. I don't have this problem as often when playing the same music on the same devices via Logitech Media Server, but that has its own problems (tracks randomly skip and some stuttering does happen, but way way less).

### How to reproduce

Play music to an AirPlay speaker I guess. It just always happens.

### Music Providers

Spotify

### Player Providers

AirPlay

### Full log output

[log.txt](https://github.com/user-attachments/files/16934088/log.txt)

### Additional information

Just thought it's worth noting that this problem does occur when using LMS as well, just way less frequently. Maybe once or not at all a track in LMS as opposed to 10 to 20 times a track in MA. LMS also just randomly skips tracks and pauses or drops out for seconds at a time, whereas MA doesn't have a "don't stop the music" type thing for Spotify (as far as I could tell). It's been hard for me to find a perfect solution to replace my Chromecast-based whole home audio solution as that has been deteriorating for years now.

### What version of Home Assistant Core are your running

2024.6.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
If it happens with LMS as well then why do you think this is a MA problem?

**Comment by Auram** [comment]
Because it happens SIGNIFICANTLY more often in MA. Like I said, it happens every few seconds in MA as opposed to once every few tracks in LMS.

**Comment by OzGav** [comment]
Are your players wired?

**Comment by Auram** [comment]
Nope, all WiFi. My network should be good enough to push it though. If that's the limitation though it would make sense to me.

**Comment by OzGav** [comment]
MA streams FLAC so requires higher bandwidth than other applications so if you are having problems with LMS that will likely be exacerbated with MA.

**Comment by Auram** [comment]
I see. I just wired the one device I could (the receiver) to see if that gives any benefit. Doesn't seem to be so far, but we'll see.

**Comment by Auram** [comment]
Interestingly, I don't think the two Soundrings are having the crackling problem, it just seems to be the receiver. Any ideas why the receiver specifically would be crackly, but the other two (which are on WiFi) sound fine?

**Comment by OzGav** [comment]
Have you changed the default volume normalisation settings on the player?

**Comment by Auram** [comment]
I just turned normalization off which did seem to help a bit, but maybe that was placebo. Would normalization introduce more or less crackling?

**Comment by OzGav** [comment]
Only if you set it too high will it be a problem

**Comment by marcelveldt** [comment]
Can you perhaps make a recording of the distortion so we could identify this a bit better ? There's a difference between disturbed sound due to some error in the sound chain or skipped frames due to network connectivity issues. 

Also I would recommend playing a tiny bit with our fine grained settings for Airplay, most especially turn compression and/or encryption on/off (just play a bit with the setting combinations) as that MIGHT help on some devices.

MA and LMS under the hood use the exact same library for streaming to airplay devices (libraop) so a coindidence that the same issue exists on both is not that crazy.

**Comment by Auram** [comment]
Yeah I'll try to get something recorded. I did record some stuff earlier, but there were just droputs/stutters in it, no crackles surprisingly. Probably tomorrow, messed with all this a bit too much today.

**Comment by Auram** [comment]
Okay, got a recording where it happens a handful of times. It's actually not as bad this morning so maybe interference has something to do with it? The receiver is wired though so idk!

Anyway, here's the timecodes where you can hear the small crackles:
00:29
01:02
01:36
02:11
02:45 (most obvious)
03:54

And here's the recording: https://drive.google.com/file/d/12HKbvNT7J0t0cPvL4A7EP0Jaghxv6pOC/view?usp=sharing

And this is with compression and normalization turned off, but I didn't notice a big difference with those turned on (at least in the few songs I've been listening to this morning). I think I'd be willing to live with these small issues since the ones I have with LMS are more irritating (same occasional crackling just less, but often it will pause/dropout or just randomly skip songs in the middle of them). 

Couple things I prefer about LMS that make me not want to switch to MA are the lack of "don't stop the music" and a way to easily tune the AirPlay volume commands. 100% volume sent via AirPlay is ridiculously loud on my receiver so in LMS I have 100% set to lower in the AirPlay bridge settings. I imagine I could fix this with a HA automation, but I can't get the MA integration to work (a problem I figured I'd solve if I could get the other kinks worked out).

**Comment by OzGav** [comment]
Do you have other player providers to try?

**Comment by jpbaril** [comment]
I do have an issue that I would describe with the same words.
Yet mine is way worse than in Auram's sample.
The problem happen around 5-10 minutes after starting playing. Once the issue starts it get worse and worse until I hit pause. Pausing and restart playing right away do solve it for another 5-10 minutes.

My "Apple device" is a Shairport-Sync Linux system.
Before using MA I was using Synology Audio Station with that same Shairport-sync setup and I never got that issue in the last few years.

**Comment by jpbaril** [comment]
Here is a sound sample.

https://github.com/user-attachments/assets/06f8acfa-33e0-45c0-a8b1-d99f18b27c88

**Comment by jpbaril** [comment]
@OzGav This is not to be closed. Having to pause and unpause music every 5 minutes is very annoying. This only happens with MA.

**Comment by OzGav** [comment]
@jpbaril You are hijacking this thread now as your issue is not the same as the OP. If you have a problem using shairport you can open a new issue.

@Auram Do you still have a problem you want followed up?

**Comment by Auram** [comment]
I stopped using MA a while ago so not really. The issue was not resolved when I stopped, but I no longer have a real personal stake in it.
