### ISSUE TITLE
Page up and Page down buttons only work intermittently - Perhaps Firefox specific

### ISSUE THREAD

**Issue by harryfine** [music-assistant/hass-music-assistant#2892]
### What version of Music Assistant has the issue?

2.3.0b20

### What version of the Home Assistant Integration have you got installed?

2024.8.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When scrolling through screens with lots of info requiring scrolling, the page up and page down buttons don't work.  While I will say it is intermittent as they worked for my one time, I could not product it after that.  So on my computer I have to scroll with the mouse wheel or use the scroll bar.  However on some searches, such as in a search within browsing with Radio Browser, searching by popularity for instance, the scroll bar is sort of useless and the scroll wheel would take you hundreds of turns to get to the bottom of the list.

### How to reproduce

It may be Firefox specific.  I tried it in Chrome just now (under Linux Mint) and while I never use Chrome, the scrolling worked.  But that was hardly a test with a sample size of 1.

### Music Providers

Tidal
Local NAS
Tunein
Radio browser

### Player Providers

Sonos

### Full log output

[Log.txt](https://github.com/user-attachments/files/16937455/Log.txt)

### What version of Home Assistant Core are your running

2024.8.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Could well be a Firefox issue as we have seen multiple inconsistencies with that as well as safari

**Comment by OzGav** [comment]
I just tried Chrome and Edge and it worked fine. Not sure if this will be able to be addressed. Solutions at this time are to use the search function or a different browser

**Comment by OzGav** [comment]
Unfortunately the dev team don’t have the capacity to deal with browser specific issues. This will be left open however in case a member of the community wants to look into it. It is possible that Firefox or Vuetify updates also fix this. Please close this if it comes good.
