### ISSUE TITLE
Music Assistant does not provide track information to media cards any more since V2.  

### ISSUE THREAD

**Issue by codemonkey2k5** [music-assistant/hass-music-assistant#2896]
### What version of Music Assistant has the issue?

2.2.3

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Since V2 of Music assistant, I can no longer see current track information on my dashboards.  The controls work but the background only shows the Music Assistant icon.  It used to show the playing artist and song name.  

What the media card shows:
![image](https://github.com/user-attachments/assets/83219384-3952-414a-985a-43c0903e8cea)

What MediaAssistant shows:

![image](https://github.com/user-attachments/assets/9b04b1af-d331-43c0-a904-9e060e44029c)

### How to reproduce

All you need to do is run media assistant and start playing anything, then look at a media card for the output device that is playing.

### Music Providers

Primarily Spotify

### Player Providers

Playing to a Chromecast device.

### Full log output

[music-assistant.log](https://github.com/user-attachments/files/16955766/music-assistant.log)

### What version of Home Assistant Core are your running

2024.9.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
You haven’t provided the most important piece of information and that is the Integration version

**Comment by eximo84** [comment]
I was playing today and looking at using fully kiosk to output to a speaker over 3.5mm jack. As part of that setup the plan was to use home assistant as a front end to music assistant so my kids can just play age appropriate stuff from MA. However I wanted to show current playing and give the option to skip etc but the HA media player doesn't reflect what's playing for some reason. 

MA server: 2.2.2
HA: 2024.9.0
MA integration: 2024.8.1 (from HACS)

**Comment by OzGav** [comment]
@eximo84 please show your yaml for the card

**Comment by eximo84** [comment]
```
type: media-control
entity: media_player.galaxy_tab_a
```

It's just the built in media card.

**Comment by eximo84** [comment]
Just testing with HomePods. So sent a service call to play a playlist from HA to MA and send audio to the MA connected HomePod. 

Music plays and using the same media card pointed at the MA HomePod media player the details match what is playing although skipping forward tracks messes up the progress bar as this doesn't appear to reset when a new song starts. 

So maybe issue is related more to Chromecast and fully kiosk. I haven't tested other players yet.

**Comment by codemonkey2k5** [comment]
> You haven’t provided the most important piece of information and that is the Integration version
> 
> edit: and I can’t reproduce this. It works fine here. Please also supply the yaml for the card

I honestly don't know where to find the integration version.  I just installed todays update and this was the info it showed:

[2.2.4] - 14.09.2024
Server 2.2.4
2.2.4 (patch release)
Frontend 2.8.13

CARD YAML:

type: media-control
entity: media_player.chromecast8272
visibility:
  - condition: state
    entity: media_player.chromecast8272
    state: playing



It worked fine in V 1.x but not since 2.x of media assistant.  

Doesn't matter where the media comes from.  Spotify and local stored media tested.

**Comment by OzGav** [comment]
The integration version is in HACS. Do you even have it installed?

**Comment by OzGav** [comment]
@eximo84 do you have the integration installed? If so are you targeting the MA entity?

**Comment by codemonkey2k5** [comment]
> The integration version is in HACS. Do you even have it installed?

I mean, it's playing music right now so I think it is installed. 

I don't see anything in HACS but I do in Addons:

![image](https://github.com/user-attachments/assets/b21178ed-4926-49da-b912-130942fba665)

**Comment by codemonkey2k5** [comment]
It looks like if you pick a single song, it does pass track info to the card.  But not if you play anything on a playlist.

**Comment by codemonkey2k5** [comment]
> @eximo84 do you have the integration installed? If so are you targeting the MA entity?

I am very confused.  As shown above, I have media assistant.  Is there some additional thing I need to install?  The card info is a couple posts up.   Like I said.  It worked fine until I updated to V2.  I've only been using Home Assistant for about a month, so this is all very new to me.

**Comment by OzGav** [comment]
Look here https://music-assistant.io/integration/

**Comment by codemonkey2k5** [comment]
OK, thanks for that.  I still don't understand how it was working before.  Maybe an architecture change when the server went to V2 but I'm just talking out of my ass.    Anyways I've installed the integration and will see if anything has changed.

**Comment by codemonkey2k5** [comment]
Installed integration from HACS but it didn't add anything new that I can see.  Same issue.  

If I select a single song, or manually add items to the queue, then the track info shows.  But if I select a playlist, then it doesn't.

This was here prior to installing the integration, and is how I was able to get music to actually play from Spotify without a big hassle:  

![image](https://github.com/user-attachments/assets/c03082a6-0698-413a-9d4c-f8ed0faff805)

**Comment by OzGav** [comment]
You started this issue saying you had a problem with Chromecast players but you are pointing to the HA player provider above so please provide more details about exactly what the problem is. Now you have the integration installed you will find there are MA provided entities. What happens if you use those entities for your card?

**Comment by codemonkey2k5** [comment]
This is incredibly frustrating.  Honestly, I wonder sometimes if I only think I have a grasp of the English language because no one ever seems to understand me.  

I only mentioned the HA players because I was repeatedly asked if I had the integration installed.  
I pointed at it to highlight that the integration is indeed installed. 

Let's try again...

I just want to see the current track playing and controls on a media-card like I originally did.  That's it.  That is all I want.

It worked, now it doesn't.   And the only change was updating HA to the latest version.


RECAP:

I have no issue playing media, via any output device. So the integration was completely unneeded as far as I can tell.  
The only issue I have is that I have no way to put the current track info and all of the player buttons on my dashboard.  

My primary music source is Spotify which works fine in media-assistant.  The built in Music Assistant player works fine.  

The only way I see any track info in a media card is if I play individual tracks.  

If I select any play list in MA, I get what I shown in my original post.  The play/pause buttons work but that's it.  

I do apricate the fact that folks are responding and offering their time.  Thank you.  
Hopefully I've described things correctly this time.

**Comment by OzGav** [comment]
You still haven’t advised what integration version you have installed then

**Comment by codemonkey2k5** [comment]
2024.9.0.

**Comment by OzGav** [comment]
Firstly,  edit your post and take the swearing out. If you do that again you will be banned.

The version is important because the Integration connects MA to HA. Are you using the MA entity for your card?

**Comment by codemonkey2k5** [comment]
Sorry, for the language.  I let my frustration get the best of me and I was hangry.   A meal and some time to calm down and 
I think I finally figured out what you were asking me.  I had been pointing to the actual speaker entity.  This used to work and does under the circumstances mentioned above.  I killed the card and created a new one, then when I listed the available entities, I saw one that actually had the artist artwork and selected that.   This seems to have resolved the issue.  

The biggest issue I have with learning all things HA from scratch is that I probably didn't set up my naming correctly. 
So, for instance, when I look for entities related to MA, I see a few options for what the same speaker.  

Thank you for putting up with my ignorance.  


![image](https://github.com/user-attachments/assets/666678de-aef8-489a-b821-0a0005dc5722)

**Comment by OzGav** [comment]
Yes I change the MA entity names and add a `ma_` at the start so they are obvious and I can search for them

**Comment by codemonkey2k5** [comment]
Good advice.  The transfer from Home Seer to Home Assistant has been messy.  I didn't realize there would be such a difference in  how things were done.  I'll likely be cleaning things up for months.  

Thank you.

**Comment by eximo84** [comment]
> @eximo84 do you have the integration installed? If so are you targeting the MA entity?

Yes and yes

**Comment by OzGav** [comment]
@eximo84 please check all existing issues and open your own issue if necessary

**Comment by eximo84** [comment]
I'll do some more testing and report back. Thanks 🙂
