### ISSUE TITLE
Stupid Question - Playlist?

### ISSUE THREAD

**Issue by Jonnehs** [music-assistant/hass-music-assistant#290]
I have a bunch of files saved in /media/music, they show up fine, i can play them etc

The "Add to playlist" button does nothing, how do I create a playlist from these file mp3s?

2022.6.0b1 on hass 2022.6.0

**Comment by Jonnehs** [comment]
@marcelveldt thanks - I see. Is there a quick way to add songs to the playlist as well, or is just one song at a time?

**Comment by marcelveldt** [comment]
set it to list mode and click at the left on the small thumb/image

**Comment by Jonnehs** [comment]
Thanks so much, really great work so far - great integration!

Ability to add network CIFS shares as a source for media would be perfect
