### ISSUE TITLE
Wrong playlist track is getting deleted

### ISSUE THREAD

**Issue by madbrain76** [music-assistant/hass-music-assistant#2903]
### What version of Music Assistant has the issue?

2.3.0b21

### What version of the Home Assistant Integration have you got installed?

None

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Trying to delete the last track of a playlist leads to an error message

### How to reproduce

1. go to playlists
2. click a playlist. I chose playlist in the MA music provider, containing 2 Qobuz tracks
3. I selected | net to the second track , and "Remove from playlist"

I got "List assignment index out of range"

![image](https://github.com/user-attachments/assets/a633d1b6-d554-47b3-8908-337376757604)

### Music Providers

MA
Qobuz

### Player Providers

N/A

### Additional information

[ma_playlist_deletion.log](https://github.com/user-attachments/files/16972425/ma_playlist_deletion.log)

### What version of Home Assistant Core are your running

2024.9.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Windows

**Comment by madbrain76** [comment]
No such problem editing a Qobuz provider playlist.

**Comment by OzGav** [comment]
It actually is deleting the next track in the list which is why it fails when you try and delete the last

**Comment by madbrain76** [comment]
> It actually is deleting the next track in the list which is why it fails when you try and delete the last

Off by 1 error, then ?

**Comment by marcelveldt** [comment]
fixed in 2.3.0 rc1

**Comment by OzGav** [comment]
Confirmed fixed
