### ISSUE TITLE
Can't install as PWA

### ISSUE THREAD

**Issue by RandomLegend** [music-assistant/hass-music-assistant#2906]
### What version of Music Assistant has the issue?

2.2.3

### What version of the Home Assistant Integration have you got installed?

Nothing in there regarding my issue

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Opening either the internal webpage inside of HomeAssistant OR the exposed webUI on Port 8095 doesn't get recognized by my browsers to be installed as PWA.

### How to reproduce

Using Brave, Thorium, etc. and open the webui

### Music Providers

Not related to that

### Player Providers

Not related to that

### Full log output

[log.log](https://github.com/user-attachments/files/16978405/log.log)

### What version of Home Assistant Core are your running

2024.9.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by RandomLegend** [comment]
Here is a video aswell

https://github.com/user-attachments/assets/6b4a6404-50c1-4722-9a29-e81fa5821c49

Same issue on my android phone aswell.

**Comment by OzGav** [comment]
Have you tried a different browser?

**Comment by RandomLegend** [comment]
What you mean by that it doesn't install as a PWA? It says that it should on your website so i thought

**Comment by RandomLegend** [comment]
Yeah but i can't install it as a PWA on my android and there it actually is beneficial to isntall it that way, because then you don't have the menu bars of your browser that take up space.

**Comment by RandomLegend** [comment]
So to conclude, this RUNS as a PWA but can't be INSTALLED as a PWA - correct?

If so, would it be possible to make it installable as such? That would be beneficial in the mobile scenario.

**Comment by OzGav** [comment]
Correct. You may wish to contribute to the discussions

https://github.com/orgs/music-assistant/discussions/2666
https://github.com/orgs/music-assistant/discussions/2348

Or start your own

**Comment by RandomLegend** [comment]
Alright, thanks

**Comment by marcelveldt** [comment]
> Opening either the internal webpage inside of HomeAssistant OR the exposed webUI on Port 8095 doesn't get recognized by my browsers to be installed as PWA.

It works on iOS (from safari) but maybe on Android its blocked because it is not running on HTTPS ?
Some day we may have our own app. Until then you should be able to use the PWA but if that is now blocked by android then you probably need to pass the webinterface through a reverse proxy to make it HTTPS
