### ISSUE TITLE
Trying to add Bluesound player has error  'PlayerFeature' has no attribute 'ENQUEUE_NEXT'

### ISSUE THREAD

**Issue by twinkie0101** [music-assistant/hass-music-assistant#2907]
### What version of Music Assistant has the issue?

2.3.0b21

### What version of the Home Assistant Integration have you got installed?

2024.8.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When trying to add a bluesound player music assistant presents the following error:

`2024-09-12 07:58:42.377 ERROR (MainThread) [music_assistant.webserver] Error handling message: config/providers/get_entries: type object 'PlayerFeature' has no attribute 'ENQUEUE_NEXT'`

### How to reproduce

Add player provider > select Bluesound

### Music Providers

N/A

### Player Providers

Bluesound

### Full log output

[d5369777_music_assistant_beta_2024-09-12T12-10-06.369Z.log](https://github.com/user-attachments/files/16978883/d5369777_music_assistant_beta_2024-09-12T12-10-06.369Z.log)
[d5369777_music_assistant_beta_2024-09-12T12-10-06.369Z.log](https://github.com/user-attachments/files/16978883/d5369777_music_assistant_beta_2024-09-12T12-10-06.369Z.log)
[d5369777_music_assistant_beta_2024-09-12T12-10-06.369Z.log](https://github.com/user-attachments/files/16978883/d5369777_music_assistant_beta_2024-09-12T12-10-06.369Z.log)

### What version of Home Assistant Core are your running

2024.9.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
@cyanogenbot

**Comment by marcelveldt** [comment]
Yes, this will be fixed in the next beta

**Comment by twinkie0101** [comment]
Confirming fix worked in latest update! Thanks for the great work!!
