### ISSUE TITLE
Music Assistant Service Call (Actions) are Missing in Home Assistant OS

### ISSUE THREAD

**Issue by bzerangue** [music-assistant/hass-music-assistant#2909]
### What version of Music Assistant has the issue?

2.2.3

### What version of the Home Assistant Integration have you got installed?

Using the Official Home Assistant Add-On - https://github.com/music-assistant/core

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Music Assistant Service Calls (Actions) are no longer showing up as an action in automations or Developer Tools > Actions.

### How to reproduce

1. Create and automation and choose and action... Music Assistant Service Calls (don't show up under actions).
2. Go to Developer Tools > Actions and search for Music Assistant, no Music Assistant Service Calls show up.

### Music Providers

We are using Spotify and YouTube Music. But this doesn't apply to the CORE issue that the Service Calls do not show up in Home Assistant.

### Player Providers

Home Assistant Players (VLC Player). But this doesn't apply to the CORE issue that the Service Calls do not show up in Home Assistant.

### What version of Home Assistant Core are your running

2024.9.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
You haven’t installed the integration

**Comment by bzerangue** [comment]
@OzGav - Thank you. I was confused with the official Home Assistant Add-On, thinking that would take care of everything. I totally missed that I had to install the integration separate from that. Please forgive me for that big miss.

**Comment by bzerangue** [comment]
This can be closed. Not a bug. Just me misreading installation notes. Again sorry for that.
