### ISSUE TITLE
Not able to authenticate Tidal. Popup not showing after clicking button.

### ISSUE THREAD

**Issue by Quarco** [music-assistant/hass-music-assistant#2912]
### What version of Music Assistant has the issue?

2024.8.1

### What version of the Home Assistant Integration have you got installed?

2024.8.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

The authentication popup won't open, also javascript error of depricated function.

Installed the latest version and 2024.6.2, but same result. I can't authenticate @Tidal.
There is an exact same issue that seems to be solved (1201) but the problem is still here!

I tried every browser I have (IE / Brave / Chrome) in normal and incognito mode, all same result.
There is a fast blink only.

### How to reproduce

Latest version HA, various versions MA

### Music Providers

Tidal

### Player Providers

Not needed for this bug.

### What version of Home Assistant Core are your running

2024.8.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
You haven't provided the server version but I will assume you are on stable. This has been noted and is being looked into

**Comment by OzGav** [comment]
This is fixed in 2.2.4

**Comment by Quarco** [comment]
Indeed, fixed today with last update :-)
