### ISSUE TITLE
YouTube music cpu and ram load

### ISSUE THREAD

**Issue by boris19** [music-assistant/hass-music-assistant#2914]
### What version of Music Assistant has the issue?

2.3.0b22

### What version of the Home Assistant Integration have you got installed?

2024.8.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Is it possible that YouTube Music is unexpectedly causing high CPU and RAM usage after continuous playback? For example, each morning the add-on has to be restarted due to overload, and then it works normally. I didn’t capture anything unusual in the logs, but I’ll send them if the issue reoccurs, as they are clean after the restart. This issue didn’t occur with Spotify, but I had to replace Spotify due to playback error #2860. However, I still need to test if the issue will reappear in the current version. I’m aware that strange behavior is mentioned in the YouTube documentation.
![IMG_2151](https://github.com/user-attachments/assets/28024d12-a5d0-4cc8-a8b6-94a00e6c0c20)

### How to reproduce

	1.	Set up YouTube Music as the primary music service in the Music Assistant add-on.
	2.	Allow the music to play continuously for several hours (typically overnight).
	3.	In the morning, observe the system’s CPU and RAM usage.
	4.	When the system load increases, Music Assistant will become completely unresponsive.
	5.	Restart the Music Assistant add-on to restore normal functionality.
	6.	After the restart, check the logs for any unusual entries (though the logs are usually clean post-restart).

### Music Providers

YouTube music 

### Player Providers

Snapcast

### What version of Home Assistant Core are your running

2024.9.0

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Windows

**Comment by marcelveldt** [comment]
Can you retest with b23 please ?

**Comment by boris19** [comment]
I’ve also noticed that in version b22, there are significantly more issues with Snapcast compared to version b17. In version b17, I encountered no Snapcast errors at all. Additionally, there were several errors related to YouTube as well. Could you please take a look at this?

[music-assistant (2).log](https://github.com/user-attachments/files/17001676/music-assistant.2.log)

**Comment by boris19** [comment]
I’m not sure if more detailed logging for Snapcast was added in version b22 compared to b17, but in b17 I didn’t experience any errors, and more importantly, the music didn’t stop playing.

**Comment by marcelveldt** [comment]
please test b23 and then report back, not add extra questions

**Comment by OzGav** [comment]
We will close this soon due to no follow up
