### ISSUE TITLE
Stream error: 'utf-8' codec can't decode byte 0xd3 in position

### ISSUE THREAD

**Issue by deboy69** [music-assistant/hass-music-assistant#2917]
### What version of Music Assistant has the issue?

2.2.4

### What version of the Home Assistant Integration have you got installed?

2024.9.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

MA wont play M3u8 stream on radio

### How to reproduce

add local url to streaming radio link

### Music Providers

NA on MA. But works on VLC Player

### Player Providers

Airplay

### What version of Home Assistant Core are your running

2024.9.1

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Alternative

**Comment by johnboiles** [comment]
Can't tell for sure without the log attached but this is probably the same as #2908

**Comment by deboy69** [comment]
I'll grab you the logs. Last ticket i opened I got "yelled" at for attaching the log without approval.

**Comment by OzGav** [comment]
@deboy69 Just attach it don’t paste it

**Comment by OzGav** [comment]
Probably fixed by https://github.com/music-assistant/server/pull/1664

Confirm when the next beta is released

**Comment by deboy69** [comment]
[MA Log.txt](https://github.com/user-attachments/files/17006316/MA.Log.txt)


The log File is attached. It definitely could be related or similar to the above log.

**Comment by johnboiles** [comment]
Looks to me like the same issue but in the playlist parsing code this time:

```
music_assistant.audio.hls_stream] Start streaming HLS stream for url http://192.168.1.242:9022/octane.m3u8
2024-09-15 09:23:39.362 ERROR (MainThread) [ffmpeg.419] Stream error: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

**Comment by marcelveldt** [comment]
Well, this is not an MA issue then as the playlist is a m3u8 and should contain UTF-8 (hence the extension m3u8 instead of just m3u) so this is just a non compliant playlist file. Its also a local address so seems to me that you have some sort of influence over it ?

Sure we can hack around our code to also accept other codings but its still super strange that an UTF-8 based playlist file does not contain UTF-8 encoding

**Comment by deboy69** [comment]
> Well, this is not an MA issue then as the playlist is a m3u8 and should contain UTF-8 (hence the extension m3u8 instead of just m3u) so this is just a non compliant playlist file. Its also a local address so seems to me that you have some sort of influence over it ?
> 
> Sure we can hack around our code to also accept other codings but its still super strange that an UTF-8 based playlist file does not contain UTF-8 encoding

m3u isnt accepted by music assistant. VLC media player shows mp4a codec and plays it. Not sure what the issue is.

**Comment by marcelveldt** [comment]
@deboy69 did you test the new version ? version 2.2.5 (or 2.3.0b24 if you are running the beta)

**Comment by deboy69** [comment]
Yes, using 2.2.5 currently and no change

**Comment by OzGav** [comment]
Marcel also queried what this playlist file is as it appears to contain non UTF-8 characters in a M3U8 file?

Why do you say MA won’t accept a M3U playlist?

**Comment by deboy69** [comment]
Idk just trial and error I guess on trying to see what I can come up with.

Another container brings in the streaming from SiriusXm locally via a local docker container.

**Comment by deboy69** [comment]
I would have to disagree. Since the container has been running fine without any updates and VLC runs fine on it. The container hasn't had updates in over a year.

Only change has been MA updates. Used to work and updates broke it unfortunately

**Comment by OzGav** [comment]
You didn’t answer the question as to what this software is?

**Comment by deboy69** [comment]
https://github.com/AngellusMortis/sxm-docker

**Comment by OzGav** [comment]
This will get looked at in due course

**Comment by OzGav** [comment]
Not stale

**Comment by OzGav** [comment]
@deboy69 Please see if this is fixed in beta 30

**Comment by deboy69** [comment]
Hello, unfortunately it did not fix the problem?

**Comment by marcelveldt** [comment]
Please test beta 33 but also be aware that b33 will even bring a siriusxm provider natively to MA

**Comment by OzGav** [comment]
@deboy69 siriusxm is now available natively in MA so please use that

**Comment by deboy69** [comment]
Thanks for the help. Can confirm native works with beta. Has a little "stuttering" every once in a while but it works.

**Comment by OzGav** [comment]
Other users have reported after a couple of station changes things settled down...?
