### ISSUE TITLE
Adding a Music Assistant server on non-standard port fails

### ISSUE THREAD

**Issue by aliask** [music-assistant/hass-music-assistant#2924]
### What version of Music Assistant has the issue?

2.2.4

### What version of the Home Assistant Integration have you got installed?

2024.9.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

After successfully configuring MASS on a non-standard HTTP port (in my case I used `:8093`) I can browse the Web UI with no problems by visiting `http://my.server.ip.address:8093`.

However, attempting to add the Music Assistant Server to my Home Assistant this URL gives an error message `Unexpected Error`.

![Screenshot from 2024-09-15 18-27-49](https://github.com/user-attachments/assets/3f90b2a7-6d24-45dc-8f62-cfc78ea9e3d1)

### How to reproduce

1. In Home Assistant, navigate to Settings > Integrations
2. Click `Add Integration`
3. Search for Music Assistant, and enter the HTTP address of the server on a custom port
4. Click `Submit`
5. Observe integration is not added, and error message is displayed.

### Music Providers

-

### Player Providers

-

### Additional information

When the submit button is pressed to trigger the error, the Home Assistance logs produces the following output:

```
2024-09-15 18:27:27.061 ERROR (MainThread) [custom_components.mass] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/mass/config_flow.py", line 74, in async_step_manual
    await self.async_set_unique_id(self.server_info.server_id)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2389, in async_set_unique_id
    raise data_entry_flow.AbortFlow("already_in_progress")
homeassistant.data_entry_flow.AbortFlow: Flow aborted: already_in_progress
```

### What version of Home Assistant Core are your running

2024.8.2

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

**Comment by aliask** [comment]
Potentially related to #2333

**Comment by OzGav** [comment]
Review the recent posts in the issue you linked and confirm you have MA setup correctly.
