### ISSUE TITLE
Sub-Players in Chromecast Groups Not Showing Artwork or Metadata

### ISSUE THREAD

**Issue by brooksben11** [music-assistant/hass-music-assistant#2926]
### What version of Music Assistant has the issue?

2.2.4

### What version of the Home Assistant Integration have you got installed?

2024.9.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

For the last few versions of MA and the integration, when I play music on a Chromecast group, only the group MA player in HA shows artwork/metadata while the sub-players within the group only show playing. Here's a screenshot, 'Upstairs' is the MA player/CC group that I'm currently playing to and 'Living Room' is one of the MA players that's part of that group. Weirdly, a couple times I've noticed that the players have very briefly (talking like a second) shown artwork/metadata, but this appears random and I've rarely observed it.

I should also mention, the native Chromecast players DO show artwork and metadata, it's just the secondary players that MA creates that lack this.

![Screenshot_20240915-133707](https://github.com/user-attachments/assets/596511ab-f354-4681-840e-f27a1b61ac46)

### How to reproduce

Play to a Chromecast group.

### Music Providers

Tidal

### Player Providers

Chromecast groups

### Full log output

Nothing in logs.

### What version of Home Assistant Core are your running

2024.9.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by marcelveldt** [comment]
this is fixed in 2.2.5 (or 2.3.0b24 if you're running the beta)

**Comment by OzGav** [comment]
@brooksben11 please confirm if this is fixed

**Comment by brooksben11** [comment]
I'm noticing the same issue with Universal Groups. This definitely wasn't the case (a few versions ago?), I'm wondering if something got changed globally that maybe affects all groups? Unfortunately, I only have Chromecast and Universal groups to test.
