### ISSUE TITLE
Add support for more media players - Denon/Marantz receiver

### ISSUE THREAD

**Issue by pvmil** [music-assistant/hass-music-assistant#293]
I really like this plugin, hope it will become part of HA core

Would it be possible to add additional media players?  To be more precise: https://www.home-assistant.io/integrations/denonavr/

I did create a HA core issue on this, but seems work is needed on music-assistant side:
https://github.com/home-assistant/core/issues/71786

**Comment by marcelveldt** [comment]
Like I already mentioned in the HA core issue report, the denon integration within HA does not have playback support. So we can't send a playback request directly to the receiver, you can only send control commands such as "go to this source" or "change volume".

The easiest bet is to just connect a playback device (streamer) to the Denon receiver such as a chromecast.
Most modern receivers have that already builtin. Look in the receivers settings if you can enable Airplay or Chromecast.

**Comment by pvmil** [comment]
Sorry, I misunderstood, after reading again it is clear. The receiver should support Airplay (1) according to specifications, but I do not seen an integration supporting this in HA. Guess it is not possible to connect to this receiver via music-assistant, I'll close this issue.
