### ISSUE TITLE
Adding Spotify to music providers fails because redirect link uses local IP instead of Nabu Casa url

### ISSUE THREAD

**Issue by CaliLuke** [music-assistant/hass-music-assistant#2930]
### What version of Music Assistant has the issue?

2.2.4

### What version of the Home Assistant Integration have you got installed?

2024.9.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I'm using Home Assistant with a Nabu Casa subscription to make my HA instance available over the internet. When I try adding Spotify as provider the sign in process generates a return page with my local IP instead of the nabu casa URL so the process can't finish.

![2024-09-16_13-28-25](https://github.com/user-attachments/assets/491b56f2-6c02-4939-bdd5-0dd52cadb327)
 

### How to reproduce

go to settings > add music provider > spotify > click on authenticate with spotify

need a home assistant instance connected to a nabu casa cloud account

### Music Providers

Spotify

### Player Providers

n/a

### What version of Home Assistant Core are your running

2024.9.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by marcelveldt** [comment]
Like described in the documentation, you need to do the authentication from within your local network. This cant be done remotely.
