### ISSUE TITLE
Playing a private Spotify playlist on DLNA player does not continue to next track

### ISSUE THREAD

**Issue by refaelsommer** [music-assistant/hass-music-assistant#2932]
### What version of Music Assistant has the issue?

2.3.0b24

### What version of the Home Assistant Integration have you got installed?

2024.9.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When playing a Spotify playlist that is public all works fine on Sonos and DLNA players and tracks continue playing one after another.

When playing a self created Spotify playlist on Sonos player works fine **but** when playing a self created Spotify playlist on my DLNA players the playlist stops when the first track finishes and does not move on to the next track.

Just to clarify, in the beginning on my dlna players Spotify public and also private playlists did not move to next track, but I configured the dlna players and set **enable queue flow mode on** and only then public playlists started working fine, but private playlists are still broken.

I see this error in the logs:
`(MainThread) [music_assistant.dlna] Enqueuing the next track failed for player BEDROOM 4 - the player probably doesn't support this. Enable 'flow mode' for this player.`

But i have enabled flow mode and still shows this error.

### How to reproduce

Create in Spotify a new playlist and add to it some tracks you like.

Refresh music assistant and list items so you can see the new playlist in music assistant.

Choose a DLNA player and play this new playlist.

Expected behavior:
Player will move to next track when a track has finished playing.

Actual behavior:
Player stops once the first track ends and does not start the next one in the playlist.

### Music Providers

Spotify

### Player Providers

DLNA - bug
Sonos - works fine

### Full log output

[music_assistant_beta_2024-09-17T07-36-50.526Z.log](https://github.com/user-attachments/files/17024494/music_assistant_beta_2024-09-17T07-36-50.526Z.log)

### What version of Home Assistant Core are your running

2024.9.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
No log?

**Comment by refaelsommer** [comment]
> No log?

Added the log

**Comment by OzGav** [comment]
Do you QUEUE FLOW MODE enabled?

**Comment by OzGav** [comment]
You have attached a part of a DEBUG log. The template instructions say:

> Please DOWNLOAD then DRAG and DROP the full log output from MA SETTINGS>>CORE into the field below. Please do NOT use debug logging unless asked to do so.

Please fix this

**Comment by refaelsommer** [comment]
> You have attached a part of a DEBUG log. The template instructions say:
> 
> > Please DOWNLOAD then DRAG and DROP the full log output from MA SETTINGS>>CORE into the field below. Please do NOT use debug logging unless asked to do so.
> 
> Please fix this

is that good?

[music_assistant_2024-09-17T07-36-50.526Z.log](https://github.com/user-attachments/files/17026172/music_assistant_2024-09-17T07-36-50.526Z.log)

**Comment by refaelsommer** [comment]
Oh I will change from debug to info and resend in a moment

**Comment by OzGav** [comment]
Thanks there was a change to default the QUEUE FLOW MODE ON in beta 24. I know you said you said you turned it on but please show a screenshot of the player that is showing the error so we can see the settings in use.

**Comment by refaelOW** [comment]
Yes I am a technical developer :) so I played around with all the settings and none of the combinations helped solving this issue.

here are some screenshots:
<img width="1473" alt="Screenshot 2024-09-17 at 17 22 10" src="https://github.com/user-attachments/assets/4bc72564-c77d-4994-94b9-c51bda8b1081">
<img width="1474" alt="Screenshot 2024-09-17 at 17 22 18" src="https://github.com/user-attachments/assets/4aa60d6d-4d12-4172-a07a-4c6dc423a014">

**Comment by marcelveldt** [comment]
Just as an observation: Be careful for clipping with such a high level for volume normalization. We have a limiter within the chain but better leave some headroom. So set it to -12 or something alike (which ia already way higher than I ususually recommend).

That said, interesting observation about the private vs public playlist. I'll investigate that

**Comment by refaelsommer** [comment]
Thanks, I probably played around with it and unintentionally left it on -5 because I see that all the other 12 players have it on -17 as you said the default is.

what does this really do?

And thanks for helping taking a look on the private playlist bug 🙏🏻
I really need this fix, I gave my kids to choose tracks they like and they wake up in the morning to the playlist tracks they chose, but after one track it stops 🤷🏻‍♂️

**Comment by refaelsommer** [comment]
I sent my question to ChatGPT:

The "target level for volume normalization" setting is used to adjust the playback volume to a consistent level across different tracks or media. This helps prevent sudden jumps in loudness between songs or videos. The value "-17" represents decibels (dB), a measure of loudness.

At a default value of -17 dB, the player tries to adjust the volume of all media to this level, ensuring they all play at a similar loudness. Lower values (e.g., -20 dB) would make tracks play quieter, while higher values (e.g., -10 dB) would make them louder.

This setting is especially useful when you have media from various sources with different recording levels, as it provides a smoother listening experience.

**Comment by OzGav** [comment]
https://music-assistant.io/faq/how-to/#use-volume-normalization-how-does-it-work

**Comment by marcelveldt** [comment]
I quickly pushed a fix for this - can you try beta25 (it will be available within 15 minutes) ?

**Comment by refaelsommer** [comment]
I am trying it right now, the log still shows error:
![IMG_6090](https://github.com/user-attachments/assets/434142d5-16b4-4dbf-9ad7-dcab7d958550)

Looks like is works 🤩 
But in one of the cases it skipped a track, I waited for a track to end and it skipped a track and started 2 tracks after.
Shuffle is disabled and repeat queue is enabled.

And why do you think it still shows this error on adding next track?

**Comment by refaelsommer** [comment]
Also I see that sometimes the player is playing a track while showing a photo and title of a different track in this playlist.

**Comment by OzGav** [comment]
The skipping track problem is a different issue related to Spotify. If you had a different music provider that would be useful to eliminate some variables but its ok if you don't As for the error will have to wait for Marcel with that one.

**Comment by refaelsommer** [comment]
Ok, so if this Spotify issue is a known one then that’s ok.

is that Spotify skipping issue being addressed on another ticket? Or found to be something that cannot be fixed for now?

**Comment by OzGav** [comment]
It needs to be fixed https://github.com/music-assistant/hass-music-assistant/issues/2863

**Comment by refaelsommer** [comment]
Ahh great!!!
You guys are doing an amazing job
Thanks 🙏🏻

**Comment by marcelveldt** [comment]
Is the original issue report fixed now ? If yes, please close here and if there are new/other issues, please open a new issue report. Otherwise it becomes super difficult for me to follow. Thanks!

**Comment by OzGav** [comment]
@refaelsommer please confirm the original issue in this report is fixed

**Comment by refaelsommer** [comment]
Yes it is fixed, thanks

**Comment by refaelsommer** [comment]
Closing this issue
