### ISSUE TITLE
Unrelated albums inside artist folder

### ISSUE THREAD

**Issue by de666** [music-assistant/hass-music-assistant#2933]
### What version of Music Assistant has the issue?

2.3.0b24

### What version of the Home Assistant Integration have you got installed?

2024.9.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Going inside an artist folder, music assistant shows also other albums apperently completly unrealated to that artist with unrelated multiple artist tags.
I don't find any sort of "rule" in this behaviour, it seems to be a sort of random thing but it happens almost for every artist.
All the files are well tagged with picard (all have musibrainz ids).

screenshot example
[screenshot_album_bug](https://github.com/user-attachments/assets/b979b4e9-3be8-4ec1-b258-9b6a0253b0ba)

### How to reproduce

Try to browse an artist (filesystem provider) and see there are albums in the list not related to that artist.

### Music Providers

Filesystem

### Player Providers

Any

### What version of Home Assistant Core are your running

2024.9.2

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Pretty sure this is a result of a bug previously fixed. You will need to do a db reset and let it rebuild to check MA SETTINGS>>CORE>>MUSIC CONTROLLER>>ADVANCED

**Comment by de666** [comment]
> Pretty sure this is a result of a bug previously fixed. You will need to do a db reset and let it rebuild to check MA SETTINGS>>CORE>>MUSIC CONTROLLER>>ADVANCED

Solved after rebuilding the database
Thanks @OzGav
