### ISSUE TITLE
[Errno 98] error while attempting to bind on address ('0.0.0.0', 8095): [errno 98] address in use

### ISSUE THREAD

**Issue by Doppelherz** [music-assistant/hass-music-assistant#2935]
### What version of Music Assistant has the issue?

2.2.5

### What version of the Home Assistant Integration have you got installed?

2024.9.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Error on Start, cannot connect to server gui

### How to reproduce

Go to Home Assistant Addons, open Music Assistant Server and start it.

### Music Providers

I don't know anymore. YouTube Music, Apple Music, Plex?

### Player Providers

Sonos

### Full log output

[d5369777_music_assistant_2024-09-17T18-28-55.355Z.log](https://github.com/user-attachments/files/17033510/d5369777_music_assistant_2024-09-17T18-28-55.355Z.log)

### What version of Home Assistant Core are your running

2024.9.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
The error seems pretty clear. Something on your device already is using the port

**Comment by Doppelherz** [comment]
Thats what i thought, but it is Home Assistant OS with only a few Addons. About a month ago it worked. But updates seem to be problematic. Tomorrow i try to restart the complete system

**Comment by OzGav** [comment]
Make sure you don’t have two versions of MA running (eg. stable and beta)

**Comment by OzGav** [comment]
@Doppelherz how did you go? I will close this soon as it is not a MA problem

**Comment by Doppelherz** [comment]
After a system reboot the port was unused and music assistant startet again. 

It has something to do with updates. I had nothing working on that port. I had both addons ( default and beta ) but beta was stopped all the time and now i‘ve uninstalled it. 

I close this issue. Thanks for checking and confirm that it was a port problem.
