### ISSUE TITLE
Sending commands to UPnP/DLNA Always fails (Works on HA Frontier Silicon integration)

### ISSUE THREAD

**Issue by distante** [music-assistant/hass-music-assistant#2939]
### What version of Music Assistant has the issue?

2.2.5

### What version of the Home Assistant Integration have you got installed?

2024.9.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Trying to control anything from My Spotify account into my [Medion Radio](https://www.amazon.de/-/en/gp/product/B0BLSS4PHQ/) always fails.

Also control volume changes do not work.

The same device is added into Home Assistant with the Frontier Silicon integration and there The play, volume and on/off controls work as expected. 

### How to reproduce

Add a Medion device, add a Spotify Music provider, try to reproduce anything.

### Music Providers

Spotify.

### Player Providers

UPnP/DLNA Player provider

### Full log output

[music-assistant.log](https://github.com/user-attachments/files/17049385/music-assistant.log)

### Additional information

Also trying to control the media providers added to HA by the integration do not work.

### What version of Home Assistant Core are your running

2024.9.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by marcelveldt** [comment]
Looks like your player has an incomplete upnp implementation. So best/only thing you can do is use the HA players integration in MA to import your HA player into MA. It will then just use the working "Frontier Silicon integration"

**Comment by distante** [comment]
Thanks, I will do it in that way.
