### ISSUE TITLE
Problem joining/unjoining Airplay players

### ISSUE THREAD

**Issue by drjjr2** [music-assistant/hass-music-assistant#2943]
### What version of Music Assistant has the issue?

2.3.0b25

### What version of the Home Assistant Integration have you got installed?

2024.9.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Problem with joining and unjoining airplay players with players stopping/playing garbled audio

### How to reproduce

1. Start a playlist on player 1
2. Start a playlist on player 2
3. call media_player.join to join player 2 to player 1. Music is properly synced and playback is normal.
4. call media_player.unjoin to unjoin player 2. Player 2 stops and player 1 continues to play as expected
5. Start a playlist on player 2. Playback stops on player 1 and player 2 is playing the track from its playlist interleaved at about 1 second intervals with the track that should be playing on player 1. MA shows player 1 still playing. MA does not show the players as linked.
6. Turn off player 2. Playback resumes on player 1. 
7. Start a different playlist on player 2. MA relinks player 2 to player 1 and player 2 is playing the playlist from player 1.

### Music Providers

Spotify

### Player Providers

Player 1 - Airplay - Denon AVRx-4400H
Player 2 - Airplay - Apple Airport Express

### Full log output

[music-assistant (3).log](https://github.com/user-attachments/files/17060175/music-assistant.3.log)

### What version of Home Assistant Core are your running

2024.9.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Groups are being reworked. I just tried recreating this with the unpublished functionality and could not so this is likely fixed. You can confirm when the next beta comes out.

**Comment by OzGav** [comment]
Beta 30 has been released. Confirm this hass been fixed

**Comment by drjjr2** [comment]
> Beta 30 has been released. Confirm this has been fixed

Awesome. I will take a look at it tomorrow.

**Comment by drjjr2** [comment]
I am still having the same issue on b30.

**Comment by OzGav** [comment]
Well that is very surprising as this has been completely rewritten and I could not reproduce it on two Airplay devices I have. Do you have any other devices you can try. We need to confirm it is indeed Airplay only.

I will try and recreate this again tomorrow.

**Comment by OzGav** [comment]
Also do you have any other Airplay devices you can try?

**Comment by drjjr2** [comment]
Yes, I was able to recreate it using:
- iEast oliostream and Airport Express
- Airport Express and Denon AVR-x4400H
- iEast oliostream and Denon AVR-x4400H

Using Spotify playlists

**Comment by OzGav** [comment]
OK I was able to reproduce this we are looking into it.

**Comment by OzGav** [comment]
@drjjr2 This should be fixed in beta 32 please confirm

**Comment by drjjr2** [comment]
Yes, this seems to be fixed in beta 33.
