### ISSUE TITLE
Resume after tts.speak

### ISSUE THREAD

**Issue by rysm83** [music-assistant/hass-music-assistant#2948]
### What version of Music Assistant has the issue?

2.2.2

### What version of the Home Assistant Integration have you got installed?

2024.8.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I created a script that plays a message with on of the media players using snapcast.  this is also added into Music Assistant.  The script works perfectly when called using home assistant.   Music is paused the messages is player then it resumes the music.  however if I call the same script using NodeRed the music paused message is played but the music does not play only stays paused. 
I'm not sure if this is an issue since it works with Home assistant calling the script but doesn't work 100% if Nodered calls the same script.

### How to reproduce

Creates a TTS action:
action: tts.cloud_say
metadata: {}
data:
  cache: false
  entity_id: media_player.tb310fu_3
  message: "{{message}}"
  language: en-GB
  options:
    voice: RyanNeural
 call the script in home assistant with automation or another action 
 action: script.new_script_1
metadata: {}
data:
  message: this is a test message using another script to call.

create same service call in nodeerd and trigger the script 

### Music Providers

Spotify

### Player Providers

Provider: Snapcast 
not in a group

### Full log output

[MusicAssistant_logfile.txt](https://github.com/user-attachments/files/17078397/MusicAssistant_logfile.txt)

### What version of Home Assistant Core are your running

2024.9.0

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Unfortunately we don’t have the capacity to assist with nodered if it works fine with HA
