### ISSUE TITLE
Spotify Setup Authentication: Timeout While Waiting for Authentication Callback

### ISSUE THREAD

**Issue by jcmleng** [music-assistant/hass-music-assistant#2949]
### What version of Music Assistant has the issue?

2.2.5

### What version of the Home Assistant Integration have you got installed?

2024.9.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Unable to add Spotify as a Music Provider. I get the error message: Timeout While Waiting for Authentication Callback

### How to reproduce

- Settings - > Add Music Provider -> Selected Spotify -> Clicked Authenticate with Spotify
- I get the Pop Up, and enter my Spotify credentials -> Agree to allow Spotify to connect to Music Assistant
- Get the message "_Music Assistant oAuth Redirect Processing your request"_ on the Pop up screen
- In the MA page, after ~30 seconds get the error _My-HA-URL says "Timeout while waithing for authentication callback"_

### Music Providers

Spotify

In my Spotify Account -> Profile ->Managed Apps, I can see a new Music Assistant line created, so the process seems to work outbound from HA/MA -> Spotify. I can replicate this outbound process by clicking the Remove Access button for the Music Assistant App in Spotify, and repeating the steps above to get the Music Assistant App created in Spotify.

### Player Providers

No issues - able to add Sonos and Chromecast 

### Full log output

[MA Log.txt](https://github.com/user-attachments/files/17083445/MA.Log.txt)

### Additional information

1. MA is installed in the same RPi instance as HA. The RPi is still operating below capacity - CPU is 5%, Memory Utilisation = 42%
2. MA integration is installed and running, have been able to add player providers and can see my media devices within MA. URL is as per the server address in the MA logs.
3. Have executed all steps from a local connection of HA - from the MA link in my HA dashboard sidebar
4. I do not have VPN installed on my network.
5. I have a paid Spotify Premium Family account
6. Have gone through all the issue logs on this topic

### What version of Home Assistant Core are your running

2024.9.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by tom5491** [comment]
Same issue here too. Running on RPi with Music Assistant v2.3.0b26

**Comment by marcelveldt** [comment]
Did you click the link the popup screen ?

**Comment by marcelveldt** [comment]
There was a small issue in the oauth redirect page after a recent change. Its fixed now.
You should be able to authenticate to spotify now

**Comment by jcmleng** [comment]
Confirmed authentication was successfully completed in a split second. Many thanks. Legend!
