### ISSUE TITLE
V.06b2: mute button not working

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#295]
The mute button in the mass player is not working (for CC). 
When tapping nothing happens.
When I re-open the player later on, the Button state changed, but music still playing:

![image](https://user-images.githubusercontent.com/4363599/171853170-eda1b637-f2cb-450e-8ab0-cbd19977822e.jpeg)

Nothing in the log file

**Comment by erkr** [comment]
Tried to call the service media_player.volume_mute directly via the developer tools. Also not any effect and no errors.

**Comment by erkr** [comment]
Behavior changed, but not properly solved in v06b3:
The mute button now stops the player, in stead of mute. This message in the logbook: `turned off triggered by service media_player.volume_mute`

**Comment by marcelveldt** [comment]
Hmmm I think I know what's going on here... For chromecast non-group players the power is mapped to mute.
I'll see if I can have it both mute and use mute as power control :-)

**Comment by marcelveldt** [comment]
this is fixed in beta 6 although muting a player will still show the player as powered off (because power is mapped to mute on CC) and a future improvement is a small mute button in the UI

**Comment by erkr** [comment]
Thanks for picking up this bug: 
Status:
- When playing muting works
- once muted, unmute is not possible as the player state is off

**Comment by marcelveldt** [comment]
This is the correct behavior. Power = mute on CC players.
HA hides the mute controls if the player is turned off but you can still run the mute service call.

So imo this is no longer a bug but "as designed"

**Comment by erkr** [comment]
We discussed plans for the offering more options for power control. 
The remaining state issue was my mistake. I used a universal media player to wrap the mass player. That universal player had the wrong state, not the mass player, my mistake 😳
