### ISSUE TITLE
Snapcast keeps increasing snapcast name

### ISSUE THREAD

**Issue by nimbling** [music-assistant/hass-music-assistant#2955]
### What version of Music Assistant has the issue?

2.3.0b26

### What version of the Home Assistant Integration have you got installed?

2024.9.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

In my snapweb interface, the snapcast name keeps increasing indefinitely. I'm at 5053 now: 
![image](https://github.com/user-attachments/assets/c35f0416-0fbb-49cd-8637-1d8e9eda91c4)

 This might be related to: https://github.com/badaix/snapcast/issues/1217 ? - though I can't find where to set "::" as an ip.

Thanks for having a look!

### How to reproduce

Install MAS, use snapcast.

### Music Providers

This happens independent of music provider. Though I have used Soundcloud and Spotify.

### Player Providers

Snapcast

### Full log output

Here's my log file (Please ignore the spotify authentication lines, I have created a new password)

[music-assistant.log](https://github.com/user-attachments/files/17095130/music-assistant.log)

### Additional information

Once a connection has been selected, this plays fine. But on new sessions, the remote snapcast client needs to be told each time what the "new" snapcast server name is.

### What version of Home Assistant Core are your running

2024.9.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
@SantiagoSotoC

**Comment by nimbling** [comment]
Here's my log with the log level set to DEBUG

[music-assistant.log](https://github.com/user-attachments/files/17095771/music-assistant.log)

**Comment by nimbling** [comment]
Just musing on this: I have all my IP addresses on the local network set to fixed IP's in the router - could that be the cause of this? (intuitively, I'd say it should prevent it... but it wouldn't be the first time that network technology made a fool out of me...)

**Comment by SantiagoSotoC** [comment]
This is not a bug, it is how ma and snapcast work, it is the name of the stream and it is dynamic

**Comment by OzGav** [comment]
Quick question. Mine just says “default”?

**Comment by nimbling** [comment]
@OzGav 
Yes, I have "default" listed there sometimes, too. But that only works if the numbered one is not present, I think.
As per your observation, it now looks like this:
<img width="761" alt="image" src="https://github.com/user-attachments/assets/68494b01-e34d-4976-97c0-918b05357d8f">
-but it will at one point start increasing that number again :(

Another log?
[music-assistant (1).log](https://github.com/user-attachments/files/17109451/music-assistant.1.log)

@SantiagoSotoC 
I have to select the increased number by hand. The server increases it's own number, but I need to point the client at that "new" snapserver name (that increased). The second one would "forget" the "default" and would need to be told to use one of those "Music assistant 1234" servers.

**Comment by nimbling** [comment]
I said default just now, and when I started to play, it shows this:

<img width="711" alt="image" src="https://github.com/user-attachments/assets/84a78a4b-5c84-411a-909e-95f4cf597c09">

I selected "default" when only that was available and my audio stopped, after waiting a bit "MusicAssistant--5030" showed up and now my sound is working again.

**Comment by SantiagoSotoC** [comment]
I don't know how to say that menu is not to be touched, it is for when snapcast is used manually, configuring the files, we use the api.
The bug is that this value changes ? 
If you use ma from its interface something doesn't work ?

**Comment by nimbling** [comment]
Yes, the value changes out of it's own accord. "Default" does not give me sound output, and the "MusicAssistant--5091" (I'm at that number now) keeps increasing.

I was listening music just now and it lost the snapcast connection.
[music-assistant.log](https://github.com/user-attachments/files/17121979/music-assistant.log)

(I just got a decent second hand amplifier... so the log might contain some of that)

**Comment by SantiagoSotoC** [comment]
Yes, streams are created and destroyed on demand, this is not a bug, if the connection was lost it is most likely a network issue, but in any case it is a snapcast bug and not a mussic asistant bug.
That number has to change, default is used when there is nothing playing. 
That number is a port and it is random, it is programmed that way.
This is the expected operation of Music Assistant
