### ISSUE TITLE
V.06b2: music shortly stutters when opening MA

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#296]
When music is playing and I re-open MA on HA, the music sometimes get shortly interrupted. Of course not very reproducible. Only saw it happen when the background tasks got activated (turning arrow)
Not noticed in any older version

**Comment by marcelveldt** [comment]
It's the result of the buffer changes in beta2. I'm going to revert those because the stuttering issue on Sonos devices is not related to the buffer.

**Comment by erkr** [comment]
Most likely a duplicate: #287

**Comment by erkr** [comment]
Solved in v06b3👍
