### ISSUE TITLE
HASS provider stopped working

### ISSUE THREAD

**Issue by jesmak** [music-assistant/hass-music-assistant#2962]
### What version of Music Assistant has the issue?

2.2.5

### What version of the Home Assistant Integration have you got installed?

2024.9.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

After updating HASS to 2024.9.3, Music Assistant's HASS Player Provider stopped working. The provider sees all the media players in HASS, and I can select the ones I want to use. However, no Music Assistant media players are created in HASS itself, nor are the HASS media players visible in Music Assistant as playback devices. Looking at the addon's logs, there's an error about invalid player id (see log attachment). Same error appears on logs, when selecting different media players for the provider. It's always 'Invalid player_id'. I've tried removing the whole addon and reinstalling it, power cycling devices, restarting the whole HASS physical server, but nothing fixes it.

### How to reproduce

- Have HASS 2024.9.3 with any kind of media player entity
- Fresh install of the Music Assistant addon in HASS
- Install Home Assistant Plugin Provider to Music Assistant
- Install Home Assistant Player Provider to Music Assistant and select any media player installed to HASS
- Reload integration on HASS side -> No entities appear
- Check logs to find the 'Invalid player_id' error

### Music Providers

Just Filesystem (remote share), don't have any others.

### Player Providers

Just Home Assistant Player Provider, don't have any others.

### Full log output

[2024-09-24_music_assistant_log.txt](https://github.com/user-attachments/files/17114100/2024-09-24_music_assistant_log.txt)

### Additional information

System is running as a VM on a Huawei server.

### What version of Home Assistant Core are your running

2024.9.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Alternative

**Comment by marcelveldt** [comment]
This issue is known and has been fixed in beta - I'll publish an update to stable as well with this fix

**Comment by jesmak** [comment]
> You ticked the box saying you checked the closed issues. How did you miss the second one? #2945

Because I'm blind as a bat and seems I only checked the open issues.
