### ISSUE TITLE
TTS on Chromecast devices not working since version 2.2.2

### ISSUE THREAD

**Issue by Dillton** [music-assistant/hass-music-assistant#2966]
### What version of Music Assistant has the issue?

2.2.3 and newer

### What version of the Home Assistant Integration have you got installed?

2024.9.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

After updating from version 2.2.2 the TTS isn't working on my Nest mini speakers.
Doesn't matter if it's a single speaker or group.
This is what I see in log.
![image](https://github.com/user-attachments/assets/51abbfa3-c86b-4573-8f18-78d88d9d2fef)

### How to reproduce

Just run version 2.2.3 or above and send simple tts.cloud_say to any speaker.

### Music Providers

Spotify, YTB and TuneIn

### Player Providers

Chromecast and Slimproto

### What version of Home Assistant Core are your running

2024.9.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by Dillton** [comment]
Same bahaviour on 2.2.6

**Comment by OzGav** [comment]
I don't think the title is accurate. I can use `tts.google_say` and that works fine however with `tts.cloud_say` then I get

`Failed to perform the action tts.cloud_say. InvalidDataError: Unable to retrieve info for http://192.168.1.165:8123/api/tts_proxy/a54d88e06612d820bc3be72877c74f257b561b19_en-au_6e8b81ac47_cloud.mp3: Server returned 404 Not Found`

However, I don't know if this is a MA problem because if I do a `tts.cloud_say` and target the HA entity then I get the Google chime but then nothing. 

So for those that are reporting this can you use a different TTS action and report back.

**Comment by Dillton** [comment]
Ok so with ==tts.google_translate_say== it works and it also works with ==tts.speak== like this which is basically the same as using ==tts.cloud_say== but I guess here is differenet backend logic thats why MA is not able to work with that:
```
action: tts.speak
target:
  entity_id: tts.home_assistant_cloud
data:
  cache: true
  media_player_entity_id: media_player.home_speakers_mass
  message: Welcome home guys.
  options:
    voice: CoraNeural
  language: en-US
```

To summarize this I still think this is MA problem with ==tts.cloud_say== but I am not sure if we should keep this issue opened.

**Comment by Dillton** [comment]
UPDATE: Not working again even with tts.speak or tts.google_say. Found out it's working only when speaker is not turned off. So when tts is sent to turned off Chromecast device the error above occurs. As already mentioned this worked last in MA 2.2.2

**Comment by Dillton** [comment]
Still present in MA version 2.2.7.

**Comment by OzGav** [comment]
> UPDATE: Not working again even with tts.speak or tts.google_say. Found out it's working only when speaker is not turned off. So when tts is sent to turned off Chromecast device the error above occurs. As already mentioned this worked last in MA 2.2.2
> 
> @OzGav Can you try to replicate the issue on your end?

I have my Google Home. It was showing as OFF in MA and I successfully sent this:

```
action: tts.google_say
data:
  entity_id: media_player.ma_kitchen_speaker
  message: testing
```

This was using beta 29

**Comment by OzGav** [comment]
Just tried with a Google Chromecast Ultra. Nothing in the queue and turned off and it worked fine…..

**Comment by Dillton** [comment]
Could this be device specific? I am using only Nest minis at the moment.

**Comment by OzGav** [comment]
Sorry just tried with a Google mini and it worked fine. Are you able to try with the beta to remove that variable?

**Comment by Dillton** [comment]
Just tried with latest beta and it's working there. So I guess lets wait untill MA 3.x.x is released?

**Comment by MarkHofmann11** [comment]
I am having a similar issue with resume not working after an announcement and running the latest beta.  Different error, but seeing this in the log when it doesn't resume:
2024-10-07 14:51:00.556 WARNING (MainThread) [music_assistant.players] Can not resume http://192.168.0.14:8097/flow/media_player.marks_office_hub/40fc003cd86f457d8599aa54e729b951.mp3?ts=1728326599 on Marks Office Hub

That isn't the real filename that was being played, but that is what was listed in the log.

**Comment by OzGav** [comment]
As this is working in beta I will close. Let us know if there are still problems when the next stable ships.
