### ISSUE TITLE
V.06b2: UI layout glitch

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#297]
In my IOS app the Tracks view looks like this:
![image](https://user-images.githubusercontent.com/4363599/171854834-2dd43b38-02f4-4454-b3e4-d879a810d874.jpeg)
Looks fine when Rotating the screen horizontally

**Comment by marcelveldt** [comment]
if you delete about 7000 tracks from your library I think the issue is solved :-)

**Comment by erkr** [comment]
Yes that works 😊

**Comment by marcelveldt** [comment]
moved the sync button to context menu
