### ISSUE TITLE
Youtube Music Plugin doesn't provide all 'Personal Playlists'

### ISSUE THREAD

**Issue by nikscha** [music-assistant/hass-music-assistant#2973]
### What version of Music Assistant has the issue?

2.2.6

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Some of the 'Personal Playlists' show up, like Liked Music and My Mix 3. However the others don't show (e.g. My Super Mix, Discovery Mix). Search also only finds Liked Music and My Mix 3, but no other personal playlists.

### How to reproduce

Search for My Mix 3. It shows. Search for My Mix 2, it doesn't show.

### Music Providers

Youtube Music

### Player Providers

Not applicable

### What version of Home Assistant Core are your running

2024.9.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
@MarvinSchenkel

**Comment by MarvinSchenkel** [comment]
Sorry life has been a bit demanding. I can confirm I can reproduce the issue, just need to find some time to actually fix it :-)

**Comment by mac-city** [comment]
Thanks!  From what I've seen, this is going to be amazing!  Setting up a music / media server now ;-)

**Comment by nikscha** [comment]
@MarvinSchenkel No worries, personal life takes priority! You're doing this for free after all 😎

**Comment by MarvinSchenkel** [comment]
I did some digging and the answer is a little bit annoying. You have to ensure that those personal lists are added to your YT Music library. By default, this is only the case for liked music and 'episodes for later'. So in order to solve your issue, you will have to go into the YT Music web app and add those personal playlists to your library.

**Comment by nikscha** [comment]
This fixes it, thank you!

**Comment by nikscha** [comment]
Did you restart the ma server? That did it for me.
Best,
Nikolai Schauer

(sent from mobile, please excuse mistakes and short form)

**Comment by MarvinSchenkel** [comment]
Are you 200% sure your added it to your YT Music library here: 
![image](https://github.com/user-attachments/assets/76af5225-bf0d-474b-8c5d-0c994b3a5c88)

**Comment by mac-city** [comment]
Ugh, I should have thought of that, lol.  Thanks!  That worked!
