### ISSUE TITLE
Home assistant player with spotify can not be controlled (Works with HA Spotify connection)

### ISSUE THREAD

**Issue by distante** [music-assistant/hass-music-assistant#2975]
### What version of Music Assistant has the issue?

2.2.5

### What version of the Home Assistant Integration have you got installed?

2024.9.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

While on MA, trying to play a song into a HA provided player does not work. It just starts and stops what was already on the queue (from another service)

Also, if Spotify did not had that player as target before (from the Spotify app), MA does nothing.

Example Right now:
HA Home assistant integration:
<img width="465" alt="image" src="https://github.com/user-attachments/assets/edb8ca1e-aed5-4be0-8f23-6f5e4f308688">

Music Assistant:
<img width="404" alt="image" src="https://github.com/user-attachments/assets/aaf3a47f-f34b-4cea-bb7a-154a3c0dccef">

### How to reproduce

Add a Medion device to Home assistant, add it as a player on MA.

### Music Providers

Spotify

### Player Providers

Home Assistant

### Full log output

[music-assistant 28.09.log](https://github.com/user-attachments/files/17173922/music-assistant.28.09.log)

### Additional information

The player is the same as the one on this issue https://github.com/music-assistant/hass-music-assistant/issues/2939. A Mediom Player (Frontier Silicon)

### What version of Home Assistant Core are your running

2024.9.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Sorry I am not 100% sure what you are describing above but it sounds like you expect MA and some other software to work together? If so that is not the case. MA works independently of any other software that may be able to play to a device. If this is not what you are asking about then please try and describe the issue again.

**Comment by distante** [comment]
Hi, sorry if I did not describe it correctly.

My expectation is that after adding a player (from Home assistant provider), I should be able to send Spotify music from using Music Assistant to the player and control it.

Currently I can only click Play/pause when the player is already running already, but each song I "send" is not picked up by the player.

I just put an screenshot of the other Spotify integration to show how there is a discrepancy between what the player is really playing and what Music Assistant is showing.

**Comment by OzGav** [comment]
What other player types have you tried? Provide all of the information requested from the troubleshooting page of the docs

**Comment by distante** [comment]
I have done everything I though could affect from the player config, disable TTS, normalization etc, On the music server I also disabled volumen normalization and almost all special settings like cross fade and so on.

I have tried changed all the HTTP profiles and nothing worked.

If you point me out to where I can see more logs I would gladly do it. I setup up the player and providers as log level but I do not see anything helpful.-

**Comment by OzGav** [comment]
Have you confirmed it is only HA player providers that are affected? Have you tried different HA entities?

**Comment by distante** [comment]
Sadly I just have that one player so I can not test another ones.

But when I provided the same radio with the DNLa provider it also failed.

**Comment by OzGav** [comment]
If you install the snapcast provider then you can stream to a browser. Why do you mention radio in your previous reply as your original report was about Spotify?

**Comment by distante** [comment]
Hello again,

Sorry I meant "Radio" as in the Hardware, [this Medion one](https://www.amazon.de/-/en/gp/product/B0BLSS4PHQ/), maybe it is not the correct english word (we use it a lot in Spanish).

I tried with the Snapcast provider and it works correctly there. I can send and control music from Spotify without any issues.

**Comment by OzGav** [comment]
Sorry to say but fixing HA player providers is low priority. This will stay here for now though.

**Comment by distante** [comment]
OK understood. Although when I add the player directly also doesn't work.

**Comment by OzGav** [comment]
If it is a native players then review the docs for assistance then the open and closed issues. If nothing helps then open an issue.

**Comment by distante** [comment]
The other issue was #2939

**Comment by OzGav** [comment]
Yeah unfortunately you are using the two most problematic player providers due to their poor standardisation

**Comment by OzGav** [comment]
Just coming back to this one. Have you tried the different HTTP profiles in the advanced settings? 

![image](https://github.com/user-attachments/assets/fd6e69c2-4dab-4688-86ba-3203ab86e2ae)

**Comment by distante** [comment]
Hello. Yes, I tried it.

**Comment by OzGav** [comment]
So just confirm that you POWER ON the player and then select a track and PLAY NOW and nothing happens? What HA integration have you used to gain access to this device?

**Comment by distante** [comment]
when I do that, nothing happens in the player but I see the track in the MA UI as if it was playing.

In HA I am using the Spotify integration it self. One thing I found out in this days, is that calling set source on the HA integration via script does not work due a missing API call. I do not know if that is related 
https://github.com/home-assistant/core/issues/129122

**Comment by OzGav** [comment]
Have you tried disabling the HA Spotify integration? If Spotify is getting calls from both then that could be the problem.

**Comment by distante** [comment]
That I had not tried, But I tried the Spotify integration itself after MA did not work, there is when I found out it was a MA issue and not something with my account.

**Comment by OzGav** [comment]
OK you can also add the Snapcast provider and try streaming to a browser tab. https://music-assistant.io/player-support/snapcast/

**Comment by distante** [comment]
Snapcast works as expected. 

I also notice now that after I was listening into snapcast, I would Play and Stop the music on the other player, but never change or select a song, It just plays what is already there.

**Comment by OzGav** [comment]
I see I have asked this before actually. Sorry too many issues to be across. So yes definately a player problem. What HA Integration is it?

Not sure what you meant in the last thing you wrote above.

**Comment by distante** [comment]
No problem.

- The player is integrated into Home Assistant with https://www.home-assistant.io/integrations/frontier_silicon
- Using https://www.home-assistant.io/integrations/spotify/ I can correctly assign the player as source and control it (prev, play, stop, next)

**Comment by OzGav** [comment]
Can you try again with beta 7 and integration 2024.11.5

**Comment by distante** [comment]
Thanks! I will try when I'm back home next week.

**Comment by distante** [comment]
So I'm back home and installed the beta versions. Turning the player on/off works, but it just reproduces what was the last track I already got on spotify.

The Error I am seeing now when I try to change tracks is this:

```
Got music, but frontier_silicon only supports playing channels
```

Could it be that MA is trying to send the track directly to the speaker instead of posting it to Spotify?

I also saw this Spotify error but I do not know if it is related:

```
Logger: homeassistant.components.spotify.coordinator
Source: helpers/update_coordinator.py:382
integration: Spotify (documentation, issues)
First occurred: 09:22:19 (3 occurrences)
Last logged: 09:23:19

Unexpected error fetching spotify data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 382, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/spotify/coordinator.py", line 97, in _async_update_data
    audio_features = await self.client.get_audio_features(item.uri)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/spotifyaio/spotify.py", line 518, in get_audio_features
    return AudioFeatures.from_json(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 7, in __mashumaro_from_json__
mashumaro.exceptions.MissingField: Field "danceability" of type float is missing in AudioFeatures instance
```

**Comment by OzGav** [comment]
Yes that is exactly how MA works. It sends a stream directly to the player. I don’t know what you are trying to do as you are posting Home Assistant errors which should have nothing to do with MA.

**Comment by distante** [comment]
I am just given more context in case that is needed...

**Comment by OzGav** [comment]
Have you tried playing to this device from HA? According to this https://github.com/home-assistant/core/issues/84925 the error you posted indicates this device is not supported?

**Comment by distante** [comment]
Before the breaking Spotify API from end November, I could control Spotify from HA using the Spotify integration that uses the API to select the tracks.

What is not possible is to play direct media files into the device.

If you say that MA doesn't interact with the Spotify API but just sends the tracks to the device, then yes, that will not work with my device ☹️

**Comment by OzGav** [comment]
OK closing this as not a MA issue
