### ISSUE TITLE
Sync Group of Snapcast player shows unavailable, while players are available

### ISSUE THREAD

**Issue by coen1111** [music-assistant/hass-music-assistant#2978]
### What version of Music Assistant has the issue?

2.3.0b27

### What version of the Home Assistant Integration have you got installed?

2024.9.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I created a Sync Group of several Snapcast players. Initially they work fine, however after some time the Sync Group becomes Unavailable, while the Players within this Sync Group are available. See the attached screenshots.

<img width="799" alt="2024-09-29 14_03_38-Music Assistant – Home Assistant - Sync group settings" src="https://github.com/user-attachments/assets/28375db0-4de3-494a-a001-6d970ae11623">
<img width="730" alt="2024-09-29 14_03_38-Music Assistant – Home Assistant - Players" src="https://github.com/user-attachments/assets/aa65a004-eb68-4d96-8600-e99f91f6c64f">

### How to reproduce

1. Create a Sync Group of several Snapcast players
2. Wait some time
3. Synch Group becomes unavailable

### Music Providers

All

### Player Providers

Snapcast

### Full log output

[music-assistant.log](https://github.com/user-attachments/files/17179198/music-assistant.log)

### What version of Home Assistant Core are your running

2024.9.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
@SantiagoSotoC

**Comment by SantiagoSotoC** [comment]
It's the first beta you've used and this appeared in the last one? Or first time you create a Sync group ?

**Comment by OzGav** [comment]
Can't recreate this. I have a group sitting there for a few hours?

**Comment by itsteddyyo** [comment]
I used to run into this issue a lot, but it’s been pretty stable for me since version 2.2.0. What worked for me before was deleting the sync group and recreating it, which would keep things stable for a few hours. But ever since the 2.2.0 update, I haven’t seen the problem come back.

**Comment by coen1111** [comment]
I replaced my MA by 2.2.0 and recreated the Sync Group, I will try to see if that works out.

**Comment by OzGav** [comment]
Well the beta should be better. So if this works with 2.2.0 then revert again to the beta and see what happens (after recreating the group in the beta server)

**Comment by coen1111** [comment]
This morning with 2.2.0 the Sync Group has become unavailable again, I also noted that you are not able to configure it once unavailable.

![image](https://github.com/user-attachments/assets/9b1a095e-513a-471c-b808-8dc0b0bda7a4)
![image](https://github.com/user-attachments/assets/b095468d-0ced-4055-a5fe-85f701edd33d)

I disabled 2.2.0 and have installed the latest beta add-on. I there recreated the Sync Group, I will update here what will happen.

**Comment by coen1111** [comment]
I encounter the same issue in 2.3.0b29. This morning a big part of my Snapcast players and the Sync Group where unavailable.

![Screenshot_20241005_065018_Home Assistant](https://github.com/user-attachments/assets/6a12a657-2667-4f2a-860c-0d0f8a9a4bc6)

**Comment by OzGav** [comment]
Do you anything unusual about your network setup? Anything at all that someone may consider non standard with your install. I have a Snapcast group sitting happily on my instance for days now.

**Comment by coen1111** [comment]
The Snapcast players are all Rpi+Hifiboards, which are connected to old stereo players. Since these stereo players have good audio, but terrible stand-by use (typically 20 W or more) I have a power plug to turn everything on/off. This did not give issues before with my Snapcast setup, but it might cause issues for the beta. 

How is the disable state for a player or Sync Group determined now?

**Comment by SantiagoSotoC** [comment]
> The Snapcast players are all Rpi+Hifiboards, which are connected to old stereo players. Since these stereo players have good audio, but terrible stand-by use (typically 20 W or more) I have a power plug to turn everything on/off. This did not give issues before with my Snapcast setup, but it might cause issues for the beta. 
> 
> How is the disable state for a player or Sync Group determined now?

Do you turn off the Raspberry pi ?
