### ISSUE TITLE
Airplay endpoints with duplicated IP addresses

### ISSUE THREAD

**Issue by MarpleA** [music-assistant/hass-music-assistant#2983]
### What version of Music Assistant has the issue?

2.2.6

### What version of the Home Assistant Integration have you got installed?

2024.9.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I use two Raspberry Pi Zeros with piCorePlayer and sharepoint-sync and squeezelite service activated.
When it comes to Airplay speakers I realized an odd behaviour. 
Some of the Airplay endpoint do have the same IP address shown in Music "Assistant -> Settings -> Speakers" even tough they have different IPs and different IDs.

<img width="628" alt="AP_bathroom_setting" src="https://github.com/user-attachments/assets/73ec50bb-67e2-4c92-b1aa-2ed3a47b767a">
<img width="628" alt="AP_diningroom_setting" src="https://github.com/user-attachments/assets/a8635bed-dbe4-4e3c-bfc0-e6553e5d4541">

A restart of the Music Assistant HA Addon does change the IPs. But then they both have IP of the other piCorePlayer.
This doesn't seem to happen to my Airplay Onkyo Receiver.

### How to reproduce

- activate sharepoint-sync on piCorePlayer
- lookup the details under "Assistant -> Settings -> Speakers"

### Music Providers

- Spotify
- tune-in

### Player Providers

- problem: piCorePlayer
- no problem: Onkyo Receiver with Airplay

### What version of Home Assistant Core are your running

2024.9.3

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
Is this maybe a caching thing as I can't recreate it? What browser are you using?

**Comment by MarpleA** [comment]
It seems this was an issue with the  Raspberry Pi Zeros. I had some more trouble with these receivers and therefore I replaced them with Wiim Minis. Since then everything works as it should.

Can be closed
