### ISSUE TITLE
Snapcast silence detection is truncating TTS announcement

### ISSUE THREAD

**Issue by whc2001** [music-assistant/hass-music-assistant#2987]
### What version of Music Assistant has the issue?

2.2.6

### What version of the Home Assistant Integration have you got installed?

2024.9.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When using MASS along with Snapcast (both built-in and external instance), audio gaps in announcements (like TTS) will cause the stream state to toggle between `playing` and `idle`. If the gap just aligns with the 250ms idle detection of MASS, the announcement will be finished forcefully (despite there might still be audio after) and what's playing before is resumed later.

What it looks like in the Snapcast log: [sc.txt](https://github.com/user-attachments/files/17190491/sc.txt)

### How to reproduce

1. Setup MASS and Snapcast instance, add a Snapcast client and connect to HomeAssistant integration
2. Play an audio file with long enough silence in it to the client though MASS with announcement enabled
3. Observe in the Snapserver log that each time silence is detected the state jump to idle
4. MASS would sometimes stop announcement when the state goes to idle, causing the announcement not finished

### Music Providers

Local, Home Assistant

### Player Providers

- Snapcast (problematic)
- Home Assistant through HASS.Agent (works fine)

### Additional information

By inspecting the source code of Snapserver, it looks like the [TCP endpoint](https://github.com/badaix/snapcast/blob/208066e5bb3f77482a62301283a8075912a7e22c/server/streamreader/tcp_stream.cpp#L44) is an instance of [ASIO endpoint](https://github.com/badaix/snapcast/blob/208066e5bb3f77482a62301283a8075912a7e22c/server/streamreader/asio_stream.hpp#L41), which implements the [silence detection function](https://github.com/badaix/snapcast/blob/208066e5bb3f77482a62301283a8075912a7e22c/server/streamreader/asio_stream.hpp#L132) with [adjustable duration in parameters](https://github.com/badaix/snapcast/blob/208066e5bb3f77482a62301283a8075912a7e22c/server/streamreader/asio_stream.hpp#L107). In such case, I have tested to manually specify a long enough `idle_threshold` (e.g. 60000 ms or 1 minute) in the [stream parameters](https://github.com/music-assistant/server/blob/4c6934587f987533c8760f36ff829c2935f604c7/music_assistant/server/providers/snapcast/__init__.py#L588-L592) of the provider, and seems the problem went away without affecting the resume time (it will still detect the `End of Stream` and transition back to `idle` in time).

Here is what the Snapserver log looks like after adding the longer timeout, note that there is only one `playing => idle` which is at `End of Stream`: [sc2.txt](https://github.com/user-attachments/files/17190629/sc2.txt)

### What version of Home Assistant Core are your running

2024.9.3

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Good problem solving but is this a duplicate of this https://github.com/music-assistant/hass-music-assistant/issues/2690

**Comment by whc2001** [comment]
> Good problem solving but is this a duplicate of this #2690

Interesting, on my setup it stops randomly instead of about 75% (I have encountered multiple times that it only plays one sentence then stop). But it does confirm that it's related to Snapcast then. I'll close this and continue in the original issue then, thanks and sorry for that.
