### ISSUE TITLE
Ungrouping players causes master to disappear

### ISSUE THREAD

**Issue by mlowijs** [music-assistant/hass-music-assistant#2995]
### What version of Music Assistant has the issue?

2.2.6

### What version of the Home Assistant Integration have you got installed?

2024.9.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

While playing music to a group, ungrouping a player from the group causes the group master player to disappear.

### How to reproduce

1. Group players
2. Play music
3. Ungroup one of the players
4. The master player disappears from the player list

Video of how to reproduce:

https://share.icloud.com/photos/076QBsOtZn8Kg3QHQG-D3cSQQ

### Music Providers

Spotify, Youtube Music

### Player Providers

Slimproto

### Full log output

[log.txt](https://github.com/user-attachments/files/17216749/log.txt)

### What version of Home Assistant Core are your running

2024.9.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
The video is coming up permission denied. How exactly are you grouping the layers?

**Comment by mlowijs** [comment]
Sorry about that, here it is on Dropbox instead: https://www.dropbox.com/scl/fi/uzh2lu2cyavla19q9oc85/Video-01-10-2024-23-20-01.mp4?rlkey=fwy834zncw268t75w0endc6xq&st=mz4iyndm&dl=0

The grouping/ungrouping is done through the Players list, accessed from the “now playing” bar.

**Comment by OzGav** [comment]
Ok I see it. I don’t have two slimproto devices to test so will have to wait for one of the others

**Comment by HJohannesA** [comment]
I am also having trouble when trying to sync different slimproto endpoints.

I run the following setup:
Music Assistant 2.2.7 (Home Assistant Addon / no Slimproto integration im HA) - also tried with Music Assistant 2.3.0b29 with same problem
2x MA-companion app for windows on Laptop (Win10) and HTPC (Win11)
1x PiCorePlayer on Raspberry Pi 3
2x SqueezePlayer for Android on an old Phone and Tablet

all off them are being autodetected by MA and shown in the "players" section. I can stream music from different sources to all of them simultaniously.

When grouping 2 players it first works perfectly. music is being synced after about 2 seconds and the experience is amazing.
Unfortunately when selecting another track or the next track in the playlist starts playing sync is slightly off again for about 1-2 seconds but after that its being synced again nicely.
I can group 2 individual players.
But when ungrouping the players they disappear and you can only access them again after restarting the MA server.

When trying to group more than 2 players the playback stops all over and even the main player does not play music anymore.
I tried different combinations with my "sqeezebox endpoints" but it seems to be the same issue no matter what kind of clients I use for grouping.

After checking the protocol log of Music Assistant in Home Assistant I stumbled across a strange issue.
I am constantly (20x per second) getting the following log:
"2024-10-12 18:27:47.591 WARNING (MainThread) [aioslimproto.server] Duplicate connection detected for player" followed by a MAC-Adress.
very strange for now is that I cant track down the MAC-Adress  within my network to figure out the device causing the problem..
maybe these two things are related somehow.

**Comment by OzGav** [comment]
Grouping is currently being totally reworked.

**Comment by HJohannesA** [comment]
Thats nice to hear since its such an amazing feature!

just adding - if you dont have 2 slimproto devices its the same problem with grouping 2 MA Companion Apps and trying to degroup them. I think I read somewhere that the Companion App is basically a "slimproto player".

**Comment by OzGav** [comment]
This is fixed in the upcoming beta group changes

**Comment by HJohannesA** [comment]
thats awesome! cant wait for it to release! thanks a lot!

**Comment by OzGav** [comment]
Beta 30 has been released.
