### ISSUE TITLE
MA  jumps more than 1 song in queue 

### ISSUE THREAD

**Issue by gpgmailencrypt** [music-assistant/hass-music-assistant#2998]
### What version of Music Assistant has the issue?

2.2.7

### What version of the Home Assistant Integration have you got installed?

2024.9.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Music stops playing the queue. This bug might be linked with #2893.
The reason seems to be that MA jumps too far when getting to the next song. I tried it with different playlists. In my case the jump was always about 6 to 8 songs further. All songs which are "jumped over" will be marked as already played. 

So the playlist is  faster empty than expected and stops with an empty queue. After reloading the browser the playlist is refilled.

### How to reproduce

Switch off random mode. Watch the playlist in the browser. The next song played is not the next song in queue. All songs in between the "expected" next song and the "played" next song will me moved the the "already played" list.
After playing the last song (there is an empty queue and a full "already played" list). Wait a few seconds and reload the page. Then the queue is full again.

### Music Providers

file system (local files)

### Player Providers

Sonos

### Full log output

empty list which is expected as last song of queue is played

### Additional information

The bug was introduced after version 2.2.1 (which works fine)

### What version of Home Assistant Core are your running

2024.9.3

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
With the volume of requests for assistance on here, Discord and the HA forums we need people to provide the information requested in a concise manner. You are getting this standard response because you have not supplied the information requested in the troubleshooting docs or in the issue report template and we are unable to quickly pinpoint the problem. Please review and supply the requested information for a more timely response to your problem. Thanks for your understanding.

**Comment by cofw2005** [comment]
I have exactly the same issue as described in the problem.

**Comment by OzGav** [comment]
@cofw2005 have you tried other music and player providers to identify exactly where the problem resides?

**Comment by cofw2005** [comment]
I have only SONOS as player. And played mp3 in local files.
I tried right now, here you can see. I am playing a queue with 44 songs.
Previous playing showed there 3 left in the queue.
![2](https://github.com/user-attachments/assets/642d7d9d-811f-4774-b736-4d552c7bac3a)
After that song, it jumped directly 9 songs.
![3](https://github.com/user-attachments/assets/2847dd28-f38f-4348-8ba0-9f7c5fc80d9d)
And again, after this song, it jumped to.
![image](https://github.com/user-attachments/assets/9171d4d3-5549-4273-bbe7-fe30fc7a7ecd)

This behavior happens only when the song playing finished and move to next song automatically. If I click the "next" button, it goes correctly to the next song in the queue.

**Comment by cofw2005** [comment]
by the way, it doesn't matter how the queue is generated, no matter from a album or from a playlist, the queue has same behavior.

**Comment by cofw2005** [comment]
Update: I managed to add a M5Stack ESPHome based media_player for testing purpose.
With this player, the queue runs correctly. No jumping in the queue.
Is it a SONOS problem? What can I do to look for further reasons?

**Comment by OzGav** [comment]
Yes I think it is a Sonos player issue. There are a number of Sonos related issues. I need to go through them and look for double ups.

**Comment by OzGav** [comment]
OK it is likely the issue here is that you are still running the stable server whereas significant improvements have been made in beta. Specifically there are now two providers, one for Series 1 speakers and one for Series 2. You will either need to wait for a future stable release or try and the beta and let us know if that resolves things. You can run both stable and beta on the same host just not at the same time.

**Comment by OzGav** [comment]
@gpgmailencrypt @cofw2005 Are you able to try the beta server to see if this is fixed?

**Comment by cofw2005** [comment]
no, I didn't want to switch from stable to beta server.

**Comment by gpgmailencrypt** [comment]
I tried it with 2.3.0b29 and it works correctly now

**Comment by cofw2005** [comment]
> I tried it with 2.3.0b29 and it works correctly now

👍🏻
