### ISSUE TITLE
[Feature Request] Send Metadata when Casting

### ISSUE THREAD

**Issue by a-pir1** [music-assistant/hass-music-assistant#300]
When casting audio to my Nest Hubs or Google TVs, it just says "Playing Default Media Receiver".  It would be nice if you could push some of the details of the song to it.  (i.e.: Album cover, song title, artist, etc.)

**Comment by erkr** [comment]
Hi, guess you are refereeing the media players in HA?! If so, you can use the option to hide the original players and export new players. The new players have the meta data included

**Comment by erkr** [comment]
That the original chromecast players don't show meta data when casting local media, seems to be an architectural limitation. Raised an issue for that 4 months ago: https://github.com/home-assistant/core/issues/65909

**Comment by a-pir1** [comment]
Changing over to the players under the Music Assistant integration does not cause my chromecasts to output any metadata either.  Still just Default Media Receiver.

**Comment by erkr** [comment]
> Changing over to the players under the Music Assistant ... Still just Default Media Receiver.

That should normally work (will label it as a bug). For Marcel it helps to provide more context:
- How do you initiate casting audio to your Nest Hubs or Google TVs. From the media browser, in music assistant, external app?
- the player started. In the developer tools you can lookup the player states (both the source player and the mass version). 
Best Eric

**Comment by marcelveldt** [comment]
I don't think this is a bug but just documentation about the "mass players"

**Comment by erkr** [comment]
Not sure, he confirmed that he tried the mass players:

> Changing over to the players under the Music Assistant integration does not cause my chromecasts to output any metadata either.  Still just Default Media Receiver.

I was wondering if the Google TV behavior can deviate from a normal CC (other player type). If so its a bug or enhancement to support them

**Comment by marcelveldt** [comment]
Yes, but the actual device itself (the display) will not display what is playing but just "streaming from Music Assistant".
Sending the actual metadata to the device is tricky or maybe even impossible without creating a special Cast receiver.

**Comment by erkr** [comment]
@a-pir1 
We will reopen the issue still persists
