### ISSUE TITLE
Music Assistant 2.2.7 + Home Assistant 2024.10.0

### ISSUE THREAD

**Issue by Links2004** [music-assistant/hass-music-assistant#3003]
### What version of Music Assistant has the issue?

2.2.7

### What version of the Home Assistant Integration have you got installed?

2024.9.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Music Assistant and Home Assistant 2024.10.0 have conflicting pip modules.

```
home-assistant-7f697659b-sw9f4:/config/deps# pip install music-assistant==2.2.4  --target ~/.homeassistant/deps

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
homeassistant 2024.10.0 requires attrs==23.2.0, but you have attrs 24.2.0 which is incompatible.
zhong-hong-hvac 1.0.12 requires attrs<24.0.0,>=23.1.0, but you have attrs 24.2.0 which is incompatible.
Successfully installed aiohappyeyeballs-2.4.3 aiohttp-3.10.8 aiosignal-1.3.1 attrs-24.2.0 frozenlist-1.4.1 idna-3.10 mashumaro-3.13.1 multidict-6.1.0 music-assistant-2.2.4 orjson-3.10.7 typing-extensions-4.12.2 yarl-1.13.1
```

### How to reproduce

Install Music Assistant HASS via HACS --> will not work.

### Music Providers

N/A

### Player Providers

N/A

### Additional information

looks like a new release is needed?

### What version of Home Assistant Core are your running

2024.10.0

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
What are you actually trying to do and how are you doing it. I have 2.2.7 and 2024.10.0 running no problems. I don't understand why you are trying to pip install?

**Comment by Links2004** [comment]
I installed the Music Assistant Integration via HACS in the latest version (2024.9.1), but this did not work.
The logs complained that the package `music-assistant` was not found.


the HA docs explain how to test and install packages here:
https://developers.home-assistant.io/docs/creating_integration_manifest/#custom-requirements-during-development--testing

the `music-assistant==2.2.4` comes from:

https://github.com/music-assistant/hass-music-assistant/blob/5adff083b4a5131f16ccc4a480df30be001a1db8/custom_components/mass/manifest.json#L10-L12

not sure why but the the integration still uses 2.2.4.

**Comment by OzGav** [comment]
Did you install the sever first?

**Comment by Links2004** [comment]
the server is running as a second container and is working.

**Comment by OzGav** [comment]
Did you already have the integration installed when you upgraded HA to 2024.10.0?

**Comment by Links2004** [comment]
no its a new install of the integration on HA 2024.10.0

**Comment by OzGav** [comment]
Yeah ok that might be the problem. You will have to be patient until someone has time to further look at this

**Comment by Links2004** [comment]
No problem, my current automatons with mopidy + snapcast are working,
but Music Assistant has a better UI an more features ;)

**Comment by Links2004** [comment]
It started working after the Home Assistant 2024.10.2 update.
not sure why but it works --> closed
