### ISSUE TITLE
Music skipping issue

### ISSUE THREAD

**Issue by zetiti10** [music-assistant/hass-music-assistant#3004]
### What version of Music Assistant has the issue?

2.0.0b135

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I have an issue when I press the skip button on Music Assistant while playing a playlist on a Denon skeaker: I click once, but there are several songs skipped.

### How to reproduce

1. Install Music Assistant
2. Start a playlist on a Denon CEOL speaker using DLNA/UPnP
3. Press the skip button once

### Music Providers

Deezer

### Player Providers

Issue with: DLNA/UPnP and Denon RCD-N9
Working fine with: Chromecast and Google Nest Hub 2

### Full log output

[Logs](https://github.com/user-attachments/files/17265845/Music_Assistant_logs.txt)

### Additional information

[Video](https://github.com/user-attachments/assets/ec3aa9f7-8d8a-414f-b65c-2fe0980966f0)

### What version of Home Assistant Core are your running

2024.8.3

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
Do you have queue flow mode on?

**Comment by zetiti10** [comment]
Yes, it is enabled

**Comment by OzGav** [comment]
Have you tried each of the different streaming profiles?

**Comment by OzGav** [comment]
Actually you are also running a version which is very old. Update the server as well.

**Comment by zetiti10** [comment]
I will try AirPlay

**Comment by zetiti10** [comment]
Hello,
I tried AirPlay to play music and it works fine.
Thank you!
