### ISSUE TITLE
YouTube Music only shows Episodes for Later in playlist (Auto Playlist) instead of my playlists

### ISSUE THREAD

**Issue by mac-city** [music-assistant/hass-music-assistant#3009]
### What version of Music Assistant has the issue?

2.2.7

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

YouTube Music only shows Episodes for Later in playlist (Auto Playlist) instead of my playlists.

### How to reproduce

Open Music Assistant and click on playlists

### Music Providers

YouTube Music

### Player Providers

YouTube Music

### What version of Home Assistant Core are your running

2024.10.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Alternative

**Comment by OzGav** [comment]
@MarvinSchenkel

**Comment by MarvinSchenkel** [comment]
Duplicate of https://github.com/music-assistant/hass-music-assistant/issues/2973
