### ISSUE TITLE
MA's HA MediaPlayers entities become unavailable with every HA restart. Manual MA integration reload fixes issue.

### ISSUE THREAD

**Issue by gith-account** [music-assistant/hass-music-assistant#3025]
### What version of Music Assistant has the issue?

2.2.7

### What version of the Home Assistant Integration have you got installed?

2024.9.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Player 1: Moode Audio Player 5.3.1 with MPD 0.20.23
Player 2: Moode Audio Player 7.3.0 with MPD 0.22.8_p0x3

in Home Assistant via Music Player Daemon Integration (MPD)

in Music Assistant as Home Assistant MediaPlayers

With every restart of Home Assistant (or, for example, an update of Music Assistant), the Music Assistant player entities become unavailable. A reload of the Music Assistant integration makes them available again.

### How to reproduce

Restart Home Assistant with the described player configuration

### Music Providers

Music Assistant, Radio Browser, Youtube Music, Spotify

### Player Providers

Home Assistant MediaPlayers

### Full log output

2024-10-08 18:22:12.531 WARNING (MainThread) [music_assistant] Error loading provider(instance) Home Assistant: 502, message='Invalid response status', url='ws://supervisor/core/api/websocket' (will be retried later)
2024-10-08 18:24:12.550 INFO (MainThread) [music_assistant] Loaded plugin provider Home Assistant
2024-10-08 18:24:12.598 INFO (MainThread) [music_assistant] Loaded player provider Home Assistant MediaPlayers

### Additional information

MASS related HA errors/warnings after HA restart:

----

Logger: homeassistant.components.media_player
Source: helpers/entity_platform.py:361
integration: Media player (documentation, issues)
First occurred: 18:22:32 (1 occurrences)
Last logged: 18:22:32

Error while setting up mass platform for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/mass/media_player.py", line 179, in async_setup_entry
    async_add_entities([MassPlayer(mass, player.player_id)])
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mass/media_player.py", line 228, in __init__
    super().__init__(mass, player_id)
  File "/config/custom_components/mass/entity.py", line 32, in __init__
    manufacturer=player.device_info.manufacturer or provider.name,
                                                    ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'name'

----

Logger: homeassistant.components.media_player.const
Source: helpers/deprecation.py:197
integration: Media player (documentation, issues)
First occurred: 18:22:32 (10 occurrences)
Last logged: 18:22:32

MEDIA_CLASS_TRACK was used from mass, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaClass.TRACK instead, please report it to the author of the 'mass' custom integration
MEDIA_TYPE_ALBUM was used from mass, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaType.ALBUM instead, please report it to the author of the 'mass' custom integration
MEDIA_TYPE_ARTIST was used from mass, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaType.ARTIST instead, please report it to the author of the 'mass' custom integration
MEDIA_TYPE_PLAYLIST was used from mass, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaType.PLAYLIST instead, please report it to the author of the 'mass' custom integration
MEDIA_TYPE_TRACK was used from mass, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaType.TRACK instead, please report it to the author of the 'mass' custom integration

### What version of Home Assistant Core are your running

2024.10.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Alternative

**Comment by gith-account** [comment]
Found similar reports in this discussion: https://github.com/orgs/music-assistant/discussions/2882

**Comment by OzGav** [comment]
You have not ATTACHED the full MA log. (Please don't PASTE it).

Your title says the problem occurs after a HA restart. Your description says it occurs after a MA or HA restart? 

How long have you waited to see if they get discovered?

**Comment by gith-account** [comment]
> You have not ATTACHED the full MA log. (Please don't PASTE it).

See attachment.

Entire server restarted around 16:22.
MA player entities become available.
HA restarted around 16:26.
MA player entities become unavailable and remain so until the MA integration is manually reloaded (or the entire server is restarted).

The relevant log entry is probably "WARNING (MainThread) [music_assistant] Error loading provider(instance) Home Assistant: 502, message='Invalid response status', url='ws://supervisor/core/api/websocket' (will be retried later)".

> Your title says the problem occurs after a HA restart. Your description says it occurs after a MA or HA restart?

See further observations above. It occurs with HA restarts.

> How long have you waited to see if they get discovered?

Hours. This is a permanent issue after HA restarts. The MA player entities remain unavailable until a manual reload of the MA integration, which brings them back immediately. On the contrary, reloading "Home Assistant MediaPlayers" under "Player Providers" in the MA settings alone does not.

The MPD entities are available and work perfectly fine in HA after HA restarts and can be selected and used from within MA, but MA's media player entities of these players will remain unavailable until the MA integration is reloaded.

[music-assistant.log](https://github.com/user-attachments/files/17437504/music-assistant.log)

**Comment by OzGav** [comment]
Is it only MPD entities? Have you tried other HA players (I don’t see this with my HA players but I don’t have MPD)?

**Comment by gith-account** [comment]
> Is it only MPD entities? Have you tried other HA players (...)?

I can only confirm it with the MPD entities. I have no other HA players in use.

**Comment by OzGav** [comment]
Please confirm this is still a problem with the 2024.11.2 version of the integration

**Comment by gith-account** [comment]
The problem persists with version 2024.11.4.

**Comment by marcelveldt** [comment]
I was never able to reproduce this issue however after some digging I think I may have found a tiny race condition that could explain this issue.

I just released 2024.11.5 as prerelease (you may need to adjust HACS to show beta releases) - please test that together with the beta server 2.4.0b6

Please test if that fixes the issue (or wait for the next stable release)
Thanks!

**Comment by OzGav** [comment]
@gith-account we will close this soon assuming fixed

**Comment by gith-account** [comment]
Sorry for the delayed response. I waited for the stable release. I am now on version 2024.12.1 and the problem seems to have been resolved. Thanks!
