### ISSUE TITLE
Works great, after 20 minutes Integration goes to 'Fails to connect'.  Adding the port allows it to connect, but fails again after 20 minutes or so.

### ISSUE THREAD

**Issue by Someguitarist** [music-assistant/hass-music-assistant#3029]
### What version of Music Assistant has the issue?

2024.10.2

### What version of the Home Assistant Integration have you got installed?

2024.9.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

The Music Assistant integration says 'Failed to connect at http://0.0.0.0'.  If I click 'Configure' and change it to 'http://0.0.0.0:8095' it works!  I can play music through all my speakers and everything no issue.  However, it looks like at about ~20-30 minutes it changes back to 'Failed to connect at http://0.0.0.0'.  Again, adding the port seems to let it work with no issues for 30 minutes or so.

I'm running both in containers, and I have tried to chmod 777 everything in Home Assistant and Music Assistant just to see if it was permissions related, and I tried removing MA, removing the integration, removing it from HACS, rebooting, and reinstalling.

What's interesting is after that it says it's discovered a MA instance, and if I click on it it says something like 'MA instance found at http://0.0.0.0.  Would you like to configure?'  If I click yes, it says it failed to add it.  Then I can see it as a failed integration and add the port and it works.  If I don't configure it from there and manually add it with the port number, it works for 20 minutes or so then goes back to failed.

I'm stumped!  Any ideas?

### How to reproduce

Just add MA integration to HA instance and wait 30 minutes or so.

### Music Providers

All work

### Player Providers

All work

### Full log output

[home-assistant_2024-10-13T14-30-11.744Z.log](https://github.com/user-attachments/files/17355969/home-assistant_2024-10-13T14-30-11.744Z.log)

### Additional information

I don't see anything in the logs that mention any issues.  It's weird that it works fine though up until it seems to lose the port number.

### What version of Home Assistant Core are your running

2024.10.2

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
You have attached an excerpt of the HA log instead of the whole MA log

**Comment by Someguitarist** [comment]
Dang, yes.  Sorry, I had searched the github but I didn't know the correct terms to find the issue.  Sorry for the reproduced issue, I'll close this one.  Hope it gets resolved soon, as the family only uses HA and I'm sure I can't get them to look into using another log in and UI and stuff  :/.

**Comment by OzGav** [comment]
I'm about to post there to clarify what settings are needed that should resolve this

**Comment by Someguitarist** [comment]
Oh god, awesome!  Thank you so much!
