### ISSUE TITLE
V.06b2: player control usability issue

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#303]
I noticed that one can't start a CC group cast (pressing play in the group player) when one of the child players is playing their own queue. Pausing that player doesn't work. The child player will resume the own queue instead of starting the group queue.

Update (my two cents):
Thinking this over, I'm missing the stop option. 
- When pausing; the current behavior can be preferred. So pause / resume the group controls the individual players.
- stop releases the individual player, without the need to clear the individual players queue. Group control will play the group queue.

**Comment by marcelveldt** [comment]
please retest this one with beta 5 (or 6)

**Comment by erkr** [comment]
I will do that

**Comment by erkr** [comment]
After the tests there where these related errors in the log: 
``` 
Logger: frontend.js.latest.202206010
Source: components/system_log/__init__.py:190 
First occurred: 20:21:23 (180 occurrences) 
Last logged: 21:30:05

http://192.168.178.47:8123/lib/mass/mass.iife.js:28:727629 TypeError: undefined is not an object (evaluating 'this.queues[n].elapsed_time=e.data')
```
