### ISSUE TITLE
[Apple Music] Reauthentication for Apple Music fails (401 - Unauthorized)

### ISSUE THREAD

**Issue by voydz** [music-assistant/hass-music-assistant#3038]
### What version of Music Assistant has the issue?

2.3.0b29

### What version of the Home Assistant Integration have you got installed?

2024.10.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

My Apple Music access token is expired. So I tried to reauthenticate today. I followed the steps in the Apple Music configuration documentation, but after I entered the access token I got an 401 Unauthroized. I tried to reload the Music Provider, I tried to deactivate and activate it again and I tried to restart MA, but nothing worked.

I reused the already existing Music Provider configuration. Deleted the old token from the music token field and entered the new one. 

### How to reproduce

* Setup Apple Music
* Follow the instructions on the docs
* Will fail with said error

### Music Providers

* Apple Music

### Player Providers

not applicable

### Full log output

[music-assistant.log](https://github.com/user-attachments/files/17392832/music-assistant.log)

### What version of Home Assistant Core are your running

2024.10.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by spirit0607** [comment]
Same here with a complete new Setup

**Comment by OzGav** [comment]
@MarvinSchenkel

**Comment by MarvinSchenkel** [comment]
Can you try logging out and in again on music.apple.com before obtaining the token? If that doesn't work, we have some work to do :-)

**Comment by Laflamme** [comment]
I'm facing the same issue and it persists after logging out and in again on music.apple.com to obtain a new token.

**Comment by voydz** [comment]
@MarvinSchenkel Same for me. I double checked, that I copied all of the token. (Not that I am saying, this happened to me before ... 😂 )

**Comment by magurac** [comment]
Add me to the list. Issue started this morning. Tried to re-auth with no luck. 
2024-10-16 05:14:12.663 WARNING (MainThread) [music_assistant.music] Sync task for Apple Music completed with errors
2024-10-16 09:46:03.450 ERROR (MainThread) [music_assistant.webserver] Error handling message: player_queues/play_pause: 'songList'
player_queues/play_media: 401, message='Unauthorized', url='https://api.music.apple.com/v1/catalog/us/songs/184335777?include=artists,albums'

**Comment by WhiteJamal** [comment]
Glad to know It wasnt just me, I've been trying to troubleshoot for about an hour! Trying multiple computers/browsers to get a token and nothing! (I just set it up last night and was worried the integration had this issue daily)

**Comment by MarvinSchenkel** [comment]
2.2.8 is available with a fix! Sorry about this, our dev token expired today. We will make sure it will get auto-updated with every release so this doesn't happen again :-).

**Comment by kuduacz** [comment]
I have same issue on 2.2.8😔

**Comment by JDogg016** [comment]
Does not work for me.  On 2.2.8

**Comment by DavidFuchs** [comment]
I'm on 2.2.8. I've signed out of Apple Music and back into it. Copy/pasted the new 'media-user-token' and still get a 401.

Great work on the project, by the way! One of my favourite HASS addons.

**Comment by chasut** [comment]
Same issue on 2.3.0b29.  My original token expired a couple of weeks ago but things were working just fine until today.  logged in and got a new token but it is not accepted with the 401 error.

**Comment by sbeverly85** [comment]
Same issue on 2.2.8 release here.

**Comment by chasut** [comment]
I just looked at the release, and the PR for the fix is showing in 2.2.8 but it is not in the Beta channel.  But it doesn't look like it is fully addressed yet anyway.

**Comment by MarvinSchenkel** [comment]
How about 2.2.9 people? Be aware this fix is not yet in beta, we will push out a new beta soon with all kinds of changes, including this fix.

**Comment by udochrist** [comment]
Working again for me with Apple Music. Thanks for the fix.

**Comment by chasut** [comment]
Thank you for the quick response on this one.
Is this fix to be merged into the Beta branch anytime soon?
