### ISSUE TITLE
HA media player card not showing track information or cover art

### ISSUE THREAD

**Issue by MaverikGoose44** [music-assistant/hass-music-assistant#3040]
### What version of Music Assistant has the issue?

2.2.7

### What version of the Home Assistant Integration have you got installed?

2024.9.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

The media player card in HA does not show cover art or track information.  This media player card is associated with the Music Assistant integration.  The media player card associated with the same device via Chromecast integration does show cover art and track information.
![HA_MA_media-card](https://github.com/user-attachments/assets/2c559e6d-3271-4af3-bf7a-06b02af98c45)

### How to reproduce

add media player card for entity integrated from MA

### Music Providers

Spotify

### Player Providers

Spotify

### What version of Home Assistant Core are your running

2024.10.2

### What type of installation are you running?

Home Assistant Core

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
You haven't listed the correct player provider. I assume Cast or are you using the HA Player?

**Comment by MaverikGoose44** [comment]
Honestly, I'm not sure, but I want to say both.  As I mentioned, the one that is through the Chromecast integration shows the cover art and track info. The other card (the integration shows 'Music Assistant') is the one that doesn't show cover art or track info.  I did install the HA player in MA.

**Comment by OzGav** [comment]
You should not use the HA player for cast players. You should be adding the device directly to MA. If you are happy with MA then you should remove the Cast integration from HA and just use the MA players.

I have many cast players and the media cards all display correctly

**Comment by MaverikGoose44** [comment]
For your Cast players/media cards -- any reason why my Spotify tracks/playlists do not show up?  They show up on the MA player.
![image](https://github.com/user-attachments/assets/780bb985-2ee2-4dd6-8ecc-ebfb09f94d08)
![image](https://github.com/user-attachments/assets/87d4b707-efad-4fa0-b0fc-d40592ce0111)

**Comment by OzGav** [comment]
You have to ensure a MA player is selected. Is that bottom pic the HA media view? If so, change the player bottom right.
