### ISSUE TITLE
host cannot contain ‚:‘

### ISSUE THREAD

**Issue by udochrist** [music-assistant/hass-music-assistant#3041]
### What version of Music Assistant has the issue?

2.2.8

### What version of the Home Assistant Integration have you got installed?

2024.9.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

the log shows an invalid ‚url‘. it looks like an ip containing a port number. the ip is the ip of my home assistant server. 
i have no idea of the effects of that error. 

i‘ve not found any reference to that ip in my config. 

### How to reproduce

start music assistant

### Music Providers

using apple. however playing music it not the issue. 

### Player Providers

airplay, dlna 

### Full log output

[music-assistant.log](https://github.com/user-attachments/files/17407917/music-assistant.log)

### What version of Home Assistant Core are your running

2014.10.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
This will get looked at soon.

**Comment by Sticky12** [comment]
I have this same error in my logs on version 2.2.9. I am unable to play music, I'm using YouTube music.

**Comment by OzGav** [comment]
It is a problem with the DLNA provider. If you have a different player then use that.

**Comment by udochrist** [comment]
the issue seems resolved after updating to 2.3.0
