### ISSUE TITLE
Network folder name not displayed in folder browser

### ISSUE THREAD

**Issue by jo-me** [music-assistant/hass-music-assistant#3045]
### What version of Music Assistant has the issue?

2.2.9

### What version of the Home Assistant Integration have you got installed?

2024.9.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

After newly adding a remote file share (and changing it's name in a second step), the folder browser shows some generated names for the remote file shares:

![image](https://github.com/user-attachments/assets/12296eaf-2ee5-4ae9-a945-4f691dcf9c9e)

![image](https://github.com/user-attachments/assets/58218822-1f96-469a-b4af-e441b32b0d7d)

### How to reproduce

1. Create a new filesystem provider for remote shares.
2. Change its name to something like "Music"
3. Open the browse tab to browse the file systems

==> wrong name shown

### Music Providers

filesystem provider for remote shares.

### Player Providers

not relevant for browsing, but I do have Chromecast players

### Full log output

[music-assistant.log](https://github.com/user-attachments/files/17440146/music-assistant.log)

### What version of Home Assistant Core are your running

2024.10.3

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by jo-me** [comment]
Both folders show the correct content and are indexed correctly as far as I can tell, so it seems just to be an issue with renaming the provider

**Comment by OzGav** [comment]
The browse view has limited functionality. No provider gets renamed there. I’ll ask Marcel if he wants to change this.

**Comment by OzGav** [comment]
This will be fixed in due course

**Comment by OzGav** [comment]
This has been fixed

**Comment by jo-me** [comment]
Confirmed!  
Thank you!
