### ISSUE TITLE
Music Assistant doesn't delete  media players or media player groups. 

### ISSUE THREAD

**Issue by Fatalmose** [music-assistant/hass-music-assistant#3046]
### What version of Music Assistant has the issue?

2024.9.1

### What version of the Home Assistant Integration have you got installed?

2024.10.3

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Media players which are created into Google Home and afterwords deleted do not disappear .
They are just marked as unreachable or inactif but no way you can delete them.
Even media players you delete in de Google Cast integration stay present into the Music Assistant integration with no way to delete them.
At the moment i have 30 active media players entities while the MA integration is showing 45.
![IMG_0610](https://github.com/user-attachments/assets/5fec3996-c94c-439d-87b5-89267da5c3d5)

### How to reproduce

Create a Media player group into Google Home.
It will appear into MA and HA.
Delete the created media player group into Google Home.
It will not disappear in the MA.

### Music Providers

Music Assistant

### Player Providers

Google Cast.
Airply.

### What version of Home Assistant Core are your running

2024.10.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Your picture is not showing these players in MA, those are entities in HA. Confirm you no longer see them in the MA UI? Have you then restarted HA?

**Comment by OzGav** [comment]
Yes might be a HA issue but I will ask

**Comment by Fatalmose** [comment]
Many thanks…

**Comment by OzGav** [comment]
You should be able to remove these by deleting the device that these relate to. So click on the entity, then the menu and then DEVICE INFO

![image](https://github.com/user-attachments/assets/09268a2a-3c05-469c-96fa-937f4b5b9815)

Then click on the device type which in the pic below is DLNA Digital Media Renderer

![image](https://github.com/user-attachments/assets/0c98e800-e086-4b0d-81c2-000adbe8d7d3)

Now find the device you want to delete, click on the menu and then DELETE. This will also remove the entity

![image](https://github.com/user-attachments/assets/33917687-197e-4a1b-a630-21465bf1ed1c)

**Comment by Fatalmose** [comment]
Yes indeed it’s a way of doing.
But the MA integration doesn’t show its entities or imported média players
separately as you can see on the picture.
You have to delete them all.
Which i did.
Afterwords there is a rescan that reintegrates the online média players and
their intities.
And yes , the off line média players or groups are deleted and do not show
of anymore.
But now I have to reprogram them into HA dashboards and automations…
It’s like that….
Thanks for the help…

**Comment by Fatalmose** [comment]
I found a way…
Click on the
MA integration.
Click on devices.
Click on the device you want to delete.
Click on the tree dots and that’s it.

**Comment by OzGav** [comment]
S you have discovered you can delete orphaned players from HA just fine. In normal circumstances if both MA and HA are running and you delete a player from MA, it will automatically be cleaned up in HA but if the HA integration is not running that could fail.

I think this issue can be closed?

**Comment by Fatalmose** [comment]
Yes indeed…
