### ISSUE TITLE
NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by Ripper6666** [music-assistant/hass-music-assistant#3049]
### What version of Music Assistant has the issue?

2.3.0b30

### What version of the Home Assistant Integration have you got installed?

2024.10.3

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

ERROR (MainThread) [music_assistant.webserver] Error handling message: players/cmd/play_pause: 'NoneType' object has no attribute 'split'

### How to reproduce

start music assistant

### Music Providers

Apple Music

### Player Providers

airplay, dlna

### Full log output

[d5369777_music_assistant_beta_2024-10-19T13-15-46.981Z.log](https://github.com/user-attachments/files/17445340/d5369777_music_assistant_beta_2024-10-19T13-15-46.981Z.log)

### What version of Home Assistant Core are your running

2024.10.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Alternative

**Comment by OzGav** [comment]
Please attach the full log. That is an excerpt.

What player provider were you using when this occurred? Or are you saying from the above that it happens with DLNA and Airplay?

**Comment by OzGav** [comment]
@MarvinSchenkel Another user reported this in #2692 and believes they have narrowed it down to Apple Music?

**Comment by hosh0815** [comment]
[music-assistant_log.log](https://github.com/user-attachments/files/17445607/music-assistant_log.log)
![421e74d20743abc3fd2138bf92726b2f3c4349976e8375ae0facfc6608f85f7203f4a15f57f14b06b5a81e97435dbdf19246840987fb7e61328a262bf38a231a](https://github.com/user-attachments/assets/3692f4fb-95ad-4fe3-882a-d156a3856d3d)

**Comment by chasut** [comment]
I am seeing this as well.  It is only with the Apple Music provider in 2.3.0b

**Comment by chasut** [comment]
Just updated to 2.3.0.b31 and I am able to play Apple Music again.

Thank you

**Comment by OzGav** [comment]
@Ripper6666 please confirm this is also fixed for you?

**Comment by hosh0815** [comment]
First look: works fine

**Comment by Ripper6666** [comment]
works fine - thanks!!
