### ISSUE TITLE
Tunein favorites not showing when tunein has a custom URL

### ISSUE THREAD

**Issue by ugenit** [music-assistant/hass-music-assistant#305]
Tunein stations don't show up when a custom URL is set in tunedin. 
If I remove the custom URL station on tunein then the stations do show on mass.

**Comment by marcelveldt** [comment]
I do not even know Tunein has such a feature :-)
Can you tell me step by step where you can enter this custom url ?

**Comment by ugenit** [comment]
Hi Marcel,

Custom urls can only be added on the mobile app. There's a add url button
on the library list.

It's straight forward. Let me know if you can't find it.

Regards
Ugen

**Comment by ugenit** [comment]
Hi Marcel,

Custom urls can only be added on the mobile app. There's a add url button
on the library list.

It's straight forward. Let me know if you can't find it.

Regards
Ugen

**Comment by ugenit** [comment]
Hi Marcel,

Custom urls can only be added on the mobile app. There's a add url button
on the library list.

It's straight forward. Let me know if you can't find it.

Regards
Ugen

**Comment by ugenit** [comment]
By the way thanks for the great add-on 👍

**Comment by marcelveldt** [comment]
Installed the TuneIn app and logged in with my personal account. There is no "add url" button in the library. Maybe some old phased out feature or something ?

**Comment by ugenit** [comment]
It's under 'my library'

**Comment by marcelveldt** [comment]
I understand but well, in my case it's not there ;-)

**Comment by ugenit** [comment]
https://help.tunein.com/what-is-a-custom-url-ryq7lcR9dvz

**Comment by marcelveldt** [comment]
I get a 404 on that link so I guess this is not available in my country ?
If you want you may send me your tunein username per PM on discord or mail so I can have a look at the API response

**Comment by ugenit** [comment]
Ok will send you my username

**Comment by ronaldvandervegt** [comment]
I have the exact same problem.

Here's a screenshot of the mobile interface, with the 'Aangepaste URL' (custom URL) button:
![tunein_customurl](https://user-images.githubusercontent.com/58534099/174613135-99abf5ee-19bb-445b-9eec-b341f029b0cc.png)

If I go to https://www.radio-browser.info/ and I search for a radio station I can add this URL for instance, in Intune:
https://radio.virginradio.co.uk/stream or https://radio.virginradio.co.uk/stream?aw_0_1st.platform=vr-web

In TuneIn it will play, perfectly fine. 
But then Music Assistant shows the Radio button greyed out.

**Comment by marcelveldt** [comment]
I found it and fixed the issue. Next patch version of MA (2022.6.5) will contain the fix
