### ISSUE TITLE
BBC Radio Stream stops playing in b31

### ISSUE THREAD

**Issue by ministryofsillywalks** [music-assistant/hass-music-assistant#3056]
### What version of Music Assistant has the issue?

2.3.0b31

### What version of the Home Assistant Integration have you got installed?

2024.10.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

BBC Radio Stream stops playing after a while.
Worked well until b31.

### How to reproduce

Play BBC Radio stream and wait
http://lstn.lv/bbc.m3u8?station=bbc_6music&bitrate=320000

### Music Providers

Radio

### Player Providers

Airplay

### Full log output

[music-assistant.log](https://github.com/user-attachments/files/17451546/music-assistant.log)

### What version of Home Assistant Core are your running

2024.10.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by ministryofsillywalks** [comment]
Was broken before and fixed.
Now seems broken again.
Old issue:
https://github.com/music-assistant/hass-music-assistant/issues/2818

**Comment by marcelveldt** [comment]
I think I have found the root cause of this issue (finally!) - it turns out a bug in ffmpeg 6.1 (which we have in our base image) which is fixed in later version. That explains why my dev machine doesnt have the issue (ffmpeg 7). There is no newer ffmpeg version available yet for alpine and I dont really feel happy to build the binaries myself but I found a workaround.

Please test next beta, beta 32. Thanks!

**Comment by ministryofsillywalks** [comment]
Thanks for the quick fix. Will test it tomorrow once everyone is awake.

**Comment by marcelveldt** [comment]
beta33 is the correct version, beta32 contained another issue and has been retracted

**Comment by ministryofsillywalks** [comment]
Stream has been playing without any issues for over an hour now.
I would say it's fixed.
Thanks a ton!
