### ISSUE TITLE
Error when adding Radio station

### ISSUE THREAD

**Issue by de666** [music-assistant/hass-music-assistant#3065]
### What version of Music Assistant has the issue?

2.3.0b33

### What version of the Home Assistant Integration have you got installed?

2024.10.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When adding the [this](https://www.radioswissclassic.ch/en/reception/internet) radio station
with the following streaming url
[http://stream.srg-ssr.ch/m/rsc_it/aacp_96](http://stream.srg-ssr.ch/m/rsc_it/aacp_96)
Music Assistant shows the following error and the station can not be added
`'dict' object has no attribute 'startswith'`

### How to reproduce

- Radio
- Add item from url
- Insert [http://stream.srg-ssr.ch/m/rsc_it/aacp_96](http://stream.srg-ssr.ch/m/rsc_it/aacp_96)

### Music Providers

Filesystem (local)
Music Assistant
RadioBrowser

### Player Providers

Chromecast
Snapcast
HomeAssistant

### Full log output

```
2024-10-23 08:40:12.419 ERROR (MainThread) [music_assistant.webserver] Error handling message: music/radios/get_radio: 'dict' object has no attribute 'startswith'
```

### Additional information

It works well with other radio stations like this
[http://swingfm.ice.infomaniak.ch/swingfm-128.mp3](http://swingfm.ice.infomaniak.ch/swingfm-128.mp3)

### What version of Home Assistant Core are your running

2024.10.3

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

**Comment by marcelveldt** [comment]
I cant reproduce this - anyone else ?

**Comment by OzGav** [comment]
No just added it and it works fine

**Comment by de666** [comment]
Can I enable some sort of debug log level to help you?

**Comment by OzGav** [comment]
@de666 any chance you can install another version of MA such as in docker or on a separate HA instance on a RPi as we cannot reproduce this. It would appear to be something unique to your situation either the HA installation you have setup or some network configuration problem.

**Comment by de666** [comment]
> @de666 any chance you can install another version of MA such as in docker or on a separate HA instance on a RPi as we cannot reproduce this. It would appear to be something unique to your situation either the HA installation you have setup or some network configuration problem.

It works using home assistant OS + music assistant addon
