### ISSUE TITLE
Cannot set player volume by scrolling anymore

### ISSUE THREAD

**Issue by lexam79** [music-assistant/hass-music-assistant#3070]
### What version of Music Assistant has the issue?

2.3.0rc2

### What version of the Home Assistant Integration have you got installed?

2024.10.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Up until a few versions ago, I was able to control the player volume using the mouse wheel over the volume bar. This is not happening anymore.

### How to reproduce

Just try to scroll the mouse wheel over the volume bar

### Music Providers

N/A (I use samba share and Apple Music)

### Player Providers

N/A (I use Sonos and Airplay)

### What version of Home Assistant Core are your running

2024.10.3

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

**Comment by marcelveldt** [comment]
Small correction: It should have been disabled only on the player select sidebar but it was accidentally disabled everywhere. 
I just fixed that - available in next version

**Comment by lexam79** [comment]
Indeed, it seems to be fixed. Thank you!
