### ISSUE TITLE
Squeezebox Players Do Not Work Without Internet Connection

### ISSUE THREAD

**Issue by doctorgaul** [music-assistant/hass-music-assistant#3071]
### What version of Music Assistant has the issue?

2.2.9

### What version of the Home Assistant Integration have you got installed?

2024.10.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I'm trying to set up a Squeezebox player (specifically a PiCorePlayer and the Music Assistant Companion app).  When I go to Providers->Player Providers and click on "Slimproto (Squeezebox players)" I'm taken to a blank setup page and about 30-60 seconds later I get the following error popup:

    Failed to install package aislimproto==3.0.1 error: Failed to read `--find-links1 URL: https://wheels.home-assistant.io/muslinux/ Caused by: Could not connect, are you offline? Caused by: Request failed after 3 retries Caused by: error sending request for url (https://wheels.home-assistant.io/muslinux/) Caused by: client error (Connect) Caused by: dns error: failed to lookup address information: Try again Caused by: failed to lookup address information: Try again

When HA/MA is connected to the internet, setting up the new player works without incident.  Prior versions of Music Assistant worked fine without ever having an internet connection, and a huge part of the reason I selected Home Assistant as my smarthome platform in the first place is that it's open source and designed to work completely offline.  What's changed that I now can't even set up a player without an internet connection?

### How to reproduce

1. Disconnect MA frominternet
2. Try to set up Squeezebox player

### Music Providers

N/A, not related to music providers

### Player Providers

Squeezebox

### Full log output

[music-assistant.log](https://github.com/user-attachments/files/17509238/music-assistant.log)

### What version of Home Assistant Core are your running

2024.10.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by marcelveldt** [comment]
The players do not need an internet connection. The server does. Why would you not have internet access on the server?

**Comment by doctorgaul** [comment]
Because it doesn't need it.  Because I keep my entire smart home system offline for security and privacy.  Is it your intention to change MA to require an always-on internet connection?

**Comment by marcelveldt** [comment]
The server (both HA and MA) need internet access - at least on startup but also to fetch metadata and lots of other things.
That requirement has always been there - you will run into tons of issues without something as basic as internet access.

Can't you just setup some basic firewall rules and just only allow outbound port 80 and 443 from the HA server ?

For the record: This requirement has always been there, you were just lucky that it worked before.
I don't treat this as issue but as feature request. Go ahead and file a feature request if you like to see this implemented.
At enough interest we can see what we can do to allow a 100% offline mode.

**Comment by doctorgaul** [comment]
> The server (both HA and MA) need internet access 

What a disappointing response.  It is clearly not true that HA or MA "need" internet access, as MA has been working fine on a fully isolated LAN for many months, and HA for well over a year.

> also to fetch metadata and lots of other things

This is not "needed" for the player to accomplish its core function of integrating music playback with the Home Assistant platform.  Why on earth would you design the software to _completely fail_ at basic tasks like adding local network players just because it lacks a demonstrably unnecessary internet connection?  I'm not trying to be rude with this question, I legitimately don't understand this design choice.  It strikes me as antithetical to the entire Home Assistant ethos.

>I don't treat this as issue but as feature request. Go ahead and file a feature request if you like to see this implemented.

I will do so, but I'm pulling my support from the project in the meantime.  Perhaps not a lot by raw dollar amount, but as a user who isn't a tech professional, I do try to contribute what I can to the projects I value, and it sounds like you folks are taking MA in a direction that is no longer useful for me.  

It's very disappointing that a project which claims to value user privacy and control would be designed - actively _changed_ - to break fully-local tasks in the absence of an unnecessary always-on internet connection.  I do hope you'll reconsider this approach.
