### ISSUE TITLE
Progress not updating/syncing, including current playing track until play/pause

### ISSUE THREAD

**Issue by tbgoose** [music-assistant/hass-music-assistant#3074]
### What version of Music Assistant has the issue?

2.3.0

### What version of the Home Assistant Integration have you got installed?

2024.10.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Music progress / status not being updated. It will update when I pause and play a track again, but then continues to stall until next interaction. Changing volume also forces the update.

### How to reproduce

Play anything form any of my providers to google cast device added as MA player

### Music Providers

YTM
Plex Media Server
Radio

### Player Providers

Google Cast device added as player in MA (not HA Cast integration)

### Full log output

https://pastebin.com/cyTtbSQS

### Additional information

Some videos showing the behaviour. In all instances music is playing.
![Screen Recording 2024-10-25 164413](https://github.com/user-attachments/assets/ae24266b-1937-4687-abd4-0c130a0af0a9)
![Screen Recording 2024-10-25 163953](https://github.com/user-attachments/assets/a6158f0a-dfa1-4276-a410-64c5eefb1559)

Have cleared cache with MA. Have cleared browser cache since updating MA this afternoon.

### What version of Home Assistant Core are your running

2024.10.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Yeah I think this is a front end glitch. See if the frontend updates if you change the volume?

**Comment by itkama** [comment]
Have the same problem, newest 2.3.0 Server.

**Comment by jcmleng** [comment]
Having the same issues on 2.3.0 Server, Spotify. The Status Bar at the bottom of the screen, Recently Played and the Queue list is not refreshing automatically. The Recently Played only refreshes when the Home Screen is refreshed. The Status bar and Queue List remains "stuck" even if I refresh the Home Page.

**Comment by tbgoose** [comment]
> See if the frontend updates if you change the volume?

Yes it does, almost any interaction forces it to update.

**Comment by marcelveldt** [comment]
Fixed in 2.3.1

**Comment by OzGav** [comment]
This is fixed for me.

**Comment by tbgoose** [comment]
Fixed for me also, thanks!
