### ISSUE TITLE
No covers are loading

### ISSUE THREAD

**Issue by loadamasta** [music-assistant/hass-music-assistant#3076]
### What version of Music Assistant has the issue?

2.4.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Almost no covers from artist, albums and song titles are shown after update to the newest version (24.10.2024), neither from spotify nor from Plex library.

### How to reproduce

open Music Assistant and have a look

### Music Providers

Spotify and Plex

### Player Providers

Sonos

### What version of Home Assistant Core are your running

2024.10.3

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
This has been noted and is being investigated

**Comment by Extrapilot1** [comment]
Not necessarily related, but I started seeing my HA RPI4 reboot every 10 min or so right after the most recent patch was installed. I disabled the Music Assistant addon, and it hasnt rebooted since.  Errors appear to be file read related, but there are no problems with any other device (all use an external SSD)- so database reads/writes are fine, reporting is fine, logs are fine etc. Only reporting in the case the cover art is related. No idea if the crash is memory leak- I dont see much in the system logs except restart details. Almost like a power-out, except again, soon as I disabled Music Assistant, this stopped, and it has been stable an hour now... If I can help with a diag etc, happy to try. Just not sure where to look.
Rob

**Comment by OzGav** [comment]
@Extrapilot1 re-enable MA and see if it starts again. If it does look in the supervisor log.

**Comment by Extrapilot1** [comment]
Yes, it crashed within 6-8 minutes. I dont see any events in Supervisor log prior to the restart- not sure if I have to enable debug mode etc. What I did see was that CPU was pegged at 100%, RAM was at 74%, and the Music Assistant interface initially was showing a spinning circle status. When I came back to open the UI again after checking CPU, I got nothing- no UI response from Music Assistant, but I had quick response from other menu items- Node Red, HACS etc. So yea, not really sure of next steps- 2am here, so rack time, but if there is anything specific I should try- happy to have a go tomorrow.
Best
Rob

**Comment by OzGav** [comment]
@Extrapilot1 this is a different problem that is being investigated.

**Comment by Extrapilot1** [comment]
Great, If I can help, let me know what to enable for logging etc-
R

**Comment by OzGav** [comment]
@loadamasta @Extrapilot1 both if your issues should be fixed in 2.3.1 or 2.4.0b1 which will be released soon. Please confirm

@Extrapilot1 so we can stay sane please open your own issue in future

**Comment by Extrapilot1** [comment]
As I said- I wasnt clear if this was related- as I was seeing file access errors where I had no problems with filesystem access via any other component. Other report on this ticket mentioned file access, and the timeline overlapped with the release that caused the CPU/crash issue.

So far as the crash is related, the new version resolved it. It seemed to require a reinstall, as for whatever reason, the update didnt want to apply if the MA addon wasnt running, and turning it on caused a 100% CPU problem which prevented the update from running (or at least, from completing) before a crash happened.

So, CPU is sane now, no crashes, app seems to be running well.

Best
R

**Comment by OzGav** [comment]
This has been fixed

**Comment by loadamasta** [comment]
> @loadamasta @Extrapilot1 both of your issues should be fixed in 2.3.1 or 2.4.0b1 which will be released soon. Please confirm
> 
> @Extrapilot1 so we can stay sane please open your own issue in future

Sorry, EMail was in spam. I confirm that the issue has been fixed. Thank you.
