### ISSUE TITLE
Music is full of "errors"/lagging

### ISSUE THREAD

**Issue by el-Presi** [music-assistant/hass-music-assistant#3077]
### What version of Music Assistant has the issue?

2.3.0

### What version of the Home Assistant Integration have you got installed?

2024.10.3

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Hi guys, I don't know how to say, but my Airplay playback on my speakers (sonos and a Denon AVR) is lagging, single speakers are dissapearing and coming back while playback.. I have a video here, which shows it.
It is happening on: Sonos (single or group), Homepods when playing via Airplay..
Does anyone have an idea, where the issue comes from?
--> https://youtu.be/rFvo9nbp_qQ

Wifi is running on a Unifi Mesh System, which does show that everything is fine..

### How to reproduce

Play Music via Airplay to One or more speakers

### Music Providers

Spotify, TuneIn

### Player Providers

Airplay

### Full log output

sorry, I just did a reboot, since then the issue is gone (normally for a few hours or even days)

### What version of Home Assistant Core are your running

2024.10.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (ntel(R) Core(TM) i7-11850H)

I don't get, what's the benefit of these screenshots for troubleshooting...
 - - - - -
 Provider Spotify:
![image](https://github.com/user-attachments/assets/ad56a3df-25d9-4daf-af00-634e40889b65)
- - - - -
Provider Tunein:
![image](https://github.com/user-attachments/assets/3042498c-3a3f-4f9d-bcdc-4197e02ca9f4)
- - - -
![image](https://github.com/user-attachments/assets/b9a189c5-af37-4a24-ad26-fca1a6ec5ed8)
![image](https://github.com/user-attachments/assets/d3c60b9f-538b-4d73-9ad4-0d7e6feffa46)
![image](https://github.com/user-attachments/assets/ca31e16b-07db-4435-a7c2-55f676961fa4)

**Comment by OzGav** [comment]
You have ticked the box saying you read the troubleshooting page but you haven’t supplied the information requested

**Comment by el-Presi** [comment]
Well...:

What music provider is in use when the problem is observed? What other music providers have you tried (if you have no others then make that clear)
**Information is given from me above**
What player provider is in use when the problem is observed? What other player providers have you tried (if you have no others then make that clear)
**Information is given from me above**
Are the players grouped?
**Information is given from me above**
How is playback being instigated (e.g. automation or via the UI)
**via UI**
If you aren't using HAOS then exactly how you have installed MA
**I have HAOS (information is given here..)**
What is working (e.g. player works with music provider X but not Y)
**Information is given from me above**
What you have tried from this page that hasn't helped
**There is no specific troubeshooting section/information for my issue, or I haven't figured out, which one fits to my issue.**

**Comment by OzGav** [comment]
You are making minimal effort. The docs are clear that you need to try other player providers and music providers. It is also clear to look at network problems, device settings and the specific provider pages. You have made no mention of what you have tried in all of these areas.

We are a small team and we need people to narrow down the problem.

**Comment by el-Presi** [comment]
> You have made no mention of what you have tried in all of these areas.
![image](https://github.com/user-attachments/assets/72826644-3819-465f-9b51-37a097d95b20)

As you can read, I've tried Spotify AND Tunein,
I've also tried Airplay AND Sonos... (ok, did not mention Sonos in the initial post, thats true :(  )

What can I try in the network area? The Wifi is configured along the suggestions in the FAQ (IGMP, multicast snooping, mDNS) - I think the hint, that it is working good for a few hours after a restart of HAOS should intent, that the network is able to transport the music packages correctly and that after a few hours (or even days) something seems to happen on the HAOS side OR within the Docker container (MA)...

Let me check, what I can collect from the provider pages (but this is all default, since I haven't changed anything here)

**Comment by OzGav** [comment]
No you misunderstand. The specific provider pages are not the MA settings they are the specific provider pages (in your case AirPlay and Sonos) in the docs.

> Review the applicable player or music provider documentation to see if there are known issues or specific troubleshooting steps or fixes.

**Comment by el-Presi** [comment]
ok sorry, my fault, will check this :) Thanks!

**Comment by el-Presi** [comment]
fixed it by myself
