### ISSUE TITLE
TuneIn Radio does not play

### ISSUE THREAD

**Issue by mihailmoise** [music-assistant/hass-music-assistant#3085]
### What version of Music Assistant has the issue?

2.3.1

### What version of the Home Assistant Integration have you got installed?

2024.10.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Till yesterday it worked as good as it usually works, playing favourite radio on Sonos group over AirPlay.
After last update today, it cannot play that radio any longer; log sais:

2024-10-26 12:16:37.730 DEBUG (MainThread) [music_assistant.webserver] Handling command players/cmd/play_pause
2024-10-26 12:16:37.735 DEBUG (MainThread) [music_assistant.players] Handling command cmd_play for player Terrace
2024-10-26 12:16:37.845 ERROR (MainThread) [aiosonos.api] Received error message without cmdId: {'namespace': 'playback:1', 'householdId': 'Sonos_1gA5lFTsjGDpQgwnlqXaFqtFlv.rNb9GJrsuDTKKDr3OIJ6', 'locationId': 'lc_0f3cb49bee624b26ad17ec579f6c0b87', 'groupId': 'RINCON_C4387576AB5E01400:3411237167', 'name': 'playbackError', 'type': 'playbackError'}

### How to reproduce

Update Music Assistant Server to 2024.10.1
Refresh all music providers, music players & groups
Select a player
Browse for a TuneIn station
Press play button

### Music Providers

TuneIn Radio

### Player Providers

Sonos

### Full log output

[d5369777_music_assistant_2024-10-26T08-59-16.656Z.log](https://github.com/user-attachments/files/17529675/d5369777_music_assistant_2024-10-26T08-59-16.656Z.log)

### What version of Home Assistant Core are your running

2024.10.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
You have ticked the box saying you have reviewed the troubleshooting page but you have not provided the required information specified therein.

**Comment by mihailmoise** [comment]
1. At restart, Music Assistant sees no players or providers; gotta get into settings and refresh every single thing showing an hourglass; if not, there's an error in the log saying player XYZ not found - it's the 2nd time today it happened
2. Even if it sees the sources and the players, the thing does not play, you have the logs
3. from yesterday to today, the only change was updating this Music Assistant, and if I remember well the HA Core
4. there's nothing about _aiosonos.api_ "**There are no discussions here yet**" nor _error message without cmdId_ on the [https://github.com/orgs/music-assistant/discussions](url)
5. getting to Google provides two links, first to Git for music Assistant

So, here we are, Music Assistant still not working and I'm starting to think it's the one that contributes to RPi freeze when asked to refresh the Home Assistant Plugin provider, although this is only a hunch...

**Comment by OzGav** [comment]
Again review the information requested. For a start you have attached an excerpt of the log with debug enabled when you were asked to attach the FULL log with debug disabled. We are a small team and we need you to read the information provided carefully and provide the information requested. You need to narrow down the problem.

**Comment by mihailmoise** [comment]
Ok, just leave it, someone will loose time in order to make you produce something valuable.
