### ISSUE TITLE
MA Stopped Playing; "Read timed out" error

### ISSUE THREAD

**Issue by jcmleng** [music-assistant/hass-music-assistant#3088]
### What version of Music Assistant has the issue?

2.3.1

### What version of the Home Assistant Integration have you got installed?

2024.10.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

MA stops playing a Spotify Playlist and generated the following error:

hass_client.exceptions.FailedCommand: Error calling SonosMediaPlayerEntity._play_media on media_player.living_sonosarc: HTTPConnectionPool(host='192.168.1.10', port=1400): Read timed out. (read timeout=9.5)

### How to reproduce

Restarted the same playlist which played a few songs, then the error recurred.

### Music Providers

Spotify

### Player Providers

Sonos Arc

### Full log output

[music-assistant.log](https://github.com/user-attachments/files/17529112/music-assistant.log)

### Additional information

Playlist was activated from the UI when it stopped. Had to wait 10-15 mins thereabouts to be able to restart the playlist - during that time, clicking on Play did nothing.

Sonos Arc and HA are on the same nework.

### What version of Home Assistant Core are your running

2024.10.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Please always supply all of the information requested in the troubleshooting docs. We need you to narrow down the problem. So go through all the combinations of things you have. Different player providers, different music provider, different items (albums, tracks, playlists) from the problem provider(s). From that we should be able to see more clearly where the problem lies.

**Comment by marcelveldt** [comment]
Question number 1 I have is why you are running the old Sonos provider while you have a Sonos S2 capable device ?

**Comment by jcmleng** [comment]
> Question number 1 I have is why you are running the old Sonos provider while you have a Sonos S2 capable device ?
@marcelveldt, I havent followed developments in the Sonos world, so I need to step back, do some research, review and update both my Sonos and MA setup.

**Comment by jcmleng** [comment]
> Please always supply all of the information requested in the troubleshooting docs. We need you to narrow down the problem. So go through all the combinations of things you have. Different player providers, different music provider, different items (albums, tracks, playlists) from the problem provider(s). From that we should be able to see more clearly where the problem lies.

I only have Spotify and the Radio Browser in my MA setup right now. The problem has been with my Spotify Playlists only, Radio Browser has been completely stable, so I have reported back on the Spotify Playlists. Will check out other Spotify items and report back. Could also be that my Sonos setup is out of date/incorrect. Will relook the setup and restart.

**Comment by marcelveldt** [comment]
Starting with the 2.3 version of MA, we use a new Sonos provider, which leverages the new local websockets API on Sonos speakers instead of the old/legacy xml/upnp api. Sinc t he releae of their app and firmware, it seems that Sonos is heaviliy throttling the old API (on S2 speakers), which explains a number of issues. So my first advise would be to start using this new Sonos provider in MA.

**Comment by jcmleng** [comment]
Thanks @marcelveldt . Thats what I have done today after confirming that both my Arc and One are both on S2. Deleted the HA Integration media players and installed the new Sonos player provider in MA. Testing this new setup now and will revert.

**Comment by jcmleng** [comment]
Have not had this issue recur in 2.3.1 since deleting the HA Integration players and installing the Sonos S2 provider. Was able to play 5-6 Spotify David Benoit albums continuously, adding new albums to the Queue in the middle, with no stoppages over 3-4 hours. Closing this issue out based on this.
