### ISSUE TITLE
cutouts during playbacks (Spotiy)

### ISSUE THREAD

**Issue by DrieWielRr** [music-assistant/hass-music-assistant#3091]
### What version of Music Assistant has the issue?

2.3.1

### What version of the Home Assistant Integration have you got installed?

2024.9.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

With every version update I keep getting more and more playback cutouts when playing from Spotify on our Spotcast setup.
I used to be able to start playback in the morning and it will keep playing all day long without any issues, then it started cutting mid track at random intervals but still acceptable (hours before failing) but now I'm lucky if it reaches 15m before it stops playing..
Selecting "next-track" usually fixes the problem and the next track starts playing but it's getting quite annoying for tracks to just randomly stop at mid track and then nothing for a long time until someone presses next track.
Also the song keeps playing in the interface well past the maximum track length, I've seen things like 3 minute song but playing for 30+ minutes?...

### How to reproduce

Start music playback and wait for it to cutout.

### Music Providers

Spotify

### Player Providers

Spotcast

### Full log output

[music-assistant.log](https://github.com/user-attachments/files/17533236/music-assistant.log)
[_snapclient_logs.txt](https://github.com/user-attachments/files/17533239/_snapclient_logs.txt)

### What version of Home Assistant Core are your running

2024.10.1

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
Spotcast isn’t a MA player provider?

**Comment by OzGav** [comment]
Hmmm maybe you meant snapcast. In any case you have ticked the box saying you have read the troubleshooting page but you have not supplied the requested information

**Comment by DrieWielRr** [comment]
Ah yes I'm sorry I meant snapcast, what did I miss?
Yes MA is intgrated with HA but HA is not controlling it directly, I use the webinterface to fully control the playback. 
I only use HA to read the snapclient playback state that MA reports to HA to control the audio amplifiers power (on/off).

My network is complicated for a home setup (im an IT guy), but everything related to MA and the snapclients are located within the same subnet/vlan so mdns or any other multicast traffic should'nt be a problem (so I didnt mention it).

Anything else I missed to report or do?

**Comment by OzGav** [comment]
The troubleshooting page at the end has a bunch of information that is to be supplied if get that far. However, 3/4 of the way down it says this

> Review the applicable player or music provider documentation to see if there are known issues or specific troubleshooting steps or fixes.

Then in the Spotify docs it says this 

> Entering a personal ClientID may speed up access to the Spotify API or eliminate rate limiting if that is encountered.

And then in your logs it says many times 

> Attempt x/5 failed: Spotify Rate Limiter

**Comment by DrieWielRr** [comment]
I've read this but does this still count for the latest version?
Spotify authentication is being handled via the browser and no longer requires a Spotify client on the same subnet. 
Within the provider I cannot find any field to enter a ClientID (I do remember seeing this in the past somewhere), so i must be definetly messing something,?
Do I need to clear the current authentication and re-authenticate for this to work?

**Comment by OzGav** [comment]
Yes if you didn’t add your own client id at the start you will have to re do it.

**Comment by DrieWielRr** [comment]
Thanks, I added the clientID ill test it out and see if it improves otherwise I might have to downgrade the MA.
For now thanks for the assist, ill close this issue.
