### ISSUE TITLE
Translation - Hungarian

### ISSUE THREAD

**Issue by bazsc20ne** [music-assistant/hass-music-assistant#3094]
### New language

Hungarian - Magyar

### Additional remarks

I'd like to contribute to the project by translating the frontend interface to Hungarian.

**Comment by OzGav** [comment]
Thanks @bazsc20ne Hungarian has been added. We will begin the process of adding it to the frontend once the translated percentage exceeds 75%. Please keep an eye on things as time goes on as new strings are added.
