### ISSUE TITLE
Soundcloud tags are split by character

### ISSUE THREAD

**Issue by danielkleinert** [music-assistant/hass-music-assistant#3107]
### What version of Music Assistant has the issue?

2

### What version of the Home Assistant Integration have you got installed?

2024

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

The Soundcloud tags get split by character.

In MA:
<img width="979" alt="Screenshot 2024-10-30 at 5 30 27 PM" src="https://github.com/user-attachments/assets/d36d5a93-c869-4443-a6e5-6b1bbea94118">

In Soundcloud:
<img width="1243" alt="Screenshot 2024-10-30 at 5 30 46 PM" src="https://github.com/user-attachments/assets/c6c98629-53f7-481c-84f9-986dc3400c85">

### How to reproduce

Look at any Soundcloud tags

### Music Providers

Soundcloud

### Player Providers

Irrelevant

### What version of Home Assistant Core are your running

2024

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

ODROID

**Comment by OzGav** [comment]
@gieljnssns

**Comment by OzGav** [comment]
Fixed in 2.3.4 beta to follow
