### ISSUE TITLE
Artists get mixed up

### ISSUE THREAD

**Issue by danielkleinert** [music-assistant/hass-music-assistant#3108]
### What version of Music Assistant has the issue?

2.3.2

### What version of the Home Assistant Integration have you got installed?

Irrelevant 

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

MA Somehow merges multiple Soundcloud artists that are in my library to display a tracks artist. I have this issue for multiple and maybe all tracks. 

MA, with additional and wrong artists:
<img width="1235" alt="Screenshot 2024-10-30 at 5 40 53 PM" src="https://github.com/user-attachments/assets/e9b5ec2e-a7ae-4990-b716-44909952e1a2">

Expected artist on Soundcloud:
<img width="1271" alt="Screenshot 2024-10-30 at 5 41 18 PM" src="https://github.com/user-attachments/assets/3c913669-2286-469e-83cc-a4cc3b791bb0">

### How to reproduce

I don't use other providers, so I can't tell if this is only a Soundcloud issue. I think artists were displayed correctly at one point. 

### Music Providers

Soundcloud, maybe others

### Player Providers

Irrelevant 

### What version of Home Assistant Core are your running

2024

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

ODROID

**Comment by OzGav** [comment]
When did you first install MA?

**Comment by danielkleinert** [comment]
Should be around June.

**Comment by OzGav** [comment]
It’s possible you have db problems from a previous issue. Please try a db reset MA SETTINGS >> CORE >>  MUSIC CONTROLLER >> ADVANCED

**Comment by danielkleinert** [comment]
This absolutely fixed it. Also sorting by added date now works correctly. Thanks ❤️
