### ISSUE TITLE
Missing Buttons in Players-UI

### ISSUE THREAD

**Issue by c-mahn** [music-assistant/hass-music-assistant#3121]
### What version of Music Assistant has the issue?

2.3.2

### What version of the Home Assistant Integration have you got installed?

2024.10.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

There are some buttons missing to add Devices, such as Group-Player or other Devices, that should be available:
![grafik](https://github.com/user-attachments/assets/b49fb7e5-c36a-4c64-ad99-b4b09c2714ef)

### How to reproduce

Open Music Assistant UI and navigate to Settings > Players

### Music Providers

Not applicable

### Player Providers

GroupPlayer

### Full log output

The log is empty.
[music-assistant.log](https://github.com/user-attachments/files/17610025/music-assistant.log)

### Additional information

I have set the interface to english for creating this issue, but normally use it in german.

### What version of Home Assistant Core are your running

2024.10.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Yes this is because you don’t have any players that can be added to a sync group. It is an item on the backlog to be fixed https://github.com/orgs/music-assistant/projects/2/views/1?pane=issue&itemId=85308853

**Comment by OzGav** [comment]
This has been fixed in 2.4.0b4
