### ISSUE TITLE
 [music_assistant] Error doing task: Task exception was never retrieved Traceback

### ISSUE THREAD

**Issue by oflaki** [music-assistant/hass-music-assistant#3124]
### What version of Music Assistant has the issue?

2.3.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I was upgrading the docker version from v2.3.0 to v2.3.2, and got an error.
`2024-11-03 20:47:35.651 ERROR (MainThread) [music_assistant] Error doing task: Task exception was never retrieved
Traceback (most recent call last):
  File "/app/venv/lib/python3.12/site-packages/aiorun.py", line 219, in new_coro
    await coro
  File "/app/venv/lib/python3.12/site-packages/music_assistant/__main__.py", line 211, in start_mass
    await mass.start()
  File "/app/venv/lib/python3.12/site-packages/music_assistant/server/server.py", line 112, in start
    self.aiozc = AsyncZeroconf(ip_version=IPVersion.V4Only)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/zeroconf/asyncio.py", line 167, in __init__
    self.zeroconf = zc or Zeroconf(
                          ^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/zeroconf/_core.py", line 179, in __init__
    listen_socket, respond_sockets = create_sockets(interfaces, unicast, ip_version, apple_p2p=apple_p2p)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/zeroconf/_utils/net.py", line 383, in create_sockets
    if add_multicast_member(cast(socket.socket, listen_socket), i):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/zeroconf/_utils/net.py", line 293, in add_multicast_member
    listen_socket.setsockopt(socket.IPPROTO_IP, socket.IP_ADD_MEMBERSHIP, _value)
OSError: [Errno 105] No buffer space available`

### How to reproduce

Upgrading or fresh install of Music Assistant

### Music Providers

N/A. Also applies with a fresh docker install

### Player Providers

N/A. Also applies with a fresh docker install

### What version of Home Assistant Core are your running

2024.10.4

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
Have you googled the error?

**Comment by oflaki** [comment]
> Have you googled the error?

Yes I have, with no luck...

**Comment by marcelveldt** [comment]
https://unix.stackexchange.com/questions/23832/is-there-a-way-to-increase-the-20-multicast-group-limit-per-socket/565907#565907

Look there for your answer.
Its a host config issue.
