### ISSUE TITLE
Sometimes doesn't resume playing after an announcement

### ISSUE THREAD

**Issue by lordbah** [music-assistant/hass-music-assistant#3129]
### What version of Music Assistant has the issue?

2.4.0b2

### What version of the Home Assistant Integration have you got installed?

2024.10.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

After HA sends an announcement via tts.speak, sometimes MA resumes playing the playlist and sometimes it doesn't. In the log file, after the announcement at 17:28:33 playback did resume, but after the announcement at 17:29:52 it did not. These two errors are logged:
```
2024-11-04 17:30:00.086 ERROR (MainThread) [ffmpeg.937] Stream error: No audio data received from source
2024-11-04 17:30:01.255 WARNING (MainThread) [music_assistant.audio.media_stream] Stream error on plex--M66KUnau://track//library/metadata/522
```
I was able to manually resume playback from the MA UI, though it went back to the beginning of the current track. It played to completion. So there is no persistent problem with reading that particular audio. I suppose it could be a spurious read failure, I'll try to log any future occurrences (not like I get visitors all that often).
[noresume.log](https://github.com/user-attachments/files/17621933/noresume.log)
Hmm, accidentally attached the log file here instead of below, and there seems to be no way to remove it.

### How to reproduce

I have an HA automation to announce objects detected by camera. It calls a script
```
announce2:
  sequence:
    - action: tts.speak
      data:
        media_player_entity_id: media_player.sonos
        message: "{{message}}"
      target:
        entity_id: tts.piper
```
So, start playing a playlist, occasionally have an object detected by a camera, Frigate notifies HA, HA calls tts.speak. The chime plays, the message is spoken, then the playlist is sometimes resumed.
The media player is an MA SyncGroup for all Sonos S1 speakers.

### Music Providers

Plex

### Player Providers

Sonos S1

### Full log output

[noresume.log](https://github.com/user-attachments/files/17621990/noresume.log)

### What version of Home Assistant Core are your running

2024.10.2

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
Can you try using a service other than tts.piper and see if that makes a difference?
