### ISSUE TITLE
Radio Playlist Number increments but Not decrement if stations deleted

### ISSUE THREAD

**Issue by ohkaja** [music-assistant/hass-music-assistant#3130]
### What version of Music Assistant has the issue?

2.3.2

### What version of the Home Assistant Integration have you got installed?

2024.10.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

If a Radio station is added it becomes e.g. number 1, the second 2, and so on.
If one station is deleted the playlist number is not free and can be reused. The counter counts up +1 after the last added station.
This behavior kicks in when you work with library://radio/number media links to play radio stations to work around the missing playlist support there.

### How to reproduce

Add e.g. 3 Radio stations. Then delete it and add it back. The 3 new ones will have the internal number 3,4,5. Should be 1,2,3.

### Music Providers

NonMusic providider. Manually added Radiostations.

### Player Providers

Radio

### Full log output

No log entries generated.

### What version of Home Assistant Core are your running

2024.10.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
These are database numbers not numbers in a list. This is expected behaviour.

**Comment by ohkaja** [comment]
Sorry but you really say, that there is no playlist option for radio stations - ok.
And then, when one find a way to workaround that disadvantage, you wipe it away with "expected behavior"?

That answer looks to simple. 

You have no good implementation to play radiostations in a simple way (one after another) without using the UI. And you can not re-use a simple number in a database table/ cell. Sad to hear.

You should switch your "expected behavior" to "problem reconized, problem will be solved somewhere in the future".

**Comment by OzGav** [comment]
It actually is. There is an item on the backlog to allow radio stations to be added to a playlist

**Comment by ohkaja** [comment]
The problem is not exclusive to radiostations. Its a general behavior when adding media manual.

Plan to implement a radio playlist support != false numbering media sources with an autoincrementing number in a database table.

I stop cherry picking now. MA is not the solution for my problem.

**Comment by OzGav** [comment]
You shouldn’t be using the database numbers anyway. Just use the name of the item or the source URI

**Comment by ohkaja** [comment]
Thats not possible. I´ll try to explain:

I have a 5 button remote (on/off, vol+, vol-, forward, backward).
That said i do the following (to workaround the playlist behavior):

1. A counter helper wich is initialized when the speaker is switched on (2.). 
2. With on/off i trigger a standardstream to play (e.g. /1).
3. When I press forward 
- the counter from 1. increases 
- sends the stream source (media_player: play media) library://radio/$counter
4. When i press backward
- the counter from 1. decreases
- sends the stream source (media_player: play media) library://radio/$counter

So you see, this way is the only one to have a "radioplaylist" wich can be easily controlled with one button press. It´s not simple possible to recreate this with the Name of the item or the source URL. As far as i dont reference $counter to an item or an URL, evaluate this and then send the right stream - If so, in this example, i will simply build a media-player-index and push this to a speaker - no need for MA.
The hope was to organize this better with MA. But with your increasing expected behavior all breaks by add or delete a station. I still think i should be possible to self number the radiostations.

As far as i only add stations all i have to do is to set a new $counter maximum and all works in seconds.

**Comment by ohkaja** [comment]
Thanks for the help, but, thats the point: Wich role plays MA in this case? I can have a select list with radiostation url's and fire they up with a automation. I wanted to replace this "solution", wich i use since years, with MA, ergo no need for MA.

Sorry for thinking that userinput is desired for improving the software. In now found out that getting more workarounds for a bad implementation is the way. :(
