### ISSUE TITLE
does not resume playback after an announcement on a group of speakers

### ISSUE THREAD

**Issue by Africa67** [music-assistant/hass-music-assistant#3135]
### What version of Music Assistant has the issue?

2.3.2

### What version of the Home Assistant Integration have you got installed?

2024.11.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I have multiple players (google cast) grouped natively in Google home. If I send an announcement to the group, the individual players do not resume.
I believe, but I'm not entirely sure, that it stopped working from version 2.3.0. Previously it worked great and without problems.

### How to reproduce

          - action: tts.google_say
            enabled: true
            continue_on_error: true
            data:
              cache: true
              entity_id: media_player.filodiffusione_2
              message: "{{ message }}"

### Music Providers

Spotify, Tune-in

### Player Providers

Chromecast

### What version of Home Assistant Core are your running

2024.10.4

### What type of installation are you running?

Home Assistant Core

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
I can't recreate this

I am no expert on the tts action but those keys of enabled and continue_on_error don't show up in the dev tools so I am not sure they are valid. Try the following in the dev tools and see what happens (replace the entitiy with your own group entity)

```
action: tts.google_say
data:
  cache: false
  entity_id: media_player.ma_google_speaker_group_2
  message: This is a test
```

**Comment by Africa67** [comment]
It's precisely the ad that doesn't work on the group. If the action is sent to each individual player the music resumes correctly for each individual player.
That's how it works:

          - action: tts.google_say
            enabled: true
            continue_on_error: true
            data:
              cache: true
              entity_id: 
                - media_player.bagno_2
                - media_player.camera_da_letto_2
                - media_player.cucina_2
                - media_player.salotto_2
              message: "{{ message }}"

**Comment by OzGav** [comment]
As I said I can’t recreate this. Sending to my group of four cast players works fine. Did you try my simple yaml action to see what happens for you?

**Comment by OzGav** [comment]
Ok that is intended behaviour https://music-assistant.io/integration/announcements/#group-behaviour

I think this can be closed?
