### ISSUE TITLE
Artist not displaying correctly

### ISSUE THREAD

**Issue by geoffmellis** [music-assistant/hass-music-assistant#3141]
### What version of Music Assistant has the issue?

2.3.2

### What version of the Home Assistant Integration have you got installed?

2024.11.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Artist showing incorrect for the band 'Foxing'. My files are tagged artist and album artist both as 'Foxing' but they keep appearing in MA with the wrong name.

Each time I remove the artists & albums from MA and re-sync they re-appear with a different incorrect artist showing.

They also have a self-titled album which doesn't show in MA at all as far as I can see, wonder if perhaps this is related.

All files are tagged with mp3tag correctly.

![ma](https://github.com/user-attachments/assets/28ede685-d435-4a6c-980a-c4afc4566855)

![mp3tag](https://github.com/user-attachments/assets/69d13bdc-e9d8-4bfa-a44b-65191e7f787c)

![mp3tag2](https://github.com/user-attachments/assets/ae54782b-2cc7-4cfb-acd7-83bc107fa4cb)

### How to reproduce

When scanning to add music this artist is always added incorrectly.

Have tried removing from MA and re-scanning (Syncronize now) on the music provider (filesystem - remote share)

### Music Providers

Filesystem (remote share)

### Player Providers

Sonos, picoreplayer, chromecast but the issue isn't playing the file.

### Full log output

[music-assistant.log](https://github.com/user-attachments/files/17663380/music-assistant.log)

### What version of Home Assistant Core are your running

2024.11.0

### What type of installation are you running?

Home Assistant Core

### On what type of hardware are you running?

ODROID

**Comment by geoffmellis** [comment]
Just for reference I've removed the artist 'Alvaro Soler, Topic' from library and re-synced filesystem. It's now re-appeared with the artist name 'JAWNS'.

![ma2](https://github.com/user-attachments/assets/ce6c203c-262f-4d19-acec-3072b4d79382)

I then removed the artist 'JAWNS' and re-synced a further time and they've re-appeared with the artist showing as 'Alexandra Stan'. Very strange..

![ma3](https://github.com/user-attachments/assets/21ca02f7-79d8-4b64-9d7a-318db933c632)

**Comment by OzGav** [comment]
If you have been using MA for a couple of months there was a bug that might still be present in your database. Try a DB reset MA SETTINGS>>CORE>>MUSIC CONTROLLER>>ADVANCED

**Comment by OzGav** [comment]
I see you say 

> All files are tagged with mp3tag correctly

yet there are 100s of warnings in your log about missing album artists and I didn’t look any further. So you need to tag your files properly as specified in the docs which means album artists as well as all unique musicbrainz identifiers.

**Comment by geoffmellis** [comment]
> I see you say
> 
> > All files are tagged with mp3tag correctly
> 
> yet there are 100s of warnings in your log about missing album artists and I didn’t look any further. So you need to tag your files properly as specified in the docs which means album artists as well as all unique musicbrainz identifiers.

Fair point! I believed I had done them all but obviously something's gone wrong. All of the Foxing files are tagged with artist & album artist as per screenshots above but I will use Picard to add musicbrainz identifiers and will go through the whole library tonight.

Thanks for your help.

**Comment by OzGav** [comment]
You may need to do another DB reset. Please close this if resolved.

**Comment by geoffmellis** [comment]
> You may need to do another DB reset. Please close this if resolved.

Thanks, yes all seems ok now. Does seem odd that other artist's being missing from 'album artist' could cause this artist to match incorrectly but it is working now. Would be great if there was an option one day to just use local metadata and not rely on Musicbrainz.

Thanks for your help anyway.
