### ISSUE TITLE
Entity media_player does not support this service.

### ISSUE THREAD

**Issue by MarkHofmann11** [music-assistant/hass-music-assistant#3153]
### What version of Music Assistant has the issue?

2024.11.x

### What version of the Home Assistant Integration have you got installed?

2024.10.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Following the upgrade from 2024.10.1 -> 2024.11.x, all of my Chromecast (Google minis and home hubs) report the following error when attempting a mass.play_media action.  mass.play_announcement works, however.

The error is:  homeassistant.exceptions.HomeAssistantError: Entity media_player.marks_office_hub does not support this service.

I am not using the HA Cast integration - only the MA add-on with Chromcast and MA integration.

### How to reproduce

Upgrade from 2024.10.1 to 2024.11.x - and try to run my automation.
```
  - action: mass.play_media
    metadata: {}
    data:
      media_id: White_Noise_10hrs
      enqueue: replace
      media_type: track
    target:
      entity_id:
      - media_player.master_bedroom_mini
```

### Music Providers

Google mini, google home hub.

### Player Providers

Only mass.play_media in automations shows the error:    - action: mass.play_media

Source: components/automation/__init.py:763
integration: Automation (documentation, issues)
First occurred: 4:09:49 PM (10 occurrences)
Last logged: 9:23:34 PM

Error while executing automation automation.whitenoise_alex_room: Entity media_player.alex_room_mini does not support this service.

### Full log output

[log.txt](https://github.com/user-attachments/files/17687262/log.txt)
![MA-2024-10 1-Integration](https://github.com/user-attachments/assets/dd8e3786-4737-43de-9b34-cc2293357729)
![MA-2024-11 1-Integration](https://github.com/user-attachments/assets/25e8a453-0c33-4873-94a7-7391c421fa00)

### Additional information

Revering back to 2024.10.1 integration resolves the issue with mass.play_media.  Attached are a display of the entities when using 2024.10.1 vs 2024.11.1.

### What version of Home Assistant Core are your running

2024.11.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Alternative

**Comment by OzGav** [comment]
Please confirm you are using the native CAST provider in MA and are not bringing in the HA entities via the HA player provider

**Comment by MarkHofmann11** [comment]
Yes, I am using the native cast in MA only.  I removed and HA Cast integration completely.  The two screen shots are the media players - 1st one using 2024.10.1 that works and 2nd one is 2024.11.x where I receive the error on mass.play_media.

**Comment by OzGav** [comment]
I cannot recreate this but with all the changes made to the integration lately I will get one of the devs to have a look.

**Comment by OzGav** [comment]
This should be fixed in the next update to the integration. Please confirm when that is released.

**Comment by MarkHofmann11** [comment]
Just upgraded to the 2024.11.3 from 2024.10.1 and can confirm the issue has been fixed.  Thank you!!!
