### ISSUE TITLE
Error handling message: player_queues/play_media: Resource not found

### ISSUE THREAD

**Issue by sunjaxx** [music-assistant/hass-music-assistant#3155]
### What version of Music Assistant has the issue?

2.4.0b4

### What version of the Home Assistant Integration have you got installed?

2024.11.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I get the error "Error handling message: player_queues/play_media: Resource not found" in the log when playing some tracks. For example track 4 of a specific album. Note that the track plays when using directly Jellyfin or VLC.

### How to reproduce

Play a specific track

### Music Providers

Jellyfin

### Player Providers

Any (same error happens when using chromecast or DLNA)

### Full log output

[music-assistant.log](https://github.com/user-attachments/files/17688633/music-assistant.log)

### What version of Home Assistant Core are your running

2024.11.1

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
Please supply the automation or script you are using which causes this.

**Comment by OzGav** [comment]
@Jc2k There are a bunch of Jellyin invalid tracks in the log which I am going to guess is the reason for the resource not found later?

**Comment by Jc2k** [comment]
The jellyfin error in that log could indicate the user lacks the download permission (We stream the download url).

If the user definitely has that permission then there is something else going on that means the jellyfin api isn't returning enough information to construct a url. That's not something I've seen happen before, so I'm currently more leaning towards a permission issue.

**Comment by OzGav** [comment]
@sunjaxx based on the above please look into whether there is a permissions problem here
