### ISSUE TITLE
HA Assist custom sentence not working

### ISSUE THREAD

**Issue by sickkick** [music-assistant/hass-music-assistant#3157]
### What version of Music Assistant has the issue?

2.4.0b4

### What version of the Home Assistant Integration have you got installed?

2024.11.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I followed the guide to setup the MA Specific Conversation Agent.

I created a dedicated OpenAi integration for MA
I created the custom_sentences/en and added play_media_on_media_player.yaml file
I setup the music assistant plugin to the correct agent.
When I ask assist to "Play led zeppelin on the office satellite" Assist response with "Now playing led zeppelin on the office but nothing actually plays on the media player.
  

### How to reproduce

I followed the guide to setup the MA Specific Conversation Agent.

I created a dedicated OpenAi integration for MA
I created the custom_sentences/en and added play_media_on_media_player.yaml file
I setup the music assistant plugin to the correct agent.
When I ask assist to "Play led zeppelin on the office satellite" Assist response with "Now playing led zeppelin on the office satellite" but it doesn't play. I get the following error in the log.

`Logger: homeassistant.core
Source: core.py:2822
First occurred: 4:05:05 PM (1 occurrences)
Last logged: 4:05:05 PM

Error executing service: <ServiceCall media_player.play_media (c:01JC9BXA6D109S7BR53TBSGRXN): entity_id=['media_player.officesatellite'], extra=, media_type=music, media_id=Led Zeppelin>
Traceback (most recent call last):
  File "/config/custom_components/mass/media_player.py", line 115, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mass/media_player.py", line 480, in _async_handle_play_media
    if item := await self.mass.music.get_item_by_name(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant_client/music.py", line 623, in get_item_by_name
    search_results = await self.search(
                     ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant_client/music.py", line 431, in search
    await self.client.send_command(
  File "/usr/local/lib/python3.12/site-packages/music_assistant_client/client.py", line 252, in send_command
    return await future
           ^^^^^^^^^^^^
music_assistant_models.errors.MusicAssistantError: 'NoneType' object has no attribute 'search'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 2822, in _run_service_call_catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/mass/media_player.py", line 115, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mass/media_player.py", line 404, in async_play_media
    await self._async_handle_play_media(
  File "/config/custom_components/mass/media_player.py", line 118, in wrapper
    raise HomeAssistantError(error_msg) from err
homeassistant.exceptions.HomeAssistantError: 'NoneType' object has no attribute 'search'`  

### Music Providers

Tidal and Spotify

### Player Providers

Snapcast
UPnP
AirPlay
Chromecast
Home Assistant MediaPlayers
Playergroup

### Full log output

[music-assistant.log](https://github.com/user-attachments/files/17689435/music-assistant.log)

### What version of Home Assistant Core are your running

2024.11.1

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
Are you using a LLM as well?

**Comment by sickkick** [comment]
ChatGPT

**Comment by OzGav** [comment]
If you want assistance you need to be more forthcoming in how you have your setup. In what way are you using ChatGPT? The response you have listed above is not the normal response. You should just get “Okay.

**Comment by sickkick** [comment]
Okay, I am using a dedicated open ai with chatGPT gpt-4o-mini as the documentation suggested. My assistant is using an OpenAI ChatGPT gpt-3.5-turbo-1106

**Comment by OzGav** [comment]
Yeah so this a LLM problem. I will tag @jozefKruszynski in case the integration needs updating but you need to investigate further what the LLM is doing. I don’t use this but can’t you subsequently ask it what intent it just used?

**Comment by OzGav** [comment]
Actually I see it is trying to use the standard media_player.play_media action. That seems to be the problem so we will look into it.

**Comment by sickkick** [comment]
Thanks for looking into this!

**Comment by jozefKruszynski** [comment]
Not sure what is happening here but it looks like the openai assist setup is directly trying to use the registered service call and for some reason this is failing.
I'll see if I can replicate similar.

**Comment by jozefKruszynski** [comment]
Hi @sickkick,
The fact that the media_type in the call to the service is incorrect, would suggest that you did not add the custom prompt to the conversation agent.
If you have done, then I am very surprised that the agent is using an invalid media type

**Comment by jozefKruszynski** [comment]
I don't see any conversation agent logs in your HA logs, can you please setup debug logging as described here:
https://music-assistant.io/integration/voice/#troubleshooting
Then please try again.

**Comment by jozefKruszynski** [comment]
I think we found the issue and it should be fixed soon

**Comment by OzGav** [comment]
This has been fixed.
