### ISSUE TITLE
YouTube Music stopped working and cannot be setup again.

### ISSUE THREAD

**Issue by SIR-Inc** [music-assistant/hass-music-assistant#3169]
### What version of Music Assistant has the issue?

2.3.2

### What version of the Home Assistant Integration have you got installed?

2024.11.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I have been using Music Assistant with my paid YouTube Music account for several weeks and it has been working very well with no issues other than some initial issues with playlists which I knew was a problem but somehow the playlists started working a couple of days later and everything has been great until today when I noticed the YouTube Music provider was not working in Music Assistant (on my Home Assistant installation) but everything else works fine, local music and providers such as SiriusXM, no issues at all with everything else. No changes have been made to my system for at least a week that might explain local system issues. After I noticed the issue I tried several troubleshooting options but nothing worked so I deleted YouTube as a provider and tried to add it again. All the steps work fine through authenticating with my Google account and there are no issues or problems reported from Google when I add access for my Home Assistant instance. All the steps to add YouTube as a provider work fine up to the point I click Save in Music Assistant and then get the following pop-up message:
ERROR: [youtube+yt_access_token] dQw4w9WgXcQ: Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)
I tried to set up YouTube as a provider a few times with different browsers, network connections and computers to make sure it was not an issue with my installation even though nothing has changed for at least several days on my systems. Each time I got the same result. I'm assuming YouTube (Google) has changed something or might be blocking this type of access. I know there are a lot of unsupported mechanisms in how this is made to work so I'm keeping my expectations in check and am only reporting this because I am so impressed with Music Assistant and want to see it succeed. Thanks so much for the great work.

### How to reproduce

Add YouTube Music as a new Music Provider. Click the AUTHENTICATE ON YOUTUBE MUSIC button and follow prompts to authenticate. Everything succeeds including an Authentication token for YouTube Music being added but when I return to the Music Assistant interface and click SAVE I get the following error in a pop-up:
ERROR: [youtube+yt_access_token] dQw4w9WgXcQ: Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)
It has been several weeks since I first successfully set up YouTube Music as a Provider and I don't clearly remember all the steps but I think that a new prompt when the first Google screen comes up for authentication is that it displays a code (e.g. SJHK-KJZW). There is a clickable message 'The codes don't match' and a Continue button. I clicked the continue button and YouTube Music (Google) didn't respond with any error messages and continued with the authentication and showed that Music Assistant was successfully set up to access my account.

### Music Providers

YouTube Music

### Player Providers

I use Home Assistant MediaPlayers and DLNA but this is not relevant as the issue takes place before you can use any MediaPlayers. When YouTube Music was working, as recently as last night (2024-11-10), everything was working normally and well.

### Full log output

[music-assistant.log](https://github.com/user-attachments/files/17709246/music-assistant.log)

### Additional information

I am using the Cloudflared add-on but I have also tested by connecting directly to the local IP of my Home Assistant instance.

### What version of Home Assistant Core are your running

2024.11.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by Dion-HA** [comment]
It looks like you now need to create a Youtube brand account (for your existing Google account) and then use this new Youtube brand account to add Youtube Music to Home Assistant, e.g.

https://github.com/music-assistant/hass-music-assistant/issues/3138#issuecomment-2469387070

**Comment by SIR-Inc** [comment]
> It looks like you now need to create a Youtube brand account (for your existing Google account) and then use this new Youtube brand account to add Youtube Music to Home Assistant, e.g.
> 
> [#3138 (comment)](https://github.com/music-assistant/hass-music-assistant/issues/3138#issuecomment-2469387070)

Thanks so much for the quick reply and link to an earlier report of this issue. I'll follow the existing issue and solutions.
