### ISSUE TITLE
Play URL uses internal docker IP address

### ISSUE THREAD

**Issue by neurove** [music-assistant/hass-music-assistant#317]
When running Music Assistant in a Docker Deployment,  it provides URLs with the internal docker IP address.
Media players which are not deployed inside  the docker network are not able to play the media.
Please add a configuration option for the IP address that is reported.

**Comment by marcelveldt** [comment]
It uses the internal IP from your HA config so if you correct that, this issue is fixed.

**Comment by neurove** [comment]
Thanks for the incredibly fast response.

I cannot change the internal IP address from the GUI. See screenshot below.
<img width="591" alt="image" src="https://user-images.githubusercontent.com/10290946/172562083-4e537ca6-0001-429a-a235-23b500d5e625.png">

Since that is a HASS issue and not MASS, I will dig deeper on how to change it in HASS.

A configuration option would still make it easier for people with Docker deployments or people using setups with reverse proxies for security/availability

**Comment by marcelveldt** [comment]
In that case there is a HA issue... other things in HA also work on base of that internal IP, such as TTS.
So key is to fix the root issue with the internal URL.

Did you restart HA after setting the URL ?

**Comment by neurove** [comment]
Yes, I did restart it. Still getting the address from the network interface.
<img width="591" alt="image" src="https://user-images.githubusercontent.com/10290946/172569651-e5d6f0aa-bb02-4a06-8b09-759080dfbfb2.png">

I got around the problem by putting mopidy in the same docker network.

Thanks again for MASS. It is great :)

**Comment by Nilson** [comment]
@neurove I am having the same issue and would like to better understand your workaround with mopidy.

**Comment by neurove** [comment]
Hi,
Music assistant creates a playlist inside mopidy with the http streaming link. That link had the internal IP address in my setup.
You can manually create a playlist inside mopidy with the correct http link (i.e. replace the IP address inside the original http link with the correct IP address).
Hope that helps

**Comment by robbert229** [comment]
@neurove @Nilson I believe that #516 might fix the issue for you both. I was running into something similar but with kubernetes instead of docker.
