### ISSUE TITLE
Option for universal groups not appearing at all

### ISSUE THREAD

**Issue by returnofthem** [music-assistant/hass-music-assistant#3177]
### What version of Music Assistant has the issue?

2.3.2

### What version of the Home Assistant Integration have you got installed?

2024.11.3

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

To the best of my abilities I have read the FAQs, followed the troubleshooting steps, and read the "read this first" section. I've tried and failed to find savvy solution by searching Google, Reddit, discussions and this issues section. 

I'm saying all this because my issue seems so basic that I must be missing something but... despite the Player Groups provider being present and enabled (for me it can't be disabled) the option to group players in any way is not present. 

Not even universal groups, which is what I want to use to group multiple players of different types + attempt to group DLNA players.

### How to reproduce

For me it's impossible not to reproduce it, it's just what I see no matter what I try. 

I've fully power cycled the HAOS machine which runs the MA add-on, I've tried different devices and browsers too.

### Music Providers

The group option is missing from from player config screen, rather than individual players.

### Player Providers

DLNA & HAOS

### Full log output

[d5369777_music_assistant_2024-11-13T23-06-38.055Z.log.txt](https://github.com/user-attachments/files/17740379/d5369777_music_assistant_2024-11-13T23-06-38.055Z.log.txt)

### Additional information

Screenshots of the group option not being present anywhere

![Screenshot_20241113_225953_Chrome](https://github.com/user-attachments/assets/ee3bd309-2e94-4d08-8a8c-af7a0281f3df)
![Screenshot_20241113_230018_Chrome](https://github.com/user-attachments/assets/52b30390-0856-4e48-a603-9a4f097dc27f)
![Screenshot_20241113_230602_Chrome](https://github.com/user-attachments/assets/90d7ca83-dc86-4455-a446-fee41e9303b3)

### What version of Home Assistant Core are your running

2024.11.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by returnofthem** [comment]
I have also found this apparent error while poking around in the browser console but I have no idea how to interpret it.
[homeassistant-1731540309494.log](https://github.com/user-attachments/files/17740411/homeassistant-1731540309494.log)

**Comment by OzGav** [comment]
This has been fixed in the beta and will be in stable soon https://github.com/music-assistant/hass-music-assistant/issues/3121

**Comment by returnofthem** [comment]
Thank you for confirming, at least I wasn't missing something!

**Comment by OzGav** [comment]
Please confirm this has been fixed in 2.3.3

**Comment by returnofthem** [comment]
Confirmed I can see the universal group options, create new groups, and play to them. 

Thanks!
