### ISSUE TITLE
Youtube Music Integration Issue Gives Error while Saving

### ISSUE THREAD

**Issue by ashishkalra14** [music-assistant/hass-music-assistant#3181]
### What version of Music Assistant has the issue?

2024.11.4

### What version of the Home Assistant Integration have you got installed?

2024.11.4

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Under Music Assistant -->Add Music Provider-->You Tube Music-->Authenticate on Youtube Music we select the Linkage happens and code gets populated but while SAVE it shows error "ERROR: [youtube+yt_access_token]               : Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)

### How to reproduce

Under Music Assistant -->Add Music Provider-->You Tube Music-->Authenticate on Youtube Music we select the Linkage happens and code gets populated but while SAVE it shows error "ERROR: [youtube+yt_access_token]               : Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)

### Music Providers

Youtube Music

### Player Providers

Home Assistant MediaPlayers

### Full log output

[d5369777_music_assistant_2024-11-15T12-14-23.369Z.log](https://github.com/user-attachments/files/17775224/d5369777_music_assistant_2024-11-15T12-14-23.369Z.log)
[home-assistant_2024-11-15T12-15-03.357Z.log](https://github.com/user-attachments/files/17775228/home-assistant_2024-11-15T12-15-03.357Z.log)

### Additional information

Core
2024.11.1
Supervisor
2024.11.3
Operating System
13.2
Frontend
20241106.2

### What version of Home Assistant Core are your running

2024.11.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
I see you ticked the box saying you reviewed the open issues but somehow you missed https://github.com/music-assistant/hass-music-assistant/issues/3138
