### ISSUE TITLE
Not able to configure home assistant integration

### ISSUE THREAD

**Issue by de666** [music-assistant/hass-music-assistant#3183]
### What version of Music Assistant has the issue?

2.2.3

### What version of the Home Assistant Integration have you got installed?

2024.11.4

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

After updating to the latest version (2024.11.4) home assistant shows configuration error 
```
Music Assistant client not ready
```
in the device & services panel.
Already tried to remove the integration and configure from scratch without success.
![2024-11-15 181157](https://github.com/user-attachments/assets/b12bbfa3-a324-4e32-9ee5-264516b5517c)
Music assistant server seems to be detected correctly but the configuration fails.

Home assistant log shows this message, don't know if it is related to the issue
```
2024-11-15 17:00:55.077 ERROR (MainThread) [custom_components.mass] Unexpected exception: Field "lookup_key" of type str is missing in ProviderInstance instance
Traceback (most recent call last):
  File "/config/custom_components/mass/__init__.py", line 151, in _client_listen
    await mass.start_listening(init_ready)
  File "/usr/local/lib/python3.12/site-packages/music_assistant_client/client.py", line 307, in start_listening
    self._handle_incoming_message(msg)
  File "/usr/local/lib/python3.12/site-packages/music_assistant_client/client.py", line 347, in _handle_incoming_message
    self._handle_event(msg)
  File "/usr/local/lib/python3.12/site-packages/music_assistant_client/client.py", line 365, in _handle_event
    self._providers = {x["instance_id"]: ProviderInstance.from_dict(x) for x in event.data}
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 23, in __mashumaro_from_dict__
mashumaro.exceptions.MissingField: Field "lookup_key" of type str is missing in ProviderInstance instance
```

### How to reproduce

1. Update to version 2024.11.4 of the integration
2. Check the device & services panel in home assistant

### Music Providers

None

### Player Providers

Chromecast
Snapcast

### Additional information

No error reported on music assistant server.

### What version of Home Assistant Core are your running

2024.11.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by dante1613** [comment]
I have the same problem. I tried different versions of integration, the minimum working version 2024.10.0, the versions above this no longer work, constant initialization.

Update from 2024.10.0 to higher versions also does not help. So far I am sitting on 2024.10.0 and not installing new updates

**Comment by OzGav** [comment]
@jozefKruszynski

**Comment by therearegods** [comment]
I have the same issue with integration version 2024.11.4.
Music assistant version - 2.2.8

**Comment by marcelveldt** [comment]
I was about to answer that the only way this error could happen is if you are running an old version of the server.
If you update to 2.3.x the issue should go away.

**Comment by dante1613** [comment]
> I was about to answer that the only way this error could happen is if you are running an old version of the server. If you update to 2.3.x the issue should go away.

I installed the music assistant for the first time 5 days ago, on a test server with HA, where it had not been installed before, so the 2.3.2 version was initially installed. I could not understand why the integration was not working, maybe I was installing it incorrectly or the addon was not installed correctly, until I started to go through different versions of the integration

**Comment by de666** [comment]
Updating to the latest version (2.3.3) solves the issue

**Comment by jozefKruszynski** [comment]
Looks like was an issue with be5a 20. Marcel released beta 21 which should fix this issue

**Comment by Switch123456789** [comment]
Awesome, thank you guys!
