### ISSUE TITLE
Track seeking not working for subsonic provider

### ISSUE THREAD

**Issue by de666** [music-assistant/hass-music-assistant#3184]
### What version of Music Assistant has the issue?

2.4.0b4

### What version of the Home Assistant Integration have you got installed?

2024.11.4

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Using the subsonic (latest version of Navidrome) as music provider.
When seeking the track using the track progress bar, the progress bar itself slides correctly and also the track time apperently increases correctly but the listening restarts from the beginning of the track instead of jumping forward, despite the progress bar and the time indicator keep going on as the seeking was made correctly.

### How to reproduce

1. start playing a track from a subsonic music provider
2. slide the track progress bar at the middle of the track
3. the track restarts playing from the beginning

### Music Providers

subsonic

### Player Providers

slimproto
snapcast

### Full log output

no errors related in the logfile

### Additional information

Not 100% sure the issue is related only to the subsonic provider, didn't try with the filesystem one but I recently switch to the subsonic provider (from a local filesystem provider) and I don't seem to remember this behaviour with the local filesystem provider.

### What version of Home Assistant Core are your running

2024.11.1

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
@khers

**Comment by Hukuma1** [comment]
Just tried the latest `2.3.4` with the fix and it's still not letting me seek? As soon as I click to skip ahead it just restarts the song from the beginning (the UI shows the song playing in the middle, but the song restarts).

**Comment by de666** [comment]
> Just tried the latest `2.3.4` with the fix and it's still not letting me seek? As soon as I click and scrub ahead it just restarts the song from the beginning (the UI shows the song playing in the middle, but the song restarts). Tried streaming to a native Google Home Mini device and an Airplay conversion of one as well (via [AirConnect](https://github.com/philippe44/AirConnect)).

Same behaviour here, it seems the fix doesn't work

**Comment by Hukuma1** [comment]
@khers I noticed this was closed out but it doesn't seem to be working. Can this please be re-opened/looked at some more?

**Comment by de666** [comment]
@marcelveldt is it possible to re-open this please?

**Comment by marcelveldt** [comment]
The mentioned fix is in beta not stable

**Comment by de666** [comment]
> The mentioned fix is in beta not stable

Fix https://github.com/music-assistant/server/pull/1798  mentioned in the chengelog of the following stable release
https://github.com/music-assistant/server/releases/tag/2.3.4

and the fix doesn't work (altrady tried in 2.3.4 and 2.3.5), so, what am I missing?

**Comment by OzGav** [comment]
BETA 2.4.0 not Stable 2.3.5

**Comment by de666** [comment]
> BETA 2.4.0 not Stable 2.3.5

ok, opened a new one, sorry for the misunderstanding
https://github.com/music-assistant/support/issues/3464

**Comment by de666** [comment]
> The code for this to work in the music provider is in stable, but there were changes needed in the core which are only in beta right now.

OK, now it's clear, I missed this.

**Comment by Hukuma1** [comment]
> BETA 2.4.0 not Stable 2.3.5 and confirm you have enabled the option in the SETTINGS

Thank you! Confirmed working (although I ended up crashing MA by seeking multiple times it seems) on my Google Home Mini using Chromecast. Although it does not work for Airplay?
