### ISSUE TITLE
Breaking Change Intoduced with the Removal of Player Attributes via the Integration

### ISSUE THREAD

**Issue by SCBionicle** [music-assistant/hass-music-assistant#3188]
### What version of Music Assistant has the issue?

2.3.2

### What version of the Home Assistant Integration have you got installed?

2024.11.4

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

A breaking changed was introduced in integration version 2024.11.0 that removed the following attributes from `media_player` entities in home assistant that broke automations:

- `queue_index`
- `items_in_queue`

### How to reproduce

Add items to a queue of a music assistant player, check the `media_player` attributes in the developer tools of home assistant.

### Music Providers

Tried:
- Spotify
- Music Assistant
- Radio Browser

Don't have access to other providers.

### Player Providers

Tried:
- Chromecast
- Slimproto
Didn't try other players because I do not have devices that connect via those platforms.

### Full log output

[music-assistant.log](https://github.com/user-attachments/files/17783751/music-assistant.log)

### Additional information

Would it be possible for these attributes to be re-added? These attributes were used for specialized sleep timers. Music assistant is being run as an addon on a windows Hyper-V VM running Home Assistant OS.

### What version of Home Assistant Core are your running

2024.11.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Alternative

**Comment by OzGav** [comment]
These were removed due to HA policies with the imminent move to core. Have you looked at the new get_queue action? It provides all that you have requested and.more

**Comment by SCBionicle** [comment]
Thank you. I was not aware of the addition.

**Comment by SCBionicle** [comment]
Also, congraduations on the accomplishment.
