### ISSUE TITLE
Dashboard in tablet lovelace UI

### ISSUE THREAD

**Issue by mrrouge** [music-assistant/hass-music-assistant#3198]
### What version of Music Assistant has the issue?

2.3.3

### What version of the Home Assistant Integration have you got installed?

2024.11.4

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Hi!
I'm trying to display the MA dashboard on a wall mounted tablet with HA official app.
I can show it using iframe from my PC browser (Admin), but I'm getting a "401: Unauthorized" error from the app (User).
Thanks for any help!

### How to reproduce

Try to display dashboard with iframe

### Music Providers

na

### Player Providers

na

### What version of Home Assistant Core are your running

2024.11.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
What is you network setup? You aren’t trying to do this with local SSL are you?

**Comment by mrrouge** [comment]
Hi, internal lan http. Just different users. Tried also open port but with no change.

**Comment by OzGav** [comment]
Does it work if you try the browser on the tablet?

**Comment by mrrouge** [comment]
Same error, 401: Unauthorized.
Logging as Admin on the App I have the left menu and the MA dashboard works from there, but not as iframe.

**Comment by OzGav** [comment]
What address are you trying to use in the iframe? Have you tried expsoing the webserver and acessing via port 8095?

**Comment by mrrouge** [comment]
Yes, expossing port 8095 or not, seems to have no effect.

Tried This:
`    cards:
      - type: iframe
        url: >-
          http://homeassistant.local:8123/api/hassio_ingress/............./#/home`
But i get: ERR_NAME_NOT_RESOLVED
And with:
`    cards:
      - type: iframe
        url: /api/hassio_ingress/................../#/home`
I get 401: Unauthorized

Both iframe urls work just fine on PC browser (Admin)

**Comment by jonasjeeliasson** [comment]
> Yes, exposing port 8095 or not, seems to have no effect.
> 
> Tried This:
> 
> ```
> cards:
>       - type: iframe
>         url: >-
>           http://homeassistant.local:8123/api/hassio_ingress/............./#/home
> ```
> 
> But i get: ERR_NAME_NOT_RESOLVED And with:
> 
> ```
> cards:
>       - type: iframe
>         url: /api/hassio_ingress/................../#/home
> ```
> 
> I get 401: Unauthorized
> 
> Both iframe urls work just fine on PC browser (Admin)

I get 401 as well in the app when trying to go through the ingress, but if I open music assistant from the sidebar once then the iframe starts working again 🤷‍♂️

**Comment by OzGav** [comment]
Expose the webserver port and try this:

```
cards:
      - type: iframe
        url: >-
          http://homeassistant.local:8095
```

**Comment by mrrouge** [comment]
Thanks, solved with: 

ipaddress:8095

It would be fantastic to have a nice lovelace page for MA!

**Comment by OzGav** [comment]
There are a number of discussions about this occurring right now https://github.com/orgs/music-assistant/discussions
