### ISSUE TITLE
Conversation agent won't play music without specifying player

### ISSUE THREAD

**Issue by caisamuels** [music-assistant/hass-music-assistant#3205]
### What version of Music Assistant has the issue?

2.3.3

### What version of the Home Assistant Integration have you got installed?

2024.11.4

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When asking the OpenAI conversation agent for a song without specifying the player, it returns raw JSON.

### How to reproduce

Without specifying player:
**Me**: Play the band U2
**OpenAI**: {"media_id":"U2","media_type":"artist"}

Specifying player:
**Me**: Play the band U2  on ESP
**OpenAI**: The artist Pink Floyd is now playing on the ESP.

### Music Providers

Spotify

### Player Providers

Home Assistant MediaPlayers

### What version of Home Assistant Core are your running

2024.11.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
How are you able to type the command and HA know what area that is coming from?

**Comment by OzGav** [comment]
Also looks like you aren't just using a conversation agent but you are using a full LLM

**Comment by caisamuels** [comment]
I just followed the MA Specific Conversation Agent tutorial. I am using OpenAI as the conversation agent. I thought you could just ask for a song without specifying the player as it is an example in the installation guide. I only have one media player set up so I just want it to play on that all the time, almost like a default media player.

**Comment by OzGav** [comment]
Ok reading your comment again I see you are using the full LLM. This is not a MA problem. You need to ask in the HA forums.
