### ISSUE TITLE
Covers not visible in playlist (subsonic provider)

### ISSUE THREAD

**Issue by de666** [music-assistant/hass-music-assistant#3215]
### What version of Music Assistant has the issue?

2.3.3

### What version of the Home Assistant Integration have you got installed?

2024.11.4

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Opening a playlist from subsonic provider results in not showing any cover art in the track list, only the main playlist cover art is shown.
This happens only for playlists, not for album track list or album list.

### How to reproduce

using subsonic provider open a playlist, no cover art displayed for any track in the playlist

### Music Providers

Subsonic

### Player Providers

Any

### Additional information

playlist view
![playlist_view](https://github.com/user-attachments/assets/a9a17170-7206-4ce4-a648-9c56b189183c)
tracks from an album view (correct), same as album list
![album_view](https://github.com/user-attachments/assets/acf00e26-3fa0-4eea-9ef2-331ed401c3f3)

Just for the record, in [Symphonium](https://symfonium.app/) android app, cover arts are correctly displayed when opening any playlist.

### What version of Home Assistant Core are your running

2024.11.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by khers** [comment]
I see this as well, the tracks in a playlist do not show the album cover art, I am not sure that album covers are associated with tracks but if they are supposed to be, I can make that change in the provider.

**Comment by de666** [comment]
> I am not sure that album covers are associated with tracks but if they are supposed to be, I can make that change in the provider.

The other providers show the track cover so I think subsonic provider should behave the same way.
