### ISSUE TITLE
Adding YouTube Music provider with premium account fails with "User does not have Youtube Music Premium"

### ISSUE THREAD

**Issue by liehann** [music-assistant/hass-music-assistant#3217]
### What version of Music Assistant has the issue?

2.4.0b7

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Trying to add YouTube Music fails with "User does not have Youtube Music Premium" error. My user does have YT Music Premium.

### How to reproduce

Have a YT Premium Family membership.
Try to add YT Music provider.
Adding provider fails with "User does not have Youtube Music Premium" error.

### Music Providers

YouTube Music

### Player Providers

N/A

### Full log output

[d5369777_music_assistant_beta_2024-11-23T19-50-21.841Z.log](https://github.com/user-attachments/files/17882385/d5369777_music_assistant_beta_2024-11-23T19-50-21.841Z.log)

### Additional information

Happy to provide additional account information and spend time debugging in detail. Please reach out with what additional information I can provide and how I can get additional logs.

### What version of Home Assistant Core are your running

2024.11.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Linux

**Comment by liehann** [comment]
I poked around the code and it looks like the error is thrown when the format doesn't match a specific format_id. Debug logging should show the response but I didn't see it in the debug logs. I've restarted the server and I only get the following logs. before the exception:

```
[youtube] Extracting URL: https://music.youtube.com/watch?v=dQw4w9WgXcQ
[youtube] dQw4w9WgXcQ: Downloading webpage
[youtube] dQw4w9WgXcQ: Downloading ios player API JSON
[youtube] dQw4w9WgXcQ: Downloading ios music player API JSON
[youtube] dQw4w9WgXcQ: Downloading m3u8 information
```

I also looked at the responses playing tracks in music.youtube.com for url https://music.youtube.com/youtubei/v1/player?prettyPrint=false request. The responses are very different but I don't see anything obvious that maps to 141 or m4a that the __init__ checks for. Eg on this [line](https://github.com/music-assistant/server/blob/stable/music_assistant/providers/ytmusic/__init__.py#L757C62-L757C75).

I think the most helpful next step is to get the full response from the watch request. Please advise what I can do to get that full response.

**Comment by liehann** [comment]
Hi OzGaz,

Thanks for the link. I couldn't tell you if it's a duplicate of what was originally reported in that issue, but the issue I ran into was reported in the comment section and the workaround suggested of using an incognito tab also worked for me. I will close as a duplicate, but happy to reopen if you want to track this issue as a separate thing from the Bad Request error.

**Comment by liehann** [comment]
Resolved.

**Comment by ragaimeena** [comment]
I am having same issue
How did you resolve it?

**Comment by MrKuenning** [comment]
I just started getting this error tonight.  I removed and re-added youtube music with the token and its saying I don't have premium.
