### ISSUE TITLE
All was working well now it keeps crashing

### ISSUE THREAD

**Issue by philspain72** [music-assistant/hass-music-assistant#3220]
### What version of Music Assistant has the issue?

2.3.3

### What version of the Home Assistant Integration have you got installed?

2024.11.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Its started crashing and would not load at all so I deleted and reinstalled still crashing and not starting on reboot

### How to reproduce

not sure what to put here its happens on startup and when I go to MA in side bar I get this
![Screenshot 2024-11-24 13 22 23](https://github.com/user-attachments/assets/373e26e6-d9ae-49cf-9da9-435fdb184e58)
![Screenshot 2024-11-24 13 21 57](https://github.com/user-attachments/assets/23107351-483e-4a15-b152-a6cad6262b7c)
if I put retry again it will start but then crashes again if I play a track it will start playing then restart

### Music Providers

local media folder

### Player Providers

chromecast

### Full log output

[mjpeg @ 0x7f967c0800] No JPEG data found in image
[mjpeg @ 0x7f967c1400] No JPEG data found in image
[vist#0:1/mjpeg @ 0x7f96450600] Error submitting packet to decoder: Invalid data found when processing input
Cannot determine format of input stream 0:1 after EOF
Error marking filters as finished
Error while filtering: Invalid data found when processing input
[vist#0:1/mjpeg @ 0x7f96450600] Decode error rate 1 exceeds maximum 0.666667
[out#0/mjpeg @ 0x7f965c0480] Nothing was written into output file, because at least one of its streams received no packets.
[mjpeg @ 0x7f993c0800] No JPEG data found in image
[mjpeg @ 0x7f993c1400] No JPEG data found in image
[vist#0:1/mjpeg @ 0x7f99050600] Error submitting packet to decoder: Invalid data found when processing input
Cannot determine format of input stream 0:1 after EOF
Error marking filters as finished
Error while filtering: Invalid data found when processing input
[vist#0:1/mjpeg @ 0x7f99050600] Decode error rate 1 exceeds maximum 0.666667
[out#0/mjpeg @ 0x7f991c0480] Nothing was written into output file, because at least one of its streams received no packets.
[mjpeg @ 0x7f84bd0800] No JPEG data found in image
[mjpeg @ 0x7f84bd1400] No JPEG data found in image
[vist#0:1/mjpeg @ 0x7f84850600] Error submitting packet to decoder: Invalid data found when processing input
Cannot determine format of input stream 0:1 after EOF
Error marking filters as finished
Error while filtering: Invalid data found when processing input
[vist#0:1/mjpeg @ 0x7f84850600] Decode error rate 1 exceeds maximum 0.666667
[out#0/mjpeg @ 0x7f849c0480] Nothing was written into output file, because at least one of its streams received no packets.
2024-11-24 05:02:24.302 ERROR (MainThread) [music_assistant] Error doing task: Task exception was never retrieved
Traceback (most recent call last):
  File "/app/venv/lib/python3.12/site-packages/music_assistant/providers/dlna/__init__.py", line 436, in discover_players
    await async_search(on_response)
  File "/app/venv/lib/python3.12/site-packages/async_upnp_client/search.py", line 193, in async_search
    await listener.async_start()
  File "/app/venv/lib/python3.12/site-packages/async_upnp_client/search.py", line 138, in async_start
    sock, _source, _target = get_ssdp_socket(self.source, self.target)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/async_upnp_client/ssdp.py", line 491, in get_ssdp_socket
    sock.setsockopt(
OSError: [Errno 19] No such device

### What version of Home Assistant Core are your running

2024.11.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
What did you delete and reinstall?

**Comment by philspain72** [comment]
I 'm running on Home Assistant Yellow. I just removed the add-on and reinstalled

**Comment by OzGav** [comment]
Please restart the addon. Wait until it starts. The first image you show is normal for when the MA server has not yet started so be patient. The open the UI, navigate to the MA SETTINGS>>CORE and download and ATTACH the log here. Please DO NOT PASTE it.

**Comment by philspain72** [comment]
[d5369777_music_assistant_2024-11-25T12-44-16.414Z.log](https://github.com/user-attachments/files/17903100/d5369777_music_assistant_2024-11-25T12-44-16.414Z.log)

**Comment by OzGav** [comment]
So MA is running and you went into the MA settings and downloaded that log?

**Comment by philspain72** [comment]
it keeps crashing if i try to play a track it gets about 30 seconds in then the track stops and MA restarts then starts playin another track and starts the same all over again.
It was working perfect ever since i install then i did not use it for a week or so and tried to use it and this keeps happening ever since

**Comment by OzGav** [comment]
I am not asking you to play a track. I want to see what the log looks like after MA starts. So please follow my instructions.

Please restart the addon. Wait until it starts. Then open the UI, navigate to the MA SETTINGS>>CORE and download and ATTACH the log.

**Comment by philspain72** [comment]
im trying i press the link that says download log
and it opens a new tab with this in http://192.168.0.125:8123/api/hassio_ingress/OXJEUVqgblV0zrTRK-Pos6L0-VuvtYJuZk7PN76KnL0/music-assistant.log but nothing else happens just a blank tab. I know I'm being stupid but not sure what I'm doing wrong sorry

**Comment by OzGav** [comment]
OK. Can you show a screen capture of the server information where you found the link for the log

**Comment by philspain72** [comment]
![Screenshot 2024-11-25 15 30 15](https://github.com/user-attachments/assets/a1666e40-d7f1-4e08-ac22-92aee620dd02)

**Comment by OzGav** [comment]
Alright that looks ok. What player providers do you use?

**Comment by philspain72** [comment]
2024-11-25 15:53:51.248 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Music Assistant Server is failed, restarting..

**Comment by OzGav** [comment]
Are you using YouTube?

**Comment by philspain72** [comment]
Im not using YouTube in HA

**Comment by OzGav** [comment]
Let us know what happens when you use safe mode. If it keeps running add one thing at a time and run with that for a while. Keep adding ONE provider at a time to narrow this down.
