### ISSUE TITLE
No Cover on Squeezebox 

### ISSUE THREAD

**Issue by kobelka** [music-assistant/hass-music-assistant#3227]
### What version of Music Assistant has the issue?

2.3.2

### What version of the Home Assistant Integration have you got installed?

2024.11.4

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

On my squeezeboxes there are no covers shown 

### How to reproduce

Start music over the music assistant

### Music Providers

tidal, spotify,tunein

### Player Providers

Squeezebox

### What version of Home Assistant Core are your running

2024.11.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Alternative

**Comment by OzGav** [comment]
You have ticked the box saying you reviewed the open issues. How is this not the same as https://github.com/music-assistant/hass-music-assistant/issues/2483
