### ISSUE TITLE
(Artist) Metadata not refreshing

### ISSUE THREAD

**Issue by ijc** [music-assistant/hass-music-assistant#3230]
### What version of Music Assistant has the issue?

2.3.3

### What version of the Home Assistant Integration have you got installed?

2024.11.5

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I was suffering from https://github.com/music-assistant/hass-music-assistant/issues/3108 and so did a database reset (while running version 2.3.3).

Since then I appear to have no artist metadata and it is not refreshing over time. I do have album images since I have those locally -- so I can't tell if remote album metadata is working or not.

It has been roughly a week since my most recent DB reset but no artist data has been retrieved other than when I have manually refreshed for individual artists. Manual update does work.

### How to reproduce

* Local storage with Picard tagged FLAC files, each directory is `ARTIST - ALBUM`
* `cover.jpeg` present in the vast majority if directories
* After a database reset no artist metadata is fetched from remote sources.

### Music Providers

Local storage, containing FLAC files. NFS mount bound into the docker container. There does not appear to be any issue with this end of things. 

Metadata providers (mentioning here since there isn't a box)
* The Audio DB
* fanart.tv
* MusicBrainz
I've set the log level to verbose on all of them and the metadata controller.

### Player Providers

I'm using Chromecast for the most part (to a Chromecast ultra on the TV and a JBL speaker). There is no issue here. There is also an nvidia shield in the system but I've never tried to play music on it.

### Full log output

[music-assistant.log](https://github.com/user-attachments/files/17918193/music-assistant.log)

### Additional information

I've tried a second database reset as well as clearing the cache.

If I disable and reenable "Enable retrieval from online metadata sources" on the metadata controller then I see:
```
2024-11-22 15:36:04.670 DEBUG (MainThread) [music_assistant.metadata] Start lookup for missing artist images...
2024-11-22 15:36:04.734 DEBUG (MainThread) [music_assistant.metadata] Start lookup for missing album images...
```
But nothing else from the metadata module(s)

I see in the git logs that metadata fetch was reworked between 2.2 and 2.3. My initial install was 2.2 or earlier and I did have metadata then, it seems to only have been when I reset after the upgrade to 2.3 that it became apparent that metadata was no longer being updated.

I see some stuff on Discord where people found the metadata was arriving slower than they expected but it seems they are getting _some_ metadata whereas I seem to be getting none at all unless I manually refresh.

I haven't tried the 2.4 beta releases since the git log doesn't seem to include anything relevant. Happy to give it a go though.

### What version of Home Assistant Core are your running

2024.11.0

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by max-t-d** [comment]
Thanks for opening this, I seem to have a similar issue, but manual refresh doesn’t work in my case. My entire library consists of tiles with initials - nothing gets fetched at all.

**Comment by ijc** [comment]
That's good, if manual refresh wasn't working then I'd wager that whatever your issue was it was distinct from (and more fundamental than) the one here.

**Comment by ijc** [comment]
@marcelveldt I'm suspicious of https://github.com/music-assistant/server/commit/823bf60f5a1d2d3c54f3f044bc52ee8e0f21a155.

I added some logging to `schedule_update_metadata` before and after the `self._lookup_jobs.put_nowait(uri)`:
```
2024-12-15 13:24:52.078 INFO (MainThread) [music_assistant.metadata] updating metadata for library://album/1515
2024-12-15 13:24:52.078 WARNING (MainThread) [music_assistant.metadata] pushing to queue with 0 items
2024-12-15 13:24:52.078 WARNING (MainThread) [music_assistant.metadata] queue now has 0 items
```
so nothing is ever queued[^0]. With some logging in `MetadataController.__init__` I see:
```
2024-12-15 13:24:40.904 INFO (MainThread) [music_assistant.metadata] MetaDataController: _lookup_jobs: <MetadataLookupQueue maxsize=0>
```

So it looks like the queue is zero size.

That's the default for `asyncio.Queue` which makes me wonder if the `MetadataLookupQueue._init` override hasn't actually worked for some reason?

I'll keep digging but thought the above was worth an update.

[^0] I also added logging for the suppressed `QueueFull` exception, but that never fires because `asyncio.Queue.full` considers a queue of size zero as "never full".

**Comment by ijc** [comment]
Ah, theory: when `asyncio.Queue.__init__(self, maxsize=0):` calls [self._init(maxsize)](https://github.com/python/cpython/blob/89f4b23f9efa4919e59cc542fd44062efc9898f2/Lib/asyncio/queues.py#L55) is is forwarding the `0` so the attempt to set a default of 100 in `MetadataLookupQueue._init` isn't taking effect.

I think `MetadataLookupQueue` needs an actual `__init__` which forwards to the superclass with it's preferred default maxsize.

**Comment by ijc** [comment]
https://github.com/music-assistant/server/pull/1805 works for me.
