### ISSUE TITLE
Random selection no longer working

### ISSUE THREAD

**Issue by TheSimTek** [music-assistant/hass-music-assistant#3232]
### What version of Music Assistant has the issue?

2.3.3

### What version of the Home Assistant Integration have you got installed?

2024.11.5

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

The random selection of my 511 track playlist is no longer working since the last update.

### How to reproduce

Select playlist and it plays in order, random selection appears in white but not activating. 

### Music Providers

Music Assistant

### Player Providers

Google Speaker

### What version of Home Assistant Core are your running

2024.11.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
It is not clear what the problem is. Please provide a clear step by step. Screenshots are helpful.

**Comment by TheSimTek** [comment]
Hi OzGav, reinstalling the add on has fixed my issue of not being able to my playlist in a random order.  Please close this ticket.
