### ISSUE TITLE
Bose Soundtouch not playing from music assistant

### ISSUE THREAD

**Issue by orangelizard** [music-assistant/hass-music-assistant#3233]
### What version of Music Assistant has the issue?

2.3.3

### What version of the Home Assistant Integration have you got installed?

2024.11.4

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Any source within Music Assistant fails to play on Bose Soundtouch speakers but plays fine on Denon Amps.

### How to reproduce

Just play any file from Music Assistant to a Bose speaker

### Music Providers

local files stored on Synology nas and Spotify

### Player Providers

Bose Soundtouch (Not Working)
Denon AVR 4800H (Working Fine)

### Full log output

[d5369777_music_assistant_2024-11-27T10-35-01.935Z.log](https://github.com/user-attachments/files/17932912/d5369777_music_assistant_2024-11-27T10-35-01.935Z.log)

### Additional information

It Fails from Music Assistant library page and from Node red mass.media nodes.

### What version of Home Assistant Core are your running

2024.11.3

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by kwesipk** [comment]
I have this same issue and would like to get this resolved. I am new and I am willing to help. Should I open a new issue?

**Comment by OzGav** [comment]
Don’t comment on closed issues. Open a Q&A in the discussion area. Issues are for faults in MA which, in this case, hasn’t been established yet.
