### ISSUE TITLE
Catalan translation

### ISSUE THREAD

**Issue by Josep-Softcatala** [music-assistant/hass-music-assistant#3252]
### New language

Català (catalan)

### Additional remarks

I want to contribute to the catalan translation.

**Comment by jozefKruszynski** [comment]
Quick question, should I add 'ca' or 'ca_ES' as the language identifier?

**Comment by jozefKruszynski** [comment]
ca_ES added.

**Comment by Josep-Softcatala** [comment]
Hi.The Catalan language is spoken in 4 different States: Andorra, Spain, France and Italy.  If there is no technical requirement, the best option is the "ca" code without State.  Furthermore, it is consistent with the language code used by Home Assistant, which is "ca".JosepEnviat des d'un mòbil Samsung
-------- Missatge original --------De: Jozef Kruszynski ***@***.***> Data: 3/12/24  10:48  (GMT+01:00) A: music-assistant/hass-music-assistant ***@***.***> Ac: Josep ***@***.***>, Author ***@***.***> Assumpte: Re: [music-assistant/hass-music-assistant] Catalan translation (Issue #3252) 
Quick question, should I add 'ca' or 'ca_ES' as the language identifier?

**Comment by jozefKruszynski** [comment]
Sorry, about that. I'll remove the ca_ES and add ca.

**Comment by Josep-Softcatala** [comment]
Thank you!JosepEnviat des d'un mòbil Samsung
-------- Missatge original --------De: Jozef Kruszynski ***@***.***> Data: 3/12/24  12:35  (GMT+01:00) A: music-assistant/hass-music-assistant ***@***.***> Ac: Josep ***@***.***>, Author ***@***.***> Assumpte: Re: [music-assistant/hass-music-assistant] Catalan translation (Issue #3252) 
Sorry, about that. I'll remove the ca_ES and add ca.

**Comment by jozefKruszynski** [comment]
I converted it now to ca, I know that it is a somewhat sensitive subject, so I apologise.

The settings may take a little while to catch up in terms of displaying correct word count etc.
