### ISSUE TITLE
Can't start a radio: Recommendations 

### ISSUE THREAD

**Issue by uneatensoup** [music-assistant/hass-music-assistant#3255]
### What version of Music Assistant has the issue?

2.3.3

### What version of the Home Assistant Integration have you got installed?

2024.11.4

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

## Description
Starting a radio mode via Music Assistant fails with a `MediaNotFoundError` related to Spotify recommendations. 

The issue persists across multiple attempts and playlists, making the feature unusable. Interestingly, this functionality was working previously but has suddenly stopped without any apparent changes.

## Steps to Reproduce
1. Attempt to start a radio mode for any playlist via the Music Assistant webserver.
2. Observe that the radio mode fails, producing the error logs below.

---

## Observed Behavior
- The radio mode fails to start.
- Errors related to `MediaNotFoundError` appear in the logs, suggesting issues with fetching recommendations from Spotify.

---

### Music Providers

- Two Spotify accounts are configured: one disabled (used with Music Assistant app) and one active (used with own Spotify app).

### Player Providers

Chromecast audio.

### Full log output

[refined_filtered_music_assistant_log.txt](https://github.com/user-attachments/files/17996143/refined_filtered_music_assistant_log.txt)

If these logs are unusable please let me know!

### What version of Home Assistant Core are your running

2024.11.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Yes it is the same and in future please don’t post debug logs unless asked. This will be looked at in due course.
