### ISSUE TITLE
Playback to Volumio media player does not start

### ISSUE THREAD

**Issue by MariuszTr** [music-assistant/hass-music-assistant#3269]
### What version of Music Assistant has the issue?

 2.3.3

### What version of the Home Assistant Integration have you got installed?

(HA Core) 2024.12.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Attempting to start playback after selecting the Volumio player results in playback not starting.
Volumio version 3.779.

### How to reproduce

Select your Volumio device as your player.
Try to start playing music.

### Music Providers

Spotify, Local files

### Player Providers

Google speakers work without any problems

### Additional information

I added the same device as a new player using the platform: mpd and its IP address as host.
Everything works fine here.

### What version of Home Assistant Core are your running

2024.12.0

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
You haven't specified what player provider you are using, I am guessing HA? You haven't attached a log? If you have it working with that other platform then I am not sure what the issue is?

**Comment by MariuszTr** [comment]
Let me start by saying that what I use and how I use it is my private business. I have Volumio integrated with HA using native integration. And in this combination everything works perfectly. However, due to the fact that Music Assistant has become an integral part of HA, I am reporting a problem that was already reported a long time ago and was never solved. But ok, thanks for your interest, but I see that my adventure with MA will end before it really began.
