### ISSUE TITLE
Mixed artist with cover

### ISSUE THREAD

**Issue by OldShaterhan** [music-assistant/hass-music-assistant#3284]
### What version of Music Assistant has the issue?

2.4.0b7

### What version of the Home Assistant Integration have you got installed?

it's official integration

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

The problem is that for some reason MASS is mixing covers with the artists:
![image](https://github.com/user-attachments/assets/db1ee5d9-261d-4de3-8c96-802b85525ab7)
This is not Cher on cover, it's sanah.
![image](https://github.com/user-attachments/assets/0c902cb1-d16c-4c21-ac36-e2d19665a2c0)
It's not Vanessa, it's sanah
![image](https://github.com/user-attachments/assets/00f54d5f-14c2-4667-ba4d-2e746baff207)
And it's nod Dawid Podsiadło, it's again sanah :D

### How to reproduce

I'm getting it on the main page of the server

### Music Providers

Spotify,
YT Music

### Player Providers

I don't think this is related.

### Additional information

I searched for labels "cover" and "artist" to check if similar issue was reported.

### What version of Home Assistant Core are your running

2024.12.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Firstly is the artist (in the text label) showing correctly for the track or album?

**Comment by OldShaterhan** [comment]
![image](https://github.com/user-attachments/assets/401a185e-7fd3-43e7-b9f7-643cf6ca84de)
I think here 2nd and 8th covers are mixed, when I try to open these:
![image](https://github.com/user-attachments/assets/376b581c-0d2d-4473-ae41-33bd5acf7ff7)
when I tried to open Maanam (shown as Will Roland) I'm getting:
![image](https://github.com/user-attachments/assets/847798d7-d322-4391-9d8b-dd088c7b0f9c)


Note: I reauthenticated Spotify & YT Music 1-2 days ago.

**Comment by OzGav** [comment]
There was a bug fixed about a month ago where artists were linked incorrectly. If you have had MA running for some time and have not done a database reset in the last month or so you may be affected by this. I suggest you do a database reset by going to MA SETTINGS>> CORE>>. MUSIC CONTROLLER >> ADVANCED

**Comment by OldShaterhan** [comment]
It's possible it is now working, but I'm not sure enough yet, as a lot of artists have no cover for now ;) (last played, albums, playlists are okay, just artists)

**Comment by OzGav** [comment]
Imagery is loaded slowly in the background. You can speed it up by selecting the artist then the menu top right and REFRESH METADATA

**Comment by OzGav** [comment]
Please close this if fixed

**Comment by OldShaterhan** [comment]
Seems to be okay now, thanks!
