### ISSUE TITLE
vb06b4 feature request : adding new sources to existing configuration

### ISSUE THREAD

**Issue by DutchJaFO** [music-assistant/hass-music-assistant#329]
situation :
I have configured my the integration with my Spotify account.
Once this was functioning I wanted to add a second source (local file system) to the integration.
I used the steps in https://github.com/music-assistant/hass-music-assistant/issues/71 to add the storage location on my nas, which worked perfectly.

problem :
The only way to do that was to delete the integration and add it again but now with the additional source configured.
This works, but is annoying as I also have to add set the area of all the new music assitant mediaplayer variants again, because I don't see them in the overall overview if I skip that.

Additional problem :
I now have duplicate artists/albums, because both Spotify and Filesystem sources have similar content.
example "Green day / American Idiot" exists both as a directory with mp3 files and as album in Spotify
It will be tricky to match or unmatch artists/albums where information is incomplete or incompatible, which may require some sort of manual override.

**Comment by marcelveldt** [comment]
1) You can click the "configure" button on the integration card to configure additional music sources.

2) Music is auto matched between sources. For local files you just need to make sure that your tags are complete.

**Comment by DutchJaFO** [comment]
the configure option doesn't offer the 'filesystem' or 'spotify' options that I get when starting from scratch.
It merely lists the existing music players while displaying an error even if I don't change a thing.

This is what I get :
![image](https://user-images.githubusercontent.com/39138434/173312274-d0cdeb44-cdd9-4d9b-bdeb-8b35e5bbe61f.png)
It lists everything in my system and because of that I can only click 'Next' , which displays an error message :
![image](https://user-images.githubusercontent.com/39138434/173313008-63aa91bc-16cf-4fd3-b24c-99424655f4fe.png)

If the next 'page' in this dialog would allow me to configure the media sources then that may be symptom of the bug.

In HA I have these DLNA renderers and servers : 
![image](https://user-images.githubusercontent.com/39138434/173313736-a5c293bc-2e45-4ca0-a589-978249bd9d75.png)
I suspect this may explain some of the duplicate mediaplayers that the system is listing.

Configured hardware in Home-Assistant  :
= PS4
= Xbox One
= NAS (Diskstation)
= Plex server (running on NAS, which creates a mediaplayer for every system that has a client ... )
= Emby / Jellyfin server (running on NAS)
= 5 Sonos speakers (3 Sonos Play:1, 1 Symfonisk, 1 Port)

Emby/Jellyfin is part of an experiment because Plex doesn't serve ISO files and I'm looking for an alternative that allows me to serve DVD's over my internal network.

**Comment by marcelveldt** [comment]
The whole "config flow" is next on my list to fix and make a bit more friendly.
And yes, if you select you want to use a player with music assistant, there's a toggle to hide the "original" player from the UI.

original player --> Music Assistant --> final player including metadata and additional controls/options

**Comment by erkr** [comment]
@DutchJaFO 
I marked this issue as a bug.
I guess you can perfectly help to validate the planned revision of the config flow against your large setup.
Best Eric

**Comment by DutchJaFO** [comment]
@erkr agreed. This is a very complex setup, but it may be typical for the kind of situation that music assistant hopes to resolve.
It may even have more than a few dead entities as a result of me re-configuring several mediaplayer integrations.

Heck ... I myself I'm still trying to re-think what I want to do with the various mediaplayers within HA itself.
My current idea is that my NAS serves as a fallback media source for the gaps in the Spotify media list and as a fallback media source whenever internet/spotify is down for some reason.

**Comment by erkr** [comment]
> My current idea is that my NAS serves as a fallback media source for the gaps in the Spotify media list and as a fallback media source whenever internet/spotify is down for some reason.

Chromecasts also won't work when Internet is down. But luckily you are not limited to them ☺️

**Comment by marcelveldt** [comment]
should be fixed in beta 6
