### ISSUE TITLE
Can't join/unjoin players since moving to Core Integration 

### ISSUE THREAD

**Issue by lacalamine64** [music-assistant/hass-music-assistant#3293]
### What version of Music Assistant has the issue?

2.3.3

### What version of the Home Assistant Integration have you got installed?

Core 2024.12.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When using join/unjoin actions in automations/scripts I get the following error:

Error running action
Invalid command: players/cmd/group_many

It started after moving to Core integration. With HACS it worked fine.

### How to reproduce

Use join/unjoin action.

### Music Providers

Spotify

### Player Providers

SONOS

### What version of Home Assistant Core are your running

2024.12.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by marcelveldt** [comment]
This is fixed in beta server - we forgot to bump the stable version. I'll try to do so this weekend

**Comment by fbloemhof** [comment]
I can confirm it is working in beta.
