### ISSUE TITLE
v06b4 wrong (album) artist for file source media

### ISSUE THREAD

**Issue by DutchJaFO** [music-assistant/hass-music-assistant#330]
situation :
configure remote file system using the shell_command and automation as listed in https://github.com/music-assistant/hass-music-assistant/issues/71

folders on remote system have a naming convention : [artist] / [album title]

result :
music assistant displays wrong (album) artist when playing the file.
home assistant itself does display the correct artist when playing the same file using a mediaplayer.

![image](https://user-images.githubusercontent.com/39138434/173256969-04238a68-17d6-4b9e-97c2-8ef45e987664.png)

I did notice that the file itself had the artist set as 'contributing artist' and 'album artist' was empty ... this may be a factor.

**Comment by marcelveldt** [comment]
Album artist ID3 tag MUST be set for this to work. Folders are only used to retrieve any additional metadata such as images or info from nfo files for the ID3 tags are leading.

**Comment by DutchJaFO** [comment]
looks like I've got a lot of work to do then ... 
Is it possible to assume 'contributing artist' = 'album artist' when the latter isn't set ?
At the very least it should show 'undefined' or 'missing' instead of a the wrong artist ('caro emerald' ?)

**Comment by marcelveldt** [comment]
No that would be very bad... consider a collection album (e.g. Hitzone etc) where you have tracks of multiple artists. 

A track has one or more artists (=contributing artist track)
A track may belong to an album
An album has one or more album artists

If we're scanning for songs on disk we read the ID3 tags. If we album tag is set but the albumartist tag is not we now fallback to various artists and print a note in the log.

**Comment by marcelveldt** [comment]
BTW: Musicbrainz Picard is a great and free tool to rapidly fix the ID3 tags

**Comment by DutchJaFO** [comment]
That makes sense. I forget that the mp3 file itself also needs the album info inside of it.

I've got MP3 tag, which is really useful when automagically fixing tag issues such as this, because it can copy info from filename as well as things like musicbrainz and freedb.  The problem is that it can be very hard to identify missing info if the mediaplayers appear to show the 'correct' info. There also appears to be a few versions of tag-info within mp3 files themselves.

**Comment by marcelveldt** [comment]
fixed small detail that changing the album artist in the ID3 tag will now overwrite the db details

**Comment by DutchJaFO** [comment]
I can't find any albums with the wrong artist in my collection at the moment.
In part because I've fixed the offending files myself (mp3's were missing album artist tags).
The one album with 'unknown' as an artist in the album overview is correct as I don't know the artist ...
