### ISSUE TITLE
Artist metadata never loaded automatically

### ISSUE THREAD

**Issue by kusk** [music-assistant/hass-music-assistant#3300]
### What version of Music Assistant has the issue?

2.3.3

### What version of the Home Assistant Integration have you got installed?

2024.12.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

After loading music from a remote share the metadata for artists are not loaded. The cover art and artist image can only be loaded manually by clicking the "Update Metadata" for each artists which is cumbersome with a large amount of different artists.

![image](https://github.com/user-attachments/assets/75d66836-7b53-4523-9e6a-134e7d4c10b9)

A fix could be to able to mass update metadata for all artists.

### How to reproduce

1. Load music from remote share.
2. Browser to "Artists"

### Music Providers

Remote Share

### Player Providers

Everyone

### What version of Home Assistant Core are your running

2024.12.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Alternative

**Comment by OzGav** [comment]
Did you really look at the issues before posting this
https://github.com/music-assistant/hass-music-assistant/issues/3230
https://github.com/music-assistant/hass-music-assistant/issues/3297
