### ISSUE TITLE
Missing "by Spotify" playlists from my library in  MA

### ISSUE THREAD

**Issue by Chacsam** [music-assistant/hass-music-assistant#3303]
### What version of Music Assistant has the issue?

2.3.3

### What version of the Home Assistant Integration have you got installed?

2024.12.3

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When connecting my Spotify account, the playlists created by Spotify which are saved in my Library do not appear in MA.
My personal playlist as well as other public/shared lists sync ok, only the "created by Spotify" ones do not (neither general thematic lists such as https://open.spotify.com/playlist/37i9dQZF1DX0Yxoavh5qJV, nor personalized such as daily mixes...) 

### How to reproduce

Happened on first synchronisation. 
Sync or reload didn't help

### Music Providers

Spotify

### Player Providers

Google Cast

### Additional information

adding A Spotify Dev API key didn't help.
No error in log:
```
2024-12-14 10:05:15.667 INFO (MainThread) [music_assistant.spotify] Successfully logged in to Spotify as User
2024-12-14 10:05:15.668 INFO (MainThread) [music_assistant] Loaded music provider Spotify
2024-12-14 10:06:03.763 INFO (MainThread) [music_assistant.music] Sync task for Spotify: User completed
```

### What version of Home Assistant Core are your running

2024.12.3

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
This is not an issue it is a feature request which already exists https://github.com/orgs/music-assistant/discussions/1797
