### ISSUE TITLE
Running Filesystem (remoteshare) Playlist Track Info Not Updating While Playing

### ISSUE THREAD

**Issue by dtspinella** [music-assistant/hass-music-assistant#3304]
### What version of Music Assistant has the issue?

2.0.1

### What version of the Home Assistant Integration have you got installed?

2024.12.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When playing a playlist from Filesystem (remote share) the track info and artwork does not update from track to track and remains on the first track played and the track time accumulates from track to track.

I have posted about this issue in the community forums but had no response and saw at least on other post on the same issue.

### How to reproduce

Select player (speaker), select playlist, hit Play. Wait for track to finish and advance to next track.

### Music Providers

Filesystem (remoteshare)

### Player Providers

Home Assistant MediaPlayers

### Full log output

I have attached the Music Assistant Server log and the debug log from the MA integration. I could discern how to get to MA Settings>>Core

[d5369777_music_assistant_2024-12-14T18-32-07.705Z.log](https://github.com/user-attachments/files/18137208/d5369777_music_assistant_2024-12-14T18-32-07.705Z.log)

[home-assistant_music_assistant_2024-12-14T18-38-58.993Z.log](https://github.com/user-attachments/files/18137220/home-assistant_music_assistant_2024-12-14T18-38-58.993Z.log)

### Additional information

The issue is the same if you use use the MA UI or playback is initiated from a script.

### What version of Home Assistant Core are your running

2024.12.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Why have you not supplied all of the info required by the troubleshooting page? Specifically what have you done to rectify this that hasn’t worked?

**Comment by dtspinella** [comment]
Meant to. I have reloaded the MA server and integration twice. I have removed the Filesystem provider and added it back in. I have created new playlists and nothing has been effective. This happened in both the older HASS custom version and now is happening in the newer version. I can view all the tracks in the playlist.

Dan Spinella
***@***.***
________________________________

**Comment by OzGav** [comment]
That is not what the player provider docs say to try

**Comment by dtspinella** [comment]
I have gone through the Player Provider doc steps. l checked all the settings and cleared the cache. Checked for proper tags. followed the steps for reload of MA,HA and the reboot. None of the steps have helped.

**Comment by OzGav** [comment]
So you have tried changing the http profiles?

**Comment by dtspinella** [comment]
Yes I have switched from automatic to the internal IP and the behavior is the same.

**Comment by OzGav** [comment]
That is not what I am talking about. Look at the docs again, in the notes section. Dot point 6 (and maybe 7)

**Comment by dtspinella** [comment]
Is this what you are referring to?

Make sure the HA internal url is set correctly. HA SETTINGS>>SYSTEM>>NETWORK>>Home Assistant URL>>Local network (set to automatic or use your internal HA IP). If it is automatic you can try changing it to http://your.internal.ip:8123/

**Comment by OzGav** [comment]
No. The troubleshooting page where you got that from eventually directs you to the player provider page. Look at the HA player provider documentation

**Comment by dtspinella** [comment]
Got it (finally :-) ) I have tried all 3 profiles and reloaded each time with no change. I do see that if I go into the dropdown for the player screen and change the player settings the screen refreshes to the currently playing track but the behavior resumes with the next track.

**Comment by happnatious1** [comment]
I am seeing the same behavior.  The cue also doesn't update.  Refreshing browser window doesn't help. Pressing next track updates the  currently playing track and the cue.

**Comment by OzGav** [comment]
What about changing the metadata profile? Also what sort of player is this. As is mentioned in the docs HA players are subject to the limitations of the HA integration.

**Comment by dtspinella** [comment]
I tried all 3 metadata with no success. I am doing this on the HA MediaPlayers. If I use the Sonos player the only player that works is my Sonos port and that works perfectly, the Play:1s will not play at all. They just queue up and will not respond to the play button.

**Comment by OzGav** [comment]
Well you have something else going on then because I think we have people using the play 1. Please be very specific with your information. Are you saying you are playing to the Play 1 via the HA media player? Are you trying any other HA media players? What do you see in the log when you use the native Sonos provider and try and play to the Play:1?

**Comment by happnatious1** [comment]
I'm using osmc(kodi) as a player. 
Music is a mp3 & flac  library on my Nas (remote share). 
Most things were working before moving MusicAssistant to the core. (Directions were not clear. I struggled.)
I feel there is an issue between MusicAssistant and the cores' web server. The web interface is not keeping pace with what is actually happening.

**Comment by dtspinella** [comment]
When using HA MediaPlayers Player Provider all my of Sonos speakers play. I only added the Sonos Player Provider to test to see if the issue was the same or not. When I try to use the Sonos created player is when I encounter the no playing issue with the Play:1s. These are two separate issues. The Sonos Player Provider issue is not a big concern to me and not surprising to me since Sonos has made a mess of things with the firmware and app changes they did. I have already removed it from the Player Providers.

**Comment by happnatious1** [comment]
My house is hardwired using a Monoprice 6 zone amp. Osmc streams an optical signal to it. I don't use Sonos.

**Comment by dtspinella** [comment]
The issue also happens with my Denon AVR (it uses the HEOS input) which is also under the HA MediaPlayers.

**Comment by OzGav** [comment]
With the Denon make sure you are using the HEOS integration not the Denon one

**Comment by dtspinella** [comment]
Thanks OzGav. Switched the AVR player to the Heos entity and that works now.

**Comment by OzGav** [comment]
@dtspinella if your initial issue is resolved please close this. If not clarify again where we are at.

**Comment by happnatious1** [comment]
The title of this issue perfectly describes the issue I'm seeing. Should I continue here or start my own issue?

**Comment by OzGav** [comment]
@happnatious1 what player provider are you using?

**Comment by happnatious1** [comment]
Home Assistant MediaPlayers
Player entities under generic settings is osmc(media_player.osmc_2)

**Comment by OzGav** [comment]
What ha integration?

**Comment by dtspinella** [comment]
Sorry for the delayed response been away. That only fixed an issue with the Denon AVR. The Sonos issue still exists.

**Comment by OzGav** [comment]
@dtspinella you need to be using the native Sonos integration

**Comment by dtspinella** [comment]
OzGav - 

I have changed  it to the Sonos integration. It initially had one issue. When I tried to play to my Sonos Port it wouldn't but redirected to the Play:1 in the dining room. I restarted both of them and now it plays to the choosen player. The display in MA now shows the correct track name, art and time info. Will the Home Assistant Media Player be able to do this in a future update?

Thanks

**Comment by OzGav** [comment]
The HA media players are a fallback option when a native player is not available. You need to use the native player and then use the MA entity for that player in HA. You should remove the Sonos integration from HA

**Comment by OzGav** [comment]
It sounds like this has been resolved and can be closed.

**Comment by dtspinella** [comment]
Should have said Sonos Player Provider not integration.Will remove the Sonos integration.

**Comment by dtspinella** [comment]
Thanks for your help.

**Comment by dtspinella** [comment]
I’m good with closing it. I have gotten everything working correctly.

Dan Spinella
***@***.***
________________________________
