### ISSUE TITLE
Home Assistant MediaPlayer not Playing after update

### ISSUE THREAD

**Issue by BrilliantStanley** [music-assistant/hass-music-assistant#3305]
### What version of Music Assistant has the issue?

2.4.0b7

### What version of the Home Assistant Integration have you got installed?

native

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Unable to start playback on Chromecast via Home assistant player after upgrading from 2.4.0b3 to 2.4.0b7. Playback was previously working on 2.4.0b3

### How to reproduce

Start playback on chromecast device added using Home Assistant Player.

### Music Providers

Any

### Player Providers

Home Assistant Player

### Full log output

[music-assistant.log](https://github.com/user-attachments/files/18139572/music-assistant.log)

### Additional information

I was unable to use the native Chromecast due to mdns restriction. HA server was located in other site using wireguard site-to-site tunnel. Chromecast device was added to home assistant via Chromecast integration using IP address.

### What version of Home Assistant Core are your running

2024.12.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
You need to use the native chromecast provider

**Comment by BrilliantStanley** [comment]
I was unable to use the native Chromecast due to mdns restriction. Chromecast device was added to home assistant via Chromecast integration using IP address. It was working on 2.4.0b3 untill when I updated to 2.4.0b7. My solution for now is to downgrade back to 2.4.0b3 which works fine.

**Comment by OzGav** [comment]
After discussions this will not be looked at for the reason I mentioned above. Sorry. Hopefully you can simplify your home network setup,
