### ISSUE TITLE
Feature request: Same stream to multiple devices?

### ISSUE THREAD

**Issue by alexd321** [music-assistant/hass-music-assistant#331]
Would be great if one could duplicate the music across devices. 

Can do this manually by copying the stream url

**Comment by marcelveldt** [comment]
Just create a group helper and you can stream to multiple devices.

**Comment by marcelveldt** [comment]
btw: manually copying the stream url will not work, that will fail the buffer

**Comment by erkr** [comment]
Marcel created a FAQ topic for this: https://github.com/music-assistant/hass-music-assistant/discussions/441
