### ISSUE TITLE
Public playlists created by Spotify are not displayed and not playable via Music Assistant

### ISSUE THREAD

**Issue by JoergBr** [music-assistant/hass-music-assistant#3310]
### What version of Music Assistant has the issue?

2.3.3

### What version of the Home Assistant Integration have you got installed?

2024.12 (integrated, not HACS)

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

1. (Only) public playlists from Spotify are not visible in Music Assistant, even though tagged as favorite in Spotify.
2. If trying to play them via URL from Home Assistant, the error "no playable items found" appears.
Example: "Feel Good Dinner" https://open.spotify.com/playlist/37i9dQZF1DXbm6HfkbMtFZ
All other playlists (own or from other users) display and are played without problems.
In HA, the playlist created by spotify CAN be played using the sonos integration!
Spotifiy is subscribed as premium.

### How to reproduce

1. Add https://open.spotify.com/playlist/37i9dQZF1DXbm6HfkbMtFZ to favorite playlists in spotify
2. Refresh library for same spotify account in Music Assistant
3. Navigate to playlists for the spotify account => playlist is not shown
4. Try to play the above URL via Home Assistant, using a player provided by Music Assistant => error "no playable items found"
5. Try to play the above URL via Home Assistant, using a player provided by the Sonos Integration => success

### Music Providers

Spotify

### Player Providers

Sonos (not grouped)

### Full log output

[music-assistant.log](https://github.com/user-attachments/files/18148062/music-assistant.log)

### Additional information

Home Assistant and Music Assistant both running in docker containers

### What version of Home Assistant Core are your running

2024.12.1

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
This is not an issue it is a feature request. Isn’t it the same as https://github.com/orgs/music-assistant/discussions/1797
