### ISSUE TITLE
Error when trying to save auth cookie for youtube music

### ISSUE THREAD

**Issue by small1** [music-assistant/hass-music-assistant#3315]
### What version of Music Assistant has the issue?

2.3.3

### What version of the Home Assistant Integration have you got installed?

2024.12.3

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When trying to save the cookie the following error pops ups:

`ERROR: [youtube] dQw4w9WgXcQ: Requested format is not available. Use --list-formats for a list of available formats`

### How to reproduce

add youtube music  provider, enter information and press save

### Music Providers

youtube music

### Player Providers

N/A as i cant add the provider

### Full log output

[music-assistant.log](https://github.com/user-attachments/files/18163375/music-assistant.log)

### Additional information

youtube music stopped working yesterday so i went to add the cookie again thinking that it timed out. But could not save the new cookie. 

### What version of Home Assistant Core are your running

2024.12.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by small1** [comment]
With debug log on:

`yt_dlp.utils.DownloadError: ERROR: [youtube] dQw4w9WgXcQ: Requested format is not available. Use --list-formats for a list of available formats

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/venv/lib/python3.12/site-packages/music_assistant/controllers/webserver.py", line 361, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/music_assistant/controllers/config.py", line 272, in save_provider_config
    config = await self._add_provider_config(provider_domain, values)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/music_assistant/controllers/config.py", line 836, in _add_provider_config
    await self.mass.load_provider_config(config)
  File "/app/venv/lib/python3.12/site-packages/music_assistant/mass.py", line 438, in load_provider_config
    await self._load_provider(prov_conf)
  File "/app/venv/lib/python3.12/site-packages/music_assistant/mass.py", line 616, in _load_provider
    await provider.handle_async_init()
  File "/app/venv/lib/python3.12/site-packages/music_assistant/providers/ytmusic/__init__.py", line 184, in handle_async_init
    if not await self._user_has_ytm_premium():
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/music_assistant/providers/ytmusic/__init__.py", line 779, in _user_has_ytm_premium
    stream_format = await self._get_stream_format(YTM_PREMIUM_CHECK_TRACK_ID)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/music_assistant/providers/ytmusic/__init__.py", line 761, in _get_stream_format
    return await asyncio.to_thread(_extract_best_stream_url_format)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/music_assistant/providers/ytmusic/__init__.py", line 756, in _extract_best_stream_url_format
    raise UnplayableMediaError(err) from err
music_assistant_models.errors.UnplayableMediaError: ERROR: [youtube] dQw4w9WgXcQ: Requested format is not available. Use --list-formats for a list of available formats`

**Comment by small1** [comment]
So the problem seems to be the inital sync some format change that requires newer yt_dlp?

**Comment by reyjeevehm** [comment]
Possible solution:
Rebuild (and fix any breaking changes) after changing to yt-dlp==2024.12.13 in https://github.com/music-assistant/server/blob/dev/requirements_all.txt

Finally fixed 4 days ago in [yt-dlp 2024.12.13](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.12.13) after multiple PRs:
https://github.com/yt-dlp/yt-dlp/pull/11750
https://github.com/yt-dlp/yt-dlp/pull/11751
https://github.com/yt-dlp/yt-dlp/pull/11752
https://github.com/yt-dlp/yt-dlp/pull/11801

Original yt-dlp issue reported 2 weeks ago:
https://github.com/yt-dlp/yt-dlp/issues/11744

**Comment by OzGav** [comment]
The dev is looking at it. Google continues to make changes which make it increasing difficult to come up with a workable solution.

**Comment by TheWebMachine** [comment]
> The dev is looking at it. Google continues to make changes which make it increasing difficult to come up with a workable solution.

We're all aware of the neverending game of cat and mouse with Google, unfortunately. 😮‍💨 Every year, I separate another part of my life from Google's ecosystem. A music divorce may have to be a 2025 goal, at this rate. I really wish they would just let us _paying_ customers have our music the way we want. I guess they just don't want our money bad enough. 🤷‍♂️

**Comment by wildoracle** [comment]
> > The dev is looking at it. Google continues to make changes which make it increasing difficult to come up with a workable solution.
> 
> We're all aware of the neverending game of cat and mouse with Google, unfortunately. 😮‍💨 Every year, I separate another part of my life from Google's ecosystem. A music divorce may have to be a 2025 goal, at this rate. I really wish they would just let us _paying_ customers have our music the way we want. I guess they just don't want our money bad enough. 🤷‍♂️

I agree. 2024 was when I finally broke down and switched from the abysmally bad google speakers for music to a SONOS system. I was hoping to use Music Assistant with my YT Music playlists because the Sonos app truncates YT playlists at some low song count like 100, making me wonder why I was listening to the same 100 songs on repeat from a playlist of thousands of songs. But Sonos doesn't mention that. It's cat-and-mouse all over again and we're the mouse.

**Comment by cybik** [comment]
As a joke: [I can't believe Rick Astley's dQw4w9WgXcQ has let us down.](https://youtu.be/dQw4w9WgXcQ)

(Feel free to delete this comment posted only for humor)

**Comment by Dnny44** [comment]
Can confirm same error here: ERROR: [youtube] dQw4w9WgXcQ: Requested format is not available. Use --list-formats for a list of available formats

**Comment by kaiserkiwi** [comment]
Updated to Home Assistant 2024.12 today and I'm unable to use YouTube Music in Music Assistant now too. That's a bummer. I hope this is soon fixed. 

My error:
```
ERROR: [youtube] dQw4w9WgXcQ: Requested format is not available. Use --list-formats for a list of available formats
```

**Comment by OzGav** [comment]
Thanks we don’t need any +1s we know the problem

**Comment by Liefxx** [comment]
I just tried installing Music Assistant for the first time and got the error.

Wild that the error is the video ID for Never Gonna Give You Up.

Good to see this is a recent thread so it's not a me thing. 

GL with the fix and thank you!

**Comment by szemod** [comment]
ERROR: [youtube] dQw4w9WgXcQ: Requested format is not available. Use --list-formats for a list of available formats
I have the same issue, and I got the cookie the same way as before, but now it doesn't work...

**Comment by OzGav** [comment]
2.3.4 includes the current fix for this. Beta to follow. Expect a 5-10 sec delay before playback commences. If it’s faster that is a bonus.

**Comment by afs5327** [comment]
Updated - working for me. 🔥 
Thank you!
