### ISSUE TITLE
V.06b4: player state issue

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#332]
This one is reasonably new (works before):
I start a radio station on my CC group. Playing starts fine, but I can't control the individual volumes of the child CC's, as their state remained off. This was the state view:
![image](https://user-images.githubusercontent.com/4363599/173324412-41953e65-6511-4270-bcb5-a191954d62af.jpeg)
Also strange that the volume indicator for the group is zero. ( I tried to adjust their volumes in the home app; their the state was playing and the volumes could be adjusted. BUT that didn't change anything in HA/MA)
After tapping the power buttons of the individual players (in MA), their state was correct:
![image](https://user-images.githubusercontent.com/4363599/173324905-c9e2dfe5-eaf6-4e92-8c4c-0105344a9147.jpeg)

**Comment by erkr** [comment]
Update v06b5:
I know this issue is still in. But some extra info. In MA the child player of the group cast has the wrong state (off):
![image](https://user-images.githubusercontent.com/4363599/173586606-a6f604a3-c4e1-429b-85ab-e3b306944294.jpeg)

The corresponding source player is correct:
![image](https://user-images.githubusercontent.com/4363599/173586657-57ee012c-f44b-4900-a068-1c9cb5b2de1b.jpeg)

**Comment by erkr** [comment]
Then I added two other players of the CC group. Same story.
They automatically start playing ad well, but their state in MA is wrong, while in HA the source players are correct

**Comment by erkr** [comment]
Nice

**Comment by erkr** [comment]
Ps: the state also fail's when the players where used before and I kept them powered

**Comment by marcelveldt** [comment]
should be fixed in beta 6

**Comment by erkr** [comment]
Thanks, it works great now in beta 7
