### ISSUE TITLE
TTS not working on Google Nest when audio is playing

### ISSUE THREAD

**Issue by xXMrJackXx** [music-assistant/hass-music-assistant#3321]
### What version of Music Assistant has the issue?

2.3.3

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When a google nest (mini or hub) is already playing music (for example from spotify), a TTS to that device isn't working.
I use the following script in one of my automations:
```
action: tts.google_cloud_say
data:
  cache: true
  entity_id: media_player.nest_mini_mass
  message: "{{message}}"
  language: de-DE
```
If ``media_player.nest_mini_mass`` is idle, TTS works. 
If it's playing music, the below exception occurs and the script stops working.
If I use the home assistant media player instead of the one music assistant created, it works again.

Exception:
``Error: CastMediaPlayerEntity.media_stop Failed: Execution of stop timed out after 10.0 s.``

### How to reproduce

Start music on a google nest player and try to call a TTS action on that device.

### Music Providers

Spotify

### Player Providers

Home Assistant MediaPlayers

### What version of Home Assistant Core are your running

2024.12.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Add the full log entry as requested in the issue template.

I cannot recreate this with a Google Mini using  tts.google_say 

Try without the language option. Try a different tts action. Try with other cast devices if you have them

**Comment by xXMrJackXx** [comment]
I tried without the language option and also the action ``tts.speak`` with entity_id ``tts.home_assistant_cloud`` and ``tts.google_cloud``. Same problem.
Unfortuntely I don't have other cast devices to try.

**Comment by OzGav** [comment]
You need to fix the problems with Spotify before this can be looked at. Review the docs and get your own clientid

**Comment by xXMrJackXx** [comment]
I have re-added the Spotify provider with 2 other (since we use 3 different accounts), all with a clientid. Same problem, log shows no new entries, except the known ``2024-12-19 11:21:00.764 ERROR (MainThread) [music_assistant.webserver] Error handling message: players/cmd/play_announcement: CastMediaPlayerEntity.media_stop Failed: Execution of stop timed out after 10.0 s.``

**Comment by OzGav** [comment]
Post the full log again please

**Comment by xXMrJackXx** [comment]
Sure
[music-assistant.log](https://github.com/user-attachments/files/18206585/music-assistant.log)

**Comment by OzGav** [comment]
There is some problem with the clientid as your log is still full of problems. Try completely removing Spotify. Wait until you see an entry in the log that the removal is complete, then restart MA and then re-add the Spotify provider with your clientid

**Comment by xXMrJackXx** [comment]
I'm sorry but I cannot see any problems with the clientid. The new log messages after re-adding the spotify account start with the log ``Removing provider spotify--ooeoYr2c``. From there on the only error I got was when trying to play an announcement as I described earlier. Other than that I only see 4 warnings about the ``RadioBrowser`` which should be unrelated to my problem.

**Comment by OzGav** [comment]
Then you have attached the wrong log above

**Comment by xXMrJackXx** [comment]
It looks like I'm the only one with this problem. 
I also still don't understand what an incomplete Spotify configuration has to do with the TTS functionallity. And since my attached log files don't seem to lead to any possible error analysis, I've now simply built a workaround:
In my automation, when the player is playing, I call the TTS action with the original entity and if not, I call it with the music assistant entity.
This is not really a solution to my problem, but at least the TTS and the subsequent actions in my automation work without interruption.
Thanks anyway for your effort.

**Comment by OzGav** [comment]
I didn’t comment further as you never did attach the log file without all the Spotify errors. However, if you are satisfied with your workaround then ok.
