### ISSUE TITLE
media_player.search not available on HASS Core

### ISSUE THREAD

**Issue by ronluna** [music-assistant/hass-music-assistant#3323]
### What version of Music Assistant has the issue?

2.4.0b7

### What version of the Home Assistant Integration have you got installed?

2024.12.4

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

media_player.search does not seems available in official HASS distribution... When using the one from HACS (CUSTOM) media_player.search is available. 

### How to reproduce

remove the MA CUSTOM instegration and replace it with the recently added to HA core. 

### Music Providers

Spotify

### Player Providers

Snapcast

### Full log output

N/A

### What version of Home Assistant Core are your running

2024.12.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by ronluna** [comment]
Just wondering ...Why migrate to the and stop maintaining the custom integration if it's going to be missing features?

**Comment by OzGav** [comment]
Because HA requirements dictated a minimal initial PR which could be properly reviewed. The remaining actions are planned to be added next HA release
