### ISSUE TITLE
Repeat mode is set to repeat the queue, but stops playing when the queue is finished

### ISSUE THREAD

**Issue by tomazzive** [music-assistant/hass-music-assistant#3332]
### What version of Music Assistant has the issue?

2.3.3

### What version of the Home Assistant Integration have you got installed?

2024.12.4

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I have a playlist with 30 songs on my local filedisk. I play the playlist on a Sonos device. I set the repeat mode to repeat the entire queue. Yet, when it reaches the final song, it stops playing music. I tried creating a new playlist with only two songs, same issue. I disabled the random order, same issue. 

### How to reproduce

- play a playlist on the Sonos device
- set the repeat mode on repeat the queue
- wait untill the last song of the playlist is played
- the music stops instead of repeating the queue
- look at the screenshot: one song remains in the queue and the current played song stops at the last second:

![image](https://github.com/user-attachments/assets/bd4433d0-e68c-4c27-9df9-d476d050d5d9)

### Music Providers

local file disk: mp3 files

### Player Providers

SONOS device

### What version of Home Assistant Core are your running

2024.12.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
You have ticked that you have read the troubleshooting docs but you have not supplied the required info from there nor the template instructions
