### ISSUE TITLE
MA ignores files with extensions that are not lowercase

### ISSUE THREAD

**Issue by baulaergrungim** [music-assistant/hass-music-assistant#3335]
### What version of Music Assistant has the issue?

2.4.0b7

### What version of the Home Assistant Integration have you got installed?

2024.12.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

MA can't see files that have uppercase letters in extensions, like "Mp3" instead of "mp3", which results in a bunch of files from my old music library missing.

### How to reproduce

Add any audio file with uppercase extension to the library (like "file.Mp3"), rescan, and try finding it.

### Music Providers

Local library/SMB

### Player Providers

Everything is affected by this problem.

### What version of Home Assistant Core are your running

2024.12.5

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Should be fixed in the next update

**Comment by OzGav** [comment]
beta 8 contains the fix for this. closing.
