### ISSUE TITLE
Error with YouTube Music Authentication

### ISSUE THREAD

**Issue by ProfessorManhattan** [music-assistant/hass-music-assistant#3336]
### What version of Music Assistant has the issue?

Latest

### What version of the Home Assistant Integration have you got installed?

2024.12.3

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When I try to connect with the cookie method, I see `ERROR: [youtube] dQw4w9WgXcQ: Requested format is not available. Use --list-formats for a list of available formats` in a front-end alert.

Only thing I see in the Log Viewer is a few unrelated warnings.

### How to reproduce

Connect with YT Music

### Music Providers

YT Music

### Player Providers

N/A

### Full log output

N/A

### Additional information

N/A

### What version of Home Assistant Core are your running

2024.12.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Don’t put latest as the MA version. Provide the actual number

**Comment by ProfessorManhattan** [comment]
Isn't it bundled in the core now?

**Comment by OzGav** [comment]
No the server will never be in core. You are referring to the integration. What you are reporting here has been fixed in server version 2.3.4 with the beta to follow soon. Hence why I asked what version you are on.

**Comment by ProfessorManhattan** [comment]
I think I'm using 2.4.0b7

**Comment by OzGav** [comment]
Ok this will be fixed for you in the next beta update
