### ISSUE TITLE
AirPlay Group Playback Fails with "No players available to form syncgroup" Error

### ISSUE THREAD

**Issue by Levtos** [music-assistant/hass-music-assistant#3338]
### What version of Music Assistant has the issue?

2.3.4

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Since updating to Music Assistant 2.3.4, I am unable to play audio on my AirPlay group, which consists of three HomePod Minis. Every attempt to play audio on the group fails with the error:
RuntimeError: No players available to form syncgroup

The group works perfectly when controlled manually via the Apple Home app. Individual playback on each HomePod via Music Assistant also works without issues.

The problem seems specific to this update, as everything worked flawlessly before.

### How to reproduce

1. Create an AirPlay group with three HomePod Minis.
2. Attempt to play audio on the group using Music Assistant.
3. Observe the error: No players available to form syncgroup.

### Music Providers

Apple Music, Soundcloud, TuneIn, Radio Browser

### Player Providers

Airplay

### Full log output

[music-assistant.log](https://github.com/user-attachments/files/18218293/music-assistant.log)

### Additional information

- The playback is initiated via the Home Assistant Music Assistant UI.
- Other AirPlay devices and individual HomePods work fine with Music Assistant.
- The issue only occurs with the group of three HomePod Minis after the update to 2.3.4.

### What version of Home Assistant Core are your running

2024.12.5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Did you really search the open issues? https://github.com/music-assistant/hass-music-assistant/issues/3221
