### ISSUE TITLE
fresh install from core: failed to connect

### ISSUE THREAD

**Issue by Morriz** [music-assistant/hass-music-assistant#3348]
### What version of Music Assistant has the issue?

no clue

### What version of the Home Assistant Integration have you got installed?

not hacs

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Just trying to install from core, after removing old installation remnants from `.storage/*`, browser storage etc, and then hard restarting...nothing works, and nothing gets installed as I don't get passed the popup to connect...

### How to reproduce

fresh install?

### Music Providers

n/a

### Player Providers

n/a

### What version of Home Assistant Core are your running

2024.12.5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
You have possibly corrupted the entries in storage by manually doing deletions. Unlikely we can help you. Suggest reinstalling Home Assistant.

**Comment by OzGav** [comment]
We will close this soon unless a problem with MA can be identified

**Comment by Morriz** [comment]
> You have possibly corrupted the entries in storage by manually doing deletions. Unlikely we can help you. Suggest reinstalling Home Assistant or restore a backup

that is a silly suggestion...you surely have identified recurring problems related to installation by now, no? Why not publish a FAQ?

**Comment by OzGav** [comment]
No actually there aren’t recurring problems with the installation. You are the first.

Yes I assumed was when you said 

> after removing old installation remnants from .storage/*

that you indeed meant manually. All other people that I have conversed with have said something like “I removed the integration” from the HA settings and from HACS.

So I unfortunately can’t help you further without more information. Listing the MA version as “no clue” and not including the full logs as requested in the troubleshooting docs and the issues template makes it impossible.

**Comment by JepNope** [comment]
I encountered the same problem when I removed and re-downloaded Music Assistant. I then restarted and the error “Connection failed” appears in the integration.

**Comment by OzGav** [comment]
@JepNope you don't seem to have the same issue as the OP as the OP is not getting the popup. If you are getting connection failed then make sure you are using the correct URL. Review then docs for where to check that

**Comment by Morriz** [comment]
nevermind, it was a memory and resource hog anyway so not practical...uninstalled
