### ISSUE TITLE
Pause not working correctly for slimproto player

### ISSUE THREAD

**Issue by de666** [music-assistant/hass-music-assistant#3349]
### What version of Music Assistant has the issue?

2.3.4

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Using slimproto player, when hitting pause, it pauses for a couple of seconds and then starts playing from the next song in the queue.

### How to reproduce

1. Start playing a couple of tracks on slimproto player
2. Pause from web UI and wait a couple of seconds without doing nothing
3. The track starts playing back again from from the next track

### Music Providers

Subsonic (Navidrome)

### Player Providers

Problem on:
Slimproto (SB player on a firetv stick)

Working correctly:
Snapcast

### Additional information

Companion app slimproto player seems to work well
sb player debug log screenshot
after pause
![screen](https://github.com/user-attachments/assets/cffbfd7b-9a39-4b0d-8e0e-6ab447768b82)

when songs restart playing
![screen2](https://github.com/user-attachments/assets/01583aac-5b8c-4dee-bcd1-fcc9e9b260ee)

### What version of Home Assistant Core are your running

2024.12.5

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Have you tried with queue flow mode on?

**Comment by de666** [comment]
> Have you tried with queue flow mode on?

With queue flow mode on it seems ok
here below the log screen
![screen](https://github.com/user-attachments/assets/13990e83-f421-4eea-a216-927f39e24afc)

**Comment by OzGav** [comment]
Then use queue flow mode. That app has many problems based on the number of reports I have seen about it.
