### ISSUE TITLE
Search Match Problem with multiple same / similar titles

### ISSUE THREAD

**Issue by bagobones** [music-assistant/hass-music-assistant#3360]
### What version of Music Assistant has the issue?

2.3.4

### What version of the Home Assistant Integration have you got installed?

2024.12.1 HACS

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

In both regular search and when trying to play tracks by using the voice intents the "TOP" match is not the best match.

For example if I search for "Hayloft" The top match is Hayloft II a different song.

If I try and use the HA Assist intents the TOP match will be used thus if I say "play track hayloft in the office", I get Hayloft II playing.

In short I would EXPECT in both an ordered text search and an exact match query that hayloft would always beat hayloft II for a query of the word hayloft?

### How to reproduce

I search for "Hayloft" The top match is Hayloft II a different song.

### Music Providers

Search for Hayloft it was the top hit

### Player Providers

The song only existed in Spotify, I have since added it to my local Plex instance and now that version is the top result. However the search results still show Spotify return Hayloft II higher than Hayloft from Spotify lower in the results set, likely because it is newer?

I should note I have this same issue with Spotify in general where it will often prefer covers or remixes based on them being recently released.

### Additional information

It seems that doing an "EXACT" search then a wild card search if that fails would resolve this issue for track names.

### What version of Home Assistant Core are your running

2024.12.5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
How have you setup the voice assistant?

**Comment by bagobones** [comment]
> How have you setup the voice assistant?

HASOS
Installed the MA official addon.
Installed the HACS integration INSTEAD of the official one as Intents do not work with the official one https://music-assistant.io/integration/voice/

I am just using intents and in this case I am just typing into the agent or using the HA app to use the HA agent.

I do not have any LLM fall back or anything enabled.

The Intents match and going into the MA interface and searchign both result in the top match being haloft II when the input is hayloft.

**Comment by OzGav** [comment]
OK re-reading your report this oes not appear to be a MA issue. MA uses the providers to return results. If MA is showing you what you see using Spotify then that is expected

**Comment by OzGav** [comment]
Sort according to what though? “Top” result will vary from person to person according to their definition. This seems like a feature request. MA is returning results according to the search criteria. You say that Spotify behaves similarly. Unless you can show the MA is not working as designed then this should be closed and you are welcome to open a feature request.

**Comment by bagobones** [comment]
> Sort according to what though? 

Basic alpha search of the aggregated provider set?

Exact match first when a single word is given?

**Comment by OzGav** [comment]
You can create a feature request here https://github.com/music-assistant/hass-music-assistant/discussions
