### ISSUE TITLE
Voice control is not working

### ISSUE THREAD

**Issue by Barsonax** [music-assistant/hass-music-assistant#3364]
### What version of Music Assistant has the issue?

2.3.4

### What version of the Home Assistant Integration have you got installed?

Using the official integration, not the HACS one

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I followed the instructions here https://music-assistant.io/integration/voice/ and added the intent files to custom_sentences/en and restarted HA but voice commands are not working.

### How to reproduce

1. Follow easiest setup for HA Assist in https://music-assistant.io/integration/voice/
2. Try to play a track using voice
3. You get 'Unexpected error during intent recognition'

### Music Providers

Doesnt even reach music assistant

### Player Providers

Doesnt even reach music assistant

### Full log output

HA log error
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/homeassistant/components/assist_pipeline/pipeline.py", line 1078, in recognize_intent
    conversation_result = await conversation.async_converse(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/homeassistant/components/conversation/agent_manager.py", line 110, in async_converse
    result = await method(conversation_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/homeassistant/components/conversation/entity.py", line 47, in internal_async_process
    return await self.async_process(user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/homeassistant/components/conversation/default_agent.py", line 368, in async_process
    return await self._async_process_intent_result(intent_result, user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/homeassistant/components/conversation/default_agent.py", line 441, in _async_process_intent_result
    intent_response = await intent.async_handle(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<10 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/homeassistant/helpers/intent.py", line 121, in async_handle
    raise UnknownIntent(f"Unknown intent {intent_type}")
homeassistant.helpers.intent.UnknownIntent: Unknown intent MassPlayMediaAssist
```

### Additional information

I also tried debugging the intent using Developer Tools -> Assist but it seems to be working there when I use this sentence `play the track twilight zone in slaapkamer`:
```
intent:
  name: MassPlayMediaAssist
slots:
  track: twilight zone
  area: slaapkamer
details:
  track:
    name: track
    value: twilight zone
    text: twilight zone
  area:
    name: area
    value: Slaapkamer
    text: slaapkamer
targets:
  light.slaapkamer:
    matched: true
  media_player.slaapkamer_speaker:
    matched: true
  light.1e_slaapkamer_lampen:
    matched: true
  sensor.1e_slaapkamer_dimmer_switch_xianzi_battery:
    matched: true
  sensor.1e_slaapkamer_dimmer_switch_xianzi_action_duration:
    matched: true
  sensor.1e_slaapkamer_dimmer_switch_rick_battery:
    matched: true
  sensor.1e_slaapkamer_dimmer_switch_rick_action_duration:
    matched: true
match: true
sentence_template: >-
  <play> <track> {track} [by <artist> {artist}] in [the ]<area>
  [((with)|(using)) {radio_mode}]
unmatched_slots: {}
source: custom
file: en/music_assistant_PlayMediaAssist.yaml
```

### What version of Home Assistant Core are your running

2024.12.5

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
Review the docs. Voice is not surrently supported in the core integration

**Comment by Barsonax** [comment]
Oh thats a surpise, since the HACS version was deprecated I thought core was the way to go. Now I read the Voice Control page again I do see this mentioned.

Is it still better to use HACS for now till Core is finished?

**Comment by OzGav** [comment]
If you need voice then yes but should be only a few days until a Blueprint is released to replace this functionality

**Comment by smirgol** [comment]
Until then you might want to try to add the `intent_script` code manually and see how it goes. According to the error, the `intent` itself seems to be available, but it's missing the script (and maybe the response part). Check this to get you started: https://community.home-assistant.io/t/ha-ma-no-voice-integration-working-throws-error/812074/17#intent-script-code-5

**Comment by e10kstarfire** [comment]
> If you need voice then yes but should be only a few days until a Blueprint is released to replace this functionality

I can't find this blueprint, does anyone have a link to it as would like to get voice control working on my new HA Voice PE?

**Comment by Barsonax** [comment]
I think the few days was a bit too optimistic with Christmas and New Year going on. Not sure when it comes but looking forward to it.

**Comment by e10kstarfire** [comment]
Yes. Seems very strange that it was all working fine via HACS then the integration moved to core and we lost this basic functionality. I wonder why it will need a blueprint to fix rather than just implementing whatever the HACS code did in core?

**Comment by Barsonax** [comment]
Idk probably a design decision, might have it's pro's and con's and iam sure the ppl building music assistant thought about it. They might not want to have to deal with maintaining it in their core code.

I do think the transition could have been smoother because now the docs say you have to use the HACS version for voice but since that repository got archived you can no longer install it. That will confuse ppl.

But they are probably just doing it in their free time so just be thankful for them making something as awesome as music assistant.

**Comment by ChaoticAlex** [comment]
I have been following the progress of these issues. The good news is that I found this blueprint in the Music Assistant code repository: https://github.com/music-assistant/blueprints/blob/main/music_assistant_blueprint.yaml. 
I have been using it for a few days, and it works well
