### ISSUE TITLE
UPnP/DLNA Players not found

### ISSUE THREAD

**Issue by joriskdzaack** [music-assistant/hass-music-assistant#3369]
### What version of Music Assistant has the issue?

2.4.0b8

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Hello! 

First of all: Thank you very much for developing MusicAssistant! I just love the system.

I'm using several Volumio (https://volumio.com/) Instances running on RaspberryPis with the UPnP feature enabled. MusicAssistant used to just discover the devices and played on them perfectly. But since I changed the client's IP address to a static one MusicAssistant doesn't seem to be able to find them anymore. I tried removing and adding the provider in MusicAssistant without luck. I also checked "Allow network scan for discovery".

My network configuration is as follows:

* Subnet Mask: 255.255.252.0
* MusicAssistant IP: 10.10.0.88 (Port 8095)
* Volumio (1) IP: 10.10.1.138
* Volumio (2) IP: 10.10.1.139

Is my network configuration supported? 

Thanks in advance!

Joris Karl Dzaack

### How to reproduce

* Change IP to a static one in a 255.255.252.0 subnet

### Music Providers

* Open Subsonic Media Server Library

### Player Providers

* UPnP/DLNA player provider used with Volumio instances.
* AirPlay player provider works without issues and can find the Volumio devices

I don't use grouped players. 

### Full log output

[music-assistant.log](https://github.com/user-attachments/files/18250727/music-assistant.log)

### What version of Home Assistant Core are your running

2025.1.0b2

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
Sorry we only provide support for flat networks. https://music-assistant.io/installation/#server-notes

I am even surprised AirPlay works but if it does that is lucky for you and you should use that
