### ISSUE TITLE
Can't play Apple Music user uploaded tracks 

### ISSUE THREAD

**Issue by Bonjei15** [music-assistant/hass-music-assistant#3378]
### What version of Music Assistant has the issue?

2.3.4

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Apple Music allows users to upload their own tracks to their library. These tracks appear along with everything else in the library and are accessible from any device, as if they're part of Apple Music's catalog. 

Music Assistant does not import these user uploaded tracks to the library. The only place I can find them is within playlists. When I select one from a playlist, it says, "No Playable Items Found". There is also not artwork for them. 

### How to reproduce

Try playing a track from Apple Music that was user uploaded. 

### Music Providers

Apple Music 

### Player Providers

Snapcast, Chromecast 

### Full log output

2024-12-28 15:04:44.099 WARNING (MainThread) [music_assistant.player_queues] Skipping apple_music://track/i.dlvVR1BtWMeoA7: track://i.dlvVR1BtWMeoA7 not found on provider apple_music
2024-12-28 15:04:44.099 ERROR (MainThread) [music_assistant.webserver] Error handling message: player_queues/play_media: No playable items found

### What version of Home Assistant Core are your running

2024.12.5

### What type of installation are you running?

Home Assistant Core

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
@MarvinSchenkel

**Comment by MarvinSchenkel** [comment]
This is by design. MA can only play uploaded music if Apple had linked it to an online version in the apple music catalog. If it cannot find that, MA won't import those tracks because it cannot play them. 

I'll see if I can filter them out of the playlist to avoid confusion. 

The recommended way to play your own music files in MA is via the file providers.
