### ISSUE TITLE
Error while starting a configured SONOS Group

### ISSUE THREAD

**Issue by hosh0815** [music-assistant/hass-music-assistant#3381]
### What version of Music Assistant has the issue?

2.3.4

### What version of the Home Assistant Integration have you got installed?

2024.12.1 ?(build in)

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

when I want to start a Song or playlist, I get the error "Song List" and the music don´t start. 

### How to reproduce

choosing a group of SONOS Speaker (not universal group) an starting a Playlist/Album/song

### Music Providers

apple music, filesystem (remote share)

### Player Providers

sonos

### Full log output

[music-assistant.log](https://github.com/user-attachments/files/18270014/music-assistant.log)

### What version of Home Assistant Core are your running

2024.12.5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Firstly, you have not provided all of the information that the troubleshooting page in the docs tells you to provide.

Secondly, your log is full of errors from all manner of problems. There are errors in local files, errors in your Apple Music files, errors with groups, errors with disconnecting players, errors with missing players and that is just the ones I could identify.

I suggest you do a minimal install and add one provider at a time and solve any problems one at a time. It is impossible at the moment to identify what is causing this when there is so much going wrong. Sorry to be the bearer of bad news.

**Comment by hosh0815** [comment]
ok, sorry for that:so here a bit background to my system: 

 I have several Vlan (IoT, privat, business) on a Unifi UDMpro and a Cisco Hardware Firwall for business (which is separated from the UDM). From business I can go into IoT and privat one way. So I´m control with my devices I use (iOS & MacOS) the MusicAssistant on the HA (IoT). The Sonos is also @ IoT. I had issues, that the playback stops, when I add to much speaker <5 to groups. So I read again the Unify and Sonos support sites. Then I decided to take out the boost from my sonos System to go back COMPLETLY to wifi and Sonos net Chanel 6. And suprise: I have no issues with bigger groups :) 
Now I thought to pregrouping in Universal or Sonos Groups, but this isn´t working. It would be nice, but for now, I´m happy with the actual situation but I wanted to report. 

So it could be, that those lot error messages are from the pro Boost(Sonos) situation. The local and Apple Music files errors, I think are always the same (wrong tags and stuff), but I don´t know, if this is reasonably for grouping speakers. 

So, for me, I keep the actual insall, because it works (without the pregrouping thing) and I keep an eye on it. Thank you !

**Comment by OzGav** [comment]
Ok note that also we don’t support MA across VLANs
