### ISSUE TITLE
Player Group expand button too close to the max volume 

### ISSUE THREAD

**Issue by milbr** [music-assistant/hass-music-assistant#3382]
### What version of Music Assistant has the issue?

2.0

### What version of the Home Assistant Integration have you got installed?

2024.12

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Max volume on player group when trying to expand player group.  This is not exactly a bug, more of a design issue. 

### How to reproduce

When using the player (group) view, the button to expand the group and see volume levels for all players in the group is right next to the max-end of the group volume control. 

This results in full volume for the group about half of the time I try to expand the player group. 

### Music Providers

Any

### Player Providers

Chromecast (or probably any) group player

### What version of Home Assistant Core are your running

2024.12

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
This is a feature request so you can bring that up in the discussions area

**Comment by OzGav** [comment]
Also you don't have to just click on that arrow to open up the player list. Try clicking towards the top on the player name
