### ISSUE TITLE
V.06b4: players remain hidden when deinstalling MA

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#339]
When I remove MA the source players remain hidden. 
![image](https://user-images.githubusercontent.com/4363599/173399355-75a4bac0-f425-4427-a94f-37358b9c3f16.png)
They can't be revived either as there is an issue in HA that entities hidden by een integration can't be enabled: https://github.com/home-assistant/frontend/issues/12887

**Comment by marcelveldt** [comment]
should be fixed in beta 6

**Comment by erkr** [comment]
I'm going to test this before installing b7
