### ISSUE TITLE
FR: Add album to the OSD

### ISSUE THREAD

**Issue by Mariusthvdb** [music-assistant/hass-music-assistant#342]
as discussed in Discord:

https://discord.com/channels/753947050995089438/753947050995089442/986191271108419584

add album here please:

<img width="1243" alt="Schermafbeelding 2022-06-14 om 10 50 30" src="https://user-images.githubusercontent.com/33354141/173542241-0d1380d8-f690-49f4-b8e8-f685d3e148d9.png">

to click and go to Album view for that album,
thanks!

**Comment by marcelveldt** [comment]
This is fixed in the 2022.7 release (currently already in beta 10)
