### ISSUE TITLE
always in Beta Version

### ISSUE THREAD

**Issue by NicoLouis-be** [music-assistant/hass-music-assistant#346]
Hi

it appears that on a fresh install you always enter the beta program.
I can't select any stable version 

![image](https://user-images.githubusercontent.com/12760841/173761860-f9b7afb9-e2d2-4118-a8b3-35594e848dce.png)

**Comment by marcelveldt** [comment]
That is correct, we are still in beta.
The first (ever) stable release is june 16th

**Comment by marcelveldt** [comment]
From the readme:

![Schermafbeelding 2022-06-15 om 08 56 33](https://user-images.githubusercontent.com/6389780/173762516-b6fbda9e-3c75-4ab7-bdbe-723bdc3f5063.png)

**Comment by NicoLouis-be** [comment]
ho my bad, i thought i had a stable version a couple of months ago

**Comment by marcelveldt** [comment]
Nope, but it wasn't really clear in the readme alone so I switched version numbering to make it more clear we're still beta.
Tomorrow will be the release of the first "official" release.

**Comment by kongjudas** [comment]
I still get beta today (17th.)
