### ISSUE TITLE
Retrieve library listings in smaller chunks

### ISSUE THREAD

**Issue by marcelveldt** [music-assistant/hass-music-assistant#347]
The library items are retrieved by the frontend when you open the panel all-at-once.
So all Artists are loaded in one batch, All Albums etc.

For people with larger collections this comes with a performance penalty:

1) There's a real large chunk of data being moved from db --> MA --> HA --> websocket --> frontend
2) It takes a while before the frontend is useable, you have to wait until the data is precached into the "store" of the frontend.
3) The HA executor is busy creating large chunks of data, I believe @bdraco has recently seen a profiler report showing this.

Solution here would be to move the item listings around as smaller chunks.
Like prefetch the first 250 items and request more if you scroll around the listings (or slowly prefetch them if you are navigating)

Not a very large job to adjust but needs to be done properly. Too much to make it into the 2022.6 release tomorrow.
This task is a reminder.

There are several issues reported directly or more indirect belonging to this issue.
- websocket can't keep up error by @erkr 
- memory consumption by @K3str3l
- load times by @Mariusthvdb

**Comment by bdraco** [comment]
Here are some call graphs of the two major performance hotspots

![from_db_row](https://user-images.githubusercontent.com/663432/173901433-c2a7cb94-ff94-4928-a244-ae90d9beb977.png)
![async_get_mass_func](https://user-images.githubusercontent.com/663432/173901447-df670726-d07a-46ec-9099-10288ccae3e9.png)

**Comment by marcelveldt** [comment]
@bdraco thanks, very helpful! Just as I suspected the load is in getting the library items all at once (e.g. tracks, albums etc).
this is also going to have a huge performance benefit of your orjson project ;-)

**Comment by bdraco** [comment]
Excellent https://github.com/home-assistant/core/pull/72847 is hopefully unblocked soon ... https://twitter.com/pvizeli/status/1537093332500979714

**Comment by erkr** [comment]
This is really working much better in beta 7 👍

**Comment by marcelveldt** [comment]
This is now implemented. Only small chunks at once are grabbed. This will save a huge performance hit and it will be even better once the orjson support hits HA core
