### ISSUE TITLE
samba nas connection

### ISSUE THREAD

**Issue by fax13** [music-assistant/hass-music-assistant#348]
hi,
the issue i have is that i can't access my nas folders.
they are connected via samba nas and i can see and play my media true the HA media folder.
i did this via shell command.
shell_command:
  mount_media_folder: mkdir -p /media/nasfiles;mount -t cifs -o vers=1.0,noserverino,user=admin,password=xxxxxxx,domain=HOME //xxx.xxx.xxx.xxx/media/Sounds /media/nasfiles
any ideas?

**Comment by erkr** [comment]
@fax13 : Welcome to MA😀

Just to be sure:
- did you configure the local media folder option in MA?
- are local files in that media folder recognized?
- is the mount situated in that local media folder?
Best
Eric

**Comment by fax13** [comment]
hi Eric,
i have added my local media file which i can see in MA but when i use the "/media/nasfiles" in MA nothing showed up.
the mounted folder is in the media folder called "nasfiles"

**Comment by erkr** [comment]
Personally I don't mount a Nas media folder. But others did successfully: https://github.com/music-assistant/hass-music-assistant/issues/71
Their approach looks very similar to what you have done. 

Maybe trivial, but the media files on your Nas contain Id3 tags (album, title, albumartist)?

**Comment by fax13** [comment]
hi,
i found the issue as the shell command was a part coded wrong
 _**-o vers=1.0,**_ should be  _**-o vers=3.0,**_
now it is loading

**Comment by erkr** [comment]
Great, thanks for the update and enjoy MA :-)

**Comment by fax13** [comment]
Yes they all are tagged as it was already done for my plex and kodi MC's

**Comment by jwister** [comment]
![image](https://user-images.githubusercontent.com/26784039/213129522-6b6876e5-e749-40b8-9cc4-6a2af1fd072d.png)
why？  code 255

**Comment by OzGav** [comment]
This isn’t a MA issue. You will probably have more success asking in a Linux forum to help you with the mount command. Having said that try it from the command line and you might get a better error message.

**Comment by jwister** [comment]
您的邮件已收到，谢谢。
