### ISSUE TITLE
volume button in phone

### ISSUE THREAD

**Issue by LukaszP2** [music-assistant/hass-music-assistant#350]
Can you add volume control from mobile app by volume button?

**Comment by erkr** [comment]
Thanks for the suggestion! If you rotate the screen it probably will be there already.
It's only missing in portrait mode on my phone

**Comment by marcelveldt** [comment]
I think he means to actually use the volume controls (the physical buttons) to control volume of the active player in MA

**Comment by LukaszP2** [comment]
> I think he means to actually use the volume controls (the physical buttons) to control volume of the active player in MA

Yes, physical buttons. It's natural I think

**Comment by erkr** [comment]
This request is a duplicate of the linked discussion #378
