### ISSUE TITLE
Spotify streaming not working for users in Denmark

### ISSUE THREAD

**Issue by leonkdk** [music-assistant/hass-music-assistant#352]
When trying to stream to my Sonos media player from y Spotify account I get the "song not encoded correctly". Playing the same track(s) directly via the Sonos app works with no issues.
Please advice - thanx in adv.

**Comment by marcelveldt** [comment]
which version of MA are you running ? I assume you try to stream it from Music Assistant ?
What Sonos speaker is this ? V2 or V1 series ?

**Comment by leonkdk** [comment]
MA running version 2022.6.0b6 (updated today). I have a rather large Sonos setup with both V1 and V2 units. The particular unit that I have used for testing is a Port (hence V2) but I am forced to use the V1 app (software) in normal Sonos operation.
For completeness I have just tried to stream to a Google Nest HUB - also having no luck in getting the stream succesfully through.

**Comment by marcelveldt** [comment]
OK, in that case I need a bit more details:

1) Please describe step by step what you did in Music Assistant 
2) What hardware is HA running on ? Also like to know the installation method such as HAOS, Container etc.

**Comment by leonkdk** [comment]
My Home Assistant instance is setup on a Raspberry Pi 4 B 8GB running on a MariaDB from a SSD drive.
Music Assistant installed through HACS.
I activated Spotify and entered my credentials (Success)
Waited til MA had retrieved all my playlists, artists etc. (Success)
Tried to activate "play" on my Sonos device (Port) (NO Success)

Have not added anything to .yaml (yet) ;-)

**Comment by leonkdk** [comment]
Nope the Spotify account is definitely too expensive ;-)

Home Assistant Core 2022.6.6
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.2
[home-assistant.log](https://github.com/music-assistant/hass-music-assistant/files/8918179/home-assistant.log)

**Comment by marcelveldt** [comment]
Thanks for the log. It's not even receiving any audio AT ALL... 
Do you have a firewall in front of HA perhaps that is a bit too strict ?
Can you please test if a radio station does work ?

**Comment by leonkdk** [comment]
Can play radio stations succesfully.
SPI Firewall for both IPv4 and IPv6 enabled on router as well as two internet filters - "Anonymous Internet requests" and "Filter Ident (port 113)". Otherwise nothing.

**Comment by marcelveldt** [comment]
OK, I believe that somehow the traffic is blocked to "librespot" the opensource spotify implementation used in Music Assistant for playback. Can you please test without the firewall just to rule that out ?

**Comment by leonkdk** [comment]
Downloaded and installed the latest update. Still no success. Attaching new logfile
[home-assistant(1).log](https://github.com/music-assistant/hass-music-assistant/files/8923318/home-assistant.1.log)
.

**Comment by marcelveldt** [comment]
Well that's a shame. I had added some additional logging but that is completely blank. Not working at all.
I'll do my best to put some more logging in there.

**Comment by marcelveldt** [comment]
I've added even more logging now in the final 2022.6.0 release, let's hope that unveils something

**Comment by leonkdk** [comment]
Fingers X-ed - here is another shot :-)
[home-assistant(2).log](https://github.com/music-assistant/hass-music-assistant/files/8924631/home-assistant.2.log)

**Comment by marcelveldt** [comment]
Hmmm, that's annoying. There's no error outputted at all.
Somehow librespot is completely failing. Question is why. Raspberry Pi is the most supported platform around, many of the MA users have the exact same setup as you.

I will chew on this a bit more and let you know. Did you perhaps already try to completely restart the HA host machine ?

**Comment by leonkdk** [comment]
Yes I have restarted the machine every time I have started the next test (as in Restart from the Dev Tools).

**Comment by marcelveldt** [comment]
Please restart the whole host because restart from dev tools only reloads the HA python code. Can you do that once for me please just to verify ?

**Comment by leonkdk** [comment]
I have done even more ... Removed Music Assistant ... Removed HACS ... reinstalled both ... physically pulled out power from RPi4 between all steps. Still no luck!

**Comment by marcelveldt** [comment]
Ok, I'm going to build a special diagnostic version later today which should help us get the cause.
I just remember something to test... Music Assistant is based on librespot as opensource Spotify client.

There actually exists a Spotify connect addon for HAOS which is also based on librespot.
This turns your HA machine into an actual spotify connect target. Not what you need perhaps but great to test if that is working, to rule out the firewall. If that does indeed work I need to have a look at the binaries included in the MA deploy.

It's this one:
https://my.home-assistant.io/redirect/supervisor_addon/?addon=a0d7b954_spotify&repository_url=https%3A%2F%2Fgithub.com%2Fhassio-addons%2Frepository

**Comment by marcelveldt** [comment]
Hmmm, I think I have found our answer...
https://github.com/librespot-org/librespot/issues/972

Are you in Denmark perhaps ?

**Comment by leonkdk** [comment]
Yes I am ;-)

**Comment by marcelveldt** [comment]
OK, great. In that case we can solve it with a workaround. There appears to be an issue with one of the Spotify servers in Denmark. I will fix this in next patch release

**Comment by Bluhme1** [comment]
Just for your information. Got the same problem. Also living in Denmark
Thank you for your great work

**Comment by marcelveldt** [comment]
I've adjusted the title for other people to spot this easily. I will provide a small patch release within an hour.

**Comment by marcelveldt** [comment]
Fix available in 2022.6.1

**Comment by leonkdk** [comment]
FANTASTIC !!! Works perfectly -... thank you for the swift reaction :-)
