### ISSUE TITLE
Search Icon is deceptive

### ISSUE THREAD

**Issue by jg8570** [music-assistant/hass-music-assistant#363]
A really minor issue, but I assumed the search icon would do something like add metadata to my tracks because of the globe mesh inside the circle of the icon. I think it should be updated to a plain one like this: 
![image](https://user-images.githubusercontent.com/66077595/174160098-a5b1210b-6632-42b3-a902-6c0051809e1c.png)

**Comment by marcelveldt** [comment]
You're right. I didn't notice that. It is actually the wrong icon indeed.

**Comment by marcelveldt** [comment]
fix released in 2022.6.5. Thanks!
