### ISSUE TITLE
Error when calling tts.cloud_say the second time

### ISSUE THREAD

**Issue by Jhonattan-Souza** [music-assistant/hass-music-assistant#364]
When I call service in the second time, this error below appears

![image](https://user-images.githubusercontent.com/19364782/174169558-fb85e2db-37eb-4ea9-a946-4ae3cdded784.png)

**Comment by marcelveldt** [comment]
Correct, you need to wait until the alert has finished. It's a failsafe.
The queue should be auto resumed once the TTS is done

**Comment by Jhonattan-Souza** [comment]
Hi @marcelveldt 
it's happening every time, even after the song has already started playing again, every time i call tts the same error occurs, it just works again by restarting the HA, but after the first time I call it, it stops again

![image](https://user-images.githubusercontent.com/19364782/174194548-657e4366-186a-4604-90d8-7391b44ebcb7.png)

**Comment by erkr** [comment]
@marcelveldt 
I have seen the same error in beta 7, when I verified issue https://github.com/music-assistant/hass-music-assistant/issues/315

**Comment by marcelveldt** [comment]
Does the issue still exist with the new stable version because i fixed a bug with Google Cast

**Comment by erkr** [comment]
Still need to verify that later today

**Comment by marcelveldt** [comment]
Please reopen if the issue is not yet fixed.
