### ISSUE TITLE
When something is playing and was called by voice, tts gets lost and doesn't play the song again

### ISSUE THREAD

**Issue by Jhonattan-Souza** [music-assistant/hass-music-assistant#365]
Replay:

Ask google to play some music in spotify by voice
Call tts service to announce
Wait the resume
The music playing is different or it just doesn't play at all

**Comment by marcelveldt** [comment]
Correct, when you play music by voice, Music Assistant is completely bypassed and has no clue how to resume the music again. It would however be very nice if we could fix that somehow and make voice commands compatible with Music Assistant :-)

**Comment by Jhonattan-Souza** [comment]
Thanks! I'll close the issue for now then

**Comment by lepras** [comment]
I was looking for a voice controlled music - smart speaker solution. So this is not possible with home assistant then? Probably should look into mycroft?
