### ISSUE TITLE
Feature Request: Raumfeld / Teufel

### ISSUE THREAD

**Issue by feutl** [music-assistant/hass-music-assistant#371]
Would it be possible to integrate Raumfeld / Teufel Support?
There is a project already trying to accomplish this, but it does not feel usable for the a broader audience.

Would be great to see a joint venture to get this integrated.

https://github.com/B5r1oJ0A9G/teufel_raumfeld

**Comment by marcelveldt** [comment]
If you add that integration to HA, it will produce players that can be used with Music Assistant.
Looking at the code of the linked integration in theory it should work out of the box.

**Comment by erkr** [comment]
We are still in an explorative test phase with this new integration. Just play with it and let us know when things don't work for you. 
Enjoy Eric
