### ISSUE TITLE
Qubuz music not working

### ISSUE THREAD

**Issue by toby-griffiths** [music-assistant/hass-music-assistant#372]
I've just signed up for the trial of Qobuz as I'm excited to get Music Assistant working, but my library is not being pulled through.  The Artists/Albums/Tracks in Music Assistant are all greyed out, despite having favourited an artist, albums.& tracks in Qobuz.

I've also tried reloading the Music Assistant integration several times since adding the tracks. I've also tried restarting Home Assistant too, but no joy.

I also have a playlist that has appeared that is not showing on my Qobuz account (looks like a 'welcome' playlist).

**Comment by marcelveldt** [comment]
OK, I'm a Qobuz subscriber myself too and it should work fabulous.
Can you send a screenshot of what is greyed out ? Any errors in de home assistant log perhaps ?

**Comment by marcelveldt** [comment]
Found the issue... The cache expiration is set at a too high number...
Fix available in 2022.6.1

**Comment by toby-griffiths** [comment]
Increadibly speedy response there.  I'm amazed.

And I'm happy to say that this one is now fixed!  Thanks you so much! 🙏🏼
