### ISSUE TITLE
latest version 2022.6.0 issue with account Spotify 

### ISSUE THREAD

**Issue by MiAutomations** [music-assistant/hass-music-assistant#374]
Hello 

I'm trying to logon with me account in the Spotify but I always receiving this msg 

![image](https://user-images.githubusercontent.com/47602733/174266692-f7883cc8-2457-4267-907c-4a6b45f94c7b.png)

I alreday try Reset account password several times reload the integrations change the password and the problem persists ... 

I'm abble to perform the logon on the other platforms webbrowser spotify page and windows APP and andoird APP also with the same credentials 

Please let me know if you need further information from my side 

Thank you in advance for your help and support

**Comment by marcelveldt** [comment]
Usually when this error is displayed it it correct and the login indeed failed ;-)

I had one other report from someone that needed to input the emailaddress instead of username.
Can you test that. If it all keeps failing, please share some details about your setup like instalation method, architecture etc

**Comment by MiAutomations** [comment]
> Usually when this error is displayed it it correct and the login indeed failed ;-)
> 
> I had one other report from someone that needed to input the emailaddress instead of username. Can you test that. If it all keeps failing, please share some details about your setup like instalation method, architecture etc

Thank you for your reply, I'm using the email address and now I tryed without email address and only the user and the problem persists ... 

I'm using a NUC running proxmox and the HA version is Home Assistant Core 2022.6.6
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.2

Thank you

**Comment by marcelveldt** [comment]
OK, that should work out of the box.
[Are you located in Denmark perhaps ?](https://github.com/music-assistant/hass-music-assistant/issues/352)

**Comment by MiAutomations** [comment]
> OK, that should work out of the box. [Are you located in Denmark perhaps ?](https://github.com/music-assistant/hass-music-assistant/issues/352)

No, I'm from Portugal

**Comment by marcelveldt** [comment]
OK, so that is not related. Can you check your logfile and share the related error here ?

**Comment by marcelveldt** [comment]
Just to confirm: You do have a Spotify Premium account right? Spotify free/basic is not supported

**Comment by MiAutomations** [comment]
> Just to confirm: You do have a Spotify Premium account right? Spotify free/basic is not supported

Ok Sorry, yes it is a Free account Thankyou and sorry again
