### ISSUE TITLE
[Bug] Cannot add tracks to a new playlist

### ISSUE THREAD

**Issue by rcjkierkels** [music-assistant/hass-music-assistant#394]
**Version**
Music Assistant 2022.6.1
Home Assistant Core 2022.6.6
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.2

**Description**
I have no playlists yet. When I try to add an item to the playlist from the tracks list I see an error in the console and nothing happends.

```
mass.iife.js:14 TypeError: K.getLibraryPlaylists is not a function
    at Proxy.s (mass.iife.js:117:17384)
    at onClick (mass.iife.js:117:19450)
    at mass.iife.js:14:44684
    at Jn (mass.iife.js:14:656)
    at gn (mass.iife.js:14:735)
    at gn (mass.iife.js:14:835)
```

**Expected behaviour**
I would expect that a new playlist will be created and the track is added to that new playlist

**How to reproduce**
![image](https://user-images.githubusercontent.com/3001864/174389523-57329cd7-dc69-41dc-966e-0f95719032e0.png)
After selecting an track from the list I click the three dots and choose 'Add to playlist...'. Then I see the error in the console and nothing happends.

**Comment by erkr** [comment]
Thanks for filing this issue.

**Comment by marcelveldt** [comment]
True, I keep forgetting to implement that. A simple "create playlist" is not yet implemented, only editing existing ones.
Very simple solution for now is to create an empty playlist (on disk as m3u or at your streaming provider).

**Comment by marcelveldt** [comment]
Please add your vote to the feature request to remind to fix this ;-)
https://github.com/music-assistant/hass-music-assistant/discussions/398?converting=1
