### ISSUE TITLE
Helper group mix Sonos/ nest mini/audio problem

### ISSUE THREAD

**Issue by WHagenauw** [music-assistant/hass-music-assistant#395]
I created a helper group with a mix from Sonos and nest mini/audio (as 2 in stereo) but in Music Assistant only the Sonos are showing in the group. Tried it several times with new groups and sometimes it works and sometimes don't.

**Comment by erkr** [comment]
Sorry to hear is it's not working as expected. For the developer it's useful to provide some setup information:

Versions:
Music Assistant 2022.6....
Home Assistant Core 2022.6...
Home Assistant Supervisor 2022.05...
Home Assistant OS 8...

Additional question: are these media players working properly individually?

**Comment by WHagenauw** [comment]
Music Assistant 2022.6.1
Home Assistant Core 2022.6.6
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.2

And yes, they work individually good. I tried to add a stereo paired nest mini and a stereo paired nest audio together with 2 sets of sonos ones. The sonos ones are showing but not the nest

**Comment by marcelveldt** [comment]
I must confess that I did not test a speaker pair being added to MA, let alone within a group. I will perform some tests tomorrow with a similar setup.

**Comment by WHagenauw** [comment]
Don't know if you tested it and made some changes for this in the latest updates (just updated to the latest release) but just tested it myself again (needed tot delete and add a nest audio pair to the helper group) and now seems to work. Only next problem is the volume. 
The Sonos volume just goes along with the overal volume but the Nest mini/audio volume starts at 0 (while it's setting is 40%). I can change the volume from the nest but the overal volume does not change. When I change after that the overall volume, the Nest stops playing. I need to change the volume from the Nest and it plays again......

**Comment by marcelveldt** [comment]
I did not yet have time to test this or make any changes. I hope to find some time to do that tomorrow. Was the nest "powered" when you tried to adjust the volume. Note that group volume only changes the volume of "powered" client players

**Comment by marcelveldt** [comment]
I (finally) managed to reproduce this issue and found out that I forgot to implement a few things for the grouped speakers. Sonos speakers behave completely different than Cast speakers in this regards. I've adjusted the code to support both grouping "variants" and I'm currently testing this change on my test setup. I'll release the patch later today.

**Comment by WHagenauw** [comment]
Great to hear that it is not something on my site. Will try it out when the
update is released. Thanks!

Op ma 27 jun. 2022 10:29 schreef Marcel van der Veldt <
***@***.***>:

**Comment by marcelveldt** [comment]
should be fixed in 2022.6.7, if not please reopen, thanks!

**Comment by WHagenauw** [comment]
Yes they all where powered. Hope to hear soon about it.

Op ma 20 jun. 2022 23:01 schreef Marcel van der Veldt <
***@***.***>:

**Comment by WHagenauw** [comment]
Hello,

The mediaplayers from the helper group are all visible in music assistant.
They all start playing (the sonos grouped and Nest grouped) but as soon as
the music starts the NEST players dissapear in the player overview from the
music assistant. They can also not be stopped or change the volume. If I
stop the group, only the sonos will stop but not the nest players.......

Kind regards,

Wim


Op wo 29 jun. 2022 om 01:16 schreef Marcel van der Veldt <
***@***.***>:
