### ISSUE TITLE
Failed to Set up, Check the logs - But still works

### ISSUE THREAD

**Issue by connor-dobbins** [music-assistant/hass-music-assistant#399]
From the integrations page I get a message saying that Music Assistant Failed to setup and to check the logs. I then tried to play media through Music Assistant and everything worked as expected.  I am running 2022.6.1 The logs showed this error message:

Logger: homeassistant.config_entries
Source: custom_components/mass/__init__.py:167
Integration: Music Assistant ([documentation](https://github.com/music-assistant/hass-music-assistant), [issues](https://github.com/music-assistant/hass-music-assistant/issues))
First occurred: 4:28:07 PM (1 occurrences)
Last logged: 4:28:07 PM

Error setting up entry Music Assistant for mass
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 339, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/mass/__init__.py", line 167, in async_setup_entry
    if player_id not in entry.options[CONF_PLAYER_ENTITIES]:
KeyError: 'player_entities'

**Comment by marcelveldt** [comment]
I think you ran into a so called "race condition" and you will not see this error again but that you reported it so I can fix it. Thanks!

**Comment by marcelveldt** [comment]
fixed in 2022.6.2
