### ISSUE TITLE
2022.6.1 - Denon DLNA player not visible within MA without first playing via Media player

### ISSUE THREAD

**Issue by vk2him** [music-assistant/hass-music-assistant#400]
Per the Discord comments, I've discovered that the Denon DLNA player will not be visible within MA after Home Assistant is restarted without first streaming music to it via the built-in Media Browser player. After a Home Assistant restart, the Denon DLNA player is available to select within the MA integration configuration window, however the Denon DLNA player will never appear until music is first played via the media browser. MA will then be able to see it until the next restart of Home Assistant as it doesn't survive the restart. Clearing cache makes no difference - as soon as music starts streaming via media player the Denon DLNA player immediately becomes visible in MA. No errors are in logs. 

I realise this is probably not a MA issue, Denon may not be fully following complying with the "Standard".

Thanks

Screenshot of DLNA entity in MA configuration:

![Screen Shot 311](https://user-images.githubusercontent.com/22878629/174414410-2ea6a63b-3674-4362-a9f3-6ac45d2cdb5f.jpg)
Missing DLNA player in MA:

![Screen Shot 309](https://user-images.githubusercontent.com/22878629/174414459-811ad401-9f58-4d2d-9f75-a8cd7d7ec37a.jpg)

After streaming via Media Browser:

![Screen Shot 329](https://user-images.githubusercontent.com/22878629/174414536-27fb2e87-1e30-4b03-92ab-0b756693d815.jpg)

**Comment by marcelveldt** [comment]
Can you please have a look at the state of the "real" media_player when it is NOT visible in MA. So in the developers menu from HA lokup the original media_player entity for the Denon and note it's state.

**Comment by vk2him** [comment]
6.2 didn't fix this Marcel - here's a screenshot of the two denon media_players. Note the 4000 thinks it's having music played to it when in reality it isn't - the 4000 Denon's  front panel says it's connected to my NAS DLNA server. I believe if a new stream is sent to it, it will play that stream.
The 4200 is powered off. Neither appear in MA.

![Screen Shot 332](https://user-images.githubusercontent.com/22878629/174459203-f007d293-e771-41a1-a18a-0a78f4aa08b4.jpg)

 If I stream music to them via the in-built media player, they don't appear in MA however as soon as i power them off they will immediately  appear in MA - the following screenshots are directly after powering off and they are then showing in MA - for clarity even though they are off, I can play music to them via MA if they are off as they will Automatically turn on and start playing.

![Screen Shot 333](https://user-images.githubusercontent.com/22878629/174459366-f91e4257-f552-4f3a-8695-0a725efa749f.jpg)

![Screen Shot 334](https://user-images.githubusercontent.com/22878629/174459434-752bc209-d80a-4270-9db9-5c6d3328ab48.jpg)

**Comment by manu3b1** [comment]
Same issue here.
media_player.mass_marantz_dlna unavailable but media_player.marantz_dlna is Idle or Playing.
<img width="1704" alt="boot-up" src="https://user-images.githubusercontent.com/46264838/174481024-862dd05f-4e88-44ea-964f-f195e902cc84.png">
<img width="1708" alt="Paying" src="https://user-images.githubusercontent.com/46264838/174481029-808c5877-0f30-4a3d-8c8b-e1ccac05b2be.png">

**Comment by vk2him** [comment]
> Same issue here with 2022.6.2. media_player.mass_marantz_dlna unavailable but media_player.marantz_dlna is Idle or Playing.>

I believe Marantz and Denon are virtually identical from a software perspective so it makes sense you're also having issues - lets hope Marcel can weave his magic !

**Comment by manu3b1** [comment]
Right.
@marcelveldt, will you reopen this ticket or clone it?

**Comment by vk2him** [comment]
He said earlier today that he would look at it again - he's probably busy with family today I guess :)

**Comment by manu3b1** [comment]
With this week big event, he will be on fire for 1 month, or more ;-)

**Comment by vk2him** [comment]
Version 6.3 released today has fixed this Denon issue - the Denon's appear in the MA Player list and if I stream to them the Denon will autopower on and select the correct Media Server source! Bravo, thanks for that.
There is however a new issue that's been introduced - the Pause button no longer works in the MA interface nor in the mass music player.  The skip forward/reverse work though.
