### ISSUE TITLE
v2022.6.2: dangling background task when cleaning queue

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#422]
When I play a radio station and then clean the queue, a dangling background tasks start spinning.
This repeats adding dangling tasks. Example after two times:
![image](https://user-images.githubusercontent.com/4363599/174440369-b4c5af20-3b8d-4d1c-a98b-5ffe9aac700f.png)

After several minutes they disappear, no errors logged

**Comment by marcelveldt** [comment]
This is perfectly fine. Where's the issue ?

**Comment by erkr** [comment]
Expected this as unintended, as it didn't take 3-5 minutes before?! Was a matter of seconds.

**Comment by marcelveldt** [comment]
This is by design. Once playback finishes of an item in the queue and there is not yet any analyse data available, the analyze job will be executed. It is strange if the analyze job is executed for items that are already analyzed before. the analyze job is used to determine the EBU-r128 loudness.

**Comment by erkr** [comment]
I will close this issue. Thanks for explaining
