### ISSUE TITLE
Front-end not loading after refresh (F5)

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#425]
I just pressed F5 to refresh my browser while I was reviewing the content a MA player queue. 
After that the web page of MA could be loaded anymore. had to clear the cache to get back in business:
![image](https://user-images.githubusercontent.com/4363599/174443023-543666a1-d6b3-43bb-b7ea-5fe192b25980.png)

Happened in Google Chrome, Version 102.0.5005.115 (Official Build) (64-bit) running on Windows 11

**Comment by marcelveldt** [comment]
OK, that is a result of forced loading the images over HTTPS... Look at the error in your console. Chrome is blocking requests  because you're accessing content from a non secure setup. I'll revert that HTTPS images thingie and think a bit more about it.

**Comment by erkr** [comment]
Pfff, glad there errors make sense to you😀

**Comment by marcelveldt** [comment]
should be fixed in 2022.6.3
