### ISSUE TITLE
Random order of track when adding album to que

### ISSUE THREAD

**Issue by SlowmoDK** [music-assistant/hass-music-assistant#440]
When i  try to play any album from local source the order is random not real order of album 

this happends no matter what the shuffle setting is on
 

![real order](https://user-images.githubusercontent.com/38811763/174453261-c3ff380f-95ed-4035-8d54-2b1dca17857c.png)
![que](https://user-images.githubusercontent.com/38811763/174453319-968fdf05-0635-4c2a-a5cd-b23edc7f1985.png)

**Comment by marcelveldt** [comment]
Oops that is a sloppy mistake nobody noticed before. It only happens on playback of an album from disk.
I'll fix it in one of the next patch releases. Thanks for reporting!

**Comment by SlowmoDK** [comment]
thanks for quick reply ... since i only use local (until deezer support) 

Being able to play in correct order makes or breaks MA for me 

I can't wait to play more when fixed

**Comment by marcelveldt** [comment]
fixed in 2022.6.3 - if you still experience any issues, please reopen this issue or create a new one, thanks!
