### ISSUE TITLE
Feature request: playback on mobile phone using companion app

### ISSUE THREAD

**Issue by jeroenterheerdt** [music-assistant/hass-music-assistant#445]
Would love to get the ability for the HA companion app to present itself as a 'media player' so I can use MA on my mobile phone to play music through bluetooth in my car for example. Right now, I use the Plex app for this purpose, but if I can get rid of the extra app and do everything through the HA companion app that would be awesome.

**Comment by erkr** [comment]
Thanks for the suggestions. Plates have a look at these two discussions:
- https://github.com/music-assistant/hass-music-assistant/discussions/396
- https://github.com/music-assistant/hass-music-assistant/discussions/384
Please continue there. I close this one as duplicate.
