### ISSUE TITLE
Login to Spotify with Facebook account.

### ISSUE THREAD

**Issue by Trigun** [music-assistant/hass-music-assistant#447]
How to login to Spotify with your Facebook account
There doesn't seem t be a possibility.

Btw great job on this!

**Comment by marcelveldt** [comment]
You're right, login of Spotify with a Facebook account is not possible (yet). If you want you can create a [feature request](https://github.com/music-assistant/hass-music-assistant/discussions/categories/feature-requests-and-ideas) for that.

**Comment by Trigun** [comment]
> You're right, login of Spotify with a Facebook account is not possible (yet). If you want you can create a [feature request](https://github.com/music-assistant/hass-music-assistant/discussions/categories/feature-requests-and-ideas) for that.

Thanks Marcel! Will do

**Comment by erkr** [comment]
Added to the discussions
