### ISSUE TITLE
deselecting filesystem provider throws unexpected warning

### ISSUE THREAD

**Issue by Mariusthvdb** [music-assistant/hass-music-assistant#458]
<img width="422" alt="Schermafbeelding 2022-06-18 om 11 28 58" src="https://user-images.githubusercontent.com/33354141/174496354-cd76e91c-d089-4dae-a538-a255b98fc27b.png">

image says it all. When deselecting, one would expect the Folder/directory to be ignored at least, or maybe even cleared.

In any case the error should not be raised and prevent the options from being saved.

and btw, the directory did exist, and was accessible ..

**Comment by marcelveldt** [comment]
I checked the code als although the error check may not be performed when the checkbox is off the only way to trigger the error is when the location does not exist...

**Comment by marcelveldt** [comment]
fixed in 2022.6.3, please reopen if you still experience any issues, thanks!
