### ISSUE TITLE
File system provider broken in 2022.6.3

### ISSUE THREAD

**Issue by asjmcguire** [music-assistant/hass-music-assistant#461]
Assuming it has something to do with commit 8fcfb7abce15a817bcb56a22cc61a383cfdc24e2
Prior to 2022.6.3 the file system provider was working fine for me, and even 2022.6.3 was working for me, UNTIL I went in to config flow to add a new speaker.
Now no matter what path I put in the file system provider box, upon saving - Music Assistant cannot be set up because the directory apparently doesn't exist - and re-entering the config flow shows the value is now blank.

I have verified countless times by running ```docker exec -it homeassistant "/bin/sh"``` on my proxmox and then running ```ls /mnt/music/music``` that the directory exists and is readable by the home assistant user.

I'm suspicious that Music Assistant is attempting to verify the existence of ""

EDIT:
I don't know what is going on, reverting to 2022.6.2 didn't fix the problem either. I have restarted Home Assistant about 12 times and tried all sorts to get Music Assistant to accept the file system path. In the end I have edited the value directly in ```core.config_entries``` (it did indeed have a path of "") and restarted Home Assistant and Music Assistant is quite happy and reading the music files again.

**Comment by marcelveldt** [comment]
Something strange going on indeed. The check if the directory exists on disk always returns false...
I'll have a look and provide a patch. Thanks for reporting!

**Comment by marcelveldt** [comment]
fixed in 2022.6.4!
