### ISSUE TITLE
HA Startup Timing (?) Issue and Mounted Media

### ISSUE THREAD

**Issue by RJ-Make** [music-assistant/hass-music-assistant#480]
### What version of Music Assistant has the issue?

2022.6.4

### The problem

When starting/restarting HA, the MA Integration does not find the media located on a mounted network drive (using Shell Command in a startup Automation)

If I reload the integration, it finds the media, hence I believe this is a timing issue?

I don't think I saw this behavior in the original (2022.6) build, but is taking place with 2022.6.3 and 2022.6.4) 

### How to reproduce

Restart HA

### What version of Home Assistant Core are your running

2022.6.6

### What type of installation are you running?

Home Assistant OS

**Comment by marcelveldt** [comment]
This is a timing issue indeed but I did not change anything in this regard. MA is already setup to load last on the list when everything else has finished. Maybe your mount command is just a bit slow to respond ?

**Comment by RJ-Make** [comment]
Thank you,

Not sure how to speed up the mount. Hmmm. 

Also, shouldn't MA make another attempt to scan/load the media after 3 hours? (This doesn't seem to be taking place if the startup scan fails)

Is there anyway to delay the first scan after startup?

**Comment by marcelveldt** [comment]
It does retry the setup if it fails. In your case it doesn't fail, the files simply aren't there.
So if the whole directory can't be found, it will fail at startup and that will be auto retried a few times by HA by default.

Idea: Mount your NAS in "/media/nas" - have the actual music in /media/nas/music" and add that folder to MA.
If at startup the mount is a bit slower than MA startup, the "/media/nas/music" does not yet exists which will fail the MA startup which in turn is auto retried after a few minutes

**Comment by marcelveldt** [comment]
Ofc: This all is just temporary. The real solution will be when MA can access the network filed itself.
