### ISSUE TITLE
Setup failed of provider spotify

### ISSUE THREAD

**Issue by Axydas** [music-assistant/hass-music-assistant#490]
### What version of Music Assistant has the issue?

2022.6.4

### The problem

When i try to setup Music Assistant i get the error:
Retrying setup: Setup failed of provider spotify: Login failed for user xxxx

### How to reproduce

I setup Music Assistant in my NUC and i connect my Spotify Account. User name and Password are correct

### Relevant log output

Logger: music_assistant.music.spotify
Source: /usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/providers/spotify.py:542
First occurred: June 14, 2022, 16:41:06 (28955 occurrences)
Last logged: 10:44:48

Error while retrieving Spotify token, details: b''

-----------------

Logger: music_assistant.music.spotify
Source: /usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/providers/spotify.py:486
First occurred: June 14, 2022, 16:41:18 (7184 occurrences)
Last logged: 10:44:50

Login failed for user 11133718793

### What version of Home Assistant Core are your running

2022.6.2

### What type of installation are you running?

Home Assistant Supervised

**Comment by marcelveldt** [comment]
Well, as the message clearly says: It can't login to your account due to wrong credentials.
If you use Facebook to log in to Spotify you need to create a device password.

Please have another good look at the credentials. Maybe open the browser and try to log in to Spotify with those exact same credentials.

Somewhere in the future we're going to support another way of logging into spotify (by using the Spotify app) but until then you will have to insert the (correct) username and password.

**Comment by Axydas** [comment]
Yes i did this twice and i am using the same credetials for the Spotify integration. I also try to connect with both username and email. Same result

**Comment by marcelveldt** [comment]
Strange! It should really work. Maybe some special characters in there which we can't handle.

**Comment by Axydas** [comment]
i am using '/' at the end of the password

**Comment by marcelveldt** [comment]
Make sure you do not have any quotes or slashes in the password just in case.

**Comment by Axydas** [comment]
i change the password without any special character, i connected to spotify.com normally, i reconnected my alexa skill with the new password successfully but music assistant is still getting error.

**Comment by Axydas** [comment]
Home Assistant Core 2022.6.2
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.2

Running on a NUC intel platform without any Firewall

**Comment by marcelveldt** [comment]
Stupid question maybe but you are running a Spotify premium account right ?
Free accounts are not supported

**Comment by Axydas** [comment]
oh that is the issue then. I using my free account. yes. i will change my user to the premium one.
