### ISSUE TITLE
Single track missing from library (maybe more)

### ISSUE THREAD

**Issue by antonyslater** [music-assistant/hass-music-assistant#492]
### What version of Music Assistant has the issue?

2022.6.4

### The problem

I have a track that appears to be missing form my library, I know I have a lot of tracks (10125), but it was present a little while ago as I was listening to it and I can't rule out having accidentally clicked on "remove from library".

My question is... Can I "force a rescan" to reinstate it (missing tracks) or would it require a deletion of the MASS DB file to then rescan everything again?

### How to reproduce

If I search for the album it does not appear as a listed track there, if I search the tracks for the individual track it does not appear in the found list either.  This is what makes me think I may have accidently removed it from my library something which if I have done by accident seems a little easy to do??

### Relevant log output

No log output for this issue.

### What version of Home Assistant Core are your running

2022.6.6

### What type of installation are you running?

Home Assistant Container

**Comment by antonyslater** [comment]
Wow @marcelveldt, as ever blown away by your responsiveness...  Happy to wait and like I say I can't rule out "user error" this end for the reason behind this track "going missing".

Loving the work by the way, I use it every day as my interface for playing music while I work! :-)

**Comment by marcelveldt** [comment]
I am going to close this as issue. It will be fixed in the next major release (2022.7.x) when the global search is introduced.
