### ISSUE TITLE
Import of files with a quote in the filename does not work

### ISSUE THREAD

**Issue by RienduPre** [music-assistant/hass-music-assistant#493]
### What version of Music Assistant has the issue?

2022.6.4

### The problem

When syncing files the process errors out, when the filename has a quote in it and stops

See error below:

### How to reproduce

import a file with a quote in te filename

### Relevant log output

Logger: music_assistant
Source: /usr/local/lib/python3.9/site-packages/music_assistant/mass.py:244
First occurred: 05:01:51 (8 occurrences)
Last logged: 13:00:58

Job [Library sync for provider Filesystem] failed with error [Errno 2] No such file or directory: '/media/nas01muziek/Dossier Radio 10 Top 4000/3087 - Manfred Mann?s Earth Band - Spirits In The Night.mp3'.
Job [Library sync for provider Filesystem] failed with error [Errno 2] No such file or directory: '/media/nas01muziek/Dossier Radio 10 Top 4000/0800 - Paul De Leeuw - ?k Heb Je Lief.mp3'.
Job [Library sync for provider Filesystem] failed with error [Errno 2] No such file or directory: '/media/nas01muziek/Dossier Radio 10 Top 4000/0511 - Manfred Mann?s Earth Band - Blinded By The Light.mp3'.
Job [Library sync for provider Filesystem] failed with error [Errno 2] No such file or directory: '/media/nas01muziek/Dossier Radio 10 Top 4000/0606 - Diana Ross - I?m Coming Out.mp3'.
Job [Library sync for provider Filesystem] failed with error [Errno 2] No such file or directory: '/media/nas01muziek/Dossier Radio 10 Top 4000/3433 - Destiny?s Child - Emotion.mp3'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/music_providers/filesystem.py", line 158, in sync_library
    stat = await asyncio.get_running_loop().run_in_executor(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/media/nas01muziek/Dossier Radio 10 Top 4000/1878 - Destiny?s Child - No No No.mp3'

### What version of Home Assistant Core are your running

2022.6.6

### What type of installation are you running?

Home Assistant Supervised

**Comment by erkr** [comment]
We tested on two systems, and both just import them fine. So marcels suggestion that it can be related to the NAS share is the most likely. I close the issue for now. Thanks for Filing!
