### ISSUE TITLE
add tracks to queue

### ISSUE THREAD

**Issue by NickyMB** [music-assistant/hass-music-assistant#498]
### What version of Music Assistant has the issue?

2022.6.4

### The problem

When I check several songs from locale library i cant add them to queue in the same time

### How to reproduce

Have some tracks in library
check them
try add them to queue

### What version of Home Assistant Core are your running

2022.6.4

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Linux

**Comment by erkr** [comment]
Please have a look a at issue: https://github.com/music-assistant/hass-music-assistant/issues/3 2 and indicate if that is the same issue.
If so the work surround is to add the tracks while the queue is playing.

**Comment by marcelveldt** [comment]
I think this is a different issue. If I understand correctly @NickyMB is selecting multiple tracks and then tries to add the selected tracks to the queue. I'll try to reproduce

**Comment by NickyMB** [comment]
Yes but when i want to add them all in one time it doesnt. Maybe im doing something wrong. I press ctrl a and then press "x selected items" and nothing happens

**Comment by marcelveldt** [comment]
Ah all at once.. I did not test that one. Only the manual selection of multiple items

**Comment by marcelveldt** [comment]
Oops, it is not designed to do that. I'll see if I can simply patch this now or else limit it

**Comment by marcelveldt** [comment]
Fix will be available in the next patch release (2022.6.5). Please reopen if you still experience issues with that version. Thanks!
