### ISSUE TITLE
Bose Sound Touch Working

### ISSUE THREAD

**Issue by juan11perez** [music-assistant/hass-music-assistant#503]
### What version of Music Assistant has the issue?

2022.6.4

### The problem

Bose soundtouch works when playing tracks from media_browser > local_media

However, playing tracks from within Music Assistant (in media browser) fails

### How to reproduce

Normal setup per instructions, attempt playing track from media_browser > music_assistant > tracks

### What version of Home Assistant Core are your running

2022.6.7

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

**Comment by Trigun** [comment]
Since you are working from a container it is using a different IP range (your docker range) I believe there is already an issue noted to have this solved. @erkr probably knows this best?

**Comment by marcelveldt** [comment]
1) What happens if you try to start the playback from the Music Assistant panel ?
2) Can you please share any relevant errors in the log ?
3) Do you perhaps have another device to playback or only Bose ?

**Comment by marcelveldt** [comment]
That error is not useable as it is only a result of the failing playback. Please look in your Home assistant logfile for errors please. Especially look for an error stating that no player connected within 10 seconds. If that error is there, the player did not connect at all and we are dealing with an IP resolve issue.

**Comment by juan11perez** [comment]
Ok, so apologies for wasting your time. I set up debugging and restarted the container. 

This time around MASS appeared on the left panel (under Home Assistant) with its own icon. This takes you into a page only for MASS and from there it works. Tracks, play without problem on the Bose speakers.

If I go via the Media Brower pannel and the select MASS, the problem persists. The file starts, but it's immediately cut off.

I set up debugging as such:

`mass: debug`

But I see no error in the log.

**Comment by marcelveldt** [comment]
No need to set logging to debug, that will give you A LOT of logging :-)

OK, thanks for the additional info. Good to know that it does work from the Music Assistant panel.
I'll take a look if I can reproduce the issue with the builtin panel.

**Comment by marcelveldt** [comment]
I reproduced the issue and managed to fix it. 
Fix will be in the next patch release (2022.6.6)

**Comment by juan11perez** [comment]
Thank you for your prompt response and thank you for this component.
Whilst there's been a bose integration in HA for a while, the reality is that playing anything via HA was cumbersome at best.
This component just works!
