### ISSUE TITLE
not loading all files

### ISSUE THREAD

**Issue by jeroenterheerdt** [music-assistant/hass-music-assistant#509]
### What version of Music Assistant has the issue?

2022.6.5

### The problem

Previously on 2022.6.3 my full library was loaded (I am using a mounted network drive). Now only part of my library is loaded. I see nothing in the logs that jumps out to me. How can I troubleshoot this? How do I collect debug logs for music assistant?

### How to reproduce

not sure - need more troubleshooting logs.

### What version of Home Assistant Core are your running

2022.6.0

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by jeroenterheerdt** [comment]
Files that are loaded are all shown as Unavailable and do not play

**Comment by marcelveldt** [comment]
Well, maybe obvious but did you check that the mount was there before MA loaded ?
What happens if you reload the MA integration ?

**Comment by jeroenterheerdt** [comment]
yes, directory is mounted. reloading results in the same.

**Comment by jeroenterheerdt** [comment]
weirdly enough it works after a reboot ...

**Comment by marcelveldt** [comment]
OK this will be more stable as soon as I finish the native smb connection so the mount workarounds are no longer needed.
