### ISSUE TITLE
Sort on artist name in album list doesn't work

### ISSUE THREAD

**Issue by jdesmedt** [music-assistant/hass-music-assistant#511]
### What version of Music Assistant has the issue?

2022.6.5

### The problem

Can't sort albums on artist name. Other sorting options work, but when sorting on artist name, the list remains empty.

### How to reproduce

Go to the album list (I only have spotify source), try to sort on Artist name, list is empty.

### What version of Home Assistant Core are your running

2022.6.7

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by erkr** [comment]
@jdesmedt: thanks for filing your issue. 
Sorting artist work fine for me. So maybe I don't grasp the real issue. Wheat is meant with the remark "the list remains empty"?

**Comment by erkr** [comment]
Thanks for the additional. Seems to be a frond end error. @marcelveldt: can you have a look?

**Comment by marcelveldt** [comment]
should be fixed in 2022.6.7, if not please reopen, thanks!
