### ISSUE TITLE
Add support for DSF files

### ISSUE THREAD

**Issue by Waggers58** [music-assistant/hass-music-assistant#519]
### What version of Music Assistant has the issue?

2022.6.6

### The problem

MA fails to recognise DSF files.  Further testing shows there is a similar problem with VW files.

### How to reproduce

I loaded the troublesome files to the directory specified as music on my local drive and then restarted HA. 

### What version of Home Assistant Core are your running

2022.6.7

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by erkr** [comment]
Thanks for filing this improvement.

**Comment by marcelveldt** [comment]
What are VW files ? Do you mean WAV files perhaps ?

**Comment by marcelveldt** [comment]
Looked at this today and it's a bit more work than I hoped due to the simple fact that the ID3 tags library (TinyTag) has no support for DSF tags. I can manually parse the tags but that will take me a bit more time. I will add it somewhere in the next release but not in a bugfix/patch release.

**Comment by Waggers58** [comment]
Hi Marcel

Thank you for looking.  Only a fraction of my music collection is in DSF files.

You are doing a grand job and I would expect you to set your priorities to meet the requirements of the many first.

Regards

Ron
________________________________

**Comment by Waggers58** [comment]
Hi Marcel

Did I say VW files, I meant WV files (easy mistake to make).  They are WavPath files, which are compressed DSD files.  I only have one album in this format, so you shouldn't worry about it.

Regards

Ron

________________________________
