### ISSUE TITLE
Artist/Album view Sort by Artist Name Blank Screen

### ISSUE THREAD

**Issue by OzGav** [music-assistant/hass-music-assistant#524]
### What version of Music Assistant has the issue?

2022.6.6

### The problem

Select ARTISTS then Select ALBUMS then SORT BY ARTIST NAME results in the following screen. I do note that it doesn't seem a useful option to sort by name as these are tracks by the same artist??

![image](https://user-images.githubusercontent.com/19848947/175884408-4ec60858-817a-4407-93a9-0e77b650bfbf.png)

### How to reproduce

As above

### What version of Home Assistant Core are your running

2022.6.6

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
This might be the same as https://github.com/music-assistant/hass-music-assistant/issues/511

**Comment by erkr** [comment]
> This might be the same as https://github.com/music-assistant/hass-music-assistant/issues/511

Think you are right

**Comment by marcelveldt** [comment]
should be fixed in 2022.6.7, if not please reopen, thanks!
