### ISSUE TITLE
Song matching is failing on case differences

### ISSUE THREAD

**Issue by OzGav** [music-assistant/hass-music-assistant#525]
### What version of Music Assistant has the issue?

2022.6.6

### The problem

Just noticed that if there is a case difference in the song title then MA is not identifying the songs as the same. If the title is otherwise the same besides case then it should be identified as the same song. See below for examples

![image](https://user-images.githubusercontent.com/19848947/175885791-3943151d-10b5-4bba-bf9e-5fb5282ef0db.png)

### How to reproduce

As above

### What version of Home Assistant Core are your running

2022.6.6

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by erkr** [comment]
Thanks for filling your issue.

**Comment by marcelveldt** [comment]
OK, thanks for the additional info. I'll take a look. Probably this listing is not even using the matcher but just lists the items from all providers (and should use the matcher) with a basic match on name

**Comment by marcelveldt** [comment]
should be fixed in 2022.6.7, if not please reopen, thanks!
