### ISSUE TITLE
Empty (mostly) Playlists Being Created On System Reboot. 

### ISSUE THREAD

**Issue by RJ-Make** [music-assistant/hass-music-assistant#536]
### What version of Music Assistant has the issue?

2022.6.6

### The problem

1) Mostly Empty Playlists are Being Created On System (Windows 10 - VMWare) Reboot. 
2) I delete the created playlists, but when I reboot the windows machine more playlists are created.
3) Seems like it's always 40 playlists (Artist Name - Album) that are created.
4) Most are empty, some have songs

### How to reproduce

Reboot the computer

### What version of Home Assistant Core are your running

2022.6.7

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Windows

**Comment by marcelveldt** [comment]
Can you run a search on your music directory for m3u files ?
MA does not create any playlists by itself so it must have detected some playlists on your disk somehow.
