### ISSUE TITLE
nvidia shield media player support

### ISSUE THREAD

**Issue by JulienFloris** [music-assistant/hass-music-assistant#537]
### What version of Music Assistant has the issue?

2022.6.4

### The problem

Can Nvidia Shield become supported as media player?
i have it integrated as media player with home assistant. But when i try to play music from Music assistant it opens "welcome to Home Assistant" screen and stay's like that. 
![image](https://user-images.githubusercontent.com/20380255/176000733-3d4d66c2-28a1-4609-a9de-d595a5f058b3.png)
![image](https://user-images.githubusercontent.com/20380255/176000754-31750fdc-8ee4-4389-a0ed-d49f1ce7cb63.png)

### How to reproduce

Cast music from home assistant to nvidia shield device

### What version of Home Assistant Core are your running

2022.6.6

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by vk2him** [comment]
I have Nvidea Shield working 100% fine - I have it setup using the Google Cast integration - what are you using, can you try this method?

![Screen Shot 346](https://user-images.githubusercontent.com/22878629/176407235-09f087f9-7fb5-49f6-99a7-1b36e2dae9a0.jpg)

**Comment by JulienFloris** [comment]
@vk2him
i'll check how i intergraded the nVidia Shield with HomeAssistant

@erkr 
I'll try to find some log's ( if possible on the device) if i can't find an other way of integrating it with home-assistant

**Comment by erkr** [comment]
> @erkr
> I'll try to find some log's ( if possible on the device) if i can't find an other way of integrating it with home-assistant

Of course, first suggestion was to check if you use the chrome cast player. 
@vk2him thanks for confirming that player works for you!

**Comment by erkr** [comment]
@JulienFloris 
Is your issue resolved? If so, Any information on the player that didn't work? So we can extend the FAQ for that

**Comment by JulienFloris** [comment]
Yes tested it and it works with version 2022.6.6 not sure what changed. Was already using that chrome cast integration. 
Did find one other bug with the volume but ill post separated post about that. Thanks everyone for the help
