### ISSUE TITLE
Error in async_setup_entry  stream_ip = get_local_ip_from_internal_url(hass)

### ISSUE THREAD

**Issue by kayloehmann** [music-assistant/hass-music-assistant#545]
### What version of Music Assistant has the issue?

2022.6.8

### The problem

During the setup of the integration i get the following error in the logs. 
<img width="1294" alt="image" src="https://user-images.githubusercontent.com/34281638/176369683-3150cb06-a959-48ab-9fd3-07c6a0897f2f.png">

Version before worked. I reinstalled the HACS component and tried to reconfigure the integration.

### How to reproduce

Reinstall Music Assistant

### Relevant log output

`Logger: homeassistant.config_entries
Source: helpers/network.py:201 
First occurred: 08:41:48 (1 occurrences) 
Last logged: 08:41:48

Error setting up entry Music Assistant for mass
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 339, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/mass/__init__.py", line 115, in async_setup_entry
    stream_ip = get_local_ip_from_internal_url(hass)
  File "/config/custom_components/mass/__init__.py", line 58, in get_local_ip_from_internal_url
    url = get_url(hass, allow_internal=True, allow_external=False)
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 201, in get_url
    raise NoURLAvailableError
homeassistant.helpers.network.NoURLAvailableError`

### What version of Home Assistant Core are your running

2022.6.7

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

ODROID

**Comment by marcelveldt** [comment]
Make sure that you enter a url in the "internal url" field of your Home Assistant settings.
This may be an IP address or local resolveable hostname.

**Comment by marcelveldt** [comment]
Settings --> System --> Network --> Home Assistant URL --> Local network

<img width="766" alt="Schermafbeelding 2022-06-29 om 09 00 40" src="https://user-images.githubusercontent.com/6389780/176372446-3897bb25-612d-469c-b6ed-ebc93b5204a9.png">

**Comment by kayloehmann** [comment]
I did change the setting, but the same error still appears.

<img width="627" alt="image" src="https://user-images.githubusercontent.com/34281638/176373373-94e5efc8-8413-4580-9824-bd1cd83cb059.png">

Maybe it is an issue with https?

**Comment by userMak** [comment]
I just realize I have the same problem. I also noticed that in System-Hardware the page is now blank. I updated music assistant before a while. Now I remove it but the problem remains

**Comment by marcelveldt** [comment]
Hmm, so you have HTTPS on the internal URL ? That is something special :-)
Most people do not have a certificate on the internal URL and only on the external URL.

So yes, it definitely has to do with that. I will add a small workaround in the code to fallback to the previous logic but that will fail for users not running HomeAssistant OS

**Comment by marcelveldt** [comment]
> 



> I just realize I have the same problem. I also noticed that in System-Hardware the page is now blank. I updated music assistant before a while. Now I remove it but the problem remains

The config/settings pages of HA have changed a lot in the previous updates. Some stuff is relocated.

**Comment by kayloehmann** [comment]
Thanks for looking into this! I do not insist on https on the internal network. Is there a way to remove it?

**Comment by kayloehmann** [comment]
I will try to remove the https config an reconfig.

**Comment by userMak** [comment]
> Hmm, so you have HTTPS on the internal URL ? That is something special :-)
> Most people do not have a certificate on the internal URL and only on the external URL.

That is my case too. The previous version was working ok although. Also I am not sure how I could change the HTTPS in my internal URL

**Comment by kayloehmann** [comment]
I made the changes and can confirm that it works again by using http.

**Comment by marcelveldt** [comment]
> I made the changes and can confirm that it works again by using http.

OK, that is good to hear. Nevertheless I'll put a small patch in the code to fallback to the interface IP when we couldn't derive the local IP from the internal URL.

**Comment by userMak** [comment]
> I made the changes and can confirm that it works again by using http.

I am using duckdns and I cannot set the internal url to http. can you tell me how you did it please?

**Comment by SeByDocKy** [comment]
Got the same error with duckdns. Everything is correctly setup for mu HA

![image](https://user-images.githubusercontent.com/6464595/176382858-b65182eb-79c4-4790-aebf-e86bed5b2846.png)

**Comment by kayloehmann** [comment]
> 

I simply removed the ssl http configuration from configuration.yaml. Thats it.

**Comment by marcelveldt** [comment]
Just wait a few hours. I will release the fix within that time

**Comment by userMak** [comment]
> Just wait a few hours. I will release the fix within that time

ok. However I just roll back to previous version and now is working again

**Comment by LordNex** [comment]
I'm getting the same error

Logger: homeassistant.config_entries
Source: helpers/network.py:207 
First occurred: 3:37:16 AM (1 occurrences) 
Last logged: 3:37:16 AM

Error setting up entry Music Assistant for mass
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 339, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/mass/__init__.py", line 115, in async_setup_entry
    stream_ip = get_local_ip_from_internal_url(hass)
  File "/config/custom_components/mass/__init__.py", line 58, in get_local_ip_from_internal_url
    url = get_url(hass, allow_internal=True, allow_external=False)
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 168, in get_url
    request_host = _get_request_host()
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 207, in _get_request_host
    raise NoURLAvailableError
homeassistant.helpers.network.NoURLAvailableError

**Comment by LordNex** [comment]
I have my home assistant setup on VMWare, I have a network interface on home assistant for each VLAN I have so that it can easily reach and control devices on any VLAN. So that might be the issue.

**Comment by marcelveldt** [comment]
@LordNex read above. A fix is on the way.

**Comment by LordNex** [comment]
![image](https://user-images.githubusercontent.com/9270948/176395724-e6fe7b0a-42e8-46f0-9e37-605b7b5bac85.jpeg)

**Comment by LordNex** [comment]
![image](https://user-images.githubusercontent.com/9270948/176395786-a1ea3304-60a4-45fc-9521-be1311b75902.jpeg)

![image](https://user-images.githubusercontent.com/9270948/176395835-bb79daa9-1b17-42a4-b8bb-1b9a97eb4aa3.jpeg)

**Comment by LordNex** [comment]
> @LordNex read above. A fix is on the way. 

@marcelveldt Seen that thanks. Just thought I'd pass along the way I have things setup incase you were wondering. I went ahead and bought a Nabu casa account a long time ago so that's usually how I connect. But I still throw DuckDNS on there for other reasons. Thanks for all the hard work. Very nice piece of software! 👍

**Comment by marcelveldt** [comment]
I just released 2022.6.9 with the fix included. Please reopen if you still experience any issues. Thanks!

**Comment by LordNex** [comment]
I'm still seeing this show up in the logs. 

This error originated from a custom integration.

Logger: custom_components.mass
Source: custom_components/mass/__init__.py:67 
Integration: Music Assistant (documentation, issues) 
First occurred: 2:05:26 AM (1 occurrences) 
Last logged: 2:05:26 AM

Unable to retrieve the internal URL from Home Assistant, this may cause issues resolving the correct internal stream ip. Please set a valid internal url in the Home Assistant configuration

**Comment by mattkerrison** [comment]
I've got the same issue:

```
Unable to retrieve the internal URL from Home Assistant, this may cause issues resolving the correct internal stream ip. Please set a valid internal url in the Home Assistant configuration
```

My configuration is using DuckDNS for external access and forwarding my port which seems to be standard practice. No other intergrations seem to have an issue with it, because of this I see 'MusicAssistant is not initialized' when trying to access it
