### ISSUE TITLE
Track not appearing on album

### ISSUE THREAD

**Issue by OzGav** [music-assistant/hass-music-assistant#548]
### What version of Music Assistant has the issue?

2022.6.8

### The problem

I have identified an album where the first track is missing. Ignoring the remaster entries you can see the track 1 “Abacab” is missing.
![98A95E32-836F-4DA4-B1B1-FC752C92D4D3](https://user-images.githubusercontent.com/19848947/176406564-a9fbbf8f-802c-4c1e-babc-138a24309d94.jpeg)
When I go and search the tracks I can see it with the correct album name (entry #2 below) but the cover art is wrong.
![FE8B1544-63A6-4A23-AE9F-47FAD1C3ACBB](https://user-images.githubusercontent.com/19848947/176407056-35d67097-0bad-4df9-af20-ebf14c7559e9.jpeg)
If I select the vertical ellipsis for entry #2 and then SHOW INFO the track is shown with the correct cover art.
![DA4AD433-7679-4D60-BDA8-EE630E446CFD](https://user-images.githubusercontent.com/19848947/176407407-e0f8c21a-e1a4-44d7-b021-ed8810aa12d2.jpeg)
I then thought maybe it has been attached to the wrong album so I navigated to “The Vertigo Years” but the tracks there are good. 
![C914659A-36F8-4089-8838-A43293001353](https://user-images.githubusercontent.com/19848947/176407648-049c2ab5-74bb-48e3-831e-3842ad20131d.jpeg)
Any ideas what could be wrong or how I can get that track back into the album?

### How to reproduce

As above 

### What version of Home Assistant Core are your running

2022.6.6

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by marcelveldt** [comment]
I assume you did check the ID3 tags of those songs ?
Would it be possible if you share these files with me so I can reproduce it myself? I can step through all logic in the debugger to find out what it's doing.

Are you on discord perhaps? my username there is marcelveldt#0393

**Comment by marcelveldt** [comment]
fixed in 2022.6.10 - please reopen if not resolved, thanks!
