### ISSUE TITLE
Database issues when id3 data is changed

### ISSUE THREAD

**Issue by vk2him** [music-assistant/hass-music-assistant#549]
### What version of Music Assistant has the issue?

2022.6.8

### The problem

I used MusicBrainz Picard  to modify the details of two tracks that were in my database - refer to this screenshot for the changes made.

![Screen Shot 341](https://user-images.githubusercontent.com/22878629/176410681-2c06c030-0338-473d-aa8e-4d0107dd4092.jpg)

Before this change, this screenshot shows what the Album looks like (Refer to the red Unplugged album):

![Screen Shot 339](https://user-images.githubusercontent.com/22878629/176411477-0f1aef14-8f0c-40a5-a9cf-368628cfcbbe.jpg)

After saving the Picard data and triggering a DB refresh, the original red unplugged album is still in the database plus the corrected version as seen in this screenshot - Note the red Unplugged album is there and the new Clapton Chronicles 

![Screen Shot 342](https://user-images.githubusercontent.com/22878629/176412116-fad88933-98d6-484e-b785-817f2369b31d.jpg)

If I look at the details of the songs in those albums, they appear twice (under old and new) and the the "preview" play icons don't work however the songs will play using the normal click to play method.

![Screen Shot 343](https://user-images.githubusercontent.com/22878629/176412905-6bd265b6-8a57-4019-b88e-2652f110b078.jpg)

Reloading MA and clearing browser cache made no difference - thanks!

### How to reproduce

See above

### Relevant log output

No errors

### Additional information

I'm running Home Assistant using Virtual Box on Windows11

### What version of Home Assistant Core are your running

2022.6.7

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Alternative

**Comment by marcelveldt** [comment]
fixed in 2022.6.10 - although it will not (or only partly) correct any already messed up situations.
You can either do a "refresh item" on the offending items or reset the database: simply disable the file provider, wait for the sync to complete and re-enable the file provider.

please reopen if not resolved, thanks!

**Comment by vk2him** [comment]
Sorry for delay - I was away all weekend - many thanks for this, yes my testing shows it's now working - I nuked the db so didn't test if it fixed previously messed up files. Cheers
