### ISSUE TITLE
Music Assistant not playing after update

### ISSUE THREAD

**Issue by Trigun** [music-assistant/hass-music-assistant#551]
### What version of Music Assistant has the issue?

2022.6.8 (latest)

### The problem

when selecting a spotify song or a radio stream, it doesn't play (it seems it happend after the update)

### How to reproduce

just select a song and play it

### Relevant log output

2022-06-29 13:49:16 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/music_assistant/models/player_queue.py", line 502, in load
item.sort_index = index
AttributeError: 'NoneType' object has no attribute 'sort_index'
2022-06-29 13:49:47 WARNING (MainThread) [music_assistant.players.stream] Abort: client(s) did not connect within 10 seconds.
2022-06-29 13:49:50 WARNING (MainThread) [music_assistant.players.stream] Abort: client(s) did not connect within 10 seconds.
2022-06-29 13:50:21 WARNING (MainThread) [music_assistant.players.stream] Abort: client(s) did not connect within 10 seconds.
2022-06-29 13:50:30 WARNING (MainThread) [music_assistant.players.stream] Abort: client(s) did not connect within 10 seconds.

### What version of Home Assistant Core are your running

ha core: 2022.6.7 - ha OS: 8.2 - supervisor: 2022.05.3 

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by marcelveldt** [comment]
OK, I've seen this issue once before and was never able to reproduce. 
Simple solution for now is to just clear the items from the queue once.

**Comment by Trigun** [comment]
done but the result stays the same.
it actually doesn't load any stream or song at all

**Comment by marcelveldt** [comment]
You used the button to clear the queue ?

![Schermafbeelding 2022-06-29 om 14 00 40](https://user-images.githubusercontent.com/6389780/176431360-5773166b-d007-43a0-a8bc-a56756f49b61.png)

**Comment by Trigun** [comment]
I don't have a settings option( where can I find it?)
also, th circle in the upper right corner keeps on spinning.

**Comment by marcelveldt** [comment]
Select player --> Click queue --> Select the contextmenu button in the top right (those 3 dots)

**Comment by Trigun** [comment]
got it, thanks! but i keep having the same issue:
![image](https://user-images.githubusercontent.com/30350020/176433171-4c0ecb8c-52d4-45cd-a6a8-47c219b63dbf.png)

**Comment by marcelveldt** [comment]
I think something else is going on,...
what do you have filled in at the "internal URL" field of your setup ?

**Comment by Trigun** [comment]
I assume the Home assistant setup?
it says:

![image](https://user-images.githubusercontent.com/30350020/176433872-c47cedfe-8ab7-48b3-8373-27961d969453.png)

**Comment by Trigun** [comment]
Interesting. when setting it to the actual internal IP adres, it all works!
extra interesting it that because it did work previously.

is it right to set the inter ip adres instead of hostname?

**Comment by Trigun** [comment]
great! thanks a lot for your quick replies and help!!

i'll mark this issue as solved.
