### ISSUE TITLE
Volume Equalization Setting Mismatch HASS/MASS

### ISSUE THREAD

**Issue by jazzyisj** [music-assistant/hass-music-assistant#554]
### What version of Music Assistant has the issue?

2022.6.6

### The problem

In the HA UI the volume equalization entities go from -40 to 0.  
In the MASS UI the volume eqalization setting sliders go from -40 to 10.
Also in the MASS UI the sliders appear to be at 20% when at their lowest value (-40)
<img width="235" alt="ha vol 10" src="https://user-images.githubusercontent.com/44064559/176499023-e16f778d-09f4-40d9-bdb0-f673e97d2dd7.PNG">
<img width="592" alt="vol 10" src="https://user-images.githubusercontent.com/44064559/176499718-79498dc4-763a-4cdf-a930-ff98cbcffa0d.PNG">
<img width="587" alt="vol -40" src="https://user-images.githubusercontent.com/44064559/176499595-16f270da-0482-4f3b-8abc-32cbab780a35.PNG">

Edit:  I think the issue is here for the 0/10 difference.  I'd do a PR but I don't know which is correct, the MASS UI or the HA one.

https://github.com/music-assistant/hass-music-assistant/blob/4e12f17507206b3193783609318f8f057a7fee86/custom_components/mass/number.py#L84

### How to reproduce

Open device settings in HA for a MASS media player and open media player settings for media player in MASS.

### What version of Home Assistant Core are your running

2022.6.7

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

ODROID

**Comment by erkr** [comment]
Yes you are right, it looks like the MA slider is 10 points off indeed. 
The slider can not move totally to the left. The max value should not be +10, but zero (or lower).
Thanks for reporting!

**Comment by marcelveldt** [comment]
fixed in 2022.6.10 - please reopen if not resolved, thanks!
