### ISSUE TITLE
minor issue when displaying album's tracks - space is missing after artists' name

### ISSUE THREAD

**Issue by pejotigrek** [music-assistant/hass-music-assistant#559]
### What version of Music Assistant has the issue?

2022.6.9

### The problem

not a big deal, but my OCD keeps the "what can be seen, cannot be unseen" mode on this:

![image](https://user-images.githubusercontent.com/10796588/176628571-46026c1e-57f1-4b7b-8819-84ac01a4ef39.png)

while displaying tracks, there's missing space after the artists' name, and before the "-" sign :)

### How to reproduce

choose an album and display it's tracks

### What version of Home Assistant Core are your running

2022.6.7

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Linux

**Comment by marcelveldt** [comment]
fixed in 2022.6.10 - please reopen if not resolved, thanks!

**Comment by pejotigrek** [comment]
> fixed in 2022.6.10 - please reopen if not resolved, thanks!

unfortunately still looks like it's not resolved [updated, tried even with newly added albums - space still missing]

**Comment by marcelveldt** [comment]
Did you refresh your browser ? It was a frontend change so you may need to force refresh it (e.g. with shift F5)

**Comment by pejotigrek** [comment]
> Did you refresh your browser ? It was a frontend change so you may need to force refresh it (e.g. with shift F5)

yes. tried them all - ctrl/shift F5, and even "clear cache and force refresh" option that's showing up when developer tools are visible [ctrl-shift-i in chrome, then right click on the refresh button]

**Comment by marcelveldt** [comment]
Hmm, you're right. It seems that this change did not make it into the final release build. Strange..
It will be in next release.
