### ISSUE TITLE
Syntax error in mass.umd.js

### ISSUE THREAD

**Issue by dlarrick** [music-assistant/hass-music-assistant#56]
This looks great and I'd love to try it out! I installed via HACS but see the following in the Chrome console when I go to the Music Assistant tab, and the frame is just white:

`Uncaught SyntaxError: Unexpected token '}'` `mass.umd.js:formatted:55`

Because that file is generated / minified, I'm having some trouble correcting this error.

**Comment by marcelveldt** [comment]
I'm about to publish an update to fix the issue. Something went wrong building the frontend app which is published in the HACS package.
