### ISSUE TITLE
Grouped Nest players not working

### ISSUE THREAD

**Issue by WHagenauw** [music-assistant/hass-music-assistant#560]
### What version of Music Assistant has the issue?

2022.6.9

### The problem

Grouped Nest players (in a helper group together with Sonos) still not working correctly.  They are showing in MA but cannot be turned on. The Sonos is playing but the Nest stays light grey color. Individually they can play but not in the helper  group.

### How to reproduce

Crreate helper group with both Sonos and Nest grouped players (don't know if Sonos needs to be in it).

### What version of Home Assistant Core are your running

2022.6.7

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by WHagenauw** [comment]
Hello Marcel,

That's just what I have 2 stereo cast sets combined with 2 Sonos stereo
sets. These combined in a helper group

Hopefully you can test this also

Kind regards

Wim




Op do 30 jun. 2022 17:28 schreef Marcel van der Veldt <
***@***.***>:

**Comment by marcelveldt** [comment]
Ah OK that is the only combi I did not try haha. Will do that now.

**Comment by marcelveldt** [comment]
fixed in 2022.6.10 - please reopen if not resolved, thanks!

**Comment by WHagenauw** [comment]
Hello,

Finally time to test it out. Seems to be working fine now!. Next thing is
to synchronize the players. Any idea when this is implemented?

Kind regards,

Wim


Op do 30 jun. 2022 om 17:47 schreef Wim Hagenauw ***@***.***>:

**Comment by marcelveldt** [comment]
OK great!
Synchronize is something to pick up within the next 2 weeks. It will not be in the launch of the 2022.7 version but it will in the 2022.8 version
