### ISSUE TITLE
Fileprovider sync crashes on a folder it can't access

### ISSUE THREAD

**Issue by OzGav** [music-assistant/hass-music-assistant#563]
### What version of Music Assistant has the issue?

2022.6.9

### The problem

If when scanning the media directory something is found which causes a permission denied error then the scan stops.

### How to reproduce

Set a directory in the media folder with administrator only permissions. Scan the folder.

### Relevant log output

```
Logger: music_assistant
Source: /usr/local/lib/python3.9/site-packages/music_assistant/mass.py:244
First occurred: 29 juin 2022 à 19:29:42 (5 occurrences)
Last logged: 07:29:29

Job [Library sync for provider Filesystem] failed with error [Errno 13] Permission denied: '/media/nasfiles/#recycle'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/music_providers/filesystem.py", line 156, in sync_library
    async for entry in scantree(self.config.path):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/music_providers/filesystem.py", line 68, in scantree
    async for subitem in scantree(entry.path):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/music_providers/filesystem.py", line 66, in scantree
    for entry in await loop.run_in_executor(None, os.scandir, path):
PermissionError: [Errno 13] Permission denied: '/media/nasfiles/#recycle'
```

### Additional information

Discussion here (https://github.com/music-assistant/hass-music-assistant/discussions/452)

### What version of Home Assistant Core are your running

2022.6.6

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by marcelveldt** [comment]
fixed in 2022.6.10 - please reopen if not resolved, thanks!
