### ISSUE TITLE
Error failing to get MB artist ID

### ISSUE THREAD

**Issue by OzGav** [music-assistant/hass-music-assistant#565]
### What version of Music Assistant has the issue?

2022.6.9

### The problem

Was looking around the database at different artists. Then later I noticed these errors. 4FRNT came from a Spotify track so not sure about that one. I think Ramiro might have been the same. 

However, Jeff Lynn's ELO MB artist ID is 0c502791-4ee9-4c5f-9696-0602b721ff3b according to the tracks which are tagged by Picard. The problem here by the looks of it is that Picard has the artist name as "Jeff Lynn's ELO" so that is what is tagged on my tracks. However, the MB artist ID tagged is for "Electric Light Orchestra" so a difference in name. Having said all of this I am wondering why MA is looking up the artist ID when it is already in the tags for the tracks?

Anthony Warlow is a different situation. The CD is a random one I got from somewhere which isn't in the MB database and has minimal tags. However Anthony Warlow is in the database with artist ID 7ad0a863-e2e0-4038-be9b-02f4011ee348 

Any ideas?

### How to reproduce

Not sure...

### Relevant log output

```
Logger: music_assistant.metadata
Source: /usr/local/lib/python3.9/site-packages/music_assistant/controllers/metadata/__init__.py:161
First occurred: 8:32:11 AM (4 occurrences)
Last logged: 8:40:47 AM

Unable to get musicbrainz ID for artist 4FRNT !
Unable to get musicbrainz ID for artist Jeff Lynne's ELO !
Unable to get musicbrainz ID for artist Ramiro !
Unable to get musicbrainz ID for artist Anthony Warlow !
```

### What version of Home Assistant Core are your running

2022.6.6

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by marcelveldt** [comment]
Just released 2022.7 beta 0
This issue should be fixed in that release. If you still experience any issues, please re-open this ticket or open a new one. Thanks!
