### ISSUE TITLE
Error Syncing NAS Share with .recycle/user Folder

### ISSUE THREAD

**Issue by LordNex** [music-assistant/hass-music-assistant#568]
### What version of Music Assistant has the issue?

Latest Release

### The problem

I have my NAS drive mapped via a script as outlined in the How To. The script runs at startup and mounts the drive fine and I can see, navigate, and play any of the files under Media>Local Files>NASFiles. But when MA syncs the drive I only see a small amount of artists show up. I looked through the logs and found the following error

Logger: music_assistant
Source: /usr/local/lib/python3.9/site-packages/music_assistant/mass.py:244 
First occurred: 2:07:59 AM (3 occurrences) 
Last logged: 5:39:28 AM

Job [Library sync for provider Filesystem] failed with error [Errno 13] Permission denied: '/media/nasfiles/.recycle/lord_nex'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/music_providers/filesystem.py", line 163, in sync_library
    async for entry in scantree(self.config.path):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/music_providers/filesystem.py", line 75, in scantree
    async for subitem in scantree(entry.path):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/music_providers/filesystem.py", line 75, in scantree
    async for subitem in scantree(entry.path):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/music_providers/filesystem.py", line 73, in scantree
    for entry in entries:
PermissionError: [Errno 13] Permission denied: '/media/nasfiles/.recycle/lord_nex'

Could this be causing the rest of the scan to fail? The user has rights to the NAS fine but probably doesn’t to the hidden .recycle folder. I didn’t know if there was anything I could do or change, I have the local files set to /media/nasfiles which is where my script mounts the drive. 

### How to reproduce

Not sure. Im running OpenMediaVault as a NAS Server on VMWare

### Relevant log output

Logger: music_assistant
Source: /usr/local/lib/python3.9/site-packages/music_assistant/mass.py:244 
First occurred: 2:07:59 AM (3 occurrences) 
Last logged: 5:39:28 AM

Job [Library sync for provider Filesystem] failed with error [Errno 13] Permission denied: '/media/nasfiles/.recycle/lord_nex'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/music_providers/filesystem.py", line 163, in sync_library
    async for entry in scantree(self.config.path):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/music_providers/filesystem.py", line 75, in scantree
    async for subitem in scantree(entry.path):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/music_providers/filesystem.py", line 75, in scantree
    async for subitem in scantree(entry.path):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/music_providers/filesystem.py", line 73, in scantree
    for entry in entries:
PermissionError: [Errno 13] Permission denied: '/media/nasfiles/.recycle/lord_nex'

### What version of Home Assistant Core are your running

2022.6.7

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Alternative

**Comment by marcelveldt** [comment]
did you test this with MA version 2022.6.10 ?

**Comment by LordNex** [comment]
It also doesn’t scan the entire directory. It seems to get one or two artists in the directory but I have hundreds. No matter how many times I scan it pretty much stays the same. It does seem to pick up the occasional extra track or at least the number of tracks has slowly went up by one or two over the past week. 

What would be nice is if it could scan that entire directory and list all audio files that it can handle. 

Let me know if there are character restrictions or anything as a few of the albums have some.

**Comment by erkr** [comment]
AFAIK uni code characters can cause issues

**Comment by LordNex** [comment]
Yes, same issue

Benjamin T Powers

On Jul 5, 2022, at 3:54 AM, Eric ***@***.***> wrote:

﻿

AFAIK uni code characters can cause issues

**Comment by LordNex** [comment]
Ok I’ll go through my list and see if there is something out of spec. Might try a cleanup app for mp3s

On Jul 5, 2022, at 3:54 AM, Eric ***@***.***> wrote:

﻿

AFAIK uni code characters can cause issues

**Comment by LordNex** [comment]
Just remapped the drive and reconfigured the integration from scratch. Still getting the same error regarding the recycle folder and that seems to be killing the sync job. I went through my directories and removed any obviously bad actors so this is the only thing holding it up. 

Can you put in a skip or ignore on directories that come up permission denied? That way it can continue to scan the folder it does have access too without stopping the whole thing.

**Comment by marcelveldt** [comment]
Can you please give version 2022.7 beta 1 a try ?
I think/hope I fixed this one today. Thanks!

**Comment by LordNex** [comment]
> Can you please give version 2022.7 beta 1 a try ?
> 
> I think/hope I fixed this one today. Thanks!

@marcelveldt Testing it out now. Thanks I'll let you know once it's finished booting and scanning

**Comment by LordNex** [comment]
@marcelveldt When it finished the scan MA was unresponsive. Rebooted and still was unresponsive. This was all I could find in the log. 

Logger: music_assistant.music_providers.filesystem
Source: /usr/local/lib/python3.10/site-packages/music_assistant/music_providers/filesystem.py:67 
First occurred: 10:34:46 PM (1 occurrences) 
Last logged: 10:34:46 PM

Skip folder /media/nasfiles/.recycle/lord_nex: [Errno 13] Permission denied: '/media/nasfiles/.recycle/lord_nex'

**Comment by marcelveldt** [comment]
Ok so it looks like my fix works for skipping the folder.
Now I'm curious what you mean with "unresponsive"

**Comment by LordNex** [comment]
> Ok so it looks like my fix works for skipping the folder.
> 
> Now I'm curious what you mean with "unresponsive"

When I'm in the iOS app, I cannot click on tracks, artists, or anything else. If on a desktop, it shows a partial sync of Spotify, but no local files. If I click on the directory browse it just has a loading progress bar that rolls up top. 

Although I have verified that I can navigate the nasfiles under Media in Home Assistant and play files from the directory. So this seems tied to MA and not HA's access to the drive mounted to nasfiles. It did look like it was attempting to scan the directory though. I guess I should also ask if there are limits to the amount it can scan as I have a modest size share, but this will eventually be scailed up to include my whole library that's close to a petabyte. I might have to see if I can find a manager that can just publish playlists instead of having to scan the entire directory.

**Comment by marcelveldt** [comment]
The recent changes make sure it can handle really large collections so you should be all set.
The only thing to look out for however is to make your structure less flattened.

So better to have an Artist\Album\track.ext structure than all files in a single folder.
Once the first scan ahs been done, your music is in the local database and will only be accessed again when you play a file or change tags.

So thing is to get through that first scan.
Maybe my fix is not good enough as it now logs but still aborts the whole sync.
I will try if i can reproduce this somehow.

**Comment by marcelveldt** [comment]
OK, another attempt to work around it in beta 2...
This should skip system directories (starting with a dot) like recycle bin and it will log any non accessible directories.

Please give 2022.7 beta 2 a try and let me know!

**Comment by LordNex** [comment]
No go. It did seem to scan more of my Spotify correctly though. Almost every song I've ever played through there showed up. But not my nasfiles. If I ,on iOS, goto browse and then to filesystem, it just spins the progress bar and never enumerates the directory


Logger: homeassistant.setup
Source: setup.py:298 
First occurred: 11:42:37 PM (1 occurrences) 
Last logged: 11:42:37 PM

Unable to prepare setup for platform mass.number: Platform not found (Exception importing custom_components.mass.number).


This error originated from a custom integration.

Logger: homeassistant.loader
Source: custom_components/mass/number.py:54 
Integration: Music Assistant (documentation, issues) 
First occurred: 11:42:37 PM (1 occurrences) 
Last logged: 11:42:37 PM

Unexpected exception importing platform custom_components.mass.number
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 618, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 635, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/mass/number.py", line 51, in <module>
    class CrossfadeDurationEntity(MassBaseEntity, NumberEntity):
  File "/config/custom_components/mass/number.py", line 54, in CrossfadeDurationEntity
    entity_description = NumberEntityDescription(
TypeError: __init__() got an unexpected keyword argument 'native_unit_of_measurement'



I see that beta 3 is out. I'll try that too and see what happens

**Comment by LordNex** [comment]
Ohh also, I had to roll back to 2022.6 due to issues with Dwains Dashboard not being patched for the new python. Not sure if that makes a difference though. If you want I can provide my system health

**Comment by LordNex** [comment]
Wait. This might be my issue. For some reason my drive mapping stopped. Let me look deeper and I'll report back when I can

**Comment by LordNex** [comment]
Sweet! Looks like beta 3 is working so far. Haven't really tried queueing anything up as everyone's asleep. But it's enumerated the directories properly. I think there may be some music videos in the directories as well. But it seems like it's working. 

Good work man 👍

**Comment by marcelveldt** [comment]
Great! 
I think you can use the MA 2022.7.x beta on HA 2022.6 but you'll just see some 'native_unit_of_measurement' errors and the control entities will not be working but that is not a real big deal I guess

**Comment by LordNex** [comment]
Yea I'm waiting for Dwain to update his dashboard as it crashes under the new python version. So as soon as that gets updated hopefully I'll be back to running normally. 

Honestly I wouldn't be surprised to see your addon adopted by HA as a default. 

Although I think I'm going to replace my google homes with an ESP based Bluetooth speaker like the muze. Less reliance on Google and the ability to run my own internal voice assistant

**Comment by LordNex** [comment]
Just wondering. Is it possible to integrate a recording feature into this so that you could output or save files. For either radio podcasts or Spotify?

I would imagine that's a totally different beast but would be a cool feature being to save an album for offline use or something.

**Comment by marcelveldt** [comment]
No that will totally violate the terms of use so that is not going to happen, sorry.
