### ISSUE TITLE
User input malformed: value must not be one of 

### ISSUE THREAD

**Issue by Mariusthvdb** [music-assistant/hass-music-assistant#580]
### What version of Music Assistant has the issue?

2022.6.10

### The problem

seeing this when clicking next on the configuration page
<img width="212" alt="Schermafbeelding 2022-07-02 om 08 37 59" src="https://user-images.githubusercontent.com/33354141/176989804-fda97c73-2307-4559-a956-be8e7a51d800.png">

### How to reproduce

indeed some of the earlier selected media_players show with their entity_id, I suppose it is because they are currently offline (not powered).

I came here to deselect the local files option for my NAS. And to reach that, we need to pass the media_players selection page first.

Seems this could be improved, maybe have 2 option panels, which can be reached separately?

anyways, these players should nt error out on the page when powered off.

### What version of Home Assistant Core are your running

2022.8.0.dev20220702

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by erkr** [comment]
It's not specific for the core dev version. See it also on core-2022.6.7

**Comment by jazzyisj** [comment]
This issue also happens with "temporary" browser players, for example a mobile browser_mod media player. 

If you set up for example an external url browser_mod media player while it is active, then go back into the configuration at a later time to set up another media player, and that browser media player has gone inactive (unavailable) you cannot finish the configuration with the unavailable media player listed.

The workaround is the same, either "activate" the unavailable media player and then restart the configuration or delete it from the list of media players.

I have not noticed any other issues so far having an "unavailable" player set up in MASS except during the config flow.

**Comment by marcelveldt** [comment]
This is the default behavior of the HA frontend. There is a "entity selector" in that config screen provided by HA.
Apparently that filters out unavailable entities. Not sure if that filter was there always or added recently. In any way I do not think it should error on those unavailable errors.

**Comment by Mariusthvdb** [comment]
well, fwiw, I didnt see it before, but admit not configuring MA on a daily base ;-)
this certainly is new, because in my home the players are never all online, so I could not have made the selection I did with this selector behavior.

More importantly maybe, I can not configure the rest of the options, which is a real issue.....

**Comment by erkr** [comment]
I can contribute to that. The issue was not there a few weeks ago

**Comment by Mariusthvdb** [comment]
hmm, for the experiment I turned them all on, even stream to my Marantz Na 7004, and the HomePod which is never off.

And yet:

<img width="558" alt="Schermafbeelding 2022-07-02 om 15 29 56" src="https://user-images.githubusercontent.com/33354141/177003013-04ba90cd-6909-4c47-8f39-e58b781100d0.png">

they wont show with their Names, and this keep blocking the Config flow

**Comment by marcelveldt** [comment]
I see a way to work around this. Will provide a fix in the 2022.7 beta
