### ISSUE TITLE
Integration Configuration issue if Device is powered off

### ISSUE THREAD

**Issue by vk2him** [music-assistant/hass-music-assistant#582]
### What version of Music Assistant has the issue?

All versions

### The problem

When I initially configure MA, I am only able to add my Music player entities that are Powered on - this is expected behaviour .

However if I **_turn off an entity_** and then go back into MA Configuration, the previously selected entity has lost it's "pretty name" and I get an error message as per following screenshot (refer to x4000 and x4200 as they have lost their pretty names). This seems to have been introduced at some stage as I never had this before - it may have occurred after a recent mod you did for Denon and devices that didn't respond to the play/stop/pause button, but I can't be 100% sure on that. 

My entities are Denon via DLNA and Browser_mod music players and they are affected with this issue.

If I power on the entity, it appears OK in MA configuration. It's a bit of an issue as I have to remember to power them on before doing any config changes.

Can previously enabled devices be "forced" to remain unless deleted? Thanks

![Screen Shot 349](https://user-images.githubusercontent.com/22878629/177039041-f8742822-55a8-4b27-adb7-b3a69d250041.jpg)

### How to reproduce

Power off an entity then go into config - refer above.

### What version of Home Assistant Core are your running

2022.6.7

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Windows

**Comment by marcelveldt** [comment]
see #580 will be fixed in next (beta) version

**Comment by vk2him** [comment]
Thanks, I'll close this then
