### ISSUE TITLE
Unable to "preview" m4a files

### ISSUE THREAD

**Issue by vk2him** [music-assistant/hass-music-assistant#584]
### What version of Music Assistant has the issue?

2022.6.10

### The problem

I'm seeing inconsistent results when trying to preview titles with m4a extension - initially when first looking at the
details of a title the Play icon to preview may or may not be enabled, If it is enabled, either moving the mouse cursor over the preview window will make the play icon grey out - or if I am able to click preview, after pressing pause it is no longer enabled. MP3 and other extension such as flac don't seem to be affected. Tested on Chrome/Brave/Microsoft Edge - same results

### How to reproduce

See above

### What version of Home Assistant Core are your running

latest

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Windows

**Comment by marcelveldt** [comment]
This one should be fixed in current beta. If not, please reopen

**Comment by vk2him** [comment]
Yes it's fixed thanks!
