### ISSUE TITLE
Unable to configure active instance

### ISSUE THREAD

**Issue by escoand** [music-assistant/hass-music-assistant#590]
### What version of Music Assistant has the issue?

2022.6.10

### The problem

Configure an active MA instance fails, even without changing anything.
![image](https://user-images.githubusercontent.com/428567/177171579-8f341e5f-5c3e-48fa-8c7a-6c969ab7c205.png)

### How to reproduce

1. Add new MA instance.
2. Click on configure.
3. Hit Continue

### What version of Home Assistant Core are your running

2022.6.7

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

ODROID

**Comment by erkr** [comment]
Please check issue #580. I guess this is the same issue?!

**Comment by escoand** [comment]
Your right, just happening if one is off.
