### ISSUE TITLE
Playback stops suddenly

### ISSUE THREAD

**Issue by escoand** [music-assistant/hass-music-assistant#595]
### What version of Music Assistant has the issue?

2022.6.10

### The problem

Music playback stops suddenly without user interaction. Maybe it has to do with https://github.com/home-assistant/core/issues/73319 and this message. But this is not happening at the same time.

```
Logger: spotipy.client
Source: /usr/local/lib/python3.9/site-packages/spotipy/client.py:276
First occurred: 4. Juli 2022 um 21:52:10 (1543 occurrences)
Last logged: 11:27:10

Max Retries reached
```

### How to reproduce

Don't know

### Relevant log output

```
Logger: aiohttp.server
Source: /usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py:405
First occurred: 5. Juli 2022 um 13:22:55 (5 occurrences)
Last logged: 11:23:19

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/streams.py", line 228, in serve_queue_stream
    await queue_stream.subscribe(client_id, audio_callback)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/streams.py", line 393, in subscribe
    await callback(self._prev_chunk)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/streams.py", line 220, in audio_callback
    image = item_in_buf.image or ""
AttributeError: 'NoneType' object has no attribute 'image'
```

### What version of Home Assistant Core are your running

2022.6.7

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

ODROID

**Comment by marcelveldt** [comment]
1) You do not need the Spotify integration in HA core for MA to work.
2) There's a bug in MA for me to solve, thanks for that errorlog snippet.

I'll do my best to make the fix available in the next release.

**Comment by marcelveldt** [comment]
Can you please give version 2022.7 beta 1 a try ?
I think I fixed this one today as I revamped the buffering. Thanks!

**Comment by escoand** [comment]
Updated and testing.

**Comment by escoand** [comment]
Yesterday I heard multiple albums without the issue. It seems you fixed the problem. Thanks.
