### ISSUE TITLE
Not really an issue

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#60]
First my compliments for this great initiative! I was searching for a solution like this for a long time. That said I plumbed several items together to be able to cast Spotify playlists to any Chromecast. 
Before installing music assistant, I would like to understand what are prerequisites and what needs to be replaced.
So I installed:
- the official Spotify integration. Still Needed for music assistant, or will it conflict? 
- On top of that I installed the HACS SpotCast and Spotify playlist card. These become obsoleted I guess.
Looking forward to start using your solution 🥳

**Comment by marcelveldt** [comment]
1) Spotify integration in HA, not needed but it will not conflict.You can have both if you want.
2) Same as above, no longer needed but you can have both ways.

This project is aimed to make it easy to cast your favorite music to every player in your house, without all the hassle. Just select music, select a player and GO

**Comment by erkr** [comment]
That is really good news, it implies I can keep the plumbing in place till I have music assistant fully working 😎
I'm going to install it right away 👍

**Comment by erkr** [comment]
I think it is nice to mention this Independence in your readme:
> Spotify integration in HA, not needed but it will not conflict.You can have both if you want.

It really helped me to give it a try :-)
