### ISSUE TITLE
Deprecation Warnings in 2022.7.0 for the Number Component  

### ISSUE THREAD

**Issue by jweston2112** [music-assistant/hass-music-assistant#600]
### What version of Music Assistant has the issue?

2022.6.10

### The problem

Receiving Deprecation Warnings in the Logs

Logger: homeassistant.components.number
Source: components/number/__init__.py:462
Integration: Number (documentation, issues)
First occurred: 3:21:41 AM (6 occurrences)
Last logged: 3:21:41 AM

Entity None (<class 'custom_components.mass.number.CrossfadeDurationEntity'>) is using deprecated NumberEntity features which will be unsupported from Home Assistant Core 2022.10, please report it to the custom component author.
Entity None (<class 'custom_components.mass.number.VolumeNormalizationTargetEntity'>) is using deprecated NumberEntity features which will be unsupported from Home Assistant Core 2022.10, please report it to the custom component author.

### How to reproduce

It just shows up in the log on Core Restart

### Relevant log output

Logger: homeassistant.components.number
Source: components/number/__init__.py:462
Integration: Number (documentation, issues)
First occurred: 3:21:41 AM (6 occurrences)
Last logged: 3:21:41 AM

Entity None (<class 'custom_components.mass.number.CrossfadeDurationEntity'>) is using deprecated NumberEntity features which will be unsupported from Home Assistant Core 2022.10, please report it to the custom component author.
Entity None (<class 'custom_components.mass.number.VolumeNormalizationTargetEntity'>) is using deprecated NumberEntity features which will be unsupported from Home Assistant Core 2022.10, please report it to the custom component author.

### What version of Home Assistant Core are your running

2022.7.0

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by marcelveldt** [comment]
This is fixed in the 2022.7 version of MA of which a first beta has been released yesterday.

**Comment by jweston2112** [comment]
Guess I should have looked in Releases... Great software BTW... Thank You!
