### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '2005-06-14'

### ISSUE THREAD

**Issue by vk2him** [music-assistant/hass-music-assistant#601]
### What version of Music Assistant has the issue?

2022.7 Beta 0

### The problem

During the initial scan of the db after upgrading to 2022.7 Beta 0 I get errors in the log

### How to reproduce

See above

### Relevant log output

Logger: music_assistant.music.file
Source: /usr/local/lib/python3.10/site-packages/music_assistant/music_providers/filesystem.py:199
First occurred: 10:24:35 AM (26 occurrences)
Last logged: 10:24:38 AM

Error processing /media/nvr/The Eagles/Farewell Tour 1/Eagles - Farewell I Tour- Live from Melbourne - Hole in the World.m4a - invalid literal for int() with base 10: '2005-06-14'
Error processing /media/nvr/The Eagles/Farewell Tour 1/Eagles - Farewell I Tour- Live from Melbourne - Take It to the Limit.m4a - invalid literal for int() with base 10: '2005-06-14'
Error processing /media/nvr/The Eagles/Farewell Tour 1/Eagles - Farewell I Tour- Live from Melbourne - Walk Away.m4a - invalid literal for int() with base 10: '2005-06-14'
Error processing /media/nvr/The Eagles/Farewell Tour 1/Eagles - Farewell I Tour- Live from Melbourne - Sunset Grill.m4a - invalid literal for int() with base 10: '2005-06-14'
Error processing /media/nvr/The Eagles/Farewell Tour 1/Eagles - Farewell I Tour- Live from Melbourne - You Belong to the City.m4a - invalid literal for int() with base 10: '2005-06-14'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/filesystem.py", line 190, in sync_library
    if track := await self._parse_track(entry.path):
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/filesystem.py", line 573, in _parse_track
    track.album.year = tags.year
  File "/usr/local/lib/python3.10/site-packages/music_assistant/helpers/tags.py", line 105, in year
    return int(tag)
ValueError: invalid literal for int() with base 10: '2005-06-14'

### What version of Home Assistant Core are your running

latest

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Windows

**Comment by erkr** [comment]
Are you running on the latest core 2022.7. Beta, or the latest stable 2022.6.7?

**Comment by marcelveldt** [comment]
This one is fixed in MA 2022.7.0 beta 1
