### ISSUE TITLE
YouTube Music - Artists, Albums, Tracks are limited to most recent 25 items added to library

### ISSUE THREAD

**Issue by Backslashh** [music-assistant/hass-music-assistant#608]
### What version of Music Assistant has the issue?

2022.7.0b1

### The problem

Browsing the Artists, Albums, Tracks sections of Music Assistant only returns most recent 25 items added to library.

### How to reproduce

Configure YouTube Music integration
Open Music Assistant and browse the Artist/Album/Tracks libraries
Only the latest 25 "added to library" items are returned.

### What version of Home Assistant Core are your running

2022.7

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by MarvinSchenkel** [comment]
Good find! Will pick this up for the next beta release :)

**Comment by MarvinSchenkel** [comment]
Yep, fixed in Beta 4 :). Please report a new issue if you encounter this bug again.
