### ISSUE TITLE
All metatdata for local media missing after upgrade to  2022.7.0b1

### ISSUE THREAD

**Issue by FrankJaco** [music-assistant/hass-music-assistant#614]
### What version of Music Assistant has the issue?

 2022.7.0b1

### The problem

I upgraded MA to 2022.7.0b1 this morning. I had ~5000 tracks / ~250 artists loaded locally. When looking in the main MA gui (choosing Music Assistant in the left pane), no tracks, albums or artists are present.  If I browse the filesystem via MA all of the tracks/artists are still there and even playable.

If I go to the HA Media gui (choosing "Media" in the left pane), then choose MA from there, an "unknown error" is displayed when clicking on Artists/Albums/Tracks/Radio Stations.

### How to reproduce

Fully reproducible.

### Relevant log output

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/mass/media_source.py:240
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 7:35:45 AM (4 occurrences)
Last logged: 7:48:24 AM

[140603368985968] Error handling message: Unknown error (unknown_error)
[140603369697920] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 1218, in websocket_browse_media
    payload = await player.async_browse_media(media_content_type, media_content_id)
  File "/usr/src/homeassistant/homeassistant/components/cast/media_player.py", line 620, in async_browse_media
    return await media_source.async_browse_media(
  File "/usr/src/homeassistant/homeassistant/components/media_source/__init__.py", line 112, in async_browse_media
    item = await _get_media_item(hass, media_content_id, None).async_browse()
  File "/usr/src/homeassistant/homeassistant/components/media_source/models.py", line 86, in async_browse
    return await self.async_media_source().async_browse_media(self)
  File "/config/custom_components/mass/media_source.py", line 133, in async_browse_media
    return await self._build_artists_listing(mass)
  File "/config/custom_components/mass/media_source.py", line 240, in _build_artists_listing
    for artist in await mass.music.artists.library()
AttributeError: 'ArtistsController' object has no attribute 'library'

### Additional information

Using Samba, I see the MA database file in /Config.  It is about  8K in size.   I haven't done so yet, but my next troubleshooting step would be to delete the MA database with the hope that it will then be rebuilt correctly. Or possibly a complete removal of MA, then a re-install.  But I figured I would see if there was info that you might want prior to taking the brute-force method.

fj

### What version of Home Assistant Core are your running

2022.7.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by marcelveldt** [comment]
Please read the release notes...
I placed a note in there that in this beta:
a) The entire collection gets rebuilt due to parser changes
b) Filesystem items are no longer added to the favorites by default

Just click the "heart" button on top of the listings to toggle between library and non library.
If you want the old behavior back, simply do a CTRL-A (select all) and choose "Add to library"

I will make this even more clear in the final release notes on stable release...

**Comment by marcelveldt** [comment]
Fix available in the 2022.7 release!
Please reopen (or create a new issue) if you still may experience issues. Thanks!
