### ISSUE TITLE
Issue with character encoding.  Problems with letters such as é,í,ó,á etc. 

### ISSUE THREAD

**Issue by digitaldarragh** [music-assistant/hass-music-assistant#619]
### What version of Music Assistant has the issue?

2022.6.10

### The problem

The following actions fail when file names contain characters such as á,é,í,ó,ú. Adding music to a queue, adding music to a playlist, adding music to play next. Also, when reading a playlist, only tracks up to the line with a file name containing one of these letters are read by Music Assistant. 

For example in a playlist, only the first two items are added. Because there is an accented character on the third line, no further lines in this playlist are processed. 

/media/nas_music/Stockton's Wing/Stockton's Wing Live - Take One/04 The Chicago Set.wav
/media/nas_music/Kila/Luna Park/05-AudioTrack 05.wav
/media/nas_music/Compilations/Éistigí_ The Essential Traditional Irish/2-10 James Brown's March, Noon Lassi.wav

### How to reproduce

Try adding a playlist with files that contain accented characters such as á,é,í,ó or ú. 

### What version of Home Assistant Core are your running

2022.7.0

### What type of installation are you running?

Home Assistant Core

### On what type of hardware are you running?

Raspberry Pi

**Comment by marcelveldt** [comment]
I think this is related to the samba implementation / network mount.
I have several tracks with unicode characters and it all works fine. The only times I hear about this is, is from people using a mounted network drive...

I have some testfiles on my disk with all sorts of strange characters as test.
All works...

Can you check your HA logs ?If I'm right you will see some "file not found" errors in there for these files ?

**Comment by erkr** [comment]
See also related issue #542

**Comment by digitaldarragh** [comment]
I don't actually see any relevant logs. But here's everything related to Music Assistant: 

```
Logger: music_assistant.music.file
Source: /usr/local/lib/python3.10/site-packages/music_assistant/music_providers/filesystem.py:566
First occurred: 1:26:27 PM (26 occurrences)
Last logged: 1:26:34 PM

/media/nas_music/Alan Kelly Gang/Small Towns and Famous Nights/08 Birdmaker.wav is missing ID3 tag [albumartist], using Various Artists as fallback
/media/nas_music/Alan Kelly Gang/Small Towns and Famous Nights/09 Dawn Jigs.wav is missing ID3 tag [albumartist], using Various Artists as fallback
/media/nas_music/Alan Kelly Gang/Small Towns and Famous Nights/10 Journeys End.wav is missing ID3 tag [albumartist], using Various Artists as fallback
/media/nas_music/Alan Kelly Gang/Small Towns and Famous Nights/11 Lollie's Waltz.wav is missing ID3 tag [albumartist], using Various Artists as fallback
/media/nas_music/Zoë Conway/The Horse's Tale/01 Sport - Petticoat Loose.wav is missing ID3 tag [albumartist], using Various Artists as fallback



Logger: music_assistant.music.file
Source: /usr/local/lib/python3.10/site-packages/music_assistant/music_providers/filesystem.py:566
First occurred: 1:18:47 PM (2 occurrences)
Last logged: 1:18:47 PM

/media/nas_music/Compilations/Celtic Treasure II - The Living Legacy o/01 The Clergy's Lamentation_Separati.m4a is missing ID3 tag [albumartist], using Various Artists as fallback

Logger: music_assistant.music
Source: /usr/local/lib/python3.10/site-packages/music_assistant/controllers/music/__init__.py:121
First occurred: 1:18:47 PM (2 occurrences)
Last logged: 1:18:49 PM

Provider ProviderType.DATABASE is not available


Logger: music_assistant.metadata
Source: /usr/local/lib/python3.10/site-packages/music_assistant/controllers/metadata/__init__.py:160
First occurred: 1:19:19 PM (1 occurrences)
Last logged: 1:19:19 PM

Unable to get musicbrainz ID for artist Various Artists !
```

**Comment by erkr** [comment]
@marcelveldt 
I think there are two issues here:
- a samba issue, @digitaldarragh can try if these files work locally, or replace the Unicode character with normal ASCII
- a stop queue to the playlist issue when a file in the list can not be read. There MA should skip the tracks not stop queueing
