### ISSUE TITLE
local media file name parsing error

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#621]
### What version of Music Assistant has the issue?

2022.7.0b2

### The problem

There was a parsing error while MA scanned my chaotic and badly structured local collection

### How to reproduce

See the  log for the file name that failed

### Relevant log output

``` 
Logger: music_assistant.music.file
Source: /usr/local/lib/python3.10/site-packages/music_assistant/music_providers/filesystem.py:199 
First occurred: 19:55:08 (1 occurrences) 
Last logged: 19:55:08

Error processing /media/MP3_normalized/Albums/KOtic/Indestructable/01 - - 01 - Falling.mp3 - invalid literal for int() with base 10: 'rigi'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/filesystem.py", line 190, in sync_library
    if track := await self._parse_track(entry.path):
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/filesystem.py", line 573, in _parse_track
    track.album.year = tags.year
  File "/usr/local/lib/python3.10/site-packages/music_assistant/helpers/tags.py", line 105, in year
    return int(tag.split("-")[0])
ValueError: invalid literal for int() with base 10: 'rigi'
``` 

### What version of Home Assistant Core are your running

2022.7.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by marcelveldt** [comment]
This is not a bug but something for you to fix. You have a faulty tag in that file and MA is friendly enough to tell you that ;-)

**Comment by marcelveldt** [comment]
Looks like the "date" tag contains some non-date value

**Comment by erkr** [comment]
I don't mind to fix, but I made the issue as all other scan issues are warnings, this was an error

**Comment by marcelveldt** [comment]
No, a date tag/field is filled with the word 'rigi' so the code is right to crash on that.
It logs the error and skips the file. I'll do my best to make the errors more readable but the error is 100% correct.

**Comment by erkr** [comment]
Yea this issue is only about the handling, the file is wrong and I will fix that👍
