### ISSUE TITLE
browsing and clicking folders duplicate the names of the source folder.

### ISSUE THREAD

**Issue by Symbiot78** [music-assistant/hass-music-assistant#623]
### What version of Music Assistant has the issue?

2022.7.0b2

### The problem

If I browse a source.. and click the same folder multiple times MA will append the dir over and over and over again.

![Skærmbillede 2022-07-08 232841](https://user-images.githubusercontent.com/3314249/178072850-0d96ed9b-c293-4627-a7bb-23dc7508717b.png)

same on local filesystem.. of course you cannot click the same folder over and over again.. unless you do it before it manages to load the content of a folder :
![Skærmbillede 2022-07-08 232942](https://user-images.githubusercontent.com/3314249/178073003-34238499-c952-4304-a77d-f908a2a5ab62.png)
)

### How to reproduce

browse.. quickly in filesystem or take your time in youtube

### Relevant log output

none

### What version of Home Assistant Core are your running

2022.7.0

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Linux

**Comment by erkr** [comment]
Yes, I need to really tap quickly. And it reproduces in beta 3 As well

**Comment by OzGav** [comment]
Just tried this and couldn't replicate it. Has it been fixed?

**Comment by marcelveldt** [comment]
Yes it has been fixed

**Comment by erkr** [comment]
I didn't succeed to replicate in 2022. 7.0
