### ISSUE TITLE
YT error: Could not determine integrated loudness of ytmusic

### ISSUE THREAD

**Issue by vk2him** [music-assistant/hass-music-assistant#638]
### What version of Music Assistant has the issue?

2022.7.0.b3

### The problem

When Volume normalisation is enabled I attempted to pay this YT "video" https://music.youtube.com/watch?v=Hvqgb1D6Opw&feature=share

It failed with the following error in logs. If I turn off Volume normalisation it works fine 

### How to reproduce

See above

### Relevant log output

Logger: music_assistant.helpers.audio
Source: /usr/local/lib/python3.10/site-packages/music_assistant/helpers/audio.py:221
First occurred: 9:50:38 AM (1 occurrences)
Last logged: 9:50:38 AM

Could not determine integrated loudness of ytmusic://track/Hvqgb1D6Opw - ffmpeg version 5.0.1 Copyright (c) 2000-2022 the FFmpeg developers built with gcc 11.2.1 (Alpine 11.2.1_git20220219) 20220219 configuration: --prefix=/usr --enable-avfilter --enable-gnutls --enable-gpl --enable-libass --enable-libmp3lame --enable-libpulse --enable-libvorbis --enable-libvpx --enable-libxvid --enable-libx264 --enable-libx265 --enable-libtheora --enable-libv4l2 --enable-libdav1d --enable-lto --enable-postproc --enable-pic --enable-pthreads --enable-shared --enable-libxcb --enable-librist --enable-libsrt --enable-libssh --enable-libvidstab --disable-stripping --disable-static --disable-librtmp --enable-libaom --enable-libopus --enable-libsoxr --enable-libwebp --enable-vaapi --enable-vdpau --enable-vulkan --enable-libdrm --disable-debug libavutil 57. 17.100 / 57. 17.100 libavcodec 59. 18.100 / 59. 18.100 libavformat 59. 16.100 / 59. 16.100 libavdevice 59. 4.100 / 59. 4.100 libavfilter 8. 24.100 / 8. 24.100 libswscale 6. 4.100 / 6. 4.100 libswresample 4. 3.100 / 4. 3.100 libpostproc 56. 3.100 / 56. 3.100 pipe:: Invalid data found when processing input

### What version of Home Assistant Core are your running

2022.7.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Windows

**Comment by vk2him** [comment]
No Marcel - the track didn't play until I turned off normalisation

**Comment by MarvinSchenkel** [comment]
Could you retest this please with the latest beta6?

**Comment by vk2him** [comment]
Yes this is fixed - many thanks!
