### ISSUE TITLE
Stuck at "Please wait while Music Assistant is being setup"

### ISSUE THREAD

**Issue by Stooovie** [music-assistant/hass-music-assistant#65]
Tried multiple times, HA 2022.5.2 on Rpi4 (32bit). Stuck on adding the integration.  No movement for 10+ minutes. Nothing in log so far.

**Comment by marcelveldt** [comment]
I think you should wait if that dialog is displayed, the dependencies are installed by HA.
Maybe there are no prebuilt packages available as you're running 32bits instead of the default/recommended 64 bits

**Comment by Stooovie** [comment]
It worked after three restarts. Now all I'm getting is a red exclamation mark and "Retrying setup: 'NoneType' object is not subscriptable". Any clue? Thanks.

**Comment by marcelveldt** [comment]
I'm already looking into that... https://github.com/music-assistant/hass-music-assistant/issues/64

**Comment by marcelveldt** [comment]
I have released version 1.0.8 just now which has the fix for this issue. Thanks!

**Comment by Stooovie** [comment]
It does. BTW thanks for a very, very cool addition to HA! I would prefer a more prominent (more exposed) Search functionality and adding network shares with music files but even this is very cool, much better than the somewhat abandoned media functionality of HA.
