### ISSUE TITLE
Compatibility with HA 2022.8 (dev)

### ISSUE THREAD

**Issue by Mariusthvdb** [music-assistant/hass-music-assistant#652]
### What version of Music Assistant has the issue?

2022.7.0b3

### The problem

<img width="335" alt="Schermafbeelding 2022-07-12 om 18 43 46" src="https://user-images.githubusercontent.com/33354141/178547642-690c56ca-756d-4b40-a5fa-03848d09f9dd.png">

no listed players

### How to reproduce

not sure, and tbh, I didnt play with MA for a while. so noticed only now
while having the ip ban going on

### Additional information

seeing a lot of these lately, and wondering is MA causes this:

![91ffa6c8c766dc2d5ea0b45c4c8b6254e86cf348_2_460x1000](https://user-images.githubusercontent.com/33354141/178547854-046243da-6831-435a-9ba6-2ea493cc62ec.jpeg)

### What version of Home Assistant Core are your running

 2022.8.0.dev20220712

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by Mariusthvdb** [comment]
for comparisons sake, this is a section in the Media tab:
<img width="369" alt="Schermafbeelding 2022-07-12 om 22 08 21" src="https://user-images.githubusercontent.com/33354141/178585533-6408de50-ee7a-4ddd-95f5-9bbc5bb7954f.png">

MA players showing with the object_id..?

**Comment by marcelveldt** [comment]
maybe an issue on current dev ?

**Comment by Mariusthvdb** [comment]
Yeah, who knows.. that’s why I posted the screen of the Media tab indicating the players are known to the system.

btw the numbers on the buttons for Artsts/Albums/playlists etc are gone too. Is that correct? Or am I suffering a major Frontend collapse….

**Comment by erkr** [comment]
In the 2022.7 betas, the numbers where removed. Not your front end😅

**Comment by Mariusthvdb** [comment]
great, thx for confirming

yet, it leaves me with the empty players list. I rechecked, after todays dev nightly, and the issue remains. Also checked the first config flow panel where we configure the player, and that looks all good, all players there, with their name (and not like before with their object_id)

Could it have been that fix introducing this new issue?

**Comment by marcelveldt** [comment]
Numbers are gone because they caused too much confusion (favorite vs non favorite listings)...

This sounds like an issue introduced in HA dev. I'll check this later today on my dev machine.

**Comment by Mariusthvdb** [comment]
more info:
I handt checked the devices in the integration panel yet, because the initial card showed the correct number of devices, and no error.

Decided to do so just now, and lo and behold, this is what I see on most players:

no name set
<img width="862" alt="Schermafbeelding 2022-07-15 om 08 41 05" src="https://user-images.githubusercontent.com/33354141/179166598-2b86b895-b40b-417d-95e0-d032a43874fb.png">

details:


<img width="837" alt="Schermafbeelding 2022-07-15 om 08 40 56" src="https://user-images.githubusercontent.com/33354141/179166668-6707a10d-0a6a-4c79-886e-f414133905b4.png">

<img width="605" alt="Schermafbeelding 2022-07-15 om 08 43 57" src="https://user-images.githubusercontent.com/33354141/179166785-7f0beb4b-d2af-4952-8c86-d80dce05ce4c.png">

I deleted all payers and added the library player back , and still the same. Only correct thing is the entity_id of the player.

really strange.

**Comment by marcelveldt** [comment]
This is caused by all kind of changes that are being worked on in HA dev.
I strongly suggest you to not run your production/family system on the HA dev version and instead have your "play setup" to testdrive the HA dev versions. In this case there's a breaking change. The change in HA dev breaks MA (again).

**Comment by Mariusthvdb** [comment]
ok, figured as much. As long as you recognize the issue ;-=)

thanks Marcel. will stop posting here then....
that is, until the next beta ;-)

**Comment by marcelveldt** [comment]
2022.8 beta 0 has been released, compatible with HA 2022.8

**Comment by Mariusthvdb** [comment]
Confirm all my players are back, and all library items  too!
