### ISSUE TITLE
Unknown music duration

### ISSUE THREAD

**Issue by OzGav** [music-assistant/hass-music-assistant#655]
### What version of Music Assistant has the issue?

2022.7.b4

### The problem

This isn’t MA’s fault but perhaps it could be allowed to handle it. The issue is that for some reason the coded duration on some tracks that I ripped from music DVD are showing a duration of ?:?? in Picard and I can’t change it. Googling suggests this value might be calculated and that is why Picard is not allowed to modify it. 

What are your thoughts about adding a catch for this situation and maybe just setting the value to 0?

### How to reproduce

Have a track in the DB with a duration of ?:??

### Relevant log output

Logger: music_assistant.music.file
Source: /usr/local/lib/python3.10/site-packages/music_assistant/music_providers/filesystem.py:199 
First occurred: 3:39:48 PM (11 occurrences) 
Last logged: 3:39:56 PM

Error processing /media/nasMusic/U2/Live From Chicago 2005/03. U2 - Elevation (Live from Chicago 2005).flac - unsupported operand type(s) for -: 'int' and 'NoneType'
Error processing /media/nasMusic/U2/Live From Chicago 2005/12. U2 - Sunday Bloody Sunday (Live from Chiacgo 2005).flac - unsupported operand type(s) for -: 'int' and 'NoneType'
Error processing /media/nasMusic/U2/Live From Chicago 2005/18. U2 - One (Live from Chicago 2005).flac - unsupported operand type(s) for -: 'int' and 'NoneType'
Error processing /media/nasMusic/U2/Live From Chicago 2005/07. U2 - New Years Day (Live from Chicago 2005).flac - unsupported operand type(s) for -: 'int' and 'NoneType'
Error processing /media/nasMusic/U2/Live From Chicago 2005/19. U2 - Zoo Station (Live from Chicago 2005).flac - unsupported operand type(s) for -: 'int' and 'NoneType'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/filesystem.py", line 192, in sync_library
    await self.mass.music.tracks.add_db_item(track)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/music/tracks.py", line 133, in add_db_item
    if compare_track(row_track, item):
  File "/usr/local/lib/python3.10/site-packages/music_assistant/helpers/compare.py", line 214, in compare_track
    abs(left_track.duration - right_track.duration) <= 2
TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'

### What version of Home Assistant Core are your running

2022.7.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by marcelveldt** [comment]
1) I will fix the code so that it can handle a missing duration (which will fix the error logged above).

2) Duration is no tag in music files but its calculated from the audio frames. If you see this issue, the only way to solve it is to recreate the file. The easiest way is with ffmpeg: 

```
ffmpeg -i input.flac -c:v copy -c:a flac output.flac
```

**Comment by OzGav** [comment]
Thanks Marcel I was trying to work out how to fix it. I will try that in a couple of days when I get home!

**Comment by marcelveldt** [comment]
please reopen if you still experience any issues
