### ISSUE TITLE
YouTube Music - My Supermix playlist not refreshing

### ISSUE THREAD

**Issue by Backslashh** [music-assistant/hass-music-assistant#657]
### What version of Music Assistant has the issue?

2022.7.0b5

### The problem

In the Youtube Music app, when you refresh your playlists, the `My Supermix` playlist is refreshed with new songs. 
When in Music Assistant, I would expect the same behaviour to happen when I `refresh` the My Supermix playlist item.

### How to reproduce

Open Music Assistant
Select Playlists
Select `My Supermix`
Note the songs in the list
Tap overflow menu (three dots)
Tap `Refresh item` under actions

### What version of Home Assistant Core are your running

2022.7.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by marcelveldt** [comment]
OK, refresh has another meaning here. Refresh in MA is "refresh the metadata" and in regular playlists this will actually force an update of the cache for playlist tracks.

In this case it seems you have some sort of dynamic playlist which contents magically change ?
We do not have support for it so I consider this a feature request.

Can you please create a feature request for this ?
Thanks!

**Comment by Backslashh** [comment]
It's not necessarily a "magic" playlist. haha. It's just the nature of the YouTube Music Mix playlists. They are constantly refreshing.
I know these playlists have a specific playlist ID that is the same regardless of who's account is logged in though.

If you login to YouTube Music and go to https://music.youtube.com/playlist?list=RDTMAK5uy_kset8DisdE7LSD4TNjEVvrKRTmG7a56sY You'll get to your own `My Supermix`

**Comment by Backslashh** [comment]
Okay,
I added a new song to an existing “regular” playlist, opened music assistant and got refresh on that playlist and the new track was NOT visible. 

So it looks like that refresh item button doesn’t work

**Comment by MarvinSchenkel** [comment]
@marcelveldt I think you fixed this right?

**Comment by marcelveldt** [comment]
Correct, fixed in next beta

**Comment by Backslashh** [comment]
Ah that’s amazing!
Thanks guys!

**Comment by Backslashh** [comment]
> Correct, fixed in next beta

Does this next beta also fix the fact that if you select a single song to play, it doesn’t keep playing songs similar to that one, like YouTube Music does?

If not, I’ll raise a feature request.

**Comment by MarvinSchenkel** [comment]
I guess this is radio functionality you are asking about? E.g. start a radio based on an album, playlist or song? This is something we are currently looking into, but feel free to open a feature request or start a discussion
