### ISSUE TITLE
Music assistant doesn't see albums

### ISSUE THREAD

**Issue by ovizii** [music-assistant/hass-music-assistant#660]
### What version of Music Assistant has the issue?

2022.7.0b1

### The problem

MA does not see the content of my local music

### How to reproduce

If I browse the local folder MA sees the content but if I go to artists, albums, tracks I see no content.

![image](https://user-images.githubusercontent.com/837902/178940884-d074aed2-eced-4c74-a904-38ecf8cd7c9a.png)

![image](https://user-images.githubusercontent.com/837902/178940992-05e2bb65-95b1-49e1-86d2-a340173f37a6.png)
(Also this doesn't seem sorted by any rule I can figure out)

![image](https://user-images.githubusercontent.com/837902/178941159-a59cce9c-5b4c-4411-be1a-6da1913e3590.png)

![image](https://user-images.githubusercontent.com/837902/178941259-208548fd-31ab-4f95-9696-a75423d3382c.png)

there is a button "add to library" - I don't think I am supposed to add each song to the library by hand?

### Relevant log output

  File "/config/custom_components/mass/media_source.py", line 135, in async_browse_media
    return await self._build_albums_listing(mass)
  File "/config/custom_components/mass/media_source.py", line 283, in _build_albums_listing
    for album in await mass.music.albums.library()
AttributeError: 'AlbumsController' object has no attribute 'library'

### Additional information

I think I am on HA OS. This is the output of the HA About page. Settings => System => Hardware just says: Virtual Machine ova

```
Home Assistant 2022.7.4
Supervisor 2022.07.0
Operating System 8.2
Frontend 20220707.0 - latest
```

### What version of Home Assistant Core are your running

2022.7.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by ovizii** [comment]
I updated MA to 2022.7.0b5 and the above error changed to 
![image](https://user-images.githubusercontent.com/837902/178943857-cada77bd-30c0-4e09-86ef-cfc62b21354b.png)

also, no more log errors but MA still doesn't see my local media except when browsing the filesystem (see screenshots above)

**Comment by marcelveldt** [comment]
Add some songs to your library and they will show up, the filter defaults to "in library" items only.
So either press CTRL-A to select all items and add them to the lib or leave the filter off

**Comment by ovizii** [comment]
At first, I was totally confused by your reply, but I seem to have it figured out, let me confirm with you.

I wasn't sure what filter you are referring to, then I found it. It seems to be this “heart” symbol:
![image](https://user-images.githubusercontent.com/837902/178957292-a569440b-59eb-44a6-960b-deb6bccf9bb3.png)

It looks like MA has indeed indexed all my music but to have to display inside the artist, album, and track sections I need to remove the “in library” filter? 

Alternatively, as you said, I could go to tracks, scroll to the very bottom, mark them all and add to library.

What would be the benefit o adding all my music to the library?

**Comment by ovizii** [comment]
figured out how to unselect, seems pretty unintuitive to me to have to click on the text "50 items selected"

![image](https://user-images.githubusercontent.com/837902/178958390-aad89832-d498-4392-852d-975e21f2aa54.png)

then you can unselect:
![image](https://user-images.githubusercontent.com/837902/178958519-05705c54-7db9-49a1-a211-269d3a6e7f50.png)


The question remains, what is the benefit of adding them to the library?

**Comment by marcelveldt** [comment]
The old behavior was to add all tracks to the library by default but that got people confused as in "hey, I just have a large collection and only some if it is favorite" so I changed the default behavior to not add everything to the library (which is more or less a favorites function). So if you want the old behavior back, just add everything to your favorites. Otherwise just use the filter. 

I made some notes about this in the release notes but nobody reads them haha.
When 2022.7 goes from beta to final I'll do my best to better inform about this in the UI and make the selection off by default.

**Comment by marcelveldt** [comment]
> figured out how to unselect, seems pretty unintuitive to me to have to click on the text "50 items selected"
yes there is a lot of work still needed in the UI to improve but only so much time....

> The question remains, what is the benefit of adding them to the library?
See above, use it as a favorites feature, just like with streaming providers

**Comment by marcelveldt** [comment]
OK, have fun and let me know once you run into some other error. The UI glitches are on my TODO anyway. At the moment I've just covered basics and some features are like MVP done and need improvements. But hey, that will keep us occupied for the next years :-)

**Comment by ovizii** [comment]
One last thing, I just saw something new in the error logs. If it's related, feel free to ask more questions if it is not, just ignore this please:

`2022-07-14 12:10:21 WARNING (MainThread) [homeassistant.helpers.frame] Detected integration that calls media_source.async_resolve_media without passing an entity_id. Please report issue for media_source using this method at homeassistant/components/media_source/__init__.py, line 138: report("calls media_source.async_resolve_media without passing an entity_id")`

**Comment by marcelveldt** [comment]
That is not from MA but from another media player implementation.
