### ISSUE TITLE
 'str' object has no attribute 'path'

### ISSUE THREAD

**Issue by OzGav** [music-assistant/hass-music-assistant#666]
### What version of Music Assistant has the issue?

2022.0.b6

### The problem

Updated to b6 and obseved this error in the logs. I have not interacted with MA at all since the reboot.

### How to reproduce

Not sure...

### Relevant log output

Logger: music_assistant
Source: /usr/local/lib/python3.10/site-packages/music_assistant/mass.py:245
First occurred: 10:47:18 AM (1 occurrences)
Last logged: 10:47:18 AM

Job [Library sync for provider Filesystem] failed with error 'str' object has no attribute 'path'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/filesystem.py", line 233, in sync_library
    await self._process_deletions(deleted_files)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/filesystem.py", line 242, in _process_deletions
    if "." not in file_path.path or file_path.path.startswith("."):
AttributeError: 'str' object has no attribute 'path'

### What version of Home Assistant Core are your running

2022.7.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by erkr** [comment]
@OzGav 
Didn't see this error anymore in the latest beta's. 
Same for you? If so we can close the issue

**Comment by OzGav** [comment]
yes looks fixed
