### ISSUE TITLE
Sidebar is duplicated when using browser-back inside Music Assistant

### ISSUE THREAD

**Issue by ezpl** [music-assistant/hass-music-assistant#667]
### What version of Music Assistant has the issue?

 2022.7.0b6

### The problem

The Home Assistant sidebar is shown several times when using the back button to navigate out of an album/artist/playlist view in Music Assistant.

![image](https://user-images.githubusercontent.com/30909027/179168773-e24a2175-16b5-457e-a95e-11dde4726cd3.png)

### How to reproduce

Click Album, use back-function in browser to get back to the main Music Assistant screen, click Album again

### What version of Home Assistant Core are your running

2022.07.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by marcelveldt** [comment]
This is a known issue and the whole reason why MA has its own back button. It is something to solve together with the HA frontend devs someday but its really low on the prio list and might even be impossible to fix.

**Comment by ezpl** [comment]
OK! Guess I should have read more thoroughly through the know issues list (?)
