### ISSUE TITLE
I didn't see Polish lang in MASS

### ISSUE THREAD

**Issue by LukaszP2** [music-assistant/hass-music-assistant#671]
### What version of Music Assistant has the issue?

2022.7.0b6

### The problem

I didn't see polish lang only emglish

### How to reproduce

Add some think :)

### What version of Home Assistant Core are your running

2022.7.0b2

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Linux

**Comment by marcelveldt** [comment]
Do you mean the MA interface itself ? Can you create a screenshot what you mean?

**Comment by LukaszP2** [comment]
![image](https://user-images.githubusercontent.com/44735995/179195842-5c204128-da3e-457e-8e5e-38d97b243a27.png)

**Comment by MarvinSchenkel** [comment]
We just released your translation as part of beta7. Could that be the issue?

**Comment by marcelveldt** [comment]
I've quickly looked at it and it seems there's an error in the Polish language file.

```
orjson.JSONDecodeError: expected `,` or `}` at line 81 column 7: line 81 column 7 (char 3707)
```

**Comment by LukaszP2** [comment]
> I've quickly looked at it and it seems there's an error in the Polish language file.
> 
> ```
> orjson.JSONDecodeError: expected `,` or `}` at line 81 column 7: line 81 column 7 (char 3707)
> ```

This is now OK, I upload good file for config. 
I'm talking about UI of MASS.

**Comment by LukaszP2** [comment]
![Zrzut ekranu 2022-07-16 115615](https://user-images.githubusercontent.com/44735995/179350063-45af6e87-748e-4b1c-b2c5-190744df4229.png)
I don't have any file in /translations/frontend. I check if I get ones more it will get in.

**Comment by marcelveldt** [comment]
translations get packaged into the release so you won't see them as such.
That said, I now see that I forgot to link the polish language file. Will be fixed in next release, thanks!

**Comment by LukaszP2** [comment]
still english inf frontend, in config there is polish - v2022.08b (HA and MASS)

**Comment by marcelveldt** [comment]
1) Clear your browser cache
2) Sometimes you need to set language to english forced and then back to another language

**Comment by LukaszP2** [comment]
second help, thx!
