### ISSUE TITLE
File Format Error when playing flac

### ISSUE THREAD

**Issue by vk2him** [music-assistant/hass-music-assistant#672]
### What version of Music Assistant has the issue?

2022beta5

### The problem

Commencing with beta 5, if I select flac on my Denon it fails and displays this in its status window

![Screen Shot 361](https://user-images.githubusercontent.com/22878629/179188031-e4f09edf-66b1-44ef-bfdf-b46119ccdbdd.jpg)

### How to reproduce

Play music with flac enabled for the entity

### Relevant log output

This error will sometimes be logged 

Logger: music_assistant.players.stream
Source: /usr/local/lib/python3.10/site-packages/music_assistant/controllers/streams.py:466
First occurred: 6:22:13 PM (1 occurrences)
Last logged: 6:22:13 PM

Abort: client(s) did not connect within 10 seconds.

### Additional information

It isn't fixed with Beta6

### What version of Home Assistant Core are your running

Supervisor 2022.07.0

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Windows

**Comment by erkr** [comment]
Hi @vk2him 
Don't own a Denon myself. If I recall correctly these players where supporting FLAC, right?
Best, 
Eric

**Comment by vk2him** [comment]
Hi Eric - yes the denon works with flac - MA worked with flac prior to beta4 - Marcel and I have been discussing on DM and I logged this issue so he could schedule. Thanks

**Comment by marcelveldt** [comment]
Can you please test this with beta9 ?
I've added back the previous method for streaming and introduced an advanced config setting to toggle between the various metadata modes as I've discovered that some settings work for some players and not for others

**Comment by vk2him** [comment]
Hi  Marcel - I can confirm it works 100% now !
1) The songs in the queue no longer scroll with either large or very small chunks selected. Towards the end of a track, the next song will appear, the timing depends on chunk size. This is excellent so thanks very much!!
2) flac works again without error .. I csn also play wav and mp3 but my amp doesn't support aac so that's fixed as well - thanks!!
