### ISSUE TITLE
Track titles and info scrambled on mobile

### ISSUE THREAD

**Issue by Mariusthvdb** [music-assistant/hass-music-assistant#674]
### What version of Music Assistant has the issue?

2022.7.0b7

### The problem

![0C6D8A9C-F778-42A4-A8C5-F35F922A32DE](https://user-images.githubusercontent.com/33354141/179238109-ae54e175-361e-4b54-879c-47047f8095da.png)

### How to reproduce

Click tab Tracks on mobile device

### Additional information

Desktop looks fine

### What version of Home Assistant Core are your running

2022.7.5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by erkr** [comment]
Hi @Mariusthvdb 
Hmm, looks perfectly fine on my iPhone XR, yours looks like an iPhone as well. So Please can you give some info on the phone and resolution.

**Comment by Mariusthvdb** [comment]
iPhone 11pro

This is album from Spotify. You can probably find it yourself

**Comment by marcelveldt** [comment]
Ah yes, this is opera or classic right ? Lots of cooperating artists/performers... I will have to limit the number of performers in this case

**Comment by Mariusthvdb** [comment]
yes, and Spotify Marquee's the track I the play bar:

**Comment by Mariusthvdb** [comment]
guess track titles are most important, if space is at stake.

**Comment by marcelveldt** [comment]
> yes, and Spotify Marquee's the track in the play bar:

nice detail indeed for the limited space. I'll see if I can do something like that too

**Comment by marcelveldt** [comment]
this should be fixed in the latest 2022.7 beta 8

**Comment by marcelveldt** [comment]
this issue should be fixed in recent (beta) version. please reopen if you still have issues.
