### ISSUE TITLE
Playing an album (local media) using checkbox does not play in correct track order

### ISSUE THREAD

**Issue by fernplant** [music-assistant/hass-music-assistant#678]
### What version of Music Assistant has the issue?

2022.7.0b7

### The problem

Playing an album (local media) using checkbox does not play in correct track order

### How to reproduce

To recreate:
From Music Assistant main page, click 'Artists', select an artist, click 'Albums', click album art to check checkbox, click 'Play'

I would expect this to begin the album and play the first track but it doesnt. It appears the track it plays is the first track in the 'Tracks' view on the 'Artist' page (which is ordered by 'Recently added' by default

### What version of Home Assistant Core are your running

2022.7.5

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Raspberry Pi

**Comment by marcelveldt** [comment]
You found a workflow that never crossed my mind :-)
Selecting items is more or less meant for doing actions but i guess you can also use it this way.
The button above is linked to whatever "main" details you're viewing, so when watching an Artist, play will play the top tracks of that artist and so on.

I consider your observation not as big but as small improvement/request.
Leave it open here as it is pretty small for me to fix so I can pick it up sometime in between.

**Comment by fernplant** [comment]
Im interested in having as few clicks as possible to start an album and stumbled on this method

Thanks very much for all your work on this great project; I am very impressed!

**Comment by marcelveldt** [comment]
I've enhanced the UI a bit to make it more clear. This change is available in the 2022.7 release
