### ISSUE TITLE
Stream from an url from playlist not working anymore

### ISSUE THREAD

**Issue by dazWiLLiE** [music-assistant/hass-music-assistant#682]
### What version of Music Assistant has the issue?

2022.7.0b7

### The problem

Since the latest update, I can no longer stream from an url from my custom playlist.

It just skips to the next item in the queue. I've verified the urls to be working.

### How to reproduce

Create M3U, add url, sync MA, play stream.

### Relevant log output

[homeassistant.components.stream] Stream error on url://radio//http://......

### What version of Home Assistant Core are your running

2022.7.5

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by jazzyisj** [comment]
I am still able to stream from an M3U playlist on 2022.7.0b7.

Have you tried substituting known working URL's or tried the URL directly in a browser to verify it's online?

**Comment by vk2him** [comment]
I'm also seeing this - my music is on a network location if that matters - I get this error in logs

Logger: music_assistant.music.file
Source: /usr/local/lib/python3.10/site-packages/music_assistant/music_providers/filesystem.py:352
First occurred: 9:52:45 AM (40 occurrences)
Last logged: 9:53:06 AM

Could not parse uri/file 16 - Born In The U.S.A..flac to track: Not a valid Music Assistant uri: 16 - Born In The U.S.A..flac
Could not parse uri/file 17 - I'm Goin' Down.flac to track: Not a valid Music Assistant uri: 17 - I'm Goin' Down.flac
Could not parse uri/file 18 - Dancing In The Dark.flac to track: Not a valid Music Assistant uri: 18 - Dancing In The Dark.flac
Could not parse uri/file 19 - One Step Up.flac to track: Not a valid Music Assistant uri: 19 - One Step Up.flac
Could not parse uri/file 20 - Tunnel Of Love.flac to track: Not a valid Music Assistant uri: 20 - Tunnel Of Love.flac

**Comment by dazWiLLiE** [comment]
@jazzyisj yes, as I wrote above, "I've verified the urls to be working." They play fine in VLC.

And the M3U is the same as before when it worked.

**Comment by dazWiLLiE** [comment]
Works again in 2022.7.0b8.
