### ISSUE TITLE
Speaker Group - no playback

### ISSUE THREAD

**Issue by tstill88** [music-assistant/hass-music-assistant#684]
### What version of Music Assistant has the issue?

2022.7.0b7

### The problem

I have created a group using HA Helper. Ive added two M5 Atom Speaker kit devices to a media player group type called test. Ive then added test as a playback device for MA, however when i pick to use this playback wont start. I can see the play button briefly flash to pause as it attempts to start but immediately stops. 

Im not quite sure if this is a MA issue or something about the ESPHome FW / setup

Playback works fine when i choose a speaker individually.

### How to reproduce

Can be reproduced by adding 2 M5 Atom / Echo speaker devices to a media playback group.

### Relevant log output

I can see the URL is sent to each speaker but playback isnt starting.

[D][media_player:059]: 'M5Stack Atom Speaker Kit' - Setting
[D][media_player:066]:   Media URL: http://192.168.0.6:8095/c3febd4e9a6e48e79c54ac105edd1f19.flac

### What version of Home Assistant Core are your running

2022.7.5

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Alternative

**Comment by marcelveldt** [comment]
Looks like its switching to FLAC media type which is not supported on ESPHome.
Thing to try/test:

HA settings --> Integrations --> Music Assistant --> Devices --> Pick the device created for your group
Make sure that all settings are visible/enabled. Set the config setting "stream type" to MP3.

**Comment by erkr** [comment]
@tstill88 
We are looking forward to hear if the setting pointed out by Marcel solved your issue.

**Comment by marcelveldt** [comment]
I've added a small guard in the code to default to MP3, available in next version.
In the meanwhile just set the default to MP3 yourself.
