### ISSUE TITLE
Cannot find media files on directory

### ISSUE THREAD

**Issue by K3str3l** [music-assistant/hass-music-assistant#69]
What is the path structure required to find media files on disk? I keep getting message "Retrying setup: Setup failed of provider filesystem: Music Directory <path here> does not exist.
Do the files have to be located in the HA instance or can I play from Network?

**Comment by marcelveldt** [comment]
At this time only local files are possible. I'll do my best to add network support later.
So for example on HA OS, the path could be /media/musicdir

**Comment by K3str3l** [comment]
ok, thanks for the quick response - I had hoped I'd be able to play from a folder I have mounted locally to HA - even got exicited as your intergration took some time to "sync" - think it would work, but unfortunately it was empty!
Congratulations on the launch of your integration - 3 years - a lot of effort in this!
