### ISSUE TITLE
Browse broken 

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#693]
### What version of Music Assistant has the issue?

2022.7.0b7

### The problem

The new browse tab is broken. In the Root it displays the media providers, but the don’t open. After that, I have to tap back several times to get out of the browser menu. 
Not all other tabs have the expected content, and playback of playlists works

### How to reproduce

Navigate to browse

### Relevant log output

None

### Additional information

![FDC63B3B-A17E-4D58-987B-1B14AB84A66F](https://user-images.githubusercontent.com/4363599/179557856-24721092-33fd-4216-8d3c-3e4351f237ae.jpeg)

Tested with the companion app, on iOS. Tried to reset the browser cache.

### What version of Home Assistant Core are your running

2022.7.5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Same here

**Comment by erkr** [comment]
Fixed in beta 8
