### ISSUE TITLE
Ampersand ( & ) in filename creates errors in the database

### ISSUE THREAD

**Issue by FrankJaco** [music-assistant/hass-music-assistant#694]
### What version of Music Assistant has the issue?

 2022.7.0b7

### The problem

A folder that was created directly by MusicBrainz/Picard contains an ampersand ( & ) in its name.:  "Buckethead & Friends"
 Inside the folder is an Album/folder called "Enter the Chicken".This contains a few MP3 files.

MASS files the Album under an Artist "Friends" instead of "Buckethead and Friends".
It appears that MASS doesn't properly delimit the ampersand in its SQL.

![image](https://user-images.githubusercontent.com/79318542/179565478-9fed0b35-52eb-4cdb-b965-bf67328b69a0.png)

### How to reproduce

Create a structure as described above.

### What version of Home Assistant Core are your running

 2022.7.5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by marcelveldt** [comment]
It has nothing to do with delimiting but its actually splitting on the ampersand.
I will remove that part of code so it may only split on the MusicBrainz Picard default splitter semicolon. Didn't even realize that code was still there until your report so thanks :-)

**Comment by OzGav** [comment]
Probably @marcelveldt knows this but I see two entries in the DB. Example Hootie & the Blowfish has an artist "Hootie" and another "the Blowfish". They both have the same album attached but the second one has no tracks? Also this doesn't always happen I see a number of correct artists in my DB such as "Jay & the Americans"?

**Comment by OzGav** [comment]
hmmm....I believe I have been successful in deleting albums but when I selct and Artist and then go to the top right menu and select DELETE FROM DATABASE ...nothing  happens...Am I doing something wrong?

**Comment by marcelveldt** [comment]
> hmmm....I believe I have been successful in deleting albums but when I select an Artist and then go to the top right menu and select DELETE FROM DATABASE ...nothing happens...Am I doing something wrong?

yes... wait for beta 10 ;-)

**Comment by OzGav** [comment]
roger...

**Comment by OzGav** [comment]
Artist delete from database works and the artists are no longer getting split for me. The only thing I noticed was a FORCE FULL SYNC didn't seem to remove the split artists so I had to do that manually. Otherwise all seems good.

**Comment by marcelveldt** [comment]
Thanks for confirming. And yes, you will have to manually delete the wrongly split artists.
Please use the delete function in the UI for that and do not go deleting directly in the db because that will do a recursive delete.

**Comment by marcelveldt** [comment]
2022.7 has been released which includes the fix.
Please reopen (or create a new issue) if you still may experience issues. Thanks!
