### ISSUE TITLE
Playback to Volumio media players does not start.

### ISSUE THREAD

**Issue by JanNogga** [music-assistant/hass-music-assistant#696]
### What version of Music Assistant has the issue?

2022.7.0b7

### The problem

First off thanks for this great project! Now to the bug:
Attempting to start playback when targetting one or a group of Volumio media players does not have any effect. The music source is Spotify, and the Volumio devices all run at version 2.917.

### How to reproduce

Select a Volumio device as the player.
Attempt to start music playback.

### Relevant log output

Logger: homeassistant.components.websocket_api.http.connection
Source: components/volumio/media_player.py:264
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 3:16:58 PM (2 occurrences)
Last logged: 3:26:41 PM

[139668042259072] Error handling message: Unknown error (unknown_error)
[139667956496992] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/mass/websockets.py", line 106, in async_get_mass_func
    await orig_func(hass, connection, msg, mass)
  File "/config/custom_components/mass/websockets.py", line 1115, in websocket_play_media
    await player_queue.play_media(msg[MEDIA], msg[COMMAND])
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/player_queue.py", line 276, in play_media
    await self.insert(queue_items, 0, passive)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/player_queue.py", line 587, in insert
    return await self.load(queue_items, passive)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/player_queue.py", line 568, in load
    await self.play_index(0, passive=passive)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/player_queue.py", line 526, in play_index
    await self.player.play_url(stream.url)
  File "/config/custom_components/mass/player_controls.py", line 251, in play_url
    await self.entity.async_play_media(
  File "/usr/src/homeassistant/homeassistant/components/volumio/media_player.py", line 264, in async_play_media
    await self._volumio.replace_and_play(json.loads(media_id))
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### Additional information

Switching the playback device to an M5Stack Atom Echo works; the selected music immediately starts playing there.

### What version of Home Assistant Core are your running

2022.7.0

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

**Comment by JanNogga** [comment]
Quick update, I added the same devices as new media players using platform: mpd and their IPs as host:. Using those with Music Assistant works perfectly so far. So there is still a bug with Volumio, which is maybe even on the side of the Volumio integration, but mpd seems to present a fairly straightforward workaround.

**Comment by erkr** [comment]
Good to hear you found a work around for now

**Comment by erkr** [comment]
@JanNogga
Hi, are you able to play music to the media players that didn't work in MA (those offered by the volumio integration) via the standard media browser (e.g. local files or radio stations)?

**Comment by mkono87** [comment]
> 

I tried this but it seems I cant add it to music assistant.

**Comment by JanNogga** [comment]
I can't say for local files, but I just tested the standard radio stations and that worked for the media players provided by the Volumio integration.
Over two days of testing though, the aforementioned mpd workaround does not seem perfect anymore either, with speakers stutterting rarely individually and quite often when part of a speaker group. I don't really remember how I setup mpd though, as it has been a while, so this is just info for people with a similiar issue trying that workaround.
Back to the topic of Volumio; if you need me to run some further tests or are interested in particular logs, I am open to providing that.

**Comment by erkr** [comment]
Marcel is going to look into this issue. Some test support is always welcome

**Comment by JanNogga** [comment]
Sure, I'll gladly test it once 2022.7 is out, thanks for looking into it!

I'm 100% not a Volumio expert, but whenever I setup a new 'node' for media playback I just use an etcher to flash the image available at [https://updates.volumio.org/pi/volumio/2.917/volumio-2.917-2021-10-06-pi.img.zip](https://updates.volumio.org/pi/volumio/2.917/volumio-2.917-2021-10-06-pi.img.zip) to an SD card for a Raspberry Pi Zero W, but any other raspi should work as well. If you have something like that laying around it might be easier to use than Virtualbox.

**Comment by marcelveldt** [comment]
Fix available in the 2022.7 release!
Please reopen (or create a new issue) if you still may experience issues. Thanks!

**Comment by JanNogga** [comment]
Unfortunately I have to report that the situation is unchanged on my side for Volumio on 2022.7. 
However, mpd, especially using grouped speakers, seems much more stable so far. There is just some small desync between speakers, which I don't feel would be migitated by switching to Volumio, which I see more as a means to end to open local music playback nodes to snapcast, airplay etc via plugins anyhow. In that sense I would be fine keeping my setup this way (mpd) until something which might be a bit more 'in sync' pops ups, like maybe streaming to snapclients via Music Assistant. That said, feel free to point out when there have been further changes that might affect this, I'm always happy to test and get back to you on it.

**Comment by marcelveldt** [comment]
I managed to install Volumio in a test VM and fixed the playback. Patch available in 2022.7.1

BTW: If you're purely interested in networked clients for multiroom playback in combination with MusicAssistant, then Volumio is a bit overkill as it is in fact a media solution on its own. If you're solely interested in networked endpoints I suggest you to take a look at squeezelite and more specific the PiCorePlayer distro which works out of the box with the "slimproto" integration in HA.

**Comment by JanNogga** [comment]
I really appreciate that you went so far as to basically replicate my setup to fix this issue. I look forward to using it on 2022.7.1!

Also thanks for suggesting PiCorePlayer, which indeed might be better suited for what I need. I hadn't considered alternatives to Volumio so far, as I just immediately went with a variation of [the system described here by Burningstone91](https://github.com/Burningstone91/smart-home-setup#multiroom-audio=l). There are some other requirements beyond Home and Music Assistant, like being able to control individual speakers or groups of speakers using airplay or spotify directly from peoples phones. However, at first glance it seems PiCorePlayer offers plugins for all kinds of things as well. It is likely that I will switch over to that in the medium term.

**Comment by JanNogga** [comment]
Just commenting to confirm that Volumio now works (really well!) on my side on 2022.7.1. Switched over to using that over mpd for now, thank you!

**Comment by marcelveldt** [comment]
OK, great to hear!
And keep in mind piCorePlayer (or the ESP32 ready baked solutions from raspiaudio) running squeezelite as an alternative for just headless playback of audio from MA

**Comment by kuduacz** [comment]
hi. same here again. 
MA 2024.7.1.b0
HA docker 2024.7.4
volumio latest
![image](https://github.com/user-attachments/assets/dabb7719-3125-4af9-9ba6-1cb3b4e0195e)
