### ISSUE TITLE
fatal.... 'ActiveConnection' object has no attribute 'send_big_result'

### ISSUE THREAD

**Issue by Mariusthvdb** [music-assistant/hass-music-assistant#700]
### What version of Music Assistant has the issue?

2022.7.0b8

### The problem

as title. Nothing happening anymore. 
Aware MA is not yet ready for 2022.8 I had to check that because of other dependencies/fixes, no use fighting HA development in that regard.

MA had that issue before (and I reported here: players listed with the object id, and not name or entity_id), but MA would still play on 1 player, and see all DB correctly. It also did play some TTS notifications, (not sure if it still does, no notifications sent yet....)

Currently, nothing is showing in the frontend at all other than the main interface. All buttons remain empty , showing the cycling white line:

<img width="1061" alt="Schermafbeelding 2022-07-21 om 09 03 00" src="https://user-images.githubusercontent.com/33354141/180150836-9088ce8b-77c0-4bc9-a974-ca23152906f9.png">

### How to reproduce

not sure, I just installed the dev nightly, and the latest MA beta

### Relevant log output

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/mass/websockets.py:138 
Integration: Home Assistant WebSocket API (documentation, issues) 
First occurred: 08:59:33 (1 occurrences) 
Last logged: 08:59:33

[140328296696224] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/mass/websockets.py", line 111, in async_get_mass_func
    await orig_func(hass, connection, msg, mass)
  File "/config/custom_components/mass/websockets.py", line 138, in websocket_artists
    await connection.send_big_result(
AttributeError: 'ActiveConnection' object has no attribute 'send_big_result'

### What version of Home Assistant Core are your running

2022.8.0.dev20220721

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by marcelveldt** [comment]
Breaking change in 2022.8 dev.. I can't help with that until a first beta is out

**Comment by Mariusthvdb** [comment]
thx Marcel, beta is in a week.. ;-)

**Comment by jweston2112** [comment]
on BETA 2022.8.0b0 and I can confirm this happens to me on this version.

**Comment by marcelveldt** [comment]
> on BETA 2022.8.0b0 and I can confirm this happens to me on this version.

Beta 2022.8 of Music Assistant will be released within 2 hours so a little patience please

**Comment by marcelveldt** [comment]
2022.8 beta 0 has been released, compatible with HA 2022.8

**Comment by drthanwho** [comment]
This is still showing up on 2022.08.0b1. I even removed the integration and reinstalled the players. It happens every time I try to get into Artists/Playlists etc for Spotify. Only thing working is individually selecting one of the created music players and sending a notification or a radio station from HA's integration (not TuneIN)
```
2022-07-29 15:07:00.522 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140149467239072] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/mass/websockets.py", line 114, in async_get_mass_func
    await orig_func(hass, connection, msg, mass)
  File "/config/custom_components/mass/websockets.py", line 675, in websocket_radios
    await connection.send_big_result(
AttributeError: 'ActiveConnection' object has no attribute 'send_big_result'
```

**Comment by marcelveldt** [comment]
@drthanwho you need to install the 2022.8 beta version of Music Assistant too!

**Comment by drthanwho** [comment]
I have done that

**Comment by marcelveldt** [comment]
And restarted HA after that ?
If you run 2022.8 beta 0 of MA this error can simply not be there

**Comment by drthanwho** [comment]
I did click reinstall and selected the beta. And HA prompted me for a restart. But now manually going into the fold to look at the manifest.json I still see the old version being referenced. Will try reinstalling it again

**Comment by drthanwho** [comment]
OK seems the first reinstall hadn't taken. Now (of course) it works. Sorry for the bother 😪

**Comment by marcelveldt** [comment]
No problem, glad you solved it!
