### ISSUE TITLE
TTS error and long delay to e.g. resume

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#715]
### What version of Music Assistant has the issue?

2022.7.0

### The problem

Interrupting the music with a tts message has long delays and an error.
The delay before starting the announcement takes several seconds longer then before.
After the announcement, the delay was before this release ca 5 seconds, now the delay is around 25-30 seconds, before the music fades in. That delay is related to an timeout error

### How to reproduce

Initiate a TTS message via the media browser to a mass player (chromecast)

### Relevant log output

``` 
Logger: music_assistant.players
Source: /usr/local/lib/python3.10/site-packages/music_assistant/models/player_queue.py:369 
First occurred: 20:48:07 (2 occurrences) 
Last logged: 20:49:59

Error while playing announcement
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/player_queue.py", line 366, in play_announcement
    await self._wait_for_state(PlayerState.PLAYING, silence_item.item_id)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/player_queue.py", line 885, in _wait_for_state
    raise TimeoutError(f"Timeout while waiting on state(s) {state}")
TimeoutError: Timeout while waiting on state(s) (<PlayerState.PLAYING: 'playing'>,)
``` 

Possibly this warning is relevant as well:

``` 
Logger: music_assistant.players
Source: /usr/local/lib/python3.10/site-packages/music_assistant/models/player_queue.py:520 
First occurred: 20:47:43 (2 occurrences) 
Last logged: 20:49:35

Ignore queue command: An announcement is in progress
``` 
### Additional information
Logging is from two attempts

### What version of Home Assistant Core are your running

2022.7.6

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by marcelveldt** [comment]
Please note this as side effect on the google cast issue. Again, only cast has these issues.

**Comment by erkr** [comment]
Thanks, hard for me to pinpoint the root cause, but if it's in the cast's integration I understand.

**Comment by marcelveldt** [comment]
Yes, it's all connected and originating at the cast speakers. I have several speakers here throughout the house and only cast speakers have this issue.

**Comment by marcelveldt** [comment]
Let's use #713 as meta issue for the google cast issues and close this one.
