### ISSUE TITLE
Embedding Music Assistant into a dashboard via webpage and URL followed by opening in iOS device causes an error

### ISSUE THREAD

**Issue by liquidbear99** [music-assistant/hass-music-assistant#720]
### What version of Music Assistant has the issue?

2022.7.0

### The problem

Embedding Music Assistant into a webpage in a dashboard via and then opening the dashboard with the embedded Music Assistant on an iOS device causes an error.

### How to reproduce

Install Music Assistant
Add a "webpage" card to a dashboard and input the url: https://[ha-base-url]/lib/mass
Access the dashboard created in the iOS app
An error pops up saying "What host to connect to?"

### Relevant log output

N/A

### Additional information

Attempting method stated here: https://github.com/music-assistant/hass-music-assistant/discussions/594

### What version of Home Assistant Core are your running

2022.7.6

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by marcelveldt** [comment]
That is not an error but a question to you to enter the URL to homeassistant

**Comment by liquidbear99** [comment]
When I enter the URL to home assistant the URL does not save and you are prompted each time you access that dashboard page to reenter the URL. In addition, the URL is not functional even when correctly entered,. On desktop, the url works and the dashboard component is fully functional. However, on iOS even after entering the correct URL the dashboard component is non-functional.

**Comment by marcelveldt** [comment]
OK, in that case it simply doesn't work. It wasn't designed to function that way.
Music Assistant has its own panel in the HA sidebar and you can use that.

Maybe create a feature request to consume the MA frontend as standalone web app and list your requirement of including it as an iframe on a HA dashboard ?

**Comment by timmelander** [comment]
I ran into the same challenge. I wanted to integrate music assistant into another dashboard, so I used the web page card and used the URL to the music assistant dashboard. It seems to work beautifully on a browser when going to my target dashboard, but tries to load when in any iOS device. I will open a feature request. Love this add on.

**Comment by liquidbear99** [comment]
Thanks @timmelander, let me know when you create that feature request and I'll close this thread and begin following the new one.

**Comment by marcelveldt** [comment]
Made a few changes in 2022.7.2
It works on my browser and iphone if I manually navigate to the URL now.

Please test if 2022.7.2 works better in this regard. If not, please comment on the feature request we have for this:
https://github.com/music-assistant/hass-music-assistant/discussions/594

**Comment by timmelander** [comment]
Done https://github.com/music-assistant/hass-music-assistant/discussions/749

**Comment by liquidbear99** [comment]
Still giving issues. I have a comment on that feature request but we can close this for now. Thanks

**Comment by marcelveldt** [comment]
> Still giving issues. I have a comment on that feature request but we can close this for now. Thanks

can you please be a bit more descriptive ?
I have tested it myself yesterday and it works so I'm curious to what usecase you guys have.

If I open safari on my mac or iphone I can open the standalone URL just fine.
Just enter the url to HA, login and all set

**Comment by marcelveldt** [comment]
Yes, and you realize that you need to enter your HA url there right ?

Btw: if it's asking  "What host to connect to?" that means you did not update to the latest version because I changed that text...

**Comment by liquidbear99** [comment]
Hi Marcel, thank you again for checking in with us. What happens with us is each time we load the dashboard we still get the prompt to "Please enter the URL to Home Assistant". This prompt occurs even on 2022.7.4 and if you follow timmelander's comment instructions I still get the "Please enter the URL to Home Assistant" dialogue each time I switch to that dashboard. The prompt occurs not only within the iOS app but also in safari in the browser on iPhone, but NOT on the computer. Let me know if this is specific enough or if I can help in any other way.

**Comment by marcelveldt** [comment]
You get that dialog because you are trying to use the MA frontend standalone. You will need to enter the server url and then login. Once you're logged in to HA the details will be stored in a cookie as long as your press that "remember me" checkbox.

So, this is not a bug but the intended behavior. If your devices has trouble remembering the cookie that will probably more likely a browser/device issue and not MA.

So the million dollar question is... Did you actually try to enter your HA url in the dialog and login ?

Maybe this is specific to loading MA in an iframe and you will need adjusted security settings for that.

**Comment by marcelveldt** [comment]
Just tested it myself. 

- Works fine if the url is opened standalone.
- Works fine in card (=iframe) when using a browser directly
- Authentication fails if opened in card (=iframe) from the companion app

So this is probably just an issue (or just security layer!) with the companion app trying to load a HA location in an iframe.
I think you get exactly the same result if you want to open HA within that card/iframe which is more or less the same.
