### ISSUE TITLE
MA starts playing for unknown reason

### ISSUE THREAD

**Issue by WHagenauw** [music-assistant/hass-music-assistant#721]
### What version of Music Assistant has the issue?

2022.7.0

### The problem

After update to latest version it happens that suddenly MA starts playing on it's own. 

### How to reproduce

I don't know, happened 2 times now.  started once in the middle of the night. Only thing is that I started Home Assistant with the mobile app (but not when it started in the middle of the night). 

### Additional information

Maybe add a STOP button next to the others so the player can also be stopped instead of only PAUSE

### What version of Home Assistant Core are your running

2022.7.6

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by marcelveldt** [comment]
Google cast speakers?

**Comment by WHagenauw** [comment]
Probably Google Cast also but also Sonos. Happened last evening and last
night. I was not at home. Neighbors complained about my outside sonos
speakers playing. Last time I played was in a group together with both of
them. When I looked in the Google app the players from the group where
playing. I paused it last evening. This morning I checked and saw (and
heared via the webcam) that again music was playing. I paused again and
changed the speaker to one inside the house just in case it happens
again....

Kind regards

Wim


Op zo 24 jul. 2022 09:56 schreef Marcel van der Veldt <
***@***.***>:

**Comment by OzGav** [comment]
I have had this happen once with a group of Google speakers.

**Comment by erkr** [comment]
Hi Marcel, maybe related to my group cast interrupted by a new child player powered up and started playing its own queue?!

**Comment by elfrinjo** [comment]
So far, I have experienced this two times on a single google cast speaker (nest mini) in a group two cast-devices a few minutes after an announcement was played.

**Comment by MarvinSchenkel** [comment]
I just experienced this with a sonos as well,straight after a home assistant restart. Couldn't find any info in the log

**Comment by marcelveldt** [comment]
I will take a look at it tonight.

Dit bericht is verzonden via mijn mobiele telefoon.
________________________________
Van: Marvin Schenkel ***@***.***>
Verzonden: Sunday, July 24, 2022 4:50:36 PM
Aan: music-assistant/hass-music-assistant ***@***.***>
CC: Marcel van der Veldt ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [music-assistant/hass-music-assistant] MA starts playing for unknown reason (Issue #721)


I just experienced this with a sonos as well,straight after a home assistant restart. Couldn't find any info in the log

**Comment by stayupthetree** [comment]
I don't know if this is helpful, but this happens to me everytime I reboot. Funny part is, it plays the very first song I used as a test after install on the first device I used to test on. I can play a bunch of stuff on different devices using it, but as soon as I reboot, boom Motorcycle Drive By starts on my bathroom speaker

**Comment by jmtatsch** [comment]
Happened here tonight as well. Don't know why home assistant rebooted at all two times.
But after that music assistent initializes seemingly normally. And then started playing 2x after each reboot on my Sonos speakers. Interestingly also our fire tv powered our tv up at like 2am and showed some previews. My wife was pissed with me.

**Comment by TheFes** [comment]
For me it also happened twice, both after a HA restart (initiated by myself because if HACS updates)

**Comment by marcelveldt** [comment]
I have found the cause of the issue. Will provide a fix first thing tomorrow. Thanks for the patience!

**Comment by erkr** [comment]
Hi Marcel,
I figured out that Powering up a new player indeed can trigger this, but only if the player is not yet in de MA player list (so after a restart) and has a queue defined from earlier sessions

**Comment by TheFes** [comment]
I have an automation which switches a radio station at 14:00 on my Nest Mini.
It just triggered, and instead of playing the radio stream, it started playing MA.

**Comment by erkr** [comment]
MA is more dominant 😉

**Comment by marcelveldt** [comment]
I've just released patch version 2022.7.1 which should fix this issue.
If you still experience any issues after updating to 2022.7.1 please let us know, thanks!
