### ISSUE TITLE
Glitch: Number of playlists / radio's becomes 100

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#722]
### What version of Music Assistant has the issue?

2022.7.0

### The problem

When I open i.e. the playlists or Radio's, the correct number of them is shown at the top left of the screen.
But when I scroll down (far enough) and back, the number becomes 100!

### How to reproduce

See attached video

### Additional information

https://user-images.githubusercontent.com/4363599/180651176-2bfce890-a9d2-4cda-bba4-183ebb0ab54a.mp4

### What version of Home Assistant Core are your running

2022.7.6

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by FrankJaco** [comment]
This issue occurs in other locations around the MA interface, not just playlists..
To reproduce in the "Artist area....
1. Open Artists and observe the number.
2. Scroll manually to the bottom of Artists, then scroll up. The number will be rounded up to the nearest hundred.
3. If you then click the heart to show favorites, then click the heart again the original number will be displayed.


![image](https://user-images.githubusercontent.com/79318542/180991749-9cde329e-0879-4686-9291-973f3a7ad24f.png)

Scroll to end, then back up....

![image](https://user-images.githubusercontent.com/79318542/180992018-7fd4ca44-845a-48a3-91c4-1ac63bc5ca12.png)

Click heart twice...

![image](https://user-images.githubusercontent.com/79318542/180992110-2e70d2f2-0753-447b-be10-fc49fe4a9a15.png)

**Comment by marcelveldt** [comment]
I wanted to give you guys something to wonder about ;-)
haha, I'll take a look. Thanks

**Comment by marcelveldt** [comment]
Fixed in 2022.7.2
