### ISSUE TITLE
Album played gets added again to queue in endless loop

### ISSUE THREAD

**Issue by fernplant** [music-assistant/hass-music-assistant#723]
### What version of Music Assistant has the issue?

2022.7.0

### The problem

When selecting an album on filesystem, and clicking "Play Now" the album will be added to the queue and play as expected but once the album/queue ends, the queue on its own gets the album added again and it plays in an endless loop

Edit: Im actually not sure about the "endless". Ive always stopped it after the second playthrough of the same album
Edit2: This time just now it began automatically playing a different album by the same artist

### How to reproduce

Play album from filesystem completely through

### Additional information

Using Google Cast speakers. Other queue behavior has seemed strange/erratic since the 2022.7 release

### What version of Home Assistant Core are your running

2022.7.6

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Raspberry Pi

**Comment by erkr** [comment]
The obvious: did you Check your queue settings (3 dots upper right corner)? Expected behavior if repeat is on

**Comment by fernplant** [comment]
Thanks. Just checked in queue settings and repeat is off

**Comment by erkr** [comment]
Thanks

**Comment by marcelveldt** [comment]
I've just released patch version 2022.7.1 which should fix this issue.
If you still experience any issues after updating to 2022.7.1 please let us know, thanks!

**Comment by fernplant** [comment]
Just tested and yep, that did it :) Thanks . There is an album art issue in queue though, super minor, but Ill submit a separate issue for that
