### ISSUE TITLE
No navigate back button in Companion app (iOS)

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#73]
Hi
A small glitch in the UI when using the iOS companion app. When I navigate into the music assistant dashboard, there is no menu button or left arrow to navigate back to the navigation bar (marked green):
![image](https://user-images.githubusercontent.com/4363599/167272274-ebd8d87e-96b3-485a-9284-3f8a659b61d1.jpeg)

When I open the same dashboard via the media browser, there is a left arrow to navigate back:
![image](https://user-images.githubusercontent.com/4363599/167272890-11e37668-db9a-4cb2-b8f2-045cb92729dd.jpeg)

**Comment by marcelveldt** [comment]
You should be able to show the HA menu panel when you swipe from the left. I'll have a look if I can programmatically open the HA sidepanel menu.

**Comment by marcelveldt** [comment]
fixed (with workaround) in version 1.0.9, please let me know if this works any better

**Comment by erkr** [comment]
Still the same. Thx for pointing me to swipe left. That indeed works. For Navbar options the menu dashes are used in the other options:
![image](https://user-images.githubusercontent.com/4363599/167287165-24765449-e494-4f7b-b90a-67101a6fc34f.jpeg)

**Comment by erkr** [comment]
Maybe important; on my PC (Chrome) there is an arrow back. It's only missing on my iPhone (mobile version)
![image](https://user-images.githubusercontent.com/4363599/167287399-33da2834-efdd-4063-a1c3-35793b6e8eb2.png)

**Comment by marcelveldt** [comment]
your iPhone is probably still using the old frontend version from cache. If you pull the screen from top to bottom it's refreshed.

Problem is that HA by default hides the entire menu on mobile and because the Music Assistant panel is sandboxed it does't have access to open the side menu. I'll have to think a bit how to solve that.

**Comment by erkr** [comment]
You are a hero, after resetting the frontend cache in the companion app (pulling down didn't do it; via 'settings -> companion app-> debugging-> rest Frontend Cache'), the arrow is there 👍 
It now navigates back to the previous dashboard that was open. A menu donut that goes back to the navigation bar would be better I guess. But this is already an improvement. Thanks

**Comment by marcelveldt** [comment]
Yeah the endgoal is to display the hamburger menu to toggle the HA sidebar menu but so far I do not have a lot of luck with that because of the app sandbox but I'll keep trying ;-)

**Comment by erkr** [comment]
Succes, anyway its not a big deal

**Comment by marcelveldt** [comment]
this should be fixed in version 1.1.5
