### ISSUE TITLE
Cannot play music nor see library

### ISSUE THREAD

**Issue by bnieves1994** [music-assistant/hass-music-assistant#739]
### What version of Music Assistant has the issue?

2022.7.0

### The problem

No music will play when launching either from the media browser or from the side bar and the side bar now wont load my youtube music or spotify it shows as if there is nothing there. The integration used to perform flawlessly then completely stopped. 

### How to reproduce

Just playing anything will start the google home then nothing comes out and the device shows it was switched to off by maas

### What version of Home Assistant Core are your running

2022.7.6

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Windows

**Comment by bnieves1994** [comment]
I am not a Home Assistant newby I have had my system up and running for about 2 years now but usually if it doesnt work I just move on but love this integration. So if there are any logs etc that could be helpful please lmk what you need and I can use some googlefu to get it over to you!

**Comment by erkr** [comment]
Hi @bnieves1994 
I need some more info to understand your issue.
- You indicated that music doesn't play in de media browser. Are you referring to the standard media browser from home assistant? Or the browser in music assistant?

- what side bar now wont load your youtube music or spotify? Music assistant doesn't have a side bar?

Some screen shot could help

**Comment by bnieves1994** [comment]
Forgive my lack of info up front. So both the home assistant media browser and the browser in music assistant. Specifically I am navigating both ways as follows. I will include screen shots

![image](https://user-images.githubusercontent.com/89528841/180865369-d08b2fcd-d9c1-4917-8ba0-1bc4565420dd.png)

![image](https://user-images.githubusercontent.com/89528841/180865417-01d28209-c961-4953-8fcb-1411acd4a4cd.png)

![image](https://user-images.githubusercontent.com/89528841/180865491-45a9d8af-1283-4d97-ac6b-49a4ef2afe83.png)

![image](https://user-images.githubusercontent.com/89528841/180865572-7d923c44-8d4f-4dfd-97dc-66c1f6243bd4.png)

If I navigate as such it still wont play music but shows my saved music in spotify etc. However when clicking music assistant in the side bar like this nothing is shown at all

![image](https://user-images.githubusercontent.com/89528841/180865756-d6fcc07c-1649-441a-b395-b34da8b867da.png)

![image](https://user-images.githubusercontent.com/89528841/180865814-896ef0b4-1e2d-4368-9a84-e0f2f8a04f4f.png)


And again however I chose to try to use it would turn the speaker on which is confirmed by the google home start up sound but then the media never plays.

**Comment by marcelveldt** [comment]
1) Please make sure you're using the latest version of Music Assistant which is 2022.7.0 (or 2022.7.1 which has been released just now).

2) Clear the browser cache because the screenshot above are from a previous/old version. You should see a search bar on top and a "browse" button after radio.

3) If playback fails, that usually is an issue with the network settings. The players need to be able to reach the HA server directly over the internal network. The IP they connect to is derived from the "internal URL" setting in the HA config. Maybe check there if it's filled with a valid url ?

**Comment by bnieves1994** [comment]
@erkr and @marcelveldt Thank you both so much for your fast responses and solutions. Everything is working as it should and the new update is incredible. Thank you both again!
