### ISSUE TITLE
Album art in queue isn't correct

### ISSUE THREAD

**Issue by fernplant** [music-assistant/hass-music-assistant#740]
### What version of Music Assistant has the issue?

2022.7.1

### The problem

The ablum art displayed in the queue doesnt correspond to the actual album art

### How to reproduce

Go to an album on local filesystem, play now. View queue

### Additional information

Screenshot: <img width="1037" alt="Screen Shot 2022-07-24 at 11 11 58 AM" src="https://user-images.githubusercontent.com/25942905/180904616-16c98a54-f036-47a5-97f8-b758294f0481.png">

### What version of Home Assistant Core are your running

2022.7.6

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Raspberry Pi

**Comment by fernplant** [comment]
Upon closer inspection, I think it is actually the correct album art but its zoomed into a particular spot of it

**Comment by erkr** [comment]
Yes that makes sense. Thanks for the update
