### ISSUE TITLE
YouTube provider 403 error for free account

### ISSUE THREAD

**Issue by amitkeret** [music-assistant/hass-music-assistant#741]
### What version of Music Assistant has the issue?

2022.7.1

### The problem

As @MarvinSchenkel suggested [here](https://github.com/music-assistant/hass-music-assistant/discussions/606#discussioncomment-3134592), non-Premium accounts might only be able to use playlists containing free music videos.

I do not have a YouTube premium account.
Was able to log in, can't see albums/artists, but can see see my playlists - all as expected so far.
Unfortunately, all of the following items, which I can add to a playlist and play on YouTube Music, return error 403:
- free song
- free music video
- my own (uploaded) song

I suspected that music videos did not play because of YouTube's restriction preventing playing only the audio without displaying the video somewhere on screen. That still doesn't explain why free songs / my own uploads get 403 error.

### How to reproduce

- create a new playlist
- search for a song and add it (both as a song AND as a video - see the example below) to the playlist
- add your on uploaded song to the playlist
- refresh YT listing on MA and try playing the items of the new playlist

![image](https://user-images.githubusercontent.com/1258597/180910520-1d2b6dd1-d904-45a2-81c1-818f2bdeb5e6.png)

### Relevant log output

```
2022-07-26 12:09:23 WARNING (MainThread) [music_assistant.players.stream] Stream error on ytmusic://track/5qm8PH4xAss
2022-07-26 12:09:24 WARNING (MainThread) [music_assistant.helpers.audio] Could not determine integrated loudness of ytmusic://track/5qm8PH4xAss - ffmpeg version 5.0.1 Copyright (c) 2000-2022 the FFmpeg developers
built with gcc 11.2.1 (Alpine 11.2.1_git20220219) 20220219
configuration: ******(long build config)******
[https @ 0x7fad820000] HTTP error 403 Forbidden
https://rr2---sn-hufvjvgx-coxl.googlevideo.com/videoplayback?******(long param string)******: Server returned 403 Forbidden (access denied)
2022-07-26 12:09:31 WARNING (MainThread) [homeassistant.components.media_player] Updating mpd media_player took longer than the scheduled update interval 0:00:10
```

### What version of Home Assistant Core are your running

2022.7.6

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by MarvinSchenkel** [comment]
Thanks for the extensive info. Will have a look to confirm whether this use-case is actually valid, because Youtube Music might just require a premium subscription ;-).

**Comment by OzGav** [comment]
I don't have a subscription and I only activated this feature an hour ago to test something for someone else who was having a problem. So far I have seen that 403 error once and not sure what caused that yet but my YouTube playlists appear and I was able to play a track from one of them to a TV and to a Google speaker. I can now also see the artist for that track in my list of artists although if I click on that artist the tracks and albums list is empty. The track appears in my list of tracks however. So seems to work although there might be some bugs to iron out?

**Comment by MarvinSchenkel** [comment]
@amitkeret . Could you test something for me?

Please:
- Remove the MA integration
- Re-add the MA integration and add the Youtube Music provider
- Try to play a song from your playlist

Could you report if this (temporarily) fixes the 403 issue?

**Comment by OzGav** [comment]
This is the 403 error I have. Not sure if it is helpful. I don't know if it happened when trying to play a track or it is occurred during the initial scan

```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/mass/websockets.py:821
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 2:24:17 PM (3 occurrences)
Last logged: 2:24:22 PM

[546658427536] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/mass/websockets.py", line 114, in async_get_mass_func
    await orig_func(hass, connection, msg, mass)
  File "/config/custom_components/mass/websockets.py", line 821, in websocket_library_add
    await mass.music.add_to_library(item.media_type, item.item_id, item.provider)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/music/__init__.py", line 271, in add_to_library
    await ctrl.add_to_library(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/media_controller.py", line 253, in add_to_library
    await prov.library_add(prov_id.item_id, self.media_type)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/ytmusic/ytmusic.py", line 284, in library_add
    result = await library_add_remove_playlist(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/ytmusic/helpers.py", line 201, in library_add_remove_playlist
    return await loop.run_in_executor(None, _library_add_remove_playlist)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/ytmusic/helpers.py", line 196, in _library_add_remove_playlist
    return "actions" in ytm.rate_playlist(prov_item_id, "LIKE")
  File "/usr/local/lib/python3.10/site-packages/ytmusicapi/mixins/library.py", line 275, in rate_playlist
    return endpoint if not endpoint else self._send_request(endpoint, body)
  File "/usr/local/lib/python3.10/site-packages/ytmusicapi/ytmusic.py", line 144, in _send_request
    raise Exception(message + error)
Exception: Server returned HTTP 403: Forbidden.
The caller does not have permission
```

**Comment by MarvinSchenkel** [comment]
> ytm.rate_playlist(prov_item_id, "LIKE")

This seem to have happened when you added a playlist to your library (the <3 icon). Did you do this when using an account without a YT Premium subscription?

**Comment by OzGav** [comment]
Yes and I did notice something when I tried to add to library. MA hung for a short period and then the heart did not change to filled. So that explains a lot.

**Comment by MarvinSchenkel** [comment]
We just had an internal discussion and unfortunately we have to close this issue. Support for free accounts will not be added, since this will get Music Assistant into trouble with Youtube. Music Assistant has no way of playing ads, practically bypassing them, which is not allowed by Youtube.

**Comment by amitkeret** [comment]
fair enough @MarvinSchenkel unfortunate but understandable :)
would be appropriate to include this caveat in the README, same as with Spotify.

btw I would imagine no ads would be associated with playing your own uploaded files, so do you have any ideas on why not even that is working?

**Comment by MarvinSchenkel** [comment]
Thanks, I just updated the README 👍 

As for why playing own music does not work, I honestly have no idea, probably because I didn't add explicit support for it. Youtube Music does not have a proper API like Spotify, Qobuz etc, which means nothing works out of the box. So adding support for Youtube Music was the result of A LOT of hacking ;-)
