### ISSUE TITLE
Using Browser-native "Back" button in Artists view causing doubling of HA left pane

### ISSUE THREAD

**Issue by FrankJaco** [music-assistant/hass-music-assistant#743]
### What version of Music Assistant has the issue?

2022.7.1

### The problem

While in MA artist view, if you use your Browsers back button (instead of the one provided by MA) results in a doubling of Home Assistant's left window pane.

![image](https://user-images.githubusercontent.com/79318542/180994198-52ea1340-5be8-4819-848c-dfc96c87c681.png)

Now click the Browser's "Back button (Not the one provided by MA)
![image](https://user-images.githubusercontent.com/79318542/180994330-1dfe755f-5b6a-452d-a43d-dfb97f129427.png)

### How to reproduce

Go to Artist view, Click Browser Back button as above.

### What version of Home Assistant Core are your running

2022.7.6

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by marcelveldt** [comment]
Yes, this is a known issue that can't be solved at the moment. Maybe someday we can fix it together with the HA frontend devs but for now it's what it is. Use MA's own navigation buttons instead.
