### ISSUE TITLE
Add config option to specify the language to use for Spotify

### ISSUE THREAD

**Issue by freundTech** [music-assistant/hass-music-assistant#751]
### What version of Music Assistant has the issue?

2022.7.1

### The problem

Spotify has some autogenerated playlists with internationalized titles. For example the autogenerated playlist "Daily Mix 1" is called "Dein Mixtape 1" in German.

I have both Spotify on my computer and my Home-Assistant installation set to English, however in Music Assistant the playlists show up with their German names. Probably because I'm in Germany or because my account is registered in Germany.

### How to reproduce

1. Create a spotify accound in a non-English-speaking Country
2. Add "Daily Mix 1" to your playlists
3. Open the playlists view in Music Assistant

### Additional information

The Spotify API accepts the "Accept-Language" header, which can be used to get the correct translation. The main problem here is probably that the Home-Assistant Language is set in the frontend and can differ between users, while Music Assistant needs to fetch the Spotify API in the backend for all users.

### What version of Home Assistant Core are your running

2022.7.7

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

ODROID

**Comment by marcelveldt** [comment]
That is a real edge case :-) We get the language from Spotify itself.
Can you quickly check your Spotify account settings and see if you can set them to another language ?

**Comment by freundTech** [comment]
I can't find any language settings in the account settings. There is a country setting, but that would require adding a payment method from that country.

I know that this is a pretty low priority issue and that there are a lot more important things to work on right now, but I thought I'd report it anyways. Maybe someday someone finds the time to look into possible solutions.

The only possible solution I can think of right now is to download the playlists multiple times, once for each language a home-assistant user has set, which is obviously less than ideal.

**Comment by marcelveldt** [comment]
May I ask why you want the playlists to be in German ?

**Comment by freundTech** [comment]
I don't want the playlists in German. They are in German and I want them in English.

Both my Home Assistant and the Spotify Client on my PC are set to English, however Music Assistant shows the German playlist names.
The Spotify API returns the names in German because Music Assistant doesn't send the `Accept-Languages` header, so it infers German as the language because my account is registered in Germany (or because my IP is German, but I don't have a VPN to test. I think the account region is more likely).

**Comment by marcelveldt** [comment]
Sorry, typo...
May I ask why you want them in English instead of German ?

Music Assistant infers the language from the account details itself because that is what 99% of the users would expect :-)

So purely out of curiosity I'd like to know why you want to defer from the defaults.
The only way forward would be a global setting to set the language but that would apply to all users.

I don't think I'm going to fix this now but I see a solution in the foreseeable future because we're working on dynamic playlists which you can orchestrate with all kind of rules. In your case you could add a playlist with the naming you like and simply add the spotify playlist mentioned as only entry...

**Comment by marcelveldt** [comment]
OK, I've marked this as enhancement to pickup at some rainy day somewhere in the future.

**Comment by martincarlsen** [comment]
I'll +1 this. All my software is in english, even though i'm danish - so its frustrating that my Music Assistant is in Danish ;-)

**Comment by erkr** [comment]
For spotify, the language is specified per app on a device:

https://support.spotify.com/us/article/change-language/

The account seems to base the default language on the country or region where you were when you signed up.

**Comment by marcelveldt** [comment]
The next beta (b136) will add support for this. A global language can then be configured in the metadata core controller options.
