### ISSUE TITLE
Browse/Filesystem function sorts lowercase letters after all uppercase, not alphabetically

### ISSUE THREAD

**Issue by FrankJaco** [music-assistant/hass-music-assistant#755]
### What version of Music Assistant has the issue?

2022.7.2

### The problem

A very minor issue, Marcel, but I wanted to report it.

When in Browse/Filesystem the folders are displayed in alphabetical order as it should, unless there is a mix of folders starting with uppercase letters and lowercase. MA will first display all the folders starting with "A" to "Z" then will display folders "a" - "z".

![image](https://user-images.githubusercontent.com/79318542/181633139-252a0b3d-c261-49e8-a286-2922bcc6c89e.png)

It is an issue that is easy to work around... Simply rename your lowercase folders with uppercase letters, and all is good. 

### How to reproduce

To reproduce change a few folder names in the filesystem to start with lowercase letters, then Browse/filesystem again.they will immediately show up after all of the uppercase entries.

### Additional information

Low priority for sure. 

### What version of Home Assistant Core are your running

2022.7.6

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Yes Marcel did some work previously with sorting and my instinct was that what you are observing is correct as in ASCII order that is what you would see. However, the yardstick we used at the time of the previous fix is what would Excel do. I just tried it and indeed Excel sorts as you are suggesting so I will mark this as a bug and see what Marcel thiks.
