### ISSUE TITLE
All free youtube music locally downloaded can't be played anymore

### ISSUE THREAD

**Issue by SeByDocKy** [music-assistant/hass-music-assistant#757]
### What version of Music Assistant has the issue?

2022.7.2

### The problem

I downloaded locally in /media some mp3 from youtube music in the past. Now I can't play them in MA.... nothing  happens when I click on them

### How to reproduce

Download a Youtube Music into your local dir

### What version of Home Assistant Core are your running

2022.7.7

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

ODROID

**Comment by OzGav** [comment]
Can you confirm that you are otherwise using premium YouTube music?

**Comment by marcelveldt** [comment]
I think the title is just really misleading. He just means local mp3 files. The youtube part is completely irrelevant

**Comment by OzGav** [comment]
Yes ok I see now. Will mark it as more info needed as playing a music file is fundamental to MA!

**Comment by SeByDocKy** [comment]
Ok I will try to be more clear. From youtuve editor, I downloaded in the past some MP3 and copied them in my HA/media players. Until 2022.7.2, I was able to play them as a normal mp3. Now... impossible to play them in MA but I can play them with the default HA media tool.....

**Comment by marcelveldt** [comment]
What player?

There is another issue reported about VLC which I'm working on. Also Kodi will be affected by this bug as well as browser based players.

**Comment by SeByDocKy** [comment]
> What player?
> 
> There is another issue reported about VLC which I'm working on. Also Kodi will be affected by this bug as well as browser based players.

The original media player of HA

**Comment by marcelveldt** [comment]
I've release version 2022.7.4 which should fix the playback issues.
