### ISSUE TITLE
Latest update playback issue

### ISSUE THREAD

**Issue by antonyslater** [music-assistant/hass-music-assistant#758]
### What version of Music Assistant has the issue?

2022.7.3

### The problem

Since the upgrade to the latest version I am unable to stream anything to my usual VLC player instance on my PC.

There are no entries made into the HA Logs but I do get an error in VLC...  I've had this message before and usually occurs when I restart HA while VLC is still open.  However this is not the case here... MASS appears to be playing, ie the radio channel is shown, the volume sliders etc work but nothing is played in VLC.  After a short while the current media display at the bottom of the MASS screen returns to showing nothing.    When I try to play an album it seems to "skip" through the tracks a if there is an issue playing (or trying to) the first 2-3 seconds before it moves onto the next track before disappearing like the radio station.

Your input can't be opened:
VLC is unable to open the MRL 'http://192.168.1.70:8095/27f012590fdd41f9bfd07c158ee086ac.flac'. Check the log for details.
Your input can't be opened:
VLC is unable to open the MRL 'http://192.168.1.70:8095/349e63d3c5ae4db2a1a6ea5f670b1e75.flac'. Check the log for details.
Your input can't be opened:
VLC is unable to open the MRL 'http://192.168.1.70:8095/2f2c4cd4c1d24248ae123b331d988f69.flac'. Check the log for details.
Your input can't be opened:
VLC is unable to open the MRL 'http://192.168.1.70:8095/5374f50c72a6456293c213a49a91568c.flac'. Check the log for details.
Your input can't be opened:
VLC is unable to open the MRL 'http://192.168.1.70:8095/31f345ba823145ec852e6005e5c37676.flac'. Check the log for details.
Your input can't be opened:
VLC is unable to open the MRL 'http://192.168.1.70:8095/96ad2a859ee34248a67acde69165521d.flac'. Check the log for details.

### How to reproduce

Simply try to play anything in MASS and the results are the same.

### Relevant log output

VLC LOG

Your input can't be opened:
VLC is unable to open the MRL 'http://192.168.1.70:8095/27f012590fdd41f9bfd07c158ee086ac.flac'. Check the log for details.
Your input can't be opened:
VLC is unable to open the MRL 'http://192.168.1.70:8095/349e63d3c5ae4db2a1a6ea5f670b1e75.flac'. Check the log for details.
Your input can't be opened:
VLC is unable to open the MRL 'http://192.168.1.70:8095/2f2c4cd4c1d24248ae123b331d988f69.flac'. Check the log for details.
Your input can't be opened:
VLC is unable to open the MRL 'http://192.168.1.70:8095/5374f50c72a6456293c213a49a91568c.flac'. Check the log for details.
Your input can't be opened:
VLC is unable to open the MRL 'http://192.168.1.70:8095/31f345ba823145ec852e6005e5c37676.flac'. Check the log for details.
Your input can't be opened:
VLC is unable to open the MRL 'http://192.168.1.70:8095/96ad2a859ee34248a67acde69165521d.flac'. Check the log for details.

### What version of Home Assistant Core are your running

2022.7.4

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

**Comment by antonyslater** [comment]
FYI - Rolling back to 2022.7.2 resolves the issue.

**Comment by marcelveldt** [comment]
Released patch 2022.7.4 which should fix the issue. Thanks!
