### ISSUE TITLE
Bug in french translation

### ISSUE THREAD

**Issue by Y-Solo** [music-assistant/hass-music-assistant#759]
### What version of Music Assistant has the issue?

2022.7.3

### The problem

Hi,
French translation only work during MASS configuration (in Settings/Devices & Services/Integrations) but dosen't work in app.
Maybe a problem in my translation file?

### How to reproduce

Delete previous version before install the newest.
Select French language in Profile settings.
Clear web browser cache.

### What version of Home Assistant Core are your running

2022.7.7

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by marcelveldt** [comment]
the patch is released in 2022.7.4
