### ISSUE TITLE
Play / Pause glitch

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#76]
Now everything is roughly working, it's time for mentioning glitches. The play / pause button doesn't update when pressed:
![image](https://user-images.githubusercontent.com/4363599/167289029-2f996533-3bc3-4558-9275-7835ab305e20.png)
When I refresh the page, it has the correct state again

**Comment by marcelveldt** [comment]
fixed in 1.0.10

**Comment by erkr** [comment]
Will test tonight 😀

**Comment by erkr** [comment]
Could wait and already tried the new version. It's fixed👍
