### ISSUE TITLE
Synchronization & showing problem

### ISSUE THREAD

**Issue by NickyMB** [music-assistant/hass-music-assistant#761]
### What version of Music Assistant has the issue?

2022.7.3

### The problem

When Im trying to sync nothing happens i need to force sync and then i can see that music is in synchronization. But when i go to music to play something i only see loading bar, the same think is in radio. 
![Zrzut ekranu 2022-07-29 143427](https://user-images.githubusercontent.com/82083134/181759863-99aa9fe1-5434-468b-b80d-3a0ea4a02816.jpg)

### How to reproduce

I have no idea

### Relevant log output

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/mass/websockets.py:388
Integration: Home Assistant WebSocket API ([documentation](https://rc.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 14:28:13 (2 occurrences)
Last logged: 14:28:13

[140395824943152] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/mass/websockets.py", line 114, in async_get_mass_func
    await orig_func(hass, connection, msg, mass)
  File "/config/custom_components/mass/websockets.py", line 388, in websocket_tracks
    await connection.send_big_result(
AttributeError: 'ActiveConnection' object has no attribute 'send_big_result'

### What version of Home Assistant Core are your running

2022.8.0b1

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Linux

**Comment by marcelveldt** [comment]
Please install the 2022.8 (beta) version of Music Assistant.
