### ISSUE TITLE
Error setting up entry Music Assistant for mass

### ISSUE THREAD

**Issue by ovizii** [music-assistant/hass-music-assistant#762]
### What version of Music Assistant has the issue?

2022.8.0b0

### The problem

MA doesn't get activated. I just ran all HA updates as well as HACS updates and then noticed these errors and MA not running. 
![image](https://user-images.githubusercontent.com/837902/181777807-6fc8fbdc-f713-490d-9e87-37a6a0370d3b.png)

I can click on configure and MA runs through its setup but still says "failed to set up"

### How to reproduce

No idea?

### Relevant log output

Logger: homeassistant.config_entries
Source: custom_components/mass/__init__.py:161
Integration: Music Assistant ([documentation](https://github.com/music-assistant/hass-music-assistant), [issues](https://github.com/music-assistant/hass-music-assistant/issues))
First occurred: 28 July 2022 at 07:29:46 (1 occurrences)
Last logged: 28 July 2022 at 07:29:46

Error setting up entry Music Assistant for mass
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 353, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/mass/__init__.py", line 161, in async_setup_entry

### Additional information

Possibly related log entry:

Logger: homeassistant.core
Source: core.py:331
First occurred: 28 July 2022 at 07:35:04 (1 occurrences)
Last logged: 28 July 2022 at 07:35:04

Something is blocking Home Assistant from wrapping up the start up phase. We're going to continue anyway. Please report the following info at https://github.com/home-assistant/core/issues: humidifier, frontend, input_boolean, number, siren, tag, api, moon, device_tracker.mqtt, cover.mqtt, select.mqtt, light.browser_mod, camera.reolink_dev, binary_sensor.mobile_app, binary_sensor.ffmpeg_noise, watchman, diagnostics, sensor.moon, switch, plex, binary_sensor.browser_mod, reolink_dev, camera.mqtt, speedtestdotnet, sensor.thermal_comfort, number.mqtt, dhcp, scheduler, binary_sensor.tod, binary_sensor.frigate, device_tracker.mobile_app, person, humidifier.mqtt, light, input_select, switch.scheduler, camera, script, fan, group, binary_sensor.tankerkoenig, radio_browser, counter, vacuum.mqtt, analytics, update.hassio, binary_sensor.mqtt, media_player.browser_mod, input_number, lock, stream, tts.google_translate, ssdp, input_button, ffmpeg, webhook, tts, scene, input_text, vacuum, onboarding, update, mass, camera.browser_mod, select, zeroconf, sensor.hassio, met, sensor.plex, websocket_api, sensor.mobile_app, input_datetime, media_source, sensor, tankerkoenig, switch.mqtt, sensor.tankerkoenig, mobile_app, alarm_control_panel.mqtt, frigate, media_player.plex, panel_custom, climate, button.mqtt, application_credentials, cover, climate.mqtt, binary_sensor.workday, sensor.frigate, map, browser_mod, hacs, logger, sensor.hacs, weather.met, lock.mqtt, http, history, button.plex, my, notify.rest, weather, blueprint, persistent_notification, homeassistant, zone, sensor.remote_homeassistant, alarm_control_panel, fan.mqtt, system_health, update.frigate, binary_sensor.reolink_dev, camera.frigate, recorder, hassio, sun, sensor.reolink_dev, binary_sensor.hassio, usb, remote_homeassistant, device_tracker, siren.mqtt, thermal_comfort, search, notify.mobile_app, sensor.watchman, network, sensor.mqtt, image, switch.frigate, energy, config, lovelace, auth, shell_command, system_log, mqtt, light.mqtt, rest, cloud, timer, automation, binary_sensor, scene.mqtt, sensor.speedtestdotnet, trace, scene.homeassistant, notify, default_config, button, media_player, logbook, device_automation, sensor.energy, switch.reolink_dev, sensor.browser_mod

### What version of Home Assistant Core are your running

2022.7.7

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Linux

**Comment by marcelveldt** [comment]
You are trying to setup Music Assistant 2022.8 version (BETA!) with HA stable version 2022.7.x
That doesn't fit. You should install the latest 2022.7.x version for HA version 2022.7.x

It's a bit of a HACS problem that you can not pinpoint specific releases to a minimal HA version (only the whole project).

**Comment by ovizii** [comment]
Can you please help me figure this out? I am on the very latest version, HA does not offer me any updates.

Home Assistant 2022.7.7
Supervisor 2022.07.0
Operating System 8.4
Frontend 20220707.1 - latest

Are these not on the latest version? 

I think I understand now.
My MA version is newer than my HA version permits. 
I guess I'll stop updating MA and wait until HA catches up :-)

**Comment by ovizii** [comment]
I simply opted out of betas for MA within HAC and reinstalled MA. All looks good now.
