### ISSUE TITLE
Bug in french translation

### ISSUE THREAD

**Issue by Y-Solo** [music-assistant/hass-music-assistant#764]
### What version of Music Assistant has the issue?

2022.7.4

### The problem

Hi,
French translations always not showing up in frontend.
Thanks for your work

### How to reproduce

Delete previous version before install the newest.
Select French language in Profile settings.
Clear web browser cache.

### What version of Home Assistant Core are your running

2022.7.7

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by Y-Solo** [comment]
I'm sorry, i was using HA with firefox in private navigation.
That's why it dosen't work.

So, I confirm it work with standard firefox navigation.
It's about cookies maybe ?

**Comment by marcelveldt** [comment]
It's probably the cache. Just try to force flush it and you're all set
