### ISSUE TITLE
IOS Companion - Not able to close Sound settings when zoom is enabled

### ISSUE THREAD

**Issue by Underknowledge** [music-assistant/hass-music-assistant#766]
### What version of Music Assistant has the issue?

2022.7.4

### The problem

On IOS, when the zoom setting is activated, the free space is too little to close the overflow menu.

![image](https://user-images.githubusercontent.com/20793849/181824375-38b1604f-9d5d-4812-8cbe-6d6a68f6b2fa.png)

### How to reproduce

Enable zoom in the display settings

### What version of Home Assistant Core are your running

2022.7

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Raspberry Pi

**Comment by marcelveldt** [comment]
In version 2022.8.1 I have added a close button on various places for accessibility reasons, including in this slideout menu.

![Schermafbeelding 2022-08-05 om 11 23 13](https://user-images.githubusercontent.com/6389780/183046982-3a656516-2221-4825-98c8-e7e167d13623.png)
