### ISSUE TITLE
NOT Compatible with OS?

### ISSUE THREAD

**Issue by Bachigaloupe** [music-assistant/hass-music-assistant#775]
### What version of Music Assistant has the issue?

2022.8.0 BETA 2

### The problem

Been updating MA each time it is offered and this time it won't run.

I don't see a new update for HA or Core and I don't have any pending updates

### How to reproduce

Install and then restart HA

### Relevant log output

Logger: homeassistant.config_entries
Source: config_entries.py:367 
First occurred: 9:46:48 PM (1 occurrences) 
Last logged: 9:46:48 PM

Config entry 'Music Assistant' for mass integration could not authenticate: Not compatible with this version of Home Assistant

### Additional information

Home Assistant 2022.7.7
Supervisor 2022.07.0
Operating System 8.4
Frontend 20220707.1 - latest

### What version of Home Assistant Core are your running

2022.7.7

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
MA 2022.8.x is only compatible with HA 2022.8.x. So if you have updated MA either roll it back or update to the HA beta. If you decide to roll back hopefully you won’t have any issues….

**Comment by OzGav** [comment]
More info see here https://github.com/music-assistant/hass-music-assistant/issues/762
