### ISSUE TITLE
Chromecast does not play once a queue did finish

### ISSUE THREAD

**Issue by Adi146** [music-assistant/hass-music-assistant#783]
### What version of Music Assistant has the issue?

2022.7.4

### The problem

Once a queue did finish the chromecast does not play another song. You have to play from another source (e.g. youtube) first and after that you can play another song with Music Assistant again. It looks like the chromecast doesn't restart the player when the stream did finish.

### How to reproduce

1. Connect to a chromecast with Music Assistant
2. Play a song and wait until is did finish
3. Try to play another song (with will not work)

### Relevant log output

Logger: music_assistant.players.stream
Source: deps/lib/python3.10/site-packages/music_assistant/controllers/streams.py:493
First occurred: 15:48:59 (20 occurrences)
Last logged: 16:14:59

Abort: client(s) did not connect within 10 seconds.

### What version of Home Assistant Core are your running

2022.7.7

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

**Comment by marcelveldt** [comment]
Sorry, this does not sound familiar and should work so maybe I do not understand what you're trying to do.

1) What do you mean with connect to a chromecast ?
2) Where did you start the playback from ? From the Music Assistant panel ? Or the Home Assistant Media panel ?
3) Did you try to play just one song or a playlist or...?

**Comment by Adi146** [comment]
I'm playing a single song on my chromecast, using the Music Assistant panel. When the song has finished I can't play another song. 
It does work fine on a Google Nest mini but not on a Chromecast with Google TV (I hate the name schemas of google).

**Comment by Adi146** [comment]
Does Music Assistant reuse the url of a stream? If that's the case, then it looks like the Chromecast thinks the stream has finished and don't want to open it again.

**Comment by marcelveldt** [comment]
Is the Google TV device directly added to MA ? Not with a universal player in between or something like that ?

**Comment by Adi146** [comment]
I haven't considered that. I had it behind a universal media player but without it, it seems to work properly. So its probably an issue with the universal media player

**Comment by marcelveldt** [comment]
Correct, it doesn't work when the cast player is wrapped with the universal player. Actually I'm just looking into that if its even possible at all but going to be complicated. Maybe just add the underlying cast player to MA ?

For the time being I wil just blacklist the universal media players

**Comment by Adi146** [comment]
Alright, thank you for your quick help

**Comment by marcelveldt** [comment]
There's an existing enhancement request for compatibility with the Universal player here #457 
Closing this issue for now.
