### ISSUE TITLE
MA is blocking a restart of HA

### ISSUE THREAD

**Issue by gieljnssns** [music-assistant/hass-music-assistant#784]
### What version of Music Assistant has the issue?

2022.8.0b2

### The problem

HA 2022.8.0b4 takes very long to restart with MA enabled

### How to reproduce

enable MA restart HA

### Additional information

Issue originally posted in HA issues
https://github.com/home-assistant/core/issues/76021

### What version of Home Assistant Core are your running

2022.8.0b4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by marcelveldt** [comment]
It appears to be stuck in some sort of loop.
Can you tell me what you have setup ? So what kind of media players and what kind of music providers.

**Comment by gieljnssns** [comment]
This are my settings. The first 5 media players are Sonos. 
![568A1BD4-E25B-4660-84DE-0BD5A2031087](https://user-images.githubusercontent.com/17234951/182403767-82e9ed35-41b2-41c9-88bd-cfbde96903b9.png)
![4759E575-3344-412E-AA06-6BD4C26B85A2](https://user-images.githubusercontent.com/17234951/182403781-42b34b5a-da8a-48f8-b4ba-d591e768cf72.png)
![F728F54D-5AFC-499A-B486-C26296AD2BF4](https://user-images.githubusercontent.com/17234951/182403788-47197b12-8926-4844-a708-990aafc96158.png)

**Comment by marcelveldt** [comment]
What's that 6th player ? I hope that is not a spotify media player ? I'm not sure if that is going to work...
You do not have any music providers activated in MA or did you just redact the screenshot ?

I've looked at the dump you've shared in the HA core issue report and what appears to be happening is a stormflood of tasks, I think as a result of some endless loop condition. So far I've identified one small issue at shutdown but I'm not so sure that can cause something like this to happen.

**Comment by gieljnssns** [comment]
Yes it was the Spotify media player. 
I had none activated. 
In 4 hours I'm working night shift. If I don't have lot to do, I try to set up MA right.

**Comment by gieljnssns** [comment]
> Maybe I'm missing something really obvious here but what's the point of MA without any Music providers activated :-)

I thought that I activated the spotify media provider with the use of the virtual media player (I didn't took the time to read the instructions properly).

Now I did it right, much better...

**Comment by marcelveldt** [comment]
OK thanks for your feedback!
I will make a small code change so that the spotify virtual player can no longer be added to MA directly as player.
That will prevent this from happening to somebody else.
