### ISSUE TITLE
Error : Not compatible with this version of Home Assistant

### ISSUE THREAD

**Issue by andreasbuff** [music-assistant/hass-music-assistant#785]
### What version of Music Assistant has the issue?

2022.8.0 BETA 2

### The problem

Hello, newest PreRelease unfortunatly is not compatible with: 
Version | core-2022.7.7
Installationstyp | Home Assistant Supervised

### How to reproduce

Integration is not starting. Showing Error: Not compatible with this version of Home Assistant

### What version of Home Assistant Core are your running

Home Assistant 2022.7.7 

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Linux

**Comment by marcelveldt** [comment]
Look at the version number of **Music Assistant 2022.8.x BETA**
Is it perhaps compatible with **Home Assistant 2022.8 BETA** ?

To resolve, you either upgrade Home Assistant to 2022.8 (beta is in final stage now, release is tomorrow) OR you downgrade Music Assistant to the latest 2022.7 stable version. There's an option hidden in HACS called "reinstall" which will let you pick the version to install.
