### ISSUE TITLE
After update 2022.8.0 of HA : no more players, nom more files. Players and files exists and work with classic mulimedia player of HA

### ISSUE THREAD

**Issue by Electronlibre2012** [music-assistant/hass-music-assistant#792]
### What version of Music Assistant has the issue?

2022.7.4

### The problem

No more files and no more players appears in the player. They are present in the "configure" section of MusicAssistant

### How to reproduce

just upgrade HassOs to 2022.8.0

### What version of Home Assistant Core are your running

2022.8.0

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by marcelveldt** [comment]
Upgrade MA to 2022.8 too!

**Comment by Electronlibre2012** [comment]
lol sorry...noob issue

but i have no 2022.8 for your very usefull and wonderfull HACS add-on... no update on HACS

only the 2022.8.0b2 is visble but cant upgrade

**Comment by marcelveldt** [comment]
You need 2022.8.0 beta 2 indeed.

**Comment by Electronlibre2012** [comment]
ok sorry understood

really nice work, i was waiting for month for such an addOn

Thanks a lot

**Comment by Electronlibre2012** [comment]
it works again, sorry for this, you can close the issue, thanks,

i used it for a couple of weeks and cant do without now ;)
