### ISSUE TITLE
Toggle In Library/Favorite for a track doesn't update UI until reload of page

### ISSUE THREAD

**Issue by skipishere** [music-assistant/hass-music-assistant#799]
### What version of Music Assistant has the issue?

2022.8.0

### The problem

When liking an individual track, the UI doesn't indicate the change of heart solid -> empty or empty -> solid when clicked. Reloading the page/navigate away and back show the change in status.

### How to reproduce

Goto any album, click the heart next to an individual track and see no UI change.

### Relevant log output

n/a

### What version of Home Assistant Core are your running

2022.8.0

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Same situation with albums and artists. As I think Marcel fixed this a while ago I will mark it as a bug.

**Comment by marcelveldt** [comment]
Fixed in 2022.8.1
