### ISSUE TITLE
Failed to cast media

### ISSUE THREAD

**Issue by seanmccabe** [music-assistant/hass-music-assistant#803]
### What version of Music Assistant has the issue?

2022.7.4

### The problem

Failed to cast media http://192.168.1.2:8095/control/media_player.lounge_speaker/next.mp3. Please make sure the URL is: Reachable from the cast device and either a publicly resolvable hostname or an IP address

Casting is using an internal address, when Google requires a public accessible secure address.

The integration should be using the external address, not the internal address. Perhaps a config option here would resolve this?

### How to reproduce

Attempt to cast using the integration

### Relevant log output

Logger: homeassistant.components.cast.media_player
Source: components/cast/media_player.py:395
Integration: Google Cast ([documentation](https://www.home-assistant.io/integrations/cast), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+cast%22))
First occurred: 12:32:59 (1 occurrences)
Last logged: 12:32:59

Failed to cast media http://192.168.1.2:8095/control/media_player.lounge_speaker/next.mp3. Please make sure the URL is: Reachable from the cast device and either a publicly resolvable hostname or an IP address

### Additional information

Unable to play anything using music assistant. It can load songs etc, attempting to play results in the Google casting chime but no further action.

### What version of Home Assistant Core are your running

2022.7.7

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

**Comment by marcelveldt** [comment]
Casting works best when used with a local IP so no dns resolving is needed at all.
Is TCP port 8095 accessible from your local network to the machine running HA? Maybe you should open a port somewhere ?

**Comment by seanmccabe** [comment]
I've put this is now through the firewall.
Odd though, would it not be smarter to send the stream URL to the speaker to make the connection to Spotify rather than relying from HA?

**Comment by marcelveldt** [comment]
No that is not possible for obvious reasons like gapless and cross fade support nor do we receive the plain http stream

**Comment by OzGav** [comment]
@seanmccabe If this issue is now resolved I think we can close this issue

**Comment by seanmccabe** [comment]
> No that is not possible for obvious reasons like gapless and cross fade support nor do we receive the plain http stream

Ah ok, I usually let Spotify handle that side of things, this obviously works a little differently.
