### ISSUE TITLE
Cannot play something

### ISSUE THREAD

**Issue by s-cochet** [music-assistant/hass-music-assistant#806]
### What version of Music Assistant has the issue?

2022.8.1

### The problem

Cannot play a track, radio or something else.

### How to reproduce

try to play a track

### Relevant log output

Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/connection.py:102
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 11:01:23 (7 occurrences)
Last logged: 11:15:28

[547622473632] Error handling message: extra keys not allowed @ data['command']. Got 'play' (invalid_format)
[547665645424] Error handling message: extra keys not allowed @ data['command']. Got 'play' (invalid_format)

### What version of Home Assistant Core are your running

2022.8.1

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Raspberry Pi

**Comment by marcelveldt** [comment]
Try to refresh the frontend in your browser cache.

**Comment by s-cochet** [comment]
Refresh didn´t work. Aber deleting the browser cache and restarting the browser it´s working again. Thank You!
