### ISSUE TITLE
Unable to load the panel source: /lib/mass/mass.iife.js.

### ISSUE THREAD

**Issue by Fonsos** [music-assistant/hass-music-assistant#807]
### What version of Music Assistant has the issue?

2022.8.1

### The problem

I had this problem since MASS 2022.8 installed at HA 2022.7.4 but it keeps happening after update to MASS 2022.8.1 and HA 2022.8.1

I deleted MASS and reinstalled I still having the issue.

![image](https://user-images.githubusercontent.com/9643213/183044571-3f2126a3-6f56-45cc-a33b-d427f885d829.png)

I have seen the #804 and I thought it will be the same error, but after updating nothing changed.

### How to reproduce

Enter to Music Assistant Panel.

I have configured YouTube Music and several Chromecast devices and groups.

### Relevant log output

No log output from MASS

### Additional information

Running on VM.

### What version of Home Assistant Core are your running

2022.8.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Alternative

**Comment by marcelveldt** [comment]
Did you install using HACS ?
You can not install from Github directly...

**Comment by Fonsos** [comment]
I installed it via HACS everytime.

**Comment by marcelveldt** [comment]
Maybe try another browser or flush the browser cache somehow ?

**Comment by Fonsos** [comment]
It was the cache 🤦‍♂️
I use to clean it with Ctrl + Mayus +F5, but this time I cleaned it with de Dev tools opened, Mayus + right mouse on the reload icon and reload wiping the cache.

Thanks and sorry for the trouble.

**Comment by marcelveldt** [comment]
Yeah, that johnny cache can be stubborn :-)
Glad you solved it!
