### ISSUE TITLE
cant use music assistant after installation

### ISSUE THREAD

**Issue by tung256** [music-assistant/hass-music-assistant#808]
### What version of Music Assistant has the issue?

2022.8.1

### The problem

after configuration, i can see ! mark.
![image](https://user-images.githubusercontent.com/37672036/183231661-4ef4f450-a4eb-466c-b7e5-77880c2a7a4f.png)
error log is seen below

### How to reproduce

after configuration, i see ! Failed to set up   in my HA Integrations tab

### Relevant log output

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/mass/__init__.py:117
Integration: Music Assistant (documentation, issues)
First occurred: 11:06:47 PM (1 occurrences)
Last logged: 11:06:47 PM

Error setting up entry Music Assistant for mass
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 353, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/mass/__init__.py", line 117, in async_setup_entry
    f"with Home Assistant version {manifest['ha_version']} (or higher)."
KeyError: 'ha_version'

### What version of Home Assistant Core are your running

2022.7.7

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
As per the release notes you must be running 2022.8.x. Please upgrade core. Whilst in theory you can downgrade MA people have had problems with HACS.

**Comment by tung256** [comment]
> 

yes, im on 2022.8x
![image](https://user-images.githubusercontent.com/37672036/183257806-801acb19-4689-423a-8451-cf3e0abff6c1.png)

**Comment by OzGav** [comment]
Weird I received an email reply from @tung256 but I don’t see it here. The screenshot showed an update available to HA 2022.8.1 so please update and report back

**Comment by tung256** [comment]
im happy to say MA is working. error went away once i updated my HA
![image](https://user-images.githubusercontent.com/37672036/183273282-562980e7-c6f6-49e5-9eee-4de39405b48c.png)

i did mount my NAS folder as siggested on github but my Media tab is still blank
![image](https://user-images.githubusercontent.com/37672036/183273303-b7c5434a-07af-438c-af00-7fdebe687bb9.png)
![image](https://user-images.githubusercontent.com/37672036/183273308-2b2afcea-0fea-4193-ab1a-292f196dea87.png)

shell_command:
  mount_nas_folder: 'mkdir -p /media/nasfiles;mount -t cifs -o vers=2.1,noserverino,username=admin,password=pass!23,domain=WORKGROUP \\192.168.1.1\USB_Storage\mp3'

this is just an ext drive connected to my Netgear Nighthawk. i see the files fine in VLC but not in HA.   what is the syntax without entering any credentials?  because VLC is read only using no id and pw.
would this work?
mount_nas_folder: 'mkdir -p /media/nasfiles;mount -t cifs -o vers=2.1,noserverino,domain=WORKGROUP \\192.168.1.1\USB_Storage\mp3'

**Comment by OzGav** [comment]
Just try it and let us know

**Comment by tung256** [comment]
no luck. i tried all 3 smb versions and no passwords too.  cant view the files shared on my Netgear router

**Comment by OzGav** [comment]
Just noticed you mount command is incomplete you aren't telling it where to mount to and your slashes are the wrong way and you are missing one. Try this

`mount -t cifs -o vers=2.1,noserverino,domain=WORKGROUP //192.168.1.1/USB_Storage/mp3 /media/nasfiles`

Try it also with vers=3.0 and also try putting in the username and password. This is what mine looks like:
`mount -t cifs -o vers=3.0,noserverino,username=guest,password=,domain=WORKGROUP //192.168.1.250/Music /media/nasMusic`

**Comment by tung256** [comment]
> This is what mine looks like: `mount -t cifs -o vers=3.0,noserverino,username=guest,password=,domain=WORKGROUP //192.168.1.250/Music /media/nasMusic`

it works now!  thank you for the sample code.
as of now, im using VLC to access the files on my Netgear.  now that HA can see the files as well, which Player should i use so i can control that app via HA?
what i mean is, i have a tablet playing music in the kitchen. how to skip to the next song while in the living room using HA? that would be so cool.

**Comment by OzGav** [comment]
You just use the controls in music Assistant. The skip buttons are at the bottom

**Comment by OzGav** [comment]
@tung256 As the original issue has been resolved I will close this. You can ask further questions about how best to use MA in the discussion area or on discord.
