### ISSUE TITLE
Tune-in don't show a favorites

### ISSUE THREAD

**Issue by stresserini** [music-assistant/hass-music-assistant#81]
I entered my email to retrieve my TUNE-IN  favorites, but it doesn't work

**Comment by erkr** [comment]
I entered my username (visible below your email when you check your account profile in the TuneIn website)

**Comment by marcelveldt** [comment]
Yeah, I should probably make that more clear in the docs. Tune-In is kind of strict when it comes to that. You need your username indeed instead of your email.

**Comment by stresserini** [comment]
I'm sorry, but entering the username and making the last update, the job remains in the background and displays nothing.
The profile set is public in my account.

**Comment by marcelveldt** [comment]
what do you mean with "the job remains in the background" ? Did you wait long enough until the initial sync is done ? That could take a few minutes on large collections

**Comment by stresserini** [comment]
![Immagine 2022-05-09 223501](https://user-images.githubusercontent.com/60366756/167493224-866a0a1e-9a52-4c21-b66a-93642e3fcf2c.png)
![Immagine 2022-05-09 223430](https://user-images.githubusercontent.com/60366756/167493251-2ce3edd6-fd1f-46f6-a1be-5626275df6d8.png)

yes, it remains for a few minutes as shown in the photo, then it remains empty

**Comment by marcelveldt** [comment]
That is strange but I found out that the Tune-In structure is a bit strange...
Are you using the new library in Intune ? Music Assistant will (for now) only show items that are in your Tune-In **library**

**Comment by stresserini** [comment]
I think so, the library are the favorites I have both in the phone app and in web access

**Comment by marcelveldt** [comment]
Are you running version 1.0.13 of Music Assistant ?

**Comment by stresserini** [comment]
yes, the lastest

**Comment by marcelveldt** [comment]
May I ask your Tune In username ? Or send it to me as PM on discord.
The profile is public so I have a look what is special about it

**Comment by stresserini** [comment]
how do i find you on discord

**Comment by marcelveldt** [comment]
marcelveldt

**Comment by marcelveldt** [comment]
Or the Music Assistant channel

https://discord.com/channels/753947050995089438/753947050995089442

**Comment by stresserini** [comment]
in addition to your name I need the 4 numbers    #xxxx

**Comment by marcelveldt** [comment]
0393

**Comment by marcelveldt** [comment]
As discussed in discord you now see the TuneIn stations in MA.
I've just checked in a small fix for the buffer of radio stations which might also fix playback on Sonos devices.
If you have time, please test with the new 1.0.14 version. Thanks!

**Comment by marcelveldt** [comment]
closing this as it was confirmed fixed by another user. If you still experience issues, please reopen this issue or create a new one. thanks!

**Comment by lolouk44** [comment]
@marcelveldt can you describe how you fixed this issue as I'm experiencing the same...
Thanks

**Comment by marcelveldt** [comment]
> @marcelveldt can you describe how you fixed this issue as I'm experiencing the same... Thanks

please open a new issue report, thanks!
