### ISSUE TITLE
<CNTL>-A action menu not visible in some cases and sometimes only grabs the first 100 entries

### ISSUE THREAD

**Issue by FrankJaco** [music-assistant/hass-music-assistant#821]
### What version of Music Assistant has the issue?

2022.8.1

### The problem

In the "Artist" area, if you press <CNTL>-A the action menu is brought up to allow you to perform an action on all entries. {For example to add ALL your artists to the library.} If you have more than 100 entries, (I have ~430 currently) if you don't scroll to the bottom of your artists first your actions will only be performed on the first 100 entries.
![image](https://user-images.githubusercontent.com/79318542/183299395-f9d26d49-0966-4ce9-8e66-e8829ea82934.png)
pressing <CNTL>-A here causes this...
![image](https://user-images.githubusercontent.com/79318542/183299430-d993eb19-3d59-4a6d-855f-ca4a8a228467.png)

However scrolling down to the very bottom of your entries (433) in my case, then pressing CNTL>-A   will pop up the option to open the action menu.  But if you press "actions" here you cannot do anything. The action menu doesn't open, nor can you scroll back to the top of the entries list. Basically locked with the only possibility to back out of artists.

To make this work as expected you must:
1. Go to the Artist list.
2.  Scroll down to the bottom of the list. (Note that you may need to scroll a little up and back down as you get to entry 100 to make it go further than 100).
3. After successfully scrolling all the way down to your last entry, scroll back to the very top of the list.
4. Now press <CNTL>-A.  The Action menu will pop up as expected, and your will be able to perform your desired action.

### How to reproduce

As above

### What version of Home Assistant Core are your running

2022.8.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
I am guessing this is the result of the “lazy loading” that MA does to speed up the UI. Will see if Marcel can come up with a solution…

**Comment by marcelveldt** [comment]
Yeah correct, it's the server side paging now messing with the "CTRL-A" select all... I'll see if I can come up with an elegant solution for this...

**Comment by FrankJaco** [comment]
Although that delay or little up-down motion is an issue, the bigger one 
is when you do scroll to the end, then do the <CNTL>-A and click 
"Actions", it doesn't display the menu and locks up the screen. Perhaps 
when "Actions" is clicked, you can automatically make the list jump back 
to the top before displaying the action menu?

fj

**Comment by OzGav** [comment]
> when you do scroll to the end, then do the <CNTL>-A and click "Actions", it doesn't display the menu and locks up the screen.

Just tried this on b31 and it works fine from the bottom of the list. Still only grabbing 100 entries from the top though.

**Comment by marcelveldt** [comment]
fixed in next frontend version (most likely beta60)
