### ISSUE TITLE
Context Menu stuck at top of page

### ISSUE THREAD

**Issue by OzGav** [music-assistant/hass-music-assistant#824]
### What version of Music Assistant has the issue?

2022.8.2

### The problem

When selecting the context menu (three dots to the right of an artist/track/album) the menu opens at the very top of the list which might be off screen which then results in the UI being frozen as you can't get to the menu to select anything or close it

![image](https://user-images.githubusercontent.com/19848947/183321311-49c0b9e3-f355-410c-8d14-5ac4f27f010b.png)

### How to reproduce

Go to an artist or select albums with list view or tracks view
Scroll down one page
Select context menu

### What version of Home Assistant Core are your running

2022.8.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by marcelveldt** [comment]
I quickly restored the old layout. Now it looks ugly again but functional :-)
Will have a look at permanent solution later

**Comment by OzGav** [comment]
It’s not that ugly :-)
