### ISSUE TITLE
defekts in sound when playing music on Denon  Heos 150, 250

### ISSUE THREAD

**Issue by chali272** [music-assistant/hass-music-assistant#832]
### What version of Music Assistant has the issue?

2022.8.2

### The problem

When playing music using Music Assistant it starts to sound really bad.  this started many versions ago. 

https://user-images.githubusercontent.com/11187523/183688390-a8793a90-c3b7-4ce1-8da7-bf777aafc8cb.mp4

### How to reproduce

start a song from ex spotify using Music Assistnad on a denon heos 150 or 250

### Relevant log output

this is al i find in the logg 
Logger: homeassistant.components.heos.media_player
Source: components/heos/media_player.py:110
Integration: Denon HEOS (documentation, issues)
First occurred: 4:59:17 PM (2 occurrences)
Last logged: 4:59:19 PM

Unable to play media: URL is relative, but does not start with a /

### What version of Home Assistant Core are your running

2022.8.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Have you looked at the troubleshooting tips about this? https://github.com/music-assistant/hass-music-assistant/discussions/709

**Comment by chali272** [comment]
Thank you, it seems to fixa the problem.


Den tis 9 aug. 2022 22:51OzGav ***@***.***> skrev:
