### ISSUE TITLE
File system music provider - can't create play list since it's mounted read-only

### ISSUE THREAD

**Issue by lmamakos** [music-assistant/hass-music-assistant#833]
### What version of Music Assistant has the issue?

2022.8.2

### The problem

I've got a file system mounted read-only via NFS and available in the Home Assistant container as `/media/music`.  I cannot create any play lists as it's attempted to be created at the root of the (read-only) file system.

I searched to see if this was a known issue, but didn't find anything; sorry if this is already a known issue?

### How to reproduce

I've only a single "Music Provider", a filesystem provider, configured as `/media/music` in the configuration panel for music assistant.  That directory is mounted read-only.

Tried to add a track to a new playlist, named `foo` and it fails.  Errors in log follows.

### Relevant log output

```
2022-08-12 00:14:47.113 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139966667869200] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/mass/websockets.py", line 114, in async_get_mass_func
    await orig_func(hass, connection, msg, mass)
  File "/config/custom_components/mass/websockets.py", line 645, in websocket_playlist_create
    new_playlist = await mass.music.playlists.create(msg[NAME], msg.get(PROVIDER_ID))
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/media/playlists.py", line 97, in create
    return await provider.create_playlist(name)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/filesystem/filesystem.py", line 454, in create_playlist
    async with self.open_file(filename, "w") as _file:
  File "/usr/local/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/filesystem/filesystem.py", line 795, in open_file
    async with aiofiles.open(file_path, mode) as _file:
  File "/usr/local/lib/python3.10/site-packages/aiofiles/base.py", line 78, in __aenter__
    self._obj = await self._coro
  File "/usr/local/lib/python3.10/site-packages/aiofiles/threadpool/__init__.py", line 80, in _open
    f = yield from loop.run_in_executor(executor, cb)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
OSError: [Errno 30] Read-only file system: '/media/music/foo.m3u'
```

More about the environment inside the container:
```
louie@macmini ~/hasstest/config % docker exec -it hasstest df /media/music
Filesystem           1K-blocks      Used Available Use% Mounted on
10.200.0.20:/mnt/z3/media/music
                     16290768384 114978688 16175789696   1% /media/music
louie@macmini ~/hasstest/config %
```

Home Assistant instance is a non-production, testing instance and launched with this docker-compose file:
```
version: "3.3"
services:
  hass:
    container_name: hasstest
    image: "homeassistant/home-assistant:2022.8.2"
    restart: "always"
    network_mode: "host"
    environment:
      - "TZ=America/New_York"
    volumes:
      - "/home/louie/hasstest/config:/config"
      - "/mnt/music:/media/music:ro"
```

### Additional information

I had imagined that the playlist was stored alongside (or inside) the music assistant database in the read/write Home Assistant configuration directory at `/config` or a subdirectory of that.  I'd rather not expost that file system as read-write as it's logically "owned" by another application running on another host.

### What version of Home Assistant Core are your running

2022.8.3

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
This doesn’t sound like an issue it sounds like an enhancement?

**Comment by lmamakos** [comment]
Bug or a feature (enhancement).. not sure.  It was a surprising behavior to me; maybe I thought that playlists spanned multiple different sources and thus would be independent of each of them and their individual storage means.  I'm coming to this with the ignorance of a brand new user and probably ill-informed expectations, or a model of how this works that I just imagined in my head vs. the reality of how it's actually built.  

Regardless, I'll see if I can play some games with how it's mounted and have a read-write directory available "above" the actual mount point.  Thanks for taking a look!  This is a really nice feature to have available in Home Assistant.

**Comment by OzGav** [comment]
@marcelveldt is back now so will see what he says....

**Comment by marcelveldt** [comment]
For now, playlists are stored on disk (or on a streaming provider ofc). I've abused the filesystem playlists to store "multi provider" playlists as m3u files as that was a real quick win to fix for now and its also portable as in it can be moved to a new MA instance, survive a MA db error etc.

For now I'm going to keep it this way. If there's any interest in a "MA universal playlist format stored in the db or file location other than musicdir", please create a feature request. Thanks!

**Comment by lmamakos** [comment]
Thanks for the follow-up.  I think I can screw around with the mount points to have a R/W directory somewhere with the music mounted underneath.   I suppose the actual "bug" is assuming that the music is on some storage that's writable, rather than than some abstract read-only repository owned by some other software.  Perhaps that's more of an architectural assumption on the nature of the music providers and something to ponder.  Related might be per-user playlists, etc.
