### ISSUE TITLE
"Got stream request for unknown or finished stream" warning every 10 s in my log

### ISSUE THREAD

**Issue by paulius2k** [music-assistant/hass-music-assistant#852]
### What version of Music Assistant has the issue?

2022.8.2

### The problem

I have this warning message repeating in my log every 10 secs for a couple of days already:
```
WARNING (MainThread) [music_assistant.stream] Got stream request for unknown or finished stream: 7ba7700c824a4108a4b601b211305065
```

### How to reproduce

I am not exactly sure how to reproduce it, but I was having issues streaming to my browser_mod media player previously. After reloading the MA integration I managed to stream to my browser, then stopped streaming - probably that's when those warnings started appearing.

Reloading the MA integration does not stop the messages in log. 

### What version of Home Assistant Core are your running

2022.8.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by marcelveldt** [comment]
I fixed a small issue yesterday that might also fix this one. Check patch version 2022.8.3.

If the issue persists than have a look if you still have a rogue browser mod player somewhere

**Comment by paulius2k** [comment]
Updated MA to 2022.8.3.
So far I see no such behavior anymore. I will close this issue after a couple of days of monitoring.

**Comment by OzGav** [comment]
Hi @paulius2k . Is this fixed?

**Comment by paulius2k** [comment]
not repeating anymore, closing
