### ISSUE TITLE
Playback is stopped on browser_mod player when browser tab is not in focus 

### ISSUE THREAD

**Issue by paulius2k** [music-assistant/hass-music-assistant#853]
### What version of Music Assistant has the issue?

2022.8.3

### The problem

I noticed that my playback (Radio or Spotify) is stopped on a `browser_mod` player when browser (Chrome in my case) tab with MA is not in focus after 5 minutes. This doesn't happen when browser tab is in focus. 

Coming back to MA tab I see that the initial screen had been loaded:
![image](https://user-images.githubusercontent.com/24705262/184906332-a15499c0-19f9-47ef-a1ab-8f0e710cd549.png)

### How to reproduce

- Play a stream on a `browser_mod` media player
- Open another tab on your browser
- Stream is stopped after 5 mins

### Relevant log output

```
WARNING (MainThread) [music_assistant.stream] Got stream request for already running stream: a1b853ef86324c408de7a8ff71197492, playback may be disturbed!
```

### What version of Home Assistant Core are your running

2022.8.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by marcelveldt** [comment]
Yes, that is the default behavior of the browser. It will suspend a browser tab when not in use to save resources.
So, not an issue with Music Assistant but browser_mod or more specific the browser limitations itself.

If you're looking for a way to enable local playback on your device maybe look into alternatives like squeeze lite or raise your votes on the feature request where we intend to enable playback from within the HA companion app (or a Music Assistant wrapped app).

**Comment by paulius2k** [comment]
Thank you, I upvoted https://github.com/music-assistant/hass-music-assistant/discussions/436 already.

Closing this one as not a bug.
