### ISSUE TITLE
Can't play local media 

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#856]
### What version of Music Assistant has the issue?

2022.8.3

### The problem

Can't play local media ( other sources work fine)

### How to reproduce

Enforce playback of a local mp3 file  

### Relevant log output

Logger: music_assistant.players.stream
Source: runner.py:119 
First occurred: August 16, 2022, 15:48:21 (11 occurrences) 
Last logged: 13:22:42

Stream error on file://track/albumsgunsnrosesgreatesthits07youcouldbeminemp3
Stream error on file://track/albumsgunsnrosesgreatesthits02sweetchildominemp3
Stream error on file://track/albumsgunsnrosesgreatesthits01welcometothejunglemp3
Stream error on file://track/albumsgunsnrosesgreatesthits09novemberrainmp3
Stream error on file://track/albumsgunsnrosesgreatesthits11yesterdaysmp3

### What version of Home Assistant Core are your running

2022.8.5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by vk2him** [comment]
This also fails with m4a files

Stream error on file://track/masonwilliamsthemasonwilliamsphonographrecordmasonwilliamsthemasonwilliamsphonographrecord7classicalgasm4a
Stream error on file://track/carpentersthesingles19691973carpentersthesingles1969197312theylongtobeclosetoyoum4a


As a test I downgraded to 2022.8.1 and the same issue exists. Thanks

**Comment by compujunk** [comment]
Here the same problem
Logger: music_assistant.players.stream
Source: runner.py:119
First occurred: 16 augustus 2022 om 20:17:57 (99 occurrences)
Last logged: 15:00:01

Stream error on file://track/artistmusicrenefrogerkhebjelief2010pop209renefrogerforadatewithyoump3
Stream error on file://track/artistmusicrenefrogerkhebjelief2010pop108renefrogerstillonyoursidemp3
Stream error on file://track/artistmusicabcthelexiconoflovedeluxeedition1982newwave212abc4ever2getherliveathammersmithodeonnovember1982mp3
Stream error on file://track/artistmusicabcthelexiconoflovedeluxeedition1982newwave117abcalphabetsoupbbcswapshopversion291181mp3
Stream error on file://track/artistmusicabcthelexiconoflovedeluxeedition1982newwave107abcdatestampmp3

**Comment by Electronlibre2012** [comment]
wait for a fix too ;)

**Comment by marcelveldt** [comment]
Downgrade to 2022.8.2 until 2022.8.4 is released, thanks.

**Comment by vk2him** [comment]
I can confirm that it works OK with 2022.8.2 - thanks

**Comment by marcelveldt** [comment]
Published a hot fix 2022.8.4

Thanks for reporting and the patience!

**Comment by vk2him** [comment]
Prefect, working well again - thanks :)
