### ISSUE TITLE
Can not start music from home assistants own media

### ISSUE THREAD

**Issue by ENGBERG80** [music-assistant/hass-music-assistant#860]
### What version of Music Assistant has the issue?

2022.8.4

### The problem

It has been an issue before, but now  i can not start music (from spotify via music assistant) from home assistant own media browser.

### How to reproduce

all the time

### What version of Home Assistant Core are your running

2022.8.6

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by userMak** [comment]
The same problem for me. 2022.8.5

**Comment by OzGav** [comment]
I assume you mean MUSIC ASSISTANT>>BROWSE>>SPOTIFY>>ALBUM/ARTIST/TRACKS/PLAYLIST ??

If so, that works fine for me. You need to provide more info. Exactly what you are trying to do, confirm you are using Spotify Premium, look for errors in the logs etc...

**Comment by ENGBERG80** [comment]
The problem is when i use Home Assistants own Media browser and select Music Assistant it wont start the music

i have the premium

**Comment by OzGav** [comment]
Any errors in the logs? I just went to HA MEDIA>>MUSIC ASSISTANT>>PLAYLISTS and selected a Spotify playlist and it worked fine to a Google Home speaker. Can you try that?

**Comment by ENGBERG80** [comment]
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/mass/media_source.py:118 
Integration: Home Assistant WebSocket API (documentation, issues) 
First occurred: 14.41.16 (1 occurrences) 
Last logged: 14.41.16

[547825131504] 'NoneType' object has no attribute 'url'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1713, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1750, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 676, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 930, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 713, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/cast/media_player.py", line 628, in async_play_media
    sourced_media = await media_source.async_resolve_media(
  File "/usr/src/homeassistant/homeassistant/components/media_source/__init__.py", line 146, in async_resolve_media
    return await item.async_resolve()
  File "/usr/src/homeassistant/homeassistant/components/media_source/models.py", line 90, in async_resolve
    return await self.async_media_source().async_resolve_media(self)
  File "/config/custom_components/mass/media_source.py", line 118, in async_resolve_media
    return PlayMedia(player.active_queue.stream.url, f"audio/{content_type}")
AttributeError: 'NoneType' object has no attribute 'url'

**Comment by ENGBERG80** [comment]
I go to MEDIA, MUSIC ASSISTANT AND MY PLAYLIST then to a Google Chrome cast audio and this error pops up

**Comment by ENGBERG80** [comment]
Same problem :(

**Comment by OzGav** [comment]
OK so I understand a playlist or a direct Spotify track results in the above error. What if you try and play a local music file (if you have one)

**Comment by ENGBERG80** [comment]
Local files works fine

**Comment by OzGav** [comment]
Ok will have to wait and see what @marcelveldt thinks

**Comment by OzGav** [comment]
As the error indicates a url issue you could also check your internal IP. Go to Settings --> System --> Network --> Home Assistant URL --> Local network (set to automatic or use your internal HA IP). If it is automatic change is to http://your.ip:8123

**Comment by ENGBERG80** [comment]
I have tried that now, and stil same problem :(

**Comment by OzGav** [comment]
I’m running out of ideas. Have you tried disabling Spotify in the MA config and reloading the integration, wait for all the Spotify data to disappear and then re-adding it?

**Comment by ENGBERG80** [comment]
Have not tried that. I Will try later :)

**Comment by ENGBERG80** [comment]
Did not work :(

**Comment by ENGBERG80** [comment]
Now it suddenly works 😱

**Comment by OzGav** [comment]
Keep testing it and see if it is all good. If not please continue to try and work out what is causing the issue.

**Comment by ENGBERG80** [comment]
I seems to work now, the only thing i noticed is, if i activate shuffle, then it start random playlists, when i select a specific playlist 🤷

**Comment by OzGav** [comment]
You shuffle the queue not the playlist. If there are existing tracks in the queue then your selected playlist will be shuffled in with those tracks.

**Comment by OzGav** [comment]
Just checking if this is now resolved?
