### ISSUE TITLE
Spotify playlists don't appear in HA Media Browser

### ISSUE THREAD

**Issue by marciogranzotto** [music-assistant/hass-music-assistant#861]
### What version of Music Assistant has the issue?

2022.8.4

### The problem

Spotify playlists available in the Music Assistant sidebar menu do not show up on HA's Media Browser

## on Music Assistant:
![Screen Shot 2022-08-19 at 10 38 08](https://user-images.githubusercontent.com/11080704/185631519-f272e253-44de-4ead-af8a-a2cff37078c6.png)

## on Media Browser:
![Screen Shot 2022-08-19 at 10 39 37](https://user-images.githubusercontent.com/11080704/185631536-6255de4d-90e5-4ff5-989a-c692ff991ec4.png)

### How to reproduce

Link an Spotify account that has playlists to Music Assistant

### What version of Home Assistant Core are your running

2022.8.6

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
I might be missing something but why do you think they should show up there?

**Comment by marcelveldt** [comment]
Only favorited playlists will show up in HA's own media browser. It doesn't have any filter or sorting options like MA's frontend has.

**Comment by marciogranzotto** [comment]
> Only favorited playlists will show up in HA's own media browser. It doesn't have any filter or sorting options like MA's frontend has.

That was it! Thank you!
Idk if that's documented somewhere, but it should probably be more visible
