### ISSUE TITLE
Using Browser Back in Chome causes Music Assistant to open Home Assistant inside MA

### ISSUE THREAD

**Issue by nthulke** [music-assistant/hass-music-assistant#866]
### What version of Music Assistant has the issue?

2022.8.4

### The problem

I first noticed it on my phone, if I hit back while in a MA menu item (playlists/browse/ect) it would show me the HA load screen and "lock up". Then I tested it on my browser and when I use the back button on the browser it opens HA inside MA so I effectivly have HA open twice on the screen. 
![MAHA](https://user-images.githubusercontent.com/69140718/185823950-c05a9096-31ef-4f26-b3ec-4a38daf03caa.png)
 

### How to reproduce

From HA click on Music Assistant on the left side tabs, then click on any of the items (Artits/Albums/Tracks/Radio/Playlists/Browse) then hit back using the browser back button not the Music Assistant back button.

### What version of Home Assistant Core are your running

2022.8.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Thaks this is a known issue. Please see here https://github.com/music-assistant/hass-music-assistant/issues/667

**Comment by nthulke** [comment]
Thanks, I did a search, but not a good one apparently :)
