### ISSUE TITLE
Short MP3 (door chime) not playing through mass players

### ISSUE THREAD

**Issue by fribse** [music-assistant/hass-music-assistant#879]
### What version of Music Assistant has the issue?

2022.8.4

### The problem

In my 'local' media files I have placed two small door chimes.

https://soundbible.com/1462-Two-Tone-Doorbell.html
and
https://soundbible.com/1599-Store-Door-Chime.html

They don't have valid MP3 tags, so I corrected that with mp3tag.

When I select one to be played on eg. a Google home, the 'ding' for media play back is played, but the chime itself is not played.
They are very short (1s and 2s) but they work fine if I play them directly to the 'non-mass' media_players.

### How to reproduce

Send the small mp3 to a google home device.

### What version of Home Assistant Core are your running

2022.8.6

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
I have just tried this and it works fine for me. You are going to have to supply more info. For example, YAML if you are using it or a screen cap of your UI config and exact location of the media files,

**Comment by OzGav** [comment]
@marcelveldt I didn't need to turn it on with my test although I do set the volume first...?

**Comment by fribse** [comment]
The two chimes are in the 'local media' library that's already in Music Assistant, and I just add them to the queue for playback.
I want it to use the 'play_media' in node red, but I haven't found the right format for the media id yet, still searching the documentation for that.
If I send it out twice, the speaker should be on, right?

These are the media players:
![billede](https://user-images.githubusercontent.com/13660621/186699158-8ba6b771-6420-4c82-a550-7987953e0845.png)
And this is the local media setup:
![billede](https://user-images.githubusercontent.com/13660621/186699322-8b0fc569-6305-4f22-9e48-8f8db9dc5641.png)

**Comment by fribse** [comment]
Hmm, I guess the path is wrong. 
Because I just found this:
Logger: music_assistant.players.stream
Source: runner.py:119
First occurred: 17.32.41 (1 occurrences)
Last logged: 17.32.41

Stream error on url://track/https://4bxxx7.ui.nabu.casa/media/local/nasfiles/automations/Store_Door_Chime.mp3
???
So that's not the way to id the media on the local drive, if it goes through the nabu casa I guess?
How can I select the audio file through music assistant?

**Comment by OzGav** [comment]
This is what you should have I believe (it works for me)
![image](https://user-images.githubusercontent.com/19848947/186844873-be288032-db11-4533-bab5-5cf70a301409.png)

**Comment by fribse** [comment]
@OzGav Hmm, I know its strange question, have you set up certificates on your local HA? I know that causes problems for the google homes to access locally (at least it says so in the docs).

**Comment by fribse** [comment]
I just tried disabling the SSL, and now I see this error:
Denne fejl stammer fra en brugerdefineret integration.

```
Logger: homeassistant.helpers.script.websocket_api_script
Source: custom_components/mass/media_player.py:429
Integration: Music Assistant (documentation, issues)
First occurred: 12.39.46 (1 occurrences)
Last logged: 12.39.46

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: Invalid uri: http://homeassistant.fribert.dk:8123/local/nasfiles/automations/store_door_chime.mp3?authSig=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiI2ZDIxMTVmZWJiYmU0MmYxYTgxNzI1M2M5YmJkNDkwNSIsInBhdGgiOiIvbG9jYWwvbmFzZmlsZXMvYXV0b21hdGlvbnMvc3RvcmVfZG9vcl9jaGltZS5tcDMiLCJwYXJhbXMiOnt9LCJpYXQiOjE2NjE1MTAzODUsImV4cCI6MTY2MTU5Njc4NX0.YMf95iHYvXKhYav6GJknjycazCWK59SM-O_6cZissYI
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/music_assistant/helpers/tags.py", line 232, in parse_tags
    raise InvalidDataError(error["string"])
music_assistant.models.errors.InvalidDataError: Server returned 404 Not Found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/player_queue.py", line 217, in play_media
    media_item = await self.mass.music.get_item_by_uri(item)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/music.py", line 231, in get_item_by_uri
    return await self.get_item(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/music.py", line 252, in get_item
    return await self.get_provider(ProviderType.URL).parse_item(item_id)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/url/url.py", line 91, in parse_item
    item_id, url, media_info = await self._get_media_info(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/url/url.py", line 152, in _get_media_info
    media_info = await parse_tags(url)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/helpers/tags.py", line 235, in parse_tags
    raise InvalidDataError(
music_assistant.models.errors.InvalidDataError: Unable to retrieve info for http://homeassistant.fribert.dk:8123/local/nasfiles/automations/store_door_chime.mp3?authSig=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiI2ZDIxMTVmZWJiYmU0MmYxYTgxNzI1M2M5YmJkNDkwNSIsInBhdGgiOiIvbG9jYWwvbmFzZmlsZXMvYXV0b21hdGlvbnMvc3RvcmVfZG9vcl9jaGltZS5tcDMiLCJwYXJhbXMiOnt9LCJpYXQiOjE2NjE1MTAzODUsImV4cCI6MTY2MTU5Njc4NX0.YMf95iHYvXKhYav6GJknjycazCWK59SM-O_6cZissYI: Server returned 404 Not Found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 447, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 680, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1713, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1750, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 676, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 930, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 713, in _handle_entity_call
    await result
  File "/config/custom_components/mass/media_player.py", line 429, in async_play_media
    await self.player.active_queue.play_media(media_id, queue_opt)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/player_queue.py", line 220, in play_media
    raise MediaNotFoundError(f"Invalid uri: {item}") from err
music_assistant.models.errors.MediaNotFoundError: Invalid uri: http://homeassistant.fribert.dk:8123/local/nasfiles/automations/store_door_chime.mp3?authSig=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiI2ZDIxMTVmZWJiYmU0MmYxYTgxNzI1M2M5YmJkNDkwNSIsInBhdGgiOiIvbG9jYWwvbmFzZmlsZXMvYXV0b21hdGlvbnMvc3RvcmVfZG9vcl9jaGltZS5tcDMiLCJwYXJhbXMiOnt9LCJpYXQiOjE2NjE1MTAzODUsImV4cCI6MTY2MTU5Njc4NX0.YMf95iHYvXKhYav6GJknjycazCWK59SM-O_6cZissYI

```

**Comment by OzGav** [comment]
No I haven’t set up SSL on my HA. 

When you say you can play music but not this MP3 are they the same thing. That is, do you have a music track and this chime in exactly the same location? 

Certainly the errors you have posted indicate an issue with the URI being malformed. I would enable SSL again and go back and look at what you have in the content ID of your service call because it is nothing like what I have?

P.S. you might want to hide your home domain name in your posts.

**Comment by fribse** [comment]
Yeah, I know, but the hostname is not valid outside, but yeah, I went back and removed it.
Yes, the location is the same filestore, it's a NFS mapped drive under the /media folder on HA.

The path:
![billede](https://user-images.githubusercontent.com/13660621/186940494-179fed80-6afd-4279-b73d-6f987ffa785f.png)
![billede](https://user-images.githubusercontent.com/13660621/186940534-48bf22b2-1fbe-40d8-8f75-f6b3131c7518.png)
another folder with music:
![billede](https://user-images.githubusercontent.com/13660621/186940595-091c6bc4-761d-46d3-b32c-39abba9e991c.png)
The folder with the chimes
![billede](https://user-images.githubusercontent.com/13660621/186940814-574a7d8a-728b-46bc-80fc-c6d6a1c8bb5a.png)
As you can see below, this is the 'filesystem' provider it's located in.
![billede](https://user-images.githubusercontent.com/13660621/186941010-a0cc22d1-19bc-4435-9989-a74d7b80783e.png)

**Comment by OzGav** [comment]
So can you confirm that once you have fixed the content ID that both your music and the chime play locally?

**Comment by fribse** [comment]
No, sorry, the point was that EVEN if I reference it through the MASS, it doesn't play the chime on my Google Home speakers when I do that from within the MASS overview.

**Comment by OzGav** [comment]
OK check the logs for errors and review this https://github.com/music-assistant/hass-music-assistant/discussions/622

**Comment by marcelveldt** [comment]
Actually I think it might just be the duration that is causing the issue. I'm currently in the middle of the refactor for the streaming engine for the grouping/syncing support but I will test this scenario and fix it on the way. Temp fix is some silence padding for these short clips so they're at least 2 seconds.

**Comment by OzGav** [comment]
Just listening to some music now and I think the tracks actually start 1-2 secs into the track…?

**Comment by OzGav** [comment]
I tried playing a countdown mp3 using MA2 and heard the first number fine so I think this is fixed. I will close in the next couple of days unless I hear to the contrary
