### ISSUE TITLE
Media Player not selectable

### ISSUE THREAD

**Issue by FrankSchoene** [music-assistant/hass-music-assistant#886]
### What version of Music Assistant has the issue?

2022.8.4

### The problem

I do see all my media player in the configuration of this integration. When I try to select one of them in MA I just get grey overlay without any media player. I can choose all of them in Spotify, but I don*t think this is idea of MA.
![Bildschirmfoto vom 2022-08-30 16-11-41](https://user-images.githubusercontent.com/83726061/187459851-5729ff6d-4704-42fa-b735-08bd437194bc.png)

### How to reproduce

?

### Relevant log output

No

### Additional information

No

### What version of Home Assistant Core are your running

2022.8.x latest stable

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by gloaysa** [comment]
Same happening to me but only on Safari desktop browser, if I open it on Chrome all is well.

**Comment by FrankSchoene** [comment]
I use Chrome. 

Am 30. August 2022 17:02:37 MESZ schrieb Guillermo Loaysa ***@***.***>:
>Same happening to me but only on Safari desktop browser, if I open it on Chrome all is well.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/music-assistant/hass-music-assistant/issues/886#issuecomment-1231793002
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by OzGav** [comment]
Have you looked at the troubleshooting FAQ specifically this section **I have updated but MA looks like the old version or isn’t working**

**Comment by FrankSchoene** [comment]
Yes. I tried with Chrome and double checked with firefox. Same result. Players not shown.

**Comment by marcelveldt** [comment]
Did you add any "browser mod" players to MA ?

**Comment by FrankSchoene** [comment]
All are Chromecasts + 2 Kodi on RPIs

**Comment by marcelveldt** [comment]
Can you please check if any errors are listed in the javascript console ?
Chrome browser --> F12 for developer tools --> console --> check for errors there

Also make 100% sure that the players are added in the Music Assistant config. Maybe even try with just one to be safe.
For example temporary remove the Kodi's to rule out an issue with those?

**Comment by FrankSchoene** [comment]
I removed all but one and I can confirm it works. 

I will add the others one by one and check which one is causing trouble.

If you leave this issue open for a day or two I`ll give you a feedback on that.

For now, thanks a lot.

**Comment by marcelveldt** [comment]
OK great, would be interesting to know which one caused trouble so we can fix it perhaps.

**Comment by FrankSchoene** [comment]
The problem is with Kodi. Everything else seems to work. 

I did not check every single player but they are in the list. As soon as I add a Kodi MA disappears in the menu.

Since I use them rarely it is not urgent for me.

**Comment by OzGav** [comment]
I have a Kodi player and apart from taking a while to start playing it seems to work ok when it does…

**Comment by FrankSchoene** [comment]
Can't confirm. MA is not even showing up in the menu when Kodi is configured

**Comment by OzGav** [comment]
I assume you are just adding the Kodi integration through SETTINGS>>DEVICES & SERVICES You aren’t doing anything unusual there. The RPis are on the same subnet for example?

**Comment by FrankSchoene** [comment]
Yep. Nothing special. Everything is on the same subnet. VLAN is in plannning but not yet there.

**Comment by OzGav** [comment]
What version of Kodi are they running? It would good to know if any of your Kodi devices work. I am listening to MA on Kodi v18.9 and it is working ok…

**Comment by OzGav** [comment]
Any updates?

**Comment by OzGav** [comment]
We will close this issue soon unless you would like more assistance
