### ISSUE TITLE
Group Media Players

### ISSUE THREAD

**Issue by bluenazgul** [music-assistant/hass-music-assistant#887]
### What version of Music Assistant has the issue?

2023.8

### The problem

Would be great if it is possible to create a Group for Media Players, so it would be possible to get Multiroom Audio.

I run two IKEA Symfonisk and one Raspiaudio ESP Muse Luxe in three rooms, with all three in one Group (to akt as a Single Player) it would be possible to play the Same Music all over the house. 

### How to reproduce

Select players

### What version of Home Assistant Core are your running

2023.8

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Hi. This is a feature request so should be in discussions. There is already a thread about this. https://github.com/music-assistant/hass-music-assistant/discussions/385 There you will see it is already possible to do this. Also see the second entry in this FAQ https://github.com/music-assistant/hass-music-assistant/discussions/710
