### ISSUE TITLE
Renaming Music Assistant devices does not change their name in Music Assistant

### ISSUE THREAD

**Issue by veitw** [music-assistant/hass-music-assistant#891]
### What version of Music Assistant has the issue?

2022.8.4

### The problem

When renaming a Music Assistant player device, its name is not being updated within Music Assistant.

### Example

One of my players is an Onkyo AVR, derived from a Chromecast media_player entity, which I renamed to "Wohnzimmer AVR", as is is an AVR residing in my living room:
![image](https://user-images.githubusercontent.com/16285895/188286983-b4260ce3-1832-4f4f-ab6a-930fd0cfc57c.png)

First I tried to reconfigure Music Assistant after renaming the origin Chromecast device, but that made no change.

Then I renamed the Music Assistant device:
![image](https://user-images.githubusercontent.com/16285895/188287107-a1aa2489-cfa0-482b-9de4-11cc40d1db88.png)

However Music Assistant still shows it as "Onkyo TX-NR555" instead of "Wohnzimmer AVR":
![image](https://user-images.githubusercontent.com/16285895/188286991-c7ac8c7f-0e4e-40cc-9def-e1baf27c937f.png)

Restarting HA and clearing the browser cache had no effect either.

### How to reproduce

Rename a Music Assistant device.

### What version of Home Assistant Core are your running

2022.8.7

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Linux

**Comment by veitw** [comment]
I also tried reconfiguring Music Assistant and removing the device, then reconfiguring again and re-adding the device.

**Comment by erkr** [comment]
Yes I can reproduce this. It seems that the name in MA is derived from the entity_id, not the friendly name.

**Comment by rcjkierkels** [comment]
Is there any way how to get the new name recognised by Music Assistant? I also tried renaming and re-adding Mass.

**Comment by GiODi20** [comment]
I only experience this when using a MPD device

**Comment by erkr** [comment]
Let's revisit this issue once MA2.0 is released

**Comment by OzGav** [comment]
Is this still an issue?

**Comment by veitw** [comment]
HA integration isn't ready yet, is it?

**Comment by OzGav** [comment]
Ah no. But I read your problem which was “ When renaming a Music Assistant player device, its name is not being updated within Music Assistant.” and perhaps you meant not being renamed in Home Assistant?

**Comment by veitw** [comment]
What I wrote and had shown in screenshots is correct, but I think the term "music assistant device" might be misleading:

What I meant is the media_player.mass_* entity in HA that is derived from a media_player.* entity when added to the music assistant integration.
Changing the friendly name of a media_player.mass_* entity or the original entity does not change the player's name in MA 1.

**Comment by OzGav** [comment]
Ok. The HA integration is being worked on now so we can check this again in a week or so

**Comment by veitw** [comment]
Great, thanks :)

**Comment by erkr** [comment]
The setup is really different for players that are supported in MA2. In the configuration you can choose your own name. So once the new integration supports players in HA as well, I guess that name will be independent from the name in HA.

**Comment by OzGav** [comment]
@erkr I think you are right. I'm inclined to close this?
