### ISSUE TITLE
starting queue on the 'wrong' speaker of a SONOS speaker group gives unexpected behaviour

### ISSUE THREAD

**Issue by DutchJaFO** [music-assistant/hass-music-assistant#892]
### What version of Music Assistant has the issue?

2022.8.4

### The problem

= 4 sets of Sonos speakers (A,B,C and D)
= grouped in Sonos app as one with 'A' as parent/master 

Execute mass_queue command on mass_B results in music starting (as expected)
However MA itself only shows the grouped queue of mass_A

### How to reproduce

= ungroup the Sonos speakers in the sonos app
= (in MA) select speaker 'B'
= group Sonos speakers in the sonos app with speaker 'A' as parent (select the speaker 'A' in the app and then 'group all' appears to be the way to do this)

Notice that in MA the displayed speaker name is 'B', but it does appear to understand that the group has 'A' as parent.
(I believe this is why the 'empty' queue is visible ... )

= Use developer tools or a script targetting 'mass_B'  in the Sonos group :
> service: mass.queue_command
> data:
>   command: play_media
>   uri: https://open.spotify.com/playlist/0qxXwSOgfNzBYJQqMhwn4n
>   enqueue_mode: play
> target:
>   entity_id: media_player.mass_B
> 
> 

Expected result : 
Music plays and queue is visible

Actual result : 
Music plays and the queue is 'empty'. The player is indicating that something is playing and you can use the 'stop' button to pause the queue.

### Additional information

I suspect that because I can't manually switch to the correct 'MA queue' this (visual?) problem occurs.

### What version of Home Assistant Core are your running

2022.8.7

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by marcelveldt** [comment]
I've completely refactored this part of the code, especially with regards to grouped speakers. So I have high hopes these kind of issues belong to the past in the next MA version :-)

I'm still working on some loose ends and then I hope to finally launch a beta version later this week.

**Comment by OzGav** [comment]
Please confirm if this is still an issue with MA V2.0.0b7

**Comment by OzGav** [comment]
Ok please close this once you are happy

**Comment by OzGav** [comment]
@DutchJaFO just checking if this can now be closed?

**Comment by OzGav** [comment]
We will close this soon due to no response
