### ISSUE TITLE
Logbook error about version

### ISSUE THREAD

**Issue by BebeMischa** [music-assistant/hass-music-assistant#900]
### What version of Music Assistant has the issue?

2022.8.4

### The problem

After HA update to 2022.9.0 got this error in the logbook

Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.mass
Source: custom_components/mass/__init__.py:122
Integration: Music Assistant (documentation, issues)
First occurred: 12:34:00 (1 occurrences)
Last logged: 12:34:00

This version of Music Assistant is compatible with Home Assistant version 2022.8, and you are running 2022.9.0. You may run into compatibility issues. Please check if there's a newer (beta) version available of Music Assistant.

### How to reproduce

Install HA latest version 2022.9.0 and latest version of MA 2022.8.4
Check HA logbook

### Additional information

Please update version compatibility.

### What version of Home Assistant Core are your running

2022.9.0

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
This is no actual problem. It will be fixed when the next version of MA is released. Please ignore it.
