### ISSUE TITLE
Getting a warning on HA logs that mass may not be compatible with the latest HA core version

### ISSUE THREAD

**Issue by jsBlackBelt** [music-assistant/hass-music-assistant#901]
### What version of Music Assistant has the issue?

2022.8.4

### The problem

Getting log warnings in HA logs:
2022-09-09 14:37:00.106 WARNING (MainThread) [custom_components.mass] This version of Music Assistant is compatible with Home Assistant version 2022.8, and you are running 2022.9.1. You may run into compatibility issues. Please check if there's a newer (beta) version available of Music Assistant.

### How to reproduce

Upgrade HA to 2022.9.x

### What version of Home Assistant Core are your running

2022.9.1

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by erkr** [comment]
Hi, thanks for reporting. This is a known, and luckily just a  harmless warning. MA works fine with the new core 2022.9.x

**Comment by DutchJaFO** [comment]
ditto here
No issues with MA other than those I was aware of already.

This warning is like the HA warning about MA :

"2022-09-09 22:51:45.293 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration mass which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant"

I kind of wished these were at a different severity setting, but that is a HA design choice.

**Comment by erkr** [comment]
Yes that second logging is from HA and always there for all custom integrations. 
The logging mentioned by @jsBlackBelt is from MA itself. Both are harmless in this case.

The reasons for these loggings is that custom integrations are not released as part of core. So library updates in core can break them. This didn't happen for 2022.9.x, but can't be predicted in advance. That is why MA explicitly warns that it was released against core 2022.8

**Comment by DutchJaFO** [comment]
yep I do like how it mentions the version it is tested against so you know if you need to upgrade.
I hope one day MA will become part of HA itself 👍

**Comment by Clusters** [comment]
Will PR #908 fix this?

**Comment by OzGav** [comment]
Maybe. It will get fixed in time. There is a significant update underway.

**Comment by OzGav** [comment]
You can now resolve this by updating to HA 2022.11.x This issue will be closed soon.
