### ISSUE TITLE
Cannot add Google TV device  in MA configuration

### ISSUE THREAD

**Issue by wmwnd** [music-assistant/hass-music-assistant#910]
### What version of Music Assistant has the issue?

2022.8.4

### The problem

I do have multiple chromecast devices, but my new Google TV does not show up whenever I want to add it to MA

### How to reproduce

MA - Configure
Configure which Home Assistant media players you would like to use with Music Assistant.
Player entities:
all chromecast entities shown , except the Google TV  (device is known in HA and up and running)

### What version of Home Assistant Core are your running

2022.9.2

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Linux

**Comment by erkr** [comment]
Hi @wmwnd 

Google TV is supposed to work as is has chromecast support.  Please have a look at:
https://github.com/music-assistant/hass-music-assistant/discussions/622
Can you please report back if your player works via de media browser (as described in the first option).
Best Eric

**Comment by wmwnd** [comment]
tested based on #622 , the player can play files direct from media , see sc
![2022-09-15_13h27_08](https://user-images.githubusercontent.com/75251605/190392675-846310a1-1547-4196-80d8-340dca965003.png)

**Comment by wmwnd** [comment]
I added the device ID **media_player.chromecast** manually into the drop-down field , then an error was displayed :

User input malformed: value must not be one of ['media_player.chromecast', 'media_player.desktop_qm356q0', 'media_player.harmony_remote', 'media_player.icybox', 'media_player.mass_0_woonkamer', 'media_player.mass_chromecast_v1', 'media_player.mass_lenovo_cd_4n341y7001', 'media_player.mediacenter_772a0a84', 'media_player.spotify_wmwnd'] @ data['player_entities'][1]

**Comment by OzGav** [comment]
This indicates the player is not supported for some reason.

**Comment by erkr** [comment]
Hi
Manually entering the player in the list won't work (only the recognised players will be accepted). For some reason the Google tv player is not recognised as a compatible player. 
In order to allow @marcelveldt to look into that, it would like help if you share the player entity properties. You can easily look then up in de development tools. 
Should look similar to this:
``` 
device_class: speaker
friendly_name: Woonkamer
supported_features: 456639
is_volume_muted: false
media_content_type: music
media_position: 0
media_position_updated_at: '2022-09-15T13:48:01.075405+00:00'
app_id: media_player.audio57woonkmr
app_name: Audio57WoonKmr
shuffle: false
repeat: false
active_child: media_player.mass_audio57woonkmr
```

**Comment by OzGav** [comment]
If I understand the supported features correctly the TV is reporting it doesn't support volume_set or volume_mute and they might be required?

**Comment by erkr** [comment]
Yes, thanks for reporting the properties back. That is what van help.
One open question still: is this Google TV player provided via the Google Cast integration, or via the Android TV integration?!

**Comment by wmwnd** [comment]
Hi, I used google cast integration

**Comment by marcelveldt** [comment]
> If I understand the supported features correctly the TV is reporting it doesn't support volume_set or volume_mute and they might be required?

I think this is the issue... It is supposed to support volume commands. I do not own a Google TV device so not possible to test. This is not a simple fix but I can make sure to add it in the refactor stuff I'm working on where I actually touched some parts that are related to this.

**Comment by wmwnd** [comment]
I will wait and see whenever this fits your schedule. Please close this ticket, no rush with it.
