### ISSUE TITLE
Low res image using Youtube Music Integration

### ISSUE THREAD

**Issue by howesey2k** [music-assistant/hass-music-assistant#912]
### What version of Music Assistant has the issue?

2022.8.4

### The problem

First of all, thank you so much for allowing us to be able to use Youtube Music with Music Assistant.
Using the notification for android TV integration, I am able to display the Media Title as well as the Media Image.
If I use the google home device with chromecasting, it shows the image full size.
However, if I use the Music Assistant integration and display the "mass" google home Media Image, it results in a smaller image. I think this may be where the image is pulled from is different to the chromecasting version.

Many thanks in advance.

### How to reproduce

service: notify.living_room_tv
data:
  title: "{{ state_attr('media_player.mass_living_room_group', 'media_title') }}"
  message: "{{ state_attr('media_player.mass_living_room_group', 'media_artist') }}"
  data:
    duration: 5
    position: bottom-left
    fontsize: small
    transparency: 75%
    color: teal
    interrupt: 0
    image:
      url: >-
        {{ state_attr('media_player.mass_living_room_group', 'entity_picture')
        }}

### What version of Home Assistant Core are your running

2022.9.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by erkr** [comment]
I guess the images provided by the mass player are indeed low res, scaled voor use in the MA UI. This notification use case was probably not considered. But I'm guessing 😉
I will label it as an enhancement.

**Comment by OzGav** [comment]
@MarvinSchenkel based on your comment on discord can we close this?

**Comment by MarvinSchenkel** [comment]
Yes. If this issue still persists after a clean install on beta 30 or higher, please reopen a new issue.
