### ISSUE TITLE
Error on Syncing NVR Files?

### ISSUE THREAD

**Issue by LordNex** [music-assistant/hass-music-assistant#915]
### What version of Music Assistant has the issue?

Latest

### The problem

Found an error going through my logs and thought you should see it. 

### How to reproduce

This is a mapped drive to the location I store my NVR data. So I’m guessing it’s scanning that. I use Frigate to encode and record my camera footage in real time for facial recognition so there is always going to be a file in use. 

### Relevant log output

Logger: music_assistant.music.file
Source: /usr/local/lib/python3.10/site-packages/music_assistant/music_providers/filesystem/filesystem.py:268 
First occurred: 2:28:38 AM (96612 occurrences) 
Last logged: 11:12:05 AM

Error processing /media/nvr/var/mnt/footage/recordings/2022-09/08/18/hallcam/14.13.mp4 - coroutine raised StopIteration
Error processing /media/nvr/var/mnt/footage/recordings/2022-09/08/18/hallcam/04.32.mp4 - coroutine raised StopIteration
Error processing /media/nvr/var/mnt/footage/recordings/2022-09/08/18/hallcam/05.21.mp4 - coroutine raised StopIteration
Error processing /media/nvr/var/mnt/footage/recordings/2022-09/08/18/hallcam/59.42.mp4 - coroutine raised StopIteration
Error processing /media/nvr/var/mnt/footage/recordings/2022-09/08/18/hallcam/53.41.mp4 - coroutine raised StopIteration
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/music_assistant/helpers/tags.py", line 233, in parse_tags
    return AudioTags.parse(data)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/helpers/tags.py", line 173, in parse
    audio_stream = next(x for x in raw["streams"] if x["codec_type"] == "audio")
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/filesystem/filesystem.py", line 253, in sync_library
    track = await self._parse_track(entry.path)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/filesystem/filesystem.py", line 490, in _parse_track
    tags = await parse_tags(track_path)
RuntimeError: coroutine raised StopIteration

### Additional information

Running Home Assistant on a Dell PowerEdge R620 with 40 cores running VMWare ESXI 7 and the OVA image of Home Assistant. 

### What version of Home Assistant Core are your running

2022.08.6

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Alternative

**Comment by LordNex** [comment]
Just seen this so that might be my issue. 

```

This error originated from a custom integration.

Logger: custom_components.mass
Source: custom_components/mass/__init__.py:122 
Integration: Music Assistant (documentation, issues) 
First occurred: 2:24:15 AM (1 occurrences) 
Last logged: 2:24:15 AM

This version of Music Assistant is compatible with Home Assistant version 2022.8, and you are running 2022.9.4. You may run into compatibility issues. Please check if there's a newer (beta) version available of Music Assistant.
```

**Comment by OzGav** [comment]
On your second point that is not a problem https://github.com/music-assistant/hass-music-assistant/issues/901

On your first point if those files are open or locked by another application then probably is the reason for the failure. One solution is for you to move these to a different path as they are not part of your music library

**Comment by OzGav** [comment]
Just checking this has been resolved by you removing locked files from the scan path?
.

**Comment by LordNex** [comment]
Yea go ahead and close. Once I specified the path not to include the NVR files, the error went away. Thanks.


On Oct 1, 2022, at 5:02 PM, OzGav ***@***.***> wrote:

﻿

Just checking this has been resolved by you removing locked files from the scan path?
.
