### ISSUE TITLE
youtube music 401 - but works.

### ISSUE THREAD

**Issue by Symbiot78** [music-assistant/hass-music-assistant#918]
### What version of Music Assistant has the issue?

2022.8.4

### The problem

HA logs show 401 unauthorized.. but it works.. very strange..

### How to reproduce

not sure. configure mass for ytube music and see in logs.

### Relevant log output

Logger: music_assistant
Source: /usr/local/lib/python3.10/site-packages/music_assistant/mass.py:232
First occurred: 17:39:11 (2 occurrences)
Last logged: 17:40:11

Job [Library sync for provider Youtube Music] failed with error Server returned HTTP 401: Unauthorized. Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project..
Job [Add ytmusic://artist/UChgxarBUCnPJV871-46bJ2g to database] failed with error Server returned HTTP 401: Unauthorized. Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project..
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/music_provider.py", line 402, in sync_library
    async for prov_item in self._get_library_gen(media_type)():
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/ytmusic/ytmusic.py", line 133, in get_library_artists
    artists_obj = await get_library_artists(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/ytmusic/helpers.py", line 105, in get_library_artists
    return await loop.run_in_executor(None, _get_library_artists)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/ytmusic/helpers.py", line 95, in _get_library_artists
    artists = ytm.get_library_subscriptions(limit=9999)
  File "/usr/local/lib/python3.10/site-packages/ytmusicapi/mixins/library.py", line 173, in get_library_subscriptions
    response = self._send_request(endpoint, body)
  File "/usr/local/lib/python3.10/site-packages/ytmusicapi/ytmusic.py", line 144, in _send_request
    raise Exception(message + error)
Exception: Server returned HTTP 401: Unauthorized.
Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.

### What version of Home Assistant Core are your running

2022.9.5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Linux

**Comment by erkr** [comment]
Hi @Symbiot78 
Most likely you YT cookie has expired. Just enter a new one in the configuration.
It probably seems to work, as tracks are playing from other providers
Best Eric

**Comment by erkr** [comment]
Please confirm if renewing the cookie fixed the issue.

**Comment by erkr** [comment]
I will close the issue, 
If it is still a problem, just let us know and we will reopen.
Best Eric

**Comment by janrivo** [comment]
> 

Where can I update the cookie token, I can't find it anywhere?

**Comment by OzGav** [comment]
Please see the FAQ which will direct you to the YouTube discussion where you will find how to obtain the cookie.

**Comment by janrivo** [comment]
I know how to obtain it. I was wondering how to update a cookie that is expired, do I need to delete and re-add the integration?

**Comment by OzGav** [comment]
No just go to SETTINGS>>INTEGRATIONS>>MUSIC ASSISTANT>>CONFIGURE and add your new cookie

**Comment by janrivo** [comment]
Thanks, I was here several times, but only saw the configuration of media players. I pressed next now and saw that there was more there, thanks for the quick replies!

**Comment by janrivo** [comment]
Thanks, I was here several times, but only saw the configuration of media players. I pressed next now and saw that there was more there, thanks for the quick replies!
