### ISSUE TITLE
Music Assistant use network Adapter IP instead of Local IP

### ISSUE THREAD

**Issue by Xhelliom** [music-assistant/hass-music-assistant#919]
### What version of Music Assistant has the issue?

2022.8.4

### The problem

Mass doesn't stream music to devices

### How to reproduce
maybe use docker without network as HOST network

### Additional information
No response

### What version of Home Assistant Core are your running
2022.9.5

### What type of installation are you running?
Home Assistant docker

### On what type of hardware are you running?
Linux / kubernetes

> Music Assistant launches its own -internal only- webserver to serve the audio stream to players on the local network on TCP port 8095. The ip-address that is communicated to players is derived from whatever you fill in at the "internal URL" field of the HA config. So it only takes the IP-address from there (and even resolves dns if needed) and ignores everything else.
> 

Hi, i have the feeling that it doesn't use the "internal URL" field but the network adapter ip : 
![image](https://user-images.githubusercontent.com/18086297/189720050-7ac40254-87ac-4a0f-976c-c157b69a92a2.png)

in my case, this happens : 
```
Logger: homeassistant.components.cast.media_player
Source: components/cast/media_player.py:403
Integration: Google Cast (documentation, issues)
First occurred: 11 septembre 2022 à 21:08:33 (14 occurrences)
Last logged: 11 septembre 2022 à 21:29:19

Failed to cast media http://10.42.5.42:8095/control/media_player.google_home_sejour/next.mp3. Please make sure the URL is: Reachable from the cast device and either a publicly resolvable hostname or an IP address
Failed to cast media http://10.42.5.42:8095/control/media_player.google_home_cuisine/next.mp3. Please make sure the URL is: Reachable from the cast device and either a publicly resolvable hostname or an IP address

```

I have my home-assistant into a kubernetes cluster, so the pod IP is different from the internal URL that i use on my LAN

_Originally posted by @Xhelliom in https://github.com/music-assistant/hass-music-assistant/issues/898#issuecomment-1244082901_

I did make it work with the help of this issue :

https://github.com/music-assistant/hass-music-assistant/issues/802

i've put my internal IP as environnement variable and it works.

If you think it's a specific issue to my hardware, feel free to close this issue.

**Comment by erkr** [comment]
Thanks for creating a separate issue. 
Great you found a solution. I will indeed close the issue, but nice to have the solution captured here.
