### ISSUE TITLE
MA does not install

### ISSUE THREAD

**Issue by Sell24** [music-assistant/hass-music-assistant#928]
### What version of Music Assistant has the issue?

2022.8.4

### The problem

I have installed the latest version of MA, but it doesn't appear anywhere in HA.  I see it under HACS as an integration but it doesn't appear in the sidebar nor does it appear in the Settings > Integration (not 100% sure it should appear here).  

I have refreshed my browser. I have rebooted my HA instance but nothing. I even checked to see if it was hidden in the sidebar. I even rebooted my machine. I uninstalled and reinstalled. But it just doesn't appear. It's like it never installed at all. 

I feel foolish but what am I missing here?

### How to reproduce

Just did a standard HACS install. Just to note other HACS integrations work.

### Relevant log output

I have searched through the logs and don't see any errors related to MA

### Additional information

Just to clarify my installation:

- Windows 10 Home
- Oracle VM 
- Supervisor: 2022.09.1
- HA OS: 9.0
- Core: 2022.9.7

### What version of Home Assistant Core are your running

2022.9.7

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Windows

**Comment by OzGav** [comment]
Noting that we can only provide limited support for non standard installs…when you say you can see it in HACS is it actually installing?

**Comment by Sell24** [comment]
I can see it under HACS > Integrations. I can also see in in the json.txt file generated by HACS diagnostics.

![image](https://user-images.githubusercontent.com/16975650/193411625-fb6556b2-4070-48e2-88ea-de1f019dbb88.png)




Under Settings > System > Logs > Home Assistant Core (Full Log) the entry for install exists:

_2022-10-01 03:04:37.671 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration mass which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant_

There are no other entries signifying failure of the integration.


Just to clarify, I have installed HA as a VirtualBox (vdi) installation under Windows as per the official HA documentation (https://www.home-assistant.io/installation/windows) . Just so I know, this is not considered a standard install?

**Comment by OzGav** [comment]
So it does appear to be installed but is not properly loading by the looks of it.

In terms of what can be supported at this early stage of the MA development cycle yes your install is not standard. There is only so much we can do to help when we helpers are running the standard HAOS. 

Having said that the usual issues are related to the network which you don’t appear to have. I do note on the page you have linked that it says “ The above-listed dependencies might differ or missing, depending on your system or personal use of Home Assistant.” so you might have a dependency missing. I will tag in @marcelveldt who might have some ideas.

**Comment by Sell24** [comment]
Ok I am an idiot. I completely misread the install instructions and confused the configure part with installing it under HACS not under HA as it should be. Sorry about that, this is only the second integration I have installed.

Just as a note on the instructions. This step: "If Home Assistant does not show, refresh your brower (cache)." That should be Music Assistant no?

Thanks for the help and I apologize for the misunderstanding on my part.

**Comment by OzGav** [comment]
No problems. The instructions are correct, having a cached version of a page can cause issues so that is why it is recommended to clear it when experiencing front end problems.
