### ISSUE TITLE
Music Assistant could not be installed with Home Assistant 2022.10

### ISSUE THREAD

**Issue by BorgTen** [music-assistant/hass-music-assistant#935]
### What version of Music Assistant has the issue?

2022.8.4

### The problem

Installation via HACS fails. Configuration flow could not be started because of an „unknown error“.

### How to reproduce

1. Add Music Assistant via HACS.
2. Restart Home Assistant
3. Try to add Music Assistant integration to Home Assistant.

### Relevant log output

Logger: frontend.js.latest.202210050
Source: components/system_log/__init__.py:227
First occurred: 00:43:15 (2 occurrences)
Last logged: 00:53:24
:0:0 ResizeObserver loop completed with undelivered notifications.

### What version of Home Assistant Core are your running

2022.10

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Raspberry Pi

**Comment by marcelveldt** [comment]
Is this a fresh installation ?
Because multiple existing users are running HA 2022.10 just fine

**Comment by BorgTen** [comment]
I am using Home Assistant for a few days now. This was the first time trying to install Music Assistant.

**Comment by novisys** [comment]
it's normal if considerring this point:
https://github.com/music-assistant/hass-music-assistant/blob/main/custom_components/mass/__init__.py
>>> **MAX_HA_VERSION=222022.8.999**

**Comment by OzGav** [comment]
No this just results in a warning in the log

**Comment by marcelveldt** [comment]
Correct, that will just print a warning in the log. MA is perfectly compatible with HA 2022.9 and 2022.10.
Also I'm not sure why a frontend error is thrown. Maybe you need to force refresh your browser as you seem to have an incompatible frontend version for the brand new HA 2022.10 version ?

**Comment by erkr** [comment]
I reinstalled MA on Core2022.10.0 worthy issues. So it is not a general issue

**Comment by papabak** [comment]
I downloaded Music Assistant. When installing this integration I repeatedly get this:

ERROR

Config flow could not be loaded: Unknown error

HA is on the latest version running on a Raspberry Pi

**Comment by erkr** [comment]
Installed manual or via HACS? I recommend via HACS.

**Comment by papabak** [comment]
I restarted another time and then the installation run as expected. Now I have to find where it shows up. Do I have to make a card to show it?

**Comment by OzGav** [comment]
Please see the installation instructions https://github.com/music-assistant/hass-music-assistant#installation--initial-configuration 

You need to add the integration and it will show up in the left hand menu

**Comment by BorgTen** [comment]
> Correct, that will just print a warning in the log. MA is perfectly compatible with HA 2022.9 and 2022.10. Also I'm not sure why a frontend error is thrown. Maybe you need to force refresh your browser as you seem to have an incompatible frontend version for the brand new HA 2022.10 version ?

After clearing the browser cache, I managed to install Music Assistant wit Home Assistant 2022.10.
