### ISSUE TITLE
Cannot add integration.

### ISSUE THREAD

**Issue by phellarv** [music-assistant/hass-music-assistant#943]
### What version of Music Assistant has the issue?

2022.8.4

### The problem

Whenever I try to add the integration it times out:
Error
Config flow could not be loaded: <html><body><h1>504 Gateway Time-out</h1> The server didn't respond in time. </body></html>

### How to reproduce

Download integration from HACS.
Restart HA.
Add integration Music Assistant.

### Relevant log output

No errors in the log, but I got this in the popup box:
Error
Config flow could not be loaded: <html><body><h1>504 Gateway Time-out</h1> The server didn't respond in time. </body></html>

### What version of Home Assistant Core are your running

2022.10.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Looking at a similar issue. Remove MA through HACS. Reboot. Try and install again.

**Comment by phellarv** [comment]
OK. Now it works. Steps I took to get it to work:
1. Remove Music Assistant through HACS.
2. Reboot host.
3. Add Music Assistant through HACS.
4. Reboot host.
5. Add integration.

The difference here seems to be a full reboot of the host versus just restarting Home Assistant.
