### ISSUE TITLE
After updating HA and MASS, unable to play anything

### ISSUE THREAD

**Issue by fernplant** [music-assistant/hass-music-assistant#946]
### What version of Music Assistant has the issue?

2022.8.4

### The problem

Was running HA 2022.7.6 and MASS 2022.7.4 without any issues but after updating to latest HA and MASS, Im unable to play anything. I have only local filesystem music so have tested only that. When I click on a track or click play now, nothing happens. I am able to call TTS and the speakers speak and Im able to adjust volume from within MASS. Using Google cast speakers. I am able to use the built in HA media browser to play the music on the Google speakers, that works fine
Happy to supply more info, just let me know. Thank you

### How to reproduce

.

### What version of Home Assistant Core are your running

 2022.10.4

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Are you playing the TTS to the MASS entities? Have you cleared the browser cache? Are there any errors in the logs?

**Comment by fernplant** [comment]
Browser cache did it, thanks for the suggestion and sorry for not trying that first myself. I deleted just site specific cache and that didnt do it, had to delete everything for some reason and then it worked.
