### ISSUE TITLE
Controling music via dashboard

### ISSUE THREAD

**Issue by NickyMB** [music-assistant/hass-music-assistant#948]
### What version of Music Assistant has the issue?

 2022.8.4

### The problem

When I try to skip song via mushroom media card on dashboard song stops and to play it again I need to open music assistant and do it from that page

### How to reproduce

Have some songs localy aded to music assitant. Try to skip them via card on dashboard

### What version of Home Assistant Core are your running

Home Assistant 2022.10.4

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
Have you tried the stock media player card to see if it is a problem with the Mushroom card vice MA? https://www.home-assistant.io/dashboards/media-control/

**Comment by NickyMB** [comment]
Never mind. I've used wrong entity
