### ISSUE TITLE
Fonts Hosted on External Servers

### ISSUE THREAD

**Issue by rogerquake** [music-assistant/hass-music-assistant#967]
### What version of Music Assistant has the issue?

2022.8.4

### The problem

When accessing Music Assistant from a device that does not have Internet access, the website hangs for a few seconds. I believe I tracked it down to some of the fonts MA uses being hosted on Google Fonts. It eventually loads, but it would be great if the fonts could be hosted locally. See the image below:

![fonts-ma](https://user-images.githubusercontent.com/28624502/198755749-69c470a0-2cdf-449c-9e78-2158f70283fa.png)

### How to reproduce

Block Internet access on the device loading the Music Assistant website through Home Assistant.

### What version of Home Assistant Core are your running

2022.10.5

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Linux

**Comment by erkr** [comment]
Thx @rogerquake

**Comment by marcelveldt** [comment]
this is fixed in v2
