### ISSUE TITLE
Memory leak when analyzing audio

### ISSUE THREAD

**Issue by MeowRay** [music-assistant/hass-music-assistant#969]
### What version of Music Assistant has the issue?

 2022.8.4 

### The problem

Memory leak and 100% disk IO when analyzing audio
The track's music is one 11-hour Chinese-named mp3

![QQ截图20221030141035](https://user-images.githubusercontent.com/29674595/198865317-2a7363f2-3d1a-422e-b5ac-50a3fe40f5a6.jpg)
![QQ截图20221030141004](https://user-images.githubusercontent.com/29674595/198865320-3519189c-0c2d-4a79-94c3-6fe2bf32a9e7.jpg)
![QQ截图20221030131815](https://user-images.githubusercontent.com/29674595/198865324-39be507a-085f-46c9-aabc-e3d99c3cc28a.jpg)
![QQ截图20221030142359](https://user-images.githubusercontent.com/29674595/198865542-39febbf6-7d8f-4e2a-8236-dedd7ff57f24.jpg)

### How to reproduce

Background job is analyzing audio

### What version of Home Assistant Core are your running

2022.10.5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by marcelveldt** [comment]
hmmm, strange as the audio chunks are just fed into ffmpeg so maybe there's a leak there.
I will investigate within a few weeks, when I'm working on that part of the code again.

**Comment by NigelVanHattum** [comment]
I don't have the exact data that @MeowRay is showing, but I do notice some similar issues when syncing large Youtube Music playlist (with songs over 1 hour). 
During the night memory usage on my Pi 4 spikes to 90% out of nowhere and the Pi as a whole becomes unresponsive. Disabled the integration for two weeks and the issues was gone. When I enabled it again, the issues rose again.

**Comment by marcelveldt** [comment]
Ah yes, that is entirely possible if a track is too long/big. This will be fixed in the V2 release of MA so in the meanwhile try to prevent tracks longer than 60 minute :-)

**Comment by OzGav** [comment]
This has been fixed in MA2. For reasons elsewhere explained it won’t be fixed in MA1
