### ISSUE TITLE
Denon AVR-X3000 not playing via MA

### ISSUE THREAD

**Issue by papabak** [music-assistant/hass-music-assistant#975]
### What version of Music Assistant has the issue?

2022.8.4

### The problem

MA installs normal. Spotify shows the proper content. When selecting a song the Denon AVR-X3000 is switched on. The progress bar turns blue showing the song with contenttype Ogg Vorbis, but then everything stops. In the Denon mass player I tried all 4 contenttypes available (wav flac mp3 and alac) without succes. I can play music from my nas on the Denon and also from my Spotify app.
Somehow MA and the Denon do not match … yet. Has anyone been successful using a Ddnon AVR with MA?

### How to reproduce

This behavior is regrettably reproducible 

### What version of Home Assistant Core are your running

2022.10.5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Have a look at the last few comments here https://github.com/music-assistant/hass-music-assistant/discussions/380

**Comment by erkr** [comment]
If I recall correctly, The avr integration doesn't provide a compatible player that supports play media by url.
But using the DLNA integration is reported to work

**Comment by papabak** [comment]
Unfortunately not Eric. I have no idea how to use DLNA with my Denon AVR.
DLNA is loaded as integration, but I do not find a connection to MA.

Op do 3 nov. 2022 om 17:56 schreef Eric ***@***.***>

**Comment by erkr** [comment]
I recall the AVR media players are not offering the play media service, only remote control. You can verify that via the development tool, to check if the service play_media with an url works.
If not, you can check if your DLNA integration adds a player for your denon. If so, check if that one works with the play media service.
If not, it's beyond my knowledge and maybe someone on discord knows how to get a DLNA player. Others have succeeded, so maybe you need to enable something on the Denon.
If that works, but that player is not configurable in MA, it is time to open an issue here. DLNA players should be supported by MA.

**Comment by erkr** [comment]
As far I can judge, this is more a support question, not an issue. So I will close this one and advice to look /ask further on the Q&A's you find in the discussion section

**Comment by papabak** [comment]
Hi Eric,
I got it working by installing an DLNA server for the Denon AVR.
It listens to port 5555. I found that on a Denon AVR forum.

**Comment by erkr** [comment]
Thanks for sharing your solution. 
Best Eric
