### ISSUE TITLE
Unable to Access Music Directory on QNAP Server

### ISSUE THREAD

**Issue by BlueMoon23** [music-assistant/hass-music-assistant#983]
### What version of Music Assistant has the issue?

2022.11.0

### The problem

I have my music stored on my QNAP Server; no matter what I try I can't access this via Music Assistant. When I try to configure MA, I enable the filesystem provider check box, enter the QNAP Directory  (I have also created a share link in QNAP), but all I get is "Directory does not exist or is not accessible". Is access to NAS possible?

### How to reproduce

See above.

### Relevant log output

See above.

### What version of Home Assistant Core are your running

2022.11

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Windows

**Comment by OzGav** [comment]
Please refer to the FAQ - How do I access my local music

**Comment by erkr** [comment]
@BlueMoon23 
Currently MA doesn't support samba shares, only local files. As pointed out by OzGav, you will find instructions in the FAQ section how to mount shares in HA and then use them in MA.
But next major release from MA, expected in December will natively support samba shares. 
Best Eric

**Comment by BlueMoon23** [comment]
Ok, thanks. I'll hold for the December release and progress it then.

**Comment by erkr** [comment]
I will close this issue for now. Best Eric
