### ISSUE TITLE
Cannot see DLNA server (serviio)

### ISSUE THREAD

**Issue by antisane** [music-assistant/hass-music-assistant#986]
### What version of Music Assistant has the issue?

2022.11.0

### The problem

Music Assistant cannot see my DLNA server (serviio) even though Home Assistant can. HA shows the files on the server within the media tab, under the DLNA tab.

### How to reproduce

Attempt to browse files. Can't, there are none to browse (according to MA).

### What version of Home Assistant Core are your running

2022.11.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Windows

**Comment by erkr** [comment]
That is correct. MA only supports DLNA players. DLNA servers as music provider is not supported!
The next major release will support samba shares. 
Best Eric
