### ISSUE TITLE
[feature request] Show metadata on target player

### ISSUE THREAD

**Issue by nagyrobi** [music-assistant/hass-music-assistant#99]
Thank you for this wonderful integration.

I'm the maintainer of the [linkplay](https://github.com/nagyrobi/home-assistant-custom-components-linkplay) media player component.

One thing I notice is that the target media player (the one really playing out the media) doesn't show any metadata (from Spotify). So for example:
- go to lovelace, where you have a (physical) media player entity (eg. `media_player.hang_up2stream`)
- go to media browser selection
- choose Music Assistant
- choose Playlists: you can see all metadata appears at this level, tracks info and coverart etc
- select a playlist, press play
- playback starts on the media player, but no metadata is being shown
- also metadata is missing on the auxiliary `media_player.mass_hang_up2stream`

Usually linkplay devices provide some metadata via UPnP so when such information is available I parse it and import it. From Media Browser local files I just parse for "Artist - Title.ext" and if that matches I also grab cover from Last.FM. For Icecast radio streams, I look for ICY-Meta in the headers of the stream.

Is there a way I could fetch rich metadata from music assistant? Or should I provide a service for you to push metadata in (would be more accurate and less stressful)?

**Comment by marcelveldt** [comment]
Music Assistant works by taking a media_player entity (source player) and creating a Queue audio stream.
That source player only receives a raw PCM audio stream or compressed with FLAC, nothing more.
Sending metadata the ordinary way is not possible because the source player (the one actually playing audio) plays a long stream of audio because all transcoding and other audio plumbing is handled by Music Assistant.


Because of the lack of metadata within Home Assistant itself I've created the optional to "spit out" the media player as a separate media_player (prefixed with mass in the entity_id). On that media player the full metadata should be available. If you're missing something, let me know.

One usecase is however not covered in this approach and that is if the actual player want to display something about what it is playing. That metadata is also lost. I've looked at ICY-Meta but that is normally used for radio streams. Not sure if it will also work for a flac/pcm stream.

Another approach could be that I fire an event on the HA eventbus with the media details, for you to pick up ?
Fetching the metadata yourself is also possible, you can access hass.data["mass"] from your custom component to have access to the full Music Assistant instance:

if mass := hass.data.get("mass"):
    queue = mass.players.get_player_queue("media_player.my_player")

Do note that this may break if I change the internals. Maybe an event is better with a predescribed format.

**Comment by nagyrobi** [comment]
> On that media player the full metadata should be available. If you're missing something, let me know.

It's not visible here at all:
![image](https://user-images.githubusercontent.com/1550668/167466160-0597e318-ff44-4ac3-9f87-736edd01b52d.png)
Top: the real media player entity
Bottom: spit-out media player prefixed with _mass_

> I've looked at ICY-Meta but that is normally used for radio streams. Not sure if it will also work for a flac/pcm stream.

Webradios are actually nothing more than audio streams. Icecast is a reputable server type which standardized the way audio streams can be optimally transported over http, and ICY-Meta is a good way implemented by Icecast to show real time metadata within the data flow. Webradios use this historically and the good part of it that it requires no extra service, textual metadata is embedded in the data flow and hardware players can easily display it too.

Actually TuneIn service is nothing more than just a directory, a collection of Icecast/Shoutcast streams, which in reality are all operated by the radio station owners themselves. So any player supporting TuneIn is in reality able to play Icecast.

Icecast supports FLAC by design and I don't think there's any reason why you couldn't feed it with uncompressed PCM. I don't mean by creating a full-blown icecast server just for this, but I think ICY-Meta can be embedded by various other means regardless of the stream compression algorythm. https://icecast.org/faq/



> Another approach could be that I fire an event on the HA eventbus with the media details, for you to pick up ?

I'd be happy to test this, and add it as extra functionality to my component. For example if the stream URL itself would follow a uniquely recognizable pattern (currently it's `http://ha.ip:8096/media_player.hang_up2stream.flac` as I've noticed, say, if we agree that the `8096/media_player` + something unique to this component substring will allways be there) I could know that the source of metadata information is on the event bus.

But I have zero experience with any sort of event bus programming so I'm all ears...

**Comment by marcelveldt** [comment]
What version of the integration are you running ?

Metadata should be present on the final media player, I'm not sure why it's missing in your case.
Any errors in the log ?


![Schermafbeelding 2022-05-10 om 00 45 53](https://user-images.githubusercontent.com/6389780/167510706-5cdab0cc-745d-4611-9f94-d72fc0ebe1df.png)

**Comment by nagyrobi** [comment]
I'm on 1.0.14. No errors in the log.

**Comment by whighway** [comment]
> One usecase is however not covered in this approach and that is if the actual player want to display something about what it is playing. That metadata is also lost. I've looked at ICY-Meta but that is normally used for radio streams. Not sure if it will also work for a flac/pcm stream.
> 
Hi I also have an end-device that shows metadata (through DLNA renderer) so it would be really great if this option could work, somehow embedding the metadata into the stream

**Comment by nagyrobi** [comment]
> through DLNA renderer

Yeah that's another way to do it (a can of worms though). DLNA doesn't embed it in the stream, but provides a separate [XML](https://github.com/nagyrobi/home-assistant-custom-components-linkplay/blob/7ff9153327296274d4384cb7b31c178634e0a1ca/custom_components/linkplay/media_player.py#L2569) with all the metas via HTTP. Needs thorough testing as the standard is very flexible, manufacturers are too creative about how they implement stuff so might very well work with some devices and may not work with others...

**Comment by marcelveldt** [comment]
I'm going to have a look at embedding ICY metadata into the stream if the player requests that in the header as a first step.
Besides that I'll provide some sort of hook and event to send the now playing info too.

**Comment by nagyrobi** [comment]
Spotify, and just enable TuneIn also. 

Metadata appears when looking through media browser so the component itself has it, it's juts not passed to the player:
![kép](https://user-images.githubusercontent.com/1550668/167594702-e2a88f51-4877-440a-a2cf-d9babdf7d154.png)

**Comment by nagyrobi** [comment]
> I'm going to have a look at embedding ICY metadata into the stream if the player requests that in the header as a first step. Besides that I'll provide some sort of hook and event to send the now playing info too.

I think the event bus approach woul suit better the needs, and could be adopted in the future by other media player integrations too.
