### ISSUE TITLE
media_player.mass.xxxx not updating status when started by automation

### ISSUE THREAD

**Issue by Symbiot78** [music-assistant/hass-music-assistant#999]
### What version of Music Assistant has the issue?

2022.11.0

### The problem

if I start playing a radiostation via an automation - the media_player.mass entity does not update. So according to the entity nothing is playing.
this is messing with my dashboards.
I've attached 2 examples.. 1 is from MA tab the other from the logbook. taken after automation was run.
if I start playing something manually then there is no problem.

So MA knows radio is playing but the entity does not.

to reference the logbook entries time is not 17:42 here.

![image](https://user-images.githubusercontent.com/3314249/203371505-0a89d6be-4402-4da2-9595-1122b2785957.png)

![image](https://user-images.githubusercontent.com/3314249/203371547-0775aa0a-f0c9-441d-9eeb-e53496352551.png)

If I look at media_player.kokken.. so outside of music assistant - that entity has updated properly.

Automation action code:

`service: media_player.play_media
target:
  entity_id: media_player.mass_kokken
data:
  media_content_id: media-source://mass/database://radio/1
  media_content_type: audio/flac
metadata:
  title: BBC Radio
  thumbnail: null
  media_class: music
  children_media_class: null
  navigateIds:
    - {}
    - media_content_type: app
      media_content_id: media-source://mass
    - media_content_type: music
      media_content_id: media-source://mass/radio`

### How to reproduce

use the above code.

### Relevant log output

none

### What version of Home Assistant Core are your running

Home Assistant 2022.11.4

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Alternative

**Comment by Symbiot78** [comment]
I am also swing that if I start playing tracks from YouTube music my dashboard will pick up the first song. Then not show the change when a new track starts

**Comment by OzGav** [comment]
Might be related to this https://github.com/music-assistant/hass-music-assistant/issues/815
Best to wait until the next version and then we will see what remains to be addressed

**Comment by Symbiot78** [comment]
I've commented on #815

**Comment by OzGav** [comment]
@Symbiot78 Please advise if this is still an issue with beta32.

**Comment by OzGav** [comment]
Closing. Can reopen if this is still a problem
